Repository 1024pix/pix, pull requests merged in 2018-04, with the labels that each got.

#15 [#15] Mise à jour des fingerprints SSH (US-1210)
  .circleci/config.yml
Labels: [Tech] Changes validated

#18 [#18][TECH] Ne pas pousser sur dokku api-production lors des MEP (US-1201).
  api/scripts/ansible/ansible.cfg
  api/scripts/ansible/clouds.yml
  api/scripts/ansible/deploy_app_prod.yml
  api/scripts/ansible/inventories/pix-production/group_vars/nodeapp.yml
  api/scripts/ansible/inventories/pix-production/inventory/openstack.py
  api/scripts/ansible/inventories/pix-production/inventory/pix
  api/scripts/ansible/inventories/pix-staging/group_vars/nodeapp.yml
  api/scripts/ansible/inventories/pix-staging/inventory/openstack.py
  api/scripts/ansible/inventories/pix-staging/inventory/pix
  api/scripts/ansible/roles/nodeapp/deploy/defaults/main.yml
  api/scripts/ansible/roles/nodeapp/deploy/tasks/main.yml
  api/scripts/ansible/roles/nodeapp/deploy/templates/pix-api.service
  api/scripts/ansible/roles/nodeapp/deploy/templates/pix-vars.sh
  api/scripts/deploy.sh
  api/scripts/deploy_ansible.sh
  infra/Makefile
  infra/README.md
  infra/administrative_tasks/reboot_database.sh
  infra/bin/dokku_client.sh
  infra/provision/00_install_doku.sh
  infra/provision/01_install_dokku_postgres.sh
  infra/provision/02_create_and_link_api_apps.sh
  infra/provision/03_add_ssh_users.sh
  infra/provision/keys/dbo.pub
  infra/provision/keys/jbu.pub
  infra/provision/keys/twi.pub
  infra/provision/user-data.yml
Labels: [Tech] Review asked

#17 [#17] Corriger le problème de CORS (US-1216).
  api/bin/www
  api/server.js
Labels: [Tech] Review asked

#16 [#16] [FEATURE] Ajout de toutes les informations dans le CSV d'export (US-1181).
  api/scripts/get-results-certifications.js
  api/tests/unit/scripts/get-results-certifications_test.js
Labels: [Func] Review asked, [Tech] Changes validated

#20 [#20][TECH] JV un commentaire Github après un deploy (US-1224).
  .circleci/config.yml
  live/scripts/signal_deploy_to_pr.sh
Labels: [Tech] Review asked

#25 [#25][FIX] Script de récupération de seconde chance (US-1228)
  api/scripts/delete-assessment.js
  api/tests/unit/script/delete-assessment_test.js
Labels: [Func] Review asked, [Tech] Review asked

#29 [#26][TECH] Corriger la suite de tests
  api/tests/unit/application/cache/index_test.js
  api/tests/unit/infrastructure/repositories/course-repository_test.js
Labels: [Tech] Review asked

#30 [#27][BSR] Jette une erreur métier lorsqu’on charge les détails d'une certification qui n’est pas complétée
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/repositories/certification-course-repository.js
Labels: [Tech] Changes validated

#11 [#11] [FEATURE] Génération de CSV de résultats certifications à partir d'un id de session (US-1182)
  api/lib/application/preHandlers/access-session.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/Session.js
  api/lib/domain/services/session-service.js
  api/lib/infrastructure/data/session.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/package.json
  api/scripts/get-results-certifications.js
  api/tests/acceptance/application/session-controller_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/application/preHandlers/access-session_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/services/session-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  api/tests/unit/scripts/delete-assessment_test.js
  api/tests/unit/scripts/get-changelog_test.js
  api/tests/unit/scripts/get-results-certifications-old_test.js
  api/tests/unit/scripts/get-results-certifications_test.js
Labels: [Func] Changes validated, [Tech] Changes done

#22 [#22] Les métriques de /metrics exposent le path dans les compteurs api_request (US-1202)
  api/lib/infrastructure/plugins/metrics.js
  api/tests/unit/infrastructure/plugins/metrics_test.js
Labels: [Func] Review asked, [Tech] Changes done

#23 [#23] [FEATURE] Ajout d'un identifiant externe sur les certifications (US-1190).
  api/db/migrations/20180409172412_add_external_id_to_certification.js
  api/db/seeds/data/certification-courses.js
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/scripts/get-results-certifications.js
  api/scripts/import-certifications-from-csv.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/scripts/import-certifications-from-csv_test.js
  api/tests/acceptance/scripts/valid-certifications-test-file.csv
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/domain/services/certification-service_test.js
  api/tests/unit/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  api/tests/unit/scripts/get-results-certifications_test.js
Labels: [Func] Review asked, [Tech] Changes required

#14 [#14] [FEATURE] Ajout de nouveaux endpoints d'authentification OAuth 2 (US-1205)
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/application/usecases/checkUserCredentialsAndGenerateAccessToken.js
  api/lib/domain/errors.js
  api/package-lock.json
  api/tests/integration/application/authentication/index_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/usecases/checkUserCredentialsAndGenerateAccessToken_test.js
Labels: [Func] Review asked, [Tech] Changes validated

#21 [#21] [CLEANUP] Calcul des marks pour les anciennes certifications (US-1051)
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/assessments/index.js
  api/lib/domain/services/assessment-service.js
  api/scripts/compute-missing-assessments-certification-marks.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/application/assessments/index_test.js
  api/tests/unit/domain/services/assessment-service_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#33 [#33] [BUGFIX] Script de suppression de compte (US-1233).
  api/scripts/delete-user.js
  api/tests/unit/scripts/delete-user_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#34 [#34] [BUGFIX] Corriger l'adresse de contact (US - 1220).
  live/app/templates/components/app-footer.hbs
Labels: [Func] Review asked, [Tech] Review asked

#39 [#39] [TECH] Déploiement de Production sur Scalingo (PI-5)
  .circleci/config.yml
  api/package.json
  api/scripts/deploy.sh
  package.json
  scripts/release/publish.sh
Labels: [Tech] Review asked

#42 [#42] [TECH] BSR des scripts de release et suppression du commit de merge (PI-10)
  scripts/release/common.sh
  scripts/release/perform.sh
  scripts/release/prepare.sh
  scripts/release/publish.sh
Labels: [Tech] Review asked

#45 [#45] [TECH] Déploiement automatique de preview et maths avec la PROD (PI-6)
  scripts/release/deploy-side-apps.sh
  scripts/release/publish.sh
Labels: [Tech] Changes validated

#37 [#37] [FEATURE] Afficher la liste des certifications des utilisateurs (US-1134).
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/Certification.js
  api/lib/domain/usecases/find-completed-user-certifications.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/certification-course.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/certification-controller_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/application/certifications/index_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/usecases/find-completed-user-certifications_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  live/app/components/certifications-list.js
  live/app/components/no-certification-panel.js
  live/app/components/user-certifications-panel.js
  live/app/models/certification.js
  live/app/models/user.js
  live/app/router.js
  live/app/routes/user-certifications.js
  live/app/styles/app.scss
  live/app/styles/components/_app-footer.scss
  live/app/styles/components/_certifications-list.scss
  live/app/styles/components/_no-certification-panel.scss
  live/app/styles/components/_user-logged-menu.scss
  live/app/styles/globals/_palette.scss
  live/app/styles/pages/_user-certifications.scss
  live/app/templates/components/certifications-list.hbs
  live/app/templates/components/no-certification-panel.hbs
  live/app/templates/components/user-certifications-panel.hbs
  live/app/templates/components/user-logged-menu.hbs
  live/app/templates/user-certifications.hbs
  live/mirage/config.js
  live/mirage/factories/certification.js
  live/mirage/scenarios/default.js
  live/public/images/sablier.svg
  live/tests/acceptance/user-certifications-test.js
  live/tests/integration/components/certifications-list-test.js
  live/tests/integration/components/no-certification-panel-test.js
  live/tests/integration/components/user-certifications-panel-test.js
  live/tests/integration/components/user-logged-menu-test.js
  live/tests/unit/models/certification-test.js
  live/tests/unit/routes/user-certifications-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#46 [#46][BSR] Pointer l'url d'intégration vers integration.pix.fr
  live/scripts/signal_deploy_to_pr.sh
  scripts/trello/comment_with_review_app_url.sh
Labels: [Tech] Changes validated

#49 [#49] [FEATURE] Ajout et mise à jour des des informations légales (PF-66).
  live/app/styles/components/_signup-form.scss
  live/app/templates/components/certification-code-validation.hbs
  live/app/templates/components/signup-form.hbs
  live/app/templates/legal-notices.hbs
Labels: [Func] Review asked, [Tech] Changes validated

#53 [#53] [HOTFIX] Resolution du bug sur staging pour récupérer les certifications (US-1134)
  api/lib/infrastructure/repositories/certification-repository.js
Labels: [Func] Changes validated, [Tech] Changes validated
