Repository 1024pix/pix, pull requests merged in 2018-05, with the labels that each got.

#41 [#41] [FEATURE] Modification de la route GET /organizations pour permettre à un Pix Master de récupérer la liste de toutes les organisations de façon sécurisée (US-1248).
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/services/organization-service.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/services/organization-service_test.js
  api/tests/unit/infrastructure/repositories/user-repository_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#50 [#50] [TECH] Ajout d'un jeu d'exemple pour une certification rejeté par l'algo (PF-98).
  api/db/seeds/data/assessment-results.js
  api/db/seeds/data/assessments.js
  api/db/seeds/data/certification-challenges.js
  api/db/seeds/data/certification-courses.js
  api/db/seeds/data/competence-marks.js
  api/db/seeds/data/sessions.js
Labels: [Func] Review asked, [Tech] Changes validated

#48 [#48] Publier une certification (PF-12)
  api/db/migrations/20180425171813_add_isPublished_to_certifications.js
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/domain/models/Certification.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-certification.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/acceptance/application/certification-controller_test.js
  api/tests/integration/application/certifications/index_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/test-helper.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/usecases/update-certification_test.js
Labels: [Tech] Changes validated

#44 [#44] [TECH] Refactoring de l'endpoint de choix de la prochaine question (PF-100).
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/services/assessment-service-utils.js
  api/lib/domain/services/assessment-service.js
  api/lib/domain/usecases/get-next-challenge-for-certification.js
  api/lib/domain/usecases/get-next-challenge-for-demo.js
  api/lib/domain/usecases/get-next-challenge-for-placement.js
  api/lib/domain/usecases/get-next-challenge-for-preview.js
  api/lib/domain/usecases/index.js
  api/package.json
  api/tests/acceptance/application/assessment-controller-get-adaptive-correct_test.js
  api/tests/acceptance/application/assessment-controller-get-adaptive_test.js
  api/tests/acceptance/application/assessment-controller-get-nonadaptive_test.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/domain/services/assessment-service_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-demo_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-preview_test.js
Labels: [Func] Changes validated, [Tech] Review asked

#56 [#56] [FEATURE] Afficher le statut d'une certification (PF-14).
  api/db/seeds/data/certification-courses.js
  api/lib/application/certificationCourses/certification-course-controller.js
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/domain/models/AssessmentResult.js
  api/lib/domain/models/Certification.js
  api/lib/domain/usecases/find-completed-user-certifications.js
  api/lib/infrastructure/repositories/assessment-result-repository.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/assessment-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/acceptance/application/certification-controller_test.js
  api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/unit/application/assessment-results/assessment-results-controller_test.js
  api/tests/unit/application/certificationCourses/certification-course-controller_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/models/Certification_test.js
  api/tests/unit/domain/usecases/find-completed-user-certifications_test.js
  api/tests/unit/domain/usecases/update-certification_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  live/app/components/certifications-list-item.js
  live/app/models/certification.js
  live/app/styles/app.scss
  live/app/styles/components/_certifications-list-item.scss
  live/app/styles/components/_certifications-list.scss
  live/app/templates/components/certifications-list-item.hbs
  live/app/templates/components/certifications-list.hbs
  live/mirage/scenarios/default.js
  live/public/images/icons/icon-check-vert.svg
  live/tests/integration/components/certifications-list-item-test.js
  live/tests/integration/components/certifications-list-test.js
Labels: [Func] Changes validated, [Tech] Changes done, [Tech] Review asked

#47 [#47] L'algorithme ne pose pas de question de plus de deux niveaux au-dessus du niveau prédit (US-1114).
  api/lib/cat/assessment.js
  api/tests/unit/cat/assessment_test.js
Labels: [Tech] Changes validated

#58 [#58] [BUGFIX] Gestion des erreurs 500 lors du partage d'un profil de compétence (PF-140).
  api/db/migrations/20171005222803_update_snapshots_add_student_and_campaign_code.js
  api/lib/application/snapshots/snapshot-controller.js
  api/lib/domain/errors.js
  api/tests/acceptance/application/snapshot-controller_test.js
  api/tests/unit/application/snapshots/snapshot-controller_test.js
  live/app/components/share-profile.js
  live/app/templates/components/share-profile.hbs
  live/tests/integration/components/share-profile-test.js
  live/tests/unit/components/share-profile-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#60 [#60] [FEATURE] L'algo doit parcourir les tubes "facile" en priorité (PF-149).
  api/lib/cat/assessment.js
  api/tests/unit/cat/assessment_test.js
Labels: [Func] Review asked, [Tech] Review asked

#63 [#63] [FEATURE] Ajout d'une URL pour lancer un test de campagne avec l'algo Smart Random (PF-57).
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/adapters/assessment-adapter.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/lib/smart_random/answer.js
  api/lib/smart_random/assessment.js
  api/lib/smart_random/challenge.js
  api/lib/smart_random/course.js
  api/lib/smart_random/skill.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/services/assessment-service_test.js
  api/tests/unit/infrastructure/adapters/assessment-adapter_test.js
  api/tests/unit/infrastructure/repositories/assessment-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  api/tests/unit/smart_random/answer_test.js
  api/tests/unit/smart_random/assessment_test.js
  api/tests/unit/smart_random/challenge_test.js
  api/tests/unit/smart_random/course_test.js
  api/tests/unit/smart_random/skill_test.js
  live/app/router.js
  live/app/routes/campaigns/create-assessment.js
  live/app/templates/campaigns/create-assessment-loading.hbs
  live/app/templates/campaigns/create-assessment.hbs
Labels: [Func] Changes validated, [Tech] Changes validated

#43 [#43] [HOTFIX] Amélioration de la sécurité lors de la création d'un compte utilisateur (US-1247).
  api/lib/application/organizations/organization-controller.js
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/create-user.js
  api/lib/domain/usecases/index.js
  api/lib/domain/validators/organization-creation-validator.js
  api/lib/domain/validators/organization-validator.js
  api/lib/domain/validators/user-validator.js
  api/lib/infrastructure/data/organization.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/lib/infrastructure/validators/errors.js
  api/lib/infrastructure/validators/grecaptcha-validator.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/authentication-controller-save_test.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/users-controller-save_test.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/acceptance/application/users/users-controller-update-password_test.js
  api/tests/integration/application/authentication/authentication-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/bookshelf-user_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/domain/validations/organization-creation-validator_test.js
  api/tests/unit/domain/validations/organization-validator_test.js
  api/tests/unit/domain/validations/user-validator_test.js
  api/tests/unit/infrastructure/models/organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
  api/tests/unit/infrastructure/validators/error_test.js
  api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
  live/app/components/signup-form.js
  live/tests/integration/components/signup-form-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#72 [#72] [TECH] Augmentation du TTL du cache à une journée (PF-172).
  api/lib/infrastructure/cache.js
Labels: [Func] Changes validated, [Tech] Changes validated

#73 [#73] [BUFIX] L'algorithme de positionnement ne filtre pas la première question par acquis prioritaire (PF-176).
  api/lib/cat/assessment.js
  api/tests/unit/cat/assessment_test.js
Labels: [Func] Review asked, [Tech] Review asked

#65 [#65] [FEATURE] Ajout des tests trans-competence a l'algo SmartRandom (PF-91).
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/models/Answer.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Course.js
  api/lib/domain/models/Score.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/SkillsProfile.js
  api/lib/domain/models/Tube.js
  api/lib/domain/services/assessment-service.js
  api/lib/domain/strategies/SmartRandom.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/lib/infrastructure/adapters/assessment-adapter.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/objects/Challenge.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/smart_random/answer.js
  api/lib/smart_random/assessment.js
  api/lib/smart_random/challenge.js
  api/lib/smart_random/course.js
  api/lib/smart_random/skill.js
  api/tests/acceptance/application/answers/answer-controller-find_test.js
  api/tests/acceptance/application/answers/answer-controller-get_test.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/acceptance/application/answers/answer-controller-update_test.js
  api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
  api/tests/acceptance/application/assessment-results/assessment-result-controller_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-adaptive-correct_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-adaptive_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-nonadaptive_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/acceptance/application/assessments/assessment-controller-post_test.js
  api/tests/fixtures/infrastructure/ChallengeAirtableDataObjectFixture.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/domain/models/Answer_test.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/Course_test.js
  api/tests/unit/domain/models/Score_test.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/models/SkillsProfile_test.js
  api/tests/unit/domain/models/Tube_test.js
  api/tests/unit/domain/models/answer_test.js
  api/tests/unit/domain/models/course_test.js
  api/tests/unit/domain/strategies/SmartRandom_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-smart-placement_test.js
  api/tests/unit/infrastructure/adapters/assessment-adapter_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/infrastructure/repositories/course-repository_test.js
  api/tests/unit/smart_random/answer_test.js
  api/tests/unit/smart_random/assessment_test.js
  api/tests/unit/smart_random/challenge_test.js
  api/tests/unit/smart_random/course_test.js
  api/tests/unit/smart_random/skill_test.js
  live/app/templates/campaigns/create-assessment-loading.hbs
  live/app/templates/campaigns/create-assessment.hbs
  live/app/templates/components/course-banner.hbs
Labels: [Func] Changes validated, [Tech] Changes done, [Tech] Review asked

#75 [#75] [FEATURE] Ajout d'une page de résultats intermédiaires pour le smart random (PF-59).
  api/lib/domain/models/Assessment.js
  api/lib/domain/usecases/get-correction-for-answer-when-assessment-ended.js
  api/tests/unit/domain/usecases/get-correction-for-answer-when-assessment-ended_test.js
  live/app/controllers/assessments/checkpoint.js
  live/app/models/assessment.js
  live/app/router.js
  live/app/routes/assessments/challenge.js
  live/app/routes/assessments/checkpoint.js
  live/app/routes/assessments/resume.js
  live/app/styles/app.scss
  live/app/styles/pages/_assessment-checkpoint.scss
  live/app/templates/assessments/checkpoint.hbs
  live/app/templates/assessments/results.hbs
  live/config/environment.js
  live/package-lock.json
  live/package.json
  live/public/images/button-continue/button-continue-next.png
  live/public/images/button-continue/button-continue-next@2x.png
  live/public/images/button-continue/button-continue-next@3x.png
  live/tests/acceptance/b2-epreuve-qcm-test.js
  live/tests/unit/controllers/assessments/checkpoint-test.js
  live/tests/unit/models/assessment-test.js
  live/tests/unit/routes/assessments/challenge-test.js
  live/tests/unit/routes/assessments/resume-test.js
  package-lock.json
  package.json
Labels: [Func] Review asked, [Tech] Review asked

#76 [#76] [BUGFIX] Correction des bogues sur la gestion de la fin d'un test (PF-170)
  api/lib/domain/models/CompetenceMark.js
  api/lib/domain/services/assessment-result-service.js
  api/lib/domain/services/assessment-service.js
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
  api/tests/acceptance/application/certification-controller_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/factory/build-competence-mark.js
  api/tests/factory/index.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/application/certificationCourses/certification-course-controller_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/models/CompetenceMark_test.js
  api/tests/unit/domain/services/assessment-result-service_test.js
  api/tests/unit/domain/services/assessment-service_test.js
  api/tests/unit/domain/services/certification-service_test.js
  api/tests/unit/infrastructure/repositories/assessment-repository_test.js
  api/tests/unit/infrastructure/repositories/certification-course-repository_test.js
  live/app/components/competence-level-progress-bar.js
  live/app/templates/components/competence-level-progress-bar.hbs
  live/tests/unit/components/competence-level-progress-bar-test.js
Labels: [Func] Review asked, [Tech] Review asked

#64 [#64] [TECH] Logging des erreurs 500 sur Sentry (PI-24)
  api/lib/plugins.js
  api/package-lock.json
  api/package.json
  live/config/environment.js
Labels: [Func] Changes validated, [Tech] Changes validated
