Repository 1024pix/pix, pull requests merged in 2018-11, with the labels that each got.

#250 [#250] [FEATURE] Ajout du didacticiel lorsqu'un utilisateur commence une campagne (PF-71).
  mon-pix/app/models/campaign-tutorial.js
  mon-pix/app/router.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/campaigns/tutorial.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_competence-level-progress-bar.scss
  mon-pix/app/styles/components/_user-certifications-detail-competence.scss
  mon-pix/app/styles/globals/_palette.scss
  mon-pix/app/styles/globals/_pix-button.scss
  mon-pix/app/styles/pages/_campaign-tutorial.scss
  mon-pix/app/templates/campaigns/fill-in-id-pix.hbs
  mon-pix/app/templates/campaigns/tutorial.hbs
  mon-pix/public/images/tutorial-campaign/icn-algo.svg
  mon-pix/public/images/tutorial-campaign/icn-recherche.svg
  mon-pix/public/images/tutorial-campaign/icn-temps.svg
  mon-pix/public/images/tutorial-campaign/icn-tutos.svg
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/start-campaigns-test.js
  mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
  mon-pix/tests/unit/routes/campaigns/tutorial-test.js
Labels: [Func] Review asked, [Tech] Changes validated

#241 [#241] [FEATURE] Le titre de la campagne est écrit dans la bannière de challenge (PF-74)
  mon-pix/app/components/campaign-banner.js
  mon-pix/app/components/placement-banner.js
  mon-pix/app/models/assessment.js
  mon-pix/app/models/campaign.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_campaign-banner.scss
  mon-pix/app/styles/components/_placement-banner.scss
  mon-pix/app/styles/globals/_fonts.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/components/campaign-banner.hbs
  mon-pix/app/templates/components/placement-banner.hbs
  mon-pix/config/environment.js
  mon-pix/mirage/data/assessments/ref-assessment-placement.js
  mon-pix/mirage/data/assessments/ref-assessment.js
  mon-pix/mirage/routes/get-campaigns.js
  mon-pix/mirage/routes/post-campaign-participation.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/public/images/pix-logo-blanc.svg
  mon-pix/tests/acceptance/challenge-page-banner-test.js
  mon-pix/tests/acceptance/index-test.js
  mon-pix/tests/acceptance/page-accueil-test.js
  mon-pix/tests/integration/components/campaign-banner-test.js
  mon-pix/tests/integration/components/placement-banner-test.js
  mon-pix/tests/unit/models/assessment-test.js
  mon-pix/tests/unit/routes/assessments/challenge-test.js
Labels: [Tech] Review asked

#256 [#256] [BUGFIX] Affichage correct sous IE de la phrase légale lors de la création de compte (PF-441).
  mon-pix/app/styles/components/_signup-form.scss
Labels: [Func] Changes validated, [Tech] Changes validated

#254 [#254] [TECH] Renommage du concept métier "OrganizationAccess" en "Membership"
  .gitignore
  api/db/migrations/20181031151955_rename-organization-accesses-into-memberships.js
  api/db/seeds/data/organization-with-related/dragon-and-co-builder.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/Membership.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/usecases/get-results-campaign-in-csv-format.js
  api/lib/domain/usecases/get-user-with-memberships.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/membership.js
  api/lib/infrastructure/data/organization.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/membership-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-memberships_test.js
  api/tests/acceptance/application/users/users-controller-get-user_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-membership.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/factory/build-membership.js
  api/tests/tooling/factory/build-user.js
  api/tests/tooling/factory/index.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/create-campaign_test.js
  api/tests/unit/domain/usecases/get-results-campaign-in-csv-format_test.js
  api/tests/unit/domain/usecases/get-user-with-memberships_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  orga/app/models/membership.js
  orga/app/models/user.js
  orga/app/services/current-organization.js
  orga/mirage/config.js
  orga/mirage/scenarios/default.js
  orga/mirage/serializers/membership.js
  orga/mirage/serializers/user.js
  orga/tests/acceptance/authentication-test.js
  orga/tests/acceptance/campaign-creation-test.js
  orga/tests/acceptance/campaign-list-test.js
  orga/tests/acceptance/terms-of-service-test.js
  orga/tests/helpers/test-init.js
  orga/tests/unit/models/membership-test.js
  orga/tests/unit/services/current-organization-test.js
Labels: [Tech] Changes validated

#251 [#251] [FEATURE] Ajout d'un texte personnalisé pour la page d'accueil lors de la création de la campagne (PO-24).
  api/db/migrations/20181030141633_add_custom_landing_page_text_to_campaign.js
  api/db/seeds/data/3rd-to-create/campaigns.js
  api/lib/domain/models/Campaign.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/tooling/database-builder/factory/build-campaign.js
  api/tests/tooling/factory/build-campaign.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  mon-pix/app/models/campaign.js
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/config/environment.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/acceptance/start-campaigns-test.js
  orga/app/models/campaign.js
  orga/app/styles/components/campaign-creation-form.scss
  orga/app/styles/globals/forms.scss
  orga/app/templates/components/campaign-creation-form.hbs
  orga/tests/acceptance/campaign-creation-test.js
  orga/tests/integration/components/campaign-creation-form-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#261 [#261] [FEATURE] Modification du tutorial avec ajout du bouton Ignorer (PF-443).
  mon-pix/app/routes/campaigns/tutorial.js
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/pages/_campaign-tutorial.scss
  mon-pix/app/templates/campaigns/tutorial.hbs
  mon-pix/tests/acceptance/challenge-page-banner-test.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/start-campaigns-test.js
Labels: [Func] Review asked, [Tech] Review asked

#263 [#263] Afficher le logo de l'organisation dans la landing page des campagnes (PF-239)
  api/db/seeds/data/3rd-to-create/campaigns.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/usecases/get-campaign-by-code.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/tooling/factory/build-campaign.js
  api/tests/unit/domain/usecases/get-campaign-by-code_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  mon-pix/app/models/campaign.js
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/acceptance/start-campaigns-test.js
Labels: [Tech] Review asked

#259 [#259] [BUGFIX] Filtrer les acquis par status (PF-147).
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/tests/tooling/fixtures/infrastructure/skillRawAirTableFixture.js
  api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
Labels: [Func] Review asked, [Tech] Review asked

#264 [#264] [FEATURE] Mise-à-jour de la bannière de reprise pour le cas où l'utilisateur n'a pas partagé ses résultats (PF-405).
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  mon-pix/app/components/resume-campaign-banner.js
  mon-pix/app/models/assessment.js
  mon-pix/app/templates/components/resume-campaign-banner.hbs
  mon-pix/tests/integration/components/resume-campaign-banner-test.js
  mon-pix/tests/unit/components/resume-campaign-banner-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#266 [#266] [BUGFIX] Affichage de l'en-tête avec le titre (s'il existe) sur les pages de résultats intermédiaires (PF-445).
  mon-pix/app/routes/assessments/checkpoint.js
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/tests/unit/routes/assessments/checkpoint-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#268 [#268] [BUGFIX] Ré-initialisation de la page de résultats d'une campagne (pf-449).
  mon-pix/app/routes/campaigns/skill-review.js
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/find-assessments.js
  mon-pix/mirage/routes/get-campaign-participation.js
  mon-pix/mirage/routes/get-courses-of-the-week.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/helpers/testing.js
  mon-pix/tests/unit/controllers/campaigns/skill-repository-test.js
  mon-pix/tests/unit/controllers/campaigns/skill-review-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#273 [TECH] Amélioration du script récupérant le ChangeLog
  api/scripts/get-changelog.js
  api/tests/unit/scripts/get-changelog_test.js
Labels: TECH REVIEW ASKED

#271 [BSR] Uniformisation du lancement des applications
  mon-pix/package.json
  orga/package.json
Labels: Ready to Merge

#270 [FEATURE] La barre de progression se met à jour en même temps que la question (PF-348).
  mon-pix/app/components/progress-bar.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/tests/unit/components/progress-bar-test.js
Labels: Ready to Merge

#276 [TECH] Début de refactoring tests d'acceptance.
  mon-pix/mirage/routes/get-answer-by-challenge-and-assessment.js
  mon-pix/tests/acceptance/board-organization-test.js
  mon-pix/tests/acceptance/challenge-attachment-test.js
  mon-pix/tests/acceptance/challenge-commons-test.js
  mon-pix/tests/acceptance/challenge-feedback-test.js
  mon-pix/tests/acceptance/challenge-qcm-test.js
  mon-pix/tests/acceptance/challenge-qcu-test.js
  mon-pix/tests/acceptance/challenge-qroc-test.js
  mon-pix/tests/acceptance/challenge-qrocm-test.js
  mon-pix/tests/acceptance/challenge-timed-test.js
  mon-pix/tests/acceptance/compare-answer-solution-qroc-test.js
  mon-pix/tests/acceptance/compare-answer-solution-test.js
  mon-pix/tests/acceptance/compte-authentication-and-profile-test.js
  mon-pix/tests/acceptance/compte-display-competence-test.js
  mon-pix/tests/acceptance/course-ending-screen-test.js
  mon-pix/tests/acceptance/d1-epreuve-validation-test.js
  mon-pix/tests/acceptance/error-redirection-test.js
  mon-pix/tests/acceptance/j2-compare-answer-solution-qroc-test.js
  mon-pix/tests/acceptance/starting-a-course-test.js
  mon-pix/tests/acceptance/timeout-jauge-test.js
Labels: TECH REVIEW ASKED

#262 [TECH] Ajout d'un système de lock afin de limiter les requêtes à Airtable (PF-416).
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/caches/cache.js
  api/lib/infrastructure/caches/in-memory-cache.js
  api/lib/infrastructure/caches/preloader.js
  api/lib/infrastructure/caches/redis-cache.js
  api/lib/infrastructure/caches/redis-client.js
  api/lib/settings.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/airtable_test.js
  api/tests/unit/infrastructure/caches/cache_test.js
  api/tests/unit/infrastructure/caches/in-memory-cache_test.js
  api/tests/unit/infrastructure/caches/redis-cache_test.js
Labels: Work on Functional Review

#243 [FEATURE] Implémentation de SAML pour le GAR (PF-362).
  api/db/migrations/20160927153108_create_users.js
  api/db/migrations/20181113161140_add_samlId_to_user.js
  api/db/migrations/20181121105953_make_users_email_nullable.js
  api/lib/application/saml/index.js
  api/lib/application/saml/saml-controller.js
  api/lib/application/users/index.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/get-or-create-saml-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/saml.js
  api/lib/routes.js
  api/lib/settings.js
  api/package-lock.json
  api/package.json
  api/scripts/make-saml-env.js
  api/tests/acceptance/application/saml-controller_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/saml/saml-controller_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/get-or-create-saml-user_test.js
  mon-pix/app/authenticators/simple.js
  mon-pix/app/routes/inscription.js
  mon-pix/app/routes/login.js
  mon-pix/tests/unit/authenticators/simple-test.js
  mon-pix/tests/unit/routes/inscription-test.js
  mon-pix/tests/unit/routes/login-test.js
Labels: Tech Review Finished

#281 [FEATURE] Recherche d'utilisateurs insensible à la casse. (PA-58)
  api/lib/infrastructure/repositories/user-repository.js
Labels: TECH REVIEW ASKED

#283 [BUGFIX] Suppression d'erreur sur get certification sans assessment. (PF-354)
  api/lib/domain/services/certification-service.js
Labels: TECH REVIEW ASKED

#285 [BUGFIX] Gestion de la recherche de positionnement lorsqu'aucun utilisateur est connecté (PF-430).
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/assessments/index.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/unit/application/assessments/assessment-controller_test.js
Labels: Tech Review Finished

#286 [BUGFIX] Rétablir la redirection de /connexion vers /compte pour les utilisateurs déjà authentifiés (PF-456)
  mon-pix/app/routes/login.js
  mon-pix/tests/unit/routes/login-test.js
Labels: Tech Review Finished

#282 [FEATURE] Mise à jour de la gestion de la première question posée à l'utilisateur (PF-436).
  api/lib/cat/assessment.js
  api/lib/domain/strategies/SmartRandom.js
  api/tests/unit/domain/strategies/SmartRandom_test.js
Labels: Tech Review Finished
