Repository 1024pix/pix, pull requests merged in 2018-10, with the labels that each got.

#229 [#229][BUGFIX] Quick hotfix, ne pas rediriger vers la page résultats en cas d'erreur d'api (PF-427)
  mon-pix/app/routes/assessments/resume.js
  mon-pix/config/environment.js
  mon-pix/tests/unit/routes/assessments/resume-test.js
Labels: [Func] Review asked, [Tech] Review asked

#240 [#240] [BUGFIX] Les documents 'embed' fonctionnent maintenant sous Internet Explorer (PF-432)
  mon-pix/app/models/challenge.js
Labels: [Func] Changes validated, [Tech] Changes validated

#238 [#238] [FEATURE] Ajout d'un bandeau pour reprendre une campagne (PF-269).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/usecases/get-user-campaign-participations.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/errors.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/acceptance/application/users/users-get-campaign-participations_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/tooling/database-builder/factory/build-campaign-participation.js
  api/tests/tooling/factory/build-campaign-participation.js
  api/tests/unit/domain/usecases/get-user-campaign-participations_test.js
  api/tests/unit/domain/usecases/get-user-with-organizations-accesses_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  mon-pix/app/components/resume-campaign-banner.js
  mon-pix/app/models/campaign-participation.js
  mon-pix/app/models/campaign.js
  mon-pix/app/models/user.js
  mon-pix/app/routes/compte.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_resume-campaign-banner.scss
  mon-pix/app/templates/components/resume-campaign-banner.hbs
  mon-pix/app/templates/compte.hbs
  mon-pix/package.json
  mon-pix/tests/integration/components/resume-campaign-banner-test.js
  mon-pix/tests/unit/components/resume-campaign-banner-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#239 [#242] [FEATURE] Ajout du endpoint GET /organizations/{id} qui permet à un Pix Master de récupérer le détail d'une organisation (PA-50).
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/models/Organization.js
  api/lib/domain/usecases/get-organization-details.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/organization-access.js
  api/lib/infrastructure/data/organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/factory/build-organization.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/get-organization-details_test.js
  api/tests/unit/infrastructure/models/organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
  orga/package-lock.json
Labels: [Tech] Changes validated

#245 [#245] Ajout d'une règle CSS pour empêcher le texte du bouton d'export de s'afficher sur 2 lignes (PO-130)
  orga/app/styles/components/campaign-item.scss
Labels: [Tech] Review asked

#244 [#244] [FEATURE] Ajout d'un message pour prévenir l'utilisateur que le résultats de ses campagnes ne sont pas inclus dans son profil (PF-400)
  mon-pix/app/components/results-warning.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_results-warning.scss
  mon-pix/app/templates/components/results-warning.hbs
  mon-pix/app/templates/compte.hbs
  mon-pix/public/images/icons/icon-warning.svg
  mon-pix/tests/integration/components/results-warning-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#242 [#242] [FEATURE] Ajout de la gestion du logo d'une organisation dans Pix Admin (PA-53).
  api/db/migrations/20181023231845_update_organizations_add_column_logourl.js
  api/db/seeds/data/organization-with-related/dragon-and-co-builder.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/models/Organization.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-organization-information.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/test-helper.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/factory/build-organization.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: [Tech] Changes validated
