Repository 1024pix/pix, pull requests merged in 2018-06, with the labels that each got.

#81 [#81] [TECH] Lance le linter avant chaque push (PF-205).
  package.json
Labels: [Func] Changes validated, [Tech] Changes validated

#69 [#69] [FEATURE] Ajout du simulateur embarqué pour les épreuves de type e-preuve (PF-38).
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/objects/AirtableResourceNotFound.js
  api/lib/infrastructure/datasources/airtable/objects/Challenge.js
  api/lib/infrastructure/datasources/airtable/objects/index.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/serializers/airtable/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/package-lock.json
  api/tests/acceptance/application/challenge-controller_test.js
  api/tests/fixtures/infrastructure/ChallengeAirtableDataObjectFixture.js
  api/tests/fixtures/infrastructure/challengeRawAirTableFixture.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/models/Challenge_test.js
  api/tests/unit/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/infrastructure/serializers/airtable/challenge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  live/app/components/challenge-embed-simulator.js
  live/app/components/challenge-statement.js
  live/app/components/challenge-stay.js
  live/app/models/challenge.js
  live/app/styles/app.scss
  live/app/styles/components/_challenge-embed-simulator.scss
  live/app/styles/components/_challenge-statement.scss
  live/app/styles/components/_challenge-stay.scss
  live/app/templates/components/challenge-embed-simulator.hbs
  live/app/templates/components/challenge-item-qcm.hbs
  live/app/templates/components/challenge-item-qcu.hbs
  live/app/templates/components/challenge-item-qroc.hbs
  live/app/templates/components/challenge-item-qrocm.hbs
  live/app/templates/components/challenge-statement.hbs
  live/app/templates/components/challenge-stay.hbs
  live/mirage/config.js
  live/mirage/data/challenges/ref-qcu-challenge.js
  live/mirage/fixtures/challenges.js
  live/tests/acceptance/g1-bandeau-no-internet-no-outils-test.js
  live/tests/integration/components/challenge-embed-simulator-test.js
  live/tests/integration/components/challenge-statement-test.js
  live/tests/integration/components/challenge-stay-test.js
  live/tests/integration/components/scoring-panel-test.js
  live/tests/unit/components/challenge-statement-test.js
  live/tests/unit/models/challenge-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#84 [#84] [TECH] Ajouter les RA en commentaire des issues Jira (pf-222).
  .circleci/config.yml
  scripts/jira/comment_with_review_app_url.sh
  scripts/trello/comment_with_review_app_url.sh
Labels: [Tech] Review asked

#82 [#82] [BUGFIX] Les skills doivent être comparés par noms (PF-103)
  api/lib/cat/challenge.js
  api/lib/cat/skill.js
  api/package.json
  api/tests/factory/build-answer.js
  api/tests/factory/build-assessment-result.js
  api/tests/factory/build-cat-challenge.js
  api/tests/factory/build-cat-tube.js
  api/tests/factory/build-certification.js
  api/tests/factory/build-challenge.js
  api/tests/factory/build-competence-mark.js
  api/tests/factory/build-skill-collection.js
  api/tests/factory/build-skill.js
  api/tests/factory/index.js
  api/tests/unit/cat/answer_test.js
  api/tests/unit/cat/assessment_test.js
  api/tests/unit/cat/challenge_test.js
  api/tests/unit/cat/skill_test.js
  api/tests/unit/domain/strategies/SmartRandom_test.js
Labels: [Func] Review asked, [Tech] Changes validated

#80 [#80] Implémentation de l'authentification sur pix-orga (PO-18)
  api/db/migrations/20180528152339_create_table_organizations_roles.js
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/application/usecases/checkUserCredentialsAndGenerateAccessToken.js
  api/lib/domain/errors.js
  api/lib/domain/models/OrganizationAccess.js
  api/lib/domain/models/OrganizationRole.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/organization-access.js
  api/lib/infrastructure/data/organization-role.js
  api/lib/infrastructure/data/organization.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/user-repository.js
  api/package-lock.json
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/factory/build-organization-access.js
  api/tests/factory/build-organization-role.js
  api/tests/factory/build-organization.js
  api/tests/factory/build-pix-role.js
  api/tests/factory/build-user.js
  api/tests/factory/index.js
  api/tests/integration/application/authentication/index_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/usecases/checkUserCredentialsAndGenerateAccessToken_test.js
  api/tests/unit/domain/models/user_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
Labels: [Tech] Review asked

#83 [#83] [TECH] Montée de version de Ember.js de 2.18 vers 3.2 (PF-207).
  live/.eslintignore
  live/.eslintrc.js
  live/app/components/feedback-panel.js
  live/app/controllers/assessments/checkpoint.js
  live/app/router.js
  live/app/routes/certifications/start.js
  live/app/services/delay.js
  live/app/utils/call-only-once.js
  live/config/environment.js
  live/config/targets.js
  live/ember-cli-build.js
  live/package-lock.json
  live/package.json
  live/public/browserconfig.xml
  live/public/crossdomain.xml
  live/testem.js
  live/tests/integration/components/signin-form-test.js
  live/tests/unit/models/assessment-test.js
  live/tests/unit/models/certification-test.js
  live/tests/unit/routes/certifications/start-test.js
Labels: [Func] Review asked, [Tech] Review asked

#88 [#88] [TECH] Mise à jour des routes pour vider le cache (PF-226)
  api/lib/application/cache/cache-controller.js
  api/lib/application/cache/index.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/remove-all-cache-entries.js
  api/lib/domain/usecases/remove-cache-entry.js
  api/lib/infrastructure/caches/in-memory-cache.js
  api/lib/infrastructure/caches/redis-cache.js
  api/tests/acceptance/application/cache-controller_test.js
  api/tests/unit/application/cache/cache-controller_test.js
  api/tests/unit/application/cache/index_test.js
  api/tests/unit/domain/usecases/remove-all-cache-entries_test.js
  api/tests/unit/domain/usecases/remove-cache-entry_test.js
  api/tests/unit/infrastructure/caches/in-memory-cache_test.js
  api/tests/unit/infrastructure/caches/redis-cache_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#86 [#86] [FEATURE] Barre de progression dans un test Smart Placement (PF-72).
  .circleci/config.yml
  api/package.json
  live/app/models/assessment.js
  live/tests/unit/models/assessment-test.js
  live/tests/unit/models/behaviors/assessment-progression/ProgressWithCheckpoints-test.js
Labels: [Func] Review asked, [Tech] Changes validated

#92 [#92] [FEATURE] Creation du endpoint /api/users/{id} avec remontée de la validation des CGU de Pix-Orga (PO-106)
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/get-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/lib/interfaces/jsonapi/index.js
  api/lib/interfaces/jsonapi/internal-error.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/acceptance/application/users/users-controller-get-user_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/user_test.js
  api/tests/unit/domain/usecases/get-user_test.js
  api/tests/unit/infrastructure/models/user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
Labels: [Func] Review asked, [Tech] Changes required

#97 [#97] Retrofit PF-154 and PF-103 in SmartRandom + BSR (PF-231).
  .gitignore
  api/lib/cat/skill.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Course.js
  api/lib/domain/models/Skill.js
  api/lib/domain/strategies/SmartRandom.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/tests/factory/build-assessment.js
  api/tests/factory/build-course.js
  api/tests/factory/build-tube.js
  api/tests/factory/index.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/cat/skill_test.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/strategies/SmartRandom_test.js
Labels: [Func] Review asked, [Tech] Changes validated

#110 [#110][BSR] Suppression d'une vieille route
  live/app/helpers/eq.js
  live/app/helpers/or.js
  live/app/router.js
  live/app/routes/placement-tests.js
  live/app/templates/placement-tests.hbs
  live/app/utils/lodash-custom.js
  live/tests/acceptance/a5-voir-liste-tests-adaptatifs-test.js
  live/tests/unit/helpers/eq-test.js
  live/tests/unit/helpers/or-test.js
  live/tests/unit/routes/placement-tests-test.js
Labels: [Tech] Review asked
