Repository 1024pix/pix, pull requests merged in 2018-07, with the labels that each got.

#111 [#111] [FEATURE] Afficher des tutoriaux sur la page de réponse (PF-62).
  api/lib/domain/models/Correction.js
  api/lib/domain/models/Tutorial.js
  api/lib/infrastructure/datasources/airtable/objects/Skill.js
  api/lib/infrastructure/datasources/airtable/objects/Tutorial.js
  api/lib/infrastructure/datasources/airtable/objects/index.js
  api/lib/infrastructure/datasources/airtable/tutorial-datasource.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/tests/acceptance/application/corrections/correction-controller_test.js
  api/tests/factory/build-hint.js
  api/tests/factory/build-tutorial.js
  api/tests/factory/index.js
  api/tests/fixtures/infrastructure/challengeAirtableDataObjectFixture.js
  api/tests/fixtures/infrastructure/skillAirtableDataObjectFixture.js
  api/tests/fixtures/infrastructure/skillRawAirTableFixture.js
  api/tests/fixtures/infrastructure/tutorialAirtableDataObjectFixture.js
  api/tests/fixtures/infrastructure/tutorialRawAirtableFixture.js
  api/tests/unit/application/corrections/corrections-controller_test.js
  api/tests/unit/infrastructure/datasources/airtable/models/Challenge_test.js
  api/tests/unit/infrastructure/datasources/airtable/models/Skill_test.js
  api/tests/unit/infrastructure/datasources/airtable/models/Tutorial_test.js
  api/tests/unit/infrastructure/datasources/airtable/tutorial-datasource_test.js
  api/tests/unit/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/repositories/solution-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
  live/app/components/tutorial-item.js
  live/app/components/tutorial-panel.js
  live/app/models/correction.js
  live/app/models/tutorial.js
  live/app/styles/app.scss
  live/app/styles/components/_tutorial-item.scss
  live/app/styles/components/_tutorial-panel.scss
  live/app/templates/components/comparison-window.hbs
  live/app/templates/components/tutorial-item.hbs
  live/app/templates/components/tutorial-panel.hbs
  live/package-lock.json
  live/public/images/icons/page-icon.svg
  live/public/images/icons/son-icon.svg
  live/public/images/icons/video-icon.svg
  live/tests/integration/components/tutorial-panel-test.js
  live/tests/unit/components/tutorial-item-test.js
  live/tests/unit/components/tutorial-panel-test.js
Labels: [Func] Review asked, [Tech] Review asked

#118 [#118] Suppression des sections "partenaires" et "bêta-testeur" sur la page d'accueil (PF-155).
  live/app/components/follower-form.js
  live/app/components/partners-enrollment-panel.js
  live/app/models/follower.js
  live/app/router.js
  live/app/routes/enrollment.js
  live/app/styles/app.scss
  live/app/styles/components/_follower-form.scss
  live/app/styles/components/_partners-enrollment-panel.scss
  live/app/styles/pages/_enrollment.scss
  live/app/styles/pages/_index.scss
  live/app/templates/components/follower-form.hbs
  live/app/templates/components/partners-enrollment-panel.hbs
  live/app/templates/enrollment.hbs
  live/app/templates/index.hbs
  live/mirage/config.js
  live/tests/acceptance/page-accueil-test.js
  live/tests/integration/components/follower-form-test.js
  live/tests/integration/components/partners-enrollment-panel-test.js
  live/tests/unit/components/follower-form-test.js
  live/tests/unit/models/follower-test.js
  live/tests/unit/routes/enrollment-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#122 [#122][TECH] Normalisation des constructeurs des modèles du domaine
  api/lib/domain/models/Answer.js
  api/lib/domain/models/AnswerStatus.js
  api/lib/domain/models/Area.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/AssessmentResult.js
  api/lib/domain/models/Authentication.js
  api/lib/domain/models/Certification.js
  api/lib/domain/models/CertificationChallenge.js
  api/lib/domain/models/CertificationContract.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Competence.js
  api/lib/domain/models/CompetenceMark.js
  api/lib/domain/models/CompetenceTree.js
  api/lib/domain/models/Correction.js
  api/lib/domain/models/Course.js
  api/lib/domain/models/Hint.js
  api/lib/domain/models/Organization.js
  api/lib/domain/models/OrganizationAccess.js
  api/lib/domain/models/OrganizationRole.js
  api/lib/domain/models/PixRole.js
  api/lib/domain/models/Profile.js
  api/lib/domain/models/ResultCompetence.js
  api/lib/domain/models/ResultCompetenceTree.js
  api/lib/domain/models/Score.js
  api/lib/domain/models/Session.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/SkillReview.js
  api/lib/domain/models/SmartPlacementAnswer.js
  api/lib/domain/models/SmartPlacementAssessment.js
  api/lib/domain/models/SmartPlacementKnowledgeElement.js
  api/lib/domain/models/Solution.js
  api/lib/domain/models/TargetProfile.js
  api/lib/domain/models/Tube.js
  api/lib/domain/models/Tutorial.js
  api/lib/domain/models/User.js
  api/lib/domain/models/UserCompetence.js
Labels: [Tech] Changes done

#114 [#114] [TECH] Réparer la route /details des certifs (PF-253).
  api/lib/application/certificationCourses/index.js
  api/lib/domain/models/CertificationContract.js
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/unit/application/certificationCourses/certification-course-controller_test.js
  api/tests/unit/domain/services/certification-service_test.js
Labels: [Func] Review asked, [Tech] Changes validated

#130 [#130] [BUGFIX] Correction du bug des questions en doubles dans le smart-random (PF-287)
  api/lib/domain/strategies/SmartRandom.js
  api/tests/unit/domain/strategies/SmartRandom_test.js
Labels: [Func] Review asked, [Tech] Review asked

#128 [#128] [CLEANUP] Suppression de la propriété "authenticationRoute" inutile dans les routes Ember.
  live/app/routes/board.js
  live/app/routes/campaigns/create-assessment.js
  live/app/routes/certifications/results.js
  live/app/routes/certifications/start.js
  live/app/routes/compte.js
  live/tests/unit/routes/compte-test.js
Labels: [Tech] Changes validated

#129 [#129] [FEATURE] Afficher le % d'avancement du smart placement (PF-78).
  api/lib/domain/models/SkillReview.js
  api/lib/domain/models/SmartPlacementAssessment.js
  api/lib/infrastructure/repositories/smart-placement-assessment-repository.js
  api/lib/infrastructure/serializers/jsonapi/skill-review-serializer.js
  api/tests/factory/build-skill-review.js
  api/tests/integration/infrastructure/repositories/smart-placement-assessment-repository_test.js
  api/tests/unit/application/skillReviews/skill-review-controller_test.js
  api/tests/unit/domain/models/SkillReview_test.js
  api/tests/unit/domain/models/SmartPlacementAssessment_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-review-serializer_test.js
  live/app/controllers/assessments/checkpoint.js
  live/app/models/skill-review.js
  live/app/routes/assessments/challenge.js
  live/app/routes/assessments/checkpoint.js
  live/app/routes/assessments/rating.js
  live/app/styles/app.scss
  live/app/styles/components/_checkpoint.scss
  live/app/styles/globals/_palette.scss
  live/app/styles/globals/_progress-bar.scss
  live/app/templates/assessments/checkpoint.hbs
  live/tests/unit/controllers/assessments/checkpoint-test.js
  live/tests/unit/models/skill-review-test.js
  live/tests/unit/routes/assessments/challenge-test.js
  live/tests/unit/routes/assessments/checkpoint-test.js
  live/tests/unit/routes/assessments/rating-test.js
Labels: [Func] Review asked, [Tech] Changes validated

#117 [#117] [FEATURE] Reprise d'une évaluation de type Smart Random (US-93).
  api/db/migrations/20160929164549_create_assessments.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/services/assessment-service.js
  api/lib/domain/usecases/find-user-assessments-by-filters.js
  api/lib/domain/usecases/index.js
  api/package.json
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/domain/services/assessment-service_test.js
  api/tests/unit/domain/usecases/find-user-assessments-by-filters.js
  live/app/components/course-banner.js
  live/app/components/progress-bar.js
  live/app/controllers/assessments/checkpoint.js
  live/app/models/assessment-progression.js
  live/app/models/assessment.js
  live/app/models/behaviors/assessment-progression/ProgressWithCheckpoints.js
  live/app/models/behaviors/assessment-progression/ProgressWithoutCheckpoints.js
  live/app/models/behaviors/assessment-progression/index.js
  live/app/router.js
  live/app/routes/assessments/challenge.js
  live/app/routes/assessments/checkpoint.js
  live/app/routes/campaigns/create-assessment.js
  live/app/routes/campaigns/start-or-resume.js
  live/app/routes/certifications/resume.js
  live/app/styles/components/_result-item.scss
  live/app/styles/pages/_assessment-checkpoint.scss
  live/app/styles/pages/_assessment-results.scss
  live/app/templates/assessments/challenge.hbs
  live/app/templates/assessments/checkpoint.hbs
  live/app/templates/campaigns/start-or-resume-loading.hbs
  live/app/templates/campaigns/start-or-resume.hbs
  live/app/templates/components/course-banner.hbs
  live/app/templates/components/progress-bar.hbs
  live/tests/unit/components/course-banner-test.js
  live/tests/unit/components/progress-bar-test.js
  live/tests/unit/models/assessment-progress-test.js
  live/tests/unit/models/assessment-test.js
  live/tests/unit/models/behaviors/assessment-progression/ProgressWithCheckpoints-test.js
  live/tests/unit/models/behaviors/assessment-progression/ProgressWithoutCheckpoints-test.js
  live/tests/unit/routes/campaigns/start-or-resume-test.js
  live/tests/unit/routes/certifications/resume-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#131 [#131] [BUGFIX] La route /admin/certifications doit retourner des informations même quand la certif n'est pas terminé (PF-291).
  api/lib/domain/services/certification-service.js
  api/tests/unit/domain/services/certification-service_test.js
Labels: [Tech] Changes done

#132 [#132] [Feature] Mise à jour du profil cible pour rendre l'expérience plus rapide pour les panels (PF-293).
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/unit/infrastructure/repositories/target-profile-repository_test.js
Labels: [Func] Changes validated, [Tech] Review asked

#133 [#133] [BUGFIX] Correction du bug affichant les compétences du profil plutôt que celui des certifs (PF-282).
  api/lib/domain/models/ResultCompetenceTree.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/acceptance/application/certification-controller_test.js
  api/tests/unit/domain/models/ResultCompetenceTree_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  live/app/components/user-certifications-detail-area.js
  live/app/models/area.js
  live/app/models/result-competence.js
  live/tests/integration/components/user-certifications-detail-area-test.js
  live/tests/integration/components/user-certifications-detail-profile-test.js
  live/tests/unit/models/result-competence-test.js
Labels: [Tech] Changes validated

#136 [#136] [BUGFIX] Correction de la page "Oups" qui s'affiche en boucle à l'expiration de la session (PF-297).
  live/app/routes/application.js
  live/tests/unit/routes/application-test.js
Labels: [Func] Review asked, [Tech] Review asked

#108 [#108] [FEATURE] Création d'une campagne (PO-82)
  api/db/migrations/20180620161732_create_campaigns.js
  api/db/seeds/data/3rd-to-create/campaigns.js
  api/db/seeds/data/3rd-to-create/organizations-accesses.js
  api/db/seeds/seed.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/models/User.js
  api/lib/domain/services/campaigns/campaign-code-generator.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/usecases/index.js
  api/lib/domain/validators/campaign-validator.js
  api/lib/infrastructure/data/campaign.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/lib/interfaces/jsonapi/forbidden-error.js
  api/lib/interfaces/jsonapi/index.js
  api/lib/interfaces/jsonapi/unprocessable-entity-error.js
  api/lib/routes.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/factory/build-campaign.js
  api/tests/factory/index.js
  api/tests/integration/application/campaigns/index_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/services/campaigns/campaign-code-generator_test.js
  api/tests/unit/domain/services/certification-course-service_test.js
  api/tests/unit/domain/usecases/create-campaign_test.js
  api/tests/unit/domain/validations/campaign-validator_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  api/tests/unit/interfaces/jsonapi/forbidden-error-test.js
  api/tests/unit/interfaces/jsonapi/internal-error-test.js
  api/tests/unit/interfaces/jsonapi/unprocessable-entity-error-test.js
Labels: [Func] Review asked, [Tech] Changes validated

#119 [#119] Ajout des tutoriels “Pour en savoir plus” à la page des résultats (PF-63).
  api/lib/domain/models/Correction.js
  api/lib/domain/usecases/get-correction-for-answer-when-assessment-ended.js
  api/lib/infrastructure/datasources/airtable/objects/Skill.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/tests/acceptance/application/corrections/correction-controller_test.js
  api/tests/fixtures/infrastructure/challengeAirtableDataObjectFixture.js
  api/tests/fixtures/infrastructure/skillAirtableDataObjectFixture.js
  api/tests/fixtures/infrastructure/skillRawAirTableFixture.js
  api/tests/fixtures/infrastructure/tutorialAirtableDataObjectFixture.js
  api/tests/integration/application/corrections/index_test.js
  api/tests/unit/application/corrections/corrections-controller_test.js
  api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
  live/app/components/comparison-window.js
  live/app/components/learning-more-panel.js
  live/app/components/tutorial-panel.js
  live/app/models/answer.js
  live/app/models/correction.js
  live/app/models/tutorial.js
  live/app/styles/app.scss
  live/app/styles/components/_comparison-window.scss
  live/app/styles/components/_learning-more-tutorial-panel.scss
  live/app/styles/components/_qcu-solution-panel.scss
  live/app/styles/components/_tutorial-panel.scss
  live/app/styles/globals/_pix-modale.scss
  live/app/templates/components/comparison-window.hbs
  live/app/templates/components/learning-more-panel.hbs
  live/app/templates/components/tutorial-panel.hbs
  live/tests/integration/components/comparison-window-test.js
  live/tests/integration/components/learning-more-panel-test.js
  live/tests/integration/components/tutorial-panel-test.js
  live/tests/unit/components/comparison-window-test.js
  live/tests/unit/components/tutorial-panel-test.js
  live/tests/unit/models/answer-test.js
  live/tests/unit/models/correction-test.js
Labels: [Func] Review asked, [Tech] Changes validated

#135 [#135] [BUGFIX] Fix certification start (PF-295)
  api/lib/infrastructure/repositories/assessment-repository.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/unit/infrastructure/repositories/assessment-repository_test.js
Labels: [Func] Review asked, [Tech] Review asked

#138 [#138] [FEATURE] Afficher le nom de l'organisation courante dans le menu de Pix-Orga (PO-116).
  api/lib/application/metrics/index.js
  api/lib/application/simulateErrors/index.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/usecases/get-user-with-organization-accesses.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-accesses-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/users-controller-get-organization-accesses_test.js
  api/tests/acceptance/application/users/users-controller-get-user_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/factory/build-user.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/create-campaign_test.js
  api/tests/unit/domain/usecases/get-user-with-organizations-accesses_test.js
  api/tests/unit/domain/usecases/get-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-accesses-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
Labels: [Func] Review asked, [Tech] Review asked

#145 [#145] [BUGFIX] Affichage de la page "Oups" pour les code erreurs API autre que 401 (PF-302)
  live/app/routes/application.js
  live/app/routes/error.js
  live/tests/acceptance/error-redirection-test.js
  live/tests/unit/routes/application-test.js
  live/tests/unit/routes/error-test.js
Labels: [Func] Review asked, [Tech] Review asked

#141 [#141] [BUGFIX] Création d'un script pour un recalcul massif des certifications (pf-296).
  api/db/batchTreatment.js
  api/scripts/recompute-assessment-results.js
  api/tests/unit/scripts/recompute-assessment-results_test.js
Labels: [Func] Review asked, [Tech] Review asked

#144 [#144] [FEATURE] Ajouter le champ "Publié" pour le résultat d'une certification (PF-300).
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/factory/build-certification-course.js
  api/tests/factory/index.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#142 [TECH] Ajout d'un script de génération de UML
  api/lib/domain/models/Campaign.js
  api/lib/domain/models/SkillReview.js
  api/scripts/generate_uml.rb
Labels: [Tech] Review asked
