Repository 1024pix/pix, pull requests merged in 2019-07, with the labels that each got.

#578 [BUGFIX] Nettoyage des données dans la DB. Puis plus de doublon dans Campaign-participation. (PF-702)
  api/db/migrations/20190626111900_add_campaign_participation_unique_constraint_on_user_and_campaign.js
Labels: Func Review Needed, Tech Review Asked

#573 [BUGFIX] Vider et replier le feedback_panel après avoir envoyé le commentaire. (PF-708)
  mon-pix/app/components/feedback-panel.js
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/feedback-panel.hbs
  mon-pix/tests/integration/components/feedback-panel-test.js
  mon-pix/tests/unit/components/feedback-panel-test.js
Labels: Func Review OK, Tech Review Asked

#584 [FEATURE] Assigner le rôle Responsable au premier membre d'une organisation, Membre aux autres. (PA-95)
  admin/app/components/organization-members-section.js
  admin/app/models/membership.js
  admin/app/models/organization-role.js
  admin/mirage/serializers/membership.js
  admin/tests/acceptance/organization-memberships-management-test.js
  admin/tests/unit/models/organization-role-test.js
  api/db/migrations/20180528152339_create_table_organizations_roles.js
  api/db/migrations/20190626102247_remove_organizationRoleId_column.js
  api/db/migrations/20190626111254_remove_organization_roles_table.js
  api/db/migrations/20190628140740_add_MEMBER_role_to_memberships.js
  api/db/seeds/data/dragon-and-co-builder.js
  api/db/seeds/data/organizations-builder.js
  api/lib/domain/models/Membership.js
  api/lib/domain/models/OrganizationRole.js
  api/lib/domain/usecases/create-membership.js
  api/lib/infrastructure/data/membership.js
  api/lib/infrastructure/data/organization-role.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/membership-serializer.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-memberships_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-membership.js
  api/tests/tooling/database-builder/factory/build-organization-role.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-membership.js
  api/tests/tooling/domain-builder/factory/build-organization-role.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/usecases/create-membership_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
Labels: Func Review OK, Tech Review Finished

#589 [BUGFIX] Sortir les résultats collectifs avec les bonnes statistiques (PO-214).
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository-test.js
Labels: Func Review Needed, Tech Review Finished

#563 [TECH] Supprime la bascule FT_USE_ONLY_V1_CERTIFICATION
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/settings.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Ready to Merge, Tech Review Finished

#588 [BUGFIX] parsing des externalId dans l'export des résultats d'une certif (PA-97).
  admin/app/services/session-info-service.js
  admin/tests/unit/services/session-info-service-test.js
Labels: Func Review OK, Tech Review Asked

#601 [BUGFIX] Corrige le démarrage des certifications
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Func Review OK

#559 [TECH] Supprime la méthtode inutile mail-service#sendWelcomeEmail
  api/lib/domain/services/mail-service.js
  api/tests/unit/domain/services/mail-service_test.js
Labels: Ready to Merge, Tech Review Finished

#604 [FEATURE] Afficher le code campagne dans Pix Orga (PO-213)
  orga/app/styles/pages/authenticated/campaigns/details.scss
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/tests/integration/components/routes/authenticated/campaigns/details-item-test.js
Labels: Func Review OK, Tech Review Asked

#598 [FEATURE] Mise en place de Matomo Tag Manager pour les applications front.
  admin/app/router.js
  admin/config/environment.js
  admin/package-lock.json
  admin/package.json
  certif/app/router.js
  certif/config/environment.js
  certif/package-lock.json
  certif/package.json
  mon-pix/app/router.js
  mon-pix/config/environment.js
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/app/router.js
  orga/config/environment.js
  orga/package-lock.json
  orga/package.json
Labels: Func Review Needed, Tech Review Asked

#602 [FEATURE] Affichage de la liste des membres dans PIX Orga (PO-99).
  api/lib/application/organizations/index.js
  api/lib/application/usecases/checkUserIsOwnerInOrganization.js
  api/lib/domain/models/Membership.js
  api/lib/domain/usecases/create-membership.js
  api/lib/domain/usecases/get-organization-memberships.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/membership-serializer.js
  api/lib/interfaces/controllers/security-controller.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-memberships_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/usecases/checkUserIsOwnerInOrganization_test.js
  api/tests/unit/domain/usecases/get-organization-memberships_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
  api/tests/unit/interfaces/controllers/security-controller_test.js
  orga/app/components/sidebar-menu.js
  orga/app/controllers/authenticated/campaigns/new.js
  orga/app/controllers/authenticated/terms-of-service.js
  orga/app/models/membership.js
  orga/app/models/organization.js
  orga/app/router.js
  orga/app/routes/application.js
  orga/app/routes/authenticated.js
  orga/app/routes/authenticated/campaigns/list.js
  orga/app/routes/authenticated/campaigns/new.js
  orga/app/routes/authenticated/index.js
  orga/app/routes/authenticated/team.js
  orga/app/routes/authenticated/team/list.js
  orga/app/routes/authenticated/terms-of-service.js
  orga/app/services/current-organization.js
  orga/app/services/current-user.js
  orga/app/styles/app.scss
  orga/app/styles/components/sidebar-menu.scss
  orga/app/styles/globals/colors.scss
  orga/app/styles/pages/authenticated/team.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/templates/authenticated.hbs
  orga/app/templates/authenticated/team.hbs
  orga/app/templates/authenticated/team/list.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/app/templates/components/routes/authenticated/team/list-items.hbs
  orga/app/templates/components/sidebar-menu.hbs
  orga/tests/acceptance/authentication-test.js
  orga/tests/acceptance/campaign-details-test.js
  orga/tests/acceptance/campaign-list-test.js
  orga/tests/acceptance/team-list-test.js
  orga/tests/acceptance/terms-of-service-test.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/routes/authenticated/team/list-items-test.js
  orga/tests/unit/routes/application-test.js
  orga/tests/unit/routes/authenticated/team-test.js
  orga/tests/unit/routes/authenticated/team/list-test.js
  orga/tests/unit/services/current-organization-test.js
  orga/tests/unit/services/current-user-test.js
Labels: Ready to Merge

#606 [BUGFIX] PixOrga ne fonctionne plus sous IE11 (PO-221).
  orga/app/styles/pages/authenticated/team/list.scss
  orga/ember-cli-build.js
Labels: Func Review OK, Tech Review Asked

#605 [FEATURE] Possibilité pour le responsable d'une organisation d'ajouter d'autres membres (PO-80).
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/add-organization-membership-with-email.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/unit/domain/usecases/add-organization-membership-with-email_test.js
  api/tests/unit/domain/usecases/create-membership_test.js
  orga/app/adapters/application.js
  orga/app/adapters/membership.js
  orga/app/components/routes/authenticated/team/new-item.js
  orga/app/controllers/authenticated/campaigns/new.js
  orga/app/controllers/authenticated/team/new.js
  orga/app/router.js
  orga/app/routes/authenticated/team.js
  orga/app/routes/authenticated/team/list.js
  orga/app/routes/authenticated/team/new.js
  orga/app/styles/app.scss
  orga/app/styles/globals/colors.scss
  orga/app/styles/globals/errors.scss
  orga/app/styles/globals/forms.scss
  orga/app/styles/pages/authenticated/campaigns.scss
  orga/app/styles/pages/authenticated/campaigns/new.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/styles/pages/authenticated/team/new.scss
  orga/app/templates/authenticated/campaigns/new.hbs
  orga/app/templates/authenticated/team/new.hbs
  orga/app/templates/components/blue-link.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
  orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/no-campaign-panel.hbs
  orga/app/templates/components/routes/authenticated/campaigns/update-item.hbs
  orga/app/templates/components/routes/authenticated/team/list-items.hbs
  orga/app/templates/components/routes/authenticated/team/new-item.hbs
  orga/app/templates/style-guide.hbs
  orga/config/environment.js
  orga/mirage/config.js
  orga/mirage/serializers/organization.js
  orga/tests/acceptance/campaign-creation-test.js
  orga/tests/acceptance/team-creation-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/new-item-test.js
  orga/tests/integration/components/routes/authenticated/team/new-item-test.js
  orga/tests/unit/routes/authenticated/team/new-test.js
Labels: Ready to Merge

#590 [TECH] Ajout d'une colonne pour savoir si l'utilisateur a été migré ou non.
  api/db/migrations/20190709160455_add_column_to_remember_migration_to_user.js
Labels: Tech Review Asked

#611 [FEATURE] Création des nouveaux comptes en profil v2 (PF-741).
  api/lib/application/answers/answer-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/get-current-user.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/acceptance/application/users/users-controller-get-user_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  api/tests/unit/domain/usecases/get-current-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/models/user.js
  mon-pix/app/routes/compte.js
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/templates/profilv2.hbs
  mon-pix/mirage/routes/post-authentications.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/acceptance/compte-authentication-and-profile-test.js
  mon-pix/tests/acceptance/profilv2-test.js
  mon-pix/tests/helpers/testing.js
Labels: Func Review OK, Tech Review Asked

#609 [FEATURE] Création de la page /campagnes permettant de rentrer un code Campagne (PF-639).
  mon-pix/app/controllers/campaigns/fill-in-campaign-code.js
  mon-pix/app/router.js
  mon-pix/app/routes/campaigns/fill-in-campaign-code.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/globals/_fonts.scss
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/start-campaigns-test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-campaign-code-test.js
Labels: Ready to Merge

#616 [TECH] Supprimer les fichiers profile-v2 oubliés.
  high-level-tests/e2e/cypress/support/step_definitions/profile.js
  mon-pix/app/controllers/profile-v2.js
  mon-pix/app/routes/profile-v2.js
  mon-pix/app/styles/pages/_profile-v2.scss
  mon-pix/app/templates/profile-v2.hbs
  mon-pix/tests/acceptance/profile-v2-test.js
  mon-pix/tests/unit/routes/profile-v2-test.js
Labels: Tech Review Asked

#620 [FEATURE] Optimisation graphique du bandeau de nouveau profil. (PF-772)
  mon-pix/app/components/signup-form.js
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/globals/_palette.scss
  mon-pix/app/styles/pages/_profile.scss
  mon-pix/app/templates/profile.hbs
  mon-pix/tests/integration/components/signup-form-test.js
Labels: Func Review Needed, Tech Review Asked

#621 [FEATURE] Ajouter des identifiants externes aux Organisations. (PA-83)
  admin/app/components/organization-members-section.js
  admin/app/models/organization.js
  admin/app/styles/authenticated/organizations/get.scss
  admin/app/templates/components/organization-information-section.hbs
  admin/tests/acceptance/organization-memberships-management-test.js
  api/db/migrations/20190719152419_add_column_externalId_to_organizations.js
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: Func Review OK

#624 [BUGFIX] Problème d'affichage des détails d'une compétence sous IE (PF-775).
  mon-pix/app/styles/components/_scorecard-details.scss
Labels: Func Review OK

#623 [TECH] Rendre les identifiants de templates Mailjet configurables
  api/lib/domain/services/mail-service.js
  api/lib/settings.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/domain/services/mail-service_test.js
Labels: Func Review Needed, Tech Review Asked

#531 [TECH] Migration des données de V1 vers V2.
  api/scripts/extract-challenge-with-skills.js
  api/scripts/migrate-v1-to-v2.js
Labels: Tech Review Asked

#614 [FEATURE] Limiter visuellement le nombre de Pix maximum pouvant être gagnés actuellement (PF-767).
  api/lib/domain/constants.js
  api/lib/domain/models/Scorecard.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/get-user-scorecards.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/get-user-scorecards_test.js
Labels: Func Review OK, Tech Review Asked

#613 [FEATURE] Recalculer le score des certifications V2 dans un état inconsistent (PF-646).
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/usecases/create-assessment-result-for-completed-assessment.js
  api/scripts/compute-missing-certifv2-scores/bin.js
  api/scripts/compute-missing-certifv2-scores/compute-missing-certifv2-scores.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/scripts/compute-missing-certifv2-scores/compute-missing-certifv2-scores_test.js
Labels: Tech Review Asked, 🌟Etoile
