Repository 1024pix/pix, pull requests merged in 2019-03, with the labels that each got.

#389 [TECH] Mise à jour de Pix admin vers Node 10.15.1
  admin/package.json
  api/scripts/get-changelog.js
  api/tests/unit/scripts/get-changelog_test.js
  package-lock.json
  package.json
  scripts/release/get-pull-requests-to-release-in-prod.js
  scripts/release/prepare.sh
  scripts/release/publish.sh
  scripts/tests/get-pull-requests-to-release-in-prod_test.js
Labels: Ready to Merge

#391 [TECH] Ajouter des colonnes userId et competenceId à la table Knowledge-elements (PF-521).
  api/db/migrations/20190301111215_add_column_user_id_to_knowledge_elements.js
  api/db/migrations/20190301111229_add_column_competence_to_knowlege_elements.js
  api/db/migrations/20190301152021_remove_pix_score_column_of_knowledge_elements.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/SmartPlacementKnowledgeElement.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/infrastructure/adapters/skill-adapter.js
  api/lib/infrastructure/data/knowledge-element.js
  api/lib/infrastructure/datasources/airtable/objects/Skill.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/tests/acceptance/application/corrections/correction-controller_test.js
  api/tests/integration/infrastructure/repositories/smart-placement-knowledge-element-repository_test.js
  api/tests/tooling/database-builder/factory/build-smart-placement-knowledge-element.js
  api/tests/tooling/domain-builder/factory/build-skill-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/build-smart-placement-knowledge-element.js
  api/tests/tooling/fixtures/infrastructure/skillAirtableDataObjectFixture.js
  api/tests/unit/domain/models/SmartPlacementKnowledgeElement_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  api/tests/unit/infrastructure/adapters/skill-adapter_test.js
  api/tests/unit/infrastructure/adapters/target-profile-adapter_test.js
  api/tests/unit/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/infrastructure/repositories/skill-repository_test.js
Labels: Ready to Merge

#382 [BSR] Answer controller - Answer repository
  api/lib/application/answers/answer-controller.js
  api/lib/domain/services/solution-service.js
  api/lib/infrastructure/adapters/answer-status-database-adapter.js
  api/lib/infrastructure/data/answer.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/lib/infrastructure/serializers/jsonapi/answer-serializer.js
  api/tests/acceptance/application/answers/answer-controller-update_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/unit/application/answers/answer-controller_test.js
  api/tests/unit/infrastructure/models/answer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/answer-serializer_test.js
Labels: Ready to Merge

#388 [TECH] Remplacement d'une longue chaîne de promesses par async/await
  api/lib/application/snapshots/snapshot-controller.js
Labels: Ready to Merge

#392 [TECH] Remove unused `seed.js` file
  api/db/seeds/data/seed.js
Labels: Ready to Merge

#390 [FEATURE] Changement de wording sur les pages et email du changement de mot de passe (PF-497)
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_password-reset-demand-form.scss
  mon-pix/app/styles/components/_signin-form.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/app/templates/components/reset-password-form.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/acceptance/password-reset-test.js
  mon-pix/tests/integration/components/password-reset-demand-form-test.js
  mon-pix/tests/integration/components/reset-password-form-test.js
  mon-pix/tests/integration/components/signin-form-test.js
  mon-pix/tests/integration/components/signup-form-test.js
Labels: Ready to Merge, Tech Review Finished

#395 [BUGFIX] Mise à jour de la barre de progression au bon moment (PF-508).
  mon-pix/app/components/progress-bar.js
  mon-pix/app/models/answer.js
  mon-pix/app/models/assessment.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/tests/unit/components/progress-bar-test.js
Labels: Tech Review Finished

#404 [TECH] Supprimer ember-table de Pix Certif (PF-534).
  certif/app/components/routes/authenticated/sessions/list-items.js
  certif/app/styles/globals/tables.scss
  certif/app/styles/globals/texts.scss
  certif/app/templates/components/routes/authenticated/sessions/list-items.hbs
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-list-test.js
  certif/tests/integration/components/routes/authenticated/sessions/list-items-test.js
Labels: Ready to Merge

#407 [BUGFIX] Fix bugs affichage réinitialisation mot de passe sous IE
  mon-pix/app/styles/components/_password-reset-demand-form.scss
  mon-pix/app/styles/pages/_sign-form.scss
Labels: FUNC REVIEW ASKED, TECH REVIEW ASKED

#402 [FEATURE] Ajout d'une page de détails d'un participant à une campagne. (PO-190)
  api/lib/application/campaignParticipationResults/campaign-participation-result-controller.js
  api/lib/application/campaignParticipationResults/index.js
  api/lib/application/campaignParticipations/campaign-participation-controller.js
  api/lib/application/campaignParticipations/index.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/domain/usecases/get-campaign-participation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/lib/infrastructure/utils/query-builder.js
  api/lib/routes.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/acceptance/application/users/users-get-campaign-participations_test.js
  api/tests/integration/infrastructure/utils/query-builder_test.js
  api/tests/tooling/database-builder/factory/build-campaign-participation.js
  api/tests/unit/application/campaignParticipationResult/campaign-participation-result_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
  api/tests/unit/domain/usecases/get-campaign-participation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  orga/app/components/routes/authenticated/campaigns/details/participants-tab.js
  orga/app/controllers/authenticated/campaigns/details/participants.js
  orga/app/models/campaign-participation-result.js
  orga/app/models/campaign-participation.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/details/participants.js
  orga/app/routes/authenticated/campaigns/details/participants/results.js
  orga/app/styles/app.scss
  orga/app/styles/globals/colors.scss
  orga/app/styles/globals/panels.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/campaigns/details/participant-results.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants.scss
  orga/app/templates/authenticated/campaigns/details/participants.hbs
  orga/app/templates/authenticated/campaigns/details/participants/results.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/participants-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs
  orga/config/environment.js
  orga/mirage/config.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/participant-results-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/participants-tab-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/participant-results-test.js
Labels: FUNC REVIEW ASKED, Tech Review Finished

#403 [FEATURE] Nouvelle page profil V2 qui présente le score des parcours ciblés (PF-371)
  mon-pix/app/components/hexagon-score.js
  mon-pix/app/router.js
  mon-pix/app/routes/profilv2.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_checkpoint.scss
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/app/styles/components/_navbar-header.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/globals/_palette.scss
  mon-pix/app/styles/pages/_campaign-tutorial.scss
  mon-pix/app/styles/pages/_profilv2.scss
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/components/hexagon-score.hbs
  mon-pix/app/templates/profilv2.hbs
  mon-pix/public/images/hexa-pix-blue.svg
  mon-pix/tests/acceptance/profilv2-test.js
  mon-pix/tests/integration/components/hexagon-score-test.js
  mon-pix/tests/unit/routes/profilv2-test.js
Labels: FUNC REVIEW ASKED, TECH REVIEW ASKED

#409 [FEATURE] Affichage du lieu de naissance sur le certificat (PF-230).
  api/lib/domain/models/Certification.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/acceptance/application/certification-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-with-competence-tree.js
  api/tests/tooling/domain-builder/factory/build-certification.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  mon-pix/app/models/certification.js
  mon-pix/app/templates/components/user-certifications-detail-header.hbs
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/integration/components/user-certifications-detail-header-test.js
Labels: Ready to Merge

#412 [BUGFIX] Affiche correctement les résultats d'un participant d'une campagne.
  orga/app/models/campaign-participation-result.js
  orga/tests/unit/models/campaign-participation-result-test.js
Labels: TECH REVIEW ASKED

#417 [FEATURE] Téléchargement du PV de session
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/files/attendance_sheet_template.ods
  api/lib/domain/services/ods-service.js
  api/lib/domain/services/xml-service.js
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/session-repository.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/session-controller_test.js
  api/tests/integration/domain/services/ods-service/ods-service_test.js
  api/tests/integration/domain/services/ods-service/testFile.ods
  api/tests/integration/domain/services/xml-service_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/domain/usecases/get-attendance-sheet_test.js
  certif/app/models/session.js
  certif/app/routes/authenticated/sessions/details.js
  certif/app/styles/globals/colors.scss
  certif/app/styles/globals/panels.scss
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/components/routes/authenticated/sessions/details-item.hbs
  certif/tests/integration/components/routes/authenticated/sessions/details-item-test.js
Labels: FUNC REVIEW ASKED

#420 Tech update tests for pg
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/infrastructure/repositories/assessment-repository_test.js
Labels: TECH REVIEW ASKED

#422 Affichage des résultats détaillés sur la page de fin de parcours (PF-543-2).
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  mon-pix/app/adapters/application.js
  mon-pix/app/adapters/challenge.js
  mon-pix/app/adapters/correction.js
  mon-pix/app/models/campaign-participation-result.js
  mon-pix/app/models/campaign-participation.js
  mon-pix/app/models/competence-result.js
  mon-pix/app/models/smart-placement-progression.js
  mon-pix/app/static-data/domain-colors.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_checkpoint.scss
  mon-pix/app/styles/components/_circle-chart.scss
  mon-pix/app/styles/components/_progression-gauge.scss
  mon-pix/app/styles/globals/_checkpoint-progress-bar.scss
  mon-pix/app/styles/globals/_tables.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/app/templates/components/circle-chart.hbs
  mon-pix/app/templates/components/progression-gauge.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/factories/smart-placement-progression.js
  mon-pix/mirage/routes/get-campaign-participation-result.js
  mon-pix/mirage/serializers/campaign-participation-result.js
  mon-pix/mirage/serializers/campaign-participation.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/integration/components/circle-chart-test.js
  mon-pix/tests/integration/components/progression-gauge-test.js
  mon-pix/tests/unit/adapters/application-test.js
  mon-pix/tests/unit/models/campaign-participation-result-test.js
  mon-pix/tests/unit/models/competence-result-test.js
  mon-pix/tests/unit/models/smart-placement-progression-test.js
Labels: Ready to Merge, 🌟🌟SPRINT STAR🌟🌟

#424 Add db:docker script
  api/scripts/database/create-database.js
  api/scripts/database/drop-database.js
  api/scripts/database/empty-database.js
  docker-compose.yml
Labels: Tech Review Finished

#428 [TECH] DatabaseBuilder: reverse the deletion order
  api/package.json
  api/tests/tooling/database-builder/database-builder.js
Labels: TECH REVIEW ASKED

#426 [BUGFIX] Correction de l'affichage du pourcentage dans le cercle de progression sous IE (PF-552).
  mon-pix/app/components/circle-chart.js
  mon-pix/app/styles/components/_circle-chart.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/skill-review.hbs
Labels: Ready to Merge

#429 [BUGFIX] Afficher le bon message coté front quand l'utilisateur n'a pas partagé sa campagne (PF-541).
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/users/users-get-campaign-participations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  mon-pix/app/routes/compte.js
Labels: FUNC REVIEW ASKED, TECH REVIEW ASKED

#434 [BUGFIX] Suppression du namespace `/api` dans Pix Admin.
  admin/app/adapters/application.js
  admin/app/adapters/certification-details.js
  admin/app/adapters/certification.js
  admin/config/environment.js
  admin/mirage/config.js
  admin/mirage/serializers/organization.js
Labels: EXPEDIT, Ready to Merge

#433 [FEATURE] Ajout des CGUs sur Pix Certif (PC-11).
  certif/app/templates/authenticated/terms-of-service.hbs
Labels: Ready to Merge

#432 [BUGFIX] Ne pas garder en mémoire les réponses dont l'enregistrement a échoué (PF-555)
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/tests/unit/routes/assessments/challenge-test.js
Labels: Ready to Merge

#435 [BUGFIX] Affiche 100% d'avancement quoiqu'il arrive sur le dernier checkpoint. (PF-542)
  mon-pix/app/controllers/assessments/checkpoint.js
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/tests/unit/controllers/assessments/checkpoint-test.js
Labels: Ready to Merge
