Repository 1024pix/pix, pull requests merged in 2019-04, with the labels that each got.

#436 [BUGFIX] Les tableaux dans les épreuves ne s'affichent plus correctement
  mon-pix/app/styles/globals/_tables.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/skill-review.hbs
Labels: FUNC REVIEW ASKED

#418 [FEATURE] Calculer le Pix Score global de l'utilisateur à afficher dans le profil v2 (PF-537).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/get-user-pix-score.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/smart-placement-knowledge-element-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/pix-score-serializer.js
  api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/users-controller-get-pix-score_test.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/acceptance/application/users/users-controller-get-user_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/integration/infrastructure/repositories/smart-placement-knowledge-element-repository_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-user-pix-score_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  docker-compose.yml
  mon-pix/app/components/hexagon-score.js
  mon-pix/app/models/pix-score.js
  mon-pix/app/models/user.js
  mon-pix/app/templates/profilv2.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/get-pix-score.js
  mon-pix/mirage/serializers/user.js
  mon-pix/package.json
  mon-pix/tests/acceptance/profilv2-test.js
Labels: Ready to Merge

#441 [TECH] Add keyword spacing to linter
  .eslintrc
  api/lib/application/saml/saml-controller.js
  api/lib/cat/course.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/Course.js
  api/lib/domain/models/Tube.js
  api/lib/domain/services/profile-completion-service.js
  api/lib/domain/services/session-service.js
  api/lib/domain/services/smart-random/challengesFilter.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/create-assessment-for-campaign.js
  api/lib/domain/usecases/create-session.js
  api/lib/domain/usecases/create-user.js
  api/lib/domain/usecases/find-certification-assessments.js
  api/lib/domain/usecases/find-placement-assessments.js
  api/lib/domain/usecases/find-sessions-for-certification-center.js
  api/lib/domain/usecases/find-smart-placement-assessments.js
  api/lib/domain/usecases/get-assessment.js
  api/lib/domain/usecases/get-campaign-by-code.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/domain/usecases/get-campaign-participation.js
  api/lib/domain/usecases/get-results-campaign-in-csv-format.js
  api/lib/domain/usecases/get-smart-placement-progression.js
  api/lib/domain/usecases/get-user-campaign-participation.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/domain/usecases/start-placement-assessment.js
  api/lib/domain/validators/campaign-validator.js
  api/lib/domain/validators/organization-creation-validator.js
  api/lib/domain/validators/user-validator.js
  api/lib/infrastructure/adapters/assessment-adapter.js
  api/lib/infrastructure/adapters/target-profile-adapter.js
  api/lib/infrastructure/caches/redis-cache.js
  api/lib/infrastructure/datasources/airtable/objects/Challenge.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/serializers/jsonapi/validation-error-serializer.js
  api/lib/infrastructure/validators/grecaptcha-validator.js
  api/tests/unit/domain/usecases/create-assessment-result-for-completed-assessment_test.js
  certif/package.json
  mon-pix/app/components/certification-results-page.js
  mon-pix/app/components/challenge-actions.js
  mon-pix/app/components/feedback-panel.js
  mon-pix/app/components/g-recaptcha.js
  mon-pix/app/components/resume-campaign-banner.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/skill-review.js
  mon-pix/app/routes/index.js
  mon-pix/app/routes/logout.js
  mon-pix/mirage/routes/post-assessments.js
  orga/package.json
Labels: TECH REVIEW ASKED

#445 [FEATURE] Renommage de surveillant en surveillant(s) (PC-44).
  certif/app/templates/components/routes/authenticated/sessions/details-item.hbs
  certif/app/templates/components/routes/authenticated/sessions/list-items.hbs
  certif/app/templates/components/routes/authenticated/sessions/new-item.hbs
  certif/app/templates/components/routes/authenticated/sessions/update-item.hbs
Labels: Ready to Merge

#253 [TECH] Ajouter Cypress en CI.
  .circleci/config.yml
  high-level-tests/e2e/cypress/integration/demo.feature
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
Labels: TECH REVIEW ASKED

#419 [FEATURE] Afficher les niveaux par compétence sur le Profil V2 de l'utilisateur (scorecard) (PF-537).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/get-user-scorecards.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
  api/lib/infrastructure/serializers/jsonapi/scorecard-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js
  api/tests/acceptance/application/users/users-controller-get-user_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/integration/infrastructure/repositories/smart-placement-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/smart-placement-knowledge-element-repository_test.js
  api/tests/tooling/domain-builder/factory/build-user-scorecard.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-user-scorecards_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/scorecard-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/models/scorecard.js
  mon-pix/app/models/user.js
  mon-pix/app/routes/profilv2.js
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/pages/_profilv2.scss
  mon-pix/app/templates/profilv2.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/fixtures/areas.js
  mon-pix/mirage/routes/get-scorecards.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/mirage/serializers/scorecard.js
  mon-pix/mirage/serializers/user.js
  mon-pix/tests/acceptance/profilv2-test.js
  mon-pix/tests/unit/models/scorecard-test.js
Labels: FUNC REVIEW ASKED, TECH REVIEW ASKED

#413 [TECH] Enrichissement du CONTRIBUTING.md sur la base de PF-371 > PF-536
  docs/CONTRIBUTING.md
Labels: TECH REVIEW ASKED

#439 [FEATURE] Affichage du profilV2 avec les cartes de couleur (PF-522).
  mon-pix/app/components/competence-card.js
  mon-pix/app/models/competence-result.js
  mon-pix/app/models/scorecard.js
  mon-pix/app/models/user.js
  mon-pix/app/static-data/area-colors.js
  mon-pix/app/static-data/domain-colors.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_circle-chart.scss
  mon-pix/app/styles/components/_competence-card.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/globals/_palette.scss
  mon-pix/app/styles/pages/_campaign-tutorial.scss
  mon-pix/app/styles/pages/_profilv2.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/app/templates/components/circle-chart.hbs
  mon-pix/app/templates/components/competence-card.hbs
  mon-pix/app/templates/profilv2.hbs
  mon-pix/mirage/fixtures/areas.js
  mon-pix/mirage/routes/get-scorecards.js
  mon-pix/tests/acceptance/profilv2-test.js
  mon-pix/tests/integration/components/circle-chart-test.js
  mon-pix/tests/integration/components/competence-card-test.js
  mon-pix/tests/unit/components/competence-card-test.js
  mon-pix/tests/unit/models/competence-result-test.js
  mon-pix/tests/unit/models/user-test.js
Labels: Ready to Merge

#446 [BUGFIX] En tant que user, je veux pouvoir appuyer sur "Entrée" pour valider une réponse d'un parcours (PF-566)
  mon-pix/app/components/challenge-actions.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/tests/integration/components/challenge-actions-test.js
Labels: TECH REVIEW ASKED

#450 [TECH] Dispatch d'un CustomEvent au lancement d'un Embed (PF-567)
  mon-pix/app/components/challenge-embed-simulator.js
Labels: TECH REVIEW ASKED

#455 [FEATURE] Scroll automatiquement en haut de page après une transition. (PF-550)
  mon-pix/app/router.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/routes/assessments/results.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/routes/base-route.js
  mon-pix/app/routes/board.js
  mon-pix/app/routes/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/skill-review.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/campaigns/tutorial.js
  mon-pix/app/routes/certifications/results.js
  mon-pix/app/routes/certifications/resume.js
  mon-pix/app/routes/challenge-preview.js
  mon-pix/app/routes/compte.js
  mon-pix/app/routes/courses/create-assessment.js
  mon-pix/app/routes/index.js
  mon-pix/app/routes/inscription.js
  mon-pix/app/routes/login.js
  mon-pix/app/routes/logout.js
  mon-pix/app/routes/not-connected.js
  mon-pix/app/routes/password-reset-demand.js
  mon-pix/app/routes/profilv2.js
  mon-pix/app/routes/reset-password.js
  mon-pix/app/routes/user-certifications/get.js
  mon-pix/app/routes/user-certifications/index.js
Labels: FUNC REVIEW ASKED, TECH REVIEW ASKED

#452 [TECH] Ajout d'un fichier de documentation d'une lib sous forme de tests unitaires
  api/tests/docs/jsonapi-serializer.test.js
Labels: TECH REVIEW ASKED

#460 [TECH] Suppression de delay service et de call-only-once
  mon-pix/app/services/delay.js
  mon-pix/app/utils/call-only-once.js
  mon-pix/config/environment.js
  mon-pix/tests/unit/services/delay-test.js
Labels: TECH REVIEW ASKED

#444 [TECH] Empêcher la redirection vers pix.fr quand on n'est pas en production
  mon-pix/config/environment.js
Labels: TECH REVIEW ASKED

#438 [BSR] Réécriture du serializer d'assessment.
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/models/Assessment.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/integration/application/assessments/assessment-controller_test.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
Labels: TECH REVIEW ASKED

#458 Fix a few integration tests on PG
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/utils/query-builder_test.js
Labels: Tech Review Finished

#456 [FEATURE] Ajout de la bannière "Reprendre la campagne" sur profilv2 (PF-544)
  high-level-tests/e2e/cypress/fixtures/target-profiles_skills.json
  high-level-tests/e2e/cypress/integration/demo.feature
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  mon-pix/app/models/campaign-participation.js
  mon-pix/app/routes/profilv2.js
  mon-pix/app/templates/profilv2.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/get-user-campaign-participations.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/mirage/serializers/campaign-participation.js
  mon-pix/mirage/serializers/user.js
  mon-pix/tests/acceptance/profilv2-test.js
Labels: Ready to Merge

#466 [BUGFIX] Filtrage des campaign-participation-results par le sharedAt de la campaign-participation.
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
Labels: Funk Review Needed, Tech Review Asked

#459 [TECH] Ajout d'un mécanisme pour les épreuves intégrant un simulateur (embed) permettant d'indiquer à l'iframe quand l'utilisateur lance le simulateur.
  mon-pix/app/components/challenge-embed-simulator.js
Labels: Tech Review Asked

#463 [BUGFIX] Corriger les problèmes de styles sur le document de PV de session (PC-41).
  api/lib/domain/files/attendance_sheet_template.ods
Labels: Tech Review Asked

#469 [BSR] Réécriture du serializer d'assessment.
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/models/Assessment.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/integration/application/assessments/assessment-controller_test.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
Labels: Func Review Needed

#461 [FEATURE] Afficher le nombre de participants et de profils reçus dans la liste des campagnes (PO-86)
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/get-organization-campaigns.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation.js
  api/tests/tooling/domain-builder/factory/build-campaign-report.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/get-organization-campaigns_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  orga/app/components/campaign-item.js
  orga/app/styles/components/campaign-item.scss
  orga/app/templates/components/campaign-item.hbs
  orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js
Labels: Tech Review Asked

#457 [BUGFIX] Correction de l'affichage des détails d'une certification pour une réponse "Abandon" (PA-82).
  api/lib/domain/models/Answer.js
  api/lib/domain/models/AnswerStatus.js
  api/lib/domain/models/Examiner.js
  api/lib/domain/services/solution-service.js
  api/tests/unit/domain/services/certification-service_test.js
  api/tests/unit/infrastructure/adapters/assessment-adapter_test.js
  mon-pix/mirage/fixtures/answers.js
Labels: Ready to Merge

#405 [TECH] Ajout d'un script pour récupérer les answers pour les statistiques.
  api/scripts/extract-answers.sh
Labels: Ready to Merge

#451 [FEATURE] Lier le profil v1 et le profil v2 grâce à un lien cliquable (PF-558).
  mon-pix/app/routes/profilv2.js
  mon-pix/app/styles/components/_results-warning.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/templates/components/results-warning.hbs
  mon-pix/app/templates/profilv2.hbs
  mon-pix/tests/acceptance/home-page-test.js
  mon-pix/tests/acceptance/profilv2-test.js
Labels: Ready to Merge

#449 [TECH] Redesign du dossier docs et du contributing.md
  docs/API.md
  docs/Accessibilite.md
  docs/Bookshelf.md
  docs/CONTRIBUTING.md
  docs/CSS.md
  docs/README.md
  docs/Responsive-Design.md
  docs/Tests.md
  docs/Usecase.md
Labels: Tech Review Asked
