Repository 1024pix/pix, pull requests merged in 2019-06, with the labels that each got.

#537 [TECH] Amélioration du database builder et des tests cassants aléatoirement
  api/db/batchTreatment.js
  api/db/migrations/20170105153948_update_answers_timeout.js
  api/db/migrations/20170329112753_add_elapsedTime_to_answers.js
  api/db/migrations/20170329153349_update_answers--add_column_result_details.js
  api/db/migrations/20170418114929_remove_login_from_users.js
  api/db/migrations/20170703105035_create_link_between_user_and_assessment.js
  api/db/migrations/20170703163243_update_assessment_with_level_and_score.js
  api/db/migrations/20170728141316_add_code_to_organization.js
  api/db/migrations/20171113103608_add_type_to_assessments.js
  api/db/migrations/20171204102525_add_userId_to_certification_course.js
  api/db/migrations/20171212144653_add_status_to_certification_course.js
  api/db/migrations/20180116161332_modify_column_completedPercentage_to_tests_finished_in_snapshots.js
  api/db/migrations/20180306151846_add_type_to_all_assessments.js
  api/db/migrations/20180315164634_add-column-access-code-on-sessions.js
  api/db/migrations/20180315164647_add-column-session-id-on-certifications.js
  api/db/migrations/20180329113849_add-indexes-on-many-tables.js
  api/db/migrations/20180405100452_migrate_assessments_info_to_assessment_results.js
  api/db/migrations/20180405100655_migrate_old_marks_in_competence-marks.js
  api/db/migrations/20180731102046_create_target_profiles_table.js
  api/db/migrations/20181128103517_add_column_create_at_to_knowledge_elements.js
  api/package.json
  api/plop/generators/usecase.js
  api/scripts/database/drop-database.js
  api/scripts/delete-user.js
  api/scripts/fill-score-level.js
  api/scripts/get-results-certifications-old.js
  api/scripts/get-results-certifications.js
  api/scripts/import-certifications-from-csv.js
  api/scripts/make-saml-env.js
  api/scripts/recompute-all-score.js
  api/scripts/reload-cache-everyday.js
  api/tests/acceptance/application/assessments/assessment-controller-post_test.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/test-helper.js
  api/tests/tooling/database-builder/database-buffer.js
  api/tests/tooling/database-builder/database-builder.js
  api/tests/tooling/database-builder/factory/build-answer.js
  api/tests/tooling/database-builder/factory/build-assessment-result.js
  api/tests/tooling/database-builder/factory/build-assessment.js
  api/tests/tooling/database-builder/factory/build-campaign-participation.js
  api/tests/tooling/database-builder/factory/build-campaign.js
  api/tests/tooling/database-builder/factory/build-certification-center-membership.js
  api/tests/tooling/database-builder/factory/build-certification-center.js
  api/tests/tooling/database-builder/factory/build-certification-challenge.js
  api/tests/tooling/database-builder/factory/build-certification-course.js
  api/tests/tooling/database-builder/factory/build-competence-evaluation.js
  api/tests/tooling/database-builder/factory/build-competence-mark.js
  api/tests/tooling/database-builder/factory/build-knowledge-element.js
  api/tests/tooling/database-builder/factory/build-membership.js
  api/tests/tooling/database-builder/factory/build-organization-role.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/database-builder/factory/build-pix-role.js
  api/tests/tooling/database-builder/factory/build-session.js
  api/tests/tooling/database-builder/factory/build-snapshot.js
  api/tests/tooling/database-builder/factory/build-target-profile-share.js
  api/tests/tooling/database-builder/factory/build-target-profile-skill.js
  api/tests/tooling/database-builder/factory/build-target-profile.js
  api/tests/tooling/database-builder/factory/build-user-pix-role.js
  api/tests/tooling/database-builder/factory/build-user.js
Labels: Tech Review Asked

#508 [TECH] Montée de version des applications Ember (3.8 → 3.9).
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  certif/tests/integration/components/routes/authenticated/sessions/update-item-test.js
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/.eslintrc.js
  orga/package-lock.json
  orga/package.json
Labels: Ready to Merge

#534 [FEATURE] Certifier suivant le profil v2 (PF-577).
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/lib/settings.js
  api/scripts/generate-all-profiles-to-certify.js
  api/tests/integration/domain/services/user-service_get-profile-to-certify_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/services/user-service_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Func Review OK, Ready to Merge, Tech Review Finished, 🌟Etoile

#550 [FEATURE] Afficher la version de la certification dans Pix Admin (PF-577).
  admin/app/models/certification.js
  admin/app/templates/authenticated/certifications/single/info.hbs
  api/db/migrations/20190606125500_add_is-v2-certification_column_in_certification-course.js
  api/db/seeds/data/certification-courses-builder.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/tooling/database-builder/factory/build-certification-course.js
  api/tests/tooling/domain-builder/factory/build-certification-course.js
  api/tests/unit/domain/services/certification-service_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
Labels: Func Review OK, Tech Review Asked, 🌟Etoile

#547 [FEATURE] Désactiver l'autocomplétion des QROC et QROCM (PF-627)
  mon-pix/app/templates/components/qroc-proposal.hbs
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/tests/integration/components/qroc-proposal-test.js
  mon-pix/tests/integration/components/qrocm-proposal-test.js
Labels: Func Review OK, Tech Review Asked

#518 [TECH] Refacto sur l'assessment coté front
  mon-pix/app/router.js
  mon-pix/app/routes/assessments.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/routes/assessments/checkpoint.js
  mon-pix/app/routes/assessments/rating.js
  mon-pix/app/routes/assessments/results.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/templates/assessments.hbs
  mon-pix/tests/acceptance/challenge-qcm-test.js
  mon-pix/tests/acceptance/challenge-qcu-test.js
  mon-pix/tests/unit/routes/assessments/challenge-test.js
  mon-pix/tests/unit/routes/assessments/rating-test.js
  mon-pix/tests/unit/routes/assessments/resume-test.js
Labels: Func Review Needed, Tech Review Asked

#546 Supprimer une phrase sur la page de fin de certification (PF-611).
  mon-pix/app/templates/components/certification-results-page.hbs
Labels: Ready to Merge

#549 [BUGFIX] Ajustements sur le CSS pour imprimer la page de résultats d'une campagne (PF-583).
  mon-pix/app/styles/pages/_skill-review.scss
Labels: Func Review OK

#535 [FEATURE] Afficher le nom de la compétence dans un assessement (PF-578).
  api/lib/domain/models/Assessment.js
  api/lib/domain/usecases/get-assessment.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/course-repository.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/domain/usecases/get-assessment_test.js
  api/tests/unit/infrastructure/repositories/competence-repository_test.js
  api/tests/unit/infrastructure/repositories/course-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  mon-pix/app/models/assessment.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/tests/acceptance/challenge-page-banner-test.js
Labels: Func Review OK, Tech Review Asked

#552 [FEATURE] Ajouter des animations CSS sur competence-card (PF-586).
  mon-pix/app/styles/components/_competence-card.scss
  mon-pix/app/styles/globals/_palette.scss
  mon-pix/app/templates/components/competence-card.hbs
Labels: Func Review OK, Tech Review Asked

#554 [TECH] Ajout d'un test cypress pour preview.
  api/lib/domain/usecases/get-assessment.js
  api/tests/unit/domain/usecases/get-assessment_test.js
  high-level-tests/e2e/cypress/fixtures/pix_roles.json
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/fixtures/users_pix_roles.json
  high-level-tests/e2e/cypress/integration/preview.feature
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
Labels: Tech Review Asked

#520 Import certification report
  admin/app/components/certification-info-published.js
  admin/app/components/certification-session-report.js
  admin/app/controllers/authenticated/certifications/sessions/info/list.js
  admin/app/routes/authenticated/certifications/sessions/info/list.js
  admin/app/services/file-reader.js
  admin/app/services/session-info-service.js
  admin/app/styles/app.scss
  admin/app/styles/authenticated/certifications/sessions/info/_list.scss
  admin/app/styles/components/certification-session-report.scss
  admin/app/styles/misc/button.scss
  admin/app/templates/authenticated/certifications/sessions.hbs
  admin/app/templates/authenticated/certifications/sessions/info/list.hbs
  admin/app/templates/components/certification-info-published.hbs
  admin/app/templates/components/certification-session-report.hbs
  admin/app/templates/components/menu-bar.hbs
  admin/ember-cli-build.js
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/certification-session-report-test.js
  admin/tests/unit/components/certification-session-report-test.js
  admin/tests/unit/controllers/authenticated/certifications/sessions/info/list-test.js
  admin/tests/unit/services/file-reader-test.js
  admin/tests/unit/services/session-info-service-test.js
Labels: Func Review OK, Tech Review Asked

#560 [FEATURE] Retouche de la fenêtre pour signaler un problème. (PF-612)
  mon-pix/app/components/feedback-panel.js
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/feedback-panel.hbs
  mon-pix/tests/acceptance/challenge-feedback-test.js
  mon-pix/tests/integration/components/comparison-window-test.js
  mon-pix/tests/integration/components/feedback-panel-test.js
  mon-pix/tests/unit/components/feedback-panel-test.js
Labels: Func Review OK, Tech Review Asked

#557 [FEATURE] Affichage de la moyenne des résultats d'une campagne. (PO-197)
  orga/app/components/routes/authenticated/campaigns/details/collective-results-tab.js
  orga/app/models/campaign-collective-result.js
  orga/app/routes/authenticated/campaigns/details/collective-results.js
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant-results.scss
  orga/app/templates/components/routes/authenticated/campaigns/details/collective-results-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs
  orga/tests/integration/components/routes/authenticated/campaigns/details/participants/results-item-test.js
  orga/tests/unit/models/campaign-collective-results-test.js
Labels: Func Review OK, Tech Review Asked

#565 [TECH] Ajout du role MEMBER dans Pix Admin/Orga (PA-95)
  api/db/migrations/20190621155332_create_member_organization_role.js
Labels: Tech Review Asked

#544 [FEATURE] Possibilité de remettre à zéro une compétence après 7 jours (PF-579-7).
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/organizations-builder.js
  api/db/seeds/data/pix-aile-profilev2-builder.js
  api/db/seeds/seed.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/models/SmartPlacementAssessment.js
  api/lib/domain/services/competence-evaluation-service.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/usecases/create-assessment-result-for-completed-assessment.js
  api/lib/domain/usecases/find-smart-placement-assessments.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/reset-competence-evaluation.js
  api/lib/domain/usecases/reset-scorecard.js
  api/lib/domain/usecases/share-campaign-result.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/competence-evaluation-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/utils/bookshelf-to-domain-converter.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/tooling/database-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/domain/services/competence-evaluation-service_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/create-assessment-result-for-completed-assessment_test.js
  api/tests/unit/domain/usecases/find-smart-placement-assessments_test.js
  api/tests/unit/domain/usecases/get-scorecard_test.js
  api/tests/unit/domain/usecases/reset-scorecard_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
  mon-pix/app/adapters/scorecard.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/scorecard-details.js
  mon-pix/app/controllers/campaigns/skill-review.js
  mon-pix/app/models/assessment.js
  mon-pix/app/models/scorecard.js
  mon-pix/app/styles/components/_competence-card.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/globals/_palette.scss
  mon-pix/app/styles/globals/_pix-modal.scss
  mon-pix/app/templates/components/competence-card.hbs
  mon-pix/app/templates/components/competence-level-progress-bar.hbs
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/app/templates/components/reset-password-form.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/app/templates/components/share-profile.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/config/environment.js
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/reset-scorecard.js
  mon-pix/tests/acceptance/competence-details-test.js
  mon-pix/tests/integration/components/scorecard-details-test.js
Labels: Ready to Merge, 🌟Etoile

#572 [BUGFIX] Affichage des résultats collectifs sous IE (PO-212)
  orga/app/routes/authenticated/campaigns/details/collective-results.js
Labels: Func Review OK, Tech Review Asked

#579 [TECH] Date de remise à zéro dans les variables d'env
  api/lib/domain/constants.js
  api/lib/settings.js
Labels: Tech Review Asked

#577 [BUGFIX] Fix de la disparition de la barre de progression en démo et en certification
  mon-pix/app/components/progress-bar.js
  mon-pix/app/models/assessment-progression.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/tests/unit/components/progress-bar-test.js
  mon-pix/tests/unit/models/assessment-progress-test.js
Labels: Tech Review Asked

#571 [FEATURE] Calcul du résultat et affichage de la certification V2. (PA-92)
  admin/config/environment.js
  api/lib/domain/constants.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/integration/domain/services/user-service_get-profile-to-certify_test.js
  api/tests/unit/domain/services/certification-service_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
Labels: Func Review OK, Tech Review Asked, 🌟Etoile

#585 [TECH] Retirer le bouton pour la remise à zéro.
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/tests/acceptance/competence-details-test.js
Labels: Func Review OK
