Repository 1024pix/pix, pull requests merged in 2019-08, with the labels that each got.

#625 [TECH] Ajout d'un glossaire des variables d'environnement dans la documentation
  docs/Glossaire-Variables-Env.md
Labels: Tech Review Asked

#631 [FEATURE] Affiche le didacticiel seulement une fois. (PF-701)
  api/db/migrations/20190730172148_add_column_has-seen-assessment-instructions_to_user.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/remember-user-has-seen-assessment-instructions.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/remember-user-has-seen-assessment-instructions_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/acceptance/application/users/users-controller-get-user_test.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/remember-user-has-seen-assessment-instructions_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/models/user.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/campaigns/tutorial.js
  mon-pix/app/templates/profile.hbs
  mon-pix/mirage/config.js
  mon-pix/tests/unit/adapters/user-test.js
  mon-pix/tests/unit/routes/campaigns/tutorial-test.js
Labels: Func Review OK, Tech Review Asked

#615 [FEATURE] Afficher les bonnes réponses sur le checkpoint pour les questions de type qrocm-dep (PF-161).
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/app/components/result-item-campaign.js
  mon-pix/app/components/result-item.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_result-item-campaign.scss
  mon-pix/app/styles/components/_result-item.scss
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/qrocm-dep-solution-panel.hbs
  mon-pix/app/templates/components/result-item-campaign.hbs
  mon-pix/app/templates/components/result-item.hbs
  mon-pix/tests/acceptance/challenge-feedback-test.js
  mon-pix/tests/acceptance/checkpoint-test.js
  mon-pix/tests/acceptance/compare-answer-solution-qroc-test.js
  mon-pix/tests/acceptance/compare-answer-solution-test.js
  mon-pix/tests/integration/components/result-item-campaign-test.js
  mon-pix/tests/integration/components/result-item-test.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel-test.js
  mon-pix/tests/unit/components/result-item-campaign-test.js
  mon-pix/tests/unit/components/result-item-test.js
Labels: Func Review OK, Tech Review Asked

#641 [FEATURE] Changement du hover du bouton pour fermer la bandeau d'information nouveau profil (PF-785).
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/pages/_profile.scss
Labels: Func Review OK, Tech Review Asked

#632 [BUGFIX] Un utilisateur doit pouvoir accéder à son profil Pix via le GAR et ne pas être bloqué (PF-774).
  api/lib/application/saml/saml-controller.js
  api/tests/acceptance/application/saml-controller_test.js
  api/tests/unit/application/saml/saml-controller_test.js
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/integration/campaign.feature
  high-level-tests/e2e/cypress/integration/login.feature
  high-level-tests/e2e/cypress/integration/profile.feature
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/login.js
  high-level-tests/e2e/package.json
  mon-pix/app/routes/application.js
  mon-pix/app/routes/login.js
  mon-pix/tests/helpers/testing.js
  mon-pix/tests/unit/routes/application-test.js
  mon-pix/tests/unit/routes/login-test.js
Labels: Tech Review Asked

#644 [BUGFIX] Répare les routes de réponses.
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/find-answer-by-challenge-and-assessment.js
  api/lib/domain/usecases/get-answer.js
  api/lib/domain/usecases/get-correction-for-answer.js
Labels: EXPEDIT, Tech Review Asked

#642 [TECH] Mise à jour de Cypress.
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
Labels: Ready to Merge

#634 [BUGFIX] Empêcher de poser des questions en trop en certification (PF-781)
  api/lib/domain/services/user-service.js
  api/tests/integration/domain/services/user-service_get-profile-to-certify_test.js
Labels: Func Review OK

#628 [FEATURE] Ajout du menu de navigation (PF-754).
  mon-pix/app/components/navbar-burger-menu.js
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/components/navbar-header.js
  mon-pix/app/components/navbar-mobile-header.js
  mon-pix/app/routes/campaigns/fill-in-campaign-code.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_navbar-burger-menu.scss
  mon-pix/app/styles/components/_navbar-desktop-header.scss
  mon-pix/app/styles/components/_navbar-header.scss
  mon-pix/app/styles/components/_navbar-mobile-header.scss
  mon-pix/app/styles/components/_user-logged-menu.scss
  mon-pix/app/styles/globals/_pix-modal.scss
  mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/app/templates/certifications/start-error.hbs
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/competence-details.hbs
  mon-pix/app/templates/competences/results.hbs
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/components/navbar-header.hbs
  mon-pix/app/templates/components/navbar-mobile-header.hbs
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/app/templates/error.hbs
  mon-pix/app/templates/profile.hbs
  mon-pix/app/templates/user-certifications.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/navigation-test.js
  mon-pix/tests/acceptance/user-certifications-test.js
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
  mon-pix/tests/integration/components/navbar-header-test.js
  mon-pix/tests/integration/components/navbar-mobile-header-test.js
  mon-pix/tests/integration/components/user-logged-menu-test.js
  mon-pix/tests/unit/components/navbar-burger-menu-test.js
  mon-pix/tests/unit/components/navbar-desktop-header-test.js
  mon-pix/tests/unit/components/navbar-header-test.js
  mon-pix/tests/unit/components/navbar-mobile-header-test.js
Labels: Func Review OK, Tech Review Asked

#647 [BUGFIX] Les liens vers les RAs ne s'affichent plus dans Github & Jira
  package.json
Labels: Tech Review Asked

#646 [FEATURE] Obliger le code campagne à s'afficher sur une seule ligne (PO-222).
  orga/app/styles/pages/authenticated/campaigns/details.scss
Labels: Func Review OK, Tech Review Asked

#650 [FEATURE] Mettre à jour le texte sur la page d'inscription (PF-797).
  mon-pix/app/templates/components/signup-form.hbs
Labels: Func Review OK, Tech Review Finished

#640 [TECH] Réécriture de certaines routes des campagnes.
  mon-pix/app/controllers/campaigns/campaign-landing-page.js
  mon-pix/app/controllers/campaigns/fill-in-id-pix.js
  mon-pix/app/controllers/campaigns/skill-review.js
  mon-pix/app/routes/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/skill-review.js
  mon-pix/app/templates/campaigns/fill-in-id-pix.hbs
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/unit/controllers/campaigns/campaign-landing-page-test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-id-pix-test.js
  mon-pix/tests/unit/controllers/campaigns/skill-review-test.js
  mon-pix/tests/unit/routes/campaigns/campaign-landing-page-test.js
  mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
Labels: Tech Review Asked

#648 [TECH] Suppression de code lié à "isAdaptive".
  api/lib/application/courses/course-controller.js
  api/lib/application/courses/index.js
  api/lib/domain/models/Course.js
  api/lib/infrastructure/repositories/course-repository.js
  api/lib/infrastructure/serializers/airtable/course-serializer.js
  api/lib/infrastructure/serializers/jsonapi/course-serializer.js
  api/tests/acceptance/application/course-controller_test.js
  api/tests/tooling/domain-builder/factory/build-course.js
  api/tests/unit/application/courses/course-controller_test.js
  api/tests/unit/application/courses/index_test.js
  api/tests/unit/infrastructure/repositories/course-repository_test.js
  api/tests/unit/infrastructure/serializers/airtable/course-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/course-serializer_test.js
  mon-pix/app/components/medal-item.js
  mon-pix/app/components/scoring-panel-tantpix.js
  mon-pix/app/components/scoring-panel.js
  mon-pix/app/components/trophy-item.js
  mon-pix/app/models/course.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_medal-item.scss
  mon-pix/app/styles/components/_scoring-panel-tantpix.scss
  mon-pix/app/styles/components/_scoring-panel.scss
  mon-pix/app/styles/components/_trophy-item.scss
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/app/templates/components/medal-item.hbs
  mon-pix/app/templates/components/scoring-panel-tantpix.hbs
  mon-pix/app/templates/components/scoring-panel.hbs
  mon-pix/app/templates/components/trophy-item.hbs
  mon-pix/mirage/fixtures/courses.js
  mon-pix/public/images/coupe.svg
  mon-pix/public/images/medaille.svg
  mon-pix/public/images/smiley.png
  mon-pix/public/images/smiley@2x.png
  mon-pix/public/images/smiley@3x.png
  mon-pix/tests/integration/components/medal-item-test.js
  mon-pix/tests/integration/components/scoring-panel-tantpix-test.js
  mon-pix/tests/integration/components/scoring-panel-test.js
  mon-pix/tests/integration/components/trophy-item-test.js
  mon-pix/tests/unit/components/scoring-panel-test.js
  mon-pix/tests/unit/models/course-test.js
Labels: Tech Review Asked

#645 [TECH] Suppression de V1 dans le back.
  api/lib/application/snapshots/index.js
  api/lib/application/snapshots/snapshot-controller.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/Competence.js
  api/lib/domain/models/Profile.js
  api/lib/domain/services/profile-completion-service.js
  api/lib/domain/services/profile-service.js
  api/lib/domain/services/snapshot-service.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/snapshot-repository.js
  api/lib/infrastructure/serializers/jsonapi/jsonapi-serializer.js
  api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
  api/lib/infrastructure/serializers/jsonapi/snapshot-serializer.js
  api/lib/infrastructure/utils/error-manager.js
  api/lib/infrastructure/validators/jsonwebtoken-verify.js
  api/tests/acceptance/application/snapshot-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/unit/application/snapshots/index_test.js
  api/tests/unit/application/snapshots/snapshot-controller_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/Profile_test.js
  api/tests/unit/domain/services/profile-completion-service_test.js
  api/tests/unit/domain/services/profile-service_test.js
  api/tests/unit/domain/services/snapshot-service_test.js
  api/tests/unit/infrastructure/repositories/snapshot-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/snapshot-serializer_test.js
  api/tests/unit/infrastructure/validators/jsonwebtoken-verify_test.js
Labels: Tech Review Asked

#630 [FEATURE] Le membre d'un centre de certification veut pouvoir télécharger un PV de session contenant la liste des candidats inscrits à celle-ci (PC-61-1)
  api/db/migrations/20190627154044_create_certification_candidates_table.js
  api/db/seeds/data/certification-candidates-builder.js
  api/db/seeds/data/sessions-builder.js
  api/db/seeds/seed.js
  api/lib/domain/files/attendance_sheet_template.ods
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/models/Session.js
  api/lib/domain/services/session-xml-service.js
  api/lib/domain/services/xml-service.js
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/infrastructure/data/certification-candidate.js
  api/lib/infrastructure/data/session.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-placeholders.js
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template.ods
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/services/ods-content-xml-service.js
  api/tests/acceptance/application/session-controller_test.js
  api/tests/acceptance/application/session/session-controller-get-attendance-sheet_test.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/acceptance/application/session/session-controller-patch_test.js
  api/tests/acceptance/application/session/session-controller-post_test.js
  api/tests/integration/domain/services/xml-service_test.js
  api/tests/integration/domain/usecases/attendance_sheet_template_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/integration/infrastructure/services/ods-content-xml-service_test.js
  api/tests/tooling/database-builder/factory/build-certification-candidate.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/get-attendance-sheet_test.js
Labels: Func Review OK, Tech Review Finished

#651 [FEATURE] Empêcher de certifier un profil V1 (PC-67).
  api/lib/domain/constants.js
  api/lib/domain/models/UserCompetence.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Func Review OK, Tech Review Asked

#655 [BUGFIX] La page de résultats d'un parcours par compétence n'affiche pas le nombre de Pix.
  mon-pix/app/routes/competences/results.js
Labels: Func Review Needed, Tech Review Asked

#657 [BUGFIX] Corrige le format de date du PV de session (PC-70)
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template.ods
  api/tests/integration/domain/usecases/attendance_sheet_template_target.ods
Labels: Func Review OK

#656 [TECH] Génération d'une importante quantité de candidats de certification dans les seeds
  api/db/seeds/data/certification-candidates-builder.js
Labels: Tech Review Asked

#652 [FEATURE] Possibilité d'afficher le mot de passe dans les formulaires (PF-116).
  certif/app/components/login-form.js
  certif/app/styles/components/login-form.scss
  certif/app/templates/components/login-form.hbs
  certif/tests/integration/components/login-form-test.js
  mon-pix/app/components/form-textfield.js
  mon-pix/app/styles/components/_form-textfield.scss
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/tests/integration/components/form-textfield-test.js
  orga/app/components/login-form.js
  orga/app/styles/components/login-form.scss
  orga/app/templates/components/login-form.hbs
  orga/tests/integration/components/login-form-test.js
Labels: Func Review OK, Tech Review Asked

#662 [FEATURE] Modifier le format des mots de passe (PF-748).
  api/lib/domain/validators/user-validator.js
  api/lib/settings.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/domain/validations/user-validator_test.js
  api/tests/unit/infrastructure/validators/password-validator_test.js
  mon-pix/app/components/reset-password-form.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/utils/password-validator.js
  mon-pix/tests/integration/components/signup-form-test.js
  mon-pix/tests/unit/components/form-textfield-test.js
  mon-pix/tests/unit/components/reset-password-form-test.js
  mon-pix/tests/unit/utils/password-validator-test.js
Labels: Func Review OK, Tech Review Asked

#665 [TECH] Rendre l'utilisateur PixAile (seeds) certifiable
  api/db/seeds/data/pix-aile-profile-builder.js
  api/db/seeds/data/pix-aile-profilev2-builder.js
  api/db/seeds/seed.js
Labels: Func Review OK, Tech Review Asked

#672 [FEATURE] Afficher une information RGPD lors de la création d'une Campagne avec Identifiant externe (PO-223).
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/campaigns/new-item.scss
  orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs
  orga/tests/acceptance/campaign-creation-test.js
Labels: Func Review Needed, Tech Review Asked

#659 [TECH] Refactoring du user-service
  api/lib/application/passwords/password-controller.js
  api/lib/domain/constants.js
  api/lib/domain/models/Answer.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/KnowledgeElement.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/UserCompetence.js
  api/lib/domain/services/user-service.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/passwords/password-controller_test.js
  api/tests/unit/domain/services/user-service_test.js
Labels: Ready to Merge

#669 [BUGFIX] Problème d'affichage de l'oeil lorsque l'utilisateur souhaite continuer d'écrire (PF-807).
  certif/tests/integration/components/login-form-test.js
  mon-pix/app/components/form-textfield.js
  mon-pix/app/styles/components/_form-textfield.scss
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/tests/integration/components/form-textfield-test.js
  orga/tests/integration/components/login-form-test.js
Labels: Func Review OK, Tech Review Asked

#671 [BUGFIX] Problème quand l'utilisateur appuie sur la touche entrer après avoir rempli un formulaire d'authentification (PF-808).
  certif/app/styles/components/login-form.scss
  certif/app/templates/components/login-form.hbs
  mon-pix/app/styles/components/_form-textfield.scss
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/tests/integration/components/form-textfield-test.js
  orga/app/styles/components/login-form.scss
  orga/app/templates/components/login-form.hbs
Labels: Func Review OK, Tech Review Asked

#675 [FEATURE] Améliorer l'affichage des champs de formulaire (PF-114).
  mon-pix/app/styles/components/_form-textfield.scss
Labels: Func Review OK, Tech Review Asked

#663 [FEATURE] Plafonner le score et le niveau lors d'une certification (PF-773).
  api/lib/domain/models/UserCompetence.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/services/scoring/scoring-certification.js
  api/lib/domain/services/scoring/scoring-service.js
  api/lib/domain/usecases/create-assessment-result-for-completed-assessment.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/tests/integration/domain/services/scoring/scoring-certification_test.js
  api/tests/integration/domain/services/user-service_get-profile-to-certify_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/services/scoring-service_test.js
  api/tests/unit/domain/usecases/create-assessment-result-for-completed-assessment_test.js
Labels: Tech Review Asked
