Repository 1024pix/pix, pull requests merged in 2019-05, with the labels that each got.

#489 [TECH] Utilisation complète des builders lorsque l'on seed la base de données.
  api/db/seeds/data/answers-builder.js
  api/db/seeds/data/answers.js
  api/db/seeds/data/assessment-results-builder.js
  api/db/seeds/data/assessment-results.js
  api/db/seeds/data/assessments-builder.js
  api/db/seeds/data/assessments.js
  api/db/seeds/data/certification-center-memberships-builder.js
  api/db/seeds/data/certification-center-memberships.js
  api/db/seeds/data/certification-centers-builder.js
  api/db/seeds/data/certification-centers.js
  api/db/seeds/data/certification-challenges-builder.js
  api/db/seeds/data/certification-challenges.js
  api/db/seeds/data/certification-courses-builder.js
  api/db/seeds/data/competence-marks-builder.js
  api/db/seeds/data/competence-marks.js
  api/db/seeds/data/dragon-and-co-builder.js
  api/db/seeds/data/pix-aile-builder.js
  api/db/seeds/data/sessions-builder.js
  api/db/seeds/data/snapshots-builder.js
  api/db/seeds/data/users_pix_roles-builder.js
  api/db/seeds/data/users_pix_roles.js
  api/db/seeds/seed.js
  api/tests/tooling/database-builder/factory/build-competence-mark.js
  api/tests/tooling/database-builder/factory/index.js
Labels: Ready to Merge

#482 [BUGFIX] Corriger l'alignement des listes à puces pour les phrases trop longues (PF-141)
  mon-pix/app/styles/components/_challenge-response.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
Labels: Ready to Merge

#483 [TECH] Séparation des scripts sqlite et npm dans le package.json de api
  .circleci/config.yml
  api/package.json
  api/scripts/database/create-database.js
  api/scripts/database/drop-database.js
  high-level-tests/e2e/README.md
  high-level-tests/e2e/package.json
Labels: Ready to Merge

#487 [TECH] Ajout d'un namespace "/api" dans les resources exposées par l'API ainsi que les adapters des apps front-end (PF-551).
  admin/app/adapters/application.js
  admin/app/adapters/certification-details.js
  admin/app/adapters/certification.js
  admin/mirage/config.js
  admin/mirage/serializers/organization.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-membership-serializer.js
  api/lib/infrastructure/serializers/jsonapi/membership-serializer.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participations-controller_test.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-certification-center-memberships_test.js
  api/tests/acceptance/application/users/users-controller-get-memberships_test.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/acceptance/application/users/users-controller-get-user_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/acceptance/application/users/users-get-campaign-participations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-membership-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  certif/app/adapters/application.js
  certif/mirage/config.js
  certif/mirage/serializers/certification-center.js
  certif/mirage/serializers/user.js
  mon-pix/app/adapters/application.js
  mon-pix/app/adapters/challenge.js
  mon-pix/app/adapters/correction.js
  mon-pix/mirage/config.js
  mon-pix/mirage/serializers/campaign-participation.js
  mon-pix/mirage/serializers/user.js
  mon-pix/tests/unit/adapters/application-test.js
  orga/app/adapters/application.js
  orga/mirage/config.js
  orga/mirage/serializers/campaign.js
  orga/mirage/serializers/organization.js
  orga/mirage/serializers/user.js
Labels: Ready to Merge

#470 [TECH] Amélioration du bookshelf-to-domain converter
  api/lib/infrastructure/data/assessment.js
  api/lib/infrastructure/data/campaign-participation.js
  api/lib/infrastructure/data/campaign.js
  api/lib/infrastructure/data/knowledge-element.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/utils/bookshelf-to-domain-converter.js
  api/package.json
  api/tests/acceptance/application/campaign-participations-controller_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/integration/infrastructure/utils/bookshelf-to-domain-converter_test.js
  api/tests/tooling/database-builder/database-builder.js
  api/tests/tooling/database-builder/factory/build-answer.js
  api/tests/tooling/database-builder/factory/build-assessment-result.js
  api/tests/tooling/database-builder/factory/build-assessment.js
  api/tests/tooling/database-builder/factory/build-campaign-participation.js
  api/tests/tooling/database-builder/factory/build-campaign.js
  api/tests/tooling/database-builder/factory/build-certification-center-membership.js
  api/tests/tooling/database-builder/factory/build-certification-challenge.js
  api/tests/tooling/database-builder/factory/build-certification-course.js
  api/tests/tooling/database-builder/factory/build-competence-mark.js
  api/tests/tooling/database-builder/factory/build-membership.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/database-builder/factory/build-smart-placement-knowledge-element.js
  api/tests/tooling/database-builder/factory/build-snapshot.js
  api/tests/tooling/database-builder/factory/build-target-profile-share.js
  api/tests/tooling/database-builder/factory/build-target-profile.js
  api/tests/tooling/database-builder/factory/build-target-profiles-skills.js
  api/tests/tooling/database-builder/factory/build-user-pix-role.js
  api/tests/tooling/database-builder/factory/build-user.js
Labels: Tech Review Asked

#492 [BUGFIX] Corriger l'affichage de certains liens de mon-pix. (PF-590)
  mon-pix/app/styles/pages/_competence-details.scss
  mon-pix/app/styles/pages/_profilv2.scss
  mon-pix/app/templates/profilv2.hbs
Labels: Ready to Merge

#477 [FEATURE] Afficher par défaut le profil V2 pour certains utilisateurs (PF-556).
  api/lib/domain/models/Profile.js
  api/lib/domain/services/profile-service.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
  api/tests/acceptance/application/users/users-controller-get-profile_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/unit/domain/services/profile-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/models/user.js
  mon-pix/app/routes/index.js
  mon-pix/tests/unit/components/user-logged-menu-test.js
Labels: Tech Review Finished

#478 [TECH] Mise en place d'outils pour faciliter les tests de charge & perfs.
  .gitignore
  api/bin/www
  api/lib/application/system/index.js
  api/lib/application/system/system-controller.js
  api/lib/infrastructure/mailjet.js
  api/lib/infrastructure/validators/grecaptcha-validator.js
  api/lib/routes.js
  api/lib/settings.js
  api/package-lock.json
  api/package.json
  api/tests/integration/application/system/system-controller_test.js
  api/tests/test-helper.js
  api/tests/unit/application/system/system-controller_test.js
  api/tests/unit/infrastructure/mailjet_test.js
  api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
  high-level-tests/load-testing/README.md
  high-level-tests/load-testing/config/common.yml
  high-level-tests/load-testing/functions.js
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/load-testing/report/.gitkeep
  high-level-tests/load-testing/scenarios/signup-and-placement.yml
Labels: Tech Review Asked

#496 [BUGFIX] Corriger le problème d'affichage des niveaux sous IE. (PF-595)
  mon-pix/app/styles/components/_circle-chart.scss
Labels: Func Review Needed, Tech Review Asked

#488 [FEATURE] Affiche la scorecard associée à la fin d'un parcours par compétence. (PF-569)
  api/lib/application/competence-evaluations/competence-evaluation-controller.js
  api/lib/application/competence-evaluations/index.js
  api/lib/domain/models/CompetenceEvaluation.js
  api/lib/domain/usecases/find-competence-evaluations.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/competence-evaluation-repository.js
  api/lib/infrastructure/serializers/jsonapi/competence-evaluation-serializer.js
  api/tests/acceptance/application/competence-evaluation-controller_test.js
  api/tests/integration/infrastructure/repositories/competence-evaluation-repository_test.js
  api/tests/unit/application/competence-evaluations/competence-evaluation-controller_test.js
  api/tests/unit/domain/usecases/find-competence-evaluations_test.js
  api/tests/unit/infrastructure/repositories/competence-evaluation-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/competence-evaluation-serializer_test.js
  mon-pix/app/components/competence-card.js
  mon-pix/app/controllers/competence-details.js
  mon-pix/app/models/competence-evaluation.js
  mon-pix/app/models/scorecard.js
  mon-pix/app/router.js
  mon-pix/app/routes/assessments/rating.js
  mon-pix/app/routes/competences/results.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/pages/_competence-details.scss
  mon-pix/app/styles/pages/_competence-results.scss
  mon-pix/app/templates/competence-details.hbs
  mon-pix/app/templates/competences/results.hbs
  mon-pix/app/templates/components/competence-card.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/mirage/config.js
  mon-pix/tests/acceptance/competence-details-test.js
  mon-pix/tests/acceptance/comptetences-results-test.js
  mon-pix/tests/integration/components/competence-card-test.js
  mon-pix/tests/unit/components/competence-card-test.js
  mon-pix/tests/unit/models/scorecard-test.js
  mon-pix/tests/unit/routes/assessments/rating-test.js
  mon-pix/tests/unit/routes/competences/results-test.js
Labels: Tech Review Asked

#486 [BUGFIX] Corriger la disposition des réponses d'un QCROQM-ind (PF-570).
  mon-pix/app/components/qrocm-ind-solution-panel.js
  mon-pix/app/styles/components/_qrocm-solution-panel.scss
  mon-pix/app/templates/components/qrocm-ind-solution-panel.hbs
  mon-pix/tests/integration/components/qrocm-ind-solution-panel-test.js
  mon-pix/tests/unit/components/qrocm-ind-solution-panel-test.js
Labels: Rework needed after Func Review

#497 [FEATURE] Modifier le wording de la page d'avertissement du chronomètre. (PF-115)
  mon-pix/app/templates/components/warning-page.hbs
Labels: Func Review Needed, Tech Review Asked

#498 [BUGFIX] Rétablir l'affichage de la barre de progression d'un checkpoint. (PF-597)
  mon-pix/app/controllers/assessments/checkpoint.js
Labels: EXPEDIT, Func Review OK, Tech Review Finished

#499 [BUGFIX] Unifier l'affichage du cercle de progression d'une compétence (pf-599)
  mon-pix/app/routes/competence-details.js
Labels: EXPEDIT, Func Review Needed, Tech Review Asked

#501 [FEATURE] Afficher un lien temporaire d'explications pour Profil v2(PF-589).
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/pages/_profilv2.scss
  mon-pix/app/templates/profilv2.hbs
  mon-pix/tests/acceptance/profilv2-test.js
Labels: Func Review Needed, Tech Review Asked

#503 [BUGFIX] Correction d'une typo dans la modale de prévention sur support mobile.
  mon-pix/app/templates/components/warning-page.hbs
Labels: Func Review OK, Tech Review Asked

#500 [TECH] Refactoring pour préparer la remise à zéro
  api/lib/domain/constants.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/Competence.js
  api/lib/domain/models/Profile.js
  api/lib/domain/models/Scorecard.js
  api/lib/domain/services/profile-service.js
  api/lib/domain/services/scoring/scoring-placement.js
  api/lib/domain/services/smart-random/catAlgorithm.js
  api/lib/domain/services/smart-random/smartRandom.js
  api/lib/domain/usecases/get-assessment.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/tests/integration/domain/services/smart-random/SmartRandom_test.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/services/profile-service_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-smart-placement_test.js
Labels: Ready to Merge

#502 [FEATURE] Modification du design de scorecard-details (PF-594)
  mon-pix/app/components/scorecard-details.js
  mon-pix/app/helpers/replace-zero-by-dash.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_competence-card.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/globals/_text.scss
  mon-pix/app/templates/components/competence-card.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/package-lock.json
  mon-pix/tests/acceptance/competence-details-test.js
  mon-pix/tests/acceptance/profilv2-test.js
  mon-pix/tests/integration/components/competence-card-test.js
  mon-pix/tests/integration/components/scorecard-details-test.js
  mon-pix/tests/unit/components/scorecard-details.js
  mon-pix/tests/unit/helpers/replace-zero-by-dash-test.js
Labels: Func Review OK, Tech Review Asked

#504 [TECH] Améliorer le script d'extraction d'answers.
  .gitignore
  api/scripts/extract-answers-reference-list
  api/scripts/extract-answers.sh
Labels: Tech Review Asked

#512 [TECH] Renommer SmartPlacementKnowledgeElement en KnowledgeElement.
  api/db/seeds/data/campaign-participations-builder.js
  api/lib/domain/models/KnowledgeElement.js
  api/lib/domain/models/SmartPlacementAssessment.js
  api/lib/domain/services/smart-random/catAlgorithm.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/lib/domain/usecases/get-progression.js
  api/lib/domain/usecases/get-results-campaign-in-csv-format.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/get-user-pix-score.js
  api/lib/domain/usecases/get-user-scorecards.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/knowledge-element.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/repositories/smart-placement-assessment-repository.js
  api/scripts/generate_uml.rb
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-competence-evaluation_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/acceptance/application/campaign-participations-controller_test.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-pix-score_test.js
  api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js
  api/tests/integration/domain/services/smart-random/SmartRandom_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/integration/infrastructure/repositories/smart-placement-assessment-repository_test.js
  api/tests/integration/infrastructure/utils/bookshelf-to-domain-converter_test.js
  api/tests/tooling/database-builder/factory/build-knowledge-element.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-knowledge-element.js
  api/tests/tooling/domain-builder/factory/build-progression.js
  api/tests/tooling/domain-builder/factory/build-smart-placement-assessment.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/KnowledgeElement_test.js
  api/tests/unit/domain/models/Progression_test.js
  api/tests/unit/domain/models/SmartPlacementAssessment_test.js
  api/tests/unit/domain/services/smart-random/challengesFilter_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  api/tests/unit/domain/usecases/find-campaign-participations-with-results_test.js
  api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-smart-placement_test.js
  api/tests/unit/domain/usecases/get-progression_test.js
  api/tests/unit/domain/usecases/get-results-campaign-in-csv-format_test.js
  api/tests/unit/domain/usecases/get-scorecard_test.js
  api/tests/unit/domain/usecases/get-user-pix-score_test.js
  api/tests/unit/domain/usecases/get-user-scorecards_test.js
Labels: Ready to Merge

#510 [TECH] Refactor des usecases `get-scorecard` et `get-user-scorecards`.
  api/lib/domain/models/Scorecard.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/get-user-scorecards.js
  api/tests/tooling/domain-builder/factory/build-competence.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/usecases/get-scorecard_test.js
  api/tests/unit/domain/usecases/get-user-scorecards_test.js
Labels: Ready to Merge

#514 Réparer le script `npm run start:watch` de l'API
  api/package.json
Labels: Ready to Merge

#509 [FEATURE] Ajout de bannières de résultats sur la page de résultats de parcours par compétence (PF-585).
  mon-pix/app/models/scorecard.js
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/pages/_competence-details.scss
  mon-pix/app/styles/pages/_competence-results.scss
  mon-pix/app/templates/competence-details.hbs
  mon-pix/app/templates/competences/results.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/mirage/serializers/competence-evaluation.js
  mon-pix/public/images/banners/congrats-text.svg
  mon-pix/public/images/banners/congrats.svg
  mon-pix/public/images/banners/not-bad-text-mobile.svg
  mon-pix/public/images/banners/not-bad-text.svg
  mon-pix/public/images/banners/not-bad.svg
  mon-pix/public/images/banners/too-bad-text.svg
  mon-pix/public/images/banners/too-bad.svg
  mon-pix/tests/acceptance/competence-details-test.js
  mon-pix/tests/acceptance/competences-results-test.js
  mon-pix/tests/acceptance/comptetences-results-test.js
  mon-pix/tests/integration/components/scorecard-details-test.js
  mon-pix/tests/unit/models/scorecard-test.js
Labels: Ready to Merge

#515 [FEATURE] Changement du texte pour les signalements (PF-504).
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/templates/components/feedback-panel.hbs
Labels: Func Review OK, Tech Review Asked

#519 [TECH] Remise en place des Answers dans les seeds.
  api/db/seeds/seed.js
Labels: Tech Review Asked

#507 [TECH] Ajout de scénarios Cypress.
  high-level-tests/e2e/cypress/integration/profilv2.feature
  high-level-tests/e2e/cypress/support/step_definitions/profilv2.js
Labels: Ready to Merge

#494 [FEATURE] Afficher la moyenne des résultats d'une campagne (PO-199).
  api/db/seeds/data/dragon-and-co-builder.js
  api/lib/application/campaignReports/campaign-report-controller.js
  api/lib/application/campaignReports/index.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/models/CampaignCollectiveResult.js
  api/lib/domain/models/CampaignCompetenceCollectiveResult.js
  api/lib/domain/usecases/compute-campaign-collective-result.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/campaign-participation.js
  api/lib/infrastructure/data/knowledge-element.js
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-collective-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/acceptance/application/campaign-participations-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository-test.js
  api/tests/integration/infrastructure/repositories/smart-placement-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/tooling/database-builder/factory/build-target-profile-skill.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-campaign-collective-result.js
  api/tests/tooling/domain-builder/factory/build-campaign-competence-collective-result.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/application/campaignReports/campaign-report-controller_test.js
  api/tests/unit/domain/models/CampaignCompetenceCollectiveResult_test.js
  api/tests/unit/domain/usecases/compute-campaign-collective-result_test.js
  api/tests/unit/domain/usecases/get-campaign-participation_test.js
  api/tests/unit/infrastructure/data/knowledge-element_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-collective-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  orga/app/models/campaign-collective-result.js
  orga/app/models/campaign-competence-collective-result.js
  orga/app/models/campaign-participation.js
  orga/app/models/campaign.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/details.js
  orga/app/routes/authenticated/campaigns/details/collective-results.js
  orga/app/templates/authenticated/campaigns/details/collective-results.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/collective-results-tab.hbs
  orga/mirage/config.js
  orga/mirage/factories/campaign-collective-result.js
  orga/mirage/serializers/campaign-collective-result.js
  orga/mirage/serializers/campaign.js
  orga/tests/acceptance/campaign-collective-result-test.js
  orga/tests/acceptance/campaign-details-test.js
  orga/tests/acceptance/campaign-participants-details-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/collective-results-tab-test.js
  orga/tests/unit/models/campaign-collective-results-test.js
  orga/tests/unit/routes/authenticated/campaigns/details/collective-results-test.js
Labels: Rework needed after Func Review, Tech Review Asked

#511 [FEATURE] Empêcher les utilisateurs de partager une campagne non terminée (PF-579-2).
  api/lib/application/campaignParticipations/campaign-participation-controller.js
  api/lib/domain/errors.js
  api/lib/domain/services/smart-random/cat-algorithm.js
  api/lib/domain/services/smart-random/challenges-filter.js
  api/lib/domain/services/smart-random/data-fetcher.js
  api/lib/domain/services/smart-random/smart-random.js
  api/lib/domain/usecases/get-correction-for-answer-when-assessment-ended.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/lib/domain/usecases/share-campaign-result.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participations-controller_test.js
  api/tests/integration/domain/services/smart-random/smart-random_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/services/smart-random/challenges-filter_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/get-correction-for-answer-when-assessment-ended_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-smart-placement_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
  mon-pix/app/controllers/campaigns/skill-review.js
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/fill-in-id-pix.hbs
  mon-pix/app/templates/campaigns/skill-review.hbs
Labels: Func Review Needed, Tech Review Asked

#522 [FEATURE] Renommer PIX en Pix dans les signalements (PF-608).
  mon-pix/app/templates/components/feedback-panel.hbs
Labels: Func Review Needed, Tech Review Asked

#523 [FEATURE] Indication du format de la date de naissance sur le PV de certif (PC-55).
  api/lib/domain/files/attendance_sheet_template.ods
Labels: Func Review OK

#524 [FEATURE] Changement de wordings sur les pages de résultats de campagnes (PO-208).
  orga/app/templates/components/campaign-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs
Labels: Func Review Needed

#516 [FEATURE] Ajout d'un champs status aux compétences évaluations (PF-579-3).
  api/db/migrations/20190520161908_add_status_to_competence_evaluations.js
  api/lib/domain/constants.js
  api/lib/domain/models/CompetenceEvaluation.js
  api/lib/domain/models/Scorecard.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/get-user-scorecards.js
  api/lib/domain/usecases/start-or-resume-competence-evaluation.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/competence-evaluation-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/serializers/jsonapi/competence-evaluation-serializer.js
  api/tests/acceptance/application/competence-evaluation-controller_test.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js
  api/tests/integration/infrastructure/repositories/competence-evaluation-repository_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/tooling/database-builder/factory/build-competence-evaluation.js
  api/tests/tooling/domain-builder/factory/build-competence-evaluation.js
  api/tests/unit/application/competence-evaluations/competence-evaluation-controller_test.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/usecases/get-scorecard_test.js
  api/tests/unit/domain/usecases/get-user-scorecards_test.js
  api/tests/unit/domain/usecases/start-or-resume-competence-evaluation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/competence-evaluation-serializer_test.js
  mon-pix/app/components/competence-card.js
  mon-pix/app/models/competence-evaluation.js
  mon-pix/tests/unit/components/competence-card-test.js
Labels: Tech Review Asked

#517 [TECH] Refacto sur l'affichage des réponses et des corrections.
  api/lib/application/answers/answer-controller.js
  api/lib/application/answers/index.js
  api/lib/application/corrections/corrections-controller.js
  api/lib/application/corrections/index.js
  api/lib/domain/models/Answer.js
  api/lib/domain/usecases/get-correction-for-answer-when-assessment-ended.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/serializers/jsonapi/answer-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/integration/application/corrections/index_test.js
  api/tests/unit/application/answers/answer-controller_test.js
  api/tests/unit/application/corrections/corrections-controller_test.js
  api/tests/unit/domain/models/Answer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/answer-serializer_test.js
  mon-pix/app/components/comparison-window.js
  mon-pix/app/components/qcm-proposals.js
  mon-pix/app/components/qcu-proposals.js
  mon-pix/app/controllers/assessments/checkpoint.js
  mon-pix/app/controllers/assessments/results.js
  mon-pix/app/models/answer.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/routes/assessments/results.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/tests/integration/components/comparison-window-test.js
  mon-pix/tests/unit/components/qcu-proposals-test.js
Labels: Func Review Needed, Tech Review Finished

#521 [TECH] Remaniement de la génération du profil de certification v1
  api/lib/domain/services/user-service.js
Labels: Tech Review Asked

#529 [TECH] Suppression de feature-list et de feature-item.
  mon-pix/app/components/feature-item.js
  mon-pix/app/components/feature-list.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_feature-item.scss
  mon-pix/app/styles/components/_feature-list.scss
  mon-pix/app/templates/components/feature-item.hbs
  mon-pix/app/templates/components/feature-list.hbs
  mon-pix/tests/integration/components/feature-item-test.js
  mon-pix/tests/integration/components/feature-list-test.js
Labels: Tech Review Asked

#527 [FEATURE] Renommer PIX en Pix (PF-609)
  mon-pix/app/index.html
  mon-pix/app/templates/components/learning-more-panel.hbs
  mon-pix/app/templates/components/modal-mobile.hbs
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/app/templates/components/pix-logo.hbs
  mon-pix/app/templates/components/reset-password-form.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/app/templates/components/tutorial-panel.hbs
  mon-pix/tests/integration/components/modal-mobile-test.js
  mon-pix/tests/integration/components/pix-logo-test.js
Labels: Func Review OK, Tech Review Asked

#525 [FEATURE] Création d'une route pour reset une CompetenceEvaluation (PF-579-4).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/reset-competence-evaluation.js
  api/lib/infrastructure/repositories/competence-evaluation-repository.js
  api/tests/acceptance/application/users/users-controller-reset-competence-evaluation_test.js
  api/tests/unit/domain/usecases/reset-competence-evaluation_test.js
Labels: Func Review Needed, Tech Review Asked

#528 [FEATURE] Cacher "n Pix avant le niveau x" si le parcours est terminé (PF-610)
  mon-pix/app/components/scorecard-details.js
  mon-pix/tests/integration/components/scorecard-details-test.js
  mon-pix/tests/unit/components/scorecard-details-test.js
Labels: Func Review OK, Tech Review Asked

#532 [FEATURE] Passer le recaptcha en feature-flipping côté front (PF-588).
  mon-pix/app/components/progress-bar.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/models/assessment-progression.js
  mon-pix/app/models/assessment.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/config/environment.js
  mon-pix/tests/integration/components/signup-form-test.js
Labels: Func Review Needed, Tech Review Asked

#530 [FEATURE] Ajout du délai de 7 jours pour réinitialiser une évaluation de compétence (PF-579-6).
  api/lib/domain/constants.js
  api/lib/domain/errors.js
  api/lib/domain/models/KnowledgeElement.js
  api/lib/domain/models/Scorecard.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/reset-competence-evaluation.js
  api/lib/domain/usecases/start-or-resume-competence-evaluation.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/serializers/jsonapi/scorecard-serializer.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/campaign-participations-controller_test.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js
  api/tests/acceptance/application/users/users-controller-reset-competence-evaluation_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/unit/domain/models/KnowledgeElement_test.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/usecases/get-scorecard_test.js
  api/tests/unit/domain/usecases/reset-competence-evaluation_test.js
Labels: Ready to Merge, 🌟Etoile

#539 [BUGFIX] Afficher "Reprendre" si la scorecard possède des knowledgeElements (PF-618)
  api/lib/domain/models/Scorecard.js
  api/tests/unit/domain/models/Scorecard_test.js
Labels: Func Review Needed, Tech Review Asked
