Repository 1024pix/pix, pull requests merged in 2019-09, with the labels that each got.

#680 [TECH] Suppression de la classe SmartPlacementAnswer
  api/lib/domain/models/SmartPlacementAnswer.js
  api/lib/domain/models/SmartPlacementAssessment.js
  api/lib/infrastructure/repositories/smart-placement-assessment-repository.js
  api/tests/tooling/domain-builder/factory/build-smart-placement-answer.js
  api/tests/tooling/domain-builder/factory/build-smart-placement-assessment.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/SmartPlacementAnswer_test.js
  api/tests/unit/domain/models/SmartPlacementAssessment_test.js
Labels: Tech Review Asked

#681 [TECH] Normalisation de la structure des modules usecases
  api/lib/domain/usecases/create-assessment-result-for-completed-assessment.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/domain/usecases/get-current-user.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/lib/domain/usecases/get-organization-campaigns.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/get-user-certification-center-memberships.js
  api/lib/domain/usecases/get-user-pix-score.js
  api/lib/domain/usecases/get-user-scorecards.js
  api/lib/domain/usecases/get-user-with-memberships.js
  api/lib/domain/usecases/get-user.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/preload-cache-entries.js
  api/lib/domain/usecases/remember-user-has-seen-assessment-instructions.js
  api/lib/domain/usecases/save-certification-center.js
  api/lib/domain/usecases/start-placement-assessment.js
Labels: Tech Review Asked

#678 [BUGFIX] Plusieurs assessments pouvaient être créés au lancement d'une session de certification (PF-747)
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/usecases/create-assessment-for-certification.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/domain/usecases/create-asssessment-for-certification_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  mon-pix/app/components/certification-starter.js
  mon-pix/app/routes/certifications/resume.js
  mon-pix/app/routes/certifications/start.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_certification-starter.scss
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/mirage/data/challenges/challenge-ids.js
  mon-pix/mirage/routes/find-assessments.js
  mon-pix/mirage/routes/get-challenge.js
  mon-pix/mirage/routes/get-challenges.js
  mon-pix/mirage/routes/get-course.js
  mon-pix/mirage/routes/get-next-challenge.js
  mon-pix/mirage/routes/post-certification-course.js
  mon-pix/tests/acceptance/certification-course-test.js
  mon-pix/tests/acceptance/resume-certification-course-test.js
  mon-pix/tests/integration/components/certification-starter-test.js
  mon-pix/tests/unit/components/certification-starter-test.js
  mon-pix/tests/unit/routes/certifications/resume-test.js
  mon-pix/tests/unit/routes/certifications/start-test.js
Labels: Func Review OK, Tech Review Asked

#660 [TECH] Supprimer les dépendances inutilisées sur mon-pix.
  .codeclimate.yml
  mon-pix/ember-cli-build.js
  mon-pix/package-lock.json
  mon-pix/package.json
  scripts/lcov-path-converter.js
Labels: Ready to Merge

#684 [TECH] Suppression des dernières références à coveralls et codeclimate dans le dossier mon-pix.
  mon-pix/README.md
  package.json
Labels: Ready to Merge

#682 [FEATURE] Offrir une navigation après le partage des résultats d'une campagne (PF-716).
  mon-pix/app/components/navbar-burger-menu.js
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/app/templates/components/assessment-banner.hbs
  mon-pix/tests/acceptance/navigation-test.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/integration/components/assessment-banner-test.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
  mon-pix/tests/unit/components/navbar-burger-menu-test.js
  mon-pix/tests/unit/components/navbar-desktop-header-test.js
Labels: Func Review OK, Tech Review Asked

#690 [BUGFIX] Une migration de mise à jour de la table answers n'était pas bloquante
  api/db/migrations/20170306151003_update_answers.js
Labels: Tech Review Asked

#679 [BUGFIX] Problème de taille des icônes d'œil pour les champs mot de passe.
  certif/app/styles/components/login-form.scss
  certif/app/templates/components/login-form.hbs
  mon-pix/app/styles/components/_form-textfield.scss
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/tests/integration/components/form-textfield-test.js
  mon-pix/tests/integration/components/signup-form-test.js
  orga/app/styles/components/login-form.scss
  orga/app/templates/components/login-form.hbs
Labels: Func Review OK, Tech Review Asked

#691 [BUGFIX] Empêcher la création de plus d'un certification-course pour un même utilisateur dans une session (PF-814)
  api/lib/domain/services/session-service.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/domain/services/session-service_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Func Review OK, Tech Review Asked

#696 [BUGFIX] Ajout d'une campaignParticipationId dans le cas d'une remise à zéro durant une campagne
  api/lib/domain/services/scorecard-service.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/domain/services/scorecard-service_test.js
Labels: Func Review Needed, Tech Review Asked

#677 [FEATURE] Afficher un warning lorsqu'une modification jury est illégale (PF-811).
  admin/app/controllers/authenticated/certifications/single/details.js
  admin/app/controllers/authenticated/certifications/single/info.js
  admin/app/styles/app.scss
  admin/app/styles/components/confirm-popup.scss
  admin/app/templates/authenticated/certifications/single/info.hbs
  admin/app/templates/components/confirm-popup.hbs
  api/lib/domain/services/certification-service.js
Labels: Ready to Merge

#697 [FEATURE] Augmenter la liste de membre d'une organisation (PA-108).
  admin/app/templates/components/organization-members-section.hbs
Labels: Func Review Needed, Tech Review Asked

#695 [TECH] Refacto du hook pre-commit
  api/scripts/NextGitCommitMessage.js
  api/scripts/get-next-commit-subject.js
  api/tests/unit/scripts/NextGitCommitMessage_test.js
  api/tests/unit/scripts/get-next-commit-subject_test.js
  package-lock.json
  package.json
  scripts/git-hook/prepend-commit-message.js
  scripts/git-hook/prepend-commit-subject.js
Labels: Ready to Merge

#653 [TECH] Suppression des positionnements V1 (`PLACEMENT`) côté serveur.
  api/lib/application/assessments/assessment-controller.js
  api/lib/cat/answer.js
  api/lib/cat/assessment.js
  api/lib/cat/challenge.js
  api/lib/cat/course.js
  api/lib/cat/skill.js
  api/lib/domain/errors.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/Skill.js
  api/lib/domain/services/scoring/scoring-placement.js
  api/lib/domain/services/scoring/scoring-service.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/find-placement-assessments.js
  api/lib/domain/usecases/get-assessment.js
  api/lib/domain/usecases/get-next-challenge-for-placement.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/start-placement-assessment.js
  api/lib/infrastructure/adapters/assessment-adapter.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-adaptive_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/integration/domain/services/scoring/scoring-certification_test.js
  api/tests/integration/domain/services/scoring/scoring-placement_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/smart-placement-assessment-repository_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/tooling/database-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-cat-answer.js
  api/tests/tooling/domain-builder/factory/build-cat-assessment.js
  api/tests/tooling/domain-builder/factory/build-cat-challenge.js
  api/tests/tooling/domain-builder/factory/build-cat-course.js
  api/tests/tooling/domain-builder/factory/build-cat-tube.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/cat/answer_test.js
  api/tests/unit/cat/assessment_test.js
  api/tests/unit/cat/challenge_test.js
  api/tests/unit/cat/course_test.js
  api/tests/unit/cat/skill_test.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/services/scoring-service_test.js
  api/tests/unit/domain/services/scoring/scoring-placement_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  api/tests/unit/domain/usecases/create-assessment-result-for-completed-assessment_test.js
  api/tests/unit/domain/usecases/find-placement-assessments_test.js
  api/tests/unit/domain/usecases/get-assessment_test.js
  api/tests/unit/domain/usecases/start-placement-assessment_test.js
  api/tests/unit/infrastructure/adapters/assessment-adapter_test.js
Labels: Tech Review Asked

#700 [BUGFIX] Lancer consécutivement deux campagnes avec demande ID (PF-825).
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
Labels: EXPEDIT, Func Review OK, Tech Review Asked

#694 [TECH] Mise à jour des dépendances de l'API
  api/db/migrations/20170105153948_update_answers_timeout.js
  api/db/migrations/20170329112753_add_elapsedTime_to_answers.js
  api/db/migrations/20170329153349_update_answers--add_column_result_details.js
  api/db/migrations/20170418114929_remove_login_from_users.js
  api/db/migrations/20170703105035_create_link_between_user_and_assessment.js
  api/db/migrations/20170703163243_update_assessment_with_level_and_score.js
  api/db/migrations/20170724181108_creating_organizations.js
  api/db/migrations/20171113101130_certification-courses.js
  api/db/migrations/20171113101244_certification-challenges.js
  api/db/migrations/20171113103608_add_type_to_assessments.js
  api/db/migrations/20171204102525_add_userId_to_certification_course.js
  api/db/migrations/20171212144653_add_status_to_certification_course.js
  api/db/migrations/20180103152804_add_completed_time_to_certification_course.js
  api/db/migrations/20180116161332_modify_column_completedPercentage_to_tests_finished_in_snapshots.js
  api/db/migrations/20180306151846_add_type_to_all_assessments.js
  api/db/migrations/20180306164441_remove-score-and-level-for-bugged-assessments.js
  api/db/migrations/20180315164634_add-column-access-code-on-sessions.js
  api/db/migrations/20180315164647_add-column-session-id-on-certifications.js
  api/db/migrations/20180329113849_add-indexes-on-many-tables.js
  api/db/migrations/20180405100236_move_status_from_certification_to_assessment.js
  api/db/migrations/20180405100530_link_marks_to_assessment_results.js
  api/db/migrations/20180731102046_create_target_profiles_table.js
  api/db/migrations/20180823173827_add-skill-id-to-certification-challenge.js
  api/lib/application/answers/answer-controller.js
  api/lib/plugins.js
  api/lib/settings.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/airtable_test.js
Labels: Func Review OK, Tech Review Asked

#687 [TECH] Découpler les review apps de l'application d'integration
  api/lib/plugins.js
  docs/Glossaire-Variables-Env.md
  scalingo.json
  scripts/jira/comment-with-review-app-url.js
  scripts/signal_deploy_to_pr.sh
Labels: Tech Review Asked

#701 [TECH] Refactorisation et nettoyage du code de création d'assessment-results.
  api/lib/application/assessment-results/assessment-result-controller.js
  api/lib/application/assessment-results/index.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/assessments/index.js
  api/lib/domain/usecases/complete-assessment.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/assessment-result-serializer.js
  api/scripts/compute-missing-certifv2-scores/bin.js
  api/scripts/compute-missing-certifv2-scores/compute-missing-certifv2-scores.js
  api/tests/acceptance/application/assessment-results/assessment-result-controller_test.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/unit/application/assessment-results/assessment-result-controller_test.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-result-serializer_test.js
  api/tests/unit/scripts/compute-missing-certifv2-scores/compute-missing-certifv2-scores_test.js
  mon-pix/app/adapters/assessment.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/mirage/config.js
  mon-pix/tests/unit/adapters/assessment-test.js
  mon-pix/tests/unit/routes/assessments/resume-test.js
Labels: Tech Review Asked

#702 [FEATURE] Accéder à un parcours prescrit avec l'identifiant externe dans l'URL (PF-824).
  high-level-tests/e2e/cypress/fixtures/campaigns.json
  high-level-tests/e2e/cypress/integration/campaign.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  mon-pix/app/controllers/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/start-campaigns-test.js
  mon-pix/tests/helpers/testing.js
  mon-pix/tests/unit/controllers/campaigns/campaign-landing-page-test.js
  mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
Labels: Ready to Merge

#705 [TECH] Suppression de la route POST /api/authentifications (PF-720).
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/integration/application/authentication/authentication-controller_test.js
  api/tests/integration/application/authentication/index_test.js
  high-level-tests/e2e/cypress/support/commands.js
  mon-pix/app/adapters/application.js
  mon-pix/app/authenticators/oauth2.js
  mon-pix/app/authenticators/simple.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/inscription.js
  mon-pix/app/routes/login.js
  mon-pix/app/routes/logout.js
  mon-pix/app/templates/login.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/post-authentications.js
  mon-pix/tests/integration/authenticators/oauth2-test.js
  mon-pix/tests/unit/adapters/application-test.js
  mon-pix/tests/unit/authenticators/oauth2-test.js
  mon-pix/tests/unit/authenticators/simple-test.js
  mon-pix/tests/unit/routes/inscription-test.js
  mon-pix/tests/unit/routes/login-test.js
Labels: Func Review OK, Tech Review Asked

#711 [TECH] Montée de version des dépendances du projet Pix Certif.
  certif/app/router.js
  certif/app/templates/components/login-form.hbs
  certif/app/templates/components/routes/authenticated/sessions/new-item.hbs
  certif/app/templates/components/routes/authenticated/sessions/update-item.hbs
  certif/mirage/factories/session.js
  certif/package-lock.json
  certif/package.json
Labels: Ready to Merge

#709 [TECH] Montée de version des dépendances du projet Pix Orga.
  orga/app/authenticators/oauth2.js
  orga/app/router.js
  orga/app/templates/components/login-form.hbs
  orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/update-item.hbs
  orga/app/templates/components/routes/authenticated/team/new-item.hbs
  orga/mirage/factories/campaign-participation-result.js
  orga/mirage/factories/campaign-participation.js
  orga/mirage/factories/campaign-report.js
  orga/mirage/factories/campaign.js
  orga/mirage/factories/student.js
  orga/mirage/factories/target-profile.js
  orga/mirage/factories/user.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/student-list-test.js
Labels: Ready to Merge

#661 [TECH] Standardisation du paramétrage de l'API.
  api/bin/www
  api/db/knex-database-connection.js
  api/lib/application/healthcheck/healthcheck-controller.js
  api/lib/application/passwords/password-controller.js
  api/lib/application/system/system-controller.js
  api/lib/application/users/index.js
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/reset-password-service.js
  api/lib/domain/services/token-service.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/caches/cache.js
  api/lib/infrastructure/caches/redis-cache.js
  api/lib/infrastructure/logger.js
  api/lib/infrastructure/mailjet.js
  api/lib/infrastructure/saml.js
  api/lib/infrastructure/validators/grecaptcha-validator.js
  api/lib/infrastructure/validators/password-validator.js
  api/lib/plugins.js
  api/package-lock.json
  api/server.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/saml-controller_test.js
  api/tests/unit/application/system/system-controller_test.js
  api/tests/unit/domain/services/reset-password-service_test.js
  api/tests/unit/infrastructure/caches/redis-cache_test.js
  api/tests/unit/infrastructure/mailjet_test.js
  api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
  docs/API.md
Labels: Ready to Merge

#716 [BUGFIX] Correction de l'apparition de bordures rouges pour les champs de saisie du formulaire de connexion pour Pix Orga et Pix Certif.
  certif/app/templates/components/login-form.hbs
  orga/app/templates/components/login-form.hbs
  orga/app/templates/components/routes/authenticated/team/new-item.hbs
Labels: EXPEDIT

#712 [TECH] Montée de version des dépendances du projet Pix Admin.
  admin/app/models/certification.js
  admin/app/router.js
  admin/package-lock.json
  admin/package.json
Labels: Ready to Merge

#685 [BUGFIX] Des candidats n'arrivaient pas à voir leurs certifications sur leur compte (dans user > 'Mes certifications') (PF-757)
  api/lib/application/certifications/certification-controller.js
  api/lib/domain/usecases/find-completed-user-certifications.js
  api/lib/domain/usecases/get-user-certification-with-result-tree.js
  api/lib/domain/usecases/get-user-certification.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-certification-publication-status.js
  api/lib/domain/usecases/update-certification.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/usecases/find-completed-user-certifications_test.js
  api/tests/unit/domain/usecases/get-user-certification-with-result-tree_test.js
  api/tests/unit/domain/usecases/get-user-certification_test.js
  api/tests/unit/domain/usecases/update-certification-publication-status_test.js
Labels: Func Review OK, Tech Review Asked

#721 [BUGFIX] L'assessment considéré par un certification course pouvait ne pas être le même si il en existe plusieurs (PA-110)
  api/db/seeds/data/answers-builder.js
  api/db/seeds/data/assessment-results-builder.js
  api/db/seeds/data/assessments-builder.js
  api/lib/infrastructure/data/certification-course.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/infrastructure/repositories/assessment-repository_test.js
Labels: EXPEDIT, Func Review OK, Tech Review Asked

#698 [TECH] Redefinir la relation entre un assessment et une participation (PF-750-1).
  api/db/migrations/20190826140605_add_column_campaign_participation_id_in_assessments.js
  api/db/migrations/20190904140605_remove_column_assessment_id_in_campaign_participation.js
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/pix-aile-profile-builder.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/models/SmartPlacementAssessment.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/usecases/create-assessment-for-campaign.js
  api/lib/domain/usecases/find-campaign-participations-with-results.js
  api/lib/domain/usecases/get-results-campaign-in-csv-format.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/infrastructure/data/assessment.js
  api/lib/infrastructure/data/campaign-participation.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/acceptance/application/users/users-get-campaign-participations_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/smart-placement-assessment-repository_test.js
  api/tests/integration/infrastructure/utils/bookshelf-to-domain-converter_test.js
  api/tests/tooling/database-builder/factory/build-assessment.js
  api/tests/tooling/database-builder/factory/build-campaign-participation.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation.js
  api/tests/tooling/domain-builder/factory/build-smart-placement-assessment.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/create-assessment-for-campaign_test.js
  api/tests/unit/domain/usecases/find-campaign-participations-with-results_test.js
  api/tests/unit/domain/usecases/get-results-campaign-in-csv-format_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
Labels: Func Review OK, Tech Review Asked

#710 [FEATURE] Ajout du département (code) aux Organisations et affichage dans Pix Admin (PA-105).
  admin/app/models/organization.js
  admin/app/templates/components/organization-information-section.hbs
  api/db/migrations/20190918105231_add_column_provinceCode_to_organizations.js
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: Ready to Merge

#726 [TECH] Retrait de la fonctionnalité plus utilisée d'import CSV dans PixAdmin (PA-111)
  admin/app/controllers/authenticated/certifications/sessions/info/list.js
  admin/app/templates/authenticated/certifications/sessions/info/list.hbs
  admin/package-lock.json
  admin/package.json
Labels: Func Review OK, Tech Review Asked

#727 [BUGFIX] Dysfonctionnement du nettoyage journalier des caches (PF-836)
  api/scripts/reload-cache-everyday.js
Labels: Func Review Needed, Tech Review Asked

#723 [FEATURE] Ajout de la progression par campagne (PF-835).
  api/db/migrations/20190826131512_add_column_isImproving_to_Assessments.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/campaignParticipations/campaign-participation-controller.js
  api/lib/application/campaignParticipations/index.js
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/domain/errors.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/SmartPlacementAssessment.js
  api/lib/domain/services/improvement-service.js
  api/lib/domain/services/smart-random/data-fetcher.js
  api/lib/domain/usecases/begin-campaign-participation-improvement.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/lib/domain/usecases/get-progression.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/share-campaign-result.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/tooling/database-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-smart-placement-assessment.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/services/improvement-service_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/begin-campaign-participation-improvement_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-smart-placement_test.js
  api/tests/unit/domain/usecases/get-progression_test.js
  api/tests/unit/infrastructure/repositories/assessment-repository_test.js
  mon-pix/app/adapters/campaign-participation.js
  mon-pix/app/adapters/challenge.js
  mon-pix/app/controllers/campaigns/skill-review.js
  mon-pix/app/routes/campaigns/skill-review.js
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/mirage/config.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/unit/adapters/campaign-participation-test.js
  mon-pix/tests/unit/adapters/challenge-test.js
  mon-pix/tests/unit/controllers/campaigns/skill-review-test.js
Labels: Func Review Needed, Tech Review Asked

#729 [FEATURE] Modification du logo dans Pix Orga (PO-245)
  orga/app/styles/pages/authenticated/terms-of-service.scss
  orga/app/styles/pages/login.scss
  orga/app/templates/authenticated.hbs
  orga/app/templates/authenticated/terms-of-service.hbs
  orga/app/templates/components/login-form.hbs
  orga/public/pix-logo-orga-beta-black.svg
  orga/public/pix-logo-orga-beta.svg
  orga/public/pix-logo-orga.svg
  orga/public/pix-orga.svg
Labels: Func Review OK, Tech Review Asked

#724 [FEATURE] Mise à jour des organisations en ajoutant un identifiant externe et le département à l'aide d'un script (PF-778).
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/update-organization-information.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/scripts/update-sco-organizations-with-province-code-and-external-id.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/scripts/update-sco-organizations-with-province-code-and-external-id_test.js
  api/tests/acceptance/scripts/valid-organizations-test-file.csv
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
Labels: Ready to Merge
