Repository 1024pix/pix, pull requests merged in 2019-11, with the labels that each got.

#802 [FEATURE] Page de reconciliation au lancement d'une campagne (PF-817).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/student-user-associations/index.js
  api/lib/application/student-user-associations/student-user-association-controller.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/models/Student.js
  api/lib/domain/usecases/get-student-linked-to-user.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/link-user-to-organization-student-data.js
  api/lib/domain/usecases/retrieve-campaign-information.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/student-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/student-user-association-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-student_test.js
  api/tests/integration/application/student-user-associations/index_test.js
  api/tests/integration/infrastructure/repositories/student-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-student-linked-to-user_test.js
  api/tests/unit/domain/usecases/link-user-to-organization-student-data_test.js
  api/tests/unit/domain/usecases/retrieve-campaign-information_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  mon-pix/app/adapters/student.js
  mon-pix/app/controllers/campaigns/join-restricted-campaign.js
  mon-pix/app/models/campaign.js
  mon-pix/app/models/student-user-association.js
  mon-pix/app/models/student.js
  mon-pix/app/router.js
  mon-pix/app/routes/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/join-restricted-campaign.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/_join-restricted-campaign.scss
  mon-pix/app/templates/campaigns/join-restricted-campaign.hbs
  mon-pix/app/transforms/date-only.js
  mon-pix/mirage/config.js
  mon-pix/mirage/data/assessments/ref-assessment-placement.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/acceptance/start-campaigns-test.js
  mon-pix/tests/unit/controllers/campaigns/join-restricted-campaign-test.js
  mon-pix/tests/unit/routes/campaigns/join-restricted-campaign-test.js
Labels: Ready to Merge

#807 [FEATURE] Script d'envoie des invitations SCO (PF-862)
  api/lib/application/organizations/index.js
  api/scripts/organizeOrganizationsByExternalId.js
  api/scripts/send-invitations-to-sco-organizations.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/test-helper.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/helpers/valid-organizations-test-file.csv
  api/tests/unit/scripts/organizeOrganizationsByExternalId.js
Labels: Func Review Needed, Tech Review Asked, 🌟Etoile

#810 [FEATURE] Ajout d'un script déclenchant le déploiement SCO.
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/update-organization-information.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/scripts/update-sco-organizations-with-is-managing-students-to-true.js
  api/tests/acceptance/scripts/update-sco-organizations-with-is-managing-students-to-true_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
Labels: Ready to Merge

#753 [FEATURE] Lier un utilisateur participant à une session de certification à un candidat inscrit au préalable à cette même session (PF-383)
  api/db/migrations/20191025161754_add_column_user_id_to_certification_candidates.js
  api/db/migrations/20191029091642_add_certification_candidates_unique_constraint_on_user_and_session.js
  api/db/pgsql-errors.js
  api/db/seeds/data/certification-candidates-builder.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/link-user-to-session-certification-candidate.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/data/certification-candidate.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/lib/infrastructure/utils/error-manager.js
  api/scripts/database/create-database.js
  api/scripts/database/drop-database.js
  api/tests/acceptance/application/session/session-controller-create-certification-candidate-participation_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/tooling/database-builder/factory/build-certification-candidate.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js
  mon-pix/app/adapters/certification-candidate.js
  mon-pix/app/components/certification-joiner.js
  mon-pix/app/components/certification-starter.js
  mon-pix/app/components/certification-stepper-join.js
  mon-pix/app/components/stepper.js
  mon-pix/app/controllers/certifications/start.js
  mon-pix/app/models/certification-candidate.js
  mon-pix/app/routes/certifications/start.js
  mon-pix/app/services/peeker.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_certification-joiner.scss
  mon-pix/app/styles/components/_certification-starter.scss
  mon-pix/app/styles/pages/_certification-start.scss
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/components/certification-joiner.hbs
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/app/templates/components/certification-stepper-join.hbs
  mon-pix/config/environment.js
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/post-session-participation.js
  mon-pix/tests/acceptance/certification-course-test.js
  mon-pix/tests/integration/components/certification-starter-test.js
  mon-pix/tests/unit/adapters/certification-candidate-test.js
  mon-pix/tests/unit/components/certification-joiner-test.js
  mon-pix/tests/unit/components/certification-starter-test.js
  mon-pix/tests/unit/models/certification-candidate-test.js
  mon-pix/tests/unit/services/peeker-test.js
Labels: Func Review Needed, Tech Review Asked

#804 [TECH] Corriger le test d'acceptance de POST /answers
  api/tests/acceptance/application/answers/answer-controller-save_test.js
Labels: Tech Review Asked

#808 [BUGFIX] Ajout d'un état "loading" quand on clique sur le bouton de création de son compte (PF-904)
  mon-pix/app/components/signup-form.js
  mon-pix/app/templates/application.hbs
  mon-pix/app/templates/campaigns/fill-in-id-pix.hbs
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/tests/integration/components/signup-form-test.js
Labels: Func Review OK, Ready to Merge

#814 [BUGFIX] Une page oups! s'affichait lorsque l'utilisateur souhaitait voir ses certifications
  admin/app/transforms/date-only.js
  api/db/seeds/data/certification-courses-builder.js
  certif/app/transforms/date-only.js
  mon-pix/app/transforms/date-only.js
  orga/app/transforms/date-only.js
Labels: Func Review OK, Tech Review Asked

#809 [FEATURE] Choisir une épreuve aléatoirement par acquis puis par challenge (PF-900).
  api/lib/domain/services/smart-random/smart-random.js
Labels: Func Review OK, Tech Review Asked

#818 [FEATURE] Remplacement du mot campagne par parcours dans un message d'erreur (PF-914).
  mon-pix/app/controllers/campaigns/fill-in-campaign-code.js
  mon-pix/app/controllers/campaigns/join-restricted-campaign.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-campaign-code-test.js
  mon-pix/tests/unit/controllers/campaigns/join-restricted-campaign-test.js
Labels: Func Review Needed, Tech Review Asked

#815 [FEATURE] Ajouter un loader pendant le calcul des résultats collectifs (PO-275).
  orga/app/styles/app.scss
  orga/app/styles/globals/loading.scss
  orga/app/templates/authenticated/campaigns/details/collective-results-loading.hbs
Labels: Func Review OK, Tech Review Asked

#822 [FEATURE] Le champ Date de naissance doit tolérer le format apparemment commun 'DD/MM/YYYY (PC-32)
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-transformation-structures.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/lib/infrastructure/utils/date-utils.js
  api/tests/acceptance/application/session/files/import-certification-candidates-test-special-birthdate-ok.ods
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_test.js
  api/tests/unit/infrastructure/utils/date-utils_test.js
Labels: Func Review Needed, Tech Review Asked

#811 [TECH] Amélioration de l'intégration de Sentry dans l'API (PF-921)
  api/lib/config.js
  api/lib/plugins.js
  package-lock.json
  package.json
  scripts/release/publish.sh
Labels: Tech Review Asked

#816 [TECH] Remplacer les vrais emails générés par de faux en @example.net (PF-919).
  api/tests/acceptance/application/snapshot-controller_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  orga/mirage/factories/user.js
Labels: Ready to Merge

#760 [TECH] Ajout de tests e2e avec Cypress sur Pix Orga (PO-280)
  .circleci/config.yml
  high-level-tests/e2e/.eslintrc.js
  high-level-tests/e2e/cypress/fixtures/memberships.json
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/integration/campaign-management.feature
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/login.js
  high-level-tests/e2e/package.json
Labels: Ready to Merge

#817 [TECH] Supprimer un appel superflu sur la récupérations des utilisateurs dans Pix Admin (PA-115).
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/find-users.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/find-users_test.js
Labels: Ready to Merge

#829 [BUGFIX] Il arrive que le seeding soit en échec à cause d'une violation de contrainte d'unicité sur les emails de la table users
  api/db/seeds/seed.js
Labels: Tech Review Asked

#823 [FEATURE] Remplacer le rôle OWNER par ADMIN (PA-106).
  admin/app/models/membership.js
  admin/tests/acceptance/organization-memberships-management-test.js
  api/db/migrations/20191112121128_update_memberships_modify_organizationRole.js
  api/db/seeds/data/dragon-and-co-builder.js
  api/db/seeds/data/organizations-builder.js
  api/lib/application/organizations/index.js
  api/lib/application/usecases/checkUserIsAdminInOrganization.js
  api/lib/domain/models/Membership.js
  api/lib/domain/usecases/answer-to-organization-invitation.js
  api/lib/domain/usecases/create-membership.js
  api/lib/interfaces/controllers/security-controller.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/organization-invitation-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/application/usecases/checkUserIsAdminInOrganization_test.js
  api/tests/unit/domain/usecases/create-membership_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
  api/tests/unit/interfaces/controllers/security-controller_test.js
  high-level-tests/e2e/cypress/fixtures/memberships.json
  orga/app/models/membership.js
  orga/app/routes/authenticated/team.js
  orga/app/services/current-user.js
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/app/templates/components/sidebar-menu.hbs
  orga/mirage/scenarios/default.js
  orga/tests/acceptance/authentication-test.js
  orga/tests/acceptance/student-list-test.js
  orga/tests/acceptance/team-creation-test.js
  orga/tests/acceptance/team-list-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
  orga/tests/unit/services/current-user-test.js
Labels: Func Review OK, Tech Review Asked

#800 [TECH] Supprime Husky et le crochet d'avant commit (PF-922)
  package-lock.json
  package.json
  scripts/git-hook/prepend-commit-subject.js
Labels: Tech Review Asked

#785 [A11Y] Page inscription (PF-888).
  high-level-tests/e2e/cypress/integration/signup.feature
  high-level-tests/e2e/cypress/support/step_definitions/login.js
  mon-pix/app/components/form-textfield.js
  mon-pix/app/initializers/aria.js
  mon-pix/app/routes/inscription.js
  mon-pix/app/styles/components/_form-textfield.scss
  mon-pix/app/styles/components/_signup-form.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/application.hbs
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/app/templates/head.hbs
  mon-pix/app/templates/inscription.hbs
  mon-pix/app/templates/login.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/public/images/icons/icon-error.svg
  mon-pix/tests/integration/components/form-textfield-test.js
  mon-pix/tests/integration/components/signup-form-test.js
Labels: Func Review Needed, Tech Review Finished

#832 [FEATURE] Ne pas importer les élèves ayant une date de sortie dans le fichier SIECLE (PO-278).
  api/lib/domain/services/students-xml-service.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/domain/services/students-xml-service_test.js
Labels: Ready to Merge

#831 [FEATURE] Finaliser une session (PC-65).
  api/db/migrations/20191029103059_add_column_status_in_session.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/session.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/acceptance/application/session-controller_test.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/tooling/database-builder/factory/build-session.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  certif/app/adapters/session.js
  certif/app/components/action-button.js
  certif/app/components/routes/authenticated/sessions/details/parameters-tab.js
  certif/app/components/routes/authenticated/sessions/session-finalizer.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/app/models/session.js
  certif/app/router.js
  certif/app/routes/authenticated/sessions/finalize.js
  certif/app/routes/authenticated/sessions/update.js
  certif/app/styles/app.scss
  certif/app/styles/components/session-finalizer.scss
  certif/app/styles/globals/colors.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/app/templates/components/action-button.hbs
  certif/app/templates/components/routes/authenticated/sessions/details/parameters-tab.hbs
  certif/app/templates/components/routes/authenticated/sessions/session-finalizer.hbs
  certif/config/environment.js
  certif/public/images/loader-white.svg
  certif/tests/acceptance/session-details-test.js
  certif/tests/integration/components/action-button-test.js
  certif/tests/unit/routes/authenticated/sessions/finalize-test.js
Labels: Func Review Needed, Tech Review Asked

#821 [BUGFIX] Le compteur de questions en certification affiche NaN en cas de reprise (PF-909)
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/application/certification-courses/index.js
  api/lib/application/courses/course-controller.js
  api/lib/application/courses/index.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/services/course-service.js
  api/lib/domain/usecases/get-certification-course.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/lib/infrastructure/utils/error-manager.js
  api/lib/routes.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/application/courses/course-controller_test.js
  api/tests/unit/application/courses/index_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/domain/services/course-service_test.js
  api/tests/unit/domain/usecases/get-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
  mon-pix/app/components/certification-starter.js
  mon-pix/app/components/progress-bar.js
  mon-pix/app/models/assessment.js
  mon-pix/app/models/certification-course.js
  mon-pix/app/models/course.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/routes/certifications/resume.js
  mon-pix/app/routes/certifications/start.js
  mon-pix/mirage/config.js
  mon-pix/mirage/factories/certification-course.js
  mon-pix/mirage/routes/get-certification-course.js
  mon-pix/mirage/routes/post-certification-course.js
  mon-pix/mirage/routes/post-courses.js
  mon-pix/mirage/serializers/certification-course.js
  mon-pix/tests/acceptance/certification-course-test.js
  mon-pix/tests/acceptance/resume-certification-course-test.js
  mon-pix/tests/unit/components/certification-starter-test.js
  mon-pix/tests/unit/models/certification-course-test.js
  mon-pix/tests/unit/models/course-test.js
  mon-pix/tests/unit/routes/certifications/resume-test.js
Labels: Func Review OK, Tech Review Asked

#836 [BUGFIX] L'identifiant externe n'était pas recopié depuis les données candidat vers le certification course à la création de celui ci (PA-120)
  api/db/migrations/20191118173128_copy-external-id-from-candidate-to-course.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/tooling/airtable-builder/airtable-builder.js
  api/tests/tooling/airtable-builder/factory/build-certification-prerequisites.js
  api/tests/tooling/airtable-builder/factory/index.js
Labels: :rocket: Ready to Merge, Func Review OK, 📜 team-certif

#839 [BUGFIX] Supprimer les barres de scroll affichées en trop sur Pix Orga (PO-271).
  orga/app/styles/pages/authenticated.scss
Labels: Func Review OK, Tech Review OK, team-prescription

#833 [FEATURE] Afficher le rôle des membres dans Pix Orga (PO-210)
  api/lib/infrastructure/repositories/membership-repository.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  orga/app/models/membership.js
  orga/app/templates/components/routes/authenticated/team/list-items.hbs
  orga/tests/acceptance/team-list-test.js
  orga/tests/integration/components/routes/authenticated/team/list-items-test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-accès

#844 [BUGFIX] Afficher les prochaines notifications de succès après une fermeture (PF-913).
  mon-pix/app/components/levelup-notif.js
Labels: Func Review OK, Tech Review Needed, team-évaluation

#848 [FEATURE] Modification de certains textes dans la page de lancement de test de certification (PF-928)
  mon-pix/app/templates/components/certification-starter.hbs
Labels: :rocket: Ready to Merge, team-certif

#827 [BUGFIX] Une sur-erreur survient en cas de problème dans la méth…
  api/lib/domain/services/course-service.js
  api/tests/unit/domain/services/course-service_test.js
Labels: Func Review Needed, Tech Review Needed

#847 [FEATURE] Interdire l'import de candidats dans PixCertif lorsqu'il existe au moins un lien entre un candidat et un utilisateur Pix (PC-83)
  api/db/seeds/data/certification-candidates-builder.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/import-certification-candidates-from-attendance-sheet.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/tests/acceptance/application/session/session-controller-get-certification-candidates_test.js
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/unit/domain/usecases/import-certification-candidates-from-attendance-sheet_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/certification-candidate.js
  certif/app/styles/globals/colors.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates-tab.scss
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/app/templates/components/routes/authenticated/sessions/details/certification-candidates-tab.hbs
  certif/mirage/config.js
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/integration/components/routes/authenticated/sessions/details-item-test.js
  certif/tests/integration/components/routes/authenticated/sessions/details/certification-candidates-tab-test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#846 [A11Y] Ajouter ALT sur les images dans les challenges
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/datasources/airtable/objects/Challenge.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/infrastructure/datasources/airtable/models/Challenge_test.js
  mon-pix/app/models/challenge.js
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/tests/integration/components/challenge-statement-test.js
  mon-pix/tests/integration/components/comparison-window-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-évaluation

#835 [BUGFIX] Ignorer les espaces autour des noms des candidats de ce…
  api/db/migrations/20191115123716_trim_lastname_firstname_from_certification_candidate.js
  api/lib/domain/usecases/link-user-to-session-certification-candidate.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-transformation-structures.js
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-1_spaces_around_names_test.ods
  api/tests/integration/domain/services/certifications-ods-service/certifications-ods-service_test.js
  api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
  mon-pix/app/components/certification-joiner.js
  mon-pix/tests/unit/components/certification-joiner-test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#838 [FEATURE] Dupliquer le bouton d'export des résultats pour les prescripteurs sur la page d'info de session dans Pix Admin (PA-118)
  admin/app/controllers/authenticated/certifications/sessions/info/index.js
  admin/app/controllers/authenticated/certifications/sessions/info/list.js
  admin/app/routes/authenticated/certifications/sessions/info.js
  admin/app/routes/authenticated/certifications/sessions/info/list.js
  admin/app/styles/authenticated/certifications/sessions.scss
  admin/app/templates/authenticated/certifications/sessions/info/index.hbs
  admin/mirage/config.js
  admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js
  admin/tests/unit/controllers/authenticated/certifications/sessions/info/index-test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#857 [BUGFIX] Optimisation des appels de récupération des orgas (PO-281).
  api/lib/infrastructure/repositories/organization-repository.js
  api/scripts/add-target-profile-shares-to-organizations.js
  api/scripts/create-or-update-sco-organizations.js
  api/scripts/helpers/organizations-by-external-id-helper.js
  api/scripts/organizeOrganizationsByExternalId.js
  api/scripts/send-invitations-to-sco-organizations.js
  api/scripts/update-sco-organizations-with-is-managing-students-to-true.js
  api/tests/acceptance/scripts/add-target-profile-shares-to-organizations_test.js
  api/tests/acceptance/scripts/create-or-update-sco-organizations_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/unit/scripts/add-target-profile-shares-to-organizations_test.js
  api/tests/unit/scripts/helpers/organizations-by-external-id-helper_test.js
  api/tests/unit/scripts/organizeOrganizationsByExternalId.js
  api/tests/unit/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/unit/scripts/update-sco-organizations-with-is-managing-students-to-true_test.js
Labels: :steam_locomotive: EXPEDIT, Func Review Needed, Tech Review Needed, team-accès, team-prescription

#850 [FEATURE] Affichage du statut de la session dans PixAdmin (PA-119)
  admin/app/models/session.js
  admin/app/templates/authenticated/certifications/sessions/info/index.hbs
  admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js
  api/db/seeds/data/sessions-builder.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/domain/usecases/get-session.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/tooling/database-builder/factory/build-session.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  api/tests/unit/domain/usecases/get-session_test.js
Labels: Func Review OK, Tech Review OK, team-certif

#859 [FEATURE] Modification vocabulaire sur la page inscription (PF-940).
  admin/app/templates/components/organization-members-section.hbs
  api/lib/domain/usecases/create-user.js
  api/lib/domain/validators/user-validator.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/domain/validations/user-validator_test.js
  certif/app/templates/components/login-form.hbs
  mon-pix/app/components/signup-form.js
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/tests/integration/components/signup-form-test.js
  orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs
  orga/app/templates/components/routes/login-form.hbs
  orga/app/templates/components/routes/register-form.hbs
Labels: Func Review OK, Tech Review OK, team-accès, team-évaluation

#863 [BUGFIX] Eviter les erreurs 500 lors du check de date de naissance quand un candidat essaie de rejoindre une session de certification (PF-941)
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/link-user-to-session-certification-candidate.js
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/tests/acceptance/application/session/session-controller-create-certification-candidate-participation_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#860 [BUGFIX] Ajouter des line-break dans la consigne des challenges (PF-939).
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_qroc-solution-panel.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-évaluation

#855 [FEATURE] Afficher une zone grise à la place de l'image d'un challenge (PF-936).
  mon-pix/app/components/challenge-illustration.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_challenge-illustration.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/templates/components/challenge-illustration.hbs
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/tests/integration/components/challenge-illustration-test.js
  mon-pix/tests/integration/components/challenge-statement-test.js
  mon-pix/tests/integration/components/comparison-window-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-évaluation

#870 [BUGFIX] Utiliser overflow-wrap au lieu de word-break.
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_qroc-solution-panel.scss
Labels: :steam_locomotive: EXPEDIT, Func Review OK, Tech Review OK, team-évaluation

#849 [FEATURE] Ajouter une étape contenant un lien vers le formbuilder lors de la finalisation de la session (PC-85)
  api/lib/domain/errors.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  certif/app/components/app-modal.js
  certif/app/components/routes/authenticated/sessions/session-finalizer.js
  certif/app/components/session-finalization-formbuilder-link-step.js
  certif/app/components/session-finalization-step-container.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/models/session.js
  certif/app/routes/authenticated/sessions/finalize.js
  certif/app/styles/app.scss
  certif/app/styles/components/session-finalization-formbuilder-link-step.scss
  certif/app/styles/components/session-finalization-step-container.scss
  certif/app/styles/components/session-finalizer.scss
  certif/app/styles/globals/app-modal.scss
  certif/app/styles/globals/colors.scss
  certif/app/styles/globals/fonts.scss
  certif/app/styles/globals/panels.scss
  certif/app/styles/pages/authenticated/sessions.scss
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/app/templates/components/routes/authenticated/sessions/details/parameters-tab.hbs
  certif/app/templates/components/routes/authenticated/sessions/session-finalizer.hbs
  certif/app/templates/components/session-finalization-formbuilder-link-step.hbs
  certif/app/templates/components/session-finalization-step-container.hbs
  certif/config/environment.js
  certif/mirage/config.js
  certif/package-lock.json
  certif/package.json
  certif/public/icons/icon-close-modal.svg
  certif/public/icons/session-finalization-edit.svg
  certif/public/icons/session-finalization-send.svg
  certif/public/icons/session-finalization-user.svg
  certif/tests/acceptance/session-details-test.js
  certif/tests/acceptance/session-finalization-test.js
  certif/tests/integration/components/session-finalization-formbuilder-link-step-test.js
  certif/tests/integration/components/session-finalization-step-container-test.js
  certif/tests/unit/components/app-modal-test.js
Labels: Func Review OK, team-certif

#830 [FEATURE] Gérer la distance d'édition lors de la réconciliation d'un user avec un student (PF-851).
  api/lib/domain/services/solution-service-qroc.js
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/lib/domain/services/solution-service-utils.js
  api/lib/domain/services/string-comparison-service.js
  api/lib/domain/services/user-reconciliation-service.js
  api/lib/domain/services/validation-comparison.js
  api/lib/domain/services/validation-treatments.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/link-user-to-organization-student-data.js
  api/lib/infrastructure/repositories/student-repository.js
  api/tests/integration/domain/services/user-reconciliation-service_test.js
  api/tests/integration/infrastructure/repositories/student-repository_test.js
  api/tests/unit/domain/services/solution-service-utils_test.js
  api/tests/unit/domain/services/string-comparison-service_test.js
  api/tests/unit/domain/services/validation-comparison_test.js
  api/tests/unit/domain/services/validation-treatments_test.js
  api/tests/unit/domain/usecases/link-user-to-organization-student-data_test.js
Labels: :rocket: Ready to Merge

#862 [BUGFIX] Vérifier que le code d'accès correspond à la session de certif (PF 931)
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  mon-pix/app/components/certification-joiner.js
  mon-pix/app/components/certification-starter.js
  mon-pix/app/components/stepper.js
  mon-pix/app/controllers/certifications/start.js
  mon-pix/app/models/certification-course.js
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/app/templates/components/stepper.hbs
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/certification-course-test.js
  mon-pix/tests/unit/components/certification-starter-test.js
Labels: Func Review OK, Tech Review Needed, team-certif
