Repository 1024pix/pix, pull requests merged in 2019-10, with the labels that each got.

#728 [TECH] Harmonisation de l'import du PV de session dans PixAdmin avec l'existant (PA-112)
  admin/app/controllers/authenticated/certifications/sessions/info/list.js
  admin/app/services/file-reader.js
  admin/app/services/session-info-service.js
  admin/app/templates/authenticated/certifications/sessions/info/list.hbs
  admin/config/environment.js
  admin/mirage/config.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/certifications-parsing-uploaded-attendance-sheet-test.js
  admin/tests/unit/services/file-reader-test.js
  admin/tests/unit/services/session-info-service-test.js
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/domain/errors.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/services/certifications-ods-service.js
  api/lib/domain/services/session-xml-service.js
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/parse-certifications-data-from-attendance-sheet.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-candidates-table-headers.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-transformation-structures.js
  api/lib/infrastructure/utils/error-manager.js
  api/lib/infrastructure/utils/ods/common-ods-utils.js
  api/lib/infrastructure/utils/ods/read-ods-utils.js
  api/lib/infrastructure/utils/ods/write-ods-utils.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/acceptance/application/certifications/files/parse-from-attendance-sheet-test-ok.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_no_last_name_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/certifications-ods-service_test.js
  api/tests/integration/domain/services/ods-service/ods-service_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/infrastructure/services/ods-content-xml-service_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/integration/infrastructure/utils/ods/read-ods-utils-extract-table-data-from-ods-file-empty_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils-extract-table-data-from-ods-file_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils-get-content-xml_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/integration/infrastructure/utils/ods/write-ods-utils_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/get-attendance-sheet_test.js
Labels: Func Review OK, Ready to Merge, Tech Review Asked

#732 [BUGFIX] Corrige une typo dans la vérification cgu de Pix Certif (PC-75)
  certif/app/routes/authenticated/index.js
  certif/tests/unit/routes/authenticated-test.js
Labels: Ready to Merge

#731 [BUGFIX] Mise à jour via campagnes des scorecards remises à zéro (PF-841).
  api/lib/domain/models/Scorecard.js
  api/tests/unit/domain/models/Scorecard_test.js
Labels: Func Review Needed, Tech Review Asked

#738 [TECH] mon-pix: suppression du composant `course-banner`
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  mon-pix/app/components/course-banner.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/routes/assessments/results.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_course-banner.scss
  mon-pix/app/styles/pages/_assessment-challenge.scss
  mon-pix/app/styles/pages/_assessment-results.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/app/templates/components/course-banner.hbs
  mon-pix/config/environment.js
  mon-pix/mirage/data/assessments/ref-assessment.js
  mon-pix/tests/acceptance/challenge-commons-test.js
  mon-pix/tests/acceptance/course-ending-screen-test.js
  mon-pix/tests/unit/components/course-banner-test.js
Labels: Func Review OK, Tech Review Asked

#734 [BUGFIX] Optimise le chargement de la bannière de reprise de campagne (PF-840).
  mon-pix/app/components/resume-campaign-banner.js
  mon-pix/tests/acceptance/profile-test.js
  mon-pix/tests/integration/components/resume-campaign-banner-test.js
  mon-pix/tests/unit/components/resume-campaign-banner-test.js
Labels: Func Review OK, Tech Review Asked

#736 [BUGFIX] Permettre de nouveau l'export des snapshots - profil v1 (PF-844).
  mon-pix/app/components/routes/board-page.js
  mon-pix/tests/acceptance/board-organization-test.js
  mon-pix/tests/integration/components/routes/board-page-test.js
Labels: Ready to Merge

#741 [BUGFIX] Polir le titre des checkpoints (PF-823).
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/templates/assessments/checkpoint.hbs
Labels: Func Review Needed, Tech Review Asked

#725 [TECH] Diviser le PATCH /users/id (PF-831).
  api/lib/application/preHandlers/user-existence-verification.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/services/reset-password-service.js
  api/lib/domain/usecases/accept-pix-certif-terms-of-service.js
  api/lib/domain/usecases/accept-pix-orga-terms-of-service.js
  api/lib/domain/usecases/update-user-password.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/users/accept-pix-certif-terms-of-service_test.js
  api/tests/acceptance/application/users/accept-pix-orga-terms-of-service_test.js
  api/tests/acceptance/application/users/update-password_test.js
  api/tests/acceptance/application/users/users-controller-update_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/unit/application/passwords/password-controller_test.js
  api/tests/unit/application/preHandlers/user-existence-verification_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/services/reset-password-service_test.js
  api/tests/unit/domain/usecases/accept-pix-certif-terms-of-service_test.js
  api/tests/unit/domain/usecases/accept-pix-orga-terms-of-service_test.js
  api/tests/unit/domain/usecases/update-user-password_test.js
  certif/app/adapters/user.js
  certif/app/controllers/authenticated/terms-of-service.js
  certif/mirage/config.js
  certif/tests/acceptance/terms-of-service-test.js
  certif/tests/unit/adapters/user-test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/reset-password-form.js
  mon-pix/mirage/config.js
  mon-pix/tests/integration/components/reset-password-form-test.js
  mon-pix/tests/unit/adapters/user-test.js
  orga/app/adapters/user.js
  orga/app/controllers/authenticated/terms-of-service.js
  orga/mirage/config.js
  orga/tests/acceptance/terms-of-service-test.js
  orga/tests/unit/adapters/user-test.js
Labels: Ready to Merge

#715 [FEATURE] Création d'une invitation pour rejoindre une Organisation (PO-238).
  api/db/migrations/20190910165023_create_organization_invitations_table.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/OrganizationInvitation.js
  api/lib/domain/usecases/accept-organization-invitation.js
  api/lib/domain/usecases/create-organization-invitation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/organization-invitation.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/lib/infrastructure/repositories/organization-invitation-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-invitation-serializer.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
  api/tests/tooling/database-builder/factory/build-organization-invitation.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-organization-invitation.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/models/OrganizationInvitation_test.js
  api/tests/unit/domain/usecases/accept-organization-invitation_test.js
  api/tests/unit/domain/usecases/create-organization-invitation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-invitation-serializer_test.js
  orga/app/adapters/membership.js
  orga/app/adapters/organization-invitation.js
  orga/app/controllers/authenticated/team/new.js
  orga/app/models/organization-invitation.js
  orga/app/routes/authenticated/team/new.js
  orga/app/templates/authenticated/team/new.hbs
  orga/app/templates/components/routes/authenticated/team/list-items.hbs
  orga/app/templates/components/routes/authenticated/team/new-item.hbs
  orga/mirage/config.js
  orga/tests/acceptance/team-creation-test.js
  orga/tests/integration/components/routes/authenticated/team/new-item-test.js
  orga/tests/unit/models/organization-invitation-test.js
Labels: Func Review OK, Tech Review Asked

#733 [FEATURE] Modifier la version du PV de session (PC-64)
  api/db/migrations/20190930115538_rename_column_birthplace_into_birthCity_in_certification_candidates.js
  api/db/migrations/20190930121453_add_columns_birthProvinceCode_and_birthCity_to_certification_candidates.js
  api/db/seeds/data/certification-candidates-builder.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/services/certifications-ods-service.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-placeholders.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-transformation-structures.js
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template.ods
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/lib/infrastructure/utils/ods/read-ods-utils.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/acceptance/application/certifications/files/parse-from-attendance-sheet-test-ok.ods
  api/tests/acceptance/application/session/files/import-certification-candidates-test-ko-invalid-data.ods
  api/tests/acceptance/application/session/files/import-certification-candidates-test-ko-invalid-file.ods
  api/tests/acceptance/application/session/files/import-certification-candidates-test-ok.ods
  api/tests/acceptance/application/session/session-controller-get-certification-candidates_test.js
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-0_extract_mandatory_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-0_extract_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-0_extract_wrongvalue_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-1_extract_mandatory_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-1_extract_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-1_extract_wrongvalue_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-0_no_last_name_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-0_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-1_no_last_name_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-1_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/certifications-ods-service_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/attendance_sheet_template_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/integration/infrastructure/utils/ods/get-content-xml_test.ods
  api/tests/integration/infrastructure/utils/ods/ods-file_table-empty_test.ods
  api/tests/integration/infrastructure/utils/ods/ods-file_test.ods
  api/tests/integration/infrastructure/utils/ods/ods-file_unknown-version_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils-extract-table-data-from-ods-file-empty_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils-extract-table-data-from-ods-file_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/integration/infrastructure/utils/ods/write-ods-utils_test.js
  api/tests/tooling/database-builder/factory/build-certification-candidate.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js
  certif/app/models/certification-candidate.js
  certif/app/templates/components/routes/authenticated/sessions/details/certification-candidates-tab.hbs
  certif/tests/integration/components/routes/authenticated/sessions/details/certification-candidates-tab-test.js
Labels: Func Review OK, Tech Review Asked

#718 [TECH] Réduire la taille des données sorties de Airtable (PF-729).
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/caches/preloader.js
  api/lib/infrastructure/datasources/airtable/AirtableResourceNotFound.js
  api/lib/infrastructure/datasources/airtable/area-datasource.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/competence-datasource.js
  api/lib/infrastructure/datasources/airtable/course-datasource.js
  api/lib/infrastructure/datasources/airtable/objects/Area.js
  api/lib/infrastructure/datasources/airtable/objects/Challenge.js
  api/lib/infrastructure/datasources/airtable/objects/Competence.js
  api/lib/infrastructure/datasources/airtable/objects/Course.js
  api/lib/infrastructure/datasources/airtable/objects/Skill.js
  api/lib/infrastructure/datasources/airtable/objects/Tutorial.js
  api/lib/infrastructure/datasources/airtable/objects/index.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/datasources/airtable/tutorial-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/course-repository.js
  api/lib/infrastructure/serializers/airtable/course-serializer.js
  api/tests/integration/infrastructure/airtable_test.js
  api/tests/unit/infrastructure/caches/preloader_test.js
  api/tests/unit/infrastructure/datasources/airtable/area-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/competence-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/models/Course_test.js
  api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
  api/tests/unit/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/infrastructure/repositories/course-repository_test.js
  api/tests/unit/infrastructure/serializers/airtable/course-serializer_test.js
Labels: Tech Review Asked, 🚫Blocked

#737 [TECH] Appliquer le pattern datasource sur course-repository
  api/lib/infrastructure/datasources/airtable/course-datasource.js
  api/lib/infrastructure/datasources/airtable/objects/Course.js
  api/lib/infrastructure/datasources/airtable/objects/index.js
  api/lib/infrastructure/repositories/course-repository.js
  api/lib/infrastructure/serializers/airtable/course-serializer.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/models/Course_test.js
  api/tests/unit/infrastructure/repositories/course-repository_test.js
  api/tests/unit/infrastructure/serializers/airtable/course-serializer_test.js
Labels: Tech Review Asked

#744 [TECH] Mise à jour des scripts e2e et de la documentation associée.
  high-level-tests/e2e/README.md
  high-level-tests/e2e/package.json
Labels: Ready to Merge

#746 [TECH] Réduire la taille des données sorties de Airtable (PF-729).
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/caches/preloader.js
  api/lib/infrastructure/datasources/airtable/AirtableResourceNotFound.js
  api/lib/infrastructure/datasources/airtable/area-datasource.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/competence-datasource.js
  api/lib/infrastructure/datasources/airtable/course-datasource.js
  api/lib/infrastructure/datasources/airtable/objects/Area.js
  api/lib/infrastructure/datasources/airtable/objects/Challenge.js
  api/lib/infrastructure/datasources/airtable/objects/Competence.js
  api/lib/infrastructure/datasources/airtable/objects/Course.js
  api/lib/infrastructure/datasources/airtable/objects/Skill.js
  api/lib/infrastructure/datasources/airtable/objects/Tutorial.js
  api/lib/infrastructure/datasources/airtable/objects/index.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/datasources/airtable/tutorial-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/integration/infrastructure/airtable_test.js
  api/tests/unit/infrastructure/caches/preloader_test.js
  api/tests/unit/infrastructure/datasources/airtable/area-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/competence-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
  api/tests/unit/infrastructure/repositories/challenge-repository_test.js
Labels: Tech Review Finished

#748 [BSR] Un fichier de test était vide et donc inutile
  api/tests/acceptance/application/users/users-controller-update_test.js
Labels: Tech Review Asked

#749 [TECH] Mise en place d'un tunnel pour démarrer la certification (PF-382).
  mon-pix/app/components/certification-starter.js
  mon-pix/app/components/certification-stepper-start.js
  mon-pix/app/components/stepper.js
  mon-pix/app/mixins/progression-tracker.js
  mon-pix/app/routes/certifications/resume.js
  mon-pix/app/routes/certifications/start.js
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/app/templates/components/certification-stepper-start.hbs
  mon-pix/app/templates/components/stepper.hbs
  mon-pix/tests/integration/components/certification-starter-test.js
  mon-pix/tests/unit/components/certification-starter-test.js
  mon-pix/tests/unit/mixins/progression-tracker-test.js
  mon-pix/tests/unit/routes/certifications/start-test.js
Labels: Tech Review Asked

#713 [TECH] S'assurer que les ids sont toujours traités en tant qu'entier
  api/lib/application/answers/answer-controller.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/campaignParticipations/campaign-participation-controller.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certifications/certification-controller.js
  api/lib/application/organizations/organization-controller.js
  api/lib/application/preHandlers/assessment-authorization.js
  api/lib/application/preHandlers/snapshot-authorization.js
  api/lib/application/preHandlers/user-existence-verification.js
  api/lib/application/scorecards/scorecard-controller.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/complete-assessment.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/find-answer-by-challenge-and-assessment.js
  api/lib/domain/usecases/get-answer.js
  api/lib/domain/usecases/get-correction-for-answer.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/get-user-certification-with-result-tree.js
  api/lib/interfaces/controllers/security-controller.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/get-user-certification-with-result-tree_test.js
Labels: Tech Review Asked

#735 [FEATURE] Restreindre les campagnes aux étudiants d'une organisation (PF-816).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/domain/usecases/get-campaign-by-code.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-campaign-information.js
  api/lib/infrastructure/repositories/student-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/student-repository_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/usecases/get-campaign-by-code_test.js
  api/tests/unit/domain/usecases/retrieve-campaign-information_test.js
  mon-pix/app/controllers/campaigns/fill-in-campaign-code.js
  mon-pix/app/templates/campaigns/start-or-resume-error.hbs
  mon-pix/tests/acceptance/start-campaigns-test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-campaign-code-test.js
Labels: Func Review OK, Tech Review Asked

#758 [FEATURE] Envoyer un e-mail pour inviter un utilisateur Pix à rejoindre une organisation (PO-244).
  api/db/migrations/20191004111924_add_temporaryKey_to_organizationInvitations.js
  api/lib/application/organization-invitations/index.js
  api/lib/application/organization-invitations/organization-invitation-controller.js
  api/lib/application/organizations/organization-controller.js
  api/lib/config.js
  api/lib/domain/models/OrganizationInvitation.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/accept-organization-invitation.js
  api/lib/domain/usecases/add-organization-membership-with-email.js
  api/lib/domain/usecases/answer-to-organization-invitation.js
  api/lib/domain/usecases/create-organization-invitation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/mailjet.js
  api/lib/infrastructure/repositories/organization-invitation-repository.js
  api/lib/routes.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/organization-invitation-controller_test.js
  api/tests/integration/application/organization-invitations/index_test.js
  api/tests/integration/application/organization-invitations/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
  api/tests/tooling/database-builder/factory/build-organization-invitation.js
  api/tests/tooling/domain-builder/factory/build-organization-invitation.js
  api/tests/unit/application/organization-invitations/index_test.js
  api/tests/unit/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/models/OrganizationInvitation_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/accept-organization-invitation_test.js
  api/tests/unit/domain/usecases/add-organization-membership-with-email_test.js
  api/tests/unit/domain/usecases/answer-to-organization-invitation_test.js
  api/tests/unit/domain/usecases/create-organization-invitation_test.js
  orga/app/adapters/organization-invitation-response.js
  orga/app/adapters/organization-invitation.js
  orga/app/models/organization-invitation-response.js
  orga/app/router.js
  orga/app/routes/invitations.js
  orga/app/templates/authenticated/team/new.hbs
  orga/app/templates/components/routes/authenticated/team/list-items.hbs
  orga/app/templates/components/routes/authenticated/team/new-item.hbs
  orga/mirage/config.js
  orga/tests/acceptance/invitations-test.js
  orga/tests/acceptance/team-creation-test.js
  orga/tests/unit/adapters/organization-invitation-response-test.js
  orga/tests/unit/models/organization-invitation-rresponse-test.js
  orga/tests/unit/routes/invitations-test.js
Labels: Development in progress, Func Review OK, Tech Review Asked, 🌟Etoile

#752 [BUGFIX] Des réponses trop longues envoyées dans les signalements (PF-865).
  api/db/migrations/20191008142311_alter_feedback_answer_column_to_text.js
Labels: Func Review OK, Tech Review Asked

#739 [FEATURE] Modification du design de la page de lancement de test de certification (PF-849)
  mon-pix/app/styles/components/_certification-starter.scss
  mon-pix/app/styles/pages/_certification-start.scss
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Func Review Needed, Tech Review Asked

#754 [FEATURE] Limiter la taille des messages de feedbacks (PF-864).
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/templates/components/feedback-panel.hbs
Labels: Func Review OK, Tech Review Asked

#730 [FEATURE] Nouveau design pour les challenges. (PF-794)
  mon-pix/app/components/certification-progress.js
  mon-pix/app/components/certification-starter.js
  mon-pix/app/components/progress-bar.js
  mon-pix/app/models/assessment-progression.js
  mon-pix/app/models/assessment.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_assessment-banner.scss
  mon-pix/app/styles/components/_certification-banner.scss
  mon-pix/app/styles/components/_certification-progress.scss
  mon-pix/app/styles/components/_certification-result.scss
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_challenge-response.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/components/_progress-bar.scss
  mon-pix/app/styles/components/_timeout-jauge.scss
  mon-pix/app/styles/globals/_palette.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
  mon-pix/app/styles/pages/_assessment-results.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/assessments/rating.hbs
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/app/templates/challenge-preview.hbs
  mon-pix/app/templates/components/assessment-banner.hbs
  mon-pix/app/templates/components/certification-banner.hbs
  mon-pix/app/templates/components/certification-progress.hbs
  mon-pix/app/templates/components/certification-results-page.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/app/templates/components/progress-bar.hbs
  mon-pix/app/utils/color-gradient.js
  mon-pix/tests/acceptance/challenge-commons-test.js
  mon-pix/tests/acceptance/challenge-page-banner-test.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/resume-competence-evaluations-test.js
  mon-pix/tests/acceptance/start-campaigns-test.js
  mon-pix/tests/integration/components/certification-banner-test.js
  mon-pix/tests/unit/components/certification-progress-test.js
  mon-pix/tests/unit/components/certification-starter-test.js
  mon-pix/tests/unit/components/progress-bar-test.js
  mon-pix/tests/unit/models/assessment-progress-test.js
Labels: Func Review Needed, Tech Review Asked

#750 [FEATURE] Indiquer à l'utilisateur s'il est certifiable (PF-751)
  api/lib/application/sessions/session-controller.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/CertificationProfile.js
  api/lib/domain/models/UserCompetence.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/services/session-code-service.js
  api/lib/domain/services/session-service.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/find-sessions.js
  api/lib/domain/usecases/get-session.js
  api/lib/domain/usecases/get-user-current-certification-profile.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-profile-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/users-controller-get-certification-profile_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/domain/services/user-service_get-profile-to-certify_test.js
  api/tests/integration/domain/services/user-service_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/CertificationProfile_test.js
  api/tests/unit/domain/models/UserCompetence_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/services/session-code-service_test.js
  api/tests/unit/domain/services/session-service_test.js
  api/tests/unit/domain/usecases/find-sessions_test.js
  api/tests/unit/domain/usecases/get-session_test.js
  api/tests/unit/domain/usecases/get-user-current-certification-profile_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/components/certification-not-certifiable.js
  mon-pix/app/models/certification-profile.js
  mon-pix/app/models/user.js
  mon-pix/app/routes/certifications/start.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_certification-not-certifiable.scss
  mon-pix/app/templates/certifications/start-error.hbs
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/components/certification-not-certifiable.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/get-certification-profile.js
  mon-pix/mirage/serializers/user.js
  mon-pix/tests/acceptance/certification-course-test.js
  mon-pix/tests/integration/components/certification-not-certifiable-test.js
  mon-pix/tests/unit/models/certification-profile-test.js
Labels: Func Review Needed, Tech Review Asked

#777 [BUGFIX] Initialiser les UserCompetences sans skills ni challenges
  api/lib/domain/models/UserCompetence.js
  api/tests/unit/domain/models/UserCompetence_test.js
Labels: Tech Review Asked

#756 [FEATURE] Lister les invitations sur la page équipe (PO-239)
  api/db/seeds/data/dragon-and-co-builder.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/models/Organization.js
  api/lib/domain/usecases/find-pending-organization-invitations.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/organization-invitation-repository.js
  api/lib/infrastructure/serializers/jsonapi/membership-serializer.js
  api/lib/infrastructure/serializers/jsonapi/organization-invitation-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-memberships_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
  api/tests/tooling/database-builder/factory/build-organization-invitation.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-pending-organization-invitations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-invitation-serializer_test.js
  orga/app/models/organization-invitation.js
  orga/app/models/organization.js
  orga/app/routes/authenticated/team/list.js
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/templates/authenticated/team/list.hbs
  orga/app/templates/components/routes/authenticated/team/list-items.hbs
  orga/mirage/config.js
  orga/mirage/factories/organization-invitation.js
  orga/mirage/scenarios/default.js
  orga/mirage/serializers/organization.js
  orga/tests/acceptance/team-creation-test.js
  orga/tests/acceptance/team-list-test.js
  orga/tests/integration/components/routes/authenticated/team/list-items-test.js
Labels: Func Review OK, Tech Review Asked

#762 [DOC] Lien vers les teams Pix cassé dans le README du repo Pix.
  README.md
Labels: Tech Review Asked

#772 [BUGFIX] Affiche correctement la progression.
  mon-pix/app/components/certification-progress.js
  mon-pix/app/components/progress-bar.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_certification-progress.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/components/certification-progress.hbs
  mon-pix/app/templates/components/progress-bar.hbs
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/unit/components/certification-progress-test.js
  mon-pix/tests/unit/components/progress-bar-test.js
Labels: Func Review OK, Tech Review Asked

#757 [FEATURE] Affichage d'un badge pour des profils cibles (PF-779).
  api/db/seeds/data/target-profile-builder.js
  api/db/seeds/seed.js
  mon-pix/app/controllers/campaigns/skill-review.js
  mon-pix/app/models/campaign.js
  mon-pix/app/models/target-profile.js
  mon-pix/app/routes/campaigns/skill-review.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/public/images/badges/Pix-emploi.svg
  mon-pix/public/images/badges/Pret-CleaNum.svg
  mon-pix/tests/unit/controllers/campaigns/skill-review-test.js
Labels: Func Review Needed, Tech Review Finished, 🚫Blocked

#781 [BUGFIX] Correction du style pour la page compétence sous IE (PF-860).
  mon-pix/app/styles/components/_certification-not-certifiable.scss
  mon-pix/app/styles/components/_scorecard-details.scss
Labels: Func Review OK, Tech Review Finished

#782 [FEATURE] Ajout d'une bannière pour staging
  mon-pix/app/components/warning-banner.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_warning-banner.scss
  mon-pix/app/templates/application.hbs
  mon-pix/app/templates/components/warning-banner.hbs
  mon-pix/config/environment.js
  mon-pix/tests/integration/components/warning-banner-test.js
Labels: Func Review OK, Tech Review Asked

#784 [BUGFIX] Télécharger les résultats CSV de grosses campagne (PO-257).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/start-writing-campaign-results-to-stream.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
Labels: Func Review OK, Tech Review Asked

#787 [FEATURE] Afficher une bannière bravo qd l'utilisateur est certi… PF-858
  mon-pix/app/components/congratulations-certification-banner.js
  mon-pix/app/controllers/certifications/start.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_congratulations-certification-banner.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/pages/_certification-start.scss
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/components/congratulations-certification-banner.hbs
Labels: Func Review OK, Tech Review Asked

#792 [FEATURE] Supprimer l'encadré d'information du nouveau profil (PF-887).
  api/db/migrations/20191028171724_delete_column_hasSeenNewProfileInfo_users_table.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/remember-user-has-seen-new-profile-info.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/remember-user-has-seen-new-profile-info_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/remember-user-has-seen-new-profile-info_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/controllers/profile.js
  mon-pix/app/models/user.js
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/pages/_profile.scss
  mon-pix/app/templates/profile.hbs
  mon-pix/mirage/config.js
  mon-pix/tests/acceptance/profile-test.js
  mon-pix/tests/unit/adapters/user-test.js
Labels: Func Review OK, Tech Review Asked

#795 [BUGFIX] User connecté /index redirigé vers /campagnes (PO-264).
  orga/app/routes/login.js
  orga/tests/acceptance/authentication-test.js
Labels: Func Review OK, Tech Review Asked

#798 [FEATURE] Ajout d'un bouton de navigation sur Pix Orga (PO-252).
  orga/app/components/sidebar-menu.js
  orga/app/styles/components/sidebar-menu.scss
  orga/app/styles/globals/colors.scss
  orga/app/templates/authenticated.hbs
  orga/app/templates/components/sidebar-menu.hbs
  orga/tests/acceptance/authentication-test.js
Labels: Func Review OK, Tech Review Asked

#801 [BUGFIX] Problème de calcul de passage de niveau pour les succès (PF-897).
  api/lib/domain/models/Scorecard.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/tests/tooling/domain-builder/factory/build-user-scorecard.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Labels: Func Review OK

#770 [FEATURE] Script d'import / update des organisations (PF-764).
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/create-organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/scripts/create-or-update-sco-organizations.js
  api/scripts/default-sco-organization-logo-base64.js
  api/scripts/helpers/csvHelpers.js
  api/tests/acceptance/scripts/create-or-update-sco-organizations_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/create-organization_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/helpers/file_with_bad_extension.html
  api/tests/unit/scripts/helpers/valid-organizations-test-file.csv
Labels: Func Review OK, Tech Review Asked
