Repository 1024pix/pix, pull requests merged in 2020-10, with the labels that each got.

#1924 [TECH] Utilisation du modèle TargetProfileWithLearningContent dans le calcul des résultats collectifs
  api/lib/domain/models/CampaignCompetenceCollectiveResult.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/models/TargetedArea.js
  api/lib/domain/usecases/compute-campaign-collective-result.js
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/airtable-builder/factory/learning-content/build-learning-content.js
  api/tests/tooling/domain-builder/factory/build-campaign-competence-collective-result.js
  api/tests/tooling/domain-builder/factory/build-targeted-area.js
  api/tests/unit/domain/models/CampaignCompetenceCollectiveResult_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  api/tests/unit/domain/models/TargetedArea_test.js
  api/tests/unit/domain/models/TargetedTube_test.js
  api/tests/unit/domain/usecases/compute-campaign-collective-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-collective-result-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK

#1893 [CLEANUP] Interdire les textes non traduits dans les templates de pix app
  mon-pix/.template-lintrc.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sco.js
  mon-pix/app/components/routes/campaigns/restricted/join-sup.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sup.js
  mon-pix/app/components/routes/campaigns/restricted/user-information-form.hbs
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/templates/campaigns/restricted/join.hbs
  mon-pix/app/templates/competences/results.hbs
  mon-pix/app/templates/components/certification-joiner.hbs
  mon-pix/app/templates/components/congratulations-certification-banner.hbs
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/app/templates/components/reset-password-form.hbs
  mon-pix/app/templates/components/routes/login-form.hbs
  mon-pix/app/templates/components/routes/login-or-register.hbs
  mon-pix/app/templates/components/routes/register-form.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/app/templates/components/update-expired-password-form.hbs
  mon-pix/app/templates/components/warning-page.hbs
  mon-pix/app/templates/not-connected.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/app/templates/update-expired-password.hbs
  mon-pix/app/templates/user-tutorials.hbs
  mon-pix/app/utils/errors-messages.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/integration/components/routes/login-form-test.js
  mon-pix/tests/integration/components/routes/login-or-register-test.js
  mon-pix/tests/integration/components/routes/register-form-test.js
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sco-test.js
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sup-test.js
  mon-pix/tests/unit/components/update-expired-password_test.js
  mon-pix/tests/unit/utils/errors-messages-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces, team-prescription

#1939 [TECH] Suppression de JQuery dans pix-app
  mon-pix/.eslintrc.js
  mon-pix/app/helpers/strip-instruction.js
  mon-pix/app/services/google-recaptcha.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#1923 [FEATURE] Affichage de la liste filtrée et paginée des profils cibles dans Pix Admin (PIX-1322).
  admin/app/adapters/target-profile.js
  admin/app/components/menu-bar.hbs
  admin/app/components/target-profiles/list-items.hbs
  admin/app/controllers/authenticated/target-profiles/list.js
  admin/app/router.js
  admin/app/routes/authenticated/target-profiles/list.js
  admin/app/templates/authenticated/target-profiles.hbs
  admin/app/templates/authenticated/target-profiles/list.hbs
  admin/mirage/config.js
  admin/tests/acceptance/target-profiles-list-test.js
  admin/tests/integration/components/menu-bar-test.js
  admin/tests/integration/components/routes/authenticated/target-profiles/list-items-test.js
  admin/tests/unit/adapters/target-profile-test.js
  admin/tests/unit/controllers/authenticated/target-profiles/list-test.js
  admin/tests/unit/routes/authenticated/target-profiles/list-test.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/usecases/find-paginated-filtered-target-profiles.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-serializer.js
  api/lib/routes.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-target-profiles_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1922 [FEATURE] Réconcilier un utilisateur venant du GAR dans une nouvelle organisation (PIX-1244).
  api/db/seeds/data/organizations-builder.js
  mon-pix/app/controllers/campaigns/restricted/login-or-register-to-access.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/unit/controllers/campaigns/restricted/login-or-register-to-access-test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#1946 [TECH] Utiliser une version stable de la dépendance jwt-decode.
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, Tech Review Needed, team-acces

#1945 [TECH] Permet de récupérer les éléments dom par une sous chaîne avec la méthode contains.
  mon-pix/tests/helpers/contains.js
  mon-pix/tests/unit/helpers/contains-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#1930 [FEATURE] Ajout d'un email pour l'envoie des résultats au(x) prescripteur(s) (PIX-974)
  api/db/migrations/20200928163952_add-result-recipient-email-column-certification-candidates.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/tests/acceptance/application/session/session-controller-get-certification-candidates_test.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/tooling/database-builder/factory/build-certification-candidate.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/certification-candidate-in-staging-item.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/certification-candidate.js
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/config/environment.js
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates-test.js
Labels: :rocket: Ready to Merge, team-certif

#1860 [FEATURE] Générer les tests de certif à partir des acquis validés directs (et plus des épreuves bien répondues) (PIX-968)
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/KnowledgeElement.js
  api/lib/domain/models/UserCompetence.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/services/placement-profile-service.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/scripts/generate-certification-test-statistics.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/integration/domain/services/pick-certification-challenge_test.js
  api/tests/integration/domain/services/placement-profile-service_test.js
  api/tests/integration/domain/usecases/get-campaign-profile_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/KnowledgeElement_test.js
  api/tests/unit/domain/models/UserCompetence_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
Labels: :rocket: Ready to Merge, team-certif

#1936 [FEATURE] Ajout du bouton de téléchargement du PV de session dans le header (PIX-985)
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/models/session.js
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/tests/acceptance/session-details-test.js
  certif/tests/unit/models/session-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1935 [FEATURE] Import d'une liste de candidats à une session avec le nouveau modèle (PIX-1336)
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/usecases/get-candidates-import-sheet.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-transformation-structures.js
  api/lib/infrastructure/files/candidates-import/candidates-import-placeholders.js
  api/lib/infrastructure/files/candidates-import/candidates_import_template.ods
  api/lib/infrastructure/utils/ods/read-ods-utils.js
  api/lib/infrastructure/utils/ods/write-ods-utils.js
  api/tests/acceptance/application/session/session-controller-get-candidates-import-sheet_test.js
  api/tests/integration/domain/usecases/get-candidates-import-sheet/candidates_import_template.ods
  api/tests/integration/domain/usecases/get-candidates-import-sheet/get-candidates-import-sheet_test.js
  api/tests/integration/infrastructure/utils/ods/files/simple-attendance_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/session.js
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1895 [DOC] Mise à jour du workflow de connexion GAR.
  docs/security/authenticate_external_IDP.puml
  docs/security/authenticate_external_IDP_overview.puml
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#1942 [TECH] Linter les templates de pix-orga dans la CI.
  .circleci/config.yml
  orga/.template-lintrc.js
  orga/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#1941 [BSR] Factorisation de la fonction du Server FailAction dans API (PIX-1343).
  api/lib/application/authentication/index.js
  api/lib/application/http-errors.js
  api/lib/application/memberships/index.js
  api/lib/application/organization-invitations/index.js
  api/lib/application/organizations/index.js
  api/lib/application/schooling-registration-dependent-users/index.js
  api/lib/application/schooling-registration-user-associations/index.js
  api/lib/application/student-user-associations/index.js
  api/lib/application/users/index.js
  api/lib/validate.js
  api/server.js
  api/tests/acceptance/application/session/session-controller-create-certification-candidate-participation_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/server/server_test.js
  api/tests/unit/validate_test.js
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed, cross-team, team-acces, team-captains, team-certif

#1933 [FEATURE] Afficher les informations de crédit d'une organisation (PIX-1287)
  api/db/seeds/data/organizations-builder.js
  api/lib/infrastructure/repositories/prescriber-repository.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/tests/acceptance/application/prescriber-controller_test.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  orga/app/components/organization-credit-info.hbs
  orga/app/components/organization-credit-info.js
  orga/app/models/organization.js
  orga/app/styles/app.scss
  orga/app/styles/components/organization-credit-info.scss
  orga/app/styles/pages/authenticated.scss
  orga/app/templates/authenticated.hbs
  orga/config/icons.js
  orga/tests/acceptance/authentication-test.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/organization-credit-info-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1917 [FEATURE] Affichage de l'aide pour la saisie de l'identifiant externe (PIX-1295).
  api/db/migrations/20201001165441_create-help-external-id-in-campaigns.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/models/Campaign.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/tooling/database-builder/factory/build-campaign.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  mon-pix/app/components/routes/campaigns/fill-in-participant-external-id.hbs
  mon-pix/app/components/routes/campaigns/fill-in-participant-external-id.js
  mon-pix/app/controllers/campaigns/fill-in-id-pix.js
  mon-pix/app/controllers/campaigns/fill-in-participant-external-id.js
  mon-pix/app/models/campaign.js
  mon-pix/app/router.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/fill-in-participant-external-id.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/_fill-in-participant-external-id.scss
  mon-pix/app/templates/campaigns/fill-in-id-pix.hbs
  mon-pix/app/templates/campaigns/fill-in-participant-external-id.hbs
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/integration/components/routes/campaigns/fill-in-participant-external-id-test.js
  mon-pix/tests/unit/components/routes/campaigns/fill-in-participant-external-id-test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-id-pix-test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-participant-external-id-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1951 [BUGFIX] Déplacement d'acquis mal pris en compte dans l'export CSV des campagnes d'évaluation et dans le calcul du résultat individuel (PIX-1346)
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/read-models/CampaignAssessmentParticipationCompetenceResult.js
  api/lib/domain/read-models/CampaignAssessmentParticipationResult.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  api/tests/unit/domain/read-models/CampaignAssessmentParticipationCompetenceResult_test.js
  api/tests/unit/domain/read-models/CampaignAssessmentParticipationResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-result-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1957 [BUGFIX] Remettre la pagination à zéro sur la page équipe de Pix Orga (PIX-1281).
  orga/app/routes/authenticated/team/list.js
  orga/tests/acceptance/team-list-test.js
Labels: :rocket: Ready to Merge, team-acces

#1952 [DOC] Ajout d'une ADR pour le choix d'une solution pour générer du PDF
  docs/adr/0013-generer-des-fichiers-pdf.md
  docs/assets/attestation_WF_V2-simple-filigrame.pdf
Labels: :rocket: Ready to Merge, cross-team, team-certif

#1962 [BUGFIX] Permettre à la CI de détecter les erreurs de tests.
  api/package.json
Labels: :rocket: Ready to Merge, cross-team, team-captains

#1956 [FEATURE] Masquer les acquis dans l'export CSV d'une organisation SCO (PIX-1104)
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1961 [FEATURE] Affichage du détail d'un profil cible dans Pix Admin (PIX-1349).
  admin/app/adapters/target-profile.js
  admin/app/components/target-profiles/list-items.hbs
  admin/app/controllers/authenticated/target-profiles/list.js
  admin/app/controllers/authenticated/target-profiles/target-profile.js
  admin/app/models/target-profile.js
  admin/app/router.js
  admin/app/routes/authenticated/target-profiles/target-profile.js
  admin/app/templates/authenticated/target-profiles/list.hbs
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/mirage/config.js
  admin/tests/acceptance/organization-target-profiles-management-test.js
  admin/tests/acceptance/target-profiles-details-test.js
  admin/tests/acceptance/target-profiles-list-test.js
  admin/tests/integration/components/routes/authenticated/target-profiles/list-items-test.js
  admin/tests/unit/adapters/target-profile-test.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/usecases/get-target-profile-details.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/domain/usecases/get-target-profile-details_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1959 [BUGFIX] Permettre à un nouveau utilisateur connecté depuis le GAR et déjà réconcilié avec un compte avec un mot de passe expiré de rejoindre une campagne (PIX-1321).
  mon-pix/app/components/routes/login-form.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed, team-acces

#1954 [TECH] Passage de Cypress à la dernière version (4.6 => 5.3).
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#1950 [FEATURE] Amélioration des choix d'épreuves (PIX-1345).
  api/lib/domain/services/pick-challenge-service.js
  api/tests/unit/domain/services/pick-challenge-service_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#1948 [TECH] Renommer les routes api/jury en api/admin
  admin/app/adapters/session.js
  admin/mirage/config.js
  admin/mirage/serializers/session.js
  admin/tests/unit/adapters/session-test.js
  api/lib/application/sessions/index.js
  api/lib/infrastructure/serializers/jsonapi/jury-session-serializer.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/acceptance/application/session/session-controller-get-jury-session_test.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/acceptance/application/session/session-controller-patch-update-publication-session_test.js
  api/tests/acceptance/application/session/session-controller-patch-user-assignment_test.js
  api/tests/acceptance/application/session/session-controller-put-results-sent-to-prescriber_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-session-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#1958 [TECH] Rendre les analytics activable via variable d'environnement (PIX-1361)
  admin/config/environment.js
  admin/package-lock.json
  admin/package.json
  certif/config/environment.js
  certif/package-lock.json
  certif/package.json
  mon-pix/config/environment.js
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/config/environment.js
  orga/package-lock.json
  orga/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#1968 [BUGFIX] Ajout d'un await sur la creation de snapshots KE lors du partage de participation
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1976 [BUGFIX] Réparation du bouton de téléchargement de pv de session (PIX-1382)
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
Labels: :rocket: Ready to Merge, :steam_locomotive: EXPEDIT, team-certif

#1953 [DOC] Mise à jour de la documentation des tests de bout-en-bout.
  high-level-tests/e2e/README.md
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#1926 [FEATURE] Gérer la mise à jour des étudiants surnuméraires des établissements supérieurs avec l'import (PIX-1124).
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/import-higher-schooling-registrations.js
  api/lib/infrastructure/perftimer.js
  api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
  api/tests/integration/domain/usecases/import-higher-schooling-registrations_test.js
  api/tests/integration/infrastructure/repositories/higher-schooling-registration-repository_test.js
  api/tests/tooling/domain-builder/factory/build-higher-schooling-registration.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/usecases/update-student-number_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1944 [BUGFIX] Empêche le dépassement mémoire lié à l'affichage des résultats collectifs (+ amélioration des perfs au passage) (PIX-1067)
  api/lib/domain/models/CampaignCollectiveResult.js
  api/lib/domain/models/CampaignCompetenceCollectiveResult.js
  api/lib/domain/read-models/CampaignCollectiveResult.js
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-collective-result.js
  api/tests/tooling/domain-builder/factory/build-campaign-competence-collective-result.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/CampaignCompetenceCollectiveResult_test.js
  api/tests/unit/domain/read-models/CampaignCollectiveResult_test.js
  api/tests/unit/domain/usecases/compute-campaign-collective-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-collective-result-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1949 [TECH] Ajouter une validation front lors de l'ajout de candidat (CERTIF)
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/certification-candidate-in-staging-item.js
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/integration/components/certification-candidate-in-staging-item-test.js
Labels: :rocket: Ready to Merge, hacktoberfest-accepted, team-certif

#1974 [BUGFIX] Suppression des colonnes d'acquis du CSV de campagne d'évaluation avec la mention NA pour le SCO (PIX-1331).
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-prescription

#1967 [FEATURE] Création du mail d'envoi des résultats de certif (PIX-978)
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/update-publication-session.js
  api/lib/infrastructure/mailers/SendinblueProvider.js
  api/lib/infrastructure/mailers/mailer.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/update-publication-session_test.js
Labels: :rocket: Ready to Merge, team-certif

#1981 [FEATURE] Ajout d'une variable d'environnement pour identifier une organization "Agri" (PIX-1350)
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/tests/acceptance/application/prescriber-controller_test.js
  api/tests/unit/domain/models/Organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  orga/app/models/organization.js
  orga/app/services/current-user.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1970 [BUG] Rediriger les utilisateurs authentifiés depuis le médiacentre vers la page de déconnexion (pix-1284)
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/routes/campaigns/restricted/join.js
  mon-pix/app/routes/logout.js
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/unit/routes/campaigns/restricted/join-test.js
  mon-pix/tests/unit/routes/logout-test.js
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed, hacktoberfest-accepted, team-acces

#1984 [CLEANUP] Retrait de la route API dépréciée POST /api/organizations/{id}/import-students pour l'import SIECLE (PIX-TODO)
  api/lib/application/organizations/index.js
  api/tests/integration/application/organizations/index_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces, team-prescription

#1979 [TECH] Utiliser le nouveau modèle de TargetProfile dans l'analyse de campagne (PIX-1388)
  api/lib/domain/models/CampaignAnalysis.js
  api/lib/domain/models/CampaignTubeRecommendation.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/models/TargetedSkill.js
  api/lib/domain/usecases/compute-campaign-analysis.js
  api/lib/domain/usecases/compute-campaign-participation-analysis.js
  api/tests/integration/domain/models/CampaignAnalysis_test.js
  api/tests/integration/domain/usecases/compute-campaign-analysis_test.js
  api/tests/integration/domain/usecases/compute-campaign-participation-analysis_test.js
  api/tests/tooling/airtable-builder/factory/learning-content/build-learning-content.js
  api/tests/tooling/domain-builder/factory/build-campaign-tube-recommendation.js
  api/tests/tooling/domain-builder/factory/build-targeted-skill.js
  api/tests/unit/domain/models/CampaignTubeRecommendation_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  api/tests/unit/domain/models/TargetedSkill_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1964 [FEATURE] Amélioration de l’accessibilité de la modal Résultats et tutos (PIX-1182).
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/components/_learning-more-tutorial-panel.scss
  mon-pix/app/styles/components/_result-item.scss
  mon-pix/app/styles/components/_tutorial-item.scss
  mon-pix/app/styles/components/_tutorial-panel.scss
  mon-pix/app/styles/globals/_pix-modal.scss
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/feedback-panel.hbs
  mon-pix/app/templates/components/learning-more-panel.hbs
  mon-pix/app/templates/components/qroc-solution-panel.hbs
  mon-pix/app/templates/components/tutorial-panel.hbs
  mon-pix/tests/acceptance/challenge-qroc-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed, team-evaluation

#1980 [FEATURE] Permettre de créer en masse des organisations SCO et leur ajouter le tag AGRI (PIX-1221).
  api/db/migrations/20201006140921_create_organization_tags.js
  api/lib/domain/models/OrganizationTag.js
  api/lib/domain/models/Tag.js
  api/lib/infrastructure/data/organization-tag.js
  api/lib/infrastructure/data/tag.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/organization-tag-repository.js
  api/lib/infrastructure/repositories/tag-repository.js
  api/scripts/create-or-update-sco-agri-organizations.js
  api/scripts/create-or-update-sco-organizations.js
  api/scripts/logo/default-sco-agri-organization-logo-base64.js
  api/scripts/logo/default-sco-organization-logo-base64.js
  api/tests/acceptance/scripts/create-or-update-sco-organizations_test.js
  api/tests/integration/infrastructure/repositories/organization-tag-repository_test.js
  api/tests/integration/infrastructure/repositories/tag-repository_test.js
  api/tests/integration/scripts/create-or-update-sco-agri-organizations_test.js
  api/tests/tooling/database-builder/factory/build-organization-tag.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/database-builder/factory/build-tag.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-organization-tag.js
  api/tests/tooling/domain-builder/factory/build-tag.js
  api/tests/tooling/domain-builder/factory/index.js
Labels: :rocket: Ready to Merge, hacktoberfest-accepted, team-acces

#1963 [FEATURE] Création du service permettant la génération des résultats de certification (PIX-1359).
  api/lib/domain/errors.js
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/lib/infrastructure/utils/csv/write-csv-utils.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/integration/infrastructure/utils/csv/write-csv-utils_test.js
  api/tests/tooling/domain-builder/factory/build-certification-result.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/services/certification/certification-service_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, hacktoberfest-accepted, team-certif

#1983 [TECH] Ajout d'une route pour télécharger les résultats d'une session (PIX-1359)
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/services/file-saver.js
  admin/app/services/session-info-service.js
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/tests/unit/controllers/authenticated/sessions/session/informations-test.js
  admin/tests/unit/services/file-saver-test.js
  admin/tests/unit/services/session-info-service-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/usecases/get-session-results.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/acceptance/application/session/session-controller-get-session-results_test.js
  api/tests/integration/domain/services/certification-service_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/tooling/database-builder/factory/build-badge.js
  api/tests/tooling/database-builder/factory/build-certification-course.js
  api/tests/tooling/database-builder/factory/build-partner-certification.js
  api/tests/tooling/domain-builder/factory/build-certification-course.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/get-session-results_test.js
Labels: :rocket: Ready to Merge, hacktoberfest-accepted, team-certif

#1978 [TECH] Finalisation de la glimmerization et de l'octanification de Pix Orga (Pix-1386).
  orga/.eslintrc.js
  orga/app/components/modal/dialog.js
  orga/app/components/routes/authenticated/campaign/report.js
  orga/app/components/routes/login-form.js
  orga/app/components/routes/register-form.js
  orga/app/components/sidebar-menu.js
  orga/app/components/user-logged-menu.js
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/controllers/authenticated/sco-students/list.js
  orga/app/controllers/authenticated/sup-students/list.js
  orga/app/models/campaign-assessment-participation-competence-result.js
  orga/app/models/campaign-assessment-participation-result.js
  orga/app/models/campaign-assessment-participation-summary.js
  orga/app/models/campaign-collective-result.js
  orga/app/models/campaign-competence-collective-result.js
  orga/app/models/campaign-profile.js
  orga/app/models/campaign.js
  orga/app/models/membership.js
  orga/app/models/organization-invitation.js
  orga/app/models/organization.js
  orga/app/models/prescriber.js
  orga/app/models/student.js
  orga/app/models/user.js
  orga/app/transforms/date-only.js
  orga/mirage/config.js
  orga/tests/integration/components/information-banner-test.js
  orga/tests/integration/components/manage-authentication-method-modal-test.js
  orga/tests/integration/components/routes/authenticated/campaign/details/tab-test.js
  orga/tests/integration/components/routes/authenticated/campaign/new-test.js
  orga/tests/integration/components/routes/authenticated/sco-students/list-items-test.js
  orga/tests/integration/components/routes/authenticated/sup-students/list-items-test.js
  orga/tests/integration/components/routes/login-form-test.js
  orga/tests/integration/components/routes/register-form-test.js
  orga/tests/integration/components/sidebar-menu-test.js
  orga/tests/integration/components/user-logged-menu-test.js
  orga/tests/unit/controllers/authenticated/sup-students/list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-prescription

#1987 [FEATURE] Rendre réutilisable le parser CSV HigherSchoolingRegistrationParser (PIX-1351)
  api/lib/infrastructure/serializers/csv/csv-registration-parser.js
  api/lib/infrastructure/serializers/csv/higher-schooling-registration-parser.js
  api/tests/unit/infrastructure/serializers/csv/csv-registration-parser_test.js
  api/tests/unit/infrastructure/serializers/csv/higher-schooling-registration-parser_test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1993 [BUGFIX] Corriger l'affichage des barres situées dans l'onglet analyse et résultats collectifs (PIX-1317)
  orga/app/styles/globals/competences.scss
Labels: :rocket: Ready to Merge, Design Review OK, team-prescription

#1990 [TECH] Mise en place d'un Feature Toggle pour spécifier quelle organisation est Pôle Emploi (Pix-1392).
  api/lib/domain/models/Organization.js
  api/tests/unit/domain/models/Organization_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, hacktoberfest-accepted, team-prescription

#1960 [TECH ] Retirer le feature toggle du telechargement de l'attestation
  mon-pix/app/components/user-certifications-detail-header.js
  mon-pix/app/templates/components/user-certifications-detail-header.hbs
  mon-pix/config/environment.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#1986 [BUG] Amélioration dans Mon-Pix de la gestion des erreurs sur la page Réinitialiser le mot de passe (PIX-1385).
  mon-pix/.template-lintrc.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/app/templates/components/update-expired-password-form.hbs
  mon-pix/tests/acceptance/update-expired-password-test.js
  mon-pix/tests/integration/components/update-expired-password-form-test.js
  mon-pix/tests/unit/components/update-expired-password_test.js
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed, hacktoberfest-accepted, team-acces

#1989 [FEATURE] Editer le champ crédits d'une organisation (PIX-1296).
  admin/app/components/organization-information-section.hbs
  admin/app/components/organization-information-section.js
  admin/mirage/config.js
  admin/mirage/factories/organization.js
  admin/tests/acceptance/organization-information-management-test.js
  admin/tests/integration/components/organization-information-section-test.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/update-organization-information.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-prescription

#1971 [FEATURE] Ajout du numéro étudiant dans l'export csv d'une campagne de collecte de profils (PIX-1139).
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1969 [FEATURE] Accessibilité de la page de résultat de campagne (PIX-1183)
  mon-pix/app/components/reached-stage.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/assessment/skill-review.hbs
  mon-pix/app/templates/components/campaign-share-button.hbs
  mon-pix/app/templates/components/campaign-skill-review-competence-result.hbs
  mon-pix/app/templates/components/reached-stage.hbs
  mon-pix/tests/integration/components/reached-stage-test.js
  mon-pix/tests/unit/components/reached-stage-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, hacktoberfest-accepted, team-evaluation

#1999 [FEATURE] Réconcilier un élève avec un match strict, et dans un second temps avec une distance d'édition si pas de match (PIX-1401).
  api/lib/domain/services/user-reconciliation-service.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-prescription

#2006 [FEATURE] Ajouter une documentation pour les organisation SCO-AGRI (PIX-1335)
  orga/app/components/sidebar-menu.js
  orga/tests/integration/components/sidebar-menu-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2003 [FEATURE] Ajouter un texte alternatif à l'image d'aide de l'identifiant externe (PIX-1363).
  api/db/migrations/20201013093514_create-alternative-text-to-external-id-help-image.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/models/Campaign.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/tooling/database-builder/factory/build-campaign.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  mon-pix/app/components/routes/campaigns/fill-in-participant-external-id.hbs
  mon-pix/app/models/campaign.js
  mon-pix/tests/integration/components/routes/campaigns/fill-in-participant-external-id-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2005 [BUGFIX] Empêcher une erreur 500 suite à une violation de contrainte lors d'une réconciliation d'un élève (PIX-1367)
  api/db/seeds/data/organizations-builder.js
  api/lib/domain/constants.js
  api/lib/domain/usecases/reconcile-schooling-registration.js
  api/tests/unit/domain/usecases/reconcile-schooling-registration_test.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco.js
  mon-pix/app/utils/errors-messages.js
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sco-test.js
  mon-pix/tests/unit/utils/errors-messages-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed, hacktoberfest-accepted, team-acces

#2000 [FEATURE] Ajouter un message d'avertissement avant de réconcilier un élève (PIX-1391).
  api/lib/application/schooling-registration-user-associations/schooling-registration-user-association-controller.js
  api/lib/domain/usecases/reconcile-schooling-registration.js
  api/tests/acceptance/application/schooling-registration-user-association-controller_test.js
  api/tests/unit/domain/usecases/reconcile-schooling-registration_test.js
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  mon-pix/app/adapters/schooling-registration-user-association.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco-information-modal.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sco-information-modal.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sco.js
  mon-pix/app/controllers/campaigns/restricted/join.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sco-information-modal_test.js
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sco-test.js
  mon-pix/tests/unit/controllers/campaigns/restricted/join-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, hacktoberfest-accepted, team-acces

#1998 [FEATURE]Afficher un onglet "Candidats" spécifique SCO sur la page de détails de ma session (PIX-1372)
  api/lib/application/feature-toggles/feature-toggle-controller.js
  api/lib/application/feature-toggles/index.js
  api/lib/config.js
  api/lib/infrastructure/serializers/jsonapi/feature-toggle-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/feature-controller_tests.js
  api/tests/unit/infrastructure/serializers/jsonapi/feature-toggle-serializer_test.js
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/app/controllers/authenticated/sessions/list.js
  certif/app/models/feature-toggle.js
  certif/app/router.js
  certif/app/routes/application.js
  certif/app/routes/authenticated/sessions/details.js
  certif/app/services/feature-toggles.js
  certif/app/services/features.js
  certif/app/styles/app.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates-sco.scss
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates-sco.hbs
  certif/mirage/config.js
  certif/mirage/factories/feature-toggle.js
  certif/public/images/adding_candidate.svg
  certif/tests/acceptance/authentication-test.js
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/acceptance/session-details-test.js
  certif/tests/acceptance/session-finalization-test.js
  certif/tests/acceptance/session-list-test.js
  certif/tests/acceptance/session-new-test.js
  certif/tests/acceptance/session-update-test.js
  certif/tests/acceptance/terms-of-service-test.js
  certif/tests/helpers/test-init.js
  certif/tests/unit/controllers/authenticated/sessions/details-test.js
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates-test.js
  certif/tests/unit/routes/authenticated/sessions/details-test.js
  certif/tests/unit/services/featureToggles-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2004 [TRANSLATION] Mise à jour des traductions.
  mon-pix/.editorconfig
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, cross-team

#2009 [TECH] Migration de `stats.pix.fr` à `analytics.pix.fr`
  admin/config/environment.js
  certif/config/environment.js
  high-level-tests/e2e/cypress.json
  mon-pix/config/environment.js
  orga/config/environment.js
Labels: :rocket: Ready to Merge, cross-team

#2020 [TECH] Refacto du certification result
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/services/certification-service.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/tooling/domain-builder/factory/build-assessment-result.js
  api/tests/tooling/domain-builder/factory/build-certification-result.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/usecases/get-certification-attestation_test.js
  api/tests/unit/domain/usecases/get-private-certificate_test.js
  api/tests/unit/domain/usecases/get-session-results_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2007 [BUGFIX] Ajouter une transaction à l'improve d'une CompetenceEval (PIX-1411).
  api/lib/application/competence-evaluations/competence-evaluation-controller.js
  api/lib/domain/usecases/improve-competence-evaluation.js
  api/tests/unit/domain/usecases/improve-competence-evaluation_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#1994 [FEATURE] Ajout de l'import CSV des élèves pour les orga SCO Agri
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/import-schooling-registrations-from-siecle.js
  api/lib/domain/usecases/index.js
  api/lib/domain/validators/higher-schooling-registration-validator.js
  api/lib/domain/validators/schooling-registration-validator.js
  api/lib/infrastructure/serializers/csv/csv-registration-parser.js
  api/lib/infrastructure/serializers/csv/higher-schooling-registration-parser.js
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/tooling/database-builder/factory/build-schooling-registration-with-user.js
  api/tests/tooling/database-builder/factory/build-schooling-registration.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/models/HigherSchoolingRegistration_test.js
  api/tests/unit/domain/usecases/import-schooling-registrations-from-siecle_test.js
  api/tests/unit/domain/validators/schooling-registration-validator_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-registration-parser_test.js
  api/tests/unit/infrastructure/serializers/csv/higher-schooling-registration-parser_test.js
  api/tests/unit/infrastructure/serializers/csv/schooling-registration-parser_test.js
  orga/app/components/routes/authenticated/sco-students/list-items.hbs
  orga/app/components/routes/authenticated/sco-students/list-items.js
  orga/app/controllers/authenticated/sco-students/list.js
  orga/mirage/config.js
  orga/tests/acceptance/sco-student-list-test.js
  orga/tests/integration/components/routes/authenticated/sco-students/list-items-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2018 [CLEANUP] Rendre les niveaux d'erreurs de lint explicites.
  .eslintrc.yaml
Labels: :rocket: Ready to Merge, cross-team

#1955 [TECH] Enlever les actions synchrones qui bloquent nodejs
  api/.eslintrc.yaml
  api/lib/domain/models/index.js
  api/lib/domain/services/encryption-service.js
  api/lib/infrastructure/utils/ods/common-ods-utils.js
  api/scripts/NextGitCommitMessage.js
  api/scripts/helpers/csvHelpers.js
  api/scripts/import-certifications-from-csv.js
  api/scripts/make-saml-env.js
  api/scripts/update-sco-organizations-with-province-code-and-external-id.js
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_test.js
  api/tests/acceptance/scripts/import-certifications-from-csv_test.js
  api/tests/acceptance/scripts/update-sco-organizations-with-province-code-and-external-id_test.js
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/domain/usecases/get-candidates-import-sheet/get-candidates-import-sheet_test.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/integration/infrastructure/utils/ods/write-ods-utils_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/domain/services/encryption-service_test.js
  api/tests/unit/infrastructure/utils/write-pdf-utils_test.js
  api/tests/unit/scripts/NextGitCommitMessage_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team, hacktoberfest-accepted

#2016 [REFACTO] Centraliser l'authentification des élèves venant du GAR (PIX-1422).
  api/db/seeds/data/seed-pix1321-builder.js
  api/db/seeds/seed.js
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/domain/usecases/authenticate-user.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/integration/application/authentication/index_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  mon-pix/app/adapters/external-user-authentication-request.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco-information-modal.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco.hbs
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/controllers/campaigns/restricted/login-or-register-to-access.js
  mon-pix/app/models/external-user-authentication-request.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/mirage/factories/user.js
  mon-pix/mirage/routes/auth/index.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/integration/components/routes/login-form-test.js
  mon-pix/tests/unit/components/routes/login-form-test.js
  mon-pix/tests/unit/controllers/campaigns/restricted/login-or-register-to-access-test.js
Labels: :rocket: Ready to Merge, hacktoberfest-accepted, team-acces

#2019 [TECH] Nettoyage et mise à jour des données de tests, aussi nommées seeds (PIX-1425).
  api/db/seeds/data/campaigns-builder.js
  api/db/seeds/data/dragon-and-co-builder.js
  api/db/seeds/data/organizations-builder.js
  api/db/seeds/data/organizations-pro-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/db/seeds/data/organizations-sup-builder.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/db/seeds/data/tags-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/db/seeds/data/users-builder.js
  api/db/seeds/data/users_pix_roles-builder.js
  api/db/seeds/seed.js
  api/tests/tooling/database-builder/factory/build-organization.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces, team-prescription

#2014 [FEATURE] Logguer en console les résultats mockés d'un participant à une campagne d'évaluation Pôle Emploi (PIX-1393).
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/campaignParticipations/campaign-participation-controller.js
  api/lib/domain/events/CampaignParticipationResultsShared.js
  api/lib/domain/events/handle-campaign-participation-results-sending.js
  api/lib/domain/events/index.js
  api/lib/domain/usecases/share-campaign-result.js
  api/lib/infrastructure/events/EventDispatcher.js
  api/tests/integration/infrastructure/event-dispatcher_test.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/events/event-choregraphy-badge-acquisition_test.js
  api/tests/unit/domain/events/event-choregraphy-campaign-participation-results-sending_test.js
  api/tests/unit/domain/events/event-choregraphy-score-certification_test.js
  api/tests/unit/domain/events/event-choregraphy-score-partner-certification_test.js
  api/tests/unit/domain/events/handle-campaign-participation-results-sending_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2021 [FEATURE] Filtrer les sessions par type de centre de certification (PIX-1341)
  admin/app/components/sessions/list-items.hbs
  admin/app/controllers/authenticated/sessions/list.js
  admin/app/routes/authenticated/sessions/list.js
  admin/app/templates/authenticated/sessions/list.hbs
  admin/tests/unit/controllers/authenticated/sessions/list-test.js
  admin/tests/unit/routes/authenticated/sessions/list-test.js
  api/lib/domain/models/CertificationCenter.js
  api/lib/domain/validators/session-validator.js
  api/lib/infrastructure/repositories/jury-session-repository.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2026 [FEATURE] Pouvoir télécharger le modèle csv en tant qu'organisation SCO-AGRICULTURE. (PIX-1357)
  api/lib/domain/usecases/get-schooling-registrations-csv-template.js
  api/lib/infrastructure/serializers/csv/higher-schooling-registration-parser.js
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/tests/unit/domain/usecases/get-schooling-registrations-csv-template_test.js
  orga/app/components/routes/authenticated/sco-students/list-items.hbs
  orga/app/components/routes/authenticated/sco-students/list-items.js
  orga/tests/integration/components/routes/authenticated/sco-students/list-items-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2015 [FEATURE] Ne pas afficher les paliers quand on a obtenu le badge CléA (PIX-1383).
  mon-pix/app/controllers/campaigns/assessment/skill-review.js
  mon-pix/app/templates/campaigns/assessment/skill-review.hbs
  mon-pix/tests/acceptance/skill-review-page-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2025 [TECH] Montée de version mineure de la BDD 12.3=>12.4.
  .circleci/config.yml
  docker-compose.yml
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed, cross-team

#2017 [BSR] Utiliser que le helper HttpTestServer, pour les tests d'intégration et les tests unitaires, dans l'API (PIX-1423).
  api/tests/integration/application/authentication/index_test.js
  api/tests/integration/application/campaignParticipations/index_test.js
  api/tests/integration/application/campaigns/index_test.js
  api/tests/integration/application/certifications/index_test.js
  api/tests/integration/application/organization-invitations/index_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/answers/index_test.js
  api/tests/unit/application/assessments/index_test.js
  api/tests/unit/application/cache/index_test.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/application/challenges/challenge-controller_test.js
  api/tests/unit/application/courses/course-controller_test.js
  api/tests/unit/application/courses/index_test.js
  api/tests/unit/application/feedbacks/feedback-controller_test.js
  api/tests/unit/application/feedbacks/index_test.js
  api/tests/unit/application/healthcheck/index_test.js
  api/tests/unit/application/organization-invitations/index_test.js
  api/tests/unit/application/prescribers/index_test.js
  api/tests/unit/application/progressions/index_test.js
  api/tests/unit/application/session/index_test.js
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed, hacktoberfest-accepted, team-acces

#2010 [TECH] Suppression de routes API dépréciées (PIX-1416).
  api/lib/application/schooling-registration-user-associations/index.js
  api/lib/application/schooling-registration-user-associations/schooling-registration-user-association-controller.js
  api/lib/application/student-dependent-users/index.js
  api/lib/application/student-user-associations/index.js
  api/lib/routes.js
  api/tests/acceptance/application/student-dependent-user-controller_test.js
  api/tests/integration/application/schooling-registration-user-associations/index_test.js
  api/tests/integration/application/student-dependent-users/index_test.js
  api/tests/integration/application/student-user-associations/index_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sup-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2028 [TECH] Enrichir les test helpers de pix certif et async/await des tests d'API
  api/tests/acceptance/application/certification-center-controller_test.js
  certif/tests/acceptance/authentication-test.js
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/acceptance/terms-of-service-test.js
  certif/tests/helpers/test-init.js
  orga/tests/acceptance/authentication-test.js
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed, team-certif

#2029 [FEATURE] Ajouter le type nombre au réponse QROC (PIX-1455).
  mon-pix/app/templates/components/qroc-proposal.hbs
  mon-pix/tests/integration/components/qroc-proposal-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#1997 [FEATURE] Afficher la liste des étudiants SCO pour l'ajout des candidats (PIX-1373)
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/usecases/find-students-from-certification-center-id.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/jsonapi/student-certification-serializer.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/domain/usecases/find-students-from-certification-center-id_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-certification-serializer_test.js
  certif/app/adapters/student.js
  certif/app/components/add-student-list.hbs
  certif/app/components/certification-candidates-sco.hbs
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/student.js
  certif/app/router.js
  certif/app/routes/authenticated/sessions/add-student.js
  certif/app/styles/app.scss
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/pages/authenticated/sessions/add-student.scss
  certif/app/templates/authenticated/sessions/add-student.hbs
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates-sco.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/mirage/config.js
  certif/mirage/factories/student.js
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/acceptance/session-details-test.js
  certif/tests/integration/components/add-student-list-test.js
  certif/tests/unit/adapters/student-test.js
  certif/tests/unit/models/student-test.js
  certif/tests/unit/routes/authenticated/sessions/add-student-test.js
Labels: :rocket: Ready to Merge, team-certif

#2023 [FEATURE] Autoriser l'import XML SIECLE seulement pour les organisations ayant un UAI concordant (PIX-1293).
  api/lib/domain/services/schooling-registrations-xml-service.js
  api/lib/domain/usecases/import-schooling-registrations-from-siecle.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/integration/domain/services/schooling-registrations-xml-service_test.js
  api/tests/unit/domain/usecases/import-schooling-registrations-from-siecle_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2033 [FEATURE] Changer le message pour les épreuves à validation auto (PIX-1453).
  mon-pix/tests/acceptance/challenge-qroc-test.js
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2036 [TRANSLATION] Ajout de traduction
  mon-pix/translations/en.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2030 [FEATURE] Permettre la selection d'élèves comme candidats d'une session (PIX-1374).
  certif/app/components/add-student-list.hbs
  certif/app/components/add-student-list.js
  certif/app/components/certif-checkbox.hbs
  certif/app/components/session-finalization-reports-informations-step.hbs
  certif/app/components/session-finalization-reports-informations-step.js
  certif/app/models/student.js
  certif/app/styles/app.scss
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/components/certif-checkbox.scss
  certif/app/styles/components/session-finalization-reports-informations-step.scss
  certif/tests/integration/components/certif-checkbox-test.js
  certif/tests/unit/components/add-student-list-test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize-test.js
  high-level-tests/e2e/cypress/support/step_definitions/pix-certif/session.js
Labels: :rocket: Ready to Merge, team-certif

#2032 [FEATURE] Afficher les résultats thématiques dans la liste des participants (PIX-1442)
  api/lib/domain/models/BadgeAcquisition.js
  api/lib/domain/models/TargetProfile.js
  api/lib/domain/read-models/CampaignAssessmentParticipationSummary.js
  api/lib/domain/usecases/find-paginated-campaign-assessment-participation-summaries.js
  api/lib/infrastructure/data/target-profile.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-assessment-participation-summary-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/tests/integration/domain/usecases/find-paginated-campaign-assessment-participation-summaries_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile.js
  api/tests/unit/domain/models/TargetProfile_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-summary-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/models/badge.js
  orga/app/models/campaign-assessment-participation-summary.js
  orga/app/models/target-profile.js
  orga/app/routes/authenticated/campaigns/campaign.js
  orga/app/styles/pages/authenticated/campaigns/details/participants.scss
  orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation, team-prescription

#2022 [FEATURE] Utiliser les tags pour définir si une organisation est de type "Agriculture" (PIX-1354).
  api/lib/domain/models/Organization.js
  api/lib/domain/models/Tag.js
  api/lib/domain/usecases/get-prescriber.js
  api/lib/infrastructure/data/organization.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/lib/infrastructure/repositories/prescriber-repository.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/lib/infrastructure/utils/bookshelf-to-domain-converter.js
  api/scripts/create-or-update-sco-agri-organizations.js
  api/tests/acceptance/application/membership-controller_test.js
  api/tests/acceptance/application/prescriber-controller_test.js
  api/tests/integration/infrastructure/models/assessment_result_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/integration/infrastructure/utils/bookshelf-to-domain-converter_test.js
  api/tests/integration/scripts/create-or-update-sco-agri-organizations_test.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/unit/domain/models/Organization_test.js
  api/tests/unit/domain/usecases/get-prescriber_test.js
  api/tests/unit/domain/usecases/get-schooling-registrations-csv-template_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2035 [FEATURE] Ajout du prénom et nom du user connecté sur la page saisie code parcours (PIX-1415).
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/tests/unit/controllers/fill-in-campaign-code-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, hacktoberfest-accepted, team-acces

#2024 [FEATURE] Afficher la liste des inscriptions d'un élève dans Pix Admin (PIX-1384).
  admin/app/components/sessions/list-items.hbs
  admin/app/components/user-detail-personal-information.hbs
  admin/app/helpers/format-date.js
  admin/app/models/schooling-registration.js
  admin/app/models/session.js
  admin/app/models/user.js
  admin/app/routes/authenticated/users/get.js
  admin/app/styles/components/user-detail-personal-information-section.scss
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/mirage/config.js
  admin/mirage/serializers/user.js
  admin/tests/acceptance/user-details-personal-information-test.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  admin/tests/integration/components/user-detail-personal-information-test.js
  admin/tests/unit/helpers/format-date-test.js
  admin/tests/unit/models/session-test.js
  api/lib/domain/models/UserDetailsForAdmin.js
  api/lib/domain/read-models/SchoolingRegistrationForAdmin.js
  api/lib/domain/usecases/dissociate-schooling-registrations.js
  api/lib/domain/usecases/get-user-details-for-admin.js
  api/lib/domain/usecases/update-user-details-for-administration.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/acceptance/application/users/update-user-details-for-administration_test.js
  api/tests/acceptance/application/users/users-controller-dissociate-schooling-registrations_test.js
  api/tests/integration/domain/usecases/dissociate-schooling-registrations_test.js
  api/tests/integration/domain/usecases/get-user-details-for-admin_test.js
  api/tests/integration/domain/usecases/update-user-details-for-administration_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-schooling-registration.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration-for-admin.js
  api/tests/tooling/domain-builder/factory/build-user-details-for-admin.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/read-models/SchoolingRegistrationForAdmin_test.js
  api/tests/unit/domain/usecases/dissociate-schooling-registration_test.js
  api/tests/unit/domain/usecases/dissociate-schooling-registrations_test.js
  api/tests/unit/domain/usecases/get-user-details-for-admin_test.js
  api/tests/unit/domain/usecases/update-user-details-for-administration_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, hacktoberfest-accepted, team-acces

#2038 [TECH] Ajout de l'intégration Sentry sur Pix App.
  mon-pix/app/app.js
  mon-pix/config/environment.js
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#1991 [DOC] Ajouter les instructions liées au cache pour l'exécution des tests E2E.
  high-level-tests/e2e/README.md
Labels: :rocket: Ready to Merge, cross-team

#2039 [TECH] Inclure le creatorId dans le fichier pour le script create-assessment-campaigns-for-sco.
  api/scripts/prod/create-assessment-campaigns-for-sco.js
  api/tests/integration/scripts/prod/create-assessment-campaigns-for-sco_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2040 [INFRA] Montée de version d'ember-simple-auth sur Pix App (PIX-1476).
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/signin-form.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/routes/login-form-test.js
  mon-pix/tests/integration/components/signin-form-test.js
  mon-pix/tests/unit/components/routes/login-form-test.js
Labels: :rocket: Ready to Merge, hacktoberfest-accepted, team-acces

#2041 [TECH] Ajout de cross-env dans devDependencies pour lancer les tests sur les postes Windows (PIX-1480)
  .gitignore
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2048 [BUG] Rediriger vers la page '/' lors d'une déconnexion, sur Pix Admin/Certif/Orga (PIX-1493).
  admin/app/services/url.js
  admin/config/environment.js
  certif/app/services/url.js
  certif/config/environment.js
  orga/app/services/url.js
  orga/config/environment.js
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed, hacktoberfest-accepted, team-acces, team-certif

#2045 [FEATURE] Cacher les bannières de Pix Orga lorsque l'organisation est SCO AGRICULTURE (PIX-1492).
  orga/app/components/information-banner.js
  orga/tests/integration/components/information-banner-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2049 [FEATURE] Ajouter un tooltip lors du survol des badges dans les résultats participant d'une campagne (PIX-1459).
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/styles/pages/authenticated/campaigns/details/participants.scss
  orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, team-evaluation, team-prescription

#2043 [BUGFIX] Page blanche en fin de campagne (PIX-1272).
  mon-pix/app/app.js
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2053 [TECH] Faire en sorte que les tests de l'API retourne une erreur le cas écheant.
  api/package.json
Labels: :rocket: Ready to Merge, cross-team

#2027 [TECH] Montée de version d'Ember (3.21 → 3.22) et des dépendances de Pix Certif.
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/package-lock.json
  certif/package.json
Labels: :rocket: Ready to Merge, team-certif

#2052 [CLEANUP] Supprimer un fichier de seeds inutile (PIX-1497).
  api/db/seeds/data/seed-pix1321-builder.js
  api/db/seeds/seed.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-acces

#1966 [TECH] Appliquer la règle de lint héritée de la racine dans /api.
  .eslintrc.yaml
  api/.eslintrc.yaml
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-session-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team, hacktoberfest-accepted

#2042 [FEATURE] Ajout des paliers dans la liste des participants (PIX-1449)
  api/db/seeds/data/stages-builder.js
  api/lib/domain/models/CampaignReport.js
  api/lib/domain/usecases/get-campaign-report.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/stage-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-report-serializer.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/integration/infrastructure/repositories/stage-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-report.js
  api/tests/unit/domain/usecases/get-campaign-report_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-report-serializer_test.js
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/components/stage-stars.hbs
  orga/app/components/stage-stars.js
  orga/app/models/campaign-report.js
  orga/app/models/stage.js
  orga/app/styles/app.scss
  orga/app/styles/components/stage-stars.scss
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
  orga/tests/integration/components/stage-stars-test.js
  orga/tests/unit/models/campaign-report-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation, team-prescription

#1934 [CLEANUP] Corriger le contraste de la page profil
  mon-pix/app/styles/components/_competence-card-desktop.scss
  mon-pix/app/styles/components/_competence-card.scss
  mon-pix/app/templates/components/competence-card-default.hbs
  mon-pix/app/templates/components/competence-card-mobile.hbs
  mon-pix/tests/integration/components/competence-card-default-test.js
  mon-pix/tests/integration/components/competence-card-mobile-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Tech Review OK, team-evaluation

#2044 [FEATURE] Inclure les résultats thématiques dans l'export des campagnes d'évaluation (PIX-1457).
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/campaign-participations-builder.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/services/campaign-csv-export-service.js
  api/lib/domain/usecases/find-paginated-campaign-assessment-participation-summaries.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-with-learning-content.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation, team-prescription

#2064 [TECH] Correcteur d'erreur d'orthographe sur le terme targetprofile dans le code (PIX-1525)
  api/lib/infrastructure/repositories/campaign-assessment-participation-summary-repository.js
Labels: :rocket: Ready to Merge, Tech Review OK, hacktoberfest-accepted, team-prescription

#2037 [TRANSLATION] Corriger le html dans les fichiers de traduction
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sco-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, cross-team, team-evaluation

#2065 [TECH] Correction d'orthographe sur le terme supernumerary (PIX-1527).
  api/lib/domain/usecases/import-higher-schooling-registrations.js
Labels: :rocket: Ready to Merge, Tech Review OK, hacktoberfest-accepted, team-prescription

#2067 [FEATURE] Changement de nom de l'identifiant en identifiant externe au sein de la page de création d'une campagne (PIX-1529).
  orga/app/components/routes/authenticated/campaign/new.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-prescription

#2047 [FEATURE] Ajout condition isShared pour afficher les badges obtenu (PIX-1490)
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2070 [TECH] Préconiser l'utilisation d'un serveur http léger dans les tests.
  api/tests/.eslintrc.yaml
  api/tests/integration/.eslintrc.yaml
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2069 [FEATURE] Ne pas afficher le lieu de naissance sur le certificat si il n'est pas disponible (PIX-1531).
  mon-pix/app/templates/components/user-certifications-detail-header.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-certif

#2068 [BUGFIX] Afficher si possible le lieu de naissance sur l'attestation de certification Pix (PIX-1504).
  api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-certif

#2050 [CLEANUP] Déplacer la mise à jour du userOrgaSettings dans l'API (PIX-1498).
  api/lib/domain/usecases/get-prescriber.js
  api/tests/integration/domain/usecases/get-prescriber_test.js
  api/tests/unit/domain/usecases/get-prescriber_test.js
  orga/app/services/current-user.js
  orga/tests/acceptance/join-test.js
  orga/tests/helpers/test-init.js
  orga/tests/unit/services/current-user-test.js
Labels: :rocket: Ready to Merge, hacktoberfest-accepted, team-acces

#2034 [FEATURE] Bloquer les boutons quand le temps est écoulé (PIX-1454).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/config/icons.js
  mon-pix/tests/integration/components/challenge-actions-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2054 [TECH] Refacto de méthodes du répo knowledge-elements utilisant les snapshots KE pour mieux répondre aux besoins (PIX-990-1)
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/read-models/CampaignAssessmentParticipationResult.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-repository.js
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-result-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1911 [TECH] Améliore la gestion des exceptions dans le database-builder (PIX-1306)
  api/db/knex-database-connection.js
  api/tests/integration/infrastructure/knex-database-connection_test.js
  api/tests/test-helper.js
  api/tests/tooling/database-builder/database-buffer.js
  api/tests/tooling/database-builder/database-builder.js
  api/tests/unit/tooling/database-builder/database-buffer_test.js
  api/tests/unit/tooling/database-builder/database-builder_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2055 [FEATURE] Ajouter le palier dans l'export des résultats d'un campagne d'évaluation (PIX-1458).
  api/lib/domain/services/campaign-csv-export-service.js
  api/lib/domain/usecases/get-campaign-report.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/infrastructure/repositories/stage-repository.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/integration/infrastructure/repositories/stage-repository_test.js
  api/tests/tooling/domain-builder/factory/build-stage.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/usecases/get-campaign-report_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2066 [FEATURE] Changement du wording de la banière SCO (remplacement Toussaint par Noël) (PIX-1528).
  orga/app/components/information-banner.hbs
  orga/tests/integration/components/information-banner-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, hacktoberfest-accepted, team-prescription

#2046 [FEATURE] Ajouter des candidats venant du SCO à une session de certif (PIX-1375)
  api/db/migrations/20201026162616_add-schooling-registration-id-column-to-certification-candidate-table.js
  api/db/seeds/data/certification/users.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/SCOCertificationCandidate.js
  api/lib/domain/usecases/enroll-students-to-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/repositories/sco-certification-candidate-repository.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/integration/infrastructure/repositories/sco-certification-candidate-repository_test.js
  api/tests/tooling/database-builder/factory/build-certification-candidate.js
  api/tests/tooling/domain-builder/factory/build-sco-certification-candidate.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/enroll-students-to-session_test.js
  certif/app/adapters/session.js
  certif/app/components/add-student-list.hbs
  certif/app/components/add-student-list.js
  certif/app/components/certif-checkbox.hbs
  certif/app/routes/authenticated/sessions/add-student.js
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/components/certif-checkbox.scss
  certif/app/templates/authenticated/sessions/add-student.hbs
  certif/mirage/config.js
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/integration/components/add-student-list-test.js
  certif/tests/unit/adapters/session-test.js
  certif/tests/unit/components/add-student-list-test.js
  certif/tests/unit/routes/authenticated/sessions/add-student-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#1856 [TECH] Montée de version d'Ember (3.18 → 3.22) et des dépendances de Pix Orga.
  orga/app/adapters/application.js
  orga/app/components/routes/authenticated/campaign/analysis/tab.js
  orga/app/components/routes/authenticated/sup-students/list-items.js
  orga/app/components/routes/authenticated/team/items.hbs
  orga/app/components/routes/login-or-register.hbs
  orga/app/models/badge.js
  orga/app/models/campaign-analysis.js
  orga/app/models/campaign-assessment-participation-competence-result.js
  orga/app/models/campaign-assessment-participation-result.js
  orga/app/models/campaign-assessment-participation-summary.js
  orga/app/models/campaign-assessment-participation.js
  orga/app/models/campaign-collective-result.js
  orga/app/models/campaign-competence-collective-result.js
  orga/app/models/campaign-participation.js
  orga/app/models/campaign-profile-competence.js
  orga/app/models/campaign-profile.js
  orga/app/models/campaign-profiles-collection-participation-summary.js
  orga/app/models/campaign-report.js
  orga/app/models/campaign-tube-recommendation.js
  orga/app/models/campaign.js
  orga/app/models/membership.js
  orga/app/models/organization-invitation-response.js
  orga/app/models/organization-invitation.js
  orga/app/models/organization.js
  orga/app/models/prescriber.js
  orga/app/models/sco-organization-invitation.js
  orga/app/models/stage.js
  orga/app/models/target-profile.js
  orga/app/models/user-orga-setting.js
  orga/app/models/user.js
  orga/app/routes/application.js
  orga/app/routes/authenticated.js
  orga/app/routes/authenticated/campaigns/update.js
  orga/app/routes/join-when-authenticated.js
  orga/app/routes/join.js
  orga/app/routes/login.js
  orga/app/routes/terms-of-service.js
  orga/config/ember-cli-update.json
  orga/mirage/config.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/routes/authenticated/campaign/analysis/tab-test.js
  orga/tests/integration/components/routes/authenticated/team/new-item-test.js
  orga/tests/unit/controllers/authenticated/sup-students/list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-captains

#2001 [TECH] Enlever la relation session hasMany certificationCandidates (CERTIF)
  certif/app/adapters/certification-candidate.js
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/app/models/session.js
  certif/app/routes/authenticated/sessions/details.js
  certif/app/routes/authenticated/sessions/details/parameters.js
  certif/app/services/current-user.js
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/mirage/config.js
  certif/mirage/factories/certification-candidate.js
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/acceptance/session-details-certification-candidates-test.js
  certif/tests/acceptance/session-details-parameters-test.js
  certif/tests/acceptance/session-details-test.js
  certif/tests/unit/adapters/certification-candidate-test.js
  certif/tests/unit/controllers/authenticated/sessions/details-test.js
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates-test.js
  certif/tests/unit/models/session-test.js
  certif/tests/unit/routes/authenticated/sessions/details-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2078 [FEATURE][PE] Mise à jour des données mocker pour le partage de résultat de campagne (PIX-1537)
  api/lib/domain/events/handle-campaign-participation-results-sending.js
  api/tests/unit/domain/events/handle-campaign-participation-results-sending_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2077 [BUGFIX] Le téléchargement du template CSV SCO agri ne fonctionne pas
  api/lib/infrastructure/repositories/membership-repository.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2060 [FEATURE] Amélioration de l'affichage des réponses en cas de mauvaise réponse sur les QCU (PIX-1475).
  mon-pix/app/components/qcu-solution-panel.js
  mon-pix/app/styles/components/_qcu-solution-panel.scss
  mon-pix/app/templates/components/qcu-solution-panel.hbs
  mon-pix/config/environment.js
  mon-pix/tests/integration/components/qcu-solution-panel-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, team-evaluation

#2081 [FEATURE] Autoriser l'import d'apprenti pour SCO Agriculture (Pix-1356)
  api/db/migrations/20201027144304_add_nationalApprenticeId_to_schooling-registrations.js
  api/lib/domain/models/SchoolingRegistration.js
  api/lib/domain/validators/schooling-registration-validator.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/tests/unit/domain/validators/schooling-registration-validator_test.js
  api/tests/unit/infrastructure/serializers/csv/schooling-registration-parser_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2057 [CLEANUP] Refacto des vérifications concernant la pérennité des comptes dans les usecases (PIX-1499).
  api/lib/domain/services/user-reconciliation-service.js
  api/lib/domain/usecases/create-and-reconcile-user-to-schooling-registration.js
  api/lib/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user.js
  api/lib/domain/usecases/reconcile-schooling-registration.js
  api/tests/acceptance/application/schooling-registration-user-association-controller_test.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
  api/tests/unit/domain/usecases/reconcile-schooling-registration_test.js
Labels: :rocket: Ready to Merge, hacktoberfest-accepted, team-acces

#1902 [TECH] Montée de version d'Ember (3.18 → 3.21) et des dépendances de Pix Admin.
  admin/.eslintrc.js
  admin/.travis.yml
  admin/app/app.js
  admin/app/components/certification-center-form.hbs
  admin/app/components/certification-centers/list-items.hbs
  admin/app/components/member-item.hbs
  admin/app/components/organization-form.hbs
  admin/app/components/organizations/list-items.hbs
  admin/app/components/sessions/list-items.hbs
  admin/app/components/target-profiles/list-items.hbs
  admin/app/components/users/list-items.hbs
  admin/app/router.js
  admin/app/routes/authenticated/certifications/certification.js
  admin/app/routes/authenticated/certifications/certification/details.js
  admin/app/routes/authenticated/certifications/certification/informations.js
  admin/app/routes/authenticated/sessions/session.js
  admin/config/ember-cli-update.json
  admin/config/targets.js
  admin/package-lock.json
  admin/package.json
  admin/tests/test-helper.js
  admin/tests/unit/routes/authenticated/certifications/certification-test.js
  admin/tests/unit/routes/authenticated/sessions/session-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team
