Repository 1024pix/pix, pull requests merged in 2020-04, with the labels that each got.

#1236 [TECH] Renommer le type de campagne TEST_GIVEN to ASSESSMENT (PO-399).
  admin/app/components/organization-information-section.hbs
  api/db/migrations/20200331131815_replace-campaign-type-TEST_GIVEN-by-ASSESSMENT.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/usecases/create-campaign.js
  api/tests/tooling/database-builder/factory/build-campaign.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/domain/models/CampaignParticipation_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/create-assessment-for-campaign_test.js
  api/tests/unit/domain/usecases/find-smart-placement-assessments_test.js
  api/tests/unit/domain/usecases/get-assessment_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  high-level-tests/e2e/cypress/fixtures/campaigns.json
  orga/app/models/campaign.js
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs
  orga/tests/acceptance/campaign-details-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details-item-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/parameters-tab-test.js
  orga/tests/unit/models/campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1234 [BUGFIX] Affichage menu sous IE (PC-140)
  certif/app/styles/pages/authenticated.scss
Labels: Func Review Needed, Tech Review OK, team-certif

#1231 [FEATURE] Modifier le design de la modal de changement de mot de passe (PO-382).
  orga/app/components/pix-modal.js
  orga/app/styles/app.scss
  orga/app/styles/components/password-reset-modal.scss
  orga/app/styles/globals/pix-modal.scss
  orga/app/templates/components/password-reset-window.hbs
Labels: Design Review OK, Func Review OK, Tech Review Needed, team-accès

#1250 [DESIGN-SYSTEM] Changer les couleurs utilisées dans Pix Orga pour celles du design system (PO-410).
  orga/app/styles/app.scss
  orga/app/styles/components/circle-chart.scss
  orga/app/styles/components/current-organization.scss
  orga/app/styles/components/login-form.scss
  orga/app/styles/components/login-or-register.scss
  orga/app/styles/components/pagination-control.scss
  orga/app/styles/components/progression-gauge.scss
  orga/app/styles/components/search-input.scss
  orga/app/styles/components/select-creator.scss
  orga/app/styles/components/sidebar-menu.scss
  orga/app/styles/components/user-logged-menu.scss
  orga/app/styles/globals/buttons.scss
  orga/app/styles/globals/colors.scss
  orga/app/styles/globals/ember-power-select-custom.scss
  orga/app/styles/globals/errors.scss
  orga/app/styles/globals/forms.scss
  orga/app/styles/globals/loading.scss
  orga/app/styles/globals/panels.scss
  orga/app/styles/globals/pix-modal.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/globals/texts.scss
  orga/app/styles/globals/titles.scss
  orga/app/styles/pages/authenticated.scss
  orga/app/styles/pages/authenticated/campaigns/details.scss
  orga/app/styles/pages/authenticated/campaigns/details/analysis.scss
  orga/app/styles/pages/authenticated/campaigns/details/collective-results/success-indicator.scss
  orga/app/styles/pages/authenticated/campaigns/details/parameters.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant-results.scss
  orga/app/styles/pages/authenticated/campaigns/list.scss
  orga/app/styles/pages/authenticated/students/list.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/styles/pages/authenticated/terms-of-service.scss
  orga/app/styles/pages/join.scss
  orga/app/styles/pages/login.scss
Labels: Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1254 [FEATURE] Invitation à Pix Orga depuis Pix Admin (PA-96).
  admin/app/adapters/organization-invitation.js
  admin/app/components/organization-members-section.hbs
  admin/app/controllers/authenticated/organizations/get.js
  admin/app/models/organization-invitation.js
  admin/app/styles/authenticated/organizations/get.scss
  admin/app/templates/authenticated/organizations/get.hbs
  admin/app/utils/email-validator.js
  admin/mirage/config.js
  admin/tests/acceptance/organization-memberships-management-test.js
  admin/tests/integration/components/organization-members-section-test.js
  admin/tests/unit/controllers/authenticated/organizations/get-test.js
  admin/tests/unit/utils/email-validator-test.js
Labels: Func Review OK, Tech Review Needed, team-accès

#1151 [TECH] Sauvegarder l'obtention des badges
  api/db/migrations/20200302104707_create_badge_acquisitions.js
  api/db/migrations/20200320163042_add_functional_key_on_badges_table.js
  api/db/seeds/data/campaigns-builder.js
  api/db/seeds/data/clea-target-profile-builder.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/db/seeds/seed.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/events/AssessmentCompleted.js
  api/lib/domain/events/handle-badge-acquisition.js
  api/lib/domain/events/index.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/BadgeAcquisition.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/usecases/complete-assessment.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/DomainTransaction.js
  api/lib/infrastructure/data/badge-acquisition.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/lib/infrastructure/utils/dependency-injection.js
  api/lib/infrastructure/utils/inject-defaults.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/tooling/database-builder/factory/build-badge-acquisition.js
  api/tests/tooling/database-builder/factory/build-badge.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-badge.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/application/campaignParticipationResult/campaign-participation-result_test.js
  api/tests/unit/domain/events/handle-badge-acquisition_test.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
  api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
  api/tests/unit/infrastructure/utils/dependency-injection_test.js
  api/tests/unit/infrastructure/utils/inject-defaults_test.js
  docs/adr/0008-découplage-fonctionnel-via-evenements.md
  docs/adr/0009-transaction-metier.md
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/templates/components/user-certifications-detail-result.hbs
Labels: Func Review Needed, Tech Review Needed, team-certif

#1261 [TECH] Suppression du endpoint obsolète /metrics.
  api/lib/application/metrics/index.js
  api/lib/application/metrics/metric-controller.js
  api/lib/infrastructure/plugins/metrics.js
  api/lib/plugins.js
  api/lib/routes.js
  api/package-lock.json
  api/package.json
  api/tests/unit/application/metrics/index_test.js
  api/tests/unit/application/metrics/metric-controller_test.js
  api/tests/unit/infrastructure/plugins/metrics_test.js
Labels: team-captains

#1248 [TECH] Catégoriser les envois d'e-mail en alimentant la propriété TAGS (PF-1213).
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/infrastructure/mailers/SendinblueProvider.js
  api/scripts/send-invitations-to-sco-organizations.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
Labels: Tech Review Needed, team-accès

#1249 [FEATURE] Afficher la liste des tutos sauvegardés sur une page dédiée (PF-1096).
  api/lib/application/tutorials/index.js
  api/lib/application/user-tutorials/index.js
  api/lib/application/user-tutorials/user-tutorials-controller.js
  api/lib/domain/usecases/find-tutorials.js
  api/lib/domain/usecases/find-user-tutorials.js
  api/lib/domain/usecases/get-correction-for-answer.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-tutorial-repository.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/tutorials/tutorials-controller_test.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/integration/infrastructure/repositories/user-tutorial-repository_test.js
  api/tests/unit/application/tutorials/index_test.js
  api/tests/unit/application/tutorials/tutorials-controller_test.js
  api/tests/unit/application/tutorials/user-tutorials-controller_test.js
  api/tests/unit/domain/usecases/find-tutorials_test.js
  api/tests/unit/domain/usecases/find-user-tutorials_test.js
  api/tests/unit/domain/usecases/get-correction-for-answer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tutorial-serializer_test.js
  mon-pix/app/adapters/tutorial.js
  mon-pix/app/components/navbar-burger-menu.js
  mon-pix/app/components/tutorial-item.js
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/models/tutorial.js
  mon-pix/app/routes/user-tutorials.js
  mon-pix/app/styles/components/_tutorial-item.scss
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/tutorial-item.hbs
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/app/templates/user-tutorials.hbs
  mon-pix/config/environment.js
  mon-pix/tests/unit/adapters/tutorial-test.js
  mon-pix/tests/unit/components/tutorial-item-test.js
Labels: Func Review Needed, Tech Review OK, team-évaluation

#1262 [DOC] Corriger la section sur le nommage des commits
  docs/CONTRIBUTING.md
Labels: :rocket: Ready to Merge

#1260 [FEATURE] MAJ Logo et phrase badge Cléa (PF-1211).
  api/db/seeds/data/campaigns-builder.js
  api/db/seeds/data/clea-target-profile-builder.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/db/seeds/seed.js
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/public/images/badges/Pix-emploi.svg
  mon-pix/public/images/badges/Pret-CleaNum.svg
Labels: Tech Review OK, team-évaluation

#1243 [TECH] Ajout et utilisation d'une route pour récupérer toutes les answers (PF-1195).
  api/lib/application/answers/answer-controller.js
  api/lib/application/answers/index.js
  api/lib/domain/usecases/find-answer-by-assessment.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/acceptance/application/answers/answer-controller-find_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/unit/application/answers/index_test.js
  api/tests/unit/domain/usecases/find-answer-by-assessment_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/mirage/routes/answers/get-answer-by-challenge-and-assessment.js
  mon-pix/tests/unit/routes/assessments/challenge-test.js
Labels: Tech Review Needed, team-évaluation

#1252 [FEATURE] Rendre une épreuve multilangue (PF-1196)
  api/lib/domain/models/Challenge.js
  api/lib/domain/services/pick-challenge-service.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-locale-management.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/fixtures/infrastructure/challengeAirtableDataObjectFixture.js
  api/tests/tooling/fixtures/infrastructure/challengeRawAirTableFixture.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/services/pick-challenge-service_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#1259 [BUGFIX] Correction du design du loader dans Pix Orga (PO-413).
  orga/app/styles/globals/pix-modal.scss
Labels: Design Review Needed, Tech Review Needed, team-accès

#1266 [BUGFIX] Correction du design du formulaire de rattachement de profils cibles (PA-200).
  admin/app/components/organization-target-profiles-section.hbs
Labels: Tech Review Needed, team-accès

#1253 [FEATURE] Créer des campagnes de type collecte de profils (PO-392).
  api/lib/domain/models/Campaign.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/validators/campaign-validator.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/lib/infrastructure/serializers/jsonapi/membership-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-orga-settings-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-memberships_test.js
  api/tests/integration/domain/usecases/create-campaign_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/tooling/domain-builder/factory/build-membership.js
  api/tests/tooling/domain-builder/factory/build-user-orga-settings.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/usecases/create-campaign_test.js
  api/tests/unit/domain/validations/campaign-validator_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-orga-settings-serializer_test.js
  high-level-tests/e2e/cypress/fixtures/organizations.json
  high-level-tests/e2e/cypress/integration/campaign-management.feature
  orga/app/components/routes/authenticated/campaigns/new-item.js
  orga/app/models/campaign.js
  orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs
  orga/mirage/config.js
  orga/tests/acceptance/campaign-creation-test.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/routes/authenticated/campaigns/new-item-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1232 [CLEANUP] Convertir les services PixApp en syntaxe native (PF-1193).
  mon-pix/app/services/current-domain.js
  mon-pix/app/services/current-user.js
  mon-pix/app/services/google-recaptcha.js
  mon-pix/app/services/mail-generator.js
  mon-pix/app/services/peeker.js
  mon-pix/app/services/splash.js
Labels: Func Review Needed, Tech Review Needed, team-accès, team-certif, team-prescription, team-évaluation

#1225 [FEATURE] Ajout d'une date de publication dans la session (PA-153)
  admin/app/components/sessions/list-items.hbs
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/models/session.js
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/mirage/factories/session.js
  admin/tests/acceptance/session-test.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.js
  admin/tests/unit/models/session-test.js
  api/db/migrations/20200326163043_add-published-at-column-to-table-sessions.js
  api/db/migrations/20200327084158_drop_column_status_table_sessions.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/db/seeds/data/certification/certification-courses-builder.js
  api/db/seeds/data/certification/certification-scores-builder.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/application/error-manager.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/create-session.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/domain/usecases/flag-session-results-as-sent-to-prescriber.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-certification-publication-status.js
  api/lib/domain/usecases/update-publication-session.js
  api/lib/domain/usecases/update-session.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/acceptance/application/session/session-controller-patch-update-publication-session_test.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/integration/application/certifications/index_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/tooling/database-builder/factory/build-session.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/create-session_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  api/tests/unit/domain/usecases/flag-session-results-as-sent-to-prescriber_test.js
  api/tests/unit/domain/usecases/update-certification-publication-status_test.js
  api/tests/unit/domain/usecases/update-publication-session_test.js
  api/tests/unit/domain/usecases/update-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  certif/app/models/session.js
Labels: Func Review Needed, Tech Review Needed, team-certif

#1271 [FEATURE] Supprimer un tutoriel de sa liste personnalisée (PF-1180).
  api/lib/application/user-tutorials/index.js
  api/lib/application/user-tutorials/user-tutorials-controller.js
  api/lib/domain/usecases/find-tutorials.js
  api/lib/domain/usecases/find-user-tutorials.js
  api/lib/domain/usecases/get-correction-for-answer.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/lib/infrastructure/repositories/user-tutorial-repository.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-attributes.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-tutorial-attributes.js
  api/lib/infrastructure/serializers/jsonapi/user-tutorial-serializer.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/integration/infrastructure/repositories/user-tutorial-repository_test.js
  api/tests/tooling/database-builder/factory/build-user-tutorial.js
  api/tests/unit/application/user-tutorials/index_test.js
  api/tests/unit/application/user-tutorials/user-tutorials-controller_test.js
  api/tests/unit/domain/usecases/find-tutorials_test.js
  api/tests/unit/domain/usecases/find-user-tutorials_test.js
  api/tests/unit/domain/usecases/get-correction-for-answer_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tutorial-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-tutorial-serializer_test.js
  mon-pix/app/adapters/tutorial.js
  mon-pix/app/adapters/user-tutorial.js
  mon-pix/app/components/tutorial-item.js
  mon-pix/app/models/tutorial.js
  mon-pix/app/models/user-tutorial.js
  mon-pix/app/routes/user-tutorials.js
  mon-pix/app/templates/components/tutorial-item.hbs
  mon-pix/app/templates/user-tutorials.hbs
  mon-pix/tests/acceptance/save-tutorial-test.js
  mon-pix/tests/unit/adapters/tutorial-test.js
  mon-pix/tests/unit/adapters/user-tutorial-test.js
  mon-pix/tests/unit/components/tutorial-item-test.js
Labels: Design Review Needed, Func Review OK, Tech Review OK, team-évaluation

#1265 [BUGFIX] Ré-afficher les messages d'erreurs renvoyés par l'API (PO-414).
  admin/package-lock.json
  admin/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: Tech Review Needed, team-accès

#1270 [TECH] Renommer tubeName de Skill dans api
  api/lib/domain/models/KnowledgeElement.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/Tube.js
  api/lib/domain/services/smart-random/cat-algorithm.js
  api/lib/domain/services/tube-service.js
  api/lib/domain/usecases/find-tutorials.js
  api/tests/unit/domain/models/Skill_test.js
Labels: Tech Review Needed, team-accès, team-certif, team-prescription, team-évaluation

#1256 [TECH] Ajout de tests E2E Cypress sur PixCertif (PC-142)
  .circleci/config.yml
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/cypress/fixtures/certification-candidates.json
  high-level-tests/e2e/cypress/fixtures/certification-center-memberships.json
  high-level-tests/e2e/cypress/fixtures/certification-centers.json
  high-level-tests/e2e/cypress/fixtures/certification-courses.json
  high-level-tests/e2e/cypress/fixtures/sessions.json
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/integration/pix-certif/certification-candidates-management.feature
  high-level-tests/e2e/cypress/integration/pix-certif/certification-session-creation.feature
  high-level-tests/e2e/cypress/integration/pix-certif/certification-session-finalization.feature
  high-level-tests/e2e/cypress/integration/pix-certif/certification-session-update.feature
  high-level-tests/e2e/cypress/integration/pix-certif/login-logout-certif.feature
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  high-level-tests/e2e/cypress/support/step_definitions/pix-certif/session.js
  high-level-tests/e2e/package.json
Labels: Tech Review Needed, team-captains

#1269 [TECH] Supprimer le endpoint DELETE /api/cache
  api/lib/application/cache/cache-controller.js
  api/lib/application/cache/index.js
  api/scripts/reload-cache-everyday.js
  api/tests/acceptance/application/cache-controller_test.js
  api/tests/unit/application/cache/cache-controller_test.js
  api/tests/unit/application/cache/index_test.js
  mon-pix/app/adapters/correction.js
  mon-pix/app/routes/challenge-preview.js
  mon-pix/mirage/config.js
  mon-pix/tests/unit/adapters/correction-test.js
Labels: Tech Review OK, team-accès, team-captains, team-certif, team-prescription, team-évaluation

#1273 [CLEANUP] Ajout de tests end-to-end pour la fonctionnalité de sauvegarde de tutoriels
  high-level-tests/e2e/cypress/integration/user-tutorials.feature
  high-level-tests/e2e/cypress/support/step_definitions/user-tutorials.js
Labels: Tech Review Needed, team-évaluation

#1268 [FEATURE] Pouvoir envoyer son profil Pix au prescripteur de la campagne de type Collecte de profils (PF-1178).
  api/db/seeds/data/campaigns-builder.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/get-user-campaign-participation-to-campaign.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/share-campaign-result.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-participation-to-campaign_test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-user-campaign-participation-to-campaign_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
  high-level-tests/e2e/cypress/fixtures/campaigns.json
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  high-level-tests/e2e/cypress/integration/pix-app/demo.feature
  high-level-tests/e2e/cypress/integration/pix-app/login-logout-app.feature
  high-level-tests/e2e/cypress/integration/pix-app/page-title.feature
  high-level-tests/e2e/cypress/integration/pix-app/preview.feature
  high-level-tests/e2e/cypress/integration/pix-app/profile.feature
  high-level-tests/e2e/cypress/integration/pix-app/signup.feature
  high-level-tests/e2e/cypress/integration/pix-app/user-tutorials.feature
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  high-level-tests/e2e/cypress/integration/pix-orga/login-logout-orga.feature
  high-level-tests/e2e/cypress/integration/pix-orga/organization-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  mon-pix/app/adapters/campaign-participation.js
  mon-pix/app/controllers/campaigns/send-profile.js
  mon-pix/app/models/campaign.js
  mon-pix/app/router.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/send-profile.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/_send-profile.scss
  mon-pix/app/templates/campaigns/send-profile.hbs
  mon-pix/mirage/routes/campaign-participations/post-campaign-participation.js
  mon-pix/mirage/routes/users/get-user-campaign-participation-to-campaign.js
  mon-pix/mirage/routes/users/index.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-collect-profiles-test.js
  mon-pix/tests/unit/controllers/campaigns/send-profile-test.js
  mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
  mon-pix/tests/unit/routes/campaigns/send-profile-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1240 [CLEANUP] Extraire la logique de scoring de certification dans un Event Handler dédié (PF-1202)
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/events/AssessmentCompleted.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/events/index.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/usecases/complete-assessment.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
Labels: Tech Review Needed, team-certif, team-évaluation

#1208 [FEATURE] certif clea zone verte (pf-1146)
  api/db/migrations/20200327110821_save_acquired_partner_certification_key_on_certif_course_table.js
  api/db/seeds/data/certification/user-badge-builder.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/db/seeds/seed.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/events/index.js
  api/lib/domain/models/AssessmentScore.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/Certification.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/models/CertificationPartnerAcquisition.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/certification-course.js
  api/lib/infrastructure/data/certification-partner-acquisition.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/certification-partner-acquisition-repository.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/integration/domain/services/scoring/scoring-certification_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-partner-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/tooling/database-builder/factory/build-certification-acquired-partner.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-certification.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  mon-pix/app/models/certification.js
  mon-pix/app/templates/components/user-certifications-detail-result.hbs
  mon-pix/public/images/badges/CleA_Num_certif.svg
  mon-pix/tests/integration/components/user-certifications-detail-result-test.js
  mon-pix/tests/unit/models/certification-test.js
Labels: Func Review Needed, Tech Review Needed, team-certif

#1185 [CLEANUP] Faire les calculs de score et de niveau à un seul endroit.
  api/lib/domain/models/Scorecard.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/domain/services/scoring/scoring-service.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/get-assessment.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/get-user-scorecards.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/domain/services/scoring/scoring-certification_test.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/services/scoring/scoring-service_test.js
  api/tests/unit/domain/usecases/get-user-scorecards_test.js
Labels: Func Review Needed, Tech Review OK, team-certif, team-évaluation

#1272 [BUGFIX] Messages d'erreurs d'authentifications erronés dans pix-certif (PC-143)
  admin/app/components/login-form.js
  certif/app/components/login-form.js
  certif/tests/integration/components/login-form-test.js
  orga/app/components/routes/login-form.js
  orga/tests/acceptance/join-test.js
  orga/tests/integration/components/routes/login-form-test.js
Labels: Func Review Needed, Tech Review Needed, team-accès

#1282 [FEATURE] Ajout d'un commentaire en dessous des profils cibles lors de la création d'une campagne (PO-415).
  api/lib/domain/validators/campaign-validator.js
  api/tests/unit/domain/validations/campaign-validator_test.js
  orga/app/components/routes/authenticated/campaigns/new-item.js
  orga/app/routes/authenticated/students.js
  orga/app/services/current-user.js
  orga/app/styles/globals/forms.scss
  orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs
  orga/app/templates/components/sidebar-menu.hbs
  orga/tests/integration/components/routes/authenticated/campaigns/new-item-test.js
  orga/tests/unit/services/current-user-test.js
Labels: Func Review Needed, Tech Review Needed, team-prescription

#1284 [FEATURE] Ajout d'un composant pour représenter les différents niveaux de recommandation des sujets (PO-403).
  orga/app/components/recommendation-indicator.js
  orga/app/helpers/multiply.js
  orga/app/helpers/sum.js
  orga/app/styles/app.scss
  orga/app/styles/components/recommendation-indicator.scss
  orga/app/templates/components/recommendation-indicator.hbs
  orga/tests/integration/components/recommendation-indicator-test.js
  orga/tests/unit/helpers/multiply-test.js
  orga/tests/unit/helpers/sum-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Tech Review OK, team-prescription

#1287 [BUGFIX] Campagnes non affichées sur IE (PO-398).
  orga/README.md
  orga/app/styles/pages/authenticated/campaigns/list.scss
  orga/app/templates/authenticated/campaigns/list.hbs
Labels: :rocket: Ready to Merge

#1278 [TECH] Retourner une réponse 204 lors de l'appel de rafraichissement du cache
  admin/app/controllers/authenticated/tools.js
  api/lib/application/cache/cache-controller.js
  api/tests/unit/application/cache/cache-controller_test.js
Labels: Tech Review Needed, team-captains

#1285 [TECH] Ajout de tests de non régression visuelle.
  .gitignore
  high-level-tests/e2e/README.md
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/cypress/integration/pix-app/user-tutorials.feature
  high-level-tests/e2e/cypress/plugins/index.js
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Compétence non commencée-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mathématiques - 1ere question-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mathématiques - 2eme question-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mathématiques - résultat évaluation-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mes Tutos - 1 tuto enregistré-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mes Tutos vide-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Profil-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Réponses et tutos - tuto enregistré-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Réponses et tutos-base.png
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
Labels: Tech Review Needed, team-accès, team-certif, team-prescription, team-évaluation

#1289 [FEATURE] Ajout d'informations sur la méthode de calcul des recommandations (PO-405).
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/campaigns/details/analysis/analysis-tab.scss
  orga/app/templates/components/routes/authenticated/campaigns/details/analysis-tab.hbs
Labels: Func Review OK, Tech Review OK

#1283 [FEATURE] Exporter les résultats de campagne de collecte de profils (PO-393).
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/seed.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/models/CertificationProfile.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/application/campaigns/index_test.js
  api/tests/integration/domain/usecases/create-campaign_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/models/CertificationProfile_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  orga/app/models/campaign.js
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/tests/unit/models/campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1296 [BUGFIX] Le menu "Élèves" ne s'affiche pas correctement lorsque l'on change d'organisation (PO-426).
  orga/app/services/current-user.js
  orga/tests/acceptance/switch-organization-test.js
  orga/tests/helpers/test-init.js
  orga/tests/unit/models/campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-accès, team-prescription

#1301 [FEATURE] Appliquer une recherche stricte sur le filtre de la colonne ID dans la liste des sessions sur PixAdmin (PA-202)
  api/lib/infrastructure/repositories/session-repository.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1290 [FEATURE] Changement des formulations de la landing page des collectes de profils (PF-1222).
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  high-level-tests/e2e/cypress/snapshots/base/pix-app/campaign-assessment.feature/Presentation campagne evaluation-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/campaign-collect-profiles.feature/Presentation campagne collecte profils-base.png
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/app/templates/components/campaign-start-block.hbs
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-collect-profiles-test.js
  mon-pix/tests/integration/components/campaign-start-block-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1307 [TECH] Ajout de tests e2e (PF-1246).
  high-level-tests/e2e/cypress/fixtures/knowledge-elements.json
  high-level-tests/e2e/cypress/fixtures/memberships.json
  high-level-tests/e2e/cypress/fixtures/organization-invitations.json
  high-level-tests/e2e/cypress/fixtures/target-profiles_skills.json
  high-level-tests/e2e/cypress/fixtures/user-orga-settings.json
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/demo.feature
  high-level-tests/e2e/cypress/integration/pix-app/preview.feature
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  high-level-tests/e2e/cypress/integration/pix-orga/members-management.feature
  high-level-tests/e2e/cypress/integration/pix-orga/organization-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  high-level-tests/e2e/cypress/support/step_definitions/member.js
  high-level-tests/e2e/cypress/support/step_definitions/organization.js
  mon-pix/app/templates/campaigns/skill-review.hbs
  orga/app/templates/components/routes/authenticated/team/list-items.hbs
Labels: :rocket: Ready to Merge, Tech Review OK, team-prescription

#1306 [FEATURE] Ordonner la liste des sessions paginée dans PixAdmin de sorte à remonter les sessions à traiter en premier par le pôle certification (PA-178)
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/lib/infrastructure/repositories/session-repository.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1305 [FEATURE] Ajout de la date de diffusion au prescripteur dans la liste des sessions sur PixAdmin (PA-189)
  admin/app/components/sessions/list-items.hbs
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1304 [TECH] Tester la présence d'un ID et pas sa valeur dans le test auto sur les tutos (PF-1244)
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
Labels: Tech Review Needed, team-évaluation

#1199 [FEATURE] Permettre l'utilisation d'un mot de passe à usage unique (PF-1027).
  api/db/migrations/20200320171110_add_column_shouldChangePassword_to_table_users.js
  api/db/seeds/data/po376-builder.js
  api/db/seeds/data/users-builder.js
  api/db/seeds/seed.js
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/error-manager.js
  api/lib/application/http-errors.js
  api/lib/application/passwords/index.js
  api/lib/application/passwords/password-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/User.js
  api/lib/domain/services/authentication-service.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-expired-password.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/acceptance/application/password-controller_test.js
  api/tests/integration/application/passwords/index_test.js
  api/tests/integration/application/passwords/password-controller_test.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/passwords/index_test.js
  api/tests/unit/application/passwords/password-controller_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/services/authentication-service_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/update-expired-password_test.js
  docs/security/reset_with_temporary_password.puml
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/integration/pix-app/update-password.feature
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  high-level-tests/e2e/cypress/support/step_definitions/update-password.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/signin-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/controllers/update-expired-password.js
  mon-pix/app/router.js
  mon-pix/app/routes/login.js
  mon-pix/app/routes/update-expired-password.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/_update-expired-password-form.scss
  mon-pix/app/templates/components/update-expired-password-form.hbs
  mon-pix/app/templates/login.hbs
  mon-pix/app/templates/update-expired-password.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/factories/user.js
  mon-pix/mirage/routes/auth/post-authentications.js
  mon-pix/mirage/routes/post-expired-password-updates.js
  mon-pix/tests/acceptance/authentication-test.js
  mon-pix/tests/acceptance/update-expired-password-test.js
  mon-pix/tests/integration/components/update-expired-password-form-test.js
  mon-pix/tests/unit/adapters/user-test.js
  mon-pix/tests/unit/components/update-expired-password_test.js
  mon-pix/tests/unit/routes/update-expired-password-test.js
Labels: team-accès

#1280 [FEATURE] Pouvoir s'assigner une session à traiter dans PixAdmin (PA-137)
  admin/app/adapters/session.js
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/models/session.js
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js
  admin/tests/acceptance/session-test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.js
  admin/tests/unit/adapters/session-test.js
  admin/tests/unit/controllers/authenticated/sessions/session/informations-test.js
  api/db/migrations/20200327225551_add-column-assignedCertificationOfficerId-column-table-sessions.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/assign-certification-officer-to-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/acceptance/application/session/session-controller-patch-user-assignment_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/tooling/database-builder/factory/build-session.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/assign-certification-officer-to-session_test.js
  api/tests/unit/domain/usecases/flag-session-results-as-sent-to-prescriber_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  certif/app/models/session.js
Labels: Func Review OK, Tech Review OK, team-certif

#1286 [FEATURE] Afficher le détail des utilisateurs dans Pix Admin (PA-192).
  admin/app/adapters/user.js
  admin/app/components/user-detail-personal-information.hbs
  admin/app/components/users/list-items.hbs
  admin/app/controllers/authenticated/users/list.js
  admin/app/models/user.js
  admin/app/router.js
  admin/app/routes/authenticated/users/get.js
  admin/app/templates/authenticated/users/get.hbs
  admin/app/templates/authenticated/users/list.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/users/get-test.js
  admin/tests/integration/components/routes/authenticated/users/list-items-test.js
  admin/tests/integration/components/user-detail-personal-information-test.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/read-models/UserDetailForAdmin.js
  api/lib/domain/usecases/get-user-detail-for-admin.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-detail-for-admin-serializer.js
  api/tests/integration/application/users/index_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-user-detail-for-admin_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-detail-for-admin-serializer_test.js
Labels: Func Review OK, Tech Review Needed, team-accès

#1279 [CLEANUP] Glimmerisation du composant pour gérer les simulateurs embarqués dans les épreuves (PF-1241).
  mon-pix/app/components/challenge-embed-simulator.js
  mon-pix/app/styles/components/_challenge-embed-simulator.scss
  mon-pix/app/templates/components/challenge-embed-simulator.hbs
  mon-pix/tests/integration/components/challenge-embed-simulator-test.js
Labels: Func Review OK, Tech Review Needed, team-évaluation

#1291 [FEATURE] Calculer et afficher la recommandation des tubes d'une campagne d'évaluation (PO-380).
  api/lib/domain/models/CampaignAnalysis.js
  api/lib/domain/models/CampaignTubeRecommendation.js
  api/lib/domain/services/recommendation-service.js
  api/lib/domain/usecases/compute-campaign-analysis.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-analysis-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/domain/models/CampaignAnalysis_test.js
  api/tests/integration/domain/usecases/compute-campaign-analysis_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-tube-recommendation.js
  api/tests/unit/domain/models/CampaignTubeRecommendation_test.js
  api/tests/unit/domain/services/recommendation-service_test.js
  api/tests/unit/domain/usecases/compute-campaign-analysis_test.js
  api/tests/unit/infrastructure/repositories/competence-tree-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-analysis-serializer_test.js
  orga/app/models/campaign-analysis.js
  orga/app/models/campaign-tube-recommendation.js
  orga/app/styles/globals/tables.scss
  orga/app/templates/authenticated/campaigns/details/analysis.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/analysis-tab.hbs
  orga/tests/unit/models/campaign-analysis-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1294 [FEATURE] Ajout d'une entrée Analyse dans la sous navigation du détails d'une campagne (PO-407).
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/tests/acceptance/campaign-details-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details-item-test.js
Labels: Func Review OK, Tech Review Needed, team-prescription

#1314 [FEATURE] afficher l id de certif dans le champ de recherche admin (PA-201)
  admin/app/routes/authenticated/certifications/certification.js
  admin/tests/unit/routes/authenticated/certifications/certification-test.js
  admin/tests/unit/routes/authenticated/sessions/session-test.js
Labels: team-certif

#1210 [TECH] Mise en transaction de la création des éléments nécessaires à un test de certification (CertifCourse, assessment et challenges) (PF-1179)
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/begin-campaign-participation-improvement.js
  api/lib/domain/usecases/create-assessment-for-campaign.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/domain/usecases/start-or-resume-competence-evaluation.js
  api/lib/infrastructure/data/certification-course.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/certification-challenge-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/integration/domain/services/user-service_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/begin-campaign-participation-improvement_test.js
  api/tests/unit/domain/usecases/create-assessment-for-campaign_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
  api/tests/unit/domain/usecases/start-or-resume-competence-evaluation_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1312 [BUGFIX] Restreindre l'accès au détail d'une campagne dans Pix Orga (PO-357).
  api/lib/application/campaigns/index.js
  api/lib/application/usecases/checkUserCanAccessCampaign.js
  api/lib/interfaces/controllers/security-controller.js
  api/tests/acceptance/application/security-controller_test.js
  api/tests/integration/application/campaigns/index_test.js
  api/tests/unit/application/usecases/checkUserCanAccessCampaign_test.js
  api/tests/unit/interfaces/controllers/security-controller_test.js
Labels: Tech Review Needed, team-accès

#1316 [TECH] Remplacer les dummy tests unitaires par défaut Ember par de vrais tests (PC-145)
  certif/app/routes/authenticated/index.js
  certif/app/routes/authenticated/sessions.js
  certif/app/routes/authenticated/sessions/list.js
  certif/tests/unit/adapters/application-test.js
  certif/tests/unit/adapters/certification-candidate-test.js
  certif/tests/unit/adapters/user-test.js
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates-test.js
  certif/tests/unit/controllers/terms-of-service-test.js
  certif/tests/unit/routes/application-test.js
  certif/tests/unit/routes/authenticated/index-test.js
  certif/tests/unit/routes/authenticated/sessions-test.js
  certif/tests/unit/routes/authenticated/sessions/details-test.js
  certif/tests/unit/routes/authenticated/sessions/details/certification-candidate-test.js
  certif/tests/unit/routes/authenticated/sessions/finalize-test.js
  certif/tests/unit/routes/authenticated/sessions/list-test.js
  certif/tests/unit/routes/authenticated/sessions/new-test.js
  certif/tests/unit/routes/authenticated/sessions/update-test.js
  certif/tests/unit/routes/not-found-test.js
Labels: Tech Review OK, team-certif

#1319 [BUGFIX] Affichage non correct du résumé des résultats collectifs de campagne d'évaluation (PO-432).
  orga/app/templates/components/routes/authenticated/campaigns/details/collective-results-tab.hbs
Labels: :rocket: Ready to Merge, Design Review OK, Tech Review OK, team-prescription

#1311 [BUGFIX] Correction de l'affichage du logo sous IE (PF-1225).
  mon-pix/app/styles/components/_assessment-banner.scss
  mon-pix/public/images/pix-logo-blanc.svg
  mon-pix/public/images/pix-logo.svg
Labels: Func Review Needed, Tech Review Needed, team-évaluation

#1303 [TECH] Correction des routes d'API destinées aux diagnostics mémoire
  api/bin/www
  api/lib/application/system/system-controller.js
  api/tests/integration/application/system/dummy-heap.txt
  api/tests/integration/application/system/system-controller_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/system/system-controller_test.js
Labels: Tech Review Needed

#1300 [TECH][FIX] Catégoriser les envois d'e-mail en alimentant la propriété TAGS (PF-1242).
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/infrastructure/mailers/SendinblueProvider.js
  api/scripts/send-invitations-to-sco-organizations.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
Labels: Tech Review Needed, team-accès

#1326 [TECH] Problème de script npm start en développement.
  admin/config/environment.js
  admin/package.json
  certif/config/environment.js
  certif/package.json
  mon-pix/config/environment.js
  mon-pix/package.json
  orga/config/environment.js
  orga/package.json
Labels: team-captains

#1327 [BSR] Remplacer Promise.all par bluebird.mapSeries lors de la génération des résultats de certification d'une session entière (PA-209)
  api/lib/domain/usecases/get-session-certifications.js
Labels: Func Review Needed, Tech Review Needed, team-certif

#1322 [FEATURE] Ajout de la recommandation pour un participant à une campagne (PO-422)
  api/lib/domain/usecases/compute-campaign-participation-analysis.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/domain/usecases/compute-campaign-participation-analysis_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/test-helper.js
  orga/app/templates/authenticated/campaigns/details/analysis.hbs
  orga/app/templates/authenticated/campaigns/details/participants/participant/analysis.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/analysis-tab.hbs
  orga/mirage/config.js
  orga/mirage/serializers/campaign-participation.js
  orga/tests/acceptance/campaign-participants-individual-results-test.js
  orga/tests/acceptance/campaign-participants-indivual-analysis-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/analysis-tab-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1324 [FEATURE] Ajouter un loader au chargement de l'analyse de campagne (PO-431)
  orga/app/routes/authenticated/campaigns/details/loading.js
  orga/app/styles/app.scss
  orga/app/styles/globals/loading.scss
  orga/app/styles/globals/pix-loader.scss
  orga/app/templates/authenticated/campaigns/details/collective-results-loading.hbs
  orga/app/templates/authenticated/campaigns/details/loading.hbs
  orga/app/templates/components/pix-loader.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/public/images/interwind.gif
  orga/tests/integration/components/pix-loader-test.js
Labels: Func Review OK, Tech Review Needed, team-prescription

#1318 [FEATURE] Affichage des tutoriels par sujets dans l'analyse de campagne (PO-408).
  api/lib/domain/models/CampaignAnalysis.js
  api/lib/domain/models/CampaignTubeRecommendation.js
  api/lib/domain/usecases/compute-campaign-analysis.js
  api/lib/domain/usecases/compute-campaign-participation-analysis.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-analysis-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/campaign-participations/campaign-participations-controller-analyses_test.js
  api/tests/integration/domain/usecases/compute-campaign-analysis_test.js
  api/tests/integration/domain/usecases/compute-campaign-participation-analysis_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-tube-recommendation.js
  api/tests/unit/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-analysis-serializer_test.js
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/routes/authenticated/campaigns/details/analysis/tube-recommendation-row.js
  orga/app/models/campaign-tube-recommendation.js
  orga/app/models/tutorial.js
  orga/app/styles/app.scss
  orga/app/styles/components/recommendation-indicator.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/campaigns/details/analysis/tube-recommendation-row.scss
  orga/app/templates/components/routes/authenticated/campaigns/details/analysis-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/analysis/tube-recommendation-row.hbs
  orga/config/environment.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/analysis/tube-recommendation-row-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1275 [FEATURE] Certif clea zone rouge (PF-1147)
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/events/CertificationScoringCompleted.js
  api/lib/domain/events/handle-badge-acquisition.js
  api/lib/domain/events/handle-certification-partner.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CertificationPartnerAcquisition.js
  api/lib/domain/usecases/complete-assessment.js
  api/lib/infrastructure/DomainTransaction.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/assessment-result-repository.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/certification-challenge-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/certification-partner-acquisition-repository.js
  api/lib/infrastructure/repositories/competence-mark-repository.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/domain/events/handle-badge-acquisition_test.js
  api/tests/unit/domain/events/handle-certification-partner_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CertificationPartnerAcquisition_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
  docs/adr/0009-transaction-metier.md
Labels: Func Review Needed, Tech Review Needed, team-certif

#1309 [FEATURE] Ajouter des filtres concernant le statut et l'envoi des résultats au prescripteur sur la liste des sessions paginées (PA-205)
  admin/app/components/sessions/list-items.hbs
  admin/app/controllers/authenticated/sessions/list.js
  admin/app/routes/authenticated/sessions/list.js
  admin/app/templates/authenticated/sessions/list.hbs
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/lib/domain/usecases/find-paginated-filtered-sessions.js
  api/lib/domain/validators/session-validator.js
  api/lib/infrastructure/repositories/session-repository.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-sessions_test.js
  api/tests/unit/domain/validations/session-validator_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1333 [FEATURE] Changement du wording de la page de saisi de code (PF-1227).
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK

#1298 [TECH] Simplification de la génération de CSV de campagne d'évaluation (PO-427).
  api/lib/domain/services/campaign-csv-export-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1335 [FEATURE] Renommer et déplacer l'entrée vers la page de saisie de code depuis le menu de PIX App (PF-1226).
  mon-pix/app/styles/components/_navbar-burger-menu.scss
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/components/navbar-mobile-header.hbs
  mon-pix/tests/acceptance/navigation-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-collect-profiles-test.js
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1339 [FEATURE] Ajuster la formulation de la page d'identifiant externe (PIX-564).
  mon-pix/app/templates/campaigns/fill-in-id-pix.hbs
Labels: Func Review OK, Tech Review OK, team-prescription

#1336 [TECH] Eviter les erreurs de contraintes d'unicité.
  api/lib/application/user-orga-settings/index.js
  api/lib/application/user-orga-settings/user-orga-settings-controller.js
  api/lib/domain/usecases/create-or-update-user-orga-settings.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-orga-settings-repository.js
  api/tests/acceptance/application/user-orga-settings-controller_test.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/unit/application/user-orga-settings/index_test.js
  api/tests/unit/application/user-orga-settings/user-orga-settings-controller_test.js
  api/tests/unit/domain/usecases/create-or-update-user-orga-settings_test.js
  orga/app/adapters/user-orga-setting.js
  orga/app/components/user-logged-menu.js
  orga/app/services/current-user.js
  orga/mirage/config.js
  orga/tests/unit/adapters/user-orga-setting-test.js
Labels: Tech Review Needed, team-accès, team-captains

#1341 [BUGFIX] Le temps d'attente d'envoi de requêtes mis en place lors de la recherche de campagnes par nom dans PixOrga ne marche plus (PO-440)
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
  orga/app/templates/components/search-input.hbs
  orga/config/environment.js
  orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1342 [BUGFIX] Affichage défectueux lorsqu'on supprime rapidement un filtre sur nom dans la liste des campagnes (PIX-583)
  orga/app/controllers/authenticated/campaigns/list.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1345 [FEATURE] Retrait de la colonne "Nombre de certifications publiées" dans la liste des sessions de PixAdmin (PIX-566).
  admin/app/components/sessions/list-items.hbs
  admin/app/models/session.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  admin/tests/unit/models/session-test.js
Labels: Func Review OK, Tech Review OK, team-certif

#1338 [FEATURE] Ajout d'onglets sur la page participant (PIX-569).
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/controllers/authenticated/campaigns/details/participants.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/details/participants/participant/analysis.js
  orga/app/routes/authenticated/campaigns/details/participants/participant/results.js
  orga/app/routes/authenticated/campaigns/participant.js
  orga/app/routes/authenticated/campaigns/participant/analysis.js
  orga/app/routes/authenticated/campaigns/participant/index.js
  orga/app/routes/authenticated/campaigns/participant/loading.js
  orga/app/routes/authenticated/campaigns/participant/results.js
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant.scss
  orga/app/templates/authenticated/campaigns/details/participants/participant/analysis.hbs
  orga/app/templates/authenticated/campaigns/details/participants/participant/results.hbs
  orga/app/templates/authenticated/campaigns/participant.hbs
  orga/app/templates/authenticated/campaigns/participant/analysis.hbs
  orga/app/templates/authenticated/campaigns/participant/loading.hbs
  orga/app/templates/authenticated/campaigns/participant/results.hbs
  orga/app/templates/components/routes/authenticated/campaigns/participant/participant-header.hbs
  orga/tests/acceptance/campaign-participants-test.js
  orga/tests/acceptance/participant-results-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/participants-tab-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/participants/participant-header-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/participant/participant-header-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1350 [BUGFIX] Export CSV d'une campagne, ne pas mettre l'id externe quand la campagne n'en a pas (PIX-592).
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
Labels: Func Review Needed, Tech Review Needed, team-prescription

#1346 [TECH] Utiliser .integer() sur les validations d'ID (PIX-591).
  api/lib/application/sessions/index.js
  api/lib/application/user-orga-settings/index.js
  api/lib/application/users/index.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/models/CompetenceMark.js
  api/tests/acceptance/application/session/session-controller-create-certification-candidate-participation_test.js
  api/tests/acceptance/application/session/session-controller-patch-user-assignment_test.js
  api/tests/acceptance/application/session/session-controller-put-results-sent-to-prescriber_test.js
  api/tests/unit/application/session/index_test.js
Labels: Tech Review Needed, team-captains, team-certif

#1355 [DOC] Met à jour la description du tag de PR `BUGFIX`
  docs/CONTRIBUTING.md
Labels: Tech Review Needed

#1347 [FEATURE] Création d'une page pour afficher la nouvelle version des cgus Pix. (PF-998)
  mon-pix/app/router.js
  mon-pix/app/routes/terms-of-service.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/_terms-of-service.scss
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/tests/acceptance/terms-of-service-test.js
Labels: Func Review OK, Tech Review Needed, team-accès

#1362 [FEATURE] Ajout de la gestion du mot de passe à usage unique sur la double mire (PF-1216).
  mon-pix/app/components/routes/login-form.js
  mon-pix/tests/integration/components/routes/login-form-test.js
Labels: Tech Review Needed, team-acces

#1358 [FEATURE] Retirer la pagination à 100 sur les participations aux campagnes (PIX-594).
  orga/app/templates/components/pagination-control.hbs
Labels: Func Review Needed, Tech Review Needed, team-captains, team-prescription

#1353 [INFRA] Corriger le démarrage des apps pour les tests Cypress en local (PIX-596).
  high-level-tests/e2e/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#1354 [FEATURE] Changer le texte du loader de campagne dans pix-app (PIX-572)
  mon-pix/app/templates/campaigns/loading.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1356 [FEATURE] Changer les messages d'erreur à la saisie de code campagne (PIX-573).
  mon-pix/app/controllers/campaigns/fill-in-campaign-code.js
  mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-campaign-code-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1351 [FEATURE] Ajout d'un lien vers la documentation pour les utilisateurs d'organisations pro (PIX-565).
  orga/app/components/sidebar-menu.js
  orga/app/models/organization.js
  orga/app/templates/components/sidebar-menu.hbs
  orga/tests/integration/components/sidebar-menu-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1348 [FEATURE] Ajout d'une bannière spécifique à l'envoi de profil (PIX-568).
  mon-pix/app/components/resume-campaign-banner.js
  mon-pix/app/templates/components/resume-campaign-banner-assessment.hbs
  mon-pix/app/templates/components/resume-campaign-banner-collect-profile.hbs
  mon-pix/app/templates/components/resume-campaign-banner.hbs
  mon-pix/tests/acceptance/profile-test.js
  mon-pix/tests/integration/components/resume-campaign-banner-test.js
  mon-pix/tests/unit/components/resume-campaign-banner-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1340 [FEATURE] Afficher le profil d'un utilisateur avant qu'il le partage dans une campagne de collecte de profils (PIX-559).
  mon-pix/app/components/competence-card-default.js
  mon-pix/app/components/competence-card-mobile.js
  mon-pix/app/controllers/campaigns/send-profile.js
  mon-pix/app/routes/campaigns/send-profile.js
  mon-pix/app/styles/components/_competence-card.scss
  mon-pix/app/styles/pages/_send-profile.scss
  mon-pix/app/templates/campaigns/send-profile.hbs
  mon-pix/app/templates/components/competence-card-default.hbs
  mon-pix/app/templates/components/competence-card-mobile.hbs
  mon-pix/app/templates/components/competence-card.hbs
  mon-pix/app/templates/components/profile-content.hbs
  mon-pix/app/templates/components/profile-scorecards.hbs
  mon-pix/app/templates/components/profile-sharing-form.hbs
  mon-pix/tests/integration/components/competence-card-default-test.js
  mon-pix/tests/integration/components/competence-card-mobile-test.js
  mon-pix/tests/unit/components/competence-card-mobile-test.js
  mon-pix/tests/unit/controllers/campaigns/send-profile-test.js
  mon-pix/tests/unit/routes/campaigns/send-profile-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation, team-prescription

#1366 [FEATURE] Mise à jour de l'apparence du bouton "J'ai un code" (PIX-595).
  mon-pix/app/styles/components/_navbar-desktop-header.scss
  mon-pix/app/styles/components/_user-logged-menu.scss
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
Labels: Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1337 [FEATURE] Ajout d'un filtre sur la colonne "Centre de certification" dans la liste des sessions paginée sur PixAdmin (PA-210)
  admin/app/components/sessions/list-items.hbs
  admin/app/controllers/authenticated/sessions/list.js
  admin/app/routes/authenticated/sessions/list.js
  admin/app/templates/authenticated/sessions/list.hbs
  admin/app/templates/components/pagination-control.hbs
  admin/mirage/factories/session.js
  admin/mirage/handlers/find-paginated-and-filtered-sessions.js
  admin/tests/acceptance/sessions-list-test.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  admin/tests/unit/controllers/authenticated/sessions/list-test.js
  admin/tests/unit/routes/authenticated/sessions/list-test.js
  api/lib/domain/usecases/find-paginated-filtered-sessions.js
  api/lib/domain/validators/session-validator.js
  api/lib/infrastructure/repositories/session-repository.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-sessions_test.js
  api/tests/unit/domain/validations/session-validator_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1332 [FEATURE] Permettre de signaler que les utilisateurs non SCO doivent valider les prochaines CGU (PF-1236).
  api/db/migrations/20200420120328_add_mustValidateTermsOfService_to_users.js
  api/db/seeds/data/users-builder.js
  api/lib/domain/models/User.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/scripts/mark-users-for-TermsOfService-revalidation.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/integration/scripts/mark-users-for-TermsOfService-revalidation_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/infrastructure/models/user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
Labels: Tech Review Needed, team-acces
