Repository 1024pix/pix, pull requests merged in 2020-05, with the labels that each got.

#1308 [CLEANUP] Appliquer la règle eslint no-get dans PixApp (PF-1247).
  mon-pix/.eslintrc.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/components/comparison-window.js
  mon-pix/app/components/learning-more-panel.js
  mon-pix/app/components/progress-bar.js
  mon-pix/app/components/qcm-solution-panel.js
  mon-pix/app/components/qcu-solution-panel.js
  mon-pix/app/components/qroc-solution-panel.js
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/app/components/qrocm-ind-solution-panel.js
  mon-pix/app/components/reset-password-form.js
  mon-pix/app/components/result-item.js
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/components/scorecard-details.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/components/user-certifications-detail-area.js
  mon-pix/app/components/user-certifications-detail-profile.js
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/controllers/assessments/checkpoint.js
  mon-pix/app/controllers/campaigns/fill-in-id-pix.js
  mon-pix/app/controllers/campaigns/send-profile.js
  mon-pix/app/controllers/campaigns/skill-review.js
  mon-pix/app/routes/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/get-certifications.js
  mon-pix/mirage/routes/get-competence-evaluations.js
  mon-pix/mirage/routes/get-progression.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/certification-course-test.js
  mon-pix/tests/integration/components/challenge-statement-test.js
  mon-pix/tests/integration/components/comparison-window-test.js
  mon-pix/tests/integration/components/qroc-solution-panel-test.js
  mon-pix/tests/integration/components/reset-password-form-test.js
  mon-pix/tests/unit/components/challenge-statement-test.js
  mon-pix/tests/unit/controllers/assessments/checkpoint-test.js
  mon-pix/tests/unit/controllers/campaigns/skill-review-test.js
Labels: Func Review Needed, Tech Review OK, team-evaluation

#1373 [FEATURE] Supprime le terme parcours des messages d'erreurs des pages de réconciliation (PIX-582).
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/controllers/campaigns/join-restricted-campaign.js
  mon-pix/tests/integration/components/routes/register-form-test.js
  mon-pix/tests/unit/controllers/campaigns/join-restricted-campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK

#1293 [FEATURE] Evaluer un tutoriel (PF-1095).
  api/db/migrations/20200414164040_create_tutorial-evaluations-table.js
  api/lib/application/tutorial-evaluations/index.js
  api/lib/application/tutorial-evaluations/tutorial-evaluations-controller.js
  api/lib/application/user-tutorials/index.js
  api/lib/domain/usecases/add-tutorial-evaluation.js
  api/lib/domain/usecases/find-user-tutorials.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/tutorial-evaluation.js
  api/lib/infrastructure/repositories/tutorial-evaluation-repository.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-attributes.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-evaluation-attributes.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-evaluation-serializer.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/tutorials/tutorial-evaluations-controller_test.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/integration/infrastructure/repositories/tutorial-evaluation-repository_test.js
  api/tests/tooling/database-builder/factory/build-tutorial-evaluation.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/unit/application/tutorial-evaluations/index_test.js
  api/tests/unit/application/tutorial-evaluations/tutorial-evaluations-controller_test.js
  api/tests/unit/application/user-tutorials/user-tutorials-controller_test.js
  api/tests/unit/domain/usecases/add-tutorial-evaluation_test.js
  api/tests/unit/domain/usecases/find-user-tutorials_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tutorial-evaluation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tutorial-serializer_test.js
  high-level-tests/e2e/cypress/integration/pix-app/user-tutorials.feature
  high-level-tests/e2e/cypress/support/step_definitions/user-tutorials.js
  mon-pix/app/adapters/tutorial-evaluation.js
  mon-pix/app/components/tutorial-item.js
  mon-pix/app/components/tutorial-panel.js
  mon-pix/app/models/tutorial-evaluation.js
  mon-pix/app/models/tutorial.js
  mon-pix/app/styles/components/_tutorial-item.scss
  mon-pix/app/templates/components/tutorial-item.hbs
  mon-pix/app/templates/components/tutorial-panel.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/put-tutorial-evaluation.js
  mon-pix/tests/acceptance/tutorial-actions-test.js
  mon-pix/tests/integration/components/tutorial-panel-test.js
  mon-pix/tests/unit/adapters/tutorial-evaluation-test.js
  mon-pix/tests/unit/components/tutorial-item-test.js
  mon-pix/tests/unit/components/tutorial-panel-test.js
  mon-pix/tests/unit/models/tutorial-evaluation-test.js
Labels: Func Review OK, Tech Review OK, team-evaluation

#1375 [CLEANUP] Suppression d'un appel inutile dans la page challenge (PIX-609).
  mon-pix/app/routes/assessments/challenge.js
Labels: team-captains, team-evaluation, team-prescription

#1369 [BUGFIX] Le changement rapide du contenu de plusieurs filtres dans les listes paginées n'est pas bien géré (PIX-598)
  admin/app/controllers/authenticated/certification-centers/list.js
  admin/app/controllers/authenticated/organizations/list.js
  admin/app/controllers/authenticated/sessions/list.js
  admin/app/controllers/authenticated/users/list.js
  orga/app/controllers/authenticated/campaigns/list.js
  orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Labels: Func Review OK, Tech Review OK, team-certif, team-prescription

#1247 [DOC] Ajouter des diagrammes de séquence sur la sécurité
  docs/security/authenticate.puml
  docs/security/reset_with_email.puml
Labels: team-acces

#1344 [BSR] Supprimer les actions dépréciées POST et PATCH sur la route user-orga-settings
  api/lib/application/user-orga-settings/index.js
  api/lib/application/user-orga-settings/user-orga-settings-controller.js
  api/lib/domain/usecases/create-user-orga-settings.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-user-orga-settings.js
  api/tests/acceptance/application/user-orga-settings-controller_test.js
  api/tests/unit/application/user-orga-settings/index_test.js
  api/tests/unit/application/user-orga-settings/user-orga-settings-controller_test.js
  api/tests/unit/domain/usecases/create-user-orga-settings_test.js
  api/tests/unit/domain/usecases/update-user-orga-settings_test.js
Labels: Tech Review Needed, team-acces

#1370 [CLEANUP] Suppression de la feature d'analyse de PV de session dans PixAdmin (PIX-600)
  admin/app/components/certification-session-report.js
  admin/app/controllers/authenticated/sessions/session/certifications.js
  admin/app/models/certification.js
  admin/app/styles/app.scss
  admin/app/styles/components/certification-session-report.scss
  admin/app/templates/authenticated/sessions/session/certifications.hbs
  admin/app/templates/components/certification-session-report.hbs
  admin/config/environment.js
  admin/mirage/config.js
  admin/tests/acceptance/certifications-parsing-uploaded-attendance-sheet-test.js
  admin/tests/integration/components/certification-session-report-test.js
  admin/tests/unit/components/certification-session-report-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/services/certifications-ods-service.js
  api/lib/domain/usecases/analyze-attendance-sheet.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-transformation-structures.js
  api/tests/acceptance/application/session/files/attendance-sheet-analysis-test-ok.ods
  api/tests/acceptance/application/session/session-controller-put-attendance-sheet-analysis_test.js
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-1_no_last_name_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-1_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-1_spaces_around_names_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-2_no_last_name_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-2_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-2_spaces_around_names_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-3_no_last_name_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-3_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-3_spaces_around_names_test.ods
  api/tests/integration/domain/services/certifications-ods-service/certifications-ods-service_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/analyze-attendance-sheet_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1297 [INFRA] Ajout d'en-têtes HTTP pour la sécurité
  admin/nginx.conf.erb
  certif/nginx.conf.erb
  mon-pix/nginx.conf.erb
  nginx.conf.erb
  orga/nginx.conf.erb
Labels: Tech Review Needed, team-captains

#1323 [CLEANUP] Refacto autour des sessions côté PixAdmin (PIX-589)
  admin/app/adapters/session.js
  admin/app/components/sessions/list-items.hbs
  admin/app/models/session.js
  admin/app/routes/authenticated/sessions/list.js
  admin/mirage/config.js
  admin/mirage/factories/session.js
  admin/mirage/handlers/find-paginated-and-filtered-sessions.js
  admin/mirage/serializers/session.js
  admin/tests/acceptance/sessions-list-test.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.js
  admin/tests/unit/adapters/session-test.js
  admin/tests/unit/routes/authenticated/sessions/list-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/CertificationOfficer.js
  api/lib/domain/models/JurySession.js
  api/lib/domain/usecases/find-paginated-filtered-sessions.js
  api/lib/domain/usecases/get-jury-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/jury-session-repository.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-session-serializer.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/acceptance/application/session/session-controller-get-certifications_test.js
  api/tests/acceptance/application/session/session-controller-get-jury-session_test.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/acceptance/application/session/session-controller-patch-update-publication-session_test.js
  api/tests/acceptance/application/session/session-controller-patch-user-assignment_test.js
  api/tests/acceptance/application/session/session-controller-put-results-sent-to-prescriber_test.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-sessions_test.js
  api/tests/unit/domain/usecases/get-jury-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-session-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Labels: Func Review Needed, Tech Review Needed, team-certif

#1381 [BUGFIX] Le résultat de certificat de l'utilisateur ne s'affiche plus (PIX-631)
  mon-pix/app/components/user-certifications-detail-profile.js
Labels: :steam_locomotive: EXPEDIT, Func Review OK, Tech Review OK, team-certif

#1383 [BUGFIX] Problème d'affichage des réponses des QROCM (PIX-636).
  mon-pix/app/components/learning-more-panel.js
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/app/components/qrocm-ind-solution-panel.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel-test.js
  mon-pix/tests/unit/components/qrocm-ind-solution-panel-test.js
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#1376 [FEATURE] Enregister l'acceptation des CGU par l'utilisateur (PF-1235)
  api/db/migrations/20200503193240_add_lastTermsOfServiceValidatedAt_to_user.js
  api/db/seeds/data/users-builder.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/accept-pix-last-terms-of-service.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/accept-pix-terms-of-service_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/accept-pix-terms-of-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/controllers/terms-of-service.js
  mon-pix/app/models/user.js
  mon-pix/app/routes/terms-of-service.js
  mon-pix/app/styles/pages/_terms-of-service.scss
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/mirage/config.js
  mon-pix/tests/acceptance/terms-of-service-test.js
  mon-pix/tests/unit/adapters/user-test.js
  mon-pix/tests/unit/controllers/terms-of-service-test.js
Labels: Func Review OK, Tech Review OK, team-acces

#1359 [INFRA] Corrige le status code HTTP "precondition failed" (421 -> 412)
  api/lib/application/http-errors.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/organization-invitation-controller_test.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/integration/application/pre-response-utils_test.js
  orga/app/components/routes/login-form.js
  orga/app/controllers/authenticated/team/new.js
  orga/app/routes/join.js
  orga/mirage/config.js
  orga/tests/acceptance/join-test.js
  orga/tests/acceptance/team-creation-test.js
Labels: Func Review Needed, Tech Review Needed

#1360 [INFRA] Possibilité d'ajouter des en-têtes HTTP grâce à des variables d'environnement.
  admin/nginx.conf.erb
  certif/nginx.conf.erb
  mon-pix/nginx.conf.erb
  nginx.conf.erb
  orga/nginx.conf.erb
Labels: Tech Review Needed, team-captains

#1367 [TECH] Regrouper les tests des cas d'erreurs des contrôleurs (PIX-599).
  api/tests/integration/application/error-manager_test.js
Labels: team-acces, team-certif, team-evaluation, team-prescription

#1368 [FEATURE] Permettre la modification d'une campagne de type collecte de profils (PIX-579).
  api/lib/domain/usecases/update-campaign.js
  api/lib/domain/validators/campaign-validator.js
  api/tests/unit/domain/usecases/update-campaign_test.js
  api/tests/unit/domain/validations/campaign-validator_test.js
  orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/update-item.hbs
  orga/tests/acceptance/campaign-update-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/parameters-tab-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/update-item-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1357 [FEATURE] Ajout de la page /cgu au workflow de connexion (PF-1249).
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/integration/pix-app/terms-of-service.feature
  mon-pix/app/mixins/secured-route-mixin.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/join-restricted-campaign.js
  mon-pix/app/routes/campaigns/skill-review.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/campaigns/tutorial.js
  mon-pix/app/routes/certifications/results.js
  mon-pix/app/routes/certifications/start.js
  mon-pix/app/routes/competences.js
  mon-pix/app/routes/competences/details.js
  mon-pix/app/routes/competences/results.js
  mon-pix/app/routes/competences/resume.js
  mon-pix/app/routes/index.js
  mon-pix/app/routes/profile.js
  mon-pix/app/routes/user-certifications/get.js
  mon-pix/app/routes/user-certifications/index.js
  mon-pix/app/styles/pages/_terms-of-service.scss
  mon-pix/tests/acceptance/terms-of-service-test.js
  mon-pix/tests/unit/mixins/secured-route-mixin-test.js
Labels: Tech Review Needed, team-acces

#1379 [FEATURE] Pouvoir trier la recommandation dans l'onglet analyse (PIX-585).
  orga/app/components/routes/authenticated/campaigns/details/analysis-tab.js
  orga/app/components/table/header-sort.hbs
  orga/app/components/table/header-sort.js
  orga/app/components/table/header.hbs
  orga/app/models/campaign-analysis.js
  orga/app/routes/authenticated/campaigns/details/analysis.js
  orga/app/routes/authenticated/campaigns/participant/analysis.js
  orga/app/styles/globals/tables.scss
  orga/app/templates/authenticated/campaigns/details/analysis.hbs
  orga/app/templates/authenticated/campaigns/participant/analysis.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/analysis-tab.hbs
  orga/tests/acceptance/campaign-analysis-test.js
  orga/tests/acceptance/campaign-collective-result-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/analysis-tab-test.js
  orga/tests/unit/models/campaign-analysis-test.js
Labels: Func Review Needed, team-prescription

#1385 [BUGFIX] Corriger les rem de la communication banner (PIX-646).
  mon-pix/app/styles/components/_communication-banner.scss
Labels: team-evaluation

#1388 [BUGFIX] Deux épreuves avec des fichiers à télécharger ont les mêmes fichiers (PIX-642).
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/mirage/factories/challenge.js
  mon-pix/tests/acceptance/challenge-qroc-test.js
Labels: Func Review OK, Tech Review Needed, team-evaluation

#1390 [BUGFIX] Rediriger vers la page de campagne après revalidation des CGU (PIX-644).
  mon-pix/app/controllers/terms-of-service.js
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
Labels: Func Review Needed, Tech Review Needed, team-acces

#1384 [CLEANUP] Retrait du code lié à la route GET /api/feedbacks, non utilisée (PIX-639)
  api/lib/application/feedbacks/feedback-controller.js
  api/lib/application/feedbacks/index.js
  api/lib/infrastructure/repositories/feedback-repository.js
  api/tests/acceptance/application/feedback-controller_test.js
  api/tests/acceptance/application/security-controller_test.js
  api/tests/acceptance/infrastructure/repositories/feedback-repository_test.js
  api/tests/unit/application/feedbacks/feedback-controller_test.js
  api/tests/unit/application/feedbacks/index_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif, team-evaluation

#1380 [FEATURE] Copier/Coller les informations contenues dans la pop-up Gestion du compte de l'élève de PixOrga (PIX-557).
  api/db/seeds/data/organizations-builder.js
  orga/app/components/password-reset-window.js
  orga/app/styles/globals/pix-modal.scss
  orga/app/templates/components/password-reset-window.hbs
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/password-reset-window-test.js
Labels: Design Review Needed, Func Review OK, Tech Review Needed, team-acces

#1386 [FEATURE] Modification du message concernant la réinitialisation d'un mot de passe, sur la double mire de connexion (PIX-556).
  mon-pix/app/styles/components/_login-form.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/templates/components/routes/login-form.hbs
Labels: Tech Review Needed, team-acces

#1378 [BUGFIX] Ne plus avoir les erreurs de transition dans la console (PIX-632).
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/join-restricted-campaign.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/tests/unit/routes/assessments/resume-test.js
Labels: Tech Review OK, team-captains, team-evaluation, team-prescription

#1374 [FEATURE] Supprimer le logo de la Marianne si l'on n'est pas sur ".fr" (PIX-603)
  mon-pix/app/components/inaccessible-campaign.js
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/components/navbar-header.js
  mon-pix/app/components/navbar-mobile-header.js
  mon-pix/app/services/url.js
  mon-pix/app/styles/components/_navbar-desktop-header.scss
  mon-pix/app/styles/components/_user-logged-menu.scss
  mon-pix/app/templates/components/inaccessible-campaign.hbs
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/components/navbar-header.hbs
  mon-pix/app/templates/components/navbar-mobile-header.hbs
  mon-pix/tests/integration/components/inaccessible-campaign-test.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
  mon-pix/tests/integration/components/navbar-header-test.js
  mon-pix/tests/integration/components/navbar-mobile-header-test.js
  mon-pix/tests/unit/components/navbar-desktop-header-test.js
  mon-pix/tests/unit/components/navbar-mobile-header-test.js
  mon-pix/tests/unit/services/url-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-evaluation

#1387 [BUGFIX] Suppression d'un warning ember-data sur les campaignParticipations.
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-participation-to-campaign_test.js
  api/tests/acceptance/application/users/users-get-campaign-participations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
Labels: Tech Review Needed, team-captains

#1392 [FEATURE] Mettre à jour le texte de la page de login de PixOrga et son design (PIX-530).
  orga/app/styles/components/login-form.scss
  orga/app/styles/pages/login.scss
  orga/app/templates/components/routes/login-form.hbs
  orga/app/templates/login.hbs
Labels: Design Review Needed, Tech Review Needed, team-acces

#1395 [FEATURE][FIX] Utiliser l'élément UL pour la liste à puces dans la double mire de connexion SCO (PIX-647).
  mon-pix/app/templates/components/routes/login-form.hbs
Labels: Tech Review Needed, team-acces

#1372 [FEATURE] Ajoute le système d'archivage sur les campagnes de type collecte de profils (PIX-584).
  api/lib/application/error-manager.js
  mon-pix/app/controllers/campaigns/send-profile.js
  mon-pix/app/templates/components/profile-sharing-form.hbs
  orga/app/models/campaign.js
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs
  orga/tests/integration/components/routes/authenticated/campaigns/details/parameters-tab-test.js
  orga/tests/unit/models/campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1389 [BUGFIX] Supprime le bouton "J'ai un code" pour les utilisateurs non connectés (PIX-601).
  mon-pix/app/styles/components/_navbar-desktop-header.scss
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1405 [BUGFIX] Utiliser le bon dégradé de couleur pour le fond de la bannière de la page évaluation.
  mon-pix/app/styles/components/_background-banner.scss
Labels: Design Review OK, Tech Review OK, team-evaluation

#1401 [BUGFIX] Ne pas permettre d'évaluer un tutoriel 2 fois (PIX-648).
  mon-pix/app/components/tutorial-item.js
  mon-pix/app/templates/components/tutorial-item.hbs
  mon-pix/tests/unit/components/tutorial-item-test.js
Labels: Func Review OK, Tech Review OK, team-evaluation

#1317 [FEATURE] Certif clea zone grise (PF-1147)
  api/db/seeds/data/certification/badge-acquisition-builder.js
  api/db/seeds/data/certification/user-badge-builder.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/db/seeds/seed.js
  api/lib/application/assessment-results/assessment-result-controller.js
  api/lib/domain/constants.js
  api/lib/domain/events/CertificationScoringCompleted.js
  api/lib/domain/events/handle-certification-partner.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CertificationContract.js
  api/lib/domain/models/CertificationPartnerAcquisition.js
  api/lib/domain/services/certification-result-service.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/tooling/database-builder/factory/build-badge-acquisition.js
  api/tests/tooling/domain-builder/factory/build-badge-acquisition.js
  api/tests/tooling/domain-builder/factory/build-skill-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/tooling/fixtures/infrastructure/skillAirtableDataObjectFixture.js
  api/tests/tooling/fixtures/infrastructure/skillRawAirTableFixture.js
  api/tests/unit/domain/events/handle-certification-partner_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CertificationPartnerAcquisition_test.js
  api/tests/unit/infrastructure/adapters/skill-adapter_test.js
  api/tests/unit/infrastructure/adapters/target-profile-adapter_test.js
  api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
  api/tests/unit/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/infrastructure/repositories/competence-repository_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/repositories/skill-repository_test.js
Labels: Tech Review Needed, team-certif

#1277 [TECH] Remplir la colonne associatedSkillId de la table certification-challenges avec l'id de l'acquis approprié (PF-1229)
  api/db/migrations/20200409104933_rename_associated-skill_into_associated-skill-name_table_certification-challenges.js
  api/db/migrations/20200509110115_update-associated-skill-id-column-certification-challenges-table.js
  api/db/seeds/data/certification/certification-data.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/services/user-service.js
  api/lib/infrastructure/repositories/certification-challenge-repository.js
  api/tests/tooling/database-builder/factory/build-certification-challenge.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1382 [INFRA] Amélioration des performances mémoire (et donc vitesse) lors de l'utilisation du knowledge-element-repository (PIX-635).
  api/lib/infrastructure/repositories/knowledge-element-repository.js
Labels: Func Review Needed, Tech Review OK, team-certif, team-evaluation, team-prescription

#1407 [BUGFIX] Correction des couleurs de la navigation.
  mon-pix/app/styles/components/_navbar-desktop-menu.scss
  mon-pix/app/styles/components/_navbar-header.scss
  mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs
  mon-pix/app/templates/certifications/start-loading.hbs
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/competences/details.hbs
  mon-pix/app/templates/competences/results.hbs
  mon-pix/app/templates/error.hbs
  mon-pix/app/templates/profile.hbs
  mon-pix/app/templates/user-certifications.hbs
  mon-pix/app/templates/user-tutorials.hbs
Labels: Design Review Needed, Tech Review OK, team-evaluation

#1406 [FEATURE] Centrer les messages d'erreur sur la page de connexion de Pix Orga (PIX-652).
  orga/app/styles/components/login-form.scss
Labels: Design Review Needed, Tech Review Needed, team-acces

#1404 [CLEANUP] Déplacement et renommage du module "security-controller"
  api/lib/application/assessment-results/index.js
  api/lib/application/cache/index.js
  api/lib/application/certification-center-memberships/index.js
  api/lib/application/certification-centers/index.js
  api/lib/application/certification-courses/index.js
  api/lib/application/memberships/index.js
  api/lib/application/organizations/index.js
  api/lib/application/schooling-registration-dependent-users/index.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/sessions/index.js
  api/lib/application/system/index.js
  api/lib/application/users/index.js
  api/lib/infrastructure/security.js
  api/tests/acceptance/application/security-pre-handlers_test.js
  api/tests/integration/application/certifications/index_test.js
  api/tests/integration/application/memberships/membership-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/application/schooling-registration-dependent-users/index_test.js
  api/tests/integration/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller_test.js
  api/tests/integration/application/student-dependent-users/index_test.js
  api/tests/integration/application/system/system-controller_test.js
  api/tests/integration/application/users/index_test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/assessments/index_test.js
  api/tests/unit/application/cache/index_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/application/courses/index_test.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/application/scorecards/index_test.js
  api/tests/unit/application/security-pre-handlers_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/tutorial-evaluations/index_test.js
  api/tests/unit/application/user-tutorials/index_test.js
  api/tests/unit/application/users/index_test.js
Labels: Tech Review Needed, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1398 [FEATURE] Améliorer le design de la page de login (PIX-511).
  certif/app/components/login-form.hbs
  certif/app/styles/components/login-form.scss
  certif/app/styles/pages/login.scss
Labels: Func Review OK, Tech Review OK, team-acces

#1400 [BUGFIX] Validation de la longueur d'un id de session.
  api/lib/application/sessions/index.js
  api/lib/config.js
  api/tests/unit/application/session/index_test.js
Labels: Tech Review Needed, team-captains

#1413 [CLEANUP] Retrait d'une clause SELECT inutile dans le KE repository
  api/lib/infrastructure/repositories/knowledge-element-repository.js
Labels: Tech Review OK, team-certif, team-evaluation, team-prescription

#1403 [FEATURE] Valider les QROCM seulement si l'utilisateur a rempli tous les champs réponse (PIX-375).
  mon-pix/app/components/challenge-item-qrocm.js
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/tests/acceptance/challenge-qrocm-test.js
Labels: Func Review Needed, Tech Review OK, team-evaluation

#1414 [BUGFIX] Suppression de warnings ember-data sur les memberships.
  api/lib/infrastructure/serializers/jsonapi/membership-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-memberships_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
Labels: Tech Review Needed, team-captains

#1415 [BUGFIX] Suppression d'un warning ember-data sur les user-orga-settings.
  api/lib/infrastructure/serializers/jsonapi/user-orga-settings-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-orga-settings-serializer_test.js
Labels: Tech Review Needed, team-captains

#1412 [BUGFIX] Empêcher le chevauchement des boutons sur la page CGU en version mobile (PIX-662)
  mon-pix/app/styles/components/_background-banner.scss
  mon-pix/app/styles/components/_certification-banner.scss
  mon-pix/app/styles/components/_congratulations-certification-banner.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/pages/_campaign-tutorial.scss
  mon-pix/app/styles/pages/_login-or-register-to-access-restricted-campaign.scss
  mon-pix/app/styles/pages/_not-connected.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/styles/pages/_terms-of-service.scss
  mon-pix/app/styles/pages/_update-expired-password-form.scss
Labels: Func Review OK, Tech Review OK, team-acces

#1416 [TECH] Ajout d'un helper de test contains pour vérifier qu'un texte est présent dans le rendu (PIX-675) .
  mon-pix/tests/helpers/contains.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
  mon-pix/tests/unit/helpers/contains-test.js
Labels: Tech Review Needed

#1399 [BUGFIX] Limiter les Pix et Levels max sur l'export de collecte de profils (PIX-615).
  api/lib/domain/models/CertificationProfile.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/get-user-current-certification-profile.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/tests/integration/domain/services/user-service_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/unit/domain/models/CertificationProfile_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/usecases/get-user-current-certification-profile_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Func Review OK, Tech Review OK, team-certif, team-evaluation, team-prescription

#1421 [BUGFIX] Corriger l'affichage de la progression sur le didacticiel (PIX-560).
  mon-pix/app/templates/campaigns/tutorial.hbs
Labels: Func Review OK, Tech Review Needed, team-evaluation

#1423 [BUGFIX] Remettre l'ancien gradient sur la page de connexion sur Pix Orga (PIX-655).
  orga/app/styles/pages/login.scss
Labels: Design Review Needed, team-acces

#1424 [BUGFIX] Changer la description de la page de connexion de Pix Certif (PIX-678)
  certif/app/components/login-form.hbs
  certif/app/styles/components/login-form.scss
Labels: Design Review OK, Func Review OK, team-acces

#1396 [FEATURE] Voir qui est assigné à une session sur Pix Admin (PIX-588)
  admin/app/adapters/user.js
  admin/app/components/sessions/list-items.hbs
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/models/user.js
  admin/app/routes/application.js
  admin/app/services/current-user.js
  admin/app/styles/authenticated/sessions/session/certifications.scss
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/styles/misc/button.scss
  admin/app/templates/authenticated/sessions/session/certifications.hbs
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/mirage/config.js
  admin/mirage/factories/user.js
  admin/tests/acceptance/authenticated/users/get-test.js
  admin/tests/acceptance/certification-centers-list-test.js
  admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js
  admin/tests/acceptance/organization-list-test.js
  admin/tests/acceptance/organization-memberships-management-test.js
  admin/tests/acceptance/organization-target-profiles-management-test.js
  admin/tests/acceptance/routes-protection-test.js
  admin/tests/acceptance/session-test.js
  admin/tests/acceptance/sessions-list-test.js
  admin/tests/acceptance/tools-page-test.js
  admin/tests/acceptance/user-list-test.js
  admin/tests/helpers/test-init.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.js
  admin/tests/unit/controllers/authenticated/sessions/session/informations-test.js
  admin/tests/unit/models/user-test.js
  admin/tests/unit/services/current-user-test.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/db/seeds/data/users-builder.js
  api/db/seeds/data/users_pix_roles-builder.js
  api/db/seeds/seed.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/assign-certification-officer-to-jury-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/jury-session-repository.js
  api/lib/infrastructure/repositories/session-repository.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/assign-certification-officer-to-session_test.js
Labels: Func Review Needed, Tech Review Needed, team-certif

#1410 [FEATURE] Modification du calcul des Pix Globaux (PIX-649)
  api/lib/domain/services/scoring/scoring-service.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
Labels: Func Review Needed, Tech Review OK, team-evaluation, team-prescription

#1408 [FEATURE] Clarifier la page de changement de mot de passe (PIX-554).
  mon-pix/app/styles/pages/_update-expired-password-form.scss
  mon-pix/app/templates/components/update-expired-password-form.hbs
Labels: :rocket: Ready to Merge, team-acces

#1393 [TECH] Glimmerize challenge-statement (PIX-676).
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/tests/integration/components/challenge-statement-test.js
  mon-pix/tests/unit/components/challenge-statement-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#1409 [TECH] Diviser le flux d'accès aux campagnes (PIX-651).
  mon-pix/app/controllers/assessment-campaigns/skill-review.js
  mon-pix/app/controllers/assessment-campaigns/tutorial.js
  mon-pix/app/controllers/campaigns/campaign-landing-page.js
  mon-pix/app/controllers/campaigns/fill-in-id-pix.js
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/controllers/profiles-collection-campaigns/send-profile.js
  mon-pix/app/controllers/restricted-campaigns/join-restricted-campaign.js
  mon-pix/app/router.js
  mon-pix/app/routes/assessment-campaigns/skill-review.js
  mon-pix/app/routes/assessment-campaigns/start-or-resume.js
  mon-pix/app/routes/assessment-campaigns/tutorial.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/routes/campaigns.js
  mon-pix/app/routes/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/fill-in-campaign-code.js
  mon-pix/app/routes/profiles-collection-campaigns/send-profile.js
  mon-pix/app/routes/profiles-collection-campaigns/start-or-resume.js
  mon-pix/app/routes/restricted-campaigns/join-restricted-campaign.js
  mon-pix/app/routes/restricted-campaigns/login-or-register-to-access-restricted-campaign.js
  mon-pix/app/templates/assessment-campaigns/skill-review.hbs
  mon-pix/app/templates/assessment-campaigns/tutorial.hbs
  mon-pix/app/templates/campaigns-error.hbs
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/app/templates/campaigns/start-or-resume.hbs
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/app/templates/profiles-collection-campaigns/send-profile.hbs
  mon-pix/app/templates/restricted-campaigns/join-restricted-campaign.hbs
  mon-pix/app/templates/restricted-campaigns/login-or-register-to-access-restricted-campaign.hbs
  mon-pix/tests/acceptance/login-or-register-to-access-restricted-campaign-test.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-collect-profiles-test.js
  mon-pix/tests/unit/controllers/assessment-campaigns/skill-review-test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-id-pix-test.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code-test.js
  mon-pix/tests/unit/controllers/profiles-collection-campaigns/send-profile-test.js
  mon-pix/tests/unit/controllers/restricted-campaigns/join-restricted-campaign-test.js
  mon-pix/tests/unit/routes/assessment-campaigns/tutorial-test.js
  mon-pix/tests/unit/routes/assessments/resume-test.js
  mon-pix/tests/unit/routes/campaigns/campaign-landing-page-test.js
  mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
  mon-pix/tests/unit/routes/profiles-collection-campaigns/send-profile-test.js
  mon-pix/tests/unit/routes/restricted-campaigns/join-restricted-campaign-test.js
  mon-pix/tests/unit/routes/restricted-campaigns/login-or-register-to-access-restricted-campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1377 [DOC] Ajouter un standard de test.
  docs/test.md
Labels: Tech Review Needed, team-acces, team-certif, team-evaluation, team-prescription

#1431 [TECH] Ajouter les sourcemaps en développement
  admin/ember-cli-build.js
  certif/ember-cli-build.js
  mon-pix/ember-cli-build.js
  orga/ember-cli-build.js
Labels: Tech Review Needed

#1420 [FEATURE] Changer la façon d'accéder à la page de détail d'un utilisateur dans Pix Admin (PIX-677).
  admin/app/components/users/list-items.hbs
  admin/app/controllers/authenticated/users/list.js
  admin/tests/acceptance/authenticated/users/get-test.js
Labels: Tech Review Needed, team-acces

#1429 [FEATURE] Traduire les titres des domaines (PIX-664)
  api/lib/infrastructure/datasources/airtable/area-datasource.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/tooling/airtable-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/build-area-airtable-data-object.js
  api/tests/tooling/fixtures/infrastructure/areaRawAirTableFixture.js
  api/tests/unit/infrastructure/repositories/area-repository_test.js
Labels: Func Review OK, Tech Review OK, team-evaluation

#1427 [BUGFIX] Nom du fichier avant jury sans underscore (PIX-661)
  admin/app/services/session-info-service.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1426 [FEATURE] Afficher la liste des participants à une collecte de profil dans pix orga (PIX-618)
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/models/CampaignProfilesCollectionParticipationSummary.js
  api/lib/domain/usecases/find-campaign-profiles-collection-participation-summaries.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-profiles-collection-participation-summary-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  api/tests/unit/domain/usecases/find-campaign-profiles-collection-participation-summaries_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-profiles-collection-participation-summary-serializer_test.js
  high-level-tests/e2e/cypress/fixtures/campaign-participations.json
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  orga/app/adapters/campaign-profiles-collection-participation-summary.js
  orga/app/models/campaign-profiles-collection-participation-summary.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/details/profiles.js
  orga/app/styles/app.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/campaigns/details/profiles.scss
  orga/app/templates/authenticated/campaigns/details/profiles.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/profiles-tab.hbs
  orga/tests/helpers/contains.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/profiles-tab-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1394 [BUGFIX] Stabilisation des perfs pour l'export CSV des campagnes de collecte de profils et d'évaluation (PIX-607).
  api/lib/config.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/lib/infrastructure/constants.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1411 [CLEANUP] Extraction d'un JuryCertificationSummary pour plus de clarté concernant le traitement des sessions (PIX-654)
  admin/app/controllers/authenticated/sessions/session/certifications.js
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/models/jury-certification-summary.js
  admin/app/models/session.js
  admin/app/routes/authenticated/sessions/session/informations.js
  admin/app/services/session-info-service.js
  admin/app/templates/authenticated/sessions/session/certifications.hbs
  admin/mirage/config.js
  admin/mirage/handlers/certifications-by-session-id.js
  admin/mirage/handlers/get-jury-certification-summaries-by-session-id.js
  admin/mirage/serializers/session.js
  admin/tests/acceptance/session-test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.js
  admin/tests/unit/controllers/authenticated/sessions/session/certifications-test.js
  admin/tests/unit/controllers/authenticated/sessions/session/informations-test.js
  admin/tests/unit/models/session-test.js
  admin/tests/unit/services/session-info-service-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/read-models/JuryCertificationSummary.js
  api/lib/domain/usecases/get-session-certifications.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-certification-summary-serializer.js
  api/lib/infrastructure/serializers/jsonapi/jury-session-serializer.js
  api/tests/acceptance/application/session/session-controller-get-certifications_test.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/get-session-certifications_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-certification-summary-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-session-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1436 [FEATURE] Rediriger sur le site vitrine après déconnexion (PF-682).
  mon-pix/app/components/password-reset-demand-form.js
  mon-pix/app/components/reset-password-form.js
  mon-pix/app/components/signin-form.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/controllers/terms-of-service.js
  mon-pix/app/routes/logout.js
  mon-pix/app/services/url.js
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/app/templates/components/reset-password-form.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/app/templates/components/update-expired-password-form.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/authentication-test.js
  mon-pix/tests/acceptance/certification-course-test.js
  mon-pix/tests/acceptance/challenge-commons-test.js
  mon-pix/tests/acceptance/challenge-page-banner-test.js
  mon-pix/tests/acceptance/competence-profile-test.js
  mon-pix/tests/acceptance/competences-details-test.js
  mon-pix/tests/acceptance/competences-results-test.js
  mon-pix/tests/acceptance/error-redirection-test.js
  mon-pix/tests/acceptance/navigation-test.js
  mon-pix/tests/acceptance/profile-test.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/resume-competence-evaluations-test.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-collect-profiles-test.js
  mon-pix/tests/acceptance/terms-of-service-test.js
  mon-pix/tests/acceptance/tutorial-actions-test.js
  mon-pix/tests/acceptance/update-expired-password-test.js
  mon-pix/tests/acceptance/user-certifications-test.js
  mon-pix/tests/helpers/authentication.js
  mon-pix/tests/integration/components/password-reset-demand-form-test.js
  mon-pix/tests/integration/components/reset-password-form-test.js
  mon-pix/tests/integration/components/signin-form-test.js
  mon-pix/tests/unit/components/password-reset-demand-form-test.js
  mon-pix/tests/unit/components/reset-password-form-test.js
  mon-pix/tests/unit/services/url-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-acces, team-evaluation

#1402 [FEATURE] Industrialiser les critères de badge (PIX-563).
  api/db/migrations/20200505174655_create_badge-criteria_table.js
  api/db/migrations/20200518173853_insert_badge_criteria.js
  api/db/seeds/data/badge-target-profile-builder.js
  api/db/seeds/data/campaigns-builder.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/db/seeds/seed.js
  api/lib/domain/events/handle-badge-acquisition.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/BadgeCriterion.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/infrastructure/data/badge-criterion.js
  api/lib/infrastructure/data/badge.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/tooling/database-builder/factory/build-badge-criterion.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-badge-criterion.js
  api/tests/tooling/domain-builder/factory/build-badge.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/events/handle-badge-acquisition_test.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
  mon-pix/app/models/badge.js
  mon-pix/app/templates/assessment-campaigns/skill-review.hbs
  mon-pix/tests/acceptance/skill-review-page-test.js
Labels: Func Review OK, Tech Review OK, team-evaluation

#1443 [FEATURE] Afficher le bon lien vers les CGU sur .org et .fr (PIX-683).
  mon-pix/app/components/signup-form.js
  mon-pix/app/services/url.js
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/tests/integration/components/signup-form-test.js
  mon-pix/tests/unit/services/url-test.js
  mon-pix/translations/en-us.json
  mon-pix/translations/fr-fr.json
Labels: Func Review OK, Tech Review OK, team-evaluation

#1440 [BUGFIX] L'ordre de tri sur la liste paginée des sessions sur PixAdmin n'est pas déterministe (PIX-728)
  api/lib/infrastructure/repositories/jury-session-repository.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1433 [TECH] Montée de version des dépendances de Pix API
  api/lib/application/sessions/index.js
  api/package-lock.json
  api/package.json
  api/tests/integration/application/authentication/index_test.js
  api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/unit/application/session/index_test.js
Labels: Func Review Needed, Tech Review Needed, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1441 [FEATURE] Résultats collectifs prenant en compte les nouvelles compétences de Pix + (PIX-673)
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository_test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1438 [BUGFIX] Affichage correct du label de l'identifiant externe dans Pix Orga (PIX-643).
  orga/app/components/routes/authenticated/campaigns/details/participants-tab.js
  orga/app/templates/components/routes/authenticated/campaigns/details/participants-tab.hbs
  orga/tests/helpers/contains.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/participants-tab-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1430 [FEATURE] Ajout du filtre sur la colonne "Qui ?" dans la liste des sessions dans Pix Admin (PA-211)
  admin/app/controllers/authenticated/sessions/list.js
  admin/app/routes/authenticated/sessions/list.js
  admin/app/styles/authenticated/sessions/list.scss
  admin/app/templates/authenticated/sessions/list.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/unit/routes/authenticated/sessions/list-test.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/validators/session-validator.js
  api/lib/infrastructure/repositories/jury-session-repository.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/validations/session-validator_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1451 [BUGFIX] Correction de la mise à jour de l'affichage de la liste des participants (PIX-747).
  orga/app/adapters/campaign-profiles-collection-participation-summary.js
  orga/app/routes/authenticated/campaigns/details/profiles.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1449 [FEATURE] Voir les campagnes archivées quand plus de campagnes actives (PIX-663)
  api/lib/application/organizations/organization-controller.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
  orga/mirage/config.js
  orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js
  orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1444 [FEATURE] Permettre la modification du rôle d'un membership dans Pix Admin (PIX-455).
  admin/app/components/organization-members-section.hbs
  admin/app/components/organization-members-section.js
  admin/app/components/role-edit.hbs
  admin/app/components/role-edit.js
  admin/mirage/config.js
  admin/tests/acceptance/organization-memberships-management-test.js
  admin/tests/helpers/contains.js
  admin/tests/helpers/test-init.js
  admin/tests/integration/components/routes/role-edit-test.js
  api/lib/application/memberships/index.js
  api/lib/application/security-pre-handlers.js
  api/tests/integration/application/memberships/membership-controller_test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1428 [BUGFIX] Empêcher l'utilisateur de demander plusieurs fois la réinitialisation de son mot de passe (PIX-489).
  mon-pix/app/components/password-reset-demand-form.js
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/tests/integration/components/password-reset-demand-form-test.js
  mon-pix/tests/unit/components/password-reset-demand-form-test.js
Labels: Tech Review Needed, team-acces

#1419 [CLEANUP] Extraction d'un modèle d'assessment dédié au scoring de certification (PIX-733)
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/events/index.js
  api/lib/domain/models/AssessmentScore.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/CertificationAssessmentScore.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/lib/infrastructure/repositories/certification-challenge-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/domain/services/scoring/scoring-certification_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-learning-content-for-certification.js
  api/tests/tooling/airtable-builder/factory/index.js
  api/tests/tooling/database-builder/factory/build-answered-not-completed-certification-assessment.js
  api/tests/tooling/database-builder/factory/build-certifiable-user.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-assessment-score.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/events/handle-certification-partner_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CertificationAssessmentScore_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1437 [FEATURE] Tracer les modifications des appartenances aux organisations (PF-494).
  api/db/migrations/20200515163806_add-column-createdat-updatedat-to-memberships.js
  api/lib/infrastructure/data/membership.js
Labels: Tech Review Needed, team-acces

#1447 [BUGFIX] Correction du calcul du score en pix (différence entre export du profil et affichage sur le profil) (PIX-739).
  api/lib/domain/services/scoring/scoring-service.js
  api/lib/domain/usecases/get-user-pix-score.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/unit/domain/usecases/get-user-pix-score_test.js
Labels: Tech Review OK, team-evaluation, team-prescription

#1446 [BUGFIX] Vérifier le seuil des 75% CléA sur le score certifié par compétence (et non positionné) (PIX-680)
  admin/app/controllers/authenticated/certifications/certification/details.js
  admin/app/controllers/authenticated/certifications/certification/informations.js
  api/db/migrations/20200522090553_add-competenceId-column-competence-marks-table.js
  api/db/seeds/data/certification/certification-data.js
  api/lib/application/assessment-results/assessment-result-controller.js
  api/lib/application/passwords/password-controller.js
  api/lib/config.js
  api/lib/domain/events/CertificationScoringCompleted.js
  api/lib/domain/events/handle-certification-partner.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CertificationPartnerAcquisition.js
  api/lib/domain/models/CompetenceMark.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/infrastructure/repositories/competence-mark-repository.js
  api/tests/integration/domain/services/scoring/scoring-certification_test.js
  api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js
  api/tests/tooling/database-builder/factory/build-competence-mark.js
  api/tests/tooling/domain-builder/factory/build-competence-mark.js
  api/tests/unit/application/passwords/password-controller_test.js
  api/tests/unit/domain/events/handle-certification-partner_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CertificationPartnerAcquisition_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/services/mail-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1453 [FEATURE] Ne pas montrer la page de présentation si l'utilisateur a déjà commencé sa participation (PIX-616).
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/profiles-collection-campaigns/start-or-resume.js
  mon-pix/tests/acceptance/navigation-test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/helpers/campaign.js
  mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1454 [FEATURE] Montrer de manière claire que l'utilisateur a déjà envoyé son profil Pix (PIX-610).
  mon-pix/app/controllers/profiles-collection-campaigns/profile-already-shared.js
  mon-pix/app/models/campaign-participation.js
  mon-pix/app/router.js
  mon-pix/app/routes/profiles-collection-campaigns/profile-already-shared.js
  mon-pix/app/routes/profiles-collection-campaigns/start-or-resume.js
  mon-pix/app/styles/pages/_send-profile.scss
  mon-pix/app/templates/components/profile-sharing-form.hbs
  mon-pix/app/templates/profiles-collection-campaigns/profile-already-shared.hbs
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1448 [CLEANUP] Utilisation d'un read-model dans le service Current-user de Pix Orga (PIX-553).
  api/lib/application/prescribers/index.js
  api/lib/application/prescribers/prescriber-controller.js
  api/lib/domain/read-models/Prescriber.js
  api/lib/domain/usecases/get-prescriber.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/prescriber-repository.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/prescriber-controller_test.js
  api/tests/integration/application/prescribers/index_test.js
  api/tests/integration/application/prescribers/prescriber-controller_test.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
  api/tests/tooling/domain-builder/factory/build-prescriber.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/prescribers/index_test.js
  api/tests/unit/application/prescribers/prescriber-controller_test.js
  api/tests/unit/domain/usecases/get-prescriber_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  orga/app/adapters/prescriber.js
  orga/app/components/user-logged-menu.js
  orga/app/controllers/terms-of-service.js
  orga/app/models/prescriber.js
  orga/app/routes/authenticated.js
  orga/app/routes/terms-of-service.js
  orga/app/services/current-user.js
  orga/app/templates/components/routes/authenticated/team/items.hbs
  orga/app/templates/components/user-logged-menu.hbs
  orga/mirage/config.js
  orga/mirage/serializers/prescriber.js
  orga/tests/acceptance/authentication-test.js
  orga/tests/acceptance/campaign-analysis-test.js
  orga/tests/acceptance/campaign-collective-result-test.js
  orga/tests/acceptance/campaign-creation-test.js
  orga/tests/acceptance/campaign-details-test.js
  orga/tests/acceptance/campaign-list-test.js
  orga/tests/acceptance/campaign-participants-individual-results-test.js
  orga/tests/acceptance/campaign-participants-indivual-analysis-test.js
  orga/tests/acceptance/campaign-participants-test.js
  orga/tests/acceptance/campaign-update-test.js
  orga/tests/acceptance/join-test.js
  orga/tests/acceptance/participant-results-test.js
  orga/tests/acceptance/student-list-test.js
  orga/tests/acceptance/switch-organization-test.js
  orga/tests/acceptance/team-creation-test.js
  orga/tests/acceptance/team-list-items-test.js
  orga/tests/acceptance/team-list-test.js
  orga/tests/acceptance/terms-of-service-test.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/user-logged-menu-test.js
  orga/tests/unit/adapters/prescriber-test.js
  orga/tests/unit/services/current-user-test.js
Labels: Tech Review Needed, team-acces

#1462 [FEATURE] Permettre à l'utilisateur d'obtenir un e-mail de réinitialisation de mot de passe en fonction de sa région (PIX-746).
  api/lib/application/passwords/password-controller.js
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/tests/unit/application/passwords/password-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
Labels: Tech Review OK, team-acces, team-evaluation

#1469 [BUGFIX] Récupérer les derniers knowledge-elements pour un skill avant la date de partage des résultats (PIX-767).
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1466 [FEATURE] Afficher uniquement la date sans la partie "temps" pour les valeurs de date de finalisation, publication et diffusion au prescripteur (PIX-765)
  admin/app/models/session.js
  admin/app/templates/authenticated/sessions/list.hbs
  admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js
  admin/tests/acceptance/session-test.js
  admin/tests/unit/models/session-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif
