Repository 1024pix/pix, pull requests merged in 2020-01, with the labels that each got.

#924 [TECH] Ajouter la preResponse dans HttpTestServer
  api/lib/infrastructure/utils/pre-response-utils.js
  api/server.js
  api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/integration/infrastructure/utils/pre-response-utils_test.js
  api/tests/test-helper.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/infrastructure/utils/pre-response-utils_test.js
  api/tests/unit/tooling/http-test-server_test.js
Labels: Tech Review Needed, team-accès

#947 [FEATURE] Forcer la mise en majuscule du code d'accès à la session (PF-885)
  mon-pix/app/styles/components/_certification-starter.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#945 [FEATURE] Ajouter la colonne "Statut" à la liste des sessions de Certif (PC-96).
  certif/app/controllers/authenticated/sessions/list.js
  certif/app/models/session.js
  certif/app/templates/authenticated/sessions/list.hbs
  certif/app/templates/components/routes/authenticated/sessions/list-items.hbs
  certif/tests/acceptance/session-list-test.js
  certif/tests/unit/models/session-test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#935 [BUGFIX] Gestion de deux mêmes types de challenge à la suite (PF-828)
  mon-pix/app/components/challenge-embed-simulator.js
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/styles/components/_challenge-embed-simulator.scss
  mon-pix/app/templates/components/challenge-embed-simulator.hbs
  mon-pix/tests/integration/components/challenge-embed-simulator-test.js
Labels: Func Review OK, Tech Review Needed, team-évaluation

#949 [BUGFIX] Rendre le champ e-mail obligatoire lors d'une invitation (PO-319).
  api/lib/application/organizations/index.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/unit/application/organizations/index_test.js
  orga/app/templates/components/routes/authenticated/team/new-item.hbs
  orga/tests/integration/components/routes/authenticated/team/new-item-test.js
Labels: Func Review OK, Tech Review OK, team-accès

#901 [FEATURE] Toujours poser la même épreuve au sein d'une évaluation (PF-959).
  api/lib/domain/services/smart-random/smart-random.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/lib/domain/usecases/share-campaign-result.js
  api/package-lock.json
  api/package.json
  api/tests/integration/domain/services/smart-random/smart-random_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-smart-placement_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#940 [TECH] Mise à jour d'Ember vers 3.14 sur PixCertif + dépendances (PC-100)
  certif/.eslintrc.js
  certif/app/adapters/application.js
  certif/app/app.js
  certif/app/components/app-modal.js
  certif/app/components/login-form.js
  certif/app/components/routes/authenticated/sessions/list-items.js
  certif/app/components/session-finalization-examiner-comment-step.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/models/certification-candidate.js
  certif/app/models/certification-center-membership.js
  certif/app/models/certification-center.js
  certif/app/models/session.js
  certif/app/models/user.js
  certif/app/routes/application.js
  certif/app/routes/authenticated/sessions/finalize.js
  certif/app/routes/logout.js
  certif/app/services/current-user.js
  certif/app/templates/authenticated.hbs
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/app/templates/authenticated/sessions/list.hbs
  certif/app/templates/authenticated/sessions/new.hbs
  certif/app/templates/authenticated/sessions/update.hbs
  certif/app/templates/authenticated/terms-of-service.hbs
  certif/app/templates/components/routes/authenticated/sessions/details-item.hbs
  certif/app/templates/components/routes/authenticated/sessions/details/certification-candidates-tab.hbs
  certif/app/templates/components/routes/authenticated/sessions/details/parameters-tab.hbs
  certif/app/templates/components/routes/authenticated/sessions/list-items.hbs
  certif/app/templates/components/routes/authenticated/sessions/new-item.hbs
  certif/app/templates/components/routes/authenticated/sessions/no-session-panel.hbs
  certif/app/templates/components/routes/authenticated/sessions/session-finalizer.hbs
  certif/app/templates/components/routes/authenticated/sessions/update-item.hbs
  certif/app/templates/login.hbs
  certif/app/transforms/date-only.js
  certif/config/optional-features.json
  certif/mirage/config.js
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/authentication-test.js
  certif/tests/integration/components/action-button-test.js
  certif/tests/integration/components/routes/authenticated/sessions/details/certification-candidates-tab-test.js
  certif/tests/integration/components/session-finalization-examiner-comment-step-test.js
  certif/tests/integration/helpers/format-percentage-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#950 [BUGFIX] Modifier l'affichage du bouton "Connectez-vous" afin qu'il n'apparaisse pas sur deux lignes (PF-1006)
  mon-pix/app/templates/components/reset-password-form.hbs
Labels: Func Review OK, Tech Review Needed, team-accès

#946 [TECH] Tentative d'amélioration du temps pris par les tests auto API
  api/db/knex-database-connection.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/security-controller_test.js
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/tooling/database-builder/database-buffer.js
  api/tests/tooling/database-builder/database-builder.js
Labels: Tech Review Needed, team-certif

#948 [FEATURE] Non validation des CGU lors de la création d'un utilisateur provenant du GAR (PF-820)
  api/lib/domain/usecases/get-or-create-saml-user.js
  api/tests/unit/domain/usecases/get-or-create-saml-user_test.js
Labels: :rocket: Ready to Merge, team-accès

#952 [FEATURE] Script de migration permettant d'invalider les CGU pour les utilisateurs provenant du GAR (PF-821)
  api/db/migrations/20200106155510_update_cgu_for_gar_users.js
Labels: :rocket: Ready to Merge, team-accès

#954 [FEATURE] Afficher une phrase de contexte (SCO) en haut de la double mire de connexion (PF-992 ).
  api/lib/domain/models/Campaign.js
  api/lib/domain/usecases/retrieve-campaign-information.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/unit/domain/usecases/retrieve-campaign-information_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  mon-pix/app/models/campaign.js
  mon-pix/app/routes/login-or-register-to-access-restricted-campaign.js
  mon-pix/app/styles/components/_login-or-register.scss
  mon-pix/app/templates/components/routes/login-or-register.hbs
  mon-pix/app/templates/login-or-register-to-access-restricted-campaign.hbs
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/acceptance/login-or-register-to-access-restricted-campaign-test.js
  mon-pix/tests/unit/components/routes/login-or-register-test.js
  mon-pix/tests/unit/routes/login-or-register-to-access-restricted-campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-accès

#917 [TECH] Modifier/simplifier l'usage de userRepository.get() (PF-1008)
  api/lib/application/usecases/checkUserHasRolePixMaster.js
  api/lib/domain/models/User.js
  api/lib/domain/services/session-authorization-service.js
  api/lib/domain/usecases/accept-pix-certif-terms-of-service.js
  api/lib/domain/usecases/accept-pix-orga-terms-of-service.js
  api/lib/domain/usecases/create-session.js
  api/lib/domain/usecases/remember-user-has-seen-assessment-instructions.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/unit/application/usecases/checkUserHasRolePixMaster_test.js
  api/tests/unit/domain/services/session-authorization-service_test.js
  api/tests/unit/domain/usecases/accept-pix-certif-terms-of-service_test.js
  api/tests/unit/domain/usecases/accept-pix-orga-terms-of-service_test.js
  api/tests/unit/domain/usecases/create-session_test.js
  api/tests/unit/domain/usecases/remember-user-has-seen-assessment-instructions_test.js
  api/tests/unit/infrastructure/repositories/user-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#932 [TECH] Retirer les colonnes users liés à la migration du profile (PF-1010).
  api/db/migrations/20191220174321_remove_user_migration_column.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/get-current-user.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/scripts/migrate-v1-to-v2.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/get-current-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
Labels: Func Review Needed, Tech Review OK, team-évaluation

#953 [A11Y] Ajouter des attributs ALT aux images (PF-669).
  mon-pix/app/templates/application.hbs
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/app/templates/campaigns/start-or-resume-error.hbs
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/components/navbar-mobile-header.hbs
  mon-pix/app/templates/components/tutorial-item-on-scorecard.hbs
Labels: Func Review Needed, Tech Review OK, team-évaluation

#964 [BUGFIX] Echec du déploiement des seeds en RA (PF-1028)
  api/db/knex-database-connection.js
Labels: Tech Review Needed, team-certif

#956 [TECH] Retrait du code lié à la création de session via POSTMAN (PF-1025)
  api/lib/domain/usecases/create-session.js
  api/tests/acceptance/application/session/session-controller-post_test.js
  api/tests/unit/domain/usecases/create-session_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#968 [BUGFIX] Le code d'accès à la session était forcé en majuscules seulement à l'affichage, mais pas lors de l'envoi du formulaire (PF-1032)
  mon-pix/app/components/certification-starter.js
  mon-pix/app/templates/components/certification-starter.hbs
Labels: Func Review OK, Tech Review Needed, team-certif

#955 [TECH] Mettre à jour node en v12.14.1 et npm en v6.13.4 (LTS) (PF-1009).
  .circleci/config.yml
  README.md
  admin/package-lock.json
  admin/package.json
  api/lib/domain/models/Certification.js
  api/lib/domain/models/Correction.js
  api/package.json
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package.json
Labels: Func Review OK, Tech Review Needed, team-accès, team-certif, team-prescription, team-évaluation

#933 [FEATURE] Indiquer à l'utilisateur qu'il a déjà répondu (PF-749).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge-item-qrocm.js
  mon-pix/app/components/qcm-proposals.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/styles/components/_challenge-embed-simulator.scss
  mon-pix/app/styles/components/_challenge-response.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/qcm-proposals.hbs
  mon-pix/app/templates/components/qcu-proposals.hbs
  mon-pix/app/templates/components/qroc-proposal.hbs
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/mirage/data/challenges/ref-qcm-challenge_not_yet_answered.js
  mon-pix/mirage/fixtures/assessments.js
  mon-pix/mirage/fixtures/challenges.js
  mon-pix/mirage/routes/get-answer-by-challenge-and-assessment.js
  mon-pix/mirage/routes/get-next-challenge.js
  mon-pix/mirage/routes/post-answers.js
  mon-pix/tests/acceptance/challenge-commons-test.js
  mon-pix/tests/acceptance/challenge-feedback-test.js
  mon-pix/tests/acceptance/challenge-qcm-test.js
  mon-pix/tests/acceptance/challenge-qcu-test.js
  mon-pix/tests/acceptance/challenge-qroc-test.js
  mon-pix/tests/acceptance/challenge-qrocm-test.js
  mon-pix/tests/acceptance/resume-campaigns-test.js
  mon-pix/tests/acceptance/starting-a-course-test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#963 [FEATURE] Amélioration du message de la page d'erreur (PF-1023)
  mon-pix/app/templates/error.hbs
Labels: :rocket: Ready to Merge, Func Review OK, team-accès

#936 [FEATURE] Ré-import du fichier SIECLE (PO-219)
  api/lib/domain/errors.js
  api/lib/domain/usecases/import-students-from-siecle.js
  api/lib/infrastructure/repositories/student-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/organizations/organization-controller-import-students_test.js
  api/tests/integration/infrastructure/repositories/student-repository_test.js
  api/tests/unit/domain/usecases/import-students-from-siecle_test.js
  orga/app/controllers/authenticated/students/list.js
  orga/mirage/config.js
  orga/tests/acceptance/student-list-test.js
Labels: Func Review OK, team-prescription

#967 [FEATURE] Modification du lien de la page de résultat d'une démo d'évaluation (PF-1031)
  mon-pix/app/controllers/assessments/results.js
  mon-pix/app/styles/pages/_assessment-results.scss
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/tests/acceptance/course-ending-screen-test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-accès

#961 [FEATURE] Afficher le nom d'utilisateur dans le menu utilisateur (PF-1022)
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/models/user.js
  mon-pix/app/styles/components/_user-logged-menu.scss
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/tests/integration/components/user-logged-menu-test.js
  mon-pix/tests/unit/components/user-logged-menu-test.js
Labels: Func Review OK, Tech Review Needed, team-accès

#962 [FEATURE] Changer le label "commentaire" en "signalement" (PC-102)
  admin/app/services/session-info-service.js
  admin/tests/unit/services/session-info-service-test.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-transformation-structures.js
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template.ods
  api/tests/acceptance/application/session/files/attendance-sheet-analysis-test-ok.ods
  api/tests/acceptance/application/session/files/import-certification-candidates-test-ko-invalid-data.ods
  api/tests/acceptance/application/session/files/import-certification-candidates-test-ko-invalid-file.ods
  api/tests/acceptance/application/session/files/import-certification-candidates-test-ok.ods
  api/tests/acceptance/application/session/files/import-certification-candidates-test-special-birthdate-ok.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-3_extract_mandatory_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-3_extract_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-3_extract_wrongvalue_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-3_no_last_name_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-3_ok_test.ods
  api/tests/integration/domain/services/certifications-ods-service/attendance_sheet_1-3_spaces_around_names_test.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/attendance_sheet_template_target.ods
  api/tests/unit/domain/models/CertificationCandidate_test.js
  certif/app/templates/components/session-finalization-candidates-informations-step.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#966 [FEATURE] Ajout d'une cellule "N° de session" au PV de session (PC-101)
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/attendance_sheet_template_target.ods
  api/tests/unit/domain/models/CertificationCandidate_test.js
Labels: :warning: Blocked, Func Review OK, Tech Review Needed, team-certif

#975 [BUGFIX] Design page finalisation session KO (pc-105)
  certif/app/styles/globals/tables.scss
  certif/app/styles/pages/authenticated/sessions.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates-tab.scss
  certif/app/templates/authenticated/sessions.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#910 [TECH] utiliser un Airtable minimal pour nos tests e2e (Cypress)
  api/lib/config.js
  high-level-tests/e2e/cypress/fixtures/target-profiles_skills.json
  high-level-tests/e2e/cypress/integration/demo.feature
  high-level-tests/e2e/cypress/integration/page-title.feature
  high-level-tests/e2e/cypress/integration/preview.feature
  high-level-tests/e2e/cypress/integration/profile.feature
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
Labels: Tech Review OK

#922 [PERF] Ajout d'un cache en mémoire et distribué (PF-969).
  api/lib/application/cache/cache-controller.js
  api/lib/application/cache/index.js
  api/lib/infrastructure/caches/Cache.js
  api/lib/infrastructure/caches/DistributedCache.js
  api/lib/infrastructure/caches/InMemoryCache.js
  api/lib/infrastructure/caches/LayeredCache.js
  api/lib/infrastructure/caches/RedisCache.js
  api/lib/infrastructure/caches/RedisClient.js
  api/lib/infrastructure/caches/cache.js
  api/lib/infrastructure/caches/learning-content-cache.js
  api/lib/infrastructure/datasources/airtable/course-datasource.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/repositories/course-repository.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-competence-evaluation_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-nonadaptive_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/challenge-controller_test.js
  api/tests/acceptance/application/competence-evaluation-controller_test.js
  api/tests/acceptance/application/course-controller_test.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-certification-profile_test.js
  api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository-test.js
  api/tests/unit/application/cache/cache-controller_test.js
  api/tests/unit/application/cache/index_test.js
  api/tests/unit/infrastructure/caches/Cache_test.js
  api/tests/unit/infrastructure/caches/DistributedCache_test.js
  api/tests/unit/infrastructure/caches/InMemoryCache_test.js
  api/tests/unit/infrastructure/caches/LayeredCache_test.js
  api/tests/unit/infrastructure/caches/RedisCache_test.js
  api/tests/unit/infrastructure/caches/cache_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/tube-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/tutorial-datasource_test.js
  api/tests/unit/infrastructure/repositories/course-repository_test.js
  docs/adr/0005-ajout-d-un-cache-memoire-distribute-pour-le-contenu-pedagogique.md
  docs/assets/learning-content-cache-architecture-after.png
  docs/assets/learning-content-cache-architecture-before.png
  docs/assets/learning-content-cache-design-after.png
  docs/assets/learning-content-cache-design-before.png
Labels: Func Review Needed, Tech Review Needed, team-accès, team-certif, team-prescription, team-évaluation

#986 [FEATURE] Placer le focus sur l'input suivante sur la page de démarrage d'une session de certification.
  mon-pix/app/components/certification-joiner.js
  mon-pix/app/templates/components/certification-joiner.hbs
Labels: Func Review OK, Tech Review Needed, team-certif

#982 [BUGFIX] Corriger l'affichage d'un bouton de mon-pix sous Safari. (PF-1042)
  mon-pix/app/styles/components/_certification-result.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#970 [FEATURE] Homogénéiser le comportement de cloture des notifications de succès mobile et desktop (PF-899).
  mon-pix/app/components/levelup-notif.js
  mon-pix/app/styles/components/_levelup-notif.scss
  mon-pix/app/templates/components/levelup-notif.hbs
Labels: Design Review OK, Func Review OK, Tech Review OK, team-évaluation

#974 [FEATURE] Actualiser le design des embed (1/2) (PF-563).
  mon-pix/app/components/challenge-embed-simulator.js
  mon-pix/app/styles/components/_challenge-embed-simulator.scss
  mon-pix/app/templates/components/challenge-embed-simulator.hbs
  mon-pix/tests/integration/components/challenge-embed-simulator-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-évaluation

#980 [TECH] Prise en compte des derniers retours de la PR #913 (prereconciliation) (PF-1038).
  api/lib/application/student-user-associations/student-user-association-controller.js
  api/lib/domain/services/user-reconciliation-service.js
  api/lib/domain/usecases/create-and-associate-user-to-student.js
  api/lib/domain/usecases/generate-username.js
  api/lib/domain/usecases/link-user-to-organization-student-data.js
  api/tests/acceptance/application/student-user-association-controller_test.js
  api/tests/integration/application/student-dependent-users/index_test.js
  api/tests/integration/application/student-user-associations/index_test.js
  api/tests/integration/domain/usecases/create-and-associate-user-to-student_test.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
  api/tests/unit/domain/usecases/create-and-associate-user-to-student_test.js
  api/tests/unit/domain/usecases/generate-username-test.js
  api/tests/unit/domain/usecases/link-user-to-organization-student-data_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-accès

#993 [TECH] Supprimer les logs non utiles
  api/lib/infrastructure/utils/error-manager.js
  api/lib/interfaces/controllers/security-controller.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
Labels: Tech Review Needed

#960 [FEATURE] Ajouter un candidat à la liste des candidats d'une session (PC-71)
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/link-user-to-session-certification-candidate.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js
  certif/app/adapters/certification-candidate.js
  certif/app/components/certification-candidate-in-staging-item.js
  certif/app/components/routes/authenticated/sessions/details/certification-candidates-tab.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/certification-candidate.js
  certif/app/serializers/application.js
  certif/app/styles/components/session-finalization-candidates-informations-step.scss
  certif/app/styles/globals/colors.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/globals/tables.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates-tab.scss
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/app/templates/components/certification-candidate-in-staging-item.hbs
  certif/app/templates/components/routes/authenticated/sessions/details/certification-candidates-tab.hbs
  certif/app/templates/components/routes/authenticated/sessions/list-items.hbs
  certif/mirage/config.js
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/integration/components/certification-candidate-in-staging-item-test.js
  certif/tests/integration/components/routes/authenticated/sessions/details/certification-candidates-tab-test.js
  certif/tests/unit/adapters/certification-candidate-test.js
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates-test.js
Labels: Design Review Needed, Func Review OK, Tech Review OK, team-certif

#997 Ajout de Sendinblue en tant que fournisseur d'emailing (PF-972).
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/lib/infrastructure/mailers/MailingProvider.js
  api/lib/infrastructure/mailers/MailjetProvider.js
  api/lib/infrastructure/mailers/SendinblueProvider.js
  api/lib/infrastructure/mailers/mailer.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/infrastructure/mailers/MailingProvider_test.js
  api/tests/unit/infrastructure/mailers/MailjetProvider_test.js
  api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
  api/tests/unit/infrastructure/mailjet_test.js
  docs/API.md
  docs/adr/0006-ajout-du-support-de-sendinblue-pour-le-mailing.md
  docs/assets/mailing-system-design.png
  package-lock.json
  package.json
Labels: Func Review OK, Tech Review Needed, team-accès, 🌟 Etoile

#979 [FEATURE] Renommer examinerComment en examinerGlobalComment (pa-102)
  admin/app/models/session.js
  admin/app/templates/authenticated/certifications/sessions/info/index.hbs
  admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js
  api/db/migrations/20200117170614_rename_session_examiner_comment_to_examiner_global_comment.js
  api/db/seeds/data/sessions-builder.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/tooling/database-builder/factory/build-session.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  certif/app/adapters/session.js
  certif/app/components/session-finalization-examiner-comment-step.hbs
  certif/app/components/session-finalization-examiner-comment-step.js
  certif/app/components/session-finalization-examiner-global-comment-step.hbs
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/models/session.js
  certif/app/styles/app.scss
  certif/app/styles/components/session-finalization-examiner-global-comment-step.scss
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/mirage/factories/session.js
  certif/tests/acceptance/session-finalization-test.js
  certif/tests/integration/components/session-finalization-examiner-comment-step-test.js
  certif/tests/integration/components/session-finalization-examiner-global-comment-step-test.js
Labels: Func Review OK, Tech Review OK, team-certif

#983 [BUGFIX] Ne pas permettre le click multiple sur les boutons de soumission de formulaire (PF-1043).
  mon-pix/app/templates/campaigns/join-restricted-campaign.hbs
  mon-pix/app/templates/components/routes/login-form.hbs
  mon-pix/app/templates/components/routes/register-form.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-accès, team-prescription

#1002 [FEATURE] Afficher un message d'information dans Pix Orga lorsqu'un utilisateur clique sur une invitation déjà acceptée (PO-276)
  orga/app/controllers/login.js
  orga/app/routes/join.js
  orga/app/styles/components/login-form.scss
  orga/app/styles/globals/colors.scss
  orga/app/templates/components/routes/login-form.hbs
  orga/app/templates/login.hbs
  orga/mirage/config.js
  orga/tests/acceptance/join-test.js
Labels: Func Review OK, Tech Review Needed, team-accès

#1003 [TECH] Amélioration de la gestion des types BIG_INTEGER dans PostgreSQL.
  api/db/knex-database-connection.js
  api/lib/infrastructure/bookshelf.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/saml-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  orga/app/models/campaign-report.js
Labels: Func Review Needed, Tech Review Needed

#984 [FEATURE] Déplacer les couleurs de domaines dans le référentiel (PF-1046).
  api/lib/domain/models/Area.js
  api/lib/domain/models/CampaignCompetenceCollectiveResult.js
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/models/CompetenceResult.js
  api/lib/domain/usecases/compute-campaign-collective-result.js
  api/lib/infrastructure/datasources/airtable/area-datasource.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-collective-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/lib/infrastructure/serializers/jsonapi/scorecard-serializer.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository-test.js
  api/tests/tooling/airtable-builder/factory/build-area.js
  api/tests/tooling/airtable-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/build-area-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/build-campaign-competence-collective-result.js
  api/tests/tooling/domain-builder/factory/build-competence-tree.js
  api/tests/tooling/fixtures/infrastructure/areaRawAirTableFixture.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/models/ResultCompetenceTree_test.js
  api/tests/unit/domain/usecases/compute-campaign-collective-result_test.js
  api/tests/unit/infrastructure/repositories/area-repository_test.js
  api/tests/unit/infrastructure/repositories/competence-repository_test.js
  api/tests/unit/infrastructure/repositories/competence-tree-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-collective-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/scorecard-serializer_test.js
  mon-pix/app/models/area.js
  mon-pix/app/models/competence-result.js
  mon-pix/app/models/scorecard.js
  mon-pix/app/static-data/area-colors.js
  mon-pix/app/templates/components/competence-card-desktop.hbs
  mon-pix/app/templates/components/competence-card.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/mirage/fixtures/areas.js
  mon-pix/tests/integration/components/competence-card-desktop-test.js
  mon-pix/tests/integration/components/competence-card-test.js
  mon-pix/tests/integration/components/scorecard-details-test.js
  mon-pix/tests/unit/models/competence-result-test.js
  mon-pix/tests/unit/models/scorecard-test.js
  orga/app/models/campaign-competence-collective-result.js
  orga/app/models/competence-result.js
  orga/app/static-data/domain-colors.js
  orga/app/styles/globals/colors.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant-results.scss
  orga/app/templates/components/routes/authenticated/campaigns/details/collective-results-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs
  orga/mirage/factories/campaign-collective-result.js
  orga/tests/acceptance/campaign-collective-result-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/collective-results-tab-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/participants/results-item-test.js
  orga/tests/unit/models/competence-result-test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#988 [FEATURE] Pix+ - Ajout et prise en compte de l'origine (Pix ou hors Pix) des compétences (PF-1047)
  api/lib/domain/models/Competence.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/get-user-scorecards.js
  api/lib/infrastructure/datasources/airtable/competence-datasource.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/tests/integration/domain/services/user-service_test.js
  api/tests/tooling/airtable-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/build-competence-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-competence.js
  api/tests/tooling/fixtures/infrastructure/competenceRawAirTableFixture.js
  api/tests/unit/domain/usecases/get-user-scorecards_test.js
  api/tests/unit/infrastructure/repositories/competence-repository_test.js
  docs/Calcul-Airtable.md
  docs/adr/0006-ajout-du-support-de-sendinblue-pour-le-mailing.md
  docs/adr/0007-calcul-des-pix.md
Labels: Func Review OK, Tech Review OK, team-évaluation

#1005 [TECH] Les tests de MonPix sur CircleCI se déclenchaient 3 fois complètement en parallèle
  mon-pix/tests/test-helper.js
Labels: Tech Review Needed

#1004 [BUGFIX] Probleme de validation des QROCM sous IE (PF-1055).
  mon-pix/app/components/challenge-item-qrocm.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#1007 [BUGFIX] Correction d'une erreur Redis au démarrage de l'API.
  api/lib/infrastructure/caches/RedisClient.js
Labels: Tech Review Needed

#985 [FEATURE] Afficher une bulle d'information sur les Pix (PF-803).
  mon-pix/app/components/hexagon-score.js
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/app/templates/components/hexagon-score.hbs
Labels: Func Review Needed, Tech Review OK, team-évaluation

#977 [FEATURE] Supprimer un candidat de la liste des candidats d'une session. (PC-73)
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/delete-unlinked-certification-candidate.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/server.js
  api/tests/acceptance/application/session/session-controller-delete-certification-candidate_test.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  api/tests/unit/domain/usecases/delete-unlinked-certification-candidate_test.js
  certif/app/adapters/certification-candidate.js
  certif/app/components/login-form.hbs
  certif/app/components/routes/authenticated/sessions/details/certification-candidates-tab.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/styles/app.scss
  certif/app/styles/globals/colors.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/globals/tables.scss
  certif/app/styles/globals/texts.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/app/templates/authenticated.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/app/templates/authenticated/terms-of-service.hbs
  certif/mirage/config.js
  certif/public/pix-certif-logo.svg
  certif/public/pix-logo-certif.svg
  certif/public/pix-logo.svg
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/unit/adapters/certification-candidate-test.js
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates-test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1008 [BUGFIX] Deux QROCs qui se suivent avec un même input conservent la réponse précédente
  mon-pix/app/components/qroc-proposal.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#1010 [BUGFIX] Requêter le détail d'une compétence avec un mauvais identifiant provoque désormais une erreur 404 plutôt que 500.
  api/lib/domain/models/Scorecard.js
  api/lib/domain/usecases/start-or-resume-competence-evaluation.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/tests/acceptance/application/competence-evaluation-controller_test.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/usecases/start-or-resume-competence-evaluation_test.js
  api/tests/unit/infrastructure/repositories/competence-repository_test.js
Labels: Tech Review Needed

#1014 [BUGFIX] L'initialisation du statut de la session à leur création ne fonctionnait pas (PC-112)
  api/lib/domain/usecases/create-session.js
  api/tests/unit/domain/usecases/create-session_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1015 [BUGFIX] Changement de texte pour l'info-bulle des 1024 pix.
  mon-pix/app/templates/components/hexagon-score.hbs
Labels: Func Review Needed, Tech Review Needed, team-évaluation

#1016 [BUGFIX] Corrige le sous-titre de la page de finalization (PC-113)
  certif/app/templates/authenticated/sessions/finalize.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#987 [FEATURE] Changer le mot de passe d'un étudiant connecté via un nom d'utilisateur (PO-322)
  api/db/seeds/data/organizations-builder.js
  api/lib/application/preHandlers/user-existence-verification.js
  api/lib/application/student-dependent-users/index.js
  api/lib/application/student-dependent-users/student-dependent-user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/find-organization-students.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-student-dependent-user-password.js
  api/lib/infrastructure/repositories/student-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/student-serializer.js
  api/lib/infrastructure/utils/error-manager.js
  api/lib/interfaces/controllers/security-controller.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/student-dependent-user-controller_test.js
  api/tests/integration/application/student-dependent-users/index_test.js
  api/tests/integration/application/student-dependent-users/student-dependent-user-controller_test.js
  api/tests/integration/infrastructure/repositories/student-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/integration/infrastructure/utils/error-manager_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/preHandlers/user-existence-verification_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/find-organization-students_test.js
  api/tests/unit/domain/usecases/update-student-dependent-user-password_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-serializer_test.js
  api/tests/unit/interfaces/controllers/security-controller_test.js
  orga/app/adapters/student-dependent-user.js
  orga/app/components/password-reset-window.js
  orga/app/components/pix-modal.js
  orga/app/components/routes/authenticated/students/list-items.js
  orga/app/models/student-dependent-user.js
  orga/app/models/student.js
  orga/app/styles/app.scss
  orga/app/styles/components/password-reset-modal.scss
  orga/app/templates/authenticated/students/list.hbs
  orga/app/templates/components/password-reset-window.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/mirage/config.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/password-reset-window-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-accès

#959 [TECH] Supprimer Bootstrap de mon-pix.
  mon-pix/app/components/result-item.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_challenge-response.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/components/_result-item.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/components/_tutorial-item-on-scorecard.scss
  mon-pix/app/styles/components/_user-certifications-detail-header.scss
  mon-pix/app/styles/components/_user-logged-menu.scss
  mon-pix/app/styles/components/_warning-timing-page.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/globals/_pix-modal.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
  mon-pix/app/styles/globals/_tables.scss
  mon-pix/app/styles/pages/_assessment-results.scss
  mon-pix/app/styles/pages/_fill-in-id-pix.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/result-item.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/ember-cli-build.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/public/images/icon-close-modal.svg
  mon-pix/tests/acceptance/compare-answer-solution-qroc-test.js
  mon-pix/tests/acceptance/course-ending-screen-test.js
  mon-pix/tests/integration/components/result-item-campaign-test.js
  mon-pix/tests/unit/components/result-item-test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#1020 [TECH] Générer des liens de reset de mot de passe en https (PF-1065).
  api/lib/application/passwords/password-controller.js
  api/tests/unit/application/passwords/password-controller_test.js
Labels: :rocket: Ready to Merge, team-accès

#1018 [FEATURE] Ajout d'un bouton pour rafraîchir le cache de données pédagogiques dans Pix Admin (PA-139).
  admin/app/adapters/learning-content-cache.js
  admin/app/controllers/authenticated/certifications/sessions/info/list.js
  admin/app/controllers/authenticated/tools.js
  admin/app/router.js
  admin/app/routes/authenticated/certifications/single/info.js
  admin/app/routes/authenticated/tools.js
  admin/app/styles/app.scss
  admin/app/styles/authenticated.scss
  admin/app/styles/authenticated/tools.scss
  admin/app/styles/misc/button.scss
  admin/app/styles/misc/callout.scss
  admin/app/styles/misc/palette.scss
  admin/app/templates/authenticated/organizations/list.hbs
  admin/app/templates/authenticated/tools.hbs
  admin/app/templates/components/menu-bar.hbs
  admin/public/images/loader-white.svg
  admin/tests/acceptance/tools-page-test.js
  admin/tests/integration/components/menu-bar-test.js
  admin/tests/unit/adapters/learning-content-cache-test.js
  admin/tests/unit/controllers/authenticated/tools-test.js
  admin/tests/unit/routes/authenticated/tools-test.js
Labels: Func Review OK

#1017 [BSR] Ajuster le style du bouton réinitialiser des embed (PF-1061).
  mon-pix/app/templates/components/challenge-embed-simulator.hbs
Labels: Func Review OK, Tech Review OK, team-évaluation

#1011 Rendre les validateurs synchrones et s'assurer qu'ils jettent correctement leurs erreurs converties 4xx (PC-110)
  api/lib/domain/usecases/create-and-associate-user-to-student.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/usecases/create-organization.js
  api/lib/domain/usecases/create-user.js
  api/lib/domain/validators/campaign-validator.js
  api/lib/domain/validators/organization-creation-validator.js
  api/lib/domain/validators/session-validator.js
  api/lib/domain/validators/user-validator.js
  api/tests/unit/domain/usecases/create-and-associate-user-to-student_test.js
  api/tests/unit/domain/usecases/create-campaign_test.js
  api/tests/unit/domain/usecases/create-organization_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/domain/validations/campaign-validator_test.js
  api/tests/unit/domain/validations/organization-creation-validator_test.js
  api/tests/unit/domain/validations/session-validator_test.js
  api/tests/unit/domain/validations/user-validator_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1024 [BUGFIX] Mise à jour de la commande de création de release sentry-cli.
  scripts/release/publish.sh
Labels: Tech Review Needed
