Repository 1024pix/pix, pull requests merged in 2020-06, with the labels that each got.

#1417 [INFRA] Désactivation de la compression des réponses HTTP
  admin/nginx.conf.erb
  api/server.js
  certif/nginx.conf.erb
  mon-pix/nginx.conf.erb
  nginx.conf.erb
  orga/nginx.conf.erb
Labels: :rocket: Ready to Merge

#1452 [CLEANUP] Ajout de tests sur les challenges (PIX-638).
  mon-pix/app/components/qroc-proposal.js
  mon-pix/app/templates/components/qroc-proposal.hbs
  mon-pix/mirage/factories/challenge.js
  mon-pix/mirage/factories/tutorial.js
  mon-pix/mirage/serializers/correction.js
  mon-pix/tests/acceptance/challenge-qcm-test.js
  mon-pix/tests/acceptance/challenge-qcu-test.js
  mon-pix/tests/acceptance/challenge-qroc-test.js
  mon-pix/tests/acceptance/challenge-qrocm-test.js
  mon-pix/tests/acceptance/challenge-timed-test.js
Labels: Tech Review OK, team-evaluation

#1457 [CLEANUP] Change la manière de récupérer les réponses d'un QCM (PIX-768).
  mon-pix/app/components/challenge-item-qcm.js
  mon-pix/app/components/qcm-proposals.js
  mon-pix/app/templates/components/qcm-proposals.hbs
Labels: Func Review OK, Tech Review OK, team-evaluation

#1472 [FEATURE] Empêcher le candidat de faire un signalement pendant le test de certification (PIX-578)
  mon-pix/app/templates/components/feedback-certification-section.hbs
  mon-pix/app/templates/components/feedback-panel.hbs
  mon-pix/tests/integration/components/feedback-certification-section-test.js
  mon-pix/tests/integration/components/feedback-panel-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1467 [BUGFIX] Ne prendre en compte que les compétences évaluées en certification lors du scoring de certification CléA (PIX-679)
  api/lib/domain/models/CertificationPartnerAcquisition.js
  api/tests/unit/domain/models/CertificationPartnerAcquisition_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1471 [FEATURE] Permettre à l'utilisateur d'obtenir un e-mail de création de compte en fonction de sa région (PIX-745).
  api/lib/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller.js
  api/lib/application/users/user-controller.js
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/create-and-associate-user-to-schooling-registration.js
  api/lib/domain/usecases/create-user.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/create-user_test.js
Labels: Tech Review Needed, team-acces

#1478 [BUGFIX] Corrections relatives au changement d'organisation dans Pix Orga (PIX-538).
  orga/app/components/user-logged-menu.js
  orga/tests/acceptance/switch-organization-test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1465 [FEATURE] Afficher la dernière date d'envoi d'une invitation dans Pix Orga (PIX-730).
  api/lib/domain/services/organization-invitation-service.js
  api/lib/infrastructure/repositories/organization-invitation-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-invitation-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-invitation-serializer_test.js
  orga/app/models/organization-invitation.js
  orga/app/templates/components/routes/authenticated/team/list-items.hbs
  orga/tests/integration/components/routes/authenticated/team/list-items-test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1480 [BUGFIX] Problème d'affichage de la bannière de reprise de parcours (PIX-770)
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/users/users-get-campaign-participations_test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1482 [CLEANUP] Correction du changelog après une mauvaise manip qui a provoqué la duplication d'une entrée (PIX-774)
  CHANGELOG.md
Labels: :rocket: Ready to Merge, team-certif

#1479 [INFRA] Ajouter les dernières variables d'environnement dans le fichier sample.env
  api/sample.env
Labels: Tech Review Needed, team-acces

#1442 [TECH] Ecriture d'un script pour élaborer des statistiques sur la qualité des tests de certification (PIX-738)
  api/scripts/generate-certification-test-statistics.js
Labels: POC, team-certif

#1474 [FEATURE] Ajout d'un composant dropdown dans Pix Orga (PIX-716).
  high-level-tests/e2e/cypress/integration/pix-orga/student-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/student.js
  orga/app/components/dropdown/content.hbs
  orga/app/components/dropdown/icon-trigger.hbs
  orga/app/components/dropdown/icon-trigger.js
  orga/app/components/dropdown/item-link.hbs
  orga/app/components/dropdown/item.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/dropdown.scss
  orga/app/styles/components/user-logged-menu.scss
  orga/app/styles/pages/authenticated/students/list.scss
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/app/templates/components/user-logged-menu.hbs
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/dropdown/icon-trigger-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
  orga/tests/integration/components/user-logged-menu-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-acces, team-prescription

#1470 [BUGFIX] Réduction de la largeur de certaines colonnes dans le tableau des membres (PIX-459).
  admin/app/components/organization-members-section.js
  admin/app/styles/misc/tables.scss
  admin/tests/acceptance/organization-memberships-management-test.js
Labels: Tech Review Needed, team-acces

#1477 [BUGFIX] Amélioration de la validation du formulaire d'inscription dans Pix Orga (PIX-468).
  orga/app/components/routes/register-form.js
  orga/app/styles/globals/errors.scss
  orga/app/templates/components/routes/register-form.hbs
  orga/app/utils/input-validator.js
  orga/tests/unit/utils/input-validator-test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1490 [BUGFIX] Correction d'un test knex-utils aléatoire
  api/tests/integration/infrastructure/utils/knex_utils_test.js
Labels: Tech Review Needed, team-prescription

#1493 [BUGFIX] La flèche de checkpoint doit s'afficher en plus grand (PIX-811).
  mon-pix/app/styles/components/_checkpoint.scss
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#1491 [FEATURE] Mettre à jour le nom, identifiant externe et département d'une organisation dans Pix Admin (PIX-456).
  admin/app/components/organization-information-section.hbs
  admin/app/components/organization-information-section.js
  admin/app/controllers/authenticated/organizations/get.js
  admin/app/styles/authenticated/organizations/get.scss
  admin/app/styles/misc/form.scss
  admin/app/styles/misc/global.scss
  admin/app/styles/misc/palette.scss
  admin/app/templates/authenticated/organizations/get.hbs
  admin/mirage/config.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/organization-information-management-test.js
  admin/tests/integration/components/organization-information-section-test.js
  api/lib/domain/usecases/update-organization-information.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1492 [TECH] Simplification de la création de badge en BDD (PIX-736).
  api/db/migrations/20200608170256_alter_table_badgePartnerCompetences_column_color_from_notNullable_to_nullable.js
  api/db/seeds/data/badge-target-profile-builder.js
  api/lib/domain/models/CampaignParticipationResult.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/tooling/database-builder/factory/build-badge-partner-competence.js
  api/tests/tooling/domain-builder/factory/build-badge-partner-competence.js
Labels: Tech Review OK, team-evaluation

#1505 [TECH] Paralléliser les tests end-to-end sur la CI.
  .circleci/config.yml
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces, team-certif, team-evaluation, team-prescription

#1484 [FEATURE] Création d'une composant graphique Modal (PIX-717).
  orga/app/components/modal/body.hbs
  orga/app/components/modal/dialog.hbs
  orga/app/components/modal/dialog.js
  orga/app/components/modal/footer.hbs
  orga/app/components/password-reset-modal.hbs
  orga/app/components/password-reset-modal.js
  orga/app/components/pix-modal.js
  orga/app/styles/app.scss
  orga/app/styles/components/modal.scss
  orga/app/styles/components/password-reset-modal.scss
  orga/app/styles/globals/pix-modal.scss
  orga/app/templates/components/password-reset-window.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/helpers/contains.js
  orga/tests/integration/components/modal/dialog-test.js
  orga/tests/integration/components/password-reset-modal-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1475 [FEATURE] Multi-badge sur une campagne (PIX-660).
  api/lib/domain/events/handle-badge-acquisition.js
  api/lib/domain/models/BadgePartnerCompetence.js
  api/lib/domain/models/CampaignParticipationBadge.js
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-badge.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-result.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/events/handle-badge-acquisition_test.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
  api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  mon-pix/app/controllers/assessment-campaigns/skill-review.js
  mon-pix/app/models/campaign-participation-badge.js
  mon-pix/app/models/campaign-participation-result.js
  mon-pix/app/models/partner-competence-result.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/assessment-campaigns/skill-review.hbs
  mon-pix/ember-cli-build.js
  mon-pix/mirage/serializers/campaign-participation-badge.js
  mon-pix/mirage/serializers/campaign-participation-result.js
  mon-pix/public/images/badges/agent_2_0.svg
  mon-pix/public/images/badges/office.svg
  mon-pix/public/images/badges/pro-recherche.svg
  mon-pix/public/images/badges/responsible_web_user.svg
  mon-pix/public/images/badges/socle-de-base.svg
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/unit/controllers/assessment-campaigns/skill-review-test.js
  mon-pix/tests/unit/models/campaign-participation-badge-test.js
  mon-pix/tests/unit/models/campaign-participation-result-test.js
  mon-pix/tests/unit/models/partner-competence-result-test.js
Labels: Func Review OK, Tech Review OK, team-evaluation

#1434 [TECH] Montée de version de Bookshelf
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/validators/campaign-validator.js
  api/lib/infrastructure/bookshelf.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/user-orga-settings-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/utils/bookshelf-to-domain-converter.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/domain/usecases/create-campaign_test.js
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1495 [CLEANUP] Clarifier la log du script de création des centres de certification.
  api/scripts/create-sco-certification-centers.js
Labels: :rocket: Ready to Merge, team-acces

#1458 [TECH] Montée de version des apps Ember de 3.15 à 3.18
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/app/templates/user-tutorials.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/app/templates/authenticated/students/list.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review Needed, team-acces, team-certif, team-evaluation, team-prescription

#1486 Afficher les informations générales d'un profil partagé pendant une campagne (PIX-626).
  api/lib/application/campaignParticipations/campaign-participation-controller.js
  api/lib/application/campaignParticipations/index.js
  api/lib/domain/models/CertificationProfile.js
  api/lib/domain/read-models/CampaignProfile.js
  api/lib/domain/usecases/get-campaign-profile.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-profile-serializer.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/integration/domain/usecases/get-campaign-profile_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  api/tests/tooling/database-builder/factory/build-campaign-participation-with-user.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/unit/domain/models/CertificationProfile_test.js
  api/tests/unit/domain/read-models/CampaignProfile_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-profile-serializer_test.js
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/adapters/campaign-profile.js
  orga/app/controllers/authenticated/campaigns/details/profiles.js
  orga/app/models/campaign-profile.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/profile.js
  orga/app/styles/app.scss
  orga/app/styles/components/previous-page-button.scss
  orga/app/styles/components/tag.scss
  orga/app/styles/globals/colors.scss
  orga/app/styles/pages/authenticated/campaigns/profiles.scss
  orga/app/templates/authenticated/campaigns/details/profiles.hbs
  orga/app/templates/authenticated/campaigns/profile.hbs
  orga/app/templates/components/previous-page-button.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/profiles-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/profile/profile.hbs
  orga/app/templates/components/tag.hbs
  orga/mirage/config.js
  orga/mirage/factories/campaign-profile.js
  orga/mirage/serializers/campaign-profile.js
  orga/tests/acceptance/profile-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/profiles-tab-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/profile/profile-test.js
  orga/tests/unit/adapters/campaign-profile-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1501 [FEATURE] Ajouter un système d'onglets dans le détail d'une organisation dans Pix Admin (PIX-827).
  admin/app/components/organization-members-section.hbs
  admin/app/controllers/authenticated/organizations/get.js
  admin/app/controllers/authenticated/organizations/get/members.js
  admin/app/controllers/authenticated/organizations/get/target-profiles.js
  admin/app/router.js
  admin/app/routes/authenticated/organizations/get/index.js
  admin/app/routes/authenticated/organizations/get/members.js
  admin/app/routes/authenticated/organizations/get/target-profiles.js
  admin/app/templates/authenticated/organizations/get.hbs
  admin/app/templates/authenticated/organizations/get/members.hbs
  admin/app/templates/authenticated/organizations/get/target-profiles.hbs
  admin/tests/acceptance/organization-information-management-test.js
  admin/tests/acceptance/organization-list-test.js
  admin/tests/acceptance/organization-memberships-management-test.js
  admin/tests/acceptance/organization-target-profiles-management-test.js
  admin/tests/unit/controllers/authenticated/organizations/get/members-test.js
Labels: Func Review OK, Tech Review OK, team-acces, team-prescription

#1499 [TECH] Suppression de la route dépréciée `/campaigns/id/csvResults` (PIX-832).
  api/lib/application/campaigns/index.js
  api/tests/integration/application/campaigns/index_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#1489 [BUGFIX] Eviter le crash de container lorsqu'une analyse de campagne se déclenche (PIX-785)
  api/lib/domain/models/CampaignAnalysis.js
  api/lib/domain/models/TargetProfile.js
  api/lib/domain/usecases/compute-campaign-analysis.js
  api/lib/infrastructure/adapters/target-profile-adapter.js
  api/lib/infrastructure/data/target-profile.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1497 [FEATURE] Ajout des info de certification dans le tableau des participants (PIX-619).
  api/lib/domain/read-models/CampaignProfilesCollectionParticipationSummary.js
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-profiles-collection-participation-summary-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  api/tests/unit/domain/usecases/find-campaign-profiles-collection-participation-summaries_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-profiles-collection-participation-summary-serializer_test.js
  orga/app/models/campaign-profiles-collection-participation-summary.js
  orga/app/styles/app.scss
  orga/app/styles/components/pix-score-tag.scss
  orga/app/styles/components/tag.scss
  orga/app/templates/components/routes/authenticated/campaigns/details/profiles-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/profile/profile.hbs
  orga/app/templates/components/tag.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/routes/authenticated/campaigns/details/profiles-tab-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/profile/profile-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1511 [FEATURE] Empêcher la connexion à Pix Orga d'un utilisateur dont le membership a été désactivé (PIX-766).
  api/db/migrations/20200612093847_add-column-disabledAt-to-memberships.js
  api/lib/infrastructure/repositories/prescriber-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-membership.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1510 [FEATURE] Changer la source de stockage des images de badges (PIX-777)
  mon-pix/app/templates/assessment-campaigns/skill-review.hbs
  mon-pix/public/images/badges/CleA_Num_certif.svg
  mon-pix/public/images/badges/Pix-emploi.svg
  mon-pix/public/images/badges/agent_2_0.svg
  mon-pix/public/images/badges/office.svg
  mon-pix/public/images/badges/pro-recherche.svg
  mon-pix/public/images/badges/responsible_web_user.svg
  mon-pix/public/images/badges/socle-de-base.svg
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#1504 [FEATURE] Permettre la mise à jour du prénom, nom et l'email d'un utilisateur connecté par email dans Pix Admin (PIX-458).
  admin/app/adapters/user.js
  admin/app/components/user-detail-personal-information.hbs
  admin/app/components/user-detail-personal-information.js
  admin/app/templates/authenticated/users/get.hbs
  admin/mirage/config.js
  admin/tests/acceptance/user-details-personal-information-test.js
  admin/tests/integration/components/user-detail-personal-information-test.js
  api/lib/application/users/index.js
  api/tests/acceptance/application/users/update-user-details-for-administration_test.js
  api/tests/integration/application/users/index_test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1507 [FEATURE] Ne plus afficher les membres désactivés dans PixOrga et PixAdmin (PIX-409).
  api/db/seeds/data/organizations-builder.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/tests/acceptance/application/security-pre-handlers_test.js
  api/tests/acceptance/application/user-orga-settings-controller_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
Labels: Tech Review Needed, team-acces

#1512 [BUGFIX] Format de date invalide lors de la création d'un utilisateur SCO (PIX-834).
  api/lib/application/schooling-registration-dependent-users/index.js
  api/lib/application/student-dependent-users/index.js
  api/tests/integration/application/schooling-registration-dependent-users/index_test.js
  api/tests/integration/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller_test.js
  api/tests/integration/application/student-dependent-users/index_test.js
Labels: Tech Review Needed, team-acces

#1496 [FEATURE] Ajouter lien vers BI sur le détail d'une organisation (PIX-605).
  admin/app/components/organization-information-section.hbs
  admin/app/components/organization-information-section.js
  admin/app/styles/app.scss
  admin/app/styles/components/organization-information-section.scss
  admin/config/environment.js
  admin/tests/helpers/create-glimmer-component.js
  admin/tests/unit/components/organization-information-section-test.js
Labels: Tech Review Needed, team-acces

#1518 [TECH] Paralléliser les tests end-to-end sur la CI.
  .circleci/config.yml
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/package.json
Labels: Tech Review Needed, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1517 [TECH] Montée de version de Node (12.18.0) et NPM (6.14.4).
  .circleci/config.yml
  INSTALLATION.md
  admin/package.json
  api/package.json
  certif/package.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package.json
  mon-pix/package.json
  orga/package.json
  package.json
  scripts/configure.sh
Labels: Tech Review Needed, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1514 [TECH] Correction des tests e2e qui échouent aléatoirement sur la CI.
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
Labels: :warning: PR Inheritance, Tech Review Needed, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1468 [CLEANUP] Ne plus sélectionner les assessment-results automatiquement lorsqu'on sélectionne un assessment depuis la BDD (PIX-775)
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/models/certification.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations-test.js
  api/lib/domain/models/Answer.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/Certification.js
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/get-assessment.js
  api/lib/domain/usecases/get-user-certification-with-result-tree.js
  api/lib/infrastructure/data/assessment.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/assessment-result-repository.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-result-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-certification.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/models/Certification_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/usecases/get-assessment_test.js
  api/tests/unit/domain/usecases/get-user-certification-with-result-tree_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-serializer_test.js
  mon-pix/app/models/assessment.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1522 [BUGFIX] Mauvais affichage des notifications après la finalisation (PIX-848)
  certif/package-lock.json
  certif/package.json
Labels: :steam_locomotive: EXPEDIT, Func Review Needed, Tech Review Needed, team-certif

#1488 [DOC] Mise à jour des bonnes pratiques d'accessibilité
  docs/Accessibilite.md
Labels: Design Review Needed, Func Review Needed, Tech Review Needed, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1513 [FEATURE] Afficher les competences avec score et niveau pour un participant (PIX-622)
  api/lib/domain/read-models/CampaignProfile.js
  api/lib/domain/read-models/CampaignProfileCompetence.js
  api/lib/infrastructure/serializers/jsonapi/campaign-profile-serializer.js
  api/tests/unit/domain/read-models/CampaignProfile_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-profile-serializer_test.js
  orga/app/models/campaign-profile-competence.js
  orga/app/models/campaign-profile.js
  orga/app/styles/app.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/campaigns/profile.scss
  orga/app/templates/components/routes/authenticated/campaigns/profile/profile.hbs
  orga/app/templates/components/routes/authenticated/campaigns/profile/table.hbs
  orga/tests/integration/components/routes/authenticated/campaigns/profile/table-test.js
  orga/tests/unit/models/campaign-profile-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1523 [TECH] Assurer que la version de node installée est 12.18.x.
  .circleci/config.yml
  admin/package.json
  api/package.json
  certif/package.json
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package.json
  mon-pix/package.json
  orga/package.json
  package.json
Labels: Tech Review Needed, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1520 [FEATURE] Filtrer les élèves par nom dans pix-orga (PIX-719).
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/find-user-with-schooling-registrations.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/utils/query-params-utils.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-organization-students_with-users-infos-test.js
  orga/app/adapters/student.js
  orga/app/components/password-reset-modal.js
  orga/app/controllers/authenticated/students/list.js
  orga/app/routes/authenticated/students/list.js
  orga/app/templates/authenticated/students/list.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/mirage/config.js
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
  orga/tests/unit/adapters/student-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1521 [BUGFIX] Ne pas lever une erreur 500 lors de la recherche d'une session avec un identifiant trop grand.
  api/lib/application/sessions/index.js
  api/lib/config.js
  api/lib/domain/validators/id-specification.js
  api/lib/domain/validators/session-validator.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/unit/application/session/index_test.js
Labels: Func Review Needed, Tech Review Needed, team-certif

#1533 [TECH] Supprimer les tests unitaires Ember redondants
  admin/tests/unit/components/certification-details-competence-test.js
  admin/tests/unit/components/certification-info-competences-test.js
  admin/tests/unit/components/certification-info-field-test.js
  admin/tests/unit/components/organization-information-section-test.js
  admin/tests/unit/serializers/certification-details-test.js
  admin/tests/unit/serializers/certification-test.js
  admin/tests/unit/serializers/organization-test.js
  admin/tests/unit/services/csv-service-test.js
  certif/tests/unit/routes/application-test.js
  orga/tests/unit/models/campaign-test.js
  orga/tests/unit/models/competence-result-test.js
  orga/tests/unit/models/student-test.js
  orga/tests/unit/routes/application-test.js
  orga/tests/unit/routes/not-found-test.js
Labels: Tech Review Needed, team-acces, team-captains, team-certif, team-prescription

#1524 [FEATURE] Permettre l'anonymisation d'un utilisateur depuis Pix Admin (PIX-729)
  admin/app/adapters/user.js
  admin/app/components/user-detail-personal-information.hbs
  admin/app/components/user-detail-personal-information.js
  admin/app/styles/misc/button.scss
  admin/app/styles/misc/palette.scss
  admin/mirage/config.js
  admin/tests/acceptance/user-details-personal-information-test.js
  admin/tests/integration/components/user-detail-personal-information-test.js
  admin/tests/unit/adapters/user-test.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/anonymize-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/users/users-controller-anonymize-user_test.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/anonymize-user_test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1532 [FEATURE] Ajout d'une colonne de titre pour les badges (PIX-849).
  api/db/migrations/20200617111042_add-column-title-to-badges.js
  api/db/seeds/data/badge-target-profile-builder.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/CampaignParticipationBadge.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/tooling/database-builder/factory/build-badge.js
  api/tests/tooling/domain-builder/factory/build-badge.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-badge.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js
  mon-pix/app/models/badge.js
Labels: Tech Review Needed, team-evaluation

#1534 [FEATURE] Afficher l'url d'une campagne dans Pix Orga suivant l'extension sur laquelle on est (fr ou org) (PIX-826).
  orga/app/components/routes/authenticated/campaigns/details/parameters-tab.js
  orga/app/models/campaign.js
  orga/app/services/current-domain.js
  orga/app/services/url.js
  orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs
  orga/config/environment.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/parameters-tab-test.js
  orga/tests/unit/services/url-test.js
Labels: Func Review OK, Tech Review OK, team-evaluation, team-prescription

#1535 [FEATURE] Filtrer les élèves par prénom dans pix-orga (PIX-721).
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/controllers/authenticated/students/list.js
  orga/app/routes/authenticated/students/list.js
  orga/app/templates/authenticated/students/list.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/mirage/config.js
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
  orga/tests/unit/controllers/authenticated/students/list-test.js
  orga/tests/unit/routes/authenticated/students/list-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1483 [DESIGN-SYSTEM] Ajout de la PixTooltip sur Pix Admin
  admin/app/components/menu-bar.hbs
  admin/app/styles/app.scss
  admin/app/styles/components/menu-bar.scss
  admin/app/styles/misc/tooltip.scss
  admin/package-lock.json
  admin/package.json
Labels: Design Review Needed, Tech Review Needed, team-acces, team-certif, team-evaluation, team-prescription

#1525 [FEATURE] Dissocier les comptes utilisateurs des élèves depuis Pix ORGA (Pix-718).
  api/lib/application/schooling-registration-user-associations/index.js
  api/lib/application/schooling-registration-user-associations/schooling-registration-user-association-controller.js
  api/lib/domain/usecases/dissociate-user-from-schooling-registration.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/schooling-registration-user-association-controller_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration.js
  api/tests/unit/domain/usecases/dissociate-user-from-schooling-registration_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer_test.js
  orga/app/adapters/student.js
  orga/app/components/dissociate-user-modal.js
  orga/app/components/routes/authenticated/students/list-items.js
  orga/app/controllers/authenticated/students/list.js
  orga/app/models/student.js
  orga/app/styles/app.scss
  orga/app/styles/components/dissociate-user-modal.scss
  orga/app/styles/components/modal.scss
  orga/app/templates/authenticated/students/list.hbs
  orga/app/templates/components/dissociate-user-modal.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/mirage/config.js
  orga/tests/acceptance/dissociate-student-test.js
  orga/tests/integration/components/dissociate-user-modal-test.js
  orga/tests/unit/adapters/student-test.js
  orga/tests/unit/models/student-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1519 [CLEANUP] Simplification et amélioration de l'accès aux campagnes (PIX-847)
  mon-pix/app/controllers/campaigns/assessment/skill-review.js
  mon-pix/app/controllers/campaigns/assessment/tutorial.js
  mon-pix/app/controllers/campaigns/campaign-landing-page.js
  mon-pix/app/controllers/campaigns/fill-in-id-pix.js
  mon-pix/app/controllers/campaigns/profiles-collection/profile-already-shared.js
  mon-pix/app/controllers/campaigns/profiles-collection/send-profile.js
  mon-pix/app/controllers/campaigns/restricted/join.js
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/router.js
  mon-pix/app/routes/assessment-campaigns/start-or-resume.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/routes/campaigns.js
  mon-pix/app/routes/campaigns/assessment/skill-review.js
  mon-pix/app/routes/campaigns/assessment/start-or-resume.js
  mon-pix/app/routes/campaigns/assessment/tutorial.js
  mon-pix/app/routes/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/fill-in-id-pix.js
  mon-pix/app/routes/campaigns/profiles-collection.js
  mon-pix/app/routes/campaigns/profiles-collection/profile-already-shared.js
  mon-pix/app/routes/campaigns/profiles-collection/send-profile.js
  mon-pix/app/routes/campaigns/profiles-collection/start-or-resume.js
  mon-pix/app/routes/campaigns/restricted/join.js
  mon-pix/app/routes/campaigns/restricted/login-or-register-to-access.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/profiles-collection-campaigns/profile-already-shared.js
  mon-pix/app/routes/profiles-collection-campaigns/send-profile.js
  mon-pix/app/routes/profiles-collection-campaigns/start-or-resume.js
  mon-pix/app/routes/restricted-campaigns/login-or-register-to-access-restricted-campaign.js
  mon-pix/app/templates/campaigns/assessment/skill-review.hbs
  mon-pix/app/templates/campaigns/assessment/tutorial.hbs
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
  mon-pix/app/templates/campaigns/profiles-collection/send-profile.hbs
  mon-pix/app/templates/campaigns/restricted/join.hbs
  mon-pix/app/templates/campaigns/restricted/login-or-register-to-access.hbs
  mon-pix/mirage/factories/campaign.js
  mon-pix/tests/acceptance/login-or-register-to-access-restricted-campaign-test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/unit/controllers/campaigns/assessment/skill-review-test.js
  mon-pix/tests/unit/controllers/campaigns/campaign-landing-page-test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-id-pix-test.js
  mon-pix/tests/unit/controllers/campaigns/profiles-collection/send-profile-test.js
  mon-pix/tests/unit/controllers/campaigns/restricted/join.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code-test.js
  mon-pix/tests/unit/routes/assessments/resume-test.js
  mon-pix/tests/unit/routes/campaigns/assessment/tutorial-test.js
  mon-pix/tests/unit/routes/campaigns/campaign-landing-page-test.js
  mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
  mon-pix/tests/unit/routes/campaigns/restricted/join.js
  mon-pix/tests/unit/routes/profiles-collection-campaigns/send-profile-test.js
  mon-pix/tests/unit/routes/restricted-campaigns/join-restricted-campaign-test.js
  mon-pix/tests/unit/routes/restricted-campaigns/login-or-register-to-access-restricted-campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1531 [TECH] Montée de la BDD en version 12
  .circleci/config.yml
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  docker-compose.yml
Labels: :rocket: Ready to Merge, team-acces, team-captains, team-certif, team-evaluation, team-prescription

#1540 [BUGFIX] Empêcher l'édition des informations d'un utilisateur connecté via le GAR depuis Pix Admin(PIX-861)
  admin/app/components/user-detail-personal-information.hbs
  admin/app/models/user.js
  admin/tests/integration/components/user-detail-personal-information-test.js
Labels: Tech Review Needed, team-acces

#1508 [TECH] Amélioration de la configuration de Bookshelf
  api/lib/infrastructure/bookshelf.js
  api/lib/infrastructure/data/answer.js
  api/lib/infrastructure/data/assessment-result.js
  api/lib/infrastructure/data/assessment.js
  api/lib/infrastructure/data/badge-acquisition.js
  api/lib/infrastructure/data/badge-criterion.js
  api/lib/infrastructure/data/badge-partner-competence.js
  api/lib/infrastructure/data/badge.js
  api/lib/infrastructure/data/campaign-participation.js
  api/lib/infrastructure/data/campaign.js
  api/lib/infrastructure/data/certification-candidate.js
  api/lib/infrastructure/data/certification-center-membership.js
  api/lib/infrastructure/data/certification-center.js
  api/lib/infrastructure/data/certification-challenge.js
  api/lib/infrastructure/data/certification-course.js
  api/lib/infrastructure/data/competence-evaluation.js
  api/lib/infrastructure/data/competence-mark.js
  api/lib/infrastructure/data/feedback.js
  api/lib/infrastructure/data/knowledge-element.js
  api/lib/infrastructure/data/membership.js
  api/lib/infrastructure/data/organization-invitation.js
  api/lib/infrastructure/data/organization.js
  api/lib/infrastructure/data/partner-certification.js
  api/lib/infrastructure/data/pix-role.js
  api/lib/infrastructure/data/reset-password-demand.js
  api/lib/infrastructure/data/schooling-registration.js
  api/lib/infrastructure/data/session.js
  api/lib/infrastructure/data/target-profile-share.js
  api/lib/infrastructure/data/target-profile-skill.js
  api/lib/infrastructure/data/target-profile.js
  api/lib/infrastructure/data/tutorial-evaluation.js
  api/lib/infrastructure/data/user-orga-settings.js
  api/lib/infrastructure/data/user-pix-role.js
  api/lib/infrastructure/data/user-tutorials.js
  api/lib/infrastructure/data/user.js
  api/lib/infrastructure/utils/bookshelf-to-domain-converter.js
Labels: team-evaluation

#1541 [CLEANUP] Corriger les erreurs signalées dans Pix Admin, par le ember template linter (PIX-828).
  admin/.template-lintrc.js
  admin/app/components/login-form.hbs
  admin/app/components/organization-form.hbs
  admin/app/components/organization-information-section.hbs
  admin/app/components/organizations/list-items.hbs
  admin/app/components/sessions/list-items.hbs
  admin/app/components/user-detail-personal-information.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/user-details-personal-information-test.js
Labels: Tech Review Needed, team-acces, team-certif, team-prescription

#1543 [BUGFIX] Déconnecter un utilisateur qui n'a plus de membership dans Pix Orga (PIX-837).
  orga/app/services/current-user.js
  orga/mirage/config.js
  orga/tests/unit/services/current-user-test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1546 [FEATURE] Amélioration des formulations lors de la réconciliation (PIX-816).
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/controllers/campaigns/restricted/join.js
  mon-pix/app/routes/campaigns/restricted/join.js
  mon-pix/app/templates/campaigns/restricted/join.hbs
  mon-pix/tests/integration/components/routes/register-form-test.js
  mon-pix/tests/unit/controllers/campaigns/restricted/join.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1516 [FEATURE] Permettre à l'utilisateur de rejoindre son parcours grâce à l'e-mail de création de compte (PIX-429).
  api/lib/application/users/user-controller.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/create-and-associate-user-to-schooling-registration.js
  api/lib/domain/usecases/create-user.js
  api/lib/infrastructure/utils/url-builder.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/create-and-associate-user-to-schooling-registration_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/infrastructure/utils/url-builder_test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/signup-form.js
  mon-pix/tests/unit/adapters/user-test.js
  mon-pix/tests/unit/components/signup-form-test.js
Labels: Func Review OK, Tech Review OK, team-acces

#1547 [FEATURE] Ajout d'un retour utilisateur lors de la dissociation d'un élève (PIX-865)
  orga/app/components/dissociate-user-modal.js
  orga/tests/integration/components/dissociate-user-modal-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1539 [BUGFIX] Erreur lorsqu'on tente de modifier une certification sur PixAdmin (PIX-866)
  api/lib/application/assessment-results/assessment-result-controller.js
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/models/CompetenceMark.js
  api/lib/domain/models/ResultCompetenceTree.js
  api/lib/domain/services/assessment-result-service.js
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/competence-mark-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-result-serializer.js
  api/scripts/get-results-certifications.js
  api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js
  api/tests/tooling/database-builder/factory/build-competence-mark.js
  api/tests/unit/application/assessment-results/assessment-result-controller_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CleaCertification_test.js
  api/tests/unit/domain/models/CompetenceMark_test.js
  api/tests/unit/domain/services/assessment-result-service_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-serializer_test.js
  api/tests/unit/scripts/get-results-certifications_test.js
Labels: :steam_locomotive: EXPEDIT, Func Review Needed, Tech Review Needed, team-certif

#1544 [BUGFIX] Permettre à un utilisateur connecté d'aller sur la page de changement de mot de passe (PIX-516).
  mon-pix/app/routes/reset-password.js
  mon-pix/tests/acceptance/reset-password-test.js
Labels: Func Review OK, Tech Review OK, team-acces

#1537 [FEATURE] Filtrer les élèves par type de connexion dans pix-orga (PIX-722)
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/tooling/database-builder/factory/build-schooling-registration-with-user.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/components/search-input.hbs
  orga/app/components/search-input.js
  orga/app/components/select-input.hbs
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/controllers/authenticated/students/list.js
  orga/app/models/student.js
  orga/app/routes/authenticated/students/list.js
  orga/app/styles/app.scss
  orga/app/styles/components/select-input.scss
  orga/app/styles/globals/forms.scss
  orga/app/templates/authenticated/campaigns/list.hbs
  orga/app/templates/authenticated/students/list.hbs
  orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
  orga/app/templates/components/routes/authenticated/campaigns/select-creator.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/app/templates/components/search-input.hbs
  orga/mirage/config.js
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
  orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1545 [FEATURE] Ajouter un nouveau type de signalement (PIX-836).
  mon-pix/app/static-data/feedback-panel-issue-labels.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#1530 [BUGFIX] Éviter de reposer un challenge auquel on a déjà répondu (PIX-210).
  api/lib/domain/services/smart-random/data-fetcher.js
  api/lib/domain/services/smart-random/skills-filter.js
  api/lib/domain/services/smart-random/smart-random.js
  api/tests/integration/domain/services/smart-random/smart-random_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/services/smart-random/skills-filter_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#1509 [FEATURE] PART-1 : Nouveau visuel certificat (PIX-597)
  mon-pix/app/components/user-certifications-detail-header.js
  mon-pix/app/models/certification.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_user-certification-hexagon-score.scss
  mon-pix/app/styles/components/_user-certifications-detail-banner.scss
  mon-pix/app/styles/components/_user-certifications-detail-header.scss
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/app/templates/components/user-certifications-detail-header.hbs
  mon-pix/app/templates/components/user-certifications-detail-result.hbs
  mon-pix/app/templates/components/user-certifications-hexagon-score.hbs
  mon-pix/app/templates/user-certifications.hbs
  mon-pix/app/templates/user-certifications/get.hbs
  mon-pix/app/templates/user-certifications/index.hbs
  mon-pix/public/images/macaron-certif.svg
  mon-pix/tests/integration/components/user-certifications-detail-header-test.js
  mon-pix/tests/integration/components/user-certifications-detail-result-test.js
Labels: Design Review Needed, Func Review Needed, Tech Review Needed, team-certif

#1506 [TECH] Ajouter les configurations d'IDE pour faciliter le déboggage.
  .gitignore
  .idea/runConfigurations/debug_admin.run.xml
  .idea/runConfigurations/debug_api_tests_watch.run.xml
  .idea/runConfigurations/debug_certif.run.xml
  .idea/runConfigurations/debug_mon-pix.run.xml
  .idea/runConfigurations/debug_orga.run.xml
  .idea/runConfigurations/start_api.run.xml
  .run/debug_admin.run.xml
  .run/debug_api_tests_watch.run.xml
  .run/debug_certif.run.xml
  .run/debug_mon-pix.run.xml
  .run/debug_orga.run.xml
  .run/start_api.run.xml
  .vscode/launch.json
Labels: Tech Review Needed, team-acces, team-certif, team-evaluation, team-prescription

#1529 [CLEANUP] Retrait de l'attribut level (déprécié) du modèle AssessmentResult (PIX-863)
  api/lib/application/assessment-results/assessment-result-controller.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/models/AssessmentResult.js
  api/lib/domain/models/CertificationAssessmentScore.js
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/services/user-service.js
  api/lib/infrastructure/repositories/assessment-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-result-serializer.js
  api/tests/tooling/database-builder/factory/build-assessment-result.js
  api/tests/tooling/domain-builder/factory/build-assessment-result.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CertificationAssessmentScore_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-serializer_test.js
Labels: Func Review Needed, Tech Review Needed, team-certif

#1554 [BUGFIX] Correction d'un test aléatoire sur les filtres des élèves
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
Labels: Tech Review Needed

#1549 [BUGFIX] Gérer les erreurs sur la page de changement de mot de passe (PIX-434).
  mon-pix/app/components/password-reset-demand-form.js
  mon-pix/app/routes/reset-password.js
  mon-pix/app/services/errors.js
  mon-pix/app/styles/components/_password-reset-demand-form.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/tests/acceptance/reset-password-test.js
  mon-pix/tests/integration/components/password-reset-demand-form-test.js
  mon-pix/tests/unit/services/errors-test.js
Labels: Design Review OK, Func Review OK, Tech Review Needed, team-acces

#1552 [CLEANUP] Corriger les erreurs signalées dans Pix Admin, par le linter dans app/templates/authenticated (PIX-878).
  admin/.template-lintrc.js
  admin/app/styles/misc/page.scss
  admin/app/templates/authenticated/certifications.hbs
  admin/app/templates/authenticated/certifications/certification/details.hbs
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/app/templates/authenticated/organizations/get.hbs
  admin/app/templates/authenticated/sessions/session.hbs
  admin/app/templates/authenticated/sessions/session/certifications.hbs
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/app/templates/authenticated/tools.hbs
  admin/app/templates/authenticated/users/get.hbs
Labels: Tech Review Needed, team-acces, team-certif, team-evaluation, team-prescription

#1551 [FEATURE] Ajout de la pagination sur le tableau des élèves (PIX-723)
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/find-paginated-filtered-schooling-registrations.js
  api/lib/domain/usecases/find-user-with-schooling-registrations.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-organization-students_with-users-infos-test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-schooling-registrations-test.js
  orga/app/components/pagination-control.js
  orga/app/controllers/authenticated/students/list.js
  orga/app/routes/authenticated/students/list.js
  orga/app/templates/components/pagination-control.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/mirage/config.js
  orga/mirage/handlers/find-filtered-paginated-students.js
  orga/mirage/handlers/find-paginated-campaign-participation-summaries.js
  orga/mirage/handlers/find-paginated-organization-memberships.js
  orga/mirage/handlers/pagination-utils.js
  orga/mirage/serializers/student.js
  orga/tests/acceptance/student-list-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1548 [BUGFIX] Bloquer les double-clics sur l'envoi de signalements (PIX-704).
  mon-pix/app/components/feedback-panel.js
  mon-pix/app/components/tutorial-item.js
  mon-pix/app/templates/components/feedback-panel.hbs
  mon-pix/app/utils/button-status-types.js
  mon-pix/config/environment.js
  mon-pix/tests/unit/components/feedback-panel-test.js
Labels: Func Review OK, Tech Review OK, team-evaluation

#1556 [FEATURE] Permettre à un prescripteur d'obtenir un e-mail d'invitation en fonction de sa région (PIX-810).
  api/lib/application/organizations/organization-controller.js
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/domain/usecases/create-organization-invitations.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/domain/usecases/create-organization-invitations_test.js
  orga/app/adapters/application.js
  orga/tests/unit/adapters/application-test.js
  scalingo.json
Labels: Func Review OK, Tech Review Needed, team-acces

#1558 [BUGFIX] Rediriger le prescrit vers son parcours après inscription (PIX-886).
  mon-pix/app/components/signup-form.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/unit/components/signup-form-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-acces

#1559 [FEATURE] Afficher le bouton retenter sur la carte de la competence (PIX-757).
  mon-pix/app/components/competence-card-default.js
  mon-pix/app/styles/components/_competence-card-desktop.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/templates/components/competence-card-default.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/tests/integration/components/competence-card-default-test.js
  mon-pix/tests/unit/components/competence-card-default-test.js
Labels: Func Review Needed, Tech Review OK, team-evaluation

#1536 [FEATURE] Afficher un message d'erreur approprié lors de la connexion à Pix App (PIX-367).
  api/lib/application/authentication/index.js
  mon-pix/app/components/signin-form.js
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/config/ember-intl.js
  mon-pix/config/environment.js
  mon-pix/tests/integration/components/signin-form-test.js
  mon-pix/translations/en-us.json
  mon-pix/translations/fr-fr.json
Labels: Design Review Needed, Func Review OK, team-acces, team-evaluation

#1553 [ORGA] Remonter l'item documentation dans le menu. (PIX-461)
  orga/app/styles/components/sidebar-menu.scss
  orga/app/styles/pages/authenticated.scss
  orga/app/templates/components/sidebar-menu.hbs
  orga/public/icons/address-book-light.svg
  orga/public/icons/book-light.svg
  orga/public/icons/chevron-square-right.svg
  orga/public/icons/users-light.svg
  orga/tests/acceptance/authentication-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1564 [BUGFIX] Vérifier qu'un membre désactivé n'accede pas aux routes de campagnes (PIX-857).
  api/lib/infrastructure/repositories/campaign-repository.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1563 [BUGFIX] Rollback Ember lint compatibilité (PIX-890)
  admin/app/components/certification-details-competence.js
  admin/app/components/certification-info-competences.js
  admin/app/components/confirm-popup.js
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/app/templates/authenticated/sessions/session/certifications.hbs
Labels: :steam_locomotive: EXPEDIT, Func Review Needed, Tech Review Needed, team-certif

#1569 [CLEANUP] Accélère la manière de construire un CertificationProfile (PIX-896)
  api/lib/domain/services/user-service.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1566 [BUGFIX] Corriger le pourcentage de la barre de progression lorsque la compétence est retentée (PIX-841).
  api/lib/domain/usecases/get-progression.js
  api/tests/unit/domain/usecases/get-progression_test.js
Labels: Tech Review Needed, team-evaluation

#1538 [FEATURE] Modification dans le design des badges sur la page de résultat (PIX-778).
  mon-pix/app/controllers/campaigns/assessment/skill-review.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_badge-acquired-card.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/assessment/skill-review.hbs
  mon-pix/app/templates/components/badge-acquired-card.hbs
  mon-pix/app/templates/components/profile-content.hbs
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/integration/components/badge-acquired-card-test.js
  mon-pix/tests/unit/controllers/campaigns/assessment/skill-review-test.js
Labels: Design Review Needed, Func Review Needed, Tech Review Needed, team-evaluation

#1528 [CLEANUP] Suppression du modèle CampaignAssessment et de son repository (PIX-897)
  api/lib/domain/models/CampaignAssessment.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/find-campaign-participations-related-to-assessment.js
  api/lib/domain/usecases/find-competence-evaluations.js
  api/lib/domain/usecases/get-progression.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/share-campaign-result.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/campaign-assessment-repository.js
  api/tests/acceptance/application/progression-controller_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
  api/tests/tooling/database-builder/factory/build-organization-invitation.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-campaign-assessment.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/answers/answer-controller_test.js
  api/tests/unit/domain/models/CampaignAssessment_test.js
  api/tests/unit/domain/usecases/find-campaign-assessments_test.js
  api/tests/unit/domain/usecases/find-campaign-participations-related-to-assessment_test.js
  api/tests/unit/domain/usecases/find-competence-evaluations_test.js
  api/tests/unit/domain/usecases/get-progression_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation, team-prescription

#1565 [FEATURE] Ajout d'un email de récupération pour les organisations (PIX-843).
  api/db/migrations/20200625113402_add-column-email-to-organizations.js
Labels: Tech Review Needed, team-acces

#1568 [FEATURE] Cacher le bouton Retenter quand l'utilisateur a terminé une compétence avec le niveau max (PIX-759).
  mon-pix/app/components/scorecard-details.js
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/tests/integration/components/scorecard-details-test.js
  mon-pix/tests/unit/components/scorecard-details-test.js
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#1557 [FEATURE] Sauvegarder l'identifiant de l'administrateur qui a modifié le lien d'un utilisateur avec une organisation (PIX-859).
  api/db/migrations/20200623155650_add_updatedByUser_to_memberships.js
  api/lib/application/memberships/index.js
  api/lib/application/memberships/membership-controller.js
  api/lib/domain/models/Membership.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-membership-role.js
  api/lib/domain/usecases/update-membership.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/lib/infrastructure/serializers/jsonapi/membership-serializer.js
  api/tests/acceptance/application/membership-controller_test.js
  api/tests/integration/application/memberships/membership-controller_test.js
  api/tests/integration/domain/usecases/update-membership_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/unit/domain/usecases/update-membership-attributes_test.js
  api/tests/unit/domain/usecases/update-membership-role_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
Labels: Func Review OK, Tech Review Needed, team-acces

#1570 [BUGFIX] Fix admin certification detail page
  api/lib/domain/models/CertificationAssessment.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
Labels: :steam_locomotive: EXPEDIT, Func Review Needed, Tech Review Needed, team-certif

#1567 [FEATURE] Alimenter les adresses e-mail des organisations (PIX-874).
  api/scripts/populate-organizations-email.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/integration/scripts/populate-organizations-email_test.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/tooling/database-builder/factory/build-organization.js
Labels: Tech Review Needed, team-acces

#1574 [BUGFIX] Retirer le message de contexte sur la double mire de Pix Orga (PIX-912).
  orga/app/templates/components/routes/login-form.hbs
  orga/tests/integration/components/routes/login-form-test.js
Labels: Func Review OK, Tech Review OK, team-acces

#1573 [INFRA] Permettre que les e-mails renvoient vers le bon environnement (PIX-888).
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/lib/infrastructure/utils/url-builder.js
  api/sample.env
  scalingo.json
Labels: Tech Review Needed, team-acces

#1576 [BUGFIX] Afficher un message d'erreur dans Pix Orga lorsque l'e-mail d'invitation est incorrect (PIX-471).
  api/lib/domain/validators/user-validator.js
  api/tests/unit/domain/validators/user-validator_test.js
  orga/app/controllers/authenticated/team/new.js
  orga/tests/acceptance/team-creation-test.js
Labels: Tech Review Needed, team-acces

#1575 [A11Y] Supprimer target='blank" des fichiers téléchargeables depuis les épreuves (PIX-835).
  mon-pix/app/templates/components/challenge-statement.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#1562 [CLEANUP] Corriger les erreurs signalées dans Pix Admin par le linter (PIX-889).
  admin/.template-lintrc.js
  admin/app/components/certification-details-competence.js
  admin/app/components/certification-info-competences.js
  admin/app/components/certification-info-field.js
  admin/app/components/pagination-control.js
  admin/app/templates/components/certification-details-answer.hbs
  admin/app/templates/components/certification-details-competence.hbs
  admin/app/templates/components/certification-info-competences.hbs
  admin/app/templates/components/certification-info-field.hbs
  admin/app/templates/components/certification-info-published.hbs
  admin/app/templates/components/certification-status-select.hbs
  admin/app/templates/components/confirm-popup.hbs
  admin/app/templates/components/pagination-control.hbs
  admin/package.json
  admin/tests/integration/components/certification-info-competences-test.js
  admin/tests/integration/components/certification-status-select-test.js
Labels: Func Review Needed, Tech Review Needed, team-acces, team-certif, team-evaluation, team-prescription

#1571 [FEATURE] Afficher l'email de l'organisation dans Pix Admin (PIX-844).
  admin/app/components/organization-information-section.hbs
  admin/app/models/organization.js
  api/db/seeds/data/organizations-builder.js
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/unit/domain/usecases/get-organization-details_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: Func Review Needed, Tech Review Needed, team-acces

#1561 [FEATURE] PART 2 - Nouveau design certificat (PIX-838)
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  mon-pix/app/components/user-certifications-detail-area.js
  mon-pix/app/components/user-certifications-detail-competence.js
  mon-pix/app/components/user-certifications-detail-competences-list.js
  mon-pix/app/components/user-certifications-detail-profile.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_user-certifications-detail-area.scss
  mon-pix/app/styles/components/_user-certifications-detail-competence.scss
  mon-pix/app/styles/components/_user-certifications-detail-competences-list.scss
  mon-pix/app/styles/components/_user-certifications-detail-profile.scss
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/app/templates/components/user-certifications-detail-area.hbs
  mon-pix/app/templates/components/user-certifications-detail-competence.hbs
  mon-pix/app/templates/components/user-certifications-detail-competences-list.hbs
  mon-pix/app/templates/components/user-certifications-detail-profile.hbs
  mon-pix/app/templates/user-certifications/get.hbs
  mon-pix/tests/integration/components/user-certifications-detail-area-test.js
  mon-pix/tests/integration/components/user-certifications-detail-competence-test.js
  mon-pix/tests/integration/components/user-certifications-detail-competences-list-test.js
  mon-pix/tests/integration/components/user-certifications-detail-profile-test.js
Labels: Design Review Needed, Func Review Needed, Tech Review Needed, team-certif

#1583 [BUGFIX] Le signalement surveillant était supprimé en enregistrant une certif (PIX-916)
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
Labels: :steam_locomotive: EXPEDIT, Tech Review Needed, team-certif

#1572 [BUGFIX] Correction de l'affichage du macaron Cléa sur la certif (PIX-879)
  mon-pix/app/styles/components/_certification-joiner.scss
  mon-pix/app/styles/components/_congratulations-certification-banner.scss
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/styles/pages/_certification-start.scss
  mon-pix/app/templates/components/certification-joiner.hbs
  mon-pix/app/templates/components/congratulations-certification-banner.hbs
  mon-pix/app/templates/components/navbar-header.hbs
  mon-pix/app/templates/components/user-certifications-detail-result.hbs
Labels: Tech Review Needed, team-certif

#1560 [BUGFIX] Corrige la numérotation des épreuves de certif dans Pix Admin (PIX-869)
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/usecases/get-next-challenge-for-certification.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/lib/infrastructure/repositories/certification-challenge-repository.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
Labels: Tech Review Needed, team-certif

#1577 [FEATURE] PART 3 - Nouveau design certificat (PIX-839)
  mon-pix/app/styles/components/_user-certifications-detail-competence.scss
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/app/templates/components/user-certifications-detail-competence.hbs
  mon-pix/app/templates/components/user-certifications-detail-competences-list.hbs
  mon-pix/app/templates/components/user-certifications-detail-result.hbs
  mon-pix/app/templates/user-certifications/get.hbs
  mon-pix/tests/integration/components/user-certifications-detail-competence-test.js
Labels: Design Review Needed, Func Review Needed, Tech Review Needed, team-certif

#1584 [FEATURE] Paramétrer l'attribut lang de Pix App (PIX-833).
  mon-pix/app/routes/application.js
  mon-pix/config/environment.js
  mon-pix/tests/integration/components/signup-form-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: team-evaluation
