Repository 1024pix/pix, pull requests merged in 2020-03, with the labels that each got.

#1133 [TECH] Enlève only et corrige un fichier de test dans pix admin
  admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js
Labels: :steam_locomotive: EXPEDIT, Tech Review Needed, team-certif, 🌟 Etoile

#1122 [FEATURE] Changer le design du bouton "Retour à la liste" sur la page certificat (PF-1051).
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/app/templates/user-certifications/get.hbs
  mon-pix/tests/acceptance/competences-details-test.js
  mon-pix/tests/acceptance/competences-results-test.js
Labels: Design Review OK, Func Review OK, Tech Review Needed, team-certif

#1126 [TECH] Augmenter le temps disponible pour les migrations de base de données lors des déploiements
  api/Procfile
  api/package.json
Labels: Tech Review Needed

#1120 [TECH] Ajout d'une colonne certificationCourseId dans la table assessments, clé étrangère vers la table certification-courses (PF-1128)
  api/db/migrations/20200225142247_add_column_certification-course-id_to_table_assessments.js
  api/lib/domain/models/Assessment.js
  api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/tooling/database-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/infrastructure/repositories/assessment-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1103 [FEATURE] Ajout d'un filtre sur le status lors de l'affichage de la liste des campagnes (PO-314).
  api/lib/application/organizations/organization-controller.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/routes/authenticated/campaigns/list.js
  orga/app/styles/pages/authenticated/campaigns/list.scss
  orga/app/templates/authenticated/campaigns/list.hbs
  orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
  orga/config/environment.js
  orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1128 [TECH] Passage de Pix Orga à Ember 3.13 (PO-353).
  orga/.eslintrc.js
  orga/app/adapters/application.js
  orga/app/routes/application.js
  orga/config/optional-features.json
  orga/mirage/config.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/password-reset-window-test.js
  orga/tests/integration/components/routes/register-form-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1131 [FEATURE] Pouvoir modifier le nom de la campagne dans PIX Orga (PO-350).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/domain/usecases/update-campaign.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/usecases/update-campaign_test.js
  orga/app/routes/authenticated/campaigns/update.js
  orga/app/templates/authenticated/campaigns/update.hbs
  orga/app/templates/components/routes/authenticated/campaigns/update-item.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1135 [TECH] Retrait de code mort : usecase plus utilisé dans le cadre de la certification sur mon-pix (PF-1136)
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/usecases/find-certification-assessments.js
  api/lib/domain/usecases/index.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/domain/usecases/find-certification-assessments_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1139 [BSR] Réusinage des utilitaires pour les fichiers ODS.
  api/lib/infrastructure/utils/ods/read-ods-utils.js
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/infrastructure/utils/ods/files/default_test.ods
  api/tests/integration/infrastructure/utils/ods/files/empty-table_test.ods
  api/tests/integration/infrastructure/utils/ods/files/get-content-xml_test.ods
  api/tests/integration/infrastructure/utils/ods/files/newline_test.ods
  api/tests/integration/infrastructure/utils/ods/files/simple-attendance_test.ods
  api/tests/integration/infrastructure/utils/ods/files/unknown-version_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/integration/infrastructure/utils/ods/write-ods-utils_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-accès

#1142 [FEATURE] Ajouter une colonne credit à la table organizations (PO-300).
  api/db/migrations/20200303153018_add-credit-column-to-organization.js
Labels: Func Review OK, Tech Review Needed, team-prescription

#1129 [FEATURE] Pouvoir changer d'organisation courante dans Pix Orga (PO-237).
  api/db/migrations/20200303140224_add_columns_createdAt_and_updatedAt_to_user_orga_settings.js
  api/lib/application/user-orga-settings/index.js
  api/lib/application/user-orga-settings/user-orga-settings-controller.js
  api/lib/application/users/index.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-user-orga-settings.js
  api/lib/infrastructure/data/user-orga-settings.js
  api/lib/infrastructure/repositories/user-orga-settings-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/user-orga-settings-controller_test.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/unit/application/user-orga-settings/index_test.js
  api/tests/unit/application/user-orga-settings/user-orga-settings-controller_test.js
  api/tests/unit/domain/usecases/update-user-orga-settings_test.js
  orga/app/components/user-logged-menu.js
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/services/current-user.js
  orga/app/styles/components/user-logged-menu.scss
  orga/app/templates/components/user-logged-menu.hbs
  orga/mirage/config.js
  orga/tests/acceptance/switch-organization-test.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/user-logged-menu-test.js
  orga/tests/unit/components/user-logged-menu-test.js
  orga/tests/unit/services/current-user-test.js
Labels: Func Review OK, Tech Review Needed, team-accès

#1144 [BUGFIX] Réinitialiser l'URL des campagnes quand je change d'organisation (PO-361).
  orga/app/components/user-logged-menu.js
  orga/tests/acceptance/switch-organization-test.js
Labels: :steam_locomotive: EXPEDIT, Func Review OK, Tech Review Needed, team-accès

#1114 [FEATURE] Ajout de la page mes tutos (PF-1102).
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  mon-pix/app/components/navbar-burger-menu.js
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/controllers/user-tutorials.js
  mon-pix/app/router.js
  mon-pix/app/routes/user-tutorials.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_background-banner.scss
  mon-pix/app/styles/components/_user-logged-menu.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/globals/_titles.scss
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/app/templates/user-tutorials.hbs
  mon-pix/config/environment.js
  mon-pix/public/images/user-tutorials/banner-icon.svg
  mon-pix/public/images/user-tutorials/illustration.svg
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
  mon-pix/tests/integration/components/user-logged-menu-test.js
  mon-pix/tests/unit/routes/user-tutorials-test.js
Labels: Design Review Needed, Func Review OK, Tech Review Needed, team-évaluation

#1137 [TECH] Nettoyage du modèle Course (PF-1137)
  api/lib/domain/models/Course.js
  api/lib/domain/services/smart-random/cat-algorithm.js
  api/lib/domain/services/smart-random/skills-filter.js
  api/lib/domain/services/smart-random/smart-random.js
  api/lib/domain/services/tube-service.js
  api/lib/infrastructure/serializers/jsonapi/course-serializer.js
  api/tests/integration/domain/services/tube-service_test.js
  api/tests/unit/domain/models/Course_test.js
  api/tests/unit/domain/services/smart-random/skills-filter_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/course-serializer_test.js
  mon-pix/app/models/course.js
  mon-pix/app/routes/courses/create-assessment.js
  mon-pix/mirage/data/demo.js
  mon-pix/mirage/routes/get-assessment.js
  mon-pix/mirage/routes/get-next-challenge.js
  mon-pix/mirage/routes/post-assessments.js
  mon-pix/mirage/scenarios/default.js
  mon-pix/tests/acceptance/starting-a-course-test.js
  mon-pix/tests/unit/routes/courses/create-assessment-test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1115 [FEATURE] Afficher les méthodes de connexion des élèves (PO-320)
  api/lib/domain/usecases/find-organization-students.js
  api/lib/infrastructure/serializers/jsonapi/student-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/unit/domain/usecases/find-organization-students_test.js
  orga/app/models/student.js
  orga/app/styles/pages/authenticated/students/list.scss
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
  orga/tests/unit/models/student-test.js
Labels: team-accès

#1145 [TECH] Range le code API qui gère les erreurs HTTP dans le répertoire `application`
  api/lib/application/campaignParticipations/campaign-participation-controller.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/competence-evaluations/competence-evaluation-controller.js
  api/lib/application/error-manager.js
  api/lib/application/feedbacks/feedback-controller.js
  api/lib/application/http-errors.js
  api/lib/application/organization-invitations/organization-invitation-controller.js
  api/lib/application/pre-response-utils.js
  api/lib/application/preHandlers/session-authorization.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/services/course-service.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/lib/infrastructure/utils/ods/read-ods-utils.js
  api/lib/infrastructure/utils/pre-response-utils.js
  api/server.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/application/pre-response-utils_test.js
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/test-helper.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/application/competence-evaluations/competence-evaluation-controller_test.js
  api/tests/unit/application/errors_test.js
  api/tests/unit/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/unit/application/pre-response-utils_test.js
  api/tests/unit/application/preHandlers/session-authorization_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/services/course-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/error-serializer_test.js
  api/tests/unit/infrastructure/utils/pre-response-utils_test.js
  api/tests/unit/tooling/http-test-server_test.js
Labels: Tech Review Needed

#1147 [FEATURE] Modifier l'entrée de menu de réinitialisation de mot de passe (PO-338).
  orga/app/styles/globals/buttons.scss
  orga/app/styles/pages/authenticated/students/list.scss
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-accès

#1152 [TECH] Déplacer les critères de badge vers l'API (PF-1149).
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-result.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
  api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js
  mon-pix/app/controllers/campaigns/skill-review.js
  mon-pix/app/models/campaign-participation-result.js
  mon-pix/mirage/routes/get-campaign-participation-result.js
  mon-pix/mirage/serializers/campaign-participation-result.js
  mon-pix/tests/unit/controllers/campaigns/skill-review-test.js
  mon-pix/tests/unit/models/campaign-participation-result-test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#1149 [TECH] Refacto des couleurs sur Pix Admin
  admin/app/styles/app.scss
  admin/app/styles/authenticated.scss
  admin/app/styles/authenticated/certifications/details.scss
  admin/app/styles/authenticated/certifications/sessions.scss
  admin/app/styles/authenticated/certifications/single.scss
  admin/app/styles/authenticated/organizations/get.scss
  admin/app/styles/authenticated/organizations/new.scss
  admin/app/styles/components/certification-details-answer.scss
  admin/app/styles/components/certification-details-competence.scss
  admin/app/styles/components/certification-session-report.scss
  admin/app/styles/components/menu-bar.scss
  admin/app/styles/components/pagination-control.scss
  admin/app/styles/login.scss
  admin/app/styles/misc/button.scss
  admin/app/styles/misc/callout.scss
  admin/app/styles/misc/form.scss
  admin/app/styles/misc/global.scss
  admin/app/styles/misc/page.scss
  admin/app/styles/misc/palette.scss
  admin/app/styles/misc/table-admin.scss
  admin/app/styles/misc/tables.scss
Labels: Design Review OK, Tech Review OK

#1148 [BUGFIX] Pouvoir accepter une invitation à rejoindre Pix Orga lorsqu'on est déjà authentifié (PO-240).
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/cypress/fixtures/organization-invitations.json
  high-level-tests/e2e/cypress/fixtures/organizations.json
  high-level-tests/e2e/cypress/integration/organization-management.feature
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/organization.js
  orga/app/router.js
  orga/app/routes/application.js
  orga/app/routes/join-when-authenticated.js
  orga/app/routes/join.js
  orga/tests/acceptance/join-test.js
  orga/tests/unit/routes/join-when-authenticated-test.js
  scalingo.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review Needed, team-accès

#1153 [TECH] Suppression de la table Snapshots (PF-1126).
  api/db/migrations/20200306143100_delete-snapshots-table.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1140 [FEATURE] Ajout d'un filtre sur la colonne "Créé par" dans la liste des campagnes (PO-330).
  api/lib/infrastructure/repositories/campaign-repository.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  orga/app/components/routes/authenticated/campaigns/list-items.js
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/routes/authenticated/campaigns/list.js
  orga/app/styles/app.scss
  orga/app/styles/components/search-input.scss
  orga/app/styles/components/select-creator.scss
  orga/app/styles/globals/tables.scss
  orga/app/templates/authenticated/campaigns/list.hbs
  orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
  orga/app/templates/components/routes/authenticated/campaigns/select-creator.hbs
  orga/mirage/serializers/membership.js
  orga/tests/acceptance/campaign-list-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1121 [TECH] Démocratisation du code HTTP 404 quand il est impossible de récupérer une ressource : routes answers (PF-1131)
  api/lib/application/answers/answer-controller.js
  api/lib/domain/usecases/find-answer-by-challenge-and-assessment.js
  api/lib/domain/usecases/get-answer.js
  api/lib/domain/usecases/get-correction-for-answer.js
  api/tests/acceptance/application/answers/answer-controller-find_test.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/acceptance/application/answers/answer-controller-get_test.js
  api/tests/acceptance/application/answers/answer-controller-update_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/unit/domain/usecases/find-answer-by-challenge-and-assessment_test.js
  api/tests/unit/domain/usecases/get-answer_test.js
  api/tests/unit/domain/usecases/get-correction-for-answer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1155 [FEATURE] Ajouter l'identifiant externe dans la liste des organisations (PA-113).
  admin/app/templates/components/routes/authenticated/organizations/list-items.hbs
  admin/tests/integration/components/routes/authenticated/organizations/list-items-test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-accès

#1162 [TECH] Retrait de la notion d'adaptatif + du type dans le modèle Course
  api/lib/domain/models/Course.js
  api/lib/infrastructure/datasources/airtable/course-datasource.js
  api/lib/infrastructure/repositories/course-repository.js
  api/lib/infrastructure/serializers/jsonapi/course-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-demo_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/tooling/airtable-builder/factory/build-course.js
  api/tests/tooling/domain-builder/factory/build-course.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  api/tests/unit/infrastructure/repositories/course-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/course-serializer_test.js
  mon-pix/app/models/course.js
  mon-pix/app/routes/courses/create-assessment.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1154 [BSR][TECH] Réusinage de quelques scripts api et de quelques fichiers de migrations.
  api/db/migrations/20180306151846_add_type_to_all_assessments.js
  api/db/migrations/20180306164441_remove-score-and-level-for-bugged-assessments.js
  api/package.json
  api/scripts/extract-challenge-with-skills.js
  api/scripts/fill-score-level.js
  api/scripts/get-results-certifications-old.js
  api/scripts/update-sco-organizations-with-province-code-and-external-id.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-accès

#1165 [BUGFIX] Autoriser l'affichage des autres membres d'une organisation pour un simple membre (PO-374).
  api/lib/application/organizations/index.js
  api/lib/application/usecases/checkUserBelongsToOrganization.js
  api/lib/interfaces/controllers/security-controller.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/acceptance/application/security-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/unit/application/usecases/checkUserBelongsToOrganization_test.js
  api/tests/unit/interfaces/controllers/security-controller_test.js
Labels: :rocket: Ready to Merge, :steam_locomotive: EXPEDIT, Func Review OK, Tech Review OK, team-prescription

#1163 [FEATURE] Affichage de la liste des profils cibles d'une organisation (PA-162).
  admin/app/models/organization.js
  admin/app/models/target-profile.js
  admin/app/templates/authenticated/organizations/get.hbs
  admin/app/templates/components/organization-target-profiles-section.hbs
  admin/tests/integration/components/organization-target-profiles-section-test.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK

#1158 [FEATURE] Lors de l'export des résultats, forcer les compétences à 0 pour les certifs rejected (PA-174)
  admin/app/services/session-info-service.js
  admin/tests/unit/services/session-info-service-test.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/db/seeds/data/certification/certification-courses-builder.js
  api/db/seeds/data/certification/certification-scores-builder.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1167 [INFRA] Amélioration de la mise en production
  .circleci/config.yml
  package.json
  scripts/release/deploy.sh
  scripts/release/prepare.sh
  scripts/release/publish.sh
Labels: Tech Review Needed

#1170 [FEATURE] Filtrer la liste des organisations par l'identifiant externe (PA-172).
  admin/app/components/routes/authenticated/organizations/list-items.js
  admin/app/controllers/authenticated/organizations/list.js
  admin/app/routes/authenticated/organizations/list.js
  admin/app/templates/authenticated/organizations/list.hbs
  admin/app/templates/components/routes/authenticated/organizations/list-items.hbs
  admin/tests/acceptance/organization-list-test.js
  admin/tests/integration/components/routes/authenticated/organizations/list-items-test.js
  api/lib/application/organizations/index.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
Labels: Func Review OK, Tech Review OK, team-accès

#1136 [FEATURE] Lister les sessions sur Pix Admin (PA-151)
  admin/app/components/routes/authenticated/sessions/list-items.js
  admin/app/controllers/authenticated/sessions/list.js
  admin/app/models/session.js
  admin/app/router.js
  admin/app/routes/authenticated/sessions/index.js
  admin/app/routes/authenticated/sessions/list.js
  admin/app/styles/misc/table-admin.scss
  admin/app/templates/authenticated/certifications/sessions/info/index.hbs
  admin/app/templates/authenticated/sessions.hbs
  admin/app/templates/authenticated/sessions/list.hbs
  admin/app/templates/components/menu-bar.hbs
  admin/app/templates/components/routes/authenticated/sessions/list-items.hbs
  admin/mirage/config.js
  admin/mirage/handlers/find-paginated-and-filtered-sessions.js
  admin/tests/acceptance/sessions-list-test.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/find-paginated-filtered-sessions.js
  api/lib/domain/usecases/find-sessions.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/acceptance/application/session/session-controller-get_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-sessions_test.js
  api/tests/unit/domain/usecases/find-sessions_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1175 [BUGFIX] Corriger la gestion des nombres décimaux en answer (PF-1155).
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/lib/domain/services/solution-service-qrocm-ind.js
  api/tests/unit/domain/services/solution-service-qrocm-dep_test.js
  api/tests/unit/domain/services/solution-service-qrocm-ind_test.js
Labels: Func Review Needed, Tech Review OK, team-évaluation

#1141 [FEATURE] Simplifier la publication de certification (PA-171)
  admin/app/adapters/session.js
  admin/app/components/certification-list-checkbox.js
  admin/app/components/certification-list.js
  admin/app/controllers/authenticated/certifications/sessions/info/list.js
  admin/app/controllers/authenticated/certifications/single/info.js
  admin/app/models/session.js
  admin/app/services/session-info-service.js
  admin/app/styles/authenticated/certifications/sessions/info/_list.scss
  admin/app/styles/misc/button.scss
  admin/app/templates/authenticated/certifications/sessions/info/list.hbs
  admin/app/templates/authenticated/certifications/single/info.hbs
  admin/app/templates/components/certification-list-checkbox.hbs
  admin/app/templates/components/certification-list-select-all.hbs
  admin/app/templates/components/certification-list.hbs
  admin/tests/integration/components/certification-list-checkbox-test.js
  admin/tests/integration/components/certification-list-select-all-test.js
  admin/tests/unit/adapters/session-test.js
  admin/tests/unit/controllers/authenticated/certifications/sessions/info/list-test.js
  admin/tests/unit/models/session-test.js
  admin/tests/unit/services/session-info-service-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-publication-session.js
  api/lib/infrastructure/data/assessment-result.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/update-publication-session_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1161 [TECH] Utiliser le champ certificationCourseId plutôt que courseId du modèle assessment dans un contexte de certification (PF-1150)
  api/db/seeds/data/certification/certification-courses-builder.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/usecases/complete-assessment.js
  api/lib/domain/usecases/get-assessment.js
  api/lib/domain/usecases/get-next-challenge-for-certification.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/data/certification-course.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
  api/tests/acceptance/application/assessments/assessment-controller-post_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/acceptance/application/session/session-controller-get-certifications_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/test-helper.js
  api/tests/tooling/database-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
  api/tests/unit/domain/usecases/get-assessment_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1164 [FEATURE] Gérer les critères de badge CLEA (PF-1132).
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/models/CompetenceResult.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-result.js
  api/tests/tooling/domain-builder/factory/build-competence-result.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/models/CompetenceResult_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  mon-pix/app/models/competence-result.js
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/mirage/routes/get-campaign-participation-result.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/unit/models/competence-result-test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#1169 [FEATURE] Optimisation du logo Pix (PF-1013).
  mon-pix/app/styles/components/_assessment-banner.scss
  mon-pix/app/styles/components/_navbar-desktop-header.scss
  mon-pix/app/styles/components/_navbar-mobile-header.scss
  mon-pix/app/styles/components/_pix-logo.scss
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/public/images/pix-logo-blanc.svg
  mon-pix/public/images/pix-logo.svg
Labels: Design Review OK, Tech Review OK, team-évaluation

#1173 [FEATURE] Affichage du nombre de crédits octroyés à une organisation dans Pix Admin (PA-173).
  admin/app/models/organization.js
  admin/app/templates/components/organization-information-section.hbs
  admin/tests/integration/components/organization-information-section-test.js
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1184 [EXPEDIT] Mauvais affichage des heures sur la liste des sessions (PA-183)
  admin/app/models/session.js
  admin/app/templates/components/routes/authenticated/sessions/list-items.hbs
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
Labels: :steam_locomotive: EXPEDIT, Func Review OK, Tech Review Needed, team-certif

#1189 [TECH] Exclure la branche master des tests sur la CI.
  .circleci/config.yml
Labels: Tech Review Needed

#1187 [FEATURE] Changer la façon de contacter le support de la page d'erreur (PF-1166).
  mon-pix/app/templates/error.hbs
Labels: Func Review Needed, Tech Review Needed, team-évaluation

#1156 [FEATURE] Permettre la ré-initialisation de mot de passe des élèves inscrit par mail (PO-339).
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/models/StudentWithUserInfo.js
  api/lib/domain/usecases/find-organization-students-with-users-infos.js
  api/lib/domain/usecases/find-organization-students.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-student-dependent-user-password.js
  api/lib/infrastructure/repositories/student-repository.js
  api/lib/infrastructure/serializers/jsonapi/student-with-user-info-serializer.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/student-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/domain-builder/factory/build-student-with-user-info.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-organization-students_test.js
  api/tests/unit/domain/usecases/find-organization-students_with-users-infos-test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-with-user-info-serializer_test.js
  orga/app/styles/components/password-reset-modal.scss
  orga/app/templates/components/password-reset-window.hbs
  orga/app/templates/components/routes/authenticated/students/list-items.hbs
  orga/tests/acceptance/student-list-test.js
  orga/tests/integration/components/password-reset-window-test.js
  orga/tests/integration/components/routes/authenticated/students/list-items-test.js
  orga/tests/unit/models/student-test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-accès

#1194 [CLEANUP] Supprimer les méthodes dépréciées fromAttributes (PF-1174)
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/CertificationChallenge.js
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/integration/domain/services/user-service_test.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/application/challenges/challenge-controller_test.js
  api/tests/unit/domain/models/Answer_test.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/usecases/get-correction-for-answer_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
Labels: Func Review OK, Tech Review Needed

#1168 [TECH] Ajout d'un composant permettant de représenter le pourcentage de succès (PO-366).
  orga/app/components/routes/authenticated/campaigns/details/collective-results/success-indicator.js
  orga/app/styles/app.scss
  orga/app/styles/globals/colors.scss
  orga/app/styles/pages/authenticated/campaigns/details/collective-results/success-indicator.scss
  orga/app/templates/components/routes/authenticated/campaigns/details/collective-results/success-indicator.hbs
  orga/tests/integration/components/routes/authenticated/campaigns/details/collective-results/success-indicator-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-prescription

#1171 [BUGFIX] Permettre la connexion aux utilisateurs dont un des memberships a été supprimé (PO-376).
  api/db/seeds/data/po376-builder.js
  api/db/seeds/seed.js
  orga/app/controllers/terms-of-service.js
  orga/app/services/current-user.js
  orga/tests/acceptance/terms-of-service-test.js
  orga/tests/unit/services/current-user-test.js
Labels: Tech Review Needed, team-accès

#1178 [TECH] Renforcer la contrainte d'unicité entre un assessment et un certification-course dans la table Assessments (PF-1161)
  api/db/migrations/20200317112058_add_unique_constraint_on_userid_certificationcourseid_table_assessments.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1179 [FEATURE] Gérer la localisation des acquis francophone ou franco-français (PF-1035).
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/constants.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/services/pick-challenge-service.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/get-next-challenge-for-smart-placement.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/caches/RedisCache.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/utils/request-response-utils.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-locale-management.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/fixtures/infrastructure/challengeAirtableDataObjectFixture.js
  api/tests/tooling/fixtures/infrastructure/challengeRawAirTableFixture.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/services/pick-challenge-service_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-smart-placement_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/utils/request-response-utils_test.js
  mon-pix/app/adapters/application.js
  mon-pix/app/services/current-domain.js
  mon-pix/tests/unit/adapters/application-test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#1188 [DESIGN-SYSTEM] Uniformisation des couleurs (CERTIF) (PF-1163)
  certif/app/styles/app.scss
  certif/app/styles/components/ember-cli-notifications-ie-fallback.scss
  certif/app/styles/components/finalize.scss
  certif/app/styles/components/login-form.scss
  certif/app/styles/components/session-finalization-examiner-global-comment-step.scss
  certif/app/styles/components/session-finalization-formbuilder-link-step.scss
  certif/app/styles/components/session-finalization-reports-informations-step.scss
  certif/app/styles/components/session-finalization-step-container.scss
  certif/app/styles/globals/app-modal.scss
  certif/app/styles/globals/colors.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/globals/panels.scss
  certif/app/styles/globals/tables.scss
  certif/app/styles/globals/texts.scss
  certif/app/styles/globals/titles.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/app/styles/pages/authenticated/terms-of-service.scss
  certif/app/styles/pages/login.scss
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-certif

#1174 [BUGFIX] Bloquer l'inscription si le formulaire n'est pas valide (PO-381).
  api/lib/domain/usecases/create-user.js
  api/lib/domain/validators/user-validator.js
  api/lib/interfaces/jsonapi/unprocessable-entity-error.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/domain/validations/user-validator_test.js
  api/tests/unit/interfaces/jsonapi/unprocessable-entity-error-test.js
  orga/app/components/routes/register-form.js
  orga/app/templates/components/routes/register-form.hbs
  orga/tests/integration/components/routes/register-form-test.js
Labels: Tech Review Needed, team-accès

#1195 [BUGFIX] Publication des certif par session KO dans Pix Admin (pa-184)
  admin/app/components/certification-list-checkbox.js
  admin/app/components/certification-list.js
  admin/app/controllers/authenticated/certifications/sessions/info/list.js
  admin/app/controllers/authenticated/certifications/single/info.js
  admin/app/models/session.js
  admin/app/templates/authenticated/certifications/sessions/info/list.hbs
  admin/app/templates/authenticated/certifications/single/info.hbs
  admin/app/templates/components/certification-list-checkbox.hbs
  admin/app/templates/components/certification-list-select-all.hbs
  admin/tests/unit/controllers/authenticated/certifications/sessions/info/list-test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1202 [CLEANUP] Retrait d'un .only oublié dans les tests PixAdmin (PA-185)
  admin/tests/unit/controllers/authenticated/certifications/sessions/info/list-test.js
Labels: Tech Review Needed

#1201 [TECH] Ajout de tests E2E sur Pix Orga (PO-383).
  high-level-tests/e2e/cypress/fixtures/answers.json
  high-level-tests/e2e/cypress/fixtures/assessments.json
  high-level-tests/e2e/cypress/fixtures/campaign-participations.json
  high-level-tests/e2e/cypress/fixtures/knowledge-elements.json
  high-level-tests/e2e/cypress/fixtures/target-profiles.json
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/integration/campaign-management.feature
  high-level-tests/e2e/cypress/integration/campaign.feature
  high-level-tests/e2e/cypress/integration/demo.feature
  high-level-tests/e2e/cypress/integration/login-logout-app.feature
  high-level-tests/e2e/cypress/integration/login-logout-orga.feature
  high-level-tests/e2e/cypress/integration/organization-management.feature
  high-level-tests/e2e/cypress/plugins/index.js
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/collective-results-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/participants-tab.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
Labels: :rocket: Ready to Merge, Tech Review OK, team-accès, team-prescription

#1198 [BUGFIX] Des utilisateurs avaient un succès pour un niveau pas encore atteint (PF-1171).
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Labels: Func Review OK, Tech Review OK, team-évaluation

#1182 [TECH] Création d'une route healthcheck/redis pour brancher Datadog et Freshping.
  api/lib/application/healthcheck/healthcheck-controller.js
  api/lib/application/healthcheck/index.js
  api/lib/infrastructure/caches/DistributedCache.js
  api/lib/infrastructure/caches/RedisCache.js
  api/lib/infrastructure/repositories/healthcheck-repository.js
  api/lib/infrastructure/utils/RedisClient.js
  api/lib/infrastructure/utils/redis-monitor.js
  api/tests/acceptance/application/healthcheck-controller_test.js
  api/tests/integration/application/healthcheck/index_test.js
  api/tests/unit/application/healthcheck/healthcheck-controller_test.js
  api/tests/unit/application/healthcheck/index_test.js
Labels: Tech Review Needed

#1186 [BUGFIX] Harmoniser le calcul de pourcentage de progression d'un candidat sur une campagne (PO-325)
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/services/campaign-participation-service.js
  api/lib/domain/usecases/start-writing-campaign-results-to-stream.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/services/campaign-participation-service_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  orga/app/helpers/.gitkeep
  orga/app/helpers/percentage.js
  orga/app/models/campaign-participation-result.js
  orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs
  orga/tests/integration/components/routes/authenticated/campaigns/details/participants/results-item-test.js
  orga/tests/unit/helpers/percentage-test.js
  orga/tests/unit/models/campaign-participation-result-test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1197 [BUGFIX] La touche "Entrée" n'est pas prise en compte dans les questions à réponses multiples (PF-1176).
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/templates/components/challenge-actions.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK

#1206 [DOC] Ajouter la section de test dans le template de PR.
  docs/pull_request_template.md
Labels: Tech Review OK, team-accès, team-certif, team-prescription, team-évaluation

#1196 [FEATURE] Ajouter un bouton de documentation qui pointe vers un lien différent en fonction du type de centre de certification (PC-136)
  api/db/seeds/data/certification/certification-center-memberships-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/db/seeds/data/certification/users.js
  api/lib/domain/usecases/create-certification-center-membership.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-membership-serializer.js
  api/tests/acceptance/application/users/users-controller-get-certification-center-memberships_test.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-membership-serializer_test.js
  certif/app/authenticators/oauth2.js
  certif/app/controllers/authenticated.js
  certif/app/models/certification-center.js
  certif/app/services/current-user.js
  certif/app/styles/pages/authenticated.scss
  certif/app/templates/authenticated.hbs
  certif/tests/acceptance/authentication-test.js
  certif/tests/unit/controllers/authenticated-test.js
Labels: Design Review OK, Func Review OK, Tech Review OK, team-certif

#1200 [FEATURE] Modifier le message d'erreur générique lors d'un import SIECLE en ajoutant un lien vers le formulaire du centre d'aide (PO-388).
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/tests/acceptance/application/organizations/organization-controller-import-students_test.js
  orga/app/controllers/authenticated/students/list.js
  orga/app/styles/globals/errors.scss
  orga/mirage/config.js
  orga/tests/acceptance/student-list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1181 [BUGFIX] Les certificats dont le test de certif n'était pas fini par le candidat mais examiné et publié par le pôle certif n'était pas visible par le candidat dans son espace de certificats (PF-1118)
  api/lib/infrastructure/data/certification-course.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1205 [TECH] Ajouter la possibilité d'avoir un type de campagne (PO-389).
  api/db/migrations/20200320170707_add-type-to-campaign.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js
  api/tests/tooling/database-builder/factory/build-campaign.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/domain/models/CampaignParticipation_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/create-assessment-for-campaign_test.js
  api/tests/unit/domain/usecases/find-smart-placement-assessments_test.js
  api/tests/unit/domain/usecases/get-assessment_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js
  high-level-tests/e2e/cypress/fixtures/campaigns.json
  orga/app/models/campaign.js
  orga/app/styles/pages/authenticated/campaigns/details.scss
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/tests/acceptance/campaign-details-test.js
  orga/tests/unit/models/campaign-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#1212 [TECH] Ajout d'une gestion de droits à la fonctionnalité de campagne de récupération profils (PO-390).
  admin/app/components/organization-information-section.hbs
  admin/app/components/organization-information-section.js
  admin/app/models/organization.js
  admin/tests/integration/components/organization-information-section-test.js
  api/db/migrations/20200324101353_add-can-collect-profiles-to-organization.js
  api/db/seeds/data/dragon-and-co-builder.js
  api/db/seeds/data/organizations-builder.js
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/tooling/database-builder/factory/build-organization.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
  orga/app/models/organization.js
Labels: Func Review Needed, Tech Review Needed, team-prescription

#1204 [FEATURE] Ajouter une colonne dans la liste des sessions pour indiquer le type du centre de certification associé (PA-175)
  admin/app/components/routes/authenticated/organizations/list-items.js
  admin/app/components/routes/authenticated/sessions/list-items.js
  admin/app/components/sessions/list-items.hbs
  admin/app/controllers/authenticated/certification-centers/list.js
  admin/app/controllers/authenticated/organizations/list.js
  admin/app/controllers/authenticated/sessions/list.js
  admin/app/controllers/authenticated/users/list.js
  admin/app/models/certification-center.js
  admin/app/models/session.js
  admin/app/models/target-profile.js
  admin/app/routes/authenticated/certification-centers/list.js
  admin/app/routes/authenticated/organizations/list.js
  admin/app/routes/authenticated/sessions/list.js
  admin/app/routes/authenticated/users/list.js
  admin/app/services/session-info-service.js
  admin/app/styles/authenticated/certifications/sessions-list.scss
  admin/app/templates/authenticated/certifications/sessions/info/index.hbs
  admin/app/templates/authenticated/sessions/list.hbs
  admin/mirage/config.js
  admin/mirage/factories/certification-center.js
  admin/mirage/factories/session.js
  admin/mirage/serializers/session.js
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
  admin/tests/unit/adapters/certification-details-test.js
  admin/tests/unit/adapters/certification-test.js
  admin/tests/unit/services/session-info-service-test.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/find-sessions-for-certification-center.js
  api/lib/infrastructure/data/session.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/tooling/database-builder/factory/build-certification-candidate.js
  api/tests/unit/domain/usecases/find-sessions-for-certification-center_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Labels: Func Review OK, Tech Review Needed, team-certif

#1213 [CLEANUP] Ajouter les couleurs et les styles de titres du design system à PixApp (PF-1181).
  mon-pix/app/styles/components/_learning-more-tutorial-panel.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/globals/_titles.scss
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/app/templates/components/learning-more-panel.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
Labels: Func Review OK, Tech Review OK, team-évaluation

#1219 [TECH] Ajout d'une règle de linter pour éviter les injections SQL
  api/.eslintrc.yaml
  api/db/knex-database-connection.js
  api/db/migrations/.eslintrc.yaml
  api/db/seeds/.eslintrc.yaml
Labels: Tech Review OK, team-accès, team-certif, team-prescription, team-évaluation

#1166 [FEATURE] Ajouter un tutoriel à sa liste (PF-1100).
  api/db/migrations/20200324161149_create-user-tutorials.js
  api/lib/application/tutorials/index.js
  api/lib/application/tutorials/tutorials-controller.js
  api/lib/domain/usecases/add-tutorial-to-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/data/user-tutorials.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/lib/infrastructure/repositories/user-tutorial-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-tutorial-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/tutorials/tutorials-controller_test.js
  api/tests/integration/infrastructure/repositories/user-tutorial-repository_test.js
  api/tests/tooling/database-builder/factory/build-user-tutorial.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/unit/application/tutorials/index_test.js
  api/tests/unit/application/tutorials/tutorials-controller_test.js
  api/tests/unit/domain/usecases/add-tutorial-to-user_test.js
  api/tests/unit/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-tutorial-serializer_test.js
  mon-pix/app/adapters/user-tutorial.js
  mon-pix/app/components/navbar-burger-menu.js
  mon-pix/app/components/tutorial-item.js
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/models/user-tutorial.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/components/_tutorial-item-on-scorecard.scss
  mon-pix/app/styles/components/_tutorial-item.scss
  mon-pix/app/styles/globals/_titles.scss
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/app/templates/components/tutorial-item-on-scorecard.hbs
  mon-pix/app/templates/components/tutorial-item.hbs
  mon-pix/app/templates/user-tutorials.hbs
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/competences-details-test.js
  mon-pix/tests/acceptance/save-tutorial-test.js
  mon-pix/tests/helpers/create-glimmer-component.js
  mon-pix/tests/integration/components/scorecard-details-test.js
  mon-pix/tests/integration/components/tutorial-item-on-scorecard-test.js
  mon-pix/tests/integration/components/tutorial-panel-test.js
  mon-pix/tests/unit/adapters/user-tutorial-test.js
  mon-pix/tests/unit/components/tutorial-item-test.js
  mon-pix/tests/unit/models/user-tutorial-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-évaluation

#1216 [BUGFIX] Des utilisateurs sont bloqués sur une épreuve. (PF-1187).
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Labels: :steam_locomotive: EXPEDIT, Func Review OK, Tech Review OK, team-évaluation

#1221 [BUGFIX] Mauvaise notification d'erreur lors de l'échec de l'ajout unitaire de candidat sur PixCertif (PC-139)
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/tests/acceptance/session-candidates-test.js
  certif/tests/acceptance/session-finalization-test.js
  certif/tests/test-helper.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1214 [INFRA] Retrait du feature toggle FT_IS_SESSION_FINALIZATION_ACTIVE (PC-137)
  certif/app/adapters/application.js
  certif/app/adapters/certification-candidate.js
  certif/app/adapters/certification-report.js
  certif/app/adapters/session.js
  certif/app/app.js
  certif/app/components/login-form.js
  certif/app/components/session-finalization-formbuilder-link-step.js
  certif/app/components/session-finalization-reports-informations-step.js
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/controllers/authenticated/sessions/list.js
  certif/app/controllers/authenticated/sessions/new.js
  certif/app/controllers/authenticated/sessions/update.js
  certif/app/routes/application.js
  certif/app/routes/authenticated.js
  certif/app/routes/authenticated/index.js
  certif/app/routes/authenticated/sessions/details.js
  certif/app/routes/authenticated/sessions/details/certification-candidates.js
  certif/app/routes/authenticated/sessions/finalize.js
  certif/app/routes/authenticated/sessions/list.js
  certif/app/routes/authenticated/sessions/new.js
  certif/app/routes/authenticated/sessions/update.js
  certif/app/routes/login.js
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/app/templates/authenticated/sessions/list.hbs
  certif/config/environment.js
  certif/tests/acceptance/session-details-test.js
  certif/tests/acceptance/session-list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1223 [CLEANUP] Suppression des scripts de gestion des releases.
  package.json
  scripts/release/common.sh
  scripts/release/deploy.sh
  scripts/release/get-pull-requests-to-release-in-prod.js
  scripts/release/publish.sh
  scripts/tests/get-pull-requests-to-release-in-prod_test.js
Labels: Tech Review Needed

#1222 [INFRA] Réduit le temps de disparition de la notification pendant les tests d'acceptance (PO-396)
  orga/tests/test-helper.js
Labels: Tech Review OK, team-prescription

#1220 [INFRA] Mise à jour des dépendances sur Pix Certif, édition Mars 2020 (PC-138)
  certif/ember-cli-build.js
  certif/package-lock.json
  certif/package.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1228 [BUGFIX] Faire en sorte que le logo de Pix Orga ne soit pas déformé sous IE (PO-289).
  orga/app/styles/pages/login.scss
  orga/app/templates/login.hbs
Labels: Func Review OK, Tech Review OK, team-accès

#1230 [BUFIX] Problème d'affichage d'une équipe avec beaucoup de membres. (PO-323).
  orga/app/styles/pages/authenticated/team/list.scss
Labels: Func Review OK, Tech Review OK, team-accès

#1227 [BUGFIX] Ne pas afficher une bande blanche en bas des CGUs de PixCertif (PC-80)
  certif/app/styles/app.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/styles/pages/authenticated/terms-of-service.scss
  certif/app/styles/pages/login.scss
Labels: Func Review Needed, Tech Review Needed, team-certif

#1215 [FEATURE] Pouvoir rattacher des profils cibles à une organisation dans Pix Admin (PA-167).
  admin/app/components/organization-members-section.hbs
  admin/app/components/organization-target-profiles-section.hbs
  admin/app/controllers/authenticated/organizations/get.js
  admin/app/models/organization.js
  admin/app/models/target-profile.js
  admin/app/styles/authenticated/organizations/get.scss
  admin/app/templates/authenticated/organizations/get.hbs
  admin/mirage/config.js
  admin/mirage/handlers/target-profiles.js
  admin/mirage/serializers/organization.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/organization-memberships-management-test.js
  admin/tests/acceptance/organization-target-profiles-management-test.js
  admin/tests/integration/components/organization-target-profiles-section-test.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/attach-target-profiles-to-organization.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/repositories/target-profile-share-repository.js
  api/scripts/add-target-profile-shares-to-organizations.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-share-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/attach-target-profiles-to-organization_test.js
  api/tests/unit/scripts/add-target-profile-shares-to-organizations_test.js
Labels: Func Review OK, Tech Review OK, team-prescription

#1217 [FEATURE] Cacher les détails pour les campagnes de récupération de profils (PO-391).
  api/db/seeds/data/campaigns-builder.js
  orga/app/models/campaign.js
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs
  orga/tests/acceptance/campaign-details-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details-item-test.js
  orga/tests/integration/components/routes/authenticated/campaigns/details/parameters-tab-test.js
  orga/tests/unit/models/campaign-test.js
Labels: Func Review Needed, Tech Review Needed, team-prescription

#1229 [BUGFIX] Numéro de session dans la barre de recherche incohérent avec la page affichée (PA-191)
  admin/app/controllers/authenticated/sessions/session.js
  admin/app/routes/authenticated/sessions/session.js
  admin/app/templates/authenticated/sessions/session.hbs
  admin/tests/acceptance/session-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#1226 [BSR] Script send-invitations-to-sco-organizations - Supprimer les appels HTTP (PF-1192).
  api/lib/infrastructure/data/membership.js
  api/scripts/helpers/csvHelpers.js
  api/scripts/send-invitations-to-sco-organizations.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/unit/scripts/send-invitations-to-sco-organizations_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-accès

#1183 [FEATURE] Accéder à une campagne Pix Emploi (PF-837)
  api/db/migrations/20200317151424_create-badge-partner-competences.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/BadgePartnerCompetence.js
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/models/Competence.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/domain/usecases/start-writing-campaign-results-to-stream.js
  api/lib/infrastructure/data/badge-partner-competence.js
  api/lib/infrastructure/data/badge.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/tooling/database-builder/factory/build-badge-partner-competence.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-badge-partner-competence.js
  api/tests/tooling/domain-builder/factory/build-badge.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-result.js
  api/tests/tooling/domain-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
  api/tests/unit/infrastructure/repositories/competence-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  mon-pix/app/models/campaign-participation-result.js
  mon-pix/app/models/partner-competence-result.js
  mon-pix/app/templates/campaigns/skill-review.hbs
  mon-pix/mirage/serializers/campaign-participation-result.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/unit/models/campaign-participation-result-test.js
  mon-pix/tests/unit/models/partner-competence-result-test.js
Labels: Func Review Needed, Tech Review Needed, team-certif, team-évaluation

#1238 [BUGFIX] [EXPEDITE] Correction de l'affichage des boutons sur la page de détails d'une campagne (PO-402).
  orga/app/models/campaign.js
  orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
  orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs
Labels: :rocket: Ready to Merge, :steam_locomotive: EXPEDIT, Func Review OK, Tech Review OK, team-prescription
