Repository 1024pix/pix, pull requests merged in 2021-09, with the labels that each got.

#3426 [FEATURE] Ajout du endpoint pour l'abandon d'une certification (pix-3063)
  api/db/database-builder/factory/build-certification-course.js
  api/db/migrations/20210831140352_add_certification-courses_abort-reason.js
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/application/certification-courses/index.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/usecases/abort-certification-course.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/package.json
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/integration/domain/usecases/abort-certification-course_test.js
  api/tests/tooling/domain-builder/factory/build-certification-course.js
  api/tests/unit/domain/models/CertificationCourse_test.js
  api/tests/unit/domain/usecases/abort-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3421 [CLEANUP] Refonte UX de l'affichage des signalement dans Pix Admin (PIX-3088)
  admin/app/components/certification/certification-issue-report.hbs
  admin/app/components/certification/certification-issue-reports.hbs
  admin/app/styles/app.scss
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/styles/components/certification-issue-report.scss
  admin/app/styles/components/certification-issue-reports.scss
  admin/app/styles/globals/fonts.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3431 [BUGFIX] Le titre de la page d'épreuve n'était pas mise à jour en cas de timeout.
  mon-pix/app/templates/assessments/challenge.hbs
Labels: :rocket: Ready to Merge, team-evaluation

#3423 [TECH] Activer à chaud la validation de l'adresse e-mail sur Pix App (PIX-3121).
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  mon-pix/app/components/user-account-connexion-methods.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/styles/pages/_connexion-methods.scss
  mon-pix/app/templates/components/user-account-connexion-methods.hbs
  mon-pix/tests/integration/components/user-account-connexion-methods_test.js
  mon-pix/tests/unit/services/feature-toggles_test.js
Labels: :rocket: Ready to Merge, team-acces

#3397 [INFRA] Aligner Pix Certif avec les composants Pix UI (PIX-3013)
  certif/app/components/action-button.hbs
  certif/app/components/add-student-list.hbs
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/certification-candidates-sco.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/import-candidates.hbs
  certif/app/components/issue-report-modal/add-issue-report-modal.hbs
  certif/app/components/issue-report-modal/issue-reports-modal.hbs
  certif/app/components/login-form.hbs
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/no-session-panel.hbs
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/styles/components/add-issue-report-modal.scss
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/globals/app-modal.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/globals/panels.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/styles/pages/authenticated/sessions.scss
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/app/styles/pages/authenticated/terms-of-service.scss
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/app/templates/authenticated/sessions/list.hbs
  certif/app/templates/authenticated/sessions/new.hbs
  certif/app/templates/authenticated/sessions/update.hbs
  certif/app/templates/terms-of-service.hbs
  certif/tests/acceptance/terms-of-service_test.js
  certif/tests/integration/components/action-button_test.js
  certif/tests/integration/components/issue-report-modal/issue-report-modal_test.js
  certif/tests/integration/components/login-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, cross-team

#3419 [FEATURE] Ne récupérer que la dernière participation d'une campagne pour chaque utilisateur dans l'onglet analyse (partie compétences) (PIX-2966).
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/tests/integration/infrastructure/repositories/campaign-collective-result-repository_test.js
  orga/app/components/campaign/analysis/competences.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3418 [A11Y] Donner plus de sémantique à la page paramètre de la campage (PIX-3055)
  orga/app/components/campaign/header/title.hbs
  orga/app/components/campaign/settings.hbs
  orga/app/components/layout/sidebar.hbs
  orga/app/styles/components/campaign/header/title.scss
  orga/app/styles/components/campaign/settings.scss
  orga/app/styles/globals/panels.scss
  orga/app/styles/globals/texts.scss
  orga/app/templates/authenticated/campaigns/campaign.hbs
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3439 [BUGFIX] Eviter les dépassements mémoire lors de finalisation de session avec beaucoup de candidats (PIX-3136)
  api/lib/domain/events/handle-auto-jury.js
  certif/app/templates/authenticated/sessions/details/parameters.hbs
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#3440 [A11Y] Amélioration de l'accessibilité de la tooltip des épreuves "focus" (PIX-3073).
  mon-pix/app/components/challenge/statement/tooltip.hbs
  mon-pix/app/styles/components/_tooltip.scss
  mon-pix/tests/integration/components/challenge/statement/focused-tooltip_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3425 [FEATURE] Afficher le message d'alerte des focus via le clavier (PIX-3074).
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/tests/acceptance/challenge-item_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3370 [FEATURE] Afficher un graphique de répartition par résultat pour les campagnes sans palier (PIX-2894).
  api/lib/application/campaigns/campaign-stats-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/usecases/get-participations-count-by-mastery-rate.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-participations-stats-repository.js
  api/lib/infrastructure/serializers/jsonapi/participations-count-by-mastery-rate.js
  api/tests/acceptance/application/campaign-stats/campaign-stats-get-participations-count-by-mastery-rate_test.js
  api/tests/integration/infrastructure/repositories/campaign-participations-stats-repository_test.js
  api/tests/test-helper.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/domain/usecases/get-participations-count-by-mastery-rate_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participations-count-by-mastery-rate_test.js
  orga/app/adapters/campaign-stats.js
  orga/app/components/campaign/charts/participants-by-mastery-percentage-loader.hbs
  orga/app/components/campaign/charts/participants-by-mastery-percentage.hbs
  orga/app/components/campaign/charts/participants-by-mastery-percentage.js
  orga/app/components/campaign/charts/result-distribution.hbs
  orga/app/styles/components/campaign/charts/participants-by-mastery-percentage.scss
  orga/app/styles/components/campaign/index.scss
  orga/app/styles/pages/authenticated/campaigns/details/assessment-results.scss
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
  orga/mirage/config.js
  orga/tests/acceptance/campaign-assessment-results_test.js
  orga/tests/integration/components/campaign/charts/participants-by-mastery-percentage_test.js
  orga/tests/integration/components/campaign/charts/result-distribution_test.js
  orga/tests/unit/adapters/campaign-stats_test.js
  orga/tests/unit/components/campaign/charts/participants-by-mastery-percentage_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3416 [BUGFIX] Rediriger vers l'organisation rejointe au moment d'accepter l'invitation (PIX-3109).
  api/lib/domain/usecases/accept-organization-invitation.js
  api/lib/domain/usecases/create-or-update-user-orga-settings.js
  api/lib/infrastructure/repositories/user-orga-settings-repository.js
  api/tests/acceptance/application/organization-invitation-controller_test.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/unit/domain/usecases/accept-organization-invitation_test.js
  api/tests/unit/domain/usecases/create-or-update-user-orga-settings_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3408 [TECH] Création du scénario Inscription et page Profil dans Pix Load-Testing (PIX-3114).
  high-level-tests/load-testing/package.json
  high-level-tests/load-testing/scenarios/signup-and-profil.yml
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3438 [BUGFIX] Corriger la méthode app.services.url.homeUrl dans Pix Orga (PIX-3134).
  orga/app/services/url.js
  orga/tests/unit/services/url_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces, team-prescription

#3435 [TECH] Encapsuler les requêtes BDD dans une transaction lors du partage d'une participation (PIX-3093).
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/domain/usecases/share-campaign-result.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/knowledge-element-snapshot-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-snapshot-repository_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3380 [TECH] Remplacer les plugins good, good-console, good-squeeze qui ont été dépréciées par hapi-pino (Pix-3051).
  api/lib/application/pre-response-utils.js
  api/lib/config.js
  api/lib/infrastructure/logger.js
  api/lib/plugins.js
  api/package-lock.json
  api/package.json
  api/server.js
  api/tests/unit/application/pre-response-utils_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3433 [TECH] Améliorer l'accessibilité de la navigation et des tooltip dans Pix Orga (PIX-2955)
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  orga/app/components/campaign/badges.hbs
  orga/app/components/campaign/charts/participants-by-stage-bar.hbs
  orga/app/components/campaign/charts/participants-by-stage.hbs
  orga/app/components/campaign/charts/participants-by-status.hbs
  orga/app/components/campaign/copy-paste-button.hbs
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/stage-stars.hbs
  orga/app/components/dropdown/item.hbs
  orga/app/components/dropdown/item.js
  orga/app/components/layout/organization-credit-info.hbs
  orga/app/components/layout/topbar.hbs
  orga/app/components/layout/user-logged-menu.hbs
  orga/app/components/student/sco/manage-authentication-method-modal.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/styles/components/campaign/stage-stars.scss
  orga/app/styles/components/dropdown.scss
  orga/app/styles/components/indicator-card.scss
  orga/app/styles/components/layout/organization-credit-info.scss
  orga/app/styles/components/layout/topbar.scss
  orga/app/styles/components/layout/user-logged-menu.scss
  orga/app/styles/globals/forms.scss
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/authentication_test.js
  orga/tests/acceptance/join_test.js
  orga/tests/acceptance/switch-organization_test.js
  orga/tests/helpers/contains.js
  orga/tests/integration/components/campaign/results/assessment-list_test.js
  orga/tests/integration/components/layout/user-logged-menu_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3436 [BUGFIX] Créer la base de données lors de la configuration du repo.
  api/scripts/PgClient.js
  api/scripts/database/create-database.js
  api/scripts/database/drop-database.js
  api/scripts/delete-assessment.js
  api/scripts/delete-user.js
  scripts/configure.sh
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#3424 [FEATURE] Sauvegarder la dernière date de connexion dans la table users (PIX-2736).
  api/db/migrations/20210831124754_add-last-logged-at-column-in-users-table.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team

#3441 [A11Y] Utiliser des balises HTML sémantiques dans la page "Activité" de Pix Orga (PIX-3056).
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/campaign/activity/dashboard.hbs
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/charts/participants-by-status-loader.hbs
  orga/app/components/campaign/charts/participants-by-status.hbs
  orga/app/components/campaign/empty-state.hbs
  orga/app/components/campaign/header/title.hbs
  orga/app/components/layout/sidebar.hbs
  orga/app/components/ui/chart-card.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/styles/components/campaign/charts/participants-by-status.scss
  orga/app/styles/components/campaign/header/tabs.scss
  orga/app/styles/components/indicator-card.scss
  orga/app/styles/pages/authenticated/campaigns/details/activity.scss
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3365 [TECH] Migrer la colonne knowledge_elements.id de INTEGER en BIG INTEGER (partie 3).
  api/db/migrations/20210820071611_remove-integer-id-from-knowledge-elements.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3445 [FEATURE] Ajouter un titre de page spécifique pour les épreuves focus (PIX-3149).
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/tests/unit/controllers/assessments/challenge_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3451 [FEATURE] Modification des messages sur les épreuves focus (PIX-3148).
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3450 [FEATURE] Nouveau message de sortie d'épreuve focus pour la certification (PIX-3069).
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3427 [FEATURE] Afficher le commentaire jury d'une session dans Pix Admin (PIX-3130)
  admin/app/components/sessions/jury-comment.hbs
  admin/app/models/session.js
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/templates/authenticated/sessions/session.hbs
  admin/app/templates/authenticated/sessions/session/certifications.hbs
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/tests/acceptance/authenticated/sessions/session/informations_test.js
  admin/tests/integration/components/sessions/jury-comment_test.js
  api/db/database-builder/factory/build-session.js
  api/db/migrations/20210831141155_add-columns-for-session-jury-comments.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/lib/domain/models/JurySession.js
  api/lib/infrastructure/repositories/jury-session-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-session-serializer.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
  api/tests/tooling/domain-builder/factory/build-jury-session.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-session-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3405 [FEAT] Suppression du champ grisé après la fin du temps imparti sur une question timée.
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3449 [TECH] Suppression de la route GET `/campaigns/id/assessment-participations` qui est dépréciée (PIX-3161).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/models/Stage.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/read-models/CampaignAssessmentParticipationSummary.js
  api/lib/domain/usecases/find-paginated-campaign-assessment-participation-summaries.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-assessment-participation-summary-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/campaign-participations/campaign-participations-controller-find-shared-participations_test.js
  api/tests/integration/domain/usecases/find-paginated-campaign-assessment-participation-summaries_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-summary-repository_test.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/domain/models/Stage_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  api/tests/unit/domain/read-models/CampaignAssessmentParticipationSummary_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-summary-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3442 [TECH] Ajouter une colonne de statut sur la table "compaign-participations" (PIX-2998).
  api/db/migrations/20210902135810_add-status-column-on-campaign-participations.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#3454 [FEATURE] Réutiliser le champ résultat pour la page "profil déjà envoyé" sur Pix App (PIX-3124).
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/models/SharedProfileForCampaign.js
  api/lib/domain/usecases/get-user-profile-shared-for-campaign.js
  api/tests/acceptance/application/users/users-get-shared-profile-for-campaign_test.js
  api/tests/unit/domain/usecases/get-user-profile-shared-for-campaign_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3452 [FEATURE] Supprimer l'affichage de html/css dans les instructions en checkpoint (PIX-2792).
  mon-pix/app/helpers/convert-to-html.js
  mon-pix/tests/unit/helpers/convert-to-html_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3432 [FEATURE] Création du formulaire pour la validation de l'adresse e-mail sur Pix App (PIX-3120).
  mon-pix/app/components/user-account/user-account-update-email-with-validation.hbs
  mon-pix/app/components/user-account/user-account-update-email-with-validation.js
  mon-pix/app/controllers/user-account/connection-methods.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_user-account-update-email-with-validation.scss
  mon-pix/app/styles/components/_user-account.scss
  mon-pix/app/styles/pages/_connexion-methods.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/components/campaign-share-button.hbs
  mon-pix/app/templates/components/campaign-start-block.hbs
  mon-pix/app/templates/components/user-account-connexion-methods.hbs
  mon-pix/app/templates/user-account/connection-methods.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/integration/components/user-account-update-email-with-validation-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3444 [FEATURE] Les épreuves focus sont échouées en certification en cas de perte du focus (PIX-3147).
  admin/app/components/certification/certification-details-answer.js
  api/lib/application/answers/index.js
  api/lib/domain/models/Answer.js
  api/lib/domain/models/AnswerStatus.js
  api/lib/domain/models/Examiner.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/infrastructure/adapters/answer-status-database-adapter.js
  api/lib/infrastructure/adapters/answer-status-json-api-adapter.js
  api/lib/infrastructure/serializers/jsonapi/answer-serializer.js
  api/tests/tooling/domain-builder/factory/build-answer.js
  api/tests/unit/application/answers/answer-controller_test.js
  api/tests/unit/domain/models/AnswerStatus_test.js
  api/tests/unit/domain/models/Answer_test.js
  api/tests/unit/domain/models/Examiner_test.js
  api/tests/unit/infrastructure/adapters/answer-status-database-adapter_test.js
  api/tests/unit/infrastructure/adapters/answer-status-json-api-adapter_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/answer-serializer_test.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/comparison-window.js
  mon-pix/app/components/result-item.js
  mon-pix/app/models/answer.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/tests/unit/routes/assessments/challenge_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3462 [FEATURE] Modification du fichier d'import Fregata (PIX-3140)
  api/tests/unit/infrastructure/serializers/csv/schooling-registration-parser_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3430 [FEATURE] Pouvoir voir les habilitations des centres de certification aux certifications complémentaires sur leur page de détails dans PixAdmin (PIX-3128)
  admin/app/models/accreditation.js
  admin/app/models/certification-center.js
  admin/app/templates/authenticated/certification-centers/get.hbs
  admin/mirage/serializers/certification-center.js
  admin/tests/acceptance/authenticated/certification-centers/get_test.js
  api/db/database-builder/factory/build-accreditation.js
  api/db/database-builder/factory/build-accredited-badge.js
  api/db/database-builder/factory/build-granted-accreditation.js
  api/db/database-builder/factory/index.js
  api/db/migrations/20210831141356_create-accreditations-table.js
  api/db/migrations/20210831142318_create-granted-accreditations-table.js
  api/db/migrations/20210831145630_create-accredited-badges-table.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/domain/models/Accreditation.js
  api/lib/domain/models/CertificationCenter.js
  api/lib/infrastructure/orm-models/Accreditation.js
  api/lib/infrastructure/orm-models/CertificationCenter.js
  api/lib/infrastructure/orm-models/CertificationCenterMembership.js
  api/lib/infrastructure/repositories/certification-center-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-serializer.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-center-repository_test.js
  api/tests/tooling/domain-builder/factory/build-accreditation.js
  api/tests/tooling/domain-builder/factory/build-certification-center.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3447 [TECH] Identifier rapidement les problèmes de nos utilisateurs via Datadog en cherchant via leur identifiant toute requête les concernant (PIX-3153).
  api/db/knex-database-connection.js
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/lib/infrastructure/http/http-agent.js
  api/lib/infrastructure/monitoring-tools.js
  api/lib/plugins.js
  api/server.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3457 [FEATURE] Changer le status de la participation au partage (PIX-3139)
  api/lib/domain/models/CampaignParticipation.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/unit/domain/models/CampaignParticipation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3455 [FEATURE][A11Y] Utiliser des balises HTML sémantiques dans la page "Résultats" et "Résultat individuel" de Pix Orga (PIX-3057).
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/campaign/charts/participants-by-stage-bar.hbs
  orga/app/components/campaign/charts/participants-by-stage.hbs
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/assessment/results.hbs
  orga/app/components/participant/profile/header.hbs
  orga/app/components/participant/profile/table.hbs
  orga/app/components/ui/pix-loader.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/charts/participants-by-stage.scss
  orga/app/styles/components/login-or-register.scss
  orga/app/styles/globals/panels.scss
  orga/app/styles/globals/pix-loader.scss
  orga/app/styles/pages/authenticated/campaigns/details/assessment-results.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant/results.scss
  orga/app/styles/pages/authenticated/campaigns/details/profile-results.scss
  orga/app/styles/pages/authenticated/campaigns/participant-profile.scss
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
  orga/app/templates/authenticated/campaigns/campaign/profile-results.hbs
  orga/tests/integration/components/participant/assessment/results_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3467 [BUGFIX] L'affichage du code d'une campagne se fait sur deux lignes (PIX-2858).
  orga/app/components/campaign/header/title.hbs
  orga/app/styles/components/campaign/header/title.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3465 [TECH] Ajour des variables CSS de Pix-ui (PIX-3186)
  certif/app/styles/app.scss
  certif/app/styles/components/add-issue-report-modal.scss
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/components/certification-candidate-details-modal.scss
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/app/styles/globals/colors.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/pages/authenticated/sessions/add-student.scss
  certif/app/styles/pages/authenticated/terms-of-service.scss
  certif/app/styles/pages/login.scss
  certif/ember-cli-build.js
Labels: :rocket: Ready to Merge, team-certif, Design Review OK

#3471 [TECH] Création d'un utilitaire générateur de code aléatoire numérique (PIX-3122).
  api/lib/infrastructure/temporary-storage/InMemoryTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/TemporaryStorage.js
  api/lib/infrastructure/utils/code-utils.js
  api/tests/unit/infrastructure/temporary-storage/InMemoryTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/TemporaryStorage_test.js
  api/tests/unit/infrastructure/utils/code-utils_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3466 [BUGFIX] Ne plus avoir l'écran grisé sur des épreuves focus (PIX-3167).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge/item.hbs
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/templates/assessments/challenge.hbs
Labels: :rocket: Ready to Merge, team-evaluation

#3453 [FEATURE][A11Y] Utiliser des balises HTML sémantiques dans la page "Analyse" de Pix Orga (PIX-3058).
  orga/app/components/campaign/analysis/competences.hbs
  orga/app/components/campaign/analysis/recommendations.hbs
  orga/app/styles/components/campaign/analysis/recommendations.scss
  orga/app/styles/components/campaign/analysis/tube-recommendation-row.scss
  orga/app/styles/globals/competences.scss
  orga/app/templates/authenticated/campaigns/campaign/analysis.hbs
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3463 [FEATURE] Marquer la participation "STARTED" au moment du "retenter". (PIX-3155)
  api/db/database-builder/factory/build-campaign-participation.js
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/usecases/begin-campaign-participation-improvement.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/tests/integration/domain/usecases/begin-campaign-participation-improvement.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/models/CampaignParticipation_test.js
  api/tests/unit/domain/usecases/begin-campaign-participation-improvement_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3443 [TECH] Réutiliser le champ résultat pour la page "résultats" sur Pix App(PIX-3123)
  api/lib/domain/constants.js
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/read-models/participant-results/ReachedStage.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-campaign-assessment-result_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/read-models/participant-results/ReachedStage_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign-participation-result.js
  mon-pix/app/templates/components/reached-stage.hbs
  mon-pix/mirage/serializers/campaign-participation-result.js
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/integration/components/reached-stage_test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3472 [FEATURE] Minimiser le nombre d'appels lors de la recherche dans les composants Pix Admin (PIX-3116).
  admin/config/environment.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3456 [TECH] Corréler et enrichir la sortie de log Hapi d'un appel API avec des métriques concernant les queries Knex associées (PIX-3168).
  api/db/knex-database-connection.js
  api/lib/config.js
  api/lib/infrastructure/monitoring-tools.js
  api/lib/plugins.js
  api/server.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3468 [FEATURE] Indiquer à l'utilisateur qu'il est sorti d'une épreuve Focus en certification (PIX-3075).
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3458 [TECH] Mesurer les temps de réponses API des appels externes à Pix via un métrique duration (PIX-3171).
  api/lib/infrastructure/http/http-agent.js
  api/lib/infrastructure/monitoring-tools.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3475 [BUGFIX] Le bloc d'alerte de sorti d'épreuve focus ne doit pas bloquer l'utilisation de certains boutons (PIX-3179).
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/tests/acceptance/challenge-item_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3473 [TECH] Monter de version caniuse-lite
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team

#3478 [BUGFIX] La notification de passage de niveau doit cacher le bouton Quitter (PIX-3176).
  mon-pix/app/styles/components/_levelup-notif.scss
Labels: :rocket: Ready to Merge, team-evaluation

#3477 [INFRA] Ajouter des helpers de tests getByLabel et queryByLabel à Pix Admin
  admin/tests/acceptance/organization-information-management_test.js
  admin/tests/helpers/extended-ember-test-helpers/click-by-label.js
  admin/tests/helpers/extended-ember-test-helpers/fill-in-by-label.js
  admin/tests/helpers/extended-ember-test-helpers/get-by-label.js
  admin/tests/helpers/extended-ember-test-helpers/query-by-label.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#3479 [BUGFIX] Pouvoir ajouter un élève qui est lié à un compte déjà lié à un élève de mon établissement (PIX-3447)
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#3460 [TECH] Associer un statut à un participation de campagne à la création et finalisation (PIX-3138)
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/usecases/complete-assessment.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/integration/domain/usecases/start-campaign-participation_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/domain/models/CampaignParticipation_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3474 [FEATURE] Créer une route permettant de lister les habilitations et mettre à jour l'affichage des habilitations d'un centre de certification dans Pix Admin (PIX-3174).
  admin/app/helpers/contains.js
  admin/app/routes/authenticated/certification-centers/get.js
  admin/app/styles/authenticated/certification-center/index.scss
  admin/app/templates/authenticated/certification-centers/get.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/certification-centers/get_test.js
  admin/tests/unit/helpers/contains_test.js
  api/lib/application/accreditations/accreditation-controller.js
  api/lib/application/accreditations/index.js
  api/lib/domain/usecases/find-accreditations.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/accreditation-repository.js
  api/lib/infrastructure/serializers/jsonapi/accreditation-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/accreditations/accreditations-controller_test.js
  api/tests/integration/infrastructure/repositories/accreditation-repository_test.js
  api/tests/unit/application/accreditations/index_test.js
  api/tests/unit/domain/usecases/find-accreditations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/accreditation-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3483 [BUGFIX] Ne pas afficher le warning d'écran de fin test si pas de certification terminée (PIX-3449)
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3470 [BUGFIX] Lors de l'import siecle si une archive zip contient plusieurs fichiers il y a une erreur (PIX-3177).
  api/lib/infrastructure/serializers/xml/siecle-parser.js
  api/lib/infrastructure/utils/xml/siecle-file-streamer.js
  api/tests/integration/domain/services/schooling-registrations-xml-service_test.js
  api/tests/integration/infrastructure/utils/xml/files/xml/bad.xml
  api/tests/integration/infrastructure/utils/xml/files/xml/bom.xml
  api/tests/integration/infrastructure/utils/xml/files/xml/unknown-encoding.xml
  api/tests/integration/infrastructure/utils/xml/files/xml/valid.xml
  api/tests/integration/infrastructure/utils/xml/files/zip/corrupted-entry.zip
  api/tests/integration/infrastructure/utils/xml/files/zip/empty-folder.zip
  api/tests/integration/infrastructure/utils/xml/files/zip/hidden-file.zip
  api/tests/integration/infrastructure/utils/xml/files/zip/several-files.zip
  api/tests/integration/infrastructure/utils/xml/files/zip/valid.zip
  api/tests/integration/infrastructure/utils/xml/siecle-file-streamer_test.js
  api/tests/tooling/fixtures/siecle-file/corrupt_entry.zip
  api/tests/tooling/fixtures/siecle-file/siecle-broken-after-uai.xml
  api/tests/tooling/fixtures/siecle-file/siecle-broken.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-bom.xml
  api/tests/tooling/fixtures/siecle-file/siecle-zipped-file.xml.zip
  api/tests/tooling/fixtures/siecle-file/template1.xml
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3481 [TECH] Migration des status de campagne participations (PIX-3000)
  api/scripts/prod/compute-participation-statuses.js
  api/tests/integration/scripts/prod/compute-participation-statuses_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3485 [TECH] Supprimer la gestion des erreurs sur les doublons d'INE dans la base de données (Pix-3189).
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/import-schooling-registrations-from-siecle.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/domain/errors_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3490 [BUGFIX] Force une valeur pour eviter un flaky test (PIX-3471)
  certif/tests/acceptance/session-finalization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, :steam_locomotive: EXPEDIT, team-certif

#3486 [TECH] Logger le dispatch de Domain Events (PIX-3175)
  api/lib/config.js
  api/lib/domain/events/index.js
  api/lib/infrastructure/events/EventDispatcher.js
  api/lib/infrastructure/events/EventDispatcherLogger.js
  api/sample.env
  api/tests/integration/infrastructure/event-dispatcher-logger_test.js
  api/tests/integration/infrastructure/event-dispatcher_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3480 [FEATURE] Distinguer les Schooling registration désactivées sur PixAdmin en utilisant la colonne 'isDisabled' (PIX-3098).
  admin/app/components/user-detail-personal-information.hbs
  admin/app/models/schooling-registration.js
  admin/app/styles/components/user-detail-personal-information-section.scss
  admin/app/styles/globals/table-admin.scss
  admin/tests/integration/components/user-detail-personal-information_test.js
  api/lib/domain/read-models/SchoolingRegistrationForAdmin.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration-for-admin.js
  api/tests/unit/domain/read-models/SchoolingRegistrationForAdmin_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3493 [CLEAN] Corrige des typos
  api/lib/application/certification-centers/index.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3482 [FEATURE] Envoyer un code de vérification par mail lors d'un changement d'adresse e-mail - API (PIX-2945).
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/send-verification-code.js
  api/lib/infrastructure/mailers/mailer.js
  api/lib/infrastructure/repositories/user-email-repository.js
  api/sample.env
  api/tests/acceptance/application/account-recovery/account-recovery-route-get_test.js
  api/tests/acceptance/application/users/send-verification-code-route-put_test.js
  api/tests/integration/infrastructure/repositories/user-email-repository_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/send-verification-code_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3495 [FEATURE] Envoyer un code de vérification par mail lors d'un changement d'adresse e-mail (PIX-3453).
  mon-pix/app/adapters/email-verification-code.js
  mon-pix/app/components/user-account/user-account-update-email-with-validation.hbs
  mon-pix/app/components/user-account/user-account-update-email-with-validation.js
  mon-pix/app/controllers/user-account/connection-methods.js
  mon-pix/app/models/email-verification-code.js
  mon-pix/app/styles/components/_user-account-update-email-with-validation.scss
  mon-pix/app/templates/user-account/connection-methods.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/user-account-update-email-with-validation-test.js
  mon-pix/tests/unit/adapters/email-verification-code-test.js
  mon-pix/tests/unit/models/email-verification-code-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3476 [FEATURE] Ajout de l'infobulle sur les épreuves non-focus (PIX-2882).
  api/db/database-builder/factory/build-user.js
  api/db/migrations/20210907094748_add-column-has-seen-other-challenges-tooltip-to-users-table.js
  api/lib/application/users/index.js
  api/lib/domain/models/User.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/remember-user-has-seen-challenge-tooltip_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/application/users/index_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/user-tutorials.feature
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mathématiques - 1ere question-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mathématiques - 2eme question-base.png
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge/item.js
  mon-pix/app/components/challenge/statement/tooltip.hbs
  mon-pix/app/components/challenge/statement/tooltip.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/models/user.js
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/certification-course_test.js
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/tests/integration/components/challenge/statement/focused-tooltip_test.js
  mon-pix/tests/integration/components/challenge/statement/tooltip_test.js
  mon-pix/tests/unit/controllers/assessments/challenge_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3501 [FEATURE] Simplifier la visibilité de l'épreuve et des tooltips (PIX-3483).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge/item.hbs
  mon-pix/app/components/challenge/item.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/tests/acceptance/challenge-item_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3488 [TECH] Refacto des requetes avec JSON_AGG (PIX-3452)
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/read-models/livret-scolaire/Certificate.js
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/lib/infrastructure/repositories/certification-result-repository.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/unit/domain/models/CertificationResult_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3499 [CLEANUP] Uniformiser les url des badges (PIX-3479).
  api/db/migrations/20210916120235_update-badges-imageUrl-to-url-with-pix-domain.js
Labels: :rocket: Ready to Merge, team-evaluation

#3491 [BUGFIX] Supprimer le double appel à getNextChallenge (PIX-2760).
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/tests/unit/routes/assessments/challenge_test.js
  mon-pix/tests/unit/routes/assessments/resume_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3511 [BUGFIX] Problème de contraste sur le bouton de texte alternatif d'une épreuve (PIX-3490).
  mon-pix/app/styles/components/_challenge-statement.scss
Labels: :rocket: Ready to Merge, team-evaluation

#3404 [BUGFIX] Vérification du timeout et du unfocus en cas de rechargement.
  api/db/database-builder/factory/build-assessment.js
  api/db/migrations/20210827153245_add-column-last-question-state-in-assessment.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/assessments/index.js
  api/lib/domain/models/Assessment.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/acceptance/application/assessments/assessment-update-last-question-state_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  mon-pix/app/adapters/assessment.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge/item.js
  mon-pix/app/components/timeout-gauge.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/models/assessment.js
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/mirage/factories/assessment.js
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/tests/acceptance/challenge-timed_test.js
  mon-pix/tests/integration/components/challenge-item-qroc_test.js
  mon-pix/tests/unit/adapters/assessment_test.js
  mon-pix/tests/unit/controllers/assessments/challenge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3498 [BUGFIX] Correction des notifications d'import SUP (PIX-3455)
  orga/app/controllers/authenticated/sup-students/import.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/sup-student-import_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3492 [TECH] Suppression des parseInt autour de request.auth.credentials.userId
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3510 [FEATURE] Ajout d'un pied de page (footer) dans Pix Orga (PIX-3487).
  orga/app/components/layout/footer.hbs
  orga/app/components/layout/footer.js
  orga/app/services/url.js
  orga/app/styles/app.scss
  orga/app/styles/components/layout/footer.scss
  orga/app/styles/components/layout/topbar.scss
  orga/app/styles/pages/authenticated.scss
  orga/app/templates/authenticated.hbs
  orga/tests/integration/components/layout/footer_test.js
  orga/tests/unit/services/url_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, Design Review OK

#3515 [FEATURE] Changement de titre de page pour les épreuves focus (PIX-3484).
  high-level-tests/e2e/cypress/integration/pix-app/page-title.feature
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3459 [FEATURE] Ajouter/modifier le commentaire jury d'une session dans Pix Admin (PIX-3131)
  admin/app/components/sessions/jury-comment.hbs
  admin/app/components/sessions/jury-comment.js
  admin/app/components/sessions/list-items.js
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/models/session.js
  admin/app/styles/app.scss
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/styles/components/sessions/jury-comment.scss
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/mirage/config.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/sessions/session/informations_test.js
  admin/tests/integration/components/sessions/jury-comment_test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/SessionJuryComment.js
  api/lib/domain/usecases/comment-session-as-jury.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/session-jury-comment-repository.js
  api/tests/acceptance/application/session/session-controller-put-comment_test.js
  api/tests/integration/infrastructure/repositories/session-jury-comment-repository_test.js
  api/tests/tooling/domain-builder/factory/build-session-jury-comment.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/SessionJuryComment.js
  api/tests/unit/domain/usecases/comment-session-as-jury_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3517 [BUGFIX] Sauvegarde l'état de la question focus seulement en cas de sortie de la fenêtre
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/mirage/routes/assessments/index.js
  mon-pix/mirage/routes/assessments/set-focusedout-state.js
Labels: :rocket: Ready to Merge, team-evaluation

#3504 [FEATURE] Ajouter une liste des badges non acquis à ceux acquis en fin de campagne (PIX-2678).
  api/db/database-builder/factory/build-badge.js
  api/db/migrations/20210917162014_add-column-visible-to-badges-table.js
  api/lib/domain/models/Badge.js
  api/lib/domain/read-models/participant-results/BadgeResult.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-campaign-assessment-result_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/tooling/domain-builder/factory/build-badge.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign-participation-badge.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_badge-card.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/components/badge-acquired-card.hbs
  mon-pix/app/templates/components/badge-card.hbs
  mon-pix/mirage/serializers/campaign-participation-badge.js
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/integration/components/badge-card_test.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3487 [FEATURE] Ne plus utiliser la colonne `isShared` des campagne participations (PIX-3144)
  api/db/database-builder/factory/build-campaign-participation.js
  api/db/seeds/data/campaign-participations-builder.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/read-models/CampaignAssessmentParticipation.js
  api/lib/domain/read-models/CampaignAssessmentParticipationResult.js
  api/lib/domain/read-models/CampaignParticipantActivity.js
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/domain/read-models/CampaignProfile.js
  api/lib/infrastructure/repositories/campaign-analysis-repository.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-repository.js
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
  api/lib/infrastructure/repositories/campaign-participant-activity-repository.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-participations-stats-repository.js
  api/lib/infrastructure/repositories/campaign-profile-repository.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/prod/compute-participation-results.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/integration/domain/usecases/begin-campaign-participation-improvement_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation.js
  api/tests/unit/domain/models/CampaignParticipation_test.js
  api/tests/unit/domain/read-models/CampaignAssessmentParticipationResult_test.js
  api/tests/unit/domain/read-models/CampaignParticipantActivity_test.js
  api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
  api/tests/unit/domain/read-models/CampaignProfile_test.js
  api/tests/unit/domain/usecases/compute-campaign-participation-analysis_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participant-activity-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-profile-serializer_test.js
  high-level-tests/e2e/cypress/fixtures/campaign-participations.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3514 [TECH] Savoir si la personne a bien répondu mais est quand même sortie (PIX-3079).
  api/db/migrations/20210920153452_add-column-focusedout-to-answers.js
  api/lib/domain/models/Answer.js
  api/lib/domain/models/Examiner.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/lib/infrastructure/serializers/jsonapi/answer-serializer.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/tooling/domain-builder/factory/build-answer.js
  api/tests/unit/domain/models/Answer_test.js
  api/tests/unit/domain/models/Examiner_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/answer-serializer_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3512 [TECH] Ajouter une Github action qui notifie les équipes sur Slack lorsque le fichier de config est modifié.
  .github/workflows/on-dev-merge.yml
Labels: :rocket: Ready to Merge, team-captains, cross-team

#3521 [BUGFIX] Le reload de la page ne doit pas faire oublié qu'on a défocus (PIX-3506).
  api/lib/application/assessments/assessment-controller.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3523 [TECH] Ajout du support pour le plugin Matomo Session Recordings
  admin/app/index.html
  admin/package.json
  certif/app/index.html
  certif/package.json
  mon-pix/app/index.html
  mon-pix/package.json
  orga/app/index.html
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3520 [FEATURE] Permettre la création de résultat thématique depuis Pix Admin 1/2 (PIX-3480).
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/usecases/create-badge.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/domain/usecases/create-badge_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3505 [FEATURE] Page de vérification de code pour un changement d'adresse e-mail (PIX-2892).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/infrastructure/serializers/jsonapi/email-verification-serializer.js
  api/tests/acceptance/application/users/send-verification-code-route-put_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/email-verification-serializer_test.js
  mon-pix/app/adapters/email-verification-code.js
  mon-pix/app/components/user-account/email-verification-code.hbs
  mon-pix/app/components/user-account/email-verification-code.js
  mon-pix/app/components/user-account/user-account-update-email-with-validation.hbs
  mon-pix/app/controllers/user-account/connection-methods.js
  mon-pix/app/models/email-verification-code.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_user-account-update-email-with-validation.scss
  mon-pix/app/styles/components/_user-account.scss
  mon-pix/app/styles/components/user-account/_email-verification-code.scss
  mon-pix/app/styles/components/user-account/_update-email-with-validation.scss
  mon-pix/app/templates/user-account/connection-methods.hbs
  mon-pix/config/environment.js
  mon-pix/mirage/config.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/user-account/connection-methods_test.js
  mon-pix/tests/acceptance/user-account_test.js
  mon-pix/tests/integration/components/user-account-update-email-with-validation-test.js
  mon-pix/tests/integration/components/user-account/email-verification-code-test.js
  mon-pix/tests/unit/adapters/email-verification-code-test.js
  mon-pix/tests/unit/controllers/user-account/connection-methods_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3484 [FEATURE] Pouvoir passer un assessment FLASH (PIX-2779).
  api/db/database-builder/factory/build-assessment.js
  api/db/database-builder/factory/build-campaign.js
  api/db/migrations/20210908085902_add-method-column-in-assessments.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/read-models/CampaignToJoin.js
  api/lib/domain/services/algorithm-methods/cat-algorithm.js
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/lib/domain/services/algorithm-methods/skills-filter.js
  api/lib/domain/services/algorithm-methods/smart-random.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/scripts/fill-in-assessment-method.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
  api/tests/integration/domain/services/algorithm-methods/smart-random_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/tooling/domain-builder/factory/build-campaign-to-join.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/services/smart-random/skills-filter_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/domain/usecases/improve-competence-evaluation_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/tests/algo_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3516 [TECH] Remplace le userId par me dans l'url certification-point-of-contacts (pix-3495)
  api/lib/application/certification-point-of-contacts/index.js
  api/tests/acceptance/application/certification-point-of-contacts/certification-point-of-contacts_test.js
  api/tests/unit/application/certification-point-of-contacts/index_test.js
  certif/app/adapters/certification-point-of-contact.js
  certif/app/services/current-user.js
  certif/mirage/config.js
  certif/tests/unit/services/current-user_test.js
  high-level-tests/e2e/cypress/support/commands.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3239 [TECH] Nommer les conteneurs Docker locaux.
  INSTALLATION.md
  docker-compose.yml
  high-level-tests/e2e/docker-compose.yml
  scripts/tests-e2e
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3519 [BUGFIX] Gérer un cas d'erreur lors d'un accès à une campagne SCO sur Pix App (PIX-3191).
  api/lib/application/error-manager.js
  api/lib/domain/constants.js
  api/lib/domain/errors.js
  api/lib/domain/services/obfuscation-service.js
  api/lib/domain/services/user-reconciliation-service.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/services/obfuscation-service_test.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sco.js
  mon-pix/app/styles/pages/_join-restricted-campaign.scss
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sco_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3518 [BUGFIX] Retirer la vérification de la ville de naissance lors de l'ajout d'un candidat SCO à une session de certification (PIX-3500)
  api/lib/domain/models/SCOCertificationCandidate.js
  api/tests/unit/domain/models/SCOCertificationCandidate_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3525 [BUGFIX] Améliorer le style de la tooltip d'explication du score Pix (PIX-3482).
  mon-pix/app/components/hexagon-score.js
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/app/templates/components/hexagon-score.hbs
  mon-pix/tests/integration/components/hexagon-score_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3524 [TECH] Mettre à jour Ember Simple Auth en 4.0.0 sur Pix App.
  mon-pix/app/adapters/application.js
  mon-pix/app/mixins/secured-route-mixin.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/campaigns/assessment/skill-review.js
  mon-pix/app/routes/campaigns/assessment/start-or-resume.js
  mon-pix/app/routes/campaigns/assessment/tutorial.js
  mon-pix/app/routes/campaigns/fill-in-participant-external-id.js
  mon-pix/app/routes/campaigns/profiles-collection.js
  mon-pix/app/routes/campaigns/profiles-collection/profile-already-shared.js
  mon-pix/app/routes/campaigns/profiles-collection/send-profile.js
  mon-pix/app/routes/campaigns/profiles-collection/start-or-resume.js
  mon-pix/app/routes/campaigns/restricted/login-or-register-to-access.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/certifications/results.js
  mon-pix/app/routes/certifications/start.js
  mon-pix/app/routes/competences.js
  mon-pix/app/routes/competences/details.js
  mon-pix/app/routes/competences/results.js
  mon-pix/app/routes/competences/resume.js
  mon-pix/app/routes/index.js
  mon-pix/app/routes/inscription.js
  mon-pix/app/routes/login.js
  mon-pix/app/routes/logout.js
  mon-pix/app/routes/not-connected.js
  mon-pix/app/routes/profile.js
  mon-pix/app/routes/sitemap.js
  mon-pix/app/routes/terms-of-service-pe.js
  mon-pix/app/routes/terms-of-service.js
  mon-pix/app/routes/update-expired-password.js
  mon-pix/app/routes/user-account.js
  mon-pix/app/routes/user-account/index.js
  mon-pix/app/routes/user-certifications/get.js
  mon-pix/app/routes/user-certifications/index.js
  mon-pix/app/routes/user-dashboard.js
  mon-pix/app/routes/user-tests.js
  mon-pix/app/services/session.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/unit/mixins/secured-route-mixin_test.js
  mon-pix/tests/unit/routes/application_test.js
  mon-pix/tests/unit/routes/login_test.js
  mon-pix/tests/unit/routes/logout_test.js
  mon-pix/tests/unit/services/session_test.js
Labels: :rocket: Ready to Merge, cross-team

#3531 [TECH] Refacto des méthodes de connexion de PixApp (PIX-3503).
  mon-pix/app/components/user-account-connexion-methods.js
  mon-pix/app/components/user-account/email-verification-code.hbs
  mon-pix/app/components/user-account/email-with-validation-form.hbs
  mon-pix/app/components/user-account/email-with-validation-form.js
  mon-pix/app/components/user-account/update-email-with-validation.hbs
  mon-pix/app/components/user-account/update-email-with-validation.js
  mon-pix/app/components/user-account/update-email.hbs
  mon-pix/app/components/user-account/update-email.js
  mon-pix/app/components/user-account/user-account-update-email-with-validation.hbs
  mon-pix/app/controllers/user-account/connection-methods.js
  mon-pix/app/routes/user-account/connection-methods.js
  mon-pix/app/styles/components/user-account/_email-verification-code.scss
  mon-pix/app/templates/components/user-account-connexion-methods.hbs
  mon-pix/app/templates/user-account/connection-methods.hbs
  mon-pix/tests/acceptance/user-account/connection-methods_test.js
  mon-pix/tests/integration/components/user-account-connexion-methods_test.js
  mon-pix/tests/integration/components/user-account/email-with-validation-form-test.js
  mon-pix/tests/integration/components/user-account/update-email_test.js
  mon-pix/tests/unit/components/user-account/email-with-validation-form-test.js
  mon-pix/tests/unit/components/user-account/update-email-with-validation-test.js
  mon-pix/tests/unit/controllers/user-account/connection-methods_test.js
Labels: :rocket: Ready to Merge, team-acces

#3542 [BUGFIX] Correction de tests qui tombent en erreur le 12 et le 30 du mois.
  orga/tests/integration/components/participant/profile/header_test.js
Labels: Tech Review OK, cross-team

#3541 Revert "[TECH] Mettre à jour Ember Simple Auth en 4.0.0 sur Pix App."
  mon-pix/app/adapters/application.js
  mon-pix/app/mixins/secured-route-mixin.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/campaigns/assessment/skill-review.js
  mon-pix/app/routes/campaigns/assessment/start-or-resume.js
  mon-pix/app/routes/campaigns/assessment/tutorial.js
  mon-pix/app/routes/campaigns/fill-in-participant-external-id.js
  mon-pix/app/routes/campaigns/profiles-collection.js
  mon-pix/app/routes/campaigns/profiles-collection/profile-already-shared.js
  mon-pix/app/routes/campaigns/profiles-collection/send-profile.js
  mon-pix/app/routes/campaigns/profiles-collection/start-or-resume.js
  mon-pix/app/routes/campaigns/restricted/login-or-register-to-access.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/certifications/results.js
  mon-pix/app/routes/certifications/start.js
  mon-pix/app/routes/competences.js
  mon-pix/app/routes/competences/details.js
  mon-pix/app/routes/competences/results.js
  mon-pix/app/routes/competences/resume.js
  mon-pix/app/routes/index.js
  mon-pix/app/routes/inscription.js
  mon-pix/app/routes/login.js
  mon-pix/app/routes/logout.js
  mon-pix/app/routes/not-connected.js
  mon-pix/app/routes/profile.js
  mon-pix/app/routes/sitemap.js
  mon-pix/app/routes/terms-of-service-pe.js
  mon-pix/app/routes/terms-of-service.js
  mon-pix/app/routes/update-expired-password.js
  mon-pix/app/routes/user-account.js
  mon-pix/app/routes/user-account/index.js
  mon-pix/app/routes/user-certifications/get.js
  mon-pix/app/routes/user-certifications/index.js
  mon-pix/app/routes/user-dashboard.js
  mon-pix/app/routes/user-tests.js
  mon-pix/app/services/session.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/unit/mixins/secured-route-mixin_test.js
  mon-pix/tests/unit/routes/application_test.js
  mon-pix/tests/unit/routes/login_test.js
  mon-pix/tests/unit/routes/logout_test.js
  mon-pix/tests/unit/services/session_test.js
Labels: :eyes: Tech Review Needed, team-acces, cross-team

#3513 [FEATURE] Scoring des certifications démarrées (PIX-2982)
  admin/app/components/certification/certification-details-answer.js
  admin/tests/integration/components/certification/certification-details-answer_test.js
  api/db/database-builder/factory/build-certification-challenge.js
  api/db/migrations/20210917121620_add-hasBeenSkippedAutomatically-in-certification-chalenge-table.js
  api/lib/domain/events/handle-auto-jury.js
  api/lib/domain/models/AnswerCollectionForScoring.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/CertificationChallengeWithType.js
  api/lib/domain/models/CertificationContract.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/read-models/CertificationDetails.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/domain/usecases/get-certification-details.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-challenge-with-type.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/models/AnswerCollectionForScoring_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/CertificationContract_test.js
  api/tests/unit/domain/read-models/CertificationDetails_test.js
  api/tests/unit/domain/usecases/get-certification-details_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3527 [FEATURE] Bloquer l'accès à Pix certif pour les CDC SCO AGRI et AEFE (PIX-3511)
  api/db/seeds/data/certification/certification-center-memberships-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/db/seeds/data/tags-builder.js
  api/lib/domain/read-models/AllowedCertificationCenterAccess.js
  api/lib/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer.js
  api/tests/tooling/domain-builder/factory/build-allowed-certification-center-access.js
  api/tests/unit/application/certification-point-of-contacts/certification-point-of-contact-controller_test.js
  api/tests/unit/domain/read-models/AllowedCertificationCenterAccess_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer_test.js
  certif/app/models/allowed-certification-center-access.js
  certif/tests/acceptance/restricted-access_test.js
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/session-details-parameters_test.js
  certif/tests/acceptance/session-details_test.js
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/acceptance/session-list_test.js
  certif/tests/acceptance/session-new_test.js
  certif/tests/acceptance/session-update_test.js
  certif/tests/helpers/test-init.js
  certif/tests/unit/controllers/authenticated_test.js
  certif/tests/unit/models/allowed-certification-center-access_test.js
  certif/tests/unit/services/current-user_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif
