Repository 1024pix/pix, pull requests merged in 2021-05, with the labels that each got.

#2924 [FEATURE] Suppression de la notion de surnuméraire de l'API (PIX-2414)
  api/db/database-builder/factory/build-schooling-registration.js
  api/db/migrations/20210429113555_replace-organization-id-student-number-index-on-schooling-registration.js
  api/db/seeds/data/organizations-sup-builder.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/models/HigherSchoolingRegistration.js
  api/lib/domain/services/user-reconciliation-service.js
  api/lib/domain/usecases/import-higher-schooling-registrations.js
  api/lib/domain/usecases/update-student-number.js
  api/lib/domain/validators/higher-schooling-registration-validator.js
  api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/tests/integration/domain/usecases/import-higher-schooling-registrations_test.js
  api/tests/integration/domain/usecases/reconcile-higher-schooling-registration_test.js
  api/tests/integration/infrastructure/repositories/higher-schooling-registration-repository_test.js
  api/tests/tooling/domain-builder/factory/build-higher-schooling-registration.js
  api/tests/unit/domain/models/HigherSchoolingRegistrationSet_test.js
  api/tests/unit/domain/models/HigherSchoolingRegistration_test.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
  api/tests/unit/domain/usecases/update-student-number_test.js
  api/tests/unit/infrastructure/serializers/csv/higher-schooling-registration-parser_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2931 [BUGFIX] Ne pas valider de badge quand ce dernier n'a pas de critère (PIX-2538).
  api/lib/domain/services/badge-criteria-service.js
  api/tests/integration/domain/event/handle-badge-acquisition_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2936 [FEATURE] Empêcher la mise à jour de "LastQuestionDate" quand l'assessment est terminé (PIX-2524).
  api/lib/application/assessments/assessment-controller.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2934 [BUGFIX] Un candidat inscrit à une session de certification ne pouvait la rejoindre si, à l'inscription, un espace au début ou à la fin est présent dans son nom ou son prénom (PIX-2382)
  api/db/migrations/20210430154711_trim-certification-candidates-first-name-and-last-name.js
  api/lib/domain/usecases/enroll-students-to-session.js
  api/tests/unit/domain/usecases/enroll-students-to-session_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2910 [FEATURE] Afficher les certification annulées (PIX-2403)
  api/lib/domain/models/PrivateCertificate.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  mon-pix/app/components/certifications-list-item.js
  mon-pix/app/templates/components/certifications-list-item.hbs
  mon-pix/tests/integration/components/certifications-list-item_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-certif

#2918 [CLEAN] Linter automatiquement les fichiers json de traduction (PIX-2525).
  api/.eslintrc.yaml
  api/package-lock.json
  api/package.json
  api/translations/en.json
  api/translations/fr.json
  mon-pix/.eslintrc.js
  mon-pix/config/linter-translation-order.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/unit/components/comparison-window_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
  orga/.eslintrc.js
  orga/config/linter-translation-order.js
  orga/package-lock.json
  orga/package.json
  orga/translations/en.json
  orga/translations/fr.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#2937 [BUGFIX] Corriger la suppression d'un membre sur Pix Orga (Pix-2541).
  api/lib/domain/usecases/accept-organization-invitation.js
  api/lib/domain/usecases/disable-membership.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/unit/domain/usecases/accept-organization-invitation_test.js
  api/tests/unit/domain/usecases/disable-membership_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
  orga/app/components/routes/authenticated/team/items.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2902 [FEATURE] Empêcher l'utilisateur de se connecter avec un mot de passe à usage unique s'il a ensuite demandé une réinitilisation par email (PIX-2035).
  api/lib/domain/usecases/create-password-reset-demand.js
  api/lib/domain/usecases/update-user-password.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/tests/integration/domain/usecases/create-password-reset-demand_test.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/unit/domain/usecases/create-password-reset-demand_test.js
  api/tests/unit/domain/usecases/update-user-password_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2935 [CLEAN] Améliore le visuel et l'accessibilité des boutons du challenge (PIX-2535).
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, cross-team

#2940 [TRANSLATION] Modifie le texte sur les campagnes.
  mon-pix/translations/en.json
  orga/package.json
  orga/translations/en.json
Labels: :rocket: Ready to Merge, cross-team

#2919 [FEATURE] Vérifier que l'utilisateur a toujours un profil validant un badge avant de le certifier (PIX-2489).
  api/lib/domain/events/handle-clea-certification-scoring.js
  api/lib/domain/models/CleaCertificationScoring.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
  api/tests/tooling/domain-builder/factory/build-clea-certification-scoring.js
  api/tests/unit/domain/events/handle-clea-certification-scoring_test.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-finished_test.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-shared_test.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-started_test.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  api/tests/unit/domain/models/CleaCertificationScoring_test.js
  api/tests/unit/domain/usecases/compute-campaign-analysis_test.js
  api/tests/unit/domain/usecases/compute-campaign-collective-result_test.js
  api/tests/unit/domain/usecases/compute-campaign-participation-analysis_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2942 [BUGFIX] Rendre l'affichage des campagnes d'une organisation dynamique dans Pix Admin (PIX-2539).
  admin/app/routes/authenticated/organizations/get/campaigns.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2895 [TECH] Mettre à jour les paquets MonPix (PIX-2511).
  mon-pix/.template-lintrc.js
  mon-pix/app/components/routes/campaigns/fill-in-participant-external-id.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sco.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sup.hbs
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/app/templates/campaigns/fill-in-participant-external-id.hbs
  mon-pix/app/templates/components/certification-joiner.hbs
  mon-pix/app/templates/components/certification-results-page.hbs
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/app/templates/components/feedback-panel.hbs
  mon-pix/app/templates/components/form-textfield-date.hbs
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/app/templates/components/qcu-proposals.hbs
  mon-pix/app/templates/components/qroc-proposal.hbs
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/app/templates/components/routes/login-form.hbs
  mon-pix/app/templates/components/user-certifications-detail-header.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/app/templates/fill-in-certificate-verification-code.hbs
  mon-pix/app/templates/terms-of-service-pe.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, cross-team

#2946 [BUGFIX] Corrige classe "cliquable" sur mes certifications
  mon-pix/app/components/certifications-list-item.js
  mon-pix/tests/integration/components/certifications-list-item_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, team-certif

#2920 [TECH] Assurer la cohérence des noms de fichiers et de dossier.
  api/.ls-lint.yml
  api/db/batch-processing.js
  api/db/migrations/20180306151846_add_type_to_all_assessments.js
  api/db/migrations/20180306164441_remove-score-and-level-for-bugged-assessments.js
  api/db/migrations/20180405100236_move_status_from_certification_to_assessment.js
  api/db/migrations/20180405100452_migrate_assessments_info_to_assessment_results.js
  api/db/migrations/20180405100530_link_marks_to_assessment_results.js
  api/db/migrations/20180405100655_migrate_old_marks_in_competence-marks.js
  api/db/migrations/20200220145419_migrate_first_organization_join_to_user_orga_settings.js
  api/package-lock.json
  api/package.json
  api/scripts/recompute-assessment-results.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2947 [TECH Documenter la configuration SAML.
  api/sample.env
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2921 [TECH] Signaler l'erreur si une route à tester est invalide.
  api/tests/integration/application/assessments/assessment-controller_test.js
  api/tests/integration/application/campaignParticipations/index_test.js
  api/tests/integration/application/campaigns/index_test.js
  api/tests/integration/application/certifications/index_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/application/healthcheck/index_test.js
  api/tests/integration/application/memberships/membership-controller_test.js
  api/tests/integration/application/organization-invitations/index_test.js
  api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/application/passwords/index_test.js
  api/tests/integration/application/passwords/password-controller_test.js
  api/tests/integration/application/prescribers/index_test.js
  api/tests/integration/application/prescribers/prescriber-controller_test.js
  api/tests/integration/application/schooling-registration-dependent-users/index_test.js
  api/tests/integration/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller_test.js
  api/tests/integration/application/schooling-registration-user-associations/index_test.js
  api/tests/integration/application/schooling-registration-user-associations/schooling-registration-user-association-controller_test.js
  api/tests/integration/application/users/index_test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/answers/index_test.js
  api/tests/unit/application/assessments/index_test.js
  api/tests/unit/application/cache/index_test.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/application/certification-centers/index_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/application/certification-issue-reports/index_test.js
  api/tests/unit/application/certification-point-of-contacts/index_test.js
  api/tests/unit/application/certification-report/index_test.js
  api/tests/unit/application/certifications/index_test.js
  api/tests/unit/application/challenges/challenge-controller_test.js
  api/tests/unit/application/courses/index_test.js
  api/tests/unit/application/feedbacks/feedback-controller_test.js
  api/tests/unit/application/feedbacks/index_test.js
  api/tests/unit/application/healthcheck/index_test.js
  api/tests/unit/application/organization-invitations/index_test.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/application/passwords/index_test.js
  api/tests/unit/application/prescribers/index_test.js
  api/tests/unit/application/progressions/index_test.js
  api/tests/unit/application/schooling-registration-user-associations/index_test.js
  api/tests/unit/application/scorecards/index_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/stages/index_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/application/user-orga-settings/index_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/tooling/http-test-server_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2941 [TECH] Supprimer la colonne IsSupernumerary dans la table SchoolingRegistration (PIX-2519).
  api/db/migrations/20210503164450_remove-isSupernumeray-column.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-prescription

#2953 [TECH] On s'assure que un slash final dans la configuration de l'url de LCMS ne fait rien casser
  api/lib/config.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2949 [BUGFIX] Problème de scroll au niveau du tableau dans Pix Orga (PIX-2536)
  orga/app/styles/globals/tables.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2896 [TECH] Compléter la colonne CampaignParticipationId dans les BadgesAcquisitions (PIX-2288).
  api/db/database-builder/factory/build-badge-acquisition.js
  api/scripts/fill-campaign-participation-id-in-badge-acquisitions.js
  api/tests/integration/scripts/fill-campaign-participation-id-in-badge-acquisitions_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2951 [BUGFIX] Afficher correctement le détail d'un test de certification qui n'a pas été complété (PIX-2501)
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/usecases/get-certification-details.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/usecases/get-certification-details_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2923 [FEATURE] Vérifier la validité des badges certifiables avant leur certification (PIX-2513).
  api/lib/domain/models/Badge.js
  api/lib/domain/services/certification-badges-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/unit/domain/services/certification-badges-service-test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: :rocket: Ready to Merge, team-certif, team-evaluation

#2957 [TECH] Corrige le lancement des tests depuis #2953
  api/lib/config.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2958 [BUGFIX] Ne pas lancer d'erreur lors d'un payload avec plus de meta que prévu par notre validation
  api/lib/application/users/index.js
  api/tests/integration/application/users/index_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team, team-acces

#2960 Mise à jour du changelog du hotfixe 3.52.1
  CHANGELOG.md
  admin/package-lock.json
  admin/package.json
  api/package-lock.json
  api/package.json
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#2962 [TECH] Supprimer le rôle jamais utilisé PIX-READER.
  api/db/migrations/20210506121007_delete_pix_reader_row_in_pix_roles.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2939 [TECH] Refacto technique préalable avant affichage des macarons sur le certificat utilisateur (PIX-2543)
  api/db/seeds/data/certification/partner-certification-builder.js
  api/lib/application/certifications/certification-controller.js
  api/lib/domain/models/PrivateCertificate.js
  api/lib/domain/usecases/certificate/get-private-certificate.js
  api/lib/domain/usecases/find-completed-user-certifications.js
  api/lib/domain/usecases/find-user-private-certificates.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/tooling/domain-builder/factory/build-private-certificate.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/models/PrivateCertificate_test.js
  api/tests/unit/domain/usecases/find-user-private-certificates_test.js
  api/tests/unit/domain/usecases/get-private-certificate_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2963 [TECH] Empêcher les rôles dupliqués.
  api/db/migrations/20210506134706_alter_users_pix_roles_add_unique_constraint.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2961 [BUGFIX] Lors d'un rescoring manuel sur PixAdmin, les competence-marks n'étaient pas enregistrées correctement (PIX-2566)
  api/db/migrations/20210506112005_fill-missing-competence-id-values-in-table-competence-marks.js
  api/db/migrations/20210506114245_remove-nullable-mentions-in-columns-table-competence-marks.js
  api/db/seeds/seed.js
  api/lib/application/assessment-results/assessment-result-controller.js
  api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
  api/tests/unit/application/assessment-results/assessment-result-controller_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2967 [CLEAN] Nettoie le CHANGELOG des entrées créées par erreur lors d'essais avec pix-bot.
  CHANGELOG.md
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2952 [FEATURE] Ajouter le statut Annulé dans Pix Admin (PIX-2402)
  admin/app/components/certification/certification-status-select.hbs
  admin/app/components/certification/certification-status-select.js
  admin/app/models/certification.js
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/tests/unit/models/certification_test.js
  api/lib/domain/read-models/CertificationResultInformation.js
  api/lib/domain/read-models/GeneralCertificationInformation.js
  api/lib/domain/read-models/JuryCertificationSummary.js
  api/lib/infrastructure/repositories/general-certification-information-repository.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-result-information-serializer.js
  api/tests/integration/infrastructure/repositories/general-certification-information_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/unit/domain/read-models/CertificationResultInformation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-information-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2956 [TECH] Pouvoir spécifier des KE dans les tests d'algo
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/index.js
  high-level-tests/test-algo/tests/algo_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2954 [FEATURE] Ajout de sous-catégories de support pour les embed (PIX-2436).
  mon-pix/app/components/feedback-panel.js
  mon-pix/app/static-data/feedback-panel-issue-labels.js
  mon-pix/app/templates/components/feedback-panel.hbs
  mon-pix/tests/integration/components/feedback-panel_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2982 [TECH] Supprimer le package inutilisé dezalgo.
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2926 [FEATURE] Afficher le statut Annulé dans le fichier des résultats de certification (PIX-2404)
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/tooling/domain-builder/factory/build-certification-result.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/CertificationResult_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2983 [TECH] Mets à jour handlebars vers 4.7.7
  admin/package-lock.json
  api/package-lock.json
  certif/package-lock.json
  mon-pix/package-lock.json
  orga/package-lock.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2973 [FEATURE] Affichage des macarons Pix+Droit sur le certificat partagé de l'utilisateur (PIX-2370)
  api/lib/application/certifications/certification-controller.js
  api/lib/domain/models/ShareableCertificate.js
  api/lib/domain/usecases/certificate/get-shareable-certificate.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/lib/infrastructure/serializers/jsonapi/shareable-certificate-serializer.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/integration/scripts/create-certification-center-memberships-from-organization-admins_test.js
  api/tests/tooling/domain-builder/factory/build-shareable-certificate-with-competence-tree.js
  api/tests/tooling/domain-builder/factory/build-shareable-certificate.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/models/ShareableCertificate_test.js
  api/tests/unit/domain/usecases/get-shareable-certificate_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/shareable-certificate-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2974 [FEATURE] Graphe de répartition des participants par palier (PIX-2550)
  orga/app/components/charts/card.hbs
  orga/app/components/charts/participants-by-stage.hbs
  orga/app/components/charts/participants-by-stage.js
  orga/app/styles/app.scss
  orga/app/styles/components/charts/cards.scss
  orga/app/styles/components/charts/participants-by-stage.scss
  orga/tests/integration/components/dashboards/participants-by-stage_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2971 [FEATURE] Passer les sessions assignées comme sessions "à traiter" (PIX-2571)
  api/lib/domain/models/CertificationOfficer.js
  api/lib/domain/models/FinalizedSession.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/assign-certification-officer-to-jury-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-officer-repository.js
  api/lib/infrastructure/repositories/finalized-session-repository.js
  api/tests/integration/infrastructure/repositories/certification-officer-repository_test.js
  api/tests/integration/infrastructure/repositories/finalized-session-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-officer.js
  api/tests/tooling/domain-builder/factory/build-finalized-session.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/CertificationOfficer_test.js
  api/tests/unit/domain/models/FinalizedSession_test.js
  api/tests/unit/domain/usecases/assign-certification-officer-to-session_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2964 [BUGFIX] Restaurer les catégories de signalements E6 et E7 (PIX-2556)
  admin/app/models/certification-issue-report.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportCategory.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2996 [BUGFIX] Les macarons de certifications complémentaires ne s'affichaient que si le candidat avait obtenu son CléA dans le certificat partagé par code (PIX-2582)
  mon-pix/app/controllers/shared-certification.js
  mon-pix/app/templates/shared-certification.hbs
  mon-pix/tests/unit/controllers/shared-certification_test.js
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2985 [FEATURE] Améliorer l'accessibilité de l'infobulle sur le nombre de pix total
  mon-pix/app/components/hexagon-score.js
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/app/templates/components/hexagon-score.hbs
  mon-pix/tests/integration/components/hexagon-score_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2955 [FEATURE] Afficher le block "repasser" pour une campagne de collecte de profils à envois multiples (PIX-2537).
  api/lib/domain/models/Campaign.js
  api/lib/domain/models/SharedProfileForCampaign.js
  api/lib/domain/usecases/get-user-profile-shared-for-campaign.js
  api/lib/infrastructure/serializers/jsonapi/shared-profile-for-campaign-serializer.js
  api/tests/acceptance/application/users/users-get-shared-profile-for-campaign_test.js
  api/tests/unit/domain/models/SharedProfileForCampaign_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/usecases/get-user-profile-shared-for-campaign_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/shared-profile-for-campaign-serializer_test.js
  mon-pix/app/models/shared-profile-for-campaign.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/_profile-already-shared.scss
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2992 [FEATURE] Inverser les listes de session à publier et à traiter dans ADMIN (PIX-2433)
  admin/app/components/menu-bar.hbs
  admin/app/templates/authenticated/sessions/list.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2988 [FEATURE] Ré-afficher les colonnes supprimées suite à l'ajout de l'index en base de donnée (PIX-2552)
  api/lib/domain/read-models/CampaignReport.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
  orga/app/components/routes/authenticated/campaign/list.hbs
  orga/tests/integration/components/routes/authenticated/campaign/list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2950 [FEATURE] Afficher les CGUs suivant la langue de l'utilisateur dans Pix Orga (PIX-2354).
  orga/app/components/terms-of-service-en.hbs
  orga/app/components/terms-of-service-fr.hbs
  orga/app/controllers/terms-of-service.js
  orga/app/styles/pages/authenticated/terms-of-service.scss
  orga/app/templates/terms-of-service.hbs
  orga/translations/en.json
  orga/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3000 [TECH] Corrige un test flacky en supprimant du code (ce n'est pas ce que vous croyez)
  api/tests/acceptance/application/users/users-controller-patch-email_test.js
  api/tests/acceptance/application/users/users-get-shared-profile-for-campaign_test.js
  api/tests/integration/domain/event/handle-badge-acquisition_test.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/domain/usecases/create-password-reset-demand_test.js
  api/tests/integration/scripts/fill-campaign-participation-id-in-badge-acquisitions_test.js
  api/tests/test-helper.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2997 [INFRA] Loguer les traces d'erreurs dont le code est 500 ou plus en dev
  api/lib/application/pre-response-utils.js
  api/lib/config.js
  api/sample.env
  api/tests/unit/application/pre-response-utils_test.js
Labels: :rocket: Ready to Merge, cross-team, team-certif

#2998 [BUGFIX] Ajouter la méthode de connexion au GAR même quand l'utilisateur doit changer son mot de passe (PIX-2345).
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/error-manager.js
  api/lib/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/AuthenticationMethod.js
  api/lib/domain/models/User.js
  api/lib/domain/services/token-service.js
  api/lib/domain/usecases/add-gar-authentication-method-to-user.js
  api/lib/domain/usecases/authenticate-external-user.js
  api/lib/domain/usecases/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/get-external-authentication-redirection-url.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/integration/domain/usecases/add-gar-authentication-method-to-user_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/models/AuthenticationMethod_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/services/token-service_test.js
  api/tests/unit/domain/usecases/add-gar-authentication-method-to-user_test.js
  api/tests/unit/domain/usecases/authenticate-external-user_test.js
  api/tests/unit/domain/usecases/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/get-external-authentication-redirection-url_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2975 [BUGFIX] Correction de l'erreur Ember "Cannot read property 'targetName' of undefined"
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/tests/unit/routes/assessments/challenge_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team, team-captains

#3011 [BUGFIX] Homogéneiser des incohérences de clé json pour les ids de compétence lors de la modification jury (PIX-2594)
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2995 [BUGFIX] Rendre la finalisation de session idempotente (PIX-2580)
  api/lib/domain/models/FinalizedSession.js
  api/lib/domain/services/session-publication-service.js
  api/lib/domain/usecases/unpublish-session.js
  api/lib/infrastructure/repositories/finalized-session-repository.js
  api/tests/acceptance/application/session/session-controller-patch-unpublish-session_test.js
  api/tests/integration/infrastructure/repositories/finalized-session-repository_test.js
  api/tests/unit/domain/models/FinalizedSession_test.js
  api/tests/unit/domain/services/session-publication-service_test.js
  api/tests/unit/domain/usecases/unpublish-session_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3013 [FEATURE] Correctif graphique de la progress bar dans l'onglet Résultats par compétence (PIX-2553).
  orga/app/styles/globals/competences.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2990 [FEATURE] Ajout d'un wording pour l'étudiant dans la page de réconciliation SUP (PIX-2547).
  mon-pix/app/components/routes/campaigns/restricted/join-sco.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sup.hbs
  mon-pix/app/templates/campaigns/restricted/join.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3012 [BUGFIX] Le taux de repro est incorrect après une neutralisation sur la page de détails d'une certification dans PixAdmin (PIX-2599)
  api/lib/domain/events/handle-pix-plus-certifications-scoring.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/ReproducibilityRate.js
  api/lib/domain/read-models/CertificationDetails.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/ReproducibilityRate_test.js
  api/tests/unit/domain/read-models/CertificationDetails_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-certif

#3014 [TECH] Supprimer la colonne color des BadgePartnerCompetences (PIX-2523).
  admin/app/components/badges/badge.hbs
  admin/app/models/badge-partner-competence.js
  admin/tests/acceptance/authenticated/badges/badges_test.js
  admin/tests/integration/components/badges/badge_test.js
  api/db/database-builder/factory/build-badge-partner-competence.js
  api/db/migrations/20210517162046_drop-column-color-in-badge-partner-competences.js
  api/db/seeds/data/badges-builder.js
  api/lib/domain/models/BadgePartnerCompetence.js
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/read-models/participant-results/PartnerCompetenceResult.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-badge-partner-competence.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/read-models/participant-results/PartnerCompetenceResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  mon-pix/app/models/partner-competence-result.js
  mon-pix/app/templates/components/campaign-skill-review-competence-result.hbs
Labels: :rocket: Ready to Merge, team-evaluation

#3001 [TECH] Déplacer la vérification du paramètre state dans l'API lors des requêtes Pole Emploi (PIX-2597).
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/authenticate-pole-emploi-user.js
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/integration/application/authentication/index_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/domain/usecases/authenticate-pole-emploi-user_test.js
  docs/security/poleEmploi/authenticate_with_pole_emploi.puml
  mon-pix/app/authenticators/oidc.js
  mon-pix/app/routes/login-pe.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces, team-captains

#3009 [FIX] Afficher un message lorsque l'external id dépasse la limité autorisé (PIX-2505)
  api/lib/application/campaign-participations/index.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/tests/integration/domain/usecases/start-campaign-participation_test.js
  api/tests/unit/application/campaignParticipations/index_test.js
  mon-pix/app/components/routes/campaigns/fill-in-participant-external-id.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/mirage/routes/campaign-participations/post-campaign-participation.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment_test.js
  mon-pix/tests/helpers/campaign.js
  mon-pix/tests/unit/components/routes/campaigns/fill-in-participant-external-id_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3016 [FEATURE] Ajout de la traduction anglaise du bouton repasser une campagne (PIX-2598)
  mon-pix/translations/en.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2989 [FEATURE] Afficher le graphique de répartition des participants par paliers (PIX-2549)
  api/db/seeds/data/campaign-participations-builder.js
  api/lib/application/campaigns/campaign-stats-controller.js
  api/lib/application/campaigns/index.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/usecases/get-campaign-participations-counts-by-stage.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participations-count-by-stage-serializer.js
  api/tests/acceptance/application/campaign-stats-controller_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/usecases/get-campaign-participations-counts-by-stage__test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/tooling/domain-builder/factory/build-stage.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participations-count-by-stage-serializer_test.js
  orga/app/adapters/campaign-stats.js
  orga/app/components/charts/participants-by-stage-loader.hbs
  orga/app/components/charts/participants-by-stage.hbs
  orga/app/components/charts/participants-by-stage.js
  orga/app/components/routes/authenticated/campaign/collective-results/results-stats.hbs
  orga/app/components/routes/authenticated/campaign/collective-results/tab.hbs
  orga/app/controllers/authenticated/campaigns/campaign/collective-results.js
  orga/app/styles/app.scss
  orga/app/styles/components/charts/cards.scss
  orga/app/styles/components/charts/participants-by-stage.scss
  orga/app/styles/components/charts/placeholders.scss
  orga/app/templates/authenticated/campaigns/campaign/collective-results.hbs
  orga/tests/integration/components/dashboards/participants-by-stage_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3018 [TECH] Retourner un code HTTP 422 lorsque le YAML n'est pas valide
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/lib/domain/services/solution-service-qrocm-ind.js
  api/tests/unit/domain/services/solution-service-qrocm-dep_test.js
  api/tests/unit/domain/services/solution-service-qrocm-ind_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3008 [FEATURE] Ajout des titres des pages de Pix Admin (PIX-2181)
  admin/app/templates/authenticated.hbs
  admin/app/templates/authenticated/certification-centers/get.hbs
  admin/app/templates/authenticated/certification-centers/list.hbs
  admin/app/templates/authenticated/certification-centers/new.hbs
  admin/app/templates/authenticated/certifications.hbs
  admin/app/templates/authenticated/certifications/certification.hbs
  admin/app/templates/authenticated/certifications/certification/details.hbs
  admin/app/templates/authenticated/certifications/certification/neutralization.hbs
  admin/app/templates/authenticated/certifications/certification/profile.hbs
  admin/app/templates/authenticated/organizations/get/campaigns.hbs
  admin/app/templates/authenticated/organizations/get/members.hbs
  admin/app/templates/authenticated/organizations/get/target-profiles.hbs
  admin/app/templates/authenticated/organizations/list.hbs
  admin/app/templates/authenticated/organizations/new.hbs
  admin/app/templates/authenticated/sessions/list.hbs
  admin/app/templates/authenticated/sessions/list/to-be-published.hbs
  admin/app/templates/authenticated/sessions/list/with-required-action.hbs
  admin/app/templates/authenticated/sessions/session.hbs
  admin/app/templates/authenticated/sessions/session/certifications.hbs
  admin/app/templates/authenticated/target-profiles.hbs
  admin/app/templates/authenticated/target-profiles/new.hbs
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/app/templates/authenticated/target-profiles/target-profile/insight.hbs
  admin/app/templates/authenticated/target-profiles/target-profile/organizations.hbs
  admin/app/templates/authenticated/tools.hbs
  admin/app/templates/authenticated/users/get.hbs
  admin/app/templates/authenticated/users/list.hbs
  admin/package-lock.json
  admin/package.json
Labels: :rocket: Ready to Merge, cross-team, team-acces

#3010 [FEATURE] Afficher les tags sur l'onglet organisation dans Pix Admin (PIX-1332).
  admin/app/adapters/tag.js
  admin/app/components/organization-all-tags.hbs
  admin/app/components/organization-all-tags.js
  admin/app/router.js
  admin/app/routes/authenticated/organizations/get/all-tags.js
  admin/app/styles/app.scss
  admin/app/styles/authenticated/organizations/all-tags.scss
  admin/app/templates/authenticated/organizations/get.hbs
  admin/app/templates/authenticated/organizations/get/all-tags.hbs
  admin/tests/integration/components/organization-all-tags_test.js
  api/lib/application/tags/index.js
  api/lib/application/tags/tag-controller.js
  api/lib/domain/usecases/find-all-tags.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/tag-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/tags/tag-api_test.js
  api/tests/integration/infrastructure/repositories/tag-repository_test.js
  api/tests/unit/application/tags/index_test.js
  api/tests/unit/application/tags/tag-controller_test.js
  api/tests/unit/domain/usecases/find-all-tags_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tag-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2984 [TECH] Prévenir les dépendances incorrectes.
  api/.depcheckrc
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/lib/domain/services/solution-service-qrocm-ind.js
  api/lib/domain/usecases/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/publish-sessions-in-batch.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3019 [SCRIPT] Ecriture d'un script pour annuler massivement des certifications (PIX-2583)
  api/scripts/prod/cancel-certifications-and-publish-sessions.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3015 [FEATURE] Annuler une certification (PIX-2572)
  admin/app/adapters/certification.js
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/models/certification.js
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/application/certification-courses/index.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/usecases/cancel-certification-course.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/domain/models/CertificationCourse_test.js
  api/tests/unit/domain/usecases/cancel-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2959 [FEATURE] Ajout des titres à toutes les pages de Pix Orga (Pix-2504).
  orga/app/components/routes/authenticated/campaign/analysis/tab.hbs
  orga/app/components/routes/authenticated/campaign/profile/details.hbs
  orga/app/components/routes/login-or-register.hbs
  orga/app/controllers/authenticated/campaigns/assessment/analysis.js
  orga/app/controllers/authenticated/campaigns/assessment/results.js
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/controllers/authenticated/campaigns/profile.js
  orga/app/routes/authenticated/campaigns/assessment/analysis.js
  orga/app/routes/authenticated/campaigns/assessment/results.js
  orga/app/templates/application.hbs
  orga/app/templates/authenticated/campaigns/assessment.hbs
  orga/app/templates/authenticated/campaigns/assessment/analysis.hbs
  orga/app/templates/authenticated/campaigns/assessment/loading.hbs
  orga/app/templates/authenticated/campaigns/assessment/results.hbs
  orga/app/templates/authenticated/campaigns/campaign.hbs
  orga/app/templates/authenticated/campaigns/campaign/analysis.hbs
  orga/app/templates/authenticated/campaigns/campaign/assessments.hbs
  orga/app/templates/authenticated/campaigns/campaign/collective-results.hbs
  orga/app/templates/authenticated/campaigns/campaign/details.hbs
  orga/app/templates/authenticated/campaigns/campaign/loading.hbs
  orga/app/templates/authenticated/campaigns/campaign/profiles.hbs
  orga/app/templates/authenticated/campaigns/list.hbs
  orga/app/templates/authenticated/campaigns/new.hbs
  orga/app/templates/authenticated/campaigns/profile.hbs
  orga/app/templates/authenticated/campaigns/update.hbs
  orga/app/templates/authenticated/certifications.hbs
  orga/app/templates/authenticated/sco-students/list.hbs
  orga/app/templates/authenticated/sup-students/list.hbs
  orga/app/templates/authenticated/team/list.hbs
  orga/app/templates/authenticated/team/list/invitations.hbs
  orga/app/templates/authenticated/team/list/members.hbs
  orga/app/templates/authenticated/team/new.hbs
  orga/app/templates/join-request.hbs
  orga/app/templates/join.hbs
  orga/app/templates/login.hbs
  orga/app/templates/terms-of-service.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/routes/login-or-register_test.js
  orga/tests/unit/controllers/authenticated/campaigns/assessment/analysis_test.js
  orga/tests/unit/controllers/authenticated/campaigns/assessment/results_test.js
  orga/tests/unit/controllers/authenticated/campaigns/list_test.js
  orga/tests/unit/controllers/authenticated/campaigns/profile_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3026 [FEATURE] Filtrer les épreuves de certif selon la langue de l'utilisateur (PIX-2557).
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/domain/services/pick-certification-challenge_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/infrastructure/datasources/learning-content/challenge-datasource_test.js
Labels: :rocket: Ready to Merge, team-certif, team-evaluation

#3005 [TECH] Suppression du composant qroc-proposal (PIX-2448).
  mon-pix/app/components/challenge-item-qroc.js
  mon-pix/app/components/qroc-proposal.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_challenge-response.scss
  mon-pix/app/styles/components/_challenge.scss
  mon-pix/app/styles/components/_qroc-proposals.scss
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/qroc-proposal.hbs
  mon-pix/tests/acceptance/challenge-qroc_test.js
  mon-pix/tests/integration/components/challenge-item-qroc_test.js
  mon-pix/tests/integration/components/qroc-proposal_test.js
  mon-pix/tests/unit/components/challenge-item-qroc_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3023 [CLEAN] Filtrer les réponses à enregistrer (PIX-2610).
  api/db/database-builder/factory/build-assessment.js
  api/db/migrations/20210519150136_add-column-last-challenge-in-assessment.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-competence-evaluation_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/tests/unit/routes/assessments/challenge_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#3029 [FEATURE] Empêcher l'accès à une session de certification déjà finalisée (PIX-2584)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/link-user-to-session-certification-candidate.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/integration/application/error-manager_test.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  mon-pix/app/components/certification-joiner.js
  mon-pix/app/components/certification-starter.js
  mon-pix/tests/integration/components/certification-joiner_test.js
  mon-pix/tests/unit/components/certification-starter_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3007 [BUGFIX] Afficher correctement le message d'erreur lors de la modification d'un identifiant déjà existant dans Pix Admin (PIX-2470).
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/update-user-details-for-administration.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/domain/usecases/update-user-details-for-administration_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/usecases/update-user-details-for-administration_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2944 [FEATURE] Changer le texte de la bannière pour les orga SCO sur Pix Orga (PIX-2545)
  orga/app/components/information-banner.hbs
  orga/app/components/information-banner.js
  orga/app/styles/app.scss
  orga/app/styles/components/information-banner.scss
  orga/app/styles/globals/texts.scss
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/information-banner_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3030 [FEATURE] Dans Pix Admin, permettre d'ouvrir les pages de détail d'une organisation et d'un centre de certification, dans un nouvel onglet (PIX-2570).
  admin/app/components/certification-centers/list-items.hbs
  admin/app/components/menu-bar.hbs
  admin/app/components/organizations/list-items.hbs
  admin/app/controllers/authenticated/certification-centers/list.js
  admin/app/controllers/authenticated/organizations/list.js
  admin/app/styles/misc/table-admin.scss
  admin/app/templates/authenticated/certification-centers/list.hbs
  admin/app/templates/authenticated/organizations/list.hbs
  admin/app/templates/authenticated/users/list.hbs
  admin/tests/acceptance/certification-centers-list_test.js
  admin/tests/acceptance/organization-list_test.js
  admin/tests/integration/components/routes/authenticated/certification-centers/list-items_test.js
  admin/tests/integration/components/routes/authenticated/organizations/list-items_test.js
  admin/tests/integration/components/routes/authenticated/users/list-items_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Design Review OK, team-acces

#3025 [FEATURE] Permettre l'affichage d'une bannière d'informations sur Pix Orga en cas de problème sur la production (Pix-2430)
  orga/app/components/communication-banner.hbs
  orga/app/components/communication-banner.js
  orga/app/styles/app.scss
  orga/app/styles/components/communication-banner.scss
  orga/app/templates/application.hbs
  orga/config/environment.js
  orga/config/icons.js
  orga/tests/integration/components/communication-banner_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3032 [FEATURE] Renommer le libellé "Profils Reçus" pour les campagnes d'évaluation en "Résultats reçus" (PIX-2603).
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/tests/integration/components/routes/authenticated/campaign/report_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2945 [TECH] Ajoute des logs de debug sur http agent
  api/lib/infrastructure/http/http-agent.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3033 [FEATURE] Marquer des signalements comme étant "résolus" (PIX-2620)
  admin/app/components/certification/certification-list.js
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/models/certification-issue-report.js
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
  api/db/database-builder/factory/build-certification-issue-report.js
  api/db/migrations/20210525140944_add-column-processed-at-table-certification-issue-reports.js
  api/db/seeds/data/certification/certification-courses-builder.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/read-models/JuryCertificationSummary.js
  api/lib/domain/usecases/save-certification-issue-report.js
  api/lib/infrastructure/repositories/certification-issue-report-repository.js
  api/lib/infrastructure/repositories/general-certification-information-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-result-information-serializer.js
  api/lib/infrastructure/serializers/jsonapi/jury-certification-summary-serializer.js
  api/tests/integration/infrastructure/repositories/certification-issue-report-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-report-repository_test.js
  api/tests/integration/infrastructure/repositories/general-certification-information-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-issue-report.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  api/tests/unit/domain/models/FinalizedSession_test.js
  api/tests/unit/domain/read-models/JuryCertificationSummary_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-information-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-certification-summary-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3038 [TECH] Supprimer des TODO.
  api/lib/infrastructure/orm-models/User.js
  api/lib/infrastructure/repositories/user-repository.js
  mon-pix/app/components/challenge-embed-simulator.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3039 [BUGFIX] Ne pas afficher de tooltip vide sur le graphique de répartition des participants par paliers lorsqu'il n'y a ni titre ni description pour le prescripteur (PIX-2629).
  api/db/seeds/data/stages-builder.js
  orga/app/components/charts/participants-by-stage-bar.hbs
  orga/app/components/charts/participants-by-stage.hbs
  orga/app/components/charts/participants-by-stage.js
  orga/app/styles/components/charts/participants-by-stage.scss
  orga/tests/integration/components/dashboards/participants-by-stage_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3002 [TECH] Nettoyer les tests unitaires des routes
  api/lib/application/answers/index.js
  api/lib/application/assessment-results/index.js
  api/lib/application/assessments/index.js
  api/tests/unit/application/answers/index_test.js
  api/tests/unit/application/assessments/index_test.js
Labels: :rocket: Ready to Merge, cross-team

#3034 Contrôler le retour de /userinfo sur PoleEmploi.
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/create-user-from-pole-emploi.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/usecases/create-user-from-pole-emploi_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#3043 [FEATURE] Importer l'information sur le sexe lors de l'import SIECLE (PIX-2637)
  api/db/database-builder/factory/build-schooling-registration.js
  api/db/migrations/20210527111219_add-column-sex-in-table-schooling-registrations.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/domain/models/SchoolingRegistration.js
  api/lib/infrastructure/serializers/xml/xml-schooling-registration-set.js
  api/tests/integration/domain/services/schooling-registrations-xml-service_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration.js
  api/tests/tooling/fixtures/siecle-file/siecle-with-bom.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-duplicate-national-student-id-and-unclosed-tag.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-duplicate-national-student-id.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-no-national-student-id.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-no-uai.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-registrations-no-longer-in-school.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-two-valid-students.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-unknown-encoding.xml
  api/tests/tooling/fixtures/siecle-file/siecle-with-wrong-uai.xml
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2987 [BUGFIX] Corriger l'erreur "TransitionAborted" lors du clic sur "Retenter" une compétence.
  mon-pix/app/services/competence-evaluation.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-captains

#3041 [BUGFIX] Ajouter l'id de l'organisation dans le titre de certaines pages de Pix Admin (PIX-2627).
  admin/app/routes/authenticated/organizations/get/all-tags.js
  admin/app/routes/authenticated/organizations/get/campaigns.js
  admin/app/templates/authenticated.hbs
  admin/app/templates/authenticated/organizations/get/all-tags.hbs
  admin/app/templates/authenticated/organizations/get/campaigns.hbs
  admin/app/templates/authenticated/organizations/get/members.hbs
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3037 [FEATURE] Améliorer l'accessibilité de la bannière d'info de Pix Certif (PIX-2632)
  certif/app/templates/authenticated.hbs
  certif/tests/acceptance/authenticated_test.js
Labels: :rocket: Ready to Merge, team-certif

#3049 [FEATURE] Importer l'information sur le sexe lors de l'import CSV (PIX-2638)
  api/lib/infrastructure/serializers/csv/csv-registration-parser.js
  api/lib/infrastructure/serializers/csv/schooling-registration-columns.js
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/integration/scripts/prod/import-apprentices_test.js
  api/tests/unit/domain/usecases/get-schooling-registrations-csv-template_test.js
  api/tests/unit/infrastructure/serializers/csv/schooling-registration-parser_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3051 [TECH] Mise à jour des dépendances de l'API
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, cross-team

#3035 [FEATURE] Afficher la liste des sessions de façon paginée sur PixCertif (PIX-2631)
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/read-models/SessionSummary.js
  api/lib/domain/usecases/find-paginated-certification-center-session-summaries.js
  api/lib/domain/usecases/find-sessions-for-certification-center.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/repositories/session-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer.js
  api/lib/infrastructure/serializers/jsonapi/session-summary-serializer.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/integration/infrastructure/repositories/session-summary-repository_test.js
  api/tests/tooling/domain-builder/factory/build-session-summary.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/certification-centers/index_test.js
  api/tests/unit/application/certification-point-of-contacts/certification-point-of-contact-controller_test.js
  api/tests/unit/domain/read-models/SessionSummary_test.js
  api/tests/unit/domain/usecases/find-paginated-certification-center-session-summaries_test.js
  api/tests/unit/domain/usecases/find-sessions-for-certification-center_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-summary-serializer_test.js
  certif/app/adapters/session-summary.js
  certif/app/components/session-summary-list.hbs
  certif/app/controllers/authenticated/sessions/list.js
  certif/app/models/certification-center.js
  certif/app/models/session-summary.js
  certif/app/routes/authenticated/sessions/list.js
  certif/app/templates/authenticated/sessions/list.hbs
  certif/mirage/config.js
  certif/mirage/serializers/certification-center.js
  certif/tests/acceptance/session-list_test.js
  certif/tests/acceptance/switch-certification-center_test.js
  certif/tests/integration/components/session-summary-list_test.js
  certif/tests/unit/adapters/session-summary_test.js
  certif/tests/unit/controllers/authenticated/sessions/list_test.js
  certif/tests/unit/models/session-summary_test.js
  certif/tests/unit/routes/authenticated/sessions/list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif
