Repository 1024pix/pix, pull requests merged in 2021-03, with the labels that each got.

#2635 [TECH] Mise à jour des dépendances du module racine.
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2623 [TECH] Proposition : supprimer MailJet 💣 📨
  api/lib/config.js
  api/lib/infrastructure/mailers/MailjetProvider.js
  api/lib/infrastructure/mailers/mailer.js
  api/lib/infrastructure/validate-environement-variables.js
  api/package-lock.json
  api/package.json
  api/sample.env
  api/tests/unit/infrastructure/mailers/MailjetProvider_test.js
  docs/API.md
  docs/adr/0021-suppression-du-support-mailjet-pour-le-mailing.md
  docs/test.md
  high-level-tests/load-testing/README.md
Labels: Tech Review OK, cross-team

#2633 [FEATURE] Préparation à l'affichage des sessions à traiter (PIX-2040)
  api/lib/application/sessions/finalized-session-controller.js
  api/lib/application/sessions/index.js
  api/lib/domain/usecases/find-finalized-sessions-with-required-action.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/finalized-session-repository.js
  api/lib/infrastructure/serializers/jsonapi/publishable-session-serializer.js
  api/lib/infrastructure/serializers/jsonapi/session-with-required-action-serializer.js
  api/tests/acceptance/application/finalized-session/finalized-session-controller-find-finalized-sessions-with-required-action_test.js
  api/tests/integration/infrastructure/repositories/finalized-session-repository_test.js
  api/tests/unit/application/session/finalized-session-controller_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/domain/usecases/find-finalized-sessions-with-required-action_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/publishable-session-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2615 [BUGFIX] Corriger le changement de mot de passe à usage unique pour un élève qui tente de se réconcilier (PIX-2196).
  mon-pix/app/routes/update-expired-password.js
  mon-pix/tests/unit/routes/update-expired-password-test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2625 [CLEAN] Suppression de la bannière de niveau 6 (PIX-2234).
  api/db/database-builder/factory/build-user.js
  api/db/migrations/20210226114025_drop-column-has-seen-new-level-info-from-users.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/remember-user-has-seen-new-level-info.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/remember-user-has-seen-new-level-info_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/profile-content.js
  mon-pix/app/models/user.js
  mon-pix/app/templates/components/profile-content.hbs
  mon-pix/public/images/Illu_niveau6_fr.svg
  mon-pix/tests/unit/adapters/user-test.js
  mon-pix/tests/unit/components/profile-content-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2630 [BUGFIX] Affichage de l'instruction avec des liens (PIX-2267).
  mon-pix/app/styles/components/_challenge-statement.scss
Labels: :rocket: Ready to Merge, team-evaluation

#2632 [TECH] Améliorer l'accessibilité du tableaux de résultats par compétences en campagne (PIX-1885).
  mon-pix/app/templates/components/campaign-skill-review-competence-result.hbs
  mon-pix/tests/acceptance/skill-review-page-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2617 [FEATURE] Ajout du filtre sur les classes pour pouvoir récupérer les résultats de certification par classe sur PixOrga (PIX-2195)
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/find-divisions-by-organization.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-divisions-by-organization_test.js
  orga/app/adapters/division.js
  orga/app/components/sidebar-menu.js
  orga/app/controllers/authenticated/certifications.js
  orga/app/routes/authenticated/certifications.js
  orga/app/services/file-saver.js
  orga/app/styles/pages/authenticated/certifications.scss
  orga/app/templates/authenticated/certifications.hbs
  orga/mirage/config.js
  orga/mirage/factories/division.js
  orga/tests/acceptance/authentication-test.js
  orga/tests/integration/components/sidebar-menu-test.js
  orga/tests/unit/adapters/division-test.js
  orga/tests/unit/controllers/authenticated/certifications-test.js
  orga/tests/unit/routes/authenticated/certifications-test.js
  orga/tests/unit/services/file-saver-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2637 [BUGFIX] Le mauvais nombre de paliers est affiché sur les cartes de participations (PIX-2277).
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2622 [FEATURE] Traduire la page de participant d'une collecte de profils (PIX-2203).
  orga/app/components/routes/authenticated/campaign/profile/details.hbs
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/components/routes/authenticated/campaign/profile/table.hbs
  orga/app/styles/components/pix-score-tag.scss
  orga/tests/integration/components/routes/authenticated/campaign/profile/details-test.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/table-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2638 [FEATURE] Affichage de la liste des sessions à traiter dans pix-admin (PIX-2040)
  admin/app/adapters/with-required-action-session.js
  admin/app/components/with-required-action-sessions/list-items.hbs
  admin/app/models/with-required-action-session.js
  admin/app/router.js
  admin/app/routes/authenticated/sessions/list/with-required-action.js
  admin/app/templates/authenticated/sessions/list.hbs
  admin/app/templates/authenticated/sessions/list/with-required-action.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/sessions/list/with-required-action-test.js
  admin/tests/unit/adapters/with-required-action-session-test.js
  admin/tests/unit/models/with-required-action-session-test.js
  admin/tests/unit/routes/authenticated/sessions/list/with-required-action-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2616 [FEATURE] Dans Pix App, ajouter "Mon compte" dans le menu utilisateur (PIX-2106).
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/application/users/index.js
  api/lib/config.js
  api/sample.env
  api/tests/acceptance/application/feature-controller_tests.js
  api/tests/acceptance/application/users/users-controller-patch-email_test.js
  mon-pix/app/components/user-account-panel.js
  mon-pix/app/components/user-account-update-email.js
  mon-pix/app/templates/components/user-account-panel.hbs
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/tests/acceptance/user-logged-menu-test.js
  mon-pix/tests/integration/components/user-account-panel-test.js
  mon-pix/tests/integration/components/user-account-update-email-test.js
  mon-pix/tests/integration/components/user-logged-menu-test.js
  mon-pix/translations/en.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, :warning: Blocked, team-acces

#2627 [TECH] Bumper les paquets Cypress et load-testing.
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  high-level-tests/e2e/cypress/support/step_definitions/member.js
  high-level-tests/e2e/cypress/support/step_definitions/page-title.js
  high-level-tests/e2e/cypress/support/step_definitions/pix-certif/session.js
  high-level-tests/e2e/cypress/support/step_definitions/profile.js
  high-level-tests/e2e/cypress/support/step_definitions/student.js
  high-level-tests/e2e/cypress/support/step_definitions/update-password.js
  high-level-tests/e2e/cypress/support/step_definitions/user-dashboard.js
  high-level-tests/e2e/cypress/support/step_definitions/user-tutorials.js
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
Labels: :rocket: Ready to Merge, cross-team

#2643 [TECH] Mise à jour du paquet de SendInBlue de la 7.2.4 pour 8.2.0.
  api/lib/infrastructure/mailers/SendinblueProvider.js
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, cross-team, team-captains

#2626 [FEATURE] Traduire dans l'API l'invitation à rejoindre Pix Orga (PIX-2212).
  api/lib/domain/services/mail-service.js
  api/tests/unit/domain/services/mail-service_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :eyes: Tech Review Needed, team-acces

#2649 [FEATURE] Dans la page Mon compte de Pix App (.org), mettre le label "Langages" au singulier (PIX-2282).
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2645 [TECH][API] Ajout d'un module i18n dans l'API pour dynamiser les traductions (Pix-2285)
  api/lib/application/healthcheck/healthcheck-controller.js
  api/lib/application/prescribers/index.js
  api/lib/plugins.js
  api/package-lock.json
  api/package.json
  api/tests/unit/application/healthcheck/healthcheck-controller_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2646 [FEATURE] Ajouter la date de création des profils cibles dans Pix Admin(PIX-2248)
  admin/app/models/target-profile.js
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-with-learning-content.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2640 [FEATURE] Retirer les succès pour les utilisateurs anonymes (PIX-2275).
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/tests/unit/controllers/assessments/challenge-test.js
  mon-pix/tests/unit/controllers/assessments/checkpoint-test.js
  mon-pix/tests/unit/routes/assessments/challenge-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2652 [TECH] Suppression des espaces inutiles dans les fichiers servers.conf.
  admin/servers.conf.erb
  certif/servers.conf.erb
  mon-pix/servers.conf.erb
  orga/servers.conf.erb
  servers.conf.erb
Labels: :rocket: Ready to Merge, cross-team, team-captains

#2634 [FEATURE] Rendre l'image des scorecard accessible (PIX-1849).
  mon-pix/app/components/competence-card-mobile.js
  mon-pix/app/helpers/scorecard-aria-label.js
  mon-pix/app/templates/components/circle-chart.hbs
  mon-pix/app/templates/components/competence-card-default.hbs
  mon-pix/app/templates/components/competence-card-mobile.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/tests/unit/components/competence-card-mobile-test.js
  mon-pix/tests/unit/helpers/scorecard-aria-label.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2641 [CLEANUP] refacto récupération de la liste des classes sco (PIX-2280)
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/models/Division.js
  api/lib/domain/usecases/find-divisions-by-certification-center.js
  api/lib/domain/usecases/find-divisions-by-organization.js
  api/lib/infrastructure/repositories/division-repository.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/jsonapi/division-serializer.js
  api/lib/infrastructure/serializers/jsonapi/sco-certification-center-division-serializer.js
  api/tests/integration/domain/usecases/get-participants-division_test.js
  api/tests/integration/infrastructure/repositories/division-repository_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-divisions-by-certification-center_test.js
  api/tests/unit/domain/usecases/find-divisions-by-organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/division-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/sco-certification-center-divisions-serializer.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2642 [FEATURE] Ajouter la traduction des messages d'erreurs lors de la création d'une campagne. (PIX-2198)
  api/lib/domain/validators/campaign-validator.js
  api/tests/unit/domain/validators/campaign-validator_test.js
  orga/app/components/routes/authenticated/campaign/new.hbs
  orga/app/controllers/authenticated/campaigns/new.js
  orga/app/helpers/display-campaign-errors.js
  orga/tests/integration/components/routes/authenticated/campaign/new-test.js
  orga/tests/unit/helpers/display-campaign-errors-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2628 [FEATURE] Afficher les paliers liés à un profil cible (PIX-2224).
  admin/app/components/target-profiles/badge-list.hbs
  admin/app/components/target-profiles/badges.hbs
  admin/app/components/target-profiles/badges.js
  admin/app/components/target-profiles/insight.hbs
  admin/app/components/target-profiles/stages.hbs
  admin/app/components/target-profiles/stages.js
  admin/app/models/stage.js
  admin/app/models/target-profile.js
  admin/app/router.js
  admin/app/routes/authenticated/target-profiles/target-profile/badges.js
  admin/app/routes/authenticated/target-profiles/target-profile/insight.js
  admin/app/styles/app.scss
  admin/app/styles/components/target-profiles/badges.scss
  admin/app/styles/components/target-profiles/insight.scss
  admin/app/styles/components/target-profiles/stages.scss
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/app/templates/authenticated/target-profiles/target-profile/badges.hbs
  admin/app/templates/authenticated/target-profiles/target-profile/insight.hbs
  admin/tests/integration/components/routes/authenticated/target-profiles/target-profile/badges-test.js
  admin/tests/integration/components/routes/authenticated/target-profiles/target-profile/insight-test.js
  admin/tests/integration/components/target-profiles/badges_test.js
  admin/tests/integration/components/target-profiles/stages_test.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/usecases/find-target-profile-stages.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/stage-repository.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/lib/infrastructure/serializers/jsonapi/stage-serializer.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/stage-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-with-learning-content.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2654 [TECH] Réactiver le linter pour Pix Admin
  .circleci/config.yml
  admin/app/components/certification-list-select-all.js
  admin/app/components/organization-members-section.js
  admin/app/components/target-profiles/stages.hbs
  admin/app/controllers/authenticated/certification-centers/list.js
  admin/app/controllers/authenticated/certifications/certification/details.js
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/controllers/authenticated/organizations/get/members.js
  admin/app/controllers/authenticated/sessions/list/all.js
  admin/app/controllers/authenticated/sessions/session/certifications.js
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/controllers/authenticated/target-profiles/list.js
  admin/app/controllers/authenticated/tools.js
  admin/app/controllers/authenticated/users/list.js
  admin/app/models/certification-details.js
  admin/app/models/certification.js
  admin/app/models/jury-certification-summary.js
  admin/app/models/membership.js
  admin/app/models/organization-invitation.js
  admin/app/models/organization.js
  admin/app/models/session.js
  admin/app/models/user.js
  admin/app/router.js
  admin/app/routes/authenticated/sessions/index.js
  admin/app/routes/authenticated/sessions/list/all.js
  admin/app/services/csv-service.js
  admin/tests/integration/components/organizations-test.js
  admin/tests/integration/components/user-detail-personal-information-test.js
Labels: :rocket: Ready to Merge, cross-team

#2631 [FEATURE] Ajout des traductions pour la page des étudiants (SUP) (PIX-2254).
  orga/app/components/routes/authenticated/sup-students/list-items.hbs
  orga/tests/integration/components/routes/authenticated/sup-students/list-items-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2661 [BUGFIX] Empêcher le téléchargement de résultats non publiés sur orga (PIX-2293)
  api/lib/domain/usecases/get-sco-certification-results-by-division.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/get-sco-certification-results-by-division_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2665 [FEATURE] Change wording for certification page labels (pix-2295)
  orga/tests/acceptance/authentication-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :eyes: Func Review Needed, :rocket: Ready to Merge, Tech Review OK, team-certif

#2663 [INFRA] Ajout d'un status de réussite ou d'échec à la méthode d'envoi d'email
  api/lib/infrastructure/mailers/mailer.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2639 [CLEAN] Renommer PublishableSessions en ToBePublishedSessions
  admin/app/adapters/to-be-published-session.js
  admin/app/components/to-be-published-sessions/list-items.hbs
  admin/app/components/to-be-published-sessions/list-items.js
  admin/app/controllers/authenticated/sessions/list/to-be-published.js
  admin/app/models/to-be-published-session.js
  admin/app/routes/authenticated/sessions/list/to-be-published.js
  admin/app/templates/authenticated/sessions/list/to-be-published.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/sessions/list/to-be-published-test.js
  admin/tests/integration/components/routes/authenticated/to-be-published-sessions/list-items-test.js
  admin/tests/unit/adapters/to-be-published-session-test.js
  admin/tests/unit/controllers/authenticated/sessions/list/to-be-published-test.js
  admin/tests/unit/models/to-be-published-session-test.js
  admin/tests/unit/routes/authenticated/sessions/list/to-be-published-test.js
  api/lib/application/sessions/finalized-session-controller.js
  api/lib/infrastructure/serializers/jsonapi/to-be-published-session-serializer.js
  api/tests/acceptance/application/finalized-session/finalized-session-controller-find-finalized-sessions-to-publish_test.js
  api/tests/unit/application/session/finalized-session-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/to-be-published-session-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2659 [CLEANUP] Supprimer les exceptions du template-lintrc de Pix App (PIX-2304).
  mon-pix/.template-lintrc.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sup.hbs
  mon-pix/app/templates/application.hbs
  mon-pix/app/templates/components/campaign-start-block.hbs
  mon-pix/app/templates/components/challenge-embed-simulator.hbs
  mon-pix/app/templates/components/footer.hbs
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/navbar-mobile-header.hbs
  mon-pix/app/templates/components/new-information.hbs
  mon-pix/app/templates/components/qrocm-dep-solution-panel.hbs
  mon-pix/app/templates/components/qrocm-ind-solution-panel.hbs
  mon-pix/app/templates/components/routes/login-or-register.hbs
  mon-pix/app/templates/components/routes/register-form.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/app/templates/components/user-certifications-detail-competence.hbs
  mon-pix/app/templates/components/user-certifications-detail-competences-list.hbs
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
Labels: :rocket: Ready to Merge, cross-team

#2662 [BUGFIX] La tooltip "Copier" dans la page détail d'une campagne n'avait pas de traduction (PIX-2305)
  orga/app/components/routes/authenticated/campaign/details/tab.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2655 [TECH] Refactorer les tests d'invitation aux organisations (PIX-2297).
  api/tests/unit/domain/services/mail-service_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2671 [BUGFIX] Affichage du burger menu cassé.
  mon-pix/app/templates/components/navbar-mobile-header.hbs
Labels: :rocket: Ready to Merge, team-evaluation

#2426 [TECH] Affiche le profil de positionnement et les acquis évalués en certification pour un test de certif sur PixAdmin (PIX-2185)
  admin/app/adapters/certified-profile.js
  admin/app/components/certification/certified-profile.hbs
  admin/app/components/certification/certified-profile.js
  admin/app/models/certified-area.js
  admin/app/models/certified-competence.js
  admin/app/models/certified-profile.js
  admin/app/models/certified-skill.js
  admin/app/models/certified-tube.js
  admin/app/router.js
  admin/app/routes/authenticated/certifications/certification/profile.js
  admin/app/styles/app.scss
  admin/app/styles/components/certified-profile.scss
  admin/app/templates/authenticated/certifications/certification.hbs
  admin/app/templates/authenticated/certifications/certification/profile.hbs
  admin/mirage/config.js
  admin/mirage/serializers/certified-profile.js
  admin/tests/acceptance/authenticated/certifications/certification/profile-test.js
  admin/tests/integration/components/certification/certified-profile-test.js
  admin/tests/unit/adapters/certified-profile-test.js
  admin/tests/unit/routes/authenticated/certifications/certification/profile-test.js
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/application/certification-courses/index.js
  api/lib/domain/read-models/CertifiedProfile.js
  api/lib/infrastructure/datasources/learning-content/skill-datasource.js
  api/lib/infrastructure/repositories/certified-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/certified-profile-serializer.js
  api/tests/integration/infrastructure/repositories/certified-profile-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certified-area.js
  api/tests/tooling/domain-builder/factory/build-certified-competence.js
  api/tests/tooling/domain-builder/factory/build-certified-profile.js
  api/tests/tooling/domain-builder/factory/build-certified-skill.js
  api/tests/tooling/domain-builder/factory/build-certified-tube.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/infrastructure/datasources/learning-content/skill-datasource_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certified-profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/is-certifiable-serializer_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team, team-certif

#2656 [FEATURE] Ajout des traductions pour la page de modification du numéro étudiant (SUP) (PIX-2255).
  api/lib/domain/usecases/update-student-number.js
  api/tests/unit/domain/usecases/update-student-number_test.js
  orga/app/components/edit-student-number-modal.hbs
  orga/app/components/edit-student-number-modal.js
  orga/mirage/config.js
  orga/tests/integration/components/edit-student-number-modal-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2629 [TECH] Bump du package.json de l'api
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2658 [TECH] Transférer la traduction de l'email de création de compte dans l'API (PIX-2213).
  api/lib/domain/services/mail-service.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2664 [TECH] Pouvoir changer le comportement de l'utilisateur dans les tests d'algo (PIX-2063).
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/index.js
  high-level-tests/test-algo/tests/algo_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2648 [FEATURE] Pouvoir mettre du markdown sur les QCU (PIX-2289).
  mon-pix/app/components/qcu-proposals.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_challenge-response.scss
  mon-pix/app/styles/components/_qcu-panel.scss
  mon-pix/app/styles/components/_qcu-proposals.scss
  mon-pix/app/styles/components/_qcu-solution-panel.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
  mon-pix/app/templates/components/qcu-proposals.hbs
  mon-pix/app/templates/components/qcu-solution-panel.hbs
  mon-pix/config/environment.js
  mon-pix/mirage/factories/challenge.js
  mon-pix/tests/acceptance/challenge-qcu-test.js
  mon-pix/tests/integration/components/qcu-solution-panel-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2653 [DOC] ADR sur la gestion des images dans Pix App.
  docs/adr/0022-gestion-des-images-dans-app.md
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2673 [FEATURE] Ne pas montrer de bannière sur la page "Certifications" sur PixOrga (PIX-2296)
  orga/app/components/information-banner.js
  orga/tests/acceptance/authentication-test.js
  orga/tests/acceptance/certifications-test.js
Labels: :eyes: Func Review Needed, :rocket: Ready to Merge, Tech Review OK, team-certif

#2668 [FIX] Ignorer les liens pole emploi connect dans le Doc Link Checker
  docs/link--check-config.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2680 [TECH] Trier les résultats par compétence dans les résultats envoyés pour le livret scolaire.
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/tests/acceptance/application/certifications-livret-scolaire/certification-controller_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2674 [FEATURE] Traduire en anglais la page Inviter un membre dans Pix Orga (PIX-2220).
  orga/app/components/routes/authenticated/team/new-item.hbs
  orga/app/controllers/authenticated/team/new.js
  orga/app/routes/authenticated/team/new.js
  orga/app/templates/authenticated/team/new.hbs
  orga/tests/acceptance/team-creation-test.js
  orga/tests/integration/components/routes/authenticated/team/new-item-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2678 [FEATURE] Rechercher une classe lors du téléchargement des résultats de certif (PIX-2306)
  orga/app/controllers/authenticated/certifications.js
  orga/app/styles/pages/authenticated/certifications.scss
  orga/app/templates/authenticated/certifications.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/unit/controllers/authenticated/certifications-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#2686 [BUGFIX] Soucis visuel sur les checkbox (PIX-2325).
  mon-pix/app/styles/globals/_redesign-inputs.scss
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2651 [FEATURE][i18n] Contextualisation des en-têtes sur l'export de résultats pour une campagne de collecte de profils (Pix-2205).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/lib/infrastructure/exports/campaigns/campaign-profile-collection-result-line.js
  api/lib/infrastructure/serializers/csv/campaign-profile-collection-export.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/infrastructure/exports/campaigns/campaign-profile-collection-result-line_test.js
  api/tests/unit/infrastructure/serializers/csv/campaign-profile-collection-export_test.js
  api/translations/en.json
  api/translations/fr.json
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/routes/authenticated/campaign/report.js
  orga/tests/integration/components/routes/authenticated/campaign/report-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2667 [FEATURE] Traduction des bannières d'information de Pix Orga (PIX-2253).
  orga/app/components/information-banner.hbs
  orga/app/components/translate-extended.hbs
  orga/app/components/translate-extended.js
  orga/tests/integration/components/information-banner-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2687 [FEATURE] Afficher la titre et la description prescripteur d'un palier dans la liste des participants d'une campagne d'évaluation de Pix Orga (PIX-2315).
  api/db/seeds/data/stages-builder.js
  api/lib/domain/models/Stage.js
  api/lib/infrastructure/serializers/jsonapi/campaign-report-serializer.js
  api/tests/tooling/domain-builder/factory/build-stage.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-report-serializer_test.js
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/components/stage-stars.hbs
  orga/app/components/stage-stars.js
  orga/app/models/stage.js
  orga/app/styles/components/stage-stars.scss
  orga/tests/integration/components/stage-stars-test.js
  orga/tests/unit/controllers/authenticated/certifications-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2669 [FEATURE] Permettre la suppression d'un membre depuis Pix Orga (PIX-404).
  admin/app/adapters/membership.js
  admin/tests/unit/adapters/membership-test.js
  api/lib/application/memberships/index.js
  api/tests/acceptance/application/membership-controller_test.js
  api/tests/integration/application/memberships/membership-controller_test.js
  orga/app/adapters/membership.js
  orga/app/components/modal/dialog.hbs
  orga/app/components/modal/dialog.js
  orga/app/components/routes/authenticated/team/items.hbs
  orga/app/components/routes/authenticated/team/items.js
  orga/app/components/routes/authenticated/team/members.hbs
  orga/app/controllers/authenticated/team/list/members.js
  orga/app/routes/authenticated/team/list.js
  orga/app/styles/components/modal.scss
  orga/app/styles/globals/buttons.scss
  orga/app/styles/globals/colors.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/templates/authenticated/team/list/members.hbs
  orga/mirage/config.js
  orga/tests/acceptance/remove-membership-test.js
  orga/tests/integration/components/modal/dialog-test.js
  orga/tests/integration/components/routes/authenticated/team/items-test.js
  orga/tests/unit/adapters/membership-test.js
  orga/tests/unit/controllers/authenticated/team/list/members-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2689 [BUGFIX] Réparer l'export des résultats pour les utilisateurs anonymes (PIX-2346).
  api/lib/domain/read-models/CampaignParticipationInfo.js
  api/tests/unit/domain/read-models/CampaignParticipationInfo_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2660 [FEATURE] Traduire dans l'API la demande de réinitialisation du mot de passe d'un utilisateur (PIX-2214).
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/create-password-reset-demand.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/create-password-reset-demand_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2691 [FEATURE] Trier la liste des classes sur la page "Certifications" (PIX-2324)
  api/lib/domain/usecases/find-divisions-by-organization.js
  api/lib/infrastructure/repositories/division-repository.js
  api/scripts/data-generation/add-many-students-to-sco-certification-center.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/integration/infrastructure/repositories/division-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2647 [FEATURE] Ajout d'un nouveau critère pour la création des RT (PIX-2258).
  api/db/database-builder/factory/build-badge-criterion.js
  api/db/migrations/20210304154309_add-partner-competences-ids-to-badge-criteria-table.js
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/campaigns-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/domain/models/BadgeCriterion.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-badge-criterion.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2666 [TECH] Ajout d'un helper front pour pouvoir avoir un choix de langue dans un bloc de text (PIX-2318).
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/helpers/text-with-multiple-lang.js
  mon-pix/tests/unit/helpers/text-with-multiple-lang-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2696 [TECH] Tri les paliers par ordre de seuil
  api/lib/infrastructure/repositories/stage-repository.js
  api/tests/integration/infrastructure/repositories/stage-repository_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2695 [TECH] Stocke les résultats des tests dans circleci
  .circleci/config.yml
  api/package-lock.json
  api/package.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2692 [BUGFIX] Ne pas afficher les campagnes pour Novice dans les TDB et pages parcours (PIX-2320).
  api/db/seeds/data/campaigns-builder.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation, team-prescription

#2694 [FEATURE] Afficher la titre et la description prescripteur d'un palier dans le détail d'un participant d'une campagne d'évaluation de Pix Orga (PIX-2316).
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2683 [BUGFIX] Supprime une faille d'injection SQL
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
Labels: :rocket: Ready to Merge, team-certif

#2682 [FEATURE] Publier des sessions en masse (PIX-2041)
  admin/app/adapters/to-be-published-session.js
  admin/app/controllers/authenticated/sessions/list/to-be-published.js
  admin/app/routes/authenticated/sessions/list/to-be-published.js
  admin/app/styles/authenticated/sessions/list.scss
  admin/app/templates/authenticated/sessions/list/to-be-published.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/sessions/list/to-be-published-test.js
  admin/tests/unit/controllers/authenticated/sessions/list/to-be-published-test.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/lib/application/http-errors.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/EmailingAttempt.js
  api/lib/domain/models/Session.js
  api/lib/domain/models/SessionPublicationBatchResult.js
  api/lib/domain/services/session-publication-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/publish-session.js
  api/lib/domain/usecases/publish-sessions-in-batch.js
  api/lib/infrastructure/mailers/mailer.js
  api/tests/acceptance/application/session/session-controller-patch-publish-session_test.js
  api/tests/acceptance/application/session/session-controller-publish-session-in-batch_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/services/session-publication-service_test.js
  api/tests/unit/domain/usecases/publish-session_test.js
  api/tests/unit/domain/usecases/publish-sessions-in-batch_test.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#2688 [FEATURE] Traduire les erreurs à l'import des CSV des élèves/étudiants (PIX-2312)
  api/lib/application/error-manager.js
  api/lib/application/http-errors.js
  api/lib/domain/errors.js
  api/lib/infrastructure/serializers/csv/csv-registration-parser.js
  api/lib/infrastructure/serializers/csv/higher-schooling-registration-parser.js
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-registration-parser_test.js
  api/tests/unit/infrastructure/serializers/csv/higher-schooling-registration-parser_test.js
  api/tests/unit/infrastructure/serializers/csv/schooling-registration-parser_test.js
  orga/app/controllers/authenticated/sco-students/list.js
  orga/app/controllers/authenticated/sup-students/list.js
  orga/app/helpers/display-campaign-errors.js
  orga/app/services/error-messages.js
  orga/tests/unit/controllers/authenticated/sup-students/list-test.js
  orga/tests/unit/services/error-messages-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2684 [FEATURE] Création de paliers depuis l'admin (PIX-1968)
  admin/app/adapters/badge.js
  admin/app/adapters/stage.js
  admin/app/components/organization-target-profiles-section.hbs
  admin/app/components/target-profiles/create-target-profile-form.hbs
  admin/app/components/target-profiles/insight.hbs
  admin/app/components/target-profiles/stages.hbs
  admin/app/components/target-profiles/stages.js
  admin/app/controllers/authenticated/organizations/get/target-profiles.js
  admin/app/models/badge.js
  admin/app/models/stage.js
  admin/app/routes/authenticated/target-profiles/target-profile/insight.js
  admin/app/styles/components/target-profiles/stages.scss
  admin/app/templates/authenticated/organizations/get/target-profiles.hbs
  admin/mirage/config.js
  admin/mirage/handlers/stages.js
  admin/mirage/handlers/target-profiles.js
  admin/mirage/serializers/target-profile.js
  admin/tests/acceptance/authenticated/target-profiles/insight-test.js
  admin/tests/integration/components/routes/authenticated/target-profiles/target-profile/insight-test.js
  admin/tests/integration/components/target-profiles/create-target-profile-form-test.js
  admin/tests/integration/components/target-profiles/stages_test.js
  admin/tests/unit/components/target-profiles/stages_test.js
  api/lib/application/error-manager.js
  api/lib/application/pre-response-utils.js
  api/lib/application/stages/index.js
  api/lib/application/stages/stages-controller.js
  api/lib/domain/models/Stage.js
  api/lib/domain/usecases/create-stage.js
  api/lib/domain/usecases/index.js
  api/lib/domain/validators/stage-validator.js
  api/lib/infrastructure/repositories/stage-repository.js
  api/lib/infrastructure/serializers/jsonapi/stage-serializer.js
  api/lib/routes.js
  api/tests/integration/infrastructure/repositories/stage-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/application/pre-response-utils_test.js
  api/tests/unit/application/stages/index_test.js
  api/tests/unit/application/stages/stages-controller_test.js
  api/tests/unit/domain/usecases/create-stage-test.js
  api/tests/unit/domain/validators/stage-validator_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/stage-serializer_test.js
  api/translations/en.json
  api/translations/fr.json
  api/translations/index.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2700 [FEATURE] Ajout d'un lien vers une documentation au sujet des résultats de certification (PIX-2338)
  orga/app/controllers/authenticated/certifications.js
  orga/app/styles/pages/authenticated/certifications.scss
  orga/app/templates/authenticated/certifications.hbs
  orga/tests/acceptance/certifications-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-certif

#2685 [FEATURE][i18n] Traduction des en-têtes csv et du contenu pour les résultats d'une campagne (PIX-2206)
  api/lib/application/campaigns/campaign-controller.js
  api/lib/domain/services/campaign-csv-export-service.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/lib/infrastructure/exports/campaigns/campaign-profile-collection-result-line.js
  api/lib/infrastructure/serializers/csv/campaign-profile-collection-export.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/tooling/i18n/i18n.js
  api/tests/tooling/i18n/i18n_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/infrastructure/exports/campaigns/campaign-profile-collection-result-line_test.js
  api/tests/unit/infrastructure/serializers/csv/campaign-profile-collection-export_test.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2690 [FEATURE] Afficher la personne assignée à la session dans la liste des sessions à traiter (Pix-2299)
  admin/app/components/with-required-action-sessions/list-items.hbs
  admin/app/models/with-required-action-session.js
  admin/tests/acceptance/authenticated/sessions/list/with-required-action-test.js
  api/db/database-builder/factory/build-finalized-session.js
  api/db/migrations/20210309173118_add_assigned_certification_officer_name_to_finalized_sessions_table.js
  api/lib/application/sessions/finalized-session-controller.js
  api/lib/domain/models/FinalizedSession.js
  api/lib/domain/usecases/assign-certification-officer-to-jury-session.js
  api/lib/infrastructure/repositories/finalized-session-repository.js
  api/lib/infrastructure/serializers/jsonapi/with-required-action-session-serializer.js
  api/tests/acceptance/application/session/session-controller-patch-user-assignment_test.js
  api/tests/integration/infrastructure/repositories/finalized-session-repository_test.js
  api/tests/unit/application/session/finalized-session-controller_test.js
  api/tests/unit/domain/usecases/assign-certification-officer-to-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/with-required-action-session_test.js
Labels: :eyes: Func Review Needed, :rocket: Ready to Merge, Tech Review OK, team-certif

#2714 [FEATURE] Modifier l'ordre des onglets sur la page "Sessions de certifications" (PIX-2302)
  admin/app/components/menu-bar.hbs
  admin/app/templates/authenticated/sessions/list.hbs
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2710 [FEATURE] Ne plus filtrer par défaut la liste de "Toutes les sessions" (PIX-2300)
  admin/app/controllers/authenticated/sessions/list/all.js
  admin/tests/acceptance/sessions-list-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2676 [FEATURE] Transfert du bandeau d'envoi de résultats de collecte de profil de la page compétences vers le TDB (PIX-2276).
  high-level-tests/e2e/cypress/integration/pix-app/user-dashboard.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  high-level-tests/e2e/cypress/support/step_definitions/user-dashboard.js
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/dashboard/content.js
  mon-pix/app/components/resume-campaign-banner.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/user-dashboard.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_navbar-mobile-header.scss
  mon-pix/app/styles/components/_new-information.scss
  mon-pix/app/styles/components/_resume-campaign-banner.scss
  mon-pix/app/templates/components/navbar-header.hbs
  mon-pix/app/templates/components/new-information.hbs
  mon-pix/app/templates/components/resume-campaign-banner-collect-profile.hbs
  mon-pix/app/templates/components/resume-campaign-banner.hbs
  mon-pix/app/templates/profile.hbs
  mon-pix/mirage/factories/user.js
  mon-pix/public/images/profile_collect_TDB_pix.svg
  mon-pix/tests/acceptance/profile-test.js
  mon-pix/tests/acceptance/user-dashboard-test.js
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/tests/integration/components/resume-campaign-banner-test.js
  mon-pix/tests/unit/components/dashboard/content-test.js
  mon-pix/tests/unit/components/resume-campaign-banner-test.js
  mon-pix/tests/unit/routes/user-dashboard-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2706 [BUGFIX] Mettre le markdown sur la bonne réponse des QCU (PIX-2350).
  mon-pix/app/components/qcu-solution-panel.js
  mon-pix/app/styles/components/_qcu-solution-panel.scss
  mon-pix/app/templates/components/qcu-solution-panel.hbs
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/challenge-qcu-test.js
  mon-pix/tests/integration/components/qcu-solution-panel-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2702 [FEATURE] Traduire en anglais la page "Mon Equipe" et la modale de suppression dans Pix Orga (PIX-2222).
  orga/app/components/dropdown/icon-trigger.hbs
  orga/app/components/routes/authenticated/team/items.hbs
  orga/app/components/routes/authenticated/team/items.js
  orga/app/components/routes/authenticated/team/members.hbs
  orga/app/models/membership.js
  orga/app/templates/authenticated/team/list.hbs
  orga/tests/acceptance/team-creation-test.js
  orga/tests/integration/components/dropdown/icon-trigger-test.js
  orga/tests/integration/components/routes/authenticated/team/items-test.js
  orga/tests/integration/components/routes/authenticated/team/members-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#2681 [TECH] Supprimer la détection de lien invalides dans la CI.
  .circleci/config.yml
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#2718 [CERTIF] Changer le contenu du bandeau sur l'ajout de candidats (PIX-2352)
  certif/app/templates/authenticated/sessions/add-student.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2717 [FEATURE] Ajout du Markdown dans le champ réponses des QCM (PIX-2290).
  mon-pix/app/styles/components/_qcm-solution-panel.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
  mon-pix/app/templates/components/qcm-proposals.hbs
  mon-pix/app/templates/components/qcm-solution-panel.hbs
  mon-pix/mirage/factories/challenge.js
  mon-pix/tests/acceptance/challenge-qcm-test.js
  mon-pix/tests/integration/components/qcm-solution-panel-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2701 [ADMIN] Organiser les compétences par rapport à leur index (Pix-2341)
  admin/app/components/target-profiles/details.js
  admin/app/models/competence.js
  admin/tests/unit/components/target-profiles/details-test.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2601 [TECH] Récupération de la dernière release du référentiel chaque jour.
  api/lib/infrastructure/lcms.js
  api/tests/test-helper.js
  api/tests/unit/infrastructure/lcms_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2722 [FEATURE] Ouvrir le lien de la documentation vers un nouvel onglet (PIX-2338)
  orga/app/templates/authenticated/certifications.hbs
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#2699 [FIX] Le bouton "Annuler" doit rediriger vers la page de présentation de la campagne (PIX-2336)
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2707 [TECH] Envoi les résultats de test des tests e2e
  .circleci/config.yml
  high-level-tests/e2e/package.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2725 [CLEANUP] Déplacer le composant feedback dans le composant global des challenges (PIX-2372).
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2720 [FEATURE] Afficher le nombre de sessions à traiter dans le libellé de l'onglet (PIX-2298)
  admin/app/controllers/authenticated/sessions/list.js
  admin/app/routes/authenticated/sessions/list.js
  admin/app/routes/authenticated/sessions/list/with-required-action.js
  admin/app/templates/authenticated/sessions/list.hbs
  admin/tests/acceptance/sessions-list-test.js
  admin/tests/unit/routes/authenticated/sessions/list-test.js
Labels: :rocket: Ready to Merge, team-certif

#2729 [FEATURE] Changer le wording sur la page Certification dans Pix Orga (PIX-2378)
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2679 [FEATURE] Notifier l'utilisateur de son changement d'email (PIX-2088).
  api/lib/application/users/user-controller.js
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/update-user-email.js
  api/lib/infrastructure/mailers/mailer.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/users/users-controller-patch-email_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/update-user-email_test.js
  api/translations/en.json
  api/translations/fr.json
  mon-pix/app/routes/application.js
  mon-pix/tests/unit/routes/application-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2711 [FEATURE] Traduction des sujets d'e-mails et correction de l'url du support (PIX-2321).
  api/lib/domain/services/mail-service.js
  api/tests/unit/domain/services/mail-service_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2731 [FEATURE] Ajout d'un onglet Neutralisation dans le détail d'une certification sur Pix Admin (PIX-2357)
  admin/app/router.js
  admin/app/routes/authenticated/certifications/certification/neutralization.js
  admin/app/templates/authenticated/certifications/certification.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2727 [TECH] Remplacer IE9 par IE11 comme navigateur le plus "vieux" à supporter sur mon-pix (PIX-2375)
  admin/config/targets.js
  certif/config/targets.js
  mon-pix/config/targets.js
  orga/config/targets.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2719 [FEATURE] Afficher le status du CléA dans le fichier des résultats de certification (PIX-2339)
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/tooling/domain-builder/factory/build-certification-result.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2657 [CLEANUP] Glimmerizer les composant login-form et register-form (PIX-2322).
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/templates/components/routes/login-form.hbs
  mon-pix/app/templates/components/routes/register-form.hbs
  mon-pix/tests/integration/components/routes/login-form-test.js
  mon-pix/tests/integration/components/routes/register-form-test.js
  mon-pix/tests/unit/components/routes/login-form-test.js
Labels: :rocket: Ready to Merge, cross-team

#2745 [CLEANUP] Supprimer G-Recaptcha (PIX-2384).
  api/lib/application/users/user-controller.js
  api/lib/config.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/create-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/validators/grecaptcha-validator.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
  mon-pix/app/components/g-recaptcha.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/models/user.js
  mon-pix/app/services/google-recaptcha.js
  mon-pix/app/templates/components/g-recaptcha.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/config/environment.js
  mon-pix/mirage/factories/user.js
  mon-pix/tests/integration/components/g-recaptcha-test.js
  mon-pix/tests/integration/components/signup-form-test.js
  mon-pix/tests/unit/components/g-recaptcha-test.js
Labels: :rocket: Ready to Merge, cross-team

#2716 [FEATURE] PixScore = 0 pour certificats Livret-scolaire non validés (PIX-2362)
  api/lib/domain/read-models/livret-scolaire/Certificate.js
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
Labels: :rocket: Ready to Merge, team-certif

#2746 [BUGFIX] Pouvoir désactiver l'envoi d'e-mails.
  api/lib/infrastructure/mailers/mailer.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2735 [FEATURE] Validation du champ "Numéro de session" sur la page "Rejoindre une session" (PIX-2379)
  mon-pix/app/components/certification-joiner.js
  mon-pix/app/styles/components/_certification-joiner.scss
  mon-pix/app/templates/components/certification-joiner.hbs
  mon-pix/tests/integration/components/certification-joiner-test.js
  mon-pix/tests/unit/components/certification-joiner-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#2741 [TECH] Mise à jour des dépendances de pix-api.
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team, team-captains

#2734 [BUGFIX] Corriger l'erreur renvoyée lors d'un changement de mot de passe pour un utilisateur sans adresse e-mail (PIX-2367).
  api/lib/domain/usecases/update-user-password.js
  api/tests/unit/domain/usecases/update-user-password_test.js
  mon-pix/app/components/reset-password-form.js
  mon-pix/app/routes/reset-password.js
  mon-pix/tests/integration/components/reset-password-form-test.js
  mon-pix/tests/unit/components/reset-password-form-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2704 [FEATURE] Traduire en anglais la page de connexion de Pix Orga (PIX-2221).
  api/lib/application/http-errors.js
  api/tests/acceptance/application/authentication-controller_test.js
  orga/app/components/routes/login-form.hbs
  orga/app/components/routes/login-form.js
  orga/app/routes/application.js
  orga/app/services/url.js
  orga/app/templates/login.hbs
  orga/tests/acceptance/join-test.js
  orga/tests/integration/components/routes/login-form-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2712 [FEATURE][i18n] Ajout de l'internationalisation dans le modèle d'import SUP (PIX-2309).
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/get-schooling-registrations-csv-template.js
  api/lib/infrastructure/serializers/csv/higher-schooling-registration-columns.js
  api/lib/infrastructure/serializers/csv/higher-schooling-registration-parser.js
  api/lib/plugins.js
  api/tests/acceptance/application/organizations/organization-controller-import-higher-schooling-registration_test.js
  api/tests/integration/domain/usecases/import-higher-schooling-registrations_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/get-schooling-registrations-csv-template_test.js
  api/tests/unit/infrastructure/serializers/csv/higher-schooling-registration-parser_test.js
  api/translations/en.json
  api/translations/fr.json
  orga/app/components/routes/authenticated/sup-students/list-items.js
  orga/app/controllers/authenticated/sup-students/list.js
  orga/tests/integration/components/routes/authenticated/sup-students/list-items-test.js
  orga/tests/unit/controllers/authenticated/sup-students/list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2650 [DOC] ADR sur le choix de Graviteeio comme API management de Pix.
  docs/adr/0019-typer-les-identifiants.md
  docs/adr/0021-gravitee-pix-apim.md
Labels: :rocket: Ready to Merge, cross-team

#2703 [FEATURE] Afficher la nouvelle solution d'une épreuve si présente dans Airtable (PIX-2265).
  api/lib/domain/models/Correction.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/tooling/fixtures/infrastructure/challengeLearningContentDataObjectFixture.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
  mon-pix/app/components/comparison-window.js
  mon-pix/app/components/qcm-solution-panel.js
  mon-pix/app/components/qcu-solution-panel.js
  mon-pix/app/components/qroc-solution-panel.js
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/app/components/qrocm-ind-solution-panel.js
  mon-pix/app/models/correction.js
  mon-pix/app/styles/components/_comparison-window.scss
  mon-pix/app/styles/components/_qroc-solution-panel.scss
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/qcm-solution-panel.hbs
  mon-pix/app/templates/components/qroc-solution-panel.hbs
  mon-pix/app/templates/components/qrocm-dep-solution-panel.hbs
  mon-pix/app/templates/components/qrocm-ind-solution-panel.hbs
  mon-pix/tests/acceptance/challenge-qroc-test.js
  mon-pix/tests/integration/components/comparison-window-test.js
  mon-pix/tests/integration/components/qcm-solution-panel-test.js
  mon-pix/tests/integration/components/qcu-solution-panel-test.js
  mon-pix/tests/integration/components/qroc-solution-panel-test.js
  mon-pix/tests/integration/components/qrocm-dep-solution-panel-test.js
  mon-pix/tests/integration/components/qrocm-ind-solution-panel-test.js
  mon-pix/tests/unit/components/comparison-window-test.js
  mon-pix/tests/unit/components/qroc-solution-panel-test.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2705 [FEATURE] Sauvegarder le temps passé sur une épreuve (PIX-2260).
  api/db/database-builder/factory/build-answer.js
  api/db/database-builder/factory/build-assessment.js
  api/db/migrations/20210310110213_add-last-question-date-in-assesments-table.js
  api/db/migrations/20210311142327_add-column-timespent-in-answers.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/events/ChallengeRequested.js
  api/lib/domain/events/handle-challenge-requested.js
  api/lib/domain/events/index.js
  api/lib/domain/models/Answer.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/utils/date-utils.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-competence-evaluation_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/tooling/domain-builder/factory/build-answer.js
  api/tests/tooling/domain-builder/factory/build-assessment.js
  api/tests/unit/application/answers/answer-controller_test.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/domain/events/event-choreography-badge-acquisition_test.js
  api/tests/unit/domain/events/event-choreography-compute-validated-skills-count_test.js
  api/tests/unit/domain/events/event-choreography-finalized-session_test.js
  api/tests/unit/domain/events/event-choreography-pole-emploi-participation-finished_test.js
  api/tests/unit/domain/events/event-choreography-pole-emploi-participation-shared_test.js
  api/tests/unit/domain/events/event-choreography-pole-emploi-participation-started_test.js
  api/tests/unit/domain/events/event-choreography-score-certification_test.js
  api/tests/unit/domain/events/event-choreography-score-partner-certification_test.js
  api/tests/unit/domain/events/handle-challenge-requested_test.js
  api/tests/unit/domain/models/Answer_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  docs/adr/0010-propager-domain-events-via-event-dispatcher.md
Labels: :rocket: Ready to Merge, team-evaluation

#2743 [FEATURE] Traduction de la modal de gestion du compte d'un élève dans Pix Orga (PIX-2226).
  high-level-tests/e2e/cypress/integration/pix-orga/sco-student-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/student.js
  orga/app/components/manage-authentication-method-modal.hbs
  orga/app/components/manage-authentication-method-modal.js
  orga/app/components/modal/dialog.hbs
  orga/tests/acceptance/sco-student-list-test.js
  orga/tests/integration/components/edit-student-number-modal-test.js
  orga/tests/integration/components/manage-authentication-method-modal-test.js
  orga/tests/integration/components/modal/dialog-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2721 [FEATURE] Modifier les champs prescriberTitle et prescriberDescription d'un palier(PIX-2314)
  admin/app/components/stages/stage.hbs
  admin/app/components/stages/update-stage.hbs
  admin/app/components/stages/update-stage.js
  admin/app/components/target-profiles/stages.hbs
  admin/app/controllers/authenticated/stages/stage.js
  admin/app/models/stage.js
  admin/app/router.js
  admin/app/routes/authenticated/stages/stage.js
  admin/app/styles/components/target-profiles/stages.scss
  admin/app/templates/authenticated/stages.hbs
  admin/app/templates/authenticated/stages/stage.hbs
  admin/tests/integration/components/stages/stage-test.js
  admin/tests/integration/components/stages/update-stage-test.js
  admin/tests/integration/components/target-profiles/stages_test.js
  admin/tests/unit/components/update-stage-test.js
  admin/tests/unit/controllers/stages/stage-test.js
  api/db/database-builder/factory/build-stage.js
  api/lib/application/stages/index.js
  api/lib/application/stages/stages-controller.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/get-stage-details.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-stage.js
  api/lib/infrastructure/repositories/stage-repository.js
  api/lib/infrastructure/serializers/jsonapi/stage-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/stage-repository_test.js
  api/tests/unit/application/stages/index_test.js
  api/tests/unit/application/stages/stages-controller_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/domain/usecases/get-stage-details_test.js
  api/tests/unit/domain/usecases/update-stage_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/stage-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2514 [TECH] Utiliser les snapshots pour calculer les resultats d'une participation à une campagne d'évaluation afin de les afficher au participant (PIX-2121).
  api/db/database-builder/factory/index.js
  api/db/database-builder/factory/knowledge-elements-snapshot-factory.js
  api/lib/application/campaign-participation-results/campaign-participation-result-controller.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-result-repository_test.js
  api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2751 [BUGFIX] Envoyer une réponse sur une épreuve en preview
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2750 [TECH] Mettre à jour notre addon ember-cli-matomo-tag-manager
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2738 [FEATURE] Traduire en anglais la page "Mon équipe / Invitations" dans Pix Orga (PIX-2225).
  orga/app/components/routes/authenticated/team/invitations.hbs
  orga/app/templates/authenticated/team/list.hbs
  orga/tests/integration/components/routes/authenticated/team/invitations-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#2740 [TECH] Mise à jour de la DB browserlist pour toutes les applications front (PIX-2383)
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2753 [TECH] Ajout de traductions sur la page "Certifications" dans Pix-Orga (PIX-2391)
  orga/translations/en.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2756 [TECH] Traduction du mot d'aide/erreur lors de la mauvaise saisie du numéro de session lors de l'accès à la certification sur PixApp (PIX-2394)
  mon-pix/translations/en.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2763 [BUGFIX] Garder la langue quand je suis connecté en simplifié/anonyme.
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/domain/usecases/authenticate-anonymous-user.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/integration/application/authentication/index_test.js
  api/tests/unit/domain/usecases/authenticate-anonymous-user_test.js
  mon-pix/app/authenticators/anonymous.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, team-acces

#2760 [BUGFIX] Mauvaise classe dans l'export des résultats d'une campagne de collecte de profils (PIX-2366)
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-info-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2709 [CLEANUP] Refactoring du scoring en vue de la neutralisation d'épreuve (Pix-2377)
  api/lib/domain/models/CertificationContract.js
  api/lib/domain/models/CertifiedLevel.js
  api/lib/domain/models/CertifiedScore.js
  api/lib/domain/models/CompetenceAnswerCollectionForScoring.js
  api/lib/domain/models/ReproducibilityRate.js
  api/lib/domain/services/certification-result-service.js
  api/tests/unit/domain/models/CertifiedLevel_test.js
  api/tests/unit/domain/models/CertifiedScore_test.js
  api/tests/unit/domain/models/CompetenceAnswerCollectionForScoring_test.js
  api/tests/unit/domain/models/ReproducibilityRate_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2767 [BUGFIX] Modifier la sauvegarde du temps sur l'assessment.
  api/lib/application/assessments/assessment-controller.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
Labels: :rocket: Ready to Merge, Tech Review OK

#2736 [FEATURE] Traduction des erreurs de l'import XML SIECLE (Pix-2313).
  api/lib/application/error-manager.js
  api/lib/application/http-errors.js
  api/lib/application/organizations/index.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/import-schooling-registrations-from-siecle.js
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/lib/infrastructure/serializers/xml/siecle-parser.js
  api/lib/infrastructure/serializers/xml/xml-schooling-registration-set.js
  api/lib/infrastructure/utils/xml/siecle-file-streamer.js
  api/scripts/helpers/csvHelpers.js
  api/tests/acceptance/application/organizations/organization-controller-import-higher-schooling-registration_test.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/services/schooling-registrations-xml-service_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/import-schooling-registrations-from-siecle_test.js
  api/tests/unit/infrastructure/serializers/csv/schooling-registration-parser_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  orga/app/controllers/authenticated/sco-students/list.js
  orga/app/controllers/authenticated/sup-students/list.js
  orga/app/services/error-messages.js
  orga/app/services/notifications.js
  orga/mirage/config.js
  orga/tests/acceptance/sco-student-list-test.js
  orga/tests/unit/controllers/authenticated/sco-students/list-test.js
  orga/tests/unit/controllers/authenticated/sup-students/list-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2752 [BUGFIX] Mettre le score à 0 pour un certificat validé non publié (PIX-2396)
  api/lib/domain/read-models/livret-scolaire/Certificate.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certifications-results-for-ls.js
Labels: :rocket: Ready to Merge, team-certif

#2754 [BUGFIX] Permettre aux étudiants faisant partie d'une orga SCO non isManagingStudents d'entrer en certif (PIX-2388)
  api/lib/domain/models/Organization.js
  api/lib/domain/usecases/link-user-to-session-certification-candidate.js
  api/lib/infrastructure/repositories/certification-center-repository.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/session-repository.js
  api/tests/acceptance/application/session/session-controller-create-certification-candidate-participation_test.js
  api/tests/integration/infrastructure/repositories/certification-center-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/domain/models/Organization_test.js
  api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2744 [FEATURE] Permettre dans pix Admin de marquer comme obsolète un profil cible (Pix-2309).
  admin/app/components/confirm-popup.hbs
  admin/app/components/confirm-popup.js
  admin/app/components/target-profiles/update-target-profile-name.js
  admin/app/controllers/authenticated/target-profiles/target-profile.js
  admin/app/models/target-profile.js
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/mirage/config.js
  admin/mirage/handlers/target-profiles.js
  admin/tests/acceptance/target-profiles-details-test.js
  admin/tests/helpers/extended-ember-test-helpers/click-by-label.js
  admin/tests/helpers/extended-ember-test-helpers/fill-in-by-label.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/outdate-target-profile.js
  api/lib/domain/usecases/update-target-profile-name.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/domain/usecases/outdate-target-profile_test.js
  api/tests/unit/domain/usecases/update-target-profile-name_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2761 [FEATURE] Masquer le lien de récupération d'espace Orga sur la page de connexion Pix Orga pour pix.org (PIX-2398).
  orga/app/components/routes/login-form.js
  orga/app/services/url.js
  orga/tests/integration/components/routes/login-form-test.js
  orga/tests/unit/services/url-test.js
Labels: :rocket: Ready to Merge, team-acces

#2755 [FEATURE] Ajout du markdown sur le champ réponses des QROC (PIX-2291).
  mon-pix/app/initializers/register-showdown-extensions.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_qroc-proposals.scss
  mon-pix/app/templates/components/qroc-proposal.hbs
  mon-pix/mirage/factories/challenge.js
  mon-pix/tests/acceptance/challenge-qroc-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2765 [FEATURE] Ajout de sous-catégories de signalements pour les liens (PIX-1640).
  mon-pix/app/static-data/feedback-panel-issue-labels.js
  mon-pix/tests/acceptance/challenge-feedback-test.js
  mon-pix/tests/integration/components/feedback-panel-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2739 [TECH] Réparer la configuration de débogage VSCode.
  .vscode/sample.launch.json
  .vscode/sample.settings.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2777 [FEATURE] A11Y- Ajout d'un aria-label hidden pour ne pas tenter de lire le svg du cercle (PIX-1883).
  mon-pix/app/templates/components/circle-chart.hbs
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2768 [TECH] Ajout de champs pour la personnalisation de la page de fin de parcours (PIX-2326)
  api/db/migrations/20210325103306_add-custom-fields-to-campaign.js
  api/lib/domain/models/Campaign.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2776 [FEATURE] Changer le titre de la page quand l'épreuve timée est terminée (PIX-2283).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2770 [FEAT] Ajout d'avertissements sur la modale de remise à zéro (PIX-2365).
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2759 [FEATURE] Ajout du markdown sur le champ réponses des QROCm (PIX-2292).
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/app/components/qrocm-ind-solution-panel.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_qrocm-proposals.scss
  mon-pix/app/styles/components/_qrocm-solution-panel.scss
  mon-pix/app/templates/components/qrocm-dep-solution-panel.hbs
  mon-pix/app/templates/components/qrocm-ind-solution-panel.hbs
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/mirage/factories/challenge.js
  mon-pix/package-lock.json
  mon-pix/tests/acceptance/challenge-qrocm-test.js
  mon-pix/tests/integration/components/qrocm-ind-solution-panel-test.js
  mon-pix/tests/integration/components/qrocm-proposal-test.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel-test.js
  mon-pix/tests/unit/components/qrocm-ind-solution-panel-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2782 [CLEANUP] Suppression du domain event ChallengeRequested (PIX-2410)
  api/lib/domain/events/ChallengeRequested.js
  api/lib/domain/events/handle-challenge-requested.js
  api/lib/domain/events/index.js
  api/tests/unit/domain/events/handle-challenge-requested_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2749 [FEATURE] Ajout d'un bouton vers "Tous mes parcours" depuis la page du tableau de bord de Pix App (PIX-2335).
  mon-pix/app/components/campaign-participation-overview/card/archived.hbs
  mon-pix/app/components/campaign-participation-overview/card/ended.hbs
  mon-pix/app/components/campaign-participation-overview/card/ongoing.hbs
  mon-pix/app/components/campaign-participation-overview/card/to-share.hbs
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/user-certifications-detail-header.js
  mon-pix/app/services/intl-date-formatter.js
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
  mon-pix/app/templates/components/certifications-list-item.hbs
  mon-pix/app/templates/components/user-certifications-detail-header.hbs
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/tests/unit/services/intl-date-formatter-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif, team-evaluation, team-prescription

#2779 [FEATURE] Ajouter un lien vers la FAQ "Comment se certifier" sur le bandeau "Bravo vous êtes certifiable" (PIX-2400)
  mon-pix/app/styles/components/_congratulations-certification-banner.scss
  mon-pix/app/templates/components/congratulations-certification-banner.hbs
  mon-pix/config/icons.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2766 [FEATURE] Ajouter l'id de campaign-participation au modèle badge-acquisition (PIX-2287).
  api/db/database-builder/factory/build-badge-acquisition.js
  api/db/migrations/20210324101030_add-campaign-participation-to-badge-acquisitions-table.js
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/events/handle-badge-acquisition.js
  api/lib/domain/models/BadgeAcquisition.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/tooling/domain-builder/factory/build-badge-acquisition.js
  api/tests/unit/domain/events/handle-badge-acquisition_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2773 [DOCS] Proposition de bonnes pratiques autour du testing de textes traduits sur les applications front Ember (PIX-2418)
  docs/Ember.md
  orga/tests/integration/components/routes/authenticated/campaign/new-test.js
  orga/tests/unit/services/error-messages-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2758 [FEATURE] Traduire en anglais la double mire dans Pix Orga (PIX-2227).
  api/lib/domain/usecases/create-user.js
  api/lib/domain/validators/user-validator.js
  api/tests/integration/domain/usecases/create-and-reconcile-user-to-schooling-registration_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/domain/validators/user-validator_test.js
  api/translations/en.json
  api/translations/fr.json
  orga/app/components/routes/login-or-register.hbs
  orga/app/components/routes/register-form.hbs
  orga/app/components/routes/register-form.js
  orga/app/styles/globals/errors.scss
  orga/tests/acceptance/join-test.js
  orga/tests/integration/components/routes/login-or-register-test.js
  orga/tests/integration/components/routes/register-form-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#2724 [TECH] Ajout de test d'accessibilité dans nos tests E2E.
  high-level-tests/e2e/cypress/integration/pix-app/demo.feature
  high-level-tests/e2e/cypress/integration/pix-app/login-logout-app.feature
  high-level-tests/e2e/cypress/support/index.js
  high-level-tests/e2e/cypress/support/step_definitions/accessibility.js
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/components/progress-bar.hbs
  mon-pix/app/templates/not-connected.hbs
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2778 [FEATURE] Gérer le focus des PixModal lors de l'entrée et la sortie (PIX-1870).
  high-level-tests/e2e/cypress/integration/pix-app/page-title.feature
  mon-pix/app/components/pix-modal.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco-information-modal.hbs
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/templates/competences.hbs
  mon-pix/app/templates/competences/details.hbs
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/result-item.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2748 [FEATURE] Script de création d'organisations PRO en masse depuis un fichier CSV (PIX-2278).
  api/lib/domain/errors.js
  api/lib/domain/models/Organization.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/domain/usecases/create-pro-organizations-with-tags.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/organization-tag-repository.js
  api/lib/infrastructure/repositories/tag-repository.js
  api/scripts/create-pro-organizations-with-tags.js
  api/tests/integration/domain/usecases/create-pro-organization-with-tags_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-tag-repository_test.js
  api/tests/integration/infrastructure/repositories/tag-repository_test.js
  api/tests/unit/domain/models/Organization_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/domain/usecases/create-pro-organizations-with-tags_test.js
Labels: :rocket: Ready to Merge, team-acces

#2795 [TECH] Mise à jour des dépendances Ember de pix-admin 3.23.1 --> 3.25.3
  admin/app/controllers/authenticated/certifications/certification/details.js
  admin/app/templates/authenticated/certifications/certification/details.hbs
  admin/config/ember-cli-update.json
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/target-profiles/insight-test.js
  admin/tests/acceptance/authenticated/target-profiles/organizations-test.js
  admin/tests/index.html
  admin/tests/test-helper.js
  admin/tests/unit/controllers/authenticated/certifications/certification/details-test.js
Labels: :rocket: Ready to Merge, cross-team

#2794 <°)))><
  api/lib/config.js
  api/tests/acceptance/application/feature-controller_tests.js
  mon-pix/app/components/hexagon-score.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/app/templates/components/hexagon-score.hbs
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/tests/integration/components/hexagon-score-test.js
  mon-pix/tests/integration/components/profile-content-test.js
  mon-pix/tests/unit/components/hexagon-score-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team
