Repository 1024pix/pix, pull requests merged in 2021-10, with the labels that each got.

#3528 [FEATURE] Ajoute le filtre sur la colonne statuts dans l'onglet activité (PIX-2667)
  api/lib/application/campaigns/index.js
  api/lib/domain/read-models/CampaignParticipantActivity.js
  api/lib/infrastructure/repositories/campaign-participant-activity-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-participant-activity-repository_test.js
  api/tests/unit/domain/read-models/CampaignParticipantActivity_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participant-activity-serializer_test.js
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/activity/participation-status.js
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/campaign/filter/participation-filters.js
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/routes/authenticated/campaigns/campaign/activity.js
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/integration/components/campaign/activity/participants-activity-list_test.js
  orga/tests/integration/components/campaign/filter/participation-filters_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3522 [FEATURE] Réutiliser le champ résultat pour les exports CSV des deux campagnes (PIX-3066).
  api/lib/domain/read-models/CampaignParticipationInfo.js
  api/lib/infrastructure/exports/campaigns/campaign-profiles-collection-result-line.js
  api/lib/infrastructure/repositories/campaign-participation-info-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-info-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-info.js
  api/tests/unit/domain/read-models/CampaignParticipationInfo_test.js
  api/tests/unit/infrastructure/exports/campaigns/campaign-profile-collection-result-line_test.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3537 [TECH] Mise à jour d'ember-template-lint dans Pix Orga.
  orga/.template-lintrc.js
  orga/app/components/auth/join-request-form.hbs
  orga/app/components/auth/login-form.hbs
  orga/app/components/auth/register-form.hbs
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/update-form.hbs
  orga/app/components/dropdown/item.hbs
  orga/app/components/dropdown/item.js
  orga/app/components/student/sup/edit-student-number-modal.hbs
  orga/app/components/team/invite-form.hbs
  orga/app/components/ui/search-input.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#3543 [FEATURE] Ajoute la colonne "groupe" sur la page "Étudiants" pour les orgas SUP isManagingStudent. (PIX-3536)
  api/lib/domain/models/UserWithSchoolingRegistration.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer_test.js
  orga/app/components/student/sup/list.hbs
  orga/app/models/student.js
  orga/tests/integration/components/students/sup/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3535 [FEATURE] Cacher les élèves désactivés de la liste des élèves pouvant être inscrits à une session de certification (PIX-3163).
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3533 [FEATURE] Arrondir à l'entier supérieur la règle de scoring globale d'une certification (PIX-3527).
  CHANGELOG.md
  admin/package-lock.json
  admin/package.json
  api/lib/domain/models/CertificationContract.js
  api/package-lock.json
  api/package.json
  api/tests/unit/domain/models/CertificationContract_test.js
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3534 [ADMIN] Ne plus bloquer l'enregistrement d'une liste d'organisations si certains sont déjà rattachées à un profil cible (PIX-3456)
  admin/app/components/target-profiles/organizations.js
  admin/mirage/handlers/target-profiles.js
  admin/tests/unit/components/target-profiles/organizations_test.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/usecases/attach-organizations-to-target-profile.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-attach-organization-serializer.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-attach-organization-serializer_test.js
  orga/tests/integration/components/participant/profile/header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3526 [FEATURE] Enregistrer la dernière date de connexion dans le cas du GAR ou de Pôle Emploi (PIX-3510).
  api/lib/application/pole-emplois/pole-emploi-controller.js
  api/lib/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller.js
  api/lib/domain/usecases/authenticate-external-user.js
  api/lib/domain/usecases/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user.js
  api/lib/domain/usecases/get-external-authentication-redirection-url.js
  api/tests/integration/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller_test.js
  api/tests/integration/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/application/schooling-registration-dependent-user/schooling-registration-dependant-user-controller_test.js
  api/tests/unit/domain/usecases/authenticate-external-user_test.js
  api/tests/unit/domain/usecases/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user_test.js
  api/tests/unit/domain/usecases/get-external-authentication-redirection-url_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team

#3496 [TECH] Séparer les différentes logiques d'accès à une campagne (PIX-3181)
  high-level-tests/e2e/cypress/support/index.js
  mon-pix/app/components/campaign-participation-overview/card/ended.hbs
  mon-pix/app/components/campaign-participation-overview/card/ongoing.hbs
  mon-pix/app/components/campaign-participation-overview/card/to-share.hbs
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco-information-modal.js
  mon-pix/app/controllers/campaigns/campaign-landing-page.js
  mon-pix/app/controllers/campaigns/fill-in-participant-external-id.js
  mon-pix/app/controllers/campaigns/restricted/join.js
  mon-pix/app/controllers/campaigns/restricted/login-or-register-to-access.js
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/router.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/campaigns/assessment/skill-review.js
  mon-pix/app/routes/campaigns/campaign-not-found.js
  mon-pix/app/routes/campaigns/entry-point.js
  mon-pix/app/routes/campaigns/profiles-collection/profile-already-shared.js
  mon-pix/app/routes/campaigns/restricted/join.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/logout.js
  mon-pix/app/services/campaign-storage.js
  mon-pix/app/templates/campaigns/campaign-not-found.hbs
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
  mon-pix/app/templates/campaigns/start-or-resume.hbs
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection_test.js
  mon-pix/tests/acceptance/user-dashboard_test.js
  mon-pix/tests/helpers/invalidate-session.js
  mon-pix/tests/test-helper.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review_test.js
  mon-pix/tests/unit/controllers/campaigns/campaign-landing-page_test.js
  mon-pix/tests/unit/controllers/campaigns/fill-in-participant-external-id_test.js
  mon-pix/tests/unit/controllers/campaigns/restricted/join_test.js
  mon-pix/tests/unit/controllers/campaigns/restricted/login-or-register-to-access_test.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code_test.js
  mon-pix/tests/unit/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/routes/campaigns/entry-point_test.js
  mon-pix/tests/unit/routes/campaigns/profiles-collection/profile-already-shared_test.js
  mon-pix/tests/unit/routes/campaigns/restricted/join_test.js
  mon-pix/tests/unit/routes/logout_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#3546 [BUGFIX] Corriger l'affichage du centre de certification courant dans Pix Certif (PIX-3560).
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/routes/authenticated/sessions/add-student.js
  certif/app/routes/authenticated/sessions/details.js
  certif/app/routes/authenticated/sessions/details/certification-candidates.js
  certif/app/routes/authenticated/sessions/finalize.js
  certif/app/routes/authenticated/sessions/update.js
  certif/app/services/current-user.js
  certif/tests/acceptance/authenticated_test.js
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/unit/controllers/authenticated/sessions/details_test.js
  certif/tests/unit/routes/authenticated/sessions/finalize_test.js
  certif/tests/unit/services/current-user_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3530 [FEATURE] Enregistrer la nouvelle adresse e-mail lorsque l'utilisateur entre le code de vérification - API (PIX-3448).
  api/lib/application/error-manager.js
  api/lib/application/http-errors.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/EmailModificationDemand.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/sco-account-recovery-service.js
  api/lib/domain/usecases/create-and-reconcile-user-to-schooling-registration.js
  api/lib/domain/usecases/create-user.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/send-email-for-account-recovery.js
  api/lib/domain/usecases/send-verification-code.js
  api/lib/domain/usecases/update-user-email-with-validation.js
  api/lib/domain/usecases/update-user-email.js
  api/lib/infrastructure/repositories/user-email-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/email-verification-serializer.js
  api/lib/infrastructure/serializers/jsonapi/update-email-serializer.js
  api/tests/acceptance/application/users/send-verification-code-route-put_test.js
  api/tests/acceptance/application/users/update-user-email-with-validation-route-post_test.js
  api/tests/integration/infrastructure/repositories/user-email-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/services/sco-account-recovery-service_test.js
  api/tests/unit/domain/usecases/account-recovery/send-email-for-account-recovery_test.js
  api/tests/unit/domain/usecases/create-and-reconcile-user-to-schooling-registration_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/domain/usecases/send-verification-code_test.js
  api/tests/unit/domain/usecases/update-user-email-with-validation_test.js
  api/tests/unit/domain/usecases/update-user-email_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/email-verification-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/update-email-serializer_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3547 [CLEANUP] Choix des épreuves de certification : clarifie la sélection des épreuves déjà répondues
  api/lib/domain/models/PlacementProfile.js
  api/lib/domain/models/UserCompetence.js
  api/lib/domain/services/certification-challenges-service.js
  api/scripts/generate-certification-test-statistics.js
  api/tests/tooling/domain-builder/factory/build-user-competence.js
  api/tests/unit/domain/models/PlacementProfile_test.js
  api/tests/unit/domain/models/UserCompetence_test.js
Labels: :rocket: Ready to Merge, team-certif

#3549 [FEATURE] Ajout d'un filtre sur la colonne "groupe" sur la page "Étudiants". (PIX-3537)
  api/db/seeds/data/organizations-sup-builder.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-schooling-registrations_test.js
  orga/app/components/student/sup/list.hbs
  orga/app/components/student/sup/list.js
  orga/app/controllers/authenticated/sup-students/list.js
  orga/app/routes/authenticated/sup-students/list.js
  orga/app/templates/authenticated/sup-students/list.hbs
  orga/mirage/handlers/find-filtered-paginated-students.js
  orga/tests/acceptance/sup-student-list_test.js
  orga/tests/integration/components/students/sup/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3556 [TECH] Ajouter stylelint à Pix Admin (PIX-3570).
  admin/.stylelintrc.json
  admin/app/styles/app.scss
  admin/app/styles/authenticated/certification-center/index.scss
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/styles/authenticated/certifications/index.scss
  admin/app/styles/authenticated/organizations/get.scss
  admin/app/styles/authenticated/sessions/list.scss
  admin/app/styles/authenticated/sessions/session/certifications.scss
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/styles/authenticated/tools.scss
  admin/app/styles/components/certification-center-form.scss
  admin/app/styles/components/certification-details-answer.scss
  admin/app/styles/components/certification-details-competence.scss
  admin/app/styles/components/certification-info-field.scss
  admin/app/styles/components/certification-issue-report.scss
  admin/app/styles/components/certification-issue-reports.scss
  admin/app/styles/components/certification/certification-status-select.scss
  admin/app/styles/components/common/tick-or-cross.scss
  admin/app/styles/components/member-item.scss
  admin/app/styles/components/modal.scss
  admin/app/styles/components/organization-form.scss
  admin/app/styles/components/organization-information-section.scss
  admin/app/styles/components/organization-members-section.scss
  admin/app/styles/components/pagination-control.scss
  admin/app/styles/components/publish-session-button.scss
  admin/app/styles/components/target-profiles/badges.scss
  admin/app/styles/components/target-profiles/create-target-profile-form.scss
  admin/app/styles/components/target-profiles/details.scss
  admin/app/styles/components/target-profiles/insight.scss
  admin/app/styles/components/target-profiles/list-items.scss
  admin/app/styles/components/target-profiles/stages.scss
  admin/app/styles/components/user-detail-personal-information-section.scss
  admin/app/styles/globals/button.scss
  admin/app/styles/globals/form.scss
  admin/app/styles/globals/global.scss
  admin/app/styles/globals/nav.scss
  admin/app/styles/globals/power-select.scss
  admin/app/styles/globals/table-admin.scss
  admin/app/styles/globals/tables.scss
  admin/app/styles/login.scss
  admin/package-lock.json
  admin/package.json
Labels: :rocket: Ready to Merge, cross-team

#3227 [TECH] Suppression de classes CSS non utilisées dans Pix-App.
  mon-pix/app/components/campaign-participation-overview/card/archived.hbs
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_checkpoint.scss
  mon-pix/app/styles/components/_comparison-window.scss
  mon-pix/app/styles/components/_footer.scss
  mon-pix/app/styles/components/_navbar-desktop-menu.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/components/_signup-form.scss
  mon-pix/app/styles/components/_tutorial-item.scss
  mon-pix/app/styles/components/_user-account.scss
  mon-pix/app/styles/components/_user-certifications-detail-banner.scss
  mon-pix/app/styles/components/_user-certifications-detail-competence.scss
  mon-pix/app/styles/components/_user-logged-menu.scss
  mon-pix/app/styles/components/campaign-participation-overview/_card.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/globals/_pix-modal.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
  mon-pix/app/styles/pages/_assessment-results.scss
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/styles/pages/_join-restricted-campaign.scss
  mon-pix/app/styles/pages/_profile.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/styles/pages/_user-certifications.scss
  mon-pix/app/templates/components/campaign-start-block.hbs
  mon-pix/app/templates/components/certification-banner.hbs
  mon-pix/app/templates/components/certification-results-page.hbs
  mon-pix/app/templates/components/certifications-list-item.hbs
  mon-pix/app/templates/components/challenge-illustration.hbs
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/app/templates/components/communication-banner.hbs
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/components/qcm-solution-panel.hbs
  mon-pix/app/templates/components/routes/login-form.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/timeout-gauge.hbs
  mon-pix/app/templates/error.hbs
  mon-pix/tests/acceptance/challenge-timed_test.js
  mon-pix/tests/acceptance/compare-answer-solution-qroc_test.js
  mon-pix/tests/integration/components/campaign-start-block_test.js
  mon-pix/tests/integration/components/certifications-list-item_test.js
  mon-pix/tests/integration/components/challenge-illustration_test.js
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/tests/integration/components/comparison-window_test.js
  mon-pix/tests/integration/components/timeout-gauge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#3540 [BUGFIX] Afficher les détails d'un badge dans pix-admin (PIX-3505).
  api/lib/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3563 [BUGFIX] Corriger le type de l'appel PUT /{id}/email/verification-code, coté Pix App (PIX-3576).
  mon-pix/app/components/user-account/email-with-validation-form.js
  mon-pix/app/models/email-verification-code.js
  mon-pix/tests/integration/components/user-account/email-with-validation-form-test.js
  mon-pix/tests/unit/components/user-account/email-with-validation-form-test.js
Labels: :rocket: Ready to Merge, team-acces

#3552 [FEATURE] Modifier le message d'erreur pour les imports SCO (PIX-3515)
  api/lib/infrastructure/utils/xml/siecle-file-streamer.js
  api/tests/integration/infrastructure/utils/xml/siecle-file-streamer_test.js
  orga/tests/unit/controllers/authenticated/sco-students/list_test.js
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3509 [FEATURE] Mettre à jour les informations d'un centre de certifications depuis Pix Admin (PIX-3478)
  admin/app/adapters/certification-center.js
  admin/app/components/certification-center-form.hbs
  admin/app/components/certification-center-form.js
  admin/app/controllers/authenticated/certification-centers/get.js
  admin/app/models/certification-center.js
  admin/app/styles/authenticated/certification-center/index.scss
  admin/app/templates/authenticated/certification-centers/get.hbs
  admin/tests/acceptance/authenticated/certification-centers/get_test.js
  admin/tests/acceptance/certification-center-form-_test.js
  admin/tests/integration/components/certification-center-form_test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get_test.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/models/GrantedAccreditation.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/save-certification-center.js
  api/lib/infrastructure/repositories/certification-center-repository.js
  api/lib/infrastructure/repositories/granted-accreditation-repository.js
  api/lib/infrastructure/serializers/jsonapi/accreditation-serializer.js
  api/tests/integration/infrastructure/repositories/granted-accreditation-repository_test.js
  api/tests/tooling/domain-builder/factory/build-granted-accreditation.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/GrantedAccreditation_test.js
  api/tests/unit/domain/usecases/save-certification-center_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3532 [TECH] Remplacer masteryPercentage par masteryRate (PIX-3496)
  api/db/database-builder/factory/build-campaign-participation.js
  api/db/migrations/20210922124114_rename-masteryPercentage-to-masteryRate.js
  api/lib/domain/models/ParticipantResultsShared.js
  api/lib/domain/read-models/CampaignAssessmentParticipation.js
  api/lib/domain/read-models/CampaignParticipationInfo.js
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/domain/read-models/CampaignReport.js
  api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
  api/lib/domain/usecases/get-campaign.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/lib/infrastructure/repositories/campaign-participation-info-repository.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-participations-stats-repository.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-assessment-result-minimal-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/scripts/prod/compute-participation-results.js
  api/tests/acceptance/application/campaign-stats/campaign-stats-get-participations-count-by-mastery-rate_test.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/integration/domain/usecases/get-campaign-participations-counts-by-stage_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-list-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-info-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participations-stats-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-results-shared-repository_test.js
  api/tests/integration/scripts/prod/compute-participation-results_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-info.js
  api/tests/unit/domain/models/ParticipantResultsShared_test.js
  api/tests/unit/domain/read-models/CampaignAssessmentParticipation_test.js
  api/tests/unit/domain/read-models/CampaignParticipationInfo_test.js
  api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
  api/tests/unit/domain/read-models/CampaignReport_test.js
  api/tests/unit/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal_test.js
  api/tests/unit/domain/usecases/get-campaign_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-result-minimal-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
  high-level-tests/e2e/cypress/fixtures/campaign-participations.json
  mon-pix/app/components/campaign-participation-overview/card/archived.hbs
  mon-pix/app/components/campaign-participation-overview/card/ended.hbs
  mon-pix/app/models/campaign-participation-overview.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/archived_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ended_test.js
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/participant/assessment/header.hbs
  orga/app/models/campaign-assessment-participation.js
  orga/app/models/campaign-assessment-result-minimal.js
  orga/tests/integration/components/campaign/results/assessment-list_test.js
  orga/tests/integration/components/participant/assessment/header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3554 [FEATURE] Permettre le ré-envoie de code de vérification lors d'un changement d'email (PIX-3497)
  mon-pix/app/components/user-account/email-verification-code.hbs
  mon-pix/app/components/user-account/email-verification-code.js
  mon-pix/app/components/user-account/email-with-validation-form.hbs
  mon-pix/app/components/user-account/email-with-validation-form.js
  mon-pix/app/components/user-account/update-email-with-validation.hbs
  mon-pix/app/components/user-account/update-email-with-validation.js
  mon-pix/app/styles/components/user-account/_email-verification-code.scss
  mon-pix/config/environment.js
  mon-pix/tests/integration/components/user-account/email-verification-code-test.js
  mon-pix/tests/integration/components/user-account/email-with-validation-form-test.js
  mon-pix/tests/unit/components/user-account/email-verification-code-test.js
  mon-pix/tests/unit/components/user-account/email-with-validation-form-test.js
  mon-pix/tests/unit/components/user-account/update-email-with-validation-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces
