Repository 1024pix/pix, pull requests merged in 2021-11, with the labels that each got.

#3667 [TECH] Mettre à jour les paquets de l'API.
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, cross-team

#3673 [BUGFIX]: Ajouter un loader pour le chargement du dashboard utilisateur
  mon-pix/app/routes/user-dashboard.js
  mon-pix/app/templates/campaigns/loading.hbs
  mon-pix/app/templates/loading.hbs
Labels: :rocket: Ready to Merge, team-evaluation

#3678 [BUGFIX] Mettre à jour la version d'hapi utilisée
  api/lib/infrastructure/monitoring-tools.js
Labels: :rocket: Ready to Merge, cross-team

#3660 [FEATURE] Afficher dans l'onglet paramètre si l'envoi multiple pour une campagne de collecte de profils est activé ( PIX-3677).
  api/lib/domain/read-models/CampaignReport.js
  api/lib/infrastructure/serializers/jsonapi/campaign-report-serializer.js
  api/tests/tooling/domain-builder/factory/build-campaign-report.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-report-serializer_test.js
  orga/app/components/campaign/settings.hbs
  orga/app/components/campaign/settings.js
  orga/app/models/campaign.js
  orga/tests/integration/components/campaign/settings_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3669 [BUGFIX] Fermer la tooltip dès que l'utilisateur clique dessus (PIX-3708).
  mon-pix/app/components/challenge/statement/tooltip.js
Labels: :rocket: Ready to Merge, team-evaluation

#3681 [BUGFIX] Use https instead of git protocol for pix-ui dependency
  admin/package-lock.json
  admin/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: :rocket: Ready to Merge, team-captains

#3679 [FEATURE] Assurer le type d'un centre de certification (PIX-3777).
  api/db/migrations/20211029181054_set-certification-center-type-as-not-null.js
  api/db/seeds/data/certification/certification-center-memberships-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/tests/integration/infrastructure/repositories/certification-center-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3659 [FEATURE] Affiche les ids des profils cibles dupliqués lors du rattachement à une organisation (PIX-3468).
  admin/app/components/organization-target-profiles-section.hbs
  admin/app/components/organization-target-profiles-section.js
  admin/app/controllers/authenticated/organizations/get/target-profiles.js
  admin/app/models/organization.js
  admin/app/templates/authenticated/organizations/get/target-profiles.hbs
  admin/mirage/handlers/target-profiles.js
  admin/tests/integration/components/organization-target-profiles-section_test.js
  admin/tests/unit/components/organization-target-profiles-section_test.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/attach-target-profiles-to-organization.js
  api/lib/infrastructure/repositories/target-profile-share-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-attach-target-profiles-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/target-profile-share-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/attach-target-profiles-to-organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-attach-target-profiles_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3666 [FEATURE] Compléter le wording pour les établissements qui se connecte sur Pix Orga (PIX-3695).
  orga/app/components/auth/login-form.hbs
  orga/app/templates/join-request.hbs
  orga/app/templates/login.hbs
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3653 [FEATURE] Permettre la création de campagne de collecte à envoi multiple (PIX-3674).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/create-form.js
  orga/app/models/campaign.js
  orga/app/styles/globals/forms.scss
  orga/tests/acceptance/campaign-creation_test.js
  orga/tests/helpers/testing-library.js
  orga/tests/integration/components/campaign/create-form_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3677 [FEATURE] Autoriser l'accès à l'espace surveillant après entrée d'un numéro de session et mot de passe valide (PIX-3729).
  api/db/database-builder/factory/build-session.js
  api/db/migrations/20211103094329_create-table-supervisor-accesses.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-for-supervising-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/supervise-session.js
  api/lib/infrastructure/repositories/supervisor-access-repository.js
  api/tests/acceptance/application/session/session-for-supervising-controller-supervise_test.js
  api/tests/integration/infrastructure/repositories/supervisor-access-repository_test.js
  api/tests/unit/application/session/session-for-supervising-controller_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/supervise-session_test.js
  certif/app/adapters/supervisor-authentication.js
  certif/app/components/login-session-supervisor-form.hbs
  certif/app/components/login-session-supervisor-form.js
  certif/app/controllers/login-session-supervisor.js
  certif/app/models/supervisor-authentication.js
  certif/app/routes/login-session-supervisor.js
  certif/app/templates/login-session-supervisor.hbs
  certif/mirage/config.js
  certif/tests/acceptance/supervisor-portal-access_test.js
  certif/tests/integration/components/login-session-supervisor-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3680 [BUGFIX] Mettre à jour le menu après la déconnexion via la page de lancement d'une campagne (PIX-3722)
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/tests/acceptance/user-dashboard_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3682 [BUGFIX] Afficher les habilitations disponibles dans un ordre constant (PIX-3778).
  admin/app/components/certification-centers/information.hbs
  admin/app/components/certification-centers/information.js
  admin/app/controllers/authenticated/certification-centers/get.js
  admin/tests/integration/components/certification-centers/information_test.js
  admin/tests/unit/components/certification-centers/information_test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#3649 [FEATURE] Pouvoir avoir la première question lors d'une campagne FLASH (PIX-2780).
  api/lib/domain/models/Challenge.js
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/infrastructure/datasources/learning-content/challenge-datasource_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3622 [TECH] Utiliser la librairie 1024pix/ember-testing-library dans les tests Pix Admin.
  admin/app/components/target-profiles/list-items.hbs
  admin/app/controllers/authenticated/target-profiles/list.js
  admin/app/templates/authenticated/target-profiles/list.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/certification-centers/get_test.js
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/acceptance/certification-center-form_test.js
  admin/tests/acceptance/organization-information-management_test.js
  admin/tests/acceptance/organization-memberships-management_test.js
  admin/tests/helpers/extended-ember-test-helpers/click-by-label.js
  admin/tests/helpers/extended-ember-test-helpers/fill-in-by-label.js
  admin/tests/helpers/testing-library.js
  admin/tests/integration/components/certification-centers/information_test.js
  admin/tests/integration/components/certification/candidate-edit-modal_test.js
  admin/tests/integration/components/organization-members-actions-section_test.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#3664 [TECH] Utiliser ember-testing-library dans les tests de Pix Orga
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/sup-student-list_test.js
  orga/tests/helpers/contains.js
  orga/tests/helpers/testing-library.js
  orga/tests/integration/components/students/sup/list_test.js
  orga/tests/integration/components/ui/divisions-filter_test.js
  orga/tests/integration/components/ui/groups-filter_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, cross-team

#3651 [FEATURE] Afficher les invitations de membre en attente d'une organisation sur Pix Admin (PIX-397).
  .eslintrc.yaml
  admin/app/adapters/organization-invitation.js
  admin/app/components/organization-invitations-action.hbs
  admin/app/components/organization-invitations-action.js
  admin/app/components/organization-invitations.hbs
  admin/app/components/organization-invitations.js
  admin/app/components/organization-team-actions-section.hbs
  admin/app/components/organization-team-section.hbs
  admin/app/components/organization-team-section.js
  admin/app/controllers/authenticated/organizations/get/invitations.js
  admin/app/controllers/authenticated/organizations/get/team.js
  admin/app/models/organization-invitation.js
  admin/app/router.js
  admin/app/routes/authenticated/organizations/get/index.js
  admin/app/routes/authenticated/organizations/get/invitations.js
  admin/app/routes/authenticated/organizations/get/team.js
  admin/app/styles/app.scss
  admin/app/styles/components/organization-invitations.scss
  admin/app/styles/components/organization-members-section.scss
  admin/app/styles/components/organization-team-section.scss
  admin/app/templates/authenticated.hbs
  admin/app/templates/authenticated/certifications/certification.hbs
  admin/app/templates/authenticated/certifications/certification/details.hbs
  admin/app/templates/authenticated/certifications/certification/neutralization.hbs
  admin/app/templates/authenticated/certifications/certification/profile.hbs
  admin/app/templates/authenticated/organizations/get.hbs
  admin/app/templates/authenticated/organizations/get/all-tags.hbs
  admin/app/templates/authenticated/organizations/get/campaigns.hbs
  admin/app/templates/authenticated/organizations/get/invitations.hbs
  admin/app/templates/authenticated/organizations/get/target-profiles.hbs
  admin/app/templates/authenticated/organizations/get/team.hbs
  admin/app/templates/authenticated/sessions/session/certifications.hbs
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/app/templates/authenticated/target-profiles/target-profile/insights.hbs
  admin/app/templates/authenticated/target-profiles/target-profile/organizations.hbs
  admin/mirage/config.js
  admin/mirage/handlers/organizations.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/details_test.js
  admin/tests/acceptance/organization-invitations-management_test.js
  admin/tests/acceptance/organization-list_test.js
  admin/tests/acceptance/organization-memberships-management_test.js
  admin/tests/integration/components/organization-invitations-action_test.js
  admin/tests/integration/components/organization-invitations_test.js
  admin/tests/integration/components/organization-team-actions-section_test.js
  admin/tests/integration/components/organization-team-section_test.js
  admin/tests/integration/components/user-detail-personal-information_test.js
  admin/tests/unit/components/organization-invitations_test.js
  admin/tests/unit/controllers/authenticated/organizations/get/invitations_test.js
  admin/tests/unit/routes/authenticated/organizations/invitations_test.js
  api/lib/application/organizations/index.js
  api/lib/infrastructure/repositories/organization-invitation-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-invitation-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-invitation-serializer_test.js
  mon-pix/.eslintrc.js
Labels: :rocket: Ready to Merge, team-acces

#3687 [BUGFIX] Corriger l'affichage de la liste déroulante des sous-catégories de signalements (PIX-3735)
  certif/app/styles/components/add-issue-report-modal.scss
  certif/package-lock.json
  certif/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3691 [FEATURE] Permettre à un surveillant de quitter la session qu'il surveille (PIX-3752).
  certif/app/components/session-supervising/header.hbs
  certif/app/styles/components/session-supervising/header.scss
  certif/tests/acceptance/supervisor-portal-access_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3683 [FEATURE] Afficher les certifications complémentaires dans la modale d'inscription d'un candidat à une session de certification (PIX-3685)
  api/lib/domain/read-models/AllowedCertificationCenterAccess.js
  api/lib/infrastructure/repositories/certification-point-of-contact-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer.js
  api/tests/integration/infrastructure/repositories/certification-point-of-contact-repository_test.js
  api/tests/tooling/domain-builder/factory/build-allowed-certification-center-access.js
  api/tests/unit/application/certification-point-of-contacts/certification-point-of-contact-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer_test.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/app/models/allowed-certification-center-access.js
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3668 [FEATURE] Optimiser la page des utilisateurs dans Pix Admin qui déclenche des requêtes couteuses à chaque chargement et à chaque recherche (PIX-3667).
  admin/app/components/users/list-items.hbs
  admin/app/controllers/authenticated/users/list.js
  admin/app/routes/authenticated/users/list.js
  admin/app/templates/authenticated/users/list.hbs
  admin/tests/acceptance/authenticated/users/get_test.js
  admin/tests/acceptance/user-list_test.js
  admin/tests/unit/controllers/authenticated/users/list_test.js
  admin/tests/unit/routes/authenticated/users/list_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces, team-captains

#3685 [FEATURE] Afficher un message d'erreur pour les invitations d'organisation annulées (PIX-1316)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/OrganizationInvitation.js
  api/lib/domain/usecases/get-organization-invitation.js
  api/tests/integration/application/error-manager_test.js
  api/tests/unit/domain/models/OrganizationInvitation_test.js
  api/tests/unit/domain/usecases/get-organization-invitation_test.js
  orga/app/components/auth/login-form.hbs
  orga/app/controllers/login.js
  orga/app/routes/join.js
  orga/app/routes/login.js
  orga/app/templates/login.hbs
  orga/mirage/config.js
  orga/tests/acceptance/join_test.js
  orga/tests/unit/routes/join_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3696 [BUGFIX] Cacher les certifications complémentaires dans la modale d'inscription d'un candidat si le FT n'est pas activé (PIX-3803).
  api/lib/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3697 [BUGFIX] Afficher le détail d'un profil cible sur Pix Admin (PIX-3807).
  admin/app/components/target-profiles/list-items.hbs
  admin/tests/acceptance/authenticated/target-profiles/list_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3694 [TECH] Prévenir l'utilisation de `console` dans l'API.
  api/.eslintrc.yaml
  api/db/batch-processing.js
  api/db/knex-database-connection.js
  api/lib/infrastructure/perftimer.js
  api/lib/infrastructure/utils/xml/siecle-file-streamer.js
  api/scripts/.eslintrc.yaml
  api/scripts/database/create-database.js
  api/scripts/database/drop-database.js
  api/scripts/database/empty-database.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3671 [TECH] Linter les fichiers YAML.
  .circleci/config.yml
  .editorconfig
  .eslintrc.yaml
  .github/workflows/auto-merge.yml
  .github/workflows/on-dev-merge.yml
  api/.eslintrc.yaml
  api/db/migrations/.eslintrc.yaml
  api/db/seeds/.eslintrc.yaml
  api/scripts/.eslintrc.yaml
  api/tests/.eslintrc.yaml
  api/tests/integration/.eslintrc.yaml
  high-level-tests/test-algo/.eslintrc.yaml
  high-level-tests/test-algo/tests/.eslintrc.yaml
  package-lock.json
  package.json
  scripts/.eslintrc.yaml
  scripts/local-domains/docker-compose.yml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3689 [FEATURE] Ajout du taux de réussite d'un résultat thématique sur Pix-Admin (PIX-3507).
  admin/app/adapters/badge-criterion.js
  admin/app/components/target-profiles/badge-form.hbs
  admin/app/components/target-profiles/badge-form.js
  admin/app/templates/authenticated/target-profiles/target-profile/badges/new.hbs
  admin/mirage/config.js
  admin/mirage/handlers/target-profiles.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/integration/components/target-profiles/badge-form_test.js
  admin/tests/unit/adapters/badge-criterion_test.js
  api/lib/application/badges/badges-controller.js
  api/lib/application/badges/index.js
  api/lib/domain/models/BadgeCriterion.js
  api/lib/domain/usecases/create-badge-criterion.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/badge-criteria-repository.js
  api/lib/infrastructure/serializers/jsonapi/badge-criteria-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-criteria-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-criteria-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3702 [BUGFIX] Empêcher le débordement de l'en-tête de colonne "Temps majoré" (PIX-3804).
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3674 [TECH] Ajouter le métrique duration dans le monitoring des appels externe en error.
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/lib/infrastructure/http/http-agent.js
  api/lib/infrastructure/monitoring-tools.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-captains, cross-team

#3684 [TECH] Bloquer le merge pour les commits de fixup
  .github/workflows/auto-merge.yml
  .github/workflows/check-commits.yml
Labels: :rocket: Ready to Merge, cross-team

#3705 [TECH] Ajout du thème Noël pour le template de pull request.
  docs/pull_request_template.md
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3695 [FEATURE] Amélioration du design des liens dans les champs réponses des écrans intermédiaires (PIX-3779).
  mon-pix/app/styles/components/_qcm-solution-panel.scss
  mon-pix/app/styles/components/_qcu-solution-panel.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3693 [FEATURE] Ajout de tooltip et traduction pour expliquer une campagne de collect de profiles envoi multiple dans l'onglet paramètres (Pix 3676).
  orga/app/components/campaign/settings.hbs
  orga/app/components/campaign/settings.js
  orga/app/styles/components/campaign/settings.scss
  orga/tests/integration/components/campaign/settings_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3711 [BUGFIX] Upgrade pix-ui to fix select element on firefox
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3692 [FEATURE] Limiter la taille de saisie d'un texte de présentation pour une campagne d'évaluation (PIX-3736)
  admin/app/components/campaigns/update.hbs
  admin/app/components/campaigns/update.js
  admin/tests/integration/components/campaigns/update_test.js
  api/lib/application/campaigns/index.js
  api/tests/integration/application/campaigns/index_test.js
  api/tests/unit/application/campaign/index_test.js
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/update-form.hbs
  orga/tests/integration/components/campaign/create-form_test.js
  orga/tests/integration/components/campaign/update-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3700 [TECH] Harmoniser l'auto-correction des sources.
  admin/package.json
  api/package.json
  certif/app/styles/globals/forms.scss
  certif/app/styles/globals/tables.scss
  certif/app/styles/pages/terms-of-service.scss
  certif/package.json
  mon-pix/package.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3714 [TECH] Forcer l'ordre de la requête pour éviter les flaky tests (PIX-3822).
  api/lib/infrastructure/repositories/certification-point-of-contact-repository.js
  api/tests/integration/infrastructure/repositories/certification-point-of-contact-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3698 [TECH] Encapsuler la logique de create-campaign dans un model (PIX-3741).
  api/lib/domain/models/CampaignCreator.js
  api/lib/domain/models/CampaignForCreation.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/usecases/index.js
  api/lib/domain/validators/campaign-creation-validator.js
  api/lib/infrastructure/repositories/campaign-creator-repository.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/tests/integration/domain/usecases/create-campaign_test.js
  api/tests/integration/infrastructure/repositories/campaign-creator-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/unit/domain/models/CampaignCreator_test.js
  api/tests/unit/domain/models/CampaignForCreation_test.js
  api/tests/unit/domain/usecases/create-campaign_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3707 [TECH] Supprimer la gestion du nom de champ et debounced des templates des filtres des tableaux (PIX-3710).
  orga/app/components/student/sco/list.hbs
  orga/app/components/student/sco/list.js
  orga/app/components/student/sup/list.hbs
  orga/app/components/student/sup/list.js
  orga/app/components/table/header-filter-input.hbs
  orga/app/components/table/header-filter-input.js
  orga/app/components/table/header-filter-multi-select.hbs
  orga/app/components/table/header-filter-multi-select.js
  orga/app/components/table/header-filter-select.hbs
  orga/app/components/table/header-filter-select.js
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/controllers/authenticated/sco-students/list.js
  orga/app/controllers/authenticated/sup-students/list.js
  orga/tests/integration/components/students/sco/list_test.js
  orga/tests/integration/components/students/sup/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3704 [FEATURE] Mises à jour d'affiche mineur sur certif (PIX-3780)
  certif/app/components/session-supervising/candidate-list.hbs
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/app/styles/components/session-supervising/candidate-list.scss
  certif/tests/integration/components/session-supervising/candidate-list_test.js
Labels: :rocket: Ready to Merge, team-certif, Design Review OK

#3703 [FEATURE] Afficher la présence des candidats en session de certification (PIX-3654)
  api/db/database-builder/factory/build-certification-candidate.js
  api/db/database-builder/factory/build-session.js
  api/db/migrations/20211029094139_add-candidate-in-session-status.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/lib/domain/models/CertificationCandidateForSupervising.js
  api/lib/infrastructure/serializers/jsonapi/certifications-livret-scolaire/certification-ls-serializer.js
  api/lib/infrastructure/serializers/jsonapi/session-for-supervising-serializer.js
  api/tests/acceptance/application/session/session-for-supervising-controller-get_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-for-supervising-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-for-supervising-serializer_test.js
  certif/app/components/session-supervising/candidate-list.hbs
  certif/app/models/certification-candidate-for-supervising.js
  certif/app/models/session-for-supervising.js
  certif/app/styles/components/session-supervising/candidate-list.scss
  certif/mirage/config.js
  certif/mirage/serializers/session-for-supervising.js
  certif/tests/acceptance/session-supervising_test.js
  certif/tests/acceptance/supervisor-portal-access_test.js
  certif/tests/integration/components/session-supervising/candidate-list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#3713 [FEATURE] Sauvegarder les certifications complémentaires auxquelles un candidat est inscrit (PIX-3681).
  api/db/migrations/20211108140716_create-table-complementary-certification-subscriptions.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/complementary-certification-subscription-repository.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-subscription-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  certif/app/components/enrolled-candidates.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/app/models/certification-candidate.js
  certif/tests/unit/components/new-certification-candidate-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3699 [TECH] Expliciter la journalisation des métriques OPS.
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/server.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3708 [TECH] Exécuter le lint des fichiers YAML dans les applications.
  admin/package-lock.json
  admin/package.json
  api/.depcheckrc
  api/package-lock.json
  api/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3701 [BUGFIX] Eviter les doublons quand on re-invite un membre sur Pix Admin (PIX-3802).
  admin/app/adapters/organization-invitation.js
  admin/app/controllers/authenticated/organizations/get/invitations.js
  admin/mirage/config.js
  admin/tests/unit/controllers/authenticated/organizations/get/invitations_test.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/infrastructure/repositories/organization-invitation-repository.js
  api/tests/integration/domain/services/organization-invitation-service_test.js
  api/tests/integration/domain/usecases/create-organization-invitations_test.js
  api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3706 [FEATURE] Modifier la présence des candidats en session de certif (PIX-3811)
  api/lib/application/certification-candidates/certification-candidates-controller.js
  api/lib/application/certification-candidates/index.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-certification-candidate-for-supervising.js
  api/lib/infrastructure/repositories/certification-candidate-for-supervising-repository.js
  api/lib/routes.js
  api/tests/acceptance/application/certification-candidates/certification-candidates-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-for-supervising-repository_test.js
  api/tests/unit/application/certification-candidates/certification-candidates-controller_test.js
  api/tests/unit/domain/usecases/update-certification-candidate-for-supervising_test.js
  certif/app/adapters/certification-candidate-for-supervising.js
  certif/app/components/session-supervising/candidate-list.hbs
  certif/app/components/session-supervising/candidate-list.js
  certif/app/controllers/session-supervising.js
  certif/app/models/certification-candidate-for-supervising.js
  certif/app/styles/components/session-supervising/candidate-list.scss
  certif/app/templates/session-supervising.hbs
  certif/mirage/config.js
  certif/tests/acceptance/session-supervising_test.js
  certif/tests/integration/components/session-supervising/candidate-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3716 [FEATURE] Avoir uniquement les épreuves dans la locale de l'utilisateur pour l'algo Flash (PIX-3782).
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/infrastructure/datasources/learning-content/challenge-datasource_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3717 [FEATURE] Ne pas sauvegarder les KE lors de campagnes Flash (PIX-2781).
  api/lib/domain/models/Assessment.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3712 [TECH] Séparer les usecases d'invitation à une orga pour un admin Pix et un admin Orga
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/create-organization-invitation-by-admin.js
  api/lib/domain/usecases/create-organization-invitations.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/organization-invitation-serializer.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/create-organization-invitation-by-admin_test.js
  api/tests/unit/domain/usecases/create-organization-invitations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-invitation-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3719 [TECH] Supprimer le pre handler checkUserIsAdminInOrganizationOrHasRolePixMaster plus utilisé (PIX-3820).
  api/lib/application/security-pre-handlers.js
  api/tests/acceptance/application/security-pre-handlers_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/unit/application/security-pre-handlers_test.js
Labels: :rocket: Ready to Merge, cross-team

#3710 [BUGFIX][ORGA] Correctly display create or modify campaign button (pix-3792)
  orga/app/styles/globals/forms.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3709 [FEATURE] Afficher les certifications complémentaires auxquelles sont inscrits les candidats dans Pix Certif (PIX-3686)
  api/db/database-builder/factory/build-complementary-certification-subscription.js
  api/db/database-builder/factory/index.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/acceptance/application/session/session-controller-get-certification-candidates_test.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/models/certification-candidate.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/certification-candidate-details-modal/certification-candidate-details-modal_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/unit/models/certification-candidate_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3725 [BUFGIX] Ne pas donner l'accès à Pix Certif à un administrateur dont l'organisation n'a pas d'UAI (PIX-3793).
  api/lib/domain/models/Organization.js
  api/lib/domain/usecases/update-membership.js
  api/tests/unit/domain/models/Organization_test.js
  api/tests/unit/domain/usecases/update-membership_test.js
Labels: :rocket: Ready to Merge, team-acces

#3720 [TECH] Simplifier le workflow d'automerge (PIX-3825)
  .github/workflows/auto-merge.yml
  .github/workflows/check-commits.yml
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3715 [FEATURE] Proposer plusieurs épreuves à la suite pour une campagne Flash (PIX-3783).
  api/db/database-builder/factory/build-campaign.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3726 [FEATURE] Ajouter une description aux profils cible et l'afficher dans pix admin(PIX-3758)
  admin/app/models/target-profile.js
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/tests/acceptance/authenticated/target-profiles/target-profile/details_test.js
  api/db/database-builder/factory/build-target-profile.js
  api/db/migrations/20211112093024_add-description-in-target-profiles.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/domain/models/TargetProfile.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-with-learning-content.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3727 [FEATURE] Restreindre l'accès à une session aux candidats autorisés (PIX-3655)
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  mon-pix/app/components/certification-starter.js
  mon-pix/tests/integration/components/certification-starter_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3718 [FEATURE] Modification de l'enregistrement de l'image d'un RT dans Pix-Admin (PIX-3481).
  admin/app/components/target-profiles/badge-form.hbs
  admin/app/components/target-profiles/badge-form.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/integration/components/target-profiles/badge-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3735 [TECH] Journaliser la version de l'application.
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/lib/plugins.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3734 [BUGFIX] La clé requête est dupliquée dans les logs.
  api/lib/plugins.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3745 [BUGFIX] Cacher les certifications complémentaires si le FT est désactivé (PIX-3854).
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/feature-toggle.js
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/certification-candidate-details-modal/certification-candidate-details-modal_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3738 [BUGFIX] Permettre l'envoi des résultats malgré une double participation non voulue à une campagne (PIX-3850).
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3732 [FEATURE] Afficher les candidats ayant démarré leur test dans l'espace surveillant (PIX-3657)
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/lib/domain/models/CertificationCandidateForSupervising.js
  api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-for-supervising-serializer.js
  api/tests/integration/infrastructure/repositories/sessions/session-for-supervising-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-for-supervising-serializer_test.js
  certif/app/components/session-supervising/candidate-list.hbs
  certif/app/models/certification-candidate-for-supervising.js
  certif/app/styles/components/session-supervising/candidate-list.scss
  certif/tests/integration/components/session-supervising/candidate-list_test.js
  certif/tests/unit/models/certification-candidate-for-supervising_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3741 [BUGFIX] Le path de la route n'est plus journalisé.
  api/lib/plugins.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3742 [TECH] Enrichir la documentation des variables d'environnement du monitoring.
  api/sample.env
Labels: :rocket: Ready to Merge, team-captains, cross-team

#3743 [TECH] Supprimer le logging des query params lors des logs de requêtes Knex.
  api/db/knex-database-connection.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#3728 [TECH] Ajouter updatedAt dans la table certification-centers (PIX-3680).
  api/db/database-builder/factory/build-certification-center.js
  api/db/migrations/20211112144138_add_updatedAt_column_to_certification_centers_table.js
  api/lib/application/organizations/index.js
  api/lib/domain/models/CertificationCenter.js
  api/lib/infrastructure/orm-models/CertificationCenter.js
  api/lib/infrastructure/repositories/certification-center-repository.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-center-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-center.js
Labels: :rocket: Ready to Merge, team-acces

#3739 [BUGFIX] Corriger les URL vers le support dans les emails transactionnels (PIX-3851).
  api/lib/domain/services/mail-service.js
  api/tests/unit/domain/services/mail-service_test.js
Labels: :rocket: Ready to Merge, team-acces

#3737 [FEATURE] Ajoute le user agent a la table feedbacks (PIX-3831)
  api/db/migrations/20211116091730_add_user_agent_to_feedbacks.js
  api/lib/application/feedbacks/feedback-controller.js
  api/lib/infrastructure/serializers/jsonapi/feedback-serializer.js
  api/tests/acceptance/application/feedback-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#3748 [BUGFIX] Réparer la page pour rejoindre une organisation (PIX-3860)
  orga/app/styles/components/login-or-register.scss
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team

#3736 [FEATURE] Bloquer l'accès à une session pour un candidat qui a déjà accédé à la session (PIX-3846)
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3729 [FEATURE] Modifier la description d'un profil cible depuis Pix Admin (PIX-3763)
  admin/app/components/target-profiles/update-target-profile.hbs
  admin/app/components/target-profiles/update-target-profile.js
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/mirage/config.js
  admin/mirage/handlers/target-profiles.js
  admin/tests/unit/components/update-target-profile-name_test.js
  admin/tests/unit/components/update-target-profile_test.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-target-profile-name.js
  api/lib/domain/usecases/update-target-profile.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/domain/usecases/update-target-profile-name_test.js
  api/tests/unit/domain/usecases/update-target-profile_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3723 [TECH] Synchroniser le workflow Jira avec celui des PR Github (PIX-3828).
  .github/workflows/jira-transition-to-dev-in-progress.yml
  .github/workflows/jira-transition-to-review.yml
Labels: :rocket: Ready to Merge, team-captains, cross-team

#3749 [BUGFIX] Supprimer les souscriptions aux certifications complémentaires (PIX-3856).
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#3750 [FEATURE] Ne pas poser des épreuves déjà passées dans l'algo Flash (PIX-3784).
  api/lib/domain/services/algorithm-methods/flash.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3751 [FEAT] Limiter le nombre de questions dans un assessment flash (PIX-3785).
  api/lib/config.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/sample.env
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3744 [FEATURE] Rattacher le premier membre d'une organisation SCO au centre de certification correspondant sur Pix Admin (PIX-3795).
  api/lib/application/memberships/membership-controller.js
  api/lib/domain/usecases/create-certification-center-membership-by-email.js
  api/lib/domain/usecases/create-certification-center-membership-for-sco-organization-member.js
  api/lib/domain/usecases/create-certification-center-membership.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-membership.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/tests/integration/application/memberships/membership-controller_test.js
  api/tests/integration/domain/usecases/create-certification-center-membership-for-sco-organization-member_test.js
  api/tests/integration/domain/usecases/update-membership_test.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/unit/application/memberships/membership-controller_test.js
  api/tests/unit/domain/usecases/create-certification-center-membership-by-email_test.js
  api/tests/unit/domain/usecases/create-certification-center-membership-for-sco-organization-member_test.js
  api/tests/unit/domain/usecases/update-membership_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3752 [BUGFIX] Ne PAS afficher le champ "Certifications complémentaires" pour un centre non habilité (PIX-3855)
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/allowed-certification-center-access.js
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates_test.js
  certif/tests/unit/models/allowed-certification-center-access_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3757 [FEATURE] Afficher le commentaire interne pour le profil cible dans Pix Admin (PIX-3868)
  admin/app/components/target-profiles/details.hbs
  admin/app/models/target-profile.js
  admin/app/styles/globals/page.scss
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/tests/acceptance/authenticated/target-profiles/target-profile/details_test.js
  api/db/database-builder/factory/build-target-profile.js
  api/db/migrations/20211118141612_add-private-comments-on-target-profile.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-with-learning-content.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3758 [TECH] Empêcher la double participation quand la campagne n'est pas multiple (PIX-3883).
  api/lib/domain/usecases/start-campaign-participation.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, cross-team

#3721 [TECH] Paralléliser le lint.
  .circleci/config.yml
  admin/package-lock.json
  admin/package.json
  api/package-lock.json
  api/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3756 [TECH] Retourner une erreur du domaine quand une participation à la campagne existe déjà.
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, cross-team

#3754 [TECH] S'assurer que l'algo flash reproduit bien les choix attendus (PIX-3874).
  api/lib/domain/services/algorithm-methods/flash.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3753 [FEATURE] Afficher les certifications complémentaires des candidats inscrits lors du téléchargement de l'ods (PIX-3687).
  api/lib/application/sessions/session-controller.js
  api/lib/domain/services/session-xml-service.js
  api/lib/domain/usecases/get-candidate-import-sheet-data.js
  api/lib/domain/usecases/get-session-with-candidates.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/files/candidates-import/1.5/candidates_import_template.ods
  api/lib/infrastructure/files/candidates-import/candidates-import-placeholders.js
  api/lib/infrastructure/files/candidates-import/fill-candidates-import-sheet.js
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/lib/infrastructure/utils/ods/added-cell-option.js
  api/lib/infrastructure/utils/ods/write-ods-utils.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-one-complementary-certification.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-two-complementary-certifications.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template.ods
  api/tests/integration/infrastructure/utils/ods/files/fill-candidates-import-sheet_test.js
  api/tests/integration/infrastructure/utils/ods/write-ods-utils_test.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/domain/usecases/get-candidate-import-sheet-data_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3759 [FEATURE] Embed + focus = :heavy_check_mark: (PIX-3041)
  mon-pix/app/components/challenge/item.hbs
  mon-pix/app/components/challenge/item.js
  mon-pix/tests/acceptance/challenge-item_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-contenu

#3760 [FEATURE] Modifier un commentaire interne depuis Pix Admin (Pix-3869)
  admin/app/components/target-profiles/insight.hbs
  admin/app/components/target-profiles/update-target-profile.hbs
  admin/app/components/target-profiles/update-target-profile.js
  admin/app/styles/app.scss
  admin/app/styles/components/target-profiles/target-profile.scss
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/tests/unit/components/update-target-profile_test.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/usecases/update-target-profile.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/domain/usecases/update-target-profile_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3765 [BUGFIX] Vérifier l'existence du contexte async local storage avant de tracer les métriques.
  api/lib/plugins.js
Labels: :rocket: Ready to Merge, team-captains, cross-team

#3746 [FEATURE] Badge: Ajouter un critère sur un ensemble d'acquis (backend)
  api/lib/application/badges/badges-controller.js
  api/lib/application/badges/index.js
  api/lib/domain/models/SkillSet.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/create-skill-set.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/skill-set-repository.js
  api/lib/infrastructure/serializers/jsonapi/badge-criteria-serializer.js
  api/lib/infrastructure/serializers/jsonapi/skill-set-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-criteria-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/skill-set-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-skill-set.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-criteria-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-set-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3755 [TECH] Refactoring algo flash pour lisibilité
  api/lib/domain/services/algorithm-methods/flash.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3766 [FEAT] Ajout d'une colonne 'Lacune' dans le tableau d'affichage des RT (PIX-3574).
  admin/app/components/target-profiles/badges.hbs
  admin/app/styles/components/target-profiles/badges.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3731 [FEATURE] Permettre l'annulation d'une invitation envoyée par l'admin d'une organisation sur Pix Orga (PIX-399).
  api/lib/application/error-manager.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/cancel-organization-invitation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/organization-invitation-repository.js
  api/tests/acceptance/application/organizations/cancel-organization-invitation-delete_test.js
  api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
  api/tests/test-helper.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/cancel-organization-invitation_test.js
  orga/app/adapters/organization-invitation.js
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/invitations-list.js
  orga/config/icons.js
  orga/mirage/config.js
  orga/tests/acceptance/invitations-list_test.js
  orga/tests/integration/components/team/invitations-list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#3763 [BUGFIX] Remettre le chargement entre les pages du flux d'accès campagne (PIX-3889).
  mon-pix/app/templates/assessments/loading.hbs
  mon-pix/app/templates/campaigns/invited/loading.hbs
  mon-pix/app/templates/campaigns/loading.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3724 [TECH] Linter en local uniquement les fichiers modifiés (PIX-3936).
  .gitignore
  admin/package.json
  api/package.json
  certif/package.json
  mon-pix/package.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3769 [TECH] Remplacer ember-cli-chai par chai sur Mon-Pix (PIX-3937).
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/test-helper.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3762 [TECH] Amélioration des transitions dans le flux d'accès campagne (PIX-3888).
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/routes/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/entrance.js
  mon-pix/app/routes/campaigns/entry-point.js
  mon-pix/app/routes/campaigns/invited.js
  mon-pix/app/routes/campaigns/invited/fill-in-participant-external-id.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code_test.js
  mon-pix/tests/unit/routes/campaigns/entrance_test.js
  mon-pix/tests/unit/routes/campaigns/entry-point_test.js
  mon-pix/tests/unit/routes/campaigns/invited/fill-in-participant-external-id_test.js
  mon-pix/tests/unit/routes/campaigns/invited_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#3768 [FEATURE] Désactive les boutons quand les champs sont vide lors du rattachement des organisations (PIX-3771).
  admin/app/components/target-profiles/organizations.hbs
  admin/app/components/target-profiles/organizations.js
  admin/tests/integration/components/target-profiles/organizations_test.js
  admin/tests/unit/components/target-profiles/organizations_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3776 [FEATURE] Empêcher la sélection d'épreuves portant sur des acquis de même nom lors du choix des épreuves d'un test de certification (PIX-3935).
  api/lib/domain/models/Skill.js
  api/lib/domain/models/UserCompetence.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/infrastructure/adapters/skill-adapter.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/tests/integration/domain/services/placement-profile-service_test.js
  api/tests/tooling/domain-builder/factory/build-skill-learning-content-data-object.js
  api/tests/tooling/domain-builder/factory/build-skill.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/unit/domain/models/UserCompetence_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/infrastructure/adapters/skill-adapter_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3764 [FEATURE] Passer en "résolu" les signalements des anciennes sessions (PIX-2641).
  api/db/migrations/20211123133135_resole-existing-certification-issue-reports.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3771 [FEATURE] Rattacher un membre au centre de certification correspondant lorsqu'il accepte l'invitation à rejoindre une organisation (PIX-3852).
  api/lib/application/organization-invitations/organization-invitation-controller.js
  api/lib/domain/usecases/accept-organization-invitation.js
  api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/unit/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/unit/domain/usecases/accept-organization-invitation_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#3781 [TECH] Améliorer l'accessibilité de la navigation sur Pix Orga (PIX-3894).
  orga/app/components/dropdown/item.hbs
  orga/app/styles/components/dropdown.scss
Labels: :rocket: Ready to Merge, team-acces, team-prescription

#3777 [TECH] Déprécier la route GET /assessments (PIX-3939).
  api/lib/application/assessments/index.js
  api/lib/application/users/index.js
  api/lib/domain/events/handle-pole-emploi-participation-finished.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/usecases/begin-campaign-participation-improvement.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-finished_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/begin-campaign-participation-improvement_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/PoleEmploiPayload_test.js
  mon-pix/app/routes/campaigns/assessment.js
  mon-pix/app/routes/campaigns/assessment/start-or-resume.js
  mon-pix/mirage/routes/assessments/find-assessments.js
  mon-pix/mirage/routes/assessments/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3767 [FEATURE] Ajuster la taille des colonnes d'IDs sur Pix Admin (PIX-3603).
  admin/app/components/certification-centers/list-items.hbs
  admin/app/components/certification-centers/memberships-section.hbs
  admin/app/components/organizations/campaigns-section.hbs
  admin/app/components/organizations/list-items.hbs
  admin/app/components/organizations/target-profiles-section.hbs
  admin/app/components/organizations/team-section.hbs
  admin/app/components/sessions/list-items.hbs
  admin/app/components/target-profiles/badges.hbs
  admin/app/components/target-profiles/list-items.hbs
  admin/app/components/target-profiles/stages.hbs
  admin/app/components/to-be-published-sessions/list-items.hbs
  admin/app/components/users/list-items.hbs
  admin/app/components/with-required-action-sessions/list-items.hbs
  admin/app/styles/globals/tables.scss
Labels: :rocket: Ready to Merge, team-evaluation

#3779 [FEATURE] Permettre d'anonymiser un utilisateur peu importe sa méthode de connexion sur Pix Admin (PIX-3773).
  admin/app/components/user-detail-personal-information.js
  admin/app/components/user-detail-personal-information/authentication-method.hbs
  admin/app/components/user-detail-personal-information/user-overview.hbs
  admin/app/components/user-detail-personal-information/user-overview.js
  admin/mirage/config.js
  admin/mirage/serializers/user.js
  admin/tests/acceptance/user-details-personal-information_test.js
  admin/tests/helpers/extended-ember-test-helpers/query-by-label.js
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/anonymize-user.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-anonymized-details-for-admin-serializer.js
  api/tests/acceptance/application/users/users-controller-anonymize-user_test.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/anonymize-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-anonymized-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#3787 [TECH] Corriger les valeurs de l'autocomplete dans le formulaire de création de compte sur Pix Orga (PIX-3896).
  orga/app/components/auth/register-form.hbs
Labels: :rocket: Ready to Merge, team-acces

#3775 [FEATURE] Sauvegarder le démarrage des certifications complémentaires(PIX-3689)
  api/db/migrations/20211122131317_create-table-complementary-certification-courses.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/certification/certification-data.js
  api/db/seeds/data/certification/partner-certification-builder.js
  api/db/seeds/data/certification/user-profiles-builder.js
  api/lib/domain/events/handle-pix-plus-certifications-scoring.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/CertificationCenter.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/models/ComplementaryCertification.js
  api/lib/domain/models/ComplementaryCertificationCourse.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/orm-models/CertificationCourse.js
  api/lib/infrastructure/orm-models/ComplementaryCertificationCourse.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-course.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif
