Repository 1024pix/pix, pull requests merged in 2021-07, with the labels that each got.

#3144 [FEATURE] Ajout de l'étape de conflit lors de la récupération de compte à la sortie du SCO (PIX-2730).
  mon-pix/app/components/recover-account-conflict-error.hbs
  mon-pix/app/components/recover-account-student-information-form.hbs
  mon-pix/app/components/recover-account-student-information-form.js
  mon-pix/app/controllers/recover-account-after-leaving-sco.js
  mon-pix/app/templates/recover-account-after-leaving-sco.hbs
  mon-pix/mirage/routes/schooling-registration-dependent-users/index.js
  mon-pix/tests/acceptance/recover-account-after-leaving-sco_test.js
  mon-pix/tests/integration/components/recover-account-conflict-error-test.js
  mon-pix/tests/integration/components/recover-account-student-information-form-test.js
  mon-pix/tests/unit/components/recover-account-student-information_test.js
  mon-pix/tests/unit/controllers/recover-account-after-leaving-sco-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3109 [TECH] Remplacer BookshelfJS par le query-builder KnexJS dans le answer-repository (PIX-2742)
  api/db/knex-database-connection.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/lib/infrastructure/utils/knex-utils.js
  api/tests/integration/infrastructure/knex-database-connection_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3110 [FEATURE] Création de la liste des participants dans l'onglet activité (PIX-2665)
  api/db/database-builder/factory/build-assessment-from-participation.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/read-models/CampaignParticipantActivity.js
  api/lib/domain/usecases/find-paginated-campaign-participants-activities.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-participant-activity-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participant-activity-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/domain/usecases/find-paginated-campaign-participant-activities_test.js
  api/tests/integration/infrastructure/repositories/campaign-participant-activity-repository_test.js
  api/tests/unit/domain/read-models/CampaignParticipantActivity_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participant-activity-serializer_test.js
  orga/app/adapters/campaign-participant-activity.js
  orga/app/components/campaign/activity/dashboard.hbs
  orga/app/components/campaign/activity/dashboard.js
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/activity/participation-status.hbs
  orga/app/components/campaign/activity/participation-status.js
  orga/app/components/charts/participants-by-status-loader.hbs
  orga/app/components/indicator-card.hbs
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/models/campaign-participant-activity.js
  orga/app/routes/authenticated/campaigns/campaign/activity.js
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/activity/dashboard.scss
  orga/app/styles/components/campaign/index.scss
  orga/app/styles/components/charts/participants-by-day.scss
  orga/app/styles/components/charts/participants-by-status.scss
  orga/app/styles/components/indicator-card.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/campaigns/details/activity.scss
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/tests/integration/components/campaign/activity/participants-activity-list_test.js
  orga/tests/unit/components/campaign/activity/dashboard_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3133 [TECH] Permettre a PE de récupérer les résultats(PIX-2682)
  api/db/seeds/data/campaigns-builder.js
  api/db/seeds/data/pole-emploi-sendings-builder.js
  api/db/seeds/seed.js
  api/lib/application/pole-emplois/index.js
  api/lib/application/pole-emplois/pole-emploi-controller.js
  api/lib/config.js
  api/lib/domain/usecases/get-pole-emploi-sendings.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/open-api-doc/pole-emploi/envois-doc.js
  api/lib/infrastructure/repositories/pole-emploi-sending-repository.js
  api/tests/acceptance/application/pole-emploi-controller_test.js
  api/tests/integration/infrastructure/repositories/pole-emploi-sending-repository_test.js
  api/tests/unit/application/pole-emploi/index_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/infrastructure/open-api-doc/pole-emploi/envois-doc_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3152 [FEATURE] Ajouter l'étape de confirmation dans la récupération de compte (PIX-2732).
  mon-pix/app/adapters/student-information.js
  mon-pix/app/components/recover-account-confirmation-step.hbs
  mon-pix/app/controllers/recover-account-after-leaving-sco.js
  mon-pix/app/models/student-information.js
  mon-pix/app/templates/recover-account-after-leaving-sco.hbs
  mon-pix/mirage/routes/schooling-registration-dependent-users/index.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/recover-account-after-leaving-sco_test.js
  mon-pix/tests/integration/components/recover-account-confirmation-step-test.js
  mon-pix/tests/integration/components/recover-account-student-information-form-test.js
  mon-pix/tests/unit/adapters/student-information-test.js
  mon-pix/tests/unit/controllers/recover-account-after-leaving-sco-test.js
  mon-pix/tests/unit/models/student-information-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#3142 [FEATURE] Simplifier la liste des candidats (PIX-2714)
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/enrolled-candidates.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/unit/components/enrolled-candidates_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#3127 [FEATURE] Valider les données de pays et villes saisis lors de l'inscription d'un candidat à une session de certification (PIX-2657).
  api/db/database-builder/factory/build-certification-cpf-city.js
  api/db/database-builder/factory/index.js
  api/lib/domain/models/CertificationCpfCity.js
  api/lib/domain/models/CertificationCpfCountry.js
  api/lib/domain/services/certification-cpf-service.js
  api/lib/infrastructure/repositories/certification-cpf-city-repository.js
  api/lib/infrastructure/repositories/certification-cpf-country-repository.js
  api/tests/integration/infrastructure/repositories/certification-cpf-city-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-cpf-country-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-cpf-city.js
  api/tests/tooling/domain-builder/factory/build-certification-cpf-country.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/services/certification-cpf-service_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3163 [CLEANUP] Corriger les typos dans sample.env
  api/sample.env
Labels: :rocket: Ready to Merge, team-acces

#3149 [TECH] Surcharger Ember simple auth session dans Pix-Admin (PIX-2766).
  admin/app/router.js
  admin/app/routes/application.js
  admin/app/routes/index.js
  admin/app/routes/login.js
  admin/app/routes/logout.js
  admin/app/services/session.js
  admin/tests/unit/routes/index_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3155 [FEATURE] Ajouter l'étape de la récupération de l'e-mail dans le parcours de récupération de compte (PIX-2738).
  mon-pix/app/components/recover-account-confirmation-step.hbs
  mon-pix/app/components/recovery-account/recover-account-backup-email-confirmation-form.hbs
  mon-pix/app/components/recovery-account/recover-account-backup-email-confirmation-form.js
  mon-pix/app/controllers/recover-account-after-leaving-sco.js
  mon-pix/app/templates/recover-account-after-leaving-sco.hbs
  mon-pix/tests/acceptance/recover-account-after-leaving-sco_test.js
  mon-pix/tests/integration/components/recover-account-confirmation-step-test.js
  mon-pix/tests/integration/components/recovery-account/recover-account-backup-email-confirmation-form-test.js
  mon-pix/tests/unit/controllers/recover-account-after-leaving-sco-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3159 [FEATURE] Améliorer l'accessibilité des libellés du menu de Pix Certif (PIX-2690)
  certif/app/templates/authenticated.hbs
Labels: :rocket: Ready to Merge, team-certif

#3165 [TECH] Autorise les champs t1, t2, t3 status a être des boolean
  api/lib/infrastructure/adapters/solution-adapter.js
  api/tests/integration/infrastructure/repositories/solution-repository_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team, team-evaluation

#3156 [TECH] Modifier l'organisation des composants de campagne dans Pix Orga (PIX-2775)
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/create-form.js
  orga/app/components/campaign/list-actions.hbs
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/no-campaign-panel.hbs
  orga/app/components/campaign/update-form.hbs
  orga/app/components/routes/authenticated/campaign/update.hbs
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/routes/authenticated/campaigns/update.js
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/index.scss
  orga/app/styles/components/campaign/list-actions.scss
  orga/app/styles/components/campaign/list.scss
  orga/app/styles/components/campaign/no-campaign-panel.scss
  orga/app/styles/pages/authenticated/campaigns/list.scss
  orga/app/templates/authenticated/campaigns/list.hbs
  orga/app/templates/authenticated/campaigns/new.hbs
  orga/app/templates/authenticated/campaigns/update.hbs
  orga/tests/integration/components/campaign/create-form_test.js
  orga/tests/integration/components/campaign/list_test.js
  orga/tests/integration/components/campaign/update-form_test.js
  orga/tests/unit/controllers/authenticated/campaigns/list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-prescription

#3169 [TECH] Modifier l'organisation des composants d'équipe dans Pix Orga (PIX-2776)
  orga/app/components/routes/authenticated/team/invitations.hbs
  orga/app/components/routes/authenticated/team/items.hbs
  orga/app/components/routes/authenticated/team/members.hbs
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/invite-form.hbs
  orga/app/components/team/members-list-item.hbs
  orga/app/components/team/members-list-item.js
  orga/app/components/team/members-list.hbs
  orga/app/components/team/remove-member-modal.hbs
  orga/app/controllers/authenticated/team/new.js
  orga/app/routes/authenticated/team/new.js
  orga/app/styles/app.scss
  orga/app/styles/components/team/index.scss
  orga/app/styles/components/team/remove-member-modal.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/styles/pages/authenticated/team/new.scss
  orga/app/templates/authenticated/team/list/invitations.hbs
  orga/app/templates/authenticated/team/list/members.hbs
  orga/app/templates/authenticated/team/new.hbs
  orga/tests/integration/components/routes/authenticated/team/new-item_test.js
  orga/tests/integration/components/team/invitations-list_test.js
  orga/tests/integration/components/team/invite-form_test.js
  orga/tests/integration/components/team/members-list-item_test.js
  orga/tests/integration/components/team/members-list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-prescription

#3146 [TECH] Contrôler INE et INA dans l'API lors de la récupération SCO.
  api/lib/application/schooling-registration-dependent-users/index.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#3171 [FEATURE] Création de la table account-recovery-demands (PIX-2777).
  api/db/migrations/20210706121344_create-account-recovery-demands-table.js
Labels: :rocket: Ready to Merge, team-acces

#3164 [FEATURE] Modifier les valeurs possibles pour la colonne "Code sexe*" de l'import Fregata (PIX-2699).
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/unit/domain/usecases/get-schooling-registrations-csv-template_test.js
  api/tests/unit/infrastructure/serializers/csv/schooling-registration-parser_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2726 [TECH] Automatiser la création des domaines locaux pour le développement
  INSTALLATION.md
  package.json
  scripts/local-domains/docker-compose.yml
  scripts/local-domains/hosts.txt
  scripts/local-domains/install
  scripts/local-domains/nginx.conf
Labels: :rocket: Ready to Merge, cross-team

#3174 [TECH] Ajouter les top level domains .fr et .org aux domaines locaux
  INSTALLATION.md
  scripts/local-domains/hosts.txt
  scripts/local-domains/nginx.conf
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3148 [BUGFIX] Ne pas sauvegarder deux fois un même badge pour un même user dans une campagne (PIX-2704).
  api/db/migrations/20210630150224_add_column_updatedAt_to_badge_acquisitions.js
  api/lib/domain/events/handle-badge-acquisition.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/unit/domain/events/handle-badge-acquisition_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3154 [TECH] Ne pas filtrer le html contenu dans la consigne d'une épreuve lors de son affichage lors du checkpoint.
  mon-pix/app/templates/components/comparison-window.hbs
Labels: :rocket: Ready to Merge, team-evaluation

#3167 [FEATURE] Mettre en page la récupération d'un compte SCO (PIX-2773).
  mon-pix/app/components/recover-account-confirmation-step.hbs
  mon-pix/app/components/recover-account-conflict-error.hbs
  mon-pix/app/components/recover-account-student-information-form.hbs
  mon-pix/app/components/recovery-account/recover-account-backup-email-confirmation-form.hbs
  mon-pix/app/controllers/recover-account-after-leaving-sco.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_recover-account-confirmation-step.scss
  mon-pix/app/styles/components/_recover-account-student-information-form.scss
  mon-pix/app/styles/pages/_recover-account-after-leaving-sco.scss
  mon-pix/app/templates/recover-account-after-leaving-sco.hbs
  mon-pix/config/icons.js
  mon-pix/mirage/routes/schooling-registration-dependent-users/index.js
  mon-pix/public/images/illustrations/recovery-account/recover-account-illustration.svg
  mon-pix/tests/acceptance/recover-account-after-leaving-sco_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3157 [TECH] Supprimer les mixins d'Ember-simple-auth 3.1.0 dans Pix Orga (PIX-2767).
  orga/app/adapters/application.js
  orga/app/components/routes/login-form.js
  orga/app/routes/application.js
  orga/app/routes/authenticated.js
  orga/app/routes/join-when-authenticated.js
  orga/app/routes/join.js
  orga/app/routes/login.js
  orga/app/routes/logout.js
  orga/app/routes/not-found.js
  orga/app/routes/terms-of-service.js
  orga/app/services/session.js
  orga/mirage/config.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/join_test.js
  orga/tests/integration/components/routes/login-form_test.js
  orga/tests/unit/routes/application_test.js
  orga/tests/unit/routes/not-found_test.js
  orga/tests/unit/services/session_test.js
Labels: :rocket: Ready to Merge, team-acces

#3145 [DOC] Proposition d'ADR pour remplacer l'usage de l'ORM BookshelfJS en faveur du query-builder KnexJS
  docs/adr/0028-remplacer-orm-bookshelfjs-par-query-builder-knexjs.md
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3168 [TECH] Gère la redéfinition de l'extension de knex QueryBuilder pour les tests en mode watch
  api/db/knex-database-connection.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3158 [TECH] Ajout du linter de tests qunit sur admin
  admin/.eslintrc.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/sessions/list/to-be-published_test.js
  admin/tests/acceptance/authenticated/sessions/list/with-required-action_test.js
  admin/tests/acceptance/session_test.js
  admin/tests/integration/components/certification/certification-details-answer_test.js
  admin/tests/integration/components/certification/certification-info-field_test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations_test.js
  admin/tests/integration/components/user-detail-personal-information_test.js
  admin/tests/unit/components/certification/certification-details-competence_test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/details_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/neutralization_test.js
  admin/tests/unit/controllers/authenticated/sessions/session/certifications_test.js
  admin/tests/unit/controllers/authenticated/sessions/session/informations_test.js
  admin/tests/unit/controllers/authenticated/target-profiles/new_test.js
  admin/tests/unit/controllers/authenticated/target-profiles/target-profile/organizations_test.js
  admin/tests/unit/models/certification-issue-report_test.js
  admin/tests/unit/models/jury-certification-summary_test.js
  admin/tests/unit/models/session_test.js
  admin/tests/unit/models/user_test.js
  admin/tests/unit/services/feature-toggles_test.js
  admin/tests/unit/utils/email-validator_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3161 [TECH] Ajout du linter de tests qunit sur certif
  certif/.eslintrc.js
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/terms-of-service_test.js
  certif/tests/integration/components/add-student-list_test.js
  certif/tests/integration/components/certification-candidate-in-staging-item_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/integration/components/session-finalization-examiner-global-comment-step_test.js
  certif/tests/unit/adapters/certification-candidate_test.js
  certif/tests/unit/adapters/certification-point-of-contact_test.js
  certif/tests/unit/adapters/division_test.js
  certif/tests/unit/adapters/session-summary_test.js
  certif/tests/unit/adapters/session_test.js
  certif/tests/unit/adapters/student_test.js
  certif/tests/unit/components/add-student-list_test.js
  certif/tests/unit/components/app-modal_test.js
  certif/tests/unit/components/enrolled-candidates_test.js
  certif/tests/unit/components/login-form_test.js
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates_test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize_test.js
  certif/tests/unit/models/certification-issue-report_test.js
  certif/tests/unit/models/certification-report_test.js
  certif/tests/unit/routes/not-found_test.js
  certif/tests/unit/services/featureToggles_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3177 [SECU] Ajout de fichier SECURITY.md
  api/SECURITY.md
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3160 [FEATURE] Ajouter une modale d'inscription d'un nouveau candidat (PIX-2713)
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  certif/app/components/certification-candidate-in-staging-item.js
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/enrolled-candidates.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/country.js
  certif/app/routes/authenticated/sessions/details/certification-candidates.js
  certif/app/styles/app.scss
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/app/styles/globals/colors.scss
  certif/app/templates/authenticated.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/mirage/config.js
  certif/mirage/factories/country.js
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/authenticated_test.js
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
  certif/tests/unit/components/enrolled-candidates_test.js
  certif/tests/unit/components/new-certification-candidate-modal_test.js
  certif/tests/unit/models/country_test.js
  certif/tests/unit/routes/authenticated/sessions/details/certification-candidate_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3172 [FEATURE] Création d'un curseur et ajout de celui-ci dans la réponse lors des envois des résultats P-E (PIX-2743)
  api/db/seeds/data/pole-emploi-sendings-builder.js
  api/lib/application/pole-emplois/pole-emploi-controller.js
  api/lib/config.js
  api/lib/domain/services/pole-emploi-service.js
  api/lib/domain/usecases/get-pole-emploi-sendings.js
  api/lib/infrastructure/repositories/pole-emploi-sending-repository.js
  api/sample.env
  api/tests/acceptance/application/pole-emploi-controller_test.js
  api/tests/integration/domain/usecases/get-pole-emploi-sendings_test.js
  api/tests/integration/infrastructure/repositories/pole-emploi-sending-repository_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/domain/services/pole-emploi-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3181 [BUGFIX] Gérer le cas de deux QROCM-dep pour une seule compétence (PIX-2793)
  api/lib/domain/models/AnswerCollectionForScoring.js
  api/lib/domain/models/CertificationContract.js
  api/lib/domain/services/certification-result-service.js
  api/tests/unit/domain/models/AnswerCollectionForScoring_test.js
  api/tests/unit/domain/models/CertificationContract_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3184 [BUGFIX] Sélectionner la France par défaut lors de l'ajout d'un candidat (PIX-2817)
  api/db/seeds/data/certification/certification-cpf-country-builder.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3162 [BUGFIX/CLEANUP] Restreindre la modification du CertificationCourse aux seuls : nom, prénom et date/lieu de naissance (PIX-2702)
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/domain/events/handle-auto-jury.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/models/CertificationReport.js
  api/lib/domain/services/certification-course-service.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/usecases/correct-candidate-identity-in-certification-course.js
  api/lib/domain/usecases/delete-certification-issue-report.js
  api/lib/domain/usecases/get-certification-course.js
  api/lib/domain/usecases/get-sco-certification-results-by-division.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/domain/usecases/save-certification-issue-report.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/certification-report-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CertificationCourse_test.js
  api/tests/unit/domain/services/certification-course-service_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/usecases/cancel-certification-course_test.js
  api/tests/unit/domain/usecases/get-certification-course_test.js
  api/tests/unit/domain/usecases/get-session-results-by-result-recipient-email_test.js
  api/tests/unit/domain/usecases/get-session-results_test.js
  api/tests/unit/domain/usecases/modify-candidate-in-certification-course_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/domain/usecases/save-certification-issue-report_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3178 [FEATURE] Afficher des tirets sur les champs vides de la modale d'affichage des détails d'un candidat (PIX-2757)
  certif/app/components/certification-candidate-details-modal.hbs
  certif/tests/integration/components/certification-candidate-details-modal/certification-candidate-details-modal_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3176 [FEATURE] Vérifier la demande de récupération de compte - Sortie SCO (Pix 2774).
  api/db/database-builder/factory/build-account-recovery-demand.js
  api/lib/application/account-recovery/account-recovery-controller.js
  api/lib/application/account-recovery/index.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/account-recovery/get-user-by-account-recovery-demand.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/tests/acceptance/application/account-recovery/account-recovery-route-get_test.js
  api/tests/integration/application/account-recovery/account-recovery-controller_test.js
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
  api/tests/unit/application/account-recovery/account-recovery-controller_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/usecases/account-recovery/get-user-by-account-recovery-demand_test.js
  api/tests/unit/domain/usecases/account-recovery/send-email-for-account-recovery_test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/router.js
  mon-pix/app/routes/account-recovery/reset-password.js
  mon-pix/app/templates/account-recovery/reset-password.hbs
  mon-pix/tests/unit/routes/account-recovery/reset-password-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3182 [BUGFIX] Aligner le bouton d'envoi des résultats avec le contenu de la page (PIX-2804)
  mon-pix/app/styles/pages/_skill-review.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3186 [BUGFIX] Permettre l'envoi du formulaire d'ajout de candidat sous Firefox (PIX-2818)
  certif/app/components/new-certification-candidate-modal.hbs
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3190 [BUGFIX] Certains pays sont importés deux fois lors de l'import CPF des pays depuis le fichier INSEE (PIX-2823)
  api/scripts/import-certification-cpf-countries.js
  api/tests/unit/scripts/import-certification-cpf-countries_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3191 [BUGFIX] La liste des pays retournée par l'API était incomplète et côté Front certains pays étaient dans le désordre (PIX-2824)
  api/lib/domain/read-models/Country.js
  api/lib/infrastructure/repositories/country-repository.js
  api/lib/infrastructure/serializers/jsonapi/country-serializer.js
  api/tests/integration/infrastructure/repositories/country-repository_test.js
  api/tests/tooling/domain-builder/factory/build-country.js
  api/tests/unit/infrastructure/serializers/jsonapi/country-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3192 [TECH] Garantir l'unicité de la temporaryKey dans la récupération de compte SCO.
  api/db/migrations/20210716074232_alter_account-recovery-demand_add_unique_temporary_key.js
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3180 [FEATURE] Vérification des informations de naissance lors de l'ajout d'un candidat à une session de certification (PIX-2715)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/services/certification-cpf-service.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/import-certification-candidates-from-candidates-import-sheet.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-data.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-file.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ok.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-special-birthdate-ok.ods
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_reports_categorization_test.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-5_extract_birth_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-5_extract_mandatory_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-5_extract_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/services/certification-cpf-service_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  api/tests/unit/domain/usecases/import-certification-candidates-from-attendance-sheet_test.js
  api/tests/unit/domain/usecases/import-certification-candidates-from-candidates-import-sheet_test.js
  certif/app/components/enrolled-candidates.js
  certif/app/components/import-candidates.js
  certif/app/components/new-certification-candidate-modal.js
  certif/mirage/config.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/unit/components/new-certification-candidate-modal_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3193 [FEATURE] Ajouter dans la liste des paliers la présence du titre et de la description du prescripteur (PIX-2831).
  admin/app/components/common/tick-or-cross.hbs
  admin/app/components/common/tick-or-cross.js
  admin/app/components/target-profiles/stages.hbs
  admin/app/models/stage.js
  admin/app/styles/app.scss
  admin/app/styles/components/common/tick-or-cross.scss
  admin/tests/integration/components/target-profiles/stages_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3194 [BUGFIX] Importer un fichier ods d'import avec des candidats ajoutés manuellement ne fonctionne pas (PIX-2830)
  api/lib/infrastructure/files/candidates-import/fill-candidates-import-sheet.js
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template.ods
  api/tests/integration/infrastructure/utils/ods/files/fill-candidates-import-sheet_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3188 [FEATURE] Afficher la date de création et le créateur pour une campagne d'évaluation (PIX-2741).
  orga/app/components/campaign-participants-details.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/tests/integration/components/routes/authenticated/campaign/report_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3196 [BUGFIX] Permettre la sauvegarde d'un assessment result annulé (PIX-2835)
  api/lib/domain/models/AssessmentResult.js
  api/lib/domain/usecases/correct-candidate-identity-in-certification-course.js
  api/lib/infrastructure/orm-models/AssessmentResult.js
  api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
  api/tests/unit/domain/usecases/correct-candidate-identity-in-certification-course_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3183 [TECH] Utiliser la version 14.17.0 de Node au lieu de 14.16.0.
  .circleci/config.yml
  .nvmrc
  INSTALLATION.md
  admin/package.json
  api/package.json
  certif/package.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package.json
  mon-pix/package.json
  orga/package.json
  package.json
  scripts/configure.sh
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3197 [TECH] Arrêter d'utiliser l'Orm-model Bookshelf Answer (PIX-2833)
  api/lib/domain/services/challenge-service.js
  api/lib/domain/services/solution-service.js
  api/lib/infrastructure/repositories/solution-repository.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/integration/domain/services/smart-random/solution-service-function-revalidate_test.js
  api/tests/integration/infrastructure/repositories/solution-repository_test.js
  api/tests/unit/domain/services/challenge-service_test.js
  api/tests/unit/domain/services/solution-service-function-match_test.js
  api/tests/unit/domain/services/solution-service-function-revalidate_test.js
  api/tests/unit/domain/services/solution-service-function-timedOut_test.js
  api/tests/unit/domain/services/solution-service-qcm_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#3199 [TECH] Déplace le fichier SECURITY.md a la racine
  SECURITY.md
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3189 [TECH] Utiliser la version mineure 12.7 de BDD PostgreSQL .
  .circleci/config.yml
  docker-compose.yml
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3205 [CLEANUP] Lancer eslint sur high-level-tests/{test-algo,e2e}
  .circleci/config.yml
  high-level-tests/e2e/package.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3200 [BUGFIX] Permettre l'envoi du formulaire d'ajout de candidat sous IE (PIX-2834)
  api/db/seeds/data/certification/certification-cpf-city-builder.js
  api/db/seeds/seed.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/styles/components/new-certification-candidate-modal.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3208 [TECH] Ameliorer l'affichage d'erreur sur le scoring (PIX-2808)
  api/lib/domain/models/CertifiedLevel.js
  api/tests/acceptance/application/certification-course-controller_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#3212 [FEATURE] Téléchargement des attestations par classe : mise en place du feature toggle (PIX-2842)
  api/lib/config.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  orga/app/controllers/authenticated/certifications.js
  orga/app/models/feature-toggle.js
  orga/app/templates/authenticated/certifications.hbs
  orga/tests/acceptance/certifications_test.js
  orga/tests/unit/controllers/authenticated/certifications_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3195 [FEATURE] Rendre le délai d'expiration de la demande de récupération SCO paramétrable (PIX-2827).
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
Labels: :rocket: Ready to Merge, team-acces

#3221 [TECH] Améliorer la traduction de "délai d'expiration".
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#3185 [FEATURE] Avoir une image par défaut sur les paliers (PIX-2769).
  api/db/database-builder/factory/build-target-profile.js
  api/db/migrations/20210713145931_set-default-target-profile-image.js
  api/lib/domain/usecases/create-target-profile.js
  api/tests/unit/domain/usecases/create-target-profile_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3201 [FEATURE] Empêcher l'usurpation d'identité lors de la récupération de compte SCO (PIX-2811).
  api/db/database-builder/factory/build-account-recovery-demand.js
  api/db/migrations/20210715153308_add-column-schoolingRegistrationId-to-account-recovery-demands-table.js
  api/lib/application/account-recovery/account-recovery-controller.js
  api/lib/application/account-recovery/index.js
  api/lib/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller.js
  api/lib/domain/models/AccountRecoveryDemand.js
  api/lib/domain/read-models/StudentInformationForAccountRecovery.js
  api/lib/domain/services/check-sco-account-recovery-service.js
  api/lib/domain/usecases/check-sco-account-recovery.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/send-email-for-account-recovery.js
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/jsonapi/student-information-for-account-recovery-serializer.js
  api/tests/acceptance/application/account-recovery/account-recovery-route-get_test.js
  api/tests/acceptance/application/account-recovery/account-recovery-route_test.js
  api/tests/acceptance/application/schooling-registration-dependent-user-route_test.js
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/tooling/domain-builder/factory/build-account-recovery-demand.js
  api/tests/unit/application/account-recovery/account-recovery-controller_test.js
  api/tests/unit/application/schooling-registration-dependent-user/schooling-registration-dependant-user-controller_test.js
  api/tests/unit/domain/services/check-sco-account-recovery-service_test.js
  api/tests/unit/domain/usecases/account-recovery/send-email-for-account-recovery_test.js
  api/tests/unit/domain/usecases/check-sco-account-recovery_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-information-for-account-recovery-serializer_test.js
  mon-pix/app/components/account-recovery/backup-email-confirmation-form.hbs
  mon-pix/app/components/account-recovery/backup-email-confirmation-form.js
  mon-pix/app/components/account-recovery/student-information-form.hbs
  mon-pix/app/components/account-recovery/student-information-form.js
  mon-pix/app/controllers/account-recovery-after-leaving-sco.js
  mon-pix/app/models/account-recovery-demand.js
  mon-pix/app/models/student-information.js
  mon-pix/app/styles/components/account-recovery/_student-information-form.scss
  mon-pix/app/styles/pages/_account-recovery-after-leaving-sco.scss
  mon-pix/app/templates/account-recovery-after-leaving-sco.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/account-recovery/backup-email-confirmation-form-test.js
  mon-pix/tests/unit/controllers/account-recovery-after-leaving-sco-test.js
  mon-pix/tests/unit/models/account-recovery-demand-test.js
  mon-pix/tests/unit/models/student-information-test.js
Labels: :rocket: Ready to Merge, team-acces

#3211 [BUGFIX] Corriger certaines régressions suite au développement CPF (PIX-2628).
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/routes/authenticated/sessions/details/certification-candidates.js
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/certification-candidate-details-modal/certification-candidate-details-modal_test.js
  certif/tests/unit/routes/authenticated/sessions/details/certification-candidate_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3225 [BUGFIX] Corriger le script d'import des villes (PIX-2857).
  api/scripts/import-certification-cpf-cities.js
  api/tests/unit/scripts/import-certification-cpf-cities_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3203 [FEATURE] Ajout du paramètre enErreur pour la récupération des résultats à la campagne Pôle emploi (PIX-2684).
  api/db/database-builder/factory/build-authentication-method.js
  api/db/database-builder/factory/index.js
  api/db/database-builder/factory/pole-emploi-sending-factory.js
  api/db/seeds/data/pole-emploi-sendings-builder.js
  api/lib/application/pole-emplois/pole-emploi-controller.js
  api/lib/domain/services/pole-emploi-service.js
  api/lib/domain/usecases/get-pole-emploi-sendings.js
  api/lib/infrastructure/repositories/pole-emploi-sending-repository.js
  api/tests/acceptance/application/pole-emploi-controller_test.js
  api/tests/integration/domain/usecases/get-pole-emploi-sendings_test.js
  api/tests/integration/infrastructure/repositories/pole-emploi-sending-repository_test.js
  api/tests/integration/scripts/prod/compute-pole-emploi-sendings_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/domain/services/pole-emploi-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3220 [BUGFIX] Changer le wording de la tooltip pour la carte total participant de l'onglet activité (PIX-2850)
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3228 [BUGFIX] Isoler la création de données de tests pour que les données n'altèrent pas d'autres tests (PIX-2867).
  api/tests/integration/domain/services/placement-profile-service_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3218 [FEATURE] Pour les campagne de collecte de profils, toujours afficher la date de création et le nom de la personne qui a créé la campagne (Pix-2822)
  orga/app/components/campaign-participants-details.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/routes/authenticated/campaign/report.js
  orga/tests/integration/components/routes/authenticated/campaign/report_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3229 [CLEANUP] Téléchargement des attestations : refactoring préparatoire à la génération de n attestations dans le même fichier (PIX-2868)
  api/lib/application/certifications/certification-controller.js
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
  api/lib/infrastructure/utils/pdf/write-pdf-utils.js
  api/tests/integration/infrastructure/utils/pdf/write-pdf-utils_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/infrastructure/utils/pdf/certification-attestation-pdf_test.js
  api/tests/unit/infrastructure/utils/write-pdf-utils_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3217 [FEATURE] Séparer l'édition des informations candidat du reste sur la page dans PixAdmin (PIX-2837)
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3232 [TECH] Supprimer la table "autojury-script-audit" (PIX-2744).
  api/db/migrations/20210722122054_drop-table-autojury-script-audit.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3234 [FEATURE] Affichage de l'onglet "Activité" pour les campagnes de collecte de profils (PIX-2772).
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/routes/authenticated/campaign/profile/details.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/routes/authenticated/campaigns/campaign.js
  orga/mirage/config.js
  orga/mirage/factories/campaign.js
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/acceptance/profile_test.js
  orga/tests/integration/components/routes/authenticated/campaign/report_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/activity_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3219 [FEATURE] Afficher un message générique quand aucun participant n'a rejoint la campagne (PIX-2671).
  orga/app/components/campaign/analysis/competences.hbs
  orga/app/components/campaign/analysis/recommendations.hbs
  orga/app/components/campaign/analysis/recommendations.js
  orga/app/components/campaign/analysis/tube-recommendation-row.hbs
  orga/app/components/campaign/analysis/tube-recommendation-row.js
  orga/app/components/campaign/copy-paste-button.hbs
  orga/app/components/campaign/copy-paste-button.js
  orga/app/components/campaign/empty-state.hbs
  orga/app/components/campaign/empty-state.js
  orga/app/components/routes/authenticated/campaign/details/tab.hbs
  orga/app/components/routes/authenticated/campaign/details/tab.js
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/routes/authenticated/campaign/report.js
  orga/app/models/campaign.js
  orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/analysis/recommendations.scss
  orga/app/styles/components/campaign/analysis/tube-recommendation-row.scss
  orga/app/styles/components/campaign/empty-state.scss
  orga/app/styles/components/campaign/index.scss
  orga/app/templates/authenticated/campaigns/assessment/analysis.hbs
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/app/templates/authenticated/campaigns/campaign/analysis.hbs
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
  orga/public/images/empty-state.svg
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/acceptance/campaign-analysis_test.js
  orga/tests/acceptance/campaign-assessment-results_test.js
  orga/tests/acceptance/campaign-profiles_test.js
  orga/tests/integration/components/campaign/activity/participants-activity-list_test.js
  orga/tests/integration/components/campaign/analysis/competences_test.js
  orga/tests/integration/components/campaign/copy-paste-button_test.js
  orga/tests/integration/components/campaign/empty-state_test.js
  orga/tests/integration/components/campaign/results/assessment-list_test.js
  orga/tests/integration/components/routes/authenticated/campaign/analysis/recommendations_test.js
  orga/tests/integration/components/routes/authenticated/campaign/analysis/tube-recommendation-row_test.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3224 [TECH] Suppression de routes dépréciées et/ou inutilisées.
  api/db/seeds/data/target-profiles-builder.js
  api/lib/application/campaign-participation-results/campaign-participation-result-controller.js
  api/lib/application/campaign-participation-results/index.js
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/application/campaign-participations/index.js
  api/lib/domain/usecases/find-campaign-participations-related-to-assessment.js
  api/lib/domain/usecases/get-campaign-participation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/acceptance/application/users/get-user-campaign-participation-to-campaign_test.js
  api/tests/acceptance/application/users/users-controller-get-campaign-participations_test.js
  api/tests/integration/application/campaignParticipations/index_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/unit/application/campaignParticipationResult/campaign-participation-result-controller_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/usecases/find-campaign-participations-related-to-assessment_test.js
  api/tests/unit/domain/usecases/get-campaign-participation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  mon-pix/mirage/routes/campaign-participations/get-campaign-participation.js
  mon-pix/mirage/routes/campaign-participations/index.js
  mon-pix/mirage/serializers/campaign-participation.js
  orga/mirage/config.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-prescription

#3237 [FEATURE] Afficher la réponse apportée par le candidat dans l'encart d'épreuve sur la page de détails d'une certification dans PixAdmin (PIX-2887)
  admin/app/components/certification/certification-details-answer.hbs
  admin/app/styles/components/certification-details-answer.scss
  admin/tests/integration/components/certification/certification-details-answer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3238 [FEATURE] Etre plus tolérant sur la vérification des noms / prénoms dans le formulaire d'entrée en certification sur PixApp (PIX-2630)
  api/db/database-builder/factory/build-certification-cpf-country.js
  api/lib/domain/services/certification-cpf-service.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/lib/infrastructure/utils/string-utils.js
  api/scripts/import-certification-cpf-countries.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/tooling/domain-builder/factory/build-country.js
  api/tests/unit/infrastructure/utils/string-utils_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3213 [FEATURE] Afficher les informations CPF dans PixAdmin (PIX-2838)
  admin/app/components/certification/certification-info-field.hbs
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/models/certification.js
  admin/app/models/feature-toggle.js
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/mirage/config.js
  admin/mirage/factories/feature-toggle.js
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
  api/db/database-builder/factory/build-certification-course.js
  api/db/database-builder/factory/build-schooling-registration-with-user.js
  api/db/database-builder/factory/build-schooling-registration.js
  api/db/migrations/20210721084659_add-birthCountry-in-certification-course-table.js
  api/db/seeds/data/certification/user-profiles-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/models/SCOCertificationCandidate.js
  api/lib/domain/read-models/CertificationResultInformation.js
  api/lib/domain/read-models/GeneralCertificationInformation.js
  api/lib/domain/usecases/enroll-students-to-session.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/general-certification-information-repository.js
  api/lib/infrastructure/repositories/sco-certification-candidate-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-result-information-serializer.js
  api/lib/infrastructure/validate-environement-variables.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/general-certification-information-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-course.js
  api/tests/tooling/domain-builder/factory/build-general-certification-information.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/read-models/CertificationResultInformation_test.js
  api/tests/unit/domain/usecases/enroll-students-to-session_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-information-serializer_test.js
  certif/app/components/add-student-list.hbs
  certif/app/components/add-student-list.js
  certif/app/styles/components/add-student-list.scss
  certif/app/templates/authenticated.hbs
  certif/app/templates/authenticated/sessions/details.hbs
  certif/tests/integration/components/add-student-list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3233 [FEATURE] Permettre de lancer plusieurs utilisateurs en même temps sur Algolix (PIX-2069).
  high-level-tests/test-algo/AlgoResult.js
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/index.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#3179 [TECH] Modifier l'organisation des composants d'élèves dans Pix Orga (PIX-2881)
  orga/app/components/routes/authenticated/sco-students/list-items.hbs
  orga/app/components/routes/authenticated/sup-students/list-items.hbs
  orga/app/components/student/sco/dissociate-user-modal.hbs
  orga/app/components/student/sco/dissociate-user-modal.js
  orga/app/components/student/sco/header-actions.hbs
  orga/app/components/student/sco/header-actions.js
  orga/app/components/student/sco/list.hbs
  orga/app/components/student/sco/list.js
  orga/app/components/student/sco/manage-authentication-method-modal.hbs
  orga/app/components/student/sco/manage-authentication-method-modal.js
  orga/app/components/student/sup/edit-student-number-modal.hbs
  orga/app/components/student/sup/edit-student-number-modal.js
  orga/app/components/student/sup/header-actions.hbs
  orga/app/components/student/sup/header-actions.js
  orga/app/components/student/sup/list.hbs
  orga/app/components/student/sup/list.js
  orga/app/templates/authenticated/sco-students/list.hbs
  orga/app/templates/authenticated/sup-students/list.hbs
  orga/tests/integration/components/students/sco/dissociate-user-modal_test.js
  orga/tests/integration/components/students/sco/header-actions_test.js
  orga/tests/integration/components/students/sco/list_test.js
  orga/tests/integration/components/students/sco/manage-authentication-method-modal_test.js
  orga/tests/integration/components/students/sup/edit-student-number-modal_test.js
  orga/tests/integration/components/students/sup/header-actions_test.js
  orga/tests/integration/components/students/sup/list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-prescription

#3236 [TECH] Refacto autour du certification-result-service (PIX-2886)
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/domain/events/handle-certification-rescoring.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/models/CertificationAssessmentScore.js
  api/lib/domain/read-models/CertificationDetails.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/domain/usecases/get-certification-details.js
  api/lib/domain/usecases/index.js
  api/tests/integration/domain/services/scoring/scoring-certification_test.js
  api/tests/tooling/domain-builder/factory/build-certification-assessment-score.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/events/handle-certification-rescoring_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/CertificationAssessmentScore_test.js
  api/tests/unit/domain/read-models/CertificationDetails_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/services/scoring/scoring-certification-service_test.js
  api/tests/unit/domain/usecases/get-certification-details_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3235 [BUGFIX]Changer le wording et la couleurs des tags dans la liste des participants dans la page Activité(PIX-2872)
  orga/app/components/campaign/activity/participation-status.js
  orga/app/components/charts/participants-by-status.js
  orga/app/components/routes/authenticated/campaign/report.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3139 [FEATURE] Ajout de nouveaux marqueurs visuels aux challenges : épreuve focus (PIX-2755).
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/styles/components/_assessment-banner.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_challenge.scss
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/pages/_assessment-challenge.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/focused-challenge-instructions.hbs
  mon-pix/app/templates/components/timed-challenge-instructions.hbs
  mon-pix/config/environment.js
  mon-pix/public/images/tag-focused-challenge.svg
  mon-pix/public/images/tag-regular-challenge.svg
  mon-pix/tests/acceptance/challenge-commons_test.js
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/acceptance/compare-answer-solution-qroc_test.js
  mon-pix/tests/acceptance/compare-answer-solution_test.js
  mon-pix/tests/integration/components/challenge-item-qroc_test.js
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3240 [FEATURE] Supprimer l'écran intermédiaire des épreuves focus (PIX-2889).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_focused-challenge-instructions.scss
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/focused-challenge-instructions.hbs
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/unit/components/challenge-item-generic_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3230 [FEATURE] Accepter une correspondance approximative sur un utilisateur lors de la sortie SCO (PIX-2758).
  api/lib/domain/services/check-sco-account-recovery-service.js
  api/lib/domain/services/user-reconciliation-service.js
  api/lib/domain/usecases/check-sco-account-recovery.js
  api/lib/domain/usecases/generate-username.js
  api/lib/domain/usecases/send-email-for-account-recovery.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/domain/services/check-sco-account-recovery-service_test.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
  api/tests/unit/domain/usecases/account-recovery/send-email-for-account-recovery_test.js
  api/tests/unit/domain/usecases/check-sco-account-recovery_test.js
Labels: :rocket: Ready to Merge, team-acces

#3214 [INFRA] Ajouter des helpers de tests getByLabel et queryByLabel
  certif/tests/helpers/extended-ember-test-helpers/click-by-label.js
  certif/tests/helpers/extended-ember-test-helpers/fill-in-by-label.js
  certif/tests/helpers/extended-ember-test-helpers/get-by-label.js
  certif/tests/helpers/extended-ember-test-helpers/query-by-label.js
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3247 [FEATURE] Déplacer l'édition des informations Candidat dans une modale dédiée dans PixAdmin (PIX-2839)
  admin/app/components/certification/candidate-edit-modal.hbs
  admin/app/components/certification/candidate-edit-modal.js
  admin/app/components/modal/body.hbs
  admin/app/components/modal/dialog.hbs
  admin/app/components/modal/dialog.js
  admin/app/components/modal/footer.hbs
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/styles/app.scss
  admin/app/styles/components/certification/candidate-edit-modal.scss
  admin/app/styles/components/modal.scss
  admin/app/styles/globals/button.scss
  admin/app/styles/globals/callout.scss
  admin/app/styles/globals/fonts.scss
  admin/app/styles/globals/form.scss
  admin/app/styles/globals/global.scss
  admin/app/styles/globals/nav.scss
  admin/app/styles/globals/page.scss
  admin/app/styles/globals/palette.scss
  admin/app/styles/globals/power-select.scss
  admin/app/styles/globals/table-admin.scss
  admin/app/styles/globals/tables.scss
  admin/app/styles/globals/utils.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/helpers/contains.js
  admin/tests/integration/components/certification/candidate-edit-modal_test.js
  admin/tests/integration/components/modal/dialog_test.js
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3248 [TECH] Réorganisation des composants relatifs à la finalisation de session sur PixCertif (PIX-2900)
  certif/app/components/session-finalization/examiner-global-comment-step.hbs
  certif/app/components/session-finalization/examiner-global-comment-step.js
  certif/app/components/session-finalization/formbuilder-link-step.hbs
  certif/app/components/session-finalization/formbuilder-link-step.js
  certif/app/components/session-finalization/reports-informations-step.hbs
  certif/app/components/session-finalization/reports-informations-step.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/styles/app.scss
  certif/app/styles/components/session-finalization/examiner-global-comment-step.scss
  certif/app/styles/components/session-finalization/formbuilder-link-step.scss
  certif/app/styles/components/session-finalization/reports-informations-step.scss
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/tests/integration/components/formbuilder-link-step_test.js
  certif/tests/integration/components/session-finalization/examiner-global-comment-step_test.js
  certif/tests/integration/components/session-finalization/reports-informations-step_test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3250 [FEATURE] Mettre à jour le libellé du destinataire des résultats dans le tableau des candidats inscrits à une session de certification (PIX-2901).
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/enrolled-candidates.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3244 [FEATURE] Permettre accéder à la page "Résultats d'un participant à une campagne d'évaluation" au clavier (PIX-2634)
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/assessment-results.js
  orga/tests/integration/components/campaign/results/assessment-list_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/assessment-results_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3241 [FEATURE] Permettre d'accéder à la page "Résultats d'un participant à une campagne de collecte de profils" au clavier(PIX-2635)
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/profiles.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/list_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/profiles_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3242 [FEATURE] Désactiver les schooling registrations à l'import des élèves (SCO) (PIX-2854)
  api/db/database-builder/factory/build-schooling-registration.js
  api/db/migrations/20210726130724_add-isDisabled-column-in-schooling-registrations-table.js
  api/db/seeds/data/organizations-sco-builder.js
  api/db/seeds/data/organizations-sup-builder.js
  api/lib/domain/models/SchoolingRegistration.js
  api/lib/domain/services/schooling-registrations-csv-service.js
  api/lib/domain/usecases/import-schooling-registrations-from-siecle.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/domain/services/schooling-registrations-csv-service_test.js
  api/tests/integration/domain/services/schooling-registrations-xml-service_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/tooling/fixtures/siecle-file/not-valid.xml
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-duplicate-national-student-id.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-no-national-student-id.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-two-valid-students.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-unknown-encoding.csv
  api/tests/tooling/fixtures/siecle-file/siecle-with-one-valid-student.xml
  api/tests/tooling/fixtures/siecle-file/siecle.xml
  api/tests/tooling/fixtures/siecle-file/wrong-file.txt
  api/tests/unit/domain/usecases/import-schooling-registrations-from-siecle_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3243 [FEATURE] Afficher les schooling registrations actives dans la liste des élèves (PIX-2859)
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3216 [FEATURE] Choisir un mot de passe lors de la récupération d'un compte SCO (PIX-2740).
  api/db/database-builder/factory/build-account-recovery-demand.js
  api/db/migrations/20210715184135_add-email-confirmed-at-to-users.js
  api/lib/application/account-recovery/account-recovery-controller.js
  api/lib/application/account-recovery/index.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/account-recovery/get-account-recovery-details.js
  api/lib/domain/usecases/account-recovery/get-user-by-account-recovery-demand.js
  api/lib/domain/usecases/account-recovery/update-user-account.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/send-email-for-account-recovery.js
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/student-information-for-account-recovery-serializer.js
  api/tests/acceptance/application/account-recovery/account-recovery-route-get_test.js
  api/tests/acceptance/application/account-recovery/account-recovery-route-patch_test.js
  api/tests/integration/application/account-recovery/account-recovery-controller_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/usecases/account-recovery/update-user-account_test.js
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-authentication-method.js
  api/tests/unit/application/account-recovery/account-recovery-controller_test.js
  api/tests/unit/domain/usecases/account-recovery/get-account-recovery-details_test.js
  api/tests/unit/domain/usecases/account-recovery/get-user-by-account-recovery-demand_test.js
  api/tests/unit/domain/usecases/account-recovery/update-user-account_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-information-for-account-recovery-serializer_test.js
  mon-pix/app/adapters/account-recovery-demand.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/account-recovery/reset-password-form.hbs
  mon-pix/app/components/account-recovery/reset-password-form.js
  mon-pix/app/models/account-recovery-demand.js
  mon-pix/app/routes/account-recovery/reset-password.js
  mon-pix/app/templates/account-recovery/reset-password.hbs
  mon-pix/tests/integration/components/account-recovery/reset-password-form-test.js
  mon-pix/tests/unit/models/account-recovery-demand-test.js
  mon-pix/tests/unit/routes/account-recovery/reset-password-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3251 [TECH] Modifier l'organisation des composants d'authentification dans Pix Orga (PIX-2902)
  orga/app/components/auth/join-request-form.hbs
  orga/app/components/auth/join-request-form.js
  orga/app/components/auth/login-form.hbs
  orga/app/components/auth/login-form.js
  orga/app/components/auth/login-or-register.hbs
  orga/app/components/auth/login-or-register.js
  orga/app/components/auth/register-form.hbs
  orga/app/components/auth/register-form.js
  orga/app/templates/join-request.hbs
  orga/app/templates/join.hbs
  orga/app/templates/login.hbs
  orga/tests/integration/components/auth/join-request-form_test.js
  orga/tests/integration/components/auth/login-form_test.js
  orga/tests/integration/components/auth/login-or-register_test.js
  orga/tests/integration/components/auth/register-form_test.js
  orga/tests/unit/components/auth/login-form_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-acces, team-prescription

#3187 [FEATURE] Ajout du filtre classe sur la page Activité pour les organisations SCO (PIX-2670).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/read-models/CampaignParticipantActivity.js
  api/lib/domain/usecases/find-paginated-campaign-participants-activities.js
  api/lib/infrastructure/repositories/campaign-participant-activity-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/domain/usecases/find-paginated-campaign-participant-activities_test.js
  api/tests/integration/infrastructure/repositories/campaign-participant-activity-repository_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participant-activity-serializer_test.js
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/activity/participation-status.js
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/campaign/filter/participation-filters.js
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/models/campaign-participant-activity.js
  orga/app/routes/authenticated/campaigns/campaign/activity.js
  orga/app/styles/app.scss
  orga/app/styles/globals/a11y.scss
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/app/templates/authenticated/campaigns/campaign/profiles.hbs
  orga/tests/integration/components/campaign/filter/participation-filters_test.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription
