Repository 1024pix/pix, pull requests merged in 2021-06, with the labels that each got.

#3045 [BUGFIX] Correction de référentiel en français alors que la langue est configurée comme l'anglais (PIX-2609).
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/get-user-profile-shared-for-campaign.js
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/lib/infrastructure/exports/campaigns/campaign-profiles-collection-result-line.js
  api/lib/infrastructure/serializers/csv/campaign-profiles-collection-export.js
  api/tests/unit/domain/usecases/get-user-profile-shared-for-campaign_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/unit/infrastructure/exports/campaigns/campaign-profile-collection-result-line_test.js
  api/tests/unit/infrastructure/serializers/csv/campaign-profile-collection-export_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3050 [FEATURE] Ajouter sur le détail d'une session un lien vers le centre de certification associé (PIX-2644)
  admin/app/models/session.js
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/mirage/factories/session.js
  admin/tests/acceptance/session_test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations_test.js
  api/lib/domain/models/JurySession.js
  api/lib/infrastructure/serializers/jsonapi/jury-session-serializer.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-session-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3046 [TECH] Afficher les RT dans le détail d'un participant, à partir de l'id de la campaignParticipation (PIX-2623)
  api/lib/domain/usecases/get-campaign-assessment-participation.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/unit/domain/usecases/get-campaign-assessment-participation_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3027 [BUGFIX] Ne pas empêcher l'export des résultats même en cas de champs manquant (PIX-2512)
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3053 [BUGFIX] Corriger le problème d'affichage du filtre de classes lorsqu'il n'y en a aucune (PIX-2605).
  orga/app/components/routes/authenticated/campaign/participation-filters.js
  orga/tests/integration/components/routes/authenticated/campaign/participation-filters_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3036 [TECH] Prévenir les faux positifs liés à la BDD dans les tests.
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/integration/scripts/create-certification-center-memberships-from-organization-admins_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3020 [FEATURE] Ne plus afficher les recID des challenges dans l'URL des assessments (PIX-327).
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/models/assessment.js
  mon-pix/app/router.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/routes/challenge-preview.js
  mon-pix/tests/acceptance/certification-course_test.js
  mon-pix/tests/acceptance/challenge-attachment_test.js
  mon-pix/tests/acceptance/challenge-commons_test.js
  mon-pix/tests/acceptance/challenge-feedback_test.js
  mon-pix/tests/acceptance/challenge-qcm_test.js
  mon-pix/tests/acceptance/challenge-qcu_test.js
  mon-pix/tests/acceptance/challenge-qroc_test.js
  mon-pix/tests/acceptance/challenge-qrocm_test.js
  mon-pix/tests/acceptance/challenge-timed_test.js
  mon-pix/tests/acceptance/logout-anonymous-user-when-access-to-not-allowed-pages_test.js
  mon-pix/tests/unit/routes/assessments/challenge_test.js
  mon-pix/tests/unit/routes/assessments/resume_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3055 [CLEAN] Supprime le champ non utilisé `skills` des objets `challenge` du référentiel.
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/integration/domain/services/pick-certification-challenge_test.js
  api/tests/tooling/domain-builder/factory/build-challenge-learning-content-data-object.js
  api/tests/tooling/fixtures/infrastructure/challengeLearningContentDataObjectFixture.js
  api/tests/unit/domain/usecases/get-next-challenge-for-demo_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-ref

#3061 [BUGFIX] Inverser le nom et prénom en anglais dans la liste des participants (PIX-2652).
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3059 Optimisation livret scolaire (PIX-2659)
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3006 [FEATURE] Autoneutraliser les questions avec signalements sans vérification préalable nécessaire (PIX-2575)
  api/lib/domain/events/AutoJuryDone.js
  api/lib/domain/events/CertificationJuryDone.js
  api/lib/domain/events/handle-auto-jury.js
  api/lib/domain/events/handle-certification-rescoring.js
  api/lib/domain/events/handle-session-finalized.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/NeutralizationAttempt.js
  api/lib/infrastructure/events/EventDispatcher.js
  api/lib/infrastructure/repositories/certification-issue-report-repository.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/integration/infrastructure/event-dispatcher_test.js
  api/tests/integration/infrastructure/repositories/certification-issue-report-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-report-repository_test.js
  api/tests/integration/infrastructure/repositories/general-certification-information-repository_test.js
  api/tests/unit/domain/events/event-choreography-certification-rescoring-after-jury_test.js
  api/tests/unit/domain/events/event-choreography-finalized-session_test.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/events/handle-session-finalized_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3062 [TECH] Changer la manière d'afficher les RT dans la liste des participants dans Pix Orga (PIX-2624)
  api/lib/domain/usecases/find-paginated-campaign-assessment-participation-summaries.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-summary-repository.js
  api/tests/integration/domain/usecases/find-paginated-campaign-assessment-participation-summaries_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-summary-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3072 [TECH] Changer la manière d'afficher les RT dans l'export CSV d'une Campagne d’évaluation dans Pix Orga (PIX-2625)
  api/lib/domain/read-models/CampaignParticipationInfo.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/infrastructure/repositories/campaign-participation-info-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-info-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-info.js
  api/tests/unit/domain/read-models/CampaignParticipationInfo_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3066 [BUGFIX] Afficher correctement le texte personnalisable d'une organisation à la fin d'un parcours prescrit (PIX-2676).
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3058 [BUGFIX] Corriger le calcul du taux de repro (PIX-2651)
  api/lib/domain/models/AnswerCollectionForScoring.js
  api/lib/domain/models/CertificationChallenge.js
  api/lib/domain/models/CertificationChallengeWithType.js
  api/lib/domain/services/certification-result-service.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-assessment.js
  api/tests/tooling/domain-builder/factory/build-certification-challenge-with-type.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/events/handle-certification-rescoring_test.js
  api/tests/unit/domain/events/handle-pix-plus-certifications-scoring_test.js
  api/tests/unit/domain/models/AnswerCollectionForScoring_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/CertificationChallengeWithType_test.js
  api/tests/unit/domain/models/CertificationChallenge_test.js
  api/tests/unit/domain/read-models/CertificationDetails_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/usecases/deneutralize-challenge_test.js
  api/tests/unit/domain/usecases/get-certification-details_test.js
  api/tests/unit/domain/usecases/neutralize-challenge_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3031 [FEATURE] Ajouter et supprimer un tag à une organisation sur Pix Admin (PIX-2601)
  admin/app/components/organization-all-tags.hbs
  admin/app/components/organization-all-tags.js
  admin/app/models/tag.js
  admin/app/routes/authenticated/organizations/get/all-tags.js
  admin/app/styles/authenticated/organizations/all-tags.scss
  admin/app/templates/authenticated/organizations/get/all-tags.hbs
  admin/tests/integration/components/organization-all-tags_test.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-organization-information.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/organization-tag-repository.js
  api/lib/infrastructure/repositories/tag-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/domain/usecases/update-organization-information_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-tag-repository_test.js
  api/tests/integration/infrastructure/repositories/tag-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: :eyes: Func Review Needed, :rocket: Ready to Merge, Tech Review OK, team-acces

#3044 [FEATURE] Permettre de récupérer la solution du challenge en cours depuis le bouton magique (PIX-2618).
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/assessments/index.js
  api/lib/application/security-pre-handlers.js
  api/lib/domain/read-models/ChallengeForPixAutoAnswer.js
  api/lib/domain/usecases/get-challenge-for-pix-auto-answer.js
  api/lib/domain/usecases/get-last-challenge-id-from-assessment-id.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/challenge-for-pix-auto-answer-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-get-challenge-for-pix-button_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-last-challenge-id_test.js
  api/tests/integration/infrastructure/repositories/challenge-for-pix-auto-answer-repository_test.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/unit/domain/usecases/get-challenge-for-pix-auto-answer_test.js
  api/tests/unit/domain/usecases/get-last-challenge-id-from-assessment-id_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team, team-evaluation

#3057 [FEATURE] Afficher la certificabilité de l'utilisateur sur les certifications complémentaires sur la page d'entrée en certification dans la bannière (PIX-2587)
  api/lib/application/users/user-controller.js
  api/lib/domain/read-models/CertificationEligibility.js
  api/lib/domain/services/certification-badges-service.js
  api/lib/domain/usecases/get-user-certification-eligibility.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/is-user-certifiable.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-eligibility-serializer.js
  api/lib/infrastructure/serializers/jsonapi/is-certifiable-serializer.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-eligibility.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/services/certification-badges-service-test.js
  api/tests/unit/domain/usecases/get-user-certification-eligibility_test.js
  api/tests/unit/domain/usecases/is-user-certifiable_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-eligibility-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/is-certifiable-serializer_test.js
  mon-pix/app/components/certification-joiner.js
  mon-pix/app/components/certification-starter.js
  mon-pix/app/components/stepper.js
  mon-pix/app/controllers/certifications/start.js
  mon-pix/app/mixins/progression-tracker.js
  mon-pix/app/models/is-certifiable.js
  mon-pix/app/services/peeker.js
  mon-pix/app/styles/components/_congratulations-certification-banner.scss
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/components/certification-joiner.hbs
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/app/templates/components/certification-stepper-join.hbs
  mon-pix/app/templates/components/certification-stepper-start.hbs
  mon-pix/app/templates/components/congratulations-certification-banner.hbs
  mon-pix/app/templates/components/stepper.hbs
  mon-pix/tests/integration/components/certification-joiner_test.js
  mon-pix/tests/integration/components/certification-starter_test.js
  mon-pix/tests/integration/components/congratulations-certification-banner_test.js
  mon-pix/tests/unit/components/certification-starter_test.js
  mon-pix/tests/unit/services/peeker_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#3070 [FEATURE] Création d'un composant de carte d'indicateur dans Pix Orga (Pix-2663).
  orga/app/components/indicator-card.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/indicator-card.scss
  orga/config/icons.js
  orga/tests/integration/components/indicator-card-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3063 [INFRA] Corriger des erreurs dans les seeds
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/organizations-sco-builder.js
Labels: :rocket: Ready to Merge, team-certif

#3069 [TECH] Afficher qu'un exemplaire d'un RT (PIX-2658)
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3076 [FEATURE] Afficher la date de création et le nom du créateur d'une campagne dans le détail d'une campagne (PIX-2672)
  orga/app/components/campaign-creation-details.hbs
  orga/app/components/campaign-participants-details.hbs
  orga/app/components/routes/authenticated/campaign/details/tab.js
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/routes/authenticated/campaign/report.js
  orga/app/styles/pages/authenticated/campaigns/details.scss
  orga/tests/integration/components/routes/authenticated/campaign/report_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3073 [FEATURE] Ajout des titres à toutes les pages de Pix Certif (PIX-2650)
  certif/app/controllers/authenticated/sessions/add-student.js
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/controllers/authenticated/sessions/new.js
  certif/app/controllers/authenticated/sessions/update.js
  certif/app/templates/application.hbs
  certif/app/templates/authenticated/sessions.hbs
  certif/app/templates/authenticated/sessions/add-student.hbs
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/app/templates/authenticated/sessions/new.hbs
  certif/app/templates/authenticated/sessions/update.hbs
  certif/app/templates/login.hbs
  certif/app/templates/logout.hbs
  certif/app/templates/terms-of-service.hbs
  certif/package-lock.json
  certif/package.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3082 [TECH] Ajout d'un index dans la table "certification-candidates" pour améliorer les performances d'affichage de la liste de candidats en prescription de certification SCO (PIX-2698)
  api/db/migrations/20210609045948_add-index-on-table-certification-candidates-column-schooling-registration-id.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3060 [TECH] Séparer les routes commune d'Orga et Admin sur les memberships (PIX-2533).
  admin/app/adapters/membership.js
  admin/mirage/config.js
  admin/tests/unit/adapters/membership_test.js
  api/lib/application/memberships/index.js
  api/tests/acceptance/application/membership-controller_test.js
  api/tests/integration/application/memberships/membership-controller_test.js
  api/tests/unit/application/memberships/index_test.js
Labels: :rocket: Ready to Merge, team-acces

#3080 [CLEANUP] Suppression des toggles : recalcule des score dans l'onglet "détail" de Pix-Admin & téléchargement des résultats de certif dans Pix-Orga (PIX-2588)
  admin/app/models/feature-toggle.js
  admin/app/serializers/certification-details.js
  admin/mirage/factories/feature-toggle.js
  admin/tests/acceptance/authenticated/certifications/certification/neutralization_test.js
  api/db/seeds/data/certification/certification-courses-builder.js
  api/db/seeds/data/certification/certification-scores-builder.js
  api/lib/application/certification-courses/index.js
  api/lib/application/organizations/index.js
  api/lib/application/security-pre-handlers.js
  api/lib/config.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/application/security-pre-handlers_test.js
  orga/app/components/sidebar-menu.js
  orga/app/models/feature-toggle.js
  orga/app/routes/authenticated/certifications.js
  orga/app/services/feature-toggles.js
  orga/mirage/factories/feature-toggle.js
  orga/tests/acceptance/authentication_test.js
  orga/tests/acceptance/certifications_test.js
  orga/tests/integration/components/sidebar-menu_test.js
  orga/tests/unit/routes/authenticated/certifications_test.js
  orga/tests/unit/services/feature-toggle_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3078 [FEATURE] Permettre de choisir la langue d'envoie des invitation par email sur Pix Admin (PIX-2559).
  admin/app/adapters/organization-invitation.js
  admin/app/components/organization-members-section.hbs
  admin/app/components/organization-members-section.js
  admin/app/controllers/authenticated/organizations/get/members.js
  admin/app/models/organization-invitation.js
  admin/app/styles/app.scss
  admin/app/styles/components/organization-members-section.scss
  admin/app/styles/misc/nav.scss
  admin/app/styles/misc/page.scss
  admin/mirage/config.js
  admin/tests/acceptance/organization-memberships-management_test.js
  admin/tests/integration/components/organization-members-section_test.js
  admin/tests/unit/controllers/authenticated/organizations/get/members_test.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
Labels: :rocket: Ready to Merge, team-acces

#3077 [FEATURE] Générer un jeton d'accès pour l'application Pôle Emploi afin de consommer l'API Pix (Pix-2679).
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/config.js
  api/lib/domain/usecases/authenticate-application.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/authentication.js
  api/tests/acceptance/application/certifications-livret-scolaire/certification-controller_test.js
  api/tests/test-helper.js
  api/tests/unit/application/authentication/authentication-controller_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3047 [TECH] Mettre à jour les dépendances présentant un risque pour la sécurité
  api/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team, team-captains

#2965 [TECH] Ajouter des détails dans les logs d'erreur du controller SAML.
  api/lib/application/saml/saml-controller.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team, team-acces

#3085 [TECH] Fix test requiring role pixMaster
  api/tests/unit/application/certification-courses/index_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-certif

#3086 [FEATURE] Ajout d'un lien vers la politique de confidentialité dans la page d'inscription sur Pix App (PIX-2694).
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/styles/components/_signup-form.scss
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment_test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/integration/components/signup-form_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3064 [FEATURE] Ajout du graphique de participants par statut (PIX-2662)
  api/lib/application/campaigns/campaign-stats-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/usecases/get-campaign-participations-counts-by-status.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participations-counts-by-status-serializer.js
  api/tests/acceptance/application/campaign-stats-controller_test.js
  api/tests/integration/domain/usecases/get-campaign-participations-counts-by-status__test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participations-counts-by-status-serializer_test.js
  orga/app/adapters/campaign-stats.js
  orga/app/components/charts/chart.hbs
  orga/app/components/charts/chart.js
  orga/app/components/charts/participants-by-status-loader.hbs
  orga/app/components/charts/participants-by-status.hbs
  orga/app/components/charts/participants-by-status.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/campaign/activity.js
  orga/app/styles/app.scss
  orga/app/styles/components/charts/cards.scss
  orga/app/styles/components/charts/index.scss
  orga/app/styles/components/charts/participants-by-status.scss
  orga/app/styles/components/charts/placeholders.scss
  orga/app/styles/pages/authenticated/campaigns/details/activity.scss
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/ember-cli-build.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/charts/participants-by-stage_test.js
  orga/tests/integration/components/charts/participants-by-status_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3087 [TECH] Forcer les tests unitaire HTTP à signaler leur échec.
  api/tests/integration/application/error-manager_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/assessments/index_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/application/certification-point-of-contacts/index_test.js
  api/tests/unit/application/organizations/index_test.js
Labels: :rocket: Ready to Merge, cross-team, team-certif

#3068 [BUGFIX] Corriger l'affichage du détail d'une certification après sa modification (PIX-2661)
  api/db/migrations/20210607142018_fix-certifications-version-v2.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/domain/models/CertificationCourse_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3074 [FEATURE] Auto neutraliser les questions portant sur les images ou simulateurs (PIX-2589).
  api/lib/domain/events/handle-auto-jury.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportResolutionAttempt.js
  api/lib/domain/models/CertificationIssueReportResolutionStrategies.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/NeutralizationAttempt.js
  api/lib/infrastructure/repositories/certification-issue-report-repository.js
  api/tests/integration/infrastructure/repositories/certification-report-repository_test.js
  api/tests/integration/infrastructure/repositories/general-certification-information-repository_test.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/CertificationIssueReportResolutionStrategies_test.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  api/tests/unit/domain/models/Challenge_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3084 [CLEAN] Lever une erreur lorsque la réponse donnée contient une clé inexistante (PIX-2424).
  api/lib/domain/services/solution-service-qrocm-ind.js
  api/tests/unit/domain/services/solution-service-qrocm-ind_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3081 [FEATURE] Proposer un nouveau template de liste de candidats pour l'import qui contient les données pour le CPF (PIX-2654)
  api/db/database-builder/factory/build-certification-candidate.js
  api/db/migrations/20210607163646_add-columns-sex-birthPostalCode-birthINSEECode-in-table-certification-candidates.js
  api/lib/config.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-transformation-structures.js
  api/lib/infrastructure/files/candidates-import/1.4/candidates_import_template.ods
  api/lib/infrastructure/files/candidates-import/1.5/candidates_import_template.ods
  api/lib/infrastructure/files/candidates-import/candidates-import-placeholders.js
  api/lib/infrastructure/files/candidates-import/fill-candidates-import-sheet.js
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/acceptance/application/session/files/1.4/import-certification-candidates-reports-categorization-test-ko-invalid-data.ods
  api/tests/acceptance/application/session/files/1.4/import-certification-candidates-reports-categorization-test-ko-invalid-file.ods
  api/tests/acceptance/application/session/files/1.4/import-certification-candidates-reports-categorization-test-ok.ods
  api/tests/acceptance/application/session/files/1.4/import-certification-candidates-reports-categorization-test-special-birthdate-ok.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-data.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-file.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ok.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-special-birthdate-ok.ods
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_reports_categorization_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/integration/infrastructure/utils/ods/files/1.4/candidates_import_template.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template.ods
  api/tests/integration/infrastructure/utils/ods/files/fill-candidates-import-sheet_test.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3067 [FEATURE] Afficher une fin de parcours personnalisé à la fin d'une campagne à accès simplifié (PIX-2613).
  api/db/seeds/data/campaigns-builder.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/templates/components/campaign-share-button.hbs
  mon-pix/tests/unit/components/routes/campaigns/skill-review_test.js
Labels: :rocket: Ready to Merge, team-acces

#3054 [BUGFIX] Stocker les données d'authentification PE temporairement (PIX-2607).
  api/lib/application/authentication/authentication-controller.js
  api/lib/config.js
  api/lib/domain/models/PoleEmploiTokens.js
  api/lib/domain/services/authentication-service.js
  api/lib/domain/usecases/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/create-user-from-pole-emploi.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/pole-emploi-tokens-repository.js
  api/lib/infrastructure/temporary-storage/InMemoryTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/TemporaryStorage.js
  api/lib/infrastructure/temporary-storage/index.js
  api/package.json
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/acceptance/application/pole-emploi-controller_test.js
  api/tests/integration/infrastructure/repositories/pole-emploi-tokens-repository_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/domain/models/PoleEmploiTokens_test.js
  api/tests/unit/domain/services/authentication-service_test.js
  api/tests/unit/domain/usecases/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/create-user-from-pole-emploi_test.js
  api/tests/unit/infrastructure/temporary-storage/InMemoryTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/TemporaryStorage_test.js
  docs/adr/0023-suppression-du-support-mailjet-pour-le-mailing.md
  docs/adr/0024-encapsuler-appel-http.md
  docs/adr/0025-precisions-sur-les-transactions-et-les-evenements-metier.md
  docs/adr/0026-tester-routeur-api.md
  docs/adr/0027-stocker-temporairement-api.md
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3096 [BUGFIX] Le critère "SomePartnerCompetences" pouvait ne pas prendre toutes les compétences (PIX-2720).
  api/lib/domain/services/badge-criteria-service.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3093 [FEATURE] Prise en compte auto des signalements sur les fichiers qui ne s'ouvrent pas (PIX-2590)
  api/lib/domain/events/handle-auto-jury.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportResolutionStrategies.js
  api/lib/domain/models/Challenge.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/models/CertificationIssueReportResolutionStrategies_test.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  api/tests/unit/domain/models/Challenge_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3079 [FEATURE] Afficher toujours les pages en français sur orga.pix.fr (PIX-2560).
  orga/app/routes/application.js
  orga/tests/unit/routes/application_test.js
  orga/tests/unit/services/url_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3088 [FEATURE] Détecter lorsque l'utilisateur perd le focus de l'onglet actif (PIX-2616).
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/tests/unit/domain/models/Challenge_test.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/models/challenge.js
Labels: :rocket: Ready to Merge, team-evaluation

#3097 [FEATURE] Simplification de la feuille d'émargement (PIX-2656)
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/usecases/import-certification-candidates-from-candidates-import-sheet.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-placeholders.js
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template.ods
  api/lib/infrastructure/files/candidates-import/candidates-import-transformation-structures.js
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/attendance_sheet_template_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/import-certification-candidates-from-attendance-sheet_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#3095 [BUGFIX] Permettre la mise à jour du logo d'une organisation (PIX-2711).
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#3094 [FEATURE] Afficher les fichiers microsoft en premier dans les épreuves (PIX-2612).
  api/lib/domain/models/Challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3083 [FEATURE] Reporter les informations CPF lors de l'inscription de candidats de certification dans le cadre de la prescription de certification SCO (PIX-2695)
  api/lib/domain/models/SCOCertificationCandidate.js
  api/lib/domain/usecases/enroll-students-to-session.js
  api/lib/infrastructure/repositories/sco-certification-candidate-repository.js
  api/tests/integration/infrastructure/repositories/sco-certification-candidate-repository_test.js
  api/tests/tooling/domain-builder/factory/build-sco-certification-candidate.js
  api/tests/unit/domain/models/SCOCertificationCandidate_test.js
  api/tests/unit/domain/usecases/enroll-students-to-session_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-certif

#3103 [FEATURE] Ajout de liens vers la preview et les informations d'une épreuve sur la page de détails d'une certification dans PixAdmin (PIX-2727)
  admin/app/components/certification/certification-details-answer.hbs
  admin/app/components/certification/certification-details-answer.js
  admin/app/styles/components/certification-details-answer.scss
  admin/tests/integration/components/certification/certification-details-answer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#3100 [BUGFIX] Suppression de la barre de défilement horizontal sur la page compétences (PIX-2726).
  mon-pix/app/styles/components/_rounded-panel.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#3091 [BUGFIX] Corriger le dysfonctionnement de la page login de Pix Admin (PIX-2133).
  admin/app/routes/index.js
  admin/app/routes/login.js
  admin/tests/unit/routes/login_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3108 [TECH] Documenter la configuration Sentry.
  api/sample.env
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3098 [FEATURE] Ajustement du scoring CléA numérique (PIX-2724)
  api/lib/domain/models/CleaCertificationScoring.js
  api/tests/unit/domain/models/CleaCertificationScoring_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3040 [TECH] Contrôler les requêtes entrantes uniquement dans le routeur.
  api/lib/application/.eslintrc.js
  api/lib/application/answers/answer-controller.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/badges/badges-controller.js
  api/lib/application/campaign-participation-results/campaign-participation-result-controller.js
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-issue-reports/certification-issue-report-controller.js
  api/lib/application/certifications/certification-controller.js
  api/lib/application/memberships/membership-controller.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/application/preHandlers/assessment-authorization.js
  api/lib/application/preHandlers/session-authorization.js
  api/lib/application/preHandlers/user-existence-verification.js
  api/lib/application/schooling-registration-dependent-users/index.js
  api/lib/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller.js
  api/lib/application/schooling-registration-user-associations/schooling-registration-user-association-controller.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/sessions/session-controller.js
  api/lib/application/stages/stages-controller.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/application/user-orga-settings/index.js
  api/lib/application/user-orga-settings/user-orga-settings-controller.js
  api/lib/application/users/user-controller.js
  api/tests/acceptance/application/schooling-registration-dependent-user-controller_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/application/stages/stages-controller_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/application/users/user-controller_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3092 [FEATURE] Reporter les informations CPF dans le certification-course du candidat lors du démarrage de son test de certification (PIX-2716)
  api/db/database-builder/factory/build-certification-course.js
  api/db/migrations/20210611081228_add-columns-sex-birthPostalCode-birthINSEECode-in-table-certification-courses.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-course.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3089 [FEATURE] Documenter le endpoint de récupération des résultats Pôle emploi (PIX-2681).
  api/lib/application/pole-emplois/index.js
  api/lib/infrastructure/open-api-doc/pole-emploi/envois-doc.js
  api/lib/infrastructure/open-api-doc/pole-emploi/erreur-doc.js
  api/lib/swaggers.js
  api/tests/acceptance/application/swagger_test.js
  api/tests/unit/infrastructure/open-api-doc/pole-emploi/envois-doc_test.js
  api/tests/unit/infrastructure/open-api-doc/pole-emploi/erreur-doc_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-acces, team-prescription

#3105 [FEATURE] Afficher les fichiers microsoft en premier dans les épreuves (PIX-2729).
  api/lib/domain/models/Challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/tests/unit/components/challenge-statement_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3107 [FEATURE] Recuperation des niveaux de compétence -1 (PIX-2737)
  api/lib/domain/read-models/livret-scolaire/Certificate.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-certif

#3115 [BUGFIX] La colonne "Ecran de fin de test" a été retirée par erreur de la feuille d'émargement (PIX-2747)
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/attendance_sheet_template_target.ods
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3099 [FEATURE] Rattraper la prise en compte auto des signalements de certif sur les session finalisées (PIX-2591)
  api/db/migrations/20210614142832_audit-table-for-autojury.js
  api/lib/domain/events/handle-auto-jury.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportResolutionStrategies.js
  api/lib/infrastructure/repositories/certification-issue-report-repository.js
  api/scripts/trigger-autojury-on-finalized-sessions.js
  api/tests/integration/infrastructure/repositories/certification-issue-report-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-report-repository_test.js
  api/tests/integration/infrastructure/repositories/general-certification-information-repository_test.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/models/CertificationIssueReportResolutionStrategies_test.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3104 [BUGFIX] Mise à jour de traductions anglaises.
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#3116 [FEATURE] Ajouter le premier formulaire pour la sortie du SCO (PIX-2562).
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  mon-pix/.editorconfig
  mon-pix/app/components/recover-account-student-information-form.hbs
  mon-pix/app/components/recover-account-student-information-form.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/router.js
  mon-pix/app/routes/recover-account-after-leaving-sco.js
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/app/templates/recover-account-after-leaving-sco.hbs
  mon-pix/mirage/factories/feature-toggle.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/recover-account-after-leaving-sco_test.js
  mon-pix/tests/integration/components/recover-account-student-information-form-test.js
  mon-pix/tests/unit/routes/recover-account-after-leaving-sco-test.js
  mon-pix/tests/unit/services/feature-toggles_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#3120 [BUGFIX] Le commentaire global n'était pas pris en compte lorsqu'on calculait si une session finalisée était publiable immédiatement (PIX-2749).
  api/lib/domain/events/AutoJuryDone.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
Labels: :rocket: Ready to Merge, team-certif

#3121 [BUGFIX] Une erreur lors du re-scoring d'une certification après une finalisation de session pouvait ne pas être pris en compte dans l'évaluation de la session comme étant directement publiable ou pas (PIX-2751)
  api/lib/domain/events/handle-auto-jury.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3122 [TECH] Supprimer le cache d'authentification plus utilisé (PIX-2733).
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/caches/authentication-cache.js
  api/tests/unit/infrastructure/caches/authentication-cache_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#3102 [FEATURE] Ajout de scripts d'import des villes et pays depuis des csv (PIX-2722)
  api/db/migrations/20210614103332_create-table-certification-cpf-countries.js
  api/db/migrations/20210614103435_create-table-certification-cpf-cities.js
  api/lib/infrastructure/utils/string-utils.js
  api/scripts/import-certification-cpf-cities.js
  api/scripts/import-certification-cpf-countries.js
  api/scripts/import-certifications-from-csv.js
  api/tests/unit/infrastructure/utils/string-utils_test.js
  api/tests/unit/scripts/import-certification-cpf-cities_test.js
  api/tests/unit/scripts/import-certification-cpf-countries_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3124 [TECH] Exposer les domaines Pix-app sur les PR/RA.
  scripts/signal_deploy_to_pr.sh
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3101 [FEATURE] Ajouter une modale de détails à la liste des candidats d'une session de certification (PIX-2712)
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/acceptance/application/session/session-controller-get-certification-candidates_test.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/enrolled-candidates.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/certification-candidate.js
  certif/app/models/feature-toggle.js
  certif/app/styles/app.scss
  certif/app/styles/components/certification-candidate-details-modal.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/mirage/factories/certification-candidate.js
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/certification-candidate-details-modal/certification-candidate-details-modal_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/unit/models/certification-candidate_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3134 [FEATURE] Améliorations CléA mineures
  api/db/seeds/data/target-profiles-builder.js
  api/lib/domain/models/CleaCertificationScoring.js
  api/lib/infrastructure/repositories/partner-certification-scoring-repository.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
  api/tests/unit/domain/models/CleaCertificationScoring_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed

#3117 [FEATURE] Gérer les épreuves "Focus" (PIX-2617).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_focused-challenge-instructions.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/feedback-panel.hbs
  mon-pix/app/templates/components/focused-challenge-instructions.hbs
  mon-pix/mirage/factories/challenge.js
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/integration/components/challenge-actions_test.js
  mon-pix/tests/unit/components/challenge-item-generic_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3113 [TECH] Bump ember-simple-auth de 3.0.1 à 3.1.0 dans Pix Admin (PIX-2450).
  admin/app/adapters/application.js
  admin/app/routes/application.js
  admin/app/routes/authenticated.js
  admin/app/routes/authenticated/certification-centers/get.js
  admin/app/routes/authenticated/certification-centers/list.js
  admin/app/routes/authenticated/organizations/list.js
  admin/app/routes/authenticated/sessions/index.js
  admin/app/routes/authenticated/sessions/list/all.js
  admin/app/routes/authenticated/target-profiles/list.js
  admin/app/routes/authenticated/target-profiles/new.js
  admin/app/routes/authenticated/users/list.js
  admin/app/routes/login.js
  admin/app/routes/logout.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/routes-protection_test.js
  admin/tests/unit/adapters/application_test.js
  admin/tests/unit/routes/about_test.js
  admin/tests/unit/routes/application_test.js
  admin/tests/unit/routes/authenticated_test.js
  admin/tests/unit/routes/index_test.js
  admin/tests/unit/routes/logout_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3119 [FEATURE] Modifier bouton vert de l'écran intermédiaire (PIX-2701).
  mon-pix/app/styles/components/_focused-challenge-instructions.scss
  mon-pix/app/styles/components/_timed-challenge-instructions.scss
  mon-pix/app/templates/components/focused-challenge-instructions.hbs
  mon-pix/app/templates/components/timed-challenge-instructions.hbs
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#3111 [FEATURE] Ajout du graphe d'activité des participants (PIX-2666)
  api/db/database-builder/factory/build-user.js
  api/db/seeds/data/campaign-participations-builder.js
  api/lib/application/campaigns/campaign-stats-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/usecases/get-campaign-participations-activity-by-day.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-participations-stats-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participations-counts-by-day-serializer.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/tests/acceptance/application/campaign-stats-controller_test.js
  api/tests/integration/domain/usecases/get-campaign-participations-activity-by-day_test.js
  api/tests/integration/infrastructure/repositories/campaign-participations-stats-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participations-counts-by-day-serializer_test.js
  orga/app/adapters/campaign-stats.js
  orga/app/components/charts/chart.hbs
  orga/app/components/charts/chart.js
  orga/app/components/charts/participants-by-day-loader.hbs
  orga/app/components/charts/participants-by-day.hbs
  orga/app/components/charts/participants-by-day.js
  orga/app/components/charts/participants-by-status.hbs
  orga/app/components/charts/participants-by-status.js
  orga/app/styles/components/charts/chart.scss
  orga/app/styles/components/charts/index.scss
  orga/app/styles/components/charts/participants-by-day.scss
  orga/app/styles/components/charts/placeholders.scss
  orga/app/styles/pages/authenticated/campaigns/details/activity.scss
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/ember-cli-build.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/charts/participants-by-day_test.js
  orga/translations/en.json
  orga/translations/fr.json
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3118 [BUGFIX] Redirection en début de parcours lorsque j'essaie d'accéder à la page de résultats sans avoir de participation(Pix-2739).
  api/lib/application/error-manager.js
  api/lib/domain/usecases/get-user-campaign-assessment-result.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/unit/domain/usecases/get-user-campaign-assessment-result_test.js
  mon-pix/app/routes/campaigns/assessment/skill-review.js
  mon-pix/app/routes/campaigns/profiles-collection.js
  mon-pix/app/routes/campaigns/profiles-collection/profile-already-shared.js
  mon-pix/app/routes/campaigns/profiles-collection/send-profile.js
  mon-pix/mirage/routes/users/get-campaign-participation-result.js
  mon-pix/mirage/routes/users/index.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment_test.js
  mon-pix/tests/unit/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/routes/campaigns/profiles-collection/profile-already-shared_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3126 [FEATURE] Ajouter des retours sur nos test d'algo (PIX-2065).
  high-level-tests/test-algo/AlgoResult.js
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
  high-level-tests/test-algo/tests/AlgoResult_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3123 [FEATURE] Activer inconditionnellement la connexion PE (PIX-2752).
  api/lib/application/authentication/authentication-controller.js
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  mon-pix/app/components/signin-form.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/config/environment.js
  mon-pix/tests/integration/components/signin-form_test.js
  mon-pix/tests/unit/services/feature-toggles_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#3125 [BUGFIX] Corriger les soucis d'affichage des boutons dans Pix App suite à une montée de version de Pix-UI
  mon-pix/app/components/routes/campaigns/fill-in-participant-external-id.hbs
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/styles/pages/_fill-in-participant-external-id.scss
  mon-pix/app/templates/components/campaign-start-block.hbs
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3135 [FEATURE] Affichage d'indicateurs montrant le nombre de participants total et le nombre de résultats reçus dans la page Activité de Pix Orga (Pix-2668).
  orga/app/components/charts/activity.hbs
  orga/app/components/charts/activity.js
  orga/app/components/charts/participants-by-status.hbs
  orga/app/components/charts/participants-by-status.js
  orga/app/components/indicator-card.hbs
  orga/app/styles/pages/authenticated/campaigns/details/activity.scss
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/config/icons.js
  orga/tests/integration/components/charts/participants-by-status_test.js
  orga/tests/unit/components/charts/activity_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3112 [CLEAN] N'utiliser que deux critères de Badges au lieu de trois critères (PIX-2707).
  admin/app/components/badges/badge.js
  api/db/migrations/20210610172018_fill_badge_partner_competence_for_critera.js
  api/db/migrations/20210616111928_rename-badge-criteria-scope.js
  api/db/seeds/data/badges-builder.js
  api/lib/domain/models/BadgeCriterion.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3128 [FEATURE] Récupérer son compte lors de la sortie du SCO - Partie 1 (PIX-2750).
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/application/error-manager.js
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/application/schooling-registration-dependent-users/index.js
  api/lib/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/read-models/StudentInformationForAccountRecovery.js
  api/lib/domain/usecases/check-sco-account-recovery.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/jsonapi/student-information-for-account-recovery-serializer.js
  api/tests/acceptance/application/schooling-registration-dependent-user-route_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/application/schooling-registration-dependent-user/schooling-registration-dependant-user-controller_test.js
  api/tests/unit/domain/usecases/check-sco-account-recovery_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-information-for-account-recovery-serializer_test.js
  mon-pix/app/adapters/student-information.js
  mon-pix/app/components/recover-account-student-information-form.hbs
  mon-pix/app/components/recover-account-student-information-form.js
  mon-pix/app/models/student-information.js
  mon-pix/tests/integration/components/recover-account-student-information-form-test.js
  mon-pix/tests/unit/adapters/student-information-test.js
  mon-pix/tests/unit/models/student-information-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3141 [FEATURE] Modifier le texte des cgu dans la page d'inscription sur Pix App (PIX-2753).
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3140 [TECH] Supprimer les mixins d'Ember-simple-auth 3.1.0 dans Pix Certif (PIX-2759).
  certif/app/adapters/application.js
  certif/app/routes/application.js
  certif/app/routes/authenticated.js
  certif/app/routes/authenticated/index.js
  certif/app/routes/login.js
  certif/app/routes/logout.js
  certif/app/routes/terms-of-service.js
  certif/app/services/session.js
  certif/mirage/config.js
  certif/tests/acceptance/authentication_test.js
  certif/tests/unit/adapters/application_test.js
  certif/tests/unit/routes/application_test.js
  certif/tests/unit/routes/authenticated/index_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-acces, team-certif

#3130 [FEATURE][A11Y] Rendre accessible la liste des campagnes sur Pix Orga (PIX-2633)
  orga/app/components/routes/authenticated/campaign/list.hbs
  orga/app/controllers/authenticated/campaigns/list.js
  orga/app/styles/components/campaign-list.scss
  orga/app/styles/globals/tables.scss
  orga/tests/integration/components/routes/authenticated/campaign/list_test.js
  orga/tests/unit/controllers/authenticated/campaigns/list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3143 [TECH] Ajout du linter de tests qunit sur orga
  orga/.eslintrc.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/remove-membership_test.js
  orga/tests/acceptance/sco-student-list_test.js
  orga/tests/acceptance/team-list_test.js
  orga/tests/integration/components/charts/participants-by-stage_test.js
  orga/tests/integration/components/dissociate-user-modal_test.js
  orga/tests/integration/components/edit-student-number-modal_test.js
  orga/tests/integration/components/indicator-card-test.js
  orga/tests/integration/components/manage-authentication-method-modal_test.js
  orga/tests/integration/components/modal/dialog_test.js
  orga/tests/integration/components/organization-credit-info_test.js
  orga/tests/integration/components/routes/authenticated/campaign/analysis/tab_test.js
  orga/tests/integration/components/routes/authenticated/campaign/report_test.js
  orga/tests/integration/components/routes/authenticated/sco-students/list-items_test.js
  orga/tests/integration/components/routes/authenticated/sup-students/list-items_test.js
  orga/tests/integration/components/routes/authenticated/team/items_test.js
  orga/tests/integration/components/routes/register-form_test.js
  orga/tests/unit/adapters/division_test.js
  orga/tests/unit/adapters/organization-invitation-response_test.js
  orga/tests/unit/adapters/prescriber_test.js
  orga/tests/unit/adapters/user-orga-setting_test.js
  orga/tests/unit/components/charts/activity_test.js
  orga/tests/unit/components/routes/login-form_test.js
  orga/tests/unit/components/user-logged-menu_test.js
  orga/tests/unit/controllers/authenticated/campaigns/list_test.js
  orga/tests/unit/controllers/authenticated/team/list/members_test.js
  orga/tests/unit/models/campaign_test.js
  orga/tests/unit/models/student_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/profiles_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign_test.js
  orga/tests/unit/routes/not-found_test.js
  orga/tests/unit/services/current-user_test.js
  orga/tests/unit/services/feature-toggle_test.js
  orga/tests/unit/services/file-saver_test.js
  orga/tests/unit/services/url_test.js
  orga/tests/unit/utils/email-validator_test.js
  orga/tests/unit/utils/input-validator_test.js
  orga/tests/unit/utils/password-validator_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3138 [BUGFIX] Le compteur "Nombre de certifications non terminées" sur la page d'information d'une session est incorrect sur PixAdmin (PIX-2723)
  admin/app/models/jury-certification-summary.js
  admin/app/models/session.js
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations_test.js
  admin/tests/unit/models/jury-certification-summary_test.js
  admin/tests/unit/models/session_test.js
Labels: :eyes: Func Review Needed, :rocket: Ready to Merge, Tech Review OK, team-certif
