Repository 1024pix/pix, pull requests merged in 2021-08, with the labels that each got.

#3258 [TECH] Modifier les composants de participation à une campagne d'eval dans Pix Orga (PIX-2908)
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/assessment/header.js
  orga/app/components/participant/assessment/results.hbs
  orga/app/components/participant/assessment/tabs.hbs
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/app/components/routes/authenticated/campaign/assessment/details.js
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/controllers/authenticated/campaigns/campaign/assessment-results.js
  orga/app/controllers/authenticated/campaigns/participant-assessment/analysis.js
  orga/app/controllers/authenticated/campaigns/participant-assessment/results.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/participant-assessment.js
  orga/app/routes/authenticated/campaigns/participant-assessment/analysis.js
  orga/app/routes/authenticated/campaigns/participant-assessment/index.js
  orga/app/routes/authenticated/campaigns/participant-assessment/loading.js
  orga/app/routes/authenticated/campaigns/participant-assessment/results.js
  orga/app/templates/authenticated/campaigns/assessment.hbs
  orga/app/templates/authenticated/campaigns/assessment/results.hbs
  orga/app/templates/authenticated/campaigns/participant-assessment.hbs
  orga/app/templates/authenticated/campaigns/participant-assessment/analysis.hbs
  orga/app/templates/authenticated/campaigns/participant-assessment/loading.hbs
  orga/app/templates/authenticated/campaigns/participant-assessment/results.hbs
  orga/app/templates/authenticated/campaigns/sco-students/list.hbs
  orga/tests/integration/components/participant/assessment/header_test.js
  orga/tests/integration/components/participant/assessment/results_test.js
  orga/tests/integration/components/participant/assessment/tabs_test.js
  orga/tests/integration/components/routes/authenticated/campaign/assessment/details_test.js
  orga/tests/unit/controllers/authenticated/campaigns/assessment/analysis_test.js
  orga/tests/unit/controllers/authenticated/campaigns/assessment/results_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/activity_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/assessment-results_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-prescription

#3204 [CLEANUP] Utilise le nom de domaine images.pix.fr
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  mon-pix/app/templates/components/user-certifications-detail-result.hbs
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3259 [TECH] Modifier les composants de participation à une campagne de profil dans Pix Orga (PIX-2910)
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/participant/profile/header.hbs
  orga/app/components/participant/profile/table.hbs
  orga/app/components/routes/authenticated/campaign/profile/details.hbs
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/components/routes/authenticated/campaign/profile/table.hbs
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/controllers/authenticated/campaigns/campaign/profiles.js
  orga/app/controllers/authenticated/campaigns/participant-profile.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/participant-profile.js
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/campaigns/participant-profile.scss
  orga/app/templates/authenticated/campaigns/participant-profile.hbs
  orga/app/templates/authenticated/campaigns/profile.hbs
  orga/tests/integration/components/participant/profile/header_test.js
  orga/tests/integration/components/participant/profile/table_test.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/details_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/activity_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/profiles_test.js
  orga/tests/unit/controllers/authenticated/campaigns/profile_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-prescription

#3263 [FEATURE] Ne permettre qu'une seule récupération de compte SCO - API (PIX-2911).
  api/db/database-builder/factory/build-account-recovery-demand.js
  api/db/database-builder/factory/build-authentication-method.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/AccountRecoveryDemand.js
  api/lib/domain/services/check-sco-account-recovery-service.js
  api/lib/domain/usecases/account-recovery/get-account-recovery-details.js
  api/lib/domain/usecases/account-recovery/update-user-account.js
  api/lib/domain/usecases/check-sco-account-recovery.js
  api/lib/domain/usecases/send-email-for-account-recovery.js
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/services/check-sco-account-recovery-service_test.js
  api/tests/unit/domain/usecases/account-recovery/get-account-recovery-details_test.js
  api/tests/unit/domain/usecases/account-recovery/send-email-for-account-recovery_test.js
  api/tests/unit/domain/usecases/account-recovery/update-user-account_test.js
  api/tests/unit/domain/usecases/check-sco-account-recovery_test.js
Labels: :rocket: Ready to Merge, team-acces

#3265 [TECH] Modifier les composants génériques d'UI dans Pix Orga (PIX-2913)
  orga/app/components/campaign/activity/dashboard.hbs
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/analysis/tube-recommendation-row.hbs
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/profile/header.hbs
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/student/sco/list.hbs
  orga/app/components/student/sup/list.hbs
  orga/app/components/table/header-filter-input.hbs
  orga/app/components/table/header-filter-select.hbs
  orga/app/components/table/pagination-control.hbs
  orga/app/components/table/pagination-control.js
  orga/app/components/team/members-list-item.hbs
  orga/app/components/team/members-list.hbs
  orga/app/components/ui/chevron.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/components/ui/pix-loader.hbs
  orga/app/components/ui/previous-page-button.hbs
  orga/app/components/ui/previous-page-button.js
  orga/app/components/ui/progress-bar.hbs
  orga/app/components/ui/progress-bar.js
  orga/app/components/ui/search-input.hbs
  orga/app/components/ui/select-input.hbs
  orga/app/templates/authenticated/campaigns/campaign/loading.hbs
  orga/app/templates/authenticated/campaigns/participant-assessment/loading.hbs
  orga/app/templates/authenticated/sco-students/list.hbs
  orga/app/templates/authenticated/sup-students/list.hbs
  orga/tests/integration/components/tables/pagination-control_test.js
  orga/tests/integration/components/ui/chevron_test.js
  orga/tests/integration/components/ui/indicator-card-test.js
  orga/tests/integration/components/ui/pix-loader_test.js
  orga/tests/integration/components/ui/previous-page-button_test.js
  orga/tests/integration/components/ui/progress-bar_test.js
  orga/tests/integration/components/ui/search-input_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-prescription

#3257 [FEATURE][A11Y] Permettre la navigation au clavier dans la liste des sessions (PIX-2691)
  certif/app/components/pagination-control.hbs
  certif/app/components/session-summary-list.hbs
  certif/app/styles/app.scss
  certif/app/styles/components/pagination-control.scss
  certif/app/styles/components/session-summary-list.scss
  certif/app/styles/globals/tables.scss
  certif/app/styles/globals/texts.scss
  certif/tests/integration/components/pagination-control_test.js
  certif/tests/integration/components/session-summary-list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3262 [BUGFIX] Sur la page de fin de campagne, afficher uniquement les badges gagnés durant celle-ci (PIX-2705)
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#3256 [FEATURE] Ajout d'une tooltip à l'arrivée d'une épreuve focus (PIX-2870).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/pages/_assessment-challenge.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/public/images/tag-focused-challenge.svg
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#3272 [CLEAN] Refacto du proposal as blocks.
  mon-pix/app/utils/proposals-as-blocks.js
  mon-pix/app/utils/proposals-parser/challenge-response-template.js
  mon-pix/app/utils/proposals-parser/input-block.js
  mon-pix/app/utils/proposals-parser/response-block.js
  mon-pix/app/utils/proposals-parser/text-block.js
  mon-pix/tests/unit/utils/proposals-parser/challenge-response-template_test.js
  mon-pix/tests/unit/utils/proposals-parser/input-block_test.js
  mon-pix/tests/unit/utils/proposals-parser/response-block_test.js
  mon-pix/tests/unit/utils/proposals-parser/text-block_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#3266 [FEATURE] Permettre l'édition de données CPF dans la modale d'édition des informations Candidat dans PixAdmin (PIX-2840)
  admin/app/components/certification/candidate-edit-modal.hbs
  admin/app/components/certification/candidate-edit-modal.js
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/models/certification.js
  admin/app/models/country.js
  admin/app/routes/authenticated/certifications/certification/informations.js
  admin/app/serializers/certification.js
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/integration/components/certification/candidate-edit-modal_test.js
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/models/certification_test.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/usecases/correct-candidate-identity-in-certification-course.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/lib/infrastructure/utils/string-utils.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-data.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-file.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ok.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-special-birthdate-ok.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-5_extract_ok_test.ods
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/models/CertificationCourse_test.js
  api/tests/unit/domain/usecases/correct-candidate-identity-in-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  api/tests/unit/infrastructure/utils/string-utils_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3222 [FEATURE] Ajout des 2 cartes sur les résultats dans l'onglet résultats sur Pix Orga (PIX-2825).
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/campaign/results/assessment-cards.hbs
  orga/app/components/campaign/results/stats.hbs
  orga/app/components/circle-chart.hbs
  orga/app/models/campaign-collective-result.js
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/index.scss
  orga/app/styles/components/campaign/results/assessment-cards.scss
  orga/app/styles/components/circle-chart.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant/results.scss
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
  orga/config/icons.js
  orga/tests/acceptance/remove-membership_test.js
  orga/tests/helpers/contains.js
  orga/tests/integration/components/campaign/results/assessment-cards_test.js
  orga/tests/integration/components/circle-chart_test.js
  orga/tests/unit/models/campaign-collective-results_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3151 [FEATURE] Choix de réponse avec un menu déroulant dans une épreuve (PIX-2262).
  mon-pix/app/components/challenge-item-qrocm.js
  mon-pix/app/components/qrocm-ind-solution-panel.js
  mon-pix/app/components/qrocm-proposal.js
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/app/utils/proposals-as-blocks.js
  mon-pix/app/utils/proposals-parser/input-block.js
  mon-pix/app/utils/proposals-parser/response-block.js
  mon-pix/app/utils/proposals-parser/select-block.js
  mon-pix/app/utils/proposals-parser/splitters.js
  mon-pix/mirage/factories/challenge.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/integration/components/qrocm-proposal_test.js
  mon-pix/tests/unit/utils/proposals-parser/challenge-response-template_test.js
  mon-pix/tests/unit/utils/proposals-parser/input-block_test.js
  mon-pix/tests/unit/utils/proposals-parser/response-block_test.js
  mon-pix/tests/unit/utils/proposals-parser/select-block_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#3245 [DOC] Expliciter la configuration BDD.
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#3273 [FEATURE] Ajouter un lien permettant d'accéder au détail d'un utilisateur depuis la page de détail d'une certification dans Pix Admin (PIX-2920).
  admin/app/models/certification.js
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
  api/lib/domain/read-models/CertificationResultInformation.js
  api/lib/domain/read-models/GeneralCertificationInformation.js
  api/lib/infrastructure/repositories/general-certification-information-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-result-information-serializer.js
  api/tests/integration/infrastructure/repositories/general-certification-information-repository_test.js
  api/tests/tooling/domain-builder/factory/build-general-certification-information.js
  api/tests/unit/domain/read-models/CertificationResultInformation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-information-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3269 [FEATURE] Améliorer l'affichage des erreurs lors de la récupération de compte suite à la sortie SCO (PIX-2851)
  mon-pix/app/components/account-recovery/conflict-error.hbs
  mon-pix/app/components/account-recovery/recovery-errors.hbs
  mon-pix/app/components/account-recovery/update-sco-record-form.hbs
  mon-pix/app/components/account-recovery/update-sco-record-form.js
  mon-pix/app/controllers/account-recovery/find-sco-record.js
  mon-pix/app/controllers/account-recovery/update-sco-record.js
  mon-pix/app/routes/account-recovery/update-sco-record.js
  mon-pix/app/templates/account-recovery/find-sco-record.hbs
  mon-pix/app/templates/account-recovery/update-sco-record.hbs
  mon-pix/tests/acceptance/account-recovery/find-sco-record_test.js
  mon-pix/tests/acceptance/account-recovery/update-sco-record_test.js
  mon-pix/tests/integration/components/account-recovery/conflict-error-test.js
  mon-pix/tests/integration/components/account-recovery/recovery-errors-test.js
  mon-pix/tests/unit/components/account-recovery/backup-email-confirmation-form_test.js
  mon-pix/tests/unit/controllers/account-recovery/find-sco-record-test.js
  mon-pix/tests/unit/routes/account-recovery/update-sco-record-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3275 [TECH] Ajout d'une méthode pour récupérer toutes les informations nécessaires à la création d'attestations de certification pour une classe SCO (PIX-2904)
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/lib/infrastructure/repositories/sco-certification-candidate-repository.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#3270 [BUGFIX] Le lien "Continuez votre expérience sur Pix" à la fin d'une campagne ne redirige plus vers la page d'accueil (PIX-2915).
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3254 [FEATURE] Un utilisateur désactivé ne peut rejoindre une campagne (PIX-2862)
  api/lib/application/error-manager.js
  api/lib/application/schooling-registration-user-associations/schooling-registration-user-association-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/find-association-between-user-and-schooling-registration.js
  api/lib/infrastructure/repositories/campaign-to-join-repository.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/campaign-to-join-repository_test.js
  api/tests/tooling/domain-builder/factory/build-schooling-registration.js
  api/tests/unit/domain/usecases/find-association-between-user-and-schooling-registration_test.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/mirage/routes/campaign-participations/post-campaign-participation.js
  mon-pix/mirage/routes/schooling-registration-user-associations/index.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection_test.js
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/unit/routes/campaigns/restricted/join_test.js
  mon-pix/tests/unit/routes/campaigns/start-or-resume_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3281 [FEATURE] Ne plus proposer la première ligne du select sur les épreuves à menu déroulant (PIX-2925).
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, team-evaluation

#3287 [BUGFIX] Changer le message d'assistance sur la page d'erreur de la sortie SCO (PIX-2935).
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3252 [TECH] Améliorer le service de génération des attestations de certification PDF pour qu'il puisse prendre en entrée plusieurs attestations (PIX-2893)
  api/lib/application/certifications/certification-controller.js
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_several_pages.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full.pdf
  api/tests/tooling/binary-comparator.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/infrastructure/utils/pdf/certification-attestation-pdf_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#3277 [FEATURE] Empêcher un élève de se réconcilier si sa schooling registration a été désactivée (PIX-2863)
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3278 [FEATURE] Ajouter une page d'import des étudiants pour les organisations SUP (Pix-2874).
  orga/app/components/student/sup/header-actions.hbs
  orga/app/components/student/sup/import.hbs
  orga/app/controllers/authenticated/sup-students/import.js
  orga/app/controllers/authenticated/sup-students/list.js
  orga/app/router.js
  orga/app/routes/authenticated/sup-students/import.js
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/students/import.scss
  orga/app/templates/authenticated/sup-students/import.hbs
  orga/app/templates/authenticated/sup-students/list.hbs
  orga/public/images/import-participant.svg
  orga/tests/acceptance/authentication_test.js
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/acceptance/campaign-analysis_test.js
  orga/tests/acceptance/campaign-assessment-results_test.js
  orga/tests/acceptance/campaign-creation_test.js
  orga/tests/acceptance/campaign-details_test.js
  orga/tests/acceptance/campaign-list_test.js
  orga/tests/acceptance/campaign-participants-individual-analysis_test.js
  orga/tests/acceptance/campaign-participants-individual-results_test.js
  orga/tests/acceptance/campaign-profiles_test.js
  orga/tests/acceptance/campaign-update_test.js
  orga/tests/acceptance/certifications_test.js
  orga/tests/acceptance/dissociate-student_test.js
  orga/tests/acceptance/information-banner_test.js
  orga/tests/acceptance/profile_test.js
  orga/tests/acceptance/remove-membership_test.js
  orga/tests/acceptance/sco-student-list_test.js
  orga/tests/acceptance/sup-student-import_test.js
  orga/tests/acceptance/sup-student-list_test.js
  orga/tests/acceptance/switch-organization_test.js
  orga/tests/acceptance/team-creation_test.js
  orga/tests/acceptance/team-list_test.js
  orga/tests/acceptance/terms-of-service_test.js
  orga/tests/helpers/authenticate-session.js
  orga/tests/integration/components/students/sup/header-actions_test.js
  orga/tests/unit/controllers/authenticated/sup-students/import_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-prescription

#3289 [BUGFIX] Changer certaines phrases du parcours de la sortie SCO (PIX-2821).
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3284 [FEATURE] Ajout de la carte du palier moyen d'une campagne d'évaluation (PIX-2890)
  orga/app/components/campaign/activity/dashboard.hbs
  orga/app/components/campaign/cards/participants-count.hbs
  orga/app/components/campaign/cards/result-average.hbs
  orga/app/components/campaign/cards/shared-count.hbs
  orga/app/components/campaign/cards/stage-average.hbs
  orga/app/components/campaign/cards/stage-average.js
  orga/app/components/campaign/results/assessment-cards.hbs
  orga/app/components/routes/authenticated/campaign/details/tab.hbs
  orga/app/components/stage-stars.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/activity/dashboard.scss
  orga/app/styles/components/campaign/results/assessment-cards.scss
  orga/app/styles/components/charts/cards.scss
  orga/app/styles/components/indicator-card.scss
  orga/app/styles/components/stage-stars.scss
  orga/app/styles/globals/pages.scss
  orga/app/styles/globals/panels.scss
  orga/app/styles/globals/shadows.scss
  orga/app/styles/pages/authenticated/campaigns/details.scss
  orga/app/styles/pages/authenticated/campaigns/details/activity.scss
  orga/app/styles/pages/authenticated/campaigns/details/assessment-results.scss
  orga/app/styles/pages/authenticated/campaigns/details/details.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants/participant/results.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
  orga/tests/integration/components/campaign/cards/participants-count_test.js
  orga/tests/integration/components/campaign/cards/result_average_test.js
  orga/tests/integration/components/campaign/cards/shared-count_test.js
  orga/tests/integration/components/campaign/cards/stage_average_test.js
  orga/tests/integration/components/campaign/results/assessment-cards_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#3285 [FEATURE] Demander a l'utilisateur d'attester sur l'honneur d'appartenance du compte (PIX-2787).
  mon-pix/app/components/account-recovery/confirmation-step.hbs
  mon-pix/app/components/account-recovery/confirmation-step.js
  mon-pix/app/styles/pages/_account-recovery.scss
  mon-pix/tests/acceptance/account-recovery/find-sco-record_test.js
  mon-pix/tests/integration/components/account-recovery/confirmation-step-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3280 [FEATURE] Demander à l'utilisateur de valider les CGU pour récupérer compte SCO (PIX-2916).
  mon-pix/app/components/account-recovery/student-information-form.hbs
  mon-pix/app/components/account-recovery/update-sco-record-form.hbs
  mon-pix/app/components/account-recovery/update-sco-record-form.js
  mon-pix/app/styles/components/account-recovery/_student-information-form.scss
  mon-pix/app/styles/components/account-recovery/_update-sco-record-form.scss
  mon-pix/app/styles/pages/_account-recovery.scss
  mon-pix/tests/acceptance/account-recovery/update-sco-record_test.js
  mon-pix/tests/integration/components/account-recovery/update-sco-record-form-test.js
  mon-pix/tests/unit/components/account-recovery/update-sco-record-form-test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3267 [FEATURE] Ne plus afficher l'infobulle si l'utilisateur l'a déjà vue (PIX-2878).
  api/db/database-builder/factory/build-user.js
  api/db/migrations/20210727092407_add-columns-has-seen-focused-and-other-challenge-tooltips.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/remember-user-has-seen-challenge-tooltip.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/remember-user-has-seen-challenge-tooltip_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/models/user.js
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/mirage/routes/users/index.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/tests/unit/adapters/user_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3293 [FEATURE] Déplacer le filtre "Afficher uniquement mes sessions" de l'onglet "Toutes les sessions" vers l'onglet "Sessions à traiter" dans Pix Admin (PIX-2360).
  admin/app/controllers/authenticated/sessions/list/all.js
  admin/app/controllers/authenticated/sessions/list/with-required-action.js
  admin/app/routes/authenticated/sessions/list/all.js
  admin/app/templates/authenticated/sessions/list/all.hbs
  admin/app/templates/authenticated/sessions/list/with-required-action.hbs
  admin/tests/acceptance/authenticated/sessions/list/with-required-action_test.js
  admin/tests/unit/routes/authenticated/sessions/list/all_test.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/validators/session-validator.js
  api/lib/infrastructure/repositories/jury-session-repository.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/validators/session-validator_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3286 [BUGFIX] Réinitialiser le champ ville lorsque l'on veut modifier un candidat dans Pix Admin dont l'inscription a été effectué par code Insee (PIX-2937).
  admin/app/components/certification/candidate-edit-modal.js
  admin/tests/integration/components/certification/candidate-edit-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3292 [BUGFIX] Désactiver le bouton "C'est parti" après avoir cliqué dessus durant la récupération compte SCO (PIX-2917).
  mon-pix/app/components/account-recovery/backup-email-confirmation-form.hbs
  mon-pix/app/components/account-recovery/backup-email-confirmation-form.js
  mon-pix/app/controllers/account-recovery/find-sco-record.js
  mon-pix/app/templates/account-recovery/find-sco-record.hbs
  mon-pix/tests/acceptance/account-recovery/find-sco-record_test.js
  mon-pix/tests/acceptance/account-recovery/update-sco-record_test.js
  mon-pix/tests/integration/components/account-recovery/backup-email-confirmation-form-test.js
  mon-pix/tests/unit/components/account-recovery/backup-email-confirmation-form_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3246 [FEATURE] Générer les codes de verification à la création de certification et ajout d'un script en production pour rétro-générer des codes de vérification (PIX-2918)
  api/lib/domain/usecases/certificate/get-private-certificate.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/scripts/prod/generate-certificate-verification-code.js
  api/tests/unit/domain/usecases/get-private-certificate_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3288 [FEATURE] Permettre de sortir dans un fichier csv les résultats d'algolix (PIX-2070).
  high-level-tests/test-algo/.eslintrc.yaml
  high-level-tests/test-algo/AlgoResult.js
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/index.js
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
  high-level-tests/test-algo/tests/.eslintrc.yaml
  high-level-tests/test-algo/tests/AlgoResult_test.js
  high-level-tests/test-algo/tests/algo_test.js
  high-level-tests/test-algo/tests/test-helpers.js
  high-level-tests/test-algo/tests/utils/CsvFile_test.js
  high-level-tests/test-algo/tests/utils/timestamp_test.js
  high-level-tests/test-algo/utils/CsvFile.js
  high-level-tests/test-algo/utils/timestamp.js
Labels: :rocket: Ready to Merge, team-evaluation

#3291 [FEATURE] Ajout des options de sélections sur les épreuves QROC (PIX-2924).
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/mirage/factories/challenge.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3295 [BUGFIX] Désactiver le bouton "Je me connecte" après avoir cliqué dessus durant la récupération compte SCO (PIX-2950).
  mon-pix/app/components/account-recovery/update-sco-record-form.hbs
  mon-pix/app/components/account-recovery/update-sco-record-form.js
  mon-pix/app/controllers/account-recovery/update-sco-record.js
  mon-pix/app/templates/account-recovery/update-sco-record.hbs
  mon-pix/tests/integration/components/account-recovery/update-sco-record-form-test.js
  mon-pix/tests/unit/components/account-recovery/update-sco-record-form-test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3298 [BUGFIX] Corriger l'affichage de la date d'achèvement d'une certification dans Pix Admin (PIX-147).
  admin/app/models/certification.js
  admin/app/models/jury-certification-summary.js
  admin/tests/unit/models/certification_test.js
  admin/tests/unit/models/jury-certification-summary_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3276 [DOC] Expliciter la configuration du cache.
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3255 [DOC] Expliciter la création des instances de la BDD locale.
  INSTALLATION.md
  docker-compose.yml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3294 [FEATURE] Réactiver les schooling registration disabled à l'import SUP (PIX-2856)
  api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/higher-schooling-registration-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3297 [FEATURE] Afficher qu'un compte existe deja lorsque l'adresse e-mail est deja utilise (PIX-2914).
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/services/sco-account-recovery-service.js
  api/lib/domain/usecases/account-recovery/get-account-recovery-details.js
  api/lib/domain/usecases/account-recovery/update-user-account.js
  api/lib/domain/usecases/check-sco-account-recovery.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/send-email-for-account-recovery.js
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/services/sco-account-recovery-service_test.js
  api/tests/unit/domain/usecases/account-recovery/get-account-recovery-details_test.js
  api/tests/unit/domain/usecases/account-recovery/send-email-for-account-recovery_test.js
  api/tests/unit/domain/usecases/account-recovery/update-user-account_test.js
  api/tests/unit/domain/usecases/check-sco-account-recovery_test.js
  mon-pix/app/controllers/account-recovery/find-sco-record.js
  mon-pix/app/controllers/account-recovery/update-sco-record.js
  mon-pix/app/routes/account-recovery/update-sco-record.js
  mon-pix/mirage/routes/account-recovery/index.js
  mon-pix/tests/acceptance/account-recovery/find-sco-record_test.js
  mon-pix/tests/acceptance/account-recovery/update-sco-record_test.js
  mon-pix/tests/unit/routes/account-recovery/update-sco-record-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3283 [TECH] Rendre Pix Orga un minimum responsive (PIX-2943)
  orga/app/components/campaign-creation-details.hbs
  orga/app/components/campaign/copy-paste-button.hbs
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/campaign/list-actions.hbs
  orga/app/components/campaign/list.hbs
  orga/app/components/routes/authenticated/campaign/details/tab.hbs
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/stage-stars.hbs
  orga/app/components/student/sco/header-actions.hbs
  orga/app/components/student/sco/list.hbs
  orga/app/components/student/sup/header-actions.hbs
  orga/app/components/student/sup/list.hbs
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/members-list-item.hbs
  orga/app/components/team/members-list.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/components/ui/previous-page-button.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/activity/dashboard.scss
  orga/app/styles/components/sidebar-menu.scss
  orga/app/styles/components/user-logged-menu.scss
  orga/app/styles/globals/pages.scss
  orga/app/styles/globals/panels.scss
  orga/app/styles/pages/authenticated.scss
  orga/app/styles/pages/authenticated/campaigns/details.scss
  orga/app/styles/pages/authenticated/campaigns/details/details.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/templates/authenticated.hbs
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#3290 [FEATURE] Créer la route de récupération des attestations par classe (PIX-2940)
  api/lib/application/error-manager.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/certificate/find-certification-attestations-for-division.js
  api/lib/domain/usecases/certificate/get-certification-attestation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-certification-attestations-for-division_test.js
  api/tests/unit/domain/usecases/get-certification-attestation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3302 [BUGFIX] Connecter l'utilisateur à la fin du processus de récupération compte SCO (PIX-2954).
  mon-pix/app/components/account-recovery/recovery-errors.hbs
  mon-pix/app/controllers/account-recovery/find-sco-record.js
  mon-pix/app/controllers/account-recovery/update-sco-record.js
  mon-pix/app/routes/account-recovery/update-sco-record.js
  mon-pix/app/templates/account-recovery/find-sco-record.hbs
  mon-pix/app/templates/account-recovery/update-sco-record.hbs
  mon-pix/tests/acceptance/account-recovery/update-sco-record_test.js
  mon-pix/tests/integration/components/account-recovery/recovery-errors-test.js
  mon-pix/tests/unit/controllers/account-recovery/update-sco-record-test.js
  mon-pix/tests/unit/routes/account-recovery/update-sco-record-test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3303 [FEATURE] Brancher le bouton de téléchargement des attestations de certification sur Pix Orga (PIX-2941)
  orga/app/controllers/authenticated/certifications.js
  orga/app/styles/pages/authenticated/certifications.scss
  orga/app/templates/authenticated/certifications.hbs
  orga/tests/acceptance/certifications_test.js
  orga/tests/unit/controllers/authenticated/certifications_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3306 [TECH] Modifier les composants du header de la page de campagne dans Pix Orga (PIX-2965)
  orga/app/components/campaign-creation-details.hbs
  orga/app/components/campaign/analysis/recommendations.hbs
  orga/app/components/campaign/header/archived-banner.hbs
  orga/app/components/campaign/header/archived-banner.js
  orga/app/components/campaign/header/tabs.hbs
  orga/app/components/campaign/header/tabs.js
  orga/app/components/campaign/header/title.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/routes/authenticated/campaign/report.js
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/analysis/recommendations.scss
  orga/app/styles/components/campaign/header/archived-banner.scss
  orga/app/styles/components/campaign/header/tabs.scss
  orga/app/styles/components/campaign/header/title.scss
  orga/app/styles/components/campaign/index.scss
  orga/app/styles/pages/authenticated/campaigns/campaign.scss
  orga/app/styles/pages/authenticated/campaigns/details.scss
  orga/app/templates/authenticated/campaigns/campaign.hbs
  orga/tests/integration/components/campaign/header/archived-banner_test.js
  orga/tests/integration/components/campaign/header/tabs_test.js
  orga/tests/integration/components/campaign/header/title_test.js
  orga/tests/integration/components/routes/authenticated/campaign/report_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#3307 [TECH] Modifier les composants de la liste des campagnes de profils dans Pix Orga (PIX-2969)
  orga/app/components/campaign/header/tabs.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/profile-results.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/campaign/profile-results.js
  orga/app/templates/authenticated/campaigns/campaign/profile-results.hbs
  orga/app/templates/authenticated/campaigns/campaign/profiles.hbs
  orga/tests/acceptance/campaign-profiles_test.js
  orga/tests/integration/components/campaign/results/profile-list_test.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/list_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/profile-results_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/profile-results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#3282 [FEATURE] Permettre de modifier une campagne depuis Pix Admin (PIX-2885)
  admin/app/components/campaigns/details.hbs
  admin/app/components/campaigns/update.hbs
  admin/app/components/campaigns/update.js
  admin/app/components/organization-campaigns-section.hbs
  admin/app/controllers/authenticated/campaigns/campaign.js
  admin/app/models/campaign.js
  admin/app/router.js
  admin/app/routes/authenticated/campaigns/campaign.js
  admin/app/templates/authenticated/campaigns/campaign.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/campaigns/details_test.js
  admin/tests/integration/components/campaigns/update_test.js
  admin/tests/unit/components/campaigns/update_test.js
  admin/tests/unit/controllers/campaigns/campaign_test.js
  api/db/database-builder/factory/build-campaign.js
  api/lib/application/campaigns/campaign-management-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/read-models/CampaignManagement.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-campaign-details-management.js
  api/lib/domain/validators/campaign-validator.js
  api/lib/infrastructure/repositories/campaign-management-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-details-management-serializer.js
  api/tests/acceptance/application/campaign-management-controller_test.js
  api/tests/integration/domain/usecases/update-campaign-details-management_test.js
  api/tests/integration/infrastructure/repositories/campaign-management-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/domain/usecases/update-campaign-details-management_test.js
  api/tests/unit/domain/validators/campaign-validator_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-details-management-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-management-serializer_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3309 [TECH] Prévenir les traces incomplètes de récupération de compte SCO (PIX-2973).
  api/db/migrations/20210810084355_alter_table_account-recovery-demands_add_not_null_schoolingRegistrationId.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3321 [BUGFIX] Correction de tests flaky et bugs sur la navbar Pix Orga
  orga/app/components/campaign/header/tabs.hbs
  orga/app/components/campaign/header/title.hbs
  orga/app/components/participant/assessment/tabs.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/header/tabs.scss
  orga/app/styles/components/participant/tabs.scss
  orga/app/styles/globals/panels.scss
  orga/app/templates/authenticated/team/list.hbs
  orga/tests/helpers/contains.js
  orga/tests/integration/components/campaign/cards/result_average_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3299 [FEATURE] Calcul des résultats d'une participation au partage (PIX-2895)
  api/db/database-builder/factory/build-knowledge-element.js
  api/db/migrations/20210802093720_add-column-mastery-percentage-on-campaign-participation.js
  api/db/migrations/20210802094853_add-column-pix-score-on-campaign-participation.js
  api/lib/domain/events/compute-campaign-participation-results.js
  api/lib/domain/events/compute-validated-skills-count.js
  api/lib/domain/events/index.js
  api/lib/domain/models/ParticipantResultsShared.js
  api/lib/domain/services/scoring/scoring-service.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/participant-results-shared-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-results-shared-repository_test.js
  api/tests/tooling/domain-builder/factory/build-knowledge-element.js
  api/tests/unit/domain/events/compute-campaign-participation-results_test.js
  api/tests/unit/domain/events/compute-validated-skills-count_test.js
  api/tests/unit/domain/events/event-choreography-compute-validated-skills-count_test.js
  api/tests/unit/domain/models/ParticipantResultsShared_test.js
  api/tests/unit/domain/services/scoring/scoring-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-prescription

#3296 [TECH] Permettre de pouvoir visualiser les résultats d'Algolix (PIX-2072).
  .gitignore
  high-level-tests/test-algo/Dockerfile
  high-level-tests/test-algo/README.md
  high-level-tests/test-algo/data_visualization.ipynb
  high-level-tests/test-algo/docker-compose.yaml
Labels: :rocket: Ready to Merge, team-evaluation

#3305 [TECH] Sortir TimedChallengeInstructions de tous les types de challenges.
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/tests/acceptance/challenge-timed_test.js
  mon-pix/tests/unit/components/challenge-item-generic_test.js
  mon-pix/tests/unit/controllers/assessments/challenge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3312 [FEATURE] Enregistrer l'identifiant du Pix Master lors de la création d'une organisation dans Pix Admin (PIX-2725).
  admin/app/models/organization.js
  api/db/database-builder/factory/build-organization.js
  api/db/database-builder/factory/build-user-pix-role.js
  api/db/migrations/20210810061837_add-column-createdBy-to-organizations.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/models/Organization.js
  api/lib/domain/usecases/create-organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/domain/usecases/create-organization_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/create-organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3318 [TECH] Prévenir les traces incomplètes sur l'utilisateur de récupération de compte SCO (PIX-2986).
  api/db/migrations/20210811153908_alter_table_account-recovery-demands_add_foreign_key_not_null_userId.js
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3313 [TECH] Supression du resultCompetenceTree service partie 1 (PIX-2971)
  api/lib/domain/usecases/certificate/get-private-certificate.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/unit/domain/usecases/find-certification-attestations-for-division_test.js
  api/tests/unit/domain/usecases/get-private-certificate_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3274 [FEATURE] Affichage de l'infobulle des épreuves focus au survol (PIX-2909).
  mon-pix/app/components/challenge-statement.js
  mon-pix/app/components/challenge/statement/tooltip.hbs
  mon-pix/app/components/challenge/statement/tooltip.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/components/_tooltip.scss
  mon-pix/app/templates/components/challenge-statement.hbs
  mon-pix/public/images/tag-focused-challenge.svg
  mon-pix/public/images/tag-regular-challenge.svg
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/tests/integration/components/challenge/challenge-statement/focused-tooltip_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3320 [FEATURE] Retravailler le visuel de message de sortie de panneau d'épreuve focus (PIX-2871).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/public/images/focused-challenge-info-alert-icon.svg
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3319 [FEATURE] Retravailler le visuel du message quand on sort d'une épreuve focus (PIX-2875).
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3323 [FEATURE] Ne plus gérer spécifiquement le statut AP lors de l'import d'une liste d'élève (PIX-2951)
  api/db/database-builder/factory/build-schooling-registration.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/SchoolingRegistration.js
  api/lib/domain/services/schooling-registrations-csv-service.js
  api/lib/domain/usecases/import-schooling-registrations-from-siecle.js
  api/lib/domain/validators/schooling-registration-set-validator.js
  api/lib/domain/validators/schooling-registration-validator.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/scripts/prod/import-apprentices.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/services/schooling-registrations-csv-service_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/integration/scripts/prod/import-apprentices_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/validators/schooling-registration-validator_test.js
  api/tests/unit/infrastructure/serializers/csv/schooling-registration-parser_test.js
  orga/app/services/error-messages.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3210 [DOC] Formater les templates Ember (hbs).
  docs/adr/0029-formater-template-ember.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3325 [FEATURE] Voir le commentaire du jury sur une certif dans le fichier des résultats (PIX-996)
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/unit/application/session/session-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3328 [FEATURE] Modifications du nom de fichier du PDF des attestations de certif (PIX-3003)
  api/lib/application/organizations/organization-controller.js
  api/tests/unit/application/organizations/organization-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3327 [BUGFIX] Empêcher l'erreur 500 quand la clé des jetons Pôle-emploi expire (PIX-2990).
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/create-user-from-pole-emploi.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/usecases/create-user-from-pole-emploi_test.js
  mon-pix/app/controllers/terms-of-service-pe.js
  mon-pix/app/templates/terms-of-service-pe.hbs
  mon-pix/tests/unit/controllers/terms-of-service-pe_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3326 [FEATURE] Adapter les courbes des participations pour qu'elles aillent jusqu'à la date de fin (PIX-2978)
  orga/app/components/campaign/charts/participants-by-day.js
  orga/tests/unit/components/campaign/charts/participants-by-day_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3324 [FEATURE] Rattacher les organisations d'un profil cible existant depuis Pix Admin (PIX-2976).
  admin/app/components/target-profiles/organizations.hbs
  admin/app/components/target-profiles/organizations.js
  admin/app/controllers/authenticated/target-profiles/target-profile/organizations.js
  admin/app/models/target-profile.js
  admin/app/routes/authenticated/target-profiles/target-profile/organizations.js
  admin/app/styles/app.scss
  admin/app/styles/components/target-profiles/organizations.scss
  admin/app/templates/authenticated/target-profiles/target-profile/organizations.hbs
  admin/mirage/config.js
  admin/mirage/handlers/target-profiles.js
  admin/tests/acceptance/authenticated/target-profiles/organizations_test.js
  admin/tests/integration/components/organizations_test.js
  admin/tests/integration/components/target-profiles/organizations_test.js
  admin/tests/unit/components/target-profiles/organizations_test.js
  admin/tests/unit/controllers/authenticated/target-profiles/target-profile/organizations_test.js
  api/lib/application/error-manager.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/attach-organizations-from-existing-target-profile.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/usecases/attach-organizations-from-existing-target-profile_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3301 [TECH] Créer un script pour calculer les résultats des participations (PIX-2896).
  api/db/database-builder/factory/build-campaign-participation.js
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/seed.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/prod/compute-participation-results.js
  api/scripts/prod/compute-validated-skills-count-for-assessment-campaign-participation.js
  api/tests/integration/scripts/prod/compute-participation-results_test.js
  api/tests/integration/scripts/prod/compute-validated-skills-count-for-assessment-campaign-participation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3304 [FEATURE] Rendre la certification CléA fonctionnelle avec le nouveau RT prévu pour la rentrée (PIX-2956)
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/certification/badge-acquisition-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/CleaCertificationResult.js
  api/lib/domain/models/CleaCertificationScoring.js
  api/lib/domain/read-models/CertificationEligibility.js
  api/lib/domain/services/certification-badges-service.js
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/lib/infrastructure/repositories/clea-certification-result-repository.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/repositories/partner-certification-scoring-repository.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/clea-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/tooling/domain-builder/factory/build-clea-certification-scoring.js
  api/tests/unit/domain/models/CleaCertificationScoring_test.js
  api/tests/unit/domain/services/certification-badges-service-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3330 [TECH] Retirer la génération lazy de code de vérification lors de la récupération du certificat utilisateur (PIX-3008)
  api/db/seeds/data/certification/certification-courses-builder.js
  api/lib/domain/usecases/certificate/get-private-certificate.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/unit/domain/usecases/get-private-certificate_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3335 [TECH] Mettre à jour les dépendances des tests de charge (PIX-3037).
  high-level-tests/load-testing/.eslintignore
  high-level-tests/load-testing/.eslintrc.yaml
  high-level-tests/load-testing/data/generate-schooling-registrations.js
  high-level-tests/load-testing/functions.js
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3334 [FEATURE] Supprimer le modèle d'import et l'explication des imports pour les orga AGRI SCO (PIX-2952).
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/domain/models/Organization.js
  api/lib/domain/usecases/get-schooling-registrations-csv-template.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/unit/domain/models/Organization_test.js
  api/tests/unit/domain/usecases/get-schooling-registrations-csv-template_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  orga/app/components/student/sco/header-actions.hbs
  orga/app/components/student/sco/header-actions.js
  orga/app/models/organization.js
  orga/app/services/current-user.js
  orga/tests/integration/components/students/sco/header-actions_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3332 [FEATURE] Ne pas afficher de conseils/tooltips pour les épreuves hors focus (PIX-2899).
  mon-pix/app/components/challenge/statement/tooltip.hbs
  mon-pix/app/components/challenge/statement/tooltip.js
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/tests/integration/components/challenge/challenge-statement/focused-tooltip_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3336 [TECH] Mettre en cohérence l'URL du support
  mon-pix/app/components/footer.js
  mon-pix/app/services/url.js
  mon-pix/app/templates/components/footer.hbs
  mon-pix/tests/acceptance/footer_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, :eyes: Func Review Needed, cross-team

#3337 [FEATURE] Rendre impossible la réconciliation SUP lorsque l'étudiant est désactivé (PIX-2864).
  api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/higher-schooling-registration-repository_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3331 [SCRIPT] Ajouter la colonne "createdBy" dans le script de création des organisations PRO (PIX-3009).
  api/lib/domain/usecases/create-pro-organizations-with-tags.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/scripts/create-pro-organizations-with-tags.js
  api/scripts/helpers/csvHelpers.js
  api/tests/integration/scripts/helpers/csvHelpers_test.js
  api/tests/integration/scripts/helpers/files/withNoRequiredfieldValue-test.csv
  api/tests/integration/scripts/helpers/files/withValidHeader-test.csv
  api/tests/unit/scripts/helpers/csvHelpers_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#3340 [FEATURE] Afficher la classe dans la liste des élèves SCO (PIX-2949).
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/domain/models/UserWithSchoolingRegistration.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer_test.js
  orga/app/components/student/sco/list.hbs
  orga/app/models/student.js
  orga/tests/integration/components/students/sco/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3350 [BUGFIX] Mettre à jour le scénario des tests de charge pour une exécution locale (PIX-3043).
  high-level-tests/load-testing/.eslintrc.yaml
  high-level-tests/load-testing/functions.js
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/load-testing/scenarios/signup-and-placement.yml
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3339 [BUGFIX] Eviter qu'un même assessment possède deux réponses pour une même épreuve (PIX-2761).
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3341 [BUGFIX] Corriger la version anglaise du message d'erreur d'expiration d'authentication (PIX-2990).
  mon-pix/translations/en.json
Labels: :rocket: Ready to Merge, team-acces

#3153 [TECH] Ajouter des helpers custom Chai pour tester à la fois les types et les contenus des objets en un appel (PIX-2768)
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/repositories/pix-plus-droit-expert-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/pix-plus-droit-maitre-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/session-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/test-helper.js
  api/tests/tooling/chai-custom-helpers/deep-equal-array.js
  api/tests/tooling/chai-custom-helpers/deep-equal-instance-omitting.js
  api/tests/tooling/chai-custom-helpers/deep-equal-instance.js
  api/tests/tooling/chai-custom-helpers/index.js
  api/tests/unit/tooling/chai-custom-helpers/deep-equal-array_test.js
  api/tests/unit/tooling/chai-custom-helpers/deep-equal-instance-omitting_test.js
  api/tests/unit/tooling/chai-custom-helpers/deep-equal-instance_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3353 [TECH] Merger les services de scoring de certification (PIX-3047).
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/domain/usecases/index.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/services/scoring/scoring-certification-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3329 [FEATURE] Ajout d'une colonne filtrable "Identifiant externe" dans la liste de "Toutes les sessions" dans Pix Admin (PIX-2647)
  admin/app/components/sessions/list-items.hbs
  admin/app/controllers/authenticated/sessions/list/all.js
  admin/app/models/session.js
  admin/app/routes/authenticated/sessions/list/all.js
  admin/mirage/factories/session.js
  admin/mirage/handlers/find-paginated-and-filtered-sessions.js
  admin/tests/integration/components/routes/authenticated/sessions/list-items_test.js
  admin/tests/unit/routes/authenticated/sessions/list/all_test.js
  api/lib/domain/models/JurySession.js
  api/lib/domain/validators/session-validator.js
  api/lib/infrastructure/repositories/jury-session-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-session-serializer.js
  api/tests/acceptance/application/session/session-controller-get-jury-session_test.js
  api/tests/integration/infrastructure/repositories/jury-session-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-session-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3351 [BUGFIX] Garder les caractères spéciaux des noms/prénoms dans l'attestation de résultat (PIX-2992)
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_several_pages.pdf
  mon-pix/app/models/certification.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3348 [FEATURE] Permettre le filtre par classe sur la liste des élèves SCO (PIX-2026).
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  orga/app/components/student/sco/list.hbs
  orga/app/controllers/authenticated/sco-students/list.js
  orga/app/routes/authenticated/sco-students/list.js
  orga/app/templates/authenticated/sco-students/list.hbs
  orga/tests/integration/components/students/sco/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3347 [FEATURE] Mettre les focus sur les autres type d'épreuves (PIX-2876).
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge/item.hbs
  mon-pix/app/components/challenge/item.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_challenge.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/pages/_assessment-challenge.scss
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/qcm-proposals.hbs
  mon-pix/app/templates/components/qcu-proposals.hbs
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/tests/acceptance/competence-profile_test.js
  mon-pix/tests/integration/components/challenge/item_test.js
  mon-pix/tests/integration/components/challenge/statement/focused-tooltip_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3300 [BUGFIX] Ne pas utiliser les traitements t1,t2,t3 pour les menu déroulants (PIX-2926).
  api/lib/domain/models/Solution.js
  api/lib/domain/models/ValidatorQROC.js
  api/lib/domain/models/ValidatorQROCMDep.js
  api/lib/domain/models/ValidatorQROCMInd.js
  api/lib/domain/services/solution-service-qroc.js
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/lib/domain/services/solution-service-qrocm-ind.js
  api/lib/domain/services/solution-service-utils.js
  api/lib/infrastructure/adapters/solution-adapter.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/unit/domain/models/ValidatorQROCMDep_test.js
  api/tests/unit/domain/models/ValidatorQROCMInd_test.js
  api/tests/unit/domain/models/ValidatorQROC_test.js
  api/tests/unit/domain/services/solution-service-qroc_test.js
  api/tests/unit/domain/services/solution-service-qrocm-dep_test.js
  api/tests/unit/domain/services/solution-service-qrocm-ind_test.js
  api/tests/unit/domain/services/solution-service-utils_test.js
  api/tests/unit/domain/services/validation-treatments_test.js
  api/tests/unit/infrastructure/adapters/solution-adapter_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3360 [TECH] Utiliser la version de node applicatif au lieu de la version de node embarquée par Cypress dans les tests E2E (PIX-3050).
  high-level-tests/e2e/cypress.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3346 [FEATURE] Ne pas afficher l'encart "Repasser" lorsque l'élève/étudiant est désactivé (PIX-2991).
  api/lib/domain/models/SharedProfileForCampaign.js
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/usecases/get-user-profile-shared-for-campaign.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/acceptance/application/users/get-campaign-assessment-result_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/domain/models/SharedProfileForCampaign_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/usecases/get-user-profile-shared-for-campaign_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/shared-profile-for-campaign-serializer_test.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/templates/components/skill-review-improve.hbs
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3355 [CLEAN] Utiliser le numéro d'épreuve pour la barre de progression (PIX-3049).
  mon-pix/app/components/progress-bar.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/utils/progress-in-assessment.js
  mon-pix/tests/unit/utils/progress-in-assessment_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3357 [TECH] Migrer la colonne knowledge_elements.id de INTEGER en BIG INTEGER (partie 1).
  api/db/migrations/20210818132942_add-bigintId-to-knowledge-elements.js
  api/db/migrations/20210818155256_copy_id_to_bigintid_on_knowledge-elements.js
  api/sample.env
  api/scripts/prepare-ke-bigint-id-to-be-used-as-primary-key.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
Labels: :rocket: Ready to Merge, cross-team

#3345 [TECH] Aligner Pix Orga avec les composants Pix UI
  orga/app/adapters/students-import.js
  orga/app/components/auth/join-request-form.hbs
  orga/app/components/auth/login-form.hbs
  orga/app/components/auth/login-or-register.hbs
  orga/app/components/auth/register-form.hbs
  orga/app/components/campaign/copy-paste-button.hbs
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/header/archived-banner.hbs
  orga/app/components/campaign/header/tabs.hbs
  orga/app/components/campaign/list-actions.hbs
  orga/app/components/campaign/no-campaign-panel.hbs
  orga/app/components/campaign/settings.hbs
  orga/app/components/campaign/update-form.hbs
  orga/app/components/student/sco/dissociate-user-modal.hbs
  orga/app/components/student/sco/header-actions.hbs
  orga/app/components/student/sco/manage-authentication-method-modal.hbs
  orga/app/components/student/sup/edit-student-number-modal.hbs
  orga/app/components/student/sup/header-actions.hbs
  orga/app/components/student/sup/import-cards/add.hbs
  orga/app/components/student/sup/import-cards/replace.hbs
  orga/app/components/table/header-filter-select.hbs
  orga/app/components/table/pagination-control.hbs
  orga/app/components/table/pagination-control.js
  orga/app/components/team/invite-form.hbs
  orga/app/components/team/members-list-item.hbs
  orga/app/components/team/remove-member-modal.hbs
  orga/app/components/ui/select-input.hbs
  orga/app/controllers/authenticated/sco-students/list.js
  orga/app/controllers/authenticated/sup-students/import.js
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/header/archived-banner.scss
  orga/app/styles/components/campaign/no-campaign-panel.scss
  orga/app/styles/components/dissociate-user-modal.scss
  orga/app/styles/components/login-form.scss
  orga/app/styles/components/manage-authentication-method-modal.scss
  orga/app/styles/components/pagination-control.scss
  orga/app/styles/components/register-form.scss
  orga/app/styles/components/select-input.scss
  orga/app/styles/globals/buttons.scss
  orga/app/styles/globals/forms.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/students/import.scss
  orga/app/styles/pages/authenticated/students/list.scss
  orga/app/styles/pages/authenticated/terms-of-service.scss
  orga/app/templates/authenticated/certifications.hbs
  orga/app/templates/authenticated/team/list.hbs
  orga/app/templates/terms-of-service.hbs
  orga/config/icons.js
  orga/package-lock.json
  orga/package.json
  orga/tests/unit/adapters/students-import_test.js
  orga/tests/unit/controllers/authenticated/sco-students/list_test.js
  orga/tests/unit/controllers/authenticated/sup-students/import_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#3359 [FEATURE] Annuler une certification si taux de réponse < 33% (PIX-3046)
  api/lib/domain/events/handle-auto-jury.js
  api/lib/domain/models/CertificationAssessment.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3362 [CLEAN] Ne pas remonter les answers en doublon (PIX-2801).
  api/lib/infrastructure/repositories/answer-repository.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/tests/acceptance/application/answers/answer-controller-find_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#3372 [TECH] Exécuter les tests de charge à partir de Scalingo (PIX-3053).
  high-level-tests/load-testing/Procfile
  high-level-tests/load-testing/README.md
  high-level-tests/load-testing/config/common.yml
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/load-testing/sample.env
  high-level-tests/load-testing/scenarios/test-connectivity.yml
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3352 [TECH] Monitorer les queries Knex avec l'id de corrélation de Hapi JS, un compteur par appel API et une durée d'exécution (PIX-3044).
  api/db/knex-database-connection.js
  api/lib/config.js
  api/lib/infrastructure/performance-tools.js
  api/server.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3376 [TECH] Mettre l'annulation via taux de réponse sous toggle (PIX-3077)
  api/lib/domain/events/handle-auto-jury.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3373 [FEATURE][A11Y] Avoir une sémantique html correcte sur la page "Liste des campagnes" (PIX-3054).
  orga/app/components/campaign/list-actions.hbs
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/no-campaign-panel.hbs
  orga/app/components/campaign/update-form.hbs
  orga/app/components/table/pagination-control.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/list-actions.scss
  orga/app/styles/components/campaign/list.scss
  orga/app/styles/components/campaign/no-campaign-panel.scss
  orga/app/styles/components/pagination-control.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/campaigns.scss
  orga/app/templates/authenticated.hbs
  orga/app/templates/authenticated/campaigns.hbs
  orga/app/templates/authenticated/campaigns/list.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3374 [BUGFIX] Afficher un encart "en attente de résultats" dans l'onglet analyse individuelle quand la personne n'a pas encore partagé ses résultats (PIX-3067).
  orga/app/components/campaign/analysis/recommendations.hbs
  orga/tests/integration/components/campaign/analysis/recommendations_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3202 [TECH] Mettre à jour les paquets de Pix App (PIX-2836).
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/result-item-campaign_test.js
Labels: :rocket: Ready to Merge, cross-team

#3366 [FEATURE] Récupérer si besoin l'identifiant externe de la participation précédente pour les campagnes à envois multiples (PIX-2675).
  api/lib/application/error-manager.js
  api/lib/domain/usecases/find-answer-by-assessment.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-to-join-repository.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/usecases/start-campaign-participation_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-to-join-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/usecases/find-answer-by-assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3385 [TECH] Rendre configurable la liste d'origines des embed autorisés
  mon-pix/app/components/challenge-item-qroc.js
  mon-pix/config/environment.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-ref 🐎

#3371 [FEATURE] Suppression de l'overlay et des alertes sur les épreuves focus déjà répondues (PIX-3005).
  mon-pix/app/components/challenge/item.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/tests/acceptance/challenge-item_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3375 [TECH] Ajout du statut de l'assessment au certificationReport (PIX-3061)
  api/db/database-builder/factory/build-certification-report.js
  api/lib/domain/models/CertificationReport.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/certification-report-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-report-serializer.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/integration/infrastructure/repositories/certification-report-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-report.js
  api/tests/unit/domain/models/CertificationReport_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-report-serializer_test.js
  certif/app/models/certification-report.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3386 [FEATURE] Résolution automatique des signalement concernant les épreuves chronométrées et temps majoré (PIX-3002)
  api/db/seeds/data/certification/certification-data.js
  api/db/seeds/data/certification/user-profiles-builder.js
  api/db/seeds/data/certification/users.js
  api/lib/domain/models/CertificationIssueReportResolutionStrategies.js
  api/tests/unit/domain/models/CertificationIssueReportResolutionStrategies_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3377 [FEATURE] Utiliser la valeur du résultat stocké en BDD du participant dans la page détail (PIX-2996)
  api/lib/domain/read-models/CampaignAssessmentParticipation.js
  api/lib/domain/read-models/CampaignAssessmentParticipationCompetenceResult.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-assessment-participation-result-serializer.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
  api/tests/unit/domain/read-models/CampaignAssessmentParticipation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer_test.js
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  orga/app/components/campaign/cards/result-average.hbs
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/assessment/results.hbs
  orga/app/components/ui/progress-bar.hbs
  orga/app/components/ui/progress-bar.js
  orga/app/models/campaign-assessment-participation-competence-result.js
  orga/app/styles/components/progress-bar.scss
  orga/app/styles/globals/panels.scss
  orga/tests/integration/components/campaign/cards/result_average_test.js
  orga/tests/integration/components/participant/assessment/header_test.js
  orga/tests/integration/components/participant/assessment/results_test.js
  orga/tests/integration/components/ui/progress-bar_test.js
  orga/tests/unit/models/campaign-assessment-participation-competence-result_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3354 [FEATURE] Nouveau panneau dans le didacticiel (PIX-2898).
  mon-pix/app/routes/campaigns/assessment/tutorial.js
  mon-pix/app/styles/pages/_campaign-tutorial.scss
  mon-pix/public/images/illustrations/tutorial-campaign/icn-focus.svg
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment_test.js
  mon-pix/tests/unit/routes/campaigns/assessment/tutorial_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#3378 [TECH] Supprime les setups de test dans le describe (pix-3378)
  api/package.json
  api/tests/unit/domain/usecases/get-session-results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3384 [TECH] Ajouter des tests pour la partie logique de l'application Pix Load-Testing (PIX-3080).
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/load-testing/processor/functions.js
  high-level-tests/load-testing/tests/.eslintrc.yaml
  high-level-tests/load-testing/tests/test-helpers.js
  high-level-tests/load-testing/tests/unit/processor/functions_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#3369 [CLEAN] Remplacement des boutons du challenge en PixButton (PIX-1210).
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
  mon-pix/app/templates/components/challenge-actions.hbs
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/tests/integration/components/challenge-actions_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#3388 [TECH] Réutiliser le champ résultat pour une campagne de collecte de profils dans l'onglet 'Résultat' (PIX-3064).
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3387 [BUGFIX] Réparer l'affichage de la liste déroulante de sélection d'une sous catégorie pour un signalement "E1-E9 Problème technique sur une question" (PIX-3084).
  certif/app/styles/components/add-issue-report-modal.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3383 [TECH] Utilisation de la colonne "masteryPercentage" pour la liste des résultats d'une campagne d'évaluation (PIX-2897)
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/read-models/CampaignReport.js
  api/lib/domain/usecases/get-campaign-participations-counts-by-stage.js
  api/lib/domain/usecases/get-campaign.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-report-serializer.js
  api/tests/integration/domain/usecases/get-campaign-participations-counts-by-stage_test.js
  api/tests/integration/domain/usecases/get-campaign-participations-counts-by-status_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-list-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-report.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  api/tests/unit/domain/read-models/CampaignReport_test.js
  api/tests/unit/domain/usecases/get-campaign_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-report-serializer_test.js
  high-level-tests/e2e/cypress/fixtures/assessments.json
  high-level-tests/e2e/cypress/fixtures/campaign-participations.json
  high-level-tests/e2e/cypress/fixtures/campaigns.json
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/models/campaign-assessment-participation-result.js
  orga/app/models/campaign-collective-result.js
  orga/app/models/campaign-competence-collective-result.js
  orga/app/models/campaign.js
  orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
  orga/tests/integration/components/campaign/results/assessment-list_test.js
  orga/tests/unit/models/campaign-assessment-participation-result_test.js
  orga/tests/unit/models/campaign-collective-results_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3402 [FEATURE] Changer le message de la bannière des organisations SCO concernant les dates de certification possibles (PIX-3096)
  certif/app/templates/authenticated.hbs
  certif/tests/acceptance/authenticated_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3396 [FEATURE] Afficher la dernière participation dans l'export d'une campagne de collecte(PIX-2967)
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3403 [BUGFIX] Pouvoir importer des fichiers d'import élèves SCO sans qu'ils soient automatiquement désactivés (PIX-3110).
  api/lib/domain/usecases/import-schooling-registrations-from-siecle.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/unit/domain/usecases/import-schooling-registrations-from-siecle_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, 🌟 Etoile, Func Review OK, team-prescription

#3407 [BUGFIX] Corriger la redirection du lien pour créer un Profil Cible (PIX-3115).
  admin/app/templates/authenticated/target-profiles/list.hbs
  admin/tests/acceptance/target-profiles-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team

#3399 [TECH] Réutiliser le champ résultat pour la page "mes parcours" (PIX-3085)
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/archived_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ended_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3409 [BUGFIX] Corriger le message d'erreur lorsque l'adresse e-mail existe déjà sur Pix App (PIX-3111).
  mon-pix/app/components/user-account-update-email.js
  mon-pix/tests/integration/components/user-account-update-email_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3411 [TECH] Supprimer le feature toggle IsScoAccountRecoveryEnabled (PIX-3059).
  api/lib/application/account-recovery/index.js
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/application/schooling-registration-dependent-users/index.js
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/account-recovery/account-recovery-route-get_test.js
  api/tests/acceptance/application/account-recovery/account-recovery-route-patch_test.js
  api/tests/acceptance/application/account-recovery/account-recovery-route_test.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/acceptance/application/schooling-registration-dependent-user-route_test.js
  api/tests/integration/application/account-recovery/account-recovery-controller_test.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/routes/account-recovery/find-sco-record.js
  mon-pix/app/routes/account-recovery/update-sco-record.js
  mon-pix/tests/acceptance/account-recovery/find-sco-record_test.js
  mon-pix/tests/acceptance/account-recovery/update-sco-record_test.js
  mon-pix/tests/unit/services/feature-toggles_test.js
Labels: :rocket: Ready to Merge, team-acces

#3417 [TECH] Remplacement des modules de log `good` et associés par les versions à jour sous `@hapi`
  api/.depcheckrc
  api/lib/plugins.js
  api/package-lock.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, dependencies

#3349 [TECH] Remplacer Bookshelf par Knex dans l'authentication-method-repository (PIX-3042)
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, :eyes: Func Review Needed, cross-team

#3415 [FEATURE] Mise à jour du bandeau d'import SCO pour la rentrée 2021 (PIX-3100).
  orga/app/components/banner/information.hbs
  orga/app/components/banner/information.js
  orga/tests/integration/components/banner/information_test.js
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3414 [FEATURE] Mettre à jour la bannière des parcours de rentrée SCO pour la rentrée 2021 (PIX-3101).
  orga/app/components/banner/information.hbs
  orga/app/components/banner/information.js
  orga/tests/integration/components/banner/information_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3420 [BUGFIX] Les certifications complémentaires ne sont pas affichées comme "Annulées" lorsque la certification Pix est annulée (PIX-3117)
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3412 [TECH] Supprimer le feature toggle pour les données CPF (pix-3105)
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/models/feature-toggle.js
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/mirage/factories/feature-toggle.js
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
  api/lib/config.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/infrastructure/files/candidates-import/candidates-import-transformation-structures.js
  api/lib/infrastructure/files/candidates-import/fill-candidates-import-sheet.js
  api/lib/infrastructure/validate-environement-variables.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_reports_categorization_test.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet-1-4_extract_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-3_extract_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_1-4_extract_mandatory_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/integration/infrastructure/utils/ods/files/1.4/candidates_import_template.ods
  api/tests/integration/infrastructure/utils/ods/files/fill-candidates-import-sheet_test.js
  api/tests/integration/infrastructure/utils/ods/files/simple-attendance_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/enrolled-candidates.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/feature-toggle.js
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/unit/components/enrolled-candidates_test.js
  high-level-tests/e2e/cypress/integration/pix-certif/certification-candidates-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/pix-certif/session.js
Labels: :eyes: Tech Review Needed, Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3406 [FEATURE] Ajout de la règle de scoring global lors du scoring d'une certification (PIX-3045)
  api/lib/domain/events/handle-certification-rescoring.js
  api/lib/domain/models/AnswerCollectionForScoring.js
  api/lib/domain/models/AssessmentResult.js
  api/lib/domain/models/CertificationAssessmentScore.js
  api/lib/domain/models/CertificationContract.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/tests/tooling/domain-builder/factory/build-assessment-result.js
  api/tests/tooling/domain-builder/factory/build-certification-assessment-score.js
  api/tests/unit/domain/events/handle-certification-rescoring_test.js
  api/tests/unit/domain/models/AnswerCollectionForScoring_test.js
  api/tests/unit/domain/models/AssessmentResult_test.js
  api/tests/unit/domain/models/CertificationContract_test.js
  api/tests/unit/domain/models/CertificationCourse_test.js
  api/tests/unit/domain/services/scoring/scoring-certification-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3398 [TECH] Ne sélectionner que les derniers résultats d'un prescrit à une campagne dans l'export d'une collecte de profils (PIX-2968).
  api/lib/infrastructure/repositories/campaign-participation-info-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-info-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3361 [FEATURE] Création d'un champ `assessmentMethod` dans les campagnes 'flash' (PIX-2778).
  api/db/database-builder/factory/build-campaign.js
  api/db/migrations/20210823142553_add-column-assessment-method-to-campaigns-table.js
  api/lib/domain/models/Campaign.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-prescription

#3422 [TECH] Importer les variables CSS de pix-ui dans admin
  admin/app/styles/app.scss
  admin/app/styles/authenticated.scss
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/styles/components/certification/candidate-edit-modal.scss
  admin/app/styles/globals/button.scss
  admin/app/styles/globals/page.scss
  admin/app/styles/globals/palette.scss
  admin/app/styles/globals/table-admin.scss
  admin/ember-cli-build.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-certif, cross-team
