Repository 1024pix/pix, pull requests merged in 2021-02, with the labels that each got.

#2473 [TECH] Mise à jour Ember pour Pix-App de la version 3.22 à 3.23
  mon-pix/config/ember-cli-update.json
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, Func Review OK, team-evaluation

#2480 [BUGFIX] Le script de calcul des acquis validés pour des participations aux parcours dépasse en mémoire lorsque la campagne a trop de participants (PIX-2079).
  api/scripts/prod/compute-validated-skills-count-for-assessment-campaign-participation.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2474 [TECH] Mise à jour Ember pour pix-admin de 3.22 à 3.23
  admin/app/components/organization-information-section.hbs
  admin/app/components/organization-information-section.js
  admin/config/ember-cli-update.json
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/organization-information-section-test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2462 [FEATURE] Cacher le bouton "Quitter" pendant un parcours aux utilisateur anonymes sur Pix App (PIX-2046).
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/controllers/assessments/checkpoint.js
  mon-pix/app/models/user.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/tests/acceptance/challenge-commons-test.js
  mon-pix/tests/acceptance/checkpoint-test.js
  mon-pix/tests/unit/controllers/assessments/challenge-test.js
  mon-pix/tests/unit/controllers/assessments/checkpoint-test.js
Labels: :rocket: Ready to Merge, team-acces

#2455 [FEATURE] Séparer la liste des membres et des invitations dans deux onglets distincts sur Pix Orga (PIX-1150).
  high-level-tests/e2e/cypress/support/step_definitions/member.js
  orga/app/components/routes/authenticated/team/invitations.hbs
  orga/app/components/routes/authenticated/team/list-items.hbs
  orga/app/components/routes/authenticated/team/members.hbs
  orga/app/router.js
  orga/app/routes/authenticated/team/list/index.js
  orga/app/routes/authenticated/team/list/invitations.js
  orga/app/routes/authenticated/team/list/members.js
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/templates/authenticated/team/list.hbs
  orga/app/templates/authenticated/team/list/invitations.hbs
  orga/app/templates/authenticated/team/list/members.hbs
  orga/tests/acceptance/team-creation-test.js
  orga/tests/acceptance/team-list-items-test.js
  orga/tests/acceptance/team-list-test.js
  orga/tests/integration/components/routes/authenticated/team/invitations-test.js
  orga/tests/integration/components/routes/authenticated/team/items-test.js
  orga/tests/integration/components/routes/authenticated/team/list-items-test.js
  orga/tests/integration/components/routes/authenticated/team/members-test.js
Labels: :rocket: Ready to Merge, team-acces

#2475 [TECH] Mise à jour Ember de pix-certif de la version 3.22 à 3.23
  certif/app/components/app-modal.js
  certif/app/components/certification-candidate-in-staging-item.js
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/controllers/authenticated/sessions/list.js
  certif/app/controllers/authenticated/sessions/new.js
  certif/app/controllers/authenticated/sessions/update.js
  certif/app/models/certification-center.js
  certif/app/models/certification-report.js
  certif/app/models/session.js
  certif/app/router.js
  certif/app/routes/authenticated/sessions/add-student.js
  certif/app/routes/authenticated/sessions/details.js
  certif/app/routes/authenticated/sessions/new.js
  certif/app/routes/authenticated/sessions/update.js
  certif/app/styles/components/add-issue-report-modal.scss
  certif/app/styles/components/dropdown.scss
  certif/app/styles/components/session-finalization-formbuilder-link-step.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/pages/authenticated.scss
  certif/config/ember-cli-update.json
  certif/package-lock.json
  certif/package.json
  certif/tests/integration/components/login-form-test.js
  certif/tests/integration/components/user-logged-menu-test.js
Labels: :rocket: Ready to Merge, team-certif

#2439 [FEATURE] Enregistrer la date de l'envoi des résultats lors de l'envoi automatique (PIX-1339)
  admin/app/adapters/session.js
  admin/app/controllers/authenticated/sessions/session/certifications.js
  admin/tests/unit/adapters/session-test.js
  admin/tests/unit/controllers/authenticated/sessions/session/certifications-test.js
  api/lib/application/error-manager.js
  api/lib/application/http-errors.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/publish-session.js
  api/lib/domain/usecases/unpublish-session.js
  api/lib/domain/usecases/update-publication-session.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/acceptance/application/session/session-controller-patch-publish-session_test.js
  api/tests/acceptance/application/session/session-controller-patch-unpublish-session_test.js
  api/tests/acceptance/application/session/session-controller-patch-update-publication-session_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/publish-session_test.js
  api/tests/unit/domain/usecases/unpublish-session_test.js
  api/tests/unit/domain/usecases/update-publication-session_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2482 [FEATURE] Rediriger vers la page par défaut de Pix App lorsqu'un utilisateur saisis /mes-parcours dans l'url et n'a pas de parcours (PIX-2007).
  mon-pix/app/controllers/terms-of-service.js
  mon-pix/app/routes/terms-of-service.js
  mon-pix/app/routes/user-tests.js
  mon-pix/tests/acceptance/user-tests-test.js
  mon-pix/tests/unit/controllers/terms-of-service-test.js
  mon-pix/tests/unit/routes/user-tests-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2484 [TEST] Création de la brique de test de l'algo (PIX-2060).
  .circleci/config.yml
  high-level-tests/test-algo/README.md
  high-level-tests/test-algo/index.js
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
  high-level-tests/test-algo/sample.env
  high-level-tests/test-algo/tests/tests.sh
Labels: :rocket: Ready to Merge, team-evaluation

#2472 [TECH] Supprimer les colonnes inutilisées dans users (PIX-1711 PIX-1833).
  api/db/database-builder/factory/build-user.js
  api/db/migrations/20210129110252_remove_password_column_from_users_table.js
  api/db/migrations/20210129124701_remove_shouldChangePassword_column_from_users_table.js
  api/db/migrations/20210129140117_remove_samlId_column_from_users_table.js
  api/lib/infrastructure/repositories/user-repository.js
  high-level-tests/e2e/cypress/fixtures/users.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2483 [FEATURE] Redirige vers le dashboard quand la feature est activée (PIX-1751).
  mon-pix/app/routes/index.js
  mon-pix/tests/acceptance/authentication-test.js
  mon-pix/tests/acceptance/terms-of-service-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2493 [TECH] Update Hapi dependencies after Joi upgrade
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/swagger_test.js
Labels: :eyes: Tech Review Needed, cross-team

#2442 [BUGFIX] Empêcher les suggestions de navigateurs sur les champs de saisie (1834)
  mon-pix/app/components/qroc-proposal.js
  mon-pix/app/components/qrocm-proposal.js
  mon-pix/app/templates/components/qroc-proposal.hbs
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/app/utils/generate-random-string.js
  mon-pix/tests/integration/components/qroc-proposal-test.js
  mon-pix/tests/integration/components/qrocm-proposal-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2485 [FEATURE] Préparer l'affichage de la liste des sessions publiables (a.k.a "Sans problèmes") (PIX-2039)
  api/db/database-builder/database-buffer.js
  api/db/database-builder/factory/build-finalized-session.js
  api/db/database-builder/factory/index.js
  api/db/migrations/20210201101653_create-finalized-session-table.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/events/SessionFinalized.js
  api/lib/domain/events/handle-session-finalized.js
  api/lib/domain/events/index.js
  api/lib/domain/models/FinalizedSession.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/infrastructure/data/finalized-session.js
  api/lib/infrastructure/repositories/finalized-session-repository.js
  api/tests/integration/infrastructure/repositories/finalized-session-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/events/event-choregraphy-finalized-session_test.js
  api/tests/unit/domain/events/handle-session-finalized_test.js
  api/tests/unit/domain/models/FinalizedSession_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  api/tests/unit/tooling/database-builder/database-buffer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2490 [TECH] Installer la même version de node en local que dans la CI.
  INSTALLATION.md
  scripts/configure.sh
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2494 [BUGFIX] Fix les notifications lors de la publication de session dans pix-certif (PIX-2096)
  admin/app/controllers/authenticated/sessions/session/certifications.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2487 [FEATURE] Passage du header, footer et TDB en 1280px (PIX-1994).
  mon-pix/app/styles/components/_footer.scss
  mon-pix/app/styles/components/_navbar-desktop-header.scss
  mon-pix/app/styles/components/dashboard/_content.scss
  mon-pix/app/styles/globals/_layout.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2491 [FEATURE] Affichage des paliers dans les résultats individuels d'une campagne d'évaluation (PIX-2053).
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/app/styles/globals/panels.scss
  orga/tests/integration/components/routes/authenticated/campaign/assessment/details-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2463 [FEATURE] Filtrer les participations aux campagnes d'évaluation par paliers (PIX-1676).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/domain/models/Stage.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/usecases/find-paginated-campaign-assessment-participation-summaries.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-summary-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/domain/usecases/find-paginated-campaign-assessment-participation-summaries_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-summary-repository_test.js
  api/tests/unit/application/campaign/index_test.js
  api/tests/unit/domain/models/Stage_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/components/routes/authenticated/campaign/participation-filters.hbs
  orga/app/components/routes/authenticated/campaign/participation-filters.js
  orga/app/controllers/authenticated/campaigns/campaign/assessments.js
  orga/app/routes/authenticated/campaigns/campaign/assessments.js
  orga/app/templates/authenticated/campaigns/campaign/assessments.hbs
  orga/tests/integration/components/routes/authenticated/campaign/participation-filters-test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/assessments-test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/assessments-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2492 [FEATURE] Affichage des résultats thématiques dans les résultats individuels d'une campagne d'évaluation (PIX-2054).
  api/db/database-builder/factory/build-assessment-from-participation.js
  api/lib/application/campaign-participation-results/campaign-participation-result-controller.js
  api/lib/application/campaign-participation-results/index.js
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/application/campaign-participations/index.js
  api/lib/domain/read-models/CampaignAssessmentParticipation.js
  api/lib/domain/usecases/get-campaign-assessment-participation.js
  api/lib/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer.js
  api/lib/routes.js
  api/tests/integration/application/campaignParticipations/index_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/unit/application/campaignParticipationResult/campaign-participation-result_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/usecases/get-campaign-assessment-participation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer_test.js
  orga/app/components/badges.hbs
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/app/components/routes/authenticated/campaign/assessment/details.js
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/models/campaign-assessment-participation.js
  orga/app/styles/globals/panels.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants.scss
  orga/tests/integration/components/routes/authenticated/campaign/assessment/details-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2450 [TECH] Prévenir l'introduction de liens non joignables dans la documentation.
  .circleci/config.yml
  docs/README.md
  docs/adr/0008-découplage-fonctionnel-via-evenements.md
  docs/adr/0013-gestion-erreurs-api-ihm.md
  docs/link--check-config.json
  docs/security/security.md
  docs/test.md
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#2489 [BUGFIX] Pouvoir se réconcilier après avoir eu une erreur et corrigé ses infos lors de la réconciliation SCO.
  mon-pix/app/components/routes/campaigns/restricted/join-sco.js
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sco-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-acces

#2481 [FEATURE] Améliorations de la page de finalisation de session (PIX-1996)
  certif/app/components/issue-report-modal/add-issue-report-modal.js
  certif/app/components/issue-report-modal/candidate-information-change-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/candidate-information-change-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/late-or-leaving-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/late-or-leaving-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/other-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/other-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/technical-problem-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/technical-problem-certification-issue-report-fields.js
  certif/app/components/session-finalization-examiner-global-comment-step.hbs
  certif/app/components/session-finalization-reports-informations-step.hbs
  certif/app/styles/components/add-issue-report-modal.scss
  certif/app/styles/components/session-finalization-examiner-global-comment-step.scss
  certif/app/styles/components/session-finalization-reports-informations-step.scss
  certif/app/styles/globals/app-modal.scss
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-finalization-test.js
  certif/tests/integration/components/issue-report-modal/candidate-information-change-certification-issue-report-fields-test.js
  certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields-test.js
  certif/tests/integration/components/issue-report-modal/late-or-leaving-certification-issue-report-fields-test.js
  certif/tests/integration/components/issue-report-modal/other-certification-issue-report-fields-test.js
  certif/tests/integration/components/issue-report-modal/technical-problem-certification-issue-report-fields-test.js
  certif/tests/integration/components/session-finalization-examiner-global-comment-step-test.js
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-certif

#2447 [DOC] ADR - Caractère obligatoire ou optionnel du use-case.
  docs/adr/0020-caractere-obligatoire-use-case.md
Labels: :rocket: Ready to Merge, cross-team

#2476 [FEATURE] Permettre aux utilisateurs de modifier leur adresse e-mail (PIX-2045).
  mon-pix/app/adapters/user.js
  mon-pix/app/components/user-account-panel.js
  mon-pix/app/styles/components/_user-account-panel.scss
  mon-pix/app/templates/components/user-account-panel.hbs
  mon-pix/mirage/routes/users/index.js
  mon-pix/tests/acceptance/user-account-test.js
  mon-pix/tests/integration/components/user-account-panel-test.js
  mon-pix/tests/unit/adapters/user-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2488 [FEATURE] Changer l'entrée de menu "Profil" en "Compétences" (PIX-2080).
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/controllers/profile.js
  mon-pix/app/router.js
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/components/profile-content.hbs
  mon-pix/app/templates/profile.hbs
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2464 [TECH] Valider les identifiants dans l'API.
  api/lib/application/answers/index.js
  api/lib/application/assessments/index.js
  api/lib/application/campaign-participation-results/index.js
  api/lib/application/campaign-participations/index.js
  api/lib/application/campaigns/index.js
  api/lib/application/certification-centers/index.js
  api/lib/application/certification-courses/index.js
  api/lib/application/certification-issue-reports/index.js
  api/lib/application/certification-point-of-contacts/index.js
  api/lib/application/certification-reports/index.js
  api/lib/application/certifications/index.js
  api/lib/application/challenges/index.js
  api/lib/application/courses/index.js
  api/lib/application/memberships/index.js
  api/lib/application/organization-invitations/index.js
  api/lib/application/organizations/index.js
  api/lib/application/prescribers/index.js
  api/lib/application/schooling-registration-user-associations/index.js
  api/lib/application/sessions/index.js
  api/lib/application/target-profiles/index.js
  api/lib/application/tutorial-evaluations/index.js
  api/lib/application/user-orga-settings/index.js
  api/lib/application/user-tutorials/index.js
  api/lib/application/users/index.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/get-correction-for-answer.js
  api/lib/domain/validators/id-specification.js
  api/lib/domain/validators/session-validator.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/acceptance/application/answers/answer-controller-get_test.js
  api/tests/integration/application/campaignParticipations/index_test.js
  api/tests/integration/application/campaigns/index_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/users/index_test.js
  api/tests/unit/application/answers/index_test.js
  api/tests/unit/application/assessments/index_test.js
  api/tests/unit/domain/types/identifiers-type_test.js
  api/tests/unit/domain/usecases/get-correction-for-answer_test.js
  docs/adr/00019-typer-les-identifiants.md
Labels: :rocket: Ready to Merge, cross-team

#2477 [FEATURE] Ajout du résultat dans les cartes terminées des tableaux de bord (PIX-2049)
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/domain/usecases/find-user-campaign-participation-overviews.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer.js
  api/tests/acceptance/application/users/users-controller-get-campaign-participation-overviews_test.js
  api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
  api/tests/unit/domain/usecases/find-user-campaign-participation-overviews_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
  mon-pix/app/components/campaign-participation-overview/card.hbs
  mon-pix/app/components/campaign-participation-overview/card.js
  mon-pix/app/models/campaign-participation-overview.js
  mon-pix/app/styles/components/campaign-participation-overview/_card.scss
  mon-pix/tests/acceptance/user-dashboard-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/grid-test.js
  mon-pix/tests/unit/components/campaign-participation-overview/card-test.js
  mon-pix/tests/unit/models/campaign-participation-overview-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2486 [FEATURE] Ajout de "Mes parcours" dans le menu de Pix App (PIX-2004)
  mon-pix/app/components/navbar-burger-menu.js
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/models/user.js
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/mirage/factories/user.js
  mon-pix/tests/acceptance/user-logged-menu-test.js
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
  mon-pix/tests/integration/components/user-logged-menu-test.js
  mon-pix/tests/unit/models/user-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2502 [BUGFIX] Les filtres sur les paliers dans la liste des participants d'une campagne sur PixOrga ne fonctionnent pas correctement (PIX-2107)
  api/db/seeds/data/campaign-participations-builder.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2503 [BUGFIX] Le script dév/local de génération de campagnes avec participants ne fonctionne plus (PIX-2108)
  api/scripts/data-generation/generate-campaign-with-participants.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-prescription

#2496 [FEATURE] Ajouter un bandeau Pix Certif pour la fonctionnalité d'envoi automatique des résultats (PIX-2087)
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/list.js
  certif/app/styles/pages/authenticated/sessions/add-student.scss
  certif/app/styles/pages/authenticated/sessions/list-items.scss
  certif/app/templates/authenticated/sessions/add-student.hbs
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/list.hbs
  certif/tests/unit/controllers/authenticated/sessions/details-test.js
  certif/tests/unit/controllers/authenticated/sessions/list-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2499 [FEATURE] Obtenir la liste des sessions "sans problème" (PIX-2095)
  api/db/database-builder/factory/build-finalized-session.js
  api/db/migrations/20210203110934_add-publishedAt-in-finalized-session-table.js
  api/lib/application/sessions/finalized-session-controller.js
  api/lib/application/sessions/index.js
  api/lib/domain/models/FinalizedSession.js
  api/lib/domain/read-models/JuryCertificationSummary.js
  api/lib/domain/usecases/find-finalized-sessions-to-publish.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/publish-session.js
  api/lib/infrastructure/repositories/finalized-session-repository.js
  api/lib/infrastructure/serializers/jsonapi/finalized-session-serializer.js
  api/tests/acceptance/application/finalized-session/finalized-session-controller-find-finalized-sessions-to-publish_test.js
  api/tests/acceptance/application/session/session-controller-patch-publish-session_test.js
  api/tests/integration/infrastructure/repositories/finalized-session-repository_test.js
  api/tests/tooling/domain-builder/factory/build-finalized-session.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/session/finalized-session-controller_test.js
  api/tests/unit/domain/events/handle-session-finalized_test.js
  api/tests/unit/domain/read-models/JuryCertificationSummary_test.js
  api/tests/unit/domain/usecases/find-finalized-sessions-to-publish_test.js
  api/tests/unit/domain/usecases/publish-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/finalized-session-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2505 [FEATURE] Affichage des compétences en anglais lorsque la langue saisie est "en" dans l'onglet des résultats collectifs (PIX-2098).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/domain/read-models/Prescriber.js
  api/lib/domain/usecases/compute-campaign-collective-result.js
  api/lib/infrastructure/repositories/prescriber-repository.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/tests/acceptance/application/prescriber-controller_test.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
  api/tests/tooling/domain-builder/factory/build-prescriber.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/usecases/compute-campaign-collective-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  orga/app/adapters/application.js
  orga/app/adapters/prescriber.js
  orga/app/adapters/user.js
  orga/app/app.js
  orga/app/formats.js
  orga/app/index.html
  orga/app/models/prescriber.js
  orga/app/routes/application.js
  orga/config/ember-intl.js
  orga/mirage/config.js
  orga/package-lock.json
  orga/package.json
  orga/tests/unit/adapters/application-test.js
  orga/tests/unit/adapters/prescriber-test.js
  orga/tests/unit/adapters/user-test.js
  orga/tests/unit/routes/application-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2512 [TECH] Génération des snapshots KE pour les données de seeds (dév/local/RA) (PIX-2119)
  api/db/batchTreatment.js
  api/db/seeds/seed.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/prod/generate-knowledge-element-snapshots-for-campaigns.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/integration/scripts/prod/generate-knowledge-element-snapshots-for-campaigns_test.js
Labels: :rocket: Ready to Merge, Tech Review OK

#2518 [TECH] Empêcher le rechargement infini des tests dans Pix Admin
  admin/tests/integration/components/target-profiles/create-target-profile-form-test.js
Labels: :rocket: Ready to Merge, cross-team

#2495 [FEATURE] Afficher un message quand le tableau de bord est vide (PIX-2081).
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/dashboard/content.js
  mon-pix/app/styles/components/_new-information.scss
  mon-pix/app/templates/components/new-information.hbs
  mon-pix/public/images/fusee.png
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/tests/unit/components/dashboard/content-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2507 [FEATURE] Afficher la liste des membres d'un centre de certification dans Pix Admin (PIX-504).
  admin/app/adapters/certification-center-membership.js
  admin/app/components/certification-center-memberships-section.hbs
  admin/app/models/certification-center-membership.js
  admin/app/models/certification-center.js
  admin/app/models/user.js
  admin/app/routes/authenticated/certification-centers/get.js
  admin/app/styles/authenticated/certification-center/index.scss
  admin/app/templates/authenticated/certification-centers/get.hbs
  admin/mirage/config.js
  admin/mirage/serializers/certification-center-membership.js
  admin/mirage/serializers/certification-center.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/certification-centers/get-test.js
  admin/tests/integration/components/certification-center-memberships-section-test.js
  admin/tests/unit/adapters/certification-center-membership-test.js
  api/db/database-builder/factory/build-certification-center-membership.js
  api/db/seeds/data/certification/certification-center-memberships-builder.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/models/CertificationCenterMembership.js
  api/lib/domain/usecases/find-certification-center-memberships-by-certification-center.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-membership-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-serializer.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-certification-center-memberships_test.js
  api/tests/integration/domain/usecases/find-certification-center-memberships-by-certification-center_test.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-center-membership.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/certification-centers/index_test.js
  api/tests/unit/domain/usecases/find-certification-center-memberships-by-certification-center_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-membership-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-serializer_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2501 [FEATURE] Changer le contenu de la tooltip dans le modèle de liste des candidats (PIX-2085)
  api/lib/infrastructure/files/candidates-import/candidates_import_template.ods
  api/tests/integration/infrastructure/utils/ods/files/candidates_import_template.ods
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2520 [FEATURE] Ne plus afficher l'état d'avancement lorsque le participant a partagé ses résultats (PIX-2127).
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/tests/integration/components/routes/authenticated/campaign/assessment/details-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2517 [TECH] Supprimer la route dépréciée users /{id}/certification-center-memberships.
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/get-user-certification-center-memberships.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/users/users-controller-get-certification-center-memberships_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-user-certification-center-memberships_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2511 [FEATURE] Permettre au script de création de membres de centre de certification d'ajouter de nouveaux membres (PIX-1948).
  api/scripts/create-certification-center-memberships-from-organization-admins.js
  api/tests/integration/scripts/create-certification-center-memberships-from-organization-admins_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2521 [FEATURE]Affichage des compétences en anglais lorsque la langue saisie est "en" dans les résultats individuels d'une campagne d'évaluation (PIX-2099).
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/domain/usecases/get-campaign-assessment-participation-result.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-repository.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/usecases/get-campaign-assessment-participation-result_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2526 [BUGFIX] Corriger la taille de l'abeille sur la page de partage de profil (PIX-2115)
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/styles/pages/_send-profile.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
  mon-pix/app/templates/components/campaign-start-block.hbs
  mon-pix/app/templates/components/skill-review-try-again.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2508 [FEATURE] Amélioration de la phrase sur le consentement dans la landing page pour un parcours (PIX-2109).
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2529 [TECH] Ajouter un titre sur les liens externes dans les consignes (PIX-2124).
  mon-pix/app/components/challenge-statement.js
  mon-pix/tests/integration/components/challenge-statement-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge

#2534 [BUGFIX] Eviter l'échec du hook des seeds dans les RAs en évitant d'ouvrir plusieurs connexions à la BDD (PIX-2139)
  api/db/seeds/seed.js
Labels: :rocket: Ready to Merge, Tech Review OK

#2506 [FEATURE] Ajout des cartes archivés dans la page 'mes-parcours' (Pix-2005)
  api/db/database-builder/factory/campaign-participation-overview-factory.js
  api/db/database-builder/factory/index.js
  api/lib/application/users/index.js
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer.js
  api/tests/acceptance/application/users/users-controller-get-campaign-participation-overviews_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
  mon-pix/app/components/campaign-participation-overview/card.hbs
  mon-pix/app/components/campaign-participation-overview/card.js
  mon-pix/app/models/campaign-participation-overview.js
  mon-pix/app/routes/user-tests.js
  mon-pix/app/styles/components/campaign-participation-overview/_card.scss
  mon-pix/tests/integration/components/campaign-participation-overview/card-test.js
  mon-pix/tests/unit/components/campaign-participation-overview/card-test.js
  mon-pix/tests/unit/models/campaign-participation-overview-test.js
  mon-pix/tests/unit/routes/user-tests-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2532 [TECH] Rendre les tests de target-profile-repository déterministes.
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2530 [TECH] Corriger et refactorer les seeds (PIX-2137).
  api/db/database-builder/factory/build-campaign.js
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/campaigns-builder.js
  api/db/seeds/data/certification/badge-acquisition-builder.js
  api/db/seeds/data/certification/users.js
  api/db/seeds/data/organizations-pro-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/db/seeds/data/organizations-sup-builder.js
  api/db/seeds/data/pix-aile-builder.js
  api/db/seeds/data/pix-emploi-target-profile-builder.js
  api/db/seeds/data/stages-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/db/seeds/data/users-builder.js
  api/db/seeds/data/users_pix_roles-builder.js
  api/db/seeds/seed.js
  api/scripts/data-generation/add-many-students-to-sco-certification-center.js
  api/tests/acceptance/scripts/add-many-divisions-and-students-to-sco-organization_test.js
  api/tests/acceptance/scripts/add-many-students-to-sco-certification-center_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-prescription

#2498 [FEATURE] Ajout du Pix-score sur le tableau de bord (PIX-1660).
  mon-pix/app/components/competence-card/list.hbs
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/dashboard/content.js
  mon-pix/app/styles/components/_badge-acquired-card.scss
  mon-pix/app/styles/components/_new-information.scss
  mon-pix/app/styles/components/campaign-participation-overview/_grid.scss
  mon-pix/app/styles/components/competence-card/_list.scss
  mon-pix/app/styles/components/dashboard/_content.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/ember-cli-build.js
  mon-pix/tests/acceptance/user-dashboard-test.js
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/tests/unit/components/dashboard/content-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2537 [BUGFIX] Corriger la marge dans les cartes de parcours (PIX-2006).
  mon-pix/app/components/campaign-participation-overview/card.hbs
  mon-pix/app/styles/components/campaign-participation-overview/_card.scss
  mon-pix/app/styles/components/campaign-participation-overview/_grid.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2538 [TECH] Récupérer toutes les épreuves posées par l'algo et y répondre juste (PIX-2061).
  high-level-tests/test-algo/.eslintignore
  high-level-tests/test-algo/.eslintrc.yaml
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/index.js
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
  high-level-tests/test-algo/tests/index_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2531 [FEATURE] Afficher un lien de téléchargement des résultats d'une session dans Pix Admin (PIX-2042)
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/models/session.js
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/mirage/config.js
  admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js
  admin/tests/acceptance/session-test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.js
  admin/tests/unit/controllers/authenticated/sessions/session/informations-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/session-results-link-service.js
  api/lib/domain/services/token-service.js
  api/tests/acceptance/application/session/session-controller-generate-session-results-download-link_test.js
  api/tests/acceptance/application/session/session-controller-get-session-results-to-download_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/services/session-results-link-service_test.js
  api/tests/unit/domain/services/token-service_test.js
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, Tech Review OK, team-certif

#2541 [FEATURE] Changement de la couleur de la bannière (PIX-2033).
  admin/app/styles/misc/palette.scss
  mon-pix/app/components/progress-bar.js
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/public/images/Illu_niveau6_fr.svg
  mon-pix/public/images/hexa-pix-blue.svg
  mon-pix/public/images/tutorial-campaign/icn-algo.svg
  mon-pix/public/images/tutorial-campaign/icn-recherche.svg
  mon-pix/public/images/tutorial-campaign/icn-temps.svg
  mon-pix/public/images/tutorial-campaign/icn-tutos.svg
  mon-pix/tests/unit/components/progress-bar-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2540 [FEATURE] Affichage des compétences en anglais lorsque la langue saisie est "en" dans les résultats individuels d'une campagne de collecte de profils (PIX-2114).
  api/db/seeds/data/campaigns-builder.js
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/domain/services/placement-profile-service.js
  api/lib/domain/usecases/get-campaign-profile.js
  api/lib/infrastructure/repositories/campaign-profile-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/tests/integration/domain/services/placement-profile-service_test.js
  api/tests/integration/domain/usecases/get-campaign-profile_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/usecases/get-campaign-profile_test.js
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/app/styles/globals/panels.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2549 [BUGFIX] Une erreur floue s'affiche lorsqu'on publie une session sur PixAdmin (PIX-2154)
  api/lib/infrastructure/repositories/finalized-session-repository.js
  api/tests/integration/infrastructure/repositories/finalized-session-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#2551 [BUGFIX] Utiliser replace au lieu de replaceAll (PIX-2155).
  mon-pix/app/components/challenge-statement.js
Labels: :rocket: Ready to Merge, team-evaluation

#2542 [FEATURE] Amélioration de l'a11y sur la page d'accès aux campagnes (PIX-1873).
  mon-pix/app/templates/fill-in-campaign-code.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2543 [FEATURE] Je veux des alt corrects pour les logo Pix qui me renvoie sur l'accueil (PIX-1837).
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/app/templates/components/pix-logo.hbs
  mon-pix/app/templates/components/reset-password-form.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/app/templates/components/update-expired-password-form.hbs
  mon-pix/app/templates/terms-of-service-pe.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/tests/integration/components/pix-logo-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2536 [FEATURE] Affichage des sujets et tutos en anglais lorsque la langue saisie est "en" dans l'analyse globale d'une campagne d'évaluation (PIX-2100).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/domain/usecases/compute-campaign-analysis.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/usecases/compute-campaign-analysis_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2545 [BUGFIX] Gérer le retour à la ligne de l'icone nouvel onglet (PIX-2152).
  mon-pix/app/styles/components/_challenge-statement.scss
Labels: :rocket: Ready to Merge, team-evaluation

#2548 [TECH] Améliorer l'a11y de la page checkpoint (PIX-1863).
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/result-item.hbs
  mon-pix/app/templates/components/tutorial-panel.hbs
Labels: :rocket: Ready to Merge, team-evaluation

#2544 [BUGFIX] Avoir une erreur 400 quand le format de réponse n'est pas le bon (PIX-2116).
  api/lib/application/answers/index.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/unit/application/answers/index_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2555 [ORGA] Ajout de la langue anglaise sur le menu gauche, ainsi que la déconnexion (PIX-2160)
  orga/app/components/sidebar-menu.hbs
  orga/app/components/user-logged-menu.hbs
  orga/tests/helpers/setup-intl-rendering.js
  orga/tests/helpers/setup-intl.js
  orga/tests/integration/components/user-logged-menu-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2515 [FEATURE] Demander 2 fois la saisie de l’adresse e-mail pour la modifier dans la page "Mon compte" sur Pix App (PIX-2082).
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/update-user-email.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/domain/usecases/update-user-details-for-administration_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/domain/usecases/update-user-email_test.js
  mon-pix/app/components/user-account-panel.js
  mon-pix/app/components/user-account-update-email.js
  mon-pix/app/controllers/user-account.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_user-account-panel.scss
  mon-pix/app/styles/components/_user-account-update-email.scss
  mon-pix/app/styles/components/_user-account.scss
  mon-pix/app/templates/components/user-account-panel.hbs
  mon-pix/app/templates/components/user-account-update-email.hbs
  mon-pix/app/templates/user-account.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/user-account-test.js
  mon-pix/tests/integration/components/user-account-panel-test.js
  mon-pix/tests/integration/components/user-account-update-email-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#2546 [CLEANUP] Suppression du toggle d'envoi automatique des resultats (PIX-2153)
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/certification-candidate-in-staging-item.js
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/enrolled-candidates.js
  certif/app/components/import-candidates.hbs
  certif/app/components/import-candidates.js
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/list.js
  certif/app/templates/authenticated/sessions/details/certification-candidates.hbs
  certif/config/environment.js
  certif/tests/acceptance/session-details-certification-candidates-test.js
  certif/tests/integration/components/enrolled-candidates-test.js
  certif/tests/integration/components/import-candidates-test.js
  certif/tests/unit/controllers/authenticated/sessions/details-test.js
  certif/tests/unit/controllers/authenticated/sessions/list-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2556 [FEATURE] Ajouter un lien à la bannière du TDB (PIX-2123).
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/dashboard/content.js
  mon-pix/app/styles/components/_new-information.scss
  mon-pix/app/templates/components/new-information.hbs
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2563 [BUGFIX] Pouvoir envoyer une réponse vide quand le temps est passé (PIX-2170).
  api/lib/application/answers/index.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2564 [BUGFIX] Bloquer les réponses après lorsque le délais de réponse est dépassé (PIX-2171).
  mon-pix/app/components/challenge-item-generic.js
Labels: :rocket: Ready to Merge, team-evaluation

#2527 [FEATURE] Afficher la liste des sessions à publier (PIX-2095)
  admin/app/adapters/publishable-session.js
  admin/app/components/publishable-sessions/list-items.hbs
  admin/app/components/publishable-sessions/list-items.js
  admin/app/controllers/authenticated/sessions/list/all.js
  admin/app/controllers/authenticated/sessions/list/to-be-published.js
  admin/app/models/publishable-session.js
  admin/app/router.js
  admin/app/routes/authenticated/sessions/list/all.js
  admin/app/routes/authenticated/sessions/list/to-be-published.js
  admin/app/routes/authenticated/sessions/session/informations.js
  admin/app/styles/app.scss
  admin/app/styles/authenticated/sessions/list.scss
  admin/app/styles/components/publish-session-button.scss
  admin/app/styles/misc/page.scss
  admin/app/templates/authenticated/sessions/list.hbs
  admin/app/templates/authenticated/sessions/list/all.hbs
  admin/app/templates/authenticated/sessions/list/to-be-published.hbs
  admin/mirage/config.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/sessions/list/to-be-published-test.js
  admin/tests/integration/components/routes/authenticated/publishable-sessions/list-items-test.js
  admin/tests/unit/adapters/publishable-session-test.js
  admin/tests/unit/controllers/authenticated/sessions/list/all-test.js
  admin/tests/unit/controllers/authenticated/sessions/list/to-be-published-test.js
  admin/tests/unit/models/publishable-session-test.js
  admin/tests/unit/routes/authenticated/sessions/list/all-test.js
  admin/tests/unit/routes/authenticated/sessions/list/to-be-published-test.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/lib/domain/usecases/unpublish-session.js
  api/lib/infrastructure/serializers/jsonapi/finalized-session-serializer.js
  api/tests/acceptance/application/finalized-session/finalized-session-controller-find-finalized-sessions-to-publish_test.js
  api/tests/acceptance/application/session/session-controller-patch-unpublish-session_test.js
  api/tests/unit/domain/usecases/unpublish-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/finalized-session-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2562 [FEATURE] Ne pas afficher le didacticiel pour une campagne simplifiée pour des novices (PIX-2130).
  api/db/database-builder/factory/build-campaign.js
  api/db/migrations/20210216141040_add-column-for-absolute-novice-to-campaigns.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/read-models/CampaignToJoin.js
  api/lib/infrastructure/serializers/jsonapi/campaign-to-join-serializer.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-to-join.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-to-join-serializer_test.js
  mon-pix/app/models/campaign.js
  mon-pix/app/routes/campaigns/assessment/start-or-resume.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2561 [API] Corriger le flaky test du script create-certification-center-memberships-from-organization-admins_test.js (PIX-2169).
  api/tests/integration/scripts/create-certification-center-memberships-from-organization-admins_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2553 [TECH] Corriger le flaky test sur PUT /api/schooling-registration-user-associations/possibilities de l'API (PIX-2157).
  api/tests/acceptance/application/schooling-registration-user-association-controller_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2565 [TECH] Ajuster l'appel au linter stylelint.
  mon-pix/app/styles/components/competence-card/_list.scss
  mon-pix/app/styles/components/dashboard/_content.scss
  mon-pix/package.json
Labels: :rocket: Ready to Merge, team-evaluation

#2554 [FEATURE] Affichage des sujets et tutos en anglais lorsque la langue saisie est "en" dans l'analyse individuelle d'une campagne d'évaluation (PIX-2101).
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/domain/usecases/compute-campaign-participation-analysis.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/tests/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/application/campaignParticipations/campaign-participation-controller_test.js
  api/tests/unit/domain/usecases/compute-campaign-analysis_test.js
  api/tests/unit/domain/usecases/compute-campaign-participation-analysis_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2557 [FEATURE] Traduction de la liste des campagnes dans Pix Orga (PIX-2142).
  orga/app/components/pagination-control.hbs
  orga/app/components/routes/authenticated/campaign/list.hbs
  orga/app/components/routes/authenticated/campaign/no-campaign-panel.hbs
  orga/app/templates/authenticated/campaigns/list.hbs
  orga/tests/integration/components/routes/authenticated/campaign/list-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2547 [A11Y] Suppression de tag 'alt' inutile (PIX-1895).
  mon-pix/app/components/timeout-gauge.js
  mon-pix/app/components/timeout-jauge.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_timed-challenge-instructions.scss
  mon-pix/app/styles/components/_timeout-gauge.scss
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/app/templates/components/timed-challenge-instructions.hbs
  mon-pix/app/templates/components/timeout-gauge.hbs
  mon-pix/app/templates/components/timeout-jauge.hbs
  mon-pix/tests/acceptance/challenge-timed-test.js
  mon-pix/tests/integration/components/timeout-gauge-test.js
  mon-pix/tests/integration/components/timeout-jauge-test.js
  mon-pix/tests/unit/components/timeout-gauge-test.js
  mon-pix/tests/unit/components/timeout-jauge-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2539 [FEATURE] Ajouter la saisie du mot de passe pour le changement d'adresse e-mail sur Pix App (PIX-1745).
  api/lib/application/error-manager.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/update-user-email.js
  api/sample.env
  api/tests/acceptance/application/users/users-controller-patch-email_test.js
  api/tests/unit/domain/usecases/update-user-email_test.js
  mon-pix/app/components/user-account-update-email.js
  mon-pix/app/controllers/user-account.js
  mon-pix/app/styles/components/_user-account-update-email.scss
  mon-pix/app/templates/components/user-account-update-email.hbs
  mon-pix/app/templates/user-account.hbs
  mon-pix/mirage/routes/users/index.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/user-account-test.js
  mon-pix/tests/integration/components/user-account-update-email-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2567 [BUGFIX] Corriger un problème d'affichage des tables dans Pix Admin (PIX-2179)
  admin/app/styles/misc/table-admin.scss
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2522 [FEATURE] Voir le nombre de participants et supprimer les filtres dans la bannière de filtres (PIX-2056).
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/components/routes/authenticated/campaign/participation-filters.hbs
  orga/app/components/routes/authenticated/campaign/participation-filters.js
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/assessments.js
  orga/app/controllers/authenticated/campaigns/campaign/profiles.js
  orga/app/templates/authenticated/campaigns/campaign/assessments.hbs
  orga/app/templates/authenticated/campaigns/campaign/profiles.hbs
  orga/config/icons.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
  orga/tests/integration/components/routes/authenticated/campaign/participation-filters-test.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/list-test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/assessments-test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/profiles-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2533 [TECH] Mettre le composant PixIconButton partout dans PixOrga (PIX-2138).
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/chevron.hbs
  orga/app/components/dropdown/icon-trigger.hbs
  orga/app/components/manage-authentication-method-modal.hbs
  orga/app/components/modal/dialog.hbs
  orga/app/components/pagination-control.hbs
  orga/app/components/pagination-control.js
  orga/app/components/previous-page-button.hbs
  orga/app/components/previous-page-button.js
  orga/app/components/routes/authenticated/campaign/analysis/tab.js
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/app/components/routes/authenticated/campaign/details/tab.hbs
  orga/app/components/routes/authenticated/campaign/profile/details.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/routes/authenticated/team/items.hbs
  orga/app/components/routes/login-form.hbs
  orga/app/components/routes/register-form.hbs
  orga/app/components/table/header-sort.hbs
  orga/app/styles/components/modal.scss
  orga/app/styles/components/pagination-control.scss
  orga/app/styles/globals/buttons.scss
  orga/app/styles/globals/forms.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/campaigns/details.scss
  orga/app/styles/pages/authenticated/campaigns/details/details.scss
  orga/app/styles/pages/authenticated/students/list.scss
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/pagination-control-test.js
  orga/tests/integration/components/previous-page-button_test.js
  orga/tests/integration/components/routes/authenticated/campaign/analysis/tab-test.js
  orga/tests/integration/components/tables/header-sort-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2558 [FEATURE] Traduction de la page de création de campagne (PIX-2143).
  orga/app/components/routes/authenticated/campaign/new.hbs
  orga/app/components/routes/authenticated/campaign/new.js
  orga/app/controllers/authenticated/campaigns/new.js
  orga/app/styles/globals/forms.scss
  orga/app/templates/authenticated/campaigns/new.hbs
  orga/tests/acceptance/campaign-creation-test.js
  orga/tests/helpers/extended-ember-test-helpers/click-by-label.js
  orga/tests/integration/components/routes/authenticated/campaign/new-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2560 [FEATURE] Traduction de la page de détails d'une campagne (PIX-2144).
  orga/app/components/routes/authenticated/campaign/details/tab.hbs
  orga/app/components/routes/authenticated/campaign/details/tab.js
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/tests/integration/components/routes/authenticated/campaign/details/tab-test.js
  orga/tests/integration/components/routes/authenticated/campaign/report-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2576 [TECH] Ajouter le feature toggle sur la récupération des résultats de certif SCO sur Pix Orga (pix-2180)
  api/lib/config.js
  api/tests/acceptance/application/feature-controller_tests.js
  orga/app/models/feature-toggle.js
  orga/app/routes/application.js
  orga/app/services/feature-toggles.js
  orga/mirage/config.js
  orga/mirage/factories/feature-toggle.js
  orga/tests/unit/routes/application-test.js
  orga/tests/unit/services/feature-toggle-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2573 [BUGFIX] Dans Pix Orga, interdire l'accès à la page de détail d'une campagne, à un utilisateur qui n'est pas membre de organisation liée (PIX-2183).
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/begin-campaign-participation-improvement.js
  api/lib/domain/usecases/compute-campaign-analysis.js
  api/lib/domain/usecases/compute-campaign-collective-result.js
  api/lib/domain/usecases/compute-campaign-participation-analysis.js
  api/lib/domain/usecases/find-answer-by-assessment.js
  api/lib/domain/usecases/find-association-between-user-and-schooling-registration.js
  api/lib/domain/usecases/find-campaign-participations-related-to-assessment.js
  api/lib/domain/usecases/find-campaign-profiles-collection-participation-summaries.js
  api/lib/domain/usecases/find-competence-evaluations-by-assessment.js
  api/lib/domain/usecases/find-paginated-campaign-assessment-participation-summaries.js
  api/lib/domain/usecases/find-tutorials.js
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/domain/usecases/get-campaign-assessment-participation-result.js
  api/lib/domain/usecases/get-campaign-assessment-participation.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/domain/usecases/get-campaign-participation.js
  api/lib/domain/usecases/get-campaign-profile.js
  api/lib/domain/usecases/get-campaign.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/get-schooling-registrations-csv-template.js
  api/lib/domain/usecases/get-scorecard.js
  api/lib/domain/usecases/get-session-with-candidates.js
  api/lib/domain/usecases/share-campaign-result.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/usecases/find-paginated-campaign-assessment-participation-summaries_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/usecases/begin-campaign-participation-improvement_test.js
  api/tests/unit/domain/usecases/compute-campaign-analysis_test.js
  api/tests/unit/domain/usecases/compute-campaign-collective-result_test.js
  api/tests/unit/domain/usecases/compute-campaign-participation-analysis_test.js
  api/tests/unit/domain/usecases/find-answer-by-assessment_test.js
  api/tests/unit/domain/usecases/find-association-between-user-and-schooling-registration_test.js
  api/tests/unit/domain/usecases/find-campaign-participations-related-to-assessment_test.js
  api/tests/unit/domain/usecases/find-campaign-profiles-collection-participation-summaries_test.js
  api/tests/unit/domain/usecases/find-competence-evaluations-by-assessment_test.js
  api/tests/unit/domain/usecases/find-tutorials_test.js
  api/tests/unit/domain/usecases/get-attendance-sheet_test.js
  api/tests/unit/domain/usecases/get-campaign-assessment-participation-result_test.js
  api/tests/unit/domain/usecases/get-campaign-assessment-participation_test.js
  api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
  api/tests/unit/domain/usecases/get-campaign-participation_test.js
  api/tests/unit/domain/usecases/get-campaign-profile_test.js
  api/tests/unit/domain/usecases/get-campaign_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/domain/usecases/get-schooling-registrations-csv-template_test.js
  api/tests/unit/domain/usecases/get-scorecard_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#2569 [BUGFIX] Pôle-emploi - Corriger la gestion du refus d'un demandeur d'emploi, interdisant PIX d'utiliser ses données (PIX-2165).
  mon-pix/app/routes/login-pe.js
  mon-pix/config/environment.js
  mon-pix/tests/unit/routes/login-pe-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-acces, team-prescription

#2550 [TECH] Empêcher le démarrage de l'API si la configuration est incorrecte.
  api/lib/infrastructure/validate-environement-variables.js
  api/server.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2580 [BUGFIX] Affichage du nom de la compétence dans les notifications de gain de niveau (PIX-2172).
  api/lib/application/answers/answer-controller.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/unit/application/answers/answer-controller_test.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/controllers/assessments/checkpoint.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
Labels: :rocket: Ready to Merge, team-evaluation

#2587 [TECH] Ignorer l'indisponibilité temporaire de martinfowler.com.
  docs/link--check-config.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2570 [FEATURE] Déconnecter un utilisateur anonyme lorsqu'il accède à une campagne à accès simplifié (PIX-2097).
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/mirage/routes/auth/index.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
  mon-pix/tests/unit/components/navbar-desktop-header-test.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2574 [FEATURE] Ne pas afficher le lien de partage pour les campagnes pour débutant (PIX-2131).
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/mirage/factories/user.js
  mon-pix/mirage/serializers/user.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2572 [A11Y] Ajouter une exception à la règle no-duplicate-landmark-elements du linter (PIX-2187).
  mon-pix/.template-lintrc.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco.hbs
  mon-pix/app/components/routes/campaigns/restricted/user-information-form.hbs
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/app/templates/components/certifications-list-item.hbs
  mon-pix/app/templates/components/form-textfield-date.hbs
  mon-pix/app/templates/components/qrocm-ind-solution-panel.hbs
  mon-pix/app/templates/components/reached-stage.hbs
  mon-pix/app/templates/components/routes/register-form.hbs
  mon-pix/app/templates/user-tutorials.hbs
Labels: :rocket: Ready to Merge, cross-team

#2586 [FEATURE] Marquer le signalement 'Problème technique' en tant que signalement impactant (PIX-2058)
  api/lib/domain/models/CertificationIssueReport.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2585 [TECH] Correction dans le nom des onglets des fichiers ODS de PixCertif (PIX-2075)
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template_reports_categorization.ods
  api/lib/infrastructure/files/candidates-import/candidates_import_template.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/attendance_sheet_template_reports_categorization_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/infrastructure/utils/ods/files/candidates_import_template.ods
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2582 [BUGFIX] Corrige la publication de sessions sans certifications
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2552 [TECH] Rafraîchir le cache en ligne de commande.
  api/package.json
  api/scripts/refresh-cache.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2590 [FEATURE] Trier la liste des sessions sans problème par date de finalisation ascendante dans PixAdmin (PIX-2207)
  api/lib/infrastructure/repositories/finalized-session-repository.js
  api/tests/integration/infrastructure/repositories/finalized-session-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2358 [FEATURE] Sécuriser l'API pour le livret scolaire (PIX-1937).
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/application/certification-livret-scolaire/index.js
  api/lib/application/error-manager.js
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/application/security-livret-scolaire-pre-handlers.js
  api/lib/application/security-pre-handlers.js
  api/lib/config.js
  api/lib/domain/errors.js
  api/lib/domain/services/token-service.js
  api/lib/domain/usecases/authenticate-application-livret-scolaire.js
  api/lib/domain/usecases/certificate/get-certifications-results-for-ls.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/open-api-doc/authentication/response-authentication-doc.js
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/lib/infrastructure/security-livret-scolaire.js
  api/lib/swaggers.js
  api/server.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/acceptance/application/certifications-livret-scolaire/certification-controller_test.js
  api/tests/acceptance/application/feature-controller_tests.js
  api/tests/acceptance/application/security-pre-handlers_test.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/acceptance/application/users/users-controller-patch-email_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
  api/tests/test-helper.js
  api/tests/tooling/domain-builder/factory/build-certifications-results-for-ls.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/preHandlers/feature-toggles_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
Labels: :rocket: Ready to Merge, team-certif

#2579 [FEATURE] Désactiver la saisie automatique des champs dans le formulaire de changement d'e-mail de Pix App (PIX-2189).
  mon-pix/app/templates/components/user-account-update-email.hbs
  mon-pix/tests/integration/components/user-account-update-email-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#2577 [FEATURE] ABCDiag - Ne pas afficher la landing page pour les campagnes “ForAbsoluteNovice” (PIX-2129).
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2588 [TECH] Améliorer l'orthographe pour prévenir les bugs.
  admin/app/templates/authenticated/tools.hbs
  api/lib/application/authentication/index.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-livret-scolaire/index.js
  api/lib/application/error-manager.js
  api/lib/application/organization-invitations/index.js
  api/lib/application/preHandlers/assessment-authorization.js
  api/lib/application/sessions/index.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/Solution.js
  api/lib/domain/models/Validation.js
  api/lib/domain/read-models/CampaignAssessmentParticipation.js
  api/lib/domain/read-models/StudentForEnrollment.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/pick-challenge-service.js
  api/lib/domain/services/smart-random/cat-algorithm.js
  api/lib/domain/services/solution-service-qrocm-ind.js
  api/lib/domain/services/solution-service.js
  api/lib/domain/usecases/create-organization-invitations.js
  api/lib/domain/usecases/find-students-for-enrollment.js
  api/lib/domain/usecases/index.js
  api/lib/domain/validators/certification-center-creation-validator.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/response-objects/unprocessable-entity-error.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/read-models/CampaignAssessmentParticipation_test.js
  api/tests/unit/domain/usecases/find-students-for-enrollement_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-certification-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2581 [FEATURE] Créer la route de récupération des résultats de certif pour orga (PIX-2191)
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/application/security-pre-handlers.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/security-pre-handlers_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2389 [CLEANUP] Glimmerizer des composants Pix APP (PIX-2186).
  mon-pix/app/components/certifications-list-item.js
  mon-pix/app/components/certifications-list.js
  mon-pix/app/components/challenge-illustration.js
  mon-pix/app/components/navbar-desktop-menu.js
  mon-pix/app/components/no-certification-panel.js
  mon-pix/app/components/progression-gauge.js
  mon-pix/app/components/user-certifications-detail-result.js
  mon-pix/app/components/user-certifications-panel.js
  mon-pix/app/templates/components/certifications-list-item.hbs
  mon-pix/app/templates/components/certifications-list.hbs
  mon-pix/app/templates/components/challenge-illustration.hbs
  mon-pix/app/templates/components/navbar-desktop-menu.hbs
  mon-pix/app/templates/components/progression-gauge.hbs
  mon-pix/app/templates/components/user-certifications-detail-result.hbs
  mon-pix/app/templates/components/user-certifications-panel.hbs
  mon-pix/tests/integration/components/certifications-list-item-test.js
  mon-pix/tests/integration/components/certifications-list-test.js
  mon-pix/tests/integration/components/challenge-illustration-test.js
  mon-pix/tests/integration/components/navbar-desktop-nav-menu-test.js
  mon-pix/tests/integration/components/no-certification-panel-test.js
  mon-pix/tests/integration/components/progression-gauge-test.js
  mon-pix/tests/integration/components/user-certifications-detail-result-test.js
  mon-pix/tests/integration/components/user-certifications-panel-test.js
Labels: :rocket: Ready to Merge, cross-team

#2594 [TECH] Supprimer des tests inutiles.
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/preHandlers/assessment-authorization_test.js
  api/tests/unit/application/preHandlers/session-authorization_test.js
  api/tests/unit/application/preHandlers/user-existence-verification_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2568 [FEATURE] Rattacher un utilisateur à un centre de certification dans Pix Admin (PIX-503).
  admin/app/adapters/certification-center-membership.js
  admin/app/controllers/authenticated/certification-centers/get.js
  admin/app/routes/authenticated/certification-centers/get.js
  admin/app/styles/authenticated/certification-center/index.scss
  admin/app/templates/authenticated/certification-centers/get.hbs
  admin/mirage/config.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/certification-centers/get-test.js
  admin/tests/integration/components/certification-center-memberships-section-test.js
  admin/tests/unit/adapters/certification-center-membership-test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get-test.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/usecases/create-certification-center-membership-by-email.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/integration/domain/usecases/create-certification-center-membership-by-email_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/certification-centers/index_test.js
  api/tests/unit/domain/usecases/create-certification-center-membership-by-email_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2595 [FEATURE] Permettre à un utilisateur connecté à app.pix.org de changer sa langue sur la page "Mon compte" (PIX-1176).
  mon-pix/app/components/user-account-panel.js
  mon-pix/app/routes/application.js
  mon-pix/app/styles/components/_user-account-panel.scss
  mon-pix/app/styles/components/_user-account-update-email.scss
  mon-pix/app/templates/components/user-account-panel.hbs
  mon-pix/app/templates/components/user-account-update-email.hbs
  mon-pix/config/icons.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/user-account-panel-test.js
  mon-pix/tests/unit/routes/application-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2578 [FEATURE] Traduction de la page de résultats individuels d'une campagne d'évaluation (PIX-2148).
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/progress-bar.hbs
  orga/app/components/progression-gauge.hbs
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/app/components/routes/authenticated/campaign/assessment/results.hbs
  orga/app/components/routes/authenticated/campaign/profile/details.hbs
  orga/app/components/stage-stars.js
  orga/tests/acceptance/campaign-participants-results-test.js
  orga/tests/acceptance/profile-test.js
  orga/tests/integration/components/routes/authenticated/campaign/assessment/details-test.js
  orga/tests/integration/components/routes/authenticated/campaign/assessment/results-test.js
  orga/tests/integration/components/stage-stars-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2575 [FEATURE] Ajouter les paliers sur les carte archivées et Terminées (Pix-2006)
  api/db/database-builder/factory/campaign-participation-overview-factory.js
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/domain/usecases/find-user-campaign-participation-overviews.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer.js
  api/tests/acceptance/application/users/users-controller-get-campaign-participation-overviews_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
  api/tests/unit/domain/usecases/find-user-campaign-participation-overviews_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
  mon-pix/app/components/campaign-participation-overview/card.hbs
  mon-pix/app/components/campaign-participation-overview/card.js
  mon-pix/app/components/campaign-participation-overview/card/archived.hbs
  mon-pix/app/components/campaign-participation-overview/card/archived.js
  mon-pix/app/components/campaign-participation-overview/card/ended.hbs
  mon-pix/app/components/campaign-participation-overview/card/ended.js
  mon-pix/app/components/campaign-participation-overview/card/ongoing.hbs
  mon-pix/app/components/campaign-participation-overview/card/to-share.hbs
  mon-pix/app/models/campaign-participation-overview.js
  mon-pix/app/styles/components/campaign-participation-overview/_card.scss
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/acceptance/user-logged-menu-test.js
  mon-pix/tests/helpers/campaign.js
  mon-pix/tests/helpers/click-by-label.js
  mon-pix/tests/helpers/contains.js
  mon-pix/tests/helpers/find-by-label.js
  mon-pix/tests/integration/components/campaign-participation-overview/card-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/archived-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ended-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ongoing-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/to-share-test.js
  mon-pix/tests/integration/components/routes/campaigns/restricted/join-sup-test.js
  mon-pix/tests/unit/components/campaign-participation-overview/card-test.js
  mon-pix/tests/unit/helpers/contains-test.js
  mon-pix/tests/unit/models/campaign-participation-overview-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2599 [TECH] Pouvoir tester l'algo sur un profil cible (PIX-2062).
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/index.js
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
  high-level-tests/test-algo/tests/index_test.js
  high-level-tests/test-algo/tests/tests.sh
Labels: :rocket: Ready to Merge, team-evaluation

#2584 [FEATURE] Traduction de la page d'analyse d'une campagne d'évaluation dans Pix Orga (PIX-2147).
  orga/app/components/chevron.hbs
  orga/app/components/routes/authenticated/campaign/analysis/tab.hbs
  orga/app/components/routes/authenticated/campaign/analysis/tab.js
  orga/app/components/routes/authenticated/campaign/analysis/tube-recommendation-row.hbs
  orga/app/components/tutorial-counter.hbs
  orga/tests/integration/components/routes/authenticated/campaign/analysis/tab-test.js
  orga/tests/integration/components/routes/authenticated/campaign/analysis/tube-recommendation-row-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2583 [FEATURE] Suppression du feature toggle "Accueil & Mes parcours" et suppression du bandeau de reprise de campagne d'évaluation (PIX-2150).
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/integration/pix-app/login-logout-app.feature
  high-level-tests/e2e/cypress/integration/pix-app/page-title.feature
  high-level-tests/e2e/cypress/integration/pix-app/profile.feature
  high-level-tests/e2e/cypress/integration/pix-app/signup.feature
  high-level-tests/e2e/cypress/integration/pix-app/terms-of-service.feature
  high-level-tests/e2e/cypress/integration/pix-app/update-password.feature
  high-level-tests/e2e/cypress/integration/pix-app/user-tutorials.feature
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  high-level-tests/e2e/cypress/support/step_definitions/update-password.js
  mon-pix/app/components/navbar-burger-menu.js
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/components/resume-campaign-banner.js
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/controllers/profile.js
  mon-pix/app/router.js
  mon-pix/app/routes/index.js
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/navbar-desktop-header.hbs
  mon-pix/app/templates/components/resume-campaign-banner-assessment.hbs
  mon-pix/app/templates/components/resume-campaign-banner.hbs
  mon-pix/app/templates/profile.hbs
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/authentication-test.js
  mon-pix/tests/acceptance/certification-course-test.js
  mon-pix/tests/acceptance/competence-profile-test.js
  mon-pix/tests/acceptance/competences-details-test.js
  mon-pix/tests/acceptance/competences-results-test.js
  mon-pix/tests/acceptance/footer-test.js
  mon-pix/tests/acceptance/navigation-test.js
  mon-pix/tests/acceptance/profile-test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/acceptance/terms-of-service-test.js
  mon-pix/tests/acceptance/tutorial-actions-test.js
  mon-pix/tests/acceptance/update-expired-password-test.js
  mon-pix/tests/acceptance/user-dashboard-test.js
  mon-pix/tests/acceptance/user-logged-menu-test.js
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
  mon-pix/tests/integration/components/resume-campaign-banner-test.js
  mon-pix/tests/integration/components/user-logged-menu-test.js
  mon-pix/tests/unit/components/resume-campaign-banner-test.js
  mon-pix/tests/unit/components/user-logged-menu-test.js
  mon-pix/tests/unit/routes/index-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation, team-prescription

#2603 [FEATURE] Ne pas afficher "Envoyé le" lorsque que la campagne n'est pas partagé ( PIX-2149)
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/app/components/routes/authenticated/campaign/profile/details.hbs
  orga/tests/integration/components/routes/authenticated/campaign/assessment/details-test.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/details-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2609 [BUG] Correction d'un flaky test dans CampaignController (PIX-2223)
  api/tests/acceptance/application/campaign-controller_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-prescription

#2607 [FEATURE] Afficher la bannière de création de campagne pour les organismes SCO Agriculture (PIX-2219)
  orga/app/components/information-banner.hbs
  orga/app/components/information-banner.js
  orga/tests/integration/components/information-banner-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2598 [FEATURE] Ajout d'un nouvel onglet "Certifications" dans le menu de PixOrga (pix-2190)
  orga/app/components/sidebar-menu.hbs
  orga/app/components/sidebar-menu.js
  orga/app/router.js
  orga/app/routes/authenticated/certifications.js
  orga/app/services/feature-toggles.js
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/certifications.scss
  orga/app/templates/authenticated/certifications.hbs
  orga/config/icons.js
  orga/tests/acceptance/authentication-test.js
  orga/tests/integration/components/sidebar-menu-test.js
  orga/tests/unit/routes/authenticated/certifications-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2593 [CLEANUP] Bumper ember-keyboard et glimmerizer les composants associés (PIX-2211).
  mon-pix/app/components/pix-modal.js
  mon-pix/app/components/routes/campaigns/restricted/join-sco-information-modal.hbs
  mon-pix/app/components/user-logged-menu.js
  mon-pix/app/styles/pages/_join-restricted-campaign.scss
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/app/templates/components/scorecard-details.hbs
  mon-pix/app/templates/components/user-logged-menu.hbs
  mon-pix/config/environment.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/unit/components/pix-modal-test.js
  mon-pix/tests/unit/components/user-logged-menu-test.js
Labels: :rocket: Ready to Merge, cross-team

#2566 [TECH] Suppression du timer en doublon
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge-item-qroc.js
  mon-pix/app/components/timeout-gauge.js
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/app/templates/components/challenge-item-qroc.hbs
  mon-pix/app/templates/components/challenge-item-qrocm.hbs
  mon-pix/tests/unit/components/timeout-gauge-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2608 [BUGFIX] Eviter de voir l'écran de warning après une épreuve timée (PIX-2176).
  mon-pix/app/components/challenge-item-generic.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2613 [FEATURE] Traduire la page de modification pour les campagnes d'évaluation et de collecte de profils (PIX-2204)
  orga/app/components/routes/authenticated/campaign/update.hbs
  orga/tests/integration/components/routes/authenticated/campaign/update-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-prescription

#2592 [TECH] Ne pas jeter d'erreur s'il n'y a pas de solution à une clé de réponse donnée
  api/lib/domain/services/solution-service-qrocm-ind.js
  api/tests/unit/domain/services/solution-service-qrocm-ind_test.js
Labels: :rocket: Ready to Merge, cross-team, team-evaluation

#2610 [FEATURE] Ajout de la traduction pour la tooltip des crédits (PIX-2197)
  orga/app/components/organization-credit-info.hbs
  orga/app/components/organization-credit-info.js
  orga/tests/integration/components/organization-credit-info-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2614 [TECH] Retrait du feature toggle pour la prescription de certif SCO (PIX-1599)
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/application/sessions/index.js
  api/lib/config.js
  api/lib/domain/usecases/authenticate-user.js
  api/tests/acceptance/application/feature-controller_tests.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/unit/application/preHandlers/feature-toggles_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/feature-toggle-serializer_test.js
  certif/app/models/feature-toggle.js
  certif/app/routes/authenticated/sessions/details.js
  certif/tests/acceptance/session-details-certification-candidates-test.js
  certif/tests/unit/controllers/authenticated/sessions/details-test.js
  certif/tests/unit/routes/authenticated/sessions/details-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2618 [TECH] Retrait du feature toggle d'activation de la catégorisation des signalements (PIX-1999)
  api/lib/application/sessions/session-controller.js
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template.ods
  api/lib/infrastructure/files/attendance-sheet/attendance_sheet_template_reports_categorization.ods
  api/lib/infrastructure/repositories/certification-report-repository.js
  api/tests/acceptance/application/feature-controller_tests.js
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_reports_categorization_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/attendance_sheet_template_reports_categorization_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/attendance_sheet_template_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/infrastructure/repositories/certification-report-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
  certif/app/adapters/session.js
  certif/app/components/session-finalization-examiner-global-comment-step.hbs
  certif/app/components/session-finalization-formbuilder-link-step.hbs
  certif/app/components/session-finalization-formbuilder-link-step.js
  certif/app/components/session-finalization-reports-informations-step.hbs
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/models/feature-toggle.js
  certif/app/routes/authenticated/sessions/details.js
  certif/app/routes/authenticated/sessions/finalize.js
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/config/environment.js
  certif/tests/acceptance/session-finalization-test.js
  certif/tests/integration/components/session-finalization-examiner-global-comment-step-test.js
  certif/tests/integration/components/session-finalization-formbuilder-link-step-test.js
  certif/tests/integration/components/session-finalization-reports-informations-step-test.js
  certif/tests/unit/adapters/session-test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize-test.js
  certif/tests/unit/routes/authenticated/sessions/finalize-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2605 [TECH] Ecriture d'un script à exécuter en local pour créer en masse des certifications dans une organisation (PIX-2194)
  api/scripts/data-generation/generate-certifications-for-organization.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2589 [FEATURE] Traduction de la page de la liste des participants d'une campagne d'évaluation(PIX-2158).
  orga/app/components/routes/authenticated/campaign/assessment/list.hbs
  orga/app/components/routes/authenticated/campaign/participation-filters.hbs
  orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2600 [FEATURE] Traduction de la page de résultats collectifs d’une campagne d'évaluation (PIX-2145).
  orga/app/components/routes/authenticated/campaign/collective-results/tab.hbs
  orga/app/components/routes/authenticated/campaign/collective-results/tab.js
  orga/tests/integration/components/routes/authenticated/campaign/collective-results/tab-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2602 [FEATURE] Traduction de la page de la liste des participants d’une campagne de collecte de profils (PIX-2200).
  orga/app/components/routes/authenticated/campaign/profile/list.hbs
  orga/tests/integration/components/routes/authenticated/campaign/profile/list-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2619 [TECH] Ajouter prescriberTitle et prescriberDescription en base de données(PIX-2167)
  api/db/database-builder/factory/build-stage.js
  api/db/migrations/20210224170037_add-prescriber-description-and-prescriber-title-to-stages-table.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2621 [FEATURE] Endpoint de téléchargement des résultats de certification SCO par classe depuis pix-orga (PIX-2077)
  api/lib/application/error-manager.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/get-sco-certification-results-by-division.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/sco-certification-candidate-repository.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/sco-certification-candidate-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/get-sco-certification-results-by-division_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2597 [FEATURE] Ajouter les liens CGU et Protection des données dans le footer de Pix App (PIX-2125).
  mon-pix/app/components/footer.js
  mon-pix/app/services/url.js
  mon-pix/app/styles/components/_footer.scss
  mon-pix/app/templates/components/footer.hbs
  mon-pix/tests/integration/components/footer-test.js
  mon-pix/tests/unit/services/url-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2612 Corrige le tri des competences pour le livret scolaire
  api/lib/domain/usecases/certificate/get-certifications-results-for-ls.js
Labels: :rocket: Ready to Merge, team-certif
