Repository 1024pix/pix, pull requests merged in 2021-04, with the labels that each got.

#2791 [FEATURE] Amélioration de l'a11y sur la page de présentation de campagne (PIX-1879).
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2784 [FEATURE] Changer la puce de couleur par une barre de couleur pour les compétences (PIX-2337)
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/components/campaign-skill-review-competence-result.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2781 [TECH] Empêcher le re-scoring lors de la récupération des détails de certification sur Admin (PIX-2419)
  admin/app/models/feature-toggle.js
  admin/app/routes/application.js
  admin/app/routes/authenticated/certifications/certification/details.js
  admin/app/serializers/certification-details.js
  admin/app/services/feature-toggles.js
  admin/mirage/config.js
  admin/mirage/factories/feature-toggle.js
  admin/tests/unit/serializers/certification-details-test.js
  admin/tests/unit/services/feature-toggles-test.js
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/application/certification-courses/index.js
  api/lib/config.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/PlacementProfile.js
  api/lib/domain/read-models/CertificationDetails.js
  api/lib/domain/usecases/get-certification-details.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/lib/infrastructure/repositories/competence-mark-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-details-serializer.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js
  api/tests/tooling/domain-builder/factory/build-answer.js
  api/tests/tooling/domain-builder/factory/build-certification-assessment.js
  api/tests/tooling/domain-builder/factory/build-certification-details.js
  api/tests/tooling/domain-builder/factory/build-placement-profile.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/PlacementProfile_test.js
  api/tests/unit/domain/read-models/CertificationDetails_test.js
  api/tests/unit/domain/usecases/get-certification-details_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-details-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2730 [FEATURE] Ajouter les épreuves Pix+ Droit lors du choix des épreuves à l'élaboration d'un test de certif (PIX-2259)
  api/db/database-builder/factory/build-badge.js
  api/db/migrations/20210318145742_add-column-is-certifiable-to-badges.js
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/campaigns-builder.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/db/seeds/data/certification/certification-center-memberships-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/db/seeds/data/certification/users.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/domain/constants.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/CampaignParticipationBadge.js
  api/lib/domain/models/CertifiableProfileForLearningContent.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/models/TargetedCompetence.js
  api/lib/domain/services/certifiable-badges.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/certifiable-profile-for-learning-content-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/integration/infrastructure/repositories/certifiable-profile-for-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-badge.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-badge.js
  api/tests/tooling/domain-builder/factory/build-certifiable-profile-for-learning-content.js
  api/tests/tooling/domain-builder/factory/build-knowledge-element.js
  api/tests/tooling/domain-builder/factory/build-targeted-competence.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/models/CertifiableProfileForLearningContent_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
  api/tests/unit/domain/services/certifiable-badges_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2802 [INFRA] Uniformise un champs de message d'erreur dans un log
  api/lib/application/sessions/session-controller.js
  api/tests/unit/application/session/session-controller_test.js
Labels: :rocket: Ready to Merge, team-certif

#2789 [FEATURE] Traduction de phrases oubliées sur Pix Orga (Pix-2426).
  orga/app/components/current-organization.hbs
  orga/app/components/dropdown/icon-trigger.hbs
  orga/app/components/edit-student-number-modal.hbs
  orga/app/components/pix-loader.hbs
  orga/app/components/routes/authenticated/campaign/analysis/tab.hbs
  orga/app/components/routes/authenticated/campaign/analysis/tube-recommendation-row.hbs
  orga/app/components/routes/authenticated/campaign/assessment/details.hbs
  orga/app/components/routes/authenticated/campaign/collective-results/success-indicator.hbs
  orga/app/components/routes/authenticated/campaign/collective-results/success-indicator.js
  orga/app/components/routes/authenticated/campaign/list.hbs
  orga/app/components/routes/authenticated/campaign/profile/details.hbs
  orga/app/components/routes/authenticated/campaign/report.hbs
  orga/app/components/routes/authenticated/sco-students/list-items.hbs
  orga/app/components/routes/authenticated/sup-students/list-items.hbs
  orga/app/components/routes/authenticated/team/items.hbs
  orga/app/components/routes/authenticated/team/items.js
  orga/app/components/routes/authenticated/team/new-item.hbs
  orga/app/components/routes/login-or-register.hbs
  orga/app/components/table/header-sort.hbs
  orga/app/components/tutorial-counter.hbs
  orga/app/components/user-logged-menu.hbs
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/campaigns/details/collective-results/success-indicator.scss
  orga/app/templates/authenticated.hbs
  orga/app/templates/authenticated/team/list.hbs
  orga/app/templates/join-request.hbs
  orga/app/templates/login.hbs
  orga/app/templates/terms-of-service.hbs
  orga/tests/acceptance/remove-membership-test.js
  orga/tests/acceptance/team-creation-test.js
  orga/tests/integration/components/current-organization-test.js
  orga/tests/integration/components/dropdown/icon-trigger-test.js
  orga/tests/integration/components/pix-loader-test.js
  orga/tests/integration/components/routes/authenticated/campaign/collective-results/success-indicator-test.js
  orga/tests/integration/components/routes/authenticated/team/items-test.js
  orga/tests/integration/components/tables/header-sort-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2769 [BUGFIX] Empecher l'embed de dépasser de l'iframe
  mon-pix/app/styles/components/_challenge-embed-simulator.scss
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2809 [TECH] Supprimer <°)))><
  api/lib/config.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  mon-pix/app/components/hexagon-score.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/app/templates/components/hexagon-score.hbs
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/tests/integration/components/hexagon-score-test.js
  mon-pix/tests/integration/components/profile-content-test.js
  mon-pix/tests/unit/components/hexagon-score-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2775 [TECH] Prévenir les injections SQL dans l'API.
  api/.eslintrc.yaml
  api/db/database-builder/database-builder.js
  api/db/knex-database-connection.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/repositories/campaign-to-join-repository.js
  api/lib/infrastructure/repositories/certification-point-of-contact-repository.js
  api/package-lock.json
  api/package.json
  api/scripts/data-generation/generate-certifications-for-organization.js
  api/scripts/generate-certification-test-statistics.js
  api/scripts/prod/compute-validated-skills-count-for-assessment-campaign-participation.js
Labels: :rocket: Ready to Merge, cross-team

#2808 [FEATURE] Changement de wording dans la page de l'envoi des résultats d'une campagne archivée sur Mon-Pix (2429).
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2797 [TECH] Parser les date only (comme les date d'anniversaire) en heure locale sans offset.
  mon-pix/app/components/user-certifications-detail-header.js
  mon-pix/app/services/intl-date-formatter.js
  mon-pix/app/templates/components/user-certifications-detail-header.hbs
  mon-pix/app/utils/parse-iso-date-only.js
  mon-pix/tests/unit/services/intl-date-formatter-test.js
  mon-pix/tests/unit/utils/parse-iso-date-only-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2804 [FEATURE] Changement de la pagination à 25 par défaut au lieu de 10 dans la liste des participants sur Pix Orga (PIX-2428).
  orga/app/controllers/authenticated/campaigns/campaign/assessments.js
  orga/app/controllers/authenticated/campaigns/campaign/profiles.js
  orga/app/routes/authenticated/campaigns/campaign/assessments.js
  orga/app/routes/authenticated/campaigns/campaign/profiles.js
  orga/tests/acceptance/campaign-participants-test.js
  orga/tests/acceptance/campaign-profiles-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2693 [TECH] Refacto de la gestion des token via Hapi (PIX-2408).
  admin/app/services/current-user.js
  admin/tests/acceptance/authenticated/certifications/certification/profile-test.js
  admin/tests/acceptance/authenticated/sessions/list/to-be-published-test.js
  admin/tests/acceptance/authenticated/sessions/list/with-required-action-test.js
  admin/tests/acceptance/certification-center-form--test.js
  admin/tests/acceptance/certification-centers-list-test.js
  admin/tests/acceptance/organization-information-management-test.js
  admin/tests/acceptance/organization-list-test.js
  admin/tests/acceptance/organization-memberships-management-test.js
  admin/tests/acceptance/organization-target-profiles-management-test.js
  admin/tests/acceptance/sessions-list-test.js
  admin/tests/acceptance/target-profiles-details-test.js
  admin/tests/acceptance/target-profiles-list-test.js
  admin/tests/acceptance/tools-page-test.js
  admin/tests/acceptance/user-list-test.js
  api/lib/application/certification-livret-scolaire/index.js
  api/lib/application/pre-response-utils.js
  api/lib/application/security-livret-scolaire-pre-handlers.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/usecases/checkUserIsAuthenticated.js
  api/lib/infrastructure/security-livret-scolaire.js
  api/lib/infrastructure/security.js
  api/server.js
  api/tests/acceptance/application/security-pre-handlers_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/application/scorecards/index_test.js
  api/tests/unit/application/security-pre-handlers_test.js
  api/tests/unit/application/stages/index_test.js
  api/tests/unit/application/tutorial-evaluations/index_test.js
  api/tests/unit/application/usecases/checkUserIsAuthenticated_test.js
  api/tests/unit/application/user-tutorials/index_test.js
  api/tests/unit/application/users/index_test.js
  certif/app/services/current-user.js
  high-level-tests/e2e/cypress/integration/pix-app/login-logout-app.feature
  mon-pix/app/mixins/secured-route-mixin.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/error.js
  mon-pix/app/services/current-user.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/unit/routes/error-test.js
  orga/app/services/current-user.js
  orga/mirage/config.js
  orga/tests/unit/services/current-user-test.js
Labels: :rocket: Ready to Merge, cross-team, team-acces

#2805 [FEATURE] Monter la limite du numéro d'épreuve de 48 à 64 lors de la finalisation de session pour inclure les épreuves Pix+ Droit (PIX-2368)
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.hbs
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2792 [FEATURE] Permettre de dissocier un utilisateur d'une seule inscription scolaire dans Pix Admin (PIX-2356).
  admin/app/adapters/schooling-registration.js
  admin/app/adapters/user.js
  admin/app/components/confirm-popup.hbs
  admin/app/components/user-detail-personal-information.hbs
  admin/app/components/user-detail-personal-information.js
  admin/app/models/schooling-registration.js
  admin/mirage/config.js
  admin/tests/acceptance/user-details-personal-information-test.js
  admin/tests/integration/components/user-detail-personal-information-test.js
  admin/tests/unit/adapters/schooling-registration-test.js
  admin/tests/unit/adapters/user-test.js
  admin/tests/unit/components/user-detail-personal-information-test.js
  api/lib/application/schooling-registration-user-associations/index.js
  api/lib/application/schooling-registration-user-associations/schooling-registration-user-association-controller.js
  api/lib/domain/usecases/dissociate-user-from-schooling-registration.js
  api/tests/acceptance/application/schooling-registration-user-association-controller_test.js
  api/tests/unit/application/schooling-registration-user-associations/index_test.js
  api/tests/unit/application/schooling-registration-user-associations/schooling-registration-user-associations-controller_test.js
  api/tests/unit/domain/usecases/dissociate-user-from-schooling-registration_test.js
  orga/app/adapters/student.js
  orga/mirage/config.js
  orga/tests/acceptance/dissociate-student-test.js
  orga/tests/unit/adapters/student-test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2816 [BUGFIX] Restoration de l'icône svg icon-reload.svg.
  admin/servers.conf.erb
  certif/servers.conf.erb
  mon-pix/public/images/icons/icon-reload.svg
  mon-pix/servers.conf.erb
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
  orga/servers.conf.erb
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2783 [APP] Utilisation du composant `PixProgressGauge` dans Pix App et Pix Orga (Pix-2333)
  mon-pix/app/components/progression-gauge.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_progression-gauge.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/components/campaign-skill-review-competence-result.hbs
  mon-pix/app/templates/components/progression-gauge.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/integration/components/progression-gauge-test.js
  orga/app/components/progression-gauge.hbs
  orga/app/components/progression-gauge.js
  orga/app/components/routes/authenticated/campaign/assessment/results.hbs
  orga/app/components/routes/authenticated/campaign/collective-results/tab.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/progression-gauge.scss
  orga/app/styles/globals/competences.scss
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/progression-gauge-test.js
  orga/tests/integration/components/routes/authenticated/campaign/assessment/results-test.js
  orga/tests/integration/components/routes/authenticated/campaign/collective-results/tab-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2814 [FEATURE] Ajout d'une page de détails des résultats thématique dans l'admin (PIX-2446)
  admin/app/components/badges/badge.hbs
  admin/app/components/target-profiles/badges.hbs
  admin/app/router.js
  admin/app/routes/authenticated/badges/badge.js
  admin/app/styles/app.scss
  admin/app/styles/components/badges/badge.scss
  admin/app/styles/components/target-profiles/badges.scss
  admin/app/templates/authenticated/badges.hbs
  admin/app/templates/authenticated/badges/badge.hbs
  admin/mirage/config.js
  admin/mirage/handlers/badges.js
  admin/tests/acceptance/authenticated/badges/badges-test.js
  admin/tests/acceptance/authenticated/target-profiles/insight-test.js
  admin/tests/integration/components/badges/badge-test.js
  admin/tests/integration/components/target-profiles/badges_test.js
  api/lib/application/badges/badges-controller.js
  api/lib/application/badges/index.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/get-badge.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/routes.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2815 [APP] Afficher le message d'une organisation à la fin d'un parcours (PIX-2328)
  api/db/database-builder/factory/build-campaign.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/read-models/CampaignToJoin.js
  api/lib/infrastructure/serializers/jsonapi/campaign-to-join-serializer.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-to-join-serializer_test.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/tests/acceptance/skill-review-page-test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review-test.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2788 [FEATURE] Afficher les méthodes de connexion d'un utilisateur sur Pix Admin (PIX-2425).
  admin/app/components/user-detail-personal-information.hbs
  admin/app/components/user-detail-personal-information.js
  admin/app/models/authentication-method.js
  admin/app/models/user.js
  admin/app/styles/components/user-detail-personal-information-section.scss
  admin/tests/integration/components/user-detail-personal-information-test.js
  admin/tests/unit/models/user-test.js
  api/db/seeds/data/users-builder.js
  api/lib/domain/models/UserDetailsForAdmin.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/acceptance/application/users/update-user-details-for-administration_test.js
  api/tests/acceptance/application/users/users-controller-dissociate-schooling-registrations_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-user-details-for-admin.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2800 [TECH] Montée de version des dépendances de Pix Admin (PR-XXX).
  admin/package-lock.json
  admin/package.json
Labels: :rocket: Ready to Merge, cross-team

#2825 [BUGFIX] Le mésusage de la DomainTransaction provoque des deadlocks dans le flux de complétion d'asssessment (PIX-2457)
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/events/handle-badge-acquisition.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/events/handle-partner-certification.js
  api/lib/domain/usecases/complete-assessment.js
  api/lib/infrastructure/repositories/assessment-result-repository.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/repositories/competence-mark-repository.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/domain/events/handle-badge-acquisition_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/events/handle-partner-certification_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
Labels: :rocket: Ready to Merge, :steam_locomotive: EXPEDIT, Func Review OK, Tech Review OK

#2799 [FEATURE] renvoyer la derniere certification pour le livret scolaire (pix-2421)
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/tests/acceptance/application/certifications-livret-scolaire/certification-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certifications-results-for-ls.js
Labels: :rocket: Ready to Merge, team-certif

#2821 [FEATURE] Afficher le bouton personnalisé dans la page de fin de parcours (Pix-2327)
  api/db/seeds/data/campaigns-builder.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/templates/components/campaign-share-button.hbs
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review-test.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2823 [BUGFIX] Affichage de la bonne identité dans le détail d'un participant à une campagne de collecte de profils (PIX-2427).
  api/lib/infrastructure/repositories/campaign-profile-repository.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2806 [FEATURE] Restreindre l'accès d'un utilisateur anonyme lors d'une campagne à accès simplifiée (Pix-2363).
  mon-pix/app/routes/application.js
  mon-pix/tests/acceptance/logout-anonymous-user-when-access-to-not-allowed-pages_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2807 [FEATURE] Supprimer une méthode de connexion d'un utilisateur dans Pix Admin (PIX-2103).
  admin/app/adapters/user.js
  admin/app/components/user-detail-personal-information.hbs
  admin/app/components/user-detail-personal-information.js
  admin/app/controllers/authenticated/users/get.js
  admin/app/models/user.js
  admin/app/routes/authenticated/users/get.js
  admin/app/styles/components/user-detail-personal-information-section.scss
  admin/app/styles/misc/global.scss
  admin/app/styles/misc/page.scss
  admin/app/templates/authenticated/users/get.hbs
  admin/config/environment.js
  admin/mirage/config.js
  admin/tests/acceptance/user-details-personal-information-test.js
  admin/tests/integration/components/user-detail-personal-information-test.js
  admin/tests/unit/adapters/user-test.js
  admin/tests/unit/models/user-test.js
  api/lib/application/error-manager.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/remove-authentication-method.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/tests/acceptance/application/users/users-controller-remove-authentication-method_test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/domain/usecases/remove-authentication-method_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2822 [FEATURE] Affichage de l'information certifiable sur les badges dans l'admin
  admin/app/components/badges/badge.hbs
  admin/app/components/badges/badge.js
  admin/app/models/badge.js
  admin/app/styles/components/badges/badge.scss
  admin/app/templates/authenticated/badges/badge.hbs
  admin/tests/integration/components/badges/badge-test.js
  admin/tests/unit/components/badges/badge-test.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2827 [FEATURE] Corriger l'affichage mobile de la page "Mon Compte" sur Pix App (PIX-2319).
  mon-pix/app/components/signin-form.js
  mon-pix/app/styles/components/_user-account-panel.scss
  mon-pix/app/styles/components/_user-account-update-email.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/user-account-panel.hbs
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
  mon-pix/tests/integration/components/signin-form-test.js
  mon-pix/tests/integration/components/user-account-panel-test.js
Labels: :rocket: Ready to Merge, team-acces

#2829 [FEATURE] Permettre la modification de l'identifiant d'un utilisateur dans Pix Admin (PIX-2102).
  admin/app/components/user-detail-personal-information.hbs
  admin/app/components/user-detail-personal-information.js
  admin/mirage/config.js
  admin/tests/acceptance/user-details-personal-information-test.js
  admin/tests/integration/components/user-detail-personal-information-test.js
  api/lib/application/users/index.js
  api/lib/domain/usecases/update-user-details-for-administration.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/acceptance/application/users/update-user-details-for-administration_test.js
  api/tests/unit/domain/usecases/update-user-details-for-administration_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2715 [TECH] Créer un repository pour l'affichage des résultats à une campagne d'évaluation d'un participant (PIX-2390).
  api/lib/application/campaign-participation-results/campaign-participation-result-controller.js
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/read-models/participant-results/BadgeResult.js
  api/lib/domain/read-models/participant-results/CompetenceResult.js
  api/lib/domain/read-models/participant-results/PartnerCompetenceResult.js
  api/lib/domain/read-models/participant-results/ReachedStage.js
  api/lib/domain/usecases/get-campaign-participation-result.js
  api/lib/domain/usecases/get-participant-result.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/unit/application/campaignParticipationResult/campaign-participation-result_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/read-models/participant-results/BadgeResult_test.js
  api/tests/unit/domain/read-models/participant-results/CompetenceResult_test.js
  api/tests/unit/domain/read-models/participant-results/PartnerCompetenceResult_test.js
  api/tests/unit/domain/read-models/participant-results/ReachedStage_test.js
  api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
  api/tests/unit/domain/usecases/get-participant-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2824 [FEATURE] Autoriser l'affichage du MarkDown sur le message de description en fin de parcours (PIX-2331).
  api/db/seeds/data/campaigns-builder.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2838 [BUGFIX] Amélioration des erreurs lors d'un appel Pôle emploi avec Axios (PIX-2460).
  api/lib/infrastructure/http/http-agent.js
  api/tests/unit/infrastructure/http/http-agent_test.js
Labels: :rocket: Ready to Merge, team-acces, team-prescription

#2828 [INFRA] Renommage de deux méthodes statiques pour les faire ressembler aux autres
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/models/AssessmentResult.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
Labels: :rocket: Ready to Merge, cross-team, team-certif

#2839 Mise à jour de wording
  admin/app/components/target-profiles/badges.hbs
  admin/app/components/target-profiles/stages.hbs
  admin/tests/integration/components/target-profiles/badges_test.js
  admin/tests/integration/components/target-profiles/stages_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2833 [FEATURE] À la fin de l'url donnée par l'organisation, ajouter le seuil du palier atteint par le participant (Pix-2329)
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review-test.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2836 [FEATURE] Affiche les critères d'un résultat thématique dans Pix Admin.
  admin/app/app.js
  admin/app/components/badges/badge.hbs
  admin/app/models/badge-criterion.js
  admin/app/models/badge.js
  admin/mirage/serializers/application.js
  admin/mirage/serializers/badge.js
  admin/tests/acceptance/authenticated/badges/badges-test.js
  admin/tests/integration/components/badges/badge-test.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2826 [FEATURE] Création de liens d'évitements (PIX-1862).
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/skiplink.hbs
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_skip-link.scss
  mon-pix/app/templates/campaigns/assessment/tutorial.hbs
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/competences/details.hbs
  mon-pix/app/templates/competences/results.hbs
  mon-pix/app/templates/components/certification-joiner.hbs
  mon-pix/app/templates/components/certification-starter.hbs
  mon-pix/app/templates/components/footer.hbs
  mon-pix/app/templates/components/navbar-header.hbs
  mon-pix/app/templates/components/profile-content.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/app/templates/fill-in-certificate-verification-code.hbs
  mon-pix/app/templates/user-account.hbs
  mon-pix/app/templates/user-certifications/index.hbs
  mon-pix/app/templates/user-tests.hbs
  mon-pix/app/templates/user-tutorials.hbs
  mon-pix/tests/integration/components/navbar-header-test.js
  mon-pix/tests/integration/components/skiplink-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, cross-team, team-evaluation

#2813 [TECH] Montée de version des dépendances de Pix Orga (PIX-2468)
  orga/package-lock.json
  orga/package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2796 [CLEANUP] Glimmerizer SignupForm (PIX-2452).
  mon-pix/app/components/signup-form.js
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/tests/integration/components/signup-form-test.js
  mon-pix/tests/unit/components/signup-form-test.js
Labels: :rocket: Ready to Merge, cross-team

#2851 [TECH] Rendre l'email à utiliser pour les notifications JIRA explicite (PIX-2472).
  sample.env
  scripts/jira/comment-with-review-app-url.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2834 [FEATURE] Ajout de nouveaux champs à la bdd pour permettre des participations multiples à la même campagne (PIX-2445).
  api/db/migrations/20210413170121_add-column-envoisMultiples-to-campaigns-and-add-isImproved-to-campaign-participations-and-update-constraint-campaign-participations-unique-userId-campaignId-isImproved.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2853 [TECH] Améliorer les index sur les requêtes par email sur password-reset-demands et users (PIX-2474).
  api/db/migrations/20210414154016_add-index-on-lower-email-column-table-users.js
  api/db/migrations/20210414161434_add-index-lower-email-reset-password.js
  api/lib/infrastructure/repositories/reset-password-demands-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/infrastructure/repositories/reset-password-demands-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2820 [FEATURE] Afficher la liste des épreuves posées en certif sur l'onglet "Neutralisation" (PIX-2358)
  admin/app/models/certification-details.js
  admin/app/routes/authenticated/certifications/certification/neutralization.js
  admin/app/templates/authenticated/certifications/certification/neutralization.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/certifications/certification/neutralization-test.js
  admin/tests/unit/models/certification-details-test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-certif

#2842 [FEATURE] Affiche les badgePartnerCompetences dans les critéres du badge
  admin/app/components/badges/badge.hbs
  admin/app/models/badge-criterion.js
  admin/app/models/badge-partner-competence.js
  admin/app/models/badge.js
  admin/mirage/handlers/badges.js
  admin/mirage/serializers/badge.js
  admin/tests/acceptance/authenticated/badges/badges-test.js
  api/db/seeds/data/badges-builder.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-badge.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#2835 [A11Y] Corrections d'accessibilité sur la page de connexion et d'inscription (PIX-2461).
  mon-pix/app/styles/components/_footer.scss
  mon-pix/app/styles/components/_form-textfield.scss
  mon-pix/app/styles/components/_signup-form.scss
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/components/footer.hbs
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/app/templates/components/signin-form.hbs
  mon-pix/app/templates/components/signup-form.hbs
  mon-pix/public/images/icons/icon-success.svg
  mon-pix/tests/acceptance/footer-test.js
  mon-pix/tests/acceptance/inscription-page-test.js
  mon-pix/tests/integration/components/signup-form-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, cross-team, team-acces, team-evaluation

#2857 [FEATURE] Générer les identifiants via les informations de l'élève présent en base sur la double mire Pix App (PIX-1785).
  api/lib/domain/usecases/generate-username.js
  api/tests/unit/domain/usecases/generate-username-test.js
Labels: :rocket: Ready to Merge, team-acces

#2860 [FEATURE] Ajouter une documentation pour orga.pix.org (PIX-2477).
  orga/app/components/sidebar-menu.js
  orga/tests/acceptance/authentication-test.js
  orga/tests/integration/components/sidebar-menu-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2840 [FEATURE] Ajouter les params externalId et masteryPercentage à l'url donnée par une orga (PIX-2440).
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review-test.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2841 [FEATURE] Ajout de la section "Compétences à retenter" sur le TDB (PIX-2263).
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/dashboard/content.js
  mon-pix/app/models/scorecard.js
  mon-pix/tests/acceptance/user-dashboard-test.js
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/tests/unit/components/dashboard/content-test.js
  mon-pix/tests/unit/models/scorecard-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2865 [SR] Supprimer les .get et .set dans les tests unitaires des models de Pix-App.
  mon-pix/tests/unit/models/answer-test.js
  mon-pix/tests/unit/models/assessment-test.js
  mon-pix/tests/unit/models/campaign-participation-badge-test.js
  mon-pix/tests/unit/models/campaign-participation-result-test.js
  mon-pix/tests/unit/models/challenge-test.js
  mon-pix/tests/unit/models/competence-result-test.js
  mon-pix/tests/unit/models/correction-test.js
  mon-pix/tests/unit/models/profile-test.js
  mon-pix/tests/unit/models/progression-test.js
  mon-pix/tests/unit/models/scorecard-test.js
  mon-pix/tests/unit/models/shared-profile-for-campaign-test.js
  mon-pix/tests/unit/models/user-test.js
Labels: :rocket: Ready to Merge, cross-team, team-evaluation

#2817 [CLEANUP] Refacto du proposal as block pour mieux afficher les blocs avec du markdown (PIX-2438).
  mon-pix/app/components/qroc-proposal.js
  mon-pix/app/components/qrocm-proposal.js
  mon-pix/app/styles/components/_qrocm-proposals.scss
  mon-pix/app/styles/components/_qrocm-solution-panel.scss
  mon-pix/app/templates/components/qrocm-proposal.hbs
  mon-pix/app/utils/proposals-as-blocks.js
  mon-pix/tests/acceptance/challenge-qrocm-test.js
  mon-pix/tests/acceptance/user-dashboard-test.js
  mon-pix/tests/integration/components/qrocm-proposal-test.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel-test.js
  mon-pix/tests/unit/components/qrocm-ind-solution-panel-test.js
  mon-pix/tests/unit/utils/proposals-as-blocks-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#2843 [TECH] Améliorer l'authentification dans l'API (PIX-2475).
  api/lib/infrastructure/authentication.js
  api/lib/infrastructure/security.js
  api/lib/swaggers.js
  api/server.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/tooling/http-test-server_test.js
Labels: Tech Review OK, cross-team, team-acces

#2856 [FEATURE] Affichage d'un sous menu dans la page Mon compte (PIX-2055).
  mon-pix/app/components/user-account-connexion-methods.js
  mon-pix/app/components/user-account-panel.js
  mon-pix/app/controllers/user-account.js
  mon-pix/app/controllers/user-account/connection-methods.js
  mon-pix/app/controllers/user-account/language.js
  mon-pix/app/router.js
  mon-pix/app/routes/user-account/connection-methods.js
  mon-pix/app/routes/user-account/index.js
  mon-pix/app/routes/user-account/language.js
  mon-pix/app/routes/user-account/personal-information.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_form-textfield.scss
  mon-pix/app/styles/components/_user-account-panel.scss
  mon-pix/app/styles/components/_user-account.scss
  mon-pix/app/styles/pages/_connexion-methods.scss
  mon-pix/app/styles/pages/_language.scss
  mon-pix/app/styles/pages/_personal-information.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/app/templates/components/user-account-connexion-methods.hbs
  mon-pix/app/templates/components/user-account-panel.hbs
  mon-pix/app/templates/components/user-account-update-email.hbs
  mon-pix/app/templates/user-account.hbs
  mon-pix/app/templates/user-account/connection-methods.hbs
  mon-pix/app/templates/user-account/language.hbs
  mon-pix/app/templates/user-account/personal-information.hbs
  mon-pix/config/icons.js
  mon-pix/tests/acceptance/personal-information-test.js
  mon-pix/tests/acceptance/user-account-test.js
  mon-pix/tests/acceptance/user-logged-menu-test.js
  mon-pix/tests/integration/components/user-account-connexion-methods-test.js
  mon-pix/tests/integration/components/user-account-panel-test.js
  mon-pix/tests/unit/controllers/user-account-test.js
  mon-pix/tests/unit/controllers/user-account/connection-methods-test.js
  mon-pix/tests/unit/controllers/user-account/language-test.js
  mon-pix/tests/unit/routes/user-account/connection-methods-test.js
  mon-pix/tests/unit/routes/user-account/language-test.js
  mon-pix/tests/unit/routes/user-account/personal-information-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2866 [BUGFIX] Correctif d'alignement entre le bouton radio et la phrase dans les QCM (PIX-2427).
  mon-pix/app/styles/components/_qcm-solution-panel.scss
Labels: :rocket: Ready to Merge, team-evaluation

#2869 [BUGFIX] Corrige la récupération des badges
  api/.eslintrc.yaml
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2830 [FEATURE] L'arrondi à l'entier supérieur n'est pas correct pour filtrer les participants dans pixOrga (PIX-2456).
  api/lib/domain/models/Stage.js
  api/tests/unit/domain/models/Stage_test.js
  api/tests/unit/domain/models/TargetProfileWithLearningContent_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2861 [TECH] Introduire un modèle dédié à la réinitialisation de mot de passe (PIX-2274).
  api/lib/application/passwords/password-controller.js
  mon-pix/app/adapters/reset-expired-password-demand.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/models/reset-expired-password-demand.js
  mon-pix/app/routes/login.js
  mon-pix/app/routes/update-expired-password.js
  mon-pix/app/templates/update-expired-password.hbs
  mon-pix/mirage/factories/reset-expired-password-demand.js
  mon-pix/mirage/routes/post-expired-password-updates.js
  mon-pix/tests/integration/components/update-expired-password-form-test.js
  mon-pix/tests/unit/adapters/reset-expired-password-demand-test.js
  mon-pix/tests/unit/adapters/user-test.js
  mon-pix/tests/unit/components/update-expired-password_test.js
  mon-pix/tests/unit/routes/login-test.js
  mon-pix/tests/unit/routes/update-expired-password-test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2863 [TECH] Retenir pour la certification de quel badge certifiable une épreuve est choisie lors du choix des épreuves de la création du test de certification (PIX-2485)
  api/db/database-builder/factory/build-certification-challenge.js
  api/db/migrations/20210416082943_add-column-certifiable-badge-key-to-certification-challenges-table.js
  api/lib/domain/models/BadgeAcquisition.js
  api/lib/domain/models/CertificationChallenge.js
  api/lib/domain/services/certifiable-badges.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/certification-challenge-repository.js
  api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-badge-acquisition.js
  api/tests/tooling/domain-builder/factory/build-certification-challenge.js
  api/tests/unit/domain/models/BadgeAcquisition_test.js
  api/tests/unit/domain/models/CertificationChallenge_test.js
  api/tests/unit/domain/services/certifiable-badges_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2875 [BUGFIX][i18n] Modification du terme "En attente" afin de le rendre plus compréhensible par le prescripteur (Pix-2486)
  orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
  orga/tests/integration/components/routes/authenticated/campaign/profile/list-test.js
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2862 [FEATURE] Afficher la dernière participation à la campagne dans le cas d'une campagne à envois multiples (Pix-2463).
  api/db/database-builder/factory/build-campaign-participation.js
  api/db/database-builder/factory/build-campaign.js
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2867 [FEATURE] Résilience Pôle emploi - Ajout d'un script de création a posteriori des pole-emploi-sendings (Pix-2483).
  api/db/database-builder/factory/build-pole-emploi-sending.js
  api/db/database-builder/factory/index.js
  api/scripts/prod/compute-pole-emploi-sendings.js
  api/tests/integration/infrastructure/repositories/campaign-participation-result-repository_test.js
  api/tests/integration/scripts/prod/compute-pole-emploi-sendings_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2819 [FEATURE] Mise en place du calcul d'obtention des certifications Pix+ à l'issue d'un test de certification (PIX-2371)
  api/lib/domain/events/CertificationScoringCompleted.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/events/handle-pix-plus-certification.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/CertificationChallenge.js
  api/lib/domain/models/PartnerCertification.js
  api/lib/domain/models/PixPlusCertification.js
  api/lib/domain/models/ReproducibilityRate.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/usecases/get-certification-details.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-scoring-completed-event.js
  api/tests/tooling/domain-builder/factory/build-pix-plus-certification.js
  api/tests/tooling/domain-builder/factory/build-reproducibility-rate.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/events/handle-pix-plus-certification_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/CertificationChallenge_test.js
  api/tests/unit/domain/models/PixPlusCertification_test.js
  api/tests/unit/domain/models/ReproducibilityRate_test.js
  api/tests/unit/domain/services/certification/certification-service_test.js
  api/tests/unit/domain/usecases/get-certification-details_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2876 [BUGFIX] Serialise tout les badgeParnerCompetences dans le critère lorsque son scope est EveryPartnerCompetence
  api/db/seeds/data/badges-builder.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2636 [CLEANUP] Glimmerizer les FormTextfields (PIX-2272).
  mon-pix/app/components/form-textfield-date.js
  mon-pix/app/components/form-textfield.js
  mon-pix/app/styles/components/_form-textfield.scss
  mon-pix/app/templates/components/form-textfield-date.hbs
  mon-pix/app/templates/components/form-textfield.hbs
  mon-pix/app/templates/components/password-reset-demand-form.hbs
  mon-pix/app/templates/components/update-expired-password-form.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/form-textfield-date-test.js
  mon-pix/tests/integration/components/form-textfield-test.js
  mon-pix/tests/integration/components/routes/register-form-test.js
  mon-pix/tests/integration/components/signup-form-test.js
  mon-pix/tests/integration/components/user-account-update-email-test.js
  mon-pix/tests/unit/components/form-textfield-date-test.js
  mon-pix/tests/unit/components/form-textfield-test.js
Labels: :rocket: Ready to Merge, cross-team

#2879 [BUGFIX] Calcul du résultat de certification : compter le nombre d'épreuves proposées (PIX-2493)
  api/lib/domain/models/CertifiedLevel.js
  api/lib/domain/models/CompetenceAnswerCollectionForScoring.js
  api/lib/domain/services/certification-result-service.js
  api/tests/unit/domain/models/CertifiedLevel_test.js
  api/tests/unit/domain/models/CompetenceAnswerCollectionForScoring_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2870 [FEATURE] Correction de l'affichage dans le burger menu sur Pix App (PIX-2469).
  mon-pix/app/styles/components/_navbar-burger-menu.scss
  mon-pix/app/templates/components/navbar-burger-menu.hbs
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
Labels: :rocket: Ready to Merge, team-acces

#2882 [BUGFIX] Valider le paramètre filter[id] de la route GET /api/organizations (PIX-2497).
  api/lib/application/organizations/index.js
  api/lib/domain/types/identifiers-type.js
  api/tests/unit/application/organizations/index_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2877 [BUGFIX] Correction des conditions d'affichage du bandeau sur l'adresse email du destinataire des résultats (PIX-2491)
  api/db/seeds/data/certification/certification-center-memberships-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
  certif/app/controllers/authenticated/sessions/list.js
  certif/tests/acceptance/session-list-test.js
  certif/tests/helpers/test-init.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2864 [FEATURE] Traduction anglaises depuis PO Editor - Avril 2021.
  api/lib/domain/services/mail-service.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/translations/en.json
  mon-pix/translations/en.json
  orga/translations/en.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#2886 [BUGFIX] Gérer les QROCM avec des clés d'input à une lettre (PIX-2502).
  mon-pix/app/utils/proposals-as-blocks.js
  mon-pix/tests/unit/utils/proposals-as-blocks-test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2846 [DOC] Proposition d'ADR pour séparer Domain Transactions et Domain Events
  docs/adr/0009-transaction-metier.md
  docs/adr/0010-propager-domain-events-via-event-dispatcher.md
  docs/adr/0023-précision-sur-les-transactions-et-les-événements-métier.md
Labels: :rocket: Ready to Merge, cross-team

#2889 [FEATURE] Modifier la bannière Pix certif pour la reprogrammation de sessions du SCO (PIX-2500)
  certif/app/styles/globals/colors.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/templates/authenticated.hbs
  certif/tests/acceptance/authenticated-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2837 [FEATURE] Ajouter un statut Annulé aux certifications
  api/db/database-builder/factory/build-certification-course.js
  api/db/migrations/20210420154410_add-column-isCancelled-to-certification-course.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-course.js
  api/tests/tooling/domain-builder/factory/build-certifications-results-for-ls.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2887 [FEATURE] Toujours renvoyer un niveau de competence positif pour le livret scolaire
  api/lib/domain/read-models/livret-scolaire/Certificate.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2881 [FEATURE] Ajout la possibilité de filtrer une liste d’étudiants SUP par numéro étudiant (PIX-2417).
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  orga/app/components/edit-student-number-modal.hbs
  orga/app/components/routes/authenticated/sup-students/list-items.hbs
  orga/app/controllers/authenticated/sup-students/list.js
  orga/app/routes/authenticated/sup-students/list.js
  orga/app/templates/authenticated/sup-students/list.hbs
  orga/tests/acceptance/sup-student-list-test.js
  orga/tests/integration/components/edit-student-number-modal-test.js
  orga/tests/integration/components/routes/authenticated/sup-students/list-items-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2894 [FEATURE] Afficher les tags de chaque organisation sur Pix Admin (PIX-197).
  admin/app/components/organization-information-section.hbs
  admin/app/models/organization.js
  admin/app/models/tag.js
  admin/app/styles/authenticated/organizations/get.scss
  admin/tests/integration/components/organization-information-section-test.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#2888 [ADMIN] Supprimer les boutons “Récupérer le fichier avant jury” et “Exporter les résultats” de la page session dans Pix Admin (PIX-2495)
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/services/csv-service.js
  admin/app/services/file-saver.js
  admin/app/services/session-info-service.js
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js
  admin/tests/acceptance/session-test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.js
  admin/tests/unit/controllers/authenticated/sessions/session/informations-test.js
  admin/tests/unit/services/csv-service-test.js
  admin/tests/unit/services/file-saver-test.js
  admin/tests/unit/services/session-info-service-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/tests/acceptance/application/session/session-controller-get-session-results_test.js
  api/tests/unit/application/session/session-controller_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2874 [FEATURE] Neutralisation d'épreuves depuis Pix-Admin (Pix-2359)
  admin/app/adapters/certification-details.js
  admin/app/components/certification/certification-details-answer.js
  admin/app/controllers/authenticated/certifications/certification/neutralization.js
  admin/app/models/certification-details.js
  admin/app/styles/app.scss
  admin/app/styles/authenticated/certifications/certification/neutralization.scss
  admin/app/templates/authenticated/certifications/certification.hbs
  admin/app/templates/authenticated/certifications/certification/neutralization.hbs
  admin/tests/integration/components/certification/certification-details-answer-test.js
  admin/tests/unit/adapters/certification-details-test.js
  admin/tests/unit/controllers/authenticated/certifications/certification/neutralization-test.js
  admin/tests/unit/models/certification-details-test.js
  api/lib/application/assessment-results/assessment-result-controller.js
  api/lib/application/assessment-results/index.js
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/domain/events/handle-certification-rescoring.js
  api/lib/domain/events/handle-pix-plus-certifications-scoring.js
  api/lib/domain/models/AnswerCollectionForScoring.js
  api/lib/domain/models/CompetenceAnswerCollectionForScoring.js
  api/lib/domain/models/ReproducibilityRate.js
  api/lib/domain/read-models/CertificationDetails.js
  api/lib/domain/services/certification-result-service.js
  api/lib/domain/usecases/neutralize-challenge.js
  api/tests/unit/application/assessment-results/assessment-result-controller_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/application/certifications/index_test.js
  api/tests/unit/domain/events/handle-certification-rescoring_test.js
  api/tests/unit/domain/models/AnswerCollectionForScoring_test.js
  api/tests/unit/domain/models/CompetenceAnswerCollectionForScoring_test.js
  api/tests/unit/domain/models/ReproducibilityRate_test.js
  api/tests/unit/domain/services/certification/certification-result-service_test.js
  api/tests/unit/domain/usecases/neutralize-challenge_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2885 [FEATURE] Ajouter les mentions concernant les certifications Pix+ Droit dans les csv de résultats de certification (PIX-2443)
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/models/CleaCertificationResult.js
  api/lib/domain/models/PixPlusDroitExpertCertificationResult.js
  api/lib/domain/models/PixPlusDroitMaitreCertificationResult.js
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/repositories/clea-certification-result-repository.js
  api/lib/infrastructure/repositories/pix-plus-droit-expert-certification-result-repository.js
  api/lib/infrastructure/repositories/pix-plus-droit-maitre-certification-result-repository.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/integration/infrastructure/repositories/clea-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/pix-plus-droit-expert-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/pix-plus-droit-maitre-certification-result-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/tooling/domain-builder/factory/build-certification-result.js
  api/tests/tooling/domain-builder/factory/build-clea-certification-result.js
  api/tests/tooling/domain-builder/factory/build-pix-plus-droit-certification-result.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/CertificationResult_test.js
  api/tests/unit/domain/models/CleaCertificationResult_test.js
  api/tests/unit/domain/models/PixPlusDroitExpertCertificationResult_test.js
  api/tests/unit/domain/models/PixPlusDroitMaitreCertificationResult_test.js
  api/tests/unit/domain/usecases/get-session-results_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2883 [FEATURE] Autoriser l'envoi multiple pour une campagne de collecte de profils (Pix-2466).
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/campaigns-builder.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2898 [BUGFIX] L'affichage du score dans la page de détails d'une certification sur PixAdmin pouvait être erroné (PIX-2507)
  api/lib/infrastructure/repositories/competence-mark-repository.js
  api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2878 [DOC] Expliciter la description des pull requests.
  docs/CONTRIBUTING.md
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2868 [TECH] Expliciter la stratégie de test du routeur dans les tests API.
  api/server.js
  api/tests/integration/application/.eslintrc.js
  api/tests/integration/application/authentication/index_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/tooling/server/http-test-server.js
  api/tests/unit/tooling/http-test-server_test.js
  docs/adr/0024-tester-routeur-api.md
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team, team-acces

#2890 [REFACTO] Calculer le résultat d'un résultat thématique en dehors d'une campagne (PIX-2488).
  api/lib/domain/events/handle-badge-acquisition.js
  api/lib/domain/services/badge-criteria-service.js
  api/tests/unit/domain/events/handle-badge-acquisition_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#2904 [FEATURE] Changer la page de maintenance (PIX-2515).
  certif/maintenance_page.html
  mon-pix/maintenance_page.html
  orga/maintenance_page.html
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2903 [BUGFIX] Supprimer le compteur de participations sur la page d'accueil de Pix Orga
  api/lib/domain/read-models/CampaignReport.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
  orga/app/components/routes/authenticated/campaign/list.hbs
  orga/tests/integration/components/routes/authenticated/campaign/list-test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2905 [BUGFIX] Suppression du join sur les campagnes participation
  api/lib/infrastructure/repositories/campaign-report-repository.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2812 [TECH] Montée de version des dépendances de Pix Certif (PIX-XXX).
  certif/package-lock.json
  certif/package.json
Labels: :rocket: Ready to Merge, cross-team

#2907 Mise à jour du changelog des hotfixes
  CHANGELOG.md
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2908 [TECH] Ajouter un index sur campaignID dans la table campaign-participations.
  api/db/migrations/20210427100545_add_indexes_on_table_campaign-participations.js
Labels: :rocket: Ready to Merge, cross-team

#2892 [FEATURE] Affichage des certifications complémentaires dans la liste des certifications sur PixAdmin (PIX-2373)
  admin/app/components/certification/certification-info-field.hbs
  admin/app/components/certification/certification-list.js
  admin/app/models/jury-certification-summary.js
  admin/tests/integration/components/certification/certification-list-test.js
  admin/tests/unit/models/jury-certification-summary-test.js
  api/lib/domain/read-models/JuryCertificationSummary.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-certification-summary-serializer.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-certification-summary-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2899 [FEATURE] Permettre de recommencer un parcours dont les résultats ont été partagés (Pix-2464)
  api/db/database-builder/factory/build-campaign-participation.js
  api/db/database-builder/factory/build-campaign.js
  api/lib/domain/models/index.js
  api/lib/domain/read-models/CampaignToJoin.js
  api/lib/domain/services/improvement-service.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-to-join-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-to-join-serializer.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-to-join-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-to-join.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-to-join-serializer_test.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review-test.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2893 [FEATURE] Simplifier le formulaire de réconciliation SUP (PIX-2415)
  api/lib/application/schooling-registration-user-associations/index.js
  api/lib/domain/usecases/reconcile-higher-schooling-registration.js
  api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
  api/tests/acceptance/application/schooling-registration-user-association-controller_test.js
  api/tests/integration/application/schooling-registration-user-associations/index_test.js
  api/tests/integration/domain/usecases/reconcile-higher-schooling-registration_test.js
  api/tests/integration/infrastructure/repositories/higher-schooling-registration-repository_test.js
  mon-pix/app/adapters/schooling-registration-user-association.js
  mon-pix/app/components/routes/campaigns/restricted/join-sup.hbs
  mon-pix/app/components/routes/campaigns/restricted/join-sup.js
  mon-pix/app/components/routes/campaigns/restricted/user-information-form.hbs
  mon-pix/mirage/routes/schooling-registration-user-associations/index.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/helpers/fill-in-by-label.js
  mon-pix/tests/integration/components/routes/campaigns/restricted/join-sup-test.js
  mon-pix/tests/unit/adapters/schooling-registration-user-association-test.js
  mon-pix/tests/unit/components/routes/campaigns/restricted/join-sup-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2854 [TECH] Lancer les tests end to end en 1 commande
  high-level-tests/e2e/Dockerfile
  high-level-tests/e2e/README.md
  high-level-tests/e2e/docker-compose.yml
  high-level-tests/e2e/env-api
  scripts/tests-e2e
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, cross-team

#2916 [TECH] Ne pas remonter d'erreur lorsqu'aucun ticket Jira ne correspond à la PR.
  .github/workflows/on-dev-merge.yml
Labels: :eyes: Tech Review Needed, cross-team

#2915 [BUGFIX] Ne change pas le focus de la modal a chaque rendu (PIX-2521)
  mon-pix/app/components/pix-modal.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#2891 [TECH] Généraliser l'encapsulation des appels http sortant de l'API.
  api/lib/.eslintrc.js
  api/lib/domain/services/authentication-service.js
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/lib/infrastructure/http/http-agent.js
  api/lib/infrastructure/lcms.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
  api/tests/unit/infrastructure/http/http-agent_test.js
  docs/adr/0023-encapsuler-appel-http.md
Labels: :eyes: Tech Review Needed, cross-team

#2873 [FEATURE] Afficher toutes les campagnes d'une organisation dans Pix Admin (PIX-2251).
  admin/app/adapters/campaign.js
  admin/app/components/organization-campaigns-section.hbs
  admin/app/models/campaign.js
  admin/app/router.js
  admin/app/routes/authenticated/organizations/get/campaigns.js
  admin/app/styles/misc/tables.scss
  admin/app/templates/authenticated/organizations/get.hbs
  admin/app/templates/authenticated/organizations/get/campaigns.hbs
  admin/tests/integration/components/organization-campaigns-section-test.js
  admin/tests/unit/adapters/campaign-test.js
  api/db/seeds/data/campaigns-builder.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/read-models/CampaignManagement.js
  api/lib/domain/usecases/find-paginated-campaign-managements.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/campaign-management-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-management-serializer.js
  api/tests/integration/infrastructure/repositories/campaign-management-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-management.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-campaign-managments_test .js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-management-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription

#2914 [FEATURE] Afficher les groupes d'acquis nécessaires pour obtenir un résultat thématique dans l'admin (PIX-2364)
  admin/app/components/badges/badge.hbs
  admin/app/components/badges/badge.js
  admin/app/components/target-profiles/badges.hbs
  admin/app/models/badge-partner-competence.js
  admin/app/models/skill.js
  admin/app/models/tube.js
  admin/app/styles/components/badges/badge.scss
  admin/mirage/handlers/badges.js
  admin/mirage/serializers/application.js
  admin/tests/acceptance/authenticated/badges/badges_test.js
  admin/tests/helpers/contains.js
  admin/tests/integration/components/badges/badge_test.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/application/badges/badges-controller.js
  api/lib/domain/models/BadgeWithLearningContent.js
  api/lib/domain/usecases/get-badge-details.js
  api/lib/domain/usecases/get-badge.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/tooling/domain-builder/factory/build-badge-with-learning-content.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/usecases/get-badge-details_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation

#2871 [BUGFIX] Gérer les erreurs produites lors d'un appel POST /api/pole-emploi/token (PIX-2490).
  api/lib/application/error-manager.js
  api/lib/application/http-errors.js
  api/lib/domain/errors.js
  api/lib/domain/services/authentication-service.js
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/lib/infrastructure/http/http-agent.js
  api/tests/acceptance/application/authentication-controller_test.js
  api/tests/unit/domain/services/authentication-service_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
  api/tests/unit/infrastructure/http/http-agent_test.js
  mon-pix/app/routes/login-pe.js
Labels: :rocket: Ready to Merge, team-acces, team-prescription

#2909 [FEATURE] Modifier les catégories de signalement (PIX-2484).
  admin/app/models/certification-issue-report.js
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportCategory.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  certif/app/components/issue-report-modal/add-issue-report-modal.js
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.js
  certif/app/models/certification-issue-report.js
  certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#2912 [API] Récupérer la derniere certif non annulée pour le livret-scolaire (pix-2520)
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/db/seeds/data/certification/certification-courses-builder.js
  api/db/seeds/data/certification/certification-scores-builder.js
  api/db/seeds/data/certification/certification-sessions-builder.js
  api/db/seeds/data/certification/user-profiles-builder.js
  api/db/seeds/data/certification/users.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2872 [FEATURE] Donner accès à Pix Certif à l'administrateur SCO lors de la modification du rôle dans PixOrga (PIX-2454).
  api/lib/application/error-manager.js
  api/lib/application/memberships/membership-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/Membership.js
  api/lib/domain/usecases/update-membership.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/repositories/certification-center-repository.js
  api/lib/infrastructure/repositories/membership-repository.js
  api/tests/acceptance/application/membership-controller_test.js
  api/tests/integration/application/memberships/membership-controller_test.js
  api/tests/integration/domain/usecases/update-membership_test.js
  api/tests/integration/infrastructure/repositories/certification-center-repository_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/unit/domain/models/Membership_test.js
  api/tests/unit/domain/usecases/update-membership-attributes_test.js
  api/tests/unit/domain/usecases/update-membership_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-acces

#2913 [FEATURE] Afficher les mentions concernant les certifications complémentaires Pix+ Droit sur la page de détails d'une certification dans PixAdmin (PIX-2374)
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/models/certification.js
  admin/app/styles/authenticated/certifications/certification/informations.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/tests/unit/controllers/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/models/certification_test.js
  api/lib/domain/read-models/CertificationResultInformation.js
  api/lib/domain/usecases/get-certification-result-information.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/certification-result-information-serializer.js
  api/tests/unit/domain/read-models/CertificationResultInformation_test.js
  api/tests/unit/domain/usecases/getCertificationResultInformation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-result-information-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-certif

#2925 [BUGFIX] Valider le payload sur POST /api/users (PIX-2514).
  api/lib/application/users/index.js
  api/tests/unit/application/users/index_test.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge, team-acces

#2933 [BUGFIX] Corrige l'entrée des dates de naissance pour l'ajout des candidats de certif (PIX-2526)
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/certification-candidate-in-staging-item.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#2932 [FEATURE] Pouvoir repasser un parcours seulement après 4 jours (PIX-2465).
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/services/improvement-service.js
  api/lib/domain/services/smart-random/data-fetcher.js
  api/lib/domain/usecases/get-progression.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-to-join-repository.js
  api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/campaign-participation-result-controller_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/services/improvement-service_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/get-progression_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign-participation-result.js
  mon-pix/app/models/competence-result.js
  mon-pix/app/models/partner-competence-result.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/components/routes/campaigns/skill-review_test.js
  mon-pix/tests/unit/models/campaign-participation-result_test.js
  mon-pix/tests/unit/models/competence-result_test.js
  mon-pix/tests/unit/models/partner-competence-result_test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-prescription
