Repository 1024pix/pix, pull requests merged in 2022-04, with the labels that each got.

#4254 [TECH] Supprimer le feature toggle FT_VALIDATE_EMAIL (PIX-3532)
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/application/users/index.js
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/acceptance/application/users/send-verification-code-route-put_test.js
  api/tests/acceptance/application/users/update-user-email-with-validation-route-post_test.js
  api/tests/unit/application/users/index_test.js
  mon-pix/app/components/user-account/update-email.hbs
  mon-pix/app/components/user-account/update-email.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/templates/user-account/connection-methods.hbs
  mon-pix/tests/acceptance/user-account/connection-methods_test.js
  mon-pix/tests/integration/components/user-account/update-email_test.js
  mon-pix/tests/unit/services/feature-toggles_test.js
Labels: :eyes: Tech Review Needed, :eyes: Func Review Needed, team-acces

#4274 [TECH] Supprimer la route inutilisée qui met à jour l'adresse e-mail sans validation sur Pix App (PIX-4686).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/config.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-user-email.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/users/users-controller-patch-email_test.js
  api/tests/integration/application/users/index_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/update-user-email_test.js
  api/translations/en.json
  api/translations/fr.json
  mon-pix/app/adapters/user.js
  mon-pix/app/controllers/user-account/connection-methods.js
  mon-pix/mirage/routes/users/index.js
  mon-pix/tests/unit/adapters/user_test.js
Labels: :rocket: Ready to Merge, team-acces

#4265 [FEATURE] Modifier l'ordre d'affichage des signalements sur la page de finalisation de session (PIX-4676)
  certif/app/components/issue-report-modal/add-issue-report-modal.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4240 [TECH] Créer des ségrégations pour les usages de redis (PIX-4635)
  api/lib/domain/services/refresh-token-service.js
  api/lib/infrastructure/caches/DistributedCache.js
  api/lib/infrastructure/caches/RedisCache.js
  api/lib/infrastructure/repositories/pole-emploi-tokens-repository.js
  api/lib/infrastructure/repositories/user-email-repository.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/TemporaryStorage.js
  api/lib/infrastructure/utils/RedisClient.js
  api/lib/infrastructure/utils/redis-monitor.js
  api/tests/integration/infrastructure/repositories/user-email-repository_test.js
  api/tests/integration/infrastructure/utils/RedisClient_test.js
  api/tests/unit/domain/services/refresh-token-service_test.js
  api/tests/unit/infrastructure/temporary-storage/TemporaryStorage_test.js
Labels: :rocket: Ready to Merge, team-acces

#4236 [TECH] Ne pas logguer les usernames lors de la création d'un compte via la réconciliation (PIX-4630)
  api/lib/domain/models/UserToCreate.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/authenticate-anonymous-user.js
  api/lib/domain/usecases/create-and-reconcile-user-to-schooling-registration.js
  api/lib/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user.js
  api/lib/domain/usecases/create-user-from-pole-emploi.js
  api/lib/domain/usecases/create-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/repositories/user-to-create-repository.js
  api/tests/acceptance/application/schooling-registration-dependent-user-route_test.js
  api/tests/integration/application/users/index_test.js
  api/tests/integration/domain/services/user-service_test.js
  api/tests/integration/domain/usecases/create-and-reconcile-user-to-schooling-registration_test.js
  api/tests/integration/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/integration/infrastructure/repositories/user-to-create-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/UserToCreate_test.js
  api/tests/unit/domain/services/user-service_test.js
  api/tests/unit/domain/usecases/authenticate-anonymous-user_test.js
  api/tests/unit/domain/usecases/create-user-from-pole-emploi_test.js
  api/tests/unit/domain/usecases/create-user_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4235 [BUGFIX] Ne pas enregistrer des réponses focusedOut sur des épreuves non focused (PIX-4627)
  api/lib/domain/models/Examiner.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/domain/models/Examiner_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, team-evaluation

#4239 [BUGFIX] Mise à jour ou non du lastQuestionState de l'assessment en fonction du challengeId
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/assessments/index.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-last-question-state.js
  api/lib/infrastructure/repositories/assessment-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-update-last-challenge-state_test.js
  api/tests/acceptance/application/assessments/assessment-update-last-question-state_test.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/unit/domain/usecases/update-last-question-state_test.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/serializers/assessment.js
  mon-pix/tests/unit/adapters/assessment_test.js
  mon-pix/tests/unit/serializers/assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-evaluation, cross-team

#4244 [FEATURE] Voir un écran intermédiaire avant de débuter une épreuve focus, le retour (Pix-4623)
  mon-pix/app/components/certification-banner.hbs
  mon-pix/app/components/certification-starter.js
  mon-pix/app/components/progress-bar.hbs
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/services/focused-certification-challenges-manager.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_certification-banner.scss
  mon-pix/app/styles/components/_focused-certification-challenge-instructions.scss
  mon-pix/app/styles/components/_progress-bar.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/components/focused-certification-challenge-instructions.hbs
  mon-pix/public/images/icone-pix-focus-rounded.svg
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/tests/integration/components/certification-starter_test.js
  mon-pix/tests/unit/controllers/assessments/challenge_test.js
  mon-pix/tests/unit/services/focused-certification-challenges-manager_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4268 [TECH] Unifier la création des read-models `TutorialForUser`.
  api/lib/domain/usecases/find-paginated-recommended-tutorials.js
  api/lib/domain/usecases/find-paginated-saved-tutorials.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/tests/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/domain/usecases/find-paginated-recommended-tutorials_test.js
  api/tests/unit/domain/usecases/find-paginated-saved-tutorials_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4272 [FEATURE] Ne pas afficher les participations supprimées dans les résultats de campagnes (PIX-4575).
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-list-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4281 [TECH] Ajouter le support d'Internet Explorer dans Pix App, Pix Orga, Pix Certif et Pix Admin
  admin/config/targets.js
  certif/config/targets.js
  certif/package-lock.json
  mon-pix/config/targets.js
  mon-pix/package-lock.json
  orga/config/targets.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#4245 [FEATURE] Création de prescrits pour les anciennes participations des utilisateurs dissociés(PIX-4484)
  api/scripts/prod/create-old-organization-learners-for-dissociated-users.js
  api/tests/integration/scripts/prod/create-old-organization-learners-for-dissociated-users_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4275 [BUGFIX] Permettre la réconciliation si l'INE est vide (PIX-4685).
  api/lib/domain/usecases/reconcile-schooling-registration.js
  api/tests/unit/domain/usecases/reconcile-schooling-registration_test.js
Labels: :rocket: Ready to Merge, team-acces

#4286 [HOTFIX] Merge du Hotfix 3.193.2
  CHANGELOG.md
  admin/package-lock.json
  admin/package.json
  api/package-lock.json
  api/package.json
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4248 [FEATURE] Faire apparaitre les signalements de focus out sur la page de détails d'une certification sur Pix Admin (PIX-4405).
  api/lib/domain/models/CertificationIssueReport.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4278 [TECH] Conditionner l'execution des jobs JIRA à la présence de la variable JIRA_URL
  .github/workflows/jira-transition-to-dev-in-progress.yaml
  .github/workflows/jira-transition-to-review.yaml
  .github/workflows/on-dev-merge.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4283 [FEATURE] Mise à jour du texte de la bannière SCO dans PixCertif (PIX-4690)
  certif/app/templates/authenticated.hbs
  certif/tests/acceptance/authenticated_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4197 [TECH] Nettoyage des erreurs sur les fonctions vides.
  api/.eslintrc.yaml
  api/db/migrations/20180306151846_add_type_to_all_assessments.js
  api/db/migrations/20180306164441_remove-score-and-level-for-bugged-assessments.js
  api/db/migrations/20210430154711_trim-certification-candidates-first-name-and-last-name.js
  api/db/migrations/20210506112005_fill-missing-competence-id-values-in-table-competence-marks.js
  api/db/migrations/20210713145931_set-default-target-profile-image.js
  api/db/migrations/20210916120235_update-badges-imageUrl-to-url-with-pix-domain.js
  api/db/migrations/20211123133135_resole-existing-certification-issue-reports.js
  api/lib/infrastructure/caches/InMemoryCache.js
  api/tests/integration/domain/usecases/abort-certification-course_test.js
  api/tests/integration/infrastructure/utils/xml/siecle-file-streamer_test.js
  api/tests/unit/application/certification-candidates/certification-candidates-controller_test.js
  api/tests/unit/domain/models/CertificationIssueReportResolutionStrategies_test.js
  api/tests/unit/domain/services/token-service_test.js
  api/tests/unit/domain/usecases/get-campaign-by-code_test.js
  api/tests/unit/infrastructure/caches/Cache_test.js
  api/tests/unit/infrastructure/caches/RedisCache_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4270 [TECH] Renommage des database-builders et attributs de ceux-ci pour les appeler `organization-learners` (PIX-4610).
  api/db/database-builder/factory/build-account-recovery-demand.js
  api/db/database-builder/factory/build-assessment-from-participation.js
  api/db/database-builder/factory/build-campaign-participation-with-organization-learner.js
  api/db/database-builder/factory/build-campaign-participation.js
  api/db/database-builder/factory/build-certification-candidate.js
  api/db/database-builder/factory/build-organization-learner.js
  api/db/database-builder/factory/index.js
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/campaigns-pro-builder.js
  api/db/seeds/data/campaigns-sco-builder.js
  api/db/seeds/data/campaigns-sup-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/db/seeds/data/organizations-sup-builder.js
  api/tests/acceptance/application/account-recovery/account-recovery-route-get_test.js
  api/tests/acceptance/application/account-recovery/account-recovery-route_test.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
  api/tests/acceptance/application/organizations/organization-controller-replace-higher-schooling-registrations_test.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/acceptance/application/schooling-registration-dependent-user-route_test.js
  api/tests/acceptance/application/schooling-registration-user-association-controller_test.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/integration/domain/services/user-service_test.js
  api/tests/integration/domain/usecases/create-and-reconcile-user-to-schooling-registration_test.js
  api/tests/integration/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user_test.js
  api/tests/integration/domain/usecases/find-paginated-campaign-participant-activities_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/domain/usecases/get-user-details-for-admin_test.js
  api/tests/integration/domain/usecases/import-higher-schooling-registrations_test.js
  api/tests/integration/domain/usecases/reconcile-higher-schooling-registration_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/integration/domain/usecases/update-user-details-for-administration_test.js
  api/tests/integration/infrastructure/repositories/account-recovery-demand-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participant-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-info-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
  api/tests/integration/infrastructure/repositories/division-repository_test.js
  api/tests/integration/infrastructure/repositories/group-repository_test.js
  api/tests/integration/infrastructure/repositories/higher-schooling-registration-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/integration/infrastructure/repositories/participations-for-campaign-management-repository_test.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/integration/infrastructure/repositories/sco-certification-candidate-repository_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-for-attendance-sheet-repository_test.js
  api/tests/integration/infrastructure/repositories/student-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/integration/scripts/prod/create-old-organization-learners-for-dissociated-users_test.js
  api/tests/tooling/domain-builder/factory/build-certifications-results-for-ls.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#4276 [FEATURE] Afficher une seule fois un message d'avertissement lorsque plusieurs épreuves focus se suivent (PIX-4617)
  mon-pix/.eslintrc.js
  mon-pix/app/components/certification-starter.js
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/services/focused-certification-challenge-warning-manager.js
  mon-pix/app/services/focused-certification-challenges-manager.js
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/tests/integration/components/certification-starter_test.js
  mon-pix/tests/test-helper.js
  mon-pix/tests/unit/controllers/assessments/challenge_test.js
  mon-pix/tests/unit/services/focused-certification-challenge-warning-manager_test.js
  mon-pix/tests/unit/services/focused-certification-challenges-manager_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4287 [TECH] Ajoute des détails dans les logs des focusOut (PIX-4722)
  api/lib/domain/models/Examiner.js
  api/lib/domain/usecases/update-last-question-state.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-captains

#4263 [TECH] Monter de versions des packages de Mon Pix.
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4201 [FEATURE] Ne pas pouvoir partager son profil si une participation a été supprimée (PIX-4443).
  api/db/database-builder/factory/build-campaign-participation.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-participation-to-campaign_test.js
  api/tests/acceptance/application/users/users-controller-get-campaign-participations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
  mon-pix/app/components/routes/campaigns/profiles-collection/send-profile.hbs
  mon-pix/app/controllers/campaigns/profiles-collection/send-profile.js
  mon-pix/app/models/campaign-participation.js
  mon-pix/app/styles/pages/_send-profile.scss
  mon-pix/app/templates/campaigns/profiles-collection/send-profile.hbs
  mon-pix/tests/integration/components/routes/campaigns/profiles_collection/send-profile_test.js
  mon-pix/tests/unit/controllers/campaigns/profiles-collection/send-profile_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4277 [FEATURE] Afficher les participations supprimées dans la liste des participations d'une campagne Pix Admin (Pix 4576).
  admin/app/components/campaigns/participation-row.hbs
  admin/app/components/campaigns/participations-section.hbs
  admin/app/models/campaign-participation.js
  admin/tests/integration/components/campaigns/participation-row_test.js
  api/db/database-builder/factory/build-campaign-participation.js
  api/lib/domain/models/ParticipationForCampaignManagement.js
  api/lib/infrastructure/repositories/participations-for-campaign-management-repository.js
  api/lib/infrastructure/serializers/jsonapi/participation-for-campaign-management-serializer.js
  api/tests/integration/infrastructure/repositories/participations-for-campaign-management-repository_test.js
  api/tests/tooling/domain-builder/factory/build-participation-for-campaign-management.js
  api/tests/unit/infrastructure/serializers/jsonapi/participation-for-campaign-management-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4273 [FEATURE] Enregistrement de tuto sur les cards V2 (PIX-4598)
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/components/tutorials/card.js
  mon-pix/mirage/config.js
  mon-pix/mirage/factories/tutorial.js
  mon-pix/mirage/routes/delete-user-tutorial.js
  mon-pix/mirage/routes/put-save-tutorial.js
  mon-pix/mirage/serializers/tutorial.js
  mon-pix/tests/acceptance/tutorial-actions_test.js
  mon-pix/tests/acceptance/user-tutorials-v2/saved_test.js
  mon-pix/tests/unit/components/tutorials/card_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4280 [TECH] Mettre fin aux connexions existantes lors de la suppression du schéma de BDD (PIX-4714)
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/scripts/database/drop-database.js
Labels: :rocket: Ready to Merge, team-certif, cross-team

#4292 [FEATURE] Monter la version de Pix-ui pour utiliser les modifications de Pix-pagination (PIX-4721).
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, Design Review OK

#4288 [FEATURE] Amélioration du design des cartes de tutos (PIX-4337).
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/styles/components/_tutorial-card.scss
  mon-pix/tests/integration/components/tutorials/card_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, Design Review OK

#4294 [TECH] Ajouter un index manquant sur la table knowledge-elements concernant la colonne "assessmentid".
  api/db/migrations/20220406083222_add_index_for_table_knowledge_elements_on_column_assessmentId.js
Labels: :rocket: Ready to Merge, team-captains, cross-team

#4295 [FEATURE] Utiliser la nouvelle card des tutoriels pour le détails des compétences (PIX-4600).
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/components/scorecard-details.js
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/tests/integration/components/scorecard-details_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#4285 [TECH] supprimer le toggle FT_CERTIFICATION_BILLING (PIX-4521)
  api/db/database-builder/factory/build-certification-candidate.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/lib/config.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/infrastructure/files/candidates-import/1.5/candidates_import_template.ods
  api/lib/infrastructure/files/candidates-import/candidates-import-transformation-structures.js
  api/lib/infrastructure/files/candidates-import/fill-candidates-import-sheet.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-data.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-file.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ok.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-special-birthdate-ok.ods
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-sco.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-billing-columns-complementary.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-billing-columns.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-one-complementary-certification-sco.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-one-complementary-certification.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-two-complementary-certifications-sco.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-two-complementary-certifications.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template.ods
  api/tests/integration/infrastructure/utils/ods/files/fill-candidates-import-sheet_test.js
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/models/SCOCertificationCandidate_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/models/feature-toggle.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/unit/controllers/authenticated/sessions/details/certification-candidates_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4299 [FEATURE] Empêcher la suppression des cartes sur la page recommandés (PIX-4736).
  mon-pix/app/components/tutorials/card.js
  mon-pix/app/components/tutorials/cards.hbs
  mon-pix/app/controllers/user-tutorials-v2/saved.js
  mon-pix/app/routes/user-tutorials-v2/saved.js
  mon-pix/app/templates/user-tutorials-v2/saved.hbs
  mon-pix/mirage/handlers/find-paginated-saved-tutorials.js
  mon-pix/tests/acceptance/user-tutorials-v2/recommended_test.js
  mon-pix/tests/acceptance/user-tutorials-v2/saved_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4284 [BUGFIX] Un membre d’espace Pix Certif ne voit pas la liste de ses candidats en prescription de certification SCO (PIX-4316)
  api/lib/infrastructure/repositories/certification-point-of-contact-repository.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/sessions/session-for-attendance-sheet-repository.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/infrastructure/repositories/certification-point-of-contact-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-for-attendance-sheet-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4267 [TECH] Stocker le clientId du parcours Pôle Emploi uniquement dans l'API (PIX-4682).
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/application/pole-emploi/index.js
  api/lib/application/pole-emploi/pole-emploi-controller.js
  api/lib/config.js
  api/lib/domain/services/authentication-service.js
  api/lib/domain/usecases/authenticate-pole-emploi-user.js
  api/sample.env
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/acceptance/application/pole-emploi-controller_test.js
  api/tests/integration/application/authentication/index_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/domain/services/authentication-service_test.js
  api/tests/unit/domain/usecases/authenticate-pole-emploi-user_test.js
  mon-pix/app/authenticators/pole-emploi.js
  mon-pix/app/routes/login-pe.js
  mon-pix/config/environment.js
  mon-pix/mirage/config.js
  mon-pix/tests/acceptance/login-pe_test.js
  mon-pix/tests/unit/routes/login-pe_test.js
Labels: :rocket: Ready to Merge, team-acces

#4298 [TECH] Remplacer la dépendance `ember-sinon` par `sinon`.
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: :rocket: Ready to Merge, cross-team

#4251 [TECH] Tracer la cause de l'erreur si la création d'un candidat échoue (PIX-4663).
  api/lib/infrastructure/repositories/certification-candidate-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4306 [TECH] Disposer d'un mot de passe par défaut sur les données de seed.
  api/db/database-builder/factory/build-user.js
  api/db/seeds/data/certification/certification-candidates-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-certif

#4304 [BUGFIX] Pagination des tutoriels : Gérer la suppression d'une page
  mon-pix/app/templates/user-tutorials-v2/recommended.hbs
  mon-pix/app/templates/user-tutorials-v2/saved.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4303 [TECH] Limiter les watchers nodemon (PIX-4745)
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#4290 [FEATURE] Ne pas afficher les pages Analyses/Résultats d'une participation supprimée (Pix-4689)
  api/lib/domain/usecases/compute-campaign-participation-analysis.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-repository.js
  api/lib/infrastructure/repositories/campaign-profile-repository.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation.js
  api/tests/unit/domain/usecases/compute-campaign-participation-analysis_test.js
  orga/app/routes/authenticated/campaigns/participant-assessment.js
  orga/app/routes/authenticated/campaigns/participant-profile.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4307 [FEATURE] Afficher les informations du compte utilisateur dans le tableau des participations d'une campagne de Pix Admin (PIX-4752).
  admin/app/components/campaigns/participation-row.hbs
  admin/app/components/campaigns/participations-section.hbs
  admin/app/models/campaign-participation.js
  admin/tests/acceptance/authenticated/campaigns/campaign-participations_test.js
  admin/tests/integration/components/campaigns/participation-row_test.js
  api/lib/domain/models/ParticipationForCampaignManagement.js
  api/lib/infrastructure/repositories/participations-for-campaign-management-repository.js
  api/lib/infrastructure/serializers/jsonapi/participation-for-campaign-management-serializer.js
  api/tests/integration/infrastructure/repositories/participations-for-campaign-management-repository_test.js
  api/tests/tooling/domain-builder/factory/build-participation-for-campaign-management.js
  api/tests/unit/domain/models/ParticipationForCampaignManagement_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participation-for-campaign-management-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4301 [TECH] Renommage des `schooling-registrations` en `organization-learners` dans les modèles du domaine (PIX-4687).
  api/lib/domain/models/CampaignParticipant.js
  api/lib/domain/models/OrganizationLearner.js
  api/lib/domain/models/UserWithOrganizationLearner.js
  api/lib/domain/read-models/OrganizationLearnerForAdmin.js
  api/lib/domain/validators/schooling-registration-validator.js
  api/lib/infrastructure/orm-models/OrganizationLearner.js
  api/lib/infrastructure/orm-models/User.js
  api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
  api/scripts/data-generation/add-many-divisions-and-students-to-sco-organization.js
  api/scripts/data-generation/add-many-students-to-sco-certification-center.js
  api/tests/acceptance/scripts/add-many-divisions-and-students-to-sco-organization_test.js
  api/tests/acceptance/scripts/add-many-students-to-sco-certification-center_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/application/schooling-registration-user-associations/schooling-registration-user-association-controller_test.js
  api/tests/integration/domain/usecases/get-user-details-for-admin_test.js
  api/tests/integration/infrastructure/repositories/higher-schooling-registration-repository_test.js
  api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-organization-learner-for-admin.js
  api/tests/tooling/domain-builder/factory/build-organization-learner.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/tooling/domain-builder/factory/build-user-with-organization-learner.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/read-models/OrganizationLearnerForAdmin_test.js
  api/tests/unit/domain/services/sco-account-recovery-service_test.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
  api/tests/unit/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user_test.js
  api/tests/unit/domain/usecases/dissociate-user-from-schooling-registration_test.js
  api/tests/unit/domain/usecases/enroll-students-to-session_test.js
  api/tests/unit/domain/usecases/find-association-between-user-and-schooling-registration_test.js
  api/tests/unit/domain/usecases/find-students-for-enrollement_test.js
  api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
  api/tests/unit/domain/usecases/generate-username_test.js
  api/tests/unit/domain/usecases/import-schooling-registrations-from-siecle_test.js
  api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
  api/tests/unit/domain/usecases/reconcile-schooling-registration_test.js
  api/tests/unit/domain/usecases/reconcile-user-to-organization_test.js
  api/tests/unit/domain/usecases/update-user-details-for-administration_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/schooling-registration-dependent-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/schooling-registration-user-association-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-certification-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-anonymized-details-for-admin-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4313 [FEATURE] Ajout d'un texte RGPD dans la liste des participations d'une campagne dans pix admin (PIX-4651).
  admin/app/components/campaigns/participations-section.hbs
  admin/app/styles/app.scss
  admin/app/styles/components/campaigns/participations-section.scss
Labels: :rocket: Ready to Merge, team-prescription

#4310 [FEATURE] Proposer des épreuves et scorer une certification Pix+ Édu de 1er degré (PIX-4754).
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/certification/badge-acquisition-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/domain/events/handle-pix-plus-edu-certifications-scoring.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/unit/domain/events/handle-pix-plus-edu-certifications-scoring_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4321 [FEATURE] Création de plusieurs lots d'acquis via un script pour le badge Cléa (PIX-4749).
  api/scripts/create-badge-criteria-for-specified-badge.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/scripts/create-badge-criteria-for-specified-badge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4327 [HOTFIX] Correction du nom d'index de Knowledge-elements (PIX-4784)
  CHANGELOG.md
  admin/package-lock.json
  admin/package.json
  api/db/migrations/20220406083222_add_index_for_table_knowledge_elements_on_column_assessmentId.js
  api/package-lock.json
  api/package.json
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4291 [FEATURE] Enregistrer ou mettre à jour le prénom et nom reçu du GAR lors de la connexion (PIX-4656)
  api/db/database-builder/factory/build-authentication-method.js
  api/lib/domain/usecases/get-external-authentication-redirection-url.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/unit/domain/usecases/get-external-authentication-redirection-url_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4325 [TECH] Fixer la vulnérabilité critique de la dépendance minimist
  api/package-lock.json
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
Labels: Tech Review OK, :rocket: Ready to Merge

#4312 [TECH] Supprimer le support des clés sans préfixe dans redis (PIX-4693)
  api/lib/infrastructure/utils/RedisClient.js
  api/tests/integration/infrastructure/utils/RedisClient_test.js
Labels: :rocket: Ready to Merge, team-acces, cross-team

#4323 [BUGFIX] Fixer la valeur de `updatedAt` des invitations quand on archive une organisation (PIX-4780).
  api/lib/infrastructure/repositories/organization-for-admin-repository.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
Labels: :rocket: Ready to Merge, team-acces

#4300 [TECH] Stocker le taux de repro d'un parcours de certification (PIX-4757)
  api/db/database-builder/factory/build-assessment-result.js
  api/db/migrations/20220407193857_add-column-reproducibility-rate-in-assessment-results-table.js
  api/lib/domain/events/handle-certification-rescoring.js
  api/lib/domain/events/handle-certification-scoring.js
  api/lib/domain/models/AssessmentResult.js
  api/lib/infrastructure/repositories/assessment-result-repository.js
  api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
  api/tests/tooling/domain-builder/factory/build-assessment-result.js
  api/tests/unit/domain/events/handle-certification-rescoring_test.js
  api/tests/unit/domain/events/handle-certification-scoring_test.js
  api/tests/unit/domain/models/AssessmentResult_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4332 [BUGFIX] Copier les skill-sets pour les utiliser dans un autre badge dans le script de création de badge-criteria (PIX-4789).
  api/scripts/create-badge-criteria-for-specified-badge.js
  api/tests/integration/scripts/create-badge-criteria-for-specified-badge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4311 [TECH] Renommer les "pe" en "pole-emploi"
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/controllers/terms-of-service-pole-emploi.js
  mon-pix/app/router.js
  mon-pix/app/routes/campaigns/access.js
  mon-pix/app/routes/login-pole-emploi.js
  mon-pix/app/routes/terms-of-service-pole-emploi.js
  mon-pix/app/templates/login-pole-emploi.hbs
  mon-pix/app/templates/terms-of-service-pole-emploi.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/tests/acceptance/login-pole-emploi_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/acceptance/terms-of-service_test.js
  mon-pix/tests/unit/controllers/terms-of-service-pole-emploi_test.js
  mon-pix/tests/unit/routes/campaigns/access_test.js
  mon-pix/tests/unit/routes/login-pole-emploi_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#4334 [TECH] Mise à jour de Pix UI dans Pix Orga (PIX-4791).
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/update-form.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4317 [A11Y] Ajouter un texte aux boutons de retour sur Pix Certif
  certif/app/styles/components/finalize.scss
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/session-details_test.js
  certif/tests/acceptance/session-finalization_test.js
  high-level-tests/e2e/cypress/support/step_definitions/pix-certif/session.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4328 [FEATURE] Afficher les macarons Pix+ Édu de 1er degré dans le certificat et certificat partagé dans Pix App (PIX-4768).
  api/lib/domain/read-models/CertifiedBadgeImage.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/tests/unit/domain/read-models/CertifiedBadgeImage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4336 [TECH] Retirer les tests de bout en bout sur PixCertif (PIX-4796)
  .circleci/config.yml
  high-level-tests/e2e/cypress.json
  high-level-tests/e2e/cypress/fixtures/assessments.json
  high-level-tests/e2e/cypress/fixtures/authentication-methods.json
  high-level-tests/e2e/cypress/fixtures/certification-candidates.json
  high-level-tests/e2e/cypress/fixtures/certification-center-memberships.json
  high-level-tests/e2e/cypress/fixtures/certification-centers.json
  high-level-tests/e2e/cypress/fixtures/certification-courses.json
  high-level-tests/e2e/cypress/fixtures/sessions.json
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/integration/pix-certif/certification-candidates-management.feature
  high-level-tests/e2e/cypress/integration/pix-certif/certification-session-creation.feature
  high-level-tests/e2e/cypress/integration/pix-certif/certification-session-finalization.feature
  high-level-tests/e2e/cypress/integration/pix-certif/certification-session-update.feature
  high-level-tests/e2e/cypress/integration/pix-certif/login-logout-certif.feature
  high-level-tests/e2e/cypress/support/commands.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  high-level-tests/e2e/cypress/support/step_definitions/pix-certif/session.js
  high-level-tests/e2e/docker-compose.yaml
  high-level-tests/e2e/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#4337 [BUGFIX] Un utilisateur pouvait voir plusieurs fois la même habilitation à cocher lors d'une inscription de candidat en certification (PIX-4797)
  api/lib/infrastructure/repositories/certification-point-of-contact-repository.js
  api/tests/integration/infrastructure/repositories/certification-point-of-contact-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4330 [BUGFIX] Ne pas afficher le message d'alerte de sortie de focus lorsque l'user reprend un nouvel assessment (PIX-4787).
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/tests/acceptance/challenge-item_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4340 [FEATURE] Ajout des nouvelles cartes tutos sur les pages checkpoint (PIX-4601).
  mon-pix/app/components/learning-more-panel.hbs
  mon-pix/app/components/learning-more-panel.js
  mon-pix/app/components/tutorial-panel.hbs
  mon-pix/app/components/tutorial-panel.js
  mon-pix/app/styles/components/_learning-more-tutorial-panel.scss
  mon-pix/app/styles/components/_tutorial-panel.scss
  mon-pix/tests/integration/components/learning-more-panel_test.js
  mon-pix/tests/integration/components/tutorial-panel_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4342 [FEATURE] Harmoniser les messages d'erreur lors de la création d'une session (PIX-4809).
  api/lib/domain/validators/session-validator.js
  api/tests/unit/domain/validators/session-validator_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4335 [TECH] Mettre le path de l'url d'authentification de Pole Emploi dans la variable d'environnement
  api/lib/config.js
  api/lib/domain/services/authentication-service.js
  api/sample.env
  api/tests/acceptance/application/pole-emploi-controller_test.js
  mon-pix/app/routes/login-pole-emploi.js
  mon-pix/config/environment.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#4314 [TECH] Gerer les volets Pix Edu en BDD via la colonne source (PIX-4746)
  api/db/database-builder/factory/build-complementary-certification-course-result.js
  api/db/migrations/20220411134827_add-column-source-to-complementary-certification-results.js
  api/db/migrations/20220411140819_migrate-complementary-certification-results-sources.js
  api/lib/domain/models/CertificationAttestation.js
  api/lib/domain/models/ComplementaryCertificationCourseResult.js
  api/lib/domain/models/PartnerCertificationScoring.js
  api/lib/domain/models/PixPlusEduCertificationScoring.js
  api/lib/domain/read-models/CertifiedBadgeImage.js
  api/lib/domain/read-models/CertifiedBadges.js
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/lib/infrastructure/repositories/partner-certification-scoring-repository.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test.js
  api/tests/tooling/domain-builder/factory/build-certification-attestation.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-course-result.js
  api/tests/unit/domain/models/CertificationAttestation_test.js
  api/tests/unit/domain/models/ComplementaryCertificationCourseResult_test.js
  api/tests/unit/domain/models/PixPlusEduCertificationScoring_test.js
  api/tests/unit/domain/read-models/CertifiedBadgeImage_test.js
  api/tests/unit/domain/read-models/CertifiedBadges_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4344 [FEATURE] Voir l'id d'un membre et le détail si l'on clique dessus (PIX-4781)
  admin/app/components/member-item.hbs
  admin/app/components/organizations/team-section.hbs
  admin/tests/acceptance/authenticated/organizations/list_test.js
  admin/tests/acceptance/authenticated/organizations/memberships-management_test.js
  admin/tests/integration/components/member-item_test.js
Labels: :rocket: Ready to Merge, team-acces

#4347 [FEATURE] Gere la certification complementaire CleA V3 (PIX-4788)
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/certification/badge-acquisition-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/CertificationAttestation.js
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/models/JuryCertification.js
  api/lib/domain/read-models/JuryCertificationSummary.js
  api/lib/domain/services/certification-badges-service.js
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/lib/infrastructure/repositories/certification-result-repository.js
  api/lib/infrastructure/repositories/clea-certification-result-repository.js
  api/lib/infrastructure/repositories/partner-certification-scoring-repository.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/lib/infrastructure/utils/pdf/get-image-path-by-badge-key.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/clea-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test.js
  api/tests/unit/domain/models/CertificationAttestation_test.js
  api/tests/unit/domain/models/CertificationResult_test.js
  api/tests/unit/domain/read-models/CertifiedBadges_test.js
  api/tests/unit/domain/services/certification-badges-service-test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-certification-summary-serializer_test.js
  api/tests/unit/infrastructure/utils/pdf/get-image-path-by-badge-key_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4297 [FEATURE] Amélioration du style des boutons des nouvelles cartes tutos (PIX-4724).
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/components/tutorials/card.js
  mon-pix/app/styles/components/_tutorial-card.scss
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/tests/acceptance/tutorial-actions_test.js
  mon-pix/tests/acceptance/user-tutorials-v2/actions_test.js
  mon-pix/tests/acceptance/user-tutorials-v2/recommended_test.js
  mon-pix/tests/acceptance/user-tutorials-v2/saved_test.js
  mon-pix/tests/integration/components/tutorials/card_test.js
  mon-pix/tests/unit/components/tutorials/card_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, Design Review OK

#4352 [FEATURE] Désactiver le bouton quand on sauvegarde un tuto (PIX-4824).
  mon-pix/app/components/tutorials/card.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4338 [TECH] Utiliser des vectoriels pour l'affichage des macarons de certification complementaire dans les pdf (PIX-4798)
  api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
  api/lib/infrastructure/utils/pdf/files/macaron_clea.pdf
  api/lib/infrastructure/utils/pdf/files/macaron_clea.png
  api/lib/infrastructure/utils/pdf/files/macaron_droit_expert.pdf
  api/lib/infrastructure/utils/pdf/files/macaron_droit_maitre.pdf
  api/lib/infrastructure/utils/pdf/files/macaron_edu_2nd_avance.pdf
  api/lib/infrastructure/utils/pdf/files/macaron_edu_2nd_confirme.pdf
  api/lib/infrastructure/utils/pdf/files/macaron_edu_2nd_expert.pdf
  api/lib/infrastructure/utils/pdf/files/macaron_edu_2nd_initie.pdf
  api/lib/infrastructure/utils/pdf/files/macaron_edu_initie.pdf
  api/lib/infrastructure/utils/pdf/files/macaron_expert.png
  api/lib/infrastructure/utils/pdf/files/macaron_maitre.png
  api/lib/infrastructure/utils/pdf/get-image-path-by-badge-key.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_several_pages.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu_temporary.pdf
  api/tests/unit/infrastructure/utils/pdf/get-image-path-by-badge-key_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4358 [TECH] Réparation d'un test flaky sur le test auto du script de création de badge-criteria à partir d'un fichier JSON (PIX-4828)
  api/scripts/create-badge-criteria-for-specified-badge.js
  api/tests/integration/scripts/create-badge-criteria-for-specified-badge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4357 [FEATURE] Modifier "Ajouter des candidats" en "Inscrire des candidats" dans Pix Certif (PIX-3007).
  certif/app/components/add-student-list.hbs
  certif/app/components/certification-candidates-sco.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/import-candidates.hbs
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/templates/authenticated/sessions/add-student.hbs
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4345 [FEATURE] Ajouter la page "Équipe" dans Pix Admin qui liste les membres Pix Admin existants (PIX-4003)
  admin/app/adapters/admin-member.js
  admin/app/components/menu-bar.hbs
  admin/app/components/team/list.hbs
  admin/app/models/admin-member.js
  admin/app/router.js
  admin/app/routes/authenticated/team/list.js
  admin/app/templates/authenticated/team.hbs
  admin/app/templates/authenticated/team/list.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/organizations/information-management_test.js
  admin/tests/acceptance/authenticated/team/list_test.js
  admin/tests/integration/components/menu-bar_test.js
  admin/tests/integration/components/team/list_test.js
  api/lib/application/admin-members/admin-member-controller.js
  api/lib/application/admin-members/index.js
  api/lib/domain/read-models/AdminMember.js
  api/lib/domain/usecases/get-admin-members.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/admin-member-repository.js
  api/lib/infrastructure/serializers/jsonapi/admin-member-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/admin-members/admin-members-route-get_test.js
  api/tests/integration/infrastructure/repositories/admin-member-repository_test.js
  api/tests/tooling/domain-builder/factory/build-admin-member.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/admin-members/admin-member-controller_test.js
  api/tests/unit/domain/usecases/get-admin-members_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/admin-member-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#4213 [TECH] Créer des routes pour permettre la sélection d'un profil sur Pix-admin (PIX-4544).
  api/lib/application/frameworks/frameworks-controller.js
  api/lib/application/frameworks/index.js
  api/lib/domain/models/Framework.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/get-framework-areas.js
  api/lib/domain/usecases/get-frameworks.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/learning-content/area-datasource.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
  api/lib/infrastructure/datasources/learning-content/framework-datasource.js
  api/lib/infrastructure/datasources/learning-content/thematic-datasource.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/framework-repository.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/repositories/tube-repository.js
  api/lib/infrastructure/serializers/jsonapi/framework-areas-serializer.js
  api/lib/infrastructure/serializers/jsonapi/framework-serializer.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/integration/infrastructure/repositories/framework-repository_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/integration/infrastructure/repositories/tube-repository_test.js
  api/tests/unit/application/frameworks/frameworks-controller_test.js
  api/tests/unit/domain/usecases/get-framework-areas_test.js
  api/tests/unit/domain/usecases/get-frameworks_test.js
  api/tests/unit/infrastructure/datasources/learning-content/area-datasource_test.js
  api/tests/unit/infrastructure/datasources/learning-content/framework-datasource_test.js
  api/tests/unit/infrastructure/datasources/learning-content/thematic-datasource_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/framework-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/pix-framework-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#4339 [FEATURE] Empêcher la tentative de création de candidat pendant un appel API (PIX-4804).
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4354 [FEATURE] Ajouter un script permettant de lancer l'auto jury pour une session (PIX-4819).
  api/scripts/launch-auto-jury-for-session.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4359 [FEATURE] Supprimer le feature toggle des tutos v2 (PIX-4817).
  high-level-tests/e2e/cypress/integration/pix-app/user-tutorials.feature
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Compétence non commencée-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mathématiques - 1ere question-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mathématiques - 2eme question-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mathématiques - résultat évaluation-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mes Tutos - 1 tuto enregistré-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Mes Tutos vide-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Profil-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Réponses et tutos - tuto enregistré-base.png
  high-level-tests/e2e/cypress/snapshots/base/pix-app/user-tutorials.feature/Réponses et tutos-base.png
  high-level-tests/e2e/cypress/support/step_definitions/user-tutorials.js
  mon-pix/app/components/learning-more-panel.hbs
  mon-pix/app/components/learning-more-panel.js
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/components/scorecard-details.js
  mon-pix/app/components/tutorial-panel.hbs
  mon-pix/app/components/tutorial-panel.js
  mon-pix/app/components/tutorials/header.hbs
  mon-pix/app/components/tutorials/header.js
  mon-pix/app/controllers/user-tutorials.js
  mon-pix/app/controllers/user-tutorials/recommended.js
  mon-pix/app/controllers/user-tutorials/saved.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/router.js
  mon-pix/app/routes/user-tutorials-v2/index.js
  mon-pix/app/routes/user-tutorials.js
  mon-pix/app/routes/user-tutorials/index.js
  mon-pix/app/routes/user-tutorials/recommended.js
  mon-pix/app/routes/user-tutorials/saved.js
  mon-pix/app/templates/user-tutorials-v2.hbs
  mon-pix/app/templates/user-tutorials.hbs
  mon-pix/app/templates/user-tutorials/recommended.hbs
  mon-pix/app/templates/user-tutorials/saved.hbs
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/acceptance/competences-details_test.js
  mon-pix/tests/acceptance/tutorial-actions_test.js
  mon-pix/tests/acceptance/user-tutorials/actions_test.js
  mon-pix/tests/acceptance/user-tutorials/recommended_test.js
  mon-pix/tests/acceptance/user-tutorials/saved_test.js
  mon-pix/tests/acceptance/user-tutorials_test.js
  mon-pix/tests/integration/components/learning-more-panel_test.js
  mon-pix/tests/integration/components/scorecard-details_test.js
  mon-pix/tests/integration/components/tutorial-panel_test.js
  mon-pix/tests/integration/components/tutorials/content_test.js
  mon-pix/tests/unit/routes/user-tutorials/recommended_test.js
  mon-pix/tests/unit/routes/user-tutorials/saved_test.js
  mon-pix/tests/unit/routes/user-tutorials_test.js
Labels: :rocket: Ready to Merge, team-evaluation

#4365 [BUGFIX] Uniformiser la taille du contenu de la page "Mes Certifications" sur Pix App (PIX-4825).
  mon-pix/app/styles/components/dashboard/_content.scss
  mon-pix/app/styles/globals/_layout.scss
Labels: :rocket: Ready to Merge, cross-team

#4370 [CLEANUP] Mise à jour de l'auto merge
  .github/workflows/auto-merge.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#4373 [TECH] Harmoniser le texte du formulaire de connexion sur Pix Admin (PIX-4852).
  admin/app/components/login-form.hbs
  admin/tests/integration/components/login-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-certif

#4308 [FEATURE] Afficher un message d'erreur si un prescrit à déjà une participation à une campagne (PIX-4674).
  api/lib/domain/models/CampaignParticipant.js
  api/lib/infrastructure/repositories/campaign-participant-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participant-repository_test.js
  api/tests/unit/domain/models/CampaignParticipant_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
  mon-pix/app/router.js
  mon-pix/app/routes/campaigns/entrance.js
  mon-pix/app/routes/campaigns/existing-participation.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/_existing-campagne.scss
  mon-pix/app/templates/campaigns/existing-participation.hbs
  mon-pix/tests/acceptance/existing-participation-test.js
  mon-pix/tests/unit/routes/campaigns/entrance_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4366 [FEATURE] Utiliser le vocabulaire métier "Inscrire un candidat" (PIX-4835).
  certif/app/components/add-student-list.hbs
  certif/app/components/add-student-list.js
  certif/app/components/enrolled-candidates.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/router.js
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/add-student-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4377 [FEATURE] Renommer le nom des labels des champs adresse email (PIX-4856).
  admin/app/components/organizations/information-section.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#4362 [TECH] Supprimer le usecase get-pix-framework au profit de get-framework-areas
  api/lib/application/frameworks/frameworks-controller.js
  api/lib/domain/usecases/get-framework-areas.js
  api/lib/domain/usecases/get-pix-framework.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
  api/lib/infrastructure/datasources/learning-content/framework-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/framework-repository.js
  api/lib/infrastructure/repositories/tube-repository.js
  api/tests/acceptance/application/frameworks/frameworks-controller_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/framework-repository_test.js
  api/tests/integration/infrastructure/repositories/tube-repository_test.js
  api/tests/unit/application/frameworks/frameworks-controller_test.js
  api/tests/unit/domain/usecases/get-framework-areas_test.js
  api/tests/unit/domain/usecases/get-pix-framework_test.js
  api/tests/unit/infrastructure/datasources/learning-content/challenge-datasource_test.js
  api/tests/unit/infrastructure/datasources/learning-content/framework-datasource_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#4378 [FEATURE] Remplacement de l'image codée sur la page de tutos vide par un PNG (PIX-4841).
  mon-pix/app/components/tutorials/saved-empty.hbs
  mon-pix/app/components/tutorials/saved-empty.js
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/public/images/illustrations/user-tutorials/saved-empty.png
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4355 [BUGFIX] ajouter une marge au bloque d'information dans la page de création de campagne (PIX-4812)
  orga/app/components/campaign/create-form.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4360 [FEATURE] Permettre le changement de rôle dans Pix Admin pour les Super Admin (PIX-4664)
  admin/app/components/team/list.hbs
  admin/app/components/team/list.js
  admin/app/models/admin-member.js
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/team/list_test.js
  admin/tests/integration/components/team/list_test.js
  api/db/database-builder/factory/build-user.js
  api/db/migrations/20220427094148_add-check-constraint-on-pix-admin-roles.js
  api/db/seeds/data/pix-admin-roles-builder.js
  api/lib/application/admin-members/admin-member-controller.js
  api/lib/application/admin-members/index.js
  api/lib/domain/constants.js
  api/lib/domain/errors.js
  api/lib/domain/models/AdminMember.js
  api/lib/domain/models/PixAdminRole.js
  api/lib/domain/models/User.js
  api/lib/domain/read-models/AdminMember.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-admin-member.js
  api/lib/infrastructure/repositories/admin-member-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/admin-member-serializer.js
  api/tests/acceptance/application/admin-members/admin-members-route-get_test.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/admin-member-repository_test.js
  api/tests/tooling/domain-builder/factory/build-admin-member.js
  api/tests/tooling/domain-builder/factory/build-pix-admin-role.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/application/admin-members/admin-member-controller_test.js
  api/tests/unit/domain/models/AdminMember_test.js
  api/tests/unit/domain/models/PixAdminRole_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/update-admin-member_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/admin-member-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces
