Repository 1024pix/pix, pull requests merged in 2022-01, with the labels that each got.

#3861 [TECH] Eviter les faux négatifs dus aux séquences de seeds (PIX-4065).
  api/db/seeds/seed.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif, cross-team

#3889 [A11Y] Rendre la navigation au niveau de la campagne accessible lors d'une zoom 200% en mode texte sur Firefox (PIX-3895)
  orga/app/styles/components/indicator-card.scss
  orga/app/styles/globals/panels.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3872 [FEATURE] Afficher le macaron Pix+ Édu sur le certificat partagé (PIX-4066).
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3879 [FEATURE] Afficher l'éligibilité d'un candidat aux certifications Pix+ Édu (PIX-3995).
  api/lib/domain/read-models/CertificationEligibility.js
  api/lib/domain/usecases/get-user-certification-eligibility.js
  api/lib/infrastructure/serializers/jsonapi/certification-eligibility-serializer.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/tooling/domain-builder/factory/build-certification-eligibility.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-user-certification-eligibility_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-eligibility-serializer_test.js
  mon-pix/app/models/is-certifiable.js
  mon-pix/app/templates/components/congratulations-certification-banner.hbs
  mon-pix/tests/integration/components/congratulations-certification-banner_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3891 [BUGFIX] Retourner sur la page paramètres après avoir créé une campagne (Pix-4089).
  orga/app/controllers/authenticated/campaigns/new.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3780 [BUGFIX] Interdire l'import des fichiers SIECLE avec un mime-type non autorisé.
  orga/app/adapters/students-import.js
  orga/app/controllers/authenticated/sco-students/list.js
  orga/config/environment.js
  orga/mirage/config.js
  orga/tests/acceptance/sco-student-list_test.js
  orga/tests/helpers/catch-err.js
  orga/tests/unit/adapters/students-import_test.js
  orga/tests/unit/controllers/authenticated/sco-students/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-captains

#3874 [BUGFIX] Bug d'affichage de l'onglet "Détails" et "Neutralisation" (PIX-4078)
  admin/app/components/certifications/status.js
  admin/app/models/jury-certification-summary.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/read-models/JuryCertificationSummary.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/unit/domain/read-models/JuryCertificationSummary_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3896 [FEATURE] Supprime le commentaire spécifique aux organisations SCO (PIX-3871)
  orga/app/components/campaign/create-form.hbs
  orga/tests/integration/components/campaign/create-form_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3893 [TECH] Faire échouer la CI sur le set recommended de eslint-mocha sur l'API.
  api/.eslintrc.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3880 [FEATURE] Permettre d'ajouter une méthode de connexion avec adresse e-mail à un utilisateur sur Pix Admin (PIX-3775).
  admin/app/adapters/user.js
  admin/app/components/users/user-detail-personal-information.hbs
  admin/app/components/users/user-detail-personal-information/add-authentication-method-modal.hbs
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/components/users/user-detail-personal-information/authentication-method.js
  admin/app/controllers/authenticated/users/get.js
  admin/app/models/user.js
  admin/app/styles/app.scss
  admin/app/styles/components/users/user-detail-personal-information-section.scss
  admin/app/styles/components/users/user-detail-personal-information/authentication-method.scss
  admin/app/styles/globals/button.scss
  admin/app/templates/authenticated/users/get.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/users/authentication-method_test.js
  admin/tests/acceptance/user-details-personal-information_test.js
  admin/tests/integration/components/users/user-detail-personal-information/authentication-method_test.js
  admin/tests/integration/components/users/user-detail-personal-information_test.js
  admin/tests/unit/models/user_test.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/errors.js
  api/lib/domain/services/password-generator.js
  api/lib/domain/usecases/add-pix-authentication-method-by-email.js
  api/lib/domain/usecases/generate-username-with-temporary-password.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-schooling-registration-dependent-user-password.js
  api/tests/acceptance/application/users/add-pix-authentication-method-by-email-route-post_test.js
  api/tests/integration/domain/usecases/add-pix-authentication-method-by-email_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/services/password-generator_test.js
  api/tests/unit/domain/usecases/add-pix-authentication-method-by-email_test.js
  api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
  api/tests/unit/domain/usecases/update-schooling-registration-dependent-user-password_test.js
Labels: :rocket: Ready to Merge, team-acces

#3895 [FEATURE] Ajouter la date de validation des cgu lors de la création de compte pix (PIX-1763)
  api/lib/domain/usecases/create-user-from-pole-emploi.js
  api/lib/domain/usecases/create-user.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/unit/domain/usecases/create-user-from-pole-emploi_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  mon-pix/tests/acceptance/terms-of-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#3899 [BUGFIX] [A11Y] Ajouter un titre au champ de filtrage sur la page d'ajout d'élèves à une session de certification (PIX-3906)
  certif/app/components/add-student-list.hbs
  certif/app/styles/components/add-student-list.scss
  certif/tests/integration/components/add-student-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3905 [BUGFIX] Corriger le test flaky sur l'api remontant les données de resultat d'une campagne (PIX-4102)
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3226 [DOC] Choisir une nouvelle librairie de gestion du temps.
  docs/adr/0030-revoir-le-choix-d-une-librarire-de-gestion-des-dates.md
Labels: :rocket: Ready to Merge, cross-team

#3903 [FEATURE] Ajout de l'url de documentation lors de la création d'une orga (Pix-3975).
  admin/app/components/organizations/form.hbs
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/create-organization.js
  api/lib/domain/validators/organization-creation-validator.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/domain/usecases/create-organization_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/create-organization_test.js
  api/tests/unit/domain/validators/organization-creation-validator_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3910 [FEATURE] Enlever le dégradé du menu dans pix Orga (PIX-4053).
  orga/app/styles/components/layout/sidebar.scss
  orga/app/styles/globals/colors.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3881 [A11Y] Ajout d'instructions pour les QCU et QCM (PIX-3916).
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/templates/components/challenge-item-qcm.hbs
  mon-pix/app/templates/components/challenge-item-qcu.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3892 [A11Y] Ajouter des formes dans les repartitions du graphique camembert sur la page Activité de Pix Orga (PIX-3893)
  orga/app/components/campaign/charts/participants-by-status.hbs
  orga/app/components/campaign/charts/participants-by-status.js
  orga/app/styles/components/campaign/charts/participants-by-status.scss
  orga/ember-cli-build.js
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3906 [FEATURE] Supprime le feature toggle du Net Promoter Score (PIX-4096)
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3867 [FEATURE] Algo flash : Enregistrer le niveau estimé et le taux d'erreur (PIX-4039)
  api/db/database-builder/factory/build-flash-assessment-result.js
  api/db/database-builder/factory/index.js
  api/db/migrations/20211223092838_create-flash-assessment-results.js
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/learning-content/datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/flash-assessment-result-repository.js
  api/tests/integration/infrastructure/repositories/flash-assessment-result-repository_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  api/tests/unit/infrastructure/datasources/learning-content/datasource_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3836 [FEATURE] Vérifier que les acquis sont valides lors de la création d'un badge (PIX-4023)
  admin/app/components/target-profiles/badge-form.hbs
  admin/app/components/target-profiles/badge-form.js
  admin/app/models/badge.js
  admin/tests/integration/components/target-profiles/badge-form_test.js
  api/lib/application/badges/badges-controller.js
  api/lib/application/badges/index.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/create-badge-criterion.js
  api/lib/domain/usecases/create-badge.js
  api/lib/domain/usecases/create-skill-set.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/badge-criteria-repository.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/repositories/skill-set-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/badge-creation-serializer.js
  api/lib/infrastructure/serializers/jsonapi/badge-criteria-serializer.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/skill-set-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/domain/usecases/create-badge_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/unit/domain/usecases/create-badge_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-creation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-criteria-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-set-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3848 [TECH] Générer des tests conformes aux conventions avec le CLI Ember.
  admin/blueprints/acceptance-test/files/tests/acceptance/__name___test.js
  admin/blueprints/adapter-test/files/tests/unit/adapters/__name___test.js
  admin/blueprints/component-test/files/tests/integration/components/__name___test.js
  admin/blueprints/route-test/files/tests/unit/routes/__name___test.js
  certif/blueprints/acceptance-test/files/tests/acceptance/__name___test.js
  certif/blueprints/adapter-test/files/tests/unit/adapters/__name___test.js
  certif/blueprints/component-test/files/tests/integration/components/__name___test.js
  certif/blueprints/route-test/files/tests/unit/routes/__name___test.js
  mon-pix/blueprints/acceptance-test/files/tests/acceptance/__name___test.js
  mon-pix/blueprints/adapter-test/files/tests/unit/adapters/__name___test.js
  mon-pix/blueprints/component-test/files/tests/integration/components/__name___test.js
  mon-pix/blueprints/route-test/files/tests/unit/routes/__name___test.js
  orga/blueprints/acceptance-test/files/tests/acceptance/__name___test.js
  orga/blueprints/adapter-test/files/tests/unit/adapters/__name___test.js
  orga/blueprints/component-test/files/tests/integration/components/__name___test.js
  orga/blueprints/route-test/files/tests/unit/routes/__name___test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team

#3902 [TECH] Disposer du résultat des tests de charge dans Datadog.
  high-level-tests/load-testing/config/common.yml
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/load-testing/sample.env
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#3913 [A11Y] Changer la couleur du graphique ayant un contraste insuffisant pour l'accessibilité (PIX-4052)
  orga/app/components/campaign/charts/participants-by-status.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3897 [BUGFIX] Corriger les repositories effectuant des opérations hors transaction à tort
  api/lib/infrastructure/repositories/account-recovery-demand-repository.js
  api/lib/infrastructure/repositories/user-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3888 [FEATURE] Modifier la page de fin de test de certification (PIX-4069)
  mon-pix/app/components/certifications/certification-ender.js
  mon-pix/app/controllers/certifications/results.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_certification-banner.scss
  mon-pix/app/styles/components/certifications/certification-ender.scss
  mon-pix/app/templates/certifications/results.hbs
  mon-pix/app/templates/components/certifications/certification-ender.hbs
  mon-pix/config/icons.js
  mon-pix/public/images/illustrations/certification-ender/results-example.svg
  mon-pix/public/images/illustrations/certification-ender/test-completed.svg
  mon-pix/tests/acceptance/certification-course_test.js
  mon-pix/tests/integration/components/certifications/certification-ender_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3907 [TECH] Assurer que l'utilisateur créateur de la campagne est bien renseigné.
  api/db/migrations/20220105132942_alter-creatorId-from-campaigns-to-be-not-nullable.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3918 [BUGFIX] Accepter les fichiers SIECLE csv avec le mime type `text/plain` (PIX-4111)
  orga/app/adapters/students-import.js
  orga/app/controllers/authenticated/sco-students/list.js
  orga/tests/unit/adapters/students-import_test.js
  orga/tests/unit/controllers/authenticated/sco-students/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-captains

#3901 [TECH] Factoriser la création des images de badge
  api/lib/domain/read-models/CertifiedBadgeImage.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/unit/domain/read-models/CertifiedBadgeImage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3914 [FEATURE] Afficher les résultats de la certification Pix+ Edu dans le csv des résultats (PIX-4080).
  api/lib/domain/models/CertificationResult.js
  api/lib/domain/models/CleaCertificationResult.js
  api/lib/domain/models/PartnerCertification.js
  api/lib/domain/models/PixPlusDroitExpertCertificationResult.js
  api/lib/domain/models/PixPlusDroitMaitreCertificationResult.js
  api/lib/domain/read-models/CertifiedBadgeImage.js
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/lib/infrastructure/repositories/certification-result-repository.js
  api/lib/infrastructure/repositories/clea-certification-result-repository.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/repositories/pix-plus-droit-expert-certification-result-repository.js
  api/lib/infrastructure/repositories/pix-plus-droit-maitre-certification-result-repository.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/clea-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/pix-plus-droit-expert-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/pix-plus-droit-maitre-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/tooling/domain-builder/factory/build-certification-result.js
  api/tests/tooling/domain-builder/factory/build-partner-certification.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/CertificationResult_test.js
  api/tests/unit/domain/read-models/CertifiedBadgeImage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3916 [DOC] Expliciter la structure d'un ADR.
  docs/adr/0001-enregistrer-les-decisions-concernant-l-architecture.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3917 [FEATURE] Afficher le flag permettant d'afficher ou non les acquis dans l'export de résultats d'une campagne (Pix 4104).
  admin/app/components/organizations/information-section.hbs
  admin/app/models/organization.js
  admin/tests/integration/components/organizations/information-section_test.js
  api/db/database-builder/factory/build-organization.js
  api/db/migrations/20220106130955_add-showskills-to-organizations.js
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/tooling/domain-builder/factory/build-organization.js
  api/tests/unit/domain/models/Organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: :rocket: Ready to Merge, team-prescription

#3912 [TECH] Algo flash : Réutiliser le niveau estimé enregistré pour trouver le prochain challenge
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/lib/infrastructure/repositories/flash-assessment-result-repository.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3911 [TECH] Supprimer la gestion de la documentation en fonction des tags dans PixOrga (PIX-3976).
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/tests/unit/domain/models/Organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  orga/app/components/layout/sidebar.js
  orga/app/models/organization.js
  orga/app/services/current-user.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/layout/sidebar_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3926 [BUGFIX] Ne pas valider les mime types sur les imports de fichiers SIECLE (PIX-4111)
  orga/app/adapters/students-import.js
  orga/app/controllers/authenticated/sco-students/list.js
  orga/config/environment.js
  orga/mirage/config.js
  orga/tests/acceptance/sco-student-list_test.js
  orga/tests/helpers/catch-err.js
  orga/tests/unit/adapters/students-import_test.js
  orga/tests/unit/controllers/authenticated/sco-students/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-prescription, team-captains

#3885 [FEATURE] Ajout des Thématiques, Compétences et Domaines dans la sélection des sujets (PIX-3948)
  api/lib/application/frameworks/frameworks-controller.js
  api/lib/application/frameworks/index.js
  api/lib/application/tubes/tubes-controller.js
  api/lib/domain/models/Competence.js
  api/lib/domain/models/Thematic.js
  api/lib/domain/usecases/get-pix-framework.js
  api/lib/domain/usecases/get-tubes-from-pix-framework.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/learning-content/thematic-datasource.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/serializers/jsonapi/framework-serializer.js
  api/lib/infrastructure/serializers/jsonapi/tube-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/frameworks/frameworks-controller_test.js
  api/tests/acceptance/application/security-pre-handlers_test.js
  api/tests/acceptance/application/tubes/tubes-controller_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/tooling/domain-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/build-thematic.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/frameworks/frameworks-controller_test.js
  api/tests/unit/application/tubes/tubes-controller_test.js
  api/tests/unit/domain/models/Thematic_test.js
  api/tests/unit/domain/usecases/get-pix-framework_test.js
  api/tests/unit/domain/usecases/get-tubes-from-pix-framework_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/framework-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tube-serializer_test.js
  orga/app/adapters/area.js
  orga/app/adapters/tube.js
  orga/app/components/tube/list.hbs
  orga/app/components/tube/list.js
  orga/app/models/area.js
  orga/app/models/competence.js
  orga/app/models/thematic.js
  orga/app/routes/authenticated/preselect-target-profile.js
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/preselect-target-profile.scss
  orga/app/templates/authenticated/preselect-target-profile.hbs
  orga/mirage/config.js
  orga/tests/acceptance/preselect-target-profile_test.js
  orga/tests/integration/components/tube/list_test.js
  orga/tests/unit/adapters/tube-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, Design Review OK, team-contenu

#3927 [BUGFIX] Affiche le message d'erreur lorsqu'une campagne n'a pas de profil cible (PIX-4091).
  api/lib/domain/validators/stage-validator.js
  api/tests/unit/domain/validators/stage-validator_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3915 [FEATURE] Afficher le message de certification terminée par le surveillant sur la page de fin de test (PIX-4110)
  mon-pix/app/controllers/certifications/results.js
  mon-pix/app/router.js
  mon-pix/app/routes/certifications/results.js
  mon-pix/app/templates/certifications/results.hbs
  mon-pix/app/templates/components/certifications/certification-ender.hbs
  mon-pix/mirage/config.js
  mon-pix/tests/acceptance/certification-course_test.js
  mon-pix/tests/integration/components/certifications/certification-ender_test.js
  mon-pix/tests/unit/routes/certifications/results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3929 [FEATURE] Ajouter les traductions manquantes à la nouvelle page de fin de test (PIX-4121)
  certif/app/components/session-supervising/candidate-in-list.js
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3920 [FEATURE] Afficher les certifications Pix+ Édu dans le tableau listant les certifications dans Pix Admin (PIX-3992).
  admin/app/models/jury-certification-summary.js
  admin/tests/unit/models/jury-certification-summary_test.js
  api/lib/domain/models/PartnerCertification.js
  api/lib/domain/read-models/JuryCertificationSummary.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-certification-summary-serializer.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-certification-summary-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3898 [FEATURE] Mise à jour des RT dans Pix-Admin (PIX-3960).
  admin/app/components/badges/badge.hbs
  admin/app/components/badges/badge.js
  admin/app/styles/components/badges/badge.scss
  admin/tests/integration/components/badges/badge_test.js
  api/lib/application/badges/badges-controller.js
  api/lib/application/badges/index.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-badge.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3936 [FEATURE] Autorise l'utilisation d'un wildcard dans les URLs autorisées a avoir un embed (PIX-4132)
  mon-pix/app/components/challenge-item-qroc.js
  mon-pix/tests/unit/components/challenge-item-qroc_test.js
Labels: :rocket: Ready to Merge, team-contenu

#3904 [TECH] Campagne FLASH1234 sans profile cible (PIX-3823)
  api/db/seeds/data/campaigns-builder.js
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/domain/usecases/get-progression.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/unit/domain/usecases/get-progression_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3923 [TECH] Suppression de paramètres inutilisés
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3919 [A11Y] Ajouter un role "columnheader" a tous les tableaux dans Pix Orga (Pix-4115)
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/charts/participants-by-day.hbs
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/components/participant/assessment/results.hbs
  orga/app/components/participant/profile/table.hbs
  orga/app/components/table/header.hbs
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/members-list.hbs
  orga/app/components/team/members-list.js
  orga/app/styles/globals/tables.scss
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#3909 [FEATURE][A11Y] Indiquer que la saisie des champs est obligatoire sur Pix Orga (PIX-3891).
  orga/app/components/auth/login-form.hbs
  orga/app/components/auth/login-form.js
  orga/app/components/auth/register-form.hbs
  orga/app/components/auth/register-form.js
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/update-form.hbs
  orga/app/styles/components/login-form.scss
  orga/app/styles/components/register-form.scss
  orga/app/styles/globals/colors.scss
  orga/app/styles/globals/forms.scss
  orga/app/styles/globals/pages.scss
  orga/tests/acceptance/campaign-creation_test.js
  orga/tests/acceptance/campaign-update_test.js
  orga/tests/integration/components/auth/login-form_test.js
  orga/tests/integration/components/auth/register-form_test.js
  orga/tests/integration/components/campaign/create-form_test.js
  orga/tests/integration/components/campaign/update-form_test.js
  orga/tests/unit/components/auth/login-form_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3940 [TECH] Suppression d'une méthode non utilisée
  api/tests/test-helper.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3925 [FEATURE][A11Y] Amélioration de l'accessibilité de la navigation sur Pix Orga (PIX-3892).
  orga/app/components/campaign/header/tabs.hbs
  orga/app/components/layout/footer.hbs
  orga/app/components/layout/sidebar.hbs
  orga/app/components/participant/assessment/tabs.hbs
  orga/app/styles/components/layout/topbar.scss
  orga/app/templates/authenticated.hbs
  orga/app/templates/authenticated/team/list.hbs
  orga/tests/acceptance/campaign-details_test.js
  orga/tests/acceptance/campaign-participants-individual-analysis_test.js
  orga/tests/acceptance/campaign-participants-individual-results_test.js
  orga/tests/acceptance/team-list_test.js
  orga/tests/integration/components/layout/footer_test.js
  orga/tests/integration/components/layout/sidebar_test.js
  orga/tests/integration/components/participant/assessment/tabs_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#3875 [FEATURE] Ne donner accès à l'espace surveillant qu'à certains centres de certification (PIX-3770).
  api/lib/application/certification-candidates/certification-candidates-controller.js
  api/lib/application/certification-candidates/index.js
  api/lib/application/error-manager.js
  api/lib/application/preHandlers/end-test-screen-removal-enabled.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/application/sessions/session-for-supervising-controller.js
  api/lib/config.js
  api/lib/domain/errors.js
  api/lib/domain/events/index.js
  api/lib/domain/services/end-test-screen-removal-service.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/end-test-screen-removal-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/lib/infrastructure/utils/string-utils.js
  api/lib/infrastructure/validate-environement-variables.js
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/acceptance/application/certification-candidates/certification-candidates-controller_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/session/session-for-supervising-controller-get_test.js
  api/tests/acceptance/application/session/session-for-supervising-controller-supervise_test.js
  api/tests/integration/infrastructure/repositories/end-test-screen-removal-repository_test.js
  api/tests/integration/infrastructure/repositories/sco-certification-candidate-repository_test.js
  api/tests/unit/application/certification-candidates/certification-candidates-controller_test.js
  api/tests/unit/application/preHandlers/end-test-screen-removal-enabled_test.js
  api/tests/unit/application/session/session-for-supervising-controller_test.js
  api/tests/unit/domain/services/end-test-screen-removal-service_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  api/tests/unit/infrastructure/utils/string-utils_test.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/tests/acceptance/authenticated_test.js
  certif/tests/acceptance/session-details-parameters_test.js
  certif/tests/unit/controllers/authenticated_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3922 [TECH] Création d'une brique Accès V2 au flux de campagne et annihilation du start-or-resume (Pix-4054).
  .eslintrc.yaml
  mon-pix/app/authenticators/oidc.js
  mon-pix/app/components/routes/campaigns/join-sco-information-modal.js
  mon-pix/app/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form.hbs
  mon-pix/app/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form.js
  mon-pix/app/controllers/campaigns/campaign-landing-page.js
  mon-pix/app/controllers/campaigns/join/sco-mediacentre.js
  mon-pix/app/controllers/campaigns/join/student-sco.js
  mon-pix/app/router.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/campaigns/access.js
  mon-pix/app/routes/campaigns/archived-error.js
  mon-pix/app/routes/campaigns/campaign-landing-page.js
  mon-pix/app/routes/campaigns/campaign-not-found.js
  mon-pix/app/routes/campaigns/entry-point.js
  mon-pix/app/routes/campaigns/join.js
  mon-pix/app/routes/campaigns/join/anonymous.js
  mon-pix/app/routes/campaigns/join/sco-mediacentre.js
  mon-pix/app/routes/campaigns/join/student-sco.js
  mon-pix/app/routes/campaigns/restricted/login-or-register-to-access.js
  mon-pix/app/routes/campaigns/start-or-resume.js
  mon-pix/app/routes/login-pe.js
  mon-pix/app/routes/terms-of-service.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/student-sco.scss
  mon-pix/app/templates/campaigns/archived-error.hbs
  mon-pix/app/templates/campaigns/join/sco-mediacentre.hbs
  mon-pix/app/templates/campaigns/join/student-sco.hbs
  mon-pix/app/templates/components/routes/register-form.hbs
  mon-pix/mirage/routes/auth/index.js
  mon-pix/tests/acceptance/login-or-register-to-access-restricted-campaign_test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/integration/components/routes/login-or-register_test.js
  mon-pix/tests/unit/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form_test.js
  mon-pix/tests/unit/controllers/campaigns/campaign-landing-page_test.js
  mon-pix/tests/unit/controllers/campaigns/join/sco-mediacentre_test.js
  mon-pix/tests/unit/controllers/campaigns/join/student-sco_test.js
  mon-pix/tests/unit/routes/campaigns/access_test.js
  mon-pix/tests/unit/routes/campaigns/campaign-landing-page_test.js
  mon-pix/tests/unit/routes/campaigns/entry-point_test.js
  mon-pix/tests/unit/routes/campaigns/join/anonymous_test.js
  mon-pix/tests/unit/routes/campaigns/join_test.js
  mon-pix/tests/unit/routes/campaigns/start-or-resume_test.js
  mon-pix/tests/unit/routes/terms-of-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#3931 [FEATURE] Afficher la colonne "Écran de fin de test vu" sur la page de finalisation de session si le centre de certification n'utilise pas le portail surveillant (PIX-3748)
  api/lib/domain/read-models/AllowedCertificationCenterAccess.js
  api/lib/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer.js
  api/tests/acceptance/application/certification-point-of-contacts/certification-point-of-contacts_test.js
  api/tests/unit/application/certification-point-of-contacts/certification-point-of-contact-controller_test.js
  api/tests/unit/domain/read-models/AllowedCertificationCenterAccess_test.js
  api/tests/unit/domain/services/end-test-screen-removal-service_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer_test.js
  certif/app/components/session-finalization/completed-reports-information-step.hbs
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/models/allowed-certification-center-access.js
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/integration/components/session-finalization/completed-reports-information-step_test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3937 [FEATURE] Changement de la consigne des QCM (PIX-4131).
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3932 [FEATURE] Enregistre le prescrit dans la participation lors de la création de la participation (PIX-4114)
  api/db/migrations/20220111143029_add-schooling-registration-id-campaign-participation.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/usecases/start-campaign-participation.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/schooling-registration-repository.js
  api/tests/integration/domain/usecases/start-campaign-participation_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation.js
  api/tests/unit/domain/models/CampaignParticipation_test.js
  api/tests/unit/domain/usecases/start-campaign-participation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3947 [FEATURE] Permettre l'ajout de l'url de documentation dans le script de création d'organisations PRO (PIX-4118).
  api/lib/infrastructure/repositories/organization-repository.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
Labels: :rocket: Ready to Merge, team-acces

#3934 [CLEANUP] Mise à jour des états possible "validé" des épreuves (PIX-4126)
  api/lib/domain/services/pick-challenge-service.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
Labels: :rocket: Ready to Merge, cross-team, team-contenu

#3943 [FEATURE] Ajout de champs éditables supplémentaires sur les RT dans Pix-Admin (PIX-4129).
  admin/app/components/badges/badge.hbs
  admin/app/components/badges/badge.js
  admin/app/styles/components/badges/badge.scss
  admin/tests/acceptance/authenticated/badges/badges_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/integration/components/badges/badge_test.js
  admin/tests/unit/components/badges/badge_test.js
  api/lib/domain/usecases/update-badge.js
  api/lib/infrastructure/serializers/jsonapi/badge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3933 [FEATURE] Pouvoir éditer le flag "Affichage acquis dans l'export résultats" d'une orga dans Pix Admin (PIX-4103).
  admin/app/components/organizations/information-section.hbs
  admin/app/components/organizations/information-section.js
  admin/mirage/factories/organization.js
  admin/tests/integration/components/organizations/information-section_test.js
  api/lib/domain/usecases/update-organization-information.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3945 [FEATURE] Supprimer la case de fin de test pour les sessions dont le centre est autorisé (PIX-4141)
  admin/app/controllers/authenticated/certifications/certification/informations.js
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/application/sessions/session-controller.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
  certif/app/controllers/authenticated.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/tests/acceptance/authenticated_test.js
  certif/tests/acceptance/session-details-parameters_test.js
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/unit/controllers/authenticated_test.js
  mon-pix/app/controllers/certifications/results.js
  mon-pix/app/models/certification-course.js
  mon-pix/app/templates/certifications/results.hbs
  mon-pix/mirage/serializers/certification-course.js
  mon-pix/tests/acceptance/certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3865 [FEATURE] Ajouter le refresh token (PIX-4017).
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/index.js
  api/lib/application/pole-emplois/pole-emploi-controller.js
  api/lib/config.js
  api/lib/domain/services/refresh-token-service.js
  api/lib/domain/services/token-service.js
  api/lib/domain/usecases/authenticate-anonymous-user.js
  api/lib/domain/usecases/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/domain/usecases/create-access-token-from-refresh-token.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/revoke-refresh-token.js
  api/lib/infrastructure/temporary-storage/InMemoryTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/utils/RedisClient.js
  api/package-lock.json
  api/package.json
  api/sample.env
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/saml-controller_test.js
  api/tests/acceptance/application/users/users-controller-update-password_test.js
  api/tests/integration/application/authentication/index_test.js
  api/tests/test-helper.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/domain/services/refresh-token-service_test.js
  api/tests/unit/domain/services/token-service_test.js
  api/tests/unit/domain/usecases/authenticate-anonymous-user_test.js
  api/tests/unit/domain/usecases/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/create-access-token-from-refresh-token_test.js
  api/tests/unit/domain/usecases/revoke-refresh-token_test.js
  api/tests/unit/infrastructure/temporary-storage/InMemoryTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
  high-level-tests/e2e/cypress/support/commands.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3942 [FEATURE] Afficher le nom du propriétaire dans la page de détail d'une campagne sur Pix Orga (PIX-4074).
  api/lib/domain/read-models/CampaignReport.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-report-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-report-serializer_test.js
  orga/app/components/campaign/header/title.hbs
  orga/app/models/campaign.js
  orga/tests/integration/components/campaign/header/title_test.js
  orga/tests/unit/models/campaign_test.js
Labels: :rocket: Ready to Merge, team-acces

#3948 [FEATURE] Afficher le statut des certifications Pix+ Édu dans la page de détail d'une certification dans Pix Admin (PIX-3993).
  admin/app/models/certification.js
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/unit/models/certification_test.js
  api/lib/domain/models/JuryCertification.js
  api/lib/infrastructure/repositories/jury-certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-certification-serializer.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/tooling/domain-builder/factory/build-jury-certification.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/models/JuryCertification_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-certification-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3939 [FEATURE] Améliorer la gestion de l'affichage du message spécifique aux badges Pix+ Édu dans le certificat pdf (PIX-4139).
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/lib/infrastructure/utils/string-utils.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu.pdf
  api/tests/unit/infrastructure/utils/string-utils_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3951 [FEATURE] Suppression de la barre de progression dans les campagnes FLASH (PIX-3934).
  api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
  api/tests/acceptance/application/assessments/assessment-controller-get_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
  mon-pix/app/models/assessment.js
  mon-pix/app/utils/progress-in-assessment.js
  mon-pix/config/environment.js
  mon-pix/mirage/factories/assessment.js
  mon-pix/tests/acceptance/challenge-flash-in-campaign_test.js
  mon-pix/tests/unit/models/assessment_test.js
  mon-pix/tests/unit/utils/progress-in-assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#3930 [FEATURE] Permettre de filtrer les profils cibles avec les tags Catégories (PIX-3764).
  api/lib/domain/read-models/campaign/TargetProfileForSpecifier.js
  api/lib/infrastructure/repositories/campaign/target-profile-for-specifier-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign/target-profile-for-specifier-serializer.js
  api/tests/integration/infrastructure/repositories/campaign/target-profile-for-specifier-repository_test.js
  api/tests/unit/domain/read-models/campaign/TargetProfileForSpecifier_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign/target-profile-for-specifier-serializer_test.js
  high-level-tests/e2e/README.md
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/create-form.js
  orga/app/models/target-profile.js
  orga/app/styles/globals/forms.scss
  orga/tests/integration/components/campaign/create-form_test.js
  orga/tests/unit/components/campaign/create-form_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3950 [FEATURE] Rafraîchir l'affichage de l'espace surveillant périodiquement (PIX-3660).
  certif/app/routes/session-supervising.js
  certif/config/environment.js
  certif/tests/acceptance/session-supervising_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3964 [FEATURE] Réduire la durée de l'access token (PIX-4166).
  api/lib/config.js
  api/lib/domain/services/token-service.js
  api/lib/domain/usecases/authenticate-external-user.js
  api/lib/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user.js
  api/lib/domain/usecases/get-external-authentication-redirection-url.js
  api/sample.env
  api/tests/integration/domain/services/token-service_test.js
  api/tests/unit/domain/services/token-service_test.js
  api/tests/unit/domain/usecases/authenticate-external-user_test.js
  api/tests/unit/domain/usecases/create-user-and-reconcile-to-schooling-registration-from-external-user_test.js
  api/tests/unit/domain/usecases/get-external-authentication-redirection-url_test.js
Labels: :rocket: Ready to Merge

#3966 [BUGFIX] Afficher qu'une seule fois un même tag dans le formulaire de création de campagne (PIX-4187)
  orga/app/components/campaign/create-form.js
  orga/tests/integration/components/campaign/create-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3952 [FEATURE] Créer des codes INSEE génériques pour Paris, Lyon et Marseille (PIX-4159)
  api/scripts/import-certification-cpf-cities.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/import-certification-cpf-cities_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3955 [FEATURE] Afficher les acquis dans les export CSV en fonction du flag showSkills (PIX-4105)
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3968 [FEATURE] Déplacer le bouton "Télécharger la sélection des sujets" à droite (PIX-4168).
  orga/app/styles/pages/authenticated/preselect-target-profile.scss
Labels: :rocket: Ready to Merge, team-contenu

#3957 [BUGFIX] Ne pas afficher les résultats/attestations des élèves désactivés dans Pix Orga (PIX-4176)
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/lib/infrastructure/repositories/sco-certification-candidate-repository.js
  api/scripts/update-certification-infos.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
  api/tests/integration/infrastructure/repositories/sco-certification-candidate-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certifications-results-for-ls.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3954 [FEATURE] Améliorer l'affichage des colonnes des tableaux sur Pix Orga (PIX-4149).
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/components/student/sco/list.hbs
  orga/app/styles/globals/tables.scss
  orga/app/styles/globals/texts.scss
Labels: :rocket: Ready to Merge, team-acces

#3921 [FEATURE] Ajout des onglets de 'Mes campagnes' et 'Toutes les campagnes' sur Pix Orga (PIX-4087)
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/find-paginated-filtered-organization-campaigns.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/components/campaign/filter/filters.hbs
  orga/app/components/campaign/header/title.hbs
  orga/app/components/campaign/list-header.hbs
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/no-campaign-panel.hbs
  orga/app/controllers/authenticated/campaigns/campaign.js
  orga/app/controllers/authenticated/campaigns/list/all-campaigns.js
  orga/app/controllers/authenticated/campaigns/list/my-campaigns.js
  orga/app/router.js
  orga/app/routes/authenticated/campaigns/campaign.js
  orga/app/routes/authenticated/campaigns/index.js
  orga/app/routes/authenticated/campaigns/list/all-campaigns.js
  orga/app/routes/authenticated/campaigns/list/index.js
  orga/app/routes/authenticated/campaigns/list/my-campaigns.js
  orga/app/styles/components/campaign/list-header.scss
  orga/app/styles/components/campaign/list.scss
  orga/app/styles/components/campaign/no-campaign-panel.scss
  orga/app/templates/authenticated/campaigns.hbs
  orga/app/templates/authenticated/campaigns/campaign.hbs
  orga/app/templates/authenticated/campaigns/list.hbs
  orga/app/templates/authenticated/campaigns/list/all-campaigns.hbs
  orga/app/templates/authenticated/campaigns/list/my-campaigns.hbs
  orga/mirage/config.js
  orga/mirage/factories/campaign.js
  orga/public/icons/icon-campagne-start.svg
  orga/tests/acceptance/authentication_test.js
  orga/tests/acceptance/campaign-details_test.js
  orga/tests/acceptance/campaign-list-all-campaigns_test.js
  orga/tests/acceptance/campaign-list-my-campaigns_test.js
  orga/tests/acceptance/campaign-list_test.js
  orga/tests/acceptance/join_test.js
  orga/tests/acceptance/sco-student-list_test.js
  orga/tests/acceptance/sup-student-import_test.js
  orga/tests/acceptance/switch-organization_test.js
  orga/tests/acceptance/team-creation_test.js
  orga/tests/acceptance/terms-of-service_test.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/campaign/filter/filters_test.js
  orga/tests/integration/components/campaign/list_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign-test.js
  orga/tests/unit/controllers/authenticated/campaigns/list/all-campaigns_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign_test.js
  orga/tests/unit/routes/authenticated/campaigns/list/all-campaigns_test.js
  orga/tests/unit/routes/authenticated/campaigns/list/my-campaigns_test.js
  orga/tests/unit/routes/authenticated/campaigns/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, team-prescription

#3972 [FEATURE] Ajouter l'information responsive sur les sujets de la page de sélection de sujets (PIX-4083)
  api/lib/domain/models/Challenge.js
  api/lib/domain/usecases/get-pix-framework.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/framework-serializer.js
  api/tests/acceptance/application/frameworks/frameworks-controller_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/usecases/get-pix-framework_test.js
  api/tests/unit/infrastructure/datasources/learning-content/challenge-datasource_test.js
  orga/app/components/tube/list.hbs
  orga/app/models/tube.js
  orga/app/styles/pages/authenticated/preselect-target-profile.scss
  orga/config/icons.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#3956 [A11Y] Suppression d'une partie du texte des aria-label dans les QROC (PIX-4174).
  mon-pix/app/components/qrocm-proposal.js
  mon-pix/tests/integration/components/qrocm-proposal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#3962 [FEATURE] Récupérer la liste des membres d'une organisation dans la création et la modification d'une campagne sur Pix Orga (PIX-4147).
  orga/app/components/campaign/create-form.js
  orga/app/controllers/authenticated/campaigns/update.js
  orga/app/models/user.js
  orga/app/routes/authenticated/campaigns/new.js
  orga/app/routes/authenticated/campaigns/update.js
  orga/app/templates/authenticated/campaigns/new.hbs
  orga/app/templates/authenticated/campaigns/update.hbs
  orga/tests/unit/routes/authenticated/campaigns/new_test.js
  orga/tests/unit/routes/authenticated/campaigns/update_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#3973 [BUGFIX] Empêcher le téléchargement quand le bouton est désactivé sur la page de sélection de sujets.
  orga/app/components/tube/list.hbs
Labels: :rocket: Ready to Merge, team-contenu

#3944 [TECH] Empêcher l'accès aux routes API de l'espace surveillant pour un utilisateur non autorisé (PIX-3731)
  api/lib/application/certification-candidates/index.js
  api/lib/application/preHandlers/assessment-supervisor-authorization.js
  api/lib/application/preHandlers/session-supervisor-authorization.js
  api/lib/application/sessions/index.js
  api/lib/infrastructure/repositories/supervisor-access-repository.js
  api/lib/infrastructure/validate-environement-variables.js
  api/tests/acceptance/application/certification-candidates/certification-candidates-controller_test.js
  api/tests/acceptance/application/session/session-for-supervising-controller-get_test.js
  api/tests/integration/infrastructure/repositories/supervisor-access-repository_test.js
  api/tests/unit/application/certification-candidates/index_test.js
  api/tests/unit/application/preHandlers/assessment-supervisor-authorization_test.js
  api/tests/unit/application/preHandlers/session-supervisor-authorization_test.js
  api/tests/unit/application/session/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3974 [FEATURE] Ignorer les écrans de FDT non renseignés dans les critères des sessions "à traiter" (PIX-4171)
  api/lib/domain/events/handle-session-finalized.js
  api/lib/domain/events/index.js
  api/lib/domain/models/FinalizedSession.js
  api/lib/infrastructure/repositories/supervisor-access-repository.js
  api/tests/integration/infrastructure/repositories/supervisor-access-repository_test.js
  api/tests/unit/domain/events/handle-session-finalized_test.js
  api/tests/unit/domain/models/FinalizedSession_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3978 [BUGFIX] Empêcher l'envoi des résultats de campagne ET dans le même temps de retenter (Pix-4238).
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3979 [TECH] Mettre à jour Pix-UI sur Pix Orga
  orga/app/components/auth/login-form.hbs
  orga/app/components/auth/login-form.js
  orga/app/components/auth/register-form.hbs
  orga/app/components/auth/register-form.js
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/create-form.js
  orga/app/components/campaign/update-form.hbs
  orga/app/components/campaign/update-form.js
  orga/app/templates/authenticated/certifications.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription, cross-team

#3965 [TECH] Nettoyage de la duplication de `campaignId` et `campaign` dans `campaign-participations`.
  api/lib/application/users/user-controller.js
  api/lib/domain/events/handle-pole-emploi-participation-finished.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/CampaignParticipation.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/usecases/begin-campaign-participation-improvement.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/reset-scorecard.js
  api/lib/domain/usecases/share-campaign-result.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/integration/domain/event/handle-pole-emploi-participation-finished_test.js
  api/tests/integration/domain/event/handle-pole-emploi-participation-shared_test.js
  api/tests/integration/domain/event/handle-pole-emploi-participation-started_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/domain/usecases/start-campaign-participation_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-finished_test.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-shared_test.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-started_test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/usecases/begin-campaign-participation-improvement_test.js
  api/tests/unit/domain/usecases/compute-campaign-participation-analysis_test.js
  api/tests/unit/domain/usecases/get-campaign-assessment-participation-result_test.js
  api/tests/unit/domain/usecases/get-campaign-assessment-participation_test.js
  api/tests/unit/domain/usecases/get-campaign-profile_test.js
  api/tests/unit/domain/usecases/get-progression_test.js
  api/tests/unit/domain/usecases/reset-scorecard_test.js
  api/tests/unit/domain/usecases/share-campaign-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3986 [FEATURE] Afficher le nombre de sujets sélectionnés dans le bouton de téléchargement (PIX-4167)
  orga/app/components/tube/list.hbs
  orga/app/components/tube/list.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-contenu

#3976 [FEATURE] Retire la case de fin de test sur les fiches d'émargement (pix-3746)
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/infrastructure/files/attendance-sheet/non_sco_attendance_sheet_template.ods
  api/lib/infrastructure/files/attendance-sheet/non_sco_attendance_sheet_template_with_fdt.ods
  api/lib/infrastructure/files/attendance-sheet/sco_attendance_sheet_template.ods
  api/lib/infrastructure/files/attendance-sheet/sco_attendance_sheet_template_with_fdt.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/non_sco_attendance_sheet_template_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/non_sco_attendance_sheet_template_target_with_fdt.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/sco_attendance_sheet_template_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/sco_attendance_sheet_template_target_with_fdt.ods
  api/tests/unit/domain/usecases/get-attendance-sheet_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#3993 [A11Y] Utiliser la même couleur pour le status des participations dans le tableau que celle utilisé sur le graphique des status dans Pix Orga (PIX-4205)
  orga/app/components/campaign/activity/participation-status.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#3981 [FEATURE] Eviter d'avoir plusieurs épreuves du même tube pour une compétence en certification (PIX-4178).
  api/lib/domain/services/certification-challenges-service.js
  api/tests/tooling/domain-builder/factory/build-certification-challenge.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3984 [FEATURE] Envoyer une erreur quand un candidat tente de reprendre son test sans autorisation (PIX-3875)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3991 [FEATURE] Permettre d'activer la facturation des certifications via FT (PIX-4262).
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#3998 [TECH] Corriger le flaky test sur Pix Certif
  certif/tests/acceptance/session-supervising_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#3988 [STYLE] Suppression de l'icone de tuto dans la fenêtre de comparaison de résultats (PIX-4266).
  mon-pix/app/styles/components/_comparison-window.scss
  mon-pix/app/templates/components/comparison-window.hbs
  mon-pix/public/images/icons/comparison-window/icon-tuto.svg
  mon-pix/tests/integration/components/comparison-window_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4001 [TECH] Corriger la connexion avec une auto completion du formulaire de connexion (PIX-4283)
  orga/app/components/auth/login-form.hbs
  orga/app/components/auth/login-form.js
  orga/tests/unit/components/auth/login-form_test.js
Labels: :rocket: Ready to Merge, team-acces, team-prescription, cross-team
