Repository 1024pix/pix, pull requests merged in 2022-06, with the labels that each got.

#4462 FEATURE Ajouter les sous categories E11 et E12 (PIX-4912)
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportCategory.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.js
  certif/app/models/certification-issue-report.js
  certif/tests/integration/components/issue-report-modal/add-issue-report-modal_test.js
  certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields_test.js
  certif/tests/unit/models/certification-issue-report_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4470 [FEATURE] Passer les sessions ayant des certifications non terminées scorées automatiquement en publiable lors de la finalisation (PIX-4848)
  api/lib/domain/models/FinalizedSession.js
  api/scripts/certification/cancel-certifications-and-publish-sessions.js
  api/scripts/certification/check-clea-elligibility.js
  api/scripts/certification/generate-certificate-verification-code.js
  api/scripts/certification/generate-certification-results.js
  api/scripts/certification/generate-certification-test-statistics.js
  api/scripts/certification/generate-last-assessments-score.js
  api/scripts/certification/get-results-certifications-old.js
  api/scripts/certification/get-results-certifications.js
  api/scripts/certification/import-certification-cpf-cities.js
  api/scripts/certification/import-certification-cpf-countries.js
  api/scripts/certification/import-certifications-from-csv.js
  api/scripts/certification/launch-auto-jury-for-session.js
  api/scripts/certification/trigger-autojury-on-finalized-sessions.js
  api/scripts/certification/trigger-session-finalized-handler.js
  api/scripts/certification/update-certification-infos.js
  api/scripts/certification/verify-certificate-code-service_script.js
  api/scripts/recompute-all-score.js
  api/scripts/recompute-assessment-results.js
  api/tests/acceptance/scripts/certification/import-certifications-from-csv_test.js
  api/tests/acceptance/scripts/certification/trigger-session-finalized-handler_test.js
  api/tests/acceptance/scripts/certification/update-certification-infos_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/tooling/domain-builder/factory/build-jury-certification-summary.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/FinalizedSession_test.js
  api/tests/unit/scripts/get-results-certifications-old_test.js
  api/tests/unit/scripts/get-results-certifications_test.js
  api/tests/unit/scripts/import-certification-cpf-cities_test.js
  api/tests/unit/scripts/import-certification-cpf-countries_test.js
  api/tests/unit/scripts/recompute-assessment-results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4432 [FEATURE] Restreindre l'accès aux actions liées aux certifications (PIX-4667)
  admin/app/components/certifications/issue-report.hbs
  admin/app/components/certifications/issue-report.js
  admin/app/controllers/authenticated/certifications/certification/details.js
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/controllers/authenticated/certifications/certification/neutralization.js
  admin/app/templates/authenticated/certifications/certification/details.hbs
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/app/templates/authenticated/certifications/certification/neutralization.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/certifications/certification/details_test.js
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/acceptance/authenticated/certifications/certification/neutralization_test.js
  admin/tests/integration/components/certifications/issue-report_test.js
  api/lib/application/assessment-results/index.js
  api/lib/application/certification-courses/index.js
  api/lib/application/certification-issue-reports/index.js
  api/lib/application/certifications/index.js
  api/tests/unit/application/assessment-results/index_test.js
  api/tests/unit/application/certification-courses/index_test.js
  api/tests/unit/application/certification-issue-reports/index_test.js
  api/tests/unit/application/certifications/index_test.js
  api/tests/unit/application/session/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-certif

#4467 [FEATURE] Ajoute un filtre sur le nom et prénom dans l'onglet Activité d'une campagne (PIX-4580)
  api/db/migrations/20220504150638_add-extension-pg-trgm.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/infrastructure/repositories/campaign-participant-activity-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/integration/domain/usecases/find-paginated-campaign-participant-activities_test.js
  api/tests/integration/infrastructure/repositories/campaign-participant-activity-repository_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/activity/participants-list.js
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/campaign/filter/participation-filters.js
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/routes/authenticated/campaigns/campaign/activity.js
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/integration/components/campaign/activity/participants-activity-list_test.js
  orga/tests/integration/components/campaign/filter/participation-filters_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/activity_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4460 [FEATURE] Utiliser le package ember-testing-library dans Pix App (PIX-4983).
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/account-recovery/find-sco-record_test.js
  mon-pix/tests/integration/components/account-recovery/backup-email-confirmation-form-test.js
Labels: :rocket: Ready to Merge, cross-team

#4471 [TECH] Mieux cibler les erreurs lors de la réinitialisation du mot de passe sur Pix App (PIX-5016)
  api/lib/domain/usecases/update-expired-password.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/unit/domain/usecases/update-expired-password_test.js
Labels: :rocket: Ready to Merge, team-acces

#4477 [BUGFIX] Rajout du nom complet de la compétence sur la bannière de l'assessment (PIX-5027).
  mon-pix/app/styles/components/_certification-banner.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4476 [BUGFIX] Corriger l'affichage multiple des certifications complémentaires dans la liste des certifications d'une session (PIX-5040).
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4484 [FEATURE] Supprimer les refresh tokens d'un utilisateur quand il est anonymisé (PIX-1990).
  api/lib/domain/services/refresh-token-service.js
  api/lib/domain/usecases/anonymize-user.js
  api/lib/infrastructure/temporary-storage/InMemoryTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/TemporaryStorage.js
  api/lib/infrastructure/utils/RedisClient.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
  api/tests/integration/infrastructure/utils/RedisClient_test.js
  api/tests/unit/domain/services/refresh-token-service_test.js
  api/tests/unit/domain/usecases/anonymize-user_test.js
  api/tests/unit/infrastructure/temporary-storage/InMemoryTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/TemporaryStorage_test.js
Labels: :rocket: Ready to Merge, team-acces

#4480 [FEATURE] Améliorer la consistance des seeds (PIX-5046)
  api/db/database-builder/factory/build-certification-candidate.js
  api/db/database-builder/factory/build-certification-course.js
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4459 [BUGFIX] Remettre le style du message d'erreur de connexion en session de certification. (PIX-4984)
  mon-pix/app/components/certification-starter.hbs
  mon-pix/app/styles/components/_certification-joiner.scss
  mon-pix/app/styles/components/_certification-starter.scss
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/campaign-participation-overview/card/disabled_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ended_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4485 [A11Y] Rendre la boulette de pertinence de la phrase explicative non lisible pour les lecteurs d'écran(PIX-4247)
  orga/app/components/campaign/analysis/recommendations.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4468 [FEATURE] Empêcher un candidat de continuer sa certification si la session est finalisée (PIX-4815)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/events/handle-auto-jury.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/models/Assessment_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  mon-pix/app/components/certifications/certification-ender.hbs
  mon-pix/app/controllers/certifications/results.js
  mon-pix/app/models/assessment.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/templates/certifications/results.hbs
  mon-pix/tests/acceptance/certification-course_test.js
  mon-pix/tests/integration/components/certifications/certification-ender_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4488 [BUGFIX] Corriger l'acronyme CNAV en majuscules sur Pix App (PIX-5023).
  mon-pix/tests/acceptance/user-account/connection-methods_test.js
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#4486 [TECH] Afficher une page d'erreur lorsque un identity provider externe nous renvoie une erreur (PIX-5017).
  api/package.json
  mon-pix/app/components/authentication/terms-of-service-pole-emploi.js
  mon-pix/app/controllers/terms-of-service-cnav.js
  mon-pix/app/routes/login-cnav.js
  mon-pix/app/routes/login-pole-emploi.js
  mon-pix/tests/unit/components/authentication/terms-of-service-pole-emploi_test.js
  mon-pix/tests/unit/controllers/terms-of-service-cnav_test.js
  mon-pix/tests/unit/routes/login-cnav_test.js
  mon-pix/tests/unit/routes/login-pole-emploi_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4482 [FEATURE] Afficher un lien pour transmettre le PV de fraude lors de la finalisation de session (PIX-4943)
  certif/app/components/issue-report-modal/fraud-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/fraud-certification-issue-report-fields.js
  certif/tests/integration/components/issue-report-modal/fraud-certification-issue-report-fields_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4489 [FEATURE] Afficher la méthode de connexion CNAV sur la page de détail d'un utilisateur sur Pix Admin (PIX-5022).
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/models/user.js
  admin/tests/integration/components/users/user-detail-personal-information/authentication-method_test.js
  admin/tests/unit/models/user_test.js
Labels: :rocket: Ready to Merge, team-acces

#4501 [TECH] Corriger la version de l'API.
  api/package-lock.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4491 [BUGFIX] Rendre les signalements E11 et E12 impactant (PIX-5054).
  api/lib/domain/models/CertificationIssueReport.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4487 [FEATURE] Afficher le niveau Pix des certifications complémentaire Pix+ Édu de 1er degré dans l'export csv des résultats (PIX-5043)
  api/lib/domain/models/CertificationResult.js
  api/lib/infrastructure/repositories/certification-result-repository.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/integration/infrastructure/repositories/certification-result-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/unit/domain/models/CertificationResult_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4495 [FEATURE] Distinguer les Profils Cibles avec gabarit dans l'écran de détail
  api/lib/domain/models/TargetProfileTemplate.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer.js
  api/tests/integration/application/target-profile/index_test.js
  api/tests/integration/application/target-profile/target-profile-controller_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-with-learning-content.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#4507 [TECH] Mettre en cohérence la seed de candidat SCO certifié (PIX-5080).
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/db/seeds/data/organizations-sco-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#4490 [TECH] Supprimer le repository Pole Emploi tokens (PIX-4935).
  api/lib/domain/usecases/authentication/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/authentication/create-user-from-pole-emploi.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/pole-emploi-tokens-repository.js
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/acceptance/application/pole-emploi-controller_test.js
  api/tests/acceptance/application/pole-emploi/token-route-post_test.js
  api/tests/acceptance/application/pole-emploi/users-route-post_test.js
  api/tests/integration/infrastructure/repositories/pole-emploi-tokens-repository_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/authentication/create-user-from-pole-emploi_test.js
Labels: :rocket: Ready to Merge, team-acces

#4499 [FEATURE] Harmoniser le fonctionnement des champs de recherche dans Pix Orga (PIX-5057).
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#4500 [BUGFIX] Corriger le scoring des certifications Pix+ Édu lors d'une neutralisation (PIX-5068)
  api/lib/infrastructure/repositories/partner-certification-scoring-repository.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4506 [FEATURE] Mettre à jour le wording du texte explicatif lorsque le signalement C1 est sélectionné (PIX-4946).
  certif/app/models/certification-issue-report.js
  certif/tests/integration/components/issue-report-modal/candidate-information-change-certification-issue-report-fields_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4513 [BUGFIX] Corriger l'export des résultats de certification pour les noms de classe ayant des caractères spéciaux (PIX-5079).
  api/lib/application/organizations/organization-controller.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/controllers/authenticated/certifications.js
  orga/app/services/file-saver.js
  orga/tests/unit/controllers/authenticated/certifications_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4509 [FEATURE] Mise à jour des templates de l'attestation de certification Pix (PIX-4968)
  api/lib/infrastructure/utils/pdf/files/attestation-template-with-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/attestation-template.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_several_pages.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu_temporary.pdf
  api/tests/integration/infrastructure/utils/pdf/files/attestation-pix-vierge-clea.pdf
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4510 [FEATURE] Améliorer le message de la page j'ai un code (Pix-4976)
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/tests/acceptance/fill-in-campaign-code_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4514 [FEATURE] Afficher le nom du créateur de l'organisation dans Pix Admin (PIX-3099)
  admin/app/components/organizations/information-section.hbs
  admin/app/models/organization.js
  admin/tests/integration/components/organizations/information-section_test.js
  api/lib/domain/models/OrganizationForAdmin.js
  api/lib/infrastructure/repositories/organization-for-admin-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-for-admin-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
  api/tests/unit/domain/models/OrganizationForAdmin_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#4512 [FEATURE] Empêcher les utilisateurs ayant le rôle métier d'accéder aux pages certifications sur Pix Admin (PIX-5062).
  admin/app/components/menu-bar.hbs
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/routes/authenticated/certifications.js
  admin/app/routes/authenticated/certifications/certification.js
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/integration/components/menu-bar_test.js
  admin/tests/unit/routes/authenticated/certifications/certification/certification_test.js
  admin/tests/unit/routes/authenticated/certifications/certification_test.js
  api/lib/application/complementary-certification-course-results/index.js
  api/tests/integration/application/complementary-certification-course-results/complementary-certification-course-results-controller_test.js
  api/tests/unit/application/complementary-certification-course-results/index_test.js
Labels: :rocket: Ready to Merge, team-acces

#4394 [TECH] Ajout de méthodes dans les seeds pour rendre un utilisateur certifiable sans avoir à importer des données réelles
  api/db/seeds/data/certification/certification-data.js
  api/db/seeds/data/certification/tooling.js
  api/db/seeds/data/certification/user-profiles-builder.js
  api/db/seeds/seed.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/infrastructure/repositories/challenge-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#4483 [TECH][ADR] Nommer les contraintes dans la BDD en cas de conflit (PIX-5048)
  .prettierrc
  docs/adr/0033-utiliser-noms-contraintes-metiers-lisibilite.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4496 [FEATURE] Remplacer le commentaire global de session par une liste de choix (PIX-4951).
  api/db/database-builder/factory/build-session.js
  api/db/migrations/20220610085239_add-columns-incident-and-joining-issue-to-session.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  certif/app/adapters/session.js
  certif/app/components/session-finalization-step-container.hbs
  certif/app/components/session-finalization/complementary-information-step.hbs
  certif/app/components/session-finalization/complementary-information-step.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/models/session.js
  certif/app/styles/app.scss
  certif/app/styles/components/session-finalization-step-container.scss
  certif/app/styles/components/session-finalization/complementary-information-step.scss
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/public/icons/edit-file.svg
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/integration/components/session-finalization-step-container_test.js
  certif/tests/integration/components/session-finalization/complementary-information-step_test.js
  certif/tests/unit/adapters/session_test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4518 [FEATURE] Afficher les infos complémentaires de la session dans PixAdmin (PIX-4952)
  admin/app/models/session.js
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/tests/acceptance/authenticated/sessions/session/informations_test.js
  admin/tests/unit/models/session_test.js
  api/lib/application/sessions/index.js
  api/lib/config.js
  api/lib/domain/models/JurySession.js
  api/lib/infrastructure/serializers/jsonapi/jury-session-serializer.js
  api/tests/acceptance/application/session/session-controller-get-jury-session_test.js
  api/tests/integration/infrastructure/repositories/sessions/jury-session-repository_test.js
  api/tests/tooling/domain-builder/factory/build-jury-session.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-session-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#4527 [TECH] Amélioration des consignes des QCU et QCM (PIX-5151).
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4526 [A11Y] Ajout de traductions pour les recommandations (PIX-5049).
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  orga/app/components/campaign/analysis/recommendation-indicator.js
  orga/tests/integration/components/campaign/analysis/recommendation-indicator_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4520 [FEATURE] Mettre à jour les attestations de certification suite au renouvellement France Compétences (PIX-5093)
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
  api/lib/infrastructure/utils/pdf/files/attestation-template-with-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/attestation-template-with-professionalizing-message-and-with-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/attestation-template-with-professionalizing-message-and-without-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/attestation-template-without-professionalizing-message-and-with-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/attestation-template-without-professionalizing-message-and-without-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/attestation-template.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_several_pages.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu_temporary.pdf
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4534 [FEATURE] Ajouter un commentaire jury dans le csv des résultats pour les certifications rejetées automatiquement(PIX-5116)
  api/db/database-builder/factory/build-assessment-result.js
  api/lib/config.js
  api/lib/domain/events/handle-certification-rescoring.js
  api/lib/domain/models/CertificationResult.js
  api/lib/infrastructure/repositories/certification-result-repository.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/integration/infrastructure/repositories/certification-result-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/tooling/domain-builder/factory/build-certification-result.js
  api/tests/unit/domain/events/handle-certification-rescoring_test.js
  api/tests/unit/domain/models/CertificationResult_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4523 [TECH] Préciser la cause de la certification en erreur lorsque l'utilisateur n'a pas répondu à toutes les questions (PIX-5084)
  api/lib/domain/models/CertificationContract.js
  api/tests/unit/domain/models/CertificationContract_test.js
  api/tests/unit/domain/services/scoring/scoring-certification-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#4524 [FEATURE] Fusionner les stratégies de résolution des signalements E1 et E2 (PIX-5115).
  api/lib/domain/models/CertificationIssueReportResolutionStrategies.js
  api/tests/unit/domain/models/CertificationIssueReportResolutionStrategies_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4530 [FEATURE] Augmenter la taille des macarons dans les certificats et certificats partagés (PIX-5126).
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4529 [FEATURE] Affichage d'une explication pour les catégories C7 et C8 sur la page de finalisation de session
  certif/app/components/issue-report-modal/non-blocking-candidate-issue-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/non-blocking-technical-issue-certification-issue-report-fields.hbs
  certif/app/styles/components/add-issue-report-modal.scss
  certif/tests/integration/components/issue-report-modal/non-blocking-candidate-issue-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/non-blocking-technical-issue-certification-issue-report-fields_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4533 [BUGFIX] Les message de format de code de vérification de l'attestation sont incohérents (PIX-5161).
  api/lib/application/certifications/index.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  mon-pix/tests/unit/controllers/fill-in-certificate-verification-code_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4537 [FEATURE] Retirer le bandeau de renseignement du mail de destinataire de la certification
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/list.js
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/list.hbs
  certif/tests/unit/controllers/authenticated/sessions/details_test.js
  certif/tests/unit/controllers/authenticated/sessions/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4539 [BUGFIX] Afficher les dates formattées que si elles existent dans Pix Admin (PIX-5141).
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/components/users/user-detail-personal-information/user-overview.js
  admin/tests/integration/components/users/user-detail-personal-information/authentication-method_test.js
Labels: :rocket: Ready to Merge, team-acces

#4543 [BUGFIX] Ne pas afficher le nouveau membre dans la liste si une erreur survient (PIX-5183)
  admin/app/components/team/add-member.js
  admin/tests/acceptance/authenticated/team/add-member_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4538 [TECH] Renommer expiredDate en expirationDate dans la table organization-places (PIX-5065).
  admin/app/components/organizations/places.hbs
  admin/app/models/organization-place.js
  admin/tests/acceptance/authenticated/organizations/places_test.js
  admin/tests/integration/components/organizations/places_test.js
  api/db/database-builder/factory/build-organization-place.js
  api/db/migrations/20220617144325-rename-expiredDate-in-expirationDate-in-organization-places-table.js
  api/db/seeds/data/organization-places-pro-builder.js
  api/lib/domain/read-models/OrganizationPlace.js
  api/lib/infrastructure/repositories/organizations/organization-place-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/organization-place-serializer.js
  api/tests/acceptance/application/organizations/find-organization-places_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organizations/organization-place-repository_test.js
  api/tests/tooling/domain-builder/factory/build-organization-place.js
  api/tests/unit/domain/read-models/OrganizationPlace_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/organization-place-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4540 [BUGFIX] Supprimer l'erreur `TransitionAborted` lors du passage du didacticiel (PIX-5167).
  mon-pix/app/routes/campaigns/assessment/tutorial.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4521 [TECH] Supprimer des exemples de configuration de debug front
  certif/config/environment.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#4532 [BUGFIX] Admin: Tooltips de la navbar cachées par les infos de la certification
  admin/app/templates/authenticated/certifications/certification/details.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4545 [FEATURE] Ne pas mentionner la valeur professionnalisante de la certification Pix par France Compétences dans les attestations téléchargées depuis le domaine .org (PIX-5162).
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  mon-pix/app/components/user-certifications-detail-header.js
  mon-pix/tests/integration/components/user-certifications-detail-header_test.js
  orga/app/controllers/authenticated/certifications.js
  orga/tests/unit/controllers/authenticated/certifications_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4497 [TECH] Mutualiser le code des interconnexions openid (PIX-5078)
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/cnav/cnav-controller.js
  api/lib/application/pole-emploi/pole-emploi-controller.js
  api/lib/domain/models/AuthenticationSessionContent.js
  api/lib/domain/services/authentication/authentication-service-registry.js
  api/lib/domain/services/authentication/cnav-authentication-service.js
  api/lib/domain/services/authentication/pole-emploi-authentication-service.js
  api/lib/domain/usecases/authentication/authenticate-cnav-user.js
  api/lib/domain/usecases/authentication/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/authentication/create-user-from-cnav.js
  api/lib/domain/usecases/authentication/create-user-from-pole-emploi.js
  api/lib/domain/usecases/create-user-from-external-identity-provider.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/cnav/users-route-post_test.js
  api/tests/acceptance/application/pole-emploi/token-route-post_test.js
  api/tests/acceptance/application/pole-emploi/users-route-post_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/cnav/cnav-controller_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/domain/models/AuthenticationSessionContent_test.js
  api/tests/unit/domain/models/PoleEmploiTokens_test.js
  api/tests/unit/domain/services/authentication/authentication-session-service_test.js
  api/tests/unit/domain/services/authentication/cnav-authentication-service_test.js
  api/tests/unit/domain/services/authentication/pole-emploi-authentication-service_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-cnav-user_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/authentication/create-user-from-cnav_test.js
  api/tests/unit/domain/usecases/authentication/create-user-from-pole-emploi_test.js
  api/tests/unit/domain/usecases/create-user-from-external-identity-provider_test.js
  mon-pix/app/authenticators/pole-emploi.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces, Design Review OK

#4555 [BUGFIX] Garder le champ vide quand l'information de dernière connexion n'est pas disponible (PIX-5193).
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/tests/integration/components/users/user-detail-personal-information/authentication-method_test.js
Labels: :rocket: Ready to Merge, team-acces

#4553 [FEATURE] Mettre à jour le nom de l'étape des signalements dans la finalisation de session (PIX-5186)
  certif/app/styles/components/session-finalization-step-container.scss
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/tests/acceptance/session-finalization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4552 [FEATURE] Afficher une phrase avec le niveau final obtenu à la certification Pix sur le certificat/certificat partagé et attestation (PIX-5136)
  api/lib/domain/read-models/CertifiedBadgeImage.js
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu.pdf
  api/tests/tooling/domain-builder/factory/build-certified-badge-image.js
  api/tests/unit/domain/read-models/CertifiedBadgeImage_test.js
  mon-pix/app/components/user-certifications-detail-result.hbs
  mon-pix/tests/integration/components/user-certifications-detail-result_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4559 [FEATURE] Améliorer l'info pour les sessions déjà finalisées sur la page de détails (PIX-5182)
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/tests/acceptance/session-details-parameters_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4519 [TECH] Mettre à jour les dépendances certif (PIX-5107)
  certif/app/components/app-modal.js
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/confirmation-modal.hbs
  certif/app/components/session-supervising/header.hbs
  certif/app/styles/app.scss
  certif/app/styles/globals/app-modal.scss
  certif/app/styles/pages/session-supervising.scss
  certif/config/ember-cli-update.json
  certif/package-lock.json
  certif/package.json
  certif/tests/index.html
  certif/tests/integration/components/login-form_test.js
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/tests/integration/components/session-supervising/header_test.js
  certif/tests/test-helper.js
  certif/tests/unit/components/app-modal_test.js
Labels: Tech Review OK, Func Review OK, team-certif

#4558 [TECH] Mise à jour des dépendances de l'API (PIX-5212)
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_several_pages.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test_full_edu_temporary.pdf
  api/tests/integration/infrastructure/utils/pdf/kit-surveillant-with-long-labels_expected.pdf
  api/tests/integration/infrastructure/utils/pdf/kit-surveillant_expected.pdf
  api/tests/tooling/domain-builder/factory/build-certification-attestation.js
  api/tests/tooling/domain-builder/factory/build-private-certificate-with-competence-tree.js
  api/tests/tooling/domain-builder/factory/build-private-certificate.js
  api/tests/tooling/domain-builder/factory/build-shareable-certificate.js
  api/tests/unit/domain/read-models/AllowedCertificationCenterAccess_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#4564 [TECH] Met à jour knex en 2.1.0 (PIX-5209)
  api/db/migrations/20220516142918_split-pix-edu-complementary-certifications.js
  api/lib/domain/usecases/update-certification-center.js
  api/lib/infrastructure/repositories/badge-acquisition-repository.js
  api/lib/infrastructure/repositories/campaign-participant-repository.js
  api/lib/infrastructure/repositories/complementary-certification-habilitation-repository.js
  api/lib/infrastructure/repositories/organization-invited-user-repository.js
  api/lib/infrastructure/repositories/organizations-to-attach-to-target-profile-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/repositories/target-profile-share-repository.js
  api/package-lock.json
  api/package.json
  api/scripts/mark-users-for-TermsOfService-revalidation.js
  api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
  api/tests/acceptance/scripts/bigint/answer/switch-tmp-bigint-tables-to-answer-ke_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/unit/domain/models/CertificationIssueReportResolutionStrategies_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4167 [TECH] API : Logguer en pretty-print 👩‍💻 si la sortie standard est envoyée vers un terminal
  api/lib/config.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4522 [TECH] Créer un nouvelle méthode pour le scénario de changement de mot de passe sur Pix App (PIX-4977).
  api/lib/application/passwords/index.js
  api/lib/application/passwords/password-controller.js
  api/lib/domain/usecases/update-expired-password.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/password-controller_test.js
  api/tests/integration/application/passwords/index_test.js
  api/tests/integration/application/passwords/password-controller_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/passwords/index_test.js
  api/tests/unit/application/passwords/password-controller_test.js
  api/tests/unit/domain/usecases/update-expired-password_test.js
  high-level-tests/e2e/cypress/fixtures/users.json
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  mon-pix/app/adapters/reset-expired-password-demand.js
  mon-pix/mirage/routes/post-expired-password-updates.js
  mon-pix/tests/unit/adapters/reset-expired-password-demand_test.js
  mon-pix/tests/unit/components/update-expired-password_test.js
Labels: :rocket: Ready to Merge, team-acces

#4343 [TECH] Calculer les résultats d'une participation à une campagne de manière asynchrone avec PgBoss (PIX-4520).
  api/Procfile
  api/db/migrations/20220415140322_add-extension-for-pgboss.js
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/application/competence-evaluations/competence-evaluation-controller.js
  api/lib/application/run-jobs.js
  api/lib/domain/events/CampaignParticipationResultsShared.js
  api/lib/domain/events/Event.js
  api/lib/domain/events/index.js
  api/lib/infrastructure/events/DependenciesBuilder.js
  api/lib/infrastructure/events/EventBus.js
  api/lib/infrastructure/events/EventBusBuilder.js
  api/lib/infrastructure/events/subscribers/LogEvent.js
  api/lib/infrastructure/events/subscribers/ScheduleParticipationResultCalculationJob.js
  api/lib/infrastructure/jobs/JobPgBoss.js
  api/lib/infrastructure/jobs/JobQueue.js
  api/lib/infrastructure/jobs/campaign-result/ParticipationResultCalculationJob.js
  api/lib/infrastructure/jobs/campaign-result/ParticipationResultCalculationJobHandler.js
  api/package-lock.json
  api/package.json
  api/scripts/database/pg-boss-migration.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/integration/infrastructure/jobs/JobQueue_test.js
  api/tests/integration/infrastructure/jobs/campaign-result/ParticipationResultCalculationJobHandler_test.js
  api/tests/integration/infrastructure/jobs/campaign-result/ParticipationResultCalculationJob_test.js
  api/tests/unit/application/campaign-participations/campaign-participation-controller_test.js
  api/tests/unit/infrastructure/events/EventBus_test.js
  api/tests/unit/infrastructure/events/handlers/LogEvent_test.js
  api/tests/unit/infrastructure/events/handlers/ScheduleParticipationResultCalculationJob_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4416 [FEATURE] Limiter les requêtes par utilisateur sur /api/token
  .circleci/config.yml
  api/lib/application/authentication/index.js
  api/lib/application/http-errors.js
  api/lib/config.js
  api/lib/infrastructure/utils/redis-rate-limit.js
  api/lib/infrastructure/validate-environement-variables.js
  api/lib/plugins.js
  api/package-lock.json
  api/package.json
  api/sample.env
  api/tests/acceptance/application/authentication-route_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains

#4548 [TECH] Mentionner les configurations de développement les plus utiles.
  INSTALLATION.md
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4574 [TECH] Lire les variables d'environnement à un seul endroit.
  api/.eslintrc.yaml
  api/lib/.eslintrc.js
  api/lib/application/healthcheck/healthcheck-controller.js
  api/lib/application/run-jobs.js
  api/lib/config.js
  api/lib/domain/services/sco-account-recovery-service.js
  api/lib/infrastructure/validate-environement-variables.js
  api/package-lock.json
  api/package.json
  api/tests/unit/domain/services/sco-account-recovery-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4576 [FEATURE] Affichage du nombre de participations dans l'onglet élèves (PIX-5169).
  api/lib/domain/models/UserWithOrganizationLearner.js
  api/lib/infrastructure/repositories/organization-learner-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-with-organization-learner-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-learner-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-organization-learner-serializer_test.js
  orga/app/components/student/sco/list.hbs
  orga/app/models/student.js
  orga/tests/integration/components/students/sco/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4556 [BUGFIX] Supprimer le flickering en arrivant sur certaines pages de Pix App (PIX-4684).
  mon-pix/app/routes/certifications/join.js
  mon-pix/app/routes/profile.js
  mon-pix/app/routes/user-certifications/index.js
  mon-pix/app/routes/user-tests.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, team-evaluation

#4550 [TECH] Glimmerizer les dernières routes de Pix APP.
  mon-pix/app/routes/application.js
  mon-pix/app/routes/campaigns/assessment/tutorial.js
  mon-pix/app/routes/inscription.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4511 [FEATURE] Permettre de désactiver l'accès à Pix Admin (PIX-4195)
  admin/app/components/organizations/member-item.hbs
  admin/app/components/team/add-member.js
  admin/app/components/team/list.hbs
  admin/app/components/team/list.js
  admin/app/models/admin-member.js
  admin/app/styles/app.scss
  admin/app/styles/components/team/list.scss
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/organizations/memberships-management_test.js
  admin/tests/acceptance/authenticated/team/add-member_test.js
  admin/tests/acceptance/authenticated/team/list_test.js
  admin/tests/integration/components/organizations/member-item_test.js
  admin/tests/integration/components/team/list_test.js
  api/lib/application/admin-members/admin-member-controller.js
  api/lib/application/admin-members/index.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/deactivate-admin-member.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/admin-member-repository.js
  api/tests/acceptance/application/admin-members/admin-member-details-route-get_test.js
  api/tests/acceptance/application/admin-members/admin-members-route-get_test.js
  api/tests/acceptance/application/admin-members/admin-members-routes_test.js
  api/tests/acceptance/application/admin-members/index_test.js
  api/tests/integration/infrastructure/repositories/admin-member-repository_test.js
  api/tests/unit/application/admin-members/admin-member-controller_test.js
  api/tests/unit/application/admin-members/index_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/deactivate-admin-member_test.js
Labels: :rocket: Ready to Merge, team-acces

#4560 [FEATURE] Retirer son évaluation d'un tutoriel (PIX-4725).
  api/db/database-builder/factory/build-tutorial-evaluation.js
  api/db/migrations/20220616131338_add-column-status-to-tutorial-evaluations.js
  api/lib/application/tutorial-evaluations/index.js
  api/lib/application/tutorial-evaluations/tutorial-evaluations-controller.js
  api/lib/domain/models/TutorialEvaluation.js
  api/lib/domain/usecases/add-tutorial-evaluation.js
  api/lib/infrastructure/orm-models/TutorialEvaluation.js
  api/lib/infrastructure/repositories/tutorial-evaluation-repository.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-evaluation-attributes.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-evaluation-serializer.js
  api/tests/acceptance/application/tutorials/tutorial-evaluations-controller_test.js
  api/tests/integration/infrastructure/repositories/tutorial-evaluation-repository_test.js
  api/tests/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/application/tutorial-evaluations/index_test.js
  api/tests/unit/application/tutorial-evaluations/tutorial-evaluations-controller_test.js
  api/tests/unit/domain/usecases/add-tutorial-evaluation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tutorial-evaluation-serializer_test.js
  mon-pix/app/adapters/tutorial-evaluation.js
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/components/tutorials/card.js
  mon-pix/app/models/tutorial-evaluation.js
  mon-pix/app/models/tutorial.js
  mon-pix/mirage/factories/tutorial.js
  mon-pix/mirage/routes/put-tutorial-evaluation.js
  mon-pix/mirage/serializers/tutorial.js
  mon-pix/tests/acceptance/tutorial-actions_test.js
  mon-pix/tests/acceptance/user-tutorials/actions_test.js
  mon-pix/tests/acceptance/user-tutorials/recommended_test.js
  mon-pix/tests/integration/components/tutorials/card_test.js
  mon-pix/tests/unit/adapters/tutorial-evaluation_test.js
  mon-pix/tests/unit/models/tutorial-evaluation_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4579 [FEATURE] Affichage du nombre de participations dans l'onglet étudiants (PIX-5172).
  orga/app/components/student/sup/list.hbs
  orga/tests/integration/components/students/sup/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4547 [FEATURE] Intégrer la sélection de sujets dans la création de profil cible (PIX-5012)
  admin/app/components/target-profiles/create-target-profile-form.hbs
  admin/app/components/target-profiles/create-target-profile-form.js
  admin/app/components/target-profiles/tubes-selection.hbs
  admin/app/components/target-profiles/tubes-selection.js
  admin/app/components/target-profiles/tubes-selection/areas.hbs
  admin/app/components/target-profiles/tubes-selection/competence.hbs
  admin/app/components/target-profiles/tubes-selection/form.hbs
  admin/app/components/target-profiles/tubes-selection/form.js
  admin/app/components/target-profiles/tubes-selection/tube.hbs
  admin/app/components/target-profiles/tubes-selection/tube.js
  admin/app/controllers/authenticated/target-profiles/new.js
  admin/app/router.js
  admin/app/routes/authenticated/target-profiles/new.js
  admin/app/routes/authenticated/target-profiles/tubes-selection.js
  admin/app/styles/app.scss
  admin/app/styles/components/target-profiles/generate-target-profile-form.scss
  admin/app/styles/components/target-profiles/tubes-selection.scss
  admin/app/templates/authenticated/target-profiles/list.hbs
  admin/app/templates/authenticated/target-profiles/new.hbs
  admin/app/templates/authenticated/target-profiles/tubes-selection.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/target-profiles/list_test.js
  admin/tests/acceptance/authenticated/target-profiles/new_test.js
  admin/tests/integration/components/target-profiles/create-target-profile-form_test.js
  admin/tests/integration/components/target-profiles/tubes-selection/tube_test.js
  admin/tests/integration/components/target-profiles/tubes-selection_test.js
  admin/tests/unit/components/target-profiles/tubes-selection_test.js
  admin/tests/unit/controllers/authenticated/target-profiles/new_test.js
  admin/tests/unit/routes/authenticated/target-profiles/tubes-selection_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#4566 [FEATURE] ETQ Pix Certif user, JV pouvoir supprimer une session (PIX-5150)
  api/lib/application/error-manager.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/delete-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/tests/acceptance/application/session/session-controller-delete_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/delete-session_test.js
  certif/app/adapters/session-summary.js
  certif/app/components/session-delete-confirm-modal.hbs
  certif/app/components/session-summary-list.hbs
  certif/app/components/session-summary-list.js
  certif/app/models/session-summary.js
  certif/app/styles/components/session-summary-list.scss
  certif/mirage/config.js
  certif/tests/acceptance/session-list_test.js
  certif/tests/integration/components/session-delete-confirm-modal_test.js
  certif/tests/integration/components/session-summary-list_test.js
  certif/tests/unit/adapters/session-summary_test.js
  certif/tests/unit/components/session-summary-list_test.js
  certif/tests/unit/models/session-summary_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4585 [TECH] Linter les fonctionnalités de NodeJs dans l'API.
  api/.eslintrc.yaml
  api/lib/.eslintrc.js
  api/lib/application/run-jobs.js
  api/lib/infrastructure/logger.js
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, cross-team

#4583 [FEATURE] Ajouter un bouton raccourcis pour le dashboard metabase (PIX-3861)
  admin/app/components/certification-centers/information.hbs
  admin/app/components/certification-centers/information.js
  admin/app/styles/components/certification-centers/information.scss
  admin/config/environment.js
  admin/tests/integration/components/certification-centers/information_test.js
  admin/tests/unit/components/certification-centers/information_test.js
  admin/tests/unit/components/organizations/information-section_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4549 [FEATURE] Les agents PIX désactivés ne peuvent plus accéder à Pix Admin (PIX-5189)
  api/db/database-builder/factory/build-user.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/usecases/checkUserHasRoleCertif.js
  api/lib/application/usecases/checkUserHasRoleMetier.js
  api/lib/application/usecases/checkUserHasRoleSuperAdmin.js
  api/lib/application/usecases/checkUserHasRoleSupport.js
  api/lib/domain/models/AdminMember.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/infrastructure/orm-models/User.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/integration/application/security-pre-handlers_test.js
  api/tests/integration/infrastructure/repositories/admin-member-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/application/usecases/checkUserHasRoleCertif_test.js
  api/tests/unit/application/usecases/checkUserHasRolePixMaster_test.js
  api/tests/unit/application/usecases/checkUserHasRolePixMetier_test.js
  api/tests/unit/application/usecases/checkUserHasRolePixSupport_test.js
  api/tests/unit/application/usecases/checkUserHasRoleSuperAdmin_test.js
  api/tests/unit/domain/models/AdminMember_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
Labels: :rocket: Ready to Merge, team-acces

#4600 [FEATURE] Ramener le profil utilisateur dans Pix Admin - Partie 1 (PIX-5130).
  admin/README.md
  admin/app/models/profile.js
  admin/app/models/scorecard.js
  admin/app/models/user.js
  admin/app/routes/authenticated/users/get.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-for-admin-serializer.js
  api/tests/acceptance/application/users/users-controller-get-user-details-for-admin_test.js
  api/tests/acceptance/application/users/users-controller-get-user-profile-for-admin_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation
