Repository 1024pix/pix, pull requests merged in 2022-10, with the labels that each got.

#5013 [TECH] Tracer les réponses ne pouvant être insérées en BDD à cause d'un encodage incorrect
  api/lib/config.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-captains

#4992 [TECH] Ajout d'une ligne de séparation entre les thématiques lors de la création d'un profil cible (PIX-5786).
  admin/app/styles/components/target-profiles/tubes-selection.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5018 [FEATURE] Permettre de ne pas saisir de nombres négatifs dans un champ dans une épreuve sur Pix App (PIX-5815)
  mon-pix/app/components/challenge-item-qroc.hbs
  mon-pix/app/components/challenge-item-qroc.js
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/tests/integration/components/challenge-item-qroc_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5001 [FEATURE] Script de création de lien entre les formations et les profils cibles (PIX-5774)
  api/db/database-builder/factory/build-training.js
  api/db/database-builder/factory/index.js
  api/lib/infrastructure/repositories/training-repository.js
  api/scripts/create-target-profile-trainings.js
  api/tests/integration/scripts/create-target-profile-trainings_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5012 [BUGFIX] Ne plus retirer un prescrit importé de l'onglet "élèves/étudiants" si on supprime toutes ses participations (PIX-5811)
  api/lib/infrastructure/repositories/sco-organization-participant-repository.js
  api/lib/infrastructure/repositories/sup-organization-participant-repository.js
  api/tests/integration/infrastructure/repositories/sco-organization-participant-repository_test.js
  api/tests/integration/infrastructure/repositories/sup-organization-participant-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5021 [BUGFIX] Corriger l'affichage du nombre de sujets pour un profil-cible lors de la création d'une campagne (PIX-5829).
  api/lib/infrastructure/repositories/campaign/target-profile-for-specifier-repository.js
  api/tests/integration/infrastructure/repositories/campaign/target-profile-for-specifier-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-contenu

#4907 [FEATURE] Ajout de logs associé a la requête lors de l'import siecle
  api/lib/infrastructure/monitoring-tools.js
  api/lib/infrastructure/utils/xml/siecle-file-streamer.js
  api/tests/integration/infrastructure/utils/xml/siecle-file-streamer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains

#5022 [BUGFIX] Empêcher le crash de l'API lors de l'appel /api/account-recovery (PIX-5830).
  api/lib/domain/usecases/account-recovery/update-user-for-account-recovery.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5028 [BUGFIX] Supprimer la hauteur fixe pour les boutons de la bannière des tutos.
  mon-pix/app/styles/pages/_user-tutorials.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4998 [FEATURE] Ajouter la date de certification pour les étudiants certifiables (Pix-5565)
  api/lib/domain/read-models/SupOrganizationParticipant.js
  api/lib/infrastructure/repositories/sup-organization-participant-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/sup-organization-participants-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/sup-organization-participant-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/sup-organization-participants-serializer_test.js
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/models/sup-organization-participant.js
  orga/tests/integration/components/sup-organization-participant/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5017 [BUGFIX] Retourner une erreur lorsque le téléchargement des résultats n'est pas sur le bon type de campagne (PIX-5822)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5029 [TECH] Ajout du thème Halloween pour le template de pull request.
  docs/pull_request_template.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4957 [FEATURE] Génération du fichier des résultats Cléa numérique (PIX-5375)
  api/db/seeds/data/certification/certification-cpf-city-builder.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-with-clea-certified-candidate-controller.js
  api/lib/domain/read-models/CleaCertifiedCandidate.js
  api/lib/domain/usecases/get-clea-certified-candidate-by-session.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/clea-certified-candidate-repository.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/acceptance/application/session/session-with-clea-certified-candidate-controller-get-clea-certified-candidate-data-csv.js
  api/tests/integration/infrastructure/repositories/clea-certified-candidate-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/tooling/domain-builder/factory/build-clea-certified-candidate.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-with-clea-certified-candidate-controller_test.js
  api/tests/unit/domain/read-models/CleaCertifiedCandidate_test.js
  api/tests/unit/domain/usecases/get-clea-certified-candidate-by-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4991 [TECH] Script de génération d'attestations de certifications (PIX-5799).
  api/db/seeds/data/certification/certification-centers-builder.js
  api/scripts/certification/generate-certification-attestations-by-session-ids.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5032 [BUGFIX] Corrige la récupération des profils cible d'une organisation (PIX-5961)
  api/lib/domain/read-models/campaign/TargetProfileForSpecifier.js
  api/lib/infrastructure/repositories/campaign/target-profile-for-specifier-repository.js
  api/tests/integration/infrastructure/repositories/campaign/target-profile-for-specifier-repository_test.js
  api/tests/unit/domain/read-models/campaign/TargetProfileForSpecifier_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign/target-profile-for-specifier-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains, cross-team

#5031 [FEATURE] Ajouter le filtre de certificabilité pour les organisations Pro (PIX-5559)
  api/lib/application/organizations/helpers.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/infrastructure/repositories/organization-participant-repository.js
  api/tests/integration/infrastructure/repositories/organization-participant-repository_test.js
  api/tests/integration/infrastructure/repositories/sco-organization-participant-repository_test.js
  api/tests/unit/application/organizations/helpers.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/components/organization-participant/list.hbs
  orga/app/controllers/authenticated/organization-participants/list.js
  orga/app/routes/authenticated/organization-participants/list.js
  orga/app/templates/authenticated/organization-participants/list.hbs
  orga/tests/acceptance/organization-participant-list_test.js
  orga/tests/integration/components/organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4949 [FEATURE] Dans pix-admin ajouter un onglet Centres de certification dans la fiche des utilisateurs (PIX-5583)
  admin/app/components/certification-centers/memberships-section.hbs
  admin/app/components/users/certification-center-memberships.hbs
  admin/app/components/users/certification-center-memberships.js
  admin/app/router.js
  admin/app/routes/authenticated/users/get/certification-centers.js
  admin/app/styles/app.scss
  admin/app/styles/components/users/get.scss
  admin/app/templates/authenticated/users/get.hbs
  admin/app/templates/authenticated/users/get/certification-center-memberships.hbs
  admin/mirage/serializers/certification-center-membership.js
  admin/mirage/serializers/user.js
  admin/tests/acceptance/authenticated/certification-centers/get_test.js
  admin/tests/acceptance/authenticated/users/get_test.js
  admin/tests/integration/components/users/certification-center-memberships_test.js
  admin/tests/unit/components/users/certification-center-memberships_test.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/find-certification-center-memberships-by-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-membership-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-organization-for-admin-serializer.js
  api/tests/acceptance/application/users/find-user-certification-centers-for-admin-route-get_test.js
  api/tests/acceptance/application/users/users-controller-get-user-details-for-admin_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/find-certification-center-memberships-by-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-membership-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-organization-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#5036 [BUGFIX] App: Ne pas rediriger un utilisateur GAR sur la page de connexion (PIX-5950)
  mon-pix/app/routes/application.js
  mon-pix/app/services/session.js
  mon-pix/tests/unit/routes/application_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5025 [FEATURE] Réajuster l'affichage des détails de session à la maquette (PIX-5788)
  certif/app/styles/pages/authenticated/sessions/details.scss
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, hacktoberfest-accepted

#5020 [FEATURE] Pouvoir identifier qui est le référent Pix d'un centre de certification (PIX-5795)
  api/lib/infrastructure/serializers/jsonapi/certification-center-membership-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-membership-serializer_test.js
  certif/app/components/members-list.hbs
  certif/app/components/members-list.js
  certif/app/models/member.js
  certif/app/styles/app.scss
  certif/app/styles/components/members-list.scss
  certif/tests/integration/components/members-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5007 [FEATURE] Rejeter la finalisation de la session si un motif d'abandon a été saisi pour un candidat qui a fini son test (PIX-5149)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/tests/acceptance/session-finalization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5019 [FEATURE] Refactorer la sélection du niveau jury d'une certification complémentaire (PIX-5800).
  api/lib/application/complementary-certification-course-results/index.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/read-models/ComplementaryCertificationCourseResultsForJuryCertification.js
  api/lib/domain/read-models/ComplementaryCertificationCourseResultsForJuryCertificationWithExternal.js
  api/lib/domain/usecases/save-jury-complementary-certification-course-result.js
  api/lib/infrastructure/repositories/complementary-certification-course-result-repository.js
  api/lib/infrastructure/repositories/jury-certification-repository.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/complementary-certification-course-results/complementary-certification-course-results-controller_test.js
  api/tests/integration/application/complementary-certification-course-results/complementary-certification-course-results-controller_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-course-result-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-course-result-for-certification-with-external.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/read-models/ComplementaryCertificationCourseResultsForJuryCertificationWithExternal_test.js
  api/tests/unit/domain/read-models/ComplementaryCertificationCourseResultsForJuryCertification_test.js
  api/tests/unit/domain/usecases/save-jury-complementary-certification-course-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-certification-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5024 [FEATURE] Ne permet pas de lancer de container worker si on veut le démarrer dans le process web
  api/Procfile
  api/index.js
  api/lib/application/run-jobs.js
  api/package.json
  api/scripts/start.sh
  api/worker.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#5042 [TECH] Connecter la nouvelle table trainings (PIX-5776)
  api/db/database-builder/factory/build-target-profile-training.js
  api/db/database-builder/factory/index.js
  api/db/seeds/data/trainings-builder.js
  api/db/seeds/seed.js
  api/lib/domain/models/Training.js
  api/lib/infrastructure/datasources/learning-content/index.js
  api/lib/infrastructure/datasources/learning-content/training-datasource.js
  api/lib/infrastructure/repositories/training-repository.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/unit/infrastructure/datasources/learning-content/training-datasource_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, hacktoberfest-accepted

#5043 [BUGFIX] Réparer l'alignement de l'intitulé de champ et de son input dans une épreuve QROC de type phrase (PIX-5970)
  mon-pix/app/styles/components/_challenge-item.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5039 [TECH] Ajout du monitoring de pg-boss
  api/lib/config.js
  api/package.json
  api/sample.env
  api/worker.js
Labels: :rocket: Ready to Merge, team-captains, cross-team, hacktoberfest-accepted

#5010 [FEATURE] Pouvoir afficher tout type de palier (seuil et niveau) (PIX-5690).
  admin/app/components/stages/stage.hbs
  admin/app/components/stages/stage.js
  admin/app/components/target-profiles/stages.hbs
  admin/app/components/target-profiles/stages.js
  admin/app/components/target-profiles/stages/new-stage.hbs
  admin/app/components/target-profiles/stages/stage.hbs
  admin/app/models/stage.js
  admin/app/styles/components/target-profiles/stages.scss
  admin/tests/integration/components/stages/stage_test.js
  admin/tests/integration/components/target-profiles/stages_test.js
  admin/tests/unit/components/target-profiles/stages_test.js
  admin/tests/unit/models/stage_test.js
  api/db/seeds/data/stages-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/infrastructure/serializers/jsonapi/stage-serializer.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/tooling/domain-builder/factory/build-stage.js
  api/tests/unit/infrastructure/serializers/jsonapi/stage-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5045 [TECH] Supprime les caractères null dans les réponses envoyées
  api/lib/infrastructure/serializers/jsonapi/answer-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/answer-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team, hacktoberfest-accepted

#5046 [A11Y] Ajouter une description au tableau de la liste des étudiants (Pix-5973)
  orga/app/components/sup-organization-participant/list.hbs
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5044 [A11Y] Ajouter une description au tableau complexe de la liste des élèves (Pix-4253)
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/routes/authenticated/organization-participants/list.js
  orga/app/routes/authenticated/sco-organization-participants/list.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5038 [FEATURE] Ajouter le filtre de certificabilité pour les organisations Sup (PIX-5563)
  api/db/seeds/data/organizations-sup-builder.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/infrastructure/repositories/sup-organization-participant-repository.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/sup-organization-participant-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/components/organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/components/sup-organization-participant/list.js
  orga/app/controllers/authenticated/sco-organization-participants/list.js
  orga/app/controllers/authenticated/sup-organization-participants/list.js
  orga/app/routes/authenticated/sup-organization-participants/list.js
  orga/app/templates/authenticated/sco-organization-participants/list.hbs
  orga/app/templates/authenticated/sup-organization-participants/list.hbs
  orga/tests/acceptance/sup-organization-participant-list_test.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/tests/unit/controllers/authenticated/sup-organization-participants/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5047 [BUGFIX] Réparer la céation d'un nouveau centre de certification dans Pix Admin (PIX-5976)
  api/lib/application/certification-centers/index.js
  api/tests/acceptance/application/certification-center-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5048 [TECH] Passage à la version 19.0.1 de Pix UI (PIX-5978)
  mon-pix/app/components/account-recovery/confirmation-step.hbs
  mon-pix/app/components/account-recovery/update-sco-record-form.hbs
  mon-pix/app/components/authentication/login-or-register-oidc.hbs
  mon-pix/app/components/authentication/terms-of-service-oidc.hbs
  mon-pix/app/components/certification-results-page.hbs
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/components/user-tutorials/filters/item-checkbox.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5049 [FEATURE] Permettre de cacher la page "Mes formations" lors de son développement (PIX-5981).
  api/db/database-builder/factory/build-target-profile-training.js
  api/lib/config.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, hacktoberfest-accepted

#5055 [TECH] Supprimer la gestion spécifique de UNAUTHORIZED
  api/lib/application/pre-response-utils.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5034 [DX] Abaisse le niveau d'assurance du wording dans le template de PR
  docs/pull_request_template.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, hacktoberfest-accepted, no-review-app

#5033 [DOCUMENTATION] Clarifier le contexte du projet pour les contributions externes
  CONTRIBUTING.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, hacktoberfest-accepted, no-review-app

#5054 [FEATURE] Afficher un empty state visuel plus text dans l'onglet Etudiants (PIX-5570).
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/components/ui/empty-state.hbs
  orga/app/styles/components/ui/empty-state.scss
  orga/app/styles/components/ui/index.scss
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/tests/integration/components/ui/empty-state_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5062 [TECH] En cas d'erreur sur le format de userInfoContent, ajouter userInfoContent dans les logs
  api/lib/domain/services/authentication/oidc-authentication-service.js
Labels: :rocket: Ready to Merge, team-acces

#5059 [TECH] Position du titre et des infos "date" et "heure de début" (PIX-5752)
  certif/app/templates/authenticated/sessions/details.hbs
Labels: :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5052 [FEATURE] Ajout d'un filtre par nom et prénom dans l'onglet étudiants (PIX-5567)
  api/lib/application/organizations/index.js
  api/lib/infrastructure/repositories/sup-organization-participant-repository.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/sup-organization-participant-repository_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-sup-participants_test.js
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/controllers/authenticated/sup-organization-participants/list.js
  orga/app/routes/authenticated/sup-organization-participants/list.js
  orga/app/templates/authenticated/sup-organization-participants/list.hbs
  orga/tests/acceptance/sup-organization-participant-list_test.js
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/tests/unit/controllers/authenticated/sup-organization-participants/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5041 [FEATURE] Afficher un message dans le tableau des élèves quand l'organisation n'a aucun élève (PIX-5569).
  api/db/seeds/data/organizations-sco-builder.js
  orga/app/components/sco-organization-participant/list.hbs
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5063 [BUGFIX] Correction du bug de la modale (PIX-5979)
  mon-pix/app/components/user-certifications-detail-result.hbs
  mon-pix/app/styles/components/_certification-starter.scss
  mon-pix/app/styles/components/_user-account.scss
  mon-pix/app/styles/components/_user-certifications-detail-competence.scss
  mon-pix/app/styles/components/_user-certifications-detail-header.scss
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/styles/components/authentication/_login-or-register-oidc.scss
  mon-pix/app/styles/components/authentication/_oidc-reconciliation.scss
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/app/styles/pages/_fill-in-certificate-verification-code.scss
  mon-pix/app/styles/pages/_send-profile.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5015 [TECH] Rendre des pages de Pix Certif plus accessible (+ testing library dans les tests) (PIX-5546).
  admin/config/environment.js
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/import-candidates.hbs
  certif/app/components/login-form.hbs
  certif/app/components/session-summary-list.hbs
  certif/app/styles/components/login-form.scss
  certif/app/styles/components/login-session-supervisor-form.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/globals/panels.scss
  certif/app/styles/globals/texts.scss
  certif/app/styles/pages/authenticated/sessions.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/app/styles/pages/terms-of-service.scss
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/app/templates/authenticated/sessions/new.hbs
  certif/app/templates/authenticated/sessions/update.hbs
  certif/app/templates/terms-of-service.hbs
  certif/config/environment.js
  certif/tests/acceptance/session-details-parameters_test.js
  certif/tests/acceptance/session-list_test.js
  certif/tests/acceptance/session-new_test.js
  certif/tests/acceptance/session-update_test.js
  certif/tests/integration/components/login-form_test.js
  certif/tests/integration/components/login-session-supervisor-form_test.js
  certif/tests/integration/components/session-summary-list_test.js
  certif/tests/integration/components/user-logged-menu_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, cross-team, hacktoberfest-accepted

#5051 [FEATURE] Après une connexion SSO, afficher prénom et nom qui seront utilisés pour créer un compte Pix
  api/lib/application/authentication/oidc/oidc-controller.js
  api/lib/domain/usecases/authentication/authenticate-oidc-user.js
  api/tests/unit/application/authentication/oidc/oidc-controller_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-oidc-user_test.js
  mon-pix/app/components/authentication/login-or-register-oidc.hbs
  mon-pix/app/components/authentication/login-or-register-oidc.js
  mon-pix/app/controllers/authentication/login-or-register-oidc.js
  mon-pix/app/routes/authentication/login-oidc.js
  mon-pix/app/styles/components/authentication/_login-or-register-oidc.scss
  mon-pix/app/templates/authentication/login-or-register-oidc.hbs
  mon-pix/tests/integration/components/authentication/login-or-register-oidc_test.js
  mon-pix/tests/unit/routes/authentication/login-oidc_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5026 [FEATURE] Dans Pix Admin afficher la liste des invitations à un centre de certification (PIX-4027)
  admin/app/adapters/certification-center-invitation.js
  admin/app/components/certification-centers/invitations.hbs
  admin/app/components/menu-bar.hbs
  admin/app/controllers/authenticated/certification-centers/get.js
  admin/app/controllers/authenticated/certification-centers/get/team.js
  admin/app/controllers/authenticated/organizations/get/team.js
  admin/app/models/certification-center-invitation.js
  admin/app/router.js
  admin/app/routes/authenticated/certification-centers/get.js
  admin/app/routes/authenticated/certification-centers/get/invitations.js
  admin/app/routes/authenticated/certification-centers/get/team.js
  admin/app/services/error-response-handler.js
  admin/app/styles/globals/nav.scss
  admin/app/templates/authenticated/certification-centers/get.hbs
  admin/app/templates/authenticated/certification-centers/get/invitations.hbs
  admin/app/templates/authenticated/certification-centers/get/team.hbs
  admin/mirage/config.js
  admin/mirage/factories/certification-center-invitation.js
  admin/tests/acceptance/authenticated/certification-centers/get/team_test.js
  admin/tests/acceptance/authenticated/certification-centers/get_test.js
  admin/tests/integration/components/certification-centers/get/invitations_test.js
  admin/tests/integration/components/menu-bar_test.js
  admin/tests/unit/adapters/certification-center-invitation_test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get/team_test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get_test.js
  admin/tests/unit/routes/authenticated/certification-centers/get/invitations_test.js
  admin/tests/unit/routes/authenticated/certification-centers/get/team_test.js
  admin/tests/unit/routes/authenticated/certification-centers/get_test.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/models/CertificationCenterInvitation.js
  api/lib/domain/usecases/find-pending-certification-center-invitations.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-center-invitation-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-invitation-serializer.js
  api/tests/acceptance/application/certifications/index_test.js
  api/tests/integration/domain/usecases/find-pending-certification-center-invitations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-invitation-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces, hacktoberfest-accepted

#5065 [FEATURE] Admin: Permettre la modification des informations du DPO pour un centre de certification (PIX-5267)
  .gitignore
  admin/app/components/certification-centers/information-edit.hbs
  admin/app/components/certification-centers/information-edit.js
  admin/app/components/certification-centers/information-view.hbs
  admin/app/components/certification-centers/information-view.js
  admin/app/components/certification-centers/information.hbs
  admin/app/components/certification-centers/information.js
  admin/app/controllers/authenticated/certification-centers/get.js
  admin/app/styles/globals/global.scss
  admin/tests/acceptance/authenticated/certification-centers/get_test.js
  admin/tests/integration/components/certification-centers/information-edit_test.js
  admin/tests/integration/components/certification-centers/information-view_test.js
  admin/tests/integration/components/certification-centers/information_test.js
  admin/tests/unit/components/certification-centers/information-edit_test.js
  admin/tests/unit/components/certification-centers/information-view_test.js
  admin/tests/unit/components/certification-centers/information_test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get_test.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/domain/usecases/update-certification-center.js
  api/lib/infrastructure/repositories/certification-center-for-admin-repository.js
  api/lib/infrastructure/repositories/complementary-certification-habilitation-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-for-admin-serializer.js
  api/tests/acceptance/application/certification-centers/index_test.js
  api/tests/integration/domain/usecases/update-certification-center_test.js
  api/tests/unit/domain/usecases/update-certification-center_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5076 [TECH] Enregistrer les formations recommandées (PIX-6038).
  api/db/migrations/20221017085933_create-user-recommended-trainings.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5053 [FEATURE] Pouvoir modifier tout type de palier (PIX-5691)
  admin/app/components/stages/stage.hbs
  admin/app/components/stages/stage.js
  admin/app/components/stages/update-stage.hbs
  admin/app/components/stages/update-stage.js
  admin/app/components/stages/view-stage.hbs
  admin/app/components/target-profiles/stages.hbs
  admin/app/components/target-profiles/stages/stage.hbs
  admin/app/components/target-profiles/target-profile.hbs
  admin/app/components/target-profiles/target-profile.js
  admin/app/controllers/authenticated/target-profiles/target-profile.js
  admin/app/controllers/authenticated/target-profiles/target-profile/stages/stage.js
  admin/app/models/target-profile.js
  admin/app/router.js
  admin/app/routes/authenticated/target-profiles/target-profile.js
  admin/app/routes/authenticated/target-profiles/target-profile/stages/stage.js
  admin/app/templates/authenticated/stages/stage.hbs
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/app/templates/authenticated/target-profiles/target-profile/stages/stage.hbs
  admin/tests/acceptance/authenticated/target-profiles/target-profile/stages/stage_test.js
  admin/tests/integration/components/stages/stage_test.js
  admin/tests/integration/components/stages/update-stage_test.js
  admin/tests/unit/components/update-stage_test.js
  admin/tests/unit/controllers/authenticated/target-profiles/target-profile/stages/stage_test.js
  admin/tests/unit/routes/authenticated/target-profiles/target-profile/stages/stage_test.js
  api/lib/application/stages/index.js
  api/lib/domain/models/TargetProfileForAdminNewFormat.js
  api/lib/domain/usecases/update-stage.js
  api/lib/infrastructure/repositories/stage-repository.js
  api/lib/infrastructure/serializers/jsonapi/stage-serializer.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-for-admin-new-format-serializer.js
  api/tests/integration/application/target-profile/index_test.js
  api/tests/unit/application/stages/index_test.js
  api/tests/unit/domain/usecases/update-stage_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/stage-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-for-admin-new-format-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, hacktoberfest-accepted, team-contenu

#5071 [TECH] Monitorer les temps d'execution des jobs dans pgboss (PIX-6011).
  api/lib/infrastructure/events/EventHandlerDependenciesBuilder.js
  api/lib/infrastructure/jobs/JobDependenciesBuilder.js
  api/lib/infrastructure/jobs/JobPgBoss.js
  api/lib/infrastructure/jobs/campaign-result/ParticipationResultCalculationJobHandler.js
  api/lib/infrastructure/jobs/campaign-result/SendSharedParticipationResultsToPoleEmploiHandler.js
  api/lib/infrastructure/jobs/monitoring/MonitoredJobHandler.js
  api/lib/infrastructure/jobs/monitoring/MonitoredJobQueue.js
  api/lib/infrastructure/jobs/monitoring/MonitoringJobExecutionTimeHandler.js
  api/worker.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#5078 [FEATURE] Améliorer la visibilité du mot de passe dans la pop-up 'Gestion du compte Pix de l'élève' sur Pix Orga (PIX-6016)
  orga/app/styles/components/manage-authentication-method-modal.scss
Labels: :rocket: Ready to Merge, team-acces

#5069 [BUGFIX] Permettre la récupération de compte SCO si l'utilisateur à une autre méthode que le GAR sur Pix App (PIX-5832).
  api/lib/domain/usecases/account-recovery/update-user-for-account-recovery.js
  api/tests/acceptance/application/account-recovery/account-recovery-route-patch_test.js
  api/tests/unit/domain/usecases/account-recovery/update-user-for-account-recovery_test.js
Labels: :rocket: Ready to Merge, team-acces, hacktoberfest-accepted

#5064 [A11Y] Rendre les liens vers le profils du prescrit plus explicites (PIX-5164)
  orga/app/components/campaign/activity/participants-list.hbs
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/integration/components/campaign/activity/participants-list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5079 [FEATURE] Enregistrer les contenus formatifs que nous recommandons aux utilisateurs (PIX-6040).
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/usecases/handle-training-recommendation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/repositories/user-recommended-training-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/integration/infrastructure/repositories/user-recommended-training-repository_test.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/domain/usecases/handle-training-recommendation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5080 [FEATURE] Afficher le code d'accès candidat à la session dans l'espace surveillant (PIX-6012)
  api/lib/domain/read-models/SessionForSupervising.js
  api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-for-supervising-serializer.js
  api/tests/integration/infrastructure/repositories/sessions/session-for-supervising-repository_test.js
  api/tests/tooling/domain-builder/factory/build-session-for-supervising.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-for-supervising-serializer_test.js
  certif/app/components/session-supervising/header.hbs
  certif/app/models/session-for-supervising.js
  certif/app/styles/components/session-supervising/header.scss
  certif/tests/integration/components/session-supervising/header_test.js
  certif/tests/unit/models/session-for-supervising_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5068 [BUGFIX] Tracer une erreur détaillée de l'appel API dentity provider dans le flow oidc (PIX-5784)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/services/authentication/authentication-service-registry.js
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/lib/infrastructure/http/errors-helper.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/services/authentication/authentication-service-registry_test.js
  api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
  api/tests/unit/infrastructure/http/errors-helper_test.js
Labels: :rocket: Ready to Merge, team-acces, cross-team

#5077 [BUGFIX] L'erreur n'est complètement tracée lors d'un appel en erreur à un partenaire
  api/lib/infrastructure/http/http-agent.js
  api/tests/unit/infrastructure/http/http-agent_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5084 [BUGFIX] Permettre aux propositions du QCM d'être sur deux lignes (PIX-6051)
  mon-pix/app/styles/components/_rounded-panel.scss
Labels: :rocket: Ready to Merge, team-evaluation, Design Review OK, hacktoberfest-accepted

#5087 [FEATURE] Monitore l'état du pool de connexion knex
  api/server.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5088 [BUGFIX] Stoppe le monitoring d'oppsy a l'arrêt du serveur
  api/index.js
  api/server.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5074 [FEATURE] Prendre en compte un nouveau critère de validation de RT défini par des sujets cappés lors de la vérification d'acquisition d'un RT (PIX-5700)
  api/db/database-builder/factory/build-badge-criterion.js
  api/db/migrations/20221014135401_add-column-capped-tubes-json-in-badge-criteria-table.js
  api/lib/domain/events/index.js
  api/lib/domain/models/BadgeCriterion.js
  api/lib/domain/models/BadgeForCalculation.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/domain/services/certification-badges-service.js
  api/lib/domain/usecases/get-user-campaign-assessment-result.js
  api/lib/domain/usecases/handle-badge-acquisition.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/badge-for-calculation-repository.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/repositories/learning-content-repository.js
  api/scripts/prod/compute-badge-acquisitions.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/integration/domain/usecases/handle-badge-acquisition_test.js
  api/tests/integration/infrastructure/repositories/badge-for-calculation-repository_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/learning-content-repository_test.js
  api/tests/integration/scripts/prod/compute-badge-acquisitions_test.js
  api/tests/tooling/domain-builder/factory/build-badge-criterion-for-calculation.js
  api/tests/tooling/domain-builder/factory/build-badge-for-calculation.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/BadgeForCalculation_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
  api/tests/unit/domain/services/certification-badges-service-test.js
  api/tests/unit/domain/services/certification-badges-service_test.js
  api/tests/unit/domain/usecases/get-user-campaign-assessment-result_test.js
  api/tests/unit/domain/usecases/handle-badge-acquisition_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, hacktoberfest-accepted, team-contenu

#5090 [TECH] Tracer l'erreur HTTP complète lors de l'appel à un client lorsque la propriété data n'est pas alimentée
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/lib/infrastructure/http/errors-helper.js
  api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
  api/tests/unit/infrastructure/http/errors-helper_test.js
  api/tests/unit/infrastructure/http/http-agent_test.js
Labels: :rocket: Ready to Merge, team-acces, cross-team

#3803 [TECH] Eviter le code involontairement non testé.
  .circleci/config.yml
  INSTALLATION.md
  api/.ls-lint.yml
  api/index.js
  api/lib/infrastructure/serializers/jsonapi/response-objects/unprocessable-entity-error.js
  api/lib/infrastructure/validate-environment-variables.js
  api/nyc.config.js
  api/package-lock.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4982 [FEATURE] Compresser les exports CPF (PIX-5399)
  api/lib/domain/services/cpf-certification-xml-export-service.js
  api/lib/infrastructure/external-storage/cpf-external-storage.js
  api/lib/infrastructure/external-storage/s3-utils.js
  api/lib/infrastructure/jobs/cpf-export/handlers/create-and-upload.js
  api/lib/infrastructure/jobs/cpf-export/handlers/planner.js
  api/tests/integration/infrastructure/jobs/cpf-export/handlers/create-and-upload_test.js
  api/tests/integration/infrastructure/jobs/cpf-export/handlers/export.xml
  api/tests/tooling/domain-builder/factory/build-cpf-certification-result.js
  api/tests/unit/domain/services/cpf-certification-xml-export-service_test.js
  api/tests/unit/infrastructure/external-storage/cpf-external-storage_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/create-and-upload_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/planner_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5095 [BUGFIX] QCM - Recentrer les inputs (PIX-6072)
  mon-pix/app/styles/components/_qcu-proposals.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, hacktoberfest-accepted

#5040 [FEATURE] App: Définir "fr" comme langue par défaut
  mon-pix/app/routes/application.js
  mon-pix/app/services/session.js
  mon-pix/tests/unit/routes/application_test.js
Labels: :rocket: Ready to Merge, team-acces

#5086 [FEATURE] Retourner les contenus formatifs dans PixApp (PIX-6052)
  api/db/database-builder/factory/build-user-recommended-training.js
  api/db/database-builder/factory/index.js
  api/lib/domain/read-models/UserRecommendedTraining.js
  api/lib/domain/usecases/find-campaign-participation-trainings.js
  api/lib/infrastructure/repositories/user-recommended-training-repository.js
  api/scripts/fill-user-recommended-trainings.js
  api/tests/acceptance/application/campaign-participation-controller_test.js
  api/tests/integration/infrastructure/repositories/user-recommended-training-repository_test.js
  api/tests/integration/scripts/fill-user-recommended-trainings_test.js
  api/tests/unit/domain/usecases/find-campaign-participation-trainings_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5101 [TECH] Supprimer le feature toggle sur les filtres des tutoriels (PIX-5686).
  api/lib/config.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  mon-pix/app/components/tutorials/header.hbs
  mon-pix/app/models/feature-toggle.js
  mon-pix/tests/acceptance/user-tutorials/recommended_test.js
  mon-pix/tests/acceptance/user-tutorials/saved_test.js
  mon-pix/tests/integration/components/tutorials/header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5060 [FEATURE] Pouvoir séléctionner le référent d'un centre de certification habilité CléA (PIX-5809)
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-certification-center-referer.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/tests/acceptance/application/certification-center-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/domain/usecases/update-certification-center-referer_test.js
  certif/app/adapters/member.js
  certif/app/components/members-list.hbs
  certif/app/components/select-referer-modal.hbs
  certif/app/controllers/authenticated/team.js
  certif/app/models/member.js
  certif/app/routes/authenticated/team.js
  certif/app/styles/app.scss
  certif/app/styles/components/select-referer-modal.scss
  certif/app/styles/pages/authenticated/team.scss
  certif/app/templates/authenticated/team.hbs
  certif/mirage/config.js
  certif/tests/acceptance/team_test.js
  certif/tests/integration/components/members-list_test.js
  certif/tests/unit/adapters/member_test.js
  certif/tests/unit/controllers/team_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5105 [BUGFIX] Corrige le passage de parametre de script d'import (PIX-6097)
  api/scripts/certification/import-certification-cpf-cities.js
Labels: :rocket: Ready to Merge, team-certif

#5102 [FEATURE] Ajouter le logo de l'éditeur sur les contenus formatifs sur Pix App (PIX-6074)
  mon-pix/app/components/training/card.hbs
  mon-pix/app/styles/components/_training-card.scss
  mon-pix/tests/integration/components/training/card_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5104 [BUGFIX] Les badges ne sont plus affichés dans PixOrga (PIX-6050).
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/tests/integration/infrastructure/repositories/campaign-report-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5110 [TECH] Corriger le path de l'url du logo des éditeurs du contenu formatifs (PIX-6108).
  mon-pix/app/components/training/card.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5085 [BUGFIX] Afficher la colonne référent seulement si le centre est habilité CléA (PIX-5989)
  certif/app/components/members-list.hbs
  certif/app/components/members-list.js
  certif/app/templates/authenticated/team.hbs
  certif/tests/integration/components/members-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5103 [TECH] Isoler la configuration de nodemon
  api/nodemon.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5099 [FEATURE] Ajout des mentions RGPD pour le SCO (PIX-5316)
  mon-pix/app/components/form-textfield-date.hbs
  mon-pix/app/components/routes/campaigns/sco-form.hbs
  mon-pix/app/components/routes/register-form.hbs
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/styles/components/_signup-form.scss
  mon-pix/app/styles/globals/_text.scss
  mon-pix/app/styles/pages/_join-restricted-campaign.scss
  mon-pix/tests/integration/components/routes/campaigns/sco-form_test.js
  mon-pix/tests/integration/components/routes/register-form_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5082 [TECH] Suppression du feature toggle pour la réconciliation de compte SSO sur Pix App (PIX-5688).
  api/lib/application/authentication/oidc/index.js
  api/lib/application/authentication/oidc/oidc-controller.js
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/config.js
  api/lib/domain/usecases/authentication/authenticate-oidc-user.js
  api/lib/infrastructure/validate-environment-variables.js
  api/sample.env
  api/tests/acceptance/application/account-recovery/account-recovery-route-get_test.js
  api/tests/acceptance/application/account-recovery/account-recovery-route-patch_test.js
  api/tests/acceptance/application/authentication/oidc/check-reconciliation-route-post_test.js
  api/tests/acceptance/application/authentication/oidc/reconcile-route-post_test.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/integration/application/authentication/oidc/index_test.js
  api/tests/unit/application/authentication/oidc/oidc-controller_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-oidc-user_test.js
  mon-pix/app/authenticators/oidc.js
  mon-pix/app/components/authentication/terms-of-service-oidc.hbs
  mon-pix/app/components/authentication/terms-of-service-oidc.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/router.js
  mon-pix/app/routes/authentication/login-oidc.js
  mon-pix/app/templates/terms-of-service-oidc.hbs
  mon-pix/tests/acceptance/oidc/oidc-authentication-flow_test.js
  mon-pix/tests/acceptance/oidc/start-campaigns-workflow-for-oidc-partner_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/integration/components/authentication/terms-of-service-oidc_test.js
  mon-pix/tests/unit/authenticators/oidc_test.js
  mon-pix/tests/unit/components/authentication/terms-of-service-oidc_test.js
  mon-pix/tests/unit/routes/authentication/login-oidc_test.js
  mon-pix/tests/unit/routes/terms-of-service-oidc_test.js
  mon-pix/tests/unit/services/feature-toggles_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces, hacktoberfest-accepted

#5109 [TECH] Supprimer la rétrocompatibilité des tutoriels (PIX-6101).
  api/lib/infrastructure/serializers/jsonapi/tutorial-serializer.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tutorial-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5108 [BUGFIX] Le bouton d'affichage de l'alternative textuelle ne garde pas le focus (PIX-2528).
  mon-pix/app/components/challenge-statement.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5107 [TASK] Api : Création d'un script de migration pour l'ajout des informations des DPOs pour des centres de certifications (PIX-5265)
  api/lib/domain/usecases/update-certification-center-data-protection-officer-information.js
  api/scripts/add-or-update-certification-centers-dpo-infos.js
  api/tests/integration/domain/usecases/update-certification-center-data-protection-officer-information_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces, no-review-app

#5106 [TASK] Api : Création d'un script de migration pour l'ajout des informations des DPOs pour des organisations (PIX-4468)
  api/lib/domain/usecases/update-organization-data-protection-officer-information.js
  api/scripts/add-or-update-organizations-dpo-infos.js
  api/tests/integration/domain/usecases/update-organization-data-protection-officer-information_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces, no-review-app

#5091 [TECH] Améliorer le temps d'exécution du processus d'anonymisation d'un utilisateur (PIX-5951)
  api/lib/domain/services/refresh-token-service.js
  api/lib/infrastructure/temporary-storage/InMemoryTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/TemporaryStorage.js
  api/lib/infrastructure/utils/RedisClient.js
  api/tests/integration/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
  api/tests/integration/infrastructure/utils/RedisClient_test.js
  api/tests/unit/domain/services/refresh-token-service_test.js
  api/tests/unit/infrastructure/temporary-storage/InMemoryTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/TemporaryStorage_test.js
Labels: :rocket: Ready to Merge, team-acces

#5037 [PERFORMANCE] Ajout d'un index sur la colonne targetProfileId de la table target-profile_tubes
  api/db/migrations/20221010075029_add-index-to-target-profile-tube.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5089 [FEATURE] Créer la double mire d'inscription/connexion Pix Certif (PIX-5005)
  certif/app/components/auth/login-or-register.hbs
  certif/app/components/auth/login-or-register.js
  certif/app/components/auth/register-form.hbs
  certif/app/components/auth/register-form.js
  certif/app/components/auth/toggable-login-form.hbs
  certif/app/components/auth/toggable-login-form.js
  certif/app/router.js
  certif/app/routes/join.js
  certif/app/services/url.js
  certif/app/styles/app.scss
  certif/app/styles/components/login-or-register.scss
  certif/app/styles/components/register-form.scss
  certif/app/styles/components/toggable-login-form.scss
  certif/app/styles/globals/texts.scss
  certif/app/styles/globals/titles.scss
  certif/app/styles/pages/join.scss
  certif/app/templates/join.hbs
  certif/app/utils/email-validator.js
  certif/app/utils/password-validator.js
  certif/tests/integration/components/auth/login-or-register_test.js
  certif/tests/integration/components/auth/register-form_test.js
  certif/tests/integration/components/auth/toggable-login-form_test.js
  certif/tests/unit/components/auth/toggable-login-form_test.js
  certif/tests/unit/routes/join_test.js
  certif/tests/unit/services/url_test.js
  certif/tests/unit/utils/email-validator_test.js
  certif/tests/unit/utils/password-validator_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5100 [TECH] Ne pas tracer les réponses ne pouvant être insérées en BDD à cause d'un encodage incorrect
  api/lib/config.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5111 [BUGFIX] Réparer l'affichage des QROC (PIX-6113).
  mon-pix/app/styles/components/_challenge-item.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5113 [FEATURE] Réduire le texte du bouton retour à l'écran précédent sur les pages sessions (PIX-5785)
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, Design Review OK, hacktoberfest-accepted

#5070 [TECH] Supprimer des routes de test de monitoring non utilisées
  api/lib/application/healthcheck/healthcheck-controller.js
  api/lib/application/healthcheck/index.js
  api/lib/application/simulateErrors/error-controller.js
  api/lib/application/simulateErrors/index.js
  api/lib/routes.js
  api/tests/acceptance/application/error-controller_test.js
  api/tests/integration/application/healthcheck/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5083 [FEATURE] Pouvoir créer au choix des paliers de type seuil ou niveau (PIX-5692)
  admin/app/components/stages/stage-level-select.hbs
  admin/app/components/stages/stage-level-select.js
  admin/app/components/stages/update-stage.hbs
  admin/app/components/stages/update-stage.js
  admin/app/components/target-profiles/stages.hbs
  admin/app/components/target-profiles/stages.js
  admin/app/components/target-profiles/stages/new-stage.hbs
  admin/tests/integration/components/routes/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/integration/components/target-profiles/stages_test.js
  api/lib/application/stages/index.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/create-stage.js
  api/lib/infrastructure/repositories/stage-repository.js
  api/tests/integration/domain/usecases/create-stage_test.js
  api/tests/tooling/domain-builder/factory/build-stage.js
  api/tests/unit/application/stages/index_test.js
  api/tests/unit/domain/usecases/create-stage_test.js
  api/tests/unit/domain/validators/stage-validator_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5125 [BUGFIX] Evite les conflicts lors de la création d'un `user-recommended-training` (PIX-6144)
  api/lib/infrastructure/repositories/user-recommended-training-repository.js
  api/tests/integration/infrastructure/repositories/user-recommended-training-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5094 [TECH] Ecrire l'état d'obtention de la certification Pix dans la table "certification-courses" lors de la publication de la certification (PIX-6071)
  api/db/database-builder/factory/build-certification-course.js
  api/db/migrations/20221018192501_add-column-pix-certification-status-in-certification-courses-table.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/scripts/certification/fill-pix-certification-status-column-in-certification-courses-table.js
  api/tests/acceptance/application/session/session-controller-patch-publish-session_test.js
  api/tests/acceptance/application/session/session-controller-patch-unpublish-session_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/integration/scripts/certification/fill-pix-certification-status-column-in-certification-courses-table_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5119 [TECH] Tracer le nombre de requêtes SQL associées à une requête http
  api/db/knex-database-connection.js
  api/lib/config.js
  api/lib/infrastructure/monitoring-tools.js
  api/lib/infrastructure/validate-environment-variables.js
  api/sample.env
  api/tests/integration/infrastructure/knex-database-performance-monitoring_test.js
Labels: :rocket: Ready to Merge, team-captains, cross-team

#5057 [TECH] Faire le lien entre le bouton de téléchargement et l'appel pour l'export csv des candidats Clea (PIX-5826)
  api/lib/application/sessions/session-with-clea-certified-candidate-controller.js
  api/tests/unit/application/session/session-with-clea-certified-candidate-controller_test.js
  certif/app/components/session-clea-results-download.hbs
  certif/app/components/session-clea-results-download.js
  certif/app/services/file-saver.js
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details.hbs
  certif/tests/acceptance/session-details_test.js
  certif/tests/integration/components/session-clea-results-download_test.js
  certif/tests/unit/components/session-clea-results-download_test.js
  certif/tests/unit/services/file-saver_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5127 [CLEANUP] Refactorer une boucle en utilisant un map
  api/lib/infrastructure/repositories/campaign-collective-result-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5130 [BUGFIX] La publication de session contenant des certifications annulées peut échouer (PIX-6152)
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#5132 [TECH] Résoudre un test flaky sur `user-recommended-trainings` repository.
  api/tests/integration/infrastructure/repositories/user-recommended-training-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5124 [TECH] Supprimer le script de calcul des recommandations des contenus formatifs (PIX-6083)
  api/scripts/fill-user-recommended-trainings.js
  api/tests/integration/scripts/fill-user-recommended-trainings_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5093 [FEATURE] Ajouter l'heure de début du test de certification du candidat sur l'espace surveillant. (PIX-6014)
  api/lib/domain/models/CertificationCandidateForSupervising.js
  api/lib/infrastructure/repositories/certification-candidate-for-supervising-repository.js
  api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-for-supervising-serializer.js
  api/tests/integration/infrastructure/repositories/certification-candidate-for-supervising-repository_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-for-supervising-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate-for-supervising.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-for-supervising-serializer_test.js
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/candidate-in-list.js
  certif/app/components/session-supervising/confirmation-modal.hbs
  certif/app/models/certification-candidate-for-supervising.js
  certif/app/styles/components/session-supervising/candidate-in-list.scss
  certif/package-lock.json
  certif/package.json
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/tests/unit/models/certification-candidate-for-supervising_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5131 [TECH] Supprimer la route inutilisée : /api/certification-center-memberships (PIX-6154).
  api/lib/application/certification-center-memberships/certification-center-membership-controller.js
  api/lib/application/certification-center-memberships/index.js
  api/lib/domain/usecases/create-certification-center-membership.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/certification-center-membership-route_test.js
Labels: :rocket: Ready to Merge, team-certif, cross-team

#5135 [TECH] Ajouter de l'outillage pour créer facilement à la volée des profil-cibles pour les seeds (PIX-6168)
  api/db/seeds/data/learning-content/target-profiles-builder.js
  api/db/seeds/data/learning-content/tooling.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#5120 [FEATURE] ETQ Pix certif user d'un CDC habilité CléA numérique, JV pouvoir modifier le référent Pix dans mon centre (PIX-5798)
  api/lib/domain/usecases/update-certification-center-referer.js
  api/lib/infrastructure/repositories/certification-center-membership-repository.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/unit/domain/usecases/update-certification-center-referer_test.js
  certif/app/components/members-list.hbs
  certif/app/components/members-list.js
  certif/app/controllers/authenticated/team.js
  certif/app/styles/pages/authenticated/team.scss
  certif/app/templates/authenticated/team.hbs
  certif/tests/unit/components/members-list_test.js
  certif/tests/unit/controllers/team_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5143 [BUGFIX] Changement de libellé de réponse incorrect (PIX-6177)
  mon-pix/tests/integration/components/qcu-solution-panel_test.js
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5126 [TECH] Tracer les requêtes HTTP en cours
  api/package-lock.json
  api/package.json
  api/sample.env
  api/server.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5138 [BUGFIX] Téléchargement impossible du fichier des résultats CléA dans Pix Certif sans message d'erreur (PIX-6158)
  api/lib/domain/read-models/CleaCertifiedCandidate.js
  api/tests/unit/domain/read-models/CleaCertifiedCandidate_test.js
  certif/app/components/session-clea-results-download.hbs
  certif/app/components/session-clea-results-download.js
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/tests/integration/components/session-clea-results-download_test.js
  certif/tests/unit/components/session-clea-results-download_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5137 [FEATURE] Deplacer la navbar certif (PIX-5744)
  certif/app/styles/app.scss
  certif/app/styles/components/user-logged-menu.scss
  certif/app/styles/globals/panels.scss
  certif/app/styles/pages/authenticated.scss
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#5123 [FEATURE] Afficher le statut “Autorisé à reprendre” dans l'espace surveillant (PIX-6019)
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/models/certification-candidate-for-supervising.js
  certif/app/styles/components/session-supervising/candidate-in-list.scss
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/tests/unit/models/certification-candidate-for-supervising_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, hacktoberfest-accepted

#5112 [FEATURE] Améliorer le reponsive de l'infobulle sur Pix App (PIX-5611)
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation
