Repository 1024pix/pix, pull requests merged in 2022-11, with the labels that each got.

#5145 [TECH] Montée de version de Pix UI sur Admin
  admin/app/components/actions-on-users-role-in-organization.hbs
  admin/app/components/badges/badge.hbs
  admin/app/components/campaigns/participation-row.hbs
  admin/app/components/certification-centers/information-view.hbs
  admin/app/components/certifications/certified-profile.hbs
  admin/app/components/certifications/issue-report.hbs
  admin/app/components/menu-bar.hbs
  admin/app/components/modal/dialog.hbs
  admin/app/components/target-profiles/old-details.hbs
  admin/app/components/target-profiles/tubes-details/tube.hbs
  admin/app/components/target-profiles/tubes-selection/tube.hbs
  admin/app/components/team/list.hbs
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/components/users/user-detail-personal-information/organization-learner-information.hbs
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/app/templates/authenticated/tools.hbs
  admin/app/templates/authenticated/users/list.hbs
  admin/config/environment.js
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/routes/authenticated/target-profiles/target-profile/old-details_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5149 [TECH] Ajout du thème Noël pour le template de pull request.
  docs/pull_request_template.md
Labels: :rocket: Ready to Merge, cross-team

#5081 [FEATURE] Nouveau design page fin de parcours (PIX-5987).
  api/lib/domain/read-models/participant-results/BadgeResult.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/unit/domain/read-models/participant-results/BadgeResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  mon-pix/app/components/badge-card-certifiable.hbs
  mon-pix/app/components/badge-card.hbs
  mon-pix/app/components/campaign-share-button.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign-participation-badge.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_badge-card-certifiable.scss
  mon-pix/app/styles/components/_badge-card.scss
  mon-pix/app/styles/components/_reached-stage.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/config/icons.js
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/components/routes/campaigns/assessment/skill-review_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5147 [FEATURE] Changement du label du numéro de session sur le dashboard des sessions (PIX-5771)
  certif/app/components/session-summary-list.hbs
  certif/tests/integration/components/session-summary-list_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5144 [FEATURE] Ajouter une route permettant de modifier du contenu formatif (PIX-6121).
  api/db/database-builder/factory/build-training.js
  api/lib/application/trainings/index.js
  api/lib/application/trainings/training-controller.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-training.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/unit/application/trainings/index_test.js
  api/tests/unit/application/trainings/training-controller_test.js
  api/tests/unit/domain/usecases/update-training_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5148 [BUGFIX] Limiter la concurrence pour le création du CSV des résultats de campagne de collecte de profils (PIX-6196).
  api/lib/infrastructure/serializers/csv/campaign-profiles-collection-export.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-captains

#5150 [TASK] Api: Retirer le code obsolète qui scan toute la base de données Redis (PIX-6080)
  api/lib/domain/services/refresh-token-service.js
  api/lib/infrastructure/temporary-storage/InMemoryTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/TemporaryStorage.js
  api/lib/infrastructure/utils/RedisClient.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
  api/tests/integration/infrastructure/utils/RedisClient_test.js
  api/tests/unit/domain/services/refresh-token-service_test.js
  api/tests/unit/infrastructure/temporary-storage/InMemoryTemporaryStorage_test.js
  api/tests/unit/infrastructure/temporary-storage/TemporaryStorage_test.js
Labels: :rocket: Ready to Merge, team-acces

#5118 [TECH] Ajouter l'id de campagne au token de récupération des résultats de la campagne (PIX-6028)
  api/lib/application/campaigns/campaign-controller.js
  api/lib/config.js
  api/lib/domain/services/token-service.js
  api/sample.env
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/services/token-service_test.js
Labels: :rocket: Ready to Merge, team-acces, team-prescription

#5154 [TECH] Supprimer le conditionnement de la page `/mes-formations` (PIX-6205).
  api/lib/config.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5156 [BUGFIX] Régler le problème d'interprétation de la valeur de la colonne isManagingStudents du script OGA (PIX-6212)
  api/scripts/create-organizations-with-tags-and-target-profiles.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/helpers/files/organizations-with-tags-and-target-profiles-test.csv
Labels: :rocket: Ready to Merge, team-acces

#5152 [TECH] Respecter la norme REST pour remonter les tutoriels (PIX-6103).
  api/lib/application/user-tutorials/index.js
  api/lib/application/user-tutorials/user-tutorials-controller.js
  api/lib/domain/models/Tutorial.js
  api/lib/domain/usecases/find-paginated-filtered-tutorials.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/unit/application/user-tutorials/index_test.js
  api/tests/unit/application/user-tutorials/user-tutorials-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-tutorials_test.js
  mon-pix/app/adapters/tutorial.js
  mon-pix/app/routes/authenticated/user-tutorials/recommended.js
  mon-pix/app/routes/authenticated/user-tutorials/saved.js
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/handlers/find-paginated-and-filtered-recommended-tutorials.js
  mon-pix/mirage/handlers/find-paginated-and-filtered-saved-tutorials.js
  mon-pix/mirage/handlers/find-paginated-and-filtered-tutorials.js
  mon-pix/mirage/routes/get-recommended-tutorials.js
  mon-pix/mirage/routes/get-saved-tutorials.js
  mon-pix/mirage/routes/get-user-tutorials.js
  mon-pix/tests/unit/adapters/tutorial_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5159 [FEATURE] En tant qu'utilisateur Pix Admin, je veux désactiver un membre Pix Certif depuis la page du user (PIX-5712)
  admin/app/components/users/certification-center-memberships.hbs
  admin/app/components/users/certification-center-memberships.js
  admin/tests/integration/components/users/certification-center-memberships_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5133 [TECH] Ajouter des informations dans les logs de pole emploi (PIX-6155).
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#5129 [TECH][API] Permettre l'inscription à Pix Certif depuis une invitation (PIX-5009).
  api/lib/application/certification-center-invitations/certification-center-invitation-controller.js
  api/lib/application/certification-center-invitations/index.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCenterInvitedUser.js
  api/lib/domain/models/OrganizationInvitedUser.js
  api/lib/domain/types/identifiers-type.js
  api/lib/domain/usecases/accept-certification-center-invitation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-center-invited-user-repository.js
  api/lib/routes.js
  api/tests/acceptance/application/certification-center-invitations/index_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/certification-center-invited-user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-center-invitation.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certification-center-invitations/certification-center-invitation-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/CertificationCenterInvitedUser_test.js
  api/tests/unit/domain/models/OrganizationInvitedUser_test.js
  api/tests/unit/domain/usecases/accept-certification-center-invitation_test.js
Labels: :rocket: Ready to Merge, team-acces, team-certif

#5153 [BUGFIX] Eviter une erreur lorsque l'on publie une session sans Referer
  api/lib/domain/services/session-publication-service.js
  api/lib/infrastructure/repositories/certification-center-repository.js
  api/tests/integration/infrastructure/repositories/certification-center-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#5122 [FEATURE] Ajouter la page "/mes-formations" sur Pix App (PIX-5759).
  api/db/seeds/data/trainings-builder.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/find-paginated-user-recommended-trainings.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-with-activity-serializer.js
  api/tests/acceptance/application/users/users-controller-find-paginated-user-recommended-trainings_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-user-recommended-trainings_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-activity-serializer_test.js
  mon-pix/app/adapters/training.js
  mon-pix/app/components/training/header.hbs
  mon-pix/app/controllers/authenticated/user-trainings.js
  mon-pix/app/models/user.js
  mon-pix/app/router.js
  mon-pix/app/routes/authenticated/user-trainings.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_training-card.scss
  mon-pix/app/styles/pages/_user-trainings.scss
  mon-pix/app/templates/authenticated/user-trainings.hbs
  mon-pix/mirage/factories/user.js
  mon-pix/mirage/routes/users/find-paginated-user-trainings.js
  mon-pix/mirage/routes/users/index.js
  mon-pix/mirage/serializers/training.js
  mon-pix/mirage/serializers/user.js
  mon-pix/tests/acceptance/user-trainings_test.js
  mon-pix/tests/acceptance/user-tutorials_test.js
  mon-pix/tests/unit/adapters/training_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5168 [BUGFIX] Permettre les tests de charge sur l'intégration
  high-level-tests/load-testing/README.md
  high-level-tests/load-testing/config/common.yaml
  high-level-tests/load-testing/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5167 [BUGFIX] Chercher l'identifiant sans la casse sur Pix App (PIX-6232)
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5117 [FEATURE] Ajout d'un formulaire pour créer une invitation pour rejoindre un centre de certif depuis Pix Admin (PIX-137)
  admin/app/adapters/certification-center-invitation.js
  admin/app/components/certification-centers/invitations-action.hbs
  admin/app/components/certification-centers/invitations-action.js
  admin/app/components/certification-centers/invitations.hbs
  admin/app/components/certification-centers/invitations.js
  admin/app/controllers/authenticated/certification-centers/get/invitations.js
  admin/app/routes/authenticated/certification-centers/get/invitations.js
  admin/app/styles/app.scss
  admin/app/styles/components/certification-centers/invitations-action.scss
  admin/app/templates/authenticated/certification-centers/get/invitations.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/certification-centers/get/invitations_test.js
  admin/tests/integration/components/certification-centers/get/invitations_test.js
  admin/tests/integration/components/certification-centers/invitations-action_test.js
  admin/tests/unit/adapters/certification-center-invitation_test.js
  admin/tests/unit/routes/authenticated/certification-centers/get/invitations_test.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/models/CertificationCenterInvitation.js
  api/lib/domain/usecases/create-or-update-certification-center-invitation-for-admin.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-center-invitation-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-center-invitation-serializer.js
  api/tests/acceptance/application/certification-centers/index_test.js
  api/tests/acceptance/application/certifications/index_test.js
  api/tests/integration/domain/usecases/create-or-update-certification-center-invitation-for-admin_test.js
  api/tests/integration/domain/usecases/find-pending-certification-center-invitations_test.js
  api/tests/test-helper.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/domain/models/CertificationCenterInvitation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-center-invitation-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5173 [TECH] Corriger le nom de la constante de l'url redis dans un test
  api/lib/config.js
  api/lib/infrastructure/temporary-storage/index.js
  api/tests/integration/infrastructure/temporary-storage/RedisTemporaryStorage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#5151 [TECH] Supprime le code specifique de certification complementaire (PIX-6199)
  api/db/constants.js
  api/db/migrations/20220303094934_add-column-temporary-partner-key-in-partner-certifications-and-populate-it.js
  api/db/migrations/20220328102301_link-complementary-certification-course-results-to-complementary-certification-courses.js
  api/db/migrations/20220516142918_split-pix-edu-complementary-certifications.js
  api/db/migrations/20220712082535_insert-complementary-certification-badges.js
  api/db/migrations/20220802093742_add-imageUrl-to-complementary-certification-badges.js
  api/db/migrations/20220802141209_set-isCertifiable-to-true-on-clea-badges.js
  api/db/migrations/20220802143639_add-level-to-clea-certif-badges.js
  api/db/migrations/20220808152543_add-label-column-to-complementary-certification-badges-table.js
  api/db/migrations/20220922141959_modify-messages-in-complementary-certification-badges.js
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/certification/complementary-certification-course-results-builder.js
  api/db/seeds/data/certification/tooling.js
  api/lib/domain/models/Badge.js
  api/lib/domain/models/CertifiableBadgeAcquisition.js
  api/lib/domain/models/ComplementaryCertificationCourseResult.js
  api/lib/domain/models/PartnerCertificationScoring.js
  api/lib/domain/models/PixPlusDroitExpertCertificationResult.js
  api/lib/domain/models/PixPlusDroitMaitreCertificationResult.js
  api/lib/domain/read-models/CertifiableBadgeLabels.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/repositories/pix-plus-droit-expert-certification-result-repository.js
  api/lib/infrastructure/repositories/pix-plus-droit-maitre-certification-result-repository.js
  api/scripts/data-generation/generate-certif-cli.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/acceptance/application/session/session-with-clea-certified-candidate-controller-get-clea-certified-candidate-data-csv.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/integration/infrastructure/repositories/certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/clea-certified-candidate-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
  api/tests/integration/infrastructure/repositories/pix-plus-droit-expert-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/pix-plus-droit-maitre-certification-result-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/integration/scripts/data-generation/generate-certif-cli_test.js
  api/tests/tooling/domain-builder/factory/build-certifiable-badge-acquisition.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-course-result-for-certification-with-external.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-course-result-for-certification.js
  api/tests/tooling/domain-builder/factory/build-pix-plus-droit-certification-result.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/complementary-certification-course-results/index_test.js
  api/tests/unit/domain/events/handle-complementary-certifications-scoring_test.js
  api/tests/unit/domain/models/ComplementaryCertificationCourseResult_test.js
  api/tests/unit/domain/models/JuryCertification_test.js
  api/tests/unit/domain/models/PixPlusDroitExpertCertificationResult_test.js
  api/tests/unit/domain/models/PixPlusDroitMaitreCertificationResult_test.js
  api/tests/unit/domain/read-models/CertifiableBadgeLabels_test.js
  api/tests/unit/domain/read-models/ComplementaryCertificationCourseResultsForJuryCertificationWithExternal_test.js
  api/tests/unit/domain/usecases/get-user-certification-eligibility_test.js
Labels: :rocket: Ready to Merge, team-certif

#5170 [TECH] Modifier les seeds de développement pour remplir la nouvelle colonne de la table "certification-courses"
  api/db/seeds/data/certification/certification-courses-builder.js
  api/db/seeds/data/certification/certification-scores-builder.js
Labels: :rocket: Ready to Merge, team-certif

#5165 [TECH] Améliorer la lisibilité du composant `scorecard-details` (PIX-5609).
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/components/scorecard-details.js
  mon-pix/app/models/scorecard.js
  mon-pix/tests/integration/components/scorecard-details_test.js
  mon-pix/tests/unit/components/scorecard-details_test.js
  mon-pix/tests/unit/models/scorecard_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5172 [FEATURE] Améliorer l'accessibilité sur Pix-App (PIX-6230)
  high-level-tests/e2e/cypress/integration/pix-app/a11y.test.js
  mon-pix/app/components/campaign-participation-overview/card/disabled.hbs
  mon-pix/app/components/campaign-participation-overview/card/ended.hbs
  mon-pix/app/components/campaign-participation-overview/card/ongoing.hbs
  mon-pix/app/components/campaign-participation-overview/card/to-share.hbs
  mon-pix/app/styles/components/_footer.scss
  mon-pix/app/styles/components/sitemap/_content.scss
  mon-pix/app/templates/authenticated/user-account/language.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5161 [FEATURE] Ajouter le lien "Politique de protection des données des élèves" dans le footer de Pix App (PIX-6203)
  mon-pix/app/components/footer.hbs
  mon-pix/app/styles/components/_footer.scss
  mon-pix/tests/integration/components/footer_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5174 [TECH] Monter les versions non problématiques de Pix App (PIX-6249)
  mon-pix/config/environment.js
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5180 [TECH] Retirer le package @ember/jquery qui n'est plus utilisé dans l'application PixApp (PIX-6239)
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5176 [FEATURE] Supprimer la notion de "v2" dans les tutoriels sur Pix-App (PIX-6102)
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/components/tutorials/cards.hbs
  mon-pix/app/components/tutorials/header.hbs
  mon-pix/app/components/tutorials/recommended-empty.hbs
  mon-pix/app/components/tutorials/saved-empty.hbs
  mon-pix/app/styles/components/_learning-more-tutorial-panel.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/components/_tutorial-card.scss
  mon-pix/app/styles/components/_tutorial-panel.scss
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/acceptance/competences-details_test.js
  mon-pix/tests/acceptance/tutorial-actions_test.js
  mon-pix/tests/acceptance/user-tutorials/recommended_test.js
  mon-pix/tests/acceptance/user-tutorials/saved_test.js
  mon-pix/tests/integration/components/learning-more-panel_test.js
  mon-pix/tests/integration/components/scorecard-details_test.js
  mon-pix/tests/integration/components/tutorial-panel_test.js
  mon-pix/tests/integration/components/tutorials/card_test.js
  mon-pix/tests/integration/components/tutorials/cards_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5179 [FEATURE] Fermer le menu utilisateur si on tabule en dehors (PIX-5427)
  mon-pix/app/components/user-logged-menu.hbs
  mon-pix/app/components/user-logged-menu.js
  mon-pix/tests/integration/components/user-logged-menu_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5177 [TECH] Retirer l'initializer Aria déprécié en vu de Ember4.x (PIX-6258)
  mon-pix/app/initializers/aria.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5181 [TECH] Supprimer le package uuid qui n'est plus utilisé dans mon-pix (PIX-6264)
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5188 [BUGFIX][ORGA] Retourner une erreur lorsque le token de récupération des résultats d'une campagne n'est plus valide (PIX-6272)
  api/lib/domain/services/token-service.js
  api/tests/unit/application/campaign/campaign-controller_test.js
  api/tests/unit/domain/services/token-service_test.js
Labels: :rocket: Ready to Merge, team-acces

#5184 [TECH] Corriger un warning jeté par Ember sur Pix App (PIX-6269).
  mon-pix/app/components/dashboard/content.js
  mon-pix/app/models/user.js
  mon-pix/tests/integration/components/dashboard/content_test.js
  mon-pix/tests/unit/components/dashboard/content_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5185 [BUGFIX] Corriger l'affichage de la page de changement de mot de passe
  mon-pix/app/styles/components/_user-account.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5194 [TECH] Supprimer les routes non utilisées (PIX-6207)
  api/lib/application/user-tutorials/index.js
  api/lib/application/user-tutorials/user-tutorials-controller.js
  api/lib/domain/usecases/find-paginated-filtered-recommended-tutorials.js
  api/lib/domain/usecases/find-paginated-filtered-saved-tutorials.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/unit/application/user-tutorials/user-tutorials-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-recommended-tutorials_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-saved-tutorials_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5192 [BUGFIX] On affiche les formations recommandées sans doublon (PIX-6277)
  api/db/seeds/data/campaigns-sco-builder.js
  api/lib/infrastructure/repositories/training-repository.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5175 [FEATURE] Permet la configuration du nombre minimum de connexion ouvertes
  api/db/knexfile.js
  api/lib/infrastructure/validate-environment-variables.js
  api/sample.env
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#5187 [FEATURE] Fermer le volet "Signaler un problème" sur Pix App (PIX-6216)
  mon-pix/app/components/comparison-window.hbs
  mon-pix/tests/acceptance/challenge-feedback_test.js
  mon-pix/tests/integration/components/comparison-window_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5191 [BUGFIX] Correction du double log du monitoring pg-boss
  api/lib/infrastructure/jobs/monitoring/MonitoredJobQueue.js
  api/worker.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#5196 [TECH] Supprimer la Pix Modal dépréciée présente sur Pix App (PIX-6228).
  mon-pix/app/components/comparison-window.hbs
  mon-pix/app/components/comparison-window.js
  mon-pix/app/components/pix-modal-deprecated.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_comparison-window.scss
  mon-pix/app/styles/components/_learning-more-tutorial-panel.scss
  mon-pix/app/styles/components/_tutorial-panel.scss
  mon-pix/app/styles/globals/_pix-modal.scss
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/acceptance/compare-answer-solution-qroc_test.js
  mon-pix/tests/acceptance/compare-answer-solution_test.js
  mon-pix/tests/integration/components/comparison-window_test.js
  mon-pix/tests/unit/components/pix-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-rocket

#5190 [TECH] Suppression du package ember-cli-deprecation-workflow sur Pix App (PIX-6242).
  mon-pix/config/deprecation-workflow.js
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5189 [TECH] Retirer les arguments obsolètes des composant natifs Ember (PIX-6271)
  mon-pix/app/components/feedback-panel.hbs
  mon-pix/app/components/form-textfield-date.hbs
  mon-pix/app/components/form-textfield.hbs
  mon-pix/app/components/qcu-proposals.hbs
  mon-pix/app/components/routes/campaigns/invited/fill-in-participant-external-id.hbs
  mon-pix/app/components/routes/login-form.hbs
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/app/templates/fill-in-certificate-verification-code.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5201 [TECH] Encapsuler le code de l'envoie à Pôle emploi dans un use cases.
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/send-shared-participation-results-to-pole-emploi.js
  api/lib/infrastructure/jobs/JobDependenciesBuilder.js
  api/lib/infrastructure/jobs/campaign-result/SendSharedParticipationResultsToPoleEmploiHandler.js
  api/tests/integration/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/integration/infrastructure/jobs/campaign-result/SendSharedParticipationResultsToPoleEmploiHandler_test.js
  api/tests/unit/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/unit/infrastructure/jobs/campaign-result/SendSharedParticipationResultsToPoleEmploiHandler_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5163 [FEATURE] Redesign de la page de certification (PIX-5986).
  api/lib/domain/usecases/get-user-certification-eligibility.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/unit/domain/usecases/get-user-certification-eligibility_test.js
  mon-pix/app/components/congratulations-certification-banner.hbs
  mon-pix/app/components/congratulations-certification-banner.js
  mon-pix/app/styles/components/_congratulations-certification-banner.scss
  mon-pix/app/templates/authenticated/certifications/join.hbs
  mon-pix/tests/integration/components/congratulations-certification-banner_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5197 [FEATURE] Améliorer le design du bloc contenant le score (PIX-6260)
  mon-pix/app/components/hexagon-score.hbs
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/app/styles/components/dashboard/_content.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5208 [BUGFIX] Corriger le design du bouton de fin de preview (PIX-9298).
  mon-pix/app/styles/pages/_assessment-results.scss
  mon-pix/app/templates/assessments/results.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5206 [TECH] Utiliser `htmlSafe` importé depuis `ember/template` (PIX-6287).
  mon-pix/app/components/challenge-embed-simulator.js
  mon-pix/app/components/communication-banner.js
  mon-pix/app/components/markdown-to-html-unsafe.js
  mon-pix/app/components/markdown-to-html.js
  mon-pix/app/components/progress-bar.js
  mon-pix/app/components/timeout-gauge.js
  mon-pix/app/helpers/text-with-multiple-lang.js
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/unit/components/progress-bar_test.js
  mon-pix/tests/unit/helpers/text-with-multiple-lang_test.js
  mon-pix/tests/unit/routes/assessments/checkpoint_test.js
  mon-pix/tests/unit/routes/assessments/resume_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-rocket

#5210 [TECH] Remplacer le composant Ember `<Input>` de type radio en `<PixRadioButton>` dans les QCU (PIX-6299)
  mon-pix/app/components/qcu-proposals.hbs
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_qcu-panel.scss
  mon-pix/app/styles/components/_qcu-proposals.scss
  mon-pix/app/styles/components/_qcu-solution-panel.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-rocket

#5182 [BUGFIX][MON-PIX] Ne pas rediriger un utilisateur GAR sur la page de connexion (lors de la re-connexion, sur navigateur SAFARI) (PIX-6131)
  api/lib/domain/usecases/get-external-authentication-redirection-url.js
  api/tests/acceptance/application/saml-controller_test.js
  api/tests/unit/domain/usecases/get-external-authentication-redirection-url_test.js
  high-level-tests/e2e/cypress/support/commands.js
  mon-pix/app/authenticators/gar.js
  mon-pix/app/instance-initializers/session.js
  mon-pix/app/router.js
  mon-pix/app/routes/authentication/login-gar.js
  mon-pix/app/services/session.js
  mon-pix/app/utils/pix-window.js
  mon-pix/tests/acceptance/user-account/connection-methods_test.js
  mon-pix/tests/helpers/authentication.js
  mon-pix/tests/unit/authenticators/gar_test.js
  mon-pix/tests/unit/instance-initializers/session-test.js
  mon-pix/tests/unit/routes/authentication/login-gar_test.js
  mon-pix/tests/unit/services/session_test.js
  mon-pix/tests/unit/utils/pix-window_test.js
Labels: :rocket: Ready to Merge, team-acces

#5158 [BUGFIX] Double scroll bar sur l'onglet "Candidats" dans Pix Certif (PIX-6039)
  certif/app/styles/pages/authenticated.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5215 [TECH] Supprimer l'intégration de JQuery sur Pix App (PIX-6306).
  mon-pix/config/optional-features.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-rocket

#5212 [TECH] Mettre à jour `ember-template-lint` sur Pix App (PIX-6301).
  mon-pix/app/components/account-recovery/student-information-form.hbs
  mon-pix/app/components/campaign-start-block.hbs
  mon-pix/app/components/certification-joiner.hbs
  mon-pix/app/components/inaccessible-campaign.hbs
  mon-pix/app/components/levelup-notif.hbs
  mon-pix/app/components/pix-toggle.hbs
  mon-pix/app/components/user-certifications-detail-competence.hbs
  mon-pix/app/components/user-certifications-detail-header.hbs
  mon-pix/app/templates/application.hbs
  mon-pix/app/templates/assessments.hbs
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/app/templates/authenticated/competences/results.hbs
  mon-pix/app/templates/authenticated/user-account.hbs
  mon-pix/app/templates/campaigns/assessment/tutorial.hbs
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
  mon-pix/app/templates/head.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, team-rocket

#5211 [TECH] Remplacer la librairie déprécié babel-eslint par son successeur @babel/eslint-parser (PIX-6300)
  mon-pix/.eslintrc.js
  mon-pix/app/components/reset-password-form.js
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/components/signup-form.js
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-rocket

#5209 [TECH] Montée de version des packages Pix Orga (PIX-6297)
  orga/.eslintrc.js
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/results/assessment-row.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-rocket

#5216 [TECH] Monter `ember-source` en 3.28.8 sur Pix App (PIX-6307).
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5199 [TECH] Logger les tentative de rafraichir le token (PIX-6283).
  api/lib/domain/events/handle-pole-emploi-participation-finished.js
  api/lib/domain/events/handle-pole-emploi-participation-started.js
  api/lib/domain/usecases/send-shared-participation-results-to-pole-emploi.js
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-finished_test.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-started_test.js
  api/tests/unit/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#5214 [BUGFIX] Alignement de la liste de RT certifiables (PIX-6302).
  mon-pix/app/styles/components/_congratulations-certification-banner.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5169 [BUGFIX] Correction de l'affichage des RT certifiants de fin de parcours (PIX-6231).
  mon-pix/app/styles/components/_badge-card-certifiable.scss
  mon-pix/app/styles/pages/_skill-review.scss
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, Design Review OK

#5217 [FEATURE] Changer les dates de certification affichées dans le bandeau des centres SCO (PIX-6308)
  certif/app/templates/authenticated.hbs
  certif/tests/acceptance/authenticated_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5223 [BUGFIX] Correction d'une regression d'affichage des Tooltips sur PixOrga (PIX-6326)
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5200 [TECH] Utiliser la dernière version mineure de NodeJs automatiquement
  .gitignore
  INSTALLATION.md
  admin/.nvmrc
  api/.nvmrc
  api/package-lock.json
  api/package.json
  certif/.nvmrc
  docs/adr/0018-specifier-version-nodejs.md
  high-level-tests/e2e/.nvmrc
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/.nvmrc
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/test-algo/.nvmrc
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
  mon-pix/.nvmrc
  orga/.nvmrc
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5221 [TECH] Retirer le "helper" hash pour migrer vers Ember 4.x (PIX-6253)
  mon-pix/app/components/checkpoint-continue.hbs
  mon-pix/app/components/checkpoint-continue.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/controllers/campaigns/profiles-collection/profile-already-shared.js
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5225 [TECH] Déplacement de tests d'acceptance des controllers dans des sous dossiers.
  api/tests/acceptance/application/cache/cache-controller_test.js
  api/tests/acceptance/application/courses/course-controller_test.js
  api/tests/acceptance/application/feature-toggles/feature-toggle-controller_tests.js
  api/tests/acceptance/application/feedbacks/feedback-controller_test.js
  api/tests/acceptance/application/saml/saml-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5186 [BUGFIX] Utiliser l'email de destinataire pour l'envoi des resultats CLéA (PIX-6248)
  api/lib/domain/read-models/CleaCertifiedCandidate.js
  api/lib/infrastructure/repositories/clea-certified-candidate-repository.js
  api/lib/infrastructure/utils/csv/certification-results.js
  api/tests/integration/infrastructure/repositories/clea-certified-candidate-repository_test.js
  api/tests/integration/infrastructure/utils/csv/certification-results_test.js
  api/tests/tooling/domain-builder/factory/build-clea-certified-candidate.js
  api/tests/unit/domain/usecases/get-clea-certified-candidate-by-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5204 [FEATURE] Refonte des RT non obtenus en fin de parcours (PIX-6246).
  api/lib/domain/read-models/participant-results/BadgeResult.js
  api/lib/domain/usecases/get-user-campaign-assessment-result.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/unit/domain/read-models/participant-results/BadgeResult_test.js
  api/tests/unit/domain/usecases/get-user-campaign-assessment-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  mon-pix/app/components/badge-card-certifiable.hbs
  mon-pix/app/components/badge-card-certifiable.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign-participation-badge.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/components/routes/campaigns/assessment/skill-review_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5171 [BUGFIX] Permettre de lancer plusieurs job d'envoi CPF en même temps (PIX-6181)
  api/lib/infrastructure/jobs/cpf-export/handlers/create-and-upload.js
  api/lib/infrastructure/jobs/cpf-export/handlers/planner.js
  api/lib/infrastructure/jobs/cpf-export/schedule-cpf-jobs.js
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/tests/integration/infrastructure/jobs/cpf-export/handlers/create-and-upload_test.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/create-and-upload_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/planner_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5226 [TECH] Déplacement de tests d'acceptance des controllers dans des sous dossiers
  api/tests/acceptance/application/campaign-participations/campaign-participation-controller_test.js
  api/tests/acceptance/application/campaign-stats/campaign-stats-get-participations-count-by-mastery-rate_test.js
  api/tests/acceptance/application/campaigns/campaign-controller_test.js
  api/tests/acceptance/application/campaigns/campaign-management-controller_test.js
  api/tests/acceptance/application/campaigns/campaign-stats-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5205 [TECH] Déplacer la gestion de l'authentification anonyme dans un service (PIX-6029)
  mon-pix/app/instance-initializers/session.js
  mon-pix/app/routes/application.js
  mon-pix/app/services/authentication.js
  mon-pix/app/services/session.js
  mon-pix/tests/unit/instance-initializers/session-test.js
  mon-pix/tests/unit/services/authentication_test.js
  mon-pix/tests/unit/services/session_test.js
Labels: :rocket: Ready to Merge, team-acces

#5183 [FEATURE] Envoyer un email à la création d'une invitation à Pix Certif (PIX-5707)
  admin/app/controllers/authenticated/certification-centers/get/invitations.js
  admin/app/controllers/authenticated/organizations/get/invitations.js
  admin/app/services/error-response-handler.js
  admin/tests/acceptance/organization-invitations-management_test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get/invitations_test.js
  admin/tests/unit/controllers/authenticated/organizations/get/invitations_test.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/error-manager.js
  api/lib/config.js
  api/lib/domain/errors.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/domain/usecases/create-or-update-certification-center-invitation-for-admin.js
  api/lib/infrastructure/mailers/mailer.js
  api/lib/infrastructure/repositories/certification-center-invitation-repository.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/services/organization-invitation-service_test.js
  api/tests/integration/domain/usecases/create-or-update-certification-center-invitation-for-admin_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/translations/en.json
  api/translations/fr.json
  scalingo.json
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5162 [FEATURE] Créer un fichier CSV d'import des sessions en masse (PIX-6132)
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/infrastructure/files/sessions-import.js
  api/tests/acceptance/application/session/session-controller-get-import-template_test.js
  api/tests/integration/infrastructure/utils/csv/sessions-import_test.js
  api/tests/unit/application/session/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5178 [FEATURE] Ajout du lien vers la page mes formations dans le menu (PIX-5760)
  api/lib/domain/read-models/UserWithActivity.js
  api/lib/domain/usecases/get-current-user.js
  api/lib/infrastructure/repositories/user-recommended-training-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-with-activity-serializer.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/integration/infrastructure/repositories/user-recommended-training-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-current-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-activity-serializer_test.js
  high-level-tests/e2e/cypress/fixtures/target-profile-trainings.json
  high-level-tests/e2e/cypress/fixtures/trainings.json
  high-level-tests/e2e/cypress/integration/pix-app/a11y.test.js
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  high-level-tests/e2e/cypress/support/step_definitions/user-dashboard.js
  mon-pix/app/components/navbar-burger-menu.hbs
  mon-pix/app/components/navbar-burger-menu.js
  mon-pix/app/components/navbar-desktop-header.hbs
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/models/user.js
  mon-pix/app/routes/campaigns/assessment/skill-review.js
  mon-pix/mirage/factories/user.js
  mon-pix/mirage/serializers/user.js
  mon-pix/tests/acceptance/user-trainings_test.js
  mon-pix/tests/integration/components/navbar-burger-menu_test.js
  mon-pix/tests/integration/components/navbar-desktop-header_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5219 [FEATURE] Ajouter la page "Mes formations" au plan du site (PIX-6281).
  mon-pix/app/components/sitemap/content.hbs
  mon-pix/tests/acceptance/sitemap_test.js
  mon-pix/tests/integration/components/Sitemap/content_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5238 feat(orga): reword campaign settings labels
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, Func Review OK, team-prescription

#5146 [FEATURE] Modifier le texte de l'erreur E11 (PIX-6182)
  admin/app/models/certification-issue-report.js
  admin/tests/integration/components/certifications/issue-report_test.js
  certif/app/models/certification-issue-report.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5230 [TECH] Corriger les éléments du SaasCompiler apparaissant dans la console lors du build de Pix App (PIX-6284).
  mon-pix/app/styles/components/_tutorial-card.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/ember-cli-build.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5241 [TECH] Déplacer les expect dans les tests de Pix App (PIX-6344).
  mon-pix/tests/acceptance/challenge-feedback_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/integration/components/feedback-panel_test.js
  mon-pix/tests/integration/components/reset-password-form_test.js
  mon-pix/tests/integration/components/user-logged-menu_test.js
  mon-pix/tests/unit/adapters/sco-organization-learner_test.js
  mon-pix/tests/unit/adapters/user_test.js
  mon-pix/tests/unit/components/action-chip_test.js
  mon-pix/tests/unit/components/challenge-statement_test.js
  mon-pix/tests/unit/components/competence-card-default_test.js
  mon-pix/tests/unit/components/markdown-to-html-unsafe_test.js
  mon-pix/tests/unit/components/markdown-to-html_test.js
  mon-pix/tests/unit/components/navbar-desktop-header_test.js
  mon-pix/tests/unit/components/password-reset-demand-form_test.js
  mon-pix/tests/unit/components/reset-password-form_test.js
  mon-pix/tests/unit/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form_test.js
  mon-pix/tests/unit/components/signin-form_test.js
  mon-pix/tests/unit/components/signup-form_test.js
  mon-pix/tests/unit/components/update-expired-password-form_test.js
  mon-pix/tests/unit/controllers/campaigns/invited/fill-in-participant-external-id_test.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code_test.js
  mon-pix/tests/unit/controllers/fill-in-certificate-verification-code_test.js
  mon-pix/tests/unit/utils/labeled-checkboxes_test.js
  mon-pix/tests/unit/utils/proposals-as-blocks_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-rocket

#5242 [TECH] Supprimer les erreurs remontées par la migration QUnit sur Pix App (PIX-6345).
  mon-pix/tests/integration/components/campaign-participation-overview/card/disabled_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ended_test.js
  mon-pix/tests/integration/components/inaccessible-campaign_test.js
  mon-pix/tests/integration/components/password-reset-demand-form_test.js
  mon-pix/tests/integration/components/profile-content_test.js
  mon-pix/tests/integration/components/user-tutorials/filters/sidebar_test.js
  mon-pix/tests/unit/routes/campaigns/entrance_test.js
  mon-pix/tests/unit/services/competence-evaluation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app, team-rocket

#5246 [TECH] Supprimer les erreurs remontées par la migration QUnit sur Pix App - partie 2 (PIX-6347).
  mon-pix/tests/integration/components/campaign-start-block_test.js
  mon-pix/tests/integration/components/challenge-embed-simulator_test.js
  mon-pix/tests/integration/components/feedback-panel_test.js
  mon-pix/tests/integration/components/form-textfield_test.js
  mon-pix/tests/integration/components/reached-stage_test.js
  mon-pix/tests/integration/components/routes/login-or-register_test.js
  mon-pix/tests/integration/components/signup-form_test.js
  mon-pix/tests/integration/components/user-account/email-with-validation-form-test.js
  mon-pix/tests/unit/components/routes/campaigns/invited/associate-sco-student-form_test.js
  mon-pix/tests/unit/components/routes/campaigns/invited/fill-in-participant-external-id_test.js
  mon-pix/tests/unit/components/routes/login-form_test.js
  mon-pix/tests/unit/controllers/account-recovery/update-sco-record-test.js
  mon-pix/tests/unit/controllers/assessments/challenge_test.js
  mon-pix/tests/unit/controllers/assessments/checkpoint_test.js
  mon-pix/tests/unit/controllers/campaigns/campaign-landing-page_test.js
  mon-pix/tests/unit/controllers/campaigns/join/student-sco_test.js
  mon-pix/tests/unit/instance-initializers/session-test.js
  mon-pix/tests/unit/mixins/secured-route-mixin_test.js
  mon-pix/tests/unit/utils/pix-window_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app, team-rocket

#5235 [FEATURE] Reformulation des messages d'erreur sur la création de campagne dans orga (PIX-6056)
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5202 [FEATURE] Permettre à un administrateur d'annuler une invitation à rejoindre un centre de certification (PIX-5003)
  admin/app/components/certification-centers/invitations.hbs
  admin/app/controllers/authenticated/certification-centers/get/invitations.js
  admin/app/styles/app.scss
  admin/app/styles/components/certification-center-invitations.scss
  admin/app/templates/authenticated/certification-centers/get/invitations.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/certification-centers/get/invitations_test.js
  admin/tests/integration/components/certification-centers/invitations_test.js
  admin/tests/unit/controllers/authenticated/certification-centers/get/invitations_test.js
  api/lib/application/certification-center-invitations/certification-center-invitation-controller.js
  api/lib/application/certification-center-invitations/index.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/cancel-certification-center-invitation.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-center-invitation-repository.js
  api/tests/acceptance/application/certification-center-invitations/index_test.js
  api/tests/integration/domain/usecases/cancel-certification-center-invitation_test.js
  api/tests/unit/application/certification-center-invitations/certification-center-invitation-controller_test.js
Labels: :rocket: Ready to Merge, team-acces

#5237 [BUGFIX] Corriger la redirection vers la double mire pour un élève ayant déjà un compte Pix (PIX-6343)
  mon-pix/app/components/routes/campaigns/join-sco-information-modal.js
  mon-pix/tests/unit/components/routes/campaigns/join-sco-information-modal_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5213 [FEATURE] Espace autour des boutons du bloc détail de session (PIX-5780)
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/tests/acceptance/session-details-parameters_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5239 [TECH] Monter la version Pix Orga en Ember 3.28 (PIX-6338)
  orga/app/components/banner/communication.js
  orga/app/components/campaign/analysis/competences.js
  orga/app/components/campaign/analysis/recommendations.js
  orga/app/components/campaign/charts/participants-by-stage.js
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/stage-stars.js
  orga/app/components/ui/progress-bar.js
  orga/app/helpers/text-with-multiple-lang.js
  orga/package-lock.json
  orga/package.json
  orga/tests/unit/helpers/text-with-multiple-lang-test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/assessment-results_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/profile-results_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign_test.js
  orga/tests/unit/routes/authenticated/campaigns/update_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-prescription, team-rocket

#5236 [FEATURE][CERTIF] Déconnecter l'utilisateur quand il arrive sur le lien pour rejoindre un centre de certification via invitation (PIX-6324)
  certif/app/instance-initializers/session.js
  certif/app/utils/pix-window.js
  certif/tests/unit/instance-initializers/session_test.js
  certif/tests/unit/utils/pix-window_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5248 [FEATURE] Ajout du bouton de téléchargement de template d'import de sessions en masse (PIX-6133).
  api/lib/application/sessions/session-controller.js
  api/tests/acceptance/application/session/session-controller-get-import-template_test.js
  certif/app/components/sessions/panel-header.hbs
  certif/app/components/sessions/panel-header.js
  certif/app/styles/pages/authenticated/sessions/list-items.scss
  certif/app/templates/authenticated/sessions/list.hbs
  certif/tests/integration/components/sessions/panel-header_test.js
  certif/tests/unit/components/sessions/panel-header_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5220 [BUGFIX] Afficher correctement les tutoriels dans la page de résultats d'une compétence (PIX-6110)
  mon-pix/app/routes/authenticated/competences/results.js
  mon-pix/tests/unit/routes/authenticated/competences/results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5249 [TECH] Supprimer les contains dans les tests de Pix App (PIX-6350).
  mon-pix/tests/acceptance/account-recovery/find-sco-record_test.js
  mon-pix/tests/acceptance/account-recovery/update-sco-record_test.js
  mon-pix/tests/acceptance/existing-participation-test.js
  mon-pix/tests/acceptance/fill-in-campaign-code_test.js
  mon-pix/tests/acceptance/personal-information_test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection_test.js
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/acceptance/update-expired-password_test.js
  mon-pix/tests/acceptance/user-dashboard_test.js
  mon-pix/tests/integration/components/account-recovery/recovery-errors-test.js
  mon-pix/tests/integration/components/account-recovery/update-sco-record-form-test.js
  mon-pix/tests/integration/components/certification-starter_test.js
  mon-pix/tests/integration/components/challenge-embed-simulator_test.js
  mon-pix/tests/integration/components/user-logged-menu_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app, team-rocket

#5222 [BUGFIX] Le focus-trap ne fonctionnait plus sur la modale de comparaison des réponses sur Pix-App (PIX-6317)
  mon-pix/app/components/comparison-window.hbs
  mon-pix/app/components/comparison-window.js
  mon-pix/app/components/qcu-solution-panel.js
  mon-pix/app/controllers/assessments/checkpoint.js
  mon-pix/app/controllers/assessments/results.js
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/assessments/results.hbs
  mon-pix/tests/acceptance/compare-answer-solution-qroc_test.js
  mon-pix/tests/acceptance/compare-answer-solution_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5193 [FEATURE] Rejoindre un centre de certif avec un compte existant (PIX-6275)
  api/lib/domain/usecases/accept-certification-center-invitation.js
  api/lib/infrastructure/repositories/certification-center-invited-user-repository.js
  api/tests/integration/infrastructure/repositories/certification-center-invited-user-repository_test.js
  api/tests/unit/domain/usecases/accept-certification-center-invitation_test.js
  certif/app/components/auth/login-or-register.hbs
  certif/app/components/auth/toggable-login-form.js
  certif/app/models/certification-center-invitation.js
  certif/app/styles/app.scss
  certif/app/styles/components/auth/toggable-login-form.scss
  certif/app/templates/join.hbs
  certif/mirage/config.js
  certif/tests/acceptance/join_test.js
  certif/tests/acceptance/routes/join_test.js
  certif/tests/integration/components/auth/toggable-login-form_test.js
  certif/tests/integration/components/login-form_test.js
  certif/tests/unit/components/auth/toggable-login-form_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5247 [BUGFIX] Couleur des titre et body sur la page de finalisation (PIX-5791)
  certif/app/components/session-finalization-step-container.hbs
  certif/app/styles/components/session-finalization-step-container.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5243 [FEATURE] Trier les résumés de jury de certification par leur nombre de signalements (PIX-6332)
  admin/app/templates/authenticated/sessions/session/informations.hbs
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportCategory.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5245 [TECH] Remplacer moment par dayjs sur Pix Orga (PIX-6346)
  orga/app/components/campaign/analysis/tube-recommendation-row.hbs
  orga/app/components/campaign/charts/participants-by-day.hbs
  orga/app/components/campaign/charts/participants-by-day.js
  orga/app/components/campaign/header/title.hbs
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/components/organization-participant/list.hbs
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/profile/header.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/components/team/invitations-list.hbs
  orga/app/components/tube/list.js
  orga/app/models/tutorial.js
  orga/app/services/session.js
  orga/app/transforms/duration-extended.js
  orga/config/environment.js
  orga/ember-cli-build.js
  orga/package-lock.json
  orga/package.json
  orga/tests/helpers/setup-intl.js
  orga/tests/integration/components/campaign/analysis/tube-recommendation-row_test.js
  orga/tests/integration/components/participant/assessment/header_test.js
  orga/tests/integration/components/team/invitations-list_test.js
  orga/tests/integration/components/tube/list_test.js
  orga/tests/unit/services/session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-rocket

#5254 [TECH] Préparer la migration vers QUnit sur Pix App (PIX-6375)
  mon-pix/app/components/certification-starter.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/mirage/routes/post-shared-certifications.js
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/acceptance/challenge-page-banner_test.js
  mon-pix/tests/acceptance/compare-answer-solution_test.js
  mon-pix/tests/acceptance/oidc/oidc-authentication-flow_test.js
  mon-pix/tests/acceptance/resume-competence-evaluations_test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/integration/components/account-recovery/backup-email-confirmation-form-test.js
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/tests/integration/components/challenge/item_test.js
  mon-pix/tests/integration/components/comparison-window_test.js
  mon-pix/tests/integration/components/congratulations-certification-banner_test.js
  mon-pix/tests/integration/components/dashboard/content_test.js
  mon-pix/tests/integration/components/feedback-panel_test.js
  mon-pix/tests/integration/components/navbar-burger-menu_test.js
  mon-pix/tests/integration/components/navbar-header_test.js
  mon-pix/tests/integration/components/qcm-solution-panel_test.js
  mon-pix/tests/integration/components/qcu-solution-panel_test.js
  mon-pix/tests/integration/components/result-item-campaign_test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/integration/components/signup-form_test.js
  mon-pix/tests/integration/components/training/card_test.js
  mon-pix/tests/integration/components/tutorials/card_test.js
  mon-pix/tests/integration/components/user-tutorials/filters/sidebar_test.js
  mon-pix/tests/unit/adapters/shared-profile-for-campaign_test.js
  mon-pix/tests/unit/components/profile-content_test.js
  mon-pix/tests/unit/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/components/user-tutorials/filters/sidebar_test.js
  mon-pix/tests/unit/routes/authentication/login_test.js
  mon-pix/tests/unit/serializers/assessment_test.js
  mon-pix/tests/unit/services/authentication_test.js
  mon-pix/tests/unit/services/oidc-identity-providers_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-rocket

#5256 [TECH] Monter les versions non problématiques sur Pix Certif (PIX-6373)
  certif/package-lock.json
  certif/package.json
Labels: :rocket: Ready to Merge, team-certif, team-rocket

#5273 [FEATURE] Créer la nouvelle table user-logins (PIX-6392)
  api/db/migrations/20221124093117_create-user-logins-table.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#5251 [TECH] Valider le feedback à l'entrée de l'API.
  api/lib/application/feedbacks/feedback-controller.js
  api/lib/application/feedbacks/index.js
  api/tests/acceptance/application/feedbacks/feedback-controller_test.js
  api/tests/acceptance/scripts/certification/trigger-session-finalized-handler_test.js
  api/tests/unit/application/feedbacks/feedback-controller_test.js
  api/tests/unit/application/feedbacks/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#5263 [TECH] Retirer les hash dépréciés en Ember 4.x sur Pix Certif (PIX-6255).
  certif/app/components/add-student-list.hbs
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/certification-candidate-in-staging-item.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/app/components/pagination-control.hbs
  certif/app/components/pagination-control.js
  certif/app/components/session-summary-list.hbs
  certif/app/styles/app.scss
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/components/pagination-control.scss
  certif/app/styles/pages/authenticated/sessions/list-items.scss
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-list_test.js
  certif/tests/integration/components/add-student-list_test.js
  certif/tests/integration/components/pagination-control_test.js
  certif/tests/integration/components/session-summary-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-rocket

#5257 [FEATURE] Création d'une route pour récupérer une liste paginée des contenus formatifs
  api/lib/application/trainings/index.js
  api/lib/application/trainings/training-controller.js
  api/lib/domain/read-models/TrainingSummary.js
  api/lib/domain/usecases/find-paginated-training-summaries.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-summary-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/tooling/domain-builder/factory/build-training-summary.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/trainings/index_test.js
  api/tests/unit/application/trainings/training-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-trainings-summary_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-summary-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5274 [TECH] Supprimer le package ember-modal-dialog sur Pix Admin (PIX-6238).
  admin/app/components/certifications/candidate-edit-modal.hbs
  admin/app/components/modal/body.hbs
  admin/app/components/modal/dialog.hbs
  admin/app/components/modal/dialog.js
  admin/app/components/modal/footer.hbs
  admin/app/components/users/user-detail-personal-information/add-authentication-method-modal.hbs
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/styles/app.scss
  admin/app/styles/components/certification/candidate-edit-modal.scss
  admin/app/styles/components/modal.scss
  admin/app/styles/components/users/user-detail-personal-information/authentication-method.scss
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/integration/components/certifications/candidate-edit-modal_test.js
  admin/tests/integration/components/modal/dialog_test.js
  mon-pix/tests/helpers/setup-modal-dialog.js
  orga/app/styles/app.scss
  orga/app/styles/components/modal.scss
Labels: :rocket: Ready to Merge, team-rocket

#5272 [TECH] Préparer la montée de version de Pix Admin pour Ember 4.X (PIX-6390)
  admin/app/controllers/authenticated/certification-centers/get/team.js
  admin/app/routes/authenticated/certification-centers/get/invitations.js
  admin/app/routes/authenticated/certification-centers/get/team.js
  admin/app/routes/authenticated/organizations/get/places/new.js
  admin/app/routes/authenticated/team/list.js
  admin/tests/integration/components/campaigns/participation-row_test.js
  admin/tests/integration/components/campaigns/participations-section_test.js
  admin/tests/integration/components/certification-centers/invitations-action_test.js
  admin/tests/integration/components/certification-centers/invitations_test.js
  admin/tests/integration/components/certification-centers/memberships-section_test.js
  admin/tests/integration/components/certifications/candidate-edit-modal_test.js
  admin/tests/integration/components/certifications/details-answer_test.js
  admin/tests/integration/components/certifications/details-competence_test.js
  admin/tests/integration/components/certifications/list_test.js
  admin/tests/integration/components/certifications/status_test.js
  admin/tests/integration/components/organizations/campaigns-section-test.js
  admin/tests/integration/components/organizations/form_test.js
  admin/tests/integration/components/organizations/invitations-action_test.js
  admin/tests/integration/components/organizations/invitations_test.js
  admin/tests/integration/components/organizations/target-profiles-section_test.js
  admin/tests/integration/components/organizations/team-section_test.js
  admin/tests/integration/components/target-profiles/badge-form_test.js
  admin/tests/integration/components/team-actions-section_test.js
  admin/tests/integration/components/users/campaign-participations_test.js
  admin/tests/integration/components/users/certification-center-memberships_test.js
  admin/tests/integration/components/users/user-organization-memberships_test.js
  admin/tests/integration/components/users/user-profile_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-rocket

#5281 [TECH] Suppression du script fix-trigger-session-finalized-handler.
  api/scripts/certification/trigger-session-finalized-handler.js
  api/tests/acceptance/scripts/certification/trigger-session-finalized-handler_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#5279 [TECH] Remplacer `ember-moment` par `ember-dayjs` sur Pix App (PIX-6408).
  high-level-tests/e2e/cypress/fixtures/trainings.json
  high-level-tests/e2e/cypress/fixtures/users.json
  mon-pix/app/components/campaign-participation-overview/card/disabled.hbs
  mon-pix/app/components/campaign-participation-overview/card/ended.hbs
  mon-pix/app/components/campaign-participation-overview/card/ongoing.hbs
  mon-pix/app/components/campaign-participation-overview/card/to-share.hbs
  mon-pix/app/components/certifications-list-item.hbs
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/components/user-certifications-detail-header.hbs
  mon-pix/app/models/tutorial.js
  mon-pix/app/services/session.js
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
  mon-pix/app/transforms/duration-extended.js
  mon-pix/config/environment.js
  mon-pix/ember-cli-build.js
  mon-pix/mirage/routes/authentication/index.js
  mon-pix/mirage/routes/authentication/oidc/index.js
  mon-pix/mirage/routes/sco-organization-learners/index.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/helpers/setup-intl.js
  mon-pix/tests/integration/components/tutorials/card_test.js
  mon-pix/tests/unit/services/session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5282 [TECH] Monter `ember-source` en 4.0.1 sur Pix App (PIX-6252).
  mon-pix/ember-cli-build.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/user-certifications-detail-header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5275 [FEATURE] Création de la page des contenus formatif dans Pix Admin (PIX-6329)
  admin/app/adapters/training-summary.js
  admin/app/components/trainings/list-summary-items.hbs
  admin/app/controllers/authenticated/trainings/list.js
  admin/app/models/training-summary.js
  admin/app/router.js
  admin/app/routes/authenticated/trainings/list.js
  admin/app/templates/authenticated/trainings.hbs
  admin/app/templates/authenticated/trainings/list.hbs
  admin/mirage/config.js
  admin/mirage/factories/training.js
  admin/mirage/handlers/find-paginated-and-filtered-sessions.js
  admin/mirage/handlers/get-jury-certification-summaries-by-session-id.js
  admin/mirage/handlers/organizations.js
  admin/mirage/handlers/pagination-utils.js
  admin/mirage/handlers/target-profiles.js
  admin/mirage/handlers/trainings.js
  admin/mirage/serializers/training-summary.js
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/integration/components/routes/authenticated/trainings/list-items_test.js
  admin/tests/unit/routes/authenticated/trainings/list_test.js
  api/db/seeds/data/trainings-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5267 [TECH] Préparer Pix Certif pour la montée de version d'Ember en 4.X (PIX-6386)
  certif/app/routes/authenticated/sessions/add-student.js
  certif/app/routes/authenticated/sessions/details.js
  certif/app/routes/authenticated/sessions/details/certification-candidates.js
  certif/app/routes/authenticated/sessions/finalize.js
  certif/app/routes/authenticated/sessions/list.js
  certif/app/routes/authenticated/sessions/new.js
  certif/app/routes/authenticated/sessions/update.js
  certif/app/routes/authenticated/team.js
  certif/app/routes/session-supervising.js
  certif/tests/integration/components/certif-checkbox_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-rocket

#5283 [TECH] Documenter le choix du framework frontend
  admin/tests/index.html
  certif/tests/index.html
  docs/adr/0037-framework-test-frontend.md
  mon-pix/tests/index.html
  orga/tests/index.html
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5264 [TECH] Supprime l'utilisation de la propriété onLoadOptions avec le composant PixMultiSelect (PIX-6383)
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/components/sup-organization-participant/list.js
  orga/app/components/ui/divisions-filter.hbs
  orga/app/components/ui/divisions-filter.js
  orga/app/components/ui/groups-filter.hbs
  orga/app/components/ui/groups-filter.js
  orga/app/components/ui/multi-select-filter.hbs
  orga/app/styles/components/ui/filters.scss
  orga/app/styles/components/ui/index.scss
  orga/tests/integration/components/campaign/activity/participants-list_test.js
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5289 [TECH] Supprime les log de niveau de log au démarrage
  api/lib/infrastructure/logger.js
Labels: :rocket: Ready to Merge, cross-team

#5286 [FEATURE] Utiliser le composant `PixPagination` de Pix UI dans Admin
  admin/app/components/campaigns/participations-section.hbs
  admin/app/components/certification-centers/list-items.hbs
  admin/app/components/organizations/campaigns-section.hbs
  admin/app/components/organizations/list-items.hbs
  admin/app/components/organizations/team-section.hbs
  admin/app/components/pagination-control.hbs
  admin/app/components/pagination-control.js
  admin/app/components/sessions/list-items.hbs
  admin/app/components/target-profiles/list-summary-items.hbs
  admin/app/components/trainings/list-summary-items.hbs
  admin/app/components/users/list-items.hbs
  admin/app/styles/app.scss
  admin/app/styles/components/pagination-control.scss
  admin/app/styles/globals/table-admin.scss
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/acceptance/sessions-list_test.js
  admin/tests/integration/components/pagination-control_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5278 [FEATURE] Envoi du fichier d'import de sessions et validations des champs de session (PIX-6173).
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/config.js
  api/lib/domain/usecases/create-sessions.js
  api/lib/domain/usecases/index.js
  api/scripts/helpers/csvHelpers.js
  api/tests/acceptance/application/session/files/sessions-import/sessions.csv
  api/tests/acceptance/application/session/session-controller-post-import-sessions_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/create-sessions_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  certif/app/components/sessions/panel-header.hbs
  certif/app/components/sessions/panel-header.js
  certif/tests/integration/components/sessions/panel-header_test.js
  certif/tests/unit/components/sessions/panel-header_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5290 [BUGFIX] Test instable sur `inMemoryTemporaryStorage.update()`
  api/tests/unit/infrastructure/temporary-storage/InMemoryTemporaryStorage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5297 [TECH] Supprimer @ember/jquery sur Pix Admin (PIX-6261).
  admin/config/optional-features.json
  admin/package-lock.json
  admin/package.json
Labels: :rocket: Ready to Merge, team-rocket

#5269 [FEATURE] Monter la version de Pix UI sur Certif de 16.1.0 à 18.0.1 (PIX-6358)
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/issue-report-modal/add-issue-report-modal.hbs
  certif/app/components/issue-report-modal/issue-reports-modal.hbs
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/app/components/select-referer-modal.hbs
  certif/app/components/session-delete-confirm-modal.hbs
  certif/app/components/session-finalization/completed-reports-information-step.hbs
  certif/app/components/session-finalization/finalization-confirmation-modal.hbs
  certif/app/components/session-finalization/uncompleted-reports-information-step.hbs
  certif/app/components/session-summary-list.hbs
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/candidate-in-list.js
  certif/app/components/session-supervising/confirmation-modal.hbs
  certif/app/components/session-supervising/header.hbs
  certif/app/components/session-supervising/header.js
  certif/app/templates/authenticated.hbs
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/app/templates/authenticated/team.hbs
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/acceptance/session-list_test.js
  certif/tests/acceptance/session-supervising_test.js
  certif/tests/acceptance/team_test.js
  certif/tests/helpers/wait-for.js
  certif/tests/integration/components/certification-candidate-details-modal/certification-candidate-details-modal_test.js
  certif/tests/integration/components/issue-report-modal/issue-report-modal_test.js
  certif/tests/integration/components/issue-reports-modal_test.js
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
  certif/tests/integration/components/session-delete-confirm-modal_test.js
  certif/tests/integration/components/session-finalization/finalization-confirmation-modal_test.js
  certif/tests/integration/components/session-finalization/uncompleted-reports-information-step_test.js
  certif/tests/integration/components/session-summary-list_test.js
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/tests/integration/components/session-supervising/header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-rocket

#5280 [TECH] Monter la version de Pix-UI en 20.2.3 sur Pix Admin (PIX-6393)
  admin/app/components/actions-on-users-role-in-organization.hbs
  admin/app/components/certifications/candidate-edit-modal.hbs
  admin/app/components/certifications/issue-report.hbs
  admin/app/components/certifications/issue-reports/resolve-issue-report-modal.hbs
  admin/app/components/confirm-popup.hbs
  admin/app/components/organizations/archiving-confirmation-modal.hbs
  admin/app/components/organizations/information-section.hbs
  admin/app/components/organizations/places/delete-modal.js
  admin/app/components/sessions/jury-comment.js
  admin/app/components/target-profiles/pdf-parameters-modal.hbs
  admin/app/components/target-profiles/target-profile.hbs
  admin/app/components/target-profiles/tubes-selection.hbs
  admin/app/components/users/user-detail-personal-information/add-authentication-method-modal.hbs
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/components/users/user-detail-personal-information/reassign-gar-authentication-method-modal.hbs
  admin/app/components/users/user-detail-personal-information/reassign-oidc-authentication-method-modal.hbs
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/acceptance/authenticated/organizations/information-management_test.js
  admin/tests/acceptance/authenticated/sessions/list/to-be-published_test.js
  admin/tests/acceptance/authenticated/sessions/session/informations_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/details_test.js
  admin/tests/acceptance/authenticated/team/list_test.js
  admin/tests/acceptance/authenticated/users/authentication-method_test.js
  admin/tests/acceptance/authenticated/users/get_test.js
  admin/tests/integration/components/actions-on-users-role-in-organization_test.js
  admin/tests/integration/components/certifications/issue-reports/resolve-issue-report-modal_test.js
  admin/tests/integration/components/routes/authenticated/to-be-published-sessions/list-items_test.js
  admin/tests/integration/components/sessions/jury-comment_test.js
  admin/tests/integration/components/target-profiles/badges_test.js
  admin/tests/integration/components/team/list_test.js
  admin/tests/integration/components/users/campaign-participations_test.js
  admin/tests/integration/components/users/user-detail-personal-information_test.js
  admin/tests/integration/components/users/user-overview_test.js
  admin/tests/integration/components/users/user-profile_test.js
  admin/tests/unit/components/badges/badge_test.js
  admin/tests/unit/components/target-profiles/organizations_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-rocket

#5291 [FEATURE] Créer l'entrée de menu pour les contenus formatifs dans Admin (PIX-6319)
  admin/app/components/menu-bar.hbs
  admin/app/services/access-control.js
  admin/tests/integration/components/menu-bar_test.js
  admin/tests/unit/services/access-control-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5276 [FEATURE] Bloquer temporairement un utilisateur qui se trompe beaucoup de mot de passe (PIX-6384)
  api/db/database-builder/factory/build-user-login.js
  api/db/database-builder/factory/index.js
  api/lib/application/authentication/index.js
  api/lib/application/error-manager.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/usecases/checkIfUserIsBlocked.js
  api/lib/config.js
  api/lib/domain/errors.js
  api/lib/domain/models/UserLogin.js
  api/lib/domain/services/authentication/pix-authentication-service.js
  api/lib/domain/services/encryption-service.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-login-repository.js
  api/sample.env
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/acceptance/application/authentication/oidc/check-reconciliation-route-post_test.js
  api/tests/acceptance/application/users/users-controller-update-password_test.js
  api/tests/integration/application/security-pre-handlers_test.js
  api/tests/integration/infrastructure/repositories/user-login-repository_test.js
  api/tests/unit/domain/models/UserLogin_test.js
  api/tests/unit/domain/services/authentication/pix-authentication-service_test.js
  api/tests/unit/domain/services/encryption-service_test.js
Labels: :rocket: Ready to Merge, team-acces

#5294 [TECH] Déplacement de tests d'acceptance des controllers dans des sous dossiers
  api/tests/acceptance/application/authentication/authentication-route_test.js
  api/tests/acceptance/application/certification-center-invitation-route_test.js
  api/tests/acceptance/application/certification-center-invitations/index_test.js
  api/tests/acceptance/application/certification-center-memberships/certification-center-membership-controller_test.js
  api/tests/acceptance/application/certification-centers/certification-center-controller_test.js
  api/tests/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/acceptance/application/certification-issue-reports/certification-issue-report-controller_test.js
  api/tests/acceptance/application/certification-reports/certification-report-controller_test.js
  api/tests/acceptance/application/challenges/challenge-controller_test.js
  api/tests/acceptance/application/competence-evaluation-controller_test.js
  api/tests/acceptance/application/competence-evaluations/competence-evaluation-controller_test.js
  api/tests/acceptance/application/memberships/membership-controller_test.js
  api/tests/acceptance/application/swagger_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5285 [TECH] Analyser les lenteurs de BDD
  api/.psqlrc
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5298 [FEATURE] Monter la version de Pix UI sur Certif de 18.0.1 à 20.2.3 (PIX-6361).
  certif/app/components/add-student-list.hbs
  certif/app/components/new-certification-candidate-modal.hbs
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/integration/components/add-student-list_test.js
Labels: :rocket: Ready to Merge, team-certif, team-rocket

#5303 [FEATURE] Informer les utilisateurs dont le compte a été bloqué temporairement (PIX-6406)
  mon-pix/app/components/signin-form.js
  mon-pix/config/environment.js
  mon-pix/mirage/routes/authentication/post-authentications.js
  mon-pix/tests/integration/components/signin-form_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5305 [BUGFIX][API] Ne pas vérifier si l'utilisateur est bloqué lorsqu'une requête pour rafraichir le token d'accès est initiée (PIX-6432)
  api/lib/application/security-pre-handlers.js
  api/tests/acceptance/application/authentication/authentication-route_test.js
  api/tests/integration/application/security-pre-handlers_test.js
Labels: :rocket: Ready to Merge, team-acces

#5266 [TECH] Utilise les nouvelles clefs de traduction du référentiel
  api/lib/domain/services/get-translated-text.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/certified-profile-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/repositories/tube-repository.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-challenge-for-pix-button_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-campaign-assessment_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-competence-evaluation_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-demo_test.js
  api/tests/acceptance/application/assessments/assessment-controller-update-last-challenge-state_test.js
  api/tests/acceptance/application/campaigns/campaign-controller_test.js
  api/tests/acceptance/application/campaigns/campaign-stats-controller_test.js
  api/tests/acceptance/application/frameworks/frameworks-controller_test.js
  api/tests/acceptance/application/scorecards/scorecard-controller_test.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-user-profile-for-admin_test.js
  api/tests/acceptance/application/users/users-controller-get-user-profile_test.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/acceptance/application/users/users-get-shared-profile-for-campaign_test.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/domain/usecases/get-campaign-participations-counts-by-stage_test.js
  api/tests/integration/domain/usecases/handle-badge-acquisition_test.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certified-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/competence-repository_test.js
  api/tests/integration/infrastructure/repositories/learning-content-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-for-admin-repository_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/integration/infrastructure/repositories/tube-repository_test.js
  api/tests/integration/scripts/fill-skill-id-in-user-saved-tutorials_test.js
  api/tests/integration/scripts/prod/compute-badge-acquisitions_test.js
  api/tests/tooling/domain-builder/factory/build-area-learning-content-data-object.js
  api/tests/tooling/domain-builder/factory/build-competence-learning-content-data-object.js
  api/tests/tooling/fixtures/infrastructure/skillLearningContentDataObjectFixture.js
  api/tests/tooling/fixtures/infrastructure/tubeLearningContentDataObjectFixture.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/unit/domain/services/get-translated-text_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5312 [BUGFIX] Stabiliser le test flaky sur InMemoryTemporaryStorage.update()
  api/tests/unit/infrastructure/temporary-storage/InMemoryTemporaryStorage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5224 [FEATURE] Création de RT par sujets cappés (PIX-5595)
  admin/app/components/badges/skill-set-criterion.js
  admin/app/components/target-profiles/badge-form.hbs
  admin/app/components/target-profiles/badge-form.js
  admin/app/components/target-profiles/badge-form/campaign-criterion.hbs
  admin/app/components/target-profiles/badge-form/capped-tubes-criterion.hbs
  admin/app/components/target-profiles/badge-form/capped-tubes-criterion.js
  admin/app/components/target-profiles/badge-form/criteria.hbs
  admin/app/components/target-profiles/badge-form/criteria.js
  admin/app/components/target-profiles/badge-form/old-criteria.hbs
  admin/app/components/target-profiles/tubes-selection/tube.js
  admin/app/models/badge.js
  admin/app/styles/components/target-profiles/badge-form.scss
  admin/mirage/factories/target-profile.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/integration/components/target-profiles/badge-form_test.js
  api/lib/application/target-profiles/index.js
  api/lib/domain/usecases/create-badge.js
  api/lib/infrastructure/repositories/badge-criteria-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/acceptance/application/target-profiles/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5309 [FEATURE] Bloquer définitivement l'utilisateur après 50 entrées de mots de passe erronés (PIX-6385)
  api/lib/application/error-manager.js
  api/lib/application/usecases/checkIfUserIsBlocked.js
  api/lib/config.js
  api/lib/domain/errors.js
  api/lib/domain/models/UserLogin.js
  api/lib/domain/services/authentication/pix-authentication-service.js
  api/sample.env
  api/tests/integration/application/security-pre-handlers_test.js
  api/tests/unit/domain/models/UserLogin_test.js
  api/tests/unit/domain/services/authentication/pix-authentication-service_test.js
  mon-pix/app/components/signin-form.js
  mon-pix/config/environment.js
  mon-pix/mirage/routes/authentication/post-authentications.js
  mon-pix/tests/integration/components/signin-form_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5310 [TECH] Remplacer `ember-moment` par `ember-dayjs` sur Pix Certif (PIX-6426).
  certif/app/components/add-student-list.hbs
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/session-summary-list.hbs
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/header.hbs
  certif/app/routes/application.js
  certif/app/routes/authenticated/sessions/update.js
  certif/app/templates/authenticated/restricted-access.hbs
  certif/app/templates/authenticated/sessions/details.hbs
  certif/config/environment.js
  certif/ember-cli-build.js
  certif/mirage/factories/certification-candidate.js
  certif/mirage/factories/session.js
  certif/mirage/factories/student.js
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/session-details_test.js
  certif/tests/acceptance/session-update_test.js
  certif/tests/helpers/setup-intl.js
  certif/tests/unit/routes/application_test.js
Labels: :rocket: Ready to Merge, team-certif, team-rocket

#5277 [FEATURE] Creer un script pour retrouver les certifications CFP non envoyés (PIX-6257)
  api/db/database-builder/factory/build-certification-course.js
  api/db/migrations/20221121154233_cpf-import-status-migration.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/infrastructure/jobs/cpf-export/handlers/create-and-upload.js
  api/lib/infrastructure/jobs/cpf-export/handlers/planner.js
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/scripts/certification/get-cpf-import-status-from-xml.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/integration/infrastructure/jobs/cpf-export/handlers/create-and-upload_test.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/integration/scripts/certification/files/xml/cpfImportLog.xml
  api/tests/integration/scripts/certification/files/xml/cpfImportLogEmpty.xml
  api/tests/integration/scripts/certification/get-cpf-import-status-from-xml_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/create-and-upload_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/planner_test.js
  api/tests/unit/scripts/files/xml/cpfImportLog.xml
  api/tests/unit/scripts/files/xml/cpfImportLogEmpty.xml
  api/tests/unit/scripts/get-cpf-import-status-from-xml_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5313 [TECH] Better blocking error codes
  api/lib/domain/errors.js
  api/tests/integration/application/security-pre-handlers_test.js
  mon-pix/app/components/signin-form.js
  mon-pix/config/environment.js
  mon-pix/mirage/routes/authentication/post-authentications.js
  mon-pix/tests/integration/components/signin-form_test.js
Labels: :rocket: Ready to Merge, team-acces

#5270 [TECH] Ajout de shell.nix pour le gestionnaire de package nix.
  shell.nix
Labels: :rocket: Ready to Merge, cross-team
