Repository 1024pix/pix, pull requests merged in 2022-07, with the labels that each got.

#4595 [BUGFIX] Rendre le bouton "J'envoie mes résultats" lisible par les lecteurs d'écran (PIX-5251)
  mon-pix/app/components/campaign-share-button.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4603 [BUGFIX] Erreur de fichier de config babel manquant lors du lint de l'API en local
  api/.eslintrc.yaml
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4599 [TECH] Arrêter gracieusement les exécutions.
  api/.eslintrc.yaml
  api/lib/application/run-jobs.js
  api/scripts/.eslintrc.yaml
  api/scripts/_template.js
  api/scripts/bigint/knowledge-elements/prepare-ke-bigint-id-to-be-used-as-primary-key.js
  api/tests/acceptance/scripts/_template.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4065 [TECH] Remonter toutes les violations de lint.
  admin/package.json
  api/package.json
  certif/package.json
  mon-pix/package.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4596 [BUGFIX] Rendre ses couleurs au certificat/certificat partagé (PIX-5230)
  mon-pix/app/styles/components/_user-certifications-detail-competence.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4536 [TECH] Utiliser Ember Testing Library dans l'application Certif
  certif/app/components/session-supervising/candidate-in-list.js
  certif/tests/acceptance/authenticated_test.js
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/acceptance/session-details-parameters_test.js
  certif/tests/helpers/extended-ember-test-helpers/click-by-label.js
  certif/tests/integration/components/login-form_test.js
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
  certif/tests/integration/components/session-finalization/finalization-confirmation-modal_test.js
  certif/tests/integration/components/session-finalization/uncompleted-reports-information-step_test.js
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/tests/integration/components/session-supervising/candidate-list_test.js
  certif/tests/integration/components/session-supervising/header_test.js
  certif/tests/integration/components/user-logged-menu_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#4571 [TECH] Utiliser les fontes de Pix-Ui sur Pix App (PIX-5128)
  mon-pix/app/styles/globals/_fonts.scss
  mon-pix/config/environment.js
  mon-pix/ember-cli-build.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/public/fonts/RobotoMono/RobotoMono-Regular.ttf
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4602 [FEATURE] Traduire les compétences sur le certificat/certificat partagé en EN (PIX-5231)
  api/lib/application/certifications/certification-controller.js
  api/lib/domain/usecases/certificate/get-private-certificate.js
  api/lib/domain/usecases/certificate/get-shareable-certificate.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/competence-tree-repository.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/usecases/get-private-certificate_test.js
  api/tests/unit/domain/usecases/get-shareable-certificate_test.js
  api/tests/unit/infrastructure/repositories/competence-tree-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4611 [TECH] Tutos v2.1 - Ajoute le feature toggle pour la sidebar de filtres (PIX-4916)
  api/lib/config.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  mon-pix/app/models/feature-toggle.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, cross-team

#4609 [FEATURE] Afficher les informations d'un profil utilisateur dans Pix Admin (PIX-5268)
  admin/app/components/users/user-detail-personal-information.hbs
  admin/app/components/users/user-detail-personal-information/user-profile.hbs
  admin/app/models/profile.js
  admin/app/models/scorecard.js
  admin/app/styles/app.scss
  admin/app/styles/components/users/user-detail-personal-information/user-profile.scss
  admin/tests/integration/components/users/user-detail-personal-information/schooling-registration-information_test.js
  admin/tests/integration/components/users/user-detail-personal-information/user-profile_test.js
  admin/tests/integration/components/users/user-detail-personal-information_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4613 [BUGFIX] Ajoute un point manquant dans le texte de la page de maintenance planifiée
  certif/maintenance_scheduled.html
  mon-pix/maintenance_scheduled.html
  orga/maintenance_scheduled.html
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains

#4598 [FEATURE] Modifier les signalements (PIX-5192).
  admin/app/components/certifications/issue-report.hbs
  admin/app/components/certifications/issue-reports/resolve-issue-report-modal.hbs
  admin/app/components/certifications/issue-reports/resolve-issue-report-modal.js
  admin/app/models/certification-issue-report.js
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/integration/components/certifications/issue-report_test.js
  admin/tests/integration/components/certifications/issue-reports/resolve-issue-report-modal_test.js
  admin/tests/unit/models/certification-issue-report_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4597 [TECH] Ajouter le système de traduction dans pix certif (PIX-5205)
  certif/app/adapters/application.js
  certif/app/formats.js
  certif/app/routes/application.js
  certif/app/templates/login.hbs
  certif/config/ember-intl.js
  certif/package-lock.json
  certif/package.json
  certif/tests/unit/adapters/application_test.js
  certif/tests/unit/routes/application_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4618 [FEATURE] App - Allonge le cache pour les polices de Pix UI
  mon-pix/servers.conf.erb
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-captains

#4623 [BUGFIX] Corriger la checkbox seulement sur la page d'inscription (PIX-5294)
  mon-pix/app/styles/components/_signup-form.scss
  mon-pix/app/styles/globals/_redesign-inputs.scss
Labels: :rocket: Ready to Merge, team-acces, cross-team

#4604 [FEATURE] Ajouter un endpoint permettant de télécharger un export XML pour le CPF (PIX-5260)
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/config.js
  api/lib/domain/read-models/CpfCertificationResult.js
  api/lib/domain/read-models/EuropeanNumericLevel.js
  api/lib/domain/read-models/EuropeanNumericLevelFactory.js
  api/lib/domain/services/cpf-certification-xml-export-service.js
  api/lib/domain/usecases/get-cpf-certification-results.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/tooling/domain-builder/factory/build-cpf-certification-result.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/read-models/EuropeanNumericLevelFactory_test.js
  api/tests/unit/domain/services/cpf-certification-xml-export-service_test.js
  api/tests/unit/domain/usecases/get-cpf-certification-results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4619 [BUGFIX] Uniformisation du wording sur la modale de mise à jour de résolution (PIX-5276).
  admin/app/components/certifications/issue-reports/resolve-issue-report-modal.js
  admin/tests/integration/components/certifications/issue-reports/resolve-issue-report-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4625 [TECH] Remplacer moment par dayjs dans Pix Admin (PIX-5297)
  admin/app/components/campaigns/details.hbs
  admin/app/components/campaigns/participation-row.hbs
  admin/app/components/certification-centers/memberships-section.hbs
  admin/app/components/certifications/info-field.hbs
  admin/app/components/organizations/campaigns-section.hbs
  admin/app/components/organizations/invitations.hbs
  admin/app/components/organizations/places.hbs
  admin/app/components/sessions/jury-comment.hbs
  admin/app/helpers/format-date.js
  admin/app/models/to-be-published-session.js
  admin/app/models/with-required-action-session.js
  admin/app/templates/authenticated/certifications/certification/informations.hbs
  admin/ember-cli-build.js
  admin/mirage/config.js
  admin/mirage/factories/session.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/organization-invitations-management_test.js
  admin/tests/integration/components/certification-centers/memberships-section_test.js
  admin/tests/integration/components/certifications/info-field_test.js
  admin/tests/integration/components/organizations/invitations_test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations_test.js
  admin/tests/integration/components/sessions/jury-comment_test.js
  package-lock.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4630 [FEATURE] Ajouter le bouton de filtre sur Pix App (PIX-4930)
  mon-pix/app/components/tutorials/header.hbs
  mon-pix/app/components/tutorials/header.js
  mon-pix/tests/integration/components/tutorials/header_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-evaluation

#4541 [FEATURE] Ajout de la page participants sur PixOrga (PIX-5120).
  api/db/seeds/data/pole-emploi-sendings-builder.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/read-models/OrganizationParticipant.js
  api/lib/domain/usecases/get-paginated-participants-for-an-organization.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/organization-participant-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/organization-participants-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/domain/usecases/get-paginated-participants-for-an-organization_test.js
  api/tests/integration/infrastructure/repositories/organization-participant-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/get-paginated-participants-for-an-organization_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/organization-participants-serializer_test.js
  orga/app/adapters/organization-participant.js
  orga/app/components/layout/sidebar.hbs
  orga/app/components/layout/sidebar.js
  orga/app/components/organization-participant/list.hbs
  orga/app/controllers/authenticated/organization-participants/list.js
  orga/app/models/organization-participant.js
  orga/app/router.js
  orga/app/routes/authenticated/organization-participants/list.js
  orga/app/templates/authenticated/organization-participants/list.hbs
  orga/mirage/config.js
  orga/mirage/factories/organization-participant.js
  orga/mirage/handlers/find-filtered-paginated-organization-participants.js
  orga/mirage/serializers/organization-participant.js
  orga/tests/acceptance/authentication_test.js
  orga/tests/acceptance/organization-participations-list_test.js
  orga/tests/integration/components/layout/sidebar_test.js
  orga/tests/integration/components/organization-participants/list_test.js
  orga/tests/unit/adapters/organization-participant_test.js
  orga/tests/unit/adapters/student_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4587 [API]Utiliser une variable d'évènement pour définir le nombre de connexion à la BDD de PgBoss (PIX-5250).
  api/Procfile
  api/lib/application/run-jobs.js
  api/lib/config.js
  api/sample.env
  docs/assets/job-states.png
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4631 [BUGFIX] Permettre la suppression de session lorsqu'un surveillant a rejoint l'espace surveillant (PIX-5280)
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  certif/app/components/session-summary-list.hbs
  certif/app/components/session-summary-list.js
  certif/app/styles/components/session-summary-list.scss
  certif/tests/acceptance/session-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4632 [TECH] Intégrer les couleurs du design system via Pix-UI pour Pix Certif (PIX-5155)
  certif/app/styles/app.scss
  certif/app/styles/components/add-issue-report-modal.scss
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/components/certif-checkbox.scss
  certif/app/styles/components/certification-candidate-details-modal.scss
  certif/app/styles/components/dropdown.scss
  certif/app/styles/components/ember-cli-notifications-ie-fallback.scss
  certif/app/styles/components/finalize.scss
  certif/app/styles/components/issue-report-modal.scss
  certif/app/styles/components/layout/footer.scss
  certif/app/styles/components/login-form.scss
  certif/app/styles/components/login-session-supervisor-form.scss
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/app/styles/components/pagination-control.scss
  certif/app/styles/components/session-finalization-step-container.scss
  certif/app/styles/components/session-finalization/complementary-information-step.scss
  certif/app/styles/components/session-finalization/examiner-global-comment-step.scss
  certif/app/styles/components/session-finalization/formbuilder-link-step.scss
  certif/app/styles/components/session-finalization/reports-information-step.scss
  certif/app/styles/components/session-summary-list.scss
  certif/app/styles/components/session-supervising/candidate-in-list.scss
  certif/app/styles/components/session-supervising/candidate-list.scss
  certif/app/styles/components/session-supervising/header.scss
  certif/app/styles/components/user-logged-menu.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/globals/panels.scss
  certif/app/styles/globals/tables.scss
  certif/app/styles/globals/texts.scss
  certif/app/styles/globals/titles.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/styles/pages/authenticated/restricted-access.scss
  certif/app/styles/pages/authenticated/sessions/add-student.scss
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates-sco.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/app/styles/pages/login-session-supervisor.scss
  certif/app/styles/pages/login.scss
  certif/app/styles/pages/session-supervising-error.scss
  certif/app/styles/pages/terms-of-service.scss
  certif/package-lock.json
  certif/package.json
Labels: :rocket: Ready to Merge, team-certif, team-evaluation, Design Review OK, cross-team

#4584 [FEATURE] Affichage du petit "i" sur la date de dernière participation dans l'onglet élèves (PIX-5171).
  api/db/database-builder/factory/build-assessment-campaign-for-skills.js
  api/db/database-builder/factory/build-assessment-campaign.js
  api/db/database-builder/factory/build-campaign.js
  api/db/seeds/data/campaigns-sco-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/domain/models/Campaign.js
  api/lib/domain/models/CampaignCreator.js
  api/lib/domain/models/CampaignToStartParticipation.js
  api/lib/domain/models/CampaignTypes.js
  api/lib/domain/models/UserWithOrganizationLearner.js
  api/lib/domain/read-models/CampaignReport.js
  api/lib/domain/read-models/CampaignToJoin.js
  api/lib/domain/validators/campaign-creation-validator.js
  api/lib/domain/validators/campaign-validator.js
  api/lib/infrastructure/repositories/campaign-management-repository.js
  api/lib/infrastructure/repositories/campaign-participant-activity-repository.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/organization-learner-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-with-organization-learner-serializer.js
  api/scripts/prod/create-assessment-campaigns-for-sco.js
  api/scripts/prod/create-profiles-collection-campaigns.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/domain/usecases/create-campaign_test.js
  api/tests/integration/infrastructure/repositories/campaign-management-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-info-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-learner-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-results-shared-repository_test.js
  api/tests/integration/scripts/prod/compute-participation-results_test.js
  api/tests/integration/scripts/prod/compute-pole-emploi-sendings_test.js
  api/tests/integration/scripts/prod/create-profiles-collection-campaigns_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-management.js
  api/tests/tooling/domain-builder/factory/build-campaign-report.js
  api/tests/tooling/domain-builder/factory/build-campaign-to-join.js
  api/tests/tooling/domain-builder/factory/build-campaign-to-start-participation.js
  api/tests/tooling/domain-builder/factory/build-campaign.js
  api/tests/unit/domain/models/CampaignCreator_test.js
  api/tests/unit/domain/models/CampaignForCreation_test.js
  api/tests/unit/domain/models/CampaignParticipation_test.js
  api/tests/unit/domain/models/CampaignToStartParticipation_test.js
  api/tests/unit/domain/read-models/CampaignReport_test.js
  api/tests/unit/domain/read-models/CampaignToJoin_test.js
  api/tests/unit/domain/usecases/create-campaign_test.js
  api/tests/unit/domain/validators/campaign-validator_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-organization-learner-serializer_test.js
  orga/app/components/student/sco/last-participation-date-tooltip.hbs
  orga/app/components/student/sco/last-participation-date-tooltip.js
  orga/app/components/student/sco/list.hbs
  orga/app/models/student.js
  orga/app/styles/app.scss
  orga/app/styles/components/student/sco/last-participation-date-tooltip.scss
  orga/app/styles/pages/authenticated/students/list.scss
  orga/tests/integration/components/students/sco/last-participation-date-tooltip_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4638 [BUGFIX] Améliorer le message indiquant la présence d'une alternative textuelle sur les illustrations dans une épreuve sur Pix App (PIX-5271)
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-evaluation

#4633 [BUGFIX] Afficher le résultat d'une campagne inactive seulement pour les participations partagées (PIX-5296)
  mon-pix/app/components/campaign-participation-overview/card/disabled.hbs
  mon-pix/app/components/campaign-participation-overview/card/disabled.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/disabled_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4646 [FEATURE] Ramener le contexte des tutoriels lorsqu'ils sont présentés au moment de la correction (PIX-5326).
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-attributes.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4621 [FEATURE] Revenir sur la page d'origine de la liste des sessions (PIX-5259).
  certif/app/routes/authenticated/sessions/list.js
  certif/mirage/config.js
  certif/mirage/handlers/find-paginated-session-summaries.js
  certif/mirage/serializers/session-summary.js
  certif/tests/acceptance/session-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4642 [FEATURE] Modifier le libellé d'un signalement de sous-catégorie E11 (PIX-5290)
  admin/app/models/certification-issue-report.js
  admin/tests/integration/components/certifications/issue-report_test.js
  certif/app/models/certification-issue-report.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4645 [BUGFIX] Suppression de la section "Autres certif comp" sur un certificat avec un commentaire (PIX-5274).
  mon-pix/app/components/user-certifications-detail-result.hbs
  mon-pix/tests/integration/components/user-certifications-detail-result_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4648 [BUGFIX] Après être réconcilié on ne peut pas accéder a une autre campagne SCO de la même organisation (PIX-5328).
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/infrastructure/serializers/jsonapi/organization-learner-identity-serializer.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-learner-identity-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4567 [FEATURE] Générer un token lors du changement de mot de passe temporaire (PIX-5202)
  api/lib/application/error-manager.js
  api/lib/application/http-errors.js
  api/lib/application/passwords/index.js
  api/lib/application/passwords/password-controller.js
  api/lib/config.js
  api/lib/domain/errors.js
  api/lib/domain/services/token-service.js
  api/lib/domain/usecases/authenticate-external-user.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/domain/usecases/update-expired-password.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/authentication-route_test.js
  api/tests/acceptance/application/password-controller_test.js
  api/tests/integration/application/passwords/index_test.js
  api/tests/integration/application/passwords/password-controller_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/application/passwords/index_test.js
  api/tests/unit/application/passwords/password-controller_test.js
  api/tests/unit/domain/services/token-service_test.js
  api/tests/unit/domain/usecases/authenticate-external-user_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/update-expired-password_test.js
  mon-pix/app/adapters/reset-expired-password-demand.js
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signin-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/models/reset-expired-password-demand.js
  mon-pix/app/routes/login.js
  mon-pix/mirage/factories/reset-expired-password-demand.js
  mon-pix/mirage/routes/auth/index.js
  mon-pix/mirage/routes/auth/post-authentications.js
  mon-pix/mirage/routes/post-expired-password-updates.js
  mon-pix/tests/acceptance/authentication_test.js
  mon-pix/tests/integration/components/routes/login-form_test.js
  mon-pix/tests/integration/components/update-expired-password-form_test.js
  mon-pix/tests/unit/adapters/reset-expired-password-demand_test.js
  mon-pix/tests/unit/components/routes/login-form_test.js
  mon-pix/tests/unit/components/signin-form_test.js
  mon-pix/tests/unit/components/update-expired-password-form_test.js
  mon-pix/tests/unit/models/reset-expired-password-demand_test.js
  mon-pix/tests/unit/routes/login_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4651 [TECH] Monter la version des BDD de tests de 13.3 à 13.7
  .circleci/config.yml
  docker-compose.yaml
  high-level-tests/e2e/docker-compose.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4647 [TECH] Ajouter la colonne "level" à la table complementary-certification-badges (PIX-5203)
  api/db/migrations/20220711194824_add-level-to-complementary-certification-badges.js
  api/db/migrations/20220712082535_insert-complementary-certification-badges.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4570 [FEATURE] Rajouter un filtre pour chercher par nom et prénom sur la liste des participations de la page résultats (PIX-5060).
  api/lib/application/campaign-participations/index.js
  api/lib/application/campaigns/index.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/campaign-participations/campaign-participations-controller-find-shared-participations_test.js
  api/tests/integration/domain/usecases/find-assessment-participation-result-list_test.js
  api/tests/integration/domain/usecases/find-campaign-profiles-collection-participation-summaries_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-list-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/assessment-results.js
  orga/app/controllers/authenticated/campaigns/campaign/profile-results.js
  orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
  orga/app/routes/authenticated/campaigns/campaign/profile-results.js
  orga/app/styles/app.scss
  orga/app/styles/components/participation-filters.scss
  orga/app/styles/components/search-input.scss
  orga/app/styles/globals/forms.scss
  orga/app/styles/globals/tables.scss
  orga/app/styles/pages/authenticated/campaigns/details/participants.scss
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/campaign-assessment-results_test.js
  orga/tests/acceptance/campaign-profiles_test.js
  orga/tests/acceptance/preselect-target-profile_test.js
  orga/tests/integration/components/campaign/results/assessment-list_test.js
  orga/tests/integration/components/campaign/results/profile-list_test.js
  orga/tests/integration/components/tube/list_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/assessment-results_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/profile-results_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/assessment-results_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/profile-results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4589 [TECH] Télécharger le dernier backup terminé dans le script de restauration de BDD.
  api/scripts/database/restore-dump/download-backup.js
Labels: :rocket: Ready to Merge, team-captains, cross-team

#4586 [TECH][ADMIN]Ajouter un service pour intercepter et notifier des erreurs de requêtes api (PIX-5244)
  admin/app/components/team/add-member.js
  admin/app/components/team/list.js
  admin/app/services/error-response-handler.js
  admin/tests/acceptance/authenticated/team/add-member_test.js
  admin/tests/acceptance/authenticated/team/list_test.js
  admin/tests/integration/components/team/list_test.js
  admin/tests/unit/routes/authenticated/certifications/certification/profile_test.js
  admin/tests/unit/routes/authenticated/sessions/list/all_test.js
  admin/tests/unit/routes/authenticated/sessions/list/to-be-published_test.js
  admin/tests/unit/routes/authenticated/sessions/session_test.js
  admin/tests/unit/routes/authenticated/target-profiles/list_test.js
  admin/tests/unit/routes/authenticated/target-profiles/target-profile/organizations_test.js
  admin/tests/unit/services/error-response-handler_test.js
  api/lib/domain/errors.js
  api/lib/infrastructure/repositories/admin-member-repository.js
  api/tests/integration/infrastructure/repositories/admin-member-repository_test.js
Labels: :rocket: Ready to Merge, team-acces, cross-team

#4643 [FEATURE] Affichage de la date de dernière participation dans l'onglet étudiants (PIX-5173).
  orga/app/components/student/sup/list.hbs
  orga/tests/integration/components/students/sup/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4593 [TECH] Déplacer le ticket Jira en review seulement si la PR n'est pas en draft (PIX-5253).
  .github/workflows/jira-transition-to-review.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4639 [FEATURE] Nouvel affichage page détails d'un profil cible (PIX-5311)
  admin/app/components/target-profiles/details.hbs
  admin/app/components/target-profiles/tubes-details/area.hbs
  admin/app/components/target-profiles/tubes-details/competence.hbs
  admin/app/components/target-profiles/tubes-details/thematic.hbs
  admin/app/components/target-profiles/tubes-details/tube.hbs
  admin/app/controllers/authenticated/target-profiles/target-profile/details.js
  admin/app/models/target-profile.js
  admin/app/models/tube.js
  admin/app/templates/authenticated/target-profiles/target-profile/details.hbs
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/TargetProfileWithLearningContent.js
  api/lib/domain/models/TargetedArea.js
  api/lib/domain/models/TargetedCompetence.js
  api/lib/domain/models/TargetedThematic.js
  api/lib/domain/models/TargetedTube.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/domain/usecases/find-assessment-participation-result-list_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-with-learning-content.js
  api/tests/tooling/domain-builder/factory/build-targeted-area.js
  api/tests/tooling/domain-builder/factory/build-targeted-competence.js
  api/tests/tooling/domain-builder/factory/build-targeted-thematic.js
  api/tests/tooling/domain-builder/factory/build-targeted-tube.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-with-learning-content-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#4650 [FEATURE] Tracer la résolution automatique sur les signalements (PIX-5258)
  api/db/database-builder/factory/build-certification-issue-report.js
  api/db/migrations/20220712125907_add-hasBeenAutomaticallyResolved-column-to-certification-issue-reports.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportResolutionStrategies.js
  api/lib/domain/usecases/manually-resolve-certification-issue-report.js
  api/lib/infrastructure/repositories/certification-issue-report-repository.js
  api/lib/infrastructure/repositories/jury-certification-repository.js
  api/tests/integration/infrastructure/repositories/certification-issue-report-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-issue-report.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  api/tests/unit/domain/usecases/manually-resolve-certification-issue-report_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#4608 [TECH] Empêcher le chevauchement :horse: des seeds et des données de test automatiques.
  api/db/database-builder/database-builder.js
  api/db/seeds/data/certification/tooling.js
  api/db/seeds/data/organizations-sco-builder.js
  api/db/seeds/seed.js
  api/tests/unit/tooling/database-builder/database-builder_test.js
Labels: :rocket: Ready to Merge, team-certif, cross-team

#4637 [TECH] Recalculer l'acquisitions des badges grâce à un script (PIX-5310).
  api/scripts/_template.js
  api/scripts/prod/compute-badge-acquisitions.js
  api/tests/integration/scripts/prod/compute-badge-acquisitions_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4634 [FEATURE] Ajouter une condition dans la réconciliation automatique lors de l'import SIECLE (PIX-4594).
  api/lib/infrastructure/repositories/organization-learner-repository.js
  api/lib/infrastructure/repositories/student-repository.js
  api/tests/integration/infrastructure/repositories/organization-learner-repository_test.js
  api/tests/integration/infrastructure/repositories/student-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#4655 [TECH] Intégrer le composant PixMessage dans Pix-App (PIX-5322)
  mon-pix/app/components/challenge-item-qcm.hbs
  mon-pix/app/components/challenge-item-qcu.hbs
  mon-pix/app/components/challenge-item-qroc.hbs
  mon-pix/app/components/challenge-item-qrocm.hbs
  mon-pix/app/components/feedback-panel.hbs
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/globals/_alert.scss
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/integration/components/feedback-panel_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4652 [FEATURE] Ramener le contexte des tutoriels lorsqu'ils sont présentés dans la page de détail d'une compétence (PIX-5338).
  api/lib/domain/usecases/find-tutorials.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/domain/usecases/find-tutorials_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4662 [TECH] Corrige le format du fichier package-lock.json
  orga/package-lock.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4607 [TECH] Renommer www en index.js
  api/Procfile
  api/bin/www
  api/index.js
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#3839 [TECH] Migrer la colonne answers.id de INTEGER en BIG INTEGER avec downtime.
  api/scripts/bigint/change-answers-id-type-to-bigint-with-downtime.js
  api/tests/acceptance/scripts/bigint/change-answers-id-type-to-bigint-with-downtime_test.js
Labels: :rocket: Ready to Merge, cross-team, bigint

#4629 [FEATURE] Envoyer le fichier d'export des certification pour le CPF sur un espace de stockage OVH (PIX-5309)
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/config.js
  api/lib/domain/services/cpf-certification-xml-export-service.js
  api/lib/infrastructure/external-storage/cpf-external-storage.js
  api/lib/infrastructure/validate-environement-variables.js
  api/package-lock.json
  api/package.json
  api/sample.env
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/services/cpf-certification-xml-export-service_test.js
  api/tests/unit/infrastructure/external-storage/cpf-external-storage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4656 [TECH] Rétablir la preview des challenges focus en local (PIX-5353).
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/routes/assessments/challenge.js
  mon-pix/app/services/focused-certification-challenge-warning-manager.js
  mon-pix/tests/unit/controllers/assessments/challenge_test.js
  mon-pix/tests/unit/services/focused-certification-challenge-warning-manager_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4667 [FEATURE] Afficher la liste des participations aux campagne pour un utilisateur dans Pix Admin (PIX-5365).
  admin/app/components/badges/badge.hbs
  admin/app/components/campaigns/participations-section.hbs
  admin/app/components/certification-centers/information.hbs
  admin/app/components/certification-centers/memberships-section.hbs
  admin/app/components/certifications/certified-profile.hbs
  admin/app/components/organizations/all-tags.hbs
  admin/app/components/organizations/campaigns-section.hbs
  admin/app/components/organizations/information-section.hbs
  admin/app/components/organizations/invitations-action.hbs
  admin/app/components/organizations/invitations.hbs
  admin/app/components/organizations/target-profiles-section.hbs
  admin/app/components/organizations/team-actions-section.hbs
  admin/app/components/organizations/team-section.hbs
  admin/app/components/stages/stage.hbs
  admin/app/components/stages/update-stage.hbs
  admin/app/components/target-profiles/organizations.hbs
  admin/app/components/users/user-detail-personal-information.hbs
  admin/app/components/users/user-detail-personal-information/campaign-participations.hbs
  admin/app/components/users/user-detail-personal-information/user-overview.hbs
  admin/app/models/user-participation.js
  admin/app/models/user.js
  admin/app/routes/authenticated/users/get.js
  admin/app/styles/globals/page.scss
  admin/app/templates/authenticated/certification-centers/get.hbs
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/tests/integration/components/users/user-detail-personal-information/campaign-participations_test.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/read-models/CampaignParticipationForUserManagement.js
  api/lib/domain/usecases/find-campaign-participations-for-user-management.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/participations-for-user-management-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-participation-for-user-management-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/acceptance/application/users/find-campaign-participations-for-user-management_test.js
  api/tests/acceptance/application/users/users-controller-get-user-details-for-admin_test.js
  api/tests/integration/infrastructure/repositories/participations-for-user-management-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-for-user-management.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/domain/usecases/find-campaign-participations-for-user-management_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-for-user-management-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, 🌟 Etoile, Func Review OK, team-prescription

#4663 [FEATURE] Restreindre l'accès aux campagnes de l'organisation CNAV sur Pix App(PIX-5114).
  api/db/seeds/data/campaigns-pro-builder.js
  api/db/seeds/data/organizations-pro-builder.js
  api/db/seeds/data/target-profiles-builder.js
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/cnav/cnav-controller.js
  api/lib/application/pole-emploi/pole-emploi-controller.js
  api/lib/domain/constants.js
  api/lib/domain/services/authentication/authentication-service-registry.js
  api/lib/domain/services/authentication/cnav-authentication-service.js
  api/lib/domain/services/authentication/cnav-oidc-authentication-service.js
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/lib/domain/services/authentication/pole-emploi-authentication-service.js
  api/lib/domain/services/authentication/pole-emploi-oidc-authentication-service.js
  api/lib/domain/usecases/authentication/authenticate-cnav-user.js
  api/lib/domain/usecases/authentication/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/create-user-from-external-identity-provider.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/cnav/cnav-controller_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/domain/services/authentication/cnav-authentication-service_test.js
  api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
  api/tests/unit/domain/services/authentication/pole-emploi-authentication-service_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-cnav-user_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/create-user-from-external-identity-provider_test.js
  mon-pix/app/authenticators/cnav.js
  mon-pix/app/models/campaign.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/campaigns/access.js
  mon-pix/app/routes/login-cnav.js
  mon-pix/tests/unit/routes/application_test.js
  mon-pix/tests/unit/routes/campaigns/access_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4654 [FEATURE] Afficher les candidat inscrits lors de la suppression d'une session (PIX-5337)
  certif/app/components/session-delete-confirm-modal.hbs
  certif/app/components/session-summary-list.hbs
  certif/app/components/session-summary-list.js
  certif/app/styles/app.scss
  certif/app/styles/components/session-delete-confirm-modal.scss
  certif/tests/integration/components/session-delete-confirm-modal_test.js
  certif/tests/integration/components/session-summary-list_test.js
  certif/tests/unit/components/session-summary-list_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4658 [TECH] Supprimer le feature toggle de la suppression des champs libres (PIX-5333)
  api/lib/config.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/infrastructure/validate-environement-variables.js
  api/tests/acceptance/application/certification-report-controller_test.js
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  api/tests/unit/domain/usecases/save-certification-issue-report_test.js
  certif/app/components/issue-report-modal/add-issue-report-modal.hbs
  certif/app/components/issue-report-modal/add-issue-report-modal.js
  certif/app/components/issue-report-modal/fraud-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/other-certification-issue-report-fields.hbs
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/models/certification-issue-report.js
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/integration/components/issue-report-modal/add-issue-report-modal_test.js
  certif/tests/integration/components/issue-report-modal/fraud-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/other-certification-issue-report-fields_test.js
  certif/tests/integration/components/session-finalization/completed-reports-information-step_test.js
  certif/tests/integration/components/session-finalization/uncompleted-reports-information-step_test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize_test.js
  certif/tests/unit/models/certification-issue-report_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4664 [FEATURE] Utilise la `PixBanner` pour le bandeau de communication sur Pix App (PIX-5361)
  mon-pix/app/components/communication-banner.hbs
  mon-pix/app/components/communication-banner.js
  mon-pix/tests/integration/components/communication-banner_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, cross-team

#4672 [FEATURE] Afficher des onglets dans la page utilisateurs de Pix Admin (PIX-5378).
  admin/app/components/users/campaign-participations.hbs
  admin/app/components/users/campaign-participations.js
  admin/app/components/users/user-detail-personal-information.hbs
  admin/app/components/users/user-detail-personal-information.js
  admin/app/components/users/user-overview.hbs
  admin/app/components/users/user-overview.js
  admin/app/components/users/user-profile.hbs
  admin/app/controllers/authenticated/users/get/campaign-participations.js
  admin/app/controllers/authenticated/users/get/information.js
  admin/app/models/user.js
  admin/app/router.js
  admin/app/routes/authenticated/users/get.js
  admin/app/routes/authenticated/users/get/campaign-participations.js
  admin/app/routes/authenticated/users/get/information.js
  admin/app/routes/authenticated/users/get/profile.js
  admin/app/styles/app.scss
  admin/app/styles/components/users/user-profile.scss
  admin/app/templates/authenticated/users/get.hbs
  admin/app/templates/authenticated/users/get/campaign-participations.hbs
  admin/app/templates/authenticated/users/get/information.hbs
  admin/app/templates/authenticated/users/get/profile.hbs
  admin/tests/acceptance/authenticated/users/get_test.js
  admin/tests/acceptance/authenticated/users/list_test.js
  admin/tests/acceptance/user-details-personal-information_test.js
  admin/tests/acceptance/user-list_test.js
  admin/tests/integration/components/users/campaign-participations_test.js
  admin/tests/integration/components/users/user-detail-personal-information_test.js
  admin/tests/integration/components/users/user-overview_test.js
  admin/tests/integration/components/users/user-profile_test.js
  admin/tests/unit/components/users/user-overview_test.js
  admin/tests/unit/controllers/authenticated/users/get/information_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4673 [BUGFIX] Suppression temporaire du test d'acceptance du script de migration BIGINT
  api/tests/acceptance/scripts/bigint/change-answers-id-type-to-bigint-with-downtime_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, bigint

#4670 [TECH] Supprimer un fichier de données de test non utilisé.
  api/tests/unit/domain/usecases/siecle.csv
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4678 [FEATURE] Mettre à jour le message de fin de campagne (PIX-5320)
  mon-pix/app/styles/components/_checkpoint.scss
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/tests/acceptance/checkpoint_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4494 [FEATURE] Permettre l'ajout d'un lots de places d'une organisation (Pix-4776).
  admin/app/adapters/organization-place.js
  admin/app/components/organizations/places-lot-creation-form.hbs
  admin/app/components/organizations/places-lot-creation-form.js
  admin/app/components/organizations/places.hbs
  admin/app/components/organizations/places.js
  admin/app/controllers/authenticated/organizations/get/places/new.js
  admin/app/models/organization-place.js
  admin/app/router.js
  admin/app/routes/authenticated/organizations/get/places/list.js
  admin/app/routes/authenticated/organizations/get/places/new.js
  admin/app/services/access-control.js
  admin/app/styles/app.scss
  admin/app/styles/components/organizations/places-lot-creation-form.scss
  admin/app/styles/components/organizations/places.scss
  admin/app/styles/globals/page.scss
  admin/app/templates/authenticated/organizations/get/places.hbs
  admin/app/templates/authenticated/organizations/get/places/list.hbs
  admin/app/templates/authenticated/organizations/get/places/new.hbs
  admin/tests/acceptance/authenticated/organizations/places-lot-creation-form_test.js
  admin/tests/acceptance/authenticated/organizations/places_test.js
  admin/tests/integration/components/organizations/places-lot-creation-form_test.js
  admin/tests/integration/components/organizations/places_test.js
  admin/tests/unit/adapters/organization-places-lot_test.js
  admin/tests/unit/controllers/authenticated/organizations/get/places/new_test.js
  admin/tests/unit/services/access-control-test.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/constants/organization-places-categories.js
  api/lib/domain/models/OrganizationPlacesLot.js
  api/lib/domain/read-models/OrganizationPlacesLotManagement.js
  api/lib/domain/usecases/create-organization-places-lot.js
  api/lib/domain/usecases/find-organization-places-lot.js
  api/lib/domain/usecases/find-organization-places.js
  api/lib/domain/usecases/index.js
  api/lib/domain/validators/organization-places-lot-validator.js
  api/lib/infrastructure/repositories/organizations/organization-place-repository.js
  api/lib/infrastructure/repositories/organizations/organization-places-lot-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/organization-places-lot-management-serializer.js
  api/lib/infrastructure/serializers/jsonapi/organization/organization-places-lot-serializer.js
  api/tests/acceptance/application/organizations/create-organization-places-lot_test.js
  api/tests/acceptance/application/organizations/find-organization-places_test.js
  api/tests/integration/application/organizations/index_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organizations/organization-places-lot-repository_test.js
  api/tests/tooling/domain-builder/factory/build-organization-places-lot-management.js
  api/tests/tooling/domain-builder/factory/build-organization-places-lot.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/organizations/index_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/models/OrganizationPlacesLot_test.js
  api/tests/unit/domain/read-models/OrganizationPlacesLotManagement_test.js
  api/tests/unit/domain/usecases/create-organization-places-lot_test.js
  api/tests/unit/domain/usecases/find-organization-places-lot_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/organization-places-lot-managment-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/organization-places-lot-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4675 [TECH] Corriger les sinon.stub().withArgs() qui ne fonctionnent pas
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/domain/events/compute-campaign-participation-results_test.js
  api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
  api/tests/unit/domain/usecases/save-admin-member_test.js
  certif/tests/unit/routes/authenticated/sessions/update_test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/services/file-saver_test.js
  orga/tests/unit/services/file-saver_test.js
  orga/tests/unit/services/session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, team-certif, team-evaluation, team-prescription, cross-team, team-contenu

#4677 [BUGFIX] Ne pas mettre à jour le rôle d'un agent Pix si aucun nouveau rôle n'est choisi (PIX-5387).
  admin/app/components/team/list.js
  admin/app/components/users/user-detail-personal-information/schooling-registration-information.hbs
  admin/tests/integration/components/team/list_test.js
  admin/tests/unit/components/team/list_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4657 [FEATURE] Ajout d'un id sur le message d'erreur sur la page de connexion de Pix App (PIX-5357)
  mon-pix/app/components/account-recovery/backup-email-confirmation-form.hbs
  mon-pix/app/components/account-recovery/student-information-form.hbs
  mon-pix/app/components/form-textfield-date.hbs
  mon-pix/app/components/form-textfield.hbs
  mon-pix/app/components/password-reset-demand-form.hbs
  mon-pix/app/components/routes/login-form.hbs
  mon-pix/app/components/routes/register-form.hbs
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/components/update-expired-password-form.hbs
  mon-pix/tests/integration/components/password-reset-demand-form_test.js
  mon-pix/tests/integration/components/routes/login-form_test.js
  mon-pix/tests/integration/components/routes/register-form_test.js
  mon-pix/tests/integration/components/signin-form_test.js
  mon-pix/tests/integration/components/signup-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4694 [TECH] Mettre à jour le serveur redis de test de 5.0.7 à 6.2.7
  .circleci/config.yml
  docker-compose.yaml
  high-level-tests/e2e/docker-compose.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4687 [TECH] Ajout d'un feature toggle pour la réconciliation de compte SSO sur Pix App (PIX-5351).
  api/lib/application/preHandlers/feature-toggles.js
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/tests/unit/services/feature-toggles_test.js
Labels: :rocket: Ready to Merge, team-acces

#4615 [FEATURE] Déconnecter un agent Pix qui a été désactivé sur Pix Admin (PIX-5279).
  api/lib/domain/usecases/deactivate-admin-member.js
  api/lib/infrastructure/repositories/admin-member-repository.js
  api/tests/integration/infrastructure/repositories/admin-member-repository_test.js
  api/tests/unit/domain/usecases/deactivate-admin-member_test.js
Labels: :rocket: Ready to Merge, team-acces, cross-team

#4699 [TECH] Ne plus récupérer de propriété id ignorée dans les tests
  api/tests/acceptance/application/certification-issue-report-controller_test.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/acceptance/application/progression-controller_test.js
  api/tests/acceptance/application/session/session-controller-publish-session-in-batch_test.js
  api/tests/integration/domain/event/handle-badge-acquisition_test.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-management-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/end-test-screen-removal-repository_test.js
  api/tests/integration/infrastructure/repositories/membership-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-learner-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-participant-repository_test.js
  api/tests/integration/infrastructure/repositories/prescriber-role-repository_test.js
  api/tests/integration/infrastructure/repositories/sco-certification-candidate-repository_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/integration/scripts/create-certification-center-memberships-from-organization-admins_test.js
  api/tests/integration/scripts/prod/compute-badge-acquisitions_test.js
Labels: :rocket: Ready to Merge, cross-team

#4698 [TECH] Clean : retirer les params inutiles
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/services/pick-challenge-service.js
  api/lib/domain/usecases/get-correction-for-answer.js
  api/scripts/extract-challenge-with-skills.js
Labels: :rocket: Ready to Merge, cross-team

#4684 [FEATURE] Ajouter une tooltip avec les informations de la dernière participation (PIX-5138)
  api/lib/domain/read-models/OrganizationParticipant.js
  api/lib/infrastructure/repositories/organization-participant-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/organization-participants-serializer.js
  api/tests/integration/domain/usecases/get-paginated-participants-for-an-organization_test.js
  api/tests/integration/infrastructure/repositories/organization-participant-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/organization-participants-serializer_test.js
  orga/app/components/organization-participant/list.hbs
  orga/app/components/student/sco/last-participation-date-tooltip.hbs
  orga/app/components/student/sco/list.hbs
  orga/app/components/ui/last-participation-date-tooltip.hbs
  orga/app/components/ui/last-participation-date-tooltip.js
  orga/app/models/organization-participant.js
  orga/app/styles/app.scss
  orga/app/styles/components/ui/last-participation-date-tooltip.scss
  orga/app/styles/pages/authenticated/participants-list.scss
  orga/tests/integration/components/organization-participants/list_test.js
  orga/tests/integration/components/students/sco/last-participation-date-tooltip_test.js
  orga/tests/integration/components/students/sco/list_test.js
  orga/tests/integration/components/ui/last-participation-date-tooltip_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4688 [FEATURE] Pix admin - Profil cible : Retirer la description du sujet dans l'affichage de ce dernier (PIX-5312)
  admin/app/components/target-profiles/tubes-selection/tube.hbs
  admin/app/controllers/authenticated/target-profiles/target-profile/details.js
  admin/app/models/tube.js
  admin/tests/integration/components/target-profiles/tubes-selection_test.js
  api/lib/infrastructure/serializers/jsonapi/framework-areas-serializer.js
  api/tests/acceptance/application/frameworks/frameworks-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/framework-areas-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#4679 [FEATURE] Ajouter des roles WAI-ARIA structurant la page (PIX-5364)
  mon-pix/.template-lintrc.js
  mon-pix/app/components/assessment-banner.hbs
  mon-pix/app/components/campaign-participation-overview/card/disabled.hbs
  mon-pix/app/components/campaign-participation-overview/card/ended.hbs
  mon-pix/app/components/campaign-participation-overview/card/ongoing.hbs
  mon-pix/app/components/campaign-participation-overview/card/to-share.hbs
  mon-pix/app/components/campaign-start-block.hbs
  mon-pix/app/components/certification-banner.hbs
  mon-pix/app/components/challenge/item.hbs
  mon-pix/app/components/competence-card-default.hbs
  mon-pix/app/components/competence-card-mobile.hbs
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/footer.hbs
  mon-pix/app/components/inaccessible-campaign.hbs
  mon-pix/app/components/navbar-burger-menu.hbs
  mon-pix/app/components/navbar-desktop-header.hbs
  mon-pix/app/components/navbar-header.hbs
  mon-pix/app/components/password-reset-demand-form.hbs
  mon-pix/app/components/profile-content.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/invited/fill-in-participant-external-id.hbs
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/components/sitemap/content.hbs
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/components/tutorials/header.hbs
  mon-pix/app/templates/assessments/challenge.hbs
  mon-pix/app/templates/assessments/checkpoint.hbs
  mon-pix/app/templates/campaigns/assessment/tutorial.hbs
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/app/templates/campaigns/invited/student-sco.hbs
  mon-pix/app/templates/campaigns/invited/student-sup.hbs
  mon-pix/app/templates/campaigns/join/sco-mediacentre.hbs
  mon-pix/app/templates/certifications/join.hbs
  mon-pix/app/templates/certifications/start-loading.hbs
  mon-pix/app/templates/certifications/start.hbs
  mon-pix/app/templates/competences/details.hbs
  mon-pix/app/templates/competences/results.hbs
  mon-pix/app/templates/error.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/app/templates/fill-in-certificate-verification-code.hbs
  mon-pix/app/templates/not-connected.hbs
  mon-pix/app/templates/profile.hbs
  mon-pix/app/templates/sitemap.hbs
  mon-pix/app/templates/user-account.hbs
  mon-pix/app/templates/user-certifications.hbs
  mon-pix/app/templates/user-certifications/index.hbs
  mon-pix/app/templates/user-dashboard.hbs
  mon-pix/app/templates/user-tests.hbs
  mon-pix/app/templates/user-tutorials.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4680 [FEATURE] Ne plus centrer la `PixBanner` de comm' sur Certif (PIX-5391)
  certif/app/styles/app.scss
  certif/app/styles/components/communication-banner.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#4681 [FEATURE] Ne plus centrer la PixBanner de comm' sur Orga (PIX-5390)
  orga/app/styles/app.scss
  orga/app/styles/components/banner/communication.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#4689 [FEATURE] Pix admin - Page détail d'un nouveau PC : reprendre les CTA (PIX-5313)
  admin/app/controllers/authenticated/target-profiles/target-profile.js
  admin/app/styles/components/target-profiles/target-profile.scss
  admin/app/templates/authenticated/target-profiles/target-profile.hbs
  admin/tests/acceptance/authenticated/target-profiles/target-profile/details_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Design Review OK, team-contenu

#4682 [FEATURE] Extraire le composant action chip (PIX-4827)
  mon-pix/app/components/action-chip.hbs
  mon-pix/app/components/action-chip.js
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/components/tutorials/card.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_action-chip.scss
  mon-pix/app/styles/components/_tutorial-card.scss
  mon-pix/tests/unit/components/action-chip_test.js
  mon-pix/tests/unit/components/tutorials/card_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4575 [TECH] Générer l'url de déconnexion de Pôle Emploi depuis l'API (PIX-4950)
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/oidc/index.js
  api/lib/application/authentication/oidc/oidc-controller.js
  api/lib/application/pole-emploi/pole-emploi-controller.js
  api/lib/config.js
  api/lib/domain/services/authentication/pole-emploi-authentication-service.js
  api/lib/domain/usecases/authentication/authenticate-pole-emploi-user.js
  api/lib/routes.js
  api/sample.env
  api/tests/acceptance/application/pole-emploi/token-route-post_test.js
  api/tests/integration/application/authentication/oidc/index_test.js
  api/tests/integration/domain/services/authentication/pole-emploi-authentication-service_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/authentication/oidc/oidc-controller_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-pole-emploi-user_test.js
  mon-pix/app/authenticators/pole-emploi.js
  mon-pix/config/environment.js
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/auth/index.js
  mon-pix/tests/acceptance/pole-emploi/pole-emploi-authentication-flow_test.js
  mon-pix/tests/unit/authenticators/pole-emploi_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4711 [TECH] Supprimer l'idToken dans redis après utilisation (PIX-4950).
  api/lib/application/authentication/oidc/index.js
  api/lib/domain/services/authentication/pole-emploi-authentication-service.js
  api/tests/acceptance/application/pole-emploi/token-route-post_test.js
  api/tests/integration/domain/services/authentication/pole-emploi-authentication-service_test.js
Labels: :rocket: Ready to Merge, team-acces

#4702 [BUGFIX] Passer l'adresse e-mail en minuscule lors de l'ajout de membre à une organisation dans Pix Admin (PIX-1772).
  admin/app/controllers/authenticated/organizations/get/team.js
  admin/app/models/organization.js
  admin/app/models/user.js
  admin/tests/unit/controllers/authenticated/organizations/get/team_test.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4704 [FEATURE] Envoyer le contexte du tutorial lors de l'enregistrement de ce dernier (PIX-5339).
  mon-pix/app/adapters/user-tutorial.js
  mon-pix/app/components/tutorials/card.js
  mon-pix/tests/unit/adapters/user-tutorial_test.js
  mon-pix/tests/unit/components/tutorials/card_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4710 [TECH] Mutualiser la déserialisation des payload avec un middleware (PIX-5415).
  api/lib/application/campaigns/campaign-controller.js
  api/server.js
  api/tests/unit/application/campaign/campaign-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#4713 [TECH] Ajoute les complementary-certification-badges manquant des seeds (PIX-5430)
  api/db/database-builder/factory/build-complementary-certification-badge.js
  api/db/seeds/data/badges-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4692 [TECH] Utiliser le nouveau service d'authentification OIDC pour la CNAV et Pôle Emploi (PIX-5388).
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/oidc/oidc-controller.js
  api/lib/application/cnav/cnav-controller.js
  api/lib/application/cnav/index.js
  api/lib/application/pole-emploi/index.js
  api/lib/application/pole-emploi/pole-emploi-controller.js
  api/lib/config.js
  api/lib/domain/services/authentication/authentication-service-registry.js
  api/lib/domain/services/authentication/cnav-authentication-service.js
  api/lib/domain/services/authentication/cnav-oidc-authentication-service.js
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/lib/domain/services/authentication/pole-emploi-authentication-service.js
  api/lib/domain/services/authentication/pole-emploi-oidc-authentication-service.js
  api/lib/domain/usecases/authentication/authenticate-cnav-user.js
  api/lib/domain/usecases/authentication/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/create-user-from-external-identity-provider.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/pole-emploi-controller_test.js
  api/tests/acceptance/application/pole-emploi/token-route-post_test.js
  api/tests/acceptance/application/pole-emploi/users-route-post_test.js
  api/tests/integration/domain/services/authentication/pole-emploi-authentication-service_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/authentication/oidc/oidc-controller_test.js
  api/tests/unit/application/cnav/cnav-controller_test.js
  api/tests/unit/application/pole-emploi/pole-emploi-controller_test.js
  api/tests/unit/domain/services/authentication/cnav-authentication-service_test.js
  api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
  api/tests/unit/domain/services/authentication/pole-emploi-authentication-service_test.js
  api/tests/unit/domain/services/authentication/pole-emploi-oidc-authentication-service_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-cnav-user_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/create-user-from-external-identity-provider_test.js
  docs/security/poleEmploi/authenticate_open_id.part1.puml
  docs/security/poleEmploi/authenticate_with_pole_emploi.puml
Labels: :rocket: Ready to Merge, team-acces

#4707 [FEATURE] Filtrer les participants par nom et prénom (PIX-5122).
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/get-paginated-participants-for-an-organization.js
  api/lib/infrastructure/repositories/campaign-participant-activity-repository.js
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/lib/infrastructure/repositories/organization-participant-repository.js
  api/lib/infrastructure/utils/filter-utils.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/domain/usecases/get-paginated-participants-for-an-organization_test.js
  api/tests/integration/infrastructure/repositories/organization-participant-repository_test.js
  api/tests/integration/infrastructure/utils/filter-utils_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/get-paginated-participants-for-an-organization_test.js
  orga/app/components/organization-participant/list.hbs
  orga/app/components/organization-participant/list.js
  orga/app/controllers/authenticated/organization-participants/list.js
  orga/app/routes/authenticated/organization-participants/list.js
  orga/app/templates/authenticated/organization-participants/list.hbs
  orga/tests/integration/components/organization-participants/list_test.js
  orga/tests/unit/controllers/authenticated/organization-participants/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4717 [BUGFIX] Rediriger l'utilisateur a la page de login quand le service de partenaire n'est pas reconnu.
  mon-pix/app/routes/authentication/login-oidc.js
  mon-pix/tests/unit/routes/authentication/login-oidc_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4715 [FEATURE] Ajouter une tooltip sur la date de la dernière participation de l’onglet Étudiants (PIX-5174).
  orga/app/components/student/sup/list.hbs
  orga/tests/integration/components/students/sup/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4709 [TECH] Appeler l'endpoint userinfo lorsqu'une information est manquante dans le token du partenaire (PIX-5393).
  api/lib/config.js
  api/lib/domain/services/authentication/cnav-oidc-authentication-service.js
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/lib/domain/services/authentication/pole-emploi-oidc-authentication-service.js
  api/lib/domain/usecases/authentication/authenticate-cnav-user.js
  api/lib/domain/usecases/authentication/authenticate-pole-emploi-user.js
  api/lib/domain/usecases/create-user-from-external-identity-provider.js
  api/sample.env
  api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-cnav-user_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-pole-emploi-user_test.js
  api/tests/unit/domain/usecases/create-user-from-external-identity-provider_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces
