Repository 1024pix/pix, pull requests merged in 2022-09, with the labels that each got.

#4838 [TECH] Utiliser le service oidc providers pour afficher les méthodes de connexion OIDC (PIX-5537)
  mon-pix/app/components/authentication/oidc-reconciliation.hbs
  mon-pix/app/components/authentication/oidc-reconciliation.js
  mon-pix/app/controllers/authenticated/user-account/connection-methods.js
  mon-pix/app/services/oidc-identity-providers.js
  mon-pix/app/templates/authenticated/user-account/connection-methods.hbs
  mon-pix/mirage/factories/authentication-method.js
  mon-pix/tests/acceptance/user-account/connection-methods_test.js
  mon-pix/tests/integration/components/authentication/oidc-reconciliation_test.js
  mon-pix/tests/unit/components/authentication/login-or-register-oidc_test.js
  mon-pix/tests/unit/components/authentication/oidc-reconciliation_test.js
  mon-pix/tests/unit/controllers/authenticated/user-account/connection-methods_test.js
  mon-pix/tests/unit/services/oidc-identity-providers_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4666 [TECH] Se déconnecter de redis avant d'arrêter le serveur
  api/index.js
  api/lib/infrastructure/plugins/rate-limit.js
  api/lib/infrastructure/temporary-storage/InMemoryTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/temporary-storage/TemporaryStorage.js
  api/lib/infrastructure/utils/redis-monitor.js
  api/lib/infrastructure/utils/redis-rate-limit.js
  api/lib/infrastructure/utils/redis-rate-limiter.js
  api/tests/unit/infrastructure/temporary-storage/TemporaryStorage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4846 [FEATURE] Afficher le SSO d'une organisation sur la page de détail d'une organisation sur Pix Admin(PIX-5571)
  admin/app/adapters/oidc-identity-provider.js
  admin/app/components/organizations/information-section-edition-mode.hbs
  admin/app/components/organizations/information-section-edition-mode.js
  admin/app/components/organizations/information-section-read-mode.hbs
  admin/app/components/organizations/information-section-read-mode.js
  admin/app/components/organizations/information-section.hbs
  admin/app/components/organizations/information-section.js
  admin/app/models/oidc-identity-provider.js
  admin/app/models/organization.js
  admin/app/routes/application.js
  admin/app/services/oidc-identity-providers.js
  admin/mirage/config.js
  admin/tests/integration/components/organizations/information-section-edition-mode_test.js
  admin/tests/integration/components/organizations/information-section-read-mode_test.js
  admin/tests/integration/components/organizations/information-section_test.js
  admin/tests/unit/components/organizations/information-section_test.js
  api/lib/domain/models/OrganizationForAdmin.js
  api/lib/infrastructure/repositories/organization-for-admin-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-for-admin-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
  api/tests/tooling/domain-builder/factory/build-organization-for-admin.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4840 [FEATURE] Améliore l'accessiblité de la tooltip du score Pix sur Pix App (PIX-5428)
  mon-pix/app/components/hexagon-score.hbs
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4817 [TECH] Utiliser la valeur de difficulté de l'acquis donnée par l'API LCMS (PIX-5531)
  api/lib/domain/models/KnowledgeElement.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/TargetedSkill.js
  api/lib/domain/read-models/CertifiedProfile.js
  api/lib/infrastructure/adapters/skill-adapter.js
  api/lib/infrastructure/repositories/certified-profile-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/repositories/target-profile-with-learning-content-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-competence-evaluation_test.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-locale-management.js
  api/tests/acceptance/application/badges/badge-controller_test.js
  api/tests/acceptance/application/campaign-controller_test.js
  api/tests/acceptance/application/campaign-participations/campaign-participations-controller-analyses_test.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/domain/services/algorithm-methods/smart-random_test.js
  api/tests/integration/domain/services/pick-certification-challenge_test.js
  api/tests/integration/domain/services/placement-profile-service_test.js
  api/tests/integration/domain/services/tube-service_test.js
  api/tests/integration/infrastructure/repositories/campaign-analysis-repository_test.js
  api/tests/integration/infrastructure/repositories/certified-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-for-admin-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certified-skill.js
  api/tests/tooling/domain-builder/factory/build-skill-collection.js
  api/tests/tooling/domain-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/build-targeted-skill.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/models/Answer_test.js
  api/tests/unit/domain/models/KnowledgeElement_test.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/models/TargetedSkill_test.js
  api/tests/unit/domain/models/Tube_test.js
  api/tests/unit/domain/read-models/CampaignAnalysis_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/domain/services/learning-content/learning-content-conversion-service_test.js
  api/tests/unit/domain/services/smart-random/skills-filter_test.js
  api/tests/unit/infrastructure/adapters/skill-adapter_test.js
  api/tests/unit/infrastructure/adapters/target-profile-adapter_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certified-profile-serializer_test.js
  api/tests/unit/scripts/compare-pix-with-latest-release_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#4848 [FEATURE] Si l'organisation est rattachée au GAR, pousser l'élève à se connecter via son Mediacentre (PIX-5140)
  api/db/seeds/data/organizations-sco-builder.js
  mon-pix/app/components/comparison-window.hbs
  mon-pix/app/components/pix-modal-deprecated.js
  mon-pix/app/components/routes/campaigns/join-sco-information-modal.hbs
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/tests/acceptance/fill-in-campaign-code_test.js
  mon-pix/tests/unit/components/pix-modal_test.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#4843 [TECH] Améliorer le message d'erreur lorsqu'on tente de créer un RT avec un acquis inconnu du profil cible (PIX-5579)
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/tests/acceptance/application/target-profile-controller_test.js
  api/tests/integration/domain/usecases/create-badge_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#4855 [BUGFIX] Ne pas remonter l'erreur de Pole Emploi au renvoie des informations de l'utilisateur (PIX_5599).
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
Labels: :rocket: Ready to Merge, team-acces

#4844 [FEATURE] Réconcilier un utilisateur externe avec son compte Pix (PIX-5345).
  api/lib/application/authentication/oidc/index.js
  api/lib/application/authentication/oidc/oidc-controller.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/authentication/authenticate-oidc-user.js
  api/lib/domain/usecases/create-oidc-user.js
  api/lib/domain/usecases/find-user-for-oidc-reconciliation.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/reconcile-oidc-user.js
  api/lib/infrastructure/serializers/jsonapi/oidc-serializer.js
  api/tests/acceptance/application/authentication/oidc/check-reconciliation-route-post_test.js
  api/tests/acceptance/application/authentication/oidc/oidc-route-post_test.js
  api/tests/acceptance/application/authentication/oidc/reconcile-route-post_test.js
  api/tests/unit/application/authentication/oidc/oidc-controller_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-oidc-user_test.js
  api/tests/unit/domain/usecases/create-oidc-user_test.js
  api/tests/unit/domain/usecases/find-user-for-oidc-reconciliation_test.js
  api/tests/unit/domain/usecases/reconcile-oidc-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/oidc-serializer_test.js
  mon-pix/app/authenticators/oidc.js
  mon-pix/app/components/authentication/login-or-register-oidc.js
  mon-pix/app/components/authentication/oidc-reconciliation.hbs
  mon-pix/app/components/authentication/oidc-reconciliation.js
  mon-pix/app/components/authentication/terms-of-service-oidc.js
  mon-pix/app/routes/authentication/login-oidc.js
  mon-pix/tests/unit/authenticators/oidc_test.js
  mon-pix/tests/unit/components/authentication/login-or-register-oidc_test.js
  mon-pix/tests/unit/components/authentication/oidc-reconciliation_test.js
  mon-pix/tests/unit/components/authentication/terms-of-service-oidc_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4784 [TECH] Script pour convertir les profil-cibles existants dans le nouveau format. Conversion acquis vers sujets cappés par niveau (PIX-5502)
  api/scripts/prod/convert-target-profiles-into-new-format.js
  api/tests/acceptance/scripts/convert-target-profiles-into-new-format_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#4862 [FEATURE] Ramener les domaines et compétences dans les pages tutos sur Pix App (PIX-5605).
  api/lib/application/frameworks/frameworks-controller.js
  api/lib/application/frameworks/index.js
  api/lib/infrastructure/serializers/jsonapi/framework-areas-serializer.js
  api/tests/acceptance/application/frameworks/frameworks-controller_test.js
  api/tests/unit/application/frameworks/frameworks-controller_test.js
  api/tests/unit/application/frameworks/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/framework-areas-serializer_test.js
  mon-pix/app/adapters/area.js
  mon-pix/app/models/area.js
  mon-pix/app/models/competence.js
  mon-pix/app/routes/authenticated/user-tutorials.js
  mon-pix/app/routes/authenticated/user-tutorials/recommended.js
  mon-pix/app/routes/authenticated/user-tutorials/saved.js
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
  mon-pix/mirage/config.js
  mon-pix/mirage/routes/get-areas.js
  mon-pix/tests/unit/adapters/area_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4860 [FEATURE][ADMIN] Afficher la date de création d'une organisation (PIX-5601)
  admin/app/components/organizations/information-section-read-mode.hbs
  admin/app/models/organization.js
  admin/tests/integration/components/organizations/information-section-read-mode_test.js
  admin/tests/unit/models/organization_test.js
  api/lib/domain/models/OrganizationForAdmin.js
  api/lib/infrastructure/repositories/organization-for-admin-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-for-admin-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4864 [FEATURE] Changer la traduction pour "Afficher une alternative textuelle" (PIX-5596).
  mon-pix/translations/en.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4861 [FEATURE] Ajouter la traduction anglaise pour l'aide sur l'utilisation d'un code parcours (PIX-5581)
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4857 [BUGFIX][ADMIN] Corriger l'affichage de l'identifiant du créateur de l'organisation (PIX-5586)
  admin/app/models/organization.js
  api/db/seeds/data/campaigns-sco-builder.js
  api/db/seeds/data/campaigns-sup-builder.js
  api/db/seeds/data/organizations-pro-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/db/seeds/data/organizations-sup-builder.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4850 [BUGFIX] Mettre à jour les packages font awesome (Pix-5558)
  orga/app/components/banner/information.hbs
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/charts/participants-by-status.hbs
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/header/archived-banner.hbs
  orga/app/components/campaign/settings/target-profile-tooltip.hbs
  orga/app/components/campaign/settings/view.hbs
  orga/app/components/campaign/stage-stars.hbs
  orga/app/components/campaign/update-form.hbs
  orga/app/components/layout/organization-credit-info.hbs
  orga/app/components/modal/dialog.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/manage-authentication-method-modal.hbs
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/members-list-item.hbs
  orga/app/components/tube/list.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/components/ui/last-participation-date-tooltip.hbs
  orga/app/components/ui/search-input.hbs
  orga/config/icons.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/ui/indicator-card-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4871 [BUGFIX] Ajout de scopes manquants pour pole emploi(PIX-5616)
  api/lib/domain/services/authentication/pole-emploi-oidc-authentication-service.js
  api/tests/acceptance/application/authentication/oidc/authentication-url-route-get_test.js
Labels: :rocket: Ready to Merge, team-acces, team-prescription

#4867 [TECH] Supprimer du code qui gère un cas qui n'arrivera jamais.
  api/lib/domain/usecases/authentication/authenticate-oidc-user.js
  api/tests/unit/domain/usecases/authentication/authenticate-oidc-user_test.js
Labels: :rocket: Ready to Merge, team-acces

#4851 [FEATURE] Enregistrer le badge éligible de la certification complémentaire lors du début de parcours (PIX-5577)
  api/db/database-builder/factory/build-complementary-certification-course.js
  api/db/migrations/20220831084146_add-complementary-certification-badges-fk-to-complementary-certification-courses.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/certification/complementary-certification-course-results-builder.js
  api/lib/domain/models/ComplementaryCertificationCourse.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/badge-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-scoring-criteria-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4876 [FEATURE] Implémenter la version définitive de la traduction des compétences Pix en compétences DigComp (PIX-5600)
  api/lib/domain/read-models/EuropeanNumericLevelFactory.js
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/unit/domain/read-models/EuropeanNumericLevelFactory_test.js
  api/tests/unit/domain/services/cpf-certification-xml-export-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4872 [CLEANUP] Met à jour l'action commune d'automerge
  .github/workflows/auto-merge.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app

#4874 [FEATURE] Afficher un message d'erreur plus approprié quand il y a un conflit de compte (PIX-4991).
  api/lib/application/error-manager.js
  api/tests/integration/application/authentication/oidc/index_test.js
  api/tests/unit/application/error-manager_test.js
  mon-pix/app/components/authentication/login-or-register-oidc.js
  mon-pix/tests/unit/components/authentication/login-or-register-oidc_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4877 [TECH] Nettoyage du test de la version d'Hapi
  api/lib/infrastructure/monitoring-tools.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4852 [FEATURE] Suppression de la sous-catégorie C3 de l'ajout de signalement. (PIX-5578).
  admin/app/models/certification-issue-report.js
  admin/tests/unit/models/certification-issue-report_test.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportCategory.js
  api/tests/unit/domain/events/handle-session-finalized_test.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
  api/tests/unit/domain/models/FinalizedSession_test.js
  certif/app/components/issue-report-modal/add-issue-report-modal.hbs
  certif/app/components/issue-report-modal/add-issue-report-modal.js
  certif/app/components/issue-report-modal/late-or-leaving-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/late-or-leaving-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/signature-issue-report-fields.hbs
  certif/app/models/certification-issue-report.js
  certif/tests/integration/components/issue-report-modal/late-or-leaving-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/signature-issue-report-fields_test.js
  certif/tests/integration/components/issue-reports-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4737 [TECH] Retirer le composant ModelsTable de la page sessions/<id>/certifications (PIX-5461)
  admin/app/adapters/session.js
  admin/app/components/certifications/list.hbs
  admin/app/components/certifications/list.js
  admin/app/components/target-profiles/update-target-profile.hbs
  admin/app/controllers/authenticated/sessions/session/certifications.js
  admin/app/routes/authenticated/sessions/session/certifications.js
  admin/app/styles/app.scss
  admin/app/styles/authenticated/sessions/session/certifications.scss
  admin/app/styles/globals/utils.scss
  admin/app/templates/authenticated/sessions/session/certifications.hbs
  admin/mirage/config.js
  admin/mirage/handlers/get-jury-certification-summaries-by-session-id.js
  admin/mirage/serializers/jury-certification-summary.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/authenticated/sessions/session/certifications_test.js
  admin/tests/integration/components/certifications/list_test.js
  api/lib/application/sessions/session-controller.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-certification-summary-serializer.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, cross-team

#4868 [TECH] Ajouter des rôles d'administration aux créateurs des organisations dans les seeds
  api/db/seeds/data/organizations-pro-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/db/seeds/data/organizations-sup-builder.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#4884 [DOC] Mise à jour de la doc
  CONTRIBUTING.md
  README.md
  docs/assets/pix-app-screenshot.png
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, no-review-app

#4878 [FEATURE] Ne pas prendre en compte les certifications pour lesquels le sexe du candidat n'est pas renseigné (PIX-5621)
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4863 [FEATURE] Afficher une sidebar pour filtrer les tutoriels par compétences (PIX-5606).
  mon-pix/app/components/tutorials/header.hbs
  mon-pix/app/components/user-tutorials/filters/item-checkbox.hbs
  mon-pix/app/components/user-tutorials/filters/item-checkbox.js
  mon-pix/app/components/user-tutorials/filters/sidebar.hbs
  mon-pix/app/components/user-tutorials/filters/sidebar.js
  mon-pix/app/controllers/authenticated/user-tutorials/recommended.js
  mon-pix/app/controllers/authenticated/user-tutorials/saved.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/user-tutorials/_sidebar.scss
  mon-pix/app/templates/authenticated/user-tutorials.hbs
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/config/icons.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/fill-in-campaign-code_test.js
  mon-pix/tests/helpers/wait-for.js
  mon-pix/tests/integration/components/user-tutorials/filters/item-checkbox_test.js
  mon-pix/tests/integration/components/user-tutorials/filters/sidebar_test.js
  mon-pix/tests/unit/components/user-tutorials/filters/item-checkbox_test.js
  mon-pix/tests/unit/components/user-tutorials/filters/sidebar_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4781 [TECH] Disposer d'un environnement local sans dépendances logicielles
  .gitignore
  admin/.dockerignore
  api/.dockerignore
  certif/.dockerignore
  docker/.dockerignore
  docker/README.md
  docker/docker-compose-dev.yaml
  docker/docker-compose.yaml
  docker/dockerfiles/Dockerfile.ember
  docker/dockerfiles/Dockerfile.hapi
  docker/dockerfiles/config/ember-nginx.conf
  docker/sample.env
  mon-pix/.dockerignore
  orga/.dockerignore
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains

#4879 [BUGFIX] Remettre les icônes supprimées par erreur (PIX-5623)
  orga/config/icons.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4858 [FEATURE] Modifier une organisation pour la lier à un SSO (PIX-5575)
  admin/app/components/organizations/information-section-edit.hbs
  admin/app/components/organizations/information-section-edit.js
  admin/app/components/organizations/information-section-view.hbs
  admin/app/components/organizations/information-section-view.js
  admin/app/components/organizations/information-section.hbs
  admin/tests/integration/components/organizations/information-section-edit_test.js
  admin/tests/integration/components/organizations/information-section-view_test.js
  admin/tests/integration/components/organizations/information-section_test.js
  admin/tests/unit/components/organizations/information-section-edit_test.js
  admin/tests/unit/components/organizations/information-section-view_test.js
  admin/tests/unit/components/organizations/information-section_test.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/usecases/update-organization-information.js
  api/lib/infrastructure/repositories/organization-for-admin-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-for-admin-serializer.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4883 [FEATURE] Filtrer les tutoriels par compétences dans Pix App (PIX-5607).
  api/lib/application/user-tutorials/user-tutorials-controller.js
  api/lib/domain/usecases/find-paginated-filtered-recommended-tutorials.js
  api/lib/domain/usecases/find-paginated-filtered-saved-tutorials.js
  api/lib/domain/usecases/find-paginated-recommended-tutorials.js
  api/lib/domain/usecases/find-paginated-saved-tutorials.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/learning-content/skill-datasource.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  api/tests/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/unit/application/user-tutorials/user-tutorials-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-recommended-tutorials_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-saved-tutorials_test.js
  api/tests/unit/domain/usecases/find-paginated-recommended-tutorials_test.js
  api/tests/unit/infrastructure/datasources/learning-content/skill-datasource_test.js
  mon-pix/app/components/user-tutorials/filters/sidebar.hbs
  mon-pix/app/controllers/authenticated/user-tutorials/recommended.js
  mon-pix/app/controllers/authenticated/user-tutorials/saved.js
  mon-pix/app/models/competence.js
  mon-pix/app/routes/authenticated/user-tutorials/recommended.js
  mon-pix/app/routes/authenticated/user-tutorials/saved.js
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
  mon-pix/mirage/factories/area.js
  mon-pix/mirage/handlers/find-paginated-and-filtered-recommended-tutorials.js
  mon-pix/mirage/handlers/find-paginated-and-filtered-saved-tutorials.js
  mon-pix/mirage/routes/get-recommended-tutorials.js
  mon-pix/mirage/routes/get-saved-tutorials.js
  mon-pix/mirage/serializers/area.js
  mon-pix/tests/acceptance/user-tutorials/recommended_test.js
  mon-pix/tests/acceptance/user-tutorials/saved_test.js
  mon-pix/tests/integration/components/user-tutorials/filters/sidebar_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4888 [TECH] Refactorer le script permettant de remplir la colonne `skillId` de la table `user-saved-tutorials` (PIX-5642).
  api/scripts/fill-skill-id-in-user-saved-tutorials.js
  api/tests/integration/scripts/fill-skill-id-in-user-saved-tutorials_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4890 [FEATURE] Remonter les compétences Pix+ en plus des compétences Pix. (PIX-5647).
  api/lib/infrastructure/repositories/certified-profile-repository.js
  api/tests/integration/infrastructure/repositories/certified-profile-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4892 [BUGFIX] Réparer la connexion GAR (PIX-5646)
  mon-pix/app/components/authentication/terms-of-service-oidc.hbs
  mon-pix/app/components/authentication/terms-of-service-oidc.js
  mon-pix/app/components/password-reset-demand-form.hbs
  mon-pix/app/components/password-reset-demand-form.js
  mon-pix/app/components/reset-password-form.hbs
  mon-pix/app/components/reset-password-form.js
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signin-form.js
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/components/signup-form.js
  mon-pix/app/components/update-expired-password-form.hbs
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/controllers/authentication/login-or-register-oidc.js
  mon-pix/app/controllers/terms-of-service.js
  mon-pix/app/services/url.js
  mon-pix/app/templates/authentication/login-or-register-oidc.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/tests/unit/services/url_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4897 [FEATURE] Ré-ordonner les champs d'édition d'une organisation (PIX-5648)
  admin/app/components/organizations/information-section-edit.hbs
  admin/app/components/organizations/information-section-edit.js
  admin/app/components/organizations/information-section-view.js
  admin/tests/unit/components/organizations/information-section-view_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4899 [BUGFIX] Ne pas afficher la "pop-up connecte toi au GAR" si l'utilisateur est déjà connecté (PIX-5649)
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/routes/logout.js
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code_test.js
  mon-pix/tests/unit/routes/logout_test.js
Labels: :rocket: Ready to Merge, team-acces

#4886 [FEATURE] Ajouter la possibilité de supprimer la méthode d'authentification CNAV (PIX-5633)
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/models/user.js
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/users/authentication-method_test.js
  admin/tests/integration/components/users/user-detail-personal-information/authentication-method_test.js
  api/lib/application/users/index.js
  api/lib/domain/usecases/remove-authentication-method.js
  api/tests/integration/application/users/index_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/domain/usecases/remove-authentication-method_test.js
Labels: :rocket: Ready to Merge, team-acces

#4895 [FEATURE] Améliorer l'accessibilité de l'affichage des tutoriels (PIX-5610).
  mon-pix/app/components/learning-more-panel.hbs
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/components/tutorial-panel.hbs
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/components/tutorials/cards.hbs
  mon-pix/app/components/tutorials/header.hbs
  mon-pix/app/components/user-tutorials/filters/sidebar.hbs
  mon-pix/app/styles/components/_choice-chip.scss
  mon-pix/app/styles/components/_learning-more-tutorial-panel.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/components/_tutorial-card.scss
  mon-pix/app/styles/components/_tutorial-panel.scss
  mon-pix/app/styles/components/user-tutorials/_sidebar.scss
  mon-pix/app/styles/pages/_user-tutorials.scss
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4866 [TECH] Refactorer le scoring des certifications complémentaires Cléa (PIX-5574)
  api/db/database-builder/factory/build-complementary-certification.js
  api/db/migrations/20220830132314_add-column-has-complementary-referential-to-complementary-certifications.js
  api/lib/domain/events/handle-clea-certification-scoring.js
  api/lib/domain/events/handle-complementary-certifications-scoring.js
  api/lib/domain/events/handle-pix-plus-certifications-scoring.js
  api/lib/domain/events/index.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/ComplementaryCertificationScoringCriteria.js
  api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
  api/lib/domain/models/ComplementaryCertificationScoringWithoutComplementaryReferential.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/clea-certification-result-repository.js
  api/lib/infrastructure/repositories/complementary-certification-scoring-criteria-repository.js
  api/tests/integration/infrastructure/repositories/clea-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-scoring-criteria-repository_test.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-scoring-criteria.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-scoring-without-complementary-referential.js
  api/tests/tooling/domain-builder/factory/build-pix-plus-certification-scoring.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/events/event-choreography-score-partner-certification_test.js
  api/tests/unit/domain/events/event-choreography-score-pix-plus-certification_test.js
  api/tests/unit/domain/events/handle-clea-certification-scoring_test.js
  api/tests/unit/domain/events/handle-complementary-certifications-scoring_test.js
  api/tests/unit/domain/events/handle-pix-plus-certifications-scoring_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/ComplementaryCertificationScoringWithComplementaryReferential_test.js
  api/tests/unit/domain/models/ComplementaryCertificationScoringWithoutComplementaryReferential_test.js
  api/tests/unit/domain/models/PixPlusCertificationScoring_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4893 [FEATURE] Retourner les souscriptions aux certifications complémentaires si le centre de certification est habilité (PIX-5602)
  api/lib/domain/usecases/get-certification-candidate-subscription.js
  api/tests/acceptance/application/certification-candidates/certification-candidates-controller_test.js
  api/tests/unit/domain/usecases/get-certification-candidate-subscription_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4891 [FEATURE] Enregistrer les certifications qui ont été générées dans un fichier d'export CPF (PIX-5624).
  api/db/database-builder/factory/build-certification-course.js
  api/db/migrations/20220907144932_add-column-exported-in-file-in-table-certification-courses.js
  api/lib/infrastructure/jobs/cpf-export/handlers/create-and-upload.js
  api/lib/infrastructure/jobs/cpf-export/handlers/planner.js
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/create-and-upload_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/planner_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4903 [TECH] Rendre les tests de sélection des épreuves de certification complémentaire plus robustes (PIX-5652).
  api/lib/domain/models/CertifiableProfileForLearningContent.js
  api/lib/domain/services/certification-challenges-service.js
  api/tests/unit/domain/models/CertifiableProfileForLearningContent_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4875 [FEATURE] Ajouter le nombre de participants/étudiants/élèves dans le titre de la page (PIX-5568).
  api/lib/application/organizations/organization-controller.js
  api/lib/infrastructure/repositories/sco-organization-participant-repository.js
  api/lib/infrastructure/repositories/sup-organization-participant-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/sco-organization-participants-serializer.js
  api/lib/infrastructure/serializers/jsonapi/organization/sup-organization-participants-serializer.js
  api/tests/integration/infrastructure/repositories/sco-organization-participant-repository_test.js
  api/tests/integration/infrastructure/repositories/sup-organization-participant-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/sco-organization-participants-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/sup-organization-participants-serializer_test.js
  orga/app/components/organization-participant/header.hbs
  orga/app/components/sco-organization-participant/header-actions.hbs
  orga/app/components/sup-organization-participant/header-actions.hbs
  orga/app/templates/authenticated/organization-participants/list.hbs
  orga/app/templates/authenticated/sco-organization-participants/list.hbs
  orga/app/templates/authenticated/sup-organization-participants/list.hbs
  orga/tests/integration/components/organization-participant/header_test.js
  orga/tests/integration/components/sco-organization-participant/header-actions_test.js
  orga/tests/integration/components/sup-organization-participant/header-actions_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4902 [FEATURE] Ajouter un titre invisible pour les domaines dans l'affichage des compétences (PIX-5608).
  mon-pix/app/components/profile-content.hbs
  mon-pix/app/components/profile-scorecards.hbs
  mon-pix/app/components/routes/campaigns/profiles-collection/send-profile.hbs
  mon-pix/app/models/profile.js
  mon-pix/app/models/shared-profile-for-campaign.js
  mon-pix/app/templates/campaigns/profiles-collection/profile-already-shared.hbs
  mon-pix/tests/acceptance/competence-profile_test.js
  mon-pix/tests/acceptance/profile_test.js
  mon-pix/tests/integration/components/profile-content_test.js
  mon-pix/tests/unit/models/profile_test.js
  mon-pix/tests/unit/models/shared-profile-for-campaign_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4915 [CLEANUP] Abaisse le niveau du log lorsque le rate limit est atteint
  api/lib/infrastructure/plugins/rate-limit.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4911 [TECH] Ajouter des cas d'utilisation pour le script d'ajout de skillId aux userSavedTutorials (PIX-5665)
  api/scripts/fill-skill-id-in-user-saved-tutorials.js
  api/tests/integration/scripts/fill-skill-id-in-user-saved-tutorials_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4913 [BUGFIX] Prévenir l'épuisement de mémoire à l'import d'un fichier SIECLE xml mal formé
  api/lib/infrastructure/utils/xml/siecle-file-streamer.js
  api/tests/integration/infrastructure/utils/xml/files/xml/garbage.xml
  api/tests/integration/infrastructure/utils/xml/siecle-file-streamer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-captains

#4921 [TECH] Corriger les tests sur la distance d'édition (Pix 5680)
  api/lib/infrastructure/utils/filter-utils.js
  api/tests/integration/infrastructure/repositories/campaign-participant-activity-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK

#4920 [TECH] Il manque un test pour la méthode update du campaign repository (Pix 5679).
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK

#4922 [TECH] Corriger les tests du organization places lot repository (Pix 5681).
  api/tests/integration/infrastructure/repositories/organizations/organization-places-lot-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK

#4873 [FEATURE] Affichage de la certificabilité dans l'onglet participant de Pix Orga (PIX-5557)
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/campaigns-pro-builder.js
  api/lib/domain/read-models/OrganizationParticipant.js
  api/lib/infrastructure/repositories/organization-participant-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/organization-participants-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-participant-repository_test.js
  api/tests/integration/infrastructure/repositories/sco-organization-participant-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/organization-participants-serializer_test.js
  orga/app/components/organization-participant/list.hbs
  orga/app/models/organization-participant.js
  orga/app/models/sco-organization-participant.js
  orga/app/transforms/nullable-boolean.js
  orga/tests/integration/components/organization-participant/list_test.js
  orga/tests/unit/transforms/nullable-boolean_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4914 [FEATURE] Simplifier l'import de candidats avec un code postal / code Insee commençant par un 0 (PIX-5305)
  api/db/seeds/data/certification/certification-cpf-city-builder.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_extract_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4908 [FEATURE] Proposer les épreuves du référentiel Pix+ en début de test de certification (PIX-5448)
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4910 [BUGFIX] Corrige la redirection lorsqu'une certification a été terminé par le superviseur (PIX-5666)
  mon-pix/app/components/challenge/item.js
  mon-pix/tests/acceptance/certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4869 [TECH] Supprimer bootstrap de admin (PIX-5614 )
  admin/app/components/card.hbs
  admin/app/components/certifications/details-answer.hbs
  admin/app/components/certifications/details-competence.hbs
  admin/app/components/organizations/form.hbs
  admin/app/components/users/user-overview.hbs
  admin/app/styles/app.scss
  admin/app/styles/authenticated/certifications/certification/details.scss
  admin/app/styles/components/card.scss
  admin/app/styles/components/certification-center-form.scss
  admin/app/styles/components/certification-details-answer.scss
  admin/app/styles/components/certification-details-competence.scss
  admin/app/styles/components/certification/candidate-edit-modal.scss
  admin/app/styles/components/organization-form.scss
  admin/app/styles/globals/form.scss
  admin/app/styles/globals/global.scss
  admin/app/styles/globals/power-select.scss
  admin/app/templates/authenticated/certifications/certification/details.hbs
  admin/ember-cli-build.js
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, cross-team

#4898 [TECH] Ajouter de nouvelles pages dans les tests axes automatisés.
  high-level-tests/e2e/cypress/integration/pix-app/a11y.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4904 [FEATURE] Ajouter un champ de recherche par nom ou prénom à la liste des candidats dans l'espace surveillant (PIX-5452)
  certif/app/components/session-supervising/candidate-list.hbs
  certif/app/components/session-supervising/candidate-list.js
  certif/app/styles/components/session-supervising/candidate-list.scss
  certif/tests/integration/components/session-supervising/candidate-list_test.js
  certif/tests/unit/components/session-supervising/candidate-list_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4926 [FEATURE] Ajout du FT pour la récupération des résultats CleA par les CDC habilités (PIX-5373).
  api/lib/config.js
  api/sample.env
  api/tests/acceptance/application/feature-toggle-controller_tests.js
  certif/app/models/feature-toggle.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#4919 [TECH] Renommer UserTutorial en UserSavedTutorial (PIX-5363)
  api/lib/application/user-tutorials/user-tutorials-controller.js
  api/lib/domain/read-models/TutorialForUser.js
  api/lib/domain/usecases/add-tutorial-to-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/lib/infrastructure/repositories/user-saved-tutorial-repository.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-attributes.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-saved-tutorial-attributes.js
  api/lib/infrastructure/serializers/jsonapi/user-saved-tutorial-serializer.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/acceptance/application/scorecard-controller_test.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/integration/infrastructure/repositories/user-saved-tutorial-repository_test.js
  api/tests/integration/infrastructure/repositories/user-tutorial-repository_test.js
  api/tests/tooling/domain-builder/factory/build-tutorial-for-user.js
  api/tests/unit/application/user-tutorials/user-tutorials-controller_test.js
  api/tests/unit/domain/usecases/add-tutorial-evaluation_test.js
  api/tests/unit/domain/usecases/add-tutorial-to-user_test.js
  api/tests/unit/domain/usecases/find-tutorials_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/tutorial-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-saved-tutorial-serializer_test.js
  mon-pix/app/adapters/user-saved-tutorial.js
  mon-pix/app/components/tutorials/card.js
  mon-pix/app/models/tutorial.js
  mon-pix/app/models/user-saved-tutorial.js
  mon-pix/mirage/config.js
  mon-pix/mirage/factories/tutorial.js
  mon-pix/mirage/handlers/find-paginated-and-filtered-saved-tutorials.js
  mon-pix/mirage/routes/delete-user-saved-tutorial.js
  mon-pix/mirage/routes/put-user-saved-tutorial.js
  mon-pix/mirage/serializers/tutorial.js
  mon-pix/tests/acceptance/user-tutorials/recommended_test.js
  mon-pix/tests/acceptance/user-tutorials/saved_test.js
  mon-pix/tests/unit/adapters/user-tutorial_test.js
  mon-pix/tests/unit/components/tutorials/card_test.js
  mon-pix/tests/unit/models/user-tutorial_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4924 [BUGFIX] Afficher la méthode de connexion CNAV dans la modale de suppression sur Pix Admin (PIX-5670).
  admin/app/components/users/user-detail-personal-information.js
  admin/tests/integration/components/users/user-detail-personal-information_test.js
  admin/tests/unit/components/users/user-detail-personal-information_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4927 [FEATURE] Supprimer les filtres sur la pages des tutoriels enregistrés (PIX-5684).
  mon-pix/app/components/tutorials/header.hbs
  mon-pix/app/controllers/authenticated/user-tutorials/saved.js
  mon-pix/app/routes/authenticated/user-tutorials/saved.js
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
  mon-pix/mirage/handlers/find-paginated-and-filtered-saved-tutorials.js
  mon-pix/tests/acceptance/user-tutorials/saved_test.js
  mon-pix/tests/integration/components/tutorials/header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4909 [TECH] Modifier la gestion du code HTTP 401 sur Pix App (PIX-5661)
  api/lib/application/pre-response-utils.js
  api/lib/infrastructure/authentication.js
  mon-pix/app/adapters/application.js
  mon-pix/app/routes/application.js
  mon-pix/tests/acceptance/authentication_test.js
  mon-pix/tests/unit/adapters/application_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4929 [BUGFIX] Supprimer l'appel au helper text-with-multiple-lang dans la page d'affichage des résultats (PIX-5703).
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4937 [TECH] Monté de versions mineurs de PixOrga (PIX-5522)
  orga/app/components/auth/login-form.hbs
  orga/app/components/auth/register-form.hbs
  orga/app/components/campaign/analysis/recommendations.hbs
  orga/app/components/campaign/analysis/tube-recommendation-row.hbs
  orga/app/components/campaign/filter/filters.hbs
  orga/app/components/campaign/stage-stars.hbs
  orga/app/components/layout/sidebar.hbs
  orga/app/components/modal/dialog.hbs
  orga/app/components/sco-organization-participant/manage-authentication-method-modal.hbs
  orga/app/components/table/header-sort.hbs
  orga/app/components/table/header.hbs
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/members-list-item.hbs
  orga/app/components/team/remove-member-modal.hbs
  orga/app/components/tube/list.hbs
  orga/app/components/ui/chevron.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4849 [TECH] Retrait des warnings liés à l'usage déprécié de process.exit() dans les scripts (PIX-5585)
  api/scripts/add-tags-to-organizations.js
  api/scripts/certification/cancel-certifications-and-publish-sessions.js
  api/scripts/certification/generate-certificate-verification-code.js
  api/scripts/certification/generate-certification-results.js
  api/scripts/certification/generate-certification-test-statistics.js
  api/scripts/certification/generate-last-assessments-score.js
  api/scripts/certification/import-certification-cpf-cities.js
  api/scripts/certification/import-certification-cpf-countries.js
  api/scripts/certification/import-certifications-from-csv.js
  api/scripts/certification/launch-auto-jury-for-session.js
  api/scripts/certification/trigger-autojury-on-finalized-sessions.js
  api/scripts/certification/trigger-session-finalized-handler.js
  api/scripts/certification/update-certification-infos.js
  api/scripts/clean-anonymized-users-authentication-methods.js
  api/scripts/create-badge-criteria-for-specified-badge.js
  api/scripts/create-certification-center-memberships-from-organization-admins.js
  api/scripts/create-or-update-sco-agri-organizations.js
  api/scripts/create-or-update-sco-organizations.js
  api/scripts/create-pro-organizations-with-tags.js
  api/scripts/create-sco-certification-centers.js
  api/scripts/create-users-accounts-for-contest.js
  api/scripts/data-generation/add-many-divisions-and-students-to-sco-organization.js
  api/scripts/data-generation/add-many-fake-members-related-to-one-organization.js
  api/scripts/data-generation/add-many-students-to-sco-certification-center.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/data-generation/generate-certifications-for-organization.js
  api/scripts/fill-campaign-participation-id-in-badge-acquisitions.js
  api/scripts/fill-skill-id-in-user-saved-tutorials.js
  api/scripts/mark-users-for-TermsOfService-revalidation.js
  api/scripts/populate-organizations-email.js
  api/scripts/prod/add-target-profile-shares-to-organizations.js
  api/scripts/prod/archive-campaigns.js
  api/scripts/prod/compute-participation-results.js
  api/scripts/prod/compute-pole-emploi-sendings.js
  api/scripts/prod/create-assessment-campaigns-for-sco.js
  api/scripts/prod/create-organization-places-lot.js
  api/scripts/prod/create-profiles-collection-campaigns.js
  api/scripts/prod/generate-knowledge-element-snapshots-for-campaigns.js
  api/scripts/prod/hide-skills-in-csv-export.js
  api/scripts/prod/select-category-for-target-profiles.js
  api/scripts/prod/update-documentation-url.js
  api/scripts/send-invitations-to-sco-organizations.js
  api/scripts/update-sco-organizations-with-is-managing-students-to-true.js
  api/scripts/update-sco-organizations-with-province-code-and-external-id.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4932 [BUGFIX] Des thématiques en dehors du profil-cible sont comprises dans le payload de lecture du profil-cible sur PixAdmin (PIX-5708)
  api/lib/infrastructure/repositories/target-profile-for-admin-repository.js
  api/tests/integration/infrastructure/repositories/target-profile-for-admin-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#4936 [BUGFIX] Correction d'un bug d'affichage de PixMultiSelect
  admin/app/styles/globals/form.scss
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, team-contenu

#4934 [TECH] Nettoyer les données d'une précédente session (PIX-5658)
  mon-pix/app/routes/authentication/login-oidc.js
  mon-pix/tests/unit/routes/authentication/login-oidc_test.js
Labels: :rocket: Ready to Merge, team-acces

#4928 [TECH] Alimenter la colonne "isReferer" dans certification-center-memberships (PIX-5374)
  api/db/database-builder/factory/build-certification-center-membership.js
  api/db/migrations/20220915083737_add-new-column-referer-to-certification-centers-memberships.js
  api/lib/domain/models/CertificationCenterMembership.js
  api/tests/tooling/domain-builder/factory/build-certification-center-membership.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#4944 [BUGFIX] Instancier Badge au lieu de Stage dans TargetProfileAdapter
  api/lib/infrastructure/adapters/target-profile-adapter.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#4917 [BUGFIX] Correction du téléchargement du contenu d'un profil cible
  api/lib/application/target-profiles/target-profile-controller.js
  api/tests/acceptance/application/target-profile-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4905 [TECH] db(api): Make databaseBuilder.factory.buildUser create email without spaces
  api/db/database-builder/factory/build-user.js
Labels: :rocket: Ready to Merge, team-acces, cross-team

#4943 [BUGFIX] Charger toutes les données quand on accède à la page de détail d'un utilisateur depuis la liste des membres d'une organisation (PIX-5726)
  admin/app/components/organizations/member-item.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4900 [FEATURE] Cacher l'URL des campagnes pour les orgas qui sont rattachés au SSO GAR(PIX-5235)
  api/db/seeds/data/organizations-pro-builder.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/domain/constants.js
  api/lib/domain/constants/saml-identity-providers.js
  api/lib/domain/models/Organization.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-for-admin-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  orga/app/components/campaign/settings/view.hbs
  orga/app/components/campaign/settings/view.js
  orga/app/models/organization.js
  orga/app/models/prescriber.js
  orga/tests/integration/components/campaign/settings/view_test.js
  orga/tests/unit/models/prescriber_test.js
Labels: :rocket: Ready to Merge, team-acces

#4854 [FEATURE] Dans pix-admin ajouter un onglet Orgas dans la fiche des utilisateurs (PIX-3963)
  admin/app/components/users/user-organization-memberships.hbs
  admin/app/components/users/user-organization-memberships.js
  admin/app/models/organization-membership.js
  admin/app/models/user.js
  admin/app/router.js
  admin/app/routes/authenticated/users/get/organizations.js
  admin/app/templates/authenticated/users/get.hbs
  admin/app/templates/authenticated/users/get/organizations.hbs
  admin/mirage/serializers/user.js
  admin/tests/acceptance/authenticated/users/get_test.js
  admin/tests/integration/components/users/user-organization-memberships_test.js
  admin/tests/unit/models/organization-membership_test.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/read-models/UserOrganizationForAdmin.js
  api/lib/domain/usecases/find-user-organizations-for-admin.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-organizations-for-admin-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-organization-for-admin-serializer.js
  api/tests/acceptance/application/users/find-user-organizations-for-admin-route-get_test.js
  api/tests/acceptance/application/users/users-controller-get-user-details-for-admin_test.js
  api/tests/integration/infrastructure/repositories/user-organizations-for-admin-repository_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/find-user-organizations-for-admin_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-organization-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#4925 [TECH] Supprimer le calcul des résultats partagés via l'event dispatcher (PIX5588).
  api/Procfile
  api/lib/application/run-jobs.js
  api/lib/domain/events/compute-campaign-participation-results.js
  api/lib/domain/events/index.js
  api/lib/infrastructure/events/DependenciesBuilder.js
  api/lib/infrastructure/events/EventBusBuilder.js
  api/lib/infrastructure/events/EventHandlerDependenciesBuilder.js
  api/lib/infrastructure/events/subscribers/LogEvent.js
  api/lib/infrastructure/events/subscribers/ScheduleParticipationResultCalculationJob.js
  api/lib/infrastructure/jobs/JobDependenciesBuilder.js
  api/lib/infrastructure/jobs/JobQueue.js
  api/lib/infrastructure/jobs/campaign-result/ParticipationResultCalculationJobHandler.js
  api/scripts/start.sh
  api/tests/unit/domain/events/compute-campaign-participation-results_test.js
  api/tests/unit/infrastructure/events/handlers/LogEvent_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4951 GitHub Workflows security hardening
  .github/workflows/auto-merge.yaml
  .github/workflows/on-dev-merge.yaml
Labels: :eyes: Tech Review Needed

#4918 [FEATURE] Filtrer les badges perdus sur la page de détails de fin de parcours (PIX-5422)
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/usecases/get-user-campaign-assessment-result.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/usecases/get-user-campaign-assessment-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif, team-prescription

#4956 [BUGFIX] Le endpoint /admin/organizations/1/target-profile-summaries renvoie des doublons (PIX-5734)
  api/lib/infrastructure/repositories/target-profile-summary-for-admin-repository.js
  api/tests/integration/infrastructure/repositories/target-profile-summary-for-admin-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, team-contenu

#4953 [FEATURE] Ajout légende onglet Profil dans Pix Admin(PIX-5657).
  admin/app/styles/app.scss
  admin/app/styles/components/profile.scss
  admin/app/templates/authenticated/certifications/certification/profile.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4930 [TECH] Nettoyages liés à la brique générique SSO OIDC (PIX-5706)
  admin/app/styles/globals/button.scss
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/routes/terms-of-service-pole-emploi.js
  mon-pix/app/styles/globals/_colors.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/tests/acceptance/user-account/connection-methods_test.js
  mon-pix/tests/unit/routes/authentication/login-or-register-oidc_test.js
Labels: :rocket: Ready to Merge, team-acces

#4912 [TECH] Refacto des repositories de récupération de données pour les certificats et attestations (PIX-5515).
  api/db/database-builder/factory/build-complementary-certification-badge.js
  api/db/database-builder/factory/build-complementary-certification.js
  api/db/migrations/20220913073642_add-has-external-jury-column-to-complementary-certifications-table.js
  api/db/migrations/20220914125923_replace-clea-image-url.js
  api/db/migrations/20220920091611_add-message-columns-to-complementary-certification-badges.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/lib/domain/models/CleaCertificationResult.js
  api/lib/domain/models/CleaCertificationScoring.js
  api/lib/domain/models/PrivateCertificate.js
  api/lib/domain/models/ShareableCertificate.js
  api/lib/domain/read-models/CertifiedBadgeImage.js
  api/lib/domain/read-models/CertifiedBadges.js
  api/lib/infrastructure/repositories/certification-attestation-repository.js
  api/lib/infrastructure/repositories/partner-certification-scoring-repository.js
  api/lib/infrastructure/repositories/private-certificate-repository.js
  api/lib/infrastructure/repositories/shareable-certificate-repository.js
  api/lib/infrastructure/serializers/jsonapi/private-certificate-serializer.js
  api/lib/infrastructure/serializers/jsonapi/shareable-certificate-serializer.js
  api/tests/acceptance/application/certifications/certification-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-attestation-repository_test.js
  api/tests/integration/infrastructure/repositories/partner-certification-scoring-repository_test.js
  api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
  api/tests/integration/infrastructure/repositories/shareable-certificate-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certified-badge-image.js
  api/tests/tooling/domain-builder/factory/build-clea-certification-result.js
  api/tests/tooling/domain-builder/factory/build-clea-certification-scoring.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-badge.js
  api/tests/tooling/domain-builder/factory/build-private-certificate.js
  api/tests/tooling/domain-builder/factory/build-shareable-certificate.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/domain/models/CleaCertificationResult_test.js
  api/tests/unit/domain/models/CleaCertificationScoring_test.js
  api/tests/unit/domain/models/PrivateCertificate_test.js
  api/tests/unit/domain/read-models/CertifiedBadgeImage_test.js
  api/tests/unit/domain/read-models/CertifiedBadges_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/private-certificate-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/shareable-certificate-serializer_test.js
  mon-pix/app/components/user-certifications-detail-result.hbs
  mon-pix/app/models/certification.js
  mon-pix/tests/integration/components/user-certifications-detail-result_test.js
  mon-pix/tests/unit/controllers/authenticated/user-certifications/get_test.js
  mon-pix/tests/unit/controllers/shared-certification_test.js
  mon-pix/tests/unit/models/certification_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4946 [TECH] Prévenir les process.exit() dans l'API
  api/db/migrations/20220712082535_insert-complementary-certification-badges.js
  api/lib/infrastructure/temporary-storage/InMemoryTemporaryStorage.js
  api/scripts/.eslintrc.yaml
  api/scripts/certification/update-certification-infos.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/database/create-database.js
  api/scripts/database/drop-database.js
  api/scripts/database/empty-database.js
  api/scripts/database/pg-boss-migration.js
  api/scripts/database/restore-dump/download-backup.js
  api/scripts/fill-skill-id-in-user-saved-tutorials.js
  api/scripts/populate-organizations-email.js
  api/tests/integration/scripts/prod/archive-campaigns_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#4958 [TECH] Attendre patiemment la cloture des clients redis
  api/index.js
  api/lib/infrastructure/caches/DistributedCache.js
  api/lib/infrastructure/caches/LayeredCache.js
  api/lib/infrastructure/caches/RedisCache.js
  api/lib/infrastructure/caches/learning-content-cache.js
  api/lib/infrastructure/temporary-storage/RedisTemporaryStorage.js
  api/lib/infrastructure/utils/RedisClient.js
  api/lib/infrastructure/utils/redis-monitor.js
  api/scripts/_template.js
  api/scripts/compare-pix-with-latest-release.js
  api/scripts/data-generation/generate-certif-cli.js
  api/scripts/prod/compute-badge-acquisitions.js
  api/scripts/prod/convert-target-profiles-into-new-format.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, team-captains, cross-team

#4940 [BUGFIX] Ne pas poser deux fois les mêmes challenges en certif si un badge est acquis plusieurs fois (PIx-5720)
  api/lib/infrastructure/repositories/certifiable-badge-acquisition-repository.js
  api/tests/integration/infrastructure/repositories/certifiable-badge-acquisition-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4945 [FEATURE] Ajouter la colonne Certificabilité dans l'onglet Étudiants (Pix-5562)
  api/db/seeds/data/campaigns-sup-builder.js
  api/db/seeds/data/organizations-sup-builder.js
  api/lib/domain/read-models/SupOrganizationParticipant.js
  api/lib/infrastructure/repositories/sup-organization-participant-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/sup-organization-participants-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/sup-organization-participant-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/sup-organization-participants-serializer_test.js
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/models/sup-organization-participant.js
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4950 [FEATURE] Afficher les compétences non Pix en premier dans le profil certifié (PIX 5655)
  admin/app/components/certifications/certified-profile.js
  admin/app/models/certified-competence.js
  admin/tests/integration/components/certifications/certified-profile_test.js
  api/lib/domain/read-models/CertifiedProfile.js
  api/lib/infrastructure/repositories/certified-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/certified-profile-serializer.js
  api/tests/integration/infrastructure/repositories/certified-profile-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certified-competence.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certified-profile-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4780 [TECH] Mises à jour mineures des packages sur certif (PIX-5523).
  certif/.eslintrc.js
  certif/.stylelintrc.json
  certif/app/components/user-logged-menu.hbs
  certif/app/styles/components/add-issue-report-modal.scss
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/components/certification-candidate-details-modal.scss
  certif/app/styles/components/ember-cli-notifications-ie-fallback.scss
  certif/app/styles/components/finalize.scss
  certif/app/styles/components/issue-report-modal.scss
  certif/app/styles/components/login-session-supervisor-form.scss
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/app/styles/components/pagination-control.scss
  certif/app/styles/components/user-logged-menu.scss
  certif/app/styles/globals/forms.scss
  certif/app/styles/globals/panels.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/styles/pages/authenticated/sessions/list-items.scss
  certif/app/styles/pages/login-session-supervisor.scss
  certif/app/styles/pages/login.scss
  certif/app/styles/pages/session-supervising-error.scss
  certif/app/templates/authenticated.hbs
  certif/app/templates/authenticated/sessions/list.hbs
  certif/package-lock.json
  certif/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, cross-team

#4959 [FEATURE] Afficher un bouton pour télécharger les resultats clea dans pix-certif (PIX-5376)
  api/db/database-builder/factory/build-complementary-certification.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/get-session.js
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/get-session_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  certif/app/components/issue-report-modal/add-issue-report-modal.js
  certif/app/components/issue-report-modal/fraud-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.js
  certif/app/components/session-clea-results-download.hbs
  certif/app/controllers/authenticated.js
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/models/certification-issue-report.js
  certif/app/models/feature-toggle.js
  certif/app/models/session.js
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details.hbs
  certif/tests/acceptance/session-details_test.js
  certif/tests/integration/components/issue-report-modal/add-issue-report-modal_test.js
  certif/tests/unit/models/session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4965 [FEATURE] Modifier les messages des badges certifiables (PIX-5769)
  api/db/migrations/20220922141959_modify-messages-in-complementary-certification-badges.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4964 [FEATURE] Modifier le wording du téléchargement de resultats CléA sur pix-certif (PIX-5768)
  api/db/database-builder/factory/build-complementary-certification.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  certif/app/components/session-clea-results-download.hbs
  certif/tests/acceptance/session-details_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4955 [FEATURE] Ajout d'un tooltip sur l'en-tête de la colonne certificabilité dans le tableau sur la page des participants (PIX-5560)
  orga/app/components/organization-participant/list.hbs
  orga/app/styles/pages/authenticated/organization-participants.scss
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4935 [FEATURE] Ne pas afficher la modale GAR si l'utilisateur est déjà connecté à Pix App (PIX-5563)
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4931 [FEATURE] Avoir un menu mobile accessible sur Pix App(PIX-5682).
  mon-pix/app/components/navbar-burger-menu.hbs
  mon-pix/app/components/navbar-header.hbs
  mon-pix/app/components/navbar-mobile-header.hbs
  mon-pix/app/components/navbar-mobile-header.js
  mon-pix/app/controllers/application.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_navbar-burger-menu.scss
  mon-pix/app/styles/components/_navbar-header.scss
  mon-pix/app/styles/components/_navbar-mobile-header.scss
  mon-pix/app/templates/application.hbs
  mon-pix/app/templates/authenticated/certifications/join.hbs
  mon-pix/app/templates/authenticated/certifications/start-loading.hbs
  mon-pix/app/templates/authenticated/certifications/start.hbs
  mon-pix/app/templates/authenticated/competences/details.hbs
  mon-pix/app/templates/authenticated/competences/results.hbs
  mon-pix/app/templates/authenticated/profile.hbs
  mon-pix/app/templates/authenticated/sitemap.hbs
  mon-pix/app/templates/authenticated/user-account.hbs
  mon-pix/app/templates/authenticated/user-certifications.hbs
  mon-pix/app/templates/authenticated/user-dashboard.hbs
  mon-pix/app/templates/authenticated/user-tests.hbs
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
  mon-pix/app/templates/error.hbs
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/app/templates/fill-in-certificate-verification-code.hbs
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/navbar-burger-menu_test.js
  mon-pix/tests/integration/components/navbar-mobile-header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#4948 [FEATURE] Remplacer les modales dépréciées dans Pix-App (PIX-5711).
  mon-pix/app/components/routes/campaigns/join-sco-information-modal.hbs
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/pages/_join-restricted-campaign.scss
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/competences-details_test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-evaluation, Design Review OK

#4962 [BUGFIX] Orga: permettre l'inscription d'une adresse e-mail en majuscules (PIX-5733)
  api/lib/application/organization-invitations/organization-invitation-controller.js
  api/tests/acceptance/application/organization-invitation-controller_test.js
  api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/unit/application/organization-invitations/organization-invitation-controller_test.js
  orga/app/components/auth/register-form.js
  orga/tests/integration/components/auth/register-form_test.js
Labels: :rocket: Ready to Merge, team-acces

#4901 [TECH] Inclure le rattachement des profils cibles dans le script OGA (PIX-4993).
  api/lib/domain/usecases/create-pro-organizations-with-tags-and-target-profiles.js
  api/lib/domain/usecases/index.js
  api/lib/domain/validators/organization-with-tags-and-target-profiles-script.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/repositories/target-profile-share-repository.js
  api/scripts/create-pro-organizations-with-tags-and-target-profiles.js
  api/scripts/helpers/csvHelpers.js
  api/tests/integration/domain/usecases/create-pro-organizations-with-tags-and-target-profiles_test.js
  api/tests/integration/infrastructure/repositories/target-profile-share-repository_test.js
  api/tests/unit/domain/usecases/create-pro-organizations-with-tags-and-target-profiles_test.js
  api/tests/unit/scripts/create-pro-organizations-with-tags_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/helpers/files/organizations-pro-with-tags-and-target-profiles-test.csv
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4954 [TECH] Rendre dynamique l'affichage des méthodes de connexions de type OIDC (PIX-5662)
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/components/users/user-detail-personal-information/authentication-method.js
  admin/app/components/users/user-detail-personal-information/reassign-oidc-authentication-method-modal.hbs
  admin/app/controllers/authenticated/users/get/information.js
  admin/app/models/user.js
  admin/app/styles/components/users/user-detail-personal-information/authentication-method.scss
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/users/authentication-method_test.js
  admin/tests/acceptance/authenticated/users/get_test.js
  admin/tests/integration/components/users/user-detail-personal-information/authentication-method_test.js
  admin/tests/integration/components/users/user-detail-personal-information_test.js
  admin/tests/unit/models/user_test.js
  api/db/database-builder/factory/build-user.js
  api/db/seeds/data/users-builder.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4969 [BUGFIX] Corrige l'affichage du lien "Mes parcours" dans la navbar mobile (PIX-5682)
  mon-pix/app/components/navbar-burger-menu.hbs
Labels: :rocket: Ready to Merge, Func Review OK, team-evaluation

#4968 [BUGFIX] Permettre aux prescrits désactivés de participer à la campagne d'une orga passée en non isManagingStudents(Pix-5772)
  api/db/seeds/data/organizations-sup-builder.js
  api/lib/infrastructure/repositories/campaign-participant-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participant-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4972 [BUGFIX] La page de détails d'un profil cible sur PixAdmin montre un référentiel non trié selon domaine/compétence/thématique/sujet (PIX-5786)
  admin/app/controllers/authenticated/target-profiles/target-profile/details.js
  admin/app/models/new-area.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-for-admin-new-format-serializer.js
  api/tests/integration/application/target-profile/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-for-admin-new-format-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#4887 [TECH] Ne pas charger les acquis en même temps que le profil cible (PIX-5643)
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/models/Progression.js
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/domain/services/badge-criteria-service.js
  api/lib/domain/services/certification-badges-service.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/get-progression.js
  api/lib/domain/usecases/get-user-campaign-assessment-result.js
  api/lib/domain/usecases/handle-badge-acquisition.js
  api/lib/domain/usecases/reset-scorecard.js
  api/lib/infrastructure/adapters/target-profile-adapter.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/learning-content-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/prod/compute-badge-acquisitions.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/domain/usecases/handle-badge-acquisition_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/integration/scripts/prod/compute-badge-acquisitions_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-result.js
  api/tests/tooling/domain-builder/factory/build-progression.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/models/Progression_test.js
  api/tests/unit/domain/services/badge-criteria-service_test.js
  api/tests/unit/domain/services/certification-badges-service-test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  api/tests/unit/domain/usecases/get-progression_test.js
  api/tests/unit/domain/usecases/get-user-campaign-assessment-result_test.js
  api/tests/unit/domain/usecases/handle-badge-acquisition_test.js
  api/tests/unit/domain/usecases/reset-scorecard_test.js
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/tests/algo_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-prescription, team-contenu

#4974 [FEATURE] Créer la table `trainings` (PIX-5763)
  api/db/migrations/20220926084112_create_trainings_table.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4963 [FEATURE] Améliorer la fonction de recherche d'un candidat dans l'espace surveillant (PIX-5728)
  certif/app/components/session-supervising/candidate-list.js
  certif/tests/integration/components/session-supervising/candidate-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4970 [FEATURE] Création de la nouvelle table pour identifier les DPOs (PIX-3501)
  api/db/database-builder/factory/build-data-protection-officer.js
  api/db/database-builder/factory/index.js
  api/db/migrations/20220923141951_create-data-protection-officers-table.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/organizations-pro-builder.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#4975 [FEATURE] Créer la table `target-profile-trainings` (PIX-5773)
  api/db/migrations/20220926091617_create_target_profile_trainings_table.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4916 [TECH] Minimiser la lecture des acquis depuis target-profiles_skills (PIX-5694)
  api/lib/domain/models/ParticipantResultsShared.js
  api/lib/domain/read-models/campaign/TargetProfileForSpecifier.js
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/domain/services/certification-badges-service.js
  api/lib/domain/services/scorecard-service.js
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/get-progression.js
  api/lib/domain/usecases/get-user-campaign-assessment-result.js
  api/lib/domain/usecases/handle-badge-acquisition.js
  api/lib/infrastructure/orm-models/TargetProfile.js
  api/lib/infrastructure/orm-models/TargetProfileSkill.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/repositories/campaign-participant-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/lib/infrastructure/repositories/campaign-report-repository.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/campaign/target-profile-for-specifier-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/lib/infrastructure/repositories/learning-content-repository.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/repositories/participant-results-shared-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/lib/infrastructure/repositories/target-profile-for-admin-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/prod/compute-badge-acquisitions.js
  api/scripts/prod/compute-participation-results.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/infrastructure/repositories/campaign/target-profile-for-specifier-repository_test.js
  api/tests/integration/scripts/prod/compute-badge-acquisitions_test.js
  api/tests/unit/domain/models/ParticipantResultsShared_test.js
  api/tests/unit/domain/read-models/campaign/TargetProfileForSpecifier_test.js
  api/tests/unit/domain/services/certification-badges-service-test.js
  api/tests/unit/domain/services/scorecard-service_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  api/tests/unit/domain/usecases/get-progression_test.js
  api/tests/unit/domain/usecases/get-user-campaign-assessment-result_test.js
  api/tests/unit/domain/usecases/handle-badge-acquisition_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign/target-profile-for-specifier-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team, team-contenu

#4984 [BUGFIX] Corriger la migration ajoutant la colonne stickerUrl dans la table complementary-certification-badges (PIX-5793)
  api/db/migrations/20220927073844_add-column-sticker-url-to-table-complementary-certification-badges.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4966 [BUGFIX] Corriger le total du nb de participant dans l'onglet Participants(PIX-5723)
  api/lib/infrastructure/repositories/organization-participant-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/organization-participants-serializer.js
  api/tests/integration/infrastructure/repositories/organization-participant-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/organization-participants-serializer_test.js
  orga/app/templates/authenticated/organization-participants/list.hbs
  orga/tests/integration/components/organization-participant/header_test.js
  orga/tests/integration/components/sco-organization-participant/header-actions_test.js
  orga/tests/integration/components/sup-organization-participant/header-actions_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4952 [FEATURE] Mettre à jour la librairie Pix-UI de 17.0.0 à 19.0.0 (Pix-5556)
  orga/app/components/campaign/activity/delete-participation-modal.hbs
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/modal/body.hbs
  orga/app/components/modal/dialog.hbs
  orga/app/components/modal/dialog.js
  orga/app/components/modal/footer.hbs
  orga/app/components/sco-organization-participant/manage-authentication-method-modal.hbs
  orga/app/components/sup-organization-participant/edit-student-number-modal.hbs
  orga/app/components/table/header-filter-input.hbs
  orga/app/components/table/header-filter-multi-select.hbs
  orga/app/components/table/header-filter-multi-select.js
  orga/app/components/table/header-filter-select.hbs
  orga/app/components/table/header-filter-select.js
  orga/app/components/team/remove-member-modal.hbs
  orga/app/components/ui/divisions-filter.hbs
  orga/app/components/ui/groups-filter.hbs
  orga/app/components/ui/multi-select-filter.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/edit-student-number-modal.scss
  orga/app/styles/components/team/remove-member-modal.scss
  orga/app/templates/authenticated/sco-organization-participants/list.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/acceptance/remove-membership_test.js
  orga/tests/acceptance/sco-organization-participant-list_test.js
  orga/tests/acceptance/sup-organization-participant-list_test.js
  orga/tests/integration/components/modal/dialog_test.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/integration/components/sup-organization-participant/edit-student-number-modal_test.js
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/tests/integration/components/team/members-list-item_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4976 [FEATURE] Bloquer la finalisation d'une session sans certification (PIX-5727)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/finalize-session.js
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/tests/acceptance/application/session/session-controller-put-finalization_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/finalize-session_test.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/tests/acceptance/session-finalization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4942 [FEATURE] Gérer l'acquisition de paliers de type niveau (PIX-5689)
  api/db/database-builder/factory/build-stage.js
  api/db/migrations/20220906131043_add-level-column-to-stages-table.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/models/Stage.js
  api/lib/domain/models/TargetProfile.js
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/domain/read-models/campaign/CampaignStages.js
  api/lib/domain/services/campaign-csv-export-service.js
  api/lib/domain/usecases/find-target-profile-stages.js
  api/lib/domain/usecases/get-campaign-participations-counts-by-stage.js
  api/lib/domain/usecases/get-campaign.js
  api/lib/domain/usecases/get-user-campaign-assessment-result.js
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/infrastructure/adapters/target-profile-adapter.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/repositories/stage-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/integration/infrastructure/repositories/stage-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-stages.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/models/TargetProfile_test.js
  api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
  api/tests/unit/domain/read-models/campaign/CampaignStages_test.js
  api/tests/unit/domain/usecases/get-campaign_test.js
  api/tests/unit/domain/usecases/get-user-campaign-assessment-result_test.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
  api/tests/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#4978 [CLEANUP] Supprime la configuration des CSP
  admin/config/environment.js
  certif/config/environment.js
  mon-pix/config/environment.js
  orga/config/environment.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4986 [FEATURE] Changer la taille de police de la date et l'heure du détail d'une session (PIX-5789)
  certif/app/styles/pages/authenticated/sessions/details.scss
  certif/app/templates/authenticated/sessions/details.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4987 [FEATURE] Alignement du bouton de création de session dans certif (PIX-5737).
  certif/app/styles/pages/authenticated/sessions/list-items.scss
  certif/app/templates/authenticated/sessions/list.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#4983 [FEATURE] Script de création de formations (PIX-5774).
  api/scripts/create-trainings.js
  api/scripts/helpers/csvHelpers.js
  api/tests/integration/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/create-trainings_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/helpers/files/withValidHeaderFilePath.csv
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#4977 [CLEANUP] Suppression de ember-cli-google-fonts de orga
  orga/config/environment.js
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#4967 [FEATURE] Ajout d'une phrase de déconnexion écran FDT pour les certif à distance (PIX-5656)
  mon-pix/app/components/certifications/certification-ender.hbs
  mon-pix/app/styles/components/certifications/certification-ender.scss
  mon-pix/tests/integration/components/certifications/certification-ender_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4989 [FEATURE] Afficher la date de certificabilité dans la liste des élèves (PIX-5476)
  api/lib/domain/read-models/OrganizationParticipant.js
  api/lib/infrastructure/repositories/organization-participant-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization/organization-participants-serializer.js
  api/tests/integration/infrastructure/repositories/organization-participant-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization/organization-participants-serializer_test.js
  orga/app/components/organization-participant/list.hbs
  orga/app/models/organization-participant.js
  orga/tests/integration/components/organization-participant/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4980 [FEATURE] Rendre générique le script de création en masse des orgas (PIX-5705).
  api/lib/domain/usecases/create-organizations-with-tags-and-target-profiles.js
  api/lib/domain/validators/organization-with-tags-and-target-profiles-script.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/scripts/create-organizations-with-tags-and-target-profiles.js
  api/scripts/helpers/csvHelpers.js
  api/tests/integration/domain/usecases/create-organizations-with-tags-and-target-profiles_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/domain/usecases/create-organizations-with-tags-and-target-profiles_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/helpers/files/organizations-pro-with-tags-and-target-profiles-test.csv
  api/tests/unit/scripts/helpers/files/organizations-with-tags-and-target-profiles-test.csv
Labels: :rocket: Ready to Merge, team-acces

#4996 [FEATURE] Optimiser les requête de récupération des certifications et améliorer le debugging (PIX-5804)
  api/lib/infrastructure/jobs/cpf-export/handlers/create-and-upload.js
  api/lib/infrastructure/jobs/cpf-export/handlers/planner.js
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/create-and-upload_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/planner_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4981 [FEATURE] Ajouter une tooltip pour expliquer la certificabilité dans l'onglet Étudiants(Pix-5564)
  orga/app/components/organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/components/ui/certificability-tooltip.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/ui/certificability-tooltip.scss
  orga/app/styles/components/ui/index.scss
  orga/app/styles/pages/authenticated/organization-participants.scss
  orga/app/styles/pages/authenticated/sco-organization-participants/list.scss
  orga/app/styles/pages/authenticated/sup-organization-participants/list.scss
  orga/tests/integration/components/organization-participant/list_test.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/tests/integration/components/ui/certificability-tooltip_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4985 [FEATURE] Admin: Afficher les informations du DPO d'une organisation (PIX-4785)
  admin/app/components/organizations/information-section-view.hbs
  admin/app/models/organization.js
  admin/tests/integration/components/organizations/information-section-view_test.js
  admin/tests/unit/models/organization_test.js
  api/db/database-builder/factory/build-data-protection-officer.js
  api/lib/domain/models/DataProtectionOfficer.js
  api/lib/domain/models/OrganizationForAdmin.js
  api/lib/infrastructure/repositories/organization-for-admin-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-for-admin-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
  api/tests/tooling/domain-builder/factory/build-data-protection-officer.js
  api/tests/tooling/domain-builder/factory/build-organization-for-admin.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#4994 [FEATURE] Créer la notion d'invitation à Pix Certif (PIX-5004)
  api/db/database-builder/factory/build-certification-center-invitation.js
  api/db/database-builder/factory/index.js
  api/db/migrations/20220927130058_create-certification-center-invitations-table.js
  api/db/seeds/data/certification/certification-center-invitations-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, no-review-app

#4979 [FEATURE] Ajout d'un filtre par nom et prénom dans l'onglet élèves (PIX-5566)
  api/lib/application/organizations/index.js
  api/lib/infrastructure/repositories/sco-organization-participant-repository.js
  api/tests/integration/infrastructure/repositories/sco-organization-participant-repository_test.js
  api/tests/unit/domain/usecases/find-paginated-filtered-sco-participants_test.js
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/controllers/authenticated/sco-organization-participants/list.js
  orga/app/routes/authenticated/sco-organization-participants/list.js
  orga/app/templates/authenticated/sco-organization-participants/list.hbs
  orga/tests/acceptance/sco-organization-participant-list_test.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/unit/controllers/authenticated/sco-organization-participants/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#4999 [BUGFIX] Valider le userId lors de la récupération des méthodes d'authentification
  api/lib/application/users/index.js
  api/tests/unit/application/users/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, team-captains

#4988 [FEATURE] Retirer le 'mailto' sur l'adresse e-mail du dpo sur les pages 'épreuves' dans les signalements (PIX-5792)
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#4993 [FEATURE] Changement du wording de la bannière de session non finalisée (PIX-5797).
  certif/app/components/session-finalization/uncompleted-reports-information-step.hbs
  certif/app/styles/components/session-finalization/reports-information-step.scss
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/integration/components/session-finalization/uncompleted-reports-information-step_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#4995 [TECH] Script de génération de résultats d'une session en CSV (PIX-5807).
  api/scripts/certification/generate-certification-csv-results-by-session-ids.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5002 [BUG] Corrige le filtre de certificabilité sur la page élèves (PIX-5817)
  api/lib/application/organizations/index.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5005 [BUGFIX] Admin: Ne pas afficher NULL lorsque les champs du DPO ne sont fournis (PIX-5814)
  admin/app/models/organization.js
  admin/tests/integration/components/organizations/information-section-view_test.js
Labels: :rocket: Ready to Merge, team-acces

#5000 [FEATURE] Ajouter le DPO au script de création des organisations en masse (PIX-5264).
  api/lib/domain/usecases/create-organizations-with-tags-and-target-profiles.js
  api/lib/domain/validators/organization-with-tags-and-target-profiles-script.js
  api/lib/infrastructure/repositories/data-protection-officer-repository.js
  api/scripts/create-organizations-with-tags-and-target-profiles.js
  api/scripts/helpers/csvHelpers.js
  api/tests/integration/domain/usecases/create-organizations-with-tags-and-target-profiles_test.js
  api/tests/integration/infrastructure/repositories/data-protection-officer-repository_test.js
  api/tests/unit/domain/usecases/create-organizations-with-tags-and-target-profiles_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/helpers/files/organizations-with-tags-and-target-profiles-test.csv
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#5003 [FEATURE] Admin: Ajouter la possibilité de modifier les informations du DPO d'une organisation (PIX-4469)
  admin/app/components/organizations/information-section-edit.hbs
  admin/app/components/organizations/information-section-edit.js
  admin/tests/acceptance/authenticated/organizations/information-management_test.js
  admin/tests/integration/components/organizations/information-section-edit_test.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-organization-information.js
  api/lib/infrastructure/repositories/data-protection-officer-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-for-admin-serializer.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/data-protection-officer-repository_test.js
  api/tests/unit/domain/usecases/update-organization-information_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#5008 [FEATURE] Rendre les profils cibles facultatif dans le script OGA (PIX-5821).
  api/lib/domain/validators/organization-with-tags-and-target-profiles-script.js
  api/tests/integration/domain/usecases/create-organizations-with-tags-and-target-profiles_test.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#5011 [FEATURE] Rendre certains champs facultatifs dans le script OGA (PIX-5825).
  api/lib/domain/validators/organization-with-tags-and-target-profiles-script.js
  api/tests/integration/domain/usecases/create-organizations-with-tags-and-target-profiles_test.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#5009 [BUGFIX] Utiliser le nombre de participants remonté par la pagination des participants (PIX-5650)
  orga/app/templates/authenticated/organization-participants/list.hbs
  orga/mirage/handlers/find-filtered-paginated-organization-participants.js
  orga/tests/acceptance/organization-participant-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription
