Repository 1024pix/pix, pull requests merged in 2023-07, with the labels that each got.

#6482 [FEATURE] ajout d'une colonne à la liste de campagnes pour afficher leurs codes (PIX-8477)
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/list.js
  orga/tests/integration/components/campaign/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6512 [TECH] Vérrouiller la version Node de l'API en v16
  api/package-lock.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#6514 [BUG] Retirer la colonne Actions de la liste d'Organisations (PIX-8535)
  admin/app/components/organizations/list-items.hbs
  admin/app/components/organizations/list-items.js
  admin/app/components/target-profiles/organizations.hbs
  admin/app/components/target-profiles/organizations.js
  admin/app/templates/authenticated/organizations/list.hbs
  admin/tests/acceptance/authenticated/organizations/list_test.js
  admin/tests/integration/components/organizations/list-items_test.js
  admin/tests/integration/components/target-profiles/organizations_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6462 [TECH] Nettoyage des erreurs liés à l'ajout d'un candidat à une session de certification (PIX-8445).
  api/lib/application/error-manager.js
  api/lib/domain/constants/certification-candidates-errors.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/correct-candidate-identity-in-certification-course.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  api/tests/unit/domain/usecases/correct-candidate-identity-in-certification-course_test.js
  certif/app/components/enrolled-candidates.js
  certif/app/components/import-candidates.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6511 [BUGFIX] Réparer l'affichage du lien contenu dans le message de blocage de compte sur Pix App, Orga, Certif, Admin (PIX-8501)
  admin/app/styles/login.scss
  certif/app/styles/globals/forms.scss
  mon-pix/app/styles/components/_login-form.scss
  mon-pix/app/styles/pages/_sign-form.scss
  orga/app/styles/components/login-form.scss
Labels: :rocket: Ready to Merge, team-acces

#6497 [TECH] Amélioration et correction des certification complémentaire dans les nouveaux seeds (PIX-8506).
  api/db/database-builder/factory/build-complementary-certification.js
  api/db/seeds/data/common/common-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6515 [TECH] Mise à jour de stylelint-config-standard-scss en v10
  1d/package-lock.json
  1d/package.json
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6530 [TECH] :wrench: Unifier la version d'image postgres utilisée
  docker/docker-compose.yaml
  high-level-tests/e2e/docker-compose.yaml
Labels: :rocket: Ready to Merge, team-captains, no-review-app

#6507 [TECH] Amélioration du code de récupération des éléments de correction d'un QROCm-dep (PIX-8214)
  api/lib/domain/models/ValidatorQROCMDep.js
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/unit/application/answers/answer-controller_test.js
  api/tests/unit/domain/models/ValidatorQROCMDep_test.js
  api/tests/unit/domain/services/solution-service-qrocm-dep_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
  mon-pix/app/components/comparison-window.js
  mon-pix/app/models/correction.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6508 [FEATURE] Afficher la notion de progressivité sur les résultats thématiques certifiants (PIX-8440)
  mon-pix/app/components/badge-card-certifiable.hbs
  mon-pix/app/components/badge-card-certifiable.js
  mon-pix/app/components/badge-card.hbs
  mon-pix/app/components/badge-card.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/styles/components/_badge-card-certifiable.scss
  mon-pix/app/styles/components/_badge-card.scss
  mon-pix/tests/acceptance/skill-review_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6543 [TECH] Spécifie les versions spécifique de ember-source et d'ember-data sur mon-pix qui fonctionnent
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6526 [TECH] A l'initialisation du databaseBuilder, s'assurer que le vidage de la BDD respecte l'ordre de dépendance des tables (PIX-8544)
  api/db/database-builder/database-builder.js
  api/tests/unit/tooling/database-builder/database-builder_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6501 [FEATURE] Suppression de l'onglet Profil pour les certifications V3 (PIX-8494).
  admin/app/models/certification.js
  admin/app/templates/authenticated/certifications/certification.hbs
  admin/tests/acceptance/authenticated/certifications/certification/certification_test.js
  api/lib/domain/models/JuryCertification.js
  api/lib/infrastructure/repositories/jury-certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/jury-certification-serializer.js
  api/tests/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/tooling/domain-builder/factory/build-jury-certification.js
  api/tests/unit/domain/models/JuryCertification_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/jury-certification-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, certif-next-gen

#6504 [FEATURE] Afficher le nombre de questions passées et total dans le compteur (PIX-8512)
  api/db/seeds/data/team-certification/data-builder.js
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/domain/models/FlashAssessmentAlgorithm.js
  api/lib/domain/usecases/get-next-challenge-for-certification.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/sample.env
  api/tests/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
Labels: :rocket: Ready to Merge, team-certif, certif-next-gen

#6502 [FEATURE] Possibilité pour les centres V3 pilotes d'importer en masses des sessions (PIX-8511).
  api/lib/domain/usecases/sessions-mass-import/create-sessions.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-create-sessions_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/create-sessions_test.js
Labels: :rocket: Ready to Merge, team-certif, certif-next-gen

#6552 [TECH] Supprimer la métrique de couverture de code plus disponible
  .gitignore
  INSTALLATION.md
  api/.eslintignore
  api/.ls-lint.yml
  api/nyc.config.js
  api/package-lock.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6520 [BUGFIX] Jeter une erreur si fichier d'import en masse de session vide (PIX-8543)
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6506 [FEATURE] Affiche la remise à zéro des acquis dans le détail du profil cible dans Pix Admin (PIX-8521).
  admin/app/components/target-profiles/target-profile.hbs
  admin/app/components/target-profiles/target-profile.js
  admin/app/models/target-profile.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/management_test.js
Labels: :rocket: Ready to Merge, team-prescription, team-devcomp

#6561 [FEATURE][ORGA] Ajouter la sélection multiple d'élèves (PIX-8468)
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/app/components/sco-organization-participant/table-headers.hbs
  orga/app/components/sco-organization-participant/table-row.hbs
  orga/app/components/sco-organization-participant/table-row.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#6567 [FEATURE] Afficher le nombre d'élèves sélectionnés dans le bandeau en bas de page (PIX-8469)
  orga/app/components/sco-organization-participant/action-bar.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#6425 [FEATURE] Vérifier la conformité des adresses e-mail lors de l'ajout d'un candidat sur Pix Certif (PIX-7888)
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/lib/infrastructure/mail-check.js
  api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_reports_categorization_test.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_extract_recipient_email_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#6553 [BUGFIX] Import en masse impossible avec des certifications complémentaires (PIX-8531)
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6568 [FEATURE] Afficher la modale de confirmation pour la réinitialisation de mots de passe en masse des élèves (PIX-8472)
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/app/components/sco-organization-participant/reset-password-modal.hbs
  orga/app/components/sco-organization-participant/reset-password-modal.js
  orga/app/styles/app.scss
  orga/app/styles/components/sco-organization-participant/reset-password-modal.scss
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#6575 [BUGFIX] Corrige les typos dans la modale de confirmation de suppression de participants (PIX-8617).
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6572 [FEATURE] Création en masse de campagnes depuis un fichier CSV (PIX-8520).
  admin/app/adapters/campaigns-import.js
  admin/app/components/administration/campaigns-import.hbs
  admin/app/components/administration/campaigns-import.js
  admin/app/components/administration/organizations-import.hbs
  admin/app/templates/authenticated/administration.hbs
  admin/mirage/config.js
  admin/tests/integration/components/administration/campaigns-import_test.js
  admin/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6573 [TECH] Permettre de bloquer l'accès sur PixAdmin du versioning des profils cibles via Feature Toggle (PIX-8575).
  admin/app/models/feature-toggle.js
  admin/mirage/factories/feature-toggle.js
  admin/tests/unit/services/feature-toggles_test.js
  api/lib/config.js
  api/lib/infrastructure/validate-environment-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggles/feature-toggle-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6583 [TECH] Harmoniser le nommage des Github actions
  .github/workflows/check-api-config-changed-dev.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6578 [BUMP] Met à jour Pix UI en version 38 dans Pix Admin (PIX-8619).
  admin/app/components/campaigns/update.hbs
  admin/app/components/campaigns/update.js
  admin/app/components/certifications/candidate-edit-modal.hbs
  admin/app/components/sessions/jury-comment.hbs
  admin/app/components/sessions/jury-comment.js
  admin/app/components/stages/update-stage.hbs
  admin/app/components/target-profiles/create-target-profile-form.hbs
  admin/app/components/target-profiles/create-target-profile-form.js
  admin/app/components/target-profiles/stages.hbs
  admin/app/components/target-profiles/update-target-profile.hbs
  admin/app/components/target-profiles/update-target-profile.js
  admin/app/styles/components/certification/candidate-edit-modal.scss
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#6423 [FEATURE] Traduire l'attestation de certification (PIX-6691).
  api/lib/application/certifications/certification-controller.js
  api/lib/application/certifications/index.js
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/constants.js
  api/lib/infrastructure/utils/pdf/AttestationViewModel.js
  api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
  api/lib/infrastructure/utils/pdf/files/EN-attestation-template-with-complementary-certification.pdf
  api/lib/infrastructure/utils/pdf/files/EN-attestation-template-without-complementary-certification.pdf
  api/lib/infrastructure/utils/pdf/files/FR-attestation-template-with-professionalizing-message-and-with-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/FR-attestation-template-with-professionalizing-message-and-without-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/FR-attestation-template-without-professionalizing-message-and-with-complementary-certifications.pdf
  api/lib/infrastructure/utils/pdf/files/FR-attestation-template-without-professionalizing-message-and-without-complementary-certifications.pdf
  api/scripts/certification/generate-certification-attestations-by-session-ids.js
  api/tests/acceptance/application/certifications/index_test.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/utils/pdf/EN-certification-confirmation-pdf_test.pdf
  api/tests/integration/infrastructure/utils/pdf/certification-attestation-pdf_test.js
  api/tests/unit/application/certifications/certification-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/translations/en.json
  api/translations/fr.json
  mon-pix/app/components/user-certifications-detail-header.js
  mon-pix/tests/integration/components/user-certifications-detail-header_test.js
  mon-pix/tests/unit/components/certification/user-certifications-detail-header_test.js
  orga/app/controllers/authenticated/certifications.js
  orga/tests/unit/controllers/authenticated/certifications_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6574 [FEATURE] Réinitialiser les mots de passe des élèves sélectionnés après confirmation (PIX-8473)
  api/lib/application/error-manager.js
  api/lib/application/sco-organization-learners/index.js
  api/lib/application/sco-organization-learners/sco-organization-learner-controller.js
  api/lib/domain/constants/update-organization-learners-password-errors.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-organization-learners-password.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/integration/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/domain/usecases/update-organization-learners-password_test.js
  orga/app/adapters/sco-organization-participant.js
  orga/app/components/sco-organization-participant/list.js
  orga/mirage/config.js
  orga/tests/acceptance/sco-organization-participant-list_test.js
  orga/tests/helpers/wait-for.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
Labels: :rocket: Ready to Merge, team-acces

#6592 [TECH] Spécifie les versions spécifique de ember-source et d'ember-data sur certif qui fonctionnent
  certif/package-lock.json
  certif/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6591 [TECH] Spécifie la version spécifique d'ember-data sur orga qui fonctionne
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6593 [TECH] Spécifie la version spécifique d'ember-source sur admin qui fonctionne
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6576 [FEAT] Création de la page avec la liste de toutes les certifications complémentaires (PIX-8576)
  admin/app/components/menu-bar.hbs
  admin/app/components/target-profiles-versioning/complementary-certifications.hbs
  admin/app/controllers/authenticated/target-profiles-versioning/complementary-certifications.js
  admin/app/router.js
  admin/app/routes/authenticated/target-profiles-versioning/complementary-certifications.js
  admin/app/routes/authenticated/target-profiles-versioning/index.js
  admin/app/services/access-control.js
  admin/app/templates/authenticated/target-profiles-versioning.hbs
  admin/app/templates/authenticated/target-profiles-versioning/complementary-certifications.hbs
  admin/tests/acceptance/authenticated/target-profiles-versioning/complementary-certifications_test.js
  admin/tests/integration/components/menu-bar_test.js
  admin/tests/unit/services/access-control-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6517 [TECH] Verifier les parametre de la route d'ajout de candidat (PIX-8537)
  api/lib/application/sessions/index.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  certif/app/components/enrolled-candidates.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/styles/components/new-certification-candidate-modal.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6586 [FEATURE] Ajoute la création d'une campagne à partir d'une campagne existante (PIX-8622).
  api/db/seeds/data/team-prescription/build-campaigns.js
  api/db/seeds/data/team-prescription/build-organization.js
  api/db/seeds/data/team-prescription/data-builder.js
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/create-form.js
  orga/app/controllers/authenticated/campaigns/new.js
  orga/app/models/campaign.js
  orga/app/routes/authenticated/campaigns/new.js
  orga/tests/integration/components/campaign/create-form_test.js
  orga/tests/unit/components/campaign/create-form_test.js
  orga/tests/unit/routes/authenticated/campaigns/new_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6420 [FEATURE] Ajouter la modalité QROC dans Pix 1d (PIX-8226)
  1d/app/initializers/register-showdown-extensions.js
  1d/app/pods/application/route.js
  1d/app/pods/components/challenge/challenge-illustration/component.js
  1d/app/pods/components/challenge/challenge-illustration/template.hbs
  1d/app/pods/components/challenge/challenge-item-qroc/component.js
  1d/app/pods/components/challenge/challenge-item-qroc/template.hbs
  1d/app/pods/components/challenge/item/template.hbs
  1d/app/styles/app.scss
  1d/app/styles/components/challenge-illustration.scss
  1d/app/styles/components/challenge-instruction.scss
  1d/app/styles/components/challenge-item-qroc.scss
  1d/app/styles/components/challenge-item.scss
  1d/app/styles/globals/_a11y.scss
  1d/app/utils/generate-random-string.js
  1d/app/utils/proposals-as-blocks.js
  1d/app/utils/proposals-parser/input-block.js
  1d/app/utils/proposals-parser/response-block.js
  1d/app/utils/proposals-parser/select-block.js
  1d/app/utils/proposals-parser/splitters.js
  1d/app/utils/proposals-parser/text-block.js
  1d/config/ember-intl.js
  1d/mirage/config.js
  1d/mirage/factories/challenge.js
  1d/package-lock.json
  1d/package.json
  1d/public/images/icons/external-link-alt.svg
  1d/tests/acceptance/challenge-item-qroc_test.js
  1d/translations/fr.json
  api/lib/domain/usecases/correct-answer.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6663 [BUGFIX] Corriger le bug de sélection de la catégorie (PIX-8680)
  admin/app/components/target-profiles/create-target-profile-form.hbs
  admin/app/components/target-profiles/create-target-profile-form.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6666 [FEATURE] Configurer la remise à zéro d'un profil cible (PIX-8444)
  admin/app/components/target-profiles/target-profile.hbs
  admin/app/components/target-profiles/update-target-profile.hbs
  admin/app/components/target-profiles/update-target-profile.js
  admin/mirage/handlers/target-profiles.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/management_test.js
  admin/translations/en.json
  admin/translations/fr.json
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/models/TargetProfileForCreation.js
  api/lib/domain/usecases/update-target-profile.js
  api/lib/infrastructure/repositories/target-profile-for-update-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-serializer.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/integration/infrastructure/repositories/target-profile-for-update-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-for-creation.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/domain/usecases/create-target-profile_test.js
  api/tests/unit/domain/usecases/update-target-profile_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-devcomp

#6558 [TECH] Mise à jour de Pix-UI sur Orga (Pix-8674)
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/create-form.js
  orga/app/components/team/invite-form.hbs
  orga/app/controllers/authenticated/team/new.js
  orga/app/templates/authenticated/team/new.hbs
  orga/mirage/factories/campaign-assessment-participation-result.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/integration/components/campaign/analysis/competences_test.js
  orga/tests/integration/components/participant/assessment/header_test.js
  orga/tests/integration/components/participant/assessment/results_test.js
  orga/tests/integration/components/team/invite-form_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-prescription

#6613 [FEATURE] Corriger le script de mise à jour des url de PixOrga (PIX-8414)
  api/scripts/prod/update-documentation-url.js
  api/tests/integration/scripts/prod/update-documentation-url_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#6653 [FEATURE] Création de la page détails d'une certification complémentaire sur Pix Admin (PIX-8577).
  admin/app/components/complementary-certifications/list.hbs
  admin/app/components/complementary-certifications/target-profiles/badges-list.hbs
  admin/app/components/complementary-certifications/target-profiles/information.hbs
  admin/app/components/complementary-certifications/target-profiles/log.hbs
  admin/app/components/menu-bar.hbs
  admin/app/components/target-profiles-versioning/complementary-certifications.hbs
  admin/app/router.js
  admin/app/routes/authenticated/complementary-certifications/complementary-certification.js
  admin/app/routes/authenticated/complementary-certifications/complementary-certification/details.js
  admin/app/routes/authenticated/complementary-certifications/complementary-certification/index.js
  admin/app/routes/authenticated/complementary-certifications/index.js
  admin/app/routes/authenticated/complementary-certifications/list.js
  admin/app/services/access-control.js
  admin/app/templates/authenticated/complementary-certifications.hbs
  admin/app/templates/authenticated/complementary-certifications/complementary-certification/details.hbs
  admin/app/templates/authenticated/complementary-certifications/list.hbs
  admin/app/templates/authenticated/target-profiles-versioning/complementary-certifications.hbs
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/complementary-certifications/list_test.js
  admin/tests/integration/components/complementary-certifications/target-profiles/badges-list_test.js
  admin/tests/integration/components/complementary-certifications/target-profiles/information_test.js
  admin/tests/integration/components/complementary-certifications/target-profiles/log_test.js
  admin/tests/integration/components/menu-bar_test.js
  admin/tests/unit/services/access-control-test.js
Labels: :rocket: Ready to Merge, team-certif

#6674 [FEATURE] Afficher les informations de la certification complémentaire sur la page de détails sur Pix Admin (PIX-8673).
  admin/app/adapters/complementary-certification.js
  admin/app/components/complementary-certifications/target-profiles/information.hbs
  admin/app/models/complementary-certification.js
  admin/app/routes/authenticated/complementary-certifications/complementary-certification/details.js
  admin/app/styles/app.scss
  admin/app/styles/components/complementary-certifications/details.scss
  admin/app/templates/authenticated/complementary-certifications/complementary-certification/details.hbs
  admin/mirage/config.js
  admin/tests/acceptance/complementary-certifications/complementary-certification/details_test.js
  admin/tests/acceptance/complementary-certifications/list_test.js
  admin/tests/integration/components/complementary-certifications/target-profiles/information_test.js
  api/lib/application/complementary-certifications/complementary-certification-controller.js
  api/lib/application/complementary-certifications/index.js
  api/lib/domain/models/ComplementaryCertificationForAdmin.js
  api/lib/domain/usecases/get-target-profile-from-complementary-certification.js
  api/lib/infrastructure/repositories/complementary-certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/complementary-certification-serializer.js
  api/tests/acceptance/application/complementary-certifications/complementary-certification-controller_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-repository_test.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-for-admin.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/complementary-certifications/index_test.js
  api/tests/unit/domain/usecases/get-target-profile-from-complementary-certification_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/complementary-certification-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#6623 [FEATURE] Supprimer le feature toggle FT_DIFFERENTIATED_TIME_INVIGILATOR_PORTAL (PIX-7837).
  api/lib/config.js
  api/lib/infrastructure/validate-environment-variables.js
  api/sample.env
  api/tests/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/candidate-in-list.js
  certif/app/models/feature-toggle.js
  certif/mirage/factories/feature-toggle.js
  certif/tests/acceptance/session-supervising_test.js
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/tests/integration/components/session-supervising/candidate-list_test.js
  certif/tests/unit/services/featureToggles_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#6672 [TECH] Tech days api arborescence monitoring setup
  .github/workflows/arborescence-monitoring.yaml
  api/package.json
  api/scripts/arborescence-monitoring/add-metrics-to-gist.js
  api/scripts/arborescence-monitoring/arborescence-monitoring.js
  api/scripts/arborescence-monitoring/quickcharts/doughnut.js
  api/scripts/arborescence-monitoring/quickcharts/quickcharts.js
  api/scripts/arborescence-monitoring/quickcharts/sankey.js
  api/scripts/arborescence-monitoring/quickcharts/time-series.js
  api/scripts/arborescence-monitoring/slack.js
  api/scripts/arborescence-monitoring/stats.js
  api/tests/acceptance/scripts/arborescence-monitoring_test.js
  api/tests/acceptance/scripts/mock-arborescence-monitoring/directory-1/file4.txt
  api/tests/acceptance/scripts/mock-arborescence-monitoring/directory-2/file5.csv
  api/tests/acceptance/scripts/mock-arborescence-monitoring/directory-2/file6.csv
  api/tests/acceptance/scripts/mock-arborescence-monitoring/file1.txt
  api/tests/acceptance/scripts/mock-arborescence-monitoring/file2.txt
  api/tests/acceptance/scripts/mock-arborescence-monitoring/file3.csv
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6669 [FEATURE] Ajouter la modalité QROCM dans pix1d (Pix-8606)
  1d/app/pods/challenge/model.js
  1d/app/pods/components/challenge/challenge-item-qroc/template.hbs
  1d/app/pods/components/challenge/challenge-item-qrocm/component.js
  1d/app/pods/components/challenge/challenge-item-qrocm/template.hbs
  1d/app/pods/components/challenge/item/component.js
  1d/app/pods/components/challenge/item/template.hbs
  1d/app/styles/app.scss
  1d/app/styles/components/challenge-item-proposals.scss
  1d/app/styles/components/challenge-item-qroc.scss
  1d/app/styles/components/challenge-item.scss
  1d/mirage/factories/challenge.js
  1d/tests/acceptance/challenge-item-qroc_test.js
  1d/tests/acceptance/challenge-item-qrocm_test.js
  1d/tests/integration/components/challenge_item_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6683 [TECH] Supprime la dépendance ember-export-application-global
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6677 [FEATURE] Ajouter la modalité QCM (Pix-8607)
  1d/app/pods/challenge/model.js
  1d/app/pods/components/challenge/challenge-item-qcm/component.js
  1d/app/pods/components/challenge/challenge-item-qcm/template.hbs
  1d/app/pods/components/challenge/item/template.hbs
  1d/app/styles/components/challenge-item-proposals.scss
  1d/app/styles/components/challenge-item.scss
  1d/app/utils/labeled-checkboxes.js
  1d/app/utils/proposals-as-array.js
  1d/app/utils/pshuffle.js
  1d/app/utils/value-as-array-of-boolean.js
  1d/mirage/factories/challenge.js
  1d/package-lock.json
  1d/package.json
  1d/tests/acceptance/challenge-item-qcm_test.js
  1d/tests/integration/components/challenge_item_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6688 [CLEANUP] Supprime de l'ancienne config sur certif
  certif/ember-cli-build.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6691 [FEATURE] Corrige le campaign tooling et ajoute des seeds pour prescription (PIX-8729)
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/db/seeds/data/team-prescription/build-campaigns.js
  api/db/seeds/data/team-prescription/build-organization.js
  api/db/seeds/data/team-prescription/build-target-profiles.js
  api/db/seeds/data/team-prescription/constants.js
  api/db/seeds/data/team-prescription/data-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6580 [FEATURE] Créer la bannière d'information pour l'ouverture du niveau 7 (Pix-8395)
  api/db/database-builder/factory/build-user.js
  api/db/migrations/20230711141725_add_column_has-seen-level-seven-info_to_users.js
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/usecases/remember-user-has-seen-level-seven-info.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-with-activity-serializer.js
  api/tests/acceptance/application/users/remember-user-has-seen-level-seven-info_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-activity-serializer_test.js
  mon-pix/app/adapters/user.js
  mon-pix/app/components/dashboard/banner.hbs
  mon-pix/app/components/new-information.hbs
  mon-pix/app/components/profile-content.hbs
  mon-pix/app/components/profile-content.js
  mon-pix/app/models/user.js
  mon-pix/app/services/url.js
  mon-pix/mirage/factories/user.js
  mon-pix/mirage/routes/users/index.js
  mon-pix/mirage/serializers/user.js
  mon-pix/tests/acceptance/profile_test.js
  mon-pix/tests/integration/components/profile-content_test.js
  mon-pix/tests/unit/services/url_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6536 [TECH] Mise à jour des tests basés sur le niveau max (PIX-8269)
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/tests/acceptance/application/users/users-get-shared-profile-for-campaign_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/domain/services/scoring/scoring-service_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/scorecard-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6681 [FEATURE] Éviter la présence d'éléments block dans des labels d'épreuve
  mon-pix/app/components/challenge-item-qroc.hbs
  mon-pix/app/components/markdown-to-html.hbs
  mon-pix/app/components/qcm-proposals.hbs
  mon-pix/app/components/qcu-proposals.hbs
  mon-pix/app/components/qrocm-ind-solution-panel.hbs
  mon-pix/app/components/qrocm-proposal.hbs
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/integration/components/qcu-proposals_test.js
  mon-pix/tests/integration/components/qrocm-ind-solution-panel_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6680 [FEATURE] Afficher les badges certifiants de la certification complementaire dans Pix Admin (PIX-8679)
  admin/app/components/complementary-certifications/list.hbs
  admin/app/components/complementary-certifications/target-profiles/badges-list.hbs
  admin/app/components/complementary-certifications/target-profiles/information.hbs
  admin/app/styles/components/complementary-certifications/details.scss
  admin/app/templates/authenticated/complementary-certifications/complementary-certification/details.hbs
  admin/tests/integration/components/complementary-certifications/target-profiles/badges-list_test.js
  admin/translations/en.json
  admin/translations/fr.json
  api/lib/infrastructure/repositories/complementary-certification-repository.js
  api/lib/infrastructure/serializers/jsonapi/complementary-certification-serializer.js
  api/tests/acceptance/application/complementary-certifications/complementary-certification-controller_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-repository_test.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-for-admin.js
  api/tests/unit/infrastructure/serializers/jsonapi/complementary-certification-serializer_test.js
Labels: :rocket: Ready to Merge, team-certif

#6693 [BUGFIX] Vérifier si l'épreuve est en autoReply (Pix-8737)
  1d/app/pods/challenge/model.js
  1d/mirage/factories/challenge.js
  1d/tests/unit/models/challenge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6699 [CLEANUP] Supprime des packages inutilisées
  1d/package-lock.json
  1d/package.json
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6697 [CHORE] Améliorer le CSS (PIX-8736)
  1d/app/pods/assessment/results/template.hbs
  1d/app/styles/app.scss
  1d/app/styles/components/answer.scss
  1d/app/styles/components/card.scss
  1d/app/styles/components/challenge-illustration.scss
  1d/app/styles/components/challenge-instruction.scss
  1d/app/styles/components/challenge-item-proposals.scss
  1d/app/styles/components/challenge-item.scss
  1d/app/styles/components/home.scss
  1d/app/styles/components/mission.scss
  1d/app/styles/components/warning.scss
  1d/app/styles/globals/_buttons.scss
  1d/app/styles/globals/_colors.scss
  1d/maintenance_page.html
  1d/maintenance_scheduled.html
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6566 [FEATURE] EPIX Réinitialisation en masse des mots de passe temporaires des élèves sur Pix Orga (PIX-8678)
  api/lib/application/error-manager.js
  api/lib/application/sco-organization-learners/index.js
  api/lib/application/sco-organization-learners/sco-organization-learner-controller.js
  api/lib/domain/constants/reset-organization-learners-password-errors.js
  api/lib/domain/errors.js
  api/lib/domain/models/OrganizationLearnerPasswordResetDTO.js
  api/lib/domain/usecases/generate-reset-organization-learners-password-cvs-content.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/reset-organization-learners-password.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/integration/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/domain/usecases/generate-reset-organization-learners-password-csv_test.js
  api/tests/unit/domain/usecases/reset-organization-learners-password_test.js
  orga/app/adapters/sco-organization-participant.js
  orga/app/components/sco-organization-participant/action-bar.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/app/components/sco-organization-participant/reset-password-modal.hbs
  orga/app/components/sco-organization-participant/reset-password-modal.js
  orga/app/components/sco-organization-participant/table-headers.hbs
  orga/app/components/sco-organization-participant/table-row.hbs
  orga/app/components/sco-organization-participant/table-row.js
  orga/app/styles/app.scss
  orga/app/styles/components/sco-organization-participant/reset-password-modal.scss
  orga/mirage/config.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/sco-organization-participant-list_test.js
  orga/tests/helpers/wait-for.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/unit/adapters/sco-organization-participant_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#6709 [TECH] Définir les environnements CircleCI en tant qu'executors
  .circleci/config.yml
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app

#6714 [TECH] Ajouter des seeds pour une activité (Pix-8752)
  api/db/database-builder/factory/build-assessment.js
  api/db/seeds/data/team-1d/data-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6713 [BUGFIX] Corrige la largeur du bouton "Je me connecte" de Pix Orga(PIX-8750).
  orga/app/styles/components/login-form.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6710 [FEATURE] Modifier le texte légal sur la page de récupération d'accès à Pix Orga (PIX-8559)
  orga/app/components/auth/join-request-form.hbs
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#6698 [BUMP] Monte la version minimale de Node.js en v16.17
  1d/package-lock.json
  1d/package.json
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/test-algo/package-lock.json
  high-level-tests/test-algo/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6708 [FEATURE] Ajouter le filtre sur la certificabilité dans la page de résultat d'une collecte de profil dans Pix Orga (PIX-2431)
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/db/seeds/data/team-prescription/build-campaigns.js
  api/db/seeds/data/team-prescription/build-organization.js
  api/lib/application/campaigns/campaign-controller.js
  api/lib/application/campaigns/index.js
  api/lib/application/organizations/helpers.js
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/tests/acceptance/application/campaigns/campaign-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  api/tests/unit/application/campaign/index_test.js
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/campaign/filter/participation-filters.js
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/controllers/authenticated/campaigns/campaign/profile-results.js
  orga/app/routes/authenticated/campaigns/campaign/profile-results.js
  orga/app/templates/authenticated/campaigns/campaign/profile-results.hbs
  orga/tests/integration/components/campaign/filter/participation-filters_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/profile-results_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/profile-results_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6719 [BUGFIX] Corriger la largeur du bouton "Je me connecte" de Pix Certif (PIX-8754).
  certif/app/components/login-form.hbs
  certif/app/styles/components/login-form.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6720 [TECH] :sparkles: Détecter les version de node dans les executors CircleCI
  .circleci/config.yml
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app, tech-days-up

#6725 [BUGFIX] Corriger la non-concordance des paramètres d'une traduction d'éligibilité sur Pix App (PIX-8755).
  mon-pix/translations/en.json
Labels: :rocket: Ready to Merge, team-certif

#6731 [TECH] Rollback de Artillery en v1 (stable)
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, tech-days-up

#6732 [TECH] Améliore les cas de test d'acceptance autour de l'affichage des modales (PIX-8756)
  1d/tests/acceptance/challenge-item-qroc_test.js
  1d/tests/acceptance/display-answer-modal_test.js
  1d/tests/acceptance/display-modal_test.js
  1d/tests/acceptance/display-warning-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6695 [TECH] Remplacer le package redis par ioredis.
  api/lib/infrastructure/caches/learning-content-cache.js
  api/lib/infrastructure/utils/RedisClient.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/utils/RedisClient_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK

#6729 [BUGFIX] Dans Pix Orga réparer le design cassé de l'affichage de la connexion Médiacentre dans la pop-up du compte de l'élève (PIX-8632)
  orga/app/components/sco-organization-participant/manage-authentication-method-modal.hbs
  orga/app/styles/components/manage-authentication-method-modal.scss
Labels: :rocket: Ready to Merge, team-acces

#6747 [TECH] Simplifier `cpfCertificationResultRepository.markCertificationToExport`
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, tech-days-up

#6715 [BUGFIX] Réparer le design de la page de récupération d'accès à Pix Orga (PIX-8315).
  orga/app/styles/components/join-request-form.scss
  orga/app/styles/globals/panels.scss
  orga/app/styles/pages/join-request.scss
Labels: :rocket: Ready to Merge, team-acces

#6728 [TECH] Ajouter un script pour mettre à jour l'attribut "identityProviderForCampaigns" d'une liste d'organisations (PIX-8433)
  api/lib/domain/usecases/update-organization.js
  api/scripts/organization/update-organizations-identity-provider-for-campaigns.js
  api/tests/unit/domain/usecases/update-organization_test.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#6712 [TECH] Ajouter un script pour mettre à jour le département d'une liste d'organisations (PIX-6970)
  api/lib/domain/usecases/organizations-administration/update-organization-province-code.js
  api/scripts/organization/update-organizations-province-code.js
  api/tests/unit/domain/usecases/organizations-administration/update-organization-province-code_test.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#6752 [TECH] Corrige le test du csv parser pour ne plus avoir de warning dans la console (PIX-8761)
  api/tests/unit/infrastructure/serializers/csv/csv-parser_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, no-review-app

#6692 [FEATURE] Afficher l'historique des badges liés à une certification complémentaire sur Pix Admin (PIX-8731).
  admin/app/components/complementary-certifications/target-profiles/history.hbs
  admin/app/components/complementary-certifications/target-profiles/information.hbs
  admin/app/components/complementary-certifications/target-profiles/information.js
  admin/app/components/complementary-certifications/target-profiles/log.hbs
  admin/app/models/complementary-certification.js
  admin/app/styles/components/complementary-certifications/details.scss
  admin/app/templates/authenticated/complementary-certifications/complementary-certification/details.hbs
  admin/tests/acceptance/authenticated/complementary-certifications/complementary-certification/details_test.js
  admin/tests/acceptance/authenticated/complementary-certifications/list_test.js
  admin/tests/acceptance/complementary-certifications/complementary-certification/details_test.js
  admin/tests/integration/components/complementary-certifications/target-profiles/history_test.js
  admin/tests/integration/components/complementary-certifications/target-profiles/information_test.js
  admin/tests/integration/components/complementary-certifications/target-profiles/log_test.js
  admin/tests/unit/components/complementary-certifications/information_test.js
  api/lib/application/complementary-certifications/complementary-certification-controller.js
  api/lib/application/complementary-certifications/index.js
  api/lib/domain/models/ComplementaryCertificationForAdmin.js
  api/lib/domain/models/ComplementaryCertificationTargetProfileHistory.js
  api/lib/domain/usecases/get-complementary-certification-target-profile-history.js
  api/lib/domain/usecases/get-target-profile-from-complementary-certification.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/complementary-certification-repository.js
  api/lib/infrastructure/repositories/complementary-certification-target-profile-history-repository.js
  api/lib/infrastructure/serializers/jsonapi/complementary-certification-serializer.js
  api/tests/acceptance/application/complementary-certifications/complementary-certification-controller_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-repository_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-target-profile-history-repository_test.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-for-admin.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-target-profile-history.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/usecases/get-complementary-certification-target-profile-history_test.js
  api/tests/unit/domain/usecases/get-target-profile-from-complementary-certification_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/complementary-certification-serializer_test.js
Labels: :rocket: Ready to Merge, team-certif

#6702 [TECH] Ajouter un test d'acceptance pour fiabiliser la route /api/admin/target-profiles/{id} (PIX-8748)
  api/lib/infrastructure/serializers/jsonapi/target-profile-for-admin-serializer.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6721 [TECH] Builder pix-admin avec Embroider
  admin/app/components/campaigns/update.js
  admin/app/components/certification-centers/information-edit.js
  admin/app/components/organizations/information-section-edit.js
  admin/app/components/target-profiles/update-target-profile.js
  admin/app/components/users/user-overview.js
  admin/app/models/campaign-form.js
  admin/app/models/certification-center-form.js
  admin/app/models/organization-form.js
  admin/app/models/target-profile-form.js
  admin/app/models/user-form.js
  admin/app/validators/presence.js
  admin/ember-cli-build.js
  admin/mirage/config.js
  admin/package-lock.json
  admin/package.json
  admin/tests/acceptance/administration_test.js
  admin/tests/acceptance/authenticated/campaigns/campaign-page_test.js
  admin/tests/acceptance/authenticated/campaigns/campaign-participations_test.js
  admin/tests/acceptance/authenticated/certification-centers/form_test.js
  admin/tests/acceptance/authenticated/certification-centers/get/invitations_test.js
  admin/tests/acceptance/authenticated/certification-centers/list_test.js
  admin/tests/acceptance/authenticated/certifications/certification/certification_test.js
  admin/tests/acceptance/authenticated/certifications/certification/details_test.js
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/acceptance/authenticated/certifications/certification/neutralization_test.js
  admin/tests/acceptance/authenticated/certifications/certification/profile_test.js
  admin/tests/acceptance/authenticated/complementary-certifications/complementary-certification/details_test.js
  admin/tests/acceptance/authenticated/complementary-certifications/list_test.js
  admin/tests/acceptance/authenticated/organizations/create-organization_test.js
  admin/tests/acceptance/authenticated/organizations/information-management_test.js
  admin/tests/acceptance/authenticated/organizations/invitations-management_test.js
  admin/tests/acceptance/authenticated/organizations/list_test.js
  admin/tests/acceptance/authenticated/organizations/memberships-management_test.js
  admin/tests/acceptance/authenticated/organizations/places-lot-creation-form_test.js
  admin/tests/acceptance/authenticated/organizations/places_test.js
  admin/tests/acceptance/authenticated/organizations/target-profiles-management_test.js
  admin/tests/acceptance/authenticated/sessions/list/to-be-published_test.js
  admin/tests/acceptance/authenticated/sessions/list/with-required-action_test.js
  admin/tests/acceptance/authenticated/sessions/session/certifications_test.js
  admin/tests/acceptance/authenticated/sessions/session/informations_test.js
  admin/tests/acceptance/authenticated/target-profiles/list_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/creation_test.js
  admin/tests/acceptance/authenticated/team/add-member_test.js
  admin/tests/acceptance/authenticated/team/list_test.js
  admin/tests/acceptance/authenticated/trainings/edit-triggers_test.js
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/acceptance/authenticated/trainings/target-profiles_test.js
  admin/tests/acceptance/authenticated/trainings/training_test.js
  admin/tests/acceptance/flag-results-sent-to-prescriptor_test.js
  admin/tests/acceptance/organization-invitations-management_test.js
  admin/tests/acceptance/session_test.js
  admin/tests/acceptance/sessions-list_test.js
  admin/tests/acceptance/tools_test.js
  admin/tests/integration/components/administration/campaigns-import_test.js
  admin/tests/integration/components/administration/organizations-import_test.js
  admin/tests/integration/components/certification-centers/information-edit_test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations_test.js
  admin/tests/unit/components/certification-centers/information-edit_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, tech-days-up

#6694 [TECH] Ajout de paramètres pour l'email de résultats de certification (PIX-8611).
  api/lib/domain/services/mail-service.js
  api/tests/unit/domain/services/mail-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6768 [BUGFIX] Créer les acquis de la campagne au moment de la création en masse (PIX-8735)
  api/lib/domain/usecases/campaigns-administration/create-campaigns.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/campaigns-administration/campaign-repository.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/integration/infrastructure/repositories/campaigns-administration/campaign-repository_test.js
  api/tests/unit/domain/usecases/campaigns-administration/create-campaigns_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6675 [FEATURE](admin) Empêcher l'ajout, la suppression et la modification de seuil ou niveau d'un palier lorsqu'une campagne est associé au profil cible. (PIX-8646)
  admin/app/components/stages/stage.hbs
  admin/app/components/stages/update-stage.hbs
  admin/app/components/stages/update-stage.js
  admin/app/components/target-profiles/insights.hbs
  admin/app/components/target-profiles/stages.hbs
  admin/app/components/target-profiles/stages.js
  admin/app/components/target-profiles/stages/stage.hbs
  admin/app/components/target-profiles/stages/stage.js
  admin/app/components/target-profiles/target-profile.hbs
  admin/app/components/target-profiles/target-profile.js
  admin/app/controllers/authenticated/target-profiles/target-profile/stages/stage.js
  admin/app/models/target-profile.js
  admin/app/styles/components/target-profiles/insights.scss
  admin/app/templates/authenticated/target-profiles/target-profile/stages/stage.hbs
  admin/mirage/factories/target-profile.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/management_test.js
  admin/tests/integration/components/stages/stage_test.js
  admin/tests/integration/components/target-profiles/stages_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6772 [BUGFIX] Réparer la selection des niveaux sur les paliers par niveaux
  api/lib/infrastructure/serializers/jsonapi/target-profile-for-admin-serializer.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6730 [FEATURE] Créer les colonnes detachedAt et createdBy pour la table complementary-certification-badges (PIX-8745).
  admin/app/components/complementary-certifications/target-profiles/history.hbs
  admin/tests/integration/components/complementary-certifications/target-profiles/history_test.js
  api/db/database-builder/factory/build-complementary-certification-badge.js
  api/db/migrations/20230725115718_add_created_by_and_detached_at_in_complementary_certification_badges.js
  api/db/seeds/data/common/common-builder.js
  api/lib/infrastructure/repositories/complementary-certification-target-profile-history-repository.js
  api/tests/acceptance/application/complementary-certifications/complementary-certification-controller_test.js
  api/tests/integration/infrastructure/repositories/complementary-certification-target-profile-history-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#6771 [TECH] Amélioration de l'affichage de la preview (PIX-8763)
  1d/app/pods/challenge-preview/route.js
  1d/app/pods/challenge-preview/template.hbs
  1d/app/pods/components/challenge/challenge-item-qcm/component.js
  1d/app/pods/components/challenge/item/component.js
  1d/app/pods/components/challenge/item/template.hbs
  1d/app/utils/pshuffle.js
  1d/mirage/config.js
  1d/tests/acceptance/display-challenge-preview_test.js
  api/lib/domain/usecases/correct-answer.js
  api/lib/infrastructure/serializers/jsonapi/activity-answer-serializer.js
  api/tests/integration/domain/usecases/correct-answer_test.js
  api/tests/unit/domain/usecases/correct-answer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6737 [TECH] Support d'une date dans le script de vérification d'eligibilité aux certifications (PIX-8746).
  api/lib/domain/services/certification-badges-service.js
  api/lib/domain/usecases/get-user-certification-eligibility.js
  api/lib/infrastructure/repositories/certifiable-badge-acquisition-repository.js
  api/scripts/certification/get-user-certifications-eligibility.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/infrastructure/repositories/certifiable-badge-acquisition-repository_test.js
  api/tests/unit/domain/services/certification-badges-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6773 [BUGFIX] Corriger l'affichage du lien sur la page de récupération d'accès à Pix Orga (PIX-8782)
  orga/app/components/auth/join-request-form.hbs
Labels: :rocket: Ready to Merge, team-acces

#6727 [TECH] Refactoring des seeds certif (PIX-8547)
  api/db/database-builder/factory/build-campaign.js
  api/db/seeds/data/common/common-builder.js
  api/db/seeds/data/common/tooling/organization-tooling.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/db/seeds/data/team-certification/data-builder.js
  api/db/seeds/data/team-contenu/data-builder.js
  api/db/seeds/data/team-evaluation/data-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6780 [TECH] Ajouter un test sur le bouton retour (PIX-8776)
  1d/app/pods/assessment/results/route.js
  1d/tests/acceptance/end-mission_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, 🎒👧🏽👦🏾 Pix1D

#6777 [TECH] Ajout de tests pour le challenge de type embed (PIX-8777)
  1d/tests/acceptance/challenge-item-qroc_test.js
  1d/tests/acceptance/challenge-item-qrocm_test.js
  1d/tests/integration/components/challenge_item_test.js
  1d/tests/unit/models/challenge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, 🎒👧🏽👦🏾 Pix1D

#6781 [TECH] Trier les data pour la génération du timeSeries chart des tech-days api arboresence
  api/scripts/arborescence-monitoring/add-metrics-to-gist.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#6717 [FEATURE] Mettre à jour le prénom et le nom reçus du GAR quand le samlID change pour un même user (PIX-4771)
  api/lib/domain/services/user-reconciliation-service.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/create-and-reconcile-user-to-organization-learner.js
  api/lib/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user.js
  api/lib/domain/usecases/reconcile-sco-organization-learner-manually.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/lib/infrastructure/repositories/organization-learner-repository.js
  api/tests/integration/domain/usecases/create-and-reconcile-user-to-organization-learner_test.js
  api/tests/integration/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user_test.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
  api/tests/unit/domain/usecases/create-and-reconcile-user-to-organization-learner_test.js
  api/tests/unit/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user_test.js
  api/tests/unit/domain/usecases/reconcile-sco-organization-learner-manually_test.js
Labels: :rocket: Ready to Merge, team-acces

#6785 [TECH] Change le repository utilisé pour eslint-plugin-knex
  api/package-lock.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6782 [TECH] Revue de la fonction shuffle pour 1d (pix-8784)
  1d/app/pods/components/challenge/challenge-item-qcm/component.js
  1d/app/pods/components/challenge/challenge-item-qcu/component.js
  1d/app/pods/components/challenge/item/template.hbs
  1d/app/utils/pshuffle.js
  1d/tests/unit/utils/pshuffle_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, 🎒👧🏽👦🏾 Pix1D
