Repository 1024pix/pix, pull requests merged in 2023-05, with the labels that each got.

#6109 [TECH] Injection de dépendances pour préparer la migration ESM - Suite
  api/lib/domain/services/assessment-result-service.js
  api/lib/domain/services/authentication/pix-authentication-service.js
  api/lib/domain/services/certification-badges-service.js
  api/lib/domain/services/course-service.js
  api/lib/domain/services/get-competence-level.js
  api/lib/domain/services/learning-content/learning-content-conversion-service.js
  api/lib/domain/services/obfuscation-service.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/domain/services/session-publication-service.js
  api/tests/unit/domain/services/assessment-result-service_test.js
  api/tests/unit/domain/services/authentication/pix-authentication-service_test.js
  api/tests/unit/domain/services/certification-badges-service_test.js
  api/tests/unit/domain/services/course-service_test.js
  api/tests/unit/domain/services/get-competence-level_test.js
  api/tests/unit/domain/services/learning-content/learning-content-conversion-service_test.js
  api/tests/unit/domain/services/obfuscation-service_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/domain/services/scoring/scoring-certification-service_test.js
  api/tests/unit/domain/services/session-publication-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6103 [TECH] Renommage de enroll en enrol (PIX-7906).
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/error-manager.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/Session.js
  api/lib/domain/read-models/StudentForEnrolment.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/enrol-students-to-session.js
  api/lib/domain/usecases/find-students-for-enrolment.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/enroll-students-to-session_test.js
  api/tests/unit/domain/usecases/find-students-for-enrolment_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/student-certification-serializer_test.js
  certif/app/adapters/session.js
  certif/app/components/add-student-list.hbs
  certif/app/components/add-student-list.js
  certif/mirage/config.js
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/unit/adapters/session_test.js
  certif/tests/unit/components/add-student-list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6099 [BUGFIX] Le rechargement d'un embed n'émet aucun evènement (PIX-7887)
  mon-pix/app/components/challenge-embed-simulator.js
  mon-pix/app/components/challenge-item-qroc.js
  mon-pix/app/utils/embed-allowed-origins.js
  mon-pix/tests/unit/components/challenge-item-qroc_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#6107 [BUGFIX] Les menus de navigation sur Admin ne sont pas en surbrillances quand on est dans une sous page (PIX-7914)
  admin/app/components/menu-bar.hbs
  admin/app/routes/authenticated/sessions/index.js
  admin/app/routes/authenticated/trainings/index.js
  admin/tests/acceptance/administration_test.js
  admin/tests/acceptance/authenticated/certification-centers/list_test.js
  admin/tests/acceptance/authenticated/certifications/certification/informations_test.js
  admin/tests/acceptance/authenticated/organizations/create-organization_test.js
  admin/tests/acceptance/authenticated/organizations/list_test.js
  admin/tests/acceptance/authenticated/organizations/memberships-management_test.js
  admin/tests/acceptance/authenticated/sessions/list/to-be-published_test.js
  admin/tests/acceptance/authenticated/sessions/list/with-required-action_test.js
  admin/tests/acceptance/authenticated/target-profiles/list_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/creation_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/management_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/organizations_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/training-summaries_test.js
  admin/tests/acceptance/authenticated/team/list_test.js
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/acceptance/authenticated/trainings/training_test.js
  admin/tests/acceptance/authenticated/users/list_test.js
  admin/tests/acceptance/flag-results-sent-to-prescriptor_test.js
  admin/tests/acceptance/tools_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#6119 [TECH] Injection de dépendances dans les models pour préparer la migration ESM
  api/lib/domain/models/UserToCreate.js
  api/lib/domain/models/ValidatorQCM.js
  api/lib/domain/models/ValidatorQCU.js
  api/lib/domain/models/ValidatorQROCMDep.js
  api/lib/domain/models/ValidatorQROCMInd.js
  api/scripts/add-tags-to-organizations.js
  api/tests/unit/domain/models/UserToCreate_test.js
  api/tests/unit/domain/models/ValidatorQCM_test.js
  api/tests/unit/domain/models/ValidatorQCU_test.js
  api/tests/unit/domain/models/ValidatorQROCMDep_test.js
  api/tests/unit/domain/models/ValidatorQROCMInd_test.js
  api/tests/unit/scripts/add-tags-to-organizations_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6100 [BUGFIX] Empêcher le scrollTop lors de l'utilisation d'un filtre/pagination (PIX-7912)
  admin/app/router.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#6105 [FEATURE] Trier les profiles cibles dans PixAdmin par status puis par nom (PIX-7913)
  api/lib/infrastructure/repositories/target-profile-summary-for-admin-repository.js
  api/tests/integration/infrastructure/repositories/target-profile-summary-for-admin-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6106 [TECH] Renvoyer une erreur 422 au lieu d'une erreur 503 quand l'appel à la route /token de l'idp échoue (PIX-7915)
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/tests/acceptance/application/authentication/oidc/token-route-post_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
Labels: :rocket: Ready to Merge, team-acces

#6124 [TECH] - Mettre en place l'injection de dépendances pour les cas restants
  api/lib/application/pre-response-utils.js
  api/lib/application/preHandlers/user-existence-verification.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/infrastructure/mailers/mailer.js
  api/lib/infrastructure/repositories/competence-tree-repository.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/tests/unit/application/pre-response-utils_test.js
  api/tests/unit/application/preHandlers/user-existence-verification_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
  api/tests/unit/infrastructure/repositories/competence-tree-repository_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6101 [TECH] Mise à jour de la langue utilisateur depuis le controller language (PIX-7871)
  mon-pix/app/controllers/authenticated/user-account/language.js
  mon-pix/app/templates/authenticated/user-account.hbs
  mon-pix/tests/acceptance/user-account_test.js
  mon-pix/tests/unit/controllers/authenticated/user-account/language_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#6120 [FEATURE] Ajouter une méthode au solution-service-qrcom-dep pour avoir le résultat complet (PIX-7865)
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/tests/unit/domain/services/solution-service-qrocm-dep_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6116 [TECH] Tester unitairement le use-case sessions-mass-import
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6084 [TECH] Permet de configurer le proxy de l'API des fronts pix vers une release de test (PIX-7880)
  admin/servers.conf.erb
  certif/servers.conf.erb
  mon-pix/servers.conf.erb
  orga/servers.conf.erb
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6134 [FEATURE] Suppression des références Gravitee (PIX-7909)
  api/lib/config.js
  api/lib/domain/usecases/authenticate-application.js
  api/lib/infrastructure/authentication.js
  api/tests/acceptance/application/authentication/authentication-route_test.js
  api/tests/acceptance/application/certifications-livret-scolaire/certification-controller_test.js
  api/tests/test-helper.js
Labels: :rocket: Ready to Merge, team-captains

#6123 [FEATURE] Utiliser les design tokens de typographie pour l'entête des épreuves (PIX-7779)
  mon-pix/app/styles/components/_assessment-banner.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_progress-bar.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6125 [BUGFIX] Améliorer la lecture d'écran des boutons d'action d'une épreuve (PIX-7920)
  mon-pix/app/components/challenge-actions.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6127 [TECH] Mettre à jour les urls de certaines Orga ayant des tags (PIX-7928)
  api/scripts/prod/update-documentation-url.js
  api/tests/integration/scripts/prod/update-documentation-url_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6074 [TECH] Uniformiser les vérifications joi pour l'import candidat (PIX-7859)
  api/lib/domain/constants/certification-candidates-errors.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  certif/tests/integration/components/sessions-import/step-two-section_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#6144 [FEATURE] Ajouter le sélecteur de langue sur la page app.pix.org/campagnes (PIX-7216)
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/tests/acceptance/fill-in-campaign-code_test.js
Labels: :rocket: Ready to Merge, team-acces

#6147 [TECH] Compléter et documenter les outils génériques pour la création de profil cibles et clés de lecture dans les seeds (PIX-7951)
  api/db/seeds/data/common/target-profile-tooling.js
  api/db/seeds/data/learning-content/target-profiles-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6138 [BUGFIX] Affichage du temps majoré dans l'Espace Surveillant (PIX-7835)
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/helpers/format-percentage.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/tests/unit/helpers/format-percentage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6143 [FEATURE] Modifier le tri des participations d'un utilisateur pour les regrouper par code campagne (PIX-5389)
  api/lib/infrastructure/repositories/participations-for-user-management-repository.js
  api/tests/integration/infrastructure/repositories/participations-for-user-management-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6130 [TECH] Met à jour vers @faker-js/faker
  admin/mirage/factories/certification-center-invitation.js
  admin/mirage/factories/certification-center.js
  admin/mirage/factories/organization-invitation.js
  admin/mirage/factories/session.js
  admin/mirage/factories/training.js
  admin/mirage/factories/user.js
  admin/package-lock.json
  admin/package.json
  certif/mirage/factories/certification-candidate.js
  certif/mirage/factories/certification-report.js
  certif/mirage/factories/country.js
  certif/mirage/factories/division.js
  certif/mirage/factories/session.js
  certif/mirage/factories/student.js
  certif/package-lock.json
  certif/package.json
  high-level-tests/load-testing/data/generate-siecle-file.js
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  high-level-tests/load-testing/processor/functions.js
  high-level-tests/load-testing/tests/unit/processor/functions_test.js
  mon-pix/mirage/factories/assessment.js
  mon-pix/mirage/factories/campaign.js
  mon-pix/mirage/factories/certification-course.js
  mon-pix/mirage/factories/challenge.js
  mon-pix/mirage/factories/competence-result.js
  mon-pix/mirage/factories/correction.js
  mon-pix/mirage/factories/course.js
  mon-pix/mirage/factories/tutorial.js
  mon-pix/mirage/factories/user.js
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/mirage/factories/campaign-participation.js
  orga/mirage/factories/campaign-profile.js
  orga/mirage/factories/campaign.js
  orga/mirage/factories/division.js
  orga/mirage/factories/organization-invitation.js
  orga/mirage/factories/organization-participant.js
  orga/mirage/factories/target-profile.js
  orga/mirage/factories/user.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/sco-organization-participant/manage-authentication-method-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6152 [TECH] Compléter et documenter les outils génériques pour la création de campagne dans les seeds (PIX-7959)
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/db/seeds/data/common/tooling/index.js
  api/db/seeds/data/common/tooling/learning-content.js
  api/db/seeds/data/common/tooling/target-profile-tooling.js
  api/db/seeds/data/learning-content/target-profiles-builder.js
  api/db/seeds/data/team-contenu/data-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6155 [TECH] Compléter et documenter les outils génériques pour la création de contenus formatifs dans les seeds (PIX-7959)
  api/db/seeds/data/common/tooling/index.js
  api/db/seeds/data/common/tooling/training-tooling.js
  api/db/seeds/data/team-contenu/data-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6159 [TECH] Mise à jour de faker en v7
  admin/mirage/factories/certification-center-invitation.js
  admin/mirage/factories/certification-center.js
  admin/mirage/factories/organization-invitation.js
  admin/mirage/factories/session.js
  admin/mirage/factories/training.js
  admin/mirage/factories/user.js
  admin/package-lock.json
  admin/package.json
  certif/mirage/factories/certification-candidate.js
  certif/mirage/factories/certification-report.js
  certif/mirage/factories/country.js
  certif/mirage/factories/division.js
  certif/mirage/factories/session.js
  certif/mirage/factories/student.js
  certif/package-lock.json
  certif/package.json
  mon-pix/mirage/factories/assessment.js
  mon-pix/mirage/factories/campaign.js
  mon-pix/mirage/factories/certification-course.js
  mon-pix/mirage/factories/challenge.js
  mon-pix/mirage/factories/competence-result.js
  mon-pix/mirage/factories/correction.js
  mon-pix/mirage/factories/course.js
  mon-pix/mirage/factories/tutorial.js
  mon-pix/mirage/factories/user.js
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/mirage/factories/campaign-participation.js
  orga/mirage/factories/campaign-profile.js
  orga/mirage/factories/campaign.js
  orga/mirage/factories/division.js
  orga/mirage/factories/organization-invitation.js
  orga/mirage/factories/organization-participant.js
  orga/mirage/factories/target-profile.js
  orga/mirage/factories/user.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/sco-organization-participant/manage-authentication-method-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6117 [TECH] Appeler session.setup de ember-simple-auth dans la route de l'application
  admin/app/routes/application.js
  admin/ember-cli-build.js
  certif/app/routes/application.js
  certif/ember-cli-build.js
  mon-pix/app/instance-initializers/session.js
  mon-pix/app/routes/application.js
  mon-pix/ember-cli-build.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/unit/adapters/application_test.js
  mon-pix/tests/unit/routes/application_test.js
  mon-pix/tests/unit/routes/campaigns/join_test.js
  mon-pix/tests/unit/services/session_test.js
  orga/app/routes/application.js
  orga/ember-cli-build.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6161 [TECH] Supprime la dépendance ember-collapsible-panel
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6165 [TECH] Déplacer les données en commun des seeds dans un fichier dédié (PIX-7996)
  api/db/seeds/data/common/common-builder.js
  api/db/seeds/data/tags-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6163 [TECH] Utiliser la méthode `render` d'`ember-testing-library` plutôt que celle de `@ember/test-helpers` (PIX-7998)
  mon-pix/blueprints/component-test/files/tests/integration/components/__name___test.js
  mon-pix/tests/integration/components/account-recovery/student-information-form-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/to-share_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/grid_test.js
  mon-pix/tests/integration/components/certification-joiner_test.js
  mon-pix/tests/integration/components/certification-not-certifiable_test.js
  mon-pix/tests/integration/components/certifications-list_test.js
  mon-pix/tests/integration/components/challenge-actions_test.js
  mon-pix/tests/integration/components/challenge-item-qroc_test.js
  mon-pix/tests/integration/components/challenge/item_test.js
  mon-pix/tests/integration/components/challenge/statement/tooltip_test.js
  mon-pix/tests/integration/components/circle-chart_test.js
  mon-pix/tests/integration/components/communication-banner_test.js
  mon-pix/tests/integration/components/comparison-window_test.js
  mon-pix/tests/integration/components/competence-card-default_test.js
  mon-pix/tests/integration/components/competence-card-mobile_test.js
  mon-pix/tests/integration/components/feedback-certification-section_test.js
  mon-pix/tests/integration/components/form-textfield-date_test.js
  mon-pix/tests/integration/components/form-textfield_test.js
  mon-pix/tests/integration/components/inaccessible-campaign_test.js
  mon-pix/tests/integration/components/learning-more-panel_test.js
  mon-pix/tests/integration/components/levelup-notif_test.js
  mon-pix/tests/integration/components/no-certification-panel_test.js
  mon-pix/tests/integration/components/pix-toggle-deprecated_test.js
  mon-pix/tests/integration/components/profile-content_test.js
  mon-pix/tests/integration/components/qcm-proposals_test.js
  mon-pix/tests/integration/components/qcm-solution-panel_test.js
  mon-pix/tests/integration/components/qcu-proposals_test.js
  mon-pix/tests/integration/components/qcu-solution-panel_test.js
  mon-pix/tests/integration/components/qroc-solution-panel_test.js
  mon-pix/tests/integration/components/qrocm-dep-solution-panel_test.js
  mon-pix/tests/integration/components/qrocm-ind-solution-panel_test.js
  mon-pix/tests/integration/components/result-item-campaign_test.js
  mon-pix/tests/integration/components/routes/campaigns/invited/associate-sup-student-form_test.js
  mon-pix/tests/integration/components/routes/campaigns/invited/fill-in-participant-external-id_test.js
  mon-pix/tests/integration/components/routes/campaigns/profiles_collection/send-profile_test.js
  mon-pix/tests/integration/components/routes/login-form_test.js
  mon-pix/tests/integration/components/routes/login-or-register_test.js
  mon-pix/tests/integration/components/timeout-gauge_test.js
  mon-pix/tests/integration/components/training/card_test.js
  mon-pix/tests/integration/components/tutorial-panel_test.js
  mon-pix/tests/integration/components/tutorials/card_test.js
  mon-pix/tests/integration/components/tutorials/cards_test.js
  mon-pix/tests/integration/components/user-certifications-detail-competence_test.js
  mon-pix/tests/integration/components/user-certifications-detail-competences-list_test.js
  mon-pix/tests/integration/components/user-tutorials/filters/item-checkbox_test.js
  mon-pix/tests/unit/helpers/contains_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6078 [FEATURE] Améliorer les tests sur Pix App avec Testing Library (part 3) (PIX-7870).
  mon-pix/app/components/assessment-banner.hbs
  mon-pix/app/components/certifications/certification-ender.hbs
  mon-pix/tests/acceptance/authentication_test.js
  mon-pix/tests/acceptance/certification-course_test.js
  mon-pix/tests/acceptance/challenge-commons_test.js
  mon-pix/tests/acceptance/challenge-page-banner_test.js
  mon-pix/tests/acceptance/profile_test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection_test.js
  mon-pix/tests/acceptance/resume-competence-evaluations_test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment_test.js
  mon-pix/tests/acceptance/user-account/connection-methods_test.js
  mon-pix/tests/acceptance/user-logged-menu_test.js
  mon-pix/tests/acceptance/user-tests_test.js
  mon-pix/tests/helpers/authentication.js
  mon-pix/tests/helpers/contains.js
  mon-pix/tests/integration/components/account-recovery/backup-email-confirmation-form-test.js
  mon-pix/tests/integration/components/account-recovery/student-information-form-test.js
  mon-pix/tests/integration/components/account-recovery/update-sco-record-form-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/disabled_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ended_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/to-share_test.js
  mon-pix/tests/integration/components/certification-joiner_test.js
  mon-pix/tests/integration/components/routes/campaigns/invited/associate-sup-student-form_test.js
  mon-pix/tests/integration/components/routes/campaigns/profiles_collection/send-profile_test.js
  mon-pix/tests/integration/components/routes/login-form_test.js
  mon-pix/tests/integration/components/tutorials/header_test.js
  mon-pix/tests/integration/components/user-account/email-verification-code-test.js
  mon-pix/tests/integration/components/user-account/email-with-validation-form-test.js
  mon-pix/tests/unit/helpers/contains_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif, cross-team

#6104 [FEATURE] Amélioration de la page de détails des profils cibles (PIX-7907)
  admin/app/components/target-profiles/target-profile.hbs
  admin/app/styles/components/target-profiles/target-profile.scss
  admin/tests/acceptance/authenticated/target-profiles/target-profile/management_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#6166 [TECH] Fournir des outils génériques et documentés orientés "Organisations" et "Centres de certification" (PIX-7995)
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/certification/complementary-certification-course-results-builder.js
  api/db/seeds/data/common/common-builder.js
  api/db/seeds/data/common/tooling/certification-center-tooling.js
  api/db/seeds/data/common/tooling/index.js
  api/db/seeds/data/common/tooling/organization-tooling.js
  api/db/seeds/data/team-certification/data-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6153 [BUGFIX] Erreur lors ajout individuel d'un 2ème candidat à une session de certification sur Pix Certif (PIX-7935).
  certif/app/components/new-certification-candidate-modal.hbs
Labels: :rocket: Ready to Merge, team-certif

#6154 [FEATURE] Désactiver le bouton Effacer les filtres lorsqu'aucun fitre n'est activé (Pix-7970)
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/filter/campaign-filters.hbs
  orga/app/components/campaign/filter/campaign-filters.js
  orga/app/components/campaign/filter/filters.hbs
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/campaign/filter/participation-filters.js
  orga/app/components/campaign/header/archived-banner.js
  orga/app/components/campaign/list.hbs
  orga/app/components/campaign/settings/view.js
  orga/app/components/campaign/update-form.js
  orga/app/components/organization-participant/learner-filters.hbs
  orga/app/components/organization-participant/learner-filters.js
  orga/app/components/organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/app/components/sco-organization-participant/sco-learner-filters.hbs
  orga/app/components/sco-organization-participant/sco-learner-filters.js
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/components/sup-organization-participant/list.js
  orga/app/components/sup-organization-participant/sup-learner-filters.hbs
  orga/app/components/sup-organization-participant/sup-learner-filters.js
  orga/app/components/team/invitations-list-item.js
  orga/app/components/team/invitations-list.js
  orga/app/components/team/members-list-item.js
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/controllers/authenticated/campaigns/list/all-campaigns.js
  orga/app/controllers/authenticated/campaigns/list/my-campaigns.js
  orga/app/controllers/authenticated/certifications.js
  orga/app/controllers/authenticated/organization-participants/list.js
  orga/app/controllers/authenticated/team/new.js
  orga/app/templates/authenticated/campaigns/campaign/profile-results.hbs
  orga/app/templates/authenticated/campaigns/list/all-campaigns.hbs
  orga/app/templates/authenticated/campaigns/list/my-campaigns.hbs
  orga/app/templates/authenticated/organization-participants/list.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/campaign/activity/participants-list_test.js
  orga/tests/integration/components/campaign/filter/campaign-filters_test.js
  orga/tests/integration/components/campaign/filter/participation-filters_test.js
  orga/tests/integration/components/campaign/list_test.js
  orga/tests/integration/components/campaign/results/assessment-list_test.js
  orga/tests/integration/components/campaign/results/profile-list_test.js
  orga/tests/integration/components/organization-participant/list_test.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/tests/unit/controllers/authenticated/campaigns/list/all-campaigns_test.js
  orga/tests/unit/controllers/authenticated/campaigns/list/my-campaigns_test.js
  orga/tests/unit/controllers/authenticated/certifications_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6156 [FEATURE][MON-PIX] Ajouter le sélecteur de langue sur la page de présentation d'une campagne (PIX-7744)
  mon-pix/app/controllers/campaigns/campaign-landing-page.js
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/tests/acceptance/campaigns/campaign-landing-page_test.js
Labels: :rocket: Ready to Merge, team-acces

#6096 [FEATURE] Afficher un bouton de confirmation de présence dans l'espace surveillant sur Pix Certif (PIX-7832)
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/candidate-in-list.js
  certif/app/styles/components/session-supervising/candidate-in-list.scss
  certif/tests/acceptance/session-supervising_test.js
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#6176 [TECH] Utiliser la méthode `visit` d'`ember-testing-library` plutôt que celle de `@ember/test-helpers` (PIX-8017)
  mon-pix/.eslintrc.js
  mon-pix/blueprints/acceptance-test/files/tests/acceptance/__name___test.js
  mon-pix/tests/acceptance/challenge-attachment_test.js
  mon-pix/tests/acceptance/challenge-feedback_test.js
  mon-pix/tests/acceptance/challenge-flash-in-campaign_test.js
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/acceptance/challenge-item-qroc_test.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/acceptance/challenge-item_test.js
  mon-pix/tests/acceptance/challenge-timed_test.js
  mon-pix/tests/acceptance/checkpoint_test.js
  mon-pix/tests/acceptance/competence-profile_test.js
  mon-pix/tests/acceptance/competences-details_test.js
  mon-pix/tests/acceptance/competences-results_test.js
  mon-pix/tests/acceptance/course-ending-screen_test.js
  mon-pix/tests/acceptance/error-redirection_test.js
  mon-pix/tests/acceptance/fill-in-certificate-verification-code_test.js
  mon-pix/tests/acceptance/footer_test.js
  mon-pix/tests/acceptance/logout-anonymous-user-when-access-to-not-allowed-pages_test.js
  mon-pix/tests/acceptance/navigation_test.js
  mon-pix/tests/acceptance/not-found-redirect-to-index_test.js
  mon-pix/tests/acceptance/starting-a-course_test.js
  mon-pix/tests/acceptance/tutorial-actions_test.js
  mon-pix/tests/acceptance/user-certifications_test.js
  mon-pix/tests/acceptance/user-trainings_test.js
  mon-pix/tests/acceptance/user-tutorials_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6082 [TECH] Supprime la dépendance ember-cli-sri des apps embroider
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6177 [FEATURE] Suppression de toutes références à Gravitee (PIX-7940)
  api/lib/config.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6137 [FEATURE] Vérification de l'égilibité des candidats à une certif compl. dans l'espace surveillant (PIX-7833).
  api/lib/domain/models/CertificationCandidateForSupervising.js
  api/lib/domain/usecases/get-session-for-supervising.js
  api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-for-supervising-serializer.js
  api/tests/integration/infrastructure/repositories/certification-candidate-for-supervising-repository_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-for-supervising-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate-for-supervising.js
  api/tests/unit/domain/models/CertificationCandidateForSupervising_test.js
  api/tests/unit/domain/usecases/get-session-for-supervising_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-for-supervising-serializer_test.js
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/candidate-in-list.js
  certif/app/models/certification-candidate-for-supervising.js
  certif/app/styles/components/session-supervising/candidate-in-list.scss
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#6160 [FEATURE] Amélioration de message de validation de suppression d'une participation (PIX-5625)
  orga/app/components/campaign/activity/delete-participation-modal.hbs
  orga/app/components/campaign/activity/delete-participation-modal.js
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/activity/participants-list.js
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/integration/components/campaign/activity/delete-participation-modal_test.js
  orga/tests/unit/controllers/authenticated/campaigns/campaign/activity_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6149 [TECH] Implementation d'un Domain Model CorrectionBlockQRCOMDep (PIX-8012)
  api/lib/domain/models/CorrectionBlockQROCMDep.js
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/tests/unit/domain/models/CorrectionBlockQROCMDep_test.js
  api/tests/unit/domain/services/solution-service-qrocm-dep_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6150 [FEATURE] Ordre aléatoire pour les propositions de QCU/QCM (PIX-7736)
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-challenge-learning-content-data-object.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  mon-pix/app/components/challenge-item-generic.js
  mon-pix/app/components/challenge-item-qcm.hbs
  mon-pix/app/components/challenge-item-qcu.hbs
  mon-pix/app/components/qcm-proposals.hbs
  mon-pix/app/components/qcm-proposals.js
  mon-pix/app/components/qcm-solution-panel.hbs
  mon-pix/app/components/qcm-solution-panel.js
  mon-pix/app/components/qcu-proposals.hbs
  mon-pix/app/components/qcu-proposals.js
  mon-pix/app/components/qcu-solution-panel.hbs
  mon-pix/app/components/qcu-solution-panel.js
  mon-pix/app/models/challenge.js
  mon-pix/app/utils/labeled-checkboxes.js
  mon-pix/app/utils/proposals-as-array.js
  mon-pix/app/utils/pshuffle.js
  mon-pix/tests/acceptance/challenge-item-qcm_test.js
  mon-pix/tests/acceptance/challenge-item-qcu_test.js
  mon-pix/tests/integration/components/qcm-solution-panel_test.js
  mon-pix/tests/integration/components/qcu-solution-panel_test.js
  mon-pix/tests/unit/components/qcm-proposals_test.js
  mon-pix/tests/unit/components/qcu-proposals_test.js
  mon-pix/tests/unit/utils/labeled-checkboxes_test.js
  mon-pix/tests/unit/utils/pshuffle_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#6193 [BUGFIX] Corrige la media query
  mon-pix/.stylelintrc.json
  mon-pix/app/styles/components/competence-card/_list.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#6195 [TECH] Améliorer les tests sur la vérification d'accès à un assessment.
  api/lib/application/preHandlers/assessment-authorization.js
  api/tests/unit/application/preHandlers/assessment-authorization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6200 [TECH] Script pour récupérer des profil cibles / clés de lectures / certifications complémentaires depuis une base existante et transformer en dump pour les seeds (PIX-8059)
  api/db/seeds/data/certification/certification-candidates-builder.js
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/certification/complementary-certification-course-results-builder.js
  api/db/seeds/data/common/common-builder.js
  api/db/seeds/data/tags-builder.js
  api/db/seeds/seed.js
  api/scripts/data-generation/seeds/dump-target-profile-data-as-seeds.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6146 [FEATURE] Permettre de sélectionner l'envoi multiple pour les campagnes d'évaluation dans pix orga (PIX-7473)
  api/lib/domain/read-models/Prescriber.js
  api/lib/infrastructure/repositories/prescriber-repository.js
  api/lib/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/tests/acceptance/application/prescribers/prescriber-controller_test.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
  api/tests/tooling/domain-builder/factory/build-prescriber.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/create-form.js
  orga/app/models/prescriber.js
  orga/tests/integration/components/campaign/create-form_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6197 [FEATURE] Amélioration de message de validation de suppression d'une participation (PIX-8049)
  orga/app/components/campaign/activity/delete-participation-modal.hbs
  orga/app/components/campaign/activity/delete-participation-modal.js
  orga/tests/integration/components/campaign/activity/delete-participation-modal_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6203 [BUGFIX] L'envoi de message échoue car le nom du channel est utilisé à la place de l'identifiant
  .github/workflows/on-dev-merge.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6204 [BUGFIX] La notification de changement de configuration ne fonctionne plus
  .github/workflows/on-dev-merge.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6205 [BUGFIX] La notification de changement de configuration ne fonctionne toujours pas
  .github/workflows/on-dev-merge.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6178 [TECH] Éviter les imports dupliqués sur Pix App (PIX-8018)
  mon-pix/.eslintrc.js
  mon-pix/app/mixins/progression-tracker.js
  mon-pix/app/services/authentication.js
  mon-pix/app/services/url.js
  mon-pix/tests/acceptance/skill-review_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6208 [TECH] Utilise la version v1 de l'action notify-file-change
  .github/workflows/on-dev-merge.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6199 [BUGFIX] Améliorer le responsive du select dans le formulaire de signalement (PIX-8056)
  mon-pix/app/styles/components/_feedback-panel.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6173 [BUGFIX] Affichage du temps majoré dans la liste des candidats de Pix Certif. (PIX-8008)
  certif/app/helpers/format-percentage.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/integration/components/session-supervising/candidate-in-list_test.js
  certif/tests/unit/helpers/format-percentage_test.js
Labels: :rocket: Ready to Merge, team-certif

#6209 [TECH] Met à jour ember-cli-notifications pour corriger les tests dans le navigateur
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6198 [FEATURE][ADMIN] Permettre la modification de la locale d'un utilisateur (PIX-7358)
  admin/app/components/users/user-overview.hbs
  admin/app/components/users/user-overview.js
  admin/app/services/references.js
  admin/tests/integration/components/users/user-overview_test.js
  api/lib/application/users/index.js
  api/lib/domain/models/UserDetailsForAdmin.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/acceptance/application/users/update-user-details-for-administration_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/domain/models/UserDetailsForAdmin_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#6188 [FEATURE] Ajout d'aléatoire dans le choix des épreuves de l'algorithme flash (PIX-7997).
  api/lib/domain/models/Assessment.js
  api/lib/domain/models/FlashAssessmentAlgorithm.js
  api/lib/domain/models/index.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/lib/domain/services/pick-challenge-service.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/utils/pseudo-random.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-campaign-assessment_test.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/infrastructure/utils/random_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, certif-next-gen

#6172 [TECH] Fournir des outils génériques et documentés orientés "sessions de certification" (PIX-7980)
  api/db/seeds/data/certification/certification-cpf-city-builder.js
  api/db/seeds/data/certification/certification-cpf-country-builder.js
  api/db/seeds/data/common/common-builder.js
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/db/seeds/data/common/tooling/generic.js
  api/db/seeds/data/common/tooling/index.js
  api/db/seeds/data/common/tooling/learning-content.js
  api/db/seeds/data/common/tooling/organization-tooling.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/db/seeds/data/team-certification/data-builder.js
  api/db/seeds/data/team-contenu/data-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6213 [TECH] Tracer les événements wip de pg-boss
  api/worker.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#6182 [FEATURE] Ajout language switcher sur la double mire de la page d'invitation pour rejoindre certif (PIX-7217)
  certif/app/components/auth/login-or-register.hbs
  certif/app/components/auth/login-or-register.js
  certif/app/components/auth/register-form.js
  certif/app/components/language-switcher.hbs
  certif/app/components/language-switcher.js
  certif/app/models/user.js
  certif/app/services/locale.js
  certif/app/services/session.js
  certif/app/styles/components/login-or-register.scss
  certif/tests/acceptance/routes/join_test.js
  certif/tests/integration/components/auth/login-or-register_test.js
  certif/tests/integration/components/language-switcher_test.js
  certif/tests/unit/components/auth/login-or-register_test.js
  certif/tests/unit/components/auth/register-form_test.js
  certif/tests/unit/services/locale_test.js
  certif/tests/unit/services/session_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#6219 [TECH] Fournir des outils génériques et documentés orientés "Profil Utilisateur" (PIX-7960)
  api/db/seeds/data/common/tooling/index.js
  api/db/seeds/data/common/tooling/profile-tooling.js
  api/db/seeds/data/team-contenu/data-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6212 [TECH][Pix Orga] Ne pas modifier la langue de l'utilisateur quand le paramètre lang se trouve dans l'url (PIX-8009)
  certif/app/services/session.js
  certif/tests/unit/services/session_test.js
  orga/app/services/session.js
  orga/tests/unit/services/session_test.js
Labels: :rocket: Ready to Merge, team-acces

#6201 [FEATURE] Modifier les requêtes en lecture pour utiliser la vue sur les prescrits actifs (PIX-7683)
  api/db/database-builder/factory/build-organization-learner.js
  api/db/seeds/data/campaigns-pro-builder.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/lib/infrastructure/repositories/campaign-participant-activity-repository.js
  api/lib/infrastructure/repositories/campaign-participant-repository.js
  api/lib/infrastructure/repositories/campaign-participation-info-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-profile-repository.js
  api/lib/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository.js
  api/lib/infrastructure/repositories/certificate-repository.js
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/lib/infrastructure/repositories/division-repository.js
  api/lib/infrastructure/repositories/group-repository.js
  api/lib/infrastructure/repositories/organization-learner-follow-up/organization-learner-repository.js
  api/lib/infrastructure/repositories/organization-learner-repository.js
  api/lib/infrastructure/repositories/organization-participant-repository.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/repositories/participations-for-campaign-management-repository.js
  api/lib/infrastructure/repositories/participations-for-user-management-repository.js
  api/lib/infrastructure/repositories/prescriber-repository.js
  api/lib/infrastructure/repositories/sco-certification-candidate-repository.js
  api/lib/infrastructure/repositories/sco-organization-participant-repository.js
  api/lib/infrastructure/repositories/sessions/session-for-attendance-sheet-repository.js
  api/lib/infrastructure/repositories/student-repository.js
  api/lib/infrastructure/repositories/sup-organization-participant-repository.js
  api/lib/infrastructure/repositories/user-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6220 [BUGFIX] Corriger l'affichage de la partie "J'ai déjà un compte" sur la double mire Pix Orga (PIX-8086)
  orga/app/components/auth/login-form.hbs
  orga/app/styles/components/login-form.scss
  orga/app/styles/pages/login.scss
  orga/app/templates/login.hbs
Labels: :rocket: Ready to Merge, team-acces

#6224 [FEATURE] Extraire la liste des PCs avec paliers par seuil à convertir en niveau depuis le fichier XLS fourni par le PRO (PIX-7860)
  api/scripts/prod/target-profile-migrations/extract-need-stages-migration.js
  api/scripts/prod/target-profile-migrations/xlsx/1.xlsx
  api/scripts/prod/target-profile-migrations/xlsx/2.xlsx
  api/scripts/prod/target-profile-migrations/xlsx/3.xlsx
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#6228 [TECH] Enrichir les outils "Campagnes" afin de permettre la création à la volée de participants (PIX-7961)
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/db/seeds/data/common/tooling/profile-tooling.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/db/seeds/data/team-contenu/data-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6196 [FEATURE] Traduire le mail des résultats de certification en anglais (PIX-6687).
  api/lib/application/sessions/session-controller.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/services/session-publication-service.js
  api/lib/domain/usecases/publish-session.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/services/session-publication-service_test.js
  api/tests/unit/domain/usecases/publish-session_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#6230 [TECH] Pouvoir switcher entre vieilles et nouvelles seeds grâce à une variable d'environnement (PIX-8104)
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6222 [TECH] [Pix Orga] Aligner la double mire sur la maquette et nos standards (PIX-8073)
  orga/app/components/auth/register-form.hbs
  orga/app/styles/components/login-or-register.scss
  orga/app/styles/components/register-form.scss
  orga/tests/acceptance/join_test.js
  orga/tests/integration/components/auth/login-or-register_test.js
  orga/tests/integration/components/auth/register-form_test.js
Labels: :rocket: Ready to Merge, team-acces

#6236 [BUGFIX] Affichage de la bonne réponse dans le panneau de correction (PIX-8110)
  mon-pix/app/components/qcu-solution-panel.hbs
  mon-pix/app/utils/labeled-checkboxes.js
  mon-pix/tests/unit/components/qcm-proposals_test.js
  mon-pix/tests/unit/components/qcu-proposals_test.js
  mon-pix/tests/unit/utils/labeled-checkboxes_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#6221 [FEATURE] Traduire la modale de confirmation de finalisation de session sur Pix Certif (PIX-8012).
  certif/app/components/session-finalization/completed-reports-information-step.hbs
  certif/app/components/session-finalization/finalization-confirmation-modal.hbs
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/integration/components/session-finalization/finalization-confirmation-modal_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#6232 [FEATURE] Ajouter un sélecteur de langue sur la page connexion de Pix Certif domaine international (PIX-5955)
  certif/app/controllers/login.js
  certif/app/styles/components/login-form.scss
  certif/app/styles/pages/login.scss
  certif/app/templates/login.hbs
  certif/tests/acceptance/login_test.js
Labels: :rocket: Ready to Merge, team-acces

#6240 [TECH] Spécifie la version minimale de node 16 sur l'API pour que cela fonctionne
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6211 [FEATURE] Renvoyer le détail de validation de QRCOM-dep depuis l'API (PIX-7919)
  api/lib/domain/models/Correction.js
  api/lib/domain/models/CorrectionBlockQROCMDep.js
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/lib/domain/usecases/get-correction-for-answer.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/unit/domain/models/CorrectionBlockQROCMDep_test.js
  api/tests/unit/domain/usecases/get-correction-for-answer_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6202 [FEATURE] Améliorer le style du bloc de réponse des épreuves Pix-App (PIX-7717)
  mon-pix/app/components/qcm-proposals.hbs
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_qcm-proposals.scss
  mon-pix/app/styles/components/_qcu-proposals.scss
  mon-pix/app/styles/components/_qrocm-proposals.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/tests/acceptance/challenge-item_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6247 [TECH] Supprime la dépendance ember-template-lint a la racine
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#5661 [FEATURE] ETQ Admin Support, télécharger les attestations de certification d'une session (PIX-7132)
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/tests/acceptance/session_test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/certificate/get-certification-attestations-for-session.js
  api/lib/domain/usecases/index.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/get-certification-attestation-for-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6241 [BUGFIX] Corrige le traitement des taches Pole Emploi (PIX-8079)
  api/lib/infrastructure/jobs/campaign-result/SendSharedParticipationResultsToPoleEmploiJob.js
  api/tests/integration/infrastructure/jobs/campaign-result/SendSharedParticipationResultsToPoleEmploiJob_test.js
  api/worker.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6223 [TECH] Monter Pix UI en v34.1.0 sur Pix Certif (PIX-7971).
  certif/app/components/add-student-list.hbs
  certif/app/components/add-student-list.js
  certif/app/components/auth/register-form.hbs
  certif/app/components/auth/register-form.js
  certif/app/components/certif-checkbox.hbs
  certif/app/components/session-finalization/complementary-information-step.hbs
  certif/app/components/session-finalization/completed-reports-information-step.hbs
  certif/app/components/session-finalization/completed-reports-information-step.js
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/styles/components/session-finalization/complementary-information-step.scss
  certif/app/styles/components/session-finalization/reports-information-step.scss
  certif/app/styles/globals/forms.scss
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/routes/join_test.js
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/integration/components/add-student-list_test.js
  certif/tests/integration/components/certif-checkbox_test.js
  certif/tests/integration/components/session-finalization/completed-reports-information-step_test.js
  certif/tests/unit/components/add-student-list_test.js
  certif/tests/unit/components/auth/register-form_test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#6257 [TECH] Active l'option staticHelpers d'embroider sur mon-pix
  mon-pix/app/components/form-textfield-date.hbs
  mon-pix/ember-cli-build.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6218 [FEATURE] Elaboration d'un simulateur de scénarios déterministes pour le nouvel algo (PIX-8037).
  api/lib/application/scenarios-simulator/index.js
  api/lib/application/scenarios-simulator/scenario-simulator-controller.js
  api/lib/domain/models/AssessmentSimulator.js
  api/lib/domain/models/FlashAssessmentAlgorithm.js
  api/lib/domain/models/index.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/simulate-flash-deterministic-assessment-scenario.js
  api/lib/infrastructure/serializers/jsonapi/scenario-simulator-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/scenario-simulator/scenario-simulator-controller_test.js
  api/tests/integration/application/scenarios-simulator/scenario-simulator-controller_test.js
  api/tests/unit/domain/models/AssessmentSimulator_test.js
  api/tests/unit/domain/usecases/simulate-flash-deterministic-assessment-scenario_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/scenario-simulator-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6261 [FEATURE] Ajouter la traduction anglaise du mail d'invitation à Pix Certif (PIX-8141).
  api/translations/en.json
Labels: :rocket: Ready to Merge, team-certif

#6258 [FEATURE] Amélioration du design de l'espace surveillant sur pix Certif (PIX-8125).
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/candidate-in-list.js
  certif/app/components/session-supervising/header.js
  certif/app/styles/components/session-supervising/candidate-in-list.scss
  certif/app/styles/components/session-supervising/header.scss
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#6256 [FEATURE] Génération d'un scénario aléatoire (PIX-8121).
  api/lib/application/scenarios-simulator/index.js
  api/lib/application/scenarios-simulator/scenario-simulator-controller.js
  api/lib/infrastructure/utils/random.js
  api/tests/acceptance/application/scenario-simulator/scenario-simulator-controller_test.js
  api/tests/integration/application/scenarios-simulator/scenario-simulator-controller_test.js
  api/tests/unit/infrastructure/utils/pseudo-random_test.js
  api/tests/unit/infrastructure/utils/random_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6259 [FEATURE] Simulation d'un scénario à partir d'une capacité (PIX-8122).
  api/lib/application/scenarios-simulator/index.js
  api/lib/application/scenarios-simulator/scenario-simulator-controller.js
  api/lib/domain/models/AssessmentSimulator.js
  api/lib/domain/services/pick-answer-service.js
  api/lib/domain/usecases/simulate-flash-deterministic-assessment-scenario.js
  api/lib/infrastructure/serializers/jsonapi/scenario-simulator-serializer.js
  api/lib/infrastructure/utils/random.js
  api/tests/acceptance/application/scenario-simulator/scenario-simulator-controller_test.js
  api/tests/integration/application/scenarios-simulator/scenario-simulator-controller_test.js
  api/tests/unit/domain/models/AssessmentSimulator_test.js
  api/tests/unit/domain/usecases/simulate-flash-deterministic-assessment-scenario_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/scenario-simulator-batch-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/scenario-simulator-serializer_test.js
  api/tests/unit/infrastructure/utils/random_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, certif-next-gen

#6226 [TECH] Améliorer les tests sur me "notifier à pole emploi" suite au passage à ESM (PIX-8065)
  api/lib/domain/events/handle-pole-emploi-participation-finished.js
  api/lib/domain/events/handle-pole-emploi-participation-started.js
  api/lib/domain/events/index.js
  api/lib/domain/usecases/send-shared-participation-results-to-pole-emploi.js
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-finished_test.js
  api/tests/unit/domain/events/handle-pole-emploi-participation-started_test.js
  api/tests/unit/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/disabled-pole-emploi-notifier_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
Labels: :rocket: Ready to Merge, team-acces, team-prescription

#6269 [FEATURE] Ajout d'une condition d’arrêt au scénario
  api/lib/application/scenarios-simulator/index.js
  api/lib/application/scenarios-simulator/scenario-simulator-controller.js
  api/lib/domain/models/AssessmentSimulator.js
  api/lib/domain/usecases/simulate-flash-deterministic-assessment-scenario.js
  api/tests/acceptance/application/scenario-simulator/scenario-simulator-controller_test.js
  api/tests/integration/application/scenarios-simulator/scenario-simulator-controller_test.js
  api/tests/unit/domain/models/AssessmentSimulator_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, certif-next-gen

#6262 [FEATURE] Améliorer le style visuel de la recommendation des contenus formatifs (PIX-7667).
  mon-pix/app/components/training/card.hbs
  mon-pix/app/styles/components/_training-card.scss
  mon-pix/app/styles/pages/_skill-review.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6271 [FEATURE] Suppression du filtre du status des challenges pour les simulateurs (PIX-8173).
  api/lib/domain/usecases/simulate-flash-deterministic-assessment-scenario.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/domain/usecases/simulate-flash-deterministic-assessment-scenario_test.js
  api/tests/unit/infrastructure/datasources/learning-content/challenge-datasource_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, certif-next-gen

#6235 [TECH] Persister les données créées par le tooling des seeds à chaque fin d'appel (PIX-8107)
  api/db/seeds/data/common/common-builder.js
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/db/seeds/data/common/tooling/certification-center-tooling.js
  api/db/seeds/data/common/tooling/organization-tooling.js
  api/db/seeds/data/common/tooling/profile-tooling.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/db/seeds/data/common/tooling/target-profile-tooling.js
  api/db/seeds/data/common/tooling/training-tooling.js
  api/db/seeds/data/team-certification/data-builder.js
  api/db/seeds/data/team-contenu/data-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6267 [BUGFIX] Remettre la génération de villes et de pays dans les seeds (PIX-8162)
  api/db/seeds/data/certification/certification-cpf-city-builder.js
  api/db/seeds/data/certification/certification-cpf-country-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#6275 [FEATURE] Remplacement de AnswerStatus par la réponse dans les simulateurs (PIX-8179).
  api/lib/domain/services/pick-answer-service.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, certif-next-gen

#6274 [FEATURE] Indiquer la réussite/l'échec d'une épreuve Pix1D dans une modale
  pix1d/app/pods/components/answer/template.hbs
  pix1d/app/pods/components/challenge/challenge-actions/template.hbs
  pix1d/app/pods/components/challenge/item/component.js
  pix1d/app/pods/components/challenge/item/template.hbs
  pix1d/app/styles/app.scss
  pix1d/app/styles/components/answer.scss
  pix1d/app/styles/components/challenge-item.scss
  pix1d/mirage/config.js
  pix1d/package-lock.json
  pix1d/package.json
  pix1d/tests/acceptance/display-answer-modal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6083 [TECH] Migre pix1d sur embroider (PIX-7764)
  pix1d/ember-cli-build.js
  pix1d/package-lock.json
  pix1d/package.json
Labels: :rocket: Ready to Merge, cross-team, 🎒👧🏽👦🏾 Pix1D

#6279 [TECH] Mise à jour de ember-dayjs
  admin/ember-cli-build.js
  admin/package-lock.json
  admin/package.json
  certif/ember-cli-build.js
  certif/package-lock.json
  certif/package.json
  mon-pix/ember-cli-build.js
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/ember-cli-build.js
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6282 [TECH] Supprime l'orb slack de la configuration de circleci
  .circleci/config.yml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6288 [BUGFIX] Ajouter le i18n à la méthode publishInBatch (PIX-8187).
  admin/package-lock.json
  admin/package.json
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/publish-sessions-in-batch.js
  api/package-lock.json
  api/package.json
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/publish-sessions-in-batch_test.js
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#6145 [FEATURE] Suppression de l'heure de fin de session de la feuille d'émargement et import de candidat (PIX-7836)
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/infrastructure/files/attendance-sheet/attendance-sheet-placeholders.js
  api/lib/infrastructure/files/attendance-sheet/non_sco_attendance_sheet_template.ods
  api/lib/infrastructure/files/attendance-sheet/sco_attendance_sheet_template.ods
  api/lib/infrastructure/files/candidates-import/1.5/candidates_import_template.ods
  api/lib/infrastructure/files/candidates-import/SessionData.js
  api/lib/infrastructure/files/candidates-import/candidates-import-placeholders.js
  api/lib/infrastructure/files/candidates-import/candidates-import-transformation-structures.js
  api/lib/infrastructure/utils/ods/write-ods-utils.js
  api/tests/integration/domain/usecases/get-attendance-sheet/non_sco_attendance_sheet_template_target.ods
  api/tests/integration/domain/usecases/get-attendance-sheet/sco_attendance_sheet_template_target.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-sco.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-all-complementary-certifications-sco.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-billing-columns-complementary.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-billing-columns.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-one-complementary-certification-sco.ods
  api/tests/unit/domain/usecases/get-attendance-sheet_test.js
  api/tests/unit/domain/usecases/get-session-for-supervising_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6263 [FEATURE] Reporter le texte des pages SCO de Pix Certif dans des clés de traduction (PIX-8023).
  certif/app/components/add-student-list.hbs
  certif/app/components/certification-candidates-sco.hbs
  certif/app/controllers/authenticated/sessions/add-student.js
  certif/app/services/url.js
  certif/app/templates/authenticated.hbs
  certif/app/templates/authenticated/restricted-access.hbs
  certif/app/templates/authenticated/sessions/add-student.hbs
  certif/app/templates/authenticated/sessions/finalize.hbs
  certif/tests/acceptance/session-add-students_test.js
  certif/tests/unit/services/url_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#6264 [FEATURE] Traduction d'éléments encore non traduits sur Pix Certif (PIX-8027).
  certif/app/components/certification-candidate-in-staging-item.hbs
  certif/app/components/certification-candidate-in-staging-item.js
  certif/app/components/session-finalization/examiner-global-comment-step.hbs
  certif/app/components/session-finalization/examiner-global-comment-step.js
  certif/app/components/session-finalization/formbuilder-link-step.hbs
  certif/app/components/session-finalization/formbuilder-link-step.js
  certif/app/components/session-summary-list.js
  certif/app/controllers/authenticated/sessions/details/parameters.js
  certif/app/styles/app.scss
  certif/app/styles/components/session-finalization/examiner-global-comment-step.scss
  certif/app/styles/components/session-finalization/formbuilder-link-step.scss
  certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/app/templates/logout.hbs
  certif/config/environment.js
  certif/tests/integration/components/certification-candidate-in-staging-item_test.js
  certif/tests/integration/components/formbuilder-link-step_test.js
  certif/tests/integration/components/session-finalization/examiner-global-comment-step_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#6287 [FEATURE] Ajout d'une capacité initiale dans les simulateurs d'évaluation (PIX-8159).
  api/lib/application/scenarios-simulator/index.js
  api/lib/application/scenarios-simulator/scenario-simulator-controller.js
  api/lib/domain/models/AssessmentSimulator.js
  api/lib/domain/usecases/simulate-flash-deterministic-assessment-scenario.js
  api/tests/integration/application/scenarios-simulator/scenario-simulator-controller_test.js
  api/tests/unit/domain/models/AssessmentSimulator_test.js
  api/tests/unit/domain/usecases/simulate-flash-deterministic-assessment-scenario_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, certif-next-gen

#6290 [TECH] Mise à jour de ember-fontawesome en version 1.0.0
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team, dependencies

#6276 [FEATURE] Arrêter la mission au 1er challenge échoué ou passé (PIX-8181)
  api/lib/domain/usecases/get-next-challenge-for-pix1d.js
  api/tests/unit/domain/usecases/get-next-challenge-for-pix1d_test.js
  pix1d/app/pods/components/answer/template.hbs
  pix1d/app/pods/components/challenge/challenge-actions/template.hbs
  pix1d/app/pods/components/challenge/challenge-item-auto-reply/template.hbs
  pix1d/app/pods/components/challenge/challenge-item-generic/component.js
  pix1d/app/pods/components/challenge/item/template.hbs
  pix1d/app/styles/app.scss
  pix1d/app/styles/components/challenge-actions.scss
  pix1d/app/styles/globals/_fonts.scss
  pix1d/public/fonts/Nunito/Nunito-SemiBold.ttf
  pix1d/tests/acceptance/display-answer-modal_test.js
  pix1d/tests/acceptance/display-challenge_test.js
  pix1d/tests/integration/components/answer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6296 [TECH] Supprime les dépendances chai-dom et eslint-plugin-mocha de mon-pix
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies
