Repository 1024pix/pix, pull requests merged in 2023-01, with the labels that each got.

#5435 [BUGFIX] Corriger l'erreur d'année sur un test CPF (pix-6704)
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/send-email_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#5396 [TECH] Test de reproduction du bug des modales avec input suite montée en version Pix UI (PIX-6492)
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/session-finalization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5426 [BUGFIX] Reprendre le design des tutoriels "Pour en apprendre davantage" sur Pix-App (PIX-6584)
  mon-pix/app/styles/components/_learning-more-tutorial-panel.scss
  mon-pix/app/styles/components/_tutorial-panel.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5097 [TECH] Ne pas attendre la connexion PoleEmploi plus longtemps que ce que Scalingo permet
  api/lib/config.js
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/lib/infrastructure/http/http-agent.js
  api/sample.env
  api/tests/acceptance/application/authentication/oidc/token-route-post_test.js
  api/tests/unit/infrastructure/http/http-agent_test.js
Labels: :rocket: Ready to Merge, cross-team

#5166 [TECH] Supprimer la route inutilisée api/users/id/membership (PIX-815).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/lib/domain/usecases/get-user-with-memberships.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-with-activity-serializer.js
  api/tests/acceptance/application/security-pre-handlers_test.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/acceptance/application/users/users-controller-get-memberships_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/usecases/get-user-with-memberships_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-activity-serializer_test.js
  orga/mirage/config.js
  orga/mirage/serializers/user.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5418 [FEATURE] Gestion des créations et groupage par session (PIX-6659)
  api/lib/domain/services/certification-sessions-service.js
  api/lib/domain/usecases/create-sessions.js
  api/tests/unit/domain/services/certification-sessions-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5420 [FEATURE] Identifier l'utilisateur admin qui a anonymisé un utilisateur (PIX-4214)
  api/db/database-builder/factory/build-user.js
  api/db/migrations/20221228135724_add-hasBeenAnonymised-and-hasBeenAnonymisedBy-to-users-table.js
  api/lib/domain/models/User.js
  api/lib/domain/models/UserDetailsForAdmin.js
  api/lib/domain/usecases/anonymize-user.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-anonymized-details-for-admin-serializer.js
  api/tests/acceptance/application/users/users-route_test.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-user-details-for-admin.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/anonymize-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-anonymized-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#5419 [FEATURE] Afficher le prénom / nom du participant dans sa page de détail (PIX-6140).
  api/lib/application/organization-learners/index.js
  api/lib/application/organization-learners/organization-learner-controller.js
  api/lib/domain/usecases/get-organization-learner.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/organization-learner-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-learner-serializer.js
  api/tests/acceptance/application/organization-learners/organization-learner-controller_test.js
  api/tests/integration/domain/usecases/get-organization-learner_test.js
  api/tests/unit/application/organization-learners/index_test.js
  api/tests/unit/application/organization-learners/organization-learner-controller_test.js
  api/tests/unit/domain/usecases/get-organization-learner_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-learner-serializer_test.js
  orga/app/models/organization-learner.js
  orga/app/routes/authenticated/organization-participants/organization-participant.js
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/organization-participants/organization-participant.scss
  orga/app/templates/authenticated/organization-participants/organization-participant.hbs
  orga/tests/unit/routes/authenticated/organization-participants/organization-participant/activity_test.js
  orga/tests/unit/routes/authenticated/organization-participants/organization-participant_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5427 [FEATURE] Changer le select de la méthode de connexion pour un multi select orga sco (PIX-6626)
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/infrastructure/repositories/sco-organization-participant-repository.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/sco-organization-participant-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  high-level-tests/e2e/cypress/support/step_definitions/student.js
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/controllers/authenticated/sco-organization-participants/list.js
  orga/app/routes/authenticated/sco-organization-participants/list.js
  orga/app/templates/authenticated/sco-organization-participants/list.hbs
  orga/mirage/handlers/find-filtered-paginated-sco-organization-participants.js
  orga/tests/acceptance/sco-organization-participant-list_test.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/unit/controllers/authenticated/sco-organization-participants/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5311 [TECH] Ajouter les catégories et sous-catégories de signalements en BDD (PIX-6510)
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-issue-report.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5434 [BUGFIX] Corriger le design des nouveaux boutons du Design System sur Pix-App (PIX-6576)
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/styles/components/_checkpoint.scss
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5443 [CLEANUP] Tri les usecases par ordre alphabétique
  api/lib/domain/usecases/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5402 [BUGFIX] Améliorer la gestion des erreurs lors de l'envoi d'une invitation à rejoindre une organisation (PIX-6420)
  admin/app/services/error-response-handler.js
  admin/tests/acceptance/organization-invitations-management_test.js
  admin/tests/unit/controllers/authenticated/organizations/get/invitations_test.js
  admin/tests/unit/services/error-response-handler_test.js
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/models/EmailingAttempt.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/infrastructure/mail-check.js
  api/lib/infrastructure/mailers/mailer.js
  api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/models/EmailingAttempt_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5441 [FEATURE] Calculer la capacité minimum pour une probabilité donnée (PIX-6713)
  api/lib/config.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/sample.env
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/domain/models/Challenge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5453 [TECH] Correction d'un test flaky sur l'api
  api/tests/integration/infrastructure/repositories/user-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5454 [FEATURE] Calculer le score Pix total pour des questions flash auxquelles l'utilisateur a répondu (PIX-6717).
  api/lib/domain/services/algorithm-methods/flash.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5455 [FEATURE] Afficher le prénom / nom de l'étudiant dans sa page de détail (PIX-6700)
  orga/app/routes/authenticated/sup-organization-participants/sup-organization-participant.js
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/sup-organization-participants/sup-organization-participant.scss
  orga/app/templates/authenticated/sup-organization-participants/sup-organization-participant.hbs
  orga/tests/unit/routes/authenticated/sup-organization-participant/sup-organization-participant_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5459 [TECH] Supprimer une notification slack non utilisée.
  .circleci/config.yml
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team, no-review-app

#5456 [FEATURE] Rendre l'étudiant cliquable pour accéder a sa page de détail (PIX-6702)
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/controllers/authenticated/sup-organization-participants/list.js
  orga/app/templates/authenticated/sup-organization-participants/list.hbs
  orga/tests/integration/components/sup-organization-participant/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5439 [FEATURE] Afficher le nom du membre qui a fait l'action d'anonymisation sur la page de détail d'un utilisateur dans Pix Admin (PIX-4221).
  admin/app/components/users/user-overview.hbs
  admin/app/components/users/user-overview.js
  admin/app/models/user.js
  admin/app/styles/components/users/user-detail-personal-information-section.scss
  admin/tests/integration/components/users/user-overview_test.js
  api/lib/domain/models/UserDetailsForAdmin.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-anonymized-details-for-admin-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/acceptance/application/users/users-controller-get-user-details-for-admin_test.js
  api/tests/acceptance/application/users/users-route_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/domain/models/UserDetailsForAdmin_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-anonymized-details-for-admin-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#5397 [TECH] Déplacer la logique métier des scorecards dans l'API (PIX-6629)
  api/lib/domain/models/Scorecard.js
  api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
  api/lib/infrastructure/serializers/jsonapi/scorecard-serializer.js
  api/tests/acceptance/application/scorecards/scorecard-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-user-profile-for-admin_test.js
  api/tests/acceptance/application/users/users-controller-get-user-profile_test.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/tooling/domain-builder/factory/build-user-scorecard.js
  api/tests/unit/domain/models/Scorecard_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/scorecard-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5432 [TECH] Simplification du modèle CertifiableBadgeAcquisition (PIX-6742)
  api/lib/domain/models/CertifiableBadgeAcquisition.js
  api/lib/domain/models/ComplementaryCertificationBadge.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/usecases/get-certification-candidate-subscription.js
  api/lib/domain/usecases/get-user-certification-eligibility.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/lib/infrastructure/repositories/badge-for-calculation-repository.js
  api/lib/infrastructure/repositories/certifiable-badge-acquisition-repository.js
  api/tests/integration/domain/services/certification-badges-service_test.js
  api/tests/integration/infrastructure/repositories/badge-for-calculation-repository_test.js
  api/tests/integration/infrastructure/repositories/certifiable-badge-acquisition-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certifiable-badge-acquisition.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-badge.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/services/certification-badges-service_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/domain/usecases/get-certification-candidate-subscription_test.js
  api/tests/unit/domain/usecases/get-user-certification-eligibility_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5440 [TECH] Créer un composant information pour extraire les informations avec un titre et une donnée (PIX-6145).
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/profile/header.hbs
  orga/app/components/ui/information-wrapper.hbs
  orga/app/components/ui/information.hbs
  orga/app/styles/components/ui/index.scss
  orga/app/styles/components/ui/information.scss
  orga/tests/integration/components/ui/information-wrapper_test.js
  orga/tests/integration/components/ui/information_test.js
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5460 [BUGFIX] Corriger le test en erreur sur get user shared profile (PIX-6708)
  api/lib/domain/usecases/get-user-profile-shared-for-campaign.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
  api/tests/acceptance/application/users/users-get-shared-profile-for-campaign_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#5462 [FEATURE] Afficher le prénom / nom de l'élève dans sa page de détail (PIX-6699)
  orga/app/routes/authenticated/sco-organization-participants/sco-organization-participant.js
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/sco-organization-participants/sco-organization-participant.scss
  orga/app/templates/authenticated/sco-organization-participants/sco-organization-participant.hbs
  orga/tests/unit/routes/authenticated/sco-organization-participants/sco-organization-participant/activity_test.js
  orga/tests/unit/routes/authenticated/sco-organization-participants/sco-organization-participant_test.js
  orga/tests/unit/routes/authenticated/sup-organization-participants/sup-organization-participant/activity_test.js
  orga/tests/unit/routes/authenticated/sup-organization-participants/sup-organization-participant_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5458 [FEATURE] Flash : Calculer le nombre de Pix obtenus par inférence (PIX-6719)
  api/lib/domain/services/algorithm-methods/flash.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5465 [FEATURE] Afficher le score Pix calculé à la fin de la campagne flash (PIX-6720)
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign-participation-result.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5448 [FEATURE] Paramétrer la date de mise à jour de la politique de confidentialité avec une variable d'environnement (PIX-6597)
  api/lib/config.js
  api/lib/domain/models/User.js
  api/lib/domain/read-models/UserWithActivity.js
  api/lib/domain/usecases/get-current-user.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-with-activity-serializer.js
  api/sample.env
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/get-current-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-activity-serializer_test.js
  mon-pix/app/components/data-protection-policy-information-banner.js
  mon-pix/app/models/user.js
  mon-pix/mirage/routes/users/index.js
  mon-pix/tests/acceptance/user-dashboard_test.js
  mon-pix/tests/integration/components/data-protection-policy-information-banner_test.js
  mon-pix/tests/unit/models/user_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5445 [TECH] Linter les titres de PR
  .github/workflows/check-pr-title.yaml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, no-review-app

#5450 [TECH] Met à jour les packages vulnérable de l'API
  api/package-lock.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5390 [TECH] Supprimer le template de PR en doublon
  docs/pull_request_template.md
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#5428 [TECH] Supprimer les règles .editorconfig obsolètes
  .editorconfig
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5457 [FEATURE] Changement de la date de fin de passage des sessions dans le SCO (PIX-6731).
  certif/app/templates/authenticated.hbs
  certif/tests/acceptance/authenticated_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5464 [FEATURE] Rendre l'élève cliquable pour accéder a sa page de détail (PIX-6701)
  orga/app/components/dropdown/icon-trigger.js
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/app/components/sup-organization-participant/list.js
  orga/app/controllers/authenticated/sco-organization-participants/list.js
  orga/app/templates/authenticated/sco-organization-participants/list.hbs
  orga/tests/integration/components/sco-organization-participant/list_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5470 [TECH] Mise à jour du projectId cypress
  high-level-tests/e2e/cypress.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5417 [TECH] Séparer les phases de test et de lint dans la CI
  .circleci/config.yml
  api/db/migrations/20220922141959_modify-messages-in-complementary-certification-badges.js
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5468 [TECH] Réparer l'usage du CLI des tests de l'algo
  high-level-tests/test-algo/algo.js
  high-level-tests/test-algo/index.js
  high-level-tests/test-algo/tests/algo_test.js
  high-level-tests/test-algo/tests/tests.sh
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5408 [FEATURE] Créer des contenus formatifs sur Pix Admin (PIX-6320)
  admin/app/adapters/training.js
  admin/app/components/trainings/create-training-form.hbs
  admin/app/components/trainings/create-training-form.js
  admin/app/controllers/authenticated/trainings/list.js
  admin/app/controllers/authenticated/trainings/new.js
  admin/app/models/target-profile.js
  admin/app/models/training.js
  admin/app/router.js
  admin/app/routes/authenticated/trainings/new.js
  admin/app/services/access-control.js
  admin/app/styles/app.scss
  admin/app/styles/components/trainings/create-training-form.scss
  admin/app/templates/authenticated/trainings/list.hbs
  admin/app/templates/authenticated/trainings/new.hbs
  admin/app/transforms/interval.js
  admin/app/utils/format-select-options.js
  admin/mirage/config.js
  admin/mirage/handlers/trainings.js
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/integration/components/trainings/create-training-form_test.js
  admin/tests/unit/components/trainings/create-training-form_test.js
  admin/tests/unit/controllers/authenticated/trainings/new_test.js
  admin/tests/unit/routes/authenticated/trainings/new_test.js
  admin/tests/unit/services/access-control-test.js
  admin/tests/unit/transforms/interval_test.js
  admin/tests/unit/utils/format-select-options_test.js
  api/lib/application/trainings/index.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/unit/application/trainings/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5472 [FEATURE] Créer une route pour l'appel au simulateur (PIX-6762)
  api/lib/application/scoring-simulator/index.js
  api/lib/application/scoring-simulator/scoring-simulator-controller.js
  api/lib/routes.js
  api/tests/acceptance/application/scoring-simulator/scoring-simulator-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5449 [TECH] Suppression de tests d'acceptance sur la pérennité des comptes dans l'API (PIX-1544).
  api/tests/acceptance/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/unit/domain/services/user-reconciliation-service_test.js
  api/tests/unit/domain/usecases/delete-certification-issue-report_test.js
  api/tests/unit/domain/usecases/generate-username_test.js
  api/tests/unit/domain/usecases/reconcile-sco-organization-learner-manually_test.js
  api/tests/unit/domain/usecases/update-organization-learner-dependent-user-password_test.js
Labels: :rocket: Ready to Merge, team-acces

#5466 [BUGFIX] L'utilisateur est bloqué définitivement alors qu'il ne devrait pas (PIX-6749)
  api/lib/application/usecases/checkIfUserIsBlocked.js
  api/lib/domain/models/UserLogin.js
  api/lib/domain/services/authentication/pix-authentication-service.js
  api/lib/domain/usecases/unblock-user-account.js
  api/tests/unit/domain/models/UserLogin_test.js
  api/tests/unit/domain/services/authentication/pix-authentication-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5391 [FEATURE] Permettre à un admin de Pix Orga de renvoyer une invitation (PIX-463)
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/domain/usecases/create-organization-invitation-by-admin.js
  api/lib/domain/usecases/create-organization-invitations.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/resend-organization-invitation.js
  api/scripts/send-invitations-to-sco-organizations.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/domain/services/organization-invitation-service_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/domain/usecases/create-organization-invitation-by-admin_test.js
  api/tests/unit/domain/usecases/create-organization-invitations_test.js
  api/tests/unit/domain/usecases/resend-organization-invitation_test.js
  orga/app/adapters/organization-invitation.js
  orga/app/components/team/invitations-list-item.hbs
  orga/app/components/team/invitations-list-item.js
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/invitations-list.js
  orga/app/styles/pages/authenticated/team/invitations-list.scss
  orga/config/environment.js
  orga/config/icons.js
  orga/tests/integration/components/team/invitations-list-item_test.js
  orga/tests/integration/components/team/invitations-list_test.js
  orga/tests/unit/adapters/organization-invitation_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5479 [TECH] Supprimer la dépendance `@1024pix/ember-testing-library` qui se trouve à la racine (PIX-6778).
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, no-review-app

#5471 [TECH] Suppression du script de création des contenus formatif (PIX-6759)
  api/scripts/create-trainings.js
  api/tests/unit/scripts/create-trainings_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5393 [TECH] Trier les traductions dans l'API
  api/.eslintrc.yaml
  api/.prettierignore
  api/package.json
  api/translations/en.json
  api/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5480 [BUGFIX][ADMIN] Laisser afficher la mention archivée lors de la mise à jour des tags d'une organisation (PIX-6445)
  admin/app/models/organization.js
  admin/tests/acceptance/authenticated/organizations/information-management_test.js
  admin/tests/unit/models/organization_test.js
  api/lib/infrastructure/repositories/organization-for-admin-repository.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5474 [FEATURE] Garantir qu'on ne compte pas un acquis plusieurs fois dans le score Pix direct (PIX-6744)
  api/lib/domain/services/algorithm-methods/flash.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5476 [FEATURE] Améliorer la validation de données pour la route de création des contenus formatifs (PIX-6753)
  api/lib/application/trainings/index.js
  api/tests/unit/application/trainings/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5482 [BUGFIX] Aligner les boutons dans la modale de suppression d'un membre sur Pix Orga (PIX-6734).
  orga/app/components/team/remove-member-modal.hbs
  orga/app/styles/components/team/remove-member-modal.scss
Labels: :rocket: Ready to Merge, team-acces

#5488 [FEATURE] Mettre à jour les textes de la page d'accueil d'une campagne pour convenir à tous nos publics (PIX-6786)
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/templates/campaigns/campaign-landing-page.hbs
  mon-pix/tests/integration/components/campaign-start-block_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK

#5485 [FEATURE][ADMIN] Après création d'une organisation, rediriger l'utilisateur vers l'onglet listant les tags (PIX-6738)
  admin/app/components/organizations/creation-form.hbs
  admin/app/controllers/authenticated/organizations/new.js
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/organizations/create-organization_test.js
  admin/tests/integration/components/organizations/creation-form_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5483 [BUGFIX] Redonner un style de puces aux listes des modales "Réponses et tutos" (PIX-6783)
  mon-pix/app/styles/components/_comparison-window.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5489 [BUGIFX][ADMIN] Améliorer la gestion des erreurs lors de l'envoi d'une invitation à rejoindre un centre de certification (PIX-6779)
  api/lib/domain/usecases/create-or-update-certification-center-invitation-for-admin.js
  api/tests/integration/domain/usecases/create-or-update-certification-center-invitation-for-admin_test.js
Labels: :rocket: Ready to Merge, team-acces

#5495 [FEATURE] Créer une route pour l'appel au simulateur de l'algorithme Flash (PIX-6765).
  api/lib/application/scoring-simulator/index.js
  api/lib/application/scoring-simulator/scoring-simulator-controller.js
  api/tests/acceptance/application/scoring-simulator/scoring-simulator-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5433 [FEATURE] Informer l'utilisateur que son compte est bloqué de manière uniforme dans Pix Orga, Pix Certif et Pix Admin (PIX-6435)
  admin/app/components/login-form.js
  admin/app/routes/application.js
  admin/app/services/url.js
  admin/config/ember-intl.js
  admin/config/environment.js
  admin/package-lock.json
  admin/package.json
  admin/tests/helpers/setup-intl-rendering.js
  admin/tests/helpers/setup-intl.js
  admin/tests/integration/components/login-form_test.js
  admin/translations/en.json
  admin/translations/fr.json
  certif/app/components/auth/toggable-login-form.js
  certif/app/components/login-form.js
  certif/app/services/url.js
  certif/config/environment.js
  certif/tests/integration/components/login-form_test.js
  certif/tests/unit/components/auth/toggable-login-form_test.js
  certif/translations/en.json
  certif/translations/fr.json
  docs/Ember.md
  mon-pix/app/components/routes/campaigns/join-sco-information-modal.js
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/components/signin-form.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/config/environment.js
  mon-pix/mirage/routes/authentication/index.js
  mon-pix/mirage/routes/authentication/post-authentications.js
  mon-pix/tests/acceptance/update-expired-password_test.js
  mon-pix/tests/integration/components/signin-form_test.js
  mon-pix/tests/integration/components/signup-form_test.js
  mon-pix/tests/integration/components/update-expired-password-form_test.js
  mon-pix/tests/unit/components/signin-form_test.js
  mon-pix/tests/unit/components/update-expired-password-form_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
  orga/app/components/auth/login-form.js
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/header/archived-banner.js
  orga/app/components/campaign/settings/view.js
  orga/app/components/campaign/update-form.js
  orga/app/components/sup-organization-participant/edit-student-number-modal.js
  orga/app/components/team/invitations-list.js
  orga/app/controllers/authenticated/campaigns/new.js
  orga/app/services/error-messages.js
  orga/app/services/url.js
  orga/config/environment.js
  orga/tests/acceptance/campaign-parameters_test.js
  orga/tests/acceptance/join_test.js
  orga/tests/integration/components/auth/login-form_test.js
  orga/tests/integration/components/campaign/create-form_test.js
  orga/tests/integration/components/team/invitations-list_test.js
  orga/tests/unit/services/error-messages_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5494 [FEATURE][ADMIN] Afficher un message d'information lorsqu'une organisation n'a pas de tags (PIX-6739)
  admin/app/components/organizations/information-section-view.hbs
  admin/app/styles/components/organization-information-section.scss
  admin/tests/integration/components/organizations/information-section-view_test.js
Labels: :rocket: Ready to Merge, team-acces

#5467 [FEATURE] Changer le texte du lien vers le site vitrine depuis App (PIX-6748).
  mon-pix/app/components/password-reset-demand-form.hbs
  mon-pix/app/components/password-reset-demand-form.js
  mon-pix/app/components/reset-password-form.hbs
  mon-pix/app/components/reset-password-form.js
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signin-form.js
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/components/signup-form.js
  mon-pix/app/components/update-expired-password-form.hbs
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/controllers/authentication/login-or-register-oidc.js
  mon-pix/app/controllers/terms-of-service.js
  mon-pix/app/services/url.js
  mon-pix/app/templates/authentication/login-or-register-oidc.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/tests/integration/components/signup-form_test.js
  mon-pix/tests/unit/services/url_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, cross-team

#5363 [TECH] Utiliser la table associative des dernier assessment results pour eviter des requetes complexes (PIX-6537)
  api/db/database-builder/factory/build-assessment-result.js
  api/db/database-builder/factory/build-certification-course-last-assessment-result.js
  api/db/database-builder/factory/index.js
  api/lib/infrastructure/repositories/certificate-repository.js
  api/lib/infrastructure/repositories/certification-livret-scolaire-repository.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/lib/infrastructure/repositories/certification-result-repository.js
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/lib/infrastructure/repositories/jury-certification-repository.js
  api/lib/infrastructure/repositories/jury-certification-summary-repository.js
  api/tests/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/acceptance/application/certifications/index_test.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/acceptance/application/session/session-controller-get-jury-certification-summaries_test.js
  api/tests/acceptance/application/session/session-controller-patch-publish-session_test.js
  api/tests/integration/infrastructure/repositories/certificate-repository_attestation_test.js
  api/tests/integration/infrastructure/repositories/certificate-repository_private_test.js
  api/tests/integration/infrastructure/repositories/certificate-repository_shareable_test.js
  api/tests/integration/infrastructure/repositories/certification-livret-scolaire-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-repository_test.js
  api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certifications-results-for-ls.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5497 [FEATURE] Annuler toutes les invitations à rejoindre une organisation qui sont actuellement en attente et non mis à jour depuis plus d'un an (PIX-6794)
  api/db/migrations/20230112103200_cancel-pending-organization-invitations-with-an-updatedAt-greater-than-a-year.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces, no-review-app

#5481 [FEATURE] Bloquer les imports SIECLE et Fregata si les données ne sont pas conformes pour le CPF (PIX-6118)
  api/db/migrations/20221123110348_remove-NULL-postalCodes.js
  api/lib/domain/read-models/CpfCertificationResult.js
  api/lib/domain/validators/organization-learner-validator.js
  api/lib/infrastructure/serializers/csv/organization-learner-columns.js
  api/lib/infrastructure/serializers/csv/organization-learner-parser.js
  api/lib/infrastructure/serializers/xml/xml-organization-learner-set.js
  api/tests/acceptance/application/organizations/organization-controller-import-sco-organization-learners_test.js
  api/tests/integration/domain/services/organization-learners-csv-service_test.js
  api/tests/integration/domain/services/organization-learners-xml-service_test.js
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-duplicate-national-student-id.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-no-national-student-id.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-two-valid-students.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-unknown-encoding.csv
  api/tests/tooling/fixtures/siecle-file/siecle-student-with-no-sex.xml
  api/tests/unit/domain/validators/organization-learner-validator_test.js
  api/tests/unit/infrastructure/serializers/csv/organization-learner-parser_test.js
  orga/app/services/error-messages.js
  orga/tests/unit/services/error-messages_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-prescription

#5475 [TECH] Implémenter le Normalize/Reset dans Pix Orga (Pix-3025)
  orga/app/components/campaign/activity/participants-list.hbs
  orga/app/components/campaign/analysis/recommendations.hbs
  orga/app/components/campaign/charts/participants-by-day-loader.hbs
  orga/app/components/campaign/charts/participants-by-day.hbs
  orga/app/components/campaign/charts/participants-by-mastery-percentage-loader.hbs
  orga/app/components/campaign/charts/participants-by-mastery-percentage.hbs
  orga/app/components/campaign/charts/participants-by-stage-loader.hbs
  orga/app/components/campaign/charts/participants-by-status-loader.hbs
  orga/app/components/campaign/charts/participants-by-status.hbs
  orga/app/components/campaign/filter/filters.hbs
  orga/app/components/campaign/results/assessment-list.hbs
  orga/app/components/campaign/results/profile-list.hbs
  orga/app/components/organization-learner/activity.hbs
  orga/app/components/organization-learner/activity/participation-list.hbs
  orga/app/components/participant/assessment/results.hbs
  orga/app/components/participant/profile/table.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/members-list.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/analysis/tube-recommendation-row.scss
  orga/app/styles/components/layout/footer.scss
  orga/app/styles/globals/a11y.scss
  orga/app/styles/globals/pages.scss
  orga/app/styles/globals/titles.scss
  orga/app/styles/pages/authenticated.scss
  orga/app/styles/pages/login.scss
  orga/app/templates/authenticated/campaigns/campaign/activity.hbs
  orga/app/templates/authenticated/campaigns/campaign/analysis.hbs
  orga/app/templates/authenticated/campaigns/campaign/assessment-results.hbs
  orga/app/templates/authenticated/campaigns/campaign/profile-results.hbs
  orga/package-lock.json
  orga/package.json
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-prescription

#5496 [FEATURE] Bloquer les imports SIECLE dans Pix Orga si il manque le code de la ville de naissance pour les élèves nés en France (PIX-6795)
  api/lib/infrastructure/serializers/xml/xml-organization-learner-set.js
  api/tests/integration/domain/services/organization-learners-xml-service_test.js
  api/tests/tooling/fixtures/siecle-file/siecle-french-student-with-no-birth-city-code.xml
  orga/app/services/error-messages.js
  orga/tests/unit/services/error-messages_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5487 [FEATURE] Simuler le score Pix avec l'ancien algorithme (PIX-6763).
  api/lib/application/scoring-simulator/index.js
  api/lib/application/scoring-simulator/scoring-simulator-controller.js
  api/lib/domain/models/OldScoringSimulation.js
  api/lib/domain/models/SimulationResult.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/simulate-old-scoring.js
  api/tests/acceptance/application/scoring-simulator/scoring-simulator-controller_test.js
  api/tests/integration/domain/usecases/simulate-old-scoring_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#5438 [FEATURE] Validation des candidats des sessions lors de l'import (PIX-6175).
  api/db/seeds/data/certification/certification-cpf-city-builder.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/domain/errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-cpf-service.js
  api/lib/domain/services/certification-sessions-service.js
  api/lib/domain/usecases/create-sessions.js
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/acceptance/application/certification-centers/certification-centers-controller-post-import-sessions_test.js
  api/tests/integration/domain/usecases/create-sessions_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-candidate.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/services/certification-sessions-service_test.js
  api/tests/unit/domain/usecases/create-sessions_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5484 [FEATURE] Formater le champs durée d'un contenu formatif dans l'API (PIX-6773)
  admin/app/models/training.js
  admin/app/transforms/interval.js
  admin/tests/unit/transforms/interval_test.js
  api/lib/application/trainings/index.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/unit/application/trainings/index_test.js
  api/tests/unit/application/trainings/training-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5338 [FEATURE] Nettoyer les tests de Pix App avec testing library (PIX-6382)
  mon-pix/app/components/dashboard/banner.hbs
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/signin-form.hbs
  mon-pix/tests/integration/components/dashboard/content_test.js
  mon-pix/tests/integration/components/hexagon-score_test.js
  mon-pix/tests/integration/components/navbar-desktop-header_test.js
  mon-pix/tests/integration/components/navbar-desktop-nav-menu_test.js
  mon-pix/tests/integration/components/navbar-header_test.js
  mon-pix/tests/integration/components/navbar-mobile-header_test.js
  mon-pix/tests/integration/components/pix-logo_test.js
  mon-pix/tests/integration/components/signin-form_test.js
  mon-pix/tests/integration/components/signup-form_test.js
  mon-pix/tests/integration/components/skiplink_test.js
  mon-pix/tests/integration/components/user-logged-menu_test.js
Labels: :rocket: Ready to Merge, cross-team, no-review-app

#5490 [BUGFIX] L'image et le titre de la page parcours ne sont pas centrés (PIX-6777).
  mon-pix/app/styles/pages/_user-tests.scss
  mon-pix/app/templates/authenticated/user-tests.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5501 [TECH] Prévenir les faux positifs dûs au helper catchErr (PIX-6828)
  api/lib/infrastructure/lcms.js
  api/tests/test-helper.js
  api/tests/test-helper_test.js
  api/tests/unit/infrastructure/lcms_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5503 [FEATURE] Simulateur de nouveau scoring (PIX-6766)
  api/lib/application/scoring-simulator/index.js
  api/lib/application/scoring-simulator/scoring-simulator-controller.js
  api/lib/domain/models/OldScoringSimulation.js
  api/lib/domain/models/ScoringSimulation.js
  api/lib/domain/models/SimulationResult.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/simulate-flash-scoring.js
  api/tests/acceptance/application/scoring-simulator/scoring-simulator-controller_test.js
  api/tests/integration/application/scoring-simulator/scoring-simulator-controller_test.js
  api/tests/integration/domain/usecases/simulate-flash-scoring_test.js
  api/tests/integration/domain/usecases/simulate-old-scoring_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#5510 [BUGFIX] Format de la donnée "code sexe" pour import Fregata dans Pix Orga (PIX-6846)
  api/lib/domain/validators/organization-learner-validator.js
  api/lib/infrastructure/serializers/csv/organization-learner-parser.js
  api/tests/acceptance/application/organizations/organization-controller-import-sco-organization-learners_test.js
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-duplicate-national-student-id.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-no-national-student-id.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-two-valid-students.csv
  api/tests/tooling/fixtures/siecle-file/siecle-csv-with-unknown-encoding.csv
  api/tests/unit/domain/validators/organization-learner-validator_test.js
  api/tests/unit/infrastructure/serializers/csv/organization-learner-parser_test.js
  orga/app/services/error-messages.js
  orga/tests/unit/services/error-messages_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5506 [CHORE] Changer le nombre de résultats par défaut pour les organisations pro (PIX-6789)
  orga/app/controllers/authenticated/organization-participants/list.js
  orga/app/routes/authenticated/organization-participants/list.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5512 [FEATURE] Ajout d'un texte spécifique pour lecteur d'écran sur le bouton de reset des filtres des tutoriels
  mon-pix/app/components/user-tutorials/filters/sidebar.hbs
  mon-pix/tests/integration/components/user-tutorials/filters/sidebar_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5516 [BUGFIX] Ré-aligner le design Pix Orga suite au Normalize (Pix-6858)
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/filter/filters.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/filters.scss
  orga/app/styles/components/layout/sidebar.scss
  orga/app/styles/components/layout/user-logged-menu.scss
  orga/app/styles/components/ui/index.scss
  orga/app/styles/components/ui/modal-display.scss
  orga/app/styles/globals/forms.scss
  orga/app/styles/globals/pages.scss
  orga/app/styles/pages/authenticated.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5514 [CHORE] Mise à jour de pix-ui en version 24.0.2 (PIX-6859)
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5504 [BUGFIX] Supprimer les divs dans les boutons présents dans la page de détails d'une compétence (PIX-6807).
  mon-pix/app/components/scorecard-details.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5502 [TECH] Utiliser les champs scorecards venant de l'API dans Pix App (PIX-6831).
  mon-pix/app/components/competence-card-default.hbs
  mon-pix/app/components/competence-card-mobile.hbs
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/helpers/scorecard-aria-label.js
  mon-pix/app/models/scorecard.js
  mon-pix/app/templates/authenticated/competences/results.hbs
  mon-pix/mirage/factories/user.js
  mon-pix/mirage/routes/get-scorecard.js
  mon-pix/mirage/routes/users/reset-scorecard.js
  mon-pix/mirage/serializers/scorecard.js
  mon-pix/tests/acceptance/competences-details_test.js
  mon-pix/tests/acceptance/competences-results_test.js
  mon-pix/tests/acceptance/profile_test.js
  mon-pix/tests/integration/components/scorecard-details_test.js
  mon-pix/tests/unit/models/scorecard_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5507 [FEATURE] Rendre le template de session compatible avec excel (PIX-6658)
  api/lib/infrastructure/files/sessions-import.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/lib/infrastructure/utils/csv/sessions-import.js
  api/tests/integration/infrastructure/utils/csv/sessions-import_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5505 [BUGFIX] Corriger les seeds : un CDC ne peut pas avoir plusieurs orga SCO rattachées (PIX-6796)
  api/db/seeds/data/certification/certification-centers-builder.js
  api/db/seeds/data/organizations-sco-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5493 [FEATURE] Permettre de modifier les champs de seuil de pré-requis et d'objectif pour les contenus formatifs (PIX-6730)
  api/db/database-builder/factory/build-training.js
  api/db/migrations/20230110144114_add_columns_prerequisiteThreshold_goalThreshold_to_trainings_table.js
  api/db/seeds/data/trainings-builder.js
  api/lib/application/trainings/index.js
  api/lib/domain/models/Training.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/tooling/domain-builder/factory/build-training.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5473 [TECH] Montée en version Pix UI vers v24.0.1 (PIX-6493)
  api/lib/domain/models/CertificationReport.js
  certif/app/components/add-student-list.hbs
  certif/app/components/issue-report-modal/candidate-information-change-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/candidate-information-change-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/app/components/select-referer-modal.hbs
  certif/app/components/session-delete-confirm-modal.hbs
  certif/app/components/session-finalization/uncompleted-reports-information-step.hbs
  certif/app/controllers/authenticated/sessions/finalize.js
  certif/app/controllers/authenticated/team.js
  certif/app/styles/app.scss
  certif/app/styles/components/add-issue-report-modal.scss
  certif/app/styles/components/finalize.scss
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/app/styles/components/select-referer-modal.scss
  certif/app/styles/components/session-delete-confirm-modal.scss
  certif/app/styles/components/session-finalization/reports-information-step.scss
  certif/app/styles/globals/modals.scss
  certif/app/styles/globals/pages.scss
  certif/app/styles/globals/titles.scss
  certif/app/styles/pages/authenticated/team.scss
  certif/app/templates/authenticated/sessions/new.hbs
  certif/app/templates/authenticated/sessions/update.hbs
  certif/app/templates/authenticated/team.hbs
  certif/package-lock.json
  certif/package.json
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/team_test.js
  certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields_test.js
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
  certif/tests/integration/components/session-finalization/uncompleted-reports-information-step_test.js
  certif/tests/unit/components/new-certification-candidate-modal_test.js
  certif/tests/unit/controllers/authenticated/sessions/finalize_test.js
  certif/tests/unit/controllers/team_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, Design Review OK

#5520 [BUGFIX] La pages des résultats dans PixOrga ne s'affiche pas (PIX-6847).
  api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
  api/tests/unit/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5513 [TECH] Harmonise et renforce les règles de lint CSS
  admin/.stylelintrc.json
  admin/app/styles/app.scss
  admin/app/styles/globals/nav.scss
  admin/package-lock.json
  admin/package.json
  certif/.stylelintrc.json
  certif/app/styles/app.scss
  certif/package-lock.json
  certif/package.json
  mon-pix/.stylelintrc.json
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, no-review-app

#5341 [ADR] Création d'un ADR pour formaliser la logique et la stratégie de gestion des paramètres régionaux et des langues (locales & languages) (PIX-6507)
  docs/adr/0040-locales-languages.md
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team, no-review-app

#5528 [TECH] Mise à jour d'Oppsy.
  api/package-lock.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team, no-review-app

#5522 [FEATURE] Ajouter les certifs complémentaires habilitées sur le CSV d'import en masse (PIX-6178).
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/get-import-session-complementary-certification-habilitations-labels.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/files/sessions-import.js
  api/tests/acceptance/application/certification-centers/certification-center-controller-get-import-template_test.js
  api/tests/integration/infrastructure/utils/csv/sessions-import_test.js
  api/tests/unit/application/certification-centers/index_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/domain/usecases/get-import-session-complementary-certification-habilitations-labels_test.js
  certif/app/components/sessions/panel-header.js
  certif/tests/unit/components/sessions/panel-header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5518 [FEATURE] Afficher les statistiques des campagnes dans la page de détail d'un prescrit (PIX-6143)
  api/lib/domain/read-models/OrganizationLearnerActivity.js
  api/lib/infrastructure/serializers/jsonapi/organization-learner-activity-serializer.js
  api/tests/tooling/domain-builder/factory/build-organization-learner-participation.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/read-models/OrganizationLearnerActivity_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-learner-activity-serializer_test.js
  orga/app/app.js
  orga/app/components/organization-learner/activity.hbs
  orga/app/components/organization-learner/activity.js
  orga/app/components/organization-learner/activity/campaign-type.hbs
  orga/app/components/organization-learner/activity/campaign-type.js
  orga/app/components/organization-learner/activity/participation-list.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/custom-icons/fapix-person-export.js
  orga/app/custom-icons/fapix-tachometer.js
  orga/app/custom-icons/index.js
  orga/app/models/organization-learner-activity.js
  orga/app/models/organization-learner-participation.js
  orga/app/models/organization-learner-statistic.js
  orga/app/styles/components/indicator-card.scss
  orga/app/styles/components/organization-learner/activity/campaign-type.scss
  orga/app/styles/components/organization-learner/activity/cards.scss
  orga/app/styles/components/organization-learner/index.scss
  orga/app/templates/authenticated/organization-participants/organization-participant/activity.hbs
  orga/app/templates/authenticated/sco-organization-participants/sco-organization-participant/activity.hbs
  orga/app/templates/authenticated/sup-organization-participants/sup-organization-participant/activity.hbs
  orga/ember-cli-build.js
  orga/package-lock.json
  orga/package.json
  orga/public/icons/assessment.svg
  orga/public/icons/profiles-collection.svg
  orga/tests/integration/components/organization-learner/activity_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5523 [FEATURE] Ajouter une route API pour récupérer un contenu formatif à partir de son ID (PIX-6732)
  api/lib/application/trainings/index.js
  api/lib/application/trainings/training-controller.js
  api/lib/domain/usecases/get-training.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/unit/application/trainings/index_test.js
  api/tests/unit/application/trainings/training-controller_test.js
  api/tests/unit/domain/usecases/get-training_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5515 [FEATURE] Simulateur scoring flash : pouvoir choisir la langue des épreuves utilisées (PIX-6856)
  api/lib/application/scoring-simulator/scoring-simulator-controller.js
  api/lib/domain/usecases/simulate-flash-scoring.js
  api/tests/acceptance/application/scoring-simulator/scoring-simulator-controller_test.js
  api/tests/integration/application/scoring-simulator/scoring-simulator-controller_test.js
  api/tests/integration/domain/usecases/simulate-flash-scoring_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#5527 [FEATURE] Ajouter un lien sur les Parcours dans l'onglet d'une organisation (PIX-6881)
  admin/app/components/organizations/target-profiles-section.hbs
  admin/tests/integration/components/organizations/target-profiles-section_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5517 [FEATURE] Simulateur scoring actuel : Calculer le score par compétence (PIX-6768)
  api/lib/domain/models/SimulationResult.js
  api/lib/domain/usecases/simulate-old-scoring.js
  api/tests/acceptance/application/scoring-simulator/scoring-simulator-controller_test.js
  api/tests/integration/domain/usecases/simulate-old-scoring_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#5526 [FEATURE] Améliorer la sémantique des listes de cartes de compétence (PIX-6817).
  mon-pix/app/components/competence-card-default.hbs
  mon-pix/app/components/competence-card-mobile.hbs
  mon-pix/app/components/competence-card/list.hbs
  mon-pix/app/styles/components/_competence-card-mobile.scss
  mon-pix/app/styles/components/competence-card/_list.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5525 [TECH] Un test unitaire du "mailer" est échec en local (PIX-6883)
  api/tests/unit/infrastructure/mailers/mailer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#5531 [FEATURE] Prise en compte du type de centre dans la génération du csv: Tarification (PIX-6179)
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/domain/models/CertificationCenter.js
  api/lib/domain/usecases/get-certification-center-for-admin.js
  api/lib/domain/usecases/get-certification-center.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/files/sessions-import.js
  api/tests/integration/infrastructure/utils/csv/sessions-import_test.js
  api/tests/unit/domain/models/CertificationCenter_test.js
  api/tests/unit/domain/usecases/get-certification-center-for-admin_test.js
  api/tests/unit/domain/usecases/get-certification-center_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5524 [BUGFIX] On ne peut plus choisir la langue du PDF du profil cible sur PixAdmin dans la modale (PIX-6876)
  admin/app/components/target-profiles/pdf-parameters-modal.hbs
  admin/app/components/target-profiles/pdf-parameters-modal.js
  admin/app/styles/app.scss
  admin/app/styles/components/target-profiles/pdf-modal.css
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5535 [BUGFIX] Réparer le champ pour modifier le SSO d'une organisation sur Pix Admin (PIX-6886).
  admin/app/components/organizations/information-section-edit.hbs
  admin/app/components/organizations/information-section-edit.js
  admin/app/components/team/add-member.hbs
  admin/tests/unit/components/organizations/information-section-edit_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5536 [TECH] Supprimer les relations inexistantes dans le serializer user.
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/lib/infrastructure/serializers/jsonapi/user-with-activity-serializer.js
  api/tests/acceptance/application/users/users-controller-get-current-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-with-activity-serializer_test.js
  mon-pix/mirage/serializers/user.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5539 [FEATURE] Permettre d'associer le SSO FWB à une organisation (PIX-6893)
  api/db/migrations/20230124090916_add-fwb-identity-provider-to-organization-table.js
Labels: :rocket: Ready to Merge, team-acces

#5530 [FEATURE] Ajout d'un champ de filtre pour la liste des tags (PIX-6737)
  admin/.stylelintrc.json
  admin/app/adapters/tag.js
  admin/app/components/organizations/all-tags.hbs
  admin/app/components/organizations/all-tags.js
  admin/app/routes/authenticated/organizations/get/all-tags.js
  admin/app/styles/components/organizations/all-tags.scss
  admin/ember-cli-build.js
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/organizations/all-tags_test.js
  admin/tests/unit/components/organizations/all-tags_test.js
  admin/tests/unit/routes/authenticated/organizations/all-tags_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team

#5486 [TECH] Améliorer l’accessibilité de la page Inscription sur Pix App (PIX-6782).
  mon-pix/app/components/form-textfield.hbs
  mon-pix/app/components/form-textfield.js
  mon-pix/app/components/password-reset-demand-form.hbs
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/components/signup-form.js
  mon-pix/app/styles/components/_password-reset-demand-form.scss
  mon-pix/app/styles/components/_signup-form.scss
  mon-pix/app/styles/globals/_buttons.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/tests/acceptance/password-reset_test.js
  mon-pix/tests/integration/components/password-reset-demand-form_test.js
  mon-pix/tests/integration/components/signup-form_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces, cross-team

#5550 [BUGFIX] Replacer la création des tag dans la page administration géré par les rôles ADMIN (PIX-6900)
  admin/app/components/administration/learning-content.hbs
  admin/app/components/administration/learning-content.js
  admin/app/components/tools/new-tag.hbs
  admin/app/components/tools/new-tag.js
  admin/app/controllers/authenticated/administration.js
  admin/app/controllers/authenticated/tools.js
  admin/app/templates/authenticated/administration.hbs
  admin/app/templates/authenticated/tools.hbs
  admin/tests/acceptance/administration_test.js
  admin/tests/acceptance/tools_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#5540 [TECH] Avoir un nommage cohérent pour le filtre des types de connexion dans l'API (Pix-6712)
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/infrastructure/repositories/sco-organization-participant-repository.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/sco-organization-participant-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/routes/authenticated/sco-organization-participants/list.js
  orga/mirage/handlers/find-filtered-paginated-sco-organization-participants.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5544 [FEATURE] Retirer le message d'inscription/connexion lorsque l'utilisateur est connecté sur la page d'envoi de profil sur PixAPP (PIX-6163)
  mon-pix/app/components/campaign-start-block.hbs
  mon-pix/tests/integration/components/campaign-start-block_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5542 [FEATURE] Afficher les heures au format 24 au lieu de 12 dans les exports des résultats (PIX-6898)
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5547 [FEATURE] Aligner graphiquement les pages de résultats de collecte d eprofils avec celle des évaluations dans Pix APP (PIX-6165)
  mon-pix/app/components/campaign-share-button.hbs
  mon-pix/app/components/profile-sharing-form.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/controllers/campaigns/profiles-collection/send-profile.js
  mon-pix/tests/unit/controllers/campaigns/profiles-collection/send-profile_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5534 [FEATURE] Permettre d'avoir une surveillant par ligne pour une meme session importée (PIX-6727)
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/acceptance/application/certification-centers/files/sessions.csv
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5545 [FEATURE] Ajouter le score par compétence dans le simulateur nouveau scoring (PIX-6769)
  api/lib/domain/models/ScoringSimulationResult.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/lib/domain/usecases/simulate-flash-scoring.js
  api/lib/domain/usecases/simulate-old-scoring.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/tests/acceptance/application/scoring-simulator/scoring-simulator-controller_test.js
  api/tests/integration/application/scoring-simulator/scoring-simulator-controller_test.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
  api/tests/integration/domain/usecases/simulate-flash-scoring_test.js
  api/tests/integration/domain/usecases/simulate-old-scoring_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#5551 [FEATURE] Séparer les résultats Flash des Participant Results (PIX-6746).
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5543 [TECH] La catégorie CONNECTION_OR_END_SCREEN devrait être dépréciée (PIX-6582)
  api/db/migrations/20230124103059_update-connection-or-end-screen-category-to-deprecated.js
  api/db/seeds/data/certification/certification-courses-builder.js
  api/lib/domain/models/CertificationIssueReport.js
  api/lib/domain/models/CertificationIssueReportCategory.js
  api/tests/tooling/domain-builder/factory/build-certification-issue-report.js
  api/tests/unit/domain/models/CertificationIssueReport_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5519 [FEATURE][ADMIN] Afficher l'information si le mot de passe est temporaire (PIX-6803)
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/components/users/user-detail-personal-information/authentication-method.js
  admin/app/models/authentication-method.js
  admin/app/styles/app.scss
  admin/tests/integration/components/users/user-detail-personal-information/authentication-method_test.js
  admin/translations/en.json
  admin/translations/fr.json
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#5561 [BUGFIX] Réparer le partitionnement des tests PixApp (PIX-6927)
  mon-pix/app/components/profile-sharing-form.hbs
  mon-pix/app/components/profile-sharing-form.js
  mon-pix/app/controllers/campaigns/profiles-collection/send-profile.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/test-helper.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5553 [FEATURE] Améliorer le contraste du texte au survol du menu utilisateur sur Pix App (PIX-6814).
  mon-pix/app/styles/components/_user-logged-menu.scss
Labels: :rocket: Ready to Merge, team-acces

#5552 [FEATURE] Ajout d'une page de détail de contenu formatif dans Pix Admin (PIX-6733)
  admin/app/components/trainings/list-summary-items.hbs
  admin/app/components/trainings/training-details-card.hbs
  admin/app/components/trainings/training-details-card.js
  admin/app/controllers/authenticated/trainings/training/details.js
  admin/app/models/training.js
  admin/app/router.js
  admin/app/routes/authenticated/trainings/training.js
  admin/app/routes/authenticated/trainings/training/details.js
  admin/app/routes/authenticated/trainings/training/index.js
  admin/app/styles/app.scss
  admin/app/styles/components/trainings/training-details-card.scss
  admin/app/templates/authenticated/trainings/training.hbs
  admin/app/templates/authenticated/trainings/training/details.hbs
  admin/mirage/config.js
  admin/mirage/handlers/trainings.js
  admin/tests/acceptance/authenticated/trainings/detail_test.js
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/integration/components/trainings/training-details-card_test.js
  admin/tests/unit/components/trainings/training-details-card_test.js
  admin/tests/unit/routes/authenticated/trainings/training_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5560 [FEATURE] Ajouter un titre dans la carte de tutoriel (PIX-6810)
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/components/tutorials/card.hbs
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/components/_tutorial-card.scss
  mon-pix/tests/integration/components/tutorials/card_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5555 [TECH] Supprimer le script de rattachement des profils cible inutilisé (PIX-5964).
  api/scripts/prod/add-target-profile-shares-to-organizations.js
  api/tests/unit/scripts/add-target-profile-shares-to-organizations_test.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#5566 [TECH] Ajout d'un script pour tester l'eligibilité d'un.e utilisat.eur.rice (PIX-6929)
  api/scripts/certification/get-user-certifications-eligibility.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK

#5546 [TECH] Remplace l'utilisation bookshelf dans le repository organization-learners
  api/lib/infrastructure/repositories/organization-learner-repository.js
  api/tests/integration/infrastructure/repositories/organization-learner-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5498 [TECH] Implémenter Normalize/Reset CSS dans Pix App (PIX-3026)
  mon-pix/app/components/account-recovery/student-information-form.hbs
  mon-pix/app/components/training/card.hbs
  mon-pix/app/components/training/card.js
  mon-pix/app/styles/components/_certification-not-certifiable.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/components/_training-card.scss
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/training/card_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-evaluation

#5562 [BUGFIX] L'utilisateur ne peut ni créer ni modifier des paliers de type "niveau" dans PixAdmin (PIX-6928)
  admin/app/components/stages/update-stage.hbs
  admin/app/components/stages/update-stage.js
  admin/app/components/target-profiles/stages.js
  admin/app/components/target-profiles/stages/new-stage.hbs
  admin/app/services/file-saver.js
  admin/app/styles/components/target-profiles/stages.scss
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/integration/components/stages/update-stage_test.js
  admin/tests/unit/components/organizations/all-tags_test.js
  admin/tests/unit/components/update-stage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5556 [FEATURE] Renvoyer le score Pix par compétence dans la route `assessment-result` (PIX-6901)
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/read-models/participant-results/BadgeResult.js
  api/lib/domain/read-models/participant-results/CompetenceResult.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/read-models/participant-results/CompetenceResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#5569 [BUGFIX] Corriger l'erreur rendant impossible la lecture des détails utilisateur sur Pix Admin (PIX-6941).
  api/lib/infrastructure/repositories/user-repository.js
Labels: :rocket: Ready to Merge, :steam_locomotive: EXPEDIT, team-acces

#5557 [FEATURE] Définir la pagination par défaut des pages à 50 éléments (PIX-6908)
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/controllers/authenticated/campaigns/campaign/assessment-results.js
  orga/app/controllers/authenticated/campaigns/campaign/profile-results.js
  orga/app/routes/authenticated/campaigns/campaign/activity.js
  orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
  orga/app/routes/authenticated/campaigns/campaign/profile-results.js
  orga/tests/acceptance/campaign-assessment-results_test.js
  orga/tests/acceptance/campaign-profiles_test.js
  orga/tests/unit/routes/authenticated/campaigns/campaign/assessment-results_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5571 [BUGFIX] corriger une régression visuelle des intitulées de réponse dans les QCM et SCU
  mon-pix/app/components/challenge-item-qcm.hbs
  mon-pix/app/components/challenge-item-qcu.hbs
  mon-pix/app/styles/components/_challenge-item.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5564 [TECH] Amélioration de l’accessibilité sur Pix Orga (PIX-6853).
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/team/invitations-list.hbs
  orga/app/components/team/members-list.hbs
  orga/app/styles/pages/authenticated/team/list.scss
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces, team-prescription, cross-team

#5548 [FEATURE] Création de(s) candidat(s) depuis l'import du fichier csv sessions en masse (PIX-6176)
  api/lib/domain/usecases/create-sessions.js
  api/lib/infrastructure/files/sessions-import.js
  api/lib/infrastructure/repositories/complementary-certification-repository.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/lib/infrastructure/utils/csv/sessions-import.js
  api/tests/integration/infrastructure/repositories/complementary-certification-repository_test.js
  api/tests/unit/domain/usecases/create-sessions_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5559 [FEATURE] Ajout de candidats à partir d'un id de session dans le csv d'import en masse (PIX-6180).
  api/lib/domain/usecases/create-sessions.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/unit/domain/usecases/create-sessions_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5573 [BUGFIX] Raccourcir le placeholder du champs certificabilité (PIX-6926)
  orga/app/components/organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sup-organization-participant/list.hbs
  orga/tests/acceptance/organization-participant-list_test.js
  orga/tests/acceptance/sup-organization-participant-list_test.js
  orga/tests/integration/components/organization-participant/list_test.js
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/integration/components/sup-organization-participant/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription
