Repository 1024pix/pix, pull requests merged in 2023-03, with the labels that each got.

#5749 [FEATURE] Modifier le contenu du message d'erreur authentification non autorisée sur Pix Certif
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5743 [FEATURE] Affichage du nombre de sessions et de candidats lors de l'import en masse de sessions (PIX-6960).
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/domain/models/SessionMassImportReport.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
  certif/app/components/import/step-two-section.hbs
  certif/app/controllers/authenticated/sessions/import.js
  certif/app/styles/pages/authenticated/sessions/import.scss
  certif/app/templates/authenticated/sessions/import.hbs
  certif/public/icons/solid-square-chevron-rigth.svg
  certif/tests/acceptance/session-import_test.js
  certif/tests/integration/components/sessions-import/step-two-section_test.js
  certif/tests/unit/controllers/authenticated/sessions/import_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5728 [CHORE] Aligner les en-tête et le contenu sur le tableau de la page des prescrits (PIX-7247)
  orga/app/components/organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sup-organization-participant/list.hbs
  orga/app/styles/pages/authenticated/organization-participants.scss
  orga/app/styles/pages/authenticated/sco-organization-participants/list.scss
  orga/app/styles/pages/authenticated/sup-organization-participants/list.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5754 [TECH] Rétablir le linter sur les dossier de tests et de scripts
  api/.eslintignore
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5741 [TECH] Retourner des tubes complets lors de la création de déclencheurs de contenu formatif (PIX-7291).
  api/lib/domain/models/TrainingTrigger.js
  api/lib/domain/models/TrainingTriggerTube.js
  api/lib/domain/usecases/create-or-update-training-trigger.js
  api/lib/infrastructure/repositories/training-trigger-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-trigger-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-trigger-repository_test.js
  api/tests/tooling/domain-builder/factory/build-training-trigger.js
  api/tests/unit/domain/usecases/create-or-update-training-trigger_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-trigger-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5744 [FEATURE] Retourner les déclencheurs liés au contenu formatif demandé (PIX-7256).
  api/lib/application/trainings/training-controller.js
  api/lib/domain/models/Training.js
  api/lib/domain/usecases/create-or-update-training-trigger.js
  api/lib/domain/usecases/get-training.js
  api/lib/domain/usecases/update-training.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/repositories/training-trigger-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/integration/infrastructure/repositories/training-trigger-repository_test.js
  api/tests/tooling/domain-builder/factory/build-training-trigger-tube.js
  api/tests/tooling/domain-builder/factory/build-training.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/trainings/training-controller_test.js
  api/tests/unit/domain/usecases/create-or-update-training-trigger_test.js
  api/tests/unit/domain/usecases/get-training_test.js
  api/tests/unit/domain/usecases/update-training_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5748 [FEATURE] Ajuster les largeurs de colonnes du tableau de paliers (PIX-7103)
  admin/app/components/target-profiles/stages.hbs
  admin/app/styles/components/target-profiles/stages.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-contenu

#5732 [FEATURE] Ajout d'un feature toggle pour l'envoi des données à PoleEmploi (PIX-7016).
  api/lib/config.js
  api/lib/domain/events/index.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/externals/pole-emploi/disabled-pole-emploi-notifier.js
  api/sample.env
  api/tests/integration/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/diabled-pole-emploi-notifier_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5729 [FEATURE][MON-PIX] Améliorer l'utilisabilité de la page d'erreur en cas de non-consentement du partage des informations de l'utilisateur entre l'identity provider et Pix (PIX-7248)
  mon-pix/app/errors/application-error.js
  mon-pix/app/errors/factories/create-application-error.js
  mon-pix/app/routes/authentication/login-oidc.js
  mon-pix/app/routes/error.js
  mon-pix/tests/unit/errors/factories/create-application-error_test.js
  mon-pix/tests/unit/routes/authentication/login-oidc_test.js
  mon-pix/tests/unit/routes/error_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5758 [FEATURE] Traduction de la page de détails d'une session sur Pix Certif (PIX-6669).
  certif/app/controllers/authenticated/sessions/details.js
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/app/templates/authenticated/sessions/import.hbs
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/session-details-parameters_test.js
  certif/tests/acceptance/session-details_test.js
  certif/tests/acceptance/session-list_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#5734 [BUGFIX] Gérer les adresses e-mail invalides lors de l'envoi d'invitations depuis Pix Orga (PIX-7188)
  api/lib/application/error-manager.js
  api/lib/application/http-errors.js
  api/lib/domain/errors.js
  api/lib/domain/models/EmailingAttempt.js
  api/lib/domain/services/organization-invitation-service.js
  api/lib/infrastructure/mailers/MailingProviderInvalidEmailError.js
  api/lib/infrastructure/mailers/SendinblueProvider.js
  api/lib/infrastructure/mailers/mailer.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/EmailingAttempt_test.js
  api/tests/unit/domain/services/organization-invitation-service_test.js
  api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
  orga/app/controllers/authenticated/team/new.js
  orga/tests/acceptance/team-creation_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5756 [BUGFIX] Restreindre les droits d'accès de modification des contenus formatifs (PIX-7305).
  admin/app/components/menu-bar.hbs
  admin/app/controllers/authenticated/trainings/list.js
  admin/app/controllers/authenticated/trainings/training.js
  admin/app/controllers/authenticated/trainings/training/target-profiles.js
  admin/app/controllers/authenticated/trainings/training/triggers.js
  admin/app/services/access-control.js
  admin/app/templates/authenticated/trainings/list.hbs
  admin/app/templates/authenticated/trainings/training.hbs
  admin/app/templates/authenticated/trainings/training/target-profiles.hbs
  admin/app/templates/authenticated/trainings/training/triggers.hbs
  admin/tests/acceptance/authenticated/trainings/edit-triggers_test.js
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/acceptance/authenticated/trainings/target-profiles_test.js
  admin/tests/acceptance/authenticated/trainings/training_test.js
  admin/tests/unit/services/access-control-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5745 [FEATURE] Permettre de confirmer la création massive des sessions sur Pix Certif (PIX-7234).
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/lib/domain/services/sessions-mass-import/temporary-sessions-storage-for-mass-import-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/sessions-mass-import/create-sessions.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-create-sessions_test.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-validate-sessions_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/domain/services/sessions-mass-import/temporary-sessions-storage-for-mass-import-service_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/create-sessions_test.js
  certif/app/adapters/sessions-mass-import-report.js
  certif/app/components/import/step-two-section.hbs
  certif/app/controllers/authenticated/sessions/import.js
  certif/app/models/sessions-mass-import-report.js
  certif/app/styles/pages/authenticated/sessions/import.scss
  certif/app/templates/authenticated/sessions/import.hbs
  certif/tests/acceptance/session-import_test.js
  certif/tests/unit/adapters/sessions-mass-import-report_test.js
  certif/tests/unit/controllers/authenticated/sessions/import_test.js
  certif/tests/unit/models/sessions-mass-import-report_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5761 [FEATURE][MON-PIX] Modifier le message d'erreur lors d'un refus de partage de données entre Pôle Emploi et Pix (PIX-7335)
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#5757 [BUGFIX] Améliorer le message d'erreur lorsqu'un utilisateur tente de rejoindre une organisation via une invitation en se connectant avec une adresse email inconnue sur Pix Orga (PIX-7269)
  orga/app/components/auth/login-form.js
  orga/config/environment.js
  orga/tests/integration/components/auth/login-form_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5760 [BUGFIX] Corriger le lien d'Accessibilité dans le footer de app.pix.org (PIX-7177)
  mon-pix/app/services/url.js
  mon-pix/tests/unit/services/url_test.js
Labels: :rocket: Ready to Merge, team-acces

#5762 [FEATURE] Ajouter des titres au plan du site sur Pix-App (PIX-6818)
  mon-pix/app/components/sitemap/content.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, cross-team

#5763 [FEATURE]: Ajouter une modale de confirmation de suppression dans le tableau de paliers (PIX-7331)
  admin/app/components/target-profiles/stages/stage.hbs
  admin/app/components/target-profiles/stages/stage.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/integration/components/target-profiles/stages_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-contenu

#5759 [FEATURE] Intégrer la gestion du palier 1er Acquis dans l'affichage de PixApp (PIX-7310)
  api/db/database-builder/factory/build-stage.js
  api/db/migrations/20230301100017_add-is-first-skill-column-on-stage.js
  api/db/seeds/data/stages-builder.js
  api/lib/domain/models/CampaignParticipationResult.js
  api/lib/domain/models/user-campaign-results/StageCollection.js
  api/lib/domain/read-models/CampaignParticipationOverview.js
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/read-models/participant-results/ReachedStage.js
  api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/lib/infrastructure/repositories/participant-result-repository.js
  api/lib/infrastructure/repositories/user-campaign-results/stage-collection-repository.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-result.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/user-campaign-results/build-stage-collection.js
  api/tests/unit/domain/models/CampaignParticipationResult_test.js
  api/tests/unit/domain/models/user-campaign-results/StageCollection_test.js
  api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/read-models/participant-results/ReachedStage_test.js
  api/tests/unit/domain/usecases/target-profile-management/create-stage_test.js
  api/tests/unit/domain/usecases/target-profile-management/delete-stage_test.js
  api/tests/unit/domain/usecases/target-profile-management/update-stage_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  mon-pix/app/components/campaign-participation-overview/card/disabled.hbs
  mon-pix/app/components/campaign-participation-overview/card/disabled.js
  mon-pix/app/components/campaign-participation-overview/card/ended.hbs
  mon-pix/app/components/campaign-participation-overview/card/ended.js
  mon-pix/app/components/reached-stage.hbs
  mon-pix/app/components/reached-stage.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/campaign-participation-result.js
  mon-pix/app/models/reached-stage.js
  mon-pix/app/styles/components/_reached-stage.scss
  mon-pix/mirage/serializers/campaign-participation-badge.js
  mon-pix/mirage/serializers/campaign-participation-result.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/disabled_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ended_test.js
  mon-pix/tests/integration/components/reached-stage_test.js
  mon-pix/tests/unit/components/reached-stage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-contenu

#5747 [TECH] Transformer manuellement les exports CJS hétérogènes dans le cadre de la migration ESM (PIX-7202)
  api/lib/application/target-profiles/presenter/pdf/manager/font-manager.js
  api/lib/application/target-profiles/presenter/pdf/manager/position-manager.js
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/domain/constants/oidc-identity-providers.js
  api/lib/domain/constants/organization-places-categories.js
  api/lib/domain/constants/saml-identity-providers.js
  api/lib/domain/events/index.js
  api/lib/domain/usecases/get-available-target-profiles-for-organization.js
  api/lib/infrastructure/authentication.js
  api/lib/infrastructure/http/http-agent.js
  api/lib/infrastructure/plugins/i18n.js
  api/lib/infrastructure/plugins/pino.js
  api/lib/infrastructure/plugins/sentry.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-attributes.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-evaluation-attributes.js
  api/lib/infrastructure/serializers/jsonapi/user-saved-tutorial-attributes.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5764 [FEATURE] Ajout de l'en-tête d'information avec certificabilité pour Orga sans import (PIX-7290)
  api/db/seeds/data/campaign-participations-builder.js
  api/db/seeds/data/campaigns-pro-builder.js
  api/lib/domain/read-models/organization-learner-follow-up/OrganizationLearner.js
  api/lib/infrastructure/repositories/organization-learner-follow-up/organization-learner-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-learner-follow-up/organization-learner-serializer.js
  api/tests/integration/infrastructure/repositories/organization-learner-follow-up/organization-learner-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-learner-follow-up/organization-learner-serializer_test.js
  orga/app/components/ui/learner-header-info.hbs
  orga/app/components/ui/learner-header-info.js
  orga/app/models/organization-learner.js
  orga/app/styles/components/previous-page-button.scss
  orga/app/styles/components/ui/information.scss
  orga/app/styles/pages/authenticated/organization-participants/organization-participant.scss
  orga/app/templates/authenticated/organization-participants/organization-participant.hbs
  orga/tests/integration/components/ui/learner-header-info_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5773 [BUGFIX] Améliorer l'affichage des adresses emails des membres des Centres de Certification dans Pix Admin (PIX-7135)
  admin/app/components/certification-centers/memberships-section.hbs
  admin/app/styles/components/member-item.scss
Labels: :rocket: Ready to Merge, team-acces

#5772 [BUGFIX] Convertir le temps majoré en decimal lors de l'import des sessions en masse sur Pix Certif (PIX-7351)
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  certif/app/controllers/authenticated/sessions/import.js
  certif/tests/unit/controllers/authenticated/sessions/import_test.js
Labels: :rocket: Ready to Merge, team-certif

#5767 [BUGFIX] Consultation de Résultat thématique - Problème d'affichage du contenu du tableau
  admin/app/components/target-profiles/badges.hbs
  admin/app/styles/components/target-profiles/badges.scss
Labels: :rocket: Ready to Merge, Func Review OK, team-contenu

#5779 [TECH] Ajouter un champ "locale" dans la table "users" (PIX-6905)
  api/db/migrations/20230307144120_add-locale-column-to-users-table.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#5768 [FEATURE] Ajoute un fil d'ariane sur les pages de détails d'une participation (PIX-7294)
  high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/assessment/header.js
  orga/app/components/participant/profile/header.hbs
  orga/app/components/participant/profile/header.js
  orga/app/components/ui/breadcrumb.hbs
  orga/app/components/ui/breadcrumb.js
  orga/app/routes/authenticated/campaigns/participant-profile.js
  orga/app/styles/components/ui/breadcrumb.scss
  orga/app/styles/components/ui/index.scss
  orga/app/templates/authenticated/campaigns/participant-profile.hbs
  orga/tests/acceptance/campaign-activity_test.js
  orga/tests/acceptance/campaign-participants-individual-results_test.js
  orga/tests/acceptance/profile_test.js
  orga/tests/integration/components/ui/breadcrumb_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5783 [BUGFIX] Une erreur est levée lors de l'arrêt de l'api (PIX-7202)
  api/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5784 [TECH] Préparer l'utilisation unique des exports nommés dans lib - Partie 2 (PIX-7202)
  api/index.js
  api/lib/application/healthcheck/healthcheck-controller.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/create-lcms-release.js
  api/lib/infrastructure/caches/learning-content-cache.js
  api/lib/infrastructure/datasources/learning-content/datasource.js
  api/lib/infrastructure/mailers/mailer.js
  api/lib/infrastructure/utils/redis-monitor.js
  api/scripts/_template.js
  api/scripts/certification/fill-last-assessment-result-certification-course-table.js
  api/scripts/certification/fill-pix-certification-status-column-in-certification-courses-table.js
  api/scripts/certification/generate-certification-attestations-by-session-ids.js
  api/scripts/certification/get-user-certifications-eligibility.js
  api/scripts/compare-pix-with-latest-release.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/data-generation/generate-certif-cli.js
  api/scripts/prod/compute-badge-acquisitions.js
  api/scripts/prod/target-profile-migrations/convert-target-profiles-into-new-format.js
  api/scripts/prod/target-profile-migrations/copy-target-profile-skills-into-campaign-skills.js
  api/scripts/prod/target-profile-migrations/parse-xls-files-for-target-profiles-migration.js
  api/scripts/refresh-cache.js
  api/scripts/toggle-is-for-absolute-novice-campaign-attribute.js
  api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
  api/tests/test-helper.js
  api/tests/unit/application/healthcheck/healthcheck-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/create-lcms-release_test.js
  api/tests/unit/infrastructure/datasources/learning-content/challenge-datasource_test.js
  api/tests/unit/infrastructure/datasources/learning-content/competence-datasource_test.js
  api/tests/unit/infrastructure/datasources/learning-content/datasource_test.js
  api/tests/unit/infrastructure/datasources/learning-content/skill-datasource_test.js
  api/tests/unit/infrastructure/datasources/learning-content/tube-datasource_test.js
  api/tests/unit/infrastructure/datasources/learning-content/tutorial-datasource_test.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
Labels: :rocket: Ready to Merge, cross-team

#5789 [TECH] Préparer l'utilisation unique des exports nommés dans lib - Partie 3 (PIX-7202)
  api/lib/routes.js
  api/server.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5790 [BUGFIX] Une erreur est levée lors de l'arrêt de l'api - Partie 2 (PIX-7202)
  api/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5766 [FEATURE] Onglet "Candidats" d'une session en anglais (PIX-6670)
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/import-candidates.hbs
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/controllers/authenticated/sessions/details/certification-candidates.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/integration/components/import-candidates_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5765 [BUGFIX] Corriger les liens dans le footer et sur la page d'invitation sur Pix Orga (PIX-7178)
  orga/app/services/url.js
  orga/tests/integration/components/layout/footer_test.js
  orga/tests/unit/services/url_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#5780 [FEATURE] Ajout de l'en-tête d'information avec certificabilité pour Orga Sco (PIX-7284)
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/components/sco-organization-participant/list.js
  orga/app/components/ui/learner-header-info.hbs
  orga/app/components/ui/learner-header-info.js
  orga/app/helpers/connection-types.js
  orga/app/models/organization-learner.js
  orga/app/models/sco-organization-participant.js
  orga/app/styles/components/ui/information.scss
  orga/app/templates/authenticated/sco-organization-participants/sco-organization-participant.hbs
  orga/tests/integration/components/ui/learner-header-info_test.js
  orga/tests/unit/models/sco-organization-participant_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5774 [BUGFIX][ADMIN] Augmenter la taille maximale du logo des organisations à 2,5Mo (PIX-7326)
  admin/app/controllers/authenticated/organizations/get.js
  admin/tests/unit/controllers/authenticated/organizations/get_test.js
  admin/translations/fr.json
  api/lib/application/organizations/index.js
  api/tests/acceptance/application/organizations/_files/logo-3mb.js
  api/tests/acceptance/application/organizations/organization-controller_test.js
  scripts/local-domains/nginx.conf
Labels: :rocket: Ready to Merge, team-acces

#5793 [CHORE] Mise à jour de Pix-Ui dans Pix Orga (PIX-7343)
  orga/app/components/auth/join-request-form.hbs
  orga/app/components/auth/login-form.hbs
  orga/app/components/auth/register-form.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/campaign/cards/stage_average_test.js
  orga/tests/integration/components/campaign/charts/participants-by-stage_test.js
  orga/tests/integration/components/campaign/stage-stars_test.js
  orga/tests/integration/components/participant/assessment/header_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5781 [FEATURE] Ajout de l'en-tête d'information avec certificabilité pour Orga Sup (PIX-7289)
  orga/app/components/ui/information.hbs
  orga/app/components/ui/learner-header-info.hbs
  orga/app/styles/components/ui/information.scss
  orga/app/templates/authenticated/sup-organization-participants/sup-organization-participant.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5797 [TECH] Amélioration de la gestion d'erreur sur la création d'un profil cible avec une organisation inconnue (PIX-7337)
  admin/app/components/target-profiles/create-target-profile-form.hbs
  api/lib/domain/usecases/create-target-profile.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/unit/domain/usecases/create-target-profile_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5788 [BUGFIX] Meilleure gestion des erreurs à la connexion, sur la double mire SCO (PIX-7046)
  api/db/seeds/data/user-logins-builder.js
  api/db/seeds/seed.js
  mon-pix/app/components/routes/login-form.hbs
  mon-pix/app/components/routes/login-form.js
  mon-pix/tests/integration/components/routes/login-form_test.js
  mon-pix/tests/unit/components/routes/login-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#5800 [FEATURE] Ajout d'un fil d'ariane sur la page de détail d'une campagne (PIX-7300)
  orga/app/components/campaign/header/title.hbs
  orga/app/components/campaign/header/title.js
  orga/app/components/ui/breadcrumb.hbs
  orga/app/controllers/authenticated/campaigns/campaign.js
  orga/app/routes/authenticated/campaigns/list/all-campaigns.js
  orga/app/routes/authenticated/campaigns/list/my-campaigns.js
  orga/app/services/navigation.js
  orga/app/styles/components/campaign/header/title.scss
  orga/app/templates/authenticated/campaigns/campaign.hbs
  orga/tests/acceptance/campaign-details_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5798 [FEATURE] Mettre le nom du prescrit comme titre sur les détails d'une participation (PIX-7296)
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/profile/header.hbs
  orga/app/components/ui/learner-header-info.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/learner-header-info.scss
  orga/app/styles/components/ui/information.scss
  orga/app/styles/globals/panels.scss
  orga/app/styles/globals/titles.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5794 [FEATURE] Récupérer les informations de référentiel des déclencheurs de contenu formatif (PIX-7353)
  api/db/seeds/data/trainings-builder.js
  api/lib/domain/models/TrainingTrigger.js
  api/lib/infrastructure/repositories/training-trigger-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/lib/infrastructure/serializers/jsonapi/training-trigger-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/integration/infrastructure/repositories/training-trigger-repository_test.js
  api/tests/tooling/domain-builder/factory/build-training-trigger.js
  api/tests/unit/domain/models/TrainingTrigger_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-trigger-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5799 [FEATURE] Améliorer le disclosure du block de signalisation de problème sur Pix-App (PIX-6862)
  mon-pix/app/components/feedback-panel.hbs
  mon-pix/app/components/feedback-panel.js
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/tests/unit/components/feedback-panel_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5805 [FEATURE] Conditionner l'affichage des déclencheurs de contenu formatif (PIX-7258)
  admin/app/components/trainings/create-training-triggers.hbs
  admin/app/models/training-trigger.js
  admin/app/models/training.js
  admin/app/models/trigger-tube.js
  admin/app/templates/authenticated/trainings/training/triggers.hbs
  admin/tests/integration/components/trainings/create-training-triggers_test.js
  api/lib/domain/models/Training.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/tooling/domain-builder/factory/build-training.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5807 [FEATURE] Éviter que le footer soit positionné en dehors de l'écran dans les pages avec peu de contenu (PIX-7437)
  mon-pix/app/styles/components/_footer.scss
  mon-pix/app/styles/globals/_layout.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5785 [FEATURE] Gestion des erreurs bloquantes sur l'import des sessions en masse (PIX-6963).
  api/lib/domain/constants/certification-candidates-errors.js
  api/lib/domain/constants/sessions-errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-cpf-service.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/lib/domain/validators/session-validator.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-validate-sessions_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/services/certification-cpf-service_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  api/tests/unit/domain/usecases/correct-candidate-identity-in-certification-course_test.js
  api/tests/unit/domain/validators/session-validator_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5806 [CLEANUP] Nettoyage des imports de libs qui viennent avec pix-ui
  admin/ember-cli-build.js
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/ember-cli-build.js
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5802 [FEATURE] Déplacer le tag certifiable à côté du nom du prescrit sur la page d'une participation (PIX-7421)
  orga/app/components/participant/profile/header.hbs
  orga/app/styles/components/participant/index.scss
  orga/app/styles/components/participant/profile.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5811 [FEATURE] Ajoute un lien vers les détails d'un participant sur les détails d'une participation (PIX-7295)
  api/lib/domain/read-models/CampaignAssessmentParticipation.js
  api/lib/domain/read-models/CampaignProfile.js
  api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
  api/lib/infrastructure/repositories/campaign-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer.js
  api/lib/infrastructure/serializers/jsonapi/campaign-profile-serializer.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-assessment-participation-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/campaign-profile-serializer_test.js
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/assessment/header.js
  orga/app/components/participant/link-to.hbs
  orga/app/components/participant/link-to.js
  orga/app/components/participant/profile/header.hbs
  orga/app/models/campaign-assessment-participation.js
  orga/app/models/campaign-profile.js
  orga/app/styles/components/participant/index.scss
  orga/app/styles/components/participant/profile.scss
  orga/config/icons.js
  orga/mirage/config.js
  orga/mirage/factories/campaign-profile.js
  orga/tests/acceptance/campaign-participants-individual-results_test.js
  orga/tests/acceptance/profile_test.js
  orga/tests/integration/components/participant/assessment/header_test.js
  orga/tests/integration/components/participant/profile/header_test.js
  orga/tests/unit/components/participant/link-to_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5407 [TECH] Script de migration automatique des critères de type "SkillSet" des RTs vers des critères "CappedTubes" (PIX-5698)
  api/db/database-builder/factory/build-badge-criterion.js
  api/scripts/data-generation/target-profiles-migration/migration-test-pro-tab.csv
  api/scripts/data-generation/target-profiles-migration/target-profiles-for-migrations.js
  api/scripts/prod/target-profile-migrations/convert-badges.js
  api/scripts/prod/target-profile-migrations/convert-target-profiles-into-new-format.js
  api/tests/acceptance/scripts/target-profile-migrations/convert-badges_test.js
  api/tests/acceptance/scripts/target-profile-migrations/convert-target-profiles-into-new-format_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5810 [BUGFIX] Ne pas afficher "Classe/Groupe" si cette info n'est pas présente pour le sco & sup. (PIX-7439)
  orga/app/components/ui/learner-header-info.hbs
  orga/tests/integration/components/ui/learner-header-info_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5816 [FEATURE] Traduction de la page Equipe de Pix Certif (PIX-6682).
  certif/translations/en.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5803 [FEATURE] Modale détail du candidat en anglais (PIX-6671)
  api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js
  api/tests/acceptance/application/session/session-controller-enroll-students_test.js
  api/tests/acceptance/application/session/session-controller-get-certification-candidates_test.js
  api/tests/acceptance/application/session/session-controller-post-certification-candidates_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/models/certification-candidate.js
  certif/mirage/config.js
  certif/tests/integration/components/certification-candidate-details-modal/certification-candidate-details-modal_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  certif/tests/unit/helpers/setup-intl.js
  certif/tests/unit/models/certification-candidate_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5819 [FEATURE] Afficher un message de succes recapitulatif apres l'import en masse (PIX-7365)
  certif/app/controllers/authenticated/sessions/import.js
  certif/tests/acceptance/session-import_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5817 [FEATURE] Traduire la page de modification de session (PIX-6674).
  certif/app/controllers/authenticated/sessions/update.js
  certif/app/templates/authenticated/sessions/update.hbs
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5809 [FEATURE] Rendre les participations cliquables sur la page d'un prescrit pour accéder à leurs détails. (PIX-7297)
  api/lib/domain/read-models/OrganizationLearnerParticipation.js
  api/lib/infrastructure/repositories/organization-learner-activity-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-learner-activity-serializer.js
  api/tests/integration/infrastructure/repositories/organization-learner-activity-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-learner-activity-serializer_test.js
  orga/app/components/organization-learner/activity/participation-list.hbs
  orga/app/components/organization-learner/activity/participation-row.hbs
  orga/app/components/organization-learner/activity/participation-row.js
  orga/app/models/campaign.js
  orga/app/models/organization-learner-participation.js
  orga/app/styles/components/learner-header-info.scss
  orga/tests/integration/components/organization-learner/activity/participation-row_test.js
  orga/tests/unit/components/organization-learner/activity/participation-row_test.js
  orga/tests/unit/models/campaign_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5812 [TECH] Ajouter un hash du username dans les logs de l'appel à api/token
  api/lib/infrastructure/plugins/pino.js
  api/tests/integration/infrastructure/plugins/pino_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#5820 [FEATURE] Affichages des erreurs bloquantes lors de l'import de session en masse (PIX-7412)
  api/lib/domain/constants/certification-candidates-errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  certif/app/components/import/step-one-section.hbs
  certif/app/components/import/step-two-section.hbs
  certif/app/components/import/step-two-section.js
  certif/app/styles/pages/authenticated/sessions/import.scss
  certif/tests/integration/components/sessions-import/step-two-section_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5824 [BUGFIX] Corriger le problème d'espacement sur la page de détail d'une compétence sur Pix-App (PIX-7327)
  mon-pix/app/components/scorecard-details.hbs
  mon-pix/app/styles/components/_scorecard-details.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5813 [FEATURE] Afficher le détail d'un déclencheur de contenu formatif (PIX-7429)
  admin/app/adapters/training-trigger.js
  admin/app/components/badges/capped-tubes-criterion.hbs
  admin/app/components/common/tubes-details/area.hbs
  admin/app/components/common/tubes-details/competence.hbs
  admin/app/components/common/tubes-details/tube.hbs
  admin/app/components/target-profiles/details.hbs
  admin/app/components/trainings/create-training-triggers.hbs
  admin/app/components/trainings/trigger/details.hbs
  admin/app/components/trainings/trigger/details.js
  admin/app/models/thematic.js
  admin/app/models/training-trigger.js
  admin/app/models/trigger-tube.js
  admin/tests/integration/components/trainings/create-training-triggers_test.js
  admin/tests/unit/adapters/training-trigger_test.js
  api/lib/application/trainings/index.js
  api/lib/domain/models/TrainingTrigger.js
  api/lib/infrastructure/repositories/training-trigger-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/lib/infrastructure/serializers/jsonapi/training-trigger-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/integration/infrastructure/repositories/training-trigger-repository_test.js
  api/tests/unit/application/trainings/index_test.js
  api/tests/unit/domain/models/TrainingTrigger_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-trigger-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5832 [FEATURE] Rendre les urls des contenus formatifs cliquable sur Pix-Admin (PIX-7389)
  admin/app/components/trainings/training-details-card.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5830 [BUGFIX] Les paginations de Pix App ne sont pas traduites (PIX-7433)
  mon-pix/app/templates/authenticated/user-trainings.hbs
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
  mon-pix/tests/acceptance/user-trainings_test.js
  mon-pix/tests/acceptance/user-tutorials/recommended_test.js
  mon-pix/tests/acceptance/user-tutorials/saved_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5828 [FEATURE] Traduire l'espace surveillant en anglais (PIX-6706).
  certif/app/components/session-supervising/candidate-list.hbs
  certif/app/components/session-supervising/header.hbs
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5837 [FEATURE] Visualiser le seuil et le nombre de sujets d'un déclencheur de contenu formatif (PIX-7260)
  admin/app/components/trainings/create-training-triggers.hbs
  admin/app/models/training-trigger.js
  admin/app/styles/components/trainings/training-triggers-tab.scss
  admin/tests/integration/components/trainings/create-training-triggers_test.js
  api/lib/domain/models/TrainingTrigger.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/lib/infrastructure/serializers/jsonapi/training-trigger-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/unit/domain/models/TrainingTrigger_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-trigger-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5826 [BUGFIX] Corrige le message de succès lors de l'import en masse (PIX-7481)
  certif/tests/acceptance/session-import_test.js
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5795 [FEATURE][MON-PIX] Enregistrer la locale d'un utilisateur depuis le cookie de PixSite lors de son inscription (PIX-7367)
  api/lib/application/error-manager.js
  api/lib/application/users/user-controller.js
  api/lib/domain/constants.js
  api/lib/domain/errors.js
  api/lib/domain/models/User.js
  api/lib/domain/models/UserToCreate.js
  api/lib/domain/usecases/create-user.js
  api/lib/infrastructure/repositories/user-to-create-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/integration/infrastructure/repositories/user-to-create-repository_test.js
  api/tests/unit/application/error-manager_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/models/UserToCreate_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
  mon-pix/app/components/signup-form.js
  mon-pix/app/models/user.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/integration/components/signup-form_test.js
  mon-pix/tests/unit/adapters/application_test.js
  mon-pix/tests/unit/components/signup-form_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5829 [FEATURE] Gestion des erreurs non bloquantes (PIX-6962)
  api/lib/domain/constants/sessions-errors.js
  api/lib/domain/models/SessionMassImportReport.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-validate-sessions_test.js
  api/tests/unit/domain/models/SessionMassImportReport_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
  certif/app/components/import/step-one-section.hbs
  certif/app/components/import/step-two-section.hbs
  certif/app/components/import/step-two-section.js
  certif/app/controllers/authenticated/sessions/import.js
  certif/app/styles/pages/authenticated/sessions/import.scss
  certif/app/templates/authenticated/sessions/import.hbs
  certif/tests/acceptance/session-import_test.js
  certif/tests/integration/components/sessions-import/step-two-section_test.js
  certif/tests/unit/controllers/authenticated/sessions/import_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5838 [BUGFIX] Afficher le déclencheur après sa création (PIX-7501).
  admin/app/controllers/authenticated/trainings/training/triggers/edit.js
  admin/app/models/training-trigger.js
  admin/mirage/handlers/trainings.js
  admin/mirage/serializers/training-trigger.js
  admin/tests/acceptance/authenticated/trainings/edit-triggers_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5815 [FEATURE] Gérer un message d'erreur spécifique si l'utilisateur rédemarre une certification avec un autre compte (PIX-6874)
  api/lib/domain/errors.js
  api/lib/domain/usecases/authenticate-external-user.js
  api/lib/domain/usecases/link-user-to-session-certification-candidate.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/scripts/data-generation/generate-certif-cli.js
  api/tests/acceptance/application/session/session-controller-create-certification-candidate-participation_test.js
  api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
  mon-pix/app/components/certification-joiner.js
  mon-pix/tests/integration/components/certification-joiner_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#5841 [FEATURE] Améliorer le design de la citation dans les consignes d'une épreuves (PIX-7370)
  mon-pix/app/styles/components/_challenge-statement.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5836 [FEATURE][ADMIN] Afficher la locale de l'utilisateur sur sa fiche (PIX-7362)
  admin/app/components/users/user-overview.hbs
  admin/app/models/user.js
  admin/tests/integration/components/users/user-overview_test.js
  api/db/database-builder/factory/build-user.js
  api/lib/domain/models/UserDetailsForAdmin.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/acceptance/application/users/users-controller-get-user-details-for-admin_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-user-details-for-admin.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#5834 [FEATURE] Création d'un script pour intervertir deux codes de campagnes (PIX-7445)
  api/db/database-builder/factory/build-campaign.js
  api/db/migrations/20230316155007_add-unicity-constraint-on-column-code-campaign.js
  api/db/seeds/data/certification/badge-acquisition-builder.js
  api/db/seeds/data/certification/complementary-certification-course-results-builder.js
  api/scripts/prod/swap-campaign-codes.js
  api/tests/integration/scripts/prod/swap-campaign-codes_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5848 [FEATURE] Préparation de la recommandation de contenu formatif - partie 2 (PIX-7503).
  api/lib/domain/services/training-recommendation.js
  api/tests/unit/domain/services/training-recommendation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5849 [FEATURE] Préparation de la recommandation de contenu formatif - partie 3 (PIX-7504).
  api/lib/domain/services/training-recommendation.js
  api/tests/unit/domain/services/training-recommendation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5823 [FEATURE] Traduction formulaire connection espace surveillant (PIX-6679)
  api/lib/application/error-manager.js
  api/lib/domain/constants/session-supervising.js
  api/lib/domain/errors.js
  api/tests/unit/application/error-manager_test.js
  certif/app/components/login-session-supervisor-form.hbs
  certif/app/components/login-session-supervisor-form.js
  certif/app/templates/login-session-supervisor.hbs
  certif/app/templates/session-supervising-error.hbs
  certif/tests/integration/components/login-session-supervisor-form_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5850 [BUGFIX] Afficher les messages d'erreur des champs pour la création et la modification de session (PIX-7161).
  api/lib/domain/validators/session-validator.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5844 [BUGFIX] Corrige l'affichage du message de changement de mot de passe sur certif
  certif/app/utils/intl/missing-message.js
  certif/config/ember-intl.js
  certif/config/environment.js
  certif/tests/integration/components/add-student-list_test.js
  certif/tests/integration/components/certif-checkbox_test.js
  certif/tests/integration/components/certification-candidate-in-staging-item_test.js
  certif/tests/integration/components/communication-banner_test.js
  certif/tests/integration/components/formbuilder-link-step_test.js
  certif/tests/integration/components/issue-report-modal/add-issue-report-modal_test.js
  certif/tests/integration/components/issue-report-modal/candidate-information-change-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/fraud-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/issue-report-modal_test.js
  certif/tests/integration/components/issue-report-modal/non-blocking-candidate-issue-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/non-blocking-technical-issue-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/signature-issue-report-fields_test.js
  certif/tests/integration/components/issue-reports-modal_test.js
  certif/tests/integration/components/login-form_test.js
  certif/tests/integration/components/login-session-supervisor-form_test.js
  certif/tests/integration/components/members-list_test.js
  certif/tests/integration/components/new-certification-candidate-details-modal/new-certification-candidate-modal_test.js
  certif/tests/integration/components/session-finalization-step-container_test.js
  certif/tests/integration/components/session-finalization/complementary-information-step_test.js
  certif/tests/integration/components/session-finalization/examiner-global-comment-step_test.js
  certif/tests/unit/controllers/authenticated/sessions/import_test.js
  certif/translations/en.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5842 [FEATURE] Enregistrer la locale de l'utilisateur à la connexion (PIX-7364)
  api/lib/application/authentication/authentication-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/services/locale-service.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/authentication/authentication-route_test.js
  api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/services/locale-service_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
Labels: :rocket: Ready to Merge, team-acces

#5861 [FEATURE] Modale autorisation à reprendre dans l'ES en anglais (PIX-6680)
  certif/app/components/session-supervising/candidate-in-list.js
  certif/app/templates/session-supervising.hbs
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5856 [FEATURE] Ajout d'un role "alert" quand le code campagne est erroné (PIX-7262)
  mon-pix/app/templates/fill-in-campaign-code.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5843 [TECH] Mise à jour de ember-cli-clipboard sur certif
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/package-lock.json
  certif/package.json
  certif/tests/integration/components/login-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, cross-team

#5840 [BUGFIX] Améliorer l'ergonomie de la modale "réponses et tutos" (PIX-7424)
  mon-pix/app/components/comparison-window.hbs
  mon-pix/app/components/feedback-panel.hbs
  mon-pix/app/styles/components/_comparison-window.scss
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/tests/acceptance/compare-answer-solution-qroc_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5857 [FEATURE] Retirer l'alternative textuelle aux logos des organisations sur la page fin de parcours (PIX-7266)
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5862 [TECH] Optimisation du training-trigger-repository (PIX-7512).
  api/lib/infrastructure/repositories/training-trigger-repository.js
  api/tests/integration/infrastructure/repositories/training-trigger-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5878 [TECH] Change les imports de ember-cli-mirage à miragejs
  admin/mirage/factories/badge.js
  admin/mirage/factories/certification-center-invitation.js
  admin/mirage/factories/certification-center.js
  admin/mirage/factories/feature-toggle.js
  admin/mirage/factories/organization-invitation.js
  admin/mirage/factories/organization.js
  admin/mirage/factories/session.js
  admin/mirage/factories/target-profile.js
  admin/mirage/factories/training.js
  admin/mirage/factories/user.js
  admin/mirage/serializers/application.js
  admin/mirage/serializers/certification-center-membership.js
  admin/mirage/serializers/certification-center.js
  admin/mirage/serializers/jury-certification-summary.js
  certif/mirage/factories/certification-candidate.js
  certif/mirage/factories/certification-issue-report.js
  certif/mirage/factories/certification-point-of-contact.js
  certif/mirage/factories/certification-report.js
  certif/mirage/factories/country.js
  certif/mirage/factories/division.js
  certif/mirage/factories/feature-toggle.js
  certif/mirage/factories/session.js
  certif/mirage/factories/student.js
  certif/mirage/serializers/application.js
  certif/mirage/serializers/session-summary.js
  certif/mirage/serializers/student.js
  orga/mirage/factories/campaign-analysis.js
  orga/mirage/factories/campaign-assessment-participation-result.js
  orga/mirage/factories/campaign-collective-result.js
  orga/mirage/factories/campaign-participation.js
  orga/mirage/factories/campaign-profile.js
  orga/mirage/factories/campaign.js
  orga/mirage/factories/division.js
  orga/mirage/factories/feature-toggle.js
  orga/mirage/factories/organization-invitation.js
  orga/mirage/factories/organization-participant.js
  orga/mirage/factories/target-profile.js
  orga/mirage/factories/user.js
  orga/mirage/serializers/application.js
  orga/mirage/serializers/area.js
  orga/mirage/serializers/campaign-analysis.js
  orga/mirage/serializers/campaign-assessment-participation-result.js
  orga/mirage/serializers/campaign-assessment-participation.js
  orga/mirage/serializers/campaign-collective-result.js
  orga/mirage/serializers/campaign.js
  orga/mirage/serializers/competence.js
  orga/mirage/serializers/framework.js
  orga/mirage/serializers/membership.js
  orga/mirage/serializers/organization-participant.js
  orga/mirage/serializers/organization.js
  orga/mirage/serializers/prescriber.js
  orga/mirage/serializers/sco-organization-participant.js
  orga/mirage/serializers/sup-organization-participant.js
  orga/mirage/serializers/thematic.js
  orga/mirage/serializers/user-orga-setting.js
  orga/mirage/serializers/user.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5839 [BUGFIX] Correction crash dans le script de cache refresh
  api/scripts/refresh-cache.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5859 [FEATURE] Enregistrer la locale à l'inscription d'un utilisateur via un SSO OIDC (PIX-7517)
  api/lib/application/authentication/oidc/oidc-controller.js
  api/lib/domain/models/UserToCreate.js
  api/lib/domain/services/locale-service.js
  api/lib/domain/usecases/authenticate-user.js
  api/lib/domain/usecases/create-oidc-user.js
  api/tests/acceptance/application/authentication/oidc/users-route-post_test.js
  api/tests/unit/application/authentication/oidc/oidc-controller_test.js
  api/tests/unit/domain/models/UserToCreate_test.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/usecases/authenticate-user_test.js
  api/tests/unit/domain/usecases/create-oidc-user_test.js
  mon-pix/app/components/authentication/login-or-register-oidc.js
  mon-pix/app/components/signup-form.js
  mon-pix/tests/unit/components/authentication/login-or-register-oidc_test.js
Labels: :rocket: Ready to Merge, team-acces

#5860 [FEATURE] Améliorer le label de la page "J'ai un code" (PIX-7263).
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  high-level-tests/e2e/cypress/support/step_definitions/index.js
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/tests/acceptance/fill-in-campaign-code_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5868 [FEATURE] Ajout d'un fil d'ariane sur la page de détail d'un prescrit (PIX-7301)
  orga/app/controllers/authenticated/organization-participants/organization-participant.js
  orga/app/controllers/authenticated/sco-organization-participants/sco-organization-participant.js
  orga/app/controllers/authenticated/sup-organization-participants/sup-organization-participant.js
  orga/app/styles/components/ui/information.scss
  orga/app/styles/pages/authenticated/organization-participants/organization-participant.scss
  orga/app/styles/pages/authenticated/sco-organization-participants/sco-organization-participant.scss
  orga/app/styles/pages/authenticated/sup-organization-participants/sup-organization-participant.scss
  orga/app/templates/authenticated/organization-participants/organization-participant.hbs
  orga/app/templates/authenticated/sco-organization-participants/sco-organization-participant.hbs
  orga/app/templates/authenticated/sup-organization-participants/sup-organization-participant.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5866 [FEATURE] Montée de version de Pix UI en v29.0.0 sur Pix App (PIX-7550)
  mon-pix/app/components/skill-review-improve.hbs
  mon-pix/app/styles/components/_assessment-banner.scss
  mon-pix/app/styles/components/_badge-card-certifiable.scss
  mon-pix/app/styles/components/_certification-joiner.scss
  mon-pix/app/styles/components/_certification-not-certifiable.scss
  mon-pix/app/styles/components/_certification-starter.scss
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_checkpoint.scss
  mon-pix/app/styles/components/_comparison-window.scss
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/components/_focused-certification-challenge-instructions.scss
  mon-pix/app/styles/components/_footer.scss
  mon-pix/app/styles/components/_login-or-register.scss
  mon-pix/app/styles/components/_navbar-burger-menu.scss
  mon-pix/app/styles/components/_new-information.scss
  mon-pix/app/styles/components/_password-reset-demand-form.scss
  mon-pix/app/styles/components/_qcm-solution-panel.scss
  mon-pix/app/styles/components/_qcu-panel.scss
  mon-pix/app/styles/components/_qcu-solution-panel.scss
  mon-pix/app/styles/components/_reached-stage.scss
  mon-pix/app/styles/components/_reset-password-form.scss
  mon-pix/app/styles/components/_result-item.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/components/_scorecard-details.scss
  mon-pix/app/styles/components/_training-card.scss
  mon-pix/app/styles/components/_tutorial-card.scss
  mon-pix/app/styles/components/_user-certification-hexagon-score.scss
  mon-pix/app/styles/components/_user-certifications-detail-competence.scss
  mon-pix/app/styles/components/_user-certifications-detail-header.scss
  mon-pix/app/styles/components/authentication/_oidc-reconciliation.scss
  mon-pix/app/styles/components/campaign-participation-overview/_card.scss
  mon-pix/app/styles/components/dashboard/_content.scss
  mon-pix/app/styles/globals/_text.scss
  mon-pix/app/styles/pages/_assessment-results.scss
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/app/styles/pages/_connection-methods.scss
  mon-pix/app/styles/pages/_course-preview.scss
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
  mon-pix/app/styles/pages/_fill-in-certificate-verification-code.scss
  mon-pix/app/styles/pages/_fill-in-participant-external-id.scss
  mon-pix/app/styles/pages/_join-restricted-campaign.scss
  mon-pix/app/styles/pages/_not-connected.scss
  mon-pix/app/styles/pages/_profile-already-shared.scss
  mon-pix/app/styles/pages/_send-profile.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/app/styles/pages/_terms-of-service.scss
  mon-pix/app/styles/pages/_update-expired-password-form.scss
  mon-pix/app/styles/pages/_user-tests.scss
  mon-pix/app/styles/pages/_user-trainings.scss
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/app/templates/fill-in-campaign-code.hbs
  mon-pix/ember-cli-build.js
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5864 [TECH] Utiliser un read-model pour les contenus formatifs destinés à Pix Admin (PIX-7548).
  api/lib/domain/read-models/TrainingForAdmin.js
  api/lib/domain/read-models/TrainingTriggerForAdmin.js
  api/lib/domain/usecases/get-training.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/repositories/training-trigger-repository.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/integration/infrastructure/repositories/training-trigger-repository_test.js
  api/tests/tooling/domain-builder/factory/build-training-for-admin.js
  api/tests/tooling/domain-builder/factory/build-training-trigger-for-admin.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/read-models/TrainingTriggerForAdmin_test.js
  api/tests/unit/domain/usecases/get-training_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-trigger-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5863 [FEATURE] Retourner le pallier atteint pour chaque compétence en fin de parcours sur Pix-App (PIX-7374)
  api/lib/domain/models/user-campaign-results/StageCollection.js
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/read-models/participant-results/CompetenceResult.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/unit/domain/models/user-campaign-results/StageCollection_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  api/tests/unit/domain/read-models/participant-results/CompetenceResult_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5896 [TECH] Met à jour @1024pix/ember-testing-library
  orga/package-lock.json
  orga/tests/acceptance/campaign-details_test.js
  orga/tests/acceptance/campaign-participants-individual-results_test.js
  orga/tests/acceptance/profile_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, cross-team

#5882 [FEATURE] Afficher un message d'erreur correct pour les erreurs liées à la locale lors de la connexion à Pix App (PIX-7434)
  mon-pix/app/components/signin-form.js
  mon-pix/tests/integration/components/signin-form_test.js
Labels: :rocket: Ready to Merge, team-acces

#5890 [FEATURE] Ajout de message d'erreurs lors du db:delete et db:create (PIX-7573)
  api/scripts/database/create-database.js
  api/scripts/database/drop-database.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5853 [FEATURE] Pré-remplir le champ d'un QROC (PIX-6411)
  mon-pix/app/components/challenge-item-qroc.js
  mon-pix/app/utils/proposals-parser/input-block.js
  mon-pix/app/utils/proposals-parser/response-block.js
  mon-pix/app/utils/proposals-parser/splitters.js
  mon-pix/tests/integration/components/challenge-item-qroc_test.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel_test.js
  mon-pix/tests/unit/components/qrocm-ind-solution-panel_test.js
  mon-pix/tests/unit/utils/proposals-as-blocks_test.js
  mon-pix/tests/unit/utils/proposals-parser/challenge-response-template_test.js
  mon-pix/tests/unit/utils/proposals-parser/input-block_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5877 [FEATURE] Enregistrer la locale de l'utilisateur à la connexion sur app.pix.fr (PIX-7549)
  mon-pix/app/services/locale.js
  mon-pix/app/services/session.js
  mon-pix/config/environment.js
  mon-pix/tests/unit/services/locale_test.js
  mon-pix/tests/unit/services/session_test.js
Labels: :rocket: Ready to Merge, team-acces

#5899 [BUGFIX] Mauvais message de palier affiché en fin de parcours (PIX-7581)
  api/lib/infrastructure/repositories/user-campaign-results/stage-collection-repository.js
  api/tests/integration/infrastructure/repositories/user-campaign-results/stage-collection-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5895 [BUGFIX] Eviter les erreurs 500 en cas de mauvais format d'heure et/ou date de session lors de l'import en masse (PIX-7575)
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5897 [TECH] Met à jour ember-cli-clipboard sur orga
  orga/app/components/campaign/copy-paste-button.hbs
  orga/app/components/sco-organization-participant/manage-authentication-method-modal.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription, cross-team

#5905 [TECH] Supprime les imports de librairie externe dans ember-cli-build
  orga/ember-cli-build.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#5855 [FEATURE] Modifier la langue d'un utilisateur depuis Pix-Admin(PIX-5767)
  admin/app/components/users/user-overview.hbs
  admin/app/components/users/user-overview.js
  admin/app/styles/app.scss
  admin/app/styles/components/users/authentication-method.scss
  admin/app/styles/components/users/organization-learners-table.scss
  admin/app/styles/components/users/user-detail-personal-information-section.scss
  admin/app/styles/components/users/user-overview.scss
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/users/get_test.js
  admin/tests/integration/components/users/user-overview_test.js
  api/lib/application/users/index.js
  api/lib/infrastructure/serializers/jsonapi/user-details-for-admin-serializer.js
  api/tests/acceptance/application/users/update-user-details-for-administration_test.js
  api/tests/tooling/domain-builder/factory/build-user-details-for-admin.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-details-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#5900 [TECH] Optimisation du style de la page "Mes tutos" (PIX-7578).
  mon-pix/app/components/tutorials/recommended-empty.hbs
  mon-pix/app/components/tutorials/saved-empty.hbs
  mon-pix/app/styles/pages/_user-tutorials.scss
  mon-pix/app/templates/authenticated/user-tutorials/recommended.hbs
  mon-pix/app/templates/authenticated/user-tutorials/saved.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5854 [TECH] Normalisation des fichiers de traductions (PIX-7511)
  certif/app/components/auth/login-or-register.hbs
  certif/app/components/auth/register-form.hbs
  certif/app/components/auth/register-form.js
  certif/app/components/auth/toggable-login-form.hbs
  certif/app/components/auth/toggable-login-form.js
  certif/app/components/certification-candidate-details-modal.hbs
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/login-form.hbs
  certif/app/components/login-session-supervisor-form.hbs
  certif/app/components/members-list.hbs
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/app/components/session-summary-list.hbs
  certif/app/components/session-supervising/candidate-in-list.hbs
  certif/app/components/session-supervising/candidate-list.hbs
  certif/app/components/session-supervising/header.hbs
  certif/app/controllers/authenticated/sessions/update.js
  certif/app/models/certification-candidate.js
  certif/app/styles/components/new-certification-candidate-modal.scss
  certif/app/templates/authenticated/sessions/details.hbs
  certif/app/templates/authenticated/sessions/details/parameters.hbs
  certif/app/templates/authenticated/sessions/new.hbs
  certif/app/templates/authenticated/sessions/update.hbs
  certif/tests/acceptance/join_test.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/acceptance/session-new_test.js
  certif/tests/integration/components/auth/login-or-register_test.js
  certif/tests/integration/components/auth/register-form_test.js
  certif/tests/integration/components/auth/toggable-login-form_test.js
  certif/tests/integration/components/new-certification-candidate-modal_test.js
  certif/tests/unit/components/auth/register-form_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5847 [TECH] Nettoyage des erreurs d'import de sessions en masse (PIX-7457)
  api/lib/domain/constants/certification-candidates-errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-cpf-service.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/services/certification-cpf-service_test.js
  certif/tests/integration/components/sessions-import/step-two-section_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5906 [FEATURE] Préparation de la recommandation de contenu formatif - partie 5 (PIX-7591).
  api/lib/domain/models/TrainingTrigger.js
  api/lib/domain/usecases/handle-training-recommendation.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/repositories/training-trigger-repository.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/integration/infrastructure/repositories/training-trigger-repository_test.js
  api/tests/unit/domain/models/TrainingTrigger_test.js
  api/tests/unit/domain/usecases/handle-training-recommendation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5907 [FEATURE] Traduire la page des cgu en anglais sur Pix Certif (PIX-6662).
  certif/app/components/terms-of-service/page-en.hbs
  certif/app/components/terms-of-service/page-fr.hbs
  certif/app/controllers/terms-of-service.js
  certif/app/styles/pages/terms-of-service.scss
  certif/app/templates/terms-of-service.hbs
  certif/tests/acceptance/terms-of-service_test.js
  certif/tests/integration/components/terms-of-service/page-fr_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#5902 [FEATURE] Traduire la modale de fin de test dans l'espace surveillant sur Pix Certif (PIX-6681).
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#5903 [BUGFIX] Gérer le mauvais format d'id de session lors de l'import en masse (PIX-7576)
  api/lib/domain/constants/sessions-errors.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5908 [FEATURE] Utiliser le cookie locale pour transmettre la locale lors de l'inscription (PIX-7564)
  api/lib/application/users/user-controller.js
  api/tests/acceptance/application/users/users-controller-save_test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/unit/application/users/user-controller_test.js
  mon-pix/app/components/signup-form.js
  mon-pix/tests/unit/components/signup-form_test.js
Labels: :rocket: Ready to Merge, team-acces

#5912 [TECH] Améliorer l'accessibilité de la page des cgu sur Pix Certif (PIX-6662).
  certif/app/components/terms-of-service/page-en.hbs
  certif/app/components/terms-of-service/page-fr.hbs
  certif/app/styles/pages/terms-of-service.scss
  certif/app/templates/terms-of-service.hbs
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#5913 [FEATURE] Changer le lien du mot de passe oublié lorsqu'on passe en domaine ORG sur Pix Certif (PIX-7593).
  certif/app/components/login-form.hbs
  certif/app/components/login-form.js
  certif/tests/integration/components/login-form_test.js
Labels: :rocket: Ready to Merge, team-certif

#5910 [TECH] Création d'un feature toggle pour la recommandation des contenus formatifs (PIX-7537)
  api/lib/config.js
  api/lib/domain/usecases/handle-training-recommendation.js
  api/sample.env
  api/tests/acceptance/application/feature-toggles/feature-toggle-controller_tests.js
  api/tests/unit/domain/usecases/handle-training-recommendation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5911 [TECH] N'avoir que le scroll du navigateur à l'affichage sur Pix Orga (PIX-7618)
  orga/app/components/banner/communication.hbs
  orga/app/styles/components/layout/footer.scss
  orga/app/styles/components/layout/sidebar.scss
  orga/app/styles/pages/authenticated.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription
