Repository 1024pix/pix, pull requests merged in 2023-04, with the labels that each got.

#5904 [FEATURE] Afficher les résultats des compétences sous forme d'étoiles sur la page de fin de parcours sur Pix-App (PIX-7557)
  api/lib/domain/read-models/participant-results/AssessmentResult.js
  api/lib/domain/read-models/participant-results/CompetenceResult.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
  mon-pix/app/components/campaigns/assessment/campaign-skill-review-competence-result.hbs
  mon-pix/app/components/campaigns/assessment/skill-review-competence-stages-result.hbs
  mon-pix/app/components/campaigns/assessment/skill-review-competence-stages-result.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/competence-result.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5920 [DOC] :memo: Ajout des entrées manquantes pour la v3.339.0 dans le changelog
  CHANGELOG.md
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#5924 [TECH] Ajout du .buildpacks manquant pour pix1d
  pix1d/.buildpacks
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#5915 [BUGFIX] Corriger le script de génération de campagne avec participation (PIX-7628)
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/prod/compute-participation-results.js
  api/tests/integration/scripts/data-generation/generate-campaign-with-participant_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5884 [TECH] Migre certif sur embroider
  admin/app/index.html
  admin/package.json
  certif/app/index.html
  certif/ember-cli-build.js
  certif/package-lock.json
  certif/package.json
  mon-pix/app/index.html
  mon-pix/package.json
  orga/app/index.html
  orga/package.json
Labels: :rocket: Ready to Merge, Func Review OK, team-certif, cross-team

#5926 [FEATURE] Ne pas permettre la modification d'une session inexistante lors de l'import en masse de session sur Pix Certif (PIX-7612).
  api/lib/domain/constants/sessions-errors.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/lib/infrastructure/repositories/sessions/session-repository.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-validate-sessions_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#5925 [TECH] Bump pix-ui 29.1.1 (PIX-7641)
  mon-pix/app/styles/pages/_challenge.scss
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5825 [FEATURE] Traduire la modale d'inscription individuelle d'un candidat en anglais sur Pix Certif (PIX-6672)
  certif/app/components/enrolled-candidates.js
  certif/tests/unit/components/enrolled-candidates_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5929 [FEATURE] Mise en place d'un algo de recommandation de contenu formatif (PIX-7506).
  api/lib/domain/models/Training.js
  api/lib/domain/models/TrainingTrigger.js
  api/lib/domain/models/TrainingTriggerTube.js
  api/lib/domain/services/training-recommendation.js
  api/lib/domain/usecases/handle-training-recommendation.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/unit/domain/models/TrainingTriggerTube_test.js
  api/tests/unit/domain/models/TrainingTrigger_test.js
  api/tests/unit/domain/models/Training_test.js
  api/tests/unit/domain/services/training-recommendation_test.js
  api/tests/unit/domain/usecases/handle-training-recommendation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5937 [FEATURE] Montée de version pix-ui@v30.0.0 sur Certif (PIX-7640)
  certif/app/components/dropdown/content.hbs
  certif/app/styles/components/auth/toggable-login-form.scss
  certif/app/styles/components/login-form.scss
  certif/app/styles/components/register-form.scss
  certif/app/styles/pages/authenticated/sessions.scss
  certif/app/styles/pages/authenticated/sessions/import.scss
  certif/app/styles/pages/join.scss
  certif/app/styles/pages/terms-of-service.scss
  certif/package-lock.json
  certif/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, cross-team

#5928 [FEATURE] Ajouter les tables de gestion des fonctionnalités pour Pix (PIX-7460)
  api/db/migrations/20230404151231_add-features-table.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5923 [FEATURE] Afficher les domaines de compétences sur la page de fin de campagne sur Pix-App (PIX-7012)
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  mon-pix/app/components/campaigns/assessment/skill-review-competence-stages-result.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/app/models/competence-result.js
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/unit/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5883 [FEATURE] Mise à jour de pixUI sur pixOrga (PIX-7560)
  orga/app/components/campaign/cards/participants-count.hbs
  orga/app/components/campaign/cards/result-average.hbs
  orga/app/components/campaign/cards/shared-count.hbs
  orga/app/components/campaign/cards/stage-average.hbs
  orga/app/components/organization-participant/header.hbs
  orga/app/components/participant/profile/header.hbs
  orga/app/components/ui/indicator-card.hbs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/analysis/tube-recommendation-row.scss
  orga/app/styles/components/campaign/cards.scss
  orga/app/styles/components/campaign/filters.scss
  orga/app/styles/components/campaign/header/title.scss
  orga/app/styles/components/campaign/no-campaign-panel.scss
  orga/app/styles/components/indicator-card.scss
  orga/app/styles/components/join-request-form.scss
  orga/app/styles/components/layout/footer.scss
  orga/app/styles/components/layout/user-logged-menu.scss
  orga/app/styles/components/learner/header.scss
  orga/app/styles/components/login-or-register.scss
  orga/app/styles/components/organization-learner/activity/campaign-type.scss
  orga/app/styles/components/organization-learner/activity/cards.scss
  orga/app/styles/components/organization-learner/activity/participation-list.scss
  orga/app/styles/components/participant/index.scss
  orga/app/styles/components/participant/no-participant-panel.scss
  orga/app/styles/components/participant/profile.scss
  orga/app/styles/components/team/remove-member-modal.scss
  orga/app/styles/components/ui/certificability-tooltip.scss
  orga/app/styles/components/ui/empty-state.scss
  orga/app/styles/components/ui/information.scss
  orga/app/styles/components/ui/last-participation-date-tooltip.scss
  orga/app/styles/components/ui/modal-display.scss
  orga/app/styles/globals/pages.scss
  orga/app/styles/globals/titles.scss
  orga/app/styles/pages/authenticated/campaigns/create-form.scss
  orga/app/styles/pages/authenticated/campaigns/details/activity.scss
  orga/app/styles/pages/authenticated/campaigns/new.scss
  orga/app/styles/pages/authenticated/certifications.scss
  orga/app/styles/pages/authenticated/organization-participants.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/styles/pages/authenticated/team/new.scss
  orga/app/styles/pages/authenticated/terms-of-service.scss
  orga/app/styles/pages/join-request.scss
  orga/app/styles/pages/join.scss
  orga/app/styles/pages/login.scss
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/ui/indicator-card-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, Design Review OK

#5942 [FEATURE] Modification du message par défaut d'un profil cible au palier 0 (PIX-7616)
  admin/app/components/target-profiles/stages.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5941 [BUGFIX] réparer la width de la sidebar et du main-content
  orga/app/styles/components/layout/sidebar.scss
  orga/app/styles/pages/authenticated.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5939 [FEATURE] Améliorer les messages d'erreurs de la gestions massive des sessions sur Pix Certif (PIX-7677).
  certif/tests/acceptance/session-import_test.js
  certif/tests/integration/components/sessions-import/step-two-section_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif, no-review-app

#5934 [FEATURE] Passer la duplication de candidat en erreur non bloquante dans l'import en masse (PIX-7181).
  api/lib/domain/constants/sessions-errors.js
  api/lib/domain/models/SessionMassImportReport.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-validate-sessions_test.js
  api/tests/unit/domain/models/SessionMassImportReport_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
  certif/app/components/import/step-two-section.js
  certif/tests/integration/components/sessions-import/step-two-section_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5930 [TECH] Ajouter une contrainte en base de données sur la colonne lang de la table users (PIX-7654)
  api/db/migrations/20230404075638_add-constraint-on-lang-column-from-users-table.js
  api/tests/integration/infrastructure/repositories/prescriber-repository_test.js
Labels: :rocket: Ready to Merge, team-acces, no-review-app

#5940 [TECH] Bump pix-ui version to 30.0.0 (PIX-7657).
  mon-pix/app/components/campaigns/assessment/skill-review-competence-stages-result.hbs
  mon-pix/app/styles/pages/_skill-review.scss
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5947 [BUGFIX] Ajouter un espacement entre les paragraphes de réponse à une épreuve (PIX-7684).
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_qcm-proposals.scss
  mon-pix/app/styles/components/_qcu-proposals.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5949 [FEATURE] Améliorer l'affichage du nom de l'organisation dans le menu sur Pix Orga (PIX-7662)
  orga/app/styles/components/layout/user-logged-menu.scss
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5935 [FEATURE] Ajouter le logo FWB et lien vers SSO FWB sur la page de app.pix.org/connexion (PIX-7253)
  api/tests/integration/domain/services/authentication/fwb-oidc-authentication-service_test.js
  api/tests/integration/domain/services/authentication/pole-emploi-oidc-authentication-service_test.js
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signin-form.js
  mon-pix/app/services/oidc-identity-providers.js
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/public/images/logo/fwb-connect-logo.svg
  mon-pix/tests/integration/components/signin-form_test.js
  mon-pix/tests/unit/services/oidc-identity-providers_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#5962 [TECH] Remplacement de boom a @hapi/boom
  api/lib/application/healthcheck/healthcheck-controller.js
  api/lib/infrastructure/authentication.js
  api/package-lock.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5966 [BUGFIX] Corrige l'envoie des emails
  admin/package-lock.json
  admin/package.json
  api/lib/infrastructure/mail-check.js
  api/package-lock.json
  api/package.json
  api/tests/test-helper.js
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains

#5959 [FEATURE] Améliorer le message d'erreur lorsque le fichier d'import en masse de session est vide sur Pix Certif (PIX-7672).
  api/lib/application/certification-centers/certification-center-controller.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  certif/app/controllers/authenticated/sessions/import.js
  certif/tests/acceptance/session-import_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#5917 [BUGFIX] Corriger l'affichage de la modale d'inscription d'un candidat sur Pix Certif (PIX-7630)
  certif/app/components/enrolled-candidates.hbs
  certif/app/components/enrolled-candidates.js
  certif/app/components/new-certification-candidate-modal.hbs
  certif/app/components/new-certification-candidate-modal.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/tests/integration/components/enrolled-candidates_test.js
  mon-pix/tests/acceptance/skill-review_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#5921 [TECH] Permettre la génération d'un grand nombre de fichers CPF (PIX-7580)
  api/lib/infrastructure/jobs/cpf-export/handlers/create-and-upload.js
  api/lib/infrastructure/jobs/cpf-export/handlers/planner.js
  api/lib/infrastructure/repositories/cpf-certification-result-repository.js
  api/tests/integration/infrastructure/repositories/cpf-certification-result-repository_test.js
  api/tests/unit/infrastructure/jobs/cpf-export/handlers/planner_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#5961 [FEATURE] Utiliser les nouvelles classes css de Pix UI pour les titres de la page des cgu sur Pix Certif (PIX-7703).
  certif/app/components/terms-of-service/page-en.hbs
  certif/app/components/terms-of-service/page-fr.hbs
  certif/app/templates/terms-of-service.hbs
Labels: :rocket: Ready to Merge, team-certif

#5751 [FEATURE] Améliorer les tests sur Pix App avec Testing Library (PIX-7131).
  mon-pix/app/components/account-recovery/confirmation-step.hbs
  mon-pix/app/components/inaccessible-campaign.hbs
  mon-pix/tests/acceptance/resume-campaigns-with-type-assessment_test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection_test.js
  mon-pix/tests/acceptance/start-campaigns-workflow_test.js
  mon-pix/tests/integration/components/account-recovery/confirmation-email-sent-test.js
  mon-pix/tests/integration/components/account-recovery/confirmation-step-test.js
  mon-pix/tests/integration/components/assessment-banner_test.js
  mon-pix/tests/integration/components/challenge-illustration_test.js
  mon-pix/tests/integration/components/checkpoint-continue_test.js
  mon-pix/tests/integration/components/scorecard-details_test.js
  mon-pix/tests/integration/components/update-expired-password-form_test.js
  mon-pix/tests/integration/components/user-certifications-panel_test.js
Labels: :rocket: Ready to Merge, cross-team

#5969 [TECH] Le CHANGELOG de la v3.242.0 est erroné (PIX-7730)
  CHANGELOG.md
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#5901 [TECH] Remplacer l'utilisation de bookshelf dans certains repositories
  api/lib/infrastructure/repositories/badge-repository.js
  api/lib/infrastructure/repositories/knowledge-element-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5946 [FEATURE] Ajouter la clé pour Activer l'envoi multiple sur les campagnes d'évaluation d'une organisation (PIX-7464)
  api/db/database-builder/database-builder.js
  api/db/knex-database-connection.js
  api/db/migrations/20230407090348_add-multiple-sending-feature.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#5968 [TECH] Aligner la signature de `buildLearningContent` avec les vrais clés i18n du référentiel
  api/tests/acceptance/application/assessments/assessment-controller-auto-validate-next-challenge_test.js
  api/tests/acceptance/application/campaign-participations/campaign-participations-controller-analyses_test.js
  api/tests/acceptance/application/campaigns/campaign-controller_test.js
  api/tests/acceptance/application/certifications/index_test.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/integration/domain/services/placement-profile-service_test.js
  api/tests/integration/infrastructure/repositories/certificate-repository_attestation_test.js
  api/tests/integration/infrastructure/repositories/certificate-repository_private_test.js
  api/tests/integration/infrastructure/repositories/certificate-repository_shareable_test.js
  api/tests/integration/infrastructure/repositories/learning-content-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-for-admin-repository_test.js
  api/tests/integration/infrastructure/repositories/training-trigger-repository_test.js
  api/tests/tooling/domain-builder/factory/build-area-learning-content-data-object.js
  api/tests/tooling/domain-builder/factory/build-certifications-results-for-ls.js
  api/tests/tooling/domain-builder/factory/build-competence-learning-content-data-object.js
  api/tests/tooling/fixtures/infrastructure/tubeLearningContentDataObjectFixture.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/tooling/learning-content-builder/build-learning-content_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5971 [TECH] Faire de l'injection de dépendance dans les controllers (part-1)
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/authentication/oidc/oidc-controller.js
  api/lib/application/campaign-participations/campaign-participation-controller.js
  api/lib/application/organizations/organization-controller.js
  api/lib/application/passwords/password-controller.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/authentication/oidc/oidc-controller_test.js
  api/tests/unit/application/campaign-participations/campaign-participation-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/passwords/password-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5974 [TECH] Faire de l'injection de dépendance dans les controllers (part-2)
  api/lib/application/account-recovery/account-recovery-controller.js
  api/lib/application/answers/answer-controller.js
  api/lib/application/assessment-results/assessment-result-controller.js
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/cache/cache-controller.js
  api/lib/application/campaigns-administration/campaign-controller.js
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/countries/country-controller.js
  api/lib/application/courses/course-controller.js
  api/tests/unit/application/account-recovery/account-recovery-controller_test.js
  api/tests/unit/application/answers/answer-controller_test.js
  api/tests/unit/application/assessment-results/assessment-result-controller_test.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/application/assessments/assessment-controller-save_test.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/application/cache/cache-controller_test.js
  api/tests/unit/application/campaigns-administration/campaign-controller_test.js
  api/tests/unit/application/certification-center-invitations/certification-center-invitation-controller_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/countries/country-controller_test.js
  api/tests/unit/application/courses/course-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5965 [FEATURE] Améliorer l'a11y du formulaire de signalisation de problème (PIX-5782)
  mon-pix/app/components/feedback-panel.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5978 [TECH] Faire de l'injection de dépendance dans les controllers (part-3)
  api/lib/application/certification-courses/certification-course-controller.js
  api/lib/application/challenges/challenge-controller.js
  api/lib/application/competence-evaluations/competence-evaluation-controller.js
  api/lib/application/frameworks/frameworks-controller.js
  api/lib/application/memberships/membership-controller.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/application/challenges/challenge-controller_test.js
  api/tests/unit/application/competence-evaluations/competence-evaluation-controller_test.js
  api/tests/unit/application/frameworks/frameworks-controller_test.js
  api/tests/unit/application/memberships/membership-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5972 [FEATURE] Traduire la modale de fermeture de l'espace surveillant sur Pix Certif (PIX-7674).
  certif/app/components/session-supervising/header.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#5893 [TECH] Migre orga sur embroider
  orga/app/components/campaign/charts/participants-by-day.js
  orga/ember-cli-build.js
  orga/package-lock.json
  orga/package.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, team-captains, cross-team

#5963 [FEATURE] Filtrer par id ou titre le tableau des contenus formatifs (PIX-7391).
  admin/app/components/trainings/list-summary-items.hbs
  admin/app/controllers/authenticated/trainings/list.js
  admin/app/routes/authenticated/trainings/list.js
  admin/app/templates/authenticated/trainings/list.hbs
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/integration/components/routes/authenticated/trainings/list-items_test.js
  admin/tests/unit/controllers/authenticated/trainings/list_test.js
  admin/tests/unit/routes/authenticated/trainings/list_test.js
  api/lib/application/trainings/index.js
  api/lib/application/trainings/training-controller.js
  api/lib/domain/usecases/find-paginated-training-summaries.js
  api/lib/infrastructure/repositories/training-repository.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/unit/application/trainings/training-controller_test.js
  api/tests/unit/domain/usecases/find-paginated-trainings-summary_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5981 [FEATURE] Visualiser si un CF est actif ou non depuis la liste sur Pix Admin (PIX-7741).
  admin/app/components/trainings/list-summary-items.hbs
  admin/app/components/trainings/list-summary-items.js
  admin/app/models/feature-toggle.js
  admin/app/models/training-summary.js
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/integration/components/routes/authenticated/trainings/list-items_test.js
  api/lib/domain/read-models/TrainingSummary.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/infrastructure/serializers/jsonapi/training-summary-serializer.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/tooling/domain-builder/factory/build-training-summary.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-summary-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#5985 [FEATURE] Visualiser si un CF est actif ou non depuis la liste des CF d'un PC sur Pix Admin (PIX-7745).
  api/lib/infrastructure/repositories/training-repository.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5984 [TECH] Faire de l'injection de dépendance dans les controllers (part-5)
  api/lib/application/organization-invitations/organization-invitation-controller.js
  api/lib/application/organization-learners/organization-learner-controller.js
  api/lib/application/prescribers/prescriber-controller.js
  api/lib/application/sco-organization-learners/sco-organization-learner-controller.js
  api/lib/application/scorecards/scorecard-controller.js
  api/lib/application/sessions/finalized-session-controller.js
  api/lib/application/sessions/session-controller.js
  api/lib/application/sessions/session-with-clea-certified-candidate-controller.js
  api/lib/application/tags/tag-controller.js
  api/tests/unit/application/organization-invitations/organization-invitation-controller_test.js
  api/tests/unit/application/organization-learners/organization-learner-controller_test.js
  api/tests/unit/application/prescribers/prescriber-controller_test.js
  api/tests/unit/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/unit/application/scorecards/scorecard-controller_test.js
  api/tests/unit/application/session/finalized-session-controller_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/application/session/session-with-clea-certified-candidate-controller_test.js
  api/tests/unit/application/tags/tag-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5796 [TECH] Migrer mon-pix sur embroider
  mon-pix/app/authenticators/gar.js
  mon-pix/app/utils/progress-in-assessment.js
  mon-pix/ember-cli-build.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/helpers/invalidate-session.js
  mon-pix/tests/unit/authenticators/gar_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains, cross-team

#5976 [BUGFIX] Permettre d'utiliser l'autofill sur les pages d'inscription de Pix App-Certif-Orga (PIX-7685)
  certif/app/components/auth/register-form.hbs
  mon-pix/app/components/signup-form.hbs
  orga/app/components/auth/register-form.hbs
  orga/app/components/auth/register-form.js
Labels: :rocket: Ready to Merge, team-acces

#5980 [BUGFIX] Remplacement de mot dans le nom de ville alternatif (PIX-7734)
  api/scripts/certification/import-certification-cpf-cities.js
  api/tests/unit/scripts/import-certification-cpf-cities_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5970 [FEATURE] Améliorer les tests de Pix App avec Testing Library (PIX-7712).
  mon-pix/app/components/campaign-participation-overview/card/ongoing.hbs
  mon-pix/app/components/competence-card-default.hbs
  mon-pix/app/components/competence-card-default.js
  mon-pix/app/components/dashboard/content.hbs
  mon-pix/app/components/dashboard/section.hbs
  mon-pix/app/components/feedback-panel.hbs
  mon-pix/app/components/new-information.hbs
  mon-pix/tests/acceptance/challenge-page-banner_test.js
  mon-pix/tests/acceptance/update-expired-password_test.js
  mon-pix/tests/acceptance/user-account_test.js
  mon-pix/tests/acceptance/user-dashboard_test.js
  mon-pix/tests/helpers/authentication.js
  mon-pix/tests/integration/components/badge-card_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ongoing_test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card_test.js
  mon-pix/tests/integration/components/campaign-start-block_test.js
  mon-pix/tests/integration/components/certification-banner_test.js
  mon-pix/tests/integration/components/choice-chip_test.js
  mon-pix/tests/integration/components/dashboard/content_test.js
  mon-pix/tests/integration/components/feedback-panel_test.js
  mon-pix/tests/integration/components/qrocm-proposal_test.js
  mon-pix/tests/integration/components/routes/register-form_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif, cross-team

#5992 [FEATURE] Amélioration de la compréhension des en-têtes du CSV d'import en masse (PIX-6655).
  api/lib/infrastructure/utils/csv/sessions-import.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-validate-sessions_test.js
  api/tests/integration/infrastructure/utils/csv/sessions-import_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5988 [TECH] Montée de version de Pix UI en v31.0.0 sur Pix-Certif (PIX-7753).
  certif/package-lock.json
  certif/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5989 [FEATURE] Afficher le statut d'un CF sur Pix Admin (PIX-7752).
  admin/app/components/trainings/training-details-card.hbs
  admin/app/components/trainings/training-details-card.js
  admin/app/models/training.js
  admin/tests/integration/components/trainings/training-details-card_test.js
  api/lib/domain/read-models/TrainingForAdmin.js
  api/lib/infrastructure/serializers/jsonapi/training-serializer.js
  api/tests/acceptance/application/trainings/training-controller_test.js
  api/tests/unit/domain/read-models/TrainingForAdmin_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/training-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#5986 [FEATURE] Montée de version de Pix UI en v31.0.0 sur Pix App (PIX-7748)
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#5889 [BUGFIX] Ajouter les traductions pour les champs en erreur dans les formulaires de création et modification de session (PIX-7157).
  certif/app/controllers/authenticated/sessions/new.js
  certif/app/controllers/authenticated/sessions/update.js
  certif/app/templates/authenticated/sessions/new.hbs
  certif/app/templates/authenticated/sessions/update.hbs
  certif/tests/unit/controllers/authenticated/sessions/new_test.js
  certif/tests/unit/controllers/authenticated/sessions/update_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5918 [TECH] Retrait du code lié à l'ancienne gestion des PCs et de ses clés de lecture sur PixAdmin (PIX-7631)
  admin/app/components/badges/badge.hbs
  admin/app/components/badges/capped-tubes-criterion.js
  admin/app/components/badges/skill-set-criterion.hbs
  admin/app/components/badges/skill-set-criterion.js
  admin/app/components/target-profiles/badge-form.hbs
  admin/app/components/target-profiles/badge-form.js
  admin/app/components/target-profiles/badge-form/old-criteria.hbs
  admin/app/components/target-profiles/old-details.hbs
  admin/app/components/target-profiles/old-details.js
  admin/app/components/target-profiles/stages.js
  admin/app/components/target-profiles/target-profile.hbs
  admin/app/components/target-profiles/target-profile.js
  admin/app/controllers/authenticated/target-profiles/target-profile/details.js
  admin/app/models/area.js
  admin/app/models/badge-criterion.js
  admin/app/models/badge.js
  admin/app/models/competence.js
  admin/app/models/new-area.js
  admin/app/models/new-competence.js
  admin/app/models/new-thematic.js
  admin/app/models/new-tube.js
  admin/app/models/old-area.js
  admin/app/models/old-competence.js
  admin/app/models/old-skill.js
  admin/app/models/old-tube.js
  admin/app/models/target-profile.js
  admin/app/models/thematic.js
  admin/app/models/tube.js
  admin/app/templates/authenticated/target-profiles/target-profile/details.hbs
  admin/mirage/config.js
  admin/mirage/factories/target-profile.js
  admin/mirage/handlers/badges.js
  admin/mirage/handlers/target-profiles.js
  admin/mirage/serializers/new-area.js
  admin/mirage/serializers/new-competence.js
  admin/mirage/serializers/new-thematic.js
  admin/mirage/serializers/target-profile.js
  admin/tests/acceptance/authenticated/target-profiles/list_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/management_test.js
  admin/tests/integration/components/badges/badge_test.js
  admin/tests/integration/components/badges/capped-tubes-criterion_test.js
  admin/tests/integration/components/routes/authenticated/target-profiles/target-profile/old-details_test.js
  admin/tests/integration/components/target-profiles/badge-form_test.js
  admin/tests/integration/components/target-profiles/stages_test.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/models/TargetProfileForAdmin.js
  api/lib/domain/models/TargetProfileForAdminOldFormat.js
  api/lib/domain/models/index.js
  api/lib/infrastructure/repositories/target-profile-for-admin-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-for-admin-new-format-serializer.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-for-admin-serializer.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/integration/application/target-profile/index_test.js
  api/tests/integration/infrastructure/repositories/target-profile-for-admin-repository_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile-for-admin.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-for-admin-new-format-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-for-admin-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5996 [TECH] Mise à jour de eslint-plugin-i18n-json en 4.0.0
  api/package-lock.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#5990 [BUGFIX] Permettre à un centre SCO qui ne gère pas d'élèves à importer en masse des sessions sur Pix Certif (PIX-7709).
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/scripts/helpers/csvHelpers.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
Labels: :rocket: Ready to Merge, team-certif

#5973 [TECH] Traduction de la modale d'ajout de signalement (PIX-6677).
  certif/app/components/issue-report-modal/add-issue-report-modal.hbs
  certif/app/components/issue-report-modal/add-issue-report-modal.js
  certif/app/components/issue-report-modal/candidate-information-change-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/candidate-information-change-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/fraud-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/in-challenge-certification-issue-report-fields.js
  certif/app/components/issue-report-modal/issue-reports-modal.hbs
  certif/app/components/issue-report-modal/non-blocking-candidate-issue-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/non-blocking-technical-issue-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/signature-issue-report-fields.hbs
  certif/app/models/certification-issue-report.js
  certif/mirage/factories/certification-issue-report.js
  certif/tests/integration/components/issue-report-modal/add-issue-report-modal_test.js
  certif/tests/integration/components/issue-report-modal/candidate-information-change-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/issue-report-modal_test.js
  certif/tests/integration/components/issue-reports-modal_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#5983 [FEATURE] Ajout d'une migration pour creer les colonnes deletedAt & deletedBy sur la table organization-learners (PIX-7681).
  api/db/migrations/20230413141704_add-deleted-on-organization-learners.js
  api/lib/infrastructure/repositories/campaign-participation-info-repository.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6005 [FEATURE] Traduction de la bannière de communication sur Pix Certif (PIX-6689).
  certif/app/components/communication-banner.hbs
  certif/app/helpers/text-with-multiple-lang.js
  certif/tests/unit/helpers/text-with-multiple-lang_test.js
Labels: :rocket: Ready to Merge, team-certif

#6001 [FEATURE] Imposer la majuscule sur la valeur lors de l'import en masse des sessions sur Pix Certif (PIX-7755).
  api/scripts/helpers/csvHelpers.js
  api/tests/unit/scripts/helpers/csvHelpers_test.js
  api/tests/unit/scripts/helpers/files/import-sessions-with-sex-value-in-lowercase-test.csv
Labels: :rocket: Ready to Merge, team-certif

#5951 [FEATURE] Pix1D - Afficher une épreuve de type embed
  api/lib/application/answers/answer-controller.js
  api/lib/application/answers/index.js
  api/lib/domain/usecases/correct-answer.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/answer-pix1d-serializer.js
  pix1d/app/pods/answer/model.js
  pix1d/app/pods/challenge/model.js
  pix1d/app/pods/challenge/route.js
  pix1d/app/pods/challenge/template.hbs
  pix1d/app/pods/components/.gitkeep
  pix1d/app/pods/components/challenge/challenge-actions/template.hbs
  pix1d/app/pods/components/challenge/challenge-embed-simulator/component.js
  pix1d/app/pods/components/challenge/challenge-embed-simulator/template.hbs
  pix1d/app/pods/components/challenge/challenge-item-auto-reply/component.js
  pix1d/app/pods/components/challenge/challenge-item-auto-reply/template.hbs
  pix1d/app/pods/components/challenge/challenge-item-generic/component.js
  pix1d/app/pods/components/challenge/challenge-statement/component.js
  pix1d/app/pods/components/challenge/challenge-statement/template.hbs
  pix1d/app/pods/components/challenge/item/component.js
  pix1d/app/pods/components/challenge/item/template.hbs
  pix1d/app/pods/components/markdown/markdown-to-html-unsafe/component.js
  pix1d/app/pods/components/markdown/markdown-to-html-unsafe/template.hbs
  pix1d/app/pods/components/markdown/markdown-to-html/component.js
  pix1d/app/pods/components/markdown/markdown-to-html/template.hbs
  pix1d/app/router.js
  pix1d/app/styles/app.scss
  pix1d/app/styles/components/challenge-embed-simulator.scss
  pix1d/app/utils/proposals-parser/challenge-response-template.js
  pix1d/mirage/config.js
  pix1d/package-lock.json
  pix1d/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6008 [FEATURE] Ajouter une boîte de dialogue de confirmation de sortie d'une campagne (PIX-7720).
  mon-pix/app/components/assessment-banner.hbs
  mon-pix/app/components/assessment-banner.js
  mon-pix/app/styles/components/_assessment-banner.scss
  mon-pix/tests/acceptance/challenge-commons_test.js
  mon-pix/tests/acceptance/challenge-page-banner_test.js
  mon-pix/tests/integration/components/assessment-banner_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6004 [FEATURE] Modification du wording des statuts des contenus formatifs (PIX-7785)
  admin/app/components/trainings/list-summary-items.hbs
  admin/app/components/trainings/training-details-card.hbs
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/integration/components/trainings/training-details-card_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6013 [FEATURE] Ajouter une nouvelle bannière pour la période de certification (PIX-7665).
  orga/app/components/banner/information.hbs
  orga/app/components/banner/information.js
  orga/config/environment.js
  orga/tests/acceptance/certifications_test.js
  orga/tests/integration/components/banner/information_test.js
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6014 [TECH] Aligner la version de Node entre les front (PIX-7803)
  pix1d/package-lock.json
  pix1d/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6007 [TECH][MON-PIX] Montée de version de Pix UI en v31.1.0 (PIX-7780)
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, cross-team

#5948 [FEATURE] Afficher Pix Certif dans la langue de l'utilisateur enregistrée dans son compte (PIX-7644)
  api/lib/domain/read-models/CertificationPointOfContact.js
  api/lib/infrastructure/repositories/certification-point-of-contact-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer.js
  api/tests/acceptance/application/certification-point-of-contacts/certification-point-of-contacts_test.js
  api/tests/integration/infrastructure/repositories/certification-point-of-contact-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-point-of-contact.js
  api/tests/unit/application/certification-point-of-contacts/certification-point-of-contact-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-point-of-contact-serializer_test.js
  certif/app/models/certification-point-of-contact.js
  certif/app/routes/application.js
  certif/app/services/current-domain.js
  certif/app/services/session.js
  certif/app/services/url.js
  certif/mirage/config.js
  certif/mirage/factories/certification-point-of-contact.js
  certif/tests/acceptance/authentication_test.js
  certif/tests/helpers/test-init.js
  certif/tests/integration/components/layout/footer_test.js
  certif/tests/unit/routes/application_test.js
  certif/tests/unit/services/current-domain_test.js
  certif/tests/unit/services/session_test.js
  certif/tests/unit/services/url_test.js
Labels: :rocket: Ready to Merge, team-acces

#6012 [TECH][CERTIF] Montée de version de Pix UI en v31.1.0 (PIX-7782)
  certif/package-lock.json
  certif/package.json
Labels: :rocket: Ready to Merge, cross-team

#6016 [BUGFIX] Corriger l'espacement avant la pagination dans la page "Mes formations" (PIX-7806).
  mon-pix/app/styles/pages/_user-trainings.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6023 [FEATURE] Agrandissement de la font du composant fil d'ariane (PIX-7659).
  orga/app/styles/components/ui/breadcrumb.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5998 [FEATURE] Modifier l'icône de l'IndicatorCard Profils reçus pour coller à la maquette (PIX-7660)
  orga/app/app.js
  orga/app/components/campaign/cards/shared-count.hbs
  orga/app/custom-icons/fapix-inbox-in.js
  orga/app/custom-icons/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6024 [TECH] Mettre à jour le package. json (PIX-7816)
  pix1d/package-lock.json
  pix1d/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6027 [BUGFIX] Correction des marges des pages de checkpoints et résultats (PIX-7818).
  mon-pix/app/styles/components/_checkpoint.scss
  mon-pix/app/styles/components/_progress-bar.scss
  mon-pix/app/styles/pages/_assessment-results.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6032 [FEATURE] align left header info content (PIX-7661)
  orga/app/styles/components/ui/information.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6000 [FEATURE] Amélioration A11y du fil d'Ariane d'import massif de sessions (PIX-7350)
  certif/app/templates/authenticated/sessions/import.hbs
  certif/tests/acceptance/session-import_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6030 [TECH] Amélioration du HTML de l'import en masse (PIX-7813).
  certif/app/components/import/step-two-section.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#6033 [BUGFIX] Mettre en anglais la traduction anglaise de la légende des filtres sur la liste de campagnes (PIX-7729)
  orga/translations/en.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6019 [FEATURE] Amélioration visuelle des consignes des écrans d'épreuve et de l'espacement en générale sur Pix-App (PIX-7716)
  mon-pix/app/components/challenge-statement.hbs
  mon-pix/app/styles/components/_challenge-actions.scss
  mon-pix/app/styles/components/_challenge-embed-simulator.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_challenge-statement.scss
  mon-pix/app/styles/components/_rounded-panel.scss
  mon-pix/app/styles/pages/_challenge.scss
  pix1d/app/styles/components/challenge-embed-simulator.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6034 [TECH] Injecter les dépendances pour préparer la migration ESM
  api/lib/application/security-pre-handlers.js
  api/lib/domain/services/token-service.js
  api/lib/domain/services/verify-certificate-code-service.js
  api/tests/unit/application/security-pre-handlers_test.js
  api/tests/unit/domain/services/verify-certificate-code-service_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6010 [TECH][ORGA] Montée de version de Pix UI en v31.1.0 (PIX-7781)
  orga/app/styles/pages/authenticated/campaigns/details/activity.scss
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/campaign/charts/participants-by-stage_test.js
Labels: :rocket: Ready to Merge, cross-team

#6022 [FEATURE] Création d'une vue pour l'affichage des prescrits actifs (PIX-7682).
  api/db/database-builder/database-builder.js
  api/db/knex-database-connection.js
  api/db/migrations/20230419155621_add-view-for-not-deleted-learners.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6029 [FEATURE] Harmonisation de la page de création de campagne (PIX-7663)
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/update-form.hbs
  orga/app/styles/globals/forms.scss
  orga/app/styles/pages/authenticated/campaigns/create-form.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5967 [TECH] Ajoute un ADR sur la suppression des prescrits avec une vue SQL (PIX-7645)
  docs/adr/0042-suppression-logique-de-données.md
  docs/adr/0045-suppression-logique-des-données-avec-historisation.md
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, no-review-app

#6044 [TECH] Montée de version de Artillery en 2.0.0
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#6046 [FEATURE] Expliquer l'obtention du palier 1er acquis lors du survol du bouton d'ajout de palier premier acquis (PIX-6517)
  admin/app/components/target-profiles/stages.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#6045 [TECH] Injecter les dépendances dans les use-cases pour préparer la migration ESM (épisode 357)
  api/lib/domain/usecases/create-organization-invitation-by-admin.js
  api/lib/domain/usecases/create-organization-invitations.js
  api/lib/domain/usecases/create-organization.js
  api/lib/domain/usecases/create-organizations-with-tags-and-target-profiles.js
  api/lib/domain/usecases/create-user.js
  api/lib/domain/usecases/get-campaign-assessment-participation.js
  api/lib/domain/usecases/get-target-profile-content-as-json.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/resend-organization-invitation.js
  api/lib/domain/usecases/send-sco-invitation.js
  api/lib/domain/usecases/update-campaign-details-management.js
  api/tests/integration/domain/usecases/create-organization_test.js
  api/tests/integration/domain/usecases/create-organizations-with-tags-and-target-profiles_test.js
  api/tests/integration/domain/usecases/update-campaign-details-management_test.js
  api/tests/unit/domain/usecases/accept-pix-certif-terms-of-service_test.js
  api/tests/unit/domain/usecases/accept-pix-orga-terms-of-service_test.js
  api/tests/unit/domain/usecases/accept-pix-terms-of-service_test.js
  api/tests/unit/domain/usecases/change-user-lang_test.js
  api/tests/unit/domain/usecases/create-or-update-user-orga-settings_test.js
  api/tests/unit/domain/usecases/create-organization-invitation-by-admin_test.js
  api/tests/unit/domain/usecases/create-organization-invitations_test.js
  api/tests/unit/domain/usecases/create-organization_test.js
  api/tests/unit/domain/usecases/create-organizations-with-tags-and-target-profiles_test.js
  api/tests/unit/domain/usecases/create-user_test.js
  api/tests/unit/domain/usecases/disable-certification-center-membership_test.js
  api/tests/unit/domain/usecases/disable-membership_test.js
  api/tests/unit/domain/usecases/find-association-between-user-and-organization-learner_test.js
  api/tests/unit/domain/usecases/get-assessment_test.js
  api/tests/unit/domain/usecases/get-campaign-assessment-participation_test.js
  api/tests/unit/domain/usecases/get-challenge-for-pix-auto-answer_test.js
  api/tests/unit/domain/usecases/get-last-challenge-id-from-assessment-id_test.js
  api/tests/unit/domain/usecases/get-session-certification-candidates_test.js
  api/tests/unit/domain/usecases/get-session-certification-reports_test.js
  api/tests/unit/domain/usecases/get-target-profile-content-as-json_test.js
  api/tests/unit/domain/usecases/handle-training-recommendation_test.js
  api/tests/unit/domain/usecases/reconcile-sco-organization-learner-automatically_test.js
  api/tests/unit/domain/usecases/remember-user-has-seen-assessment-instructions_test.js
  api/tests/unit/domain/usecases/resend-organization-invitation_test.js
  api/tests/unit/domain/usecases/send-sco-invitation_test.js
  api/tests/unit/domain/usecases/update-campaign-details-management_test.js
  api/tests/unit/domain/usecases/update-user-password_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6028 [TECH] Tester la stack Scalingo 22
  scalingo.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6020 [TECH][ADMIN] Montée de version de Pix UI en v31.1.0 (PIX-7784)
  admin/package-lock.json
  admin/package.json
Labels: :rocket: Ready to Merge, cross-team

#6021 [BUGFIX] Pix certif double scrollbar sur la liste des sessions (PIX-7413)
  certif/app/styles/pages/authenticated.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6039 [FEATURE] Traduction du date picker de création et de modification de session (PIX-7811).
  certif/app/controllers/authenticated/sessions/new.js
  certif/app/controllers/authenticated/sessions/update.js
  certif/app/templates/authenticated/sessions/new.hbs
  certif/app/templates/authenticated/sessions/update.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6015 [TECH] Supprimer le FT lié aux recommandations des CF (PIX-7805).
  admin/app/components/trainings/list-summary-items.hbs
  admin/app/components/trainings/list-summary-items.js
  admin/app/components/trainings/training-details-card.hbs
  admin/app/components/trainings/training-details-card.js
  admin/app/models/feature-toggle.js
  admin/tests/acceptance/authenticated/trainings/list_test.js
  admin/tests/integration/components/routes/authenticated/trainings/list-items_test.js
  admin/tests/integration/components/trainings/training-details-card_test.js
  api/lib/config.js
  api/lib/domain/usecases/handle-training-recommendation.js
  api/tests/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/acceptance/application/feature-toggles/feature-toggle-controller_tests.js
  api/tests/unit/domain/usecases/handle-training-recommendation_test.js
  high-level-tests/e2e/cypress/fixtures/campaign_skills.json
  high-level-tests/e2e/cypress/fixtures/training-trigger-tubes.json
  high-level-tests/e2e/cypress/fixtures/training-triggers.json
  high-level-tests/e2e/cypress/support/step_definitions/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6055 [TECH] Annule les mises à jour d'ember-cookies
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6057 [FEATURE] remplacement du palier 1 par un booléen premier acquis (PIX-7787)
  api/db/database-builder/factory/build-stage.js
  api/scripts/prod/target-profile-migrations/replace-threshold1-with-first-skill-stage.js
  api/tests/integration/scripts/prod/replace-threshold1-with-first-skill-stage_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5975 [FEATURE] Permettre au service CPF de renvoyer plusieurs erreurs (PIX-7727)
  api/lib/domain/constants/certification-candidates-errors.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/services/certification-cpf-service.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/correct-candidate-identity-in-certification-course.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/services/certification-cpf-service_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  api/tests/unit/domain/usecases/correct-candidate-identity-in-certification-course_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
  certif/tests/integration/components/sessions-import/step-two-section_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6061 [BUGFIX] Supprimer la mauvaise vérification d'un doublon de candidat lors d'un import en masse de sessions sur Pix Certif (PIX-7838).
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#6070 [TECH] Supprime popper.js de admin
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6041 [FEATURE] Empêcher l'import en masse pour un centre SCO isNotManagingStudent utilisant un modèle csv SUP/PRO (PIX-7774)
  api/lib/infrastructure/serializers/csv/csv-serializer.js
  api/tests/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6072 [TECH] Mise à jour de dépendances sur pix-admin
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6025 [FEATURE] Empêcher validation et création des sessions en masse pour les centres sco isManagingStudent (PIX-7775)
  api/lib/application/certification-centers/index.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/usecases/checkOrganizationIsScoAndManagingStudent.js
  api/tests/acceptance/application/certification-centers/certification-center-controller-get-import-template_test.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-create-sessions_test.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-validate-sessions_test.js
  api/tests/unit/application/certification-centers/index_test.js
  api/tests/unit/application/security-pre-handlers_test.js
  api/tests/unit/application/usecases/checkOrganizationIsScoAndManagingStudent_test.js
  certif/app/controllers/authenticated/sessions/import.js
  certif/tests/unit/controllers/authenticated/sessions/import_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6073 [TECH] Corrige un mauvais import dans pix-admin
  admin/tests/unit/models/session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6069 [TECH] Supprimer les colonnes non utilisées de la table `trainings`(PIX-7857).
  api/db/database-builder/factory/build-training.js
  api/db/migrations/20230425073218_remove-useless-trainings-columns.js
  api/db/seeds/data/trainings-builder.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6026 [FEATURE] Ajouter un language switcher sur la page d'inscription de Pix App (PIX-7742)
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/controllers/inscription.js
  mon-pix/app/services/current-domain.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/pages/_inscription.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/inscription.hbs
  mon-pix/config/icons.js
  mon-pix/tests/acceptance/inscription_test.js
  mon-pix/tests/unit/components/signup-form_test.js
  mon-pix/tests/unit/services/current-domain_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#6059 [TECH] Assurer la cohérence de données lors de la MAJ d'un déclencheur de contenu formatif (PIX-7852).
  api/lib/application/trainings/training-controller.js
  api/lib/domain/usecases/create-or-update-training-trigger.js
  api/lib/infrastructure/repositories/training-trigger-repository.js
  api/tests/unit/application/trainings/training-controller_test.js
  api/tests/unit/domain/usecases/create-or-update-training-trigger_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6003 [BUGFIX] Ne plus appeler le provider de mail lors de l'exécution des tests (PIX-7783)
  api/lib/infrastructure/mail-check.js
  api/lib/infrastructure/mailers/mailer.js
  api/tests/unit/infrastructure/mailers/mailer_test.js
Labels: :rocket: Ready to Merge, cross-team

#6075 [FEATURE] Afficher l'image du profil cible dans l'encart de détails sur PixAdmin (PIX-7129)
  admin/app/components/target-profiles/target-profile.hbs
  admin/tests/acceptance/authenticated/target-profiles/target-profile/management_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#6056 [BUGFIX] Retirer le scroll automatique lors de l'utilisation d'un filtre sur Pix Orga (PIX-7850)
  orga/app/router.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6054 [FEATURE] Upgrade pix-ui version to 32.0.0 (PIX-7843)
  orga/app/components/campaign/cards/participants-count.hbs
  orga/app/components/campaign/cards/result-average.hbs
  orga/app/components/campaign/cards/shared-count.hbs
  orga/app/components/campaign/cards/stage-average.hbs
  orga/app/components/organization-learner/activity.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6053 [BUGFIX] Corriger la width des form-field info sur la page de création de campagne (PIX-7846)
  orga/app/styles/globals/forms.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6060 [FEATURE] Changer la couleur des icônes "?" dans la section avec le graphique “statuts” des participations
  orga/app/styles/components/campaign/charts/participants-by-status.scss
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#6079 [TECH] Injection de dépendances pour préparer la migration ESM
  api/lib/domain/services/certification-challenges-service.js
  api/lib/domain/services/reset-password-service.js
  api/lib/domain/usecases/get-user-by-reset-password-demand.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-session.js
  api/tests/integration/domain/services/pick-certification-challenge_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/domain/services/reset-password-service_test.js
  api/tests/unit/domain/usecases/update-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6081 [TECH] Mettre en place l'injection de dépendance pour la migration ESM
  api/lib/application/preHandlers/session-supervisor-authorization.js
  api/lib/domain/services/sessions-mass-import/sessions-import-validation-service.js
  api/lib/domain/usecases/create-session.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/tests/unit/application/preHandlers/session-supervisor-authorization_test.js
  api/tests/unit/domain/services/sessions-mass-import/sessions-import-validation-service_test.js
  api/tests/unit/domain/usecases/create-session_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#5991 [FEATURE] Afficher Pix Orga dans la langue de l'utilisateur enregistrée dans son compte (PIX-5766)
  admin/tests/helpers/setup-intl.js
  certif/app/services/session.js
  certif/tests/helpers/setup-intl.js
  certif/tests/unit/services/session_test.js
  mon-pix/app/services/session.js
  mon-pix/tests/helpers/setup-intl.js
  orga/app/components/auth/login-form.js
  orga/app/controllers/authenticated/certifications.js
  orga/app/routes/application.js
  orga/app/services/current-domain.js
  orga/app/services/session.js
  orga/app/services/url.js
  orga/mirage/config.js
  orga/tests/acceptance/authentication_test.js
  orga/tests/acceptance/invitations-list_test.js
  orga/tests/helpers/setup-intl.js
  orga/tests/helpers/test-init.js
  orga/tests/integration/components/auth/login-form_test.js
  orga/tests/integration/components/auth/register-form_test.js
  orga/tests/integration/components/layout/footer_test.js
  orga/tests/integration/components/layout/sidebar_test.js
  orga/tests/unit/controllers/authenticated/certifications_test.js
  orga/tests/unit/routes/application_test.js
  orga/tests/unit/services/current-domain_test.js
  orga/tests/unit/services/session_test.js
  orga/tests/unit/services/url_test.js
Labels: :rocket: Ready to Merge, team-acces

#6076 [TECH] Injecter les dépendances dans le use-case `start-writing-campaign-assessment-results-to-stream` pour préparer la migration ESM
  api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6047 [TECH] Suppression du feature toggle de la recuperation des resultats pour les centres de certifications habilités (PIX-7828).
  api/lib/config.js
  api/sample.env
  api/tests/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  certif/app/components/members-list.js
  certif/app/controllers/authenticated/team.js
  certif/app/models/feature-toggle.js
  certif/app/models/session.js
  certif/tests/acceptance/session-details_test.js
  certif/tests/acceptance/team_test.js
  certif/tests/integration/components/members-list_test.js
  certif/tests/unit/controllers/team_test.js
  certif/tests/unit/models/session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6090 [FEATURE] Permettre à l'utilisateur de modifier l'url vers l'image du profil cible (PIX-7863)
  admin/app/components/target-profiles/update-target-profile.hbs
  admin/app/components/target-profiles/update-target-profile.js
  admin/tests/unit/components/update-target-profile_test.js
  api/lib/application/target-profiles/index.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/models/TargetProfileForUpdate.js
  api/lib/domain/models/index.js
  api/lib/domain/usecases/update-target-profile.js
  api/lib/domain/validators/target-profile/base-validation.js
  api/lib/infrastructure/repositories/target-profile-for-update-repository.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/integration/infrastructure/repositories/target-profile-for-update-repository_test.js
  api/tests/unit/application/target-profiles/index_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/domain/models/TargetProfileForUpdate_test.js
  api/tests/unit/domain/usecases/update-target-profile_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#6086 [BUGFIX] Afficher toutes les compétences lors de la sélection de tubes sur Pix Admin (PIX-7882).
  admin/app/components/common/tubes-selection.js
  admin/mirage/config.js
  admin/mirage/handlers/frameworks.js
  admin/mirage/serializers/framework.js
  admin/tests/integration/components/common/tubes-selection_test.js
  admin/tests/integration/components/target-profiles/create-target-profile-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6091 [FEATURE] Monter la version de pixUI en v33.1 sur PixOrga (PIX-7894)
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#5858 [FEATURE] Import d'une liste de candidats via l'.ods en anglais (PIX-6685)
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/CertificationCandidate.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/usecases/import-certification-candidates-from-candidates-import-sheet.js
  api/lib/domain/usecases/sessions-mass-import/validate-sessions.js
  api/lib/infrastructure/files/candidates-import/1.5/candidates_import_template.ods
  api/lib/infrastructure/files/candidates-import/CandidateData.js
  api/lib/infrastructure/files/candidates-import/candidates-import-placeholders.js
  api/lib/infrastructure/files/candidates-import/candidates-import-transformation-structures.js
  api/lib/infrastructure/files/candidates-import/fill-candidates-import-sheet.js
  api/lib/infrastructure/utils/ods/read-ods-utils.js
  api/lib/infrastructure/utils/ods/write-ods-utils.js
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-data.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ko-invalid-file.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-ok.ods
  api/tests/acceptance/application/session/files/1.5/import-certification-candidates-reports-categorization-test-special-birthdate-ok.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_extract_birth_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_extract_mandatory_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_extract_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_extract_with_billing_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_extract_with_complementary_certifications_ko_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/attendance_sheet_extract_with_complementary_certifications_ok_test.ods
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-sco.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-all-complementary-certifications-sco.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-billing-columns-complementary.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-billing-columns.ods
  api/tests/integration/infrastructure/utils/ods/files/1.5/candidates_import_template-with-one-complementary-certification-sco.ods
  api/tests/integration/infrastructure/utils/ods/files/fill-candidates-import-sheet_test.js
  api/tests/integration/infrastructure/utils/ods/files/simple-attendance_test.ods
  api/tests/integration/infrastructure/utils/ods/read-ods-utils_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/models/CertificationCandidate_test.js
  api/tests/unit/domain/usecases/import-certification-candidates-from-candidates-import-sheet_test.js
  api/tests/unit/domain/usecases/sessions-mass-import/validate-sessions_test.js
  api/translations/en.json
  api/translations/fr.json
  certif/app/models/session.js
  certif/tests/unit/models/session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6093 [TECH] Utiliser le test helper mockLearningContent à la place de sinon.stub quand c'est nécessaire
  api/tests/integration/scripts/data-generation/generate-certif-cli_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#6018 [TECH] Ajout du lint sur les fichiers de traduction de Certif (PIX-7807).
  certif/.eslintrc.js
  certif/.prettierignore
  certif/package-lock.json
  certif/package.json
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6092 [FEAUTRE] Afficher "Terminé" sur une participation partagé pour une campagne archivé (PIX-5626)
  mon-pix/app/models/campaign-participation-overview.js
  mon-pix/tests/unit/models/campaign-participation-overview_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6097 [TECH] Injection de dépendances pour préparer la migration ESM
  api/lib/application/usecases/checkAdminMemberHasRoleCertif.js
  api/lib/application/usecases/checkAdminMemberHasRoleMetier.js
  api/lib/application/usecases/checkAdminMemberHasRoleSuperAdmin.js
  api/lib/application/usecases/checkAdminMemberHasRoleSupport.js
  api/lib/application/usecases/checkUserBelongsToLearnersOrganization.js
  api/lib/application/usecases/checkUserBelongsToOrganization.js
  api/lib/application/usecases/checkUserBelongsToOrganizationManagingStudents.js
  api/lib/application/usecases/checkUserBelongsToScoOrganizationAndManagesStudents.js
  api/lib/application/usecases/checkUserBelongsToSupOrganizationAndManagesStudents.js
  api/lib/application/usecases/checkUserIsAdminInOrganization.js
  api/lib/application/usecases/checkUserIsMemberOfCertificationCenter.js
  api/lib/application/usecases/checkUserIsMemberOfCertificationCenterSession.js
  api/lib/application/usecases/checkUserOwnsCertificationCourse.js
  api/tests/unit/application/usecases/checkAdminMemberHasRoleCertif_test.js
  api/tests/unit/application/usecases/checkAdminMemberHasRolePixMetier_test.js
  api/tests/unit/application/usecases/checkAdminMemberHasRolePixSupport_test.js
  api/tests/unit/application/usecases/checkAdminMemberHasRoleSuperAdmin_test.js
  api/tests/unit/application/usecases/checkUserBelongsToLearnersOrganization_test.js
  api/tests/unit/application/usecases/checkUserBelongsToOrganizationManagingStudents_test.js
  api/tests/unit/application/usecases/checkUserBelongsToOrganization_test.js
  api/tests/unit/application/usecases/checkUserBelongsToScoOrganizationAndManagesStudents_test.js
  api/tests/unit/application/usecases/checkUserBelongsToSupOrganizationAndManagesStudents_test.js
  api/tests/unit/application/usecases/checkUserIsAdminInOrganization_test.js
  api/tests/unit/application/usecases/checkUserIsMemberOfCertificationCenterSession_test.js
  api/tests/unit/application/usecases/checkUserIsMemberOfCertificationCenter_test.js
  api/tests/unit/application/usecases/checkUserOwnsCertificationCourse_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6098 [TECH] Injection de dépendances pour préparer la migration ESM
  api/lib/domain/usecases/correct-answer-then-update-assessment.js
  api/lib/domain/usecases/create-and-reconcile-user-to-organization-learner.js
  api/lib/domain/usecases/create-campaign.js
  api/lib/domain/usecases/get-attendance-sheet.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/send-verification-code.js
  api/tests/integration/domain/usecases/create-and-reconcile-user-to-organization-learner_test.js
  api/tests/integration/domain/usecases/create-campaign_test.js
  api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
  api/tests/unit/domain/usecases/create-and-reconcile-user-to-organization-learner_test.js
  api/tests/unit/domain/usecases/create-campaign_test.js
  api/tests/unit/domain/usecases/get-attendance-sheet_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
  api/tests/unit/domain/usecases/send-verification-code_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6036 [TECH] S'aligner sur les standards utilisés sur Certif dans Pix App, concernant i18N(PIX-7556)
  mon-pix/app/adapters/application.js
  mon-pix/app/components/dashboard/content.js
  mon-pix/app/components/footer.js
  mon-pix/app/components/inaccessible-campaign.js
  mon-pix/app/components/navbar-header.js
  mon-pix/app/components/signin-form.js
  mon-pix/app/components/user-certifications-detail-header.js
  mon-pix/app/controllers/authenticated/user-account.js
  mon-pix/app/controllers/authenticated/user-account/language.js
  mon-pix/app/models/certification.js
  mon-pix/app/services/current-domain.js
  mon-pix/app/services/session.js
  mon-pix/app/services/url.js
  mon-pix/app/templates/authenticated/user-account.hbs
  mon-pix/tests/integration/components/Sitemap/content_test.js
  mon-pix/tests/integration/components/dashboard/content_test.js
  mon-pix/tests/integration/components/footer_test.js
  mon-pix/tests/integration/components/inaccessible-campaign_test.js
  mon-pix/tests/integration/components/password-reset-demand-form_test.js
  mon-pix/tests/integration/components/reset-password-form_test.js
  mon-pix/tests/integration/components/signin-form_test.js
  mon-pix/tests/integration/components/user-certifications-detail-header_test.js
  mon-pix/tests/unit/adapters/application_test.js
  mon-pix/tests/unit/controllers/authenticated/user-account/language_test.js
  mon-pix/tests/unit/controllers/authenticated/user-account_test.js
  mon-pix/tests/unit/models/certification_test.js
  mon-pix/tests/unit/services/session_test.js
  mon-pix/tests/unit/services/url_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#6094 [TECH] Nettoyage du code inutile lié à l'usage des target-profiles_skills (PIX-6696)
  api/db/database-builder/factory/build-assessment-campaign-for-skills.js
  api/lib/domain/models/TargetProfile.js
  api/lib/domain/usecases/create-target-profile.js
  api/lib/infrastructure/repositories/campaign-repository.js
  api/lib/infrastructure/repositories/campaign/target-profile-for-specifier-repository.js
  api/lib/infrastructure/repositories/target-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/campaign-report-serializer.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/data-generation/target-profiles-migration/migration-test-pro-tab.csv
  api/scripts/data-generation/target-profiles-migration/target-profiles-for-migrations.js
  api/scripts/prod/target-profile-migrations/copy-target-profile-skills-into-campaign-skills.js
  api/tests/acceptance/application/campaigns/campaign-controller_test.js
  api/tests/acceptance/application/users/users-controller-get-campaign-participation-overviews_test.js
  api/tests/acceptance/scripts/target-profile-migrations/convert-target-profiles-into-new-format_test.js
  api/tests/acceptance/scripts/target-profile-migrations/copy-target-profile-skills-into-campaign-skills_test.js
  api/tests/integration/domain/usecases/get-campaign_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign/target-profile-for-specifier-repository_test.js
  api/tests/integration/infrastructure/repositories/learning-content-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
  api/tests/integration/scripts/data-generation/generate-campaign-with-participant_test.js
  api/tests/integration/scripts/data-generation/generate-certif-cli_test.js
  api/tests/tooling/domain-builder/factory/build-target-profile.js
  api/tests/unit/domain/models/TargetProfile_test.js
  api/tests/unit/domain/services/smart-random/skills-filter_test.js
  api/tests/unit/domain/usecases/create-target-profile_test.js
  high-level-tests/e2e/cypress/fixtures/target-profile_tubes.json
  high-level-tests/e2e/cypress/fixtures/target-profiles_skills.json
  high-level-tests/e2e/cypress/integration/pix-app/a11y-authenticated-1.test.js
  high-level-tests/e2e/cypress/integration/pix-app/a11y-authenticated-2.test.js
  high-level-tests/e2e/cypress/integration/pix-app/a11y-not-authenticated.test.js
  high-level-tests/e2e/cypress/support/step_definitions/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#5645 [BUGFIX] Écran de fin de campagne flash : crash si épreuves périmées/archivées (PIX-7106)
  api/lib/domain/services/algorithm-methods/data-fetcher.js
  api/tests/integration/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
  api/tests/unit/domain/services/smart-random/data-fetcher_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team
