Repository 1024pix/pix, pull requests merged in 2023-06, with the labels that each got.

#6291 [FEATURE] Améliorer l'a11y de la page de lancement d'une épreuve chronométrée (PIX-7670).
  mon-pix/.template-lintrc.js
  mon-pix/app/components/timed-challenge-instructions.hbs
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6285 [TECH] Mis à jour des instanciations des Chart sur PixOrga (PIX-8186)
  certif/app/services/locale.js
  mon-pix/app/services/locale.js
  orga/app/components/campaign/charts/participants-by-day.js
  orga/app/components/ui/chart.js
  orga/app/services/locale.js
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#6299 [FEATURE] Toujours afficher le résultat en pourcentage d'une campagne (PIX-7986)
  orga/app/components/campaign/cards/result-average.hbs
  orga/app/components/campaign/cards/stage-average.js
  orga/app/components/campaign/charts/participants-by-stage.hbs
  orga/app/components/campaign/charts/participants-by-stage.js
  orga/app/components/campaign/results/assessment-row.hbs
  orga/app/components/campaign/stage-stars-old.js
  orga/app/components/campaign/stage-stars.js
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/assessment/header.js
  orga/app/components/ui/mastery-percentage-display.hbs
  orga/app/components/ui/progress-bar.hbs
  orga/app/components/ui/progress-bar.js
  orga/app/styles/components/ui/index.scss
  orga/app/styles/components/ui/mastery-percentage-display.scss
  orga/app/styles/globals/panels.scss
  orga/tests/integration/components/campaign/cards/stage_average_test.js
  orga/tests/integration/components/participant/assessment/header_test.js
  orga/tests/integration/components/ui/progress-bar_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6302 [TECH] Revert le ticket Améliorer le style visuel du bloc d'embed d'une épreuve (PIX-8112)
  mon-pix/app/components/challenge-embed-simulator.hbs
  mon-pix/app/styles/components/_challenge-embed-simulator.scss
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app

#6294 [FEATURE] Pix1D - Ajouter la prévisualisation des challenges (PIX-8048)
  api/lib/application/assessments/assessment-controller.js
  api/lib/application/assessments/index.js
  api/lib/domain/usecases/create-preview-assessment.js
  api/lib/domain/usecases/index.js
  api/tests/integration/domain/usecases/create-preview-assessment_test.js
  api/tests/unit/application/assessments/assessment-controller_test.js
  api/tests/unit/application/assessments/index_test.js
  pix1d/app/adapters/assessment.js
  pix1d/app/pods/assessment/challenge/route.js
  pix1d/app/pods/challenge-preview/route.js
  pix1d/app/router.js
  pix1d/mirage/config.js
  pix1d/mirage/factories/challenge.js
  pix1d/tests/acceptance/display-challenge-preview_test.js
  pix1d/tests/unit/routes/assessment-challenge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6303 [FEATURE] Avoir toujours la liste des badges et des logos des éditeurs de CF à jour (PIX-8218).
  admin/app/components/target-profiles/badge-form.hbs
  admin/app/components/trainings/create-or-update-training-form.hbs
Labels: :rocket: Ready to Merge, team-devcomp

#6242 [FEATURE] Création du endpoint pour la suppression de prescrits (PIX-7948)
  api/db/seeds/data/campaigns-pro-builder.js
  api/lib/application/organization-learners-management/index.js
  api/lib/application/organization-learners-management/organization-learners-controller.js
  api/lib/application/security-pre-handlers.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/organization-learners-management/delete-organization-learners.js
  api/lib/infrastructure/repositories/organization-learners-management/campaign-participation-repository.js
  api/lib/infrastructure/repositories/organization-learners-management/organization-learner-repository.js
  api/lib/routes.js
  api/tests/acceptance/application/organization-learners-management/organization-learners-controller_test.js
  api/tests/integration/application/organization-learners-management/index_test.js
  api/tests/integration/infrastructure/repositories/organization-learners-management/campaign-participation-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-learners-management/organization-learner-repository_test.js
  api/tests/unit/domain/usecases/organization-learners-management/delete-organization-learners_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6312 [BUMP] Mise à jour des dépendances vulnérables sur admin
  admin/package-lock.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6298 [FEATURE] Forcer des compétences dans l'algorithme Flash (PIX-8160)
  api/lib/application/scenarios-simulator/index.js
  api/lib/application/scenarios-simulator/scenario-simulator-controller.js
  api/lib/domain/models/FlashAssessmentAlgorithm.js
  api/lib/domain/services/algorithm-methods/flash.js
  api/lib/domain/usecases/simulate-flash-deterministic-assessment-scenario.js
  api/tests/integration/application/scenarios-simulator/scenario-simulator-controller_test.js
  api/tests/integration/domain/services/algorithm-methods/flash_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, certif-next-gen

#6151 [TECH] Documenter le choix de l'injection de dépendances
  docs/adr/0046-injecter-les-dependances-api.md
  docs/api-dependencies.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6304 [TECH] Corriger l'alignement des étoiles dans Pix Orga (PIX-7983)
  orga/app/components/campaign/charts/participants-by-mastery-percentage.js
  orga/app/components/campaign/charts/participants-by-stage.hbs
  orga/app/components/campaign/filter/participation-filters.hbs
  orga/app/components/campaign/filter/participation-filters.js
  orga/app/components/campaign/results/assessment-row.hbs
  orga/app/components/campaign/stage-stars-old.hbs
  orga/app/components/campaign/stage-stars-old.js
  orga/app/components/campaign/stage-stars.hbs
  orga/app/components/campaign/stage-stars.js
  orga/app/components/ui/mastery-percentage-display.hbs
  orga/app/components/ui/mastery-percentage-display.js
  orga/app/styles/components/campaign/charts/participants-by-stage.scss
  orga/app/styles/components/campaign/index.scss
  orga/app/styles/components/campaign/stage-average.scss
  orga/app/styles/components/campaign/stage-stars.scss
  orga/app/styles/components/participation-filters.scss
  orga/app/styles/components/ui/mastery-percentage-display.scss
  orga/tests/integration/components/campaign/filter/participation-filters_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6313 [BUGFIX] Corriger la création de campagne à envoi multiple (PIX-8238)
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  orga/app/components/campaign/create-form.hbs
  orga/app/components/campaign/create-form.js
  orga/tests/unit/components/campaign/create-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6314 [TECH] Gestion de langue manquante sur le kit superviseur (PIX-8243)
  CHANGELOG.md
  admin/package-lock.json
  admin/package.json
  api/lib/infrastructure/utils/pdf/supervisor-kit-pdf.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/utils/pdf/supervisor-kit-pdf_test.js
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6322 [BUGFIX] Permettre à un candidat éligible mais non inscrit à une certif complémentaire de passer la certification (PIX-8257).
  api/lib/domain/models/CertificationCandidate.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: :rocket: Ready to Merge, team-certif

#6243 [FEATURE] Empêcher la soumission du formulaire d'inscription de Pix App si des erreurs n'ont pas été corrigées (PIX-7815)
  mon-pix/app/components/signup-form.js
  mon-pix/tests/integration/components/signup-form_test.js
  mon-pix/tests/unit/components/signup-form_test.js
Labels: :rocket: Ready to Merge, team-acces

#6309 [FEATURE] Améliorer l'accessibilité de la modale de solution des QROC/m (PIX-8189).
  mon-pix/app/components/qroc-solution-panel.hbs
  mon-pix/app/components/qroc-solution-panel.js
  mon-pix/app/components/qrocm-dep-solution-panel.hbs
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/app/components/qrocm-ind-solution-panel.hbs
  mon-pix/app/components/qrocm-ind-solution-panel.js
  mon-pix/app/styles/components/_comparison-window.scss
  mon-pix/app/styles/components/_qrocm-solution-panel.scss
  mon-pix/tests/integration/components/qroc-solution-panel_test.js
  mon-pix/tests/integration/components/qrocm-dep-solution-panel_test.js
  mon-pix/tests/integration/components/qrocm-ind-solution-panel_test.js
  mon-pix/tests/unit/components/qroc-solution-panel_test.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel_test.js
  mon-pix/tests/unit/components/qrocm-ind-solution-panel_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6325 [TECH] Mise à jour du CHANGELOG (PIX-8243)
  CHANGELOG.md
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6327 [BUGFIX] Retourner une erreur dans la méthode getWithComplementaryCertification lorsque le candidat n'existe pas (PIX-8266).
  api/lib/infrastructure/repositories/certification-candidate-repository.js
  api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js
Labels: :rocket: Ready to Merge, team-certif

#6337 [BUGFIX] :ambulance: Hotfix v4.2.1
  CHANGELOG.md
  admin/package-lock.json
  admin/package.json
  api/package-lock.json
  api/package.json
  certif/package-lock.json
  certif/package.json
  high-level-tests/e2e/package-lock.json
  high-level-tests/e2e/package.json
  high-level-tests/load-testing/package-lock.json
  high-level-tests/load-testing/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge

#6335 [TECH] Utiliser toString() au lieu de .string sur les instances SafeString
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/app/components/qrocm-ind-solution-panel.js
  mon-pix/tests/unit/components/markdown-to-html-unsafe_test.js
  mon-pix/tests/unit/components/markdown-to-html_test.js
  mon-pix/tests/unit/components/routes/campaigns/invited/associate-sco-student-form_test.js
  mon-pix/tests/unit/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6300 [FEATURE] Script de migration des paliers seuils en niveaux (PIX-8098)
  api/scripts/prod/target-profile-migrations/extract-need-stages-migration.js
  api/scripts/prod/target-profile-migrations/migrate-stages-to-level.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#6343 [TECH] Suppression de dépendances a la racine inutilisés
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6307 [FEATURE] Amélioration et ajout d'une barre de défilement au menu utilisateur sur Pix Certif (PIX-8154).
  certif/app/components/dropdown/item.hbs
  certif/app/components/user-logged-menu.hbs
  certif/app/styles/components/dropdown.scss
  certif/app/styles/components/user-logged-menu.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/templates/authenticated.hbs
  certif/tests/acceptance/authenticated_test.js
  certif/tests/acceptance/authentication_test.js
  certif/tests/acceptance/session-list_test.js
  certif/tests/integration/components/user-logged-menu_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#6329 [FEATURE] Rapatrie le code de hapi-pino dans l'API
  api/lib/infrastructure/plugins/pino.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/plugins/pino_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6323 [TECH] Monter de version Ember 4.12 sur PixOrga (PIX-8264)
  orga/app/components/campaign/list.js
  orga/app/templates/authenticated/campaigns/list/all-campaigns.hbs
  orga/app/templates/authenticated/campaigns/list/my-campaigns.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/auth/login-form_test.js
  orga/tests/integration/components/auth/login-or-register_test.js
  orga/tests/integration/components/campaign/activity/delete-participation-modal_test.js
  orga/tests/integration/components/campaign/list_test.js
  orga/tests/integration/components/tables/pagination-control_test.js
  orga/tests/integration/components/ui/previous-page-button_test.js
  orga/tests/unit/components/auth/login-or-register_test.js
  orga/tests/unit/controllers/authenticated/sco-organization-participants/list_test.js
  orga/tests/unit/controllers/authenticated/sup-organization-participants/import_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#6334 [BUGFIX] La bonne réponse affichée pour un QCM mélangé n'est pas bonne (PIX-8250)
  mon-pix/app/components/qcm-solution-panel.js
  mon-pix/app/utils/value-as-array-of-boolean.js
  mon-pix/tests/unit/utils/value-as-array-of-boolean_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#6324 [BUGFIX] Exiger les données obligatoires sur la route POST /api/certification-courses (PIX-8262).
  api/lib/application/certification-courses/index.js
  api/tests/acceptance/application/certification-courses/index_test.js
  api/tests/unit/application/certification-courses/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, team-captains

#6344 [FEATURE] Ajout de la colonne isV3Pilot dans la table certification-centers (PIX-8249)
  api/db/migrations/20230605135419_add-is-v3-pilot-column-to-certification-center-table.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, certif-next-gen

#6308 [FEATURE] Filtrer les bonnes réponses utilisateurs des solutions (PIX-8147)
  api/lib/domain/models/Correction.js
  api/lib/domain/models/CorrectionBlockQROCMDep.js
  api/lib/domain/services/solution-service-qrocm-dep.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/serializers/jsonapi/correction-serializer.js
  api/tests/acceptance/application/answers/answer-controller-get-correction_test.js
  api/tests/unit/domain/models/CorrectionBlockQROCMDep_test.js
  api/tests/unit/domain/services/solution-service-qrocm-dep_test.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/correction-serializer_test.js
  mon-pix/app/components/comparison-window.hbs
  mon-pix/app/components/comparison-window.js
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/app/models/correction.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/integration/components/qrocm-dep-solution-panel_test.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6306 [FEATURE] Design des épreuves avec embed auto dans Pix1D (PIX-8100)
  pix1d/app/pods/components/answer-feedback/template.hbs
  pix1d/app/pods/components/answer/template.hbs
  pix1d/app/pods/components/challenge/challenge-embed-simulator/component.js
  pix1d/app/pods/components/challenge/challenge-embed-simulator/template.hbs
  pix1d/app/pods/components/challenge/challenge-instruction/template.hbs
  pix1d/app/pods/components/challenge/challenge-item-auto-reply/component.js
  pix1d/app/pods/components/challenge/challenge-item-auto-reply/template.hbs
  pix1d/app/pods/components/challenge/challenge-item-generic/component.js
  pix1d/app/pods/components/challenge/challenge-statement/component.js
  pix1d/app/pods/components/challenge/challenge-statement/template.hbs
  pix1d/app/pods/components/challenge/item/component.js
  pix1d/app/pods/components/challenge/item/template.hbs
  pix1d/app/styles/app.scss
  pix1d/app/styles/components/challenge-actions.scss
  pix1d/app/styles/components/challenge-embed-simulator.scss
  pix1d/app/styles/components/challenge-instruction.scss
  pix1d/app/styles/components/challenge-item.scss
  pix1d/tests/integration/components/answer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, Design Review OK, 🎒👧🏽👦🏾 Pix1D

#6353 [TECH] Supprimer les warnings sinon.stub
  api/tests/acceptance/scripts/create-users-accounts-for-contest_test.js
  api/tests/integration/domain/usecases/cancel-certification-center-invitation_test.js
  api/tests/integration/infrastructure/repositories/admin-member-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-places-capacity-repository_test.js
  api/tests/unit/domain/usecases/account-recovery/update-user-for-account-recovery_test.js
  api/tests/unit/domain/usecases/update-campaign-details-management_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6332 [TECH] Proposer l'injection de dépendance pour les répositories
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/correction-repository.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/utils/dependency-injection.js
  api/tests/unit/infrastructure/repositories/correction-repository_test.js
  api/tests/unit/infrastructure/utils/dependency-injection_test.js
Labels: :rocket: Ready to Merge, cross-team

#6358 [TECH] Suppression de déprécations de faker
  admin/mirage/factories/session.js
  admin/mirage/factories/training.js
  admin/mirage/factories/user.js
  certif/mirage/factories/certification-candidate.js
  certif/mirage/factories/certification-report.js
  certif/mirage/factories/country.js
  certif/mirage/factories/division.js
  certif/mirage/factories/session.js
  certif/mirage/factories/student.js
  mon-pix/mirage/factories/assessment.js
  mon-pix/mirage/factories/campaign.js
  mon-pix/mirage/factories/certification-course.js
  mon-pix/mirage/factories/challenge.js
  mon-pix/mirage/factories/competence-result.js
  mon-pix/mirage/factories/correction.js
  mon-pix/mirage/factories/tutorial.js
  mon-pix/mirage/factories/user.js
  orga/mirage/factories/campaign-participation.js
  orga/mirage/factories/campaign-profile.js
  orga/mirage/factories/campaign.js
  orga/mirage/factories/division.js
  orga/mirage/factories/organization-participant.js
  orga/mirage/factories/user.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6328 [FEATURE] Afficher si l'envoi multiple est dispo dans les paramètres d'une campagne d'évaluation (PIX-8198)
  orga/app/components/campaign/settings/view.hbs
  orga/app/components/campaign/settings/view.js
  orga/tests/integration/components/campaign/settings/view_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6359 [TECH] Trier le fichier index des use-cases.
  api/lib/domain/usecases/index.js
Labels: :rocket: Ready to Merge, cross-team

#6360 [BUGFIX] Corrige les jobs pgboss
  api/lib/infrastructure/jobs/JobQueue.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6365 [BUGFIX] Un test d'acceptance pix-admin échoue aléatoirement (PIX-8341)
  admin/testem.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#6366 [TECH] Augmenter le temps d'inactivité du browser sur pix-admin
  admin/testem.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#6362 [TECH] Mise à jour du changelog après le hotfix 4.2.1
  CHANGELOG.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6361 [FEATURE] Amélioration du wording lors de la création d'une campagne d'évaluation (PIX-8293)
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6266 [FEATURE] Empêcher la double soumission des formulaires d'authentification (PIX-8153)
  mon-pix/app/components/authentication/login-or-register-oidc.hbs
  mon-pix/app/components/authentication/login-or-register-oidc.js
  mon-pix/app/components/authentication/oidc-reconciliation.hbs
  mon-pix/app/components/authentication/oidc-reconciliation.js
  mon-pix/app/components/routes/campaigns/sco-form.hbs
  mon-pix/app/components/routes/campaigns/sco-form.js
  mon-pix/app/components/routes/login-form.hbs
  mon-pix/app/components/routes/register-form.hbs
  mon-pix/app/components/routes/register-form.js
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signin-form.js
  mon-pix/tests/unit/components/authentication/login-or-register-oidc_test.js
  mon-pix/tests/unit/components/authentication/oidc-reconciliation_test.js
  mon-pix/tests/unit/components/register-form_test.js
  mon-pix/tests/unit/components/routes/campaigns/sco-form_test.js
  mon-pix/tests/unit/components/routes/login-form_test.js
  mon-pix/tests/unit/components/signin-form_test.js
Labels: :rocket: Ready to Merge, team-acces

#6369 [FEATURE] Script de rollback de migrations des paliers des PC (PIX-8338)
  api/scripts/prod/target-profile-migrations/revert-stages-to-threshold.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#6378 [BUGFIX] Utilise un mot de passe statique dans les tests
  mon-pix/mirage/factories/user.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6352 [FEATURE] Ajout de la version dans la DB pour les certification-courses (PIX-8299).
  api/db/database-builder/factory/build-answered-not-completed-certification-assessment.js
  api/db/database-builder/factory/build-certification-course.js
  api/db/migrations/20230612092952_add-version-column-on-certification-course.js
  api/db/seeds/data/certification/certification-courses-builder.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/tests/integration/scripts/certification/get-cpf-import-status-from-xml_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6383 [BUGFIX] Informer l'utilisateur de la maintenance sur pix1d (PIX-8336)
  pix1d/maintenance_page.html
  pix1d/maintenance_scheduled.html
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6391 [TECH] Remise de l'ancienne requête de publication de sessions en masse (PIX-8365).
  api/lib/infrastructure/repositories/certification-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, certif-next-gen

#6367 [TECH] Automatiquement importer les usecases pour leur injecter les dépendances
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/utils/import-named-exports-from-dir.js
  api/tests/integration/infrastructure/utils/imports/import-named-exports-from-dir_test.js
  api/tests/integration/infrastructure/utils/imports/sample-conflict/a.js
  api/tests/integration/infrastructure/utils/imports/sample-conflict/b.js
  api/tests/integration/infrastructure/utils/imports/sample/a.js
  api/tests/integration/infrastructure/utils/imports/sample/b-c-d.js
  api/tests/integration/infrastructure/utils/imports/sample/dir/e.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6373 [FEATURE] Filtrer les épreuves périmées dans les simulateurs (PIX-8328).
  api/lib/application/scenarios-simulator/index.js
  api/lib/application/scenarios-simulator/scenario-simulator-controller.js
  api/lib/domain/usecases/simulate-flash-deterministic-assessment-scenario.js
  api/lib/infrastructure/datasources/learning-content/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/unit/infrastructure/datasources/learning-content/challenge-datasource_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, certif-next-gen

#6371 [FEATURE] Ajout de la checkbox principale sur la liste des participants
  orga/app/components/organization-participant/list.hbs
  orga/app/components/organization-participant/list.js
  orga/app/components/selectable-list.hbs
  orga/app/components/selectable-list.js
  orga/tests/integration/components/selectable-list_test.js
  orga/tests/unit/components/selectable-list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#6397 [TECH] Utiliser l'attribut embedHeight pour setter la hauteur d'un embed (PIX-8370)
  pix1d/app/pods/components/challenge/challenge-embed-simulator/component.js
  pix1d/app/pods/components/challenge/challenge-embed-simulator/template.hbs
  pix1d/app/pods/components/challenge/item/template.hbs
  pix1d/app/styles/components/challenge-embed-simulator.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6400 [BUMP] Mise à jour de @ember/test-helpers et de @ember/qunit sur les applications
  admin/package-lock.json
  admin/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  pix1d/package-lock.json
  pix1d/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, dependencies

#6399 [TECH] Refacto de la méthode privée "#" en "_"
  api/lib/infrastructure/utils/pseudo-random.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, certif-next-gen

#6381 [TECH] Remplacer le champ isV2Certification par version dans les certification (PIX-8298)
  api/db/database-builder/factory/build-answered-not-completed-certification-assessment.js
  api/db/database-builder/factory/build-certification-course.js
  api/db/migrations/20230614145126_remove-isV2Certification-from-certification-courses.js
  api/db/seeds/data/certification/certification-courses-builder.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/lib/domain/models/CertificationAssessment.js
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/models/CertificationVersion.js
  api/lib/domain/services/placement-profile-service.js
  api/lib/domain/services/scoring/scoring-certification-service.js
  api/lib/domain/usecases/get-certification-details.js
  api/lib/infrastructure/repositories/certification-assessment-repository.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/scripts/data-generation/generate-certifications-for-organization.js
  api/tests/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/integration/domain/services/pick-certification-challenge_test.js
  api/tests/integration/domain/services/placement-profile-service_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-assessment.js
  api/tests/tooling/domain-builder/factory/build-certification-course.js
  api/tests/unit/domain/events/handle-auto-jury_test.js
  api/tests/unit/domain/events/handle-certification-rescoring_test.js
  api/tests/unit/domain/models/CertificationAssessment_test.js
  api/tests/unit/domain/models/CertificationResult_test.js
  api/tests/unit/domain/services/scoring/scoring-certification-service_test.js
  api/tests/unit/domain/usecases/deneutralize-challenge_test.js
  api/tests/unit/domain/usecases/get-certification-details_test.js
  api/tests/unit/domain/usecases/neutralize-challenge_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6333 [BUGFIX] Corriger les urls de la documentation des Organisations en fonction de certains TAGS (PIX-8271)
  api/scripts/prod/update-documentation-url.js
  api/tests/integration/scripts/prod/update-documentation-url_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6406 [TECH] Revert partiel de la PR 6346 - Passage de mission linéaire Pix1D (PIX-7693)
  api/db/database-builder/factory/build-activity.js
  api/db/database-builder/factory/build-answer.js
  api/db/database-builder/factory/index.js
  api/db/migrations/20230606174700_add-activity-id-on-answer.js
  api/db/migrations/20230616090242_delete-activity-id-in-answers-table.js
  api/lib/domain/models/Activity.js
  api/lib/domain/models/Answer.js
  api/lib/domain/usecases/correct-answer.js
  api/lib/domain/usecases/get-next-challenge-for-pix1d.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/activity-repository.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/integration/domain/usecases/correct-answer_test.js
  api/tests/integration/domain/usecases/get-next-challenge-for-pix1d_test.js
  api/tests/integration/infrastructure/repositories/activity-repository_test.js
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-activity.js
  api/tests/tooling/domain-builder/factory/build-answer.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/Answer_test.js
  api/tests/unit/domain/usecases/correct-answer_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-pix1d_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains, 🎒👧🏽👦🏾 Pix1D

#6398 [BUGFIX] Harmoniser la taille des cartes des contenus formatifs (PIX-8349).
  mon-pix/app/styles/components/_training-card.scss
Labels: :rocket: Ready to Merge, Func Review OK, team-devcomp

#6415 [TECH] Afficher l'avancement des migrations de BDD
  api/package.json
Labels: :rocket: Ready to Merge, team-captains

#6295 [FEATURE] Traduire les erreurs lors de l'import de candidats sur Pix Certif (PIX-7967).
  api/db/seeds/data/common/common-builder.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/lib/application/error-manager.js
  api/lib/domain/constants/certification-candidates-errors.js
  api/lib/domain/errors.js
  api/lib/domain/services/certification-candidates-ods-service.js
  api/lib/domain/services/certification-cpf-service.js
  api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/services/certification-cpf-service_test.js
  certif/app/components/import-candidates.js
  certif/mirage/config.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6408 [FEATURE] Identification des sessions NextGen en base de données (pix-8374)
  api/db/database-builder/factory/build-certification-center.js
  api/db/database-builder/factory/build-session.js
  api/db/migrations/20230616082943_add-version-field-in-session.js
  api/lib/domain/models/CertificationCenter.js
  api/lib/domain/models/Session.js
  api/lib/domain/usecases/create-session.js
  api/lib/infrastructure/repositories/certification-center-repository.js
  api/tests/acceptance/application/certification-centers/certification-center-controller_test.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-create-sessions_test.js
  api/tests/integration/infrastructure/repositories/sessions/session-repository_test.js
  api/tests/tooling/domain-builder/factory/build-certification-center.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/domain/models/Session_test.js
  api/tests/unit/domain/usecases/create-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6388 [FEATURE] Renvoyer le pourcentage d'acquisition d'un Résultat Thématique à la fin d'une campagne (PIX-8058).
  api/lib/domain/models/BadgeCriterionForCalculation.js
  api/lib/domain/models/BadgeForCalculation.js
  api/lib/domain/read-models/participant-results/BadgeResult.js
  api/lib/domain/usecases/get-user-campaign-assessment-result.js
  api/lib/infrastructure/repositories/badge-for-calculation-repository.js
  api/lib/infrastructure/serializers/jsonapi/participant-result-serializer.js
  api/tests/acceptance/application/users/get-user-campaign-assessment-result_test.js
  api/tests/tooling/domain-builder/factory/build-badge-criterion-for-calculation.js
  api/tests/tooling/domain-builder/factory/build-badge-for-calculation.js
  api/tests/unit/domain/models/BadgeCriterionForCalculation_test.js
  api/tests/unit/domain/models/BadgeForCalculation_test.js
  api/tests/unit/domain/read-models/participant-results/BadgeResult_test.js
  api/tests/unit/domain/usecases/get-user-campaign-assessment-result_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6419 [TECH] Mise à jour de Pix-UI en V36 sur pix-certif (PIX-8389).
  certif/package-lock.json
  certif/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6412 [BUGFIX] QCU: Mention "La bonne réponse est : ..." incorrecte (PIX-8385)
  mon-pix/app/components/qcu-solution-panel.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#6385 [FEATURE] Traduire les erreurs lors de la création d'un candidat via la modale sur Pix Certif (PIX-8320).
  api/lib/application/error-manager.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/add-certification-candidate-to-session.js
  api/lib/domain/usecases/correct-candidate-identity-in-certification-course.js
  api/tests/unit/domain/errors_test.js
  api/tests/unit/domain/usecases/add-certification-candidate-to-session_test.js
  certif/app/components/enrolled-candidates.js
  certif/tests/acceptance/session-details-certification-candidates_test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6428 [TECH] Corriger la v4.4.0 dans le CHANGELOG
  CHANGELOG.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6384 [FEATURE] Afficher les corrections QROCM-dep sous les champs en erreur (PIX-8263)
  mon-pix/app/components/qrocm-dep-solution-panel.hbs
  mon-pix/app/components/qrocm-dep-solution-panel.js
  mon-pix/tests/acceptance/challenge-item-qrocm_test.js
  mon-pix/tests/integration/components/qrocm-dep-solution-panel_test.js
  mon-pix/tests/unit/components/qrocm-dep-solution-panel_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, Design Review OK

#6431 [TECH] Création des seeds pour la certif next-gen (PIX-8402).
  api/db/seeds/data/common/tooling/certification-center-tooling.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/db/seeds/data/team-certification/data-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, certif-next-gen

#6437 [BUGFIX] Les métriques systèmes ne sont plus tracées (PIX-8411)
  api/lib/infrastructure/plugins/pino.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6414 [TECH] Analyser la progression des migrations lors des MEP (PIX-8336)
  api/.psqlrc
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6438 [BUGFIX] Les signalements ne peuvent plus être ajoutés à la finalisation de la session (PIX-8416).
  certif/app/components/issue-report-modal/add-issue-report-modal.hbs
  certif/app/components/issue-report-modal/add-issue-report-modal.js
  certif/app/components/issue-report-modal/candidate-information-change-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/non-blocking-candidate-issue-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/non-blocking-technical-issue-certification-issue-report-fields.hbs
  certif/app/components/issue-report-modal/signature-issue-report-fields.hbs
  certif/tests/acceptance/session-finalization_test.js
  certif/tests/integration/components/issue-report-modal/candidate-information-change-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/non-blocking-candidate-issue-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/non-blocking-technical-issue-certification-issue-report-fields_test.js
  certif/tests/integration/components/issue-report-modal/signature-issue-report-fields_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6429 [TECH] Remplacer eslint-plugin-node par son successeur eslint-plugin-n.
  api/.eslintrc.yaml
  api/index.js
  api/lib/.eslintrc.cjs
  api/lib/application/healthcheck/healthcheck-controller.js
  api/lib/config.js
  api/lib/infrastructure/utils/import-named-exports-from-directory.js
  api/lib/infrastructure/validate-environment-variables.js
  api/package-lock.json
  api/package.json
  api/scripts/.eslintrc.yaml
  api/scripts/certification/verify-certificate-code-service_script.js
  api/scripts/data-generation/generate-certif-cli.js
  api/tests/integration/infrastructure/utils/imports/import-named-exports-from-directory_test.js
  api/tests/test-helper.js
  api/worker.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6435 [BUGFIX] Améliorer le design de l'input sur l'écran de réponse des QROC sur Pix-App (PIX-8316)
  mon-pix/app/styles/components/_qroc-solution-panel.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, Design Review OK

#6421 [FEATURE] Ajoute la possibilité de réinitialiser la liste de participants sélectionnés (PIX-8391)
  orga/app/components/in-element.hbs
  orga/app/components/in-element.js
  orga/app/components/organization-participant/list.hbs
  orga/app/components/organization-participant/list.js
  orga/app/components/selectable-list.hbs
  orga/app/components/selectable-list.js
  orga/app/components/table/pagination-control.js
  orga/app/styles/components/ui/action-bar.scss
  orga/tests/integration/components/in-element_test.js
  orga/tests/integration/components/organization-participant/list_test.js
  orga/tests/unit/components/selectable-list_test.js
  orga/tests/unit/components/table/pagination-control_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#6433 [TECH] Uniformisation des `scripts` des `package.json`
  1d/package-lock.json
  1d/package.json
  admin/package-lock.json
  admin/package.json
  api/.depcheckrc
  api/package-lock.json
  api/package.json
  certif/package-lock.json
  certif/package.json
  mon-pix/README.md
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6440 [TECH] Corriger l'import des fichiers d'un dossier sur Windows.
  api/lib/infrastructure/utils/import-named-exports-from-directory.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6430 [TECH] Refactorer l'utilitaire de barreling
  api/db/database-builder/factory/index.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/utils/import-named-exports-from-directory.js
  api/tests/integration/infrastructure/utils/imports/import-named-exports-from-directory_test.js
  api/tests/integration/infrastructure/utils/imports/sample/b-c-d.js
  api/tests/integration/infrastructure/utils/imports/sample/directory/e.js
  api/tests/integration/infrastructure/utils/imports/sample/e
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6407 [TECH] Faciliter la création de migrations BDD
  api/db/template.js
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#6413 [FEATURE] Identification de la version des certification-courses (PIX-8273).
  api/lib/domain/models/CertificationCourse.js
  api/lib/domain/services/placement-profile-service.js
  api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/tooling/domain-builder/factory/build-session.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6446 [TECH] Suppression des scripts `dev` des applis fronts
  admin/package.json
  certif/package.json
  mon-pix/package.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6427 [TECH] Ajouter une config pour jouer Pix1d sur safari (PIX-8403)
  1d/ember-cli-build.js
  api/lib/domain/usecases/get-next-challenge-for-pix1d.js
  api/tests/integration/domain/usecases/get-next-challenge-for-pix1d_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-pix1d_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6260 [FEATURE] Ajoute le détachement d'un profil cible d'une organisation (PIX-7028)
  admin/app/adapters/target-profile.js
  admin/app/components/organizations/list-items.hbs
  admin/app/components/target-profiles/organizations.hbs
  admin/app/controllers/authenticated/target-profiles/target-profile/organizations.js
  admin/app/templates/authenticated/target-profiles/target-profile/organizations.hbs
  admin/tests/integration/components/target-profiles/organizations_test.js
  admin/tests/integration/controllers/authenticated/target-profiles/target-profile/organizations_test.js
  admin/tests/unit/adapters/target-profile_test.js
  admin/tests/unit/components/organizations/list-items_test.js
  api/lib/application/target-profiles-management/index.js
  api/lib/application/target-profiles-management/target-profile-management-controller.js
  api/lib/domain/models/target-profile-management/TargetProfile.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/target-profile-management/detach-organizations-from-target-profile.js
  api/lib/infrastructure/repositories/target-profile-management/target-profile-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profiles-management/target-profile-detach-organizations-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/target-profiles-management/index_test.js
  api/tests/integration/application/target-profiles-management/index_test.js
  api/tests/integration/infrastructure/repositories/target-profile-management/target-profile-repository_test.js
  api/tests/unit/application/target-profiles-management/target-profile-management-controller_test.js
  api/tests/unit/domain/models/target-profile-management/TargetProfile_test.js
  api/tests/unit/domain/usecases/target-profile-management/detach-organizations-from-target-profile_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-management/target-profile-detach-organizations-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6436 [TECH] Amélioration des tests en utilisant Testing Library (PIX-8412)
  orga/tests/integration/components/campaign/cards/participants-count_test.js
  orga/tests/integration/components/campaign/cards/result_average_test.js
  orga/tests/integration/components/campaign/cards/shared-count_test.js
  orga/tests/integration/components/campaign/charts/participants-by-mastery-percentage_test.js
  orga/tests/integration/components/campaign/charts/participants-by-status_test.js
  orga/tests/integration/components/campaign/charts/result-distribution_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, no-review-app

#6450 [FEATURE] Pix1D - Amélioration de la page d'introduction de mission
  1d/app/pods/mission/template.hbs
  1d/app/styles/app.scss
  1d/app/styles/components/mission.scss
  1d/app/styles/globals/_fonts.scss
  1d/public/fonts/Nunito/Nunito-VariableFont_wght.ttf
  1d/tests/acceptance/display-mission_test.js
  1d/tests/acceptance/start-mission_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6452 [FEATURE] Ajout d'une modale de confirmation quand on détache une orga d'un profil cible (PIX-7030)
  admin/app/components/organizations/list-items.hbs
  admin/app/components/organizations/list-items.js
  admin/app/components/target-profiles/organizations.hbs
  admin/tests/integration/components/organizations/list-items_test.js
  admin/tests/integration/components/routes/authenticated/organizations/list-items_test.js
  admin/tests/integration/components/target-profiles/organizations_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6445 [FEATURE] Utiliser le nouvel algorithme pour choisir les épreuves lors d'une certif v3 (PIX-8426)
  api/lib/application/assessments/assessment-controller.js
  api/lib/domain/usecases/get-next-challenge-for-certification.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-certification_spec.js
  api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6453 [FEATURE] Afficher les résultats thématiques en lacunes lorsqu'ils sont certifiantes ou non (PIX-8438)
  api/db/seeds/data/badges-builder.js
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.js
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/components/routes/campaigns/assessment/skill-review_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6447 [FEATURE] Améliorer l'affichage des solutions des QROCm (PIX-6221).
  mon-pix/app/components/qrocm-dep-solution-panel.hbs
  mon-pix/app/components/qrocm-ind-solution-panel.hbs
  mon-pix/app/styles/components/_qrocm-solution-panel.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, Design Review OK

#6441 [TECH] Linter les traduction de Pix Admin
  .eslintrc.yaml
  admin/.eslintrc.js
  admin/.prettierignore
  admin/config/linter-translation-order.cjs
  admin/package.json
  admin/translations/en.json
  admin/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6449 [FEATURE] Terminer la session de certif V3 après un nombre précis de questions (PIX-8436).
  api/lib/domain/constants.js
  api/lib/domain/models/AssessmentSimulator.js
  api/lib/domain/models/FlashAssessmentAlgorithm.js
  api/lib/domain/usecases/get-next-challenge-for-certification.js
  api/lib/domain/usecases/simulate-flash-deterministic-assessment-scenario.js
  api/tests/unit/domain/models/AssessmentSimulator_test.js
  api/tests/unit/domain/models/FlashAssessmentAlgorithm_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6434 [TECH] Mise à jour des configurations de vscode
  .eslintignore
  .gitignore
  .vscode/extensions.json
  .vscode/sample.launch.json
  .vscode/sample.settings.json
  INSTALLATION.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6460 [TECH] Nettoyage des fichiers de l'ajout de la modale pour détacher un profil cible (PIX-8450)
  admin/app/components/organizations/list-items.hbs
  admin/tests/integration/components/organizations/list-items_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6448 [FEATURE] Ajouter un aria-label sur les liens d'aide sur les épreuves sur Pix-App (PIX-8076)
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6463 [FEATURE] Modifier le texte sur la double mire SSO PIX-8407
  mon-pix/tests/integration/components/authentication/login-or-register-oidc_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-acces

#6458 [FEATURE] Pix1D - Prévenir l'élève s'il n'a pas terminé son activité à la validation (PIX-8281)
  1d/app/pods/components/answer-feedback/component.js
  1d/app/pods/components/answer-feedback/template.hbs
  1d/app/pods/components/challenge/challenge-actions/template.hbs
  1d/app/pods/components/challenge/item/component.js
  1d/app/pods/components/challenge/item/template.hbs
  1d/app/pods/components/warning-feedback/template.hbs
  1d/app/styles/app.scss
  1d/app/styles/components/answer.scss
  1d/app/styles/components/challenge-actions.scss
  1d/app/styles/components/mission.scss
  1d/app/styles/components/warning.scss
  1d/app/styles/globals/_buttons.scss
  1d/mirage/config.js
  1d/tests/acceptance/display-answer-modal_test.js
  1d/tests/acceptance/display-warning-modal_test.js
  1d/tests/integration/components/answer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6469 [CLEANUP] Supprime la version en doublon en haut du changelog
  CHANGELOG.md
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team

#6473 [BUGFIX] Corrige le script test:api:watch cassé depuis le passage aux modules ESM
  api/nodemon.json
  api/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6320 [FEATURE] Retravailler l'accessibilité des signalements de problème en épreuve (PIX-7668).
  mon-pix/app/components/feedback-panel.hbs
  mon-pix/tests/acceptance/challenge-feedback_test.js
  mon-pix/tests/integration/components/feedback-panel_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, Design Review OK

#6464 [TECH] Supprimer les faux positifs sur les tests automatisés en utilisant VScode (PIX-8663).
  api/tests/integration/domain/services/organization-learners-csv-service_test.js
  api/tests/integration/domain/services/organization-learners-xml-service_test.js
  api/tests/integration/scripts/prod/archive-campaigns_test.js
Labels: :rocket: Ready to Merge, cross-team

#6443 [TECH] Créer un jeu de données pour une session demarrée (PIX-8409)
  api/db/seeds/data/common/tooling/organization-tooling.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/db/seeds/data/team-certification/data-builder.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#6487 [FEATURE] Pix1D - Ajouter un bouton de retour vers l'accueil à la page de fin de mission (Pix-8481)
  1d/app/pods/assessment/results/template.hbs
  1d/app/pods/components/mission-card/template.hbs
  1d/app/pods/mission/template.hbs
  1d/app/styles/components/card.scss
  1d/app/styles/components/mission.scss
  1d/app/styles/globals/_buttons.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 Pix1D

#6401 [TECH] Mettre à jour les seeds de la Team Accès (PIX-8208)
  api/db/seeds/data/common/common-builder.js
  api/db/seeds/data/team-acces/build-blocked-users.js
  api/db/seeds/data/team-acces/build-pix-admin-roles.js
  api/db/seeds/data/team-acces/build-temporary-blocked-user.js
  api/db/seeds/data/team-acces/build-users.js
  api/db/seeds/data/team-acces/constants.js
  api/db/seeds/data/team-acces/data-builder.js
  api/db/seeds/seed.js
Labels: :rocket: Ready to Merge, team-acces

#6229 [BREAKING] Ajouter la fonctionnalité d'activer/désactiver facilement un SSO OIDC (PIX-7749)
  api/db/database-builder/factory/build-authentication-method.js
  api/db/seeds/data/organizations-pro-builder.js
  api/db/seeds/data/users-builder.js
  api/lib/application/authentication/oidc/index.js
  api/lib/application/authentication/oidc/oidc-controller.js
  api/lib/application/users/index.js
  api/lib/config.js
  api/lib/domain/constants/oidc-identity-providers.js
  api/lib/domain/services/authentication/authentication-service-registry.js
  api/lib/domain/services/authentication/cnav-oidc-authentication-service.js
  api/lib/domain/services/authentication/fwb-oidc-authentication-service.js
  api/lib/domain/services/authentication/oidc-authentication-service.js
  api/lib/domain/services/authentication/pole-emploi-oidc-authentication-service.js
  api/lib/domain/usecases/get-identity-providers.js
  api/lib/domain/usecases/remove-authentication-method.js
  api/lib/domain/validators/organization-with-tags-and-target-profiles-script.js
  api/lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/lib/infrastructure/repositories/pole-emploi-sending-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/sample.env
  api/tests/acceptance/application/authentication/oidc/authentication-url-route-get_test.js
  api/tests/acceptance/application/authentication/oidc/reconcile-route-post_test.js
  api/tests/acceptance/application/authentication/oidc/token-route-post_test.js
  api/tests/acceptance/application/authentication/oidc/users-route-post_test.js
  api/tests/integration/domain/services/authentication/pole-emploi-oidc-authentication-service_test.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-to-join-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-authentication-method.js
  api/tests/unit/application/authentication/oidc/oidc-controller_test.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/domain/models/AuthenticationMethod_test.js
  api/tests/unit/domain/services/authentication/authentication-service-registry_test.js
  api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
  api/tests/unit/domain/usecases/authentication/authenticate-oidc-user_test.js
  api/tests/unit/domain/usecases/get-identity-providers_test.js
  api/tests/unit/domain/usecases/organizations-administration/update-organization-information_test.js
  api/tests/unit/domain/usecases/reassign-authentication-method-to-another-user_test.js
  api/tests/unit/domain/usecases/remove-authentication-method_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/authentication-methods-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#6461 [FEATURE] Afficher la notion de progressivité sur les résultats thématiques en lacunes non certifiants (PIX-8057)
  mon-pix/app/components/badge-card.hbs
  mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
  mon-pix/app/models/campaign-participation-badge.js
  mon-pix/app/styles/components/_badge-card.scss
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/skill-review_test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/tests/unit/components/routes/campaigns/assessment/skill-review_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6493 [BUGFIX] Trace seulement les vraies erreurs dans l'API (PIX-8484)
  api/lib/infrastructure/plugins/pino.js
  api/package-lock.json
  api/package.json
  api/tests/integration/infrastructure/plugins/pino_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#6492 [TECH] Partager la configuration ESLint
  .eslintrc.cjs
  admin/package-lock.json
  admin/package.json
  api/.depcheckrc
  api/.eslintrc.cjs
  api/package-lock.json
  api/package.json
  certif/package-lock.json
  certif/package.json
  config/linter-translation-order.cjs
  mon-pix/package-lock.json
  mon-pix/package.json
  orga/package-lock.json
  orga/package.json
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#6500 [BUGFIX] Ajout de la version de session pour l'import en masse (PIX-8510).
  api/lib/domain/models/Session.js
  api/tests/acceptance/application/certification-centers/sessions-mass-import/certification-centers-controller-post-create-sessions_test.js
Labels: :rocket: Ready to Merge, team-certif, certif-next-gen

#6495 [BUGFIX] Rectifier l'alignement des réponses d'un QROCm passé (PIX-8488).
  mon-pix/app/styles/components/_qrocm-solution-panel.scss
Labels: :rocket: Ready to Merge, team-evaluation, Design Review OK

#6411 [TECH] Utiliser les nouvelles seeds pour la team xp eval (PIX-8225).
  api/db/seeds/data/team-evaluation/data-builder.js
  api/db/seeds/seed.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#6483 [FEATURE] Ajoute le champ areKnowledgeElementsResettable dans la table target-profiles (PIX-8486)
  api/db/migrations/20230623135203_add-column-areKnowledgeElementsResettable-in-target-profiles-table.js
Labels: :rocket: Ready to Merge, team-prescription, team-devcomp

#6444 [FEATURE] Permettre aux organisation type PRO de supprimer des prescrits (PIX-6616)
  orga/app/adapters/organization-participant.js
  orga/app/components/in-element.hbs
  orga/app/components/in-element.js
  orga/app/components/organization-participant/action-bar.hbs
  orga/app/components/organization-participant/deletion-modal.hbs
  orga/app/components/organization-participant/deletion-modal.js
  orga/app/components/organization-participant/learner-filters.hbs
  orga/app/components/organization-participant/list.hbs
  orga/app/components/organization-participant/list.js
  orga/app/components/organization-participant/table-headers.hbs
  orga/app/components/organization-participant/table-row.hbs
  orga/app/components/selectable-list.hbs
  orga/app/components/selectable-list.js
  orga/app/components/table/pagination-control.js
  orga/app/components/ui/action-bar.hbs
  orga/app/controllers/authenticated/organization-participants/list.js
  orga/app/routes/authenticated/organization-participants/list.js
  orga/app/styles/app.scss
  orga/app/styles/components/ui/action-bar.scss
  orga/app/styles/pages/authenticated/organization-participants/deletion-modal.scss
  orga/app/styles/pages/authenticated/organization-participants/list.scss
  orga/app/templates/authenticated/organization-participants/list.hbs
  orga/config/environment.js
  orga/tests/integration/components/in-element_test.js
  orga/tests/integration/components/organization-participant/list_test.js
  orga/tests/integration/components/selectable-list_test.js
  orga/tests/integration/components/ui/action-bar_test.js
  orga/tests/unit/components/selectable-list_test.js
  orga/tests/unit/components/table/pagination-control_test.js
  orga/tests/unit/controllers/authenticated/organization-participants/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6292 [ADMIN] Permettre de déplacer une méthode de connexion via SSO vers un autre utilisateur (PIX-7738)
  admin/app/components/users/user-detail-personal-information/authentication-method.hbs
  admin/app/components/users/user-detail-personal-information/authentication-method.js
  admin/app/controllers/authenticated/users/get/information.js
  admin/tests/acceptance/authenticated/users/authentication-method_test.js
  admin/tests/integration/components/users/user-detail-personal-information/authentication-method_test.js
  admin/tests/integration/components/users/user-detail-personal-information_test.js
  admin/tests/unit/components/users/user-detail-personal-information/authentication-method_test.js
  api/db/database-builder/factory/build-authentication-method.js
  api/db/database-builder/factory/build-user.js
  api/db/migrations/20201125103011_migrate-samlid-to-authentication-methods.js
  api/db/seeds/data/organizations-sco-builder.js
  api/lib/application/users/index.js
  api/lib/domain/constants/identity-providers.js
  api/lib/domain/constants/saml-identity-providers.js
  api/lib/domain/models/AuthenticationMethod.js
  api/lib/domain/models/User.js
  api/lib/domain/services/obfuscation-service.js
  api/lib/domain/services/user-service.js
  api/lib/domain/usecases/account-recovery/update-user-for-account-recovery.js
  api/lib/domain/usecases/add-pix-authentication-method-by-email.js
  api/lib/domain/usecases/authenticate-external-user.js
  api/lib/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user.js
  api/lib/domain/usecases/get-external-authentication-redirection-url.js
  api/lib/domain/usecases/remove-authentication-method.js
  api/lib/domain/usecases/send-verification-code.js
  api/lib/domain/usecases/update-expired-password.js
  api/lib/domain/validators/organization-with-tags-and-target-profiles-script.js
  api/lib/infrastructure/repositories/authentication-method-repository.js
  api/lib/infrastructure/repositories/sco-organization-participant-repository.js
  api/lib/infrastructure/repositories/user-repository.js
  api/tests/acceptance/application/authentication/authentication-route_test.js
  api/tests/acceptance/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/acceptance/application/users/get-user-authentication-methods-route-get_test.js
  api/tests/acceptance/application/users/reassign-authentication-methods-route-put_test.js
  api/tests/acceptance/application/users/users-controller-remove-authentication-method_test.js
  api/tests/integration/domain/services/user-service_test.js
  api/tests/integration/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user_test.js
  api/tests/integration/infrastructure/repositories/authentication-method-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-for-admin-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-learner-follow-up/organization-learner-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/domain-builder/factory/build-authentication-method.js
  api/tests/unit/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/AuthenticationMethod_test.js
  api/tests/unit/domain/services/obfuscation-service_test.js
  api/tests/unit/domain/usecases/account-recovery/update-user-for-account-recovery_test.js
  api/tests/unit/domain/usecases/add-pix-authentication-method-by-email_test.js
  api/tests/unit/domain/usecases/authenticate-external-user_test.js
  api/tests/unit/domain/usecases/get-external-authentication-redirection-url_test.js
  api/tests/unit/domain/usecases/remove-authentication-method_test.js
  api/tests/unit/domain/usecases/send-verification-code_test.js
  api/tests/unit/domain/usecases/update-expired-password_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-for-admin-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
Labels: :rocket: Ready to Merge, team-acces

#6505 [BUGFIX] Ajouter la possibilité de trier la page élèves par Classe (PIX-8479)
  api/lib/application/organizations/index.js
  api/lib/infrastructure/repositories/sco-organization-participant-repository.js
  api/tests/integration/infrastructure/repositories/sco-organization-participant-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  orga/app/components/sco-organization-participant/list.hbs
  orga/app/controllers/authenticated/sco-organization-participants/list.js
  orga/app/routes/authenticated/sco-organization-participants/list.js
  orga/app/templates/authenticated/sco-organization-participants/list.hbs
  orga/tests/integration/components/sco-organization-participant/list_test.js
  orga/tests/unit/controllers/authenticated/sco-organization-participants/list_test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#6477 [FEATURE] Empêcher un challenge d'être enregistré deux fois pendant une certif V3 (PIX-8470).
  api/lib/domain/models/CertificationChallenge.js
  api/lib/domain/usecases/get-next-challenge-for-certification.js
  api/lib/infrastructure/repositories/certification-challenge-repository.js
  api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6454 [TECH] Ajouter des tests au prehandler assessment-authorization (PIX-8022).
  api/tests/unit/application/preHandlers/assessment-authorization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#6496 [FEATURE] Retourner le nouveau champ areKnowledgeElementsResettable dans l'API
  api/db/database-builder/factory/build-target-profile.js
  api/lib/application/target-profiles/target-profile-controller.js
  api/lib/domain/models/TargetProfileForAdmin.js
  api/lib/infrastructure/repositories/target-profile-for-admin-repository.js
  api/lib/infrastructure/serializers/jsonapi/target-profile-for-admin-serializer.js
  api/tests/integration/infrastructure/repositories/target-profile-for-admin-repository_test.js
  api/tests/unit/application/target-profiles/target-profile-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/target-profile-for-admin-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-prescription, team-devcomp

#6488 [TECH] Récupération du dernier challenge vu lors d'une reprise de session (PIX-8258).
  api/lib/domain/models/CertificationChallenge.js
  api/lib/domain/usecases/get-next-challenge-for-certification.js
  api/lib/infrastructure/repositories/certification-challenge-repository.js
  api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-for-certification_test.js
  api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
  api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, certif-next-gen

#6509 [BUGFIX] Permettre de revenir dans une organisation PRO après suppression (Pix-8527)
  api/db/migrations/20230630132006_add-deleted-at-for-one-active-organization-learners.js
  api/db/seeds/data/campaigns-pro-builder.js
  api/lib/infrastructure/repositories/campaign-participant-repository.js
  api/lib/infrastructure/repositories/organization-learners-management/campaign-participation-repository.js
  api/tests/integration/infrastructure/repositories/campaign-participant-repository_test.js
  api/tests/integration/infrastructure/repositories/organization-learners-management/campaign-participation-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription
