Repository 1024pix/pix, pull requests merged in 2024-12, with the labels that each got.

#10632 [FEATURE] Utiliser PixIcon dans Pix App - Partie 1 (PIX-14775).
  high-level-tests/e2e/cypress/support/step_definitions/assessment.js
  mon-pix/app/components/account-recovery/student-information-form.hbs
  mon-pix/app/components/assessment-banner.hbs
  mon-pix/app/components/authentication/new-password-input/password-rule.gjs
  mon-pix/app/components/authentication/new-password-input/password-rule.scss
  mon-pix/app/components/certification-banners/congratulations-certification-banner.hbs
  mon-pix/app/components/certification-joiner.hbs
  mon-pix/app/components/certification-starter.hbs
  mon-pix/app/components/certifications/certification-ender.hbs
  mon-pix/app/components/challenge-actions.hbs
  mon-pix/app/components/challenge-embed-simulator.hbs
  mon-pix/app/components/challenge-illustration.hbs
  mon-pix/app/components/challenge-item/challenge-item-qcm.hbs
  mon-pix/app/components/challenge-item/challenge-item-qcu.hbs
  mon-pix/app/components/challenge-item/challenge-item-qroc.hbs
  mon-pix/app/components/challenge-item/challenge-item-qrocm.hbs
  mon-pix/app/components/challenge-statement.hbs
  mon-pix/app/components/feedback-panel-v3.hbs
  mon-pix/app/components/feedback-panel.hbs
  mon-pix/app/components/hexagon-score.hbs
  mon-pix/app/components/inaccessible-campaign.hbs
  mon-pix/app/components/module/_recap.scss
  mon-pix/app/components/module/element/_download.scss
  mon-pix/app/components/module/element/download.gjs
  mon-pix/app/components/module/recap.gjs
  mon-pix/app/components/navbar-burger-menu.hbs
  mon-pix/app/components/navbar-mobile-header.hbs
  mon-pix/app/components/new-information.hbs
  mon-pix/app/components/result-item.hbs
  mon-pix/app/components/routes/register-form.hbs
  mon-pix/app/components/sitemap/content.hbs
  mon-pix/app/components/user-certifications-detail-header.hbs
  mon-pix/app/components/user-certifications-detail-result.hbs
  mon-pix/app/components/user-logged-menu.hbs
  mon-pix/app/styles/components/_assessment-banner.scss
  mon-pix/app/styles/components/_certification-joiner.scss
  mon-pix/app/styles/components/_certification-starter.scss
  mon-pix/app/styles/components/_challenge-embed-simulator.scss
  mon-pix/app/styles/components/_challenge-item.scss
  mon-pix/app/styles/components/_congratulations-certification-banner.scss
  mon-pix/app/styles/components/_feedback-panel-v3.scss
  mon-pix/app/styles/components/_feedback-panel.scss
  mon-pix/app/styles/components/_hexagon-score.scss
  mon-pix/app/styles/components/_learning-more-tutorial-panel.scss
  mon-pix/app/styles/components/_navbar-burger-menu.scss
  mon-pix/app/styles/components/_navbar-mobile-header.scss
  mon-pix/app/styles/components/_new-information.scss
  mon-pix/app/styles/components/_user-certifications-detail-header.scss
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/styles/components/_user-logged-menu.scss
  mon-pix/app/styles/components/certifications/certification-ender.scss
  mon-pix/app/styles/components/sitemap/_content.scss
  mon-pix/app/styles/pages/_campaign-landing-page.scss
  mon-pix/app/styles/pages/_fill-in-certificate-verification-code.scss
  mon-pix/app/templates/fill-in-certificate-verification-code.hbs
  mon-pix/app/utils/result-icon.js
  mon-pix/tests/integration/components/certification-banners/congratulations-certification-banner-test.js
  mon-pix/tests/integration/components/module/download-test.gjs
  mon-pix/tests/unit/components/result-item-test.js
Labels: :rocket: Ready to Merge, cross-team

#10663 [TECH] Support du format CSV pour le script de rescoring de certification (PIX-15366).
  api/scripts/certification/rescore-certifications.js
  api/tests/integration/scripts/certification/rescore-certifications_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-captains

#10673 [BUGFIX] :bug: Plus d'erreur 500 si une épreuve est à la fois répondue et signalée (PIX-15484)
  api/src/certification/evaluation/domain/usecases/get-next-challenge.js
  api/src/shared/infrastructure/repositories/answer-repository.js
  api/tests/certification/evaluation/unit/domain/usecases/get-next-challenge_test.js
  api/tests/shared/integration/infrastructure/repositories/answer-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10637 [FEATURE] Pouvoir faire une recherche exacte d'utilisateurs dans Pix Admin (PIX-9567)
  admin/app/controllers/authenticated/users/list.js
  admin/app/routes/authenticated/users/list.js
  admin/app/styles/authenticated/users/list.scss
  admin/app/templates/authenticated/users/list.hbs
  admin/tests/acceptance/authenticated/users/list-test.js
  admin/tests/unit/routes/authenticated/users/list-test.js
  admin/translations/en.json
  admin/translations/fr.json
  api/src/identity-access-management/application/user/user.admin.controller.js
  api/src/identity-access-management/application/user/user.admin.route.js
  api/src/identity-access-management/domain/constants/user-query.js
  api/src/identity-access-management/domain/usecases/find-paginated-filtered-users.usecase.js
  api/src/identity-access-management/infrastructure/repositories/user.repository.js
  api/tests/identity-access-management/acceptance/application/user/user.admin.route.test.js
  api/tests/identity-access-management/integration/application/user/user.admin.route.test.js
  api/tests/identity-access-management/integration/infrastructure/repositories/user.repository.test.js
  api/tests/identity-access-management/unit/application/user/user.admin.controller.test.js
  api/tests/identity-access-management/unit/domain/usecases/find-paginated-filtered-users.usecase.test.js
Labels: :rocket: Ready to Merge, team-acces

#10681 [FEATURE] Appeler l'API d'anonymisation de compte à partir de la modale de confirmation (PIX-14914)
  mon-pix/app/components/user-account/delete-account-section.gjs
  mon-pix/app/components/user-account/delete-account-section.scss
  mon-pix/tests/integration/components/user-account/delete-account-section-test.gjs
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10697 [BUGFIX] Ne pas appeler le usecase "reward user" si l'utlilisateur n'est pas connecte (PIX-15528)
  api/src/evaluation/application/answers/answer-controller.js
  api/src/prescription/organization-learner/domain/usecases/find-organization-learners-with-participations.js
  api/src/quest/domain/usecases/reward-user.js
  api/tests/evaluation/unit/application/answers/answer-controller_test.js
  api/tests/prescription/organization-learner/unit/domain/usecases/find-organization-learners-with-participations_test.js
  api/tests/quest/unit/domain/usecases/reward-user_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10698 [BUGFIX] Impossible de patcher les acquis en recette (PIX-15533)
  api/src/learning-content/infrastructure/repositories/area-repository.js
  api/src/learning-content/infrastructure/repositories/challenge-repository.js
  api/src/learning-content/infrastructure/repositories/competence-repository.js
  api/src/learning-content/infrastructure/repositories/course-repository.js
  api/src/learning-content/infrastructure/repositories/framework-repository.js
  api/src/learning-content/infrastructure/repositories/learning-content-repository.js
  api/src/learning-content/infrastructure/repositories/mission-repository.js
  api/src/learning-content/infrastructure/repositories/skill-repository.js
  api/src/learning-content/infrastructure/repositories/thematic-repository.js
  api/src/learning-content/infrastructure/repositories/tube-repository.js
  api/src/learning-content/infrastructure/repositories/tutorial-repository.js
  api/tests/learning-content/integration/infrastructure/repositories/skill-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#10685 [FEATURE] cacher les infos d'une participation supprimée (Pix-14303)
  admin/app/adapters/user-participation.js
  admin/app/components/users/campaign-participations.gjs
  admin/app/models/user-participation.js
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/users/get-test.js
  admin/tests/integration/components/users/campaign-participations-test.gjs
  api/src/prescription/campaign-participation/domain/models/CampaignParticipationForUserManagement.js
  api/src/prescription/campaign-participation/infrastructure/repositories/participations-for-user-management-repository.js
  api/src/prescription/campaign-participation/infrastructure/serializers/jsonapi/campaign-participation-for-user-management-serializer.js
  api/tests/prescription/campaign-participation/acceptance/application/admin-campaign-participation-route_test.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/participations-for-user-management-repository_test.js
  api/tests/prescription/campaign-participation/unit/infrastructure/serializers/jsonapi/campaign-participation-for-user-management-serializer_test.js
  api/tests/tooling/domain-builder/factory/build-campaign-participation-for-user-management.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10686 [BUGFIX] Corriger la mise à jour trop tôt du rôle d'un membre sur Pix Orga (PIX-11534)
  orga/app/components/team/members-list-item.hbs
  orga/app/components/team/members-list-item.js
  orga/tests/integration/components/team/members-list-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10691 [FEATURE] Permettre de naviguer dans le module en cliquant sur les étapes de la sidebar (PIX-15397)
  mon-pix/app/components/module/_navbar.scss
  mon-pix/app/components/module/grain.gjs
  mon-pix/app/components/module/navbar.gjs
  mon-pix/app/components/module/passage.gjs
  mon-pix/tests/integration/components/module/grain_test.gjs
  mon-pix/tests/integration/components/module/navbar_test.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#10494 [TECH] Migration de PixAdmin / Composants communs et layout (PIX-15221)
  admin/app/components/common/tick-or-cross.gjs
  admin/app/components/common/tubes-details/tube.gjs
  admin/app/components/common/tubes-selection/tube.gjs
  admin/app/components/layout/breadcrumb.gjs
  admin/app/components/layout/menu-bar/entry.gjs
  admin/app/components/layout/menu-bar/index.gjs
  admin/app/styles/components/common/tubes-selection.scss
  admin/app/styles/components/layout/breadcrumb.scss
  admin/app/styles/components/layout/menu-bar.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#10696 [FEATURE] Telecharger via Pix les resultats de sessions via POST (PIX-15514)
  api/src/certification/results/application/certification-results-controller.js
  api/src/certification/results/application/certification-results-route.js
  api/tests/certification/results/acceptance/application/certification-results-route_test.js
  api/tests/certification/results/unit/application/certification-results-controller_test.js
  api/tests/certification/results/unit/application/certification-results-route_test.js
  mon-pix/app/components/download-session-results.gjs
  mon-pix/app/services/file-saver.js
  mon-pix/tests/integration/components/download-session-results-test.gjs
  mon-pix/tests/unit/services/file-saver-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-prescription

#10661 [FEATURE] Supprimer les learners précédent l'ajout de l'import à format (Pix-15428)
  api/src/organizational-entities/application/http-error-mapper-configuration.js
  api/src/organizational-entities/application/organization/organization.admin.controller.js
  api/src/organizational-entities/domain/errors.js
  api/src/organizational-entities/domain/models/OrganizationFeature.js
  api/src/organizational-entities/domain/usecases/add-organization-feature-in-batch.js
  api/src/organizational-entities/domain/usecases/index.js
  api/src/organizational-entities/infrastructure/repositories/organization-feature-repository.js
  api/src/prescription/learner-management/application/api/learners-api.js
  api/src/prescription/learner-management/domain/usecases/find-organization-learners-before-import-feature.js
  api/src/prescription/learner-management/infrastructure/repositories/organization-learner-repository.js
  api/tests/organizational-entities/integration/application/organization/organization.admin.route.test.js
  api/tests/organizational-entities/integration/infrastructure/repositories/organization-feature-repository_test.js
  api/tests/organizational-entities/unit/application/organization/organization.admin.controller.test.js
  api/tests/organizational-entities/unit/domain/models/OrganizationFeature_test.js
  api/tests/organizational-entities/unit/domain/usecases/add-organization-feature-in-batch_test.js
  api/tests/prescription/learner-management/integration/infrastructure/repositories/organization-learner-repository_test.js
  api/tests/prescription/learner-management/unit/application/api/learners-api_test.js
  api/tests/prescription/learner-management/unit/domain/usecases/find-organization-learners-before-import-feature_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#10702 [FEATURE] Pouvoir logger en debug sur un scope réduit (PIX-15534)
  api/sample.env
  api/src/shared/config.js
  api/src/shared/infrastructure/utils/logger.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#10700 [TECH] Migrer la route POST /api/admin/users/{id}/remove-authentication dans src (PIX-15518)
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/src/identity-access-management/application/user/user.admin.controller.js
  api/src/identity-access-management/application/user/user.admin.route.js
  api/src/identity-access-management/domain/usecases/remove-authentication-method.usecase.js
  api/tests/acceptance/application/users/users-controller-remove-authentication-method_test.js
  api/tests/identity-access-management/acceptance/application/user/user.admin.route.test.js
  api/tests/identity-access-management/integration/application/user/user.admin.route.test.js
  api/tests/identity-access-management/unit/application/user/user.admin.controller.test.js
  api/tests/identity-access-management/unit/domain/usecases/remove-authentication-method.usecase.test.js
  api/tests/integration/application/users/user-controller_test.js
  api/tests/unit/application/users/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, Bounded-context-migration

#10711 [TECH] Modifier le type de la colonne reward ID de la table Profile Rewards (PIX-15546).
  api/db/migrations/20240820101213_add-profile-rewards-table.js
  api/db/migrations/20241204091429_alter-profile-rewards-columns.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#10706 [FEATURE] Modifier les couleurs de l'espace surveillant sur Pix Certif (PIX-15549).
  certif/app/components/login-session-supervisor/footer.scss
  certif/app/components/login-session-supervisor/form.scss
  certif/app/components/login-session-supervisor/header.scss
  certif/app/components/login-session-supervisor/index.gjs
  certif/app/components/login-session-supervisor/index.scss
  certif/app/styles/components/session-supervising/candidate-list.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, Design Review OK

#10678 [TECH] Suppression des paramètres non utilisés de l'algo flash (PIX-15475).
  admin/app/components/administration/certification/flash-algorithm-configuration/form.gjs
  admin/app/components/administration/certification/flash-algorithm-configuration/index.gjs
  admin/app/models/flash-algorithm-configuration.js
  admin/tests/integration/components/administration/certification/flash-algorithm-configuration_test.gjs
  admin/tests/unit/adapters/flash-algorithm-configuration-test.js
  admin/tests/unit/components/administration/certification/flash-algorithm-configuration-test.js
  admin/translations/en.json
  admin/translations/fr.json
  api/db/database-builder/factory/build-flash-algorithm-configuration.js
  api/db/migrations/20241128152506_remove-unused-columns-in-flash-algorithm-configurations-table.js
  api/db/seeds/data/team-certification/data-builder.js
  api/lib/domain/usecases/get-next-challenge-for-campaign-assessment.js
  api/scripts/certification/next-gen/generate-flash-algorithm-configuration.js
  api/src/certification/flash-certification/application/flash-assessment-configuration-route.js
  api/src/certification/flash-certification/domain/models/FlashAssessmentAlgorithm.js
  api/src/certification/flash-certification/domain/models/FlashAssessmentAlgorithmForcedCompetencesRule.js
  api/src/certification/flash-certification/domain/models/FlashAssessmentAlgorithmPassageByAllCompetencesRule.js
  api/src/certification/flash-certification/domain/models/FlashAssessmentSuccessRateHandler.js
  api/src/certification/flash-certification/domain/models/FlashAssessmentSuccessRateHandlerFixedStrategy.js
  api/src/certification/flash-certification/domain/services/algorithm-methods/flash.js
  api/src/certification/flash-certification/infrastructure/serializers/flash-algorithm-configuration-serializer.js
  api/src/certification/shared/domain/models/FlashAssessmentAlgorithmConfiguration.js
  api/tests/certification/evaluation/unit/domain/services/scoring/scoring-v3_test.js
  api/tests/certification/evaluation/unit/domain/usecases/get-next-challenge_test.js
  api/tests/certification/flash-certification/acceptance/application/flash-assessment-configuration-route_test.js
  api/tests/certification/flash-certification/integration/application/flash-assessment-configuration-controller_test.js
  api/tests/certification/flash-certification/integration/infrastructure/repositories/flash-algorithm-configuration-repository_test.js
  api/tests/certification/flash-certification/unit/domain/models/FlashAssessmentAlgorithmForcedCompetencesRule_test.js
  api/tests/certification/flash-certification/unit/domain/models/FlashAssessmentAlgorithmPassageByAllCompetencesRule_test.js
  api/tests/certification/flash-certification/unit/domain/models/FlashAssessmentSuccessRateHandler_test.js
  api/tests/certification/flash-certification/unit/domain/services/algorithm-methods/flash_test.js
  api/tests/certification/flash-certification/unit/domain/usecases/update-active-flash-assessment-configuration_test.js
  api/tests/certification/flash-certification/unit/infrastructure/serializers/flash-algorithm-configuration-serializer_test.js
  api/tests/certification/scoring/integration/application/services/scoring-degradation-service_test.js
  api/tests/certification/shared/integration/infrastructure/repositories/flash-algorithm-configuration-repository_test.js
  api/tests/certification/shared/unit/domain/models/FlashAssessmentAlgorithm_test.js
  api/tests/integration/scripts/certification/next-gen/generate-flash-algorithm-configuration_test.js
  api/tests/tooling/domain-builder/factory/build-flash-algorithm-configuration.js
  api/tests/tooling/domain-builder/factory/build-flash-assessment-algorithm-success-rate-handler.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10677 [TECH] Migrer la route de mise à jour Has Seen Assessment Instructions (PIX-14725).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/src/evaluation/application/users/index.js
  api/src/evaluation/application/users/user-controller.js
  api/src/evaluation/domain/usecases/remember-user-has-seen-assessment-instructions.js
  api/src/evaluation/infrastructure/repositories/user-repository.js
  api/src/identity-access-management/application/api/users-api.js
  api/src/identity-access-management/domain/usecases/mark-assessment-instructions-info-as-seen.usecase.js
  api/tests/evaluation/unit/application/users/user-controller_test.js
  api/tests/evaluation/unit/domain/usecases/remember-user-has-seen-assessment-instructions_test.js
  api/tests/identity-access-management/integration/domain/usecases/mark-assessment-instructions-info-as-seen.usecase.test.js
  api/tests/unit/application/users/user-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10684 [TECH] Appliquer le nouveau nommage des composants sur Pix Admin (PIX-14606)
  admin/app/components/administration/certification/sco-whitelist-configuration.gjs
  admin/app/components/administration/certification/scoring-simulator.gjs
  admin/app/components/administration/common/learning-content.gjs
  admin/app/components/campaigns/update.gjs
  admin/app/components/common/tubes-details/area.gjs
  admin/app/components/common/tubes-details/competence.gjs
  admin/app/components/common/tubes-selection/areas.gjs
  admin/app/components/common/tubes-selection/competence.gjs
  admin/app/components/complementary-certifications/attach-badges/badges/list.gjs
  admin/app/components/complementary-certifications/target-profiles/information.gjs
  admin/app/components/login-form.gjs
  admin/app/components/organizations/information-section-view.gjs
  admin/app/components/target-profiles/badge-form/criteria.gjs
  admin/app/components/target-profiles/edit-target-profile-form.gjs
  admin/app/components/target-profiles/insights.gjs
  admin/app/components/users/user-overview.gjs
  admin/app/styles/components/common/tubes-selection.scss
  admin/app/styles/components/target-profiles/insights.scss
  admin/app/templates/authenticated/tools.hbs
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#10693 [TECH] Migration du usecase `computeCertificability`dans le BC Prescription (PIX-15342)
  api/lib/domain/usecases/generate-username-with-temporary-password.js
  api/lib/domain/usecases/update-organization-learner-dependent-user-password.js
  api/lib/infrastructure/repositories/organization-learner-repository.js
  api/src/identity-access-management/domain/usecases/get-account-recovery-details.usecase.js
  api/src/identity-access-management/domain/usecases/index.js
  api/src/prescription/learner-management/application/jobs/compute-certificability-job-controller.js
  api/src/prescription/learner-management/domain/errors.js
  api/src/prescription/learner-management/domain/usecases/compute-organization-learner-certificability.js
  api/src/prescription/learner-management/domain/usecases/index.js
  api/src/prescription/learner-management/infrastructure/repositories/organization-learner-repository.js
  api/src/shared/application/usecases/checkUserBelongsToLearnersOrganization.js
  api/src/shared/domain/errors.js
  api/tests/identity-access-management/unit/domain/usecases/get-account-recovery-details.usecase.test.js
  api/tests/integration/infrastructure/repositories/organization-learner-repository_test.js
  api/tests/prescription/learner-management/integration/infrastructure/repositories/organization-learner-repository_test.js
  api/tests/prescription/learner-management/unit/application/jobs/compute-certificability-job-controller_test.js
  api/tests/prescription/organization-learner/unit/domain/usecases/compute-organization-learner-certificability_test.js
  api/tests/shared/integration/domain/services/user-service_test.js
  api/tests/shared/unit/application/usecases/checkUserBelongsToLearnersOrganization_test.js
  api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
  api/tests/unit/domain/usecases/update-organization-learner-dependent-user-password_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription, Bounded-context-migration

#10716 [TECH] Ajout de monitoring sur api/token (PIX-15565)
  api/src/identity-access-management/application/monitor-pre-handlers.js
  api/src/identity-access-management/application/token/token.route.js
  api/src/identity-access-management/infrastructure/utils/crypto.js
  api/tests/identity-access-management/unit/application/monitor-pre-handlers.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, team-captains

#10715 [TECH] Supprimer l'action qui vérifie que Scalingo a bien la version de Node.js
  .github/workflows/check-node-version-availability-on-scalingo.yml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#10622 [FEATURE] Correction typo module chatgpt-parle-francais
  api/src/devcomp/infrastructure/datasources/learning-content/modules/chatgpt-parle-francais.json
Labels: :rocket: Ready to Merge, team-devcomp, contribution-modulix

#10658 [TECH] Suppression de l'ancien design des pages d'authentification (PIX-15327)
  api/sample.env
  api/src/shared/config.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature
  high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature
  mon-pix/app/components/password-reset-demand-form.hbs
  mon-pix/app/components/password-reset-demand-form.js
  mon-pix/app/components/reset-password-form.hbs
  mon-pix/app/components/reset-password-form.js
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signin-form.js
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/components/signup-form.js
  mon-pix/app/controllers/authentication/login.js
  mon-pix/app/controllers/inscription/inscription.js
  mon-pix/app/controllers/password-reset-demand.js
  mon-pix/app/controllers/reset-password.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/models/password-reset-demand.js
  mon-pix/app/routes/reset-password.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_password-reset-demand-form.scss
  mon-pix/app/styles/components/_reset-password-form.scss
  mon-pix/app/styles/components/_signup-form.scss
  mon-pix/app/styles/pages/_inscription.scss
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/app/templates/authentication/login.hbs
  mon-pix/app/templates/inscription/inscription.hbs
  mon-pix/app/templates/password-reset-demand.hbs
  mon-pix/app/templates/reset-password.hbs
  mon-pix/mirage/models/password-reset-demand.js
  mon-pix/tests/acceptance/authentication/authentication-redirections-test.js
  mon-pix/tests/acceptance/authentication/login-test.js
  mon-pix/tests/acceptance/authentication/password-reset-demand-form-test.js
  mon-pix/tests/acceptance/authentication/reset-password-form-test.js
  mon-pix/tests/acceptance/authentication/signup-test.js
  mon-pix/tests/acceptance/authentication/sso-selection-test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection-test.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/integration/components/password-reset-demand-form-test.js
  mon-pix/tests/integration/components/reset-password-form-test.js
  mon-pix/tests/integration/components/signin-form-test.js
  mon-pix/tests/integration/components/signup-form-test.js
  mon-pix/tests/unit/components/password-reset-demand-form-test.js
  mon-pix/tests/unit/components/reset-password-form-test.js
  mon-pix/tests/unit/components/signin-form-test.js
  mon-pix/tests/unit/components/signup-form-test.js
  mon-pix/tests/unit/models/password-reset-demand-test.js
  mon-pix/tests/unit/routes/reset-password-test.js
  mon-pix/tests/unit/services/feature-toggles-test.js
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10721 [FEATURE] Ajouter un prehandler pour la route de récupération d'une liste d'attestations (PIX-15593)
  api/src/prescription/organization-learner/application/organization-learners-route.js
  api/tests/prescription/organization-learner/acceptance/application/organization-learner-route_test.js
  api/tests/prescription/organization-learner/unit/application/organization-learners-route_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-prescription

#10722 [BUGFIX] Rajouter un fond derrière le bloc d'alerte d'une épreuve focus (PIX-15545).
  mon-pix/app/styles/pages/_challenge.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10680 [FEATURE] Ajout du Pix Navigation dans Pix Certif (PIX-14554).
  certif/app/components/add-student-list.hbs
  certif/app/components/communication-banner.hbs
  certif/app/components/layout/banners.gjs
  certif/app/components/layout/sidebar.gjs
  certif/app/components/members-list.hbs
  certif/app/components/sessions/session-details/enrolled-candidates/index.gjs
  certif/app/components/sessions/session-list.gjs
  certif/app/components/team/invitations-list.hbs
  certif/app/components/user-logged-menu.hbs
  certif/app/components/user-logged-menu.js
  certif/app/styles/app.scss
  certif/app/styles/components/add-issue-report-modal.scss
  certif/app/styles/components/add-student-list.scss
  certif/app/styles/components/layout/banners.scss
  certif/app/styles/components/layout/footer.scss
  certif/app/styles/components/layout/sidebar.scss
  certif/app/styles/components/user-logged-menu.scss
  certif/app/styles/globals/tables.scss
  certif/app/styles/globals/texts.scss
  certif/app/styles/pages/authenticated.scss
  certif/app/styles/pages/authenticated/sessions/add-student.scss
  certif/app/styles/pages/authenticated/sessions/import.scss
  certif/app/styles/pages/authenticated/sessions/list-items.scss
  certif/app/templates/application.hbs
  certif/app/templates/authenticated.hbs
  certif/app/templates/authenticated/sessions/import.hbs
  certif/app/templates/logout.hbs
  certif/app/templates/session-supervising.hbs
  certif/public/certif-logo.svg
  certif/tests/acceptance/authenticated-test.js
  certif/tests/acceptance/authentication-test.js
  certif/tests/acceptance/join-test.js
  certif/tests/acceptance/routes/join-test.js
  certif/tests/acceptance/session-list-test.js
  certif/tests/acceptance/team/list/list-test.js
  certif/tests/integration/components/communication-banner-test.js
  certif/tests/integration/components/layout/banners_test.gjs
  certif/tests/integration/components/layout/sidebar_test.gjs
  certif/tests/integration/components/user-logged-menu-test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, Design Review OK

#10719 [TECH] Changement de l'URL de recuperation des resultats de certification (PIX-15515).
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/services/session-results-link-service.js
  api/sample.env
  api/src/certification/results/application/certification-results-controller.js
  api/src/certification/results/application/certification-results-route.js
  api/src/certification/results/domain/services/session-results-link-service.js
  api/src/shared/config.js
  api/src/shared/domain/services/token-service.js
  api/tests/acceptance/application/session/session-controller-generate-session-results-download-link_test.js
  api/tests/certification/results/acceptance/application/certification-results-route_test.js
  api/tests/certification/results/unit/application/certification-results-route_test.js
  api/tests/certification/results/unit/domain/services/session-results-link-service_test.js
  api/tests/identity-access-management/unit/domain/usecases/create-user.usecase.test.js
  api/tests/identity-access-management/unit/domain/usecases/validate-user-account-email.usecase.test.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  api/tests/shared/unit/domain/services/token-service_test.js
  api/tests/shared/unit/infrastructure/utils/url-builder_test.js
  api/tests/shared/unit/mail/domain/email-default-variables_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/services/session-results-link-service_test.js
  api/tests/unit/domain/usecases/create-and-reconcile-user-to-organization-learner_test.js
  api/tests/unit/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/unit/infrastructure/externals/pole-emploi/PoleEmploiPayload_test.js
Labels: :rocket: Ready to Merge, team-certif

#10726 [BUGFIX] Mission: alt des illustrations (PIX-15601)
  api/src/school/infrastructure/repositories/mission-repository.js
  api/tests/school/integration/infrastructure/repositories/mission-repository_test.js
  junior/app/templates/identified/missions/mission/introduction.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#10725 [FEATURE] Ajouter l'entrée `Statistiques` pour les organisations ayant la feature sur PixOrga (PIX-15453)
  orga/app/components/layout/sidebar.hbs
  orga/app/components/layout/sidebar.js
  orga/app/models/prescriber.js
  orga/app/router.js
  orga/app/routes/authenticated/statistics.js
  orga/app/services/current-user.js
  orga/tests/integration/components/layout/sidebar-test.js
  orga/tests/unit/models/prescriber-test.js
  orga/tests/unit/routes/authenticated/statistics-test.js
  orga/tests/unit/services/current-user-test.js
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10665 [FEATURE] Intégrer le nouvelle navigation sur PixOrga (PIX-15369)
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  orga/app/components/layout/organization-places-or-credit-info.gjs
  orga/app/components/layout/sidebar.hbs
  orga/app/components/layout/sidebar.js
  orga/app/components/layout/user-logged-menu.hbs
  orga/app/components/layout/user-logged-menu.js
  orga/app/styles/app.scss
  orga/app/styles/components/layout/organization-places-or-credit-info.scss
  orga/app/styles/components/layout/sidebar.scss
  orga/app/styles/globals/pages.scss
  orga/app/styles/pages/authenticated.scss
  orga/app/styles/pages/authenticated/preselect-target-profile.scss
  orga/app/templates/authenticated.hbs
  orga/app/templates/login.hbs
  orga/public/pix-orga-color.svg
  orga/public/pix-orga.svg
  orga/tests/acceptance/authentication-test.js
  orga/tests/acceptance/campaign-creation-test.js
  orga/tests/acceptance/switch-organization-test.js
  orga/tests/integration/components/layout/organization-places-or-credit-info_test.gjs
  orga/tests/integration/components/layout/sidebar-test.js
  orga/tests/integration/components/layout/user-logged-menu-test.js
  orga/tests/unit/components/user-logged-menu-test.js
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10727 [TECH] Mise à jour des icônes dans admnistration de PixAdmin (PIX-15604)
  admin/app/components/administration/common/learning-content.gjs
  admin/app/components/organizations/places.gjs
  admin/app/components/target-profiles/badge-form/criteria.gjs
  admin/app/components/target-profiles/insights.gjs
  admin/app/components/target-profiles/stages.gjs
  admin/app/components/trainings/create-training-triggers.gjs
  admin/app/templates/authenticated/certification-centers/list.hbs
  admin/app/templates/authenticated/organizations/list.hbs
  admin/app/templates/authenticated/target-profiles/list.hbs
  admin/app/templates/authenticated/trainings/list.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#10704 [TECH] Migrer la route PATCH /api/admin/certification-center-memberships/{id} dans src (PIX-15537)
  api/lib/application/certification-center-memberships/certification-center-membership-controller.js
  api/lib/application/certification-center-memberships/index.js
  api/src/team/application/certification-center-membership/certification-center-membership.admin.controller.js
  api/src/team/application/certification-center-membership/certification-center-membership.admin.route.js
  api/src/team/application/routes.js
  api/src/team/domain/usecases/update-certification-center-membership.usecase.js
  api/tests/acceptance/application/certification-center-memberships/certification-center-membership-controller_test.js
  api/tests/team/acceptance/application/certification-center-membership/certification-center-membership.admin.route.test.js
  api/tests/team/acceptance/application/certification-center-membership/certification-center-membership.route.test.js
  api/tests/team/unit/domain/usecases/update-certification-center-membership_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, Bounded-context-migration

#10728 [BUGFIX] MAJ l'interface lors de l'import JSON d'un profil-cible (PIX-15548).
  admin/app/components/common/tubes-selection.gjs
  admin/tests/integration/components/common/tubes-selection-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10734 [BUGFIX] Ignorer les réponses envoyés par les autres simulateurs auto (PIX-15256)
  mon-pix/app/components/module/element/embed.gjs
  mon-pix/tests/integration/components/module/embed_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#10737 [FEATURE] Déplacer les CGU vers un onglet dédié
  admin/app/components/users/cgu.gjs
  admin/app/components/users/user-overview.gjs
  admin/app/router.js
  admin/app/routes/authenticated/users/get/cgu.js
  admin/app/styles/app.scss
  admin/app/styles/components/users/cgu.scss
  admin/app/templates/authenticated/users/get.hbs
  admin/app/templates/authenticated/users/get/cgu.hbs
  admin/tests/acceptance/authenticated/users/get-test.js
  admin/tests/integration/components/users/cgu-test.gjs
  admin/tests/integration/components/users/user-overview-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10718 [FEATURE] Faire remonter le nombre de clics sur le bouton "Exporter les résultats de campagne" dans Matomo
  orga/app/components/campaign/header/tabs.gjs
  orga/app/routes/application.js
  orga/config/environment.js
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/campaign/header/tabs-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#10740 [FEATURE] Mettre à jour la traduction des "courses" (PIX-15606).
  mon-pix/translations/en.json
  mon-pix/translations/nl.json
Labels: :eyes: Tech Review Needed, team-evaluation

#10714 [TECH] Migration de la route de publication de session (PIX-14476).
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/services/mail-service.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/publish-sessions-in-batch.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/scripts/certification/send-certification-result-emails.js
  api/src/certification/session-management/application/session-publication-controller.js
  api/src/certification/session-management/application/session-publication-route.js
  api/src/certification/session-management/domain/errors.js
  api/src/certification/session-management/domain/services/mail-service.js
  api/src/certification/session-management/domain/services/session-publication-service.js
  api/src/certification/session-management/domain/usecases/index.js
  api/src/certification/session-management/domain/usecases/publish-session.js
  api/src/certification/session-management/infrastructure/repositories/certification-repository.js
  api/src/certification/session-management/infrastructure/repositories/index.js
  api/src/certification/session-management/routes.js
  api/src/shared/application/error-manager.js
  api/src/shared/domain/errors.js
  api/tests/certification/session-management/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/certification/session-management/unit/application/session-publication-controller_test.js
  api/tests/certification/session-management/unit/application/session-publication-route_test.js
  api/tests/certification/session-management/unit/domain/services/mail-service_test.js
  api/tests/certification/session-management/unit/domain/services/session-publication-service_test.js
  api/tests/certification/session-management/unit/domain/usecases/publish-session_test.js
  api/tests/integration/application/error-manager_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/domain/usecases/publish-sessions-in-batch_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, Bounded-context-migration

#10705 [TECH] Migrer la route PATCH /api/admin/certification-centers/{id} dans src (PIX-15539)
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/src/organizational-entities/application/certification-center/certification-center.admin.controller.js
  api/src/organizational-entities/application/certification-center/certification-center.admin.route.js
  api/src/organizational-entities/domain/usecases/create-certification-center.usecase.js
  api/src/organizational-entities/domain/usecases/index.js
  api/src/organizational-entities/domain/usecases/update-certification-center.usecase.js
  api/src/organizational-entities/domain/validators/certification-center-creation.validator.js
  api/tests/acceptance/application/certification-centers/index_test.js
  api/tests/organizational-entities/acceptance/application/certification-center/certification-center.admin.route.test.js
  api/tests/organizational-entities/integration/domain/usecases/update-certification-center.usecase.test.js
  api/tests/organizational-entities/unit/domain/validators/certification-center-creation.validator.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, Bounded-context-migration

#10741 [TECH] Ajouter les traductions manquantes pour la page de sélection SSO (PIX-15609)
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#10745 [FEATURE] Traduction manquante depuis Phrase ES et NL (PIX-14930)
  mon-pix/translations/es.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#10743 [TECH] Améliorer la gestion d'erreurs lors du téléchargement des résultats de session sur Pix App (PIX-15587).
  api/src/shared/application/error-manager.js
  api/src/shared/domain/errors.js
  api/tests/shared/integration/application/error-manager_test.js
  mon-pix/app/components/download-session-results.gjs
  mon-pix/app/components/user-certifications-detail-header.hbs
  mon-pix/app/components/user-certifications-detail-header.js
  mon-pix/app/services/file-saver.js
  mon-pix/app/styles/components/_user-certifications-detail-header.scss
  mon-pix/tests/integration/components/download-session-results-test.gjs
  mon-pix/tests/integration/components/user-certifications-detail-header-test.js
  mon-pix/tests/unit/services/file-saver-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#10733 [TECH] Suppression de la route GET /download-all-results (PIX-15516).
  api/src/certification/results/application/certification-results-controller.js
  api/src/certification/results/application/certification-results-route.js
  api/tests/certification/results/acceptance/application/certification-results-route_test.js
  api/tests/certification/results/unit/application/certification-results-controller_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#10739 [FEATURE] Création du feature toggle FT_NEW_LEGAL_DOCUMENTS_VERSIONING (PIX-15567)
  api/sample.env
  api/src/shared/config.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  orga/app/models/feature-toggle.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10753 [TECH] attend la deconnexion dans le hook After (Pix-15599)
  api/tests/test-helper.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#10749 [TECH] Supprimer @fortawesome de Pix Certif (PIX-15426).
  certif/package-lock.json
  certif/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10752 [TECH] Passer le status de l'ADR 56 à "Validé"
  docs/adr/0056-standardisation-des-scripts-nodejs.md
Labels: :rocket: Ready to Merge, cross-team

#10742 [FEATURE] Création des tables legal documents (PIX-15578)
  api/db/migrations/20241206094819_create-legal-document-versions-table.js
  api/db/migrations/20241206100509_create-legal-document-version-user-acceptances.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10746 [TECH] Supprimer 3 composants obsolètes (PIX-15614).
  mon-pix/app/components/badge-card-certifiable.hbs
  mon-pix/app/components/badge-card-certifiable.js
  mon-pix/app/components/badge-card.hbs
  mon-pix/app/components/badge-card.js
  mon-pix/app/components/reached-stage.hbs
  mon-pix/app/components/reached-stage.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_badge-card-certifiable.scss
  mon-pix/app/styles/components/_badge-card.scss
  mon-pix/app/styles/components/_reached-stage.scss
  mon-pix/tests/integration/components/badge-card-test.js
  mon-pix/tests/integration/components/reached-stage-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#10729 [FEATURE]: couper le lien entre les utilisateurs et leurs recommended trainings lors de l'anonymisation (PIX-15558)
  api/scripts/prod/delete-and-anonymise-organization-learners.js
  api/tests/integration/scripts/prod/delete-and-anonymise-organization-learners_test.js
Labels: :rocket: Ready to Merge, team-prescription

#10750 [BUGFIX] Suppression des doublons de réponses lors de l'appel à /next (PIX-15561).
  api/src/shared/infrastructure/repositories/answer-repository.js
  api/tests/shared/integration/infrastructure/repositories/answer-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10732 [TECH] Migrer la route GET /api/certification-point-of-contacts/me dans src (PIX-15543)
  api/lib/application/certification-point-of-contacts/certification-point-of-contact-controller.js
  api/lib/application/certification-point-of-contacts/index.js
  api/lib/domain/usecases/index.js
  api/lib/routes.js
  api/src/identity-access-management/application/user/user.controller.js
  api/src/identity-access-management/application/user/user.route.js
  api/src/identity-access-management/domain/usecases/get-certification-point-of-contact.usecase.js
  api/src/identity-access-management/domain/usecases/index.js
  api/src/identity-access-management/infrastructure/repositories/certification-point-of-contact.repository.js
  api/src/identity-access-management/infrastructure/serializers/jsonapi/certification-point-of-contact.serializer.js
  api/tests/acceptance/application/certification-point-of-contacts/certification-point-of-contact-controller_test.js
  api/tests/identity-access-management/acceptance/application/user/user.route.test.js
  api/tests/identity-access-management/integration/application/user/user.route.test.js
  api/tests/identity-access-management/integration/domain/usecases/get-certification-point-of-contact.usecase.test.js
  api/tests/identity-access-management/unit/application/user/user.controller.test.js
  api/tests/identity-access-management/unit/infrastructure/serializers/jsonapi/certification-point-of-contact.serializer.test.js
  api/tests/integration/infrastructure/repositories/certification-point-of-contact.repository.test.js
  api/tests/unit/application/certification-point-of-contacts/certification-point-of-contact-controller_test.js
  api/tests/unit/application/certification-point-of-contacts/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10754 [TECH] Supprimer la fonctionnalité pour définir la date d'envoi des résultats aux prescripteurs sur Pix Admin (PIX-15538).
  admin/app/adapters/session.js
  admin/app/components/sessions/session-informations.gjs
  admin/app/controllers/authenticated/sessions/session/informations.js
  admin/app/models/session.js
  admin/app/styles/authenticated/sessions/session/informations.scss
  admin/app/templates/authenticated/sessions/session/informations.hbs
  admin/mirage/config.js
  admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js
  admin/tests/acceptance/session-test.js
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.gjs
  admin/tests/unit/models/session-test.js
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/flag-session-results-as-sent-to-prescriber.js
  api/src/certification/session-management/domain/models/SessionManagement.js
  api/tests/acceptance/application/session/session-controller-put-results-sent-to-prescriber_test.js
  api/tests/certification/session-management/unit/domain/models/SessionManagement_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/usecases/flag-session-results-as-sent-to-prescriber_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10744 [BUGFIX] Ne plus retourner de 500 lors de la consultation de learner d'organization ayant l'import à format (Pix-15610)
  api/src/prescription/learner-management/domain/read-models/OrganizationLearnerForAdmin.js
  api/tests/prescription/learner-management/unit/domain/read-models/OrganizationLearnerForAdmin_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10755 [FEATURE] Permettre de rendre les <ol> sur 2 colonnes (PIX-15592)
  api/src/devcomp/infrastructure/datasources/learning-content/modules/didacticiel-modulix.json
  api/tests/devcomp/acceptance/scripts/get-elements_test.js
  mon-pix/app/components/module/_normalize.scss
  mon-pix/app/components/module/_passage.scss
  mon-pix/app/styles/app.scss
Labels: :rocket: Ready to Merge, team-devcomp

#10481 [DOC] ADR-57 - Migration des fichiers SCSS dans le dossier des composants
  docs/adr/0057-migration-css-dans-les-composants.md
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, team-evaluation, cross-team, team-contenu

#10731 [TECH] Migrer le usecase de calcul de resultat dans le BC Campaign Participations (PIX-15341)
  api/lib/domain/events/index.js
  api/lib/domain/usecases/complete-assessment.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/stages/handle-stage-acquisition.js
  api/lib/infrastructure/repositories/campaign-participation-repository.js
  api/lib/infrastructure/repositories/campaign-participation-result-repository.js
  api/scripts/prod/compute-participation-results.js
  api/src/devcomp/domain/usecases/index.js
  api/src/evaluation/domain/usecases/index.js
  api/src/identity-access-management/domain/usecases/index.js
  api/src/prescription/campaign-participation/application/jobs/participation-result-calculation-job-controller.js
  api/src/prescription/campaign-participation/domain/errors.js
  api/src/prescription/campaign-participation/domain/models/ParticipantResultsShared.js
  api/src/prescription/campaign-participation/domain/usecases/index.js
  api/src/prescription/campaign-participation/domain/usecases/save-computed-campaign-participation-result.js
  api/src/prescription/campaign-participation/infrastructure/repositories/campaign-participation-repository.js
  api/src/prescription/campaign-participation/infrastructure/repositories/participant-results-shared-repository.js
  api/src/shared/domain/errors.js
  api/src/shared/domain/models/index.js
  api/tests/integration/domain/usecases/complete-assessment_test.js
  api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/participant-results-shared-repository_test.js
  api/tests/prescription/campaign-participation/unit/application/jobs/participation-result-calculation-job-controller_test.js
  api/tests/prescription/campaign-participation/unit/domain/models/ParticipantResultsShared_test.js
  api/tests/prescription/campaign-participation/unit/domain/usecases/save-computed-campaign-participation-result_test.js
  api/tests/unit/domain/usecases/complete-assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-prescription, team-devcomp, Bounded-context-migration

#10762 [BUGFIX] Crash du rafraichissement du cache en recette (PIX-15642)
  api/sample.env
  api/scripts/generate-cron.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, team-contenu

#10761 [FEATURE] Mise à jour du message en cas d'incident technique non bloquant sur Pix Certif (PIX-15391).
  certif/tests/integration/components/issue-report-modal/non-blocking-technical-issue-certification-issue-report-fields-test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10763 [BUGFIX] Nouveaux repositories learning content : résultats en doublon (PIX-15640)
  api/lib/infrastructure/repositories/framework-repository.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/repositories/tube-repository.js
  api/src/devcomp/infrastructure/repositories/tutorial-repository.js
  api/src/shared/infrastructure/repositories/area-repository.js
  api/src/shared/infrastructure/repositories/challenge-repository_old.js
  api/src/shared/infrastructure/repositories/competence-repository.js
  api/src/shared/infrastructure/repositories/learning-content-repository.js
  api/src/shared/infrastructure/repositories/skill-repository.js
  api/tests/devcomp/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/integration/infrastructure/repositories/framework-repository_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/integration/infrastructure/repositories/tube-repository_test.js
  api/tests/shared/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/shared/integration/infrastructure/repositories/competence-repository_test.js
  api/tests/shared/integration/infrastructure/repositories/skill-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#10758 [FEATURE] Création de l'API legal documents (PIX-15580)
  api/db/database-builder/factory/build-legal-document-version.js
  api/src/legal-documents/application/api/legal-documents-api.js
  api/src/legal-documents/domain/models/LegalDocument.js
  api/src/legal-documents/domain/usecases/accept-legal-document-by-user-id.usecase.js
  api/src/legal-documents/domain/usecases/index.js
  api/src/legal-documents/infrastructure/repositories/legal-document.repository.js
  api/src/legal-documents/infrastructure/repositories/user-acceptance.repository.js
  api/src/legal-documents/infrastructure/repositories/user.repository.js
  api/tests/legal-documents/integration/application/api/legal-documents-api.test.js
  api/tests/legal-documents/integration/domain/usecases/accept-legal-document-by-user-id.usecase.test.js
  api/tests/legal-documents/integration/infrastructure/repositories/legal-document.repository.test.js
  api/tests/legal-documents/integration/infrastructure/repositories/user-acceptance.repository.test.js
  api/tests/legal-documents/integration/infrastructure/repositories/user.repository.test.js
  api/tests/tooling/domain-builder/factory/build-legal-document.js
  api/tests/tooling/domain-builder/factory/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10770 [BUGFIX] Mélange des options QCM à tort (PIX-15655)
  mon-pix/app/components/challenge-item/challenge-item-qcm.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#10738 [BUGFIX] Ajouter blocage compte utilisateur sur 2 formulaires oubliés provoquant des user-logins.failureCount supérieurs à 50 (PIX-14229)
  api/db/database-builder/factory/build-user.js
  api/lib/application/authentication/index.js
  api/src/identity-access-management/application/oidc-provider/oidc-provider.route.js
  api/src/identity-access-management/application/token/token.controller.js
  api/src/identity-access-management/domain/models/UserLogin.js
  api/src/identity-access-management/domain/usecases/authenticate-user.js
  api/src/shared/application/security-pre-handlers.js
  api/tests/identity-access-management/integration/application/oidc-provider.route.test.js
  api/tests/integration/application/authentication/index_test.js
  api/tests/shared/integration/application/security-pre-handlers_test.js
  api/tests/unit/domain/models/UserLogin_test.js
  mon-pix/app/adapters/user-oidc-authentication-request.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10760 [TECH] Isoler le contexte du GAR dans le session service via des fonctions dédiés
  mon-pix/app/components/navbar-desktop-header.js
  mon-pix/app/components/routes/campaigns/invited/associate-sco-student-form.js
  mon-pix/app/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form.js
  mon-pix/app/components/routes/login-form.js
  mon-pix/app/components/update-expired-password-form.js
  mon-pix/app/controllers/campaigns/campaign-landing-page.js
  mon-pix/app/controllers/campaigns/join/sco-mediacentre.js
  mon-pix/app/controllers/campaigns/join/student-sco.js
  mon-pix/app/controllers/fill-in-campaign-code.js
  mon-pix/app/routes/campaigns/access.js
  mon-pix/app/routes/fill-in-campaign-code.js
  mon-pix/app/routes/logout.js
  mon-pix/app/routes/terms-of-service.js
  mon-pix/app/services/session.js
  mon-pix/tests/helpers/service-stubs.js
  mon-pix/tests/integration/components/navbar-desktop-header-test.js
  mon-pix/tests/integration/components/routes/login-form-test.js
  mon-pix/tests/unit/components/navbar-desktop-header-test.js
  mon-pix/tests/unit/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form-test.js
  mon-pix/tests/unit/components/routes/login-form-test.js
  mon-pix/tests/unit/components/update-expired-password-form-test.js
  mon-pix/tests/unit/controllers/campaigns/join/sco-mediacentre-test.js
  mon-pix/tests/unit/controllers/campaigns/join/student-sco-test.js
  mon-pix/tests/unit/controllers/fill-in-campaign-code-test.js
  mon-pix/tests/unit/routes/campaigns/access-test.js
  mon-pix/tests/unit/routes/fill-in-campaign-code-test.js
  mon-pix/tests/unit/routes/logout-test.js
  mon-pix/tests/unit/routes/terms-of-service-test.js
  mon-pix/tests/unit/services/session-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10757 [TECH] Utiliser le type error sur les PixNotificationAlert.
  admin/app/components/administration/common/learning-content.gjs
  admin/app/components/login-form.gjs
  orga/app/components/auth/register-form.hbs
Labels: :rocket: Ready to Merge, team-acces, cross-team

#10769 [FEATURE] Mettre a jour le logo du ministère sur les attestation de sixième (PIX-15512)
  api/db/seeds/data/team-prescription/build-quests.js
  api/src/profile/infrastructure/serializers/pdf/templates/sixth-grade-attestation-template.pdf
Labels: :rocket: Ready to Merge, Func Review OK, team-evaluation

#10747 [BUGFIX] Afficher les données de campagnes supprimées non anonymisé (PIX-15613)
  api/src/prescription/campaign-participation/domain/models/CampaignParticipationForUserManagement.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/participations-for-user-management-repository_test.js
  api/tests/prescription/campaign-participation/unit/domain/models/CampaignParticipationForUserManagement_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10772 [BUGFIX] Retirer l'externalId d'une organisation dans le menu lorsque celle ci n'en possède pas (Pix-15658)
  api/db/seeds/data/common/organization-builder.js
  orga/app/components/layout/sidebar.gjs
  orga/app/components/layout/sidebar.hbs
  orga/app/components/layout/sidebar.js
  orga/app/components/layout/user-logged-menu.gjs
  orga/app/components/layout/user-logged-menu.hbs
  orga/tests/integration/components/layout/user-logged-menu-test.js
  orga/tests/unit/components/user-logged-menu-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10759 [BUGFIX] Permettre la finalisation des sessions ayant à la fois des certifications complétés et une raison d'abandon (PIX-15524).
  api/src/certification/session-management/domain/usecases/finalize-session.js
  api/src/certification/shared/infrastructure/repositories/certification-course-repository.js
  api/tests/certification/session-management/integration/domain/usecases/finalize-session_test.js
  api/tests/certification/session-management/unit/domain/usecases/finalize-session_test.js
  api/tests/certification/shared/integration/infrastructure/repositories/certification-course-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10775 [BUGFIX] Corrige l'affichage du dashboard en anglais.
  mon-pix/translations/en.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10751 [FEATURE] Afficher les statistiques dans Pix Orga (PIX-15455)
  api/src/prescription/organization-learner/application/organization-learners-controller.js
  api/src/prescription/organization-learner/infrastructure/serializers/jsonapi/analysis-by-tubes-serializer.js
  api/tests/prescription/organization-learner/acceptance/application/organization-learner-route_test.js
  api/tests/prescription/organization-learner/unit/application/organization-learners-controller_test.js
  api/tests/prescription/organization-learner/unit/infrastructure/serializers/jsonapi/analysis-by-tubes-serializer_test.js
  orga/app/adapters/analysis-by-tube.js
  orga/app/components/layout/sidebar.gjs
  orga/app/components/statistics/cover-rate-gauge.gjs
  orga/app/components/statistics/index.gjs
  orga/app/components/statistics/tag-level.gjs
  orga/app/models/analysis-by-tube.js
  orga/app/routes/authenticated/statistics.js
  orga/app/styles/app.scss
  orga/app/styles/components/statistics.scss
  orga/app/styles/components/statistics/cover-rate-gauge.scss
  orga/app/templates/authenticated/statistics.hbs
  orga/mirage/config.js
  orga/tests/acceptance/statistics-test.js
  orga/tests/integration/components/statistics/index-test.gjs
  orga/tests/integration/components/statistics/tag-level-test.gjs
  orga/tests/unit/adapters/analysis-by-tube-test.js
  orga/tests/unit/routes/authenticated/statistics-test.js
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10771 [FEATURE] Traiter les retours sur la flashcard (PIX-15324)
  mon-pix/app/components/module/element/flashcards/_flashcards-card.scss
  mon-pix/app/components/module/element/flashcards/flashcards.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#10789 [FEATURE] Remplacer les icônes stockées par le composant PixIcon (Pix-15454)
  mon-pix/app/components/module/grain/tag.gjs
  mon-pix/public/images/icons/icon-book.svg
  mon-pix/public/images/icons/icon-cog.svg
  mon-pix/public/images/icons/icon-cognition.svg
  mon-pix/public/images/icons/icon-door-open.svg
  mon-pix/public/images/icons/icon-mountain.svg
Labels: :rocket: Ready to Merge, team-devcomp

#10774 [BUGFIX] Perte des infos GAR quand la page est rafraichie (PIX-12534)
  mon-pix/app/authenticators/gar.js
  mon-pix/app/services/session.js
  mon-pix/app/utils/session-storage-entry.js
  mon-pix/tests/unit/services/session-test.js
  mon-pix/tests/unit/utils/session-storage-entry-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10779 [FEATURE] Calculer l'obtention de l'attestation a la fin du parcours (PIX-15498)
  api/src/shared/application/assessments/assessment-controller.js
  api/tests/shared/unit/application/assessments/assessment-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10791 [TECH] Appliquer le nouveau shade aux composants PixReturnTo sur Pix App (PIX-15685).
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/app/templates/authenticated/user-certifications/get.hbs
  mon-pix/app/templates/shared-certification.hbs
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#10463 [TECH] :truck: déplace la route et les fichiers utilisé pour `user-orga-settings`
  api/lib/application/user-orga-settings/index.js
  api/lib/routes.js
  api/src/shared/application/error-manager.js
  api/src/shared/domain/errors.js
  api/src/team/application/routes.js
  api/src/team/application/user-orga-settings.controller.js
  api/src/team/application/user-orga-settings.route.js
  api/src/team/domain/errors.js
  api/src/team/domain/usecases/create-or-update-user-orga-settings.usecase.js
  api/src/team/domain/usecases/get-prescriber.js
  api/src/team/infrastructure/serializers/jsonapi/user-orga-settings.serializer.js
  api/tests/integration/application/error-manager_test.js
  api/tests/team/acceptance/application/user-orga-settings.controller.test.js
  api/tests/team/unit/application/user-orga-settings.controller.test.js
  api/tests/team/unit/application/user-orga-settings.route.test.js
  api/tests/team/unit/domain/usecases/create-or-update-user-orga-settings.usecase.test.js
  api/tests/team/unit/domain/usecases/get-prescriber_test.js
  api/tests/team/unit/infrastructure/serializers/jsonapi/user-orga-settings.serializer.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, Bounded-context-migration

#10778 [TECH] Migration de la route de dépublication de session (PIX-15676).
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/certification-repository.js
  api/src/certification/session-management/application/session-publication-controller.js
  api/src/certification/session-management/application/session-publication-route.js
  api/src/certification/session-management/domain/services/session-publication-service.js
  api/src/certification/session-management/domain/usecases/index.js
  api/src/certification/session-management/domain/usecases/unpublish-session.js
  api/src/certification/session-management/infrastructure/repositories/certification-repository.js
  api/tests/acceptance/application/session/session-controller-patch-publish-session_test.js
  api/tests/acceptance/application/session/session-controller-patch-unpublish-session_test.js
  api/tests/certification/session-management/acceptance/application/session-publication-route_test.js
  api/tests/certification/session-management/integration/domain/usecases/publish-session_test.js
  api/tests/certification/session-management/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/certification/session-management/unit/application/session-publication-controller_test.js
  api/tests/certification/session-management/unit/application/session-publication-route_test.js
  api/tests/certification/session-management/unit/domain/usecases/unpublish-session_test.js
  api/tests/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, Bounded-context-migration

#10795 [BUGFIX] Garantir un comportement ISO entre l'ancienne version et la nouvelle version du repository lorsqu'on passe des valeurs invalides en guise de collection (PIX-15696)
  api/lib/infrastructure/repositories/tube-repository.js
  api/tests/devcomp/integration/infrastructure/repositories/tutorial-repository_test.js
  api/tests/integration/infrastructure/repositories/tube-repository_test.js
  api/tests/shared/integration/infrastructure/repositories/skill-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#10793 [FEATURE] Changement de disposition (PIX-15487)
  orga/app/components/mission/details.gjs
  orga/app/styles/pages/authenticated/mission.scss
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#10788 [TECH] Migrer les usecases de copie des badges et paliers d'un profil cible (PIX-15675).
  api/src/evaluation/domain/usecases/copy-target-profile-badges.js
  api/src/evaluation/domain/usecases/copy-target-profile-stages.js
  api/src/prescription/target-profile/application/admin-target-profile-controller.js
  api/tests/evaluation/integration/domain/usecases/copy-target-profile-badges_test.js
  api/tests/evaluation/integration/domain/usecases/copy-target-profile-stages_test.js
  api/tests/evaluation/unit/domain/usecases/copy-target-profile-badges_test.js
  api/tests/evaluation/unit/domain/usecases/copy-target-profile-stages_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10804 [TECH] Revoir l'injection des dépendances du model User (PIX-15712)
  api/src/identity-access-management/domain/models/User.js
  api/tests/identity-access-management/unit/domain/models/User.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#10800 [TECH] Améliorer les logs de la route /api/token (PIX-15710)
  api/src/identity-access-management/application/monitor-pre-handlers.js
  api/src/shared/infrastructure/monitoring-tools.js
  api/src/shared/infrastructure/plugins/pino.js
  api/tests/identity-access-management/unit/application/monitor-pre-handlers.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#10776 [TECH] Utilisation des session et currentUser service stubs dans Pix App (PIX-15677)
  mon-pix/app/components/data-protection-policy-information-banner.js
  mon-pix/tests/helpers/service-stubs.js
  mon-pix/tests/integration/components/authentication/login-form-test.gjs
  mon-pix/tests/integration/components/authentication/signup-form/index-test.gjs
  mon-pix/tests/integration/components/autonomous-course/landing-page-start-block-test.js
  mon-pix/tests/integration/components/campaign-start-block-test.js
  mon-pix/tests/integration/components/campaign/skill-review/attestation-result-test.gjs
  mon-pix/tests/integration/components/campaigns/assessment/results/hero/evaluation-results-hero-test.js
  mon-pix/tests/integration/components/campaigns/assessment/results/tabs/trainings-test.js
  mon-pix/tests/integration/components/certifications/certification-ender-test.js
  mon-pix/tests/integration/components/challenge-statement-test.js
  mon-pix/tests/integration/components/challenge/statement/tooltip-test.js
  mon-pix/tests/integration/components/dashboard/content-test.js
  mon-pix/tests/integration/components/data-protection-policy-information-banner-test.js
  mon-pix/tests/integration/components/footer/footer-links-test.js
  mon-pix/tests/integration/components/navbar-burger-menu-test.js
  mon-pix/tests/integration/components/navbar-desktop-nav-menu-test.js
  mon-pix/tests/integration/components/navbar-header-test.js
  mon-pix/tests/integration/components/navbar-mobile-header-test.js
  mon-pix/tests/integration/components/profile-content-test.js
  mon-pix/tests/integration/components/routes/campaigns/invited/associate-sup-student-form-test.js
  mon-pix/tests/integration/components/routes/register-form-test.js
  mon-pix/tests/integration/components/tutorial-panel-test.js
  mon-pix/tests/integration/components/tutorials/card-test.js
  mon-pix/tests/integration/components/user-logged-menu-test.js
  mon-pix/tests/unit/adapters/application-test.js
  mon-pix/tests/unit/adapters/email-verification-code-test.js
  mon-pix/tests/unit/components/authentication/login-or-register-oidc-test.js
  mon-pix/tests/unit/components/authentication/oidc-reconciliation-test.js
  mon-pix/tests/unit/components/autonomous-courses/landing-page-start-block-test.js
  mon-pix/tests/unit/components/navbar-mobile-header-test.js
  mon-pix/tests/unit/components/register-form-test.js
  mon-pix/tests/unit/components/routes/campaigns/join-sco-information-modal-test.js
  mon-pix/tests/unit/components/routes/login-form-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team

#10764 [TECH] Migrer send-started-participation-results-to-pole-emploi vers le contexte Prescription (PIX-15337)
  api/db/database-builder/factory/build-pole-emploi-sending.js
  api/lib/domain/events/index.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/send-completed-participation-results-to-pole-emploi.js
  api/lib/domain/usecases/send-shared-participation-results-to-pole-emploi.js
  api/scripts/prod/insert-missing-pole-emploi-sending-from-date.js
  api/src/prescription/campaign-participation/application/jobs/participation-started-job-controller.js
  api/src/prescription/campaign-participation/domain/models/PoleEmploiSending.js
  api/src/prescription/campaign-participation/domain/usecases/index.js
  api/src/prescription/campaign-participation/domain/usecases/send-started-participation-results-to-pole-emploi.js
  api/src/prescription/campaign-participation/infrastructure/externals/pole-emploi/PoleEmploiPayload.js
  api/src/prescription/campaign-participation/infrastructure/externals/pole-emploi/disabled-pole-emploi-notifier.js
  api/src/prescription/campaign-participation/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/src/shared/domain/models/index.js
  api/tests/integration/domain/usecases/send-completed-participation-results-to-pole-emploi_test.js
  api/tests/integration/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/integration/scripts/prod/insert-missing-pole-emploi-sending-from-date_test.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/send-started-participation-results-to-pole-emploi_test.js
  api/tests/prescription/campaign-participation/unit/application/jobs/participation-started-job-controller_test.js
  api/tests/prescription/campaign-participation/unit/domain/models/PoleEmploiSending_test.js
  api/tests/prescription/campaign-participation/unit/infrastructure/externals/pole-emploi/PoleEmploiPayload_test.js
  api/tests/prescription/campaign-participation/unit/infrastructure/externals/pole-emploi/disabled-pole-emploi-notifier_test.js
  api/tests/prescription/campaign-participation/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
  api/tests/tooling/domain-builder/factory/build-pole-emploi-sending.js
  api/tests/unit/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10796 [BUGFIX] Se baser sur le status d'une participation et non sur une date de partage pour le `isShared` (Pix-15648)
  api/src/prescription/campaign-participation/domain/models/PreviousCampaignParticipation.js
  api/src/prescription/campaign-participation/infrastructure/repositories/participant-result-repository.js
  api/src/shared/domain/read-models/participant-results/AssessmentResult.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/participant-result-repository_test.js
  api/tests/prescription/campaign-participation/unit/domain/models/PreviousCampaignParticipation_test.js
  api/tests/prescription/campaign-participation/unit/infrastructure/serializers/jsonapi/participant-result-serializer_test.js
  api/tests/unit/domain/read-models/participant-results/AssessmentResult_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10797 [BUGFIX] Retirer cette petite étoile dans mon-pix (PIX-15721)
  mon-pix/app/components/inaccessible-campaign.hbs
  mon-pix/app/templates/campaigns/existing-participation.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10794 [FEATURE] Ajouter de la pagination sur la page statistiques (PIX-15683)
  orga/app/components/statistics/index.gjs
  orga/app/routes/authenticated/statistics.js
  orga/app/styles/components/statistics.scss
  orga/tests/integration/components/statistics/index-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10781 [FEATURE] Script d'ajout d'un document legal (PIX-15582)
  api/scripts/legal-documents/add-new-legal-document-version.js
  api/src/legal-documents/domain/errors.js
  api/src/legal-documents/domain/models/LegalDocument.js
  api/src/legal-documents/domain/models/LegalDocumentService.js
  api/src/legal-documents/domain/models/LegalDocumentType.js
  api/src/legal-documents/domain/usecases/accept-legal-document-by-user-id.usecase.js
  api/src/legal-documents/domain/usecases/create-legal-document.usecase.js
  api/src/legal-documents/infrastructure/repositories/legal-document.repository.js
  api/src/shared/application/scripts/parsers.js
  api/tests/legal-documents/integration/application/api/legal-documents-api.test.js
  api/tests/legal-documents/integration/domain/usecases/accept-legal-document-by-user-id.usecase.test.js
  api/tests/legal-documents/integration/domain/usecases/create-legal-document.usecase.test.js
  api/tests/legal-documents/integration/infrastructure/repositories/legal-document.repository.test.js
  api/tests/legal-documents/integration/infrastructure/repositories/user-acceptance.repository.test.js
  api/tests/legal-documents/unit/domain/models/LegalDocumentService.test.js
  api/tests/legal-documents/unit/domain/models/LegalDocumentType.test.js
  api/tests/legal-documents/unit/domain/usecase/create-legal-document.usecase.test.js
  api/tests/shared/unit/application/scripts/parsers_test.js
  api/tests/tooling/domain-builder/factory/build-legal-document.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10798 [FEATURE] Montée de version de PixUI vers la 51.2.0 (PIX-15700)
  orga/app/components/banner/certification.gjs
  orga/app/components/banner/sco-communication.gjs
  orga/app/components/banner/survey.gjs
  orga/app/components/campaign/filter/campaign-filters.gjs
  orga/app/components/places/capacity-alert.gjs
  orga/app/components/places/places-lot-alert.gjs
  orga/app/templates/authenticated/missions/list.hbs
  orga/app/templates/authenticated/team/new.hbs
  orga/package-lock.json
  orga/package.json
  orga/tests/integration/components/banner/sco-communication-test.gjs
  orga/tests/integration/components/places/capacity-alert_test.gjs
  orga/tests/integration/components/places/places-lot-alert-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#10799 [TECH] Migrer la route User Has Seen Challenge Tooltip (PIX-15689).
  api/lib/application/users/index.js
  api/lib/application/users/user-controller.js
  api/src/identity-access-management/application/user/user.controller.js
  api/src/identity-access-management/application/user/user.route.js
  api/src/identity-access-management/domain/usecases/remember-user-has-seen-challenge-tooltip.usecase.js
  api/tests/acceptance/application/users/remember-user-has-seen-challenge-tooltip_test.js
  api/tests/identity-access-management/acceptance/application/user/user.route.test.js
  api/tests/identity-access-management/integration/application/user/user.route.test.js
  api/tests/identity-access-management/unit/application/user/user.controller.test.js
  api/tests/integration/application/users/index_test.js
  api/tests/unit/application/users/user-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10810 [FEATURE] Modifier le lien pour l'interprétation des résultats en anglais sur Pix Orga (PIX-15679).
  orga/translations/en.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10817 [FEATURE] Ajouter la date d'extraction à la page statistiques sur Pix Orga (PIX-15458).
  orga/app/components/statistics/index.gjs
  orga/app/styles/components/statistics.scss
  orga/tests/integration/components/statistics/index-test.gjs
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10806 [FEATURE] Amélioration de l'affichage de la fiche pédagogique (PIX-15487)
  orga/app/components/mission/details.gjs
  orga/app/components/mission/navigation.gjs
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/list-header.scss
  orga/app/styles/components/mission/navigation.scss
  orga/app/styles/pages/authenticated/mission.scss
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#10822 [FEATURE] Mettre à jour le wording du bandeau Pix Certif pour les centres SCO sur Pix Certif (PIX-15652).
  certif/app/components/layout/banners.gjs
  certif/tests/acceptance/authenticated-test.js
  certif/tests/acceptance/session-list-test.js
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10808 [FEATURE] Ajouter les filtres par domaines sur la page statistiques (PIX-15725)
  orga/app/components/attestations/sixth-grade.gjs
  orga/app/components/statistics/index.gjs
  orga/app/styles/components/statistics.scss
  orga/tests/integration/components/attestations/sixth-grade-test.gjs
  orga/tests/integration/components/statistics/index-test.gjs
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10813 [TECH] Migrer les résultats partagés et complétés à Pôle Emploi vers le contexte Prescription (Pix-15339)
  api/lib/domain/events/index.js
  api/lib/domain/usecases/index.js
  api/scripts/prod/insert-missing-pole-emploi-sending-from-date.js
  api/src/prescription/campaign-participation/application/jobs/participation-shared-job-controller.js
  api/src/prescription/campaign-participation/domain/usecases/index.js
  api/src/prescription/campaign-participation/domain/usecases/send-shared-participation-results-to-pole-emploi.js
  api/src/prescription/campaign-participation/infrastructure/repositories/campaign-participation-result-repository.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/campaign-participation-result-repository_test.js
  api/tests/prescription/campaign-participation/unit/application/jobs/participation-shared-job-controller_test.js
  api/tests/prescription/campaign-participation/unit/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10784 [FEATURE] Ajout d'un bouton reload pour les embed (PIX-15418)
  junior/app/components/challenge/challenge-embed-simulator/component.js
  junior/app/components/challenge/challenge-embed-simulator/template.hbs
  junior/app/components/challenge/item/component.js
  junior/app/components/challenge/item/template.hbs
  junior/app/styles/components/challenge/challenge-embed-simulator.scss
  junior/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, Design Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#10825 [FEATURE] Ajouter des descriptions dans la page statistiques (PIX-15457)
  orga/app/components/statistics/index.gjs
  orga/app/styles/components/statistics.scss
  orga/tests/integration/components/statistics/index-test.gjs
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10832 [TECH] Corrige la conjugaison de "was" en "were" dans le script de configuration.
  scripts/configure.sh
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#10824 [BUGFIX] Corriger la mention "Terminé" sur la dernière flashcard (PIX-15735)
  mon-pix/app/components/module/element/flashcards/_flashcards-card.scss
Labels: :rocket: Ready to Merge, team-devcomp

#10802 [FEATURE] déplace le footer d'orga en base de la page (pix-15615)
  orga/app/styles/components/layout/footer.scss
  orga/app/styles/components/ui/action-bar.scss
  orga/app/templates/authenticated.hbs
  orga/package-lock.json
  orga/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10819 [TECH] Utiliser de fausses données pour les test du script get-elements-csv (PIX-15633)
  api/tests/devcomp/acceptance/scripts/get-elements_test.js
  api/tests/devcomp/acceptance/scripts/test-module.json
Labels: :rocket: Ready to Merge, team-devcomp

#10835 [FEATURE]: formater les date dans les export de résultats en utilisant le fuseau Europe/Paris
  api/src/prescription/campaign/infrastructure/exports/campaigns/campaign-profiles-collection-result-line.js
  api/src/prescription/campaign/infrastructure/utils/CampaignAssessmentCsvLine.js
  api/tests/prescription/campaign/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/prescription/campaign/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/prescription/campaign/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/prescription/campaign/unit/infrastructure/exports/campaigns/campaign-profiles-collection-result-line_test.js
  api/tests/prescription/campaign/unit/infrastructure/serializers/csv/campaign-profiles-collection-export_test.js
  api/tests/prescription/campaign/unit/infrastructure/utils/CampaignAssessmentCsvLine_test.js
  api/translations/en.json
  api/translations/es.json
  api/translations/fr.json
  api/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10811 [FEATURE] Effacer le message d'erreur de saisie de l'externalId lors de la modification du précedent en erreur (PIX-15158)
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/db/seeds/data/team-prescription/build-campaigns.js
  mon-pix/app/components/routes/campaigns/invited/fill-in-participant-external-id.gjs
  mon-pix/app/components/routes/campaigns/invited/fill-in-participant-external-id.hbs
  mon-pix/app/components/routes/campaigns/invited/fill-in-participant-external-id.js
  mon-pix/tests/integration/components/routes/campaigns/invited/fill-in-participant-external-id-test.js
  mon-pix/tests/unit/components/routes/campaigns/invited/fill-in-participant-external-id-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10756 [TECH] :truck: Déplacement de la route `session-summaries` vers `src`
  api/lib/application/certification-centers/certification-center-controller.js
  api/lib/application/certification-centers/index.js
  api/src/certification/session-management/application/certification-centers-session-summaries-controller.js
  api/src/certification/session-management/application/certification-centers-session-summaries-route.js
  api/src/certification/session-management/domain/usecases/find-paginated-certification-center-session-summaries.js
  api/src/certification/session-management/domain/usecases/index.js
  api/src/certification/session-management/infrastructure/repositories/index.js
  api/src/certification/session-management/infrastructure/serializers/session-summary-serializer.js
  api/src/certification/session-management/routes.js
  api/tests/certification/session-management/unit/application/certification-centers-session-summaries-controller.test.js
  api/tests/certification/session-management/unit/application/certification-centers-session-summaries-route.test.js
  api/tests/certification/session-management/unit/domain/usecases/find-paginated-certification-center-session-summaries_test.js
  api/tests/certification/session-management/unit/infrastructure/serializers/session-summary-serializer_test.js
  api/tests/unit/application/certification-centers/certification-center-controller_test.js
  api/tests/unit/application/certification-centers/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, Bounded-context-migration

#10842 [TECH] Migration de la route `/api/admin/sessions/publish-in-batch` (PIX-15768).
  api/lib/application/sessions/index.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/usecases/index.js
  api/src/certification/session-management/application/session-publication-controller.js
  api/src/certification/session-management/application/session-publication-route.js
  api/src/certification/session-management/domain/models/SessionPublicationBatchResult.js
  api/src/certification/session-management/domain/usecases/publish-sessions-in-batch.js
  api/src/shared/domain/models/index.js
  api/tests/certification/session-management/acceptance/application/session-controller-publish-session-in-batch_test.js
  api/tests/certification/session-management/unit/application/session-publication-controller_test.js
  api/tests/certification/session-management/unit/application/session-publication-route_test.js
  api/tests/certification/session-management/unit/domain/usecases/publish-sessions-in-batch_test.js
  api/tests/unit/application/session/index_test.js
  api/tests/unit/application/session/session-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10805 [FEATURE] Faciliter les changements de noms des fournisseurs d'identité OIDC (pix-15616)
  admin/app/components/users/user-detail-authentication-methods.gjs
  admin/app/components/users/user-detail-personal-information/authentication-method.gjs
  admin/app/controllers/authenticated/users/get/authentication-methods.js
  admin/tests/acceptance/authenticated/users/authentication-method-test.js
  admin/tests/unit/components/users/user-detail-authentication-methods-test.js
  admin/tests/unit/components/users/user-detail-personal-information/authentication-method-test.js
  admin/tests/unit/controllers/authenticated/users/get/authentication-methods-test.js
  docker/sample.env
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10827 [FEATURE] Rendre asynchrone l'import à format sur PixOrga (Pix-15437)
  api/src/prescription/learner-management/application/jobs/import-common-organization-learners-job-controller.js
  api/src/prescription/learner-management/application/jobs/validate-common-organization-learners-import-file-job-controller.js
  api/src/prescription/learner-management/application/organization-learners-controller.js
  api/src/prescription/learner-management/domain/models/ImportCommonOrganizationLearnersJob.js
  api/src/prescription/learner-management/domain/models/ValidateCommonOrganizationImportFileJob.js
  api/src/prescription/learner-management/domain/usecases/import-from-feature/save-organization-learners-file.js
  api/src/prescription/learner-management/domain/usecases/import-from-feature/send-organization-learners-file.js
  api/src/prescription/learner-management/domain/usecases/import-from-feature/validate-organization-learners-file.js
  api/src/prescription/learner-management/domain/usecases/index.js
  api/src/prescription/learner-management/infrastructure/repositories/jobs/import-common-organization-learners-job-repository.js
  api/src/prescription/learner-management/infrastructure/repositories/jobs/validate-common-organization-learners-import-file-job-repository.js
  api/tests/prescription/learner-management/acceptance/application/organization-learners-route_test.js
  api/tests/prescription/learner-management/integration/infrastructure/repositories/jobs/import-common-organization-learners-job-repository_test.js
  api/tests/prescription/learner-management/integration/infrastructure/repositories/jobs/validate-common-organization-learners-import-file-job-repository_test.js
  api/tests/prescription/learner-management/unit/application/jobs/import-common-organization-learners-job-controller_test.js
  api/tests/prescription/learner-management/unit/application/jobs/validate-common-organization-learners-import-file-job-controller_test.js
  api/tests/prescription/learner-management/unit/application/organization-learners-controller_test.js
  api/tests/prescription/learner-management/unit/domain/usecases/import-from-feature/save-organization-learners-file_test.js
  api/tests/prescription/learner-management/unit/domain/usecases/import-from-feature/send-organization-learners-file_test.js
  api/tests/prescription/learner-management/unit/domain/usecases/import-from-feature/validate-organization-learners-file_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10826 [FEATURE] Rendre la page attestations visible seulement aux admins de l'organisation (PIX-15611)
  api/db/seeds/data/team-prescription/build-quests.js
  api/src/prescription/organization-learner/application/organization-learners-route.js
  api/tests/prescription/organization-learner/acceptance/application/organization-learner-route_test.js
  api/tests/prescription/organization-learner/unit/application/organization-learners-route_test.js
  orga/app/services/current-user.js
  orga/tests/unit/services/current-user-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-prescription

#10815 [BUGFIX] :recycle: remaniement de la vérification des valeurs contenues dans le fichier CSV d'import de session en masse (PIX-15719)
  api/src/shared/infrastructure/serializers/csv/csv-serializer.js
  api/tests/shared/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10845 [FEATURE] Ajouter une contrainte d'unicite sur la table profile-rewards (PIX-15781)
  api/db/migrations/20241218101624_add-unicity-constraint-on-profile-rewards-table.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10834 [TECH] Migrer en GJS les composants `organization-learners` de pixOrga (Pix 15749)
  orga/app/components/organization-learner/activity.gjs
  orga/app/components/organization-learner/activity.hbs
  orga/app/components/organization-learner/activity.js
  orga/app/components/organization-learner/activity/empty-state.gjs
  orga/app/components/organization-learner/activity/empty-state.hbs
  orga/app/components/organization-learner/activity/empty-state.js
  orga/app/components/organization-learner/activity/participation-list.gjs
  orga/app/components/organization-learner/activity/participation-list.hbs
  orga/app/components/organization-learner/activity/participation-row.gjs
  orga/app/components/organization-learner/activity/participation-row.hbs
  orga/app/components/organization-learner/activity/participation-row.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10843 [BUGFIX] Problème d'affichage sur les leçons (PIX-15767)
  junior/app/components/challenge/item/component.js
  junior/app/models/challenge.js
  junior/tests/unit/models/challenge-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#10830 [FEATURE] Suivre l'utilisation de la barre de navigation Modulix dans Matomo (PIX-15535)(PIX-14866)
  mon-pix/app/components/module/navbar.gjs
  mon-pix/app/components/module/passage.gjs
  mon-pix/tests/integration/components/module/navbar_test.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#10851 [FEATURE] Prendre en compte le feature toggle quest enabled (PIX-15789)
  api/src/shared/application/assessments/assessment-controller.js
  api/tests/shared/unit/application/assessments/assessment-controller_test.js
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/index.gjs
  mon-pix/tests/integration/components/campaigns/assessment/results/hero/evaluation-results-hero-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-prescription

#10787 [FEATURE] Script de migration des données CGUs de Pix Orga vers le nouveau modèle (PIX-15583)
  api/db/database-builder/factory/build-legal-document-version-user-acceptance.js
  api/src/legal-documents/scripts/add-new-legal-document-version.js
  api/src/legal-documents/scripts/convert-users-orga-cgu-data.js
  api/tests/legal-documents/integration/scripts/convert-users-orga-cgu-data.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10855 [TECH] Supprimer l'action auto-merge local
  .github/workflows/auto-merge.yaml
Labels: :rocket: Ready to Merge

#10836 [TECH] Migration de composants en GJS (PIX-15766)
  orga/app/components/learner/header.gjs
  orga/app/components/learner/header.hbs
  orga/app/components/organization-participant/action-bar.gjs
  orga/app/components/organization-participant/action-bar.hbs
  orga/app/components/organization-participant/no-participant-panel.gjs
  orga/app/components/organization-participant/no-participant-panel.hbs
  orga/app/components/organization-participant/no-participant-panel.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10857 [FEATURE] Rendre la documentation d’installation de Companion traduisible (PIX-15812)
  mon-pix/app/components/companion/blocker.gjs
  mon-pix/app/components/companion/check.gjs
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, team-companion

#10831 [FEATURE] Ajouter le script pour rattraper les retard d'obtention des attestations (PIX-15510)
  api/src/profile/scripts/sixth-grade-attestation-reward.js
  api/tests/profile/integration/scripts/sixth-grade-attestation-reward_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10850 [BUGFIX] Ne pas créer plusieurs récompenses de quêtes (PIX-15804)
  api/src/quest/domain/usecases/reward-user.js
  api/tests/quest/integration/domain/usecases/reward-user_test.js
  mon-pix/app/models/feature-toggle.js
Labels: Tech Review OK, Func Review OK, team-evaluation, team-prescription

#10861 [BUGFIX] Afficher le tableau de la page statistiques même quand le titre du sujet est vide (PIX-15821).
  orga/app/components/statistics/index.gjs
  orga/app/styles/components/statistics.scss
  orga/tests/integration/components/statistics/index-test.gjs
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: :rocket: Ready to Merge

#10844 [FEATURE] campaign participation id in ke snapshots (Pix-15753)
  api/db/database-builder/factory/build-knowledge-element-snapshot.js
  api/db/database-builder/factory/knowledge-elements-snapshot-factory.js
  api/db/migrations/20241218140743_create-campaignparticipationid-column-in-ke-snaphots.js
  api/db/seeds/data/common/tooling/campaign-tooling.js
  api/lib/infrastructure/repositories/knowledge-element-snapshot-repository.js
  api/scripts/prod/generate-knowledge-element-snapshots-for-campaigns.js
  api/src/prescription/campaign-participation/infrastructure/repositories/campaign-participation-repository.js
  api/src/prescription/shared/domain/read-models/CampaignParticipationKnowledgeElementSnapshots.js
  api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
  api/tests/integration/infrastructure/repositories/knowledge-element-snapshot-repository_test.js
  api/tests/integration/scripts/prod/generate-knowledge-element-snapshots-for-campaigns_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10814 [FEATURE] améliore les messages d'erreur d'import de prescrits
  api/src/prescription/learner-management/domain/read-models/OrganizationImportDetail.js
  api/src/prescription/learner-management/infrastructure/serializers/jsonapi/organization-import-detail-serializer.js
  api/tests/prescription/learner-management/integration/infrastructure/repositories/organization-import-repository_test.js
  api/tests/prescription/learner-management/unit/domain/read-models/OrganizationImportDetail_test.js
  api/tests/prescription/learner-management/unit/infrastructure/serializers/jsonapi/organization-import-detail-serializer_test.js
  orga/app/components/import/banner.gjs
  orga/app/models/organization-import-detail.js
  orga/tests/integration/components/import/banner_test.gjs
  orga/tests/unit/models/organization-import-detail-test.js
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10852 [FEATURE] Traduction en ES & NL de l'e-mail de suppression du compte (PIX-15805)
  api/tests/unit/domain/services/mail-service_test.js
  api/translations/es.json
  api/translations/nl.json
Labels: :rocket: Ready to Merge, team-acces

#10833 [FEATURE] Adjust self delete account (PIX-15713)
  admin/app/components/users/user-overview.gjs
  admin/app/models/user.js
  admin/tests/integration/components/users/user-overview-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
  api/src/identity-access-management/domain/models/UserDetailsForAdmin.js
  api/src/identity-access-management/infrastructure/repositories/user.repository.js
  api/src/identity-access-management/infrastructure/serializers/jsonapi/user-details-for-admin.serializer.js
  api/tests/identity-access-management/acceptance/application/user/user.admin.route.test.js
  api/tests/identity-access-management/unit/infrastructure/serializers/jsonapi/user-details-for-admin.serializer.test.js
  mon-pix/translations/es.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10869 [TECH] :truck: déplace la route « jury certif summary »
  api/lib/application/sessions/session-controller.js
  api/lib/routes.js
  api/src/certification/session-management/application/jury-certification-summaries-route.js
  api/src/certification/session-management/application/session-controller.js
  api/src/certification/session-management/infrastructure/serializers/jury-certification-summary-serializer.js
  api/src/certification/session-management/routes.js
  api/tests/certification/session-management/unit/application/jury-certification-summaries-route_test.js
  api/tests/certification/session-management/unit/application/session-controller_test.js
  api/tests/certification/session-management/unit/infrastructure/serializers/jury-certification-summary-serializer_test.js
  api/tests/unit/application/session/session-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, Bounded-context-migration

#10860 [FEATURE] Ajouter une route API donnant accès au résultat de certif d'un élève (PIX-15799).
  api/lib/application/sco-organization-learners/index.js
  api/server.js
  api/src/identity-access-management/application/account-recovery/account-recovery.route.js
  api/src/parcoursup/application/certification-controller.js
  api/src/parcoursup/application/certification-route.js
  api/src/parcoursup/application/routes.js
  api/src/parcoursup/domain/read-models/CertificationResult.js
  api/src/parcoursup/domain/usecases/get-certification-result.js
  api/src/parcoursup/domain/usecases/index.js
  api/src/parcoursup/infrastructure/repositories/certification-repository.js
  api/src/shared/domain/types/identifiers-type.js
  api/tests/parcoursup/acceptance/application/certification-routes_test.js
  api/tests/parcoursup/integration/repositories/certification-repository_test.js
  api/tests/parcoursup/unit/application/certification-route_test.js
  api/tests/parcoursup/unit/domain/usecases/get-certification-result_test.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/parcoursup/build-certification-result.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, Parcoursup

#10876 [BUGFIX] corriger l'affichage du dashboard en version espagnole
  mon-pix/translations/es.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#10828 [FEATURE] Optimisation de l'écran de challenge Pix Junior (PIX-15739)
  junior/app/components/challenge/challenge-wrapper.gjs
  junior/app/components/challenge/template.hbs
  junior/app/components/robot-dialog.gjs
  junior/app/styles/app.scss
  junior/app/styles/components/bubble.scss
  junior/app/styles/components/challenge/challenge-item.scss
  junior/app/styles/components/challenge/challenge-media.scss
  junior/app/styles/components/challenge/challenge-wrapper.scss
  junior/app/styles/components/footer.scss
  junior/app/styles/components/robot-dialog.scss
  junior/app/styles/globals/_colors.scss
  junior/app/styles/pages/identified/missions/introduction.scss
  junior/app/styles/pages/identified/missions/mission.scss
  junior/app/styles/pages/organization-code.scss
  junior/app/styles/pages/school.scss
  junior/app/templates/identified/missions/mission/introduction.hbs
  junior/app/templates/school/divisions.hbs
  junior/app/templates/school/students.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Design Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#10867 [BUGFIX] L'icone en cas de succès d'import a disparu (PIX-15762)
  orga/app/components/import/banner.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10840 [TECH] Monter la version d'ember-source orga en V6 (PIX-15770)
  orga/app/components/participant/assessment/results.gjs
  orga/app/components/participant/assessment/results.hbs
  orga/app/components/tube/list.js
  orga/app/models/campaign-assessment-participation-result.js
  orga/app/routes/authenticated/campaigns/participant-assessment/results.js
  orga/app/templates/authenticated/campaigns/participant-assessment/results.hbs
  orga/config/environment.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/campaign-participants-individual-results-test.js
  orga/tests/acceptance/organization-participant-list-test.js
  orga/tests/acceptance/profile-test.js
  orga/tests/acceptance/remove-membership-test.js
  orga/tests/acceptance/sco-organization-participant-list-test.js
  orga/tests/acceptance/sup-organization-participant-list-test.js
  orga/tests/integration/components/participant/assessment/results-test.js
  orga/tests/unit/models/campaign-assessment-participation-result-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10858 [FEATURE] Pouvoir créer un élément Expand dans le contenu d'un Module (PIX-15772)
  api/src/devcomp/domain/models/element/Expand.js
  api/src/devcomp/infrastructure/datasources/learning-content/modules/didacticiel-modulix.json
  api/src/devcomp/infrastructure/factories/module-factory.js
  api/tests/devcomp/unit/domain/models/element/Expand_test.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/element/expand-schema.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/module-schema.js
  api/tests/devcomp/unit/infrastructure/factories/module-factory_test.js
Labels: :rocket: Ready to Merge, team-devcomp

#10875 [BUGFIX] Autoriser la suppression / desactivation des apprenants n'ayant pas de studentNumber ou nationalStudeId (PIX-15831)
  api/src/prescription/learner-management/infrastructure/repositories/sup-organization-learner-repository.js
  api/tests/prescription/learner-management/integration/infrastructure/repositories/sup-organization-learner-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10863 [TECH] Mutualiser les heading sur PixOrga (Pix-15826)
  admin/app/styles/globals/page.scss
  high-level-tests/e2e/cypress/support/step_definitions/campaign.js
  orga/app/components/attestations/sixth-grade.gjs
  orga/app/components/auth/login-or-register.hbs
  orga/app/components/campaign/create-form.gjs
  orga/app/components/campaign/header/title.gjs
  orga/app/components/campaign/list-header.gjs
  orga/app/components/import/index.gjs
  orga/app/components/learner/header.gjs
  orga/app/components/mission/details.gjs
  orga/app/components/organization-participant/header.gjs
  orga/app/components/participant/assessment/header.hbs
  orga/app/components/participant/profile/header.hbs
  orga/app/components/places/title.gjs
  orga/app/components/sco-organization-participant/header-actions.hbs
  orga/app/components/statistics/index.gjs
  orga/app/components/terms-of-service/page-en.hbs
  orga/app/components/terms-of-service/page-fr.hbs
  orga/app/components/terms-of-service/page-nl.hbs
  orga/app/components/ui/page-title.gjs
  orga/app/components/ui/previous-page-button.hbs
  orga/app/components/ui/previous-page-button.js
  orga/app/styles/app.scss
  orga/app/styles/components/campaign/header/title.scss
  orga/app/styles/components/login-or-register.scss
  orga/app/styles/components/places/statistics.scss
  orga/app/styles/components/places/title.scss
  orga/app/styles/components/statistics.scss
  orga/app/styles/components/ui/breadcrumb.scss
  orga/app/styles/components/ui/form-field.scss
  orga/app/styles/components/ui/index.scss
  orga/app/styles/components/ui/page-title.scss
  orga/app/styles/globals/texts.scss
  orga/app/styles/globals/titles.scss
  orga/app/styles/pages/authenticated/campaigns/new-item.scss
  orga/app/styles/pages/authenticated/campaigns/new.scss
  orga/app/styles/pages/authenticated/certifications.scss
  orga/app/styles/pages/authenticated/team/list.scss
  orga/app/templates/authenticated/campaigns/new.hbs
  orga/app/templates/authenticated/campaigns/update.hbs
  orga/app/templates/authenticated/certifications.hbs
  orga/app/templates/authenticated/missions/list.hbs
  orga/app/templates/authenticated/organization-participants/organization-participant.hbs
  orga/app/templates/authenticated/preselect-target-profile.hbs
  orga/app/templates/authenticated/sco-organization-participants/sco-organization-participant.hbs
  orga/app/templates/authenticated/sup-organization-participants/sup-organization-participant.hbs
  orga/app/templates/authenticated/team/list.hbs
  orga/app/templates/authenticated/team/new.hbs
  orga/app/templates/join-request.hbs
  orga/app/templates/login.hbs
  orga/tests/integration/components/ui/previous-page-button-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, Design Review OK

#10868 [FEATURE] Permettre de masquer le champ JSON dans la preview modulix (PIX-15830)
  mon-pix/app/components/module/preview.gjs
  mon-pix/app/styles/pages/_module-preview.scss
  mon-pix/tests/acceptance/module/preview-test.js
  mon-pix/tests/integration/components/module/preview_test.gjs
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: :rocket: Ready to Merge, team-devcomp

#10866 [FEATURE] Afficher un élement Expand (PIX-15773)
  mon-pix/app/components/module/element.gjs
  mon-pix/app/components/module/element/expand.gjs
  mon-pix/app/components/module/grain.gjs
  mon-pix/tests/integration/components/module/element_test.gjs
  mon-pix/tests/integration/components/module/expand_test.gjs
  mon-pix/tests/integration/components/module/grain_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#10829 [DOC] ADR sur le nouveau système de cache de contenu pédagogique au niveau de l'API Pix (PIX-15472)
  api/src/learning-content/infrastructure/repositories/learning-content-repository.js
  docs/adr/0057-migration-css-dans-les-composants.md
  docs/adr/0058-modification-du-cache-du-contenu-pedagogique.md
  docs/assets/learning-content-cache-v2_graphe-mise-en-cache.png
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#10885 [BUGFIX] cache le filtre du propriétaire de campagne sur la page mes campagnes (pix-15837)
  orga/app/components/campaign/list.gjs
  orga/app/templates/authenticated/campaigns/list/all-campaigns.hbs
  orga/app/templates/authenticated/campaigns/list/my-campaigns.hbs
  orga/tests/integration/components/campaign/list-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10884 [FEATURE] Donner la possibilitée aux organisations sans imports de télécharger des attestations (PIX-15612)
  api/db/seeds/data/common/organization-builder.js
  api/db/seeds/data/team-prescription/build-quests.js
  api/src/prescription/organization-learner/infrastructure/repositories/organization-learner-repository.js
  api/tests/prescription/organization-learner/integration/infrastructure/repositories/organization-learner-repository_test.js
  orga/app/components/attestations/sixth-grade.gjs
  orga/app/controllers/authenticated/attestations.js
  orga/app/routes/authenticated/attestations.js
  orga/tests/integration/components/attestations/sixth-grade-test.gjs
  orga/tests/unit/controllers/authenticated/attestations-test.js
  orga/tests/unit/routes/authenticated/attestations-test.js
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#10887 [TECH] Migrer PixOrga vers Eslint v9 (PIX-15851)
  orga/.eslintignore
  orga/.eslintrc.cjs
  orga/.template-lintrc.mjs
  orga/app/components/auth/register-form.js
  orga/app/components/campaign/header/archived-banner.gjs
  orga/app/components/campaign/header/tabs.gjs
  orga/app/components/campaign/settings/view.gjs
  orga/app/components/sco-organization-participant/manage-authentication-method-modal.js
  orga/app/components/team/invitations-list-item.js
  orga/app/components/team/invitations-list.js
  orga/app/components/team/members-list-item.js
  orga/app/controllers/authenticated/campaigns/campaign/activity.js
  orga/app/controllers/authenticated/sup-organization-participants/list.js
  orga/app/routes/authenticated/import-organization-participants.js
  orga/app/routes/authenticated/organization-participants/organization-participant/activity.js
  orga/app/routes/authenticated/sco-organization-participants/sco-organization-participant/activity.js
  orga/app/routes/authenticated/sup-organization-participants/sup-organization-participant/activity.js
  orga/app/services/current-user.js
  orga/ember-cli-build.mjs
  orga/eslint.config.mjs
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/campaign-details-test.js
  orga/tests/acceptance/campaign-participants-individual-results-test.js
  orga/tests/acceptance/profile-test.js
  orga/tests/acceptance/switch-organization-test.js
  orga/tests/acceptance/team-list-test.js
  orga/translations/en.json
  orga/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-prescription

#10895 [FEATURE] Message de warning pour épreuve jouable sans acquis (PIX-15858)
  api/src/shared/infrastructure/repositories/challenge-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, team-contenu

#10881 [FEATURE] :sparkles: Ajoute une stratégie de contrôle plus strict pour l'accès au endpoint Parcoursup (PIX-15801)
  api/lib/infrastructure/authentication.js
  api/src/parcoursup/application/certification-route.js
  api/src/shared/config.js
  api/tests/parcoursup/acceptance/application/certification-route_test.js
  api/tests/parcoursup/unit/application/certification-route_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-certif

#10888 [FEATURE] Mise à jour des textes des nouveaux gabarits (PIX-15840).
  high-level-tests/e2e/cypress/integration/pix-app/page-title.feature
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  mon-pix/app/styles/globals/_page-header.scss
  mon-pix/app/templates/authenticated/user-tests.hbs
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation

#10903 [BUGFIX] Garanti l'ordonnancement des compétences dans l'attestation de certification
  api/db/seeds/data/common/tooling/session-tooling.js
  api/src/certification/results/infrastructure/repositories/competence-tree-repository.js
  api/src/shared/domain/models/Area.js
  api/tests/shared/unit/domain/models/Area_test.js
  api/tests/tooling/domain-builder/factory/build-competence-tree.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10896 [FEATURE] Connecte un datamart externe pour servir les résultats de certification pour ParcourSup (PIX-15800).
  .circleci/config.yml
  api/datamart/datamart-builder/datamart-buffer.js
  api/datamart/datamart-builder/datamart-builder.js
  api/datamart/datamart-builder/factory/build-certification-result.js
  api/datamart/datamart-builder/factory/index.js
  api/datamart/knexfile.js
  api/datamart/migrations/20241224080125-create-certification-results-table.js
  api/datamart/seeds/csv/data_export_parcoursup_certif_result.csv
  api/datamart/seeds/populate-certification-results.js
  api/db/knex-database-connection.js
  api/db/knexfile.js
  api/db/utils/build-postgres-environment.js
  api/package.json
  api/sample.env
  api/scripts/datamart/create-datamart.js
  api/scripts/datamart/drop-datamart.js
  api/src/parcoursup/infrastructure/repositories/certification-repository.js
  api/tests/parcoursup/acceptance/application/certification-route_test.js
  api/tests/parcoursup/integration/repositories/certification-repository_test.js
  api/tests/test-helper.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#10870 [TECH] Mise à jour de ESLint vers la V9 (PIX-15823)
  junior/.eslintignore
  junior/.eslintrc.cjs
  junior/.prettierignore
  junior/.template-lintrc.mjs
  junior/app/components/challenge/component.js
  junior/ember-cli-build.mjs
  junior/eslint.config.mjs
  junior/package-lock.json
  junior/package.json
  junior/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR
