Repository 1024pix/pix, pull requests merged in 2025-10, with the labels that each got.

#13728 [BUGFIX] Permettre l'authentification par SSO aux utilisateurs sortant d'un parcours Modulix (PIX-19665)
  mon-pix/app/routes/authentication/login-oidc.js
  mon-pix/app/routes/inscription/inscription.js
  mon-pix/tests/unit/routes/authentication/login-oidc-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#13760 [BUGFIX] Ajouter la locale es-419 manquante dans Pix API CHALLENGE_LOCALES (PIX-19820)
  api/src/shared/domain/services/locale-service.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#13727 [FEATURE] Afficher le champ "Équipe en charge" dans le formulaire d'édition d'une organisation (PIX-19598)
  admin/app/components/organizations/information-section-edit.gjs
  admin/app/models/organization-form.js
  admin/app/models/organization.js
  admin/app/styles/globals/form.scss
  admin/tests/integration/components/organizations/information-section-edit-test.gjs
  admin/tests/integration/components/organizations/information-section-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-acquisition

#13768 [BUGFIX] Ne pas vider le cache redis s'il n'est pas démarré après chaque test (PIX-19840)
  api/src/shared/infrastructure/mutex/RedisMutex.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, contribution-modulix

#13715 [TECH] Inverser la manière dont on récupère les module recommandé (Pix-19284).
  api/src/quest/domain/models/CombinedCourse.js
  api/tests/quest/unit/domain/models/CombinedCourse_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, :dango: Combinix

#13751 [TECH] Ajouter une transaction lors de l'archivage d'organisation (PIX-19756)
  api/src/organizational-entities/domain/usecases/archive-organization.usecase.js
  api/src/organizational-entities/infrastructure/repositories/organization-for-admin.repository.js
  api/src/prescription/campaign/application/api/campaigns-api.js
  api/src/prescription/campaign/domain/models/CampaignsDestructor.js
  api/src/prescription/campaign/domain/usecases/find-active-campaign-ids-by-organization.js
  api/src/prescription/campaign/domain/usecases/index.js
  api/src/prescription/campaign/infrastructure/repositories/campaign-management-repository.js
  api/tests/prescription/campaign/integration/domain/usecases/find-active-campaign-ids-by-organization_test.js
  api/tests/prescription/campaign/integration/infrastructure/repositories/campaign-management-repository_test.js
  api/tests/prescription/campaign/unit/domain/usecases/find-active-campaign-ids-by-organization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription

#13774 [BUGFIX] Corriger le bug d'affichage de la flashcard lorsqu'elle co-existe avec un stepper horizontal (PIX-19845)
  mon-pix/app/components/module/element/flashcards/flashcards.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#13772 [FEATURE] Ajouter une table `combined_courses` pour isoler les données n'appartenant pas aux quêtes (Pix-19763).
  api/db/migrations/20251002120922_add-combined-courses-table.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, team-captains, :dango: Combinix

#13770 [TECH] Gestion du caractère obligatoire du champ administration-team à la création unitaire (PIX-19808)
  admin/app/components/organizations/creation-form.gjs
  admin/app/controllers/authenticated/organizations/new.js
  admin/tests/acceptance/authenticated/organizations/create-organization-test.js
  admin/tests/integration/components/organizations/creation-form-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
  api/src/organizational-entities/domain/validators/organization-creation-validator.js
  api/src/organizational-entities/infrastructure/serializers/jsonapi/organizations-administration/organization-for-admin.serializer.js
  api/tests/organizational-entities/acceptance/application/organization/organization.admin.route.test.js
  api/tests/organizational-entities/integration/domain/usecases/create-organization_test.js
  api/tests/organizational-entities/unit/domain/validators/organization-creation-validator_test.js
  api/tests/organizational-entities/unit/infrastructure/serializers/jsonapi/organization-for-admin.serializer.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acquisition

#13776 [BUGFIX] Empêcher d'envoyer un email à un destinaire des résultats si le candidat n'a pas de certif-course (PIX-19805).
  api/src/certification/session-management/domain/services/session-publication-service.js
  api/src/certification/session-management/domain/usecases/publish-session.js
  api/src/certification/session-management/domain/usecases/publish-sessions-in-batch.js
  api/src/certification/session-management/infrastructure/repositories/certification-repository.js
  api/tests/certification/session-management/integration/infrastructure/repositories/certification-repository_test.js
  api/tests/certification/session-management/unit/domain/services/session-publication-service_test.js
  api/tests/certification/session-management/unit/domain/usecases/publish-session_test.js
  api/tests/certification/session-management/unit/domain/usecases/publish-sessions-in-batch_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#13750 [BUGFIX] Gérer le cas où le token de réinitialisation du mot de passe a expiré (PIX-19474).
  api/sample.env
  api/src/identity-access-management/application/http-error-mapper-configuration.js
  api/src/identity-access-management/domain/errors.js
  api/src/identity-access-management/domain/usecases/update-expired-password.usecase.js
  api/src/shared/config.js
  api/tests/identity-access-management/unit/domain/usecases/update-expired-password.usecase.test.js
  mon-pix/app/components/update-expired-password-form.gjs
  mon-pix/app/services/error-messages.js
  mon-pix/tests/integration/components/update-expired-password-form-test.js
  mon-pix/translations/en.json
  mon-pix/translations/es-419.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#13775 [TECH] Migrer les confs de PixCoeur dans la table certification_versions (PIX-19830).
  api/scripts/certification/migrate-certification-configurations-to-versions.js
  api/src/certification/shared/domain/models/Frameworks.js
  api/tests/integration/scripts/certification/migrate-certification-configurations-to-versions_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#13779 [TECH] Passer l'id de corrélation de requête à ChatPix pour faciliter le regroupement des logs et le débuggage sur Datadog
  api/src/llm/infrastructure/repositories/prompt-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK

#13781 [FEATURE] Intégration retours IAGENFonction_NOV
  api/src/devcomp/infrastructure/datasources/learning-content/modules/IAGenFonction_NOV.json
Labels: :rocket: Ready to Merge, contribution-modulix

#13796 [BUGFIX] Réparer la création d'orga dans les seeds certif
  api/db/seeds/data/team-certification/shared/common-organisations.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#13773 [FEATURE] Ajouter les parcours apprenants au chargement de PixOrga (pix-19813)
  api/src/team/infrastructure/serializers/jsonapi/prescriber-serializer.js
  api/tests/team/acceptance/application/prescriber-informations.controller.test.js
  api/tests/team/unit/infrastructure/serializers/jsonapi/prescriber-serializer_test.js
  orga/app/models/organization.js
  orga/app/services/current-user.js
  orga/tests/unit/services/current-user-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#13788 [FEATURE] Ajouter un feature toggle pour le nouveau design des pages d'authentification de Pix Orga (PIX-19794)
  api/config/feature-toggles-config.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  orga/app/models/feature-toggle.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#13767 [FEATURE] Enregistrer la nouvelle équipe en charge lors de la modification d'une organisation (PIX-19599)
  admin/app/components/organizations/information-section-edit.gjs
  api/src/organizational-entities/domain/models/OrganizationForAdmin.js
  api/tests/organizational-entities/integration/domain/usecases/update-organization-information.usecase_test.js
  api/tests/organizational-entities/unit/domain/models/OrganizationForAdmin_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-acquisition

#13793 [FEATURE] Remonter les métadonnées des images présentes dans les QAB (PIX-19683).
  api/src/devcomp/domain/models/element/qab/QAB.js
  api/src/devcomp/infrastructure/factories/module-factory.js
  api/tests/devcomp/integration/infrastructure/factories/module-factory_test.js
Labels: :rocket: Ready to Merge, team-devcomp

#13783 [FEATURE] Utiliser les données de la table `combined_courses` au lieu de quests (Pix-19851).
  api/db/database-builder/factory/build-combined-course.js
  api/src/prescription/organization-learner/domain/usecases/index.js
  api/src/quest/application/combined-course-controller.js
  api/src/quest/application/combined-course-route.js
  api/src/quest/application/usecases/check-user-can-manage-combined-course.js
  api/src/quest/domain/models/CombinedCourse.js
  api/src/quest/domain/services/combined-course-details-service.js
  api/src/quest/domain/usecases/find-combined-course-participations.js
  api/src/quest/domain/usecases/get-combined-course-by-code.js
  api/src/quest/domain/usecases/get-combined-course-by-id.js
  api/src/quest/domain/usecases/get-combined-course-by-quest-id.js
  api/src/quest/domain/usecases/get-combined-course-statistics.js
  api/src/quest/domain/usecases/get-combined-courses-by-organization-id.js
  api/src/quest/domain/usecases/index.js
  api/src/quest/domain/usecases/start-combined-course.js
  api/src/quest/domain/usecases/update-combined-course.js
  api/src/quest/infrastructure/repositories/combined-course-participation-repository.js
  api/src/quest/infrastructure/repositories/combined-course-repository.js
  api/src/quest/infrastructure/repositories/quest-repository.js
  api/src/shared/application/security-pre-handlers.js
  api/src/shared/domain/types/identifiers-type.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/prescription/organization-learner/acceptance/application/organization-to-join-route_test.js
  api/tests/prescription/organization-learner/integration/domain/usecases/get-organization-to-join_test.js
  api/tests/quest/acceptance/application/combined-course-route_test.js
  api/tests/quest/integration/application/usecases/check-user-can-manage-combined-course_test.js
  api/tests/quest/integration/domain/services/combined-course-details-service_test.js
  api/tests/quest/integration/domain/usecases/find-combined-course-participations_test.js
  api/tests/quest/integration/domain/usecases/get-combined-course-by-code_test.js
  api/tests/quest/integration/domain/usecases/get-combined-course-by-id_test.js
  api/tests/quest/integration/domain/usecases/get-combined-course-statistics_test.js
  api/tests/quest/integration/domain/usecases/get-combined-courses-by-organization-id_test.js
  api/tests/quest/integration/domain/usecases/get-verified-code_test.js
  api/tests/quest/integration/domain/usecases/start-combined-course_test.js
  api/tests/quest/integration/domain/usecases/update-combined-course_test.js
  api/tests/quest/integration/infrastructure/repositories/combined-course-participation-repository_test.js
  api/tests/quest/integration/infrastructure/repositories/combined-course-repository_test.js
  api/tests/quest/integration/infrastructure/repositories/quest-repository_test.js
  api/tests/quest/unit/application/combined-course-controller_test.js
  api/tests/quest/unit/application/combined-course-route_test.js
  api/tests/quest/unit/domain/models/CombinedCourse_test.js
  api/tests/quest/unit/domain/usecases/get-combined-courses-by-organization-id_test.js
  api/tests/shared/unit/application/security-pre-handlers_test.js
  api/tests/tooling/domain-builder/factory/build-combined-course-details.js
  high-level-tests/e2e-playwright/tests/pix-app/combined-course.test.ts
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, :dango: Combinix

#13815 [FEATURE] Ajouter deux colonnes à la table combined_course_participations : combinedCourseId et organizationLearnerParticipationId
  api/db/migrations/20251006093941_add-combined-course-id-and-organization-learner-participation-id-in-combined_course_participations.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, :dango: Combinix

#13807 [FEATURE] Ajouter les feedbacks pour les QCU déclaratif en mode preview (PIX-19892).
  mon-pix/app/components/module/element/qcu-declarative.gjs
  mon-pix/tests/integration/components/module/qcu-declarative_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#13814 [BUGFIX] Ne sélectionner que des challenges calibrés dans une certification Pix+ (PIX-19895).
  api/src/shared/infrastructure/repositories/challenge-repository.js
  api/tests/shared/integration/infrastructure/repositories/challenge-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#13803 [FEATURE] QAB : fixer la hauteur des images et temps de transition des cartes (PIX-19618)
  mon-pix/app/components/module/element/qab/_qab-card.scss
  mon-pix/app/components/module/element/qab/qab.gjs
Labels: :rocket: Ready to Merge, Design Review OK, team-devcomp

#13801 [FEATURE] Animation et couleurs des feedbacks (PIX-19327).
  mon-pix/app/components/module/_feedback.scss
  mon-pix/app/components/module/element/_qcm.scss
  mon-pix/app/components/module/element/_qcu-discovery.scss
  mon-pix/app/components/module/element/_qcu.scss
  mon-pix/app/components/module/element/qab/_qab.scss
  mon-pix/app/components/module/element/qab/qab.gjs
  mon-pix/app/components/module/element/qcu-discovery.gjs
Labels: :rocket: Ready to Merge, Design Review OK, team-devcomp

#13748 [FEATURE] Afficher les durées des certifications Pix+ sur les écrans d'entrée (PIX-19589)
  mon-pix/app/components/certification-instructions/step-two.gjs
  mon-pix/app/components/certification-instructions/steps.gjs
  mon-pix/tests/integration/components/steps-test.gjs
  mon-pix/tests/unit/components/certification-instructions/steps-test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#13818 [TECH] Supprime la dépendance dotenv.
  api/datamart/knexfile.js
  api/datawarehouse/knexfile.js
  api/db/knexfile.js
  api/index.js
  api/index.maddo.js
  api/package-lock.json
  api/package.json
  api/scripts/certification/finishing-reconciled-at-migration.js
  api/scripts/certification/fix-validated-live-alert-certification-challenge-ids.js
  api/scripts/certification/import-certification-cpf-cities.js
  api/scripts/certification/send-certification-result-emails.js
  api/scripts/data-generation/generate-campaign-with-participants.js
  api/scripts/data-generation/generate-certif-cli.js
  api/scripts/data-generation/seeds/dump-target-profile-data-as-seeds.js
  api/scripts/database/create-database.js
  api/scripts/database/drop-database.js
  api/scripts/database/pg-boss-migration.js
  api/scripts/generate-api-documentation.js
  api/scripts/get-difficulties-from-challenge-ids.js
  api/scripts/prod/compute-participation-results.js
  api/scripts/prod/select-category-for-target-profiles.js
  api/scripts/prod/target-profile-migrations/convert-target-profiles-into-new-format.js
  api/scripts/prod/target-profile-migrations/extract-need-stages-migration.js
  api/scripts/prod/target-profile-migrations/migrate-stages-to-level.js
  api/scripts/prod/target-profile-migrations/parse-xls-files-for-target-profiles-migration.js
  api/scripts/prod/target-profile-migrations/revert-stages-to-threshold.js
  api/scripts/refresh-cache.js
  api/src/shared/application/scripts/script.js
  api/src/shared/config.js
  api/src/shared/load-env-file-if-exists.js
  api/tests/acceptance/database/configuration.cjs
  api/tests/test-helper.js
  api/worker.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#13787 [BUGFIX] Ne pas afficher le message informatif du repasser quand on ne peut pas repasser (PIX-19852)
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/retry-or-reset-block.gjs
  mon-pix/tests/integration/components/campaigns/assessment/results/evaluation-results-hero/retry-or-reset-block-test.js
  mon-pix/translations/en.json
  mon-pix/translations/es-419.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#13820 [BUGFIX] Correction de la durée de la certification Pix+ Édu - espace surveillant (PIX-19903)
  certif/app/components/session-supervising/candidate-in-list.js
  certif/tests/integration/components/session-supervising/candidate-in-list-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#13827 [FEATURE] fix typo IAGenFonction
  api/src/devcomp/infrastructure/datasources/learning-content/modules/IAGenFonction_IND.json
  api/src/devcomp/infrastructure/datasources/learning-content/modules/IAGenFonction_NOV.json
Labels: :rocket: Ready to Merge, contribution-modulix

#13812 [FEATURE] Enregistrer l'équipe en charge lors de la création d'organisations en masse (PIX-19600)
  api/src/organizational-entities/domain/usecases/create-organizations-with-tags-and-target-profiles.usecase.js
  api/src/organizational-entities/domain/validators/organization-with-tags-and-target-profiles.js
  api/src/shared/infrastructure/serializers/csv/csv-serializer.js
  api/tests/organizational-entities/acceptance/application/organization/organization.admin.route.test.js
  api/tests/organizational-entities/integration/domain/usecases/create-organizations-with-tags-and-target-profiles.usecase.test.js
  api/tests/organizational-entities/integration/domain/validators/organization-with-tags-and-target-profiles.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acquisition

#13777 [TECH] Seeds : ajouter des versions CORE pour la table certification_versions (PIX-19847).
  api/db/database-builder/factory/build-certification-version.js
  api/db/seeds/data/team-certification/shared/setup-configuration.js
  api/db/seeds/data/team-certification/tools/algorithm-configuration/create-certification-version.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#13826 [BUGFIX] Corriger le fond violet sur la page de récap (PIX-19912)
  mon-pix/app/components/module/instruction/_recap.scss
Labels: :rocket: Ready to Merge, team-devcomp

#13798 [FEATURE] création IAGenEthique_NOV.json
  api/src/devcomp/infrastructure/datasources/learning-content/modules/IAGenEthique_NOV.json
Labels: :rocket: Ready to Merge, contribution-modulix
