Repository 1024pix/pix, pull requests merged in 2025-05, with the labels that each got.

#11905 [FEATURE] Rendre le processus d'authentifcation OIDC plus résistant aux retours arrière (PIX-13945)
  api/src/identity-access-management/application/oidc-provider/oidc-provider.controller.js
  api/src/shared/application/error-manager.js
  api/tests/identity-access-management/unit/application/oidc-provider.controller.test.js
  junior/tests/acceptance/access-school-test.js
  junior/tests/acceptance/start-mission-test.js
  junior/tests/helpers/unaborted-visit.js
  mon-pix/app/routes/authentication/login-oidc.js
  mon-pix/app/services/error-messages.js
  mon-pix/app/services/location.js
  mon-pix/app/services/oidc-identity-providers.js
  mon-pix/mirage/routes/authentication/oidc/index.js
  mon-pix/tests/acceptance/authentication/login-or-register-oidc-test.js
  mon-pix/tests/acceptance/oidc/oidc-authentication-flow-test.js
  mon-pix/tests/acceptance/oidc/start-campaigns-workflow-for-oidc-partner-test.js
  mon-pix/tests/helpers/service-stubs.js
  mon-pix/tests/helpers/unaborted-visit.js
  mon-pix/tests/unit/components/authentication/login-or-register-oidc-test.js
  mon-pix/tests/unit/routes/authentication/login-oidc-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12197 [BUGFIX] Retirer un texte inutile dans la boîte de dialog d'archivage d'un centre de certification (PIX-17686)
  admin/app/components/certification-centers/information-view.gjs
  admin/translations/en.json
  admin/translations/fr.json
Labels: :rocket: Ready to Merge, Func Review OK, team-acces

#12207 [TECH] Ajout d'un index sur mission-assessments.organizationLearnerId
  api/db/migrations/20250502095103_add_index_on_table_mission-assessments.js
Labels: :rocket: Ready to Merge, team-captains

#12198 [FEATURE] Ajouter un feature toggle pour la nouvelle récupération de compte (PIX-17503)
  api/config/feature-toggles-config.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#12155 [TECH] Utiliser les paliers acquis pour calculer la moyenne obtenue sur une campagne (PIX-17630)
  api/src/evaluation/infrastructure/repositories/stage-acquisition-repository.js
  api/src/prescription/campaign/domain/usecases/get-campaign.js
  api/src/prescription/campaign/domain/usecases/index.js
  api/src/prescription/campaign/infrastructure/repositories/campaign-report-repository.js
  api/src/prescription/campaign/infrastructure/repositories/helpers/get-latest-participation-shared-for-one-learner.js
  api/src/shared/domain/read-models/CampaignReport.js
  api/tests/evaluation/integration/infrastructure/repositories/stage-acquisition-repository_test.js
  api/tests/prescription/campaign/integration/domain/usecases/get-campaign_test.js
  api/tests/prescription/campaign/integration/infrastructure/repositories/campaign-report-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12205 [FEATURE] Replication de data_pro_campaigns_kpi_aggregated vers organizations_cover_rates (PIX-17716)
  api/src/maddo/infrastructure/repositories/replication-repository.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-maddo

#12204 [BUGFIX] Retirer le scroll horizontal sur la page j'ai un code de PixAPP (PIX-17705)
  mon-pix/app/styles/pages/_fill-in-campaign-code.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12206 [TECH] Migrer le feature toggle pour les missions expérimentales de Junior vers le nouveaux système
  api/config/feature-toggles-config.js
  api/sample.env
  api/src/school/infrastructure/repositories/mission-repository.js
  api/src/shared/config.js
  api/tests/school/integration/domain/usecases/find-all-active-missions_test.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team, 🎒👧🏽👦🏾 PIX JUNIOR, feature-toggle

#12209 [TECH] Ne pas configurer les jobs PgBoss si PGBOSS_CONNECTION_POOL_MAX_SIZE=0 (PIX-17727)
  api/tests/unit/worker_test.js
  api/worker.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team, team-maddo

#12109 [TECH] :truck: Déplace le cas d'utilisation `getAssessment` vers `src/evaluation/`
  api/src/certification/shared/domain/usecases/index.js
  api/src/shared/application/assessments/assessment-controller.js
  api/src/shared/application/assessments/index.js
  api/src/shared/domain/usecases/get-assessment.js
  api/src/shared/domain/usecases/index.js
  api/tests/shared/integration/application/assessments/assessment-controller_test.js
  api/tests/shared/integration/domain/usecases/get-assessment_test.js
  api/tests/shared/unit/application/assessements/assessment-controller-save_test.js
  api/tests/shared/unit/application/assessements/assessment-controller_test.js
  api/tests/shared/unit/application/assessements/index_test.js
  api/tests/shared/unit/domain/usecases/get-assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, team-evaluation, team-prescription, 🎒👧🏽👦🏾 PIX JUNIOR, Bounded-context-migration

#12161 [TECH] utiliser des modèles intermédiaires pour la calcul du taux de couverture par tube et par comptétence (PIX-17700)
  api/src/prescription/API.md
  api/src/prescription/campaign/application/api/models/CampaignListItem.js
  api/src/prescription/campaign/application/api/models/CampaignParticipation.js
  api/src/prescription/campaign/domain/models/CampaignResultLevelsPerTubesAndCompetences.js
  api/src/prescription/campaign/domain/models/CompetenceResultForKnowledgeElementSnapshots.js
  api/src/prescription/campaign/domain/models/TubeResultForKnowledgeElementSnapshots.js
  api/src/prescription/campaign/domain/read-models/CampaignParticipation.js
  api/src/prescription/campaign/domain/usecases/get-campaign-participations.js
  api/src/prescription/campaign/infrastructure/serializers/jsonapi/campaign-result-levels-per-tubes-and-competences-serializer.js
  api/src/shared/domain/read-models/CampaignReport.js
  api/tests/prescription/campaign/integration/domain/usecases/find-paginated-filtered-organization-campaigns_test.js
  api/tests/prescription/campaign/integration/domain/usecases/get-campaign-participations_test.js
  api/tests/prescription/campaign/integration/domain/usecases/get-result-levels-per-tubes-and-competences_test.js
  api/tests/prescription/campaign/unit/application/api/campaigns-api_test.js
  api/tests/prescription/campaign/unit/domain/models/CampaignResultLevelsPerTubesAndCompetences_test.js
  api/tests/prescription/campaign/unit/domain/models/TubeResultForKnowledgeElementSnapshots_test.js
  api/tests/prescription/campaign/unit/infrastructure/serializers/jsonapi/campaign-result-levels-per-tubes-and-competences-serializer_test.js
  api/tests/test-helper.js
  api/tests/test-helper_test.js
  api/tests/unit/domain/read-models/CampaignReport_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12223 [BUGFIX] Positionner le résultat global à partiellement atteint quand au moins une étape est réussie
  api/src/school/domain/services/compute-global-result.js
  api/tests/school/unit/domain/services/compute-global-result_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#12137 [FEATURE] Améliorer l'UX de l'écran de connexion à l'espace surveillant (PIX-17460).
  certif/app/components/login-session-supervisor/footer.gjs
  certif/app/components/login-session-supervisor/footer.scss
  certif/app/components/login-session-supervisor/form.gjs
  certif/app/components/login-session-supervisor/form.scss
  certif/app/components/login-session-supervisor/header.gjs
  certif/app/components/login-session-supervisor/header.scss
  certif/app/components/login-session-supervisor/index.gjs
  certif/app/components/login-session-supervisor/index.scss
  certif/app/styles/app.scss
  certif/app/styles/components/login-session-supervisor.scss
  certif/tests/acceptance/session-supervising-error-test.js
  certif/tests/acceptance/session-supervising-test.js
  certif/tests/acceptance/supervisor-portal-access-test.js
  certif/tests/integration/components/login-session-supervisor/form-test.gjs
  certif/tests/integration/components/login-session-supervisor/index-test.gjs
  certif/translations/en.json
  certif/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12202 [FEATURE] Ajout d'une route de rescoring de certification (PIX-17625).
  api/src/certification/evaluation/application/certification-rescoring-controller.js
  api/src/certification/evaluation/application/certification-rescoring-route.js
  api/src/certification/evaluation/domain/models/Session.js
  api/src/certification/evaluation/domain/usecases/index.js
  api/src/certification/evaluation/domain/usecases/rescore-certification.js
  api/src/certification/evaluation/infrastructure/repositories/session-repository.js
  api/src/certification/evaluation/routes.js
  api/src/shared/domain/errors.js
  api/tests/certification/evaluation/acceptance/application/certification-rescoring-route_test.js
  api/tests/certification/evaluation/integration/infrastructure/repositories/session-repository_test.js
  api/tests/certification/evaluation/unit/application/certification-rescoring-route_test.js
  api/tests/certification/evaluation/unit/domain/usecases/rescore-certification_test.js
  api/tests/tooling/domain-builder/factory/certification/evaluation/build-session.js
  api/tests/tooling/domain-builder/factory/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12219 [TECH] Suppression de la colonne isV3Pilot en BDD (PIX-17580).
  api/db/migrations/20250505132751_remove-isV3Pilot-column-in-certification-centers-table.js
  api/tests/shared/acceptance/application/assessments/assessment-controller-get-next-challenge-for-certification_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, team-captains

#12231 [TECH] Renommage de CertificationRescoredByScript.
  api/scripts/certification/rescore-certifications.js
  api/src/certification/evaluation/domain/events/CertificationRescored.js
  api/src/certification/evaluation/domain/usecases/rescore-certification.js
  api/src/shared/domain/events/handle-certification-rescoring.js
  api/tests/certification/evaluation/unit/domain/usecases/rescore-certification_test.js
  api/tests/integration/scripts/certification/rescore-certifications_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#12212 [BUGFIX] Supprimer les date de legal-document-version-user-acceptances lorsqu'on anonymise un utilisateur (PIX-17730)
  api/src/legal-documents/infrastructure/repositories/user-acceptance.repository.js
  api/src/privacy/domain/usecases/anonymize-user.usecase.js
  api/tests/legal-documents/integration/infrastructure/repositories/user-acceptance.repository.test.js
  api/tests/privacy/integration/domain/usecases/anonymize-user.usecase.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12110 [TECH] :truck: Déplace le cas d'utilisation `find competence evaluations by assessment` vers le répertoire `src/shared/`
  api/src/evaluation/domain/usecases/find-competence-evaluations-by-assessment.js
  api/src/shared/application/assessments/assessment-controller.js
  api/tests/evaluation/unit/domain/usecases/find-competence-evaluations-by-assessment_test.js
  api/tests/shared/unit/application/assessements/assessment-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-evaluation, cross-team, Bounded-context-migration

#12217 [FEATURE] Assurer cohérence du sequenceNumber dans les events enregistrés (PIX-17708)
  api/db/database-builder/factory/build-passage-event.js
  api/src/devcomp/domain/factories/passage-event-factory.js
  api/src/devcomp/domain/usecases/record-passage-events.js
  api/src/devcomp/infrastructure/repositories/passage-event-repository.js
  api/tests/devcomp/integration/repositories/passage-event-repository_test.js
  api/tests/devcomp/unit/domain/factories/passage-event-factory_test.js
  api/tests/devcomp/unit/domain/usecases/record-passage-events_test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12159 [FEATURE] Appeler la route d'archivage des centres de certification en lot depuis Pix Admin (PIX-17628).
  admin/app/adapters/certification-centers-batch-archive.js
  admin/app/components/administration/deployment/certification-centers-batch-archive.gjs
  admin/app/components/administration/deployment/index.gjs
  admin/tests/integration/components/administration/deployment/certification-centers-batch-archive-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12227 [FEATURE] Créer un service pour enregistrer une séquence d'événements dans un passage (PIX-16955)
  api/src/devcomp/infrastructure/serializers/jsonapi/passage-event-serializer.js
  api/tests/devcomp/acceptance/application/passages/passage-events-controller_test.js
  api/tests/devcomp/unit/infrastructure/serializers/jsonapi/passage-event-serializer_test.js
  mon-pix/app/adapters/passage-events-collection.js
  mon-pix/app/components/module/element/flashcards/flashcards.gjs
  mon-pix/app/models/passage-events-collection.js
  mon-pix/app/routes/module/passage.js
  mon-pix/app/services/passage-events.js
  mon-pix/tests/integration/components/module/flashcards_test.gjs
  mon-pix/tests/unit/adapters/passage-events-collection-test.js
  mon-pix/tests/unit/routes/module/passage-test.js
  mon-pix/tests/unit/services/passage-events-test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12184 [FEATURE] Amélioration des certificats V2 sur Pix App (PIX-17632).
  mon-pix/app/components/certifications/candidate-certificate/v2-certificate.gjs
  mon-pix/app/components/certifications/candidate-certificate/v3-certificate.gjs
  mon-pix/app/components/certifications/certificate-information/competences-details.gjs
  mon-pix/app/components/certifications/certificate-information/complementary-information-details.gjs
  mon-pix/app/components/certifications/certificate-information/header-details.gjs
  mon-pix/app/components/certifications/shareable-certificate/v2-certificate.gjs
  mon-pix/app/components/certifications/shareable-certificate/v3-certificate.gjs
  mon-pix/app/models/certification.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_user-certification-hexagon-score.scss
  mon-pix/app/styles/components/_user-certifications-detail-competence.scss
  mon-pix/app/styles/components/_user-certifications-detail-competences-list.scss
  mon-pix/app/styles/components/_user-certifications-detail-header.scss
  mon-pix/app/styles/components/_user-certifications-detail-result.scss
  mon-pix/app/styles/components/certifications/candidate-certificate/_v2-certificate.scss
  mon-pix/app/styles/components/certifications/certificate-information/_complementary-information-details.scss
  mon-pix/app/styles/components/certifications/certificate-information/_header-details.scss
  mon-pix/app/styles/components/certifications/shareable-certificate/_v2-certificate.scss
  mon-pix/app/styles/components/certifications/shareable-certificate/_v3-certificate.scss
  mon-pix/app/styles/pages/_user-certifications-get.scss
  mon-pix/public/images/macaron-certif.svg
  mon-pix/tests/acceptance/authenticated/user-certifications/get-test.js
  mon-pix/tests/helpers/get-table-data.js
  mon-pix/tests/integration/components/certifications/certificate-information/competences-details-test.gjs
  mon-pix/tests/integration/components/certifications/complementary-information-details-test.gjs
  mon-pix/tests/integration/components/header-details-test.gjs
  mon-pix/tests/integration/components/user-certifications-detail-competence-test.js
  mon-pix/tests/integration/components/user-certifications-detail-competences-list-test.js
  mon-pix/tests/integration/components/user-certifications-detail-header-test.js
  mon-pix/tests/unit/components/certifications/header-details-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12228 [TECH] Migrer le feature toggle de l'activation des quêtes vers le nouveaux système (PIX-17760)
  api/config/feature-toggles-config.js
  api/src/evaluation/application/answers/answer-controller.js
  api/src/evaluation/infrastructure/repositories/answer-job-repository.js
  api/src/shared/application/assessments/assessment-controller.js
  api/src/shared/config.js
  api/tests/evaluation/acceptance/application/answers/answer-controller-save_test.js
  api/tests/evaluation/unit/application/answers/answer-controller_test.js
  api/tests/evaluation/unit/infrastructure/repositories/answer-job-repository_test.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  api/tests/shared/unit/application/assessements/assessment-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12076 [FEATURE] Création module au-dela-des-mots-de-passe (débutant)
  api/src/devcomp/infrastructure/datasources/learning-content/modules/au-dela-des-mots-de-passe.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12230 [TECH] Migrer le feature toggle de basculement synchrone/asynchrone des quêtes vers le nouveaux système (PIX-17761)
  api/config/feature-toggles-config.js
  api/src/evaluation/application/answers/answer-controller.js
  api/src/evaluation/infrastructure/repositories/answer-job-repository.js
  api/src/shared/config.js
  api/tests/evaluation/acceptance/application/answers/answer-controller-save_test.js
  api/tests/evaluation/unit/application/answers/answer-controller_test.js
  api/tests/evaluation/unit/infrastructure/repositories/answer-job-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12188 [FEATURE] Afficher la nouvelle page d'analyse de résultat
  api/src/prescription/campaign/infrastructure/serializers/jsonapi/campaign-report-serializer.js
  api/src/prescription/campaign/infrastructure/serializers/jsonapi/campaign-result-levels-per-tubes-and-competences-serializer.js
  api/tests/prescription/campaign/unit/infrastructure/serializers/jsonapi/campaign-report-serializer_test.js
  api/tests/prescription/campaign/unit/infrastructure/serializers/jsonapi/campaign-result-levels-per-tubes-and-competences-serializer_test.js
  orga/app/components/analysis/analysis-per-tubes-and-competences.gjs
  orga/app/components/analysis/analysis-per-tubes-and-competences.scss
  orga/app/models/campaign-result-levels-per-tubes-and-competence.js
  orga/app/models/campaign.js
  orga/app/models/levels-per-competence.js
  orga/app/models/levels-per-tube.js
  orga/app/routes/authenticated/campaigns/campaign/analysis.js
  orga/app/styles/app.scss
  orga/app/templates/authenticated/campaigns/campaign/analysis.gjs
  orga/tests/acceptance/campaign-analysis-test.js
  orga/tests/integration/components/analysis/analysis-per-tubes-and-competences_test.gjs
  orga/tests/unit/routes/authenticated/campaigns/campaign/analysis-test.js
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12239 [TECH] Corriger le flaky sur la route passage de Pix App (PIX-17784)
  mon-pix/tests/unit/routes/module/passage-test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12234 [TECH] Ajoute la gestion des juridictions dans le script de gestion des applications clientes.
  api/scripts/identity-access-management/client-applications.js
  api/src/identity-access-management/infrastructure/repositories/client-application.repository.js
  api/tests/identity-access-management/integration/infrastructure/repositories/client-application.repository.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-maddo

#12243 [FEATURE] Supprimer les contraintes non génériques dans la table audit-log (PIX-17737)
  audit-logger/src/db/migrations/20250507131419_drop-non-generic-constraints.ts
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#12218 [FEATURE] Récupérer les informations nécessaires à l'affichage dynamique de la récupération de compte (PIX-17504)
  api/lib/application/sco-organization-learners/sco-organization-learner-controller.js
  api/src/identity-access-management/application/account-recovery/account-recovery.controller.js
  api/src/identity-access-management/domain/usecases/get-account-recovery-details.usecase.js
  api/src/identity-access-management/infrastructure/repositories/authentication-method.repository.js
  api/src/identity-access-management/infrastructure/serializers/jsonapi/student-information-for-account-recovery.serializer.js
  api/tests/identity-access-management/acceptance/application/account-recovery/account-recovery.route.test.js
  api/tests/identity-access-management/integration/application/account-recovery/account-recovery.controller.test.js
  api/tests/identity-access-management/integration/domain/usecases/get-account-recovery-details.usecase.test.js
  api/tests/identity-access-management/integration/infrastructure/repositories/authentication-method.repository.test.js
  api/tests/identity-access-management/unit/application/account-recovery/account-recovery.controller.test.js
  api/tests/identity-access-management/unit/domain/usecases/get-account-recovery-details.usecase.test.js
  api/tests/identity-access-management/unit/infrastructure/serializers/jsonapi/student-information-for-account-recovery.serializer.test.js
Labels: :rocket: Ready to Merge, team-acces

#12208 [BUGFIX] Les "embed" des modules n'acceptent pas le copier-coller (PIX-17602)
  mon-pix/app/components/module/element/embed.gjs
  mon-pix/tests/integration/components/module/embed_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12246 [FEATURE] Supprimer les contraintes non génériques dans AuditLogger (PIX-17790)
  audit-logger/src/lib/controllers/create-audit-log.controller.ts
  audit-logger/src/lib/domain/models/audit-log.ts
  audit-logger/src/lib/domain/models/models.definition.ts
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12245 [FEATURE] Élargir les contraintes de UserAnonymizedEventLoggingJob pour pouvoir traiter tous les événements (PIX-17789)
  api/src/identity-access-management/domain/models/UserAnonymizedEventLoggingJob.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12203 [TECH] Déplacer les Banner Alert dans le PixAppLayout de PixApp (PIX-17724)
  mon-pix/app/components/authentication-layout/index.gjs
  mon-pix/app/components/authentication-layout/index.scss
  mon-pix/app/components/data-protection-policy-information-banner.gjs
  mon-pix/app/components/global/app-layout.gjs
  mon-pix/app/controllers/application.js
  mon-pix/app/styles/app.scss
  mon-pix/app/templates/application.gjs
  mon-pix/app/templates/authenticated.gjs
  mon-pix/app/templates/authenticated/attestations.gjs
  mon-pix/app/templates/authenticated/certifications/join.gjs
  mon-pix/app/templates/authenticated/certifications/resume.gjs
  mon-pix/app/templates/authenticated/competences.gjs
  mon-pix/app/templates/authenticated/profile.gjs
  mon-pix/app/templates/authenticated/sitemap.gjs
  mon-pix/app/templates/authenticated/user-account.gjs
  mon-pix/app/templates/authenticated/user-certifications/get.gjs
  mon-pix/app/templates/authenticated/user-certifications/index.gjs
  mon-pix/app/templates/authenticated/user-dashboard.gjs
  mon-pix/app/templates/authenticated/user-tests.gjs
  mon-pix/app/templates/authenticated/user-trainings.gjs
  mon-pix/app/templates/authenticated/user-tutorials.gjs
  mon-pix/app/templates/download-session-results.gjs
  mon-pix/app/templates/error.gjs
  mon-pix/app/templates/fill-in-campaign-code.gjs
  mon-pix/app/templates/fill-in-certificate-verification-code.gjs
  mon-pix/app/templates/shared-certification.gjs
  mon-pix/tests/acceptance/application-test.js
  mon-pix/tests/integration/components/global/app-layout-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, cross-team

#12213 [BUGFIX] Ne plus retourner d'erreur BDD lors d'une violation de contrainte sur un double insertion de feature sur un learner (PIX-17734)
  api/src/prescription/organization-learner-feature/application/organization-learner-features-controller.js
  api/src/prescription/organization-learner-feature/domain/usecases/create-organization-learner-feature.js
  api/src/prescription/organization-learner/infrastructure/repositories/organization-learner-feature-repository.js
  api/tests/prescription/organization-learner-feature/integration/infrastructure/organization-learner-feature-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, 🎒👧🏽👦🏾 PIX JUNIOR

#12224 [BUGFIX] Corriger le calcul de résultat d'une étape (PIX-17751)
  api/src/school/domain/services/compute-step-result.js
  api/tests/school/unit/domain/services/compute-step-result_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#12247 [FEATURE] Réinitialiser le numéro de séquence lors du démarrage d'un passage dans Pix App (PIX-17710)
  mon-pix/app/services/passage-events.js
  mon-pix/tests/unit/services/passage-events-test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12222 [BUGFIX] Ne pas interrompre le script d'envoi d'invitations en masse à rejoindre une organisation (PIX-16645)
  api/src/shared/application/scripts/parsers.js
  api/src/team/scripts/send-organization-invitations.script.js
  api/tests/shared/unit/application/scripts/files/invalid.csv
  api/tests/shared/unit/application/scripts/files/valid.csv
  api/tests/shared/unit/application/scripts/parsers_test.js
  api/tests/team/unit/scripts/send-organization-invitations.script_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12027 [TECH] Supprimer le code du feature toggle isPixAdminNewSidebarEnabled (PIX-17458)
  admin/app/controllers/authenticated.js
  admin/app/models/feature-toggle.js
  admin/app/templates/authenticated.hbs
  admin/tests/acceptance/authenticated-test.js
  admin/tests/acceptance/authenticated/certification-centers/list-test.js
  admin/tests/acceptance/authenticated/sessions/list/to-be-published-test.js
  admin/tests/acceptance/authenticated/sessions/list/with-required-action-test.js
  api/config/feature-toggles-config.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12238 [TECH] Ajout du juryId sur la route de rescoring (PIX-17781).
  api/src/certification/evaluation/application/certification-rescoring-controller.js
  api/src/certification/evaluation/domain/events/CertificationRescored.js
  api/src/certification/evaluation/domain/usecases/rescore-certification.js
  api/tests/certification/evaluation/acceptance/application/certification-rescoring-route_test.js
  api/tests/certification/evaluation/unit/application/certification-rescoring-route_test.js
  api/tests/certification/evaluation/unit/domain/usecases/rescore-certification_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12226 [FEATURE] Alignement du footer sur le contenu (pix-17757)
  junior/app/components/footer.gjs
  junior/app/styles/components/footer.scss
  junior/app/templates/organization-code.hbs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, 🎒👧🏽👦🏾 PIX JUNIOR

#12244 [FEATURE] : Envoyer tous les passage events de type FLASHCARDS au service passage-events (PIX-17779)
  api/src/devcomp/domain/models/passage-events/flashcard-events.js
  api/src/devcomp/infrastructure/datasources/learning-content/modules/bac-a-sable.json
  api/tests/devcomp/integration/domain/models/flashcard-events/flashcard-events_test.js
  mon-pix/app/components/module/element/flashcards/flashcards.gjs
  mon-pix/tests/integration/components/module/flashcards_test.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12264 [FEATURE] Ajout d'un boolean pour activer/désactiver la nouvelle suppression (PIX-17706)
  api/config/feature-toggles-config.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12252 [FEATURE] Affichage du positionnement global sur la nouvelle page d'analyse de campagne (PIX-17026)
  orga/app/components/analysis/analysis-per-tubes-and-competences.gjs
  orga/app/components/analysis/analysis-per-tubes-and-competences.scss
  orga/app/components/analysis/global-positioning.gjs
  orga/app/components/analysis/global-positioning.scss
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/campaigns/campaign/analysis.scss
  orga/app/templates/authenticated/campaigns/campaign/analysis.gjs
  orga/tests/acceptance/campaign-analysis-test.js
  orga/tests/integration/components/analysis/analysis-per-tubes-and-competences_test.gjs
  orga/tests/integration/components/analysis/global-positioning_test.gjs
  orga/tests/integration/templates/analysis_test.gjs
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12270 [FEATURE] Afficher les titres des grains dans la navbar (PIX-17587)
  mon-pix/app/components/module/layout/navbar.gjs
  mon-pix/tests/integration/components/module/navbar_test.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12258 [TECH] Déplacer le feature toggle Companion dans le front mon-pix (PIX-17805)
  api/sample.env
  api/src/shared/config.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  certif/app/models/feature-toggle.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/services/pix-companion.js
  mon-pix/config/environment.js
  mon-pix/tests/unit/services/feature-toggles-test.js
  mon-pix/tests/unit/services/pix-companion-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-companion

#12248 [FEATURE] Envoyer une notification Slack suite à une release
  .github/workflows/release.yml
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, cross-team, no-review-app

#12263 [BUGFIX] Retirer la contrainte qui veut qu'une organisation fille ait le même type que l'organisation mère (PIX-17775)
  admin/app/controllers/authenticated/organizations/get/children.js
  admin/tests/unit/controllers/authenticated/organizations/get/children-test.js
  admin/translations/en.json
  admin/translations/fr.json
  api/src/organizational-entities/domain/usecases/attach-child-organization-to-organization.js
  api/tests/organizational-entities/acceptance/application/organization/organization.admin.route.test.js
  api/tests/organizational-entities/unit/domain/usecases/attach-child-organization-to-organization_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12275 Revert "[FEATURE] Afficher les titres des grains dans la navbar (PIX-17587)" (PIX-17587)
  mon-pix/app/components/module/layout/navbar.gjs
  mon-pix/tests/integration/components/module/navbar_test.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12241 [TECH] optimisation d'une requête certif
  api/src/certification/session-management/infrastructure/repositories/session-summary-repository.js
  api/src/shared/infrastructure/utils/knex-utils.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#12271 [FEATURE] Aligner les columns de tableaux dans la page d'analyse de résultats (PIX-17803)
  orga/app/components/analysis/analysis-per-tubes-and-competences.gjs
  orga/app/components/analysis/analysis-per-tubes-and-competences.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12260 [BUGFIX] Corriger le script de rattrapage de données sur la suppression des dates (PIX-17731)
  api/src/legal-documents/scripts/backfill-data-for-anonymized-users.script.js
  api/tests/legal-documents/integration/scripts/backfill-data-for-anonymized-users.script.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12276 [FEATURE] Support nouveau type d'element `qcu-declarative`(PIX-17683)
  api/scripts/modulix/get-elements-csv.js
  api/src/devcomp/domain/factories/passage-event-factory.js
  api/src/devcomp/domain/models/element/QCU-declarative.js
  api/src/devcomp/domain/models/element/QCU.js
  api/src/devcomp/domain/models/passage-events/answerable-element-events.js
  api/src/devcomp/infrastructure/datasources/learning-content/modules/bac-a-sable.json
  api/src/devcomp/infrastructure/factories/module-factory.js
  api/tests/devcomp/acceptance/scripts/get-elements-csv_test.js
  api/tests/devcomp/acceptance/scripts/test-module.json
  api/tests/devcomp/integration/domain/models/flashcard-events/answerable-element-events_test.js
  api/tests/devcomp/unit/domain/factories/passage-event-factory_test.js
  api/tests/devcomp/unit/domain/models/element/QCU-declarative_test.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/element/qcu-declarative-schema.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/module-schema.js
  api/tests/devcomp/unit/infrastructure/factories/module-factory_test.js
  api/tests/devcomp/unit/infrastructure/serializers/jsonapi/module-serializer_test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12249 [FEATURE] Traiter les événements "PASSAGE_TERMINATED" comme les autres enregistrements de traces d'apprentissage (PIX-17663)(PIX-16729)
  api/src/devcomp/application/passage-events/passage-events-controller.js
  api/src/devcomp/application/passages/controller.js
  api/src/devcomp/domain/usecases/record-passage-events.js
  api/src/devcomp/domain/usecases/terminate-passage.js
  api/tests/devcomp/acceptance/application/passages/passage-events-controller_test.js
  api/tests/devcomp/unit/application/passage-events/passage-events-controller_test.js
  api/tests/devcomp/unit/application/passages/controller_test.js
  api/tests/devcomp/unit/domain/usecases/record-passage-events_test.js
  api/tests/devcomp/unit/domain/usecases/terminate-passage_test.js
  mon-pix/app/components/module/passage.gjs
  mon-pix/app/services/passage-events.js
  mon-pix/mirage/routes/passages/create-passage-events.js
  mon-pix/mirage/routes/passages/index.js
  mon-pix/tests/integration/components/module/passage_test.gjs
  mon-pix/tests/unit/services/passage-events-test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12211 [TECH] Utiliser Stages acquisitions dans la page des Résultats d'une campagne de type ASSESSMENT (Pix-17297)
  api/src/evaluation/infrastructure/repositories/stage-acquisition-repository.js
  api/src/prescription/campaign/domain/usecases/get-campaign.js
  api/src/prescription/campaign/domain/usecases/index.js
  api/src/prescription/campaign/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
  api/src/prescription/campaign/infrastructure/exports/campaigns/campaign-assessment-result-line.js
  api/src/prescription/campaign/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/src/prescription/campaign/infrastructure/repositories/campaign-participation-info-repository.js
  api/src/prescription/campaign/infrastructure/repositories/campaign-report-repository.js
  api/src/prescription/campaign/infrastructure/repositories/helpers/get-latest-participation-shared-for-one-learner.js
  api/src/prescription/campaign/infrastructure/repositories/target-profile-repository.js
  api/src/prescription/campaign/infrastructure/serializers/csv/campaign-assessment-export.js
  api/src/shared/domain/models/user-campaign-results/StageCollection.js
  api/src/shared/domain/read-models/CampaignReport.js
  api/src/shared/infrastructure/repositories/organization-repository.js
  api/tests/evaluation/integration/infrastructure/repositories/stage-acquisition-repository_test.js
  api/tests/prescription/campaign/integration/domain/usecases/get-campaign_test.js
  api/tests/prescription/campaign/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/prescription/campaign/integration/infrastructure/repositories/campaign-assessment-participation-result-list-repository_test.js
  api/tests/prescription/campaign/integration/infrastructure/repositories/campaign-report-repository_test.js
  api/tests/prescription/campaign/unit/infrastructure/exports/campaigns/campaign-assessment-result-line_test.js
Labels: :rocket: Ready to Merge, Func Review OK, team-prescription

#12278 [FEATURE] Ajouter le type d'élément custom dans le get-element-csv (PIX-17426)
  api/scripts/modulix/get-elements-csv.js
  api/tests/devcomp/acceptance/scripts/get-elements-csv_test.js
  api/tests/devcomp/acceptance/scripts/test-module.json
Labels: :rocket: Ready to Merge, team-devcomp

#12289 [BUGFIX] Encoder les apostrophes dans les PDF v3 (PIX-17829).
  api/src/certification/results/infrastructure/utils/pdf/templates/certificate.js
  api/tests/certification/results/integration/infrastructure/utils/pdf/certificate-test.pdf
  api/tests/certification/results/integration/infrastructure/utils/pdf/generate-pdf-certificate_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12214 [TECH] Vraie simulation de certification V3 dans les seeds
  api/db/seeds/data/team-certification/cases/simple-sco-managing-students-certification.js
  api/db/seeds/data/team-certification/tools/create-published-session-with-completed-validated-certification.js
  api/db/seeds/data/team-certification/tools/makeCandidatePassCertification.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12290 [FEATURE] Modifier le message de la notification Slack post release
  .github/workflows/release.yml
Labels: :rocket: Ready to Merge, team-captains, cross-team

#12269 [FEATURE] Permettre la suppression d'une campaign-participation avec anonymisation (Pix-17709)
  admin/app/adapters/user-participation.js
  admin/mirage/config.js
  admin/tests/acceptance/authenticated/users/get-test.js
  admin/tests/unit/adapters/user-participation-test.js
  api/src/prescription/campaign-participation/application/campaign-participation-controller.js
  api/src/prescription/campaign-participation/application/campaign-participation-route.js
  api/src/prescription/campaign-participation/domain/models/CampaignParticipation.js
  api/src/prescription/campaign-participation/domain/usecases/delete-campaign-participation-for-admin.js
  api/src/prescription/campaign-participation/domain/usecases/delete-campaign-participation.js
  api/src/prescription/campaign-participation/domain/usecases/index.js
  api/src/prescription/campaign-participation/infrastructure/repositories/campaign-participation-repository.js
  api/tests/prescription/campaign-participation/acceptance/application/campaign-participation-route_test.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/delete-campaign-participation_test.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/campaign-participation-repository_test.js
  api/tests/prescription/campaign-participation/unit/application/campaign-participation-controller_test.js
  api/tests/prescription/campaign-participation/unit/application/campaign-participation-route_test.js
  api/tests/prescription/campaign-participation/unit/domain/models/CampaignParticipation_test.js
  api/tests/prescription/campaign-participation/unit/domain/usecases/delete-campaign-participation-for-admin_test.js
  api/tests/prescription/campaign-participation/unit/domain/usecases/delete-campaign-participation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12292 [TECH] Automatiser la création de version Jira à la création d’un nouveau tag
  .github/workflows/create-jira-version.yaml
Labels: :rocket: Ready to Merge

#12295 [TECH] Retirer le script de rattrapage de donnée sur l'anonymisation (PIX-17841)
  api/src/legal-documents/scripts/backfill-data-for-anonymized-users.script.js
  api/tests/legal-documents/integration/scripts/backfill-data-for-anonymized-users.script.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#12288 [FEATURE] Streamer/Batch les lignes CSV du script d'anonymisation (PIX-17830)
  api/scripts/certification/fix-doubled-answers.js
  api/scripts/certification/rescore-certifications.js
  api/src/evaluation/scripts/add-multiple-level-stages.js
  api/src/identity-access-management/scripts/anonymize-users-in-batch.script.js
  api/src/organizational-entities/scripts/add-or-update-certification-centers-dpo-info.js
  api/src/organizational-entities/scripts/archive-certification-centers-script.js
  api/src/shared/application/scripts/parsers.js
  api/src/shared/infrastructure/helpers/csv.js
  api/src/team/scripts/send-organization-invitations.script.js
  api/tests/identity-access-management/unit/scripts/anonymize-users-in-batch.script.test.js
  api/tests/shared/unit/application/scripts/files/invalid.csv
  api/tests/shared/unit/application/scripts/files/valid.csv
  api/tests/shared/unit/application/scripts/parsers_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12268 [TECH] Migration DDD : migration de api/lib/infrastructure/authentication.js vers src/ (PIX-17797)
  api/server.js
  api/server.maddo.js
  api/src/certification/results/application/livret-scolaire-route.js
  api/src/certification/results/application/parcoursup-route.js
  api/src/identity-access-management/infrastructure/server-authentication.js
  api/src/prescription/campaign-participation/application/pole-emploi-route.js
  api/src/prescription/organization-place/application/organization-place-route.js
  api/src/shared/infrastructure/authentication-strategy-names.js
  api/tests/identity-access-management/unit/infrastructure/server-authentication.test.js
  api/tests/tooling/server/http-test-server.js
Labels: :rocket: Ready to Merge, team-acces, Bounded-context-migration

#12285 [FEATURE] Supprimer les méthode d'authentifications GAR et nom d'utilisateur lors de la sortie du sco (PIX-17509)
  api/src/identity-access-management/domain/usecases/update-user-for-account-recovery.usecase.js
  api/tests/identity-access-management/integration/infrastructure/repositories/user.repository.test.js
  api/tests/identity-access-management/unit/domain/usecases/update-user-for-account-recovery.usecase.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12307 [TECH] Séparer 2 commandes dans la github action de création de version jira
  .github/workflows/create-jira-version.yaml
Labels: Tech Review OK, :rocket: Ready to Merge

#12265 [FEATURE] Ajouter une action "Archiver en masse des organisations" dans Pix Admin (PIX-17151)
  admin/app/components/administration/deployment/index.gjs
  admin/app/components/administration/deployment/organizations-batch-archive.gjs
  admin/app/services/current-domain.js
  admin/app/services/request-manager-handlers/app-info-handler.js
  admin/app/services/request-manager-handlers/auth-handler.js
  admin/app/services/request-manager-handlers/json-handler.js
  admin/app/services/request-manager-handlers/locale-handler.js
  admin/app/services/request-manager.js
  admin/tests/integration/components/administration/deployment/organizations-batch-archive-test.gjs
  admin/tests/unit/services/request-manager-test.js
  admin/translations/en.json
  admin/translations/fr.json
  api/src/organizational-entities/application/http-error-mapper-configuration.js
  api/src/organizational-entities/application/organization/organization.admin.controller.js
  api/src/organizational-entities/application/organization/organization.admin.route.js
  api/src/organizational-entities/domain/errors.js
  api/src/organizational-entities/domain/usecases/archive-organizations-in-batch.usecase.js
  api/src/organizational-entities/domain/usecases/index.js
  api/src/organizational-entities/infrastructure/repositories/organization-for-admin.repository.js
  api/src/shared/infrastructure/serializers/csv/csv-serializer.js
  api/tests/organizational-entities/acceptance/application/organization/organization.admin.route.test.js
  api/tests/organizational-entities/integration/domain/usecases/archive-organization.usecase.test.js
  api/tests/organizational-entities/integration/domain/usecases/archive-organizations-in-batch.usecase.test.js
  api/tests/organizational-entities/integration/infrastructure/repositories/organization-for-admin.repository.test.js
  api/tests/shared/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12298 [TECH] Mise à jour des packages sur PixOrga (PIX-17866)
  orga/package-lock.json
  orga/package.json
Labels: :rocket: Ready to Merge, Func Review OK, team-prescription

#12310 [FEATURE] Améliorer le design des modules (PIX-17833)
  mon-pix/app/components/module/element/_embed.scss
  mon-pix/app/components/module/grain/_grain.scss
  mon-pix/app/components/module/grain/grain.gjs
  mon-pix/app/components/module/layout/navbar.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12314 [TECH] Correction de deprecation SCSS dans Pix Orga
  orga/app/styles/components/campaign/charts/campaign-badge-acquisitions.scss
  orga/app/styles/components/campaign/charts/participants-by-stage.scss
  orga/app/styles/components/campaign/charts/results-distribution.scss
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12320 [BUGFIX] Changer le déclencheur de l'action
  .github/workflows/create-jira-version.yaml
Labels: :rocket: Ready to Merge

#12312 [FEATURE] Modulix - QROCM : corriger choix input pour autoriser Number (PIX-17424)
  api/src/devcomp/infrastructure/datasources/learning-content/modules/bac-a-sable.json
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/element/qrocm-schema.js
  mon-pix/app/components/module/element/qrocm.gjs
  mon-pix/tests/integration/components/module/qrocm_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12316 [TECH] Remplacer inject par service de l'import @ember/service
  admin/app/components/certification-centers/information-edit.gjs
  admin/app/services/current-user.js
  admin/app/services/feature-toggles.js
  admin/app/services/oidc-identity-providers.js
  admin/app/services/request-manager-handlers/auth-handler.js
  admin/app/services/request-manager-handlers/locale-handler.js
  admin/app/services/url.js
  certif/app/services/current-user.js
  certif/app/services/feature-toggles.js
  certif/app/services/features.js
  certif/app/services/locale.js
  certif/app/services/url.js
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/custom-organization-block.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/index.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/retry-or-reset-block.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-tabs/results-details/index.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-tabs/rewards/index.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-tabs/trainings.gjs
  mon-pix/app/components/global/app-layout.gjs
  mon-pix/app/components/global/app-main-header.gjs
  mon-pix/app/components/global/app-navigation.gjs
  mon-pix/app/services/authentication.js
  mon-pix/app/services/competence-evaluation.js
  mon-pix/app/services/current-user.js
  mon-pix/app/services/error-messages.js
  mon-pix/app/services/feature-toggles.js
  mon-pix/app/services/locale.js
  mon-pix/app/services/oidc-identity-providers.js
  mon-pix/app/services/request-manager-handlers/auth-handler.js
  mon-pix/app/services/request-manager-handlers/locale-handler.js
  mon-pix/app/services/url.js
  mon-pix/app/templates/application.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12305 [FEATURE] Utilise le composant CoverRateGauge dans la table d'analyse des resultats par sujets / compétences (PIX-17857)
  orga/app/components/analysis/analysis-per-tubes-and-competences.gjs
  orga/app/components/statistics/cover-rate-gauge.gjs
  orga/app/styles/components/statistics/cover-rate-gauge.scss
  orga/tests/integration/components/analysis/analysis-per-tubes-and-competences_test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12304 [FEATURE] Mettre à jour et generaliser updatedAt à l'anonymisation (PIX-17867)
  api/src/identity-access-management/domain/models/User.js
  api/tests/identity-access-management/integration/domain/usecases/anonymize-user.usecase.test.js
  api/tests/identity-access-management/unit/domain/models/User.test.js
  api/tests/privacy/integration/domain/usecases/anonymize-user.usecase.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12323 [BUGFIX] Corriger la mention du groupe dans le message slack envoyé par le workflow de release.
  .github/workflows/release.yml
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains, no-review-app

#12303 [FEATURE] Empêcher Ember de gérer les erreurs 403 de type HTML dans PixApp (PIX-17835).
  mon-pix/app/routes/application.js
  mon-pix/tests/unit/routes/application-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, cross-team

#12286 [FEATURE] Anonymiser les badges lors de la suppression des participations (PIX-17712)
  api/src/evaluation/infrastructure/repositories/badge-acquisition-repository.js
  api/src/prescription/campaign-participation/domain/usecases/delete-campaign-participation.js
  api/tests/evaluation/integration/infrastructure/repositories/badge-acquisition-repository_test.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/delete-campaign-participation_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12311 [TECH] Mise à jour de librairies sur Pix-Certif.
  certif/package-lock.json
  certif/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#12284 [TECH] Nettoyage de code inutil suite et fin de (PIX-17709)
  api/src/prescription/campaign-participation/application/campaign-participation-controller.js
  api/src/prescription/campaign-participation/application/campaign-participation-route.js
  api/src/prescription/campaign-participation/domain/usecases/delete-campaign-participation-for-admin.js
  api/tests/prescription/campaign-participation/acceptance/application/campaign-participation-route_test.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/delete-campaign-participation-for-admin_test.js
  api/tests/prescription/campaign-participation/unit/application/campaign-participation-route_test.js
  api/tests/prescription/campaign-participation/unit/domain/usecases/delete-campaign-participation-for-admin_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12318 [BUGFIX] Mauvais wording lors du signalement d'une épreuve avec pièce jointe (PIX-17677)
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#12282 [FEATURE] Modifier l'affichage de la dernière page de récupération de compte (PIX-17505)
  mon-pix/app/components/account-recovery/update-sco-record-form.gjs
  mon-pix/app/models/account-recovery-demand.js
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/routes/account-recovery/update-sco-record.js
  mon-pix/app/routes/logout.js
  mon-pix/app/styles/components/account-recovery/_update-sco-record-form.scss
  mon-pix/app/styles/pages/_account-recovery.scss
  mon-pix/app/templates/account-recovery/update-sco-record.gjs
  mon-pix/tests/acceptance/account-recovery/update-sco-record-test.js
  mon-pix/tests/integration/components/account-recovery/update-sco-record-form-test.js
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12322 [TECH] Remplacer l'utilisation du slug d'un module par l'id (PIX-17701)
  api/src/devcomp/application/passages/controller.js
  api/src/devcomp/domain/usecases/create-passage.js
  api/src/devcomp/infrastructure/repositories/module-repository.js
  api/src/devcomp/infrastructure/serializers/jsonapi/module-serializer.js
  api/tests/devcomp/acceptance/application/passages/passage-controller_test.js
  api/tests/devcomp/integration/repositories/module-repository_test.js
  api/tests/devcomp/unit/application/passages/controller_test.js
  api/tests/devcomp/unit/domain/usecases/create-passage_test.js
  api/tests/devcomp/unit/infrastructure/serializers/jsonapi/module-serializer_test.js
  mon-pix/app/adapters/module.js
  mon-pix/app/components/module/instruction/details.gjs
  mon-pix/app/components/module/passage.gjs
  mon-pix/app/models/module.js
  mon-pix/app/routes/module.js
  mon-pix/tests/acceptance/module/navigate-into-the-module-details_test.js
  mon-pix/tests/acceptance/module/navigate-into-the-module-passage_test.js
  mon-pix/tests/acceptance/module/navigate-into-the-module-recap_test.js
  mon-pix/tests/acceptance/module/retake_completed_module_test.js
  mon-pix/tests/acceptance/module/retry-qcm_test.js
  mon-pix/tests/acceptance/module/retry-qcu_test.js
  mon-pix/tests/acceptance/module/retry-qrocm_test.js
  mon-pix/tests/acceptance/module/verify-qcm_test.js
  mon-pix/tests/acceptance/module/verify-qcu_test.js
  mon-pix/tests/acceptance/module/verify-qrocm_test.js
  mon-pix/tests/acceptance/module/visit-module-details-page_test.js
  mon-pix/tests/acceptance/module/visit-module-passage-page_test.js
  mon-pix/tests/acceptance/module/visit-module-recap-page_test.js
  mon-pix/tests/integration/components/module/details_test.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
  mon-pix/tests/unit/adapters/module-test.js
  mon-pix/tests/unit/routes/module/module-test.js
  mon-pix/tests/unit/routes/module/passage-test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12324 [BUGFIX] Afficher les CF dans "Mes formations" quand l'envoi des résultats est désactivé (PIX-17581)
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-tabs/trainings.gjs
  mon-pix/tests/integration/components/campaigns/assessment/results/tabs/trainings-test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12331 [BUGFIX] Corriger l'import des modifiers provenant de PixUI (PIX-17922)
  admin/app/components/complementary-certifications/attach-badges/target-profile-selector/searchbar.gjs
  admin/tests/integration/components/common/tubes-selection-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-captains, cross-team

#12332 [TECH] Suppression des blueprints custom EmberJS
  admin/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js
  admin/blueprints/adapter-test/files/tests/unit/adapters/__name__-test.js
  admin/blueprints/component-test/files/tests/integration/components/__name__-test.js
  admin/blueprints/route-test/files/tests/unit/routes/__name__-test.js
  certif/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js
  certif/blueprints/adapter-test/files/tests/unit/adapters/__name__-test.js
  certif/blueprints/component-test/files/tests/integration/components/__name__-test.js
  certif/blueprints/route-test/files/tests/unit/routes/__name__-test.js
  junior/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js
  junior/blueprints/adapter-test/files/tests/unit/adapters/__name__-test.js
  junior/blueprints/component-test/files/tests/integration/components/__name__-test.js
  junior/blueprints/route-test/files/tests/unit/routes/__name__-test.js
  mon-pix/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js
  mon-pix/blueprints/adapter-test/files/tests/unit/adapters/__name__-test.js
  mon-pix/blueprints/component-test/files/tests/integration/components/__name__-test.js
  mon-pix/blueprints/route-test/files/tests/unit/routes/__name__-test.js
  orga/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js
  orga/blueprints/adapter-test/files/tests/unit/adapters/__name__-test.js
  orga/blueprints/component-test/files/tests/integration/components/__name__-test.js
  orga/blueprints/route-test/files/tests/unit/routes/__name__-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12254 [TECH] Migrer le suivi matomo vers plausible sur mon-pix
  mon-pix/app/components/attestations/content.gjs
  mon-pix/app/components/campaign-participation-overview/card/ended.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/attestation-result.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/custom-organization-block.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/index.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/retry-or-reset-block.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-tabs/results-details/index.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-tabs/rewards/index.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-tabs/trainings.gjs
  mon-pix/app/components/challenge-statement.gjs
  mon-pix/app/components/module/instruction/details.gjs
  mon-pix/app/components/module/passage.gjs
  mon-pix/app/components/training/card.gjs
  mon-pix/app/components/tutorials/card.gjs
  mon-pix/app/controllers/assessments/challenge.js
  mon-pix/app/metrics-adapters/plausible-adapter.js
  mon-pix/app/routes/application.js
  mon-pix/app/routes/assessments/resume.js
  mon-pix/app/routes/authenticated/certifications/resume.js
  mon-pix/app/routes/authenticated/competences/resume.js
  mon-pix/app/routes/authenticated/index.js
  mon-pix/app/routes/authenticated/user-account/delete-account.js
  mon-pix/app/routes/authenticated/user-account/index.js
  mon-pix/app/routes/authenticated/user-tutorials/index.js
  mon-pix/app/routes/authentication/sso-selection.js
  mon-pix/app/routes/campaigns/access.js
  mon-pix/app/routes/campaigns/assessment/start-or-resume.js
  mon-pix/app/routes/campaigns/entrance.js
  mon-pix/app/routes/campaigns/entry-point.js
  mon-pix/app/routes/campaigns/invited.js
  mon-pix/app/routes/campaigns/profiles-collection/start-or-resume.js
  mon-pix/app/routes/courses/start.js
  mon-pix/app/routes/module/index.js
  mon-pix/app/routes/not-found.js
  mon-pix/app/services/locale.js
  mon-pix/app/services/pix-metrics.js
  mon-pix/config/environment.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/application-test.js
  mon-pix/tests/acceptance/challenge-page-banner-test.js
  mon-pix/tests/integration/components/campaign-participation-overview/card/ended-test.js
  mon-pix/tests/integration/components/campaign/skill-review/attestation-result-test.gjs
  mon-pix/tests/integration/components/challenge-statement-test.js
  mon-pix/tests/integration/components/module/details_test.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
  mon-pix/tests/unit/components/module/video_test.gjs
  mon-pix/tests/unit/components/training/card-test.js
  mon-pix/tests/unit/components/tutorials/card-test.js
  mon-pix/tests/unit/metrics-adapters/plausible-adapter-test.js
  mon-pix/tests/unit/services/locale-test.js
  mon-pix/tests/unit/services/pix-metrics-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12333 [TECH] Suppression de Husky et Lint-staged
  .husky/.gitignore
  .husky/detect-learning-content
  .husky/lint
  .husky/pre-commit
  .husky/protect-branch
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12334 [TECH] Modifier le token github utilisé par le workflow de release
  .github/workflows/release.yml
Labels: :rocket: Ready to Merge, team-captains, cross-team, no-review-app

#12296 [TECH] Supprimer le script pour archiver en masse des centres de certification (PIX-17843)
  api/src/organizational-entities/scripts/archive-certification-centers-script.js
  api/tests/organizational-entities/unit/scripts/archive-certification-centers-script.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#12346 [BUGFIX] Corriger l'interpolation des variables dans la github action de création de version jira
  .github/workflows/create-jira-version.yaml
Labels: :rocket: Ready to Merge

#12343 [TECH] Corriger une injection de dépendances dans les tests qui était mal réalisée
  api/src/organizational-entities/domain/usecases/index.js
  api/src/organizational-entities/infrastructure/repositories/index.js
  api/tests/organizational-entities/integration/infrastructure/repositories/certification-center-api.repository.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#12325 [FEATURE] Ajoute la colonne "Type de campagne" dans la création de campagnes en masse (PIX-17859)
  api/src/prescription/campaign/application/campaign-adminstration-controller.js
  api/src/prescription/campaign/domain/errors.js
  api/src/prescription/campaign/domain/models/CampaignCreator.js
  api/src/prescription/campaign/domain/usecases/create-campaigns.js
  api/src/shared/infrastructure/serializers/csv/csv-serializer.js
  api/tests/prescription/campaign/unit/domain/models/CampaignCreator_test.js
  api/tests/prescription/campaign/unit/domain/usecases/create-campaigns_test.js
  api/tests/shared/unit/infrastructure/serializers/csv/csv-serializer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12349 [FEATURE] Créer la table des référentiels cadres (PIX-17884).
  api/db/migrations/20250519151410_create-certification-frameworks-challenges-table.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, no-review-app

#12277 [FEATURE] Appliquer le nouveau design de la liste des certifications sur Pix App (PIX-17664).
  api/src/certification/results/domain/models/PrivateCertificate.js
  api/src/certification/results/infrastructure/repositories/certificate-repository.js
  api/src/certification/results/infrastructure/serializers/private-certificate-serializer.js
  api/tests/certification/evaluation/acceptance/application/certification-route_test.js
  api/tests/certification/results/integration/infrastructure/repositories/certificate-repository_test.js
  api/tests/certification/results/unit/application/certificate-controller_test.js
  api/tests/certification/results/unit/domain/models/PrivateCertificate_test.js
  api/tests/certification/results/unit/infrastructure/serializers/private-certificate-serializer_test.js
  api/tests/tooling/domain-builder/factory/build-private-certificate.js
  mon-pix/app/components/certifications-list-item.gjs
  mon-pix/app/components/certifications-list.gjs
  mon-pix/app/components/certifications/list/item.gjs
  mon-pix/app/components/certifications/list/panel.gjs
  mon-pix/app/components/no-certification-panel.gjs
  mon-pix/app/components/user-certifications-panel.gjs
  mon-pix/app/models/certification.js
  mon-pix/app/styles/app.scss
  mon-pix/app/styles/components/_certifications-list-item.scss
  mon-pix/app/styles/components/_certifications-list.scss
  mon-pix/app/styles/components/_no-certification-panel.scss
  mon-pix/app/styles/components/_user-certification-hexagon-score.scss
  mon-pix/app/styles/components/certifications/list/_item.scss
  mon-pix/app/styles/components/certifications/list/_panel.scss
  mon-pix/app/templates/authenticated/user-certifications/index.gjs
  mon-pix/public/images/certificate/pix-score-hexagon.svg
  mon-pix/tests/acceptance/user-certifications-test.js
  mon-pix/tests/integration/components/certifications-list-item-test.js
  mon-pix/tests/integration/components/certifications-list-test.js
  mon-pix/tests/integration/components/certifications/certificate-information/complementary-information-details-test.gjs
  mon-pix/tests/integration/components/certifications/list/item-test.gjs
  mon-pix/tests/integration/components/certifications/list/panel-test.gjs
  mon-pix/tests/integration/components/no-certification-panel-test.js
  mon-pix/tests/integration/components/user-certifications-panel-test.js
  mon-pix/tests/unit/components/certifications/list/item-test.gjs
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: :rocket: Ready to Merge, Func Review OK, team-certif, Design Review OK

#12342 [TECH] Corrige le lockfile pour qu'il soit cohérent avec le fichier package.json
  certif/package-lock.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12336 [TECH] Suppression de dépendances non utilisées dans App/Admin/Junior
  admin/package-lock.json
  admin/package.json
  junior/config/environment.js
  junior/package-lock.json
  junior/package.json
  mon-pix/config/environment.js
  mon-pix/package-lock.json
  mon-pix/package.json
  mon-pix/tests/acceptance/user-tutorials/recommended-test.js
  mon-pix/tests/integration/components/tutorials/header-test.js
Labels: :rocket: Ready to Merge, cross-team

#12108 [TECH] :truck: Déplace le cas d'utilisation `create preview assessment` vers le repertoire `src/shared/`
  api/src/school/application/assessment-controller.js
  api/src/school/application/assessment-route.js
  api/src/school/domain/usecases/create-preview-assessment.js
  api/src/shared/application/assessments/assessment-controller.js
  api/src/shared/application/assessments/index.js
  api/tests/school/integration/domain/usecases/create-preview-assessment_test.js
  api/tests/school/unit/application/assessment-controller_test.js
  api/tests/school/unit/application/assessment-route_test.js
  api/tests/shared/unit/application/assessements/assessment-controller_test.js
  api/tests/shared/unit/application/assessements/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, Bounded-context-migration

#12353 [FEATURE] Afficher les POIC dans Modulix (PIX-17941)
  api/src/devcomp/infrastructure/datasources/learning-content/modules/bac-a-sable.json
  mon-pix/app/components/module/_normalize.scss
Labels: :rocket: Ready to Merge, team-devcomp

#12232 [FEATURE] Rendre générique le/les SSO utilisé(s) pour l'accès à Pix Admin (pouvoir utiliser ProConnect) (PIX-17895)
  admin/app/authenticators/oidc.js
  admin/app/components/login-form.gjs
  admin/app/models/oidc-identity-provider.js
  admin/app/routes/authentication/login-oidc.js
  admin/app/services/oidc-identity-providers.js
  admin/tests/integration/components/login-form-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12347 [FEATURE] Vider le champ mot de passe de la mire de connexion Pix App en cas d'erreur (PIX-17928)
  api/src/identity-access-management/application/http-error-mapper-configuration.js
  api/src/identity-access-management/domain/errors.js
  mon-pix/app/components/authentication/login-form.gjs
  mon-pix/app/services/error-messages.js
  mon-pix/config/environment.js
  mon-pix/tests/integration/components/authentication/login-form-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12215 [TECH] Ajouter un workflow pour gérer les vieilles pull requests
  .github/workflows/check-old-pull-requests.yml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, no-review-app

#12359 [TECH] Remplacer ember-flatpickr par un input date natif dans PixAdmin
  admin/app/app.js
  admin/app/components/certifications/candidate-edit-modal.gjs
  admin/app/styles/app.scss
  admin/ember-cli-build.js
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/certifications/candidate-edit-modal-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12115 [TECH] :truck: Déplace le cas d'utilisation `getCorrectionForAnswer` vers `src/evaluation/`
  api/lib/infrastructure/repositories/index.js
  api/src/evaluation/application/answers/answer-controller.js
  api/src/evaluation/domain/usecases/get-correction-for-answer.js
  api/src/evaluation/domain/usecases/index.js
  api/src/evaluation/infrastructure/repositories/correction-repository.js
  api/src/evaluation/infrastructure/repositories/index.js
  api/tests/evaluation/integration/infrastructure/repositories/correction-repository_test.js
  api/tests/evaluation/unit/application/answers/answer-controller_test.js
  api/tests/evaluation/unit/domain/usecases/get-correction-for-answer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, Bounded-context-migration

#12283 [TECH] Améliore la partie SQL de la vérification du code de certification (Pix-17791)
  api/db/migrations/20250513134311_remove-uppercase-index-on-certif-courses-table.js
  api/src/certification/evaluation/domain/services/verify-certificate-code-service.js
  api/src/certification/results/application/certificate-route.js
  api/src/certification/results/domain/usecases/get-certification-result-for-parcoursup.js
  api/src/certification/shared/infrastructure/repositories/certification-course-repository.js
  api/tests/certification/evaluation/unit/domain/services/verify-certificate-code-service_test.js
  api/tests/certification/results/acceptance/application/certificate-route_test.js
  api/tests/certification/results/unit/application/certificate-route_test.js
  api/tests/certification/results/unit/domain/usecases/get-certification-result-for-parcoursup_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif, team-captains

#12360 [FEATURE] Modifier les valeurs pour l'affichage des niveaux dans les tags (PIX-17967)
  orga/app/components/statistics/tag-level.gjs
  orga/tests/integration/components/analysis/analysis-per-tubes-and-competences_test.gjs
  orga/tests/integration/components/statistics/tag-level-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12345 [FEATURE] Création d'un endpoint côté API pour démarrer une conversation avec le LLM dans le cadre d'une épreuve avec un embed de prompt LLM (PIX-17903)
  api/config/feature-toggles-config.js
  api/db/seeds/data/team-contenu/data-builder.js
  api/sample.env
  api/src/devcomp/application/passages/controller.js
  api/src/devcomp/application/passages/index.js
  api/src/devcomp/domain/usecases/index.js
  api/src/devcomp/domain/usecases/start-embed-llm-chat.js
  api/src/llm/application/api/llm-api.js
  api/src/llm/application/api/models/LLMChatDTO.js
  api/src/llm/application/pre-handlers/index.js
  api/src/llm/domain/models/LLMChat.js
  api/src/shared/application/security-pre-handlers.js
  api/src/shared/config.js
  api/src/shared/infrastructure/utils/logger.js
  api/tests/devcomp/acceptance/application/passages/passage-controller_test.js
  api/tests/devcomp/unit/domain/usecases/start-embed-llm-chat_test.js
  api/tests/llm/integration/application/api/llm-api_test.js
  api/tests/llm/unit/application/pre-handlers/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu, team-devcomp

#12335 [TECH] Créer un script de suppression des méthodes de connexion pour les anciens utilisateurs scolaires (PIX-17515).
  api/src/identity-access-management/scripts/delete-ex-sco-authentication-methods.script.js
  api/tests/identity-access-management/integration/scripts/delete-ex-sco-authentication-methods.script.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12358 [TECH] Récupérer la configuration de l'algo v3 dans la BDD (PIX-17937).
  api/db/database-builder/factory/build-flash-algorithm-configuration.js
  api/sample.env
  api/src/certification/shared/infrastructure/repositories/certification-course-repository.js
  api/src/shared/config.js
  api/tests/certification/evaluation/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/certification/shared/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/shared/acceptance/application/assessments/assessment-controller-get-next-challenge-for-certification_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12339 [TECH] Remplacer des helpers dans admin par du code natif
  admin/app/components/badges/badge.gjs
  admin/app/components/certification-centers/information-edit.gjs
  admin/app/components/certifications/candidate-edit-modal.gjs
  admin/app/components/certifications/certification/comments.gjs
  admin/app/components/login-form.gjs
  admin/app/components/organizations/places-lot-creation-form.gjs
  admin/app/components/organizations/target-profiles-section.gjs
  admin/app/components/stages/update-stage.gjs
  admin/app/components/target-profiles/organizations.gjs
  admin/app/controllers/authenticated/certification-centers/get/team.js
  admin/app/controllers/authenticated/certifications.js
  admin/app/controllers/authenticated/sessions/session.js
  admin/app/controllers/authenticated/trainings/training/target-profiles.js
  admin/app/templates/authenticated/certification-centers/get/team.hbs
  admin/app/templates/authenticated/certifications.hbs
  admin/app/templates/authenticated/sessions/session.hbs
  admin/app/templates/authenticated/trainings/training/target-profiles.hbs
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12352 [FEATURE] Exécution du simulateur de déroulé sur des certifications complémentaires (PIX-17936).
  api/db/database-builder/factory/build-certification-frameworks-challenge.js
  api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-repository.js
  api/src/certification/flash-certification/application/scenario-simulator-controller.js
  api/src/certification/flash-certification/application/scenario-simulator-route.js
  api/src/certification/flash-certification/domain/usecases/index.js
  api/src/certification/flash-certification/domain/usecases/simulate-flash-assessment-scenario.js
  api/src/certification/shared/infrastructure/repositories/complementary-certification-repository.js
  api/src/shared/infrastructure/repositories/challenge-repository.js
  api/tests/certification/complementary-certification/integration/infrastucture/repositories/complementary-certification-repository_test.js
  api/tests/certification/flash-certification/integration/application/scenario-simulator-controller_test.js
  api/tests/certification/flash-certification/unit/domain/usecases/simulate-flash-assessment-scenario_test.js
  api/tests/shared/integration/infrastructure/repositories/challenge-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12367 [FEATURE] Afficher l'analyse des resultats par competence. (PIX-17675)
  orga/app/components/analysis/analysis-per-competence.gjs
  orga/app/components/analysis/analysis-per-tube-or-competence.gjs
  orga/app/components/analysis/analysis-per-tube.gjs
  orga/app/components/analysis/analysis-per-tubes-and-competences.gjs
  orga/app/components/analysis/analysis-per-tubes-and-competences.scss
  orga/app/components/statistics/cover-rate-gauge.gjs
  orga/app/styles/app.scss
  orga/app/styles/pages/authenticated/campaigns/campaign/analysis.scss
  orga/app/templates/authenticated/campaigns/campaign/analysis.gjs
  orga/tests/acceptance/campaign-analysis-test.js
  orga/tests/integration/components/analysis/analysis-per-competence_test.gjs
  orga/tests/integration/components/analysis/analysis-per-tube_test.gjs
  orga/tests/integration/components/analysis/analysis-per-tubes-or-competence_test.gjs
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12373 [FEATURE] Créer le nouvel élément Question A/B (QAB) dans l'API (PIX-17831)
  api/scripts/modulix/get-elements-csv.js
  api/src/devcomp/domain/models/element/qab/QAB.js
  api/src/devcomp/domain/models/element/qab/QABCard.js
  api/src/devcomp/infrastructure/datasources/learning-content/modules/bac-a-sable.json
  api/src/devcomp/infrastructure/factories/module-factory.js
  api/tests/devcomp/acceptance/scripts/get-elements-csv_test.js
  api/tests/devcomp/acceptance/scripts/test-module.json
  api/tests/devcomp/unit/domain/models/element/qab/QABCard_test.js
  api/tests/devcomp/unit/domain/models/element/qab/QAB_test.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/element/qab-schema.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/module-schema.js
  api/tests/devcomp/unit/infrastructure/factories/module-factory_test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12377 [TECH] Exposer la doc de l’API MaDDo sur /documentation/maddo
  api/server.maddo.js
  api/src/shared/swaggers.js
  api/tests/shared/acceptance/application/swaggers_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, :bellhop_bell: ping-jp, team-maddo

#12369 [TECH] Nettoyage de dépendances et packages.json de PixAdmin
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12374 [FEATURE] Communication entre Pix App et l’embed pix-llm (PIX-17788)
  api/src/devcomp/infrastructure/datasources/learning-content/modules/test-iframe-llm.json
  mon-pix/app/components/module/component/element.gjs
  mon-pix/app/components/module/element/embed.gjs
  mon-pix/app/components/module/grain/grain.gjs
  mon-pix/app/services/embed-api-proxy.js
  mon-pix/tests/integration/components/module/embed_test.gjs
  mon-pix/tests/unit/services/embed-api-proxy-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu, team-devcomp

#12372 [TECH] Correction test flaky certif (PIX-17996).
  certif/tests/acceptance/session-details-certification-candidates-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#12348 [BUGFIX] Corriger le champ "Adresse email" du formulaire de sortie du sco (PIX-17516)
  mon-pix/app/components/account-recovery/update-sco-record-form.gjs
  mon-pix/app/styles/pages/_account-recovery.scss
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12381 [TECH] Flaky sur le repo campaign participation
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/campaign-participation-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-prescription, cross-team

#12382 [FEATURE] Supprimer les stepsLabels et avoir toutes les jauges sur 8 niveaux (PIX-18033)
  orga/app/components/analysis/global-positioning.gjs
  orga/app/components/statistics/cover-rate-gauge.gjs
  orga/tests/integration/components/analysis/global-positioning_test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12253 [TECH] Passer le feature toggle du bouton de vocalisation au nouveau système
  api/config/feature-toggles-config.js
  api/sample.env
  api/src/shared/config.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, feature-toggle

#12383 [TECH] E2E flakies: s'assurer que le serveur X11 est démarré sur la CI
  .circleci/config.yml
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12370 [BUGFIX] Récompense de quête non partagée avec l'organisation (PIX-17944)
  api/db/seeds/data/team-prescription/build-quests.js
  api/src/prescription/campaign-participation/application/learner-participation-controller.js
  api/src/profile/application/profile-controller.js
  api/src/profile/application/profile-route.js
  api/src/shared/application/assessments/assessment-controller.js
  api/tests/prescription/campaign-participation/unit/application/learner-participation-controller_test.js
  api/tests/profile/acceptance/application/share-profile-reward-route_test.js
  api/tests/profile/unit/application/profile-controller_test.js
  mon-pix/app/adapters/campaign-participation-result.js
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-hero/index.gjs
  mon-pix/app/components/campaigns/assessment/results/evaluation-results-tabs/trainings.gjs
  mon-pix/app/services/campaign-participation-result.js
  mon-pix/tests/integration/components/campaigns/assessment/results/evaluation-results-tabs-test.js
  mon-pix/tests/integration/components/campaigns/assessment/results/hero/evaluation-results-hero-test.js
  mon-pix/tests/integration/components/campaigns/assessment/results/tabs/trainings-test.js
  mon-pix/tests/integration/components/routes/campaigns/assessment/evaluation-results-test.js
  mon-pix/tests/unit/services/campaign-participation-result-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, team-noa(h)

#12384 [FEATURE] Afficher CLEA dans le certificat V3 sur Pix App (PIX-17892).
  api/src/certification/results/domain/models/v3/Certificate.js
  api/src/certification/results/infrastructure/repositories/certificate-repository.js
  api/src/certification/results/infrastructure/serializers/certificate-serializer.js
  api/tests/certification/results/acceptance/application/certificate-route_test.js
  api/tests/certification/results/integration/infrastructure/repositories/certificate-repository_test.js
  api/tests/certification/results/unit/infrastructure/serializers/certificate-serializer_test.js
  api/tests/tooling/domain-builder/factory/certification/results/build-v3-certification-attestation.js
  mon-pix/app/components/certifications/candidate-certificate/v3-certificate.gjs
  mon-pix/app/components/certifications/certificate-information/clea-certification.gjs
  mon-pix/app/components/certifications/certificate-information/competences-details.gjs
  mon-pix/app/components/certifications/list/item.gjs
  mon-pix/app/components/certifications/shareable-certificate/v3-certificate.gjs
  mon-pix/app/models/certification.js
  mon-pix/app/styles/components/certifications/candidate-certificate/_v3-certificate.scss
  mon-pix/app/styles/components/certifications/certificate-information/_complementary-information-details.scss
  mon-pix/tests/integration/components/certifications/candidate-certificate/v3-certificate-test.gjs
  mon-pix/tests/integration/components/certifications/certificate-information/competences-details-test.gjs
  mon-pix/tests/integration/components/certifications/list/item-test.gjs
  mon-pix/tests/integration/components/certifications/shareable-certificate/v3-certificate-test.gjs
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: :rocket: Ready to Merge, Func Review OK, team-certif

#12385 [FEATURE] Anonymiser les données d'un participant à la suppression de celui-ci (PIX-17488).
  api/db/database-builder/factory/build-organization-learner.js
  api/src/prescription/learner-management/domain/models/OrganizationLearner.js
  api/src/prescription/learner-management/domain/usecases/delete-organization-learners.js
  api/src/prescription/learner-management/infrastructure/repositories/organization-learner-repository.js
  api/tests/prescription/learner-management/integration/domain/usecases/delete-organization-learners_test.js
  api/tests/prescription/learner-management/integration/infrastructure/repositories/organization-learner-repository_test.js
  api/tests/prescription/learner-management/unit/domain/models/OrganizationLearner_test.js
  api/tests/tooling/domain-builder/factory/build-organization-learner.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12407 [TECH] Augmenter le timeout sur des tests de generation PDF
  api/tests/certification/results/integration/infrastructure/utils/pdf/get-certificates-pdf-buffer_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12400 [FEATURE] Permettre de créer un référentiel cadre (PIX-18046).
  api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-repository.js
  api/src/certification/configuration/application/complementary-certification-controller.js
  api/src/certification/configuration/application/complementary-certification-route.js
  api/src/certification/configuration/domain/usecases/create-consolidated-framework.js
  api/src/certification/configuration/domain/usecases/index.js
  api/src/certification/configuration/infrastructure/repositories/consolidated-framework-repository.js
  api/tests/certification/complementary-certification/acceptance/application/complementary-certification-controller_test.js
  api/tests/certification/configuration/acceptance/application/complementary-certification-route_test.js
  api/tests/certification/configuration/integration/infrastructure/repositories/consolidated-framework-repository_test.js
  api/tests/certification/configuration/unit/application/complementary-certification-route_test.js
  api/tests/certification/configuration/unit/domain/usecases/create-consolidated-framework_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif
