Repository 1024pix/pix, pull requests merged in 2025-06, with the labels that each got.

#12302 [TECH] :truck: Déplace la route et le cas d'utilisation `ScoOrganizationLearnerAccountRecovery`
  api/lib/application/sco-organization-learners/index.js
  api/lib/application/sco-organization-learners/sco-organization-learner-controller.js
  api/src/identity-access-management/application/organization-learner-account-recovery/organization-learner-account-recovery.controller.js
  api/src/identity-access-management/application/organization-learner-account-recovery/organization-learner-account-recovery.route.js
  api/src/identity-access-management/application/routes.js
  api/src/identity-access-management/domain/usecases/check-sco-account-recovery.usecase.js
  api/src/identity-access-management/domain/usecases/index.js
  api/tests/identity-access-management/unit/domain/usecases/check-sco-account-recovery_test.js
  api/tests/integration/application/sco-organization-learners/index_test.js
  api/tests/unit/application/sco-organization-learners/sco-organization-learner-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, Bounded-context-migration

#12378 [TECH] :truck: Retire l'utilisation du mot `attestation` du cas d'utilisation de récupération d'un certificat (PIX-18024)
  api/src/certification/results/application/certificate-controller.js
  api/src/certification/results/domain/usecases/get-certificate.js
  api/src/certification/results/domain/usecases/get-certification-attestations-for-session.js
  api/src/certification/results/infrastructure/repositories/certificate-repository.js
  api/src/certification/results/scripts/generate-certification-attestations-by-session-ids.js
  api/tests/certification/results/integration/infrastructure/repositories/certificate-repository_test.js
  api/tests/certification/results/unit/application/certificate-controller_test.js
  api/tests/certification/results/unit/domain/usecases/get-certificate_test.js
  api/tests/certification/results/unit/domain/usecases/get-certificates-for-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#12406 [FEATURE] Modifier le texte de la modale de suppression de participation dans PixAdmin (PIX-18058)
  admin/app/components/users/campaign-participations.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12404 [TECH] Remplacer certaines dependances de Pix Admin
  admin/app/adapters/organization.js
  admin/app/adapters/session.js
  admin/app/components/organizations/information-section.gjs
  admin/app/components/sessions/session-informations.gjs
  admin/package-lock.json
  admin/package.json
  admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.gjs
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12418 [TECH] Bump des dépendances de linters et formatters Pix Admin
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12380 [TECH] :truck: Renommer le cas d'utilisation `get-certification-attestations-for-session` pour enlever `attestations` (PIX-18028)
  api/src/certification/results/application/certificate-controller.js
  api/src/certification/results/domain/usecases/get-certificates-for-session.js
  api/tests/certification/results/unit/application/certificate-controller_test.js
  api/tests/certification/results/unit/domain/usecases/get-certificates-for-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12423 [TECH] Mise à jour de dépendances Pix Admin
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12403 [FEATURE] Détacher les assessments quand on supprime une participation (PIX-18047).
  api/db/database-builder/factory/build-assessment-from-participation.js
  api/src/prescription/campaign-participation/domain/usecases/delete-campaign-participation.js
  api/src/prescription/learner-management/domain/usecases/delete-organization-learners.js
  api/src/prescription/learner-management/domain/usecases/index.js
  api/src/shared/domain/models/Assessment.js
  api/src/shared/infrastructure/repositories/assessment-repository.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/delete-campaign-participation_test.js
  api/tests/prescription/learner-management/integration/domain/usecases/delete-organization-learners_test.js
  api/tests/shared/integration/infrastructure/repositories/assessment-repository_test.js
  api/tests/shared/unit/domain/models/Assessment_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12416 [FEATURE] Remplacer Matomo par Plausible (PIX-18037).
  mon-pix/app/routes/not-found.js
  orga/app/components/campaign/filter/participation-filters.gjs
  orga/app/components/campaign/header/tabs.gjs
  orga/app/controllers/authenticated/attestations.js
  orga/app/metrics-adapters/plausible-adapter.js
  orga/app/routes/application.js
  orga/app/routes/authenticated/campaigns/index.js
  orga/app/routes/authenticated/campaigns/list/index.js
  orga/app/routes/authenticated/campaigns/participant-assessment/index.js
  orga/app/routes/authenticated/index.js
  orga/app/routes/authenticated/missions/mission/index.js
  orga/app/routes/authenticated/team/list/index.js
  orga/app/routes/not-found.js
  orga/app/services/pix-metrics.js
  orga/config/environment.js
  orga/package-lock.json
  orga/package.json
  orga/tests/acceptance/application-test.js
  orga/tests/integration/components/banner/sco-communication-test.gjs
  orga/tests/integration/components/campaign/filter/participation-filters-test.gjs
  orga/tests/integration/components/campaign/header/tabs-test.js
  orga/tests/unit/controllers/authenticated/attestations-test.js
  orga/tests/unit/metrics-adapters/plausible-adapter-test.js
  orga/tests/unit/services/pix-metrics-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12443 [TECH] :truck: Renomme le script de génération de certificats par id de session (pix-18092)
  api/src/certification/results/scripts/generate-certificates-by-session-ids.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#12459 [TECH] Mise à jour des dépendances PixAdmin (build and intl)
  admin/package-lock.json
  admin/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12452 [FEATURE] Permettre la création d'un `client-application` sans juridiction via le script dédié.
  api/scripts/identity-access-management/client-applications.js
  api/src/identity-access-management/infrastructure/repositories/client-application.repository.js
  api/tests/identity-access-management/integration/infrastructure/repositories/client-application.repository.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-maddo

#12419 [TECH] Supprimer la version de session dans le usecase retrieve-last-or-create-certification-course (PIX-18075).
  api/src/certification/evaluation/domain/usecases/retrieve-last-or-create-certification-course.js
  api/tests/certification/evaluation/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/certification/evaluation/acceptance/application/certification-courses/index_test.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#12396 [FEATURE] Arrêter d'utiliser le campaignCode sur les routes liées au model ScoOrganizationLearner de mon-pix (Pix-18050)
  api/lib/application/sco-organization-learners/index.js
  api/lib/application/sco-organization-learners/sco-organization-learner-controller.js
  api/lib/domain/usecases/generate-username.js
  api/src/prescription/learner-management/application/organization-learners-controller.js
  api/src/prescription/learner-management/application/organization-learners-route.js
  api/src/prescription/learner-management/application/sco-organization-management-controller.js
  api/src/prescription/learner-management/application/sco-organization-management-route.js
  api/src/prescription/learner-management/domain/usecases/reconcile-sco-organization-learner-automatically.js
  api/src/prescription/learner-management/domain/usecases/reconcile-sco-organization-learner-manually.js
  api/tests/acceptance/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/integration/application/sco-organization-learners/index_test.js
  api/tests/prescription/learner-management/acceptance/application/organization-learners-route_test.js
  api/tests/prescription/learner-management/acceptance/application/sco-organization-management-route_test.js
  api/tests/prescription/learner-management/integration/application/organization-learners-route_test.js
  api/tests/prescription/learner-management/integration/application/sco-organization-management-route_test.js
  api/tests/prescription/learner-management/unit/domain/usecases/reconcile-sco-organization-learner-automatically_test.js
  api/tests/prescription/learner-management/unit/domain/usecases/reconcile-sco-organization-learner-manually_test.js
  api/tests/unit/domain/usecases/generate-username_test.js
  high-level-tests/e2e/cypress/downloads/downloads.html
  mon-pix/app/components/routes/campaigns/invited/associate-sco-student-form.gjs
  mon-pix/app/components/routes/login-or-register.gjs
  mon-pix/app/components/routes/register-form.gjs
  mon-pix/app/controllers/campaigns/join/student-sco.js
  mon-pix/app/models/sco-organization-learner.js
  mon-pix/app/routes/campaigns/access.js
  mon-pix/app/routes/campaigns/invited/student-sco.js
  mon-pix/app/templates/campaigns/invited/student-sco.gjs
  mon-pix/app/templates/campaigns/join/student-sco.gjs
  mon-pix/mirage/routes/sco-organization-learners/index.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/unit/components/routes/campaigns/invited/associate-sco-student-form-test.js
  mon-pix/tests/unit/controllers/campaigns/join/student-sco-test.js
Labels: :rocket: Ready to Merge, :dango: Combinix

#12340 [FEATURE] Utiliser le webcomponent `message-conversation` à la place de la vidéo (PIX-17921)
  api/src/devcomp/infrastructure/datasources/learning-content/modules/bien-ecrire-son-adresse-mail.json
  mon-pix/app/components/module/element/_custom-element.scss
  mon-pix/app/styles/app.scss
Labels: :rocket: Ready to Merge, team-contenu, team-devcomp

#12425 [BUGFIX] Ajustements graphiques et textuels pour la sortie du sco (PIX-18044)
  mon-pix/app/styles/components/account-recovery/_confirmation-step.scss
  mon-pix/app/styles/pages/_account-recovery.scss
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12441 [FEATURE] Revoir le comportement de la barre de progression du module (PIX-18090)
  mon-pix/app/components/module/passage.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12434 [TECH] Rendre la date de finalisation de session dépendante de la BDD (PIX-17939).
  api/src/certification/session-management/domain/usecases/finalize-session.js
  api/src/certification/session-management/infrastructure/repositories/session-repository.js
  api/tests/certification/session-management/integration/infrastructure/repositories/session-repository_test.js
  api/tests/certification/session-management/unit/domain/usecases/finalize-session_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#12429 [FEATURE] Edition du fond pour le QCU déclaratif (PIX-17906)
  mon-pix/app/components/module/component/_proposal-button.scss
  mon-pix/app/components/module/element/_qcu-declarative.scss
Labels: :rocket: Ready to Merge, team-devcomp

#12439 [TECH] Ne plus avoir de code spécifique v3 dans le usecase verify-candidate-identity (PIX-18091).
  api/src/certification/enrolment/domain/usecases/verify-candidate-identity.js
  api/tests/certification/enrolment/unit/domain/usecases/verify-candidate-identity_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, no-review-app

#12440 [TECH] :truck: Déplace la route `batch usename password generate` vers `src/prescription/organization-learner` (Pix-17851)
  api/lib/application/sco-organization-learners/index.js
  api/lib/application/sco-organization-learners/sco-organization-learner-controller.js
  api/src/prescription/organization-learner/application/sco-organization-learner-controller.js
  api/src/prescription/organization-learner/application/sco-organization-learner-route.js
  api/src/prescription/organization-learner/domain/usecases/generate-organization-learners-username-and-temporary-password.js
  api/src/prescription/organization-learner/domain/usecases/generate-reset-organization-learners-password-cvs-content.js
  api/src/prescription/organization-learner/domain/usecases/index.js
  api/tests/integration/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/prescription/organization-learner/integration/application/sco-organization-learner-controller_test.js
  api/tests/prescription/organization-learner/integration/domain/usecases/generate-organization-learners-username-and-temporary-password_test.js
  api/tests/prescription/organization-learner/unit/domain/usecases/generate-reset-organization-learners-password-csv_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription, Bounded-context-migration

#12476 [FEATURE] Modulix - remplacer le questionnaire en fin de module (PIX-18061)
  mon-pix/app/components/module/instruction/recap.gjs
  mon-pix/tests/acceptance/module/navigate-into-the-module-recap_test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12467 [TECH] :wastebasket: nettoyage des fichiers index du répertoire `lib/`
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/index.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, Bounded-context-migration

#12464 [FEATURE] Ajouter un feature toggle pour conserver ses pix après avoir participé à une campagne et s'être créé un compte (PIX-18015)
  api/config/feature-toggles-config.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  mon-pix/app/models/feature-toggle.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12461 [BUGFIX] Utiliser les knowledge element snapshot pour l'affichage des résultats individuel d'un prescrit dans PixOrga (PIX-17964).
  api/db/seeds/data/team-prescription/build-organization-learners-with-multiple-participations.js
  api/src/prescription/campaign-participation/infrastructure/repositories/campaign-assessment-participation-result-repository.js
  api/tests/prescription/campaign-participation/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12430 [TECH] Rendre le processus de connexion depuis un mediacentre agnostique des campagnes (PIX-18087)
  api/src/prescription/organization-learner/application/sco-organization-learner-controller.js
  api/src/prescription/organization-learner/application/sco-organization-learner-route.js
  api/src/prescription/organization-learner/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user.js
  api/tests/prescription/organization-learner/acceptance/application/sco-organization-learner-route_test.js
  api/tests/prescription/organization-learner/integration/application/sco-organization-learner-route_test.js
  api/tests/prescription/organization-learner/integration/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user_test.js
  api/tests/prescription/organization-learner/unit/application/sco-organization-learner-controller_test.js
  api/tests/prescription/organization-learner/unit/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user_test.js
  mon-pix/app/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form.gjs
  mon-pix/app/models/external-user.js
  mon-pix/app/templates/campaigns/join/sco-mediacentre.gjs
  mon-pix/tests/unit/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, :dango: Combinix

#12448 [TECH] Supprimer le model API SessionVersion (PIX-18095).
  api/db/seeds/data/common/tooling/session-tooling.js
  api/scripts/certification/fix-competence-marks.js
  api/src/certification/enrolment/domain/models/SessionEnrolment.js
  api/src/certification/enrolment/domain/usecases/create-session.js
  api/src/certification/enrolment/domain/usecases/verify-candidate-subscriptions.js
  api/src/certification/results/infrastructure/repositories/certificate-repository.js
  api/src/certification/session-management/domain/models/JurySession.js
  api/src/certification/session-management/domain/models/SessionManagement.js
  api/src/certification/shared/domain/models/SessionVersion.js
  api/src/certification/shared/domain/validators/session-validator.js
  api/tests/certification/enrolment/acceptance/application/session-route_test.js
  api/tests/certification/enrolment/unit/domain/usecases/create-session_test.js
  api/tests/certification/enrolment/unit/domain/usecases/verify-candidate-subscriptions_test.js
  api/tests/certification/evaluation/acceptance/application/certificate-route_test.js
  api/tests/certification/evaluation/acceptance/application/certification-courses/certification-course-controller_test.js
  api/tests/certification/evaluation/unit/domain/usecases/get-next-challenge_test.js
  api/tests/certification/results/acceptance/application/certificate-route_test.js
  api/tests/certification/results/integration/infrastructure/repositories/certificate-repository_test.js
  api/tests/certification/results/integration/infrastructure/utils/pdf/generate-v2-pdf-certificate_test.js
  api/tests/certification/results/unit/application/certificate-controller_test.js
  api/tests/certification/results/unit/domain/models/CertificationAttestation_test.js
  api/tests/certification/results/unit/domain/models/PrivateCertificate_test.js
  api/tests/certification/results/unit/infrastructure/serializers/certificate-serializer_test.js
  api/tests/certification/results/unit/infrastructure/serializers/private-certificate-serializer_test.js
  api/tests/certification/session-management/acceptance/application/cancellation-route_test.js
  api/tests/certification/session-management/acceptance/application/certification-course-route_test.js
  api/tests/certification/session-management/acceptance/application/finalize-route_test.js
  api/tests/certification/session-management/integration/infrastructure/repositories/session-for-supervising-repository_test.js
  api/tests/shared/acceptance/application/assessments/assessment-controller-get-next-challenge-for-certification_test.js
  api/tests/tooling/domain-builder/factory/build-certification-attestation.js
  api/tests/tooling/domain-builder/factory/build-jury-certification.js
  api/tests/tooling/domain-builder/factory/build-private-certificate.js
  api/tests/tooling/domain-builder/factory/certification/enrolment/build-session.js
  api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, no-review-app

#12388 [FEATURE] WIP module IAG fonctionnement novice tmp-ia-fonctionnement-debut
  api/src/devcomp/infrastructure/datasources/learning-content/modules/tmp-ia-fonctionnement-debut.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12297 [FEATURE] WIP Création d'un module sur les Deepfakes
  api/src/devcomp/infrastructure/datasources/learning-content/modules/ia-deepfakes.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12486 [FEATURE] Dernières corrections modules tmp-ia-fonctionnement-debut.json
  api/src/devcomp/infrastructure/datasources/learning-content/modules/tmp-ia-fonctionnement-debut.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12394 [FEATURE] WIP Create prompt-intermediaire.json
  api/src/devcomp/infrastructure/datasources/learning-content/modules/prompt-intermediaire.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12362 [FEATURE] WIP module mon premier prompt
  api/src/devcomp/infrastructure/datasources/learning-content/modules/ia-premier-prompt.json
Labels: :rocket: Ready to Merge, :bellhop_bell: ping-jp, contribution-modulix

#12472 [FEATURE] Ne plus parler de session de version dans admin (PIX-18109).
  admin/tests/acceptance/sessions-list-test.js
  admin/translations/en.json
  admin/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12495 [TECH] Supprimer la méthode lock du RedisClient
  api/package-lock.json
  api/package.json
  api/src/shared/infrastructure/utils/RedisClient.js
  api/tests/shared/integration/infrastructure/utils/RedisClient_test.js
Labels: :rocket: Ready to Merge

#12493 [TECH] Renomme une chaine de caractère dans un test
  api/tests/certification/configuration/unit/application/complementary-certification-route_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, no-review-app

#12431 [FEATURE] Couper le lien entre user-recommended-training et la participation lors de la suppression de celle-ci (PIX-18049)
  api/db/database-builder/factory/build-user-recommended-training.js
  api/db/migrations/20221017085933_create-user-recommended-trainings.js
  api/db/migrations/20241119103307_devcomp-user-recommended-trainings-remove-nullable-constraint-on-campaign-participation-id.js
  api/scripts/prod/delete-and-anonymise-organization-learners.js
  api/scripts/prod/delete-organization-learners-from-organization.js
  api/src/devcomp/infrastructure/repositories/training-repository.js
  api/src/devcomp/infrastructure/repositories/user-recommended-training-repository.js
  api/src/prescription/campaign-participation/domain/usecases/delete-campaign-participation.js
  api/src/prescription/campaign-participation/domain/usecases/index.js
  api/src/prescription/campaign/domain/usecases/delete-campaigns.js
  api/src/prescription/campaign/domain/usecases/index.js
  api/src/prescription/learner-management/domain/usecases/delete-organization-learners.js
  api/src/prescription/learner-management/domain/usecases/index.js
  api/tests/devcomp/integration/infrastructure/repositories/user-recommended-training-repository_test.js
  api/tests/evaluation/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/integration/scripts/prod/delete-and-anonymise-organization-learners_test.js
  api/tests/integration/scripts/prod/delete-organization-learners-from-organization_test.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/delete-campaign-participation_test.js
  api/tests/prescription/campaign/integration/domain/usecases/delete-campaigns_test.js
  api/tests/prescription/learner-management/integration/domain/usecases/delete-organization-learners_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12462 [TECH] Déplace le flag hasUserSeenJoinPage dans un storage spécifique à la logique d'accès (PIX-18100)
  mon-pix/app/components/routes/campaigns/invited/associate-sco-student-form.gjs
  mon-pix/app/components/routes/campaigns/join-sco-information-modal.gjs
  mon-pix/app/components/routes/campaigns/join/associate-sco-student-with-mediacentre-form.gjs
  mon-pix/app/controllers/campaigns/invited/student-sco.js
  mon-pix/app/controllers/campaigns/join/sco-mediacentre.js
  mon-pix/app/routes/campaigns/access.js
  mon-pix/app/routes/campaigns/entry-point.js
  mon-pix/app/routes/campaigns/join/student-sco.js
  mon-pix/app/routes/logout.js
  mon-pix/app/services/access-storage.js
  mon-pix/app/services/base-storage.js
  mon-pix/app/services/campaign-storage.js
  mon-pix/app/templates/campaigns/invited/student-sco.gjs
  mon-pix/app/templates/campaigns/join/sco-mediacentre.gjs
  mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/unit/components/routes/campaigns/join-sco-information-modal-test.js
  mon-pix/tests/unit/routes/campaigns/access-test.js
  mon-pix/tests/unit/routes/campaigns/entry-point-test.js
  mon-pix/tests/unit/services/access-storage-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, :dango: Combinix

#12505 [TECH] Passer les feature toggles de metric à des variables d'environnement classique
  api/server.js
  api/server.maddo.js
  api/src/monitoring/infrastructure/metrics.js
  api/src/shared/config.js
  api/src/shared/infrastructure/plugins/pino.js
  api/tests/monitoring/integration/infrastructure/metrics_test.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
  api/tests/shared/integration/infrastructure/jobs/JobQueue_test.js
  api/tests/unit/worker_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#12501 [FEATURE] Enlever un mot d'une description (PIX-18168)
  orga/translations/en.json
  orga/translations/fr.json
  orga/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12504 [FEATURE] Détacher les campaignParticipation supprimés des assessments et des badges non certifiants (PIX-18164).
  api/src/prescription/campaign/domain/usecases/delete-campaigns.js
  api/src/prescription/campaign/domain/usecases/index.js
  api/tests/prescription/campaign/integration/domain/usecases/delete-campaigns_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12510 [TECH] Ajouter la permission pour le contenu dans le workflow qui ferme les PRs inactive depuis un mois
  .github/workflows/check-old-pull-requests.yml
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app

#12484 [TECH] Supprimer le feature-toggle isV3CertificationAttestationEnabled (PIX-17340).
  api/config/feature-toggles-config.js
  api/src/certification/results/infrastructure/repositories/certificate-repository.js
  api/tests/certification/evaluation/acceptance/application/certificate-route_test.js
  api/tests/certification/results/integration/infrastructure/repositories/certificate-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif

#12421 [TECH] Enlever les sources junior du container RA front
  .slugignore
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, 🎒👧🏽👦🏾 PIX JUNIOR

#12526 Revert "[BUMP] Update dependency @1024pix/epreuves-components to ^0.3.0 (mon-pix)"
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: :rocket: Ready to Merge, team-devcomp

#12498 [TECH] :hammer: Création d'un référentiel cadre à partir d'un profil cible (PIX-18131)
  api/scripts/certification/target-profile-to-calibrated-framework.js
  api/tests/integration/scripts/certification/target-profile-to-calibrated-framework_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12525 [FEATURE] Créer routes pour l'intégration du LLM dans le contexte de l'évaluation (PIX-18171)
  api/src/evaluation/application/assessments/assessment-controller.js
  api/src/evaluation/application/assessments/assessment-routes.js
  api/src/evaluation/domain/usecases/index.js
  api/src/evaluation/domain/usecases/prompt-to-llm-chat.js
  api/src/evaluation/domain/usecases/start-embed-llm-chat.js
  api/tests/evaluation/acceptance/application/assessments/assessment-controller-complete-assessment_test.js
  api/tests/evaluation/unit/domain/usecases/prompt-to-llm-chat_test.js
  api/tests/evaluation/unit/domain/usecases/start-embed-llm-chat_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-contenu

#11800 [TECH] Correction des deprecations EmberJs sur Pix Admin
  admin/app/components/badges/capped-tubes-criterion.gjs
  admin/app/components/certification-centers/creation-form.gjs
  admin/app/components/certification-centers/information-edit.gjs
  admin/app/components/certification-centers/information-view.gjs
  admin/app/components/certification-centers/invitations.gjs
  admin/app/components/certifications/certified-profile.gjs
  admin/app/components/common/tubes-selection.gjs
  admin/app/components/common/tubes-selection/thematic.gjs
  admin/app/components/complementary-certifications/attach-badges/index.gjs
  admin/app/components/complementary-certifications/list.gjs
  admin/app/components/organizations/all-tags.gjs
  admin/app/components/organizations/information-section-view.gjs
  admin/app/components/organizations/invitations.gjs
  admin/app/components/sessions/certifications/list.gjs
  admin/app/components/target-profiles/badge-form/capped-tubes-criterion.gjs
  admin/app/components/target-profiles/badge-form/criteria.gjs
  admin/app/components/target-profiles/stages.gjs
  admin/app/components/trainings/trigger/details.gjs
  admin/app/components/users/certification-centers/memberships.gjs
  admin/app/components/users/user-detail-personal-information/authentication-method.gjs
  admin/app/components/users/user-organization-memberships.gjs
  admin/app/components/users/user-overview.gjs
  admin/app/controllers/authenticated/certification-centers/new.js
  admin/app/controllers/authenticated/certifications/certification/informations.js
  admin/app/controllers/authenticated/complementary-certifications/complementary-certification/attach-target-profile/new.js
  admin/app/controllers/authenticated/complementary-certifications/complementary-certification/attach-target-profile/update.js
  admin/app/controllers/authenticated/organizations/get/team.js
  admin/app/controllers/authenticated/target-profiles/target-profile/details.js
  admin/app/controllers/authenticated/users/get/authentication-methods.js
  admin/app/models/area.js
  admin/app/models/competence.js
  admin/app/models/organization.js
  admin/app/models/stage-collection.js
  admin/app/models/training.js
  admin/app/routes/authenticated/certification-centers/new.js
  admin/app/routes/authenticated/complementary-certifications/complementary-certification/attach-target-profile/new.js
  admin/app/routes/authenticated/complementary-certifications/complementary-certification/attach-target-profile/update.js
  admin/app/services/oidc-identity-providers.js
  admin/app/templates/authenticated/certification-centers/new.hbs
  admin/config/environment.js
  admin/tests/integration/components/certification-centers/creation-form-test.gjs
  admin/tests/integration/components/certification-centers/information-view-test.gjs
  admin/tests/integration/components/routes/authenticated/target-profiles/target-profile/insights-test.gjs
  admin/tests/unit/components/certification-centers/information-edit-test.js
  admin/tests/unit/components/users/certification-centers/memberships-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12509 [TECH] :truck: Déplace la route `Campaign-participation` vers `src/devcomp/`
  api/lib/routes.js
  api/src/devcomp/application/campaign-participations/campaign-participation-controller.js
  api/src/devcomp/application/campaign-participations/campaign-participation-route.js
  api/src/devcomp/routes.js
  api/tests/devcomp/acceptance/application/campaign-participations/campaign-participation-controller_test.js
  api/tests/unit/application/campaign-participations/campaign-participation-controller_test.js
  api/tests/unit/application/campaign-participations/index_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-devcomp, Bounded-context-migration

#12507 [FEATURE] Création d'un script pour calculer la dette liée aux médias Modulix (PIX-18177)
  api/scripts/modulix/get-modules-assets-debt.js
Labels: :rocket: Ready to Merge, team-devcomp

#12530 [FEATURE] Créer la page Référentiel cadre sur Pix Admin (PIX-18186).
  admin/app/components/complementary-certifications/header.gjs
  admin/app/components/complementary-certifications/item/header.gjs
  admin/app/components/complementary-certifications/target-profiles/information.gjs
  admin/app/router.js
  admin/app/routes/authenticated/complementary-certifications/item.js
  admin/app/styles/app.scss
  admin/app/styles/components/complementary-certifications/details.scss
  admin/app/styles/components/complementary-certifications/header.scss
  admin/app/styles/components/complementary-certifications/item.scss
  admin/app/templates/authenticated/complementary-certifications/complementary-certification.hbs
  admin/app/templates/authenticated/complementary-certifications/item.hbs
  admin/app/templates/authenticated/complementary-certifications/item/framework.hbs
  admin/app/templates/authenticated/complementary-certifications/item/target-profile.hbs
  admin/tests/acceptance/authenticated/complementary-certifications/item-test.js
  admin/tests/integration/components/complementary-certifications/header-test.gjs
  admin/tests/integration/components/complementary-certifications/target-profiles/information-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
Labels: :rocket: Ready to Merge, team-certif

#12535 [FEATURE] Ajouter l'élément Custom message-conversation à la validation Joi (PIX-18220)
  api/src/devcomp/infrastructure/datasources/conversion/joi-to-json-schema.js
  api/src/devcomp/infrastructure/datasources/learning-content/samples/elements/custom/message-conversation.sample.js
  api/tests/devcomp/unit/infrastructure/datasources/conversion/joi-to-json-schema_test.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/element/custom-element-schema.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/module-validation_test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12356 [FEATURE] Pouvoir vérifier depuis Pix Admin si un utilisateur est en capacité de valider une quête (PIX-18008)
  admin/app/components/administration/common/index.gjs
  admin/app/components/administration/common/user-quest-checker.gjs
  admin/app/styles/components/administration/index.scss
  admin/app/styles/components/administration/user-quest-checker.scss
  admin/tests/integration/components/administration/common/user-quest-checker-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
  api/src/quest/application/index.js
  api/src/quest/application/quest-controller.js
  api/src/quest/domain/usecases/check-user-quest-success.js
  api/src/quest/infrastructure/repositories/quest-repository.js
  api/src/shared/domain/types/identifiers-type.js
  api/tests/quest/integration/domain/usecases/check-user-quest-success_test.js
  api/tests/quest/integration/infrastructure/repositories/quest-repository_test.js
  api/tests/quest/unit/application/index_test.js
  api/tests/quest/unit/application/quest-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12549 FEATURE : ajout vidéos définitives PPN1 ENT
  api/src/devcomp/infrastructure/datasources/learning-content/modules/decouverte-de-l-ent.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12513 [FEATURE] Faire disparaître les élements du toaster automatiquement lors du changement de page sur Pix Admin (PIX-18169).
  admin/app/router.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/insights-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12554 [FEATURE] Support des web-components Vue >=3.5.15 (PIX-18219)
  junior/app/components/challenge/content/embedded-web-component.gjs
  junior/package-lock.json
  junior/package.json
  mon-pix/app/components/module/element/custom-element.gjs
  mon-pix/package-lock.json
  mon-pix/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu, 🎒👧🏽👦🏾 PIX JUNIOR, team-devcomp

#12387 [FEATURE] Nouveaux messages d'erreur lors d'une tentative de connexion (PIX-17949)
  api/src/identity-access-management/application/http-error-mapper-configuration.js
  api/src/identity-access-management/domain/errors.js
  api/src/identity-access-management/domain/models/UserLogin.js
  api/src/identity-access-management/domain/services/pix-authentication-service.js
  api/src/identity-access-management/domain/usecases/authenticate-for-saml.usecase.js
  api/src/identity-access-management/domain/usecases/authenticate-user.js
  api/src/identity-access-management/domain/usecases/find-user-for-oidc-reconciliation.usecase.js
  api/src/shared/application/error-manager.js
  api/src/shared/application/http-errors.js
  api/src/shared/application/usecases/checkIfUserIsBlocked.js
  api/src/shared/domain/errors.js
  api/tests/identity-access-management/integration/domain/services/pix-authentication-service.test.js
  api/tests/identity-access-management/unit/application/http-error-mapper-configuration_test.js
  api/tests/identity-access-management/unit/domain/services/pix-authentication-service.test.js
  api/tests/shared/integration/domain/services/.gitkeep
  api/tests/shared/integration/domain/usecases/.gitkeep
  api/tests/shared/integration/domain/usecases/check-if-user-is-blocked.test.js
  api/tests/unit/domain/models/UserLogin_test.js
  mon-pix/app/components/authentication/login-form.gjs
  mon-pix/app/components/authentication/login-or-register-oidc.gjs
  mon-pix/app/components/authentication/oidc-reconciliation.gjs
  mon-pix/app/components/authentication/signup-form/index.gjs
  mon-pix/app/components/routes/login-form.gjs
  mon-pix/app/services/error-messages.js
  mon-pix/config/environment.js
  mon-pix/tests/acceptance/start-campaigns-workflow-test.js
  mon-pix/tests/integration/components/authentication/login-form-test.gjs
  mon-pix/tests/integration/components/authentication/signup-form/index-test.gjs
  mon-pix/tests/integration/components/routes/login-form-test.js
  mon-pix/tests/unit/components/authentication/login-or-register-oidc-test.js
  mon-pix/tests/unit/components/authentication/oidc-reconciliation-test.js
  mon-pix/tests/unit/components/routes/login-form-test.js
  mon-pix/tests/unit/services/error-messages-test.js
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/fr.json
  mon-pix/translations/nl.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12570 [TECH] Supprimer l’utilisation du WebComponent cartes-a-retourner
  api/src/devcomp/infrastructure/datasources/learning-content/modules/bac-a-sable.json
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/element/custom-element-schema.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu, team-devcomp

#12541 [FEATURE] Remplir l'onglet profil cible dans la page des complémentaires sur Pix Admin (PIX-18187).
  admin/app/components/complementary-certifications/item/target-profile.gjs
  admin/app/components/complementary-certifications/target-profiles/information.gjs
  admin/app/templates/authenticated/complementary-certifications/item/target-profile.hbs
  admin/tests/integration/components/complementary-certifications/item/header-test.gjs
  admin/tests/integration/components/complementary-certifications/item/target-profile-test.gjs
Labels: :rocket: Ready to Merge, team-certif

#12529 [TECH] :truck: Déplace la route `generate username with temporary password` vers `src/prescription/` (pix-17853)
  api/lib/application/sco-organization-learners/index.js
  api/lib/application/sco-organization-learners/sco-organization-learner-controller.js
  api/src/prescription/organization-learner/application/sco-organization-learner-controller.js
  api/src/prescription/organization-learner/application/sco-organization-learner-route.js
  api/src/prescription/organization-learner/domain/usecases/generate-username-with-temporary-password.js
  api/tests/acceptance/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/integration/application/sco-organization-learners/index_test.js
  api/tests/integration/application/sco-organization-learners/sco-organization-learner-controller_test.js
  api/tests/prescription/organization-learner/acceptance/application/sco-organization-learner-route_test.js
  api/tests/prescription/organization-learner/integration/application/sco-organization-learner-controller_test.js
  api/tests/prescription/organization-learner/integration/application/sco-organization-learner-route_test.js
  api/tests/prescription/organization-learner/unit/domain/usecases/generate-username-with-temporary-password_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription, Bounded-context-migration

#12578 [BUGFIX] Corriger des clés de traduction du bouton "s'inscrire" en nl, es, en (PIX-18326)
  mon-pix/translations/en.json
  mon-pix/translations/es.json
  mon-pix/translations/nl.json
Labels: :rocket: Ready to Merge, team-acces

#12546 [FEATURE] Ajout du formulaire de création de référentiel cadre (PIX-18188).
  admin/app/adapters/certification-consolidated-framework.js
  admin/app/components/complementary-certifications/item/framework.gjs
  admin/app/components/complementary-certifications/item/framework/creation-form.gjs
  admin/app/models/certification-consolidated-framework.js
  admin/app/router.js
  admin/app/routes/authenticated/complementary-certifications/item/framework/new.js
  admin/app/styles/app.scss
  admin/app/styles/components/complementary-certifications/item/framework.scss
  admin/app/templates/authenticated/complementary-certifications/item.hbs
  admin/app/templates/authenticated/complementary-certifications/item/framework.hbs
  admin/app/templates/authenticated/complementary-certifications/item/framework/index.hbs
  admin/app/templates/authenticated/complementary-certifications/item/framework/new.hbs
  admin/tests/acceptance/authenticated/complementary-certifications/item-test.js
  admin/tests/integration/components/complementary-certifications/item/framework/creation-form-test.gjs
  admin/translations/en.json
  admin/translations/fr.json
  api/src/certification/complementary-certification/domain/models/ComplementaryCertificationForTargetProfileAttachment.js
  api/src/certification/complementary-certification/domain/models/ComplementaryCertificationTargetProfileHistory.js
  api/src/certification/complementary-certification/infrastructure/serializers/jsonapi/complementary-certification-serializer.js
  api/src/certification/configuration/application/complementary-certification-controller.js
  api/tests/certification/complementary-certification/integration/infrastucture/repositories/complementary-certification-for-target-profile-attachment-repository_test.js
  api/tests/certification/complementary-certification/unit/infrastructure/serializers/complementary-certification-serializer_test.js
  api/tests/certification/configuration/acceptance/application/complementary-certification-route_test.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-for-target-profile-attachment.js
  api/tests/tooling/domain-builder/factory/build-complementary-certification-target-profile-history-for-admin.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12583 [BUGFIX] Corriger le lien 123formbuilder de la page de récap (PIX-18328)
  mon-pix/app/components/module/instruction/recap.gjs
  mon-pix/tests/acceptance/module/navigate-into-the-module-recap_test.js
Labels: :rocket: Ready to Merge, team-devcomp

#12543 [TECH] Unification de la date de création des challenges d'un référentiel cadre (PIX-18284).
  api/src/certification/configuration/infrastructure/repositories/consolidated-framework-repository.js
  api/tests/certification/configuration/integration/infrastructure/repositories/consolidated-framework-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12580 [FEATURE] Ajouter l'animation des cartes vers la droite lorsque la réponse est incorrecte pour les QAB (PIX-18117)
  mon-pix/app/components/module/element/qab/_qab-card.scss
  mon-pix/app/components/module/element/qab/qab-card.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12548 [TECH] Simplification des seeds Certification (PIX-17640).
  api/db/seeds/data/common/tooling/index.js
  api/db/seeds/data/common/tooling/session-tooling.js
  api/db/seeds/data/team-certification/cases/simple-pro-certification.js
  api/db/seeds/data/team-certification/cases/simple-sco-managing-students-certification.js
  api/db/seeds/data/team-certification/constants.js
  api/db/seeds/data/team-certification/data-builder.js
  api/db/seeds/data/team-certification/setup-configuration.js
  api/db/seeds/data/team-certification/shared/common-certifiable-user.js
  api/db/seeds/data/team-certification/shared/common-organisation.js
  api/db/seeds/data/team-certification/shared/constants.js
  api/db/seeds/data/team-certification/shared/setup-configuration.js
  api/db/seeds/data/team-certification/tools/add-session.js
  api/db/seeds/data/team-certification/tools/algorithm-configuration/create-competence-scoring-configuration.js
  api/db/seeds/data/team-certification/tools/algorithm-configuration/create-flash-configuration.js
  api/db/seeds/data/team-certification/tools/algorithm-configuration/create-issue-report-categories.js
  api/db/seeds/data/team-certification/tools/algorithm-configuration/create-scoring-configuration.js
  api/db/seeds/data/team-certification/tools/publish-session-with-validated-certification.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12591 [TECH] Mettre à jour le message Slack pour indiquer seulement que la mise en recette est lancée
  .github/workflows/release.yml
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app

#12605 [TECH] Corriger le message slack
  .github/workflows/release.yml
Labels: :rocket: Ready to Merge, no-review-app

#12600 [TECH] Ajout d'un log en cas de différence entre le sub récupéré et le précédent (externalIdentifier) (PIX-18360)
  api/src/identity-access-management/domain/usecases/find-user-for-oidc-reconciliation.usecase.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces

#12603 [TECH] :truck: Déplace `stage-collection-repository` vers `src/prescription/`
  api/src/prescription/campaign-participation/domain/usecases/index.js
  api/src/prescription/campaign/domain/usecases/index.js
  api/src/prescription/campaign/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
  api/src/prescription/campaign/infrastructure/repositories/stage-collection-repository.js
  api/src/shared/infrastructure/repositories/stage-collection-repository.js
  api/tests/prescription/campaign/integration/infrastructure/repositories/stage-collection-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription, Bounded-context-migration

#12612 [BUGFIX] Afficher les bonnes urls dans la documentation OpenAPI (PIX-18396)
  api/src/shared/swaggers.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12610 [BUGFIX] Transférer les réponses LLM en ArrayBuffer pour Safari (PIX-18391)
  mon-pix/app/services/embed-api-proxy.js
  mon-pix/tests/unit/services/embed-api-proxy-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-contenu

#12579 [TECH] :truck: Déplace le `ComplementaryCertificationCourseResultRepository` vers `src/certification/`
  api/src/certification/session-management/infrastructure/repositories/complementary-certification-course-result-repository.js
  api/src/shared/domain/events/index.js
  api/tests/certification/evaluation/integration/domain/services/scoring/score-complementary-certification-v2_test.js
  api/tests/certification/evaluation/integration/domain/services/scoring/score-double-certification-v3_test.js
  api/tests/certification/session-management/integration/infrastructure/repositories/complementary-certification-course-result-repository_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, Bounded-context-migration

#12607 [TECH] :broom: Nettoyage du fichier index des usescases de `lib/`
  api/lib/domain/usecases/index.js
  api/lib/routes.js
  api/src/shared/routes.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, Bounded-context-migration

#12568 [TECH] Montée de version EmberJS pour PixAdmin
  admin/app/components/campaigns/update.gjs
  admin/app/components/organizations/information-section-edit.gjs
  admin/ember-cli-build.js
  admin/package-lock.json
  admin/package.json
  admin/tests/unit/components/target-profiles/organizations-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12621 [BUGFIX] Réparer l'affichage du nombre de tentatives de connexions restantes (PIX-18405)
  api/src/identity-access-management/domain/errors.js
  api/tests/identity-access-management/unit/application/http-error-mapper-configuration_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12627 [TECH] Bump audit-logger dependencies
  audit-logger/package-lock.json
  audit-logger/package.json
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#12619 [FEATURE] Repenser l'affichage des niveaux sur la page d'analyse de Pix Orga (PIX-18337)
  api/src/prescription/campaign/infrastructure/serializers/jsonapi/campaign-result-levels-per-tubes-and-competences-serializer.js
  api/src/prescription/organization-learner/application/organization-learners-route.js
  api/src/prescription/organization-learner/infrastructure/serializers/jsonapi/analysis-by-tubes-serializer.js
  api/tests/prescription/campaign/unit/application/api/campaigns-api_test.js
  api/tests/prescription/campaign/unit/infrastructure/serializers/jsonapi/campaign-result-levels-per-tubes-and-competences-serializer_test.js
  api/tests/prescription/organization-learner/acceptance/application/organization-learner-route_test.js
  api/tests/prescription/organization-learner/unit/infrastructure/serializers/jsonapi/analysis-by-tubes-serializer_test.js
  api/tests/tooling/domain-builder/factory/prescription/campaign/build-campaign-result-levels-per-tubes-and-competences.js
  api/tests/unit/domain/read-models/CampaignReport_test.js
  orga/app/components/statistics/cover-rate-gauge.gjs
  orga/app/components/statistics/tag-level.gjs
  orga/app/helpers/levels-info.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12626 [FEATURE] ajouter une route PATCH users/{id} pour enrichir un utilisateur anonyme avec des données d'authentification (Pix-18022)
  api/db/database-builder/factory/build-user.js
  api/src/identity-access-management/application/user/user.controller.js
  api/src/identity-access-management/application/user/user.route.js
  api/src/identity-access-management/domain/models/User.js
  api/src/identity-access-management/domain/usecases/upgrade-to-real-user.usecase.js
  api/src/identity-access-management/infrastructure/repositories/user.repository.js
  api/tests/identity-access-management/acceptance/application/user/user.route.test.js
  api/tests/identity-access-management/integration/domain/usecases/upgrade-to-real-user.usecase.test.js
  api/tests/identity-access-management/unit/application/user/user.controller.test.js
  api/tests/identity-access-management/unit/domain/models/User.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12638 [DOC] Corriger l'exemple de titre de PR
  CONTRIBUTING.md
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12640 [FEATURE] Lister par défaut les feature-toggles.
  api/package.json
  api/src/shared/infrastructure/feature-toggles/feature-toggles-script.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, cross-team

#12545 [FEATURE] Modifications suite panels et retours prompt-intermediaire
  api/src/devcomp/infrastructure/datasources/learning-content/modules/prompt-intermediaire.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12596 [FEATURE] WIP Créa module débbutant IA, vous avez dit IA ?
  api/src/devcomp/infrastructure/datasources/learning-content/modules/ia-dit-ia.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12489 [FEATURE] module IA fonc INT
  api/src/devcomp/infrastructure/datasources/learning-content/modules/tmp-ia-int-mgo.json
Labels: contribution-modulix

#12624 [FEATURE] Supprimer l'appel au service metrics lorsqu'une flashcard a été répondu (PIX-18366)
  mon-pix/app/components/module/component/element.gjs
  mon-pix/app/components/module/grain/grain.gjs
  mon-pix/app/components/module/passage.gjs
  mon-pix/tests/integration/components/module/passage_test.gjs
Labels: :rocket: Ready to Merge, team-devcomp

#12662 [FEATURE] Ajouter un feature flag pour l'envoi de résultats automatique (PIX-18452).
  api/config/feature-toggles-config.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12655 [TECH] Création de la table `calibrations` dans le datamart. (PIX-18447).
  api/datamart/migrations/20250625144056_create-calibrations-table-in-datamart.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-certif, team-captains

#12646 [TECH] Ne plus remonter les anciens feature toggles dans le front
  api/src/shared/application/feature-toggles/feature-toggle-controller.js
  api/tests/shared/acceptance/application/feature-toggles/feature-toggle-controller_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team, feature-toggle

#12674 [FEATURE] Supprimer l'envoi automatique des résultats vers France Travail (PIX-18459).
  api/db/migrations/20250627075112_allow-null-pole-emploi-sending.js
  api/scripts/prod/insert-missing-pole-emploi-sending-from-date.js
  api/src/prescription/campaign-participation/domain/models/PoleEmploiSending.js
  api/src/prescription/campaign-participation/domain/usecases/index.js
  api/src/prescription/campaign-participation/domain/usecases/send-completed-participation-results-to-pole-emploi.js
  api/src/prescription/campaign-participation/domain/usecases/send-shared-participation-results-to-pole-emploi.js
  api/src/prescription/campaign-participation/domain/usecases/send-started-participation-results-to-pole-emploi.js
  api/src/prescription/campaign-participation/infrastructure/externals/pole-emploi/disabled-pole-emploi-notifier.js
  api/src/prescription/campaign-participation/infrastructure/externals/pole-emploi/pole-emploi-notifier.js
  api/tests/integration/scripts/prod/insert-missing-pole-emploi-sending-from-date_test.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/send-completed-participation-results-to-pole-emploi_test.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/prescription/campaign-participation/integration/domain/usecases/send-started-participation-results-to-pole-emploi_test.js
  api/tests/prescription/campaign-participation/unit/domain/models/PoleEmploiSending_test.js
  api/tests/prescription/campaign-participation/unit/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
  api/tests/prescription/campaign-participation/unit/infrastructure/externals/pole-emploi/disabled-pole-emploi-notifier_test.js
  api/tests/prescription/campaign-participation/unit/infrastructure/externals/pole-emploi/pole-emploi-notifier_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12668 [FEATURE] Partager automatiquement les résultats de campagne (PIX-18454)
  mon-pix/app/models/feature-toggle.js
  mon-pix/app/routes/campaigns/assessment/results.js
  mon-pix/tests/acceptance/campaigns/campaign-results-test.js
  mon-pix/tests/unit/routes/campaigns/assessment/results-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-prescription

#12613 [TECH] Separer le rescoring de certification pour simplifier le bugfix a venir (PIX-18353).
  api/db/seeds/data/team-certification/tools/publish-session-with-validated-certification.js
  api/src/certification/evaluation/application/api/rescore-certification-api.js
  api/src/certification/evaluation/application/certification-admin-controller.js
  api/src/certification/evaluation/application/certification-rescoring-controller.js
  api/src/certification/evaluation/domain/usecases/rescore-v2-certification.js
  api/src/certification/evaluation/domain/usecases/rescore-v3-certification.js
  api/src/certification/session-management/application/finalize-controller.js
  api/src/certification/session-management/domain/events/AutoJuryDone.js
  api/src/certification/session-management/domain/usecases/cancel.js
  api/src/certification/session-management/domain/usecases/finalize-session.js
  api/src/certification/session-management/domain/usecases/process-auto-jury.js
  api/src/certification/session-management/domain/usecases/register-publishable-session.js
  api/src/certification/session-management/domain/usecases/reject-certification-course.js
  api/src/certification/session-management/domain/usecases/uncancel.js
  api/src/certification/session-management/domain/usecases/unreject-certification-course.js
  api/src/certification/session-management/infrastructure/repositories/certification-rescoring-repository.js
  api/src/certification/shared/domain/models/CertificationCourse.js
  api/src/certification/shared/infrastructure/repositories/certification-course-repository.js
  api/tests/certification/evaluation/acceptance/application/certification-rescoring-route_test.js
  api/tests/certification/evaluation/unit/application/certification-admin-controller_test.js
  api/tests/certification/evaluation/unit/domain/usecases/rescore-v2-certification_test.js
  api/tests/certification/evaluation/unit/domain/usecases/rescore-v3-certification_test.js
  api/tests/certification/session-management/integration/infrastructure/repositories/certification-rescoring-repository_test.js
  api/tests/certification/session-management/unit/application/finalize-controller_test.js
  api/tests/certification/session-management/unit/domain/usecases/cancel_test.js
  api/tests/certification/session-management/unit/domain/usecases/process-auto-jury_test.js
  api/tests/certification/session-management/unit/domain/usecases/register-publishable-session_test.js
  api/tests/certification/session-management/unit/domain/usecases/reject-certification-course_test.js
  api/tests/certification/session-management/unit/domain/usecases/uncancel_test.js
  api/tests/certification/session-management/unit/domain/usecases/unreject-certification-course_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-certif

#12686 [FEATURE] Rendre les claims additionels optionels (PIX-18457)
  api/src/identity-access-management/domain/models/ClaimManager.js
  api/src/identity-access-management/domain/services/oidc-authentication-service.js
  api/tests/identity-access-management/unit/domain/models/ClaimManager.test.js
  api/tests/identity-access-management/unit/domain/services/oidc-authentication-service.test.js
  mon-pix/app/components/authentication/login-or-register-oidc.gjs
  mon-pix/app/styles/components/authentication/_login-or-register-oidc.scss
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12693 [FEATURE] Permettre à un utilisateur anonyme d'être redirigé vers son dashboard après inscription (PIX-18445)
  mon-pix/app/components/authentication/signup-form/index.gjs
  mon-pix/app/models/user.js
  mon-pix/tests/acceptance/authentication/signup-test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces

#12500 [FEATURE]WIP module mon premier prompt V2
  api/src/devcomp/infrastructure/datasources/learning-content/modules/ia-premier-prompt.json
Labels: :rocket: Ready to Merge, contribution-modulix

#12695 [TECH] Retirer les configs poleEmploi du fichier ENV (PIX-18503).
  api/sample.env
  api/src/shared/config.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, team-acces, team-prescription

#12697 [FEATURE] Ajouter un minimum de CSS aux tableaux HTML insérés dans les WYSIWYG pour les rendre lisible (PIX-18502)
  api/src/devcomp/infrastructure/datasources/learning-content/modules/bac-a-sable.json
  api/src/devcomp/infrastructure/datasources/learning-content/modules/tmp-ia-int-mgo.json
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/module-validation_test.js
  api/tests/devcomp/unit/infrastructure/datasources/learning-content/validation/utils.js
  high-level-tests/e2e/cypress/integration/pix-app/modulix-a11y.feature
  mon-pix/app/components/module/element/_text.scss
  mon-pix/app/styles/app.scss
Labels: :rocket: Ready to Merge, team-devcomp

#12703 [BUGFIX] Corriger le numéro de version dans le workflow de release
  .github/workflows/release.yml
Labels: Tech Review OK, :rocket: Ready to Merge, no-review-app

#12701 [TECH] Permettre de spécifier quelle release récupérer côté PixApi lorsqu'un ID de release est renseigné dans une variable d'env
  api/db/seeds/data/common/learningcontent-builder.js
  api/sample.env
  api/src/learning-content/domain/usecases/refresh-learning-content-cache.js
  api/src/shared/config.js
  api/src/shared/infrastructure/lcms-client.js
  api/tests/learning-content/unit/domain/usecases/refresh-learning-content-cache_test.js
  api/tests/shared/integration/infrastructure/lcms-client_test.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, techdays-25-next

#12690 [FEATURE] Migration BDD ajouter une colonne "code" et une colonne "organizationId" à la table "quests" (PIX-18466)
  api/db/migrations/20250627084010_add-code-column-to-quests.js
Labels: Tech Review OK, :rocket: Ready to Merge, Func Review OK, :dango: Combinix
